### ISSUE TITLE
Question - Return macOS Version

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1000]
Sorry for all the questions!

I'm currently using the following AppleScript to return the current macOS version:

```
function macOSVersion()
	ok,appleScriptmacOSVersion = hs.osascript.applescript("return system version of (system info)")
	return appleScriptmacOSVersion
end
```

Is there anyway to do this natively within Lua? I've tried **os.version**, but it doesn't seem to work?

**Comment by asmagill** [comment]
Check out `hs.host.operatingSystemVersion()`.  It returns a table with the `major`, `minor`, and `patch` keys defining the OS version.

**Comment by latenitefilms** [comment]
Perfect, thank you! Sorry, I didn't notice the **hs.host** section in the Docs.
