### ISSUE TITLE
Improve hs.application bundle handling

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1001]
Sorry - next question! I'm using the below code to get the version of Final Cut Pro (regardless of whether it's open or not). Is there anyway to do this in natively in Lua?

```
function finalCutProVersion()
    if isFinalCutProInstalled() then
        ok,appleScriptFinalCutProVersion = hs.osascript.applescript('return version of application "Final Cut Pro"')    
        return appleScriptFinalCutProVersion
    else
        return "Not Installed"
    end 
end
```

**Comment by cmsj** [comment]
I don't think we can do that right now, but there are a few things we could add here that would help:

- easier conversion between app paths and bundle IDs
- fetching the InfoDictionary for an app bundle (which should contain the version information)

**Comment by cmsj** [comment]
(it might even make sense to deprecate the bundle stuff we have in `hs.application` and move it to an `hs.bundle` or similar)

**Comment by cmsj** [comment]
So we have hs.application.pathForBundleID() and now hs.application.infoForBundleID(), the latter of which will let you get the version of an application, if you know its Bundle ID. I think that should be sufficient for your needs, but I can probably figure out how to add a version that works by path if you really need it :)
