### ISSUE TITLE
hs.styledtext.ansi or hs.task is performing character substitution, I think

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1002]
I have a fake geeklet that displays the output of a script (called by hs.task) in an hs.styledtext.ansi object.

The script today happened to return text with the Greek letter beta in it.  But HS displayed the character as an ordinary, lowercase 'b'.

Anybody know what's going on?  The character is (according to Vim 0x03B2).  If I redirect the script output to a file "foo", and then use the `file` command to see what kind of file it is, it says "UTF-8 Unicode text".

If I change the geeklet so that instead of directly reading the stdout of a script, it runs `cat` on that same file "foo", then the beta is correctly displayed.

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)

(FWIW, hs.task seems to be pretty careful about encoding the stdout/stderr of tasks with UTF8)

**Comment by chdiza** [comment]
I had forgot about this issue.  I tried just now to reproduce it and failed.  Must've been silently fixed at some point.
