### ISSUE TITLE
Add triangle primitive to hs.drawing

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1005]
Sorry - this seems like a silly question, and maybe I'm just bad at maths, but I'm just wondering how you draw a triangle on the screen?

**Comment by cmsj** [comment]
At the moment you pretty much can't, the primitives are line/rect/arc/circle, but no triangle. I think @asmagill has some hs.drawing changes in the pipeline - maybe that will help?

**Comment by latenitefilms** [comment]
No worries! I think I can probably achieve what I need with three lines then, as they only need to be small triangles. Thanks @cmsj !
