### ISSUE TITLE
Cannot map 'Q' in Dvorak

### ISSUE THREAD

**Issue by vbauerster** [Hammerspoon/hammerspoon#1010]
I use [Dvorak](https://github.com/vbauerster/DeepDvorak) keyboard layout.
HS gives following error, when trying to bind <kbd>Q</kbd> key.
While in Qwerty, there is no such error.

``` lua
hyper = { "alt" }
-- Lock System
hs.hotkey.bind(hyper, 'Q', 'Lock system', function() hs.caffeinate.lockScreen() end)
```

```
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:342: Invalid key: Q - this may mean that the key requested does not exist in your keymap (particularly if you switch keyboard layouts frequently)
stack traceback:
    [C]: in function 'error'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:190: in function 'hs.hotkey.internal.new'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:342: in function 'hs.hotkey.internal.bind'
    /Users/vbauer/.hammerspoon/init.lua:13: in main chunk
    [C]: in function 'xpcall'
    ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
    (...tail calls...)
```

**Comment by latenitefilms** [comment]
Maybe try:

```
hyper = { "alt" }
-- Lock System
hs.hotkey.bind(hyper, 12, 'Lock system', function() hs.caffeinate.lockScreen() end)
```

**Comment by vbauerster** [comment]
@latenitefilms Yep this helped!
But, this locking functionality is useless for me, because it doesn't preserve original layout.
I mean the lock screen defaults to Qwerty layout, and theres is no way to change it.

**Comment by latenitefilms** [comment]
I'm no expert, but maybe [hs.keycodes.currentLayout()](http://www.hammerspoon.org/docs/hs.keycodes.html#currentLayout) could be of help?

**Comment by asmagill** [comment]
I'm not sure why assigning the key when the Dvorak layout is in effect fails... `Q` is a valid key in both -- it's in a different location on the keyboard, but it's still valid...  what does `hs.keycodes.map["q"]` return when Dvorak is enabled?  It's 7 on my machine, which puts it as the second display character in the second to bottom keyboard row.

As to the other question:

Are you saying that the when the lock screen is displayed, the layout automatically changes to Qwerty and that's what you have to use to type your password to log back in?

You might be able to use `hs.caffeinate.watcher` to detect `screensDidLock` and/or `screensDidUnlock` and when detected, use `hs.keycodes.setLayout` to set the layout you want... not sure if it will change the layout for the lock screen or not -- that's actually handled by a system process that the user isn't the owner for, but give it a shot -- it could at least be used to change the layout back when you return.

**Comment by vbauerster** [comment]
I'm using [Programmer Dvorak](https://github.com/vbauerster/DeepDvorak) modification. In my case `hs.keycodes.map["q"]` gives `nil`. However with built-in Mac's Dvorak it indeed gives 7.

**Comment by vbauerster** [comment]
@asmagill 
> Are you saying that the when the lock screen is displayed, the layout automatically changes to Qwerty and that's what you have to use to type your password to log back in?

Absolutely correct

**Comment by asmagill** [comment]
Was looking at the Workman layout so I can install it and see about replicating/addressing your issue and I noticed this line in the README.md file of the Mac sub-directory:

> Copying the bundle to /Library/Keyboard Layouts/ requires administrator rights to the computer, but will allow the layout system-wide, including the OS X login screen. To enable input options on the login window, check the option in System Preferences / Users & Groups / Login Options / Show Input menu in login window.

So my question at least wrt to the lock screen portion is have you put the layout in the system location and enabled this option?  You may need to reboot as well for it to fully take effect and be available/active when the `loginwindow` process is frontmost (i.e. during login and when the lock screen is presented)

I'll be installing these layouts myself later today to try and track down why `q` isn't working since it is defined in both layouts.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
