### ISSUE TITLE
hs.timer.doAt and invalid times

### ISSUE THREAD

**Issue by brandonpittman** [Hammerspoon/hammerspoon#1013]
I tried all the example from the API docs for timer.doAt, and every time the console pops up with a crash message claiming the times are invalid. If an interval is given, then the error states that it's an "invalid time string".

**Comment by deverman** [comment]
Hello, I am having the same problem. Anyone have some suggestion on how to fix this?

my call is: 

hs.timer.doAt("20:00:00",volume.mute())


The error is:

	[C]: in function 'error'
	...poon.app/Contents/Resources/extensions/hs/timer/init.lua:35: in upvalue 'timeStringToSeconds'
	...poon.app/Contents/Resources/extensions/hs/timer/init.lua:253: in function 'hs.timer.doAt'
	/Users/example/.hammerspoon/init.lua:163: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by junkblocker** [comment]
@deverman try

```lua
hs.timer.doAt("20:00", function() volume.mute() end)
```

The docs say the time format is `HH:MM` (not `HH:MM:SS`) and you need a function, not the result of a statement as a callback.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
