### ISSUE TITLE
pl.strict breaks help

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#102]
```
> help()
...rspoon.app/Contents/Resources/extensions/hs/doc/init.lua:99: variable 'debug.docs.module' is not declared
```

(this is via `hs`, same happens in REPL). In the code I see that `debug.docs.module` is some kind of fallback, so I suppose there are two issues here:
* somehow my help() wants to fall back from the normal behaviour
* the fall back makes no sense

**Comment by cmsj** [comment]
I don't think we have the debug.docs.module variable anymore, so I don't think this issue needs to stay open. It'd be interesting to know what pl.strict thinks of Hammerspoon these days though.
