### ISSUE TITLE
Question - Building complicated interfaces?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1020]
I want to build a fairly complex interface using Hammerspoon - like the attached image, for assigning shortcut keys to things.

Is this remotely possible? Any pointers on where to start?

<img width="512" alt="screen shot 2016-10-04 at 9 13 15 am" src="https://cloud.githubusercontent.com/assets/22286696/19056064/da67d518-8a12-11e6-9116-af4476257d52.png">

**Comment by asmagill** [comment]
ATM, probably not... drawing is limited to the basic objects provided by `hs.drawing` and using metamethod tricks with tables of drawings to treat multiple objects like a single Hammerspoon entity; and getting user input is limited to a combination of using `hs.chooser`, and `hs.webview` with javascript.

Of course you can always roll your own module in Objective-C (and maybe Swift, but there were some issues with proper integration -- search for Swift in the closed issues here for more info) , but I don't think that's what you have in mind.

I have been working on `hs._asm.canvas`, which extends the drawing possibilities, and more recently `hs._asm.enclosure` which allows mixing canvas objects, webview objects, and potentially any NSView type object OS X provides (this means movie playback, text entry, buttons, etc.), but it's pretty early stages at present.  Long term I hope to replace `hs.drawing` and `hs.webview` (and `hs._asm.canvas`) with `hs._asm.enclosure` and its submodules (there are currently wrappers for both drawing and webview that I've been using for a while now without problem), but the documentation is pretty lacking and I have a lot more to do on the other view types front.

You can check them out at https://github.com/asmagill/hammerspoon_asm/tree/master/enclosure and https://github.com/asmagill/hammerspoon_asm/tree/master/canvas, but it will be a while yet before they are ready for general inclusion.  My ultimate goal for it would be to allow exactly what you're describing, but I don't think it's there yet.

**Comment by latenitefilms** [comment]
Thanks @asmagill for the detailed reply!

I wonder if I can solve this with AppleScript? Will have to have a play!

**Comment by cmsj** [comment]
I'm gonna close this out for now, I don't think there's any direct actions to take. We want to get to complex UI building eventually, but it will likely take a while :)
