### ISSUE TITLE
Question - Translating Apple's Function-Key Unicodes to hs.keycodes?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1021]
Is there an easy way to translate [Apple's Function-Key Unicodes](https://developer.apple.com/reference/appkit/1535851-function_key_unicodes?language=objc), such as **NSF1FunctionKey** to something Hammerspoon can understand (i.e. "F1")?

I'm currently just using a whole heap of if...then's - but I'm sure there's a smarter way!

Thanks in advance!

**Comment by latenitefilms** [comment]
On a similar note, I'm also trying to reverse engineer an Apple-created plist which contains shortcut keys for Final Cut Pro. By testing one by one, I've determined that the below modifierMask values match the listed modifier keys - but I'm just wondering how Apple is calculating the mask value? What's that value actually mean? Any ideas?

Thanks in advance!

```
-- modifierMask = 131072 	(shift)
-- modifierMask = 262144 	(control)
-- modifierMask = 524288 	(option)
-- modifierMask = 1048576	(command)			
-- modifierMask = 786432	(control + option)
-- modifierMask = 393216	(control + shift)
-- modifierMask = 1310720	(control + command)			
-- modifierMask = 1572864	(option + command)
-- modifierMask = 655360	(shift + option)
-- modifierMask = 1179648	(command + shift)
-- modifierMask = 917504	(control + shift + option)
-- modifierMask = 1703936	(option + command + shift)
-- modifierMask = 1835008 	(control + option + command)
```

**Comment by asmagill** [comment]
Most likely the modifier masks match up to the NSEvent modifier flags.  The [current Apple API docs for them](https://developer.apple.com/reference/appkit/nsevent/modifier_flags) lists them all as deprecated but doesn't list a replacement... this is incorrect and they do have replacements if you look at /System/Library/Frameworks/AppKit.framework/Versions/C/Headers/NSEvent.h (assuming you have XCode installed), but in any case, I prefer the layout of the previous API docs which lists them like this:

~~~

Modifier Flags
The following constants (except for NSDeviceIndependentModifierFlagsMask) represent device-independent bits found in event modifier flags:

Declaration
OBJECTIVE-C
enum {
   NSAlphaShiftKeyMask = 1 << 16,
   NSShiftKeyMask      = 1 << 17,
   NSControlKeyMask    = 1 << 18,
   NSAlternateKeyMask  = 1 << 19,
   NSCommandKeyMask    = 1 << 20,
   NSNumericPadKeyMask = 1 << 21,
   NSHelpKeyMask       = 1 << 22,
   NSFunctionKeyMask   = 1 << 23,
   NSDeviceIndependentModifierFlagsMask = 0xffff0000U 
};
~~~

**Comment by asmagill** [comment]
As to the Apple Unicode keys, no we currently do not have a mapping setup.

We do have a couple of similar lookup tables, but not one matching the specific numeric values listed at the link you provide... it could be added to `hs.utf8` if you want to populate it with appropriate characters... take a look at `hs.utf8.registeredKeys` which is a table mapping some "human readable" key names to a unicode character that is commonly used for each symbol and `hs.application.menuGlyphs` which is a table mapping key glyph numbers returned by `hs.application:getMenuItems` and `hs._asm.axuielement` for the unicode character of the symbol.

**Comment by latenitefilms** [comment]
Legend, thanks so much @asmagill !

I'll try work it out myself, but just in case you happen to be online... any chance you could give me an example of how I can translate the **NSEvent.h** code to something I can actually use in Hammerspoon?

**Comment by latenitefilms** [comment]
Sorry to be a pain, but seeing as you're online @asmagill - I'm still struggling with this too.

Any suggestions on how I can create a Lua function that inputs a modifierMask (i.e. '131072') and returns a result that tells me what that modifierMask means (i.e. 'shift')?

**Comment by asmagill** [comment]
Something like might work:

~~~lua
maskToTable = function(value)
    local modifiers = {
        AlphaShift = 1 << 16,
        Shift      = 1 << 17,
        Control    = 1 << 18,
        Alternate  = 1 << 19,
        Command    = 1 << 20,
        NumericPad = 1 << 21,
        Help       = 1 << 22,
        Function   = 1 << 23,
    }

    local answer = {}

    for k, v in pairs(modifiers) do
        if (value & v) == v then
            table.insert(answer, k)
        end
    end

    return answer
end
~~~

**Comment by latenitefilms** [comment]
You're a genius! Thank you! That seems to work great!
