### ISSUE TITLE
Question - how to perform a double left click?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1027]
Does anyone have any ideas on how I can force Lua to double click on something?

I've tried:

```
hs.eventtap.leftClick(selectedEffectPosition)
hs.eventtap.leftClick(selectedEffectPosition)
```

...but it didn't work. I've also tried putting in a delay, but again, no help:

```
hs.eventtap.leftClick(selectedEffectPosition)
hs.timer.usleep(((hs.eventtap.doubleClickInterval() - 0.1)*1000000))
hs.eventtap.leftClick(selectedEffectPosition)
```

I've also tried:

```
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, selectedEffectPosition):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, selectedEffectPosition):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, selectedEffectPosition):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, selectedEffectPosition):post()
```

Any ideas?

**Comment by latenitefilms** [comment]
Annoyingly, I'm still stuck on this. Basically I have a UI element (AXImage) that doesn't have any Actions, so the only way I can get it to do anything is double click on it - but it's not working.

Any ideas @asmagill or @cmsj ?

**Comment by asmagill** [comment]
I'm not that familiar with generating events with eventtap (detecting and capturing them, yes, generating them... not so much) because the timing of things and tracking what was the frontmost application or focused element seemed, to me at any rate, to make the code brittle and too prone to being inconsistent... just my experience, though.

WRT to the image not having any actions attached to it, if it's a user interface element that you can click on, then *something* around it should -- unless the developers of the app are mean :-)... maybe its parent or a child element?  I'd start with looking at the output of something like `hs.inspect(object:parent():buildTree(2))` and see if it's contained or if it contains a "cell" of some sort with the same or similar dimensions (the 2 in the `buildTree` method limits the search depth to 2 levels away from the starting point... you can experiment and see what works best for you).  I should probably add an `actions` table to the buildTree method as well, since it's an examination tool and actions are often what you're wanting to find... I'll see about adding that later when I get a chance.

**Comment by latenitefilms** [comment]
Thanks @asmagill !

Unfortunately, I think the developers (i.e. Apple) are mean in this case.

Here's the report from UI Browser:

```
PATH:
AXApplication "Final Cut Pro"
	AXWindow "Final Cut Pro" (window 1)
		AXSplitGroup (splitter group 1)
			AXGroup (group 1)
				AXGroup (group 1)
					AXSplitGroup (splitter group 1)
						AXScrollArea (scroll area 1)
							AXGrid (UI element 1)
								AXImage "Magic Bullet Looks" (image 1)

ACTIONS:
AXShowMenu

ATTRIBUTES (long values are truncated to 60 characters):
AXChildren
	type: array
	value: (array of 0 items)
	modifiable: no
AXFocused
	type: Boolean
	value: false
	modifiable: yes
AXFrame
	type: rect
	value: {{1543.5, 674}, {109, 89}} x, y, width, height
	modifiable: no
AXHelp
	type: (null)
	value: (null)
	modifiable: no
AXParent
	type: UIElement
	value: AXGrid
	modifiable: no
AXPosition
	type: point
	value: {1543.5, 674} x, y
	modifiable: no
AXRole
	type: string
	value: AXImage
	modifiable: no
AXRoleDescription
	type: string
	value: "image"
	modifiable: no
AXSize
	type: size
	value: {109, 89} width, height
	modifiable: no
AXTitle
	type: string
	value: "Magic Bullet Looks"
	modifiable: no
AXTopLevelUIElement
	type: UIElement
	value: AXWindow "Final Cut Pro"
	modifiable: no
AXWindow
	type: UIElement
	value: AXWindow "Final Cut Pro"
	modifiable: no

NOTIFICATIONS:
AXAnnouncementRequested
AXCreated
AXElementBusyChanged
AXFocusedUIElementChanged
AXHelpTagCreated
AXLayoutChanged
AXMoved
AXResized
AXRowCollapsed
AXRowCountChanged
AXRowExpanded
AXSelectedCellsChanged
AXSelectedChildrenChanged
AXSelectedChildrenMoved
AXSelectedColumnsChanged
AXSelectedRowsChanged
AXSelectedTextChanged
AXTitleChanged
AXUIElementDestroyed
AXUnitsChanged
AXValueChanged
```

It has an action for right-clicking (i.e. 'AXShowMenu'), but no action that does the same thing as double clicking. It's parent elements are also no help.

Would would be REALLY handy in a future release of your amazing code is building in some kind of "force press" (i.e. if "AXPress" doesn't exist, do a press programatically somehow). No idea if this is possible - maybe doing the "mouse workaround" is the only way?

**Comment by latenitefilms** [comment]
Sadly, I'm still struggling with this. Who would have thought double clicking something would be so tricky!

I've tried:

```
-- CLICK:
local mouseClickEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, selectedEffectPosition)
mouseClickEvent:post()
local mouseReleaseEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, selectedEffectPosition)
mouseReleaseEvent:post()

-- WAIT:
local sleepAmountInMicroSeconds = hs.eventtap.doubleClickInterval() * 1000000
hs.timer.usleep(sleepAmountInMicroSeconds)

-- CLICK:
local mouseClickEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, selectedEffectPosition)
mouseClickEvent:post()
local mouseReleaseEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, selectedEffectPosition)
mouseReleaseEvent:post()
```

...and I've also tried adjusting the **hs.timer.usleep** to bigger and smaller, but no matter what I do, it still doesn't seem to be double clicking the UI element it's over.

Any ideas?

**Comment by asmagill** [comment]
What is the effect of double clicking on the image when you do so by hand?  Does it select the item, or perform an action of some sort?  I'll see if I can find something similar that I already have installed -- I checked Safari, but it's AXImage objects do have a "AXPress" action, so that's out -- but knowing what you're expecting it to do would help in finding something as similar as possible.

**Comment by latenitefilms** [comment]
@asmagill - When I double click it by hand, it basically applies whatever item I've double clicked to the currently selected clip on the edit timeline. That's what's so annoying - I can double click it by hand, and it works - but no matter what I've tried, I can't seem to double click it programatically, regardless of whether I'm using AppleScript, Lua or even a [3rd party tool](http://www.hamsoftengineering.com/codeSharing/MouseTools/MouseTools.html). Apple must be doing something really funky behind the scenes - as it makes absolutely no sense that I can double click it, but MouseTools can't.

Attached is an image of what the AXImage looks like. It's the highlighted yellow item.

If you're really keen - you can actually [download](http://www.apple.com/au/final-cut-pro/trial/) a 30-day free trial of Final Cut Pro.

Thanks so much for all your help!

<img width="392" alt="screen shot 2016-10-06 at 5 07 13 pm" src="https://cloud.githubusercontent.com/assets/22286696/19142238/bea5485c-8be7-11e6-9755-2e719fb82118.png">

**Comment by asmagill** [comment]
Ok, the following seems to work to select a word in the Terminal application with a double-click:

~~~lua
 -- make sure application is focused so we don't run into an issue of the first click being eaten to bring the app forward
hs.application.launchOrFocus("Terminal")

local point = { x = 106.890625, y = 159.78125 }
local clickState = hs.eventtap.event.properties.mouseEventClickState
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], point):setProperty(clickState, 1):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], point):setProperty(clickState, 1):post()
hs.timer.usleep(1000)
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], point):setProperty(clickState, 2):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], point):setProperty(clickState, 2):post()
~~~

**Comment by asmagill** [comment]
If we can confirm this works across a broad spectrum of applications, I'll put an update in the `hs.eventtap.leftClick` and `rightClick` functions to take an optional `clickCount` parameter.

**Comment by latenitefilms** [comment]
GENIUS!!

Thank you so much @asmagill - this works perfectly!!

```
function doubleLeftClick(point)
	local clickState = hs.eventtap.event.properties.mouseEventClickState
	hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], point):setProperty(clickState, 1):post()
	hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], point):setProperty(clickState, 1):post()
	hs.timer.usleep(1000)
	hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], point):setProperty(clickState, 2):post()
	hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], point):setProperty(clickState, 2):post()
end
```
