### ISSUE TITLE
Question - repl-based exploration

### ISSUE THREAD

**Issue by grav** [Hammerspoon/hammerspoon#1028]
I am a Lua n00b. I've started toying with Hammerspoon by using `print` statements all over the place and looking at the console. But what I'd really like to do is to explore Lua and Hammerspoon using the repl.

However, but I cannot find out how to require the hs modules? I've installed a Lua using Homebrew, and I've also tried starting the `setup.lua` file located in the `Resources` folder in the application bundle without any luck.

Any pointers? Is it at all possible to use Hammerspoon from a repl?

**Comment by cmsj** [comment]
@grav so the Console is effectively a REPL, but we also have http://www.hammerspoon.org/docs/hs.ipc.html which can install a command line IPC client that gives you what is also effectively a REPL.

**Comment by grav** [comment]
Oh, d'uh! Didn't notice that! :-) Thanks!
