### ISSUE TITLE
make help(hs.ipc) work

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#103]
As compared to `help('hs.ipc')`

**Comment by cmsj** [comment]
@asmagill I do like the `help.hs.foo` syntax we have, but I think it's non-obvious, where `help()` is something that people probably expect to work. At some point I will get around to either using @Habbie 's suggestion of autopopulating the magic variables, or just add it to all of the modules by hand.

**Comment by cmsj** [comment]
I'm going to close this out now- realistically I don't think we're ever going to get around to the metadata that would be necessary to make this work. It would be very intrusive and cumbersome.

**Comment by asmagill** [comment]
With command preprocessing with `hs._consoleInputPreparser` this has been possible for some time... see #921
