### ISSUE TITLE
How to get SPECIFIC Application?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1030]
One of the issues I've come across randomly is that I'll type something like:

`hs.application("Final Cut Pro")`

...expecting it to get see if the "Final Cut Pro" application is open, but it'll find some other random item - such as a browser window. For example:

```
> hs.application("Final Cut Pro")
hs.window: Final Cut Pro Radio (0x7ff7a2fb3458)	hs.application: Safari (0x7ff7a0d4e608)
```

Is there anyway to force **hs.application** to only look for exactly what you're after (as opposed to a 'hint')?

I've also noticed that **hs.appfinder.appFromWindowTitle("Final Cut Pro")** is inconsistent. For example, if Final Cut Pro's not running, I would EXPECT it to return **nil**, but instead it returns nothing, which seems a bit odd?

Any suggestions?

**Comment by asmagill** [comment]
See `hs.application.get` -- `hs.application(...)` is actually a shorthand for `hs.application.find`, and find tries to match as many possibilities as it can so you can choose.

As to appFinder returning nothing or nil, well... we're inconsistent, in my opinion, but when looking at things strictly from the Lua side, nil and "nothing" are essentially the same thing in the following sense:  If you assign a variable the return value of a function which returns nothing, then the variable will equal `nil`.

In fact, to test if a function parameter was provided or set as an explicit `nil`, you have to do something like the following (there is *no* way to distinguish nil from nothing by testing only the variable/parameter on the Lua side of things):

~~~lua
testFunc = function(...)
   local args = table.pack(...)
   if args.n == 0 then
      -- no parameter was passed in
   elseif args.n == 1 and type(args[1]) == "nil") then
      -- a single nil was passed in
...
~~~

In the C/Objective-C portion of the modules, nothing (i.e. no parameter) and nil are distinct, but not in pure Lua.

**Comment by latenitefilms** [comment]
No worries! Thanks @asmagill !

I solved it with the following code:

```
function isFinalCutProRunning()

	local result = nil

	if hs.application("Final Cut Pro") == nil then
		result = false
	else
		if hs.appfinder.appFromName("Final Cut Pro") == nil then
			result = false
		else
			if hs.application("Final Cut Pro"):isRunning() then
				result = true
			else
				result = false
			end
		end
	end

	return result

end
```
