### ISSUE TITLE
Switch to specific layout on command left key press only?

### ISSUE THREAD

**Issue by piskov** [Hammerspoon/hammerspoon#1039]
Since Karabiner is down in Siera a lot of us stuck with switching between keyboard layouts using ugly ctlr+space.

Is it possible in hammerspoon to do the following:
1. On left command key press switch to “en” keyboard layout
2. On right command key press switch to another, e. g. “ru” keyboard layout.

I’ve tried to do the following:

```
hs.hotkey.bind(nil, 58, function()
    hs.keycodes.setLayout("Russian - Ilya Birman Typography")
end)


hs.hotkey.bind(nil, 61, function()
    hs.keycodes.setLayout("English - Ilya Birman Typography")
end)
```

… but it’s not working. 58 and 61 are codes for left and right alts (since I don’t know the correct codes for left and right command). And the layout names are correct of what layouts are installed on my mac.

**Comment by asmagill** [comment]
You can't bind just a modifier as a hotkey, but you can use the eventtap module... something like this would probably work:

~~~lua
layoutWatcher = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function(e)
    local flags = e:getFlags()
    if flags.cmd and not (flags.alt or flags.shift or flags.ctrl or flags.fn) then
        local keyCode = e:getKeyCode()
        if keyCode == 0x37 then
            print("~~ left cmd key")
        elseif keyCode == 0x36 then
            print("~~ right cmd key")
        end
    end    
end):start()
~~~

**Comment by asmagill** [comment]
Thinking about it, though, you'll probably want to set up a timer and make sure that no key press or flag changes occur within a specific timeout to make sure that the cmd key is *just* the command key and not part of a key-sequence (like cmd-Q, etc.)

I do something like that in this file here which checks to see if a command key is pressed and held to display a cheatsheet like display: https://github.com/asmagill/hammerspoon-config/blob/master/utils/_keys/cheatsheet.lua#L253

**Comment by piskov** [comment]
Skipped timer alltogether by adding couple of variables. Changes language on command KeyUp event, but only if nothing happened after command KeyDown (e. g. another key press, mouse click, scroll, etc.)

No previous Lua or Hammerspoon experience whatsoever, so may contain bugs or be not very optimised.

```
local module = {}
module.showPopUp = false
module.leftCmdLayout = "English - Ilya Birman Typography"
module.rightCmdLayout = "Russian - Ilya Birman Typography"


module.eventwatcher = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function(e)

    local flags = e:getFlags()

    if flags.cmd
       and not (flags.alt or flags.shift or flags.ctrl or flags.fn)
       and not module.cmdShouldBeIgnored
    then
        module.cmdWasPressed = true
        return false;
    end

    if flags.cmd
       and (flags.alt or flags.shift or flags.ctrl or flags.fn)
    then
        module.cmdShouldBeIgnored = true
        return false;
    end

    if not flags.cmd
       and module.cmdWasPressed
    then
        if not module.cmdShouldBeIgnored then            
            local keyCode = e:getKeyCode()

            if keyCode == 0x37 then
                hs.keycodes.setLayout(module.leftCmdLayout)
		
		if module.showPopUp then
  		    hs.alert.show("English", 0.2)
		end

	    elseif keyCode == 0x36 then
		hs.keycodes.setLayout(module.rightCmdLayout)
		
		if module.showPopUp then
  		    hs.alert.show("Russian", 0.2)
		end
	    end
	end

	module.cmdWasPressed = false
	module.cmdShouldBeIgnored = false
    end

    return false;
end):start()


module.eventwatcher = hs.eventtap.new({"all", hs.eventtap.event.types.flagsChanged}, function(e)

    local flags = e:getFlags()

    if flags.cmd and module.cmdWasPressed then
	module.cmdShouldBeIgnored = true
    end

    if not flags.cmd
       and module.cmdShouldBeIgnored
    then
	module.cmdWasPressed = false
	module.cmdShouldBeIgnored = false
    end

    return false;
end):start()
```

**Comment by stepango** [comment]
https://gist.github.com/stepango/3b7dda91c8ab82ec88a14a3ef89a296a
