### ISSUE TITLE
Suggestion - Inconsistencies between eventtap & hotkey?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1040]
It seems a bit odd that you can feed "cmd", "command" or "⌘" into **hs.hotkey**, but only "cmd" into **hs.eventtap**? 

It also seems a bit strange that **hs.hotkey** will take a keycode number or string, but **hs.eventtap** will only take a string?

I feel like these sort of things should be consistent across the board?

**Comment by asmagill** [comment]
They were written at different times and some of the additions have been added by different people... While I agree that we should strive for consistency, it hasn't been a high priority for most of us as we spend most of the time we have available bug fixing and expanding capabilities.

However, (a) if you have the time and want to have a go at it, by all means, we welcome the additions, or (b) posting a notice like this so we can have something to refer back to.

@cmsj, My thought is that we should probably have a thread of "known inconsistencies" (or this can become one) so we can track them and address them as and when we can.

**Comment by cmsj** [comment]
@asmagill +1 an inconsistencies Issue to track these things. There are loads :)

**Comment by cmsj** [comment]
@latenitefilms are we talking about `hs.eventtap.event.newKeyEvent()` here? If so it should support the unicode versions of the modifier keys.

**Comment by latenitefilms** [comment]
Sorry @cmsj - I just realised I never replied to this. Apologies!

This is what I mean...

`hs.eventtap.keyStroke(modifiers, character)`
**modifiers** - A table containing the keyboard modifiers to apply ("fn", "ctrl", "alt", "cmd", "shift", "fn", or their Unicode equivalents)

**vs**

`hs.hotkey.bind(mods, key, message, pressedfn, releasedfn, repeatfn) -> hs.hotkey object`
**mods** - A table or a string containing (as elements, or as substrings with any separator) the keyboard modifiers required, which should be zero or more of the following:
"cmd", "command" or "⌘"
"ctrl", "control" or "⌃"
"alt", "option" or "⌥"
"shift" or "⇧"

I've solved this in my own code by using:

```
function convertModifiersKeysForEventTap(input)
	for i in pairs(input) do
		if input[i] == "control" 	then input[i] = "ctrl" end
		if input[i] == "option" 	then input[i] = "alt" end
		if input[i] == "command" 	then input[i] = "cmd" end
		if input[i] == "⌃" 			then input[i] = "ctrl" end
		if input[i] == "⌥" 			then input[i] = "alt" end
		if input[i] == "⌘" 			then input[i] = "cmd" end
		if input[i] == "⇧" 			then input[i] = "shift" end
	end
	return input
end
```

and

```
function keyCodeTranslator(input)
	local englishKeyCodes = {
		["'"] = 39,
		[","] = 43,
		["-"] = 27,
		["."] = 47,
		["/"] = 44,
		["0"] = 29,
		["1"] = 18,
		["2"] = 19,
		["3"] = 20,
		["4"] = 21,
		["5"] = 23,
		["6"] = 22,
		["7"] = 26,
		["8"] = 28,
		["9"] = 25,
		[";"] = 41,
		["="] = 24,
		["["] = 33,
		["\\"] = 42,
		["]"] = 30,
		["`"] = 50,
		["a"] = 0,
		["b"] = 11,
		["c"] = 8,
		["d"] = 2,
		["delete"] = 51,
		["down"] = 125,
		["e"] = 14,
		["end"] = 119,
		["escape"] = 53,
		["f"] = 3,
		["f1"] = 122,
		["f10"] = 109,
		["f11"] = 103,
		["f12"] = 111,
		["f13"] = 105,
		["f14"] = 107,
		["f15"] = 113,
		["f16"] = 106,
		["f17"] = 64,
		["f18"] = 79,
		["f19"] = 80,
		["f2"] = 120,
		["f20"] = 90,
		["f3"] = 99,
		["f4"] = 118,
		["f5"] = 96,
		["f6"] = 97,
		["f7"] = 98,
		["f8"] = 100,
		["f9"] = 101,
		["forwarddelete"] = 117,
		["g"] = 5,
		["h"] = 4,
		["help"] = 114,
		["home"] = 115,
		["i"] = 34,
		["j"] = 38,
		["k"] = 40,
		["l"] = 37,
		["left"] = 123,
		["m"] = 46,
		["n"] = 45,
		["o"] = 31,
		["p"] = 35,
		["pad*"] = 67,
		["pad+"] = 69,
		["pad-"] = 78,
		["pad."] = 65,
		["pad/"] = 75,
		["pad0"] = 82,
		["pad1"] = 83,
		["pad2"] = 84,
		["pad3"] = 85,
		["pad4"] = 86,
		["pad5"] = 87,
		["pad6"] = 88,
		["pad7"] = 89,
		["pad8"] = 91,
		["pad9"] = 92,
		["pad="] = 81,
		["padclear"] = 71,
		["padenter"] = 76,
		["pagedown"] = 121,
		["pageup"] = 116,
		["q"] = 12,
		["r"] = 15,
		["return"] = 36,
		["right"] = 124,
		["s"] = 1,
		["space"] = 49,
		["t"] = 17,
		["tab"] = 48,
		["u"] = 32,
		["up"] = 126,
		["v"] = 9,
		["w"] = 13,
		["x"] = 7,
		["y"] = 16,
		["z"] = 6,
		["§"] = 10
	}
	if englishKeyCodes[input] == nil then
		if keycodes.map[input] == nil then
			return ""
		else
			return keycodes.map[input]
		end
	else
		return englishKeyCodes[input]
	end
end
```

**Comment by latenitefilms** [comment]
You're an absolute legend @asmagill! Thank you so much!
