### ISSUE TITLE
Feature Request: Pattern matching / regex for hs.application:findMenuItem()

### ISSUE THREAD

**Issue by n8henrie** [Hammerspoon/hammerspoon#1041]
As briefly discussed on IRC:

Some menu items change depending on context, e.g. number of items selected. My current example: export in Photos.app.

With a single photo selected: `Export Unmodified Original For 1 Photo…`
With two: `Export Unmodified Original For 2 Photos…`

(note it is `…` not `...`)

If there were a way to implement some kind of regex or pattern matching in this method it would greatly simplify finding this menu item (rather than having to do something like `:getMenuItems()` and recursively search the table for the item in question.

For example: `:findMenuItem("Export Unmodified Original For (%d)+ Photos?…")` (this is likely wrong, I need to read up on Lua regex, but hopefully you get the idea).

**Comment by latenitefilms** [comment]
Agreed - this would be a welcome addition.

It could even be simpler, for example, you could just give it "Export Unmodified Original For", and it could return a table with any menu items that contain this string.
