### ISSUE TITLE
Improve hs.ipc.cliInstall() failure messaging

### ISSUE THREAD

**Issue by raguay** [Hammerspoon/hammerspoon#1046]
I installed the http-server node.js library and it promptly installed a script as /usr/local/bin/hs. This destroyed the hs command used by Hammerspoon for ipc communications. I removed the hs command and restarted Hammerspoon, but the console keeps coming up with:

cli installation problem: incomplete installation of 'hs' and 'hs.1'.

and it will not re-install the hs command. How can I force it to fix this?

**Comment by asmagill** [comment]
I should probably adjust the module to allow a forced install... at the time I was more concerned with not changing things for someone who has a non-standard setup and wanted to put things in specific places or have multiple versions around for testing, etc.

The simplest fix is to remove the remaining link and then restart hammerspoon again.  It looks like you're using the default path, so type the following in a Terminal shell window (one of these, in your case the first one, will likely generate an error -- that's ok, ignore it):

~~~sh
rm /usr/local/bin/hs
rm /usr/local/share/man/man1/hs.1
~~~

Now it should install on Hammerspoon's restart correctly (or you can force a reinstall without a restart by typing `hs.ipc.cliInstall()` into the Hammerspoon console)

**Comment by irliao** [comment]
@asmagill I tried your commands but still got the same error after restarting Hammerspoon. 
@raguay I ran into the exact same issue with http-server and was able to fix the cli problem by:

1. completely remove Hammerspoon.app using [AppCleaner](https://freemacsoft.net/appcleaner/)
2. remove /usr/local/bin/hs
3. reinstall latest Hammerspoon release and reenable Accessibility
4. run hs.ipc.cliInstall() in Hammerspoon console

Hope this helps!

**Comment by raguay** [comment]
Actually, once I removed the hs and hs.1 man file, it reinstalled it just
fine. I had deleted just the hs file, but not the man file. If either file
exists, then neither file is installed. I would figure the one that doesn't
exist would still get installed.

**Comment by cmsj** [comment]
I'm not sure we should do anything if only one of the files exists - it might be something we don't control, and then we'd be adding a man page for an httpd server, or whatever `/usr/local/bin/hs` is.

I'm also not convinced we should have a force option. This seems like the kind of corner case where the user is required to figure out what's going on.

The only thing I can think of here that we should do, is give a better error message about why the `cliInstall` failed.

**Comment by cmsj** [comment]
I'm not actually sure we need this issue - if cliInstall() throws an error, cliUninstall() can be used to correct the situation, per the docs. Please anyone re-open if you disagree.
