### ISSUE TITLE
Question - Keeping Mouse Held Down?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1052]
I'm trying to write a function that essentially holds the left mouse key down whilst a certain keyboard key is pressed, and releases the mouse when the keyboard key is released.

The problem I'm running into is that if I have the below code in a **function()**:

`hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], controlLocation):post()`

...once that **function()** reaches **end**, the mouse seems to be released, even though I haven't given it a **leftMouseUp** signal.

Any ideas how I can get around this? @asmagill ?

Thanks in advance!

**Comment by asmagill** [comment]
With Safari as my frontmost application, I did the following while my mouse pointer was hovering over the `Safari` menubar label:

~~~lua
controlLocation = hs.mouse.getAbsolutePosition()
g = hs.hotkey.bind({"shift", "alt"}, "g", function()
    hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], controlLocation):post()
end, function()
    hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], controlLocation):post()
end)
~~~

And as long as I let the menu actually display before releasing `g`, it seems to work as expected... shift-alt-g causes the "application menu" to open and releasing it causes it to close.

Then I tried this:

~~~lua
g = hs.hotkey.bind({"shift", "alt"}, "g", function()
    hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], hs.mouse.getAbsolutePosition()):post()
end, function()
    hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseUp"], hs.mouse.getAbsolutePosition()):post()
end)
~~~

Doesn't work reliably... when I move the mouse pointer to a window's title bar and press shift-alt-g, if I move the mouse *within the window itself*, the window will move when I release shift-alt-g... if I move to a place outside of the window, it does nothing on release... I suspect it has to do with when the coordinates are being calculated (`hs.mouse.getAbsolutePosition()`).

So... it does appear to work *sometimes* -- I'd need to know more about what you're trying to do and how far apart the mouseDown and mouseUp events are and what other events might be occurring in between them...

**Comment by latenitefilms** [comment]
Thanks @asmagill !

I'm trying to control a Color Board puck in Final Cut Pro (see attached photo).

<img width="406" alt="color-board" src="https://cloud.githubusercontent.com/assets/22286696/19629689/fdadad0a-99c5-11e6-9a1d-9e45879d1e1b.png">

The control is basically a text field, where if you click and the mouse down, when you move the mouse up, the value increases, and when you move the mouse down, the value decreases.

What I would like to do is write a function that does the following when a keyboard key is held down:

- Get the current position of the mouse (let's call this original position)
- Move mouse to position of text field
- Click and hold
- Now when the mouse moves up the value should move up, and when the mouse moves down, the playhead should move down
- When you release the keyboard key, the mouse will move back to the original position

Obviously this is a bit of a hack way of doing things, but unfortunately the only other way to control the "pucks" is with Final Cut Pro's built in keyboard shortcuts, and they're slow.

I've also played around with programatically changing the text field value via GUI Scripting, but although I can change the value of the text field - changing it doesn't actually do anything. I need some kind of way to make it "activate". Unfortunately the Text Field doesn't have any useful Actions. Attached is a screenshot of what UI Browser tells me.

<img width="1233" alt="color-board-gui" src="https://cloud.githubusercontent.com/assets/22286696/19629817/f2c0e076-99c8-11e6-9cac-d7d04c5d0bc8.png">

**Comment by NeighNeighNeigh** [comment]
Sorry to take you back so far in time, but wondering if you ever got this worked out? I've been setting up a point-of-sales keyboard to use with a variety of applications. It would be _really handy_ if I could remap a key so that while it is held, it performs a combination of a keypress _and_ a mouse press - only releasing them when the key is released.
