### ISSUE TITLE
Inspiration...

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1058]
I would LOVE it if you could build something like this using Hammerspoon:

http://www.videocopilot.net/blog/2016/10/new-workflow-plug-in-fx-console-is-now-available/

This is a great example of the kind of user interfaces it would be awesome if you could build use Lua.

**Comment by cmsj** [comment]
@latenitefilms have you seen hs.chooser? It's not quite as capable as the one shown in that video, but it's essentially the same kind of thing.

**Comment by cmsj** [comment]
(I'm going to go ahead and close this now, please feel free to re-open if you think there is more we need to do here)

**Comment by latenitefilms** [comment]
I didn't even think about **hs.chooser** - I've seen it in the API documents, but haven't played with it yet. Thanks @cmsj - I'll give it a bash!

**Comment by latenitefilms** [comment]
@cmsj - I've finally had a proper play with **hs.chooser** - it's awesome! Thank you!

A few things I'd love to see added to it:

- Ability to "right click" on results. For example, I'd love the ability to right click on a result, which opens up a menu allowing me to "Remove Search Result", etc.

- I'd love a function that allows me to know if the **hs.chooser** is currently visible or not.

- Dark Mode doesn't look great for some reason on my machine (MacBook Pro, macOS 10.11.6, Hammerspoon 0.9.48)  - see attached screenshots:

<img width="1886" alt="lightmode" src="https://cloud.githubusercontent.com/assets/22286696/19756501/dc93f638-9c68-11e6-9479-9e65d585eddd.png">
<img width="1886" alt="darkmode" src="https://cloud.githubusercontent.com/assets/22286696/19756502/dcec3f32-9c68-11e6-8eb1-22a0a7cf085b.png">

- Also, I'm being REALLY picky - but if you look at the attached screenshot you can see that the UI elements don't really line up:

<img width="793" alt="ui-glitch" src="https://cloud.githubusercontent.com/assets/22286696/19761237/c1e23d0a-9c80-11e6-9f0d-f7aaec14cd7b.png">

I might try giving some of these a bash myself sometime!

**Comment by cmsj** [comment]
@latenitefilms dark mode is fixed in git, so that'll be fine in the next release (see #1053) - this also somewhat masks the UI misalignment. I've just added an `:isVisible()` method. I'm not sure about adding a context menu - I can see that it would be useful, but I'm not sure it's something I have time for right now. Maybe I could add a very simple "user right clicked at this point" callback, which gets the row information, and then hs.menubar could be used to open a menu at that location?

**Comment by asmagill** [comment]
@cmsj, +1 on passing the location and having hs.menubar used to generate the pop-up menu... down the road I hope to make some additions to hs.menubar to make it more useful in other modules/places and it will simplify things in terms of consistency if there is only one place to update/modify... Or if you do decide on something more integrated, then have it take an `hs.menubar` object as a parameter and pull the menu from that -- keep the menu parsing code centralized for the same reason.

**Comment by latenitefilms** [comment]
@cmsj - Awesome, thank you! Curious... how often do new releases come out? Sorry for my ignorance, but is this something I could implement prior to the new version of Hammerspoon coming out?

@asmagill - I really like the idea of having **hs.menubar** work as a pop-up menu!

**Comment by cmsj** [comment]
@latenitefilms the releases are pretty ad-hoc. We probably have enough stuff queued up to start thinking about a new release soon :)

**Comment by latenitefilms** [comment]
@cmsj @asmagill - Thanks so much for adding the right click callback - it's very helpful! I'm currently using it to allow the user to customise the chooser search results via a menubar, which works great.

However, I'm confused how I can actually make use of **selectedRow**. What I want to do is write a function that allows you to "delete" items from the chooser - but I'm not exactly sure how you can use the **selectedRow** to work out the contents of the selected item? Any tips?

**Comment by cmsj** [comment]
It just tells you which row is highlighted. To get the actual row data you'd need to cross reference that with the choices table you have the chooser

**Comment by latenitefilms** [comment]
@cmsj - No worries, I thought as much - but because the row number changes depending on what the **hs.chooser:query** string is, it means you need to basically "do the search" again, which means you're relying on the end user to make sure their search function is identical to what you're doing in Objective-C with the Chooser. It would be great if there was something like **hs.chooser:selectedRow()["text"]** and **hs.chooser:selectedRow()["uuid"]** built-into **hs.chooser**. Does that make sense?

**Comment by asmagill** [comment]
I haven't played with the chooser much, but it is something I've been planning to do... I would agree that having selectedRow (with a special argument or even a different method, if you're worried about backwards compatibility) return a table with all of the relevant pieces would be *very* useful to how I've envisioned wanting to use it... but as I've said, I don't know much about it yet, so maybe I'm missing something.

**Comment by latenitefilms** [comment]
@cmsj - Seeing as you're online now... just wondering if you've got any thoughts on this?

**Comment by cmsj** [comment]
Sorry, meant to comment on this a while ago. I think it should be fine to return the data for the selected row. Either as a new method, `selectedRowData()` or as a second return value from `selectedRow()` so it doesn't break the current API. Any preferences? (@asmagill too)

**Comment by latenitefilms** [comment]
@cmsj - No worries! I'm happy with either option - although I don't actually see the use-case for **selectedRow()** as it currently stands, so I'm curious if anyone would actually be using it? I wonder if you could just replace it all together?

**Comment by latenitefilms** [comment]
Sorry @cmsj @asmagill - I know you're no-doubt all very busy, but I just wanted to quickly check in to see if any progress has been made on this?
