### ISSUE TITLE
Porting "Launcher mode v2" from Karabiner (turn any key to modifier key while hold down and able to chain up to 2 key after it)

### ISSUE THREAD

**Issue by dunkarooftop** [Hammerspoon/hammerspoon#1059]
In Karabiner you are able to turn any key (include alphabet character) in to modifier key while holding down and chain up to 2 keys after to execute an event (key stroke, run applescript, open apps, files...etc)

for example

while holding down "O" tap "F" to open Firefox
while holding down "O" tap "F", "F" to run an applescript

Basically need something to turn any key while tap do it's default role, while holding down go into a mode, while in that mode, listening for key, after 1st key wait say 200ms if no fallowing key run event1, if there are key tap within 200ms run event2

I been doing research on this so far found these 3 topic closest to what I want but not really
@JakeSc
https://github.com/JakeSc/dotfiles/blob/master/hammerspoon/init.lua
@smackesey
https://github.com/Hammerspoon/hammerspoon/issues/208
https://github.com/Hammerspoon/hammerspoon/issues/209

any tips would be much appreciated.

**Comment by cmsj** [comment]
@dunkarooftop a quick glance at the first one (by @JakeSc ) suggests that it's pretty close to what you want - what's missing from it?

**Comment by JakeSc** [comment]
@dunkarooftop I know what you mean. Karabiner Launcher Mode comes built in with a couple defaults:
`O` + `X`: Launch Xcode
`O` + `X` `X`: Launch Simulator

My Hammerspoon implementation accomplishes the first one and others like it, but not the second one. I have no plans to build support for multiple key presses in a single shortcut sequence, but my script can be modified to accomplish this. 

Your solution of setting a timer works.
 
I might also suggest adding a mapping table that maps each key in the shortcut config to how many times it's been pressed while the Launcher modifier has been held down. Then, upon releasing the Launcher modifier key, iterate through the table so check if the counts match any sequence provided in the config.

**Comment by dunkarooftop** [comment]
@cmsj with @JakeSs solution it also lost the default function of the assign modifier key when use alone and not able to chain more then 1 key after it. I am super new to Hammerspoon but super impressed by  the possibility and flexibility.  I will dig in more to the API docs and report back if I made any progress. Thanks. Any more tips are welcome as well thank you

**Comment by dunkarooftop** [comment]
One reason I really wanna port Launcher mode in to Hammerspoon is share the idea of "Nature Language Hotkey Method" I was in the middle of writing the blog post then it hit that Karabiner no longer work with sierra. Like to share the ideas here. The fallowing is part of the W.I.P. version

> When working with computer the hotkey does help to get things done snappier and make us feel like a high level computer ninja. But my problem with traditional hot keys system are:

>1. They are hard to remember because modifier keys are not meaningful to us human.

>2. There are different sets of hotkeys for each app. Our mind is best for doing creative works not to wast on remembering awkward hotkeys.

>3. They are uncomfortable for to execute. It's like playing twister with our fingers.

>The goal of this post is to share a better way to manage the way  we talk to computer. Let them speak our language, not the other way around to craft a better experience. And this is not just for the geeky coder/tinkler but for graphic designer even more. One of the worst hotkey design category is graphic design apps. (I am looking at you Photoshop, and MAYA 3D.) There are just too many functions and menu items in those apps which result those 3 modifier hotkey monsters to torture our head and fingers! Let me free you from it and make your fingers to dance like //PL on the keyboard. I assume most people who stumble on this page will be more coder alike. But I will be using a lot of graphic app reference in this post to keep the designer feel more like home, coder alike can imagine in your own scenario.

>Thankfully there is a better way to do so on Mac with the help of Karabiner - A powerful and staple keyboard customizer for OS X (It’s own tag line). It's a amazing free open source project by Takayama Fumihiko. It can do so many interesting things that I wrote about it on my other blog post. This post is diving down on one creative use of its “luncher mod”. With nature language method you can reduce context switch and stay in the creative flow much easier.

>I gonna start from a high level point of view show you what nature language method (NLM) looks like in action then dive in deeper to show how it's done after. Think AWESOME key is a super charged modifier key for now.

>###For general task mode:
**open Firefox**  holding “AWESOME”, tap “F”
**open Terminal**  holding “AWESOME”, tap “T”
(no more endless cmd+tab to sea of opened apps)
**open my Documents folder** holding “AWESOME”, tap “D”
**open Download Inbox** holding “AWESOME”, tap “D”, tap “I”
**Toggle Wifi** holding “AWESOME”, tap “W”
**Empty Trash** holding “AWESOME”, tap “E”, tap “T”
**Eject All** “AWESOME”, tap “E”, tap “A”
**Move window to Left half** “AWESOME”, tap “M”, tap “L”
**Move window to Right half** “AWESOME”, tap “M”, tap “R”
or in (WASD as arrow)
**Move window to left(a) half** “AWESOME”, tap “M”, tap “A”
**Move window to right(d) half** “AWESOME”, tap “M”, tap “D”

>###For designer in Photoshop mode:
(next few example we group all related action to start with the same character, in this case “L” for all “Layers” events. It’s exercising “chunking”)
**flatten layers -> Layers Flatten** holding “AWESOME”, tap “L”, tap “F”
**merge visible layers -> Layers Merge visible** holding “AWESOME”, tap “L”, tap “M”
**new Layer via copy(C)** holding “AWESOME”, tap “L”, tap “C”
**new Layer via cut(X)** holding “AWESOME”, tap “L”, tap “X”

>###For working in text editor mode
>I gonna use a popular text editor “Sublime Text” as an example here, I will barrow the idea from Vim which we talk to text editor to execute command. (Matter of fact the whole Nature Language Method was inspired by Vim. Talking to computer in plan English is much better than non sense modifier keys.

>**Cut Line** holding “AWESOME”, tap “C”,  tap “L”
**Insert line After** holding “AWESOME”, tap “I”,  tap “A”
**Insert line Before** holding “AWESOME”, tap “I”,  tap “B”
**Move line/selection Up** holding “AWESOME”, tap “M”,  tap “U”
**Move line/selection Down** holding “AWESOME”, tap “M”,  tap “D”
**Duplicate Line(s)** holding “AWESOME”, tap “D”,  tap “L”
**select current Word** holding “AWESOME”, tap “W”
**Quick-open files by name** holding “AWESOME”, tap “Q”
**Goto symbol** holding “AWESOME”, tap “G”, “S”
**Goto Line in current file** holding “AWESOME”, tap “G”,  tap “L”
**Command prompt** holding “AWESOME”, tap “C”
**toggle sidebar** holding “AWESOME”, tap “S”,  tap “B”
**Find** holding “AWESOME”, tap “F”
**Find in Files** holding “AWESOME”, tap “F”,  tap “F”

>You get the idea, and yes I am aware that some of the NLM require one more key to do the command but the gain here is the less context switch. You are just talking normally to the editor. :)

**Comment by cmsj** [comment]
I'd note that Karabiner Elements has come a long way now on Sierra, and I think generally it's better to wait for KE to re-implement features, rather than try to shoehorn them into Hammerspoon, so I'm going to close this issue out.
