### ISSUE TITLE
Bug: Keys stop working when opening file in MacVim via hotkey

### ISSUE THREAD

**Issue by n8henrie** [Hammerspoon/hammerspoon#1068]
I'm having a sort of weird issue with a hotkey that I use to run an AppleScript. It's set up this way because I previously used Karabiner + Quicksilver to manage my hyper + hotkeys, and have since ported it over to Karabiner-Elements + Hammerspoon.

I use it to open Macvim buffers with to the Finder selection. The AppleScript works fine by itself, but when called from hammerspoon, numerous keys do nothing at all until Macvim is closed -- they don't even register as keypresses in Karabiner-EventViewer.

I thought would be helpful to tell what keys don't work, so I just tried to go through them and realized that it's all the keys I've used to bind a hammerspoon-activated hyper hotkey.

So for example, I select 2 files and hit `hyper v` to open in Macvim. Macvim opens with a file in each buffer, as expected. However:

- `c` doesn't work (I have `hyper c` bound to remove nonprintable characters from the clipboard)
- `p` doesn't work (`hyper p` activates Messages.app)
- `return` doesn't work, which makes it harder to quit Macvim (`hyper return` activates Finder and merges all windows)

The AppleScript, which works fine if I select a file or files manually and run in Script Editor (take out the check for frontmost if running in Script Editor), and runs fine with my old Quicksilver hotkey setup:

```applescript
tell application "Finder"
	set the_selection to the selection

	-- If Finder is frontmost and one or more files selected, open each in a buffer
	if frontmost is true and (count of the_selection) is greater than 0 then
		set all_paths to ""
		repeat with each in the_selection
			set all_paths to all_paths & " " & quoted form of (POSIX path of (each as alias))
		end repeat
		do shell script "/usr/local/bin/mvim" & all_paths
	else
		-- If Finder is not frontmost or no files selected, just activate
		tell application "MacVim" to activate
	end if
end tell
```

Relevant hammerspoon config:

```lua
hyper = hs.hotkey.modal.new({}, "F18")
-- Actual hyper key is f19, set through Karabiner-Elements
f19 = hs.hotkey.bind({}, 'F19', function() hyper:enter() end, function() hyper:exit() end)

hyper:bind({}, 'v', nil, function() run_applescript("/path/to/Open in MacVim.scpt"); hyper:exit(); end)
```

I have a few similar hotkey setups that run applescripts and work fine. For example, for testing, I copied the above Macvim setup to instead bing `hyper t` to run `/usr/local/bin/edit` (Textwrangler) on selected files, and that worked fine.

I thought it might have something to do with the `do shell script` command continuing to run the process and not releasing hammerspoon's hyper mode, so I tried a few things like
- running the `mvim` command in a subshell `do shell script "(mvim file1 file2)"`
- double subshell and backgrounding `do shell script "((mvim file1 file2) &) &"`
- `do shell script "mvim file1 file2 & disown"`

None of those change the issue -- Macvim comes up with both files, and any key used in a hammerspoon hyper hotkey combo is completely disabled.

Sorry, this is a little difficult to describe, so I hope I've done an okay job. Let me know if I can provide more info, or if anyone else is / isn't able to reproduce.

EDIT: Forgot to mention, but everything works fine if I use TextWrangler's `/usr/local/bin/edit` command instead of `mvim`.

**Comment by cmsj** [comment]
Apologies for the slow reply.

Does /usr/local/bin/mvim block until MacVim quits? That would be my immediate guess of what's going on here.

If that is the issue, then you could use the AppleScript to just gather the list of selected filenames, and then do the other parts with Hammerspoon functions (e.g. hs.task is good for running background processes)

**Comment by n8henrie** [comment]
That's likely the issue.

I can still reproduce but found a workaround, using AppleScript's `do shell script "open -a macvim" file_paths` style seems to work, full applescript below.

```applescript
tell application "Finder"
	set the_selection to the selection
	if frontmost is true and (count of the_selection) is greater than 0 then
		set all_paths to ""
		repeat with each in the_selection
			set all_paths to all_paths & " " & quoted form of (POSIX path of (each as alias))
		end repeat
		do shell script "open -a macvim " & all_paths
	else
		tell application "MacVim" to activate
	end if
end tell
```
