### ISSUE TITLE
Bind hs.hotkey.modal to function keys without the need to use the Fn key

### ISSUE THREAD

**Issue by saagarjha** [Hammerspoon/hammerspoon#1070]
I'm trying to bind to a Hyper+F1 (brightness down) keypress (F17 has already been remapped from the Hyper key using [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements)):

```lua
local k = hs.hotkey.modal.new({}, "F17")
k:bind({}, "F1", nil, function() hs.alert.show("Foo") end)
```

Unfortunately, this requires pressing Caps Lock+Fn+F1 to activate, instead of Caps Lock+F1 (which decreases the brightness). Is there any way to get this to work without requiring the Fn key to be pressed?

**Comment by cmsj** [comment]
I can't immediately think of a way to do this, because the OS is going to intercept the brightness keypress and not make it visible to us. Sorry!
