### ISSUE TITLE
window.layout "active" mode broken since 0.9.47

### ISSUE THREAD

**Issue by wsmith323** [Hammerspoon/hammerspoon#1079]
I know that window.layout is experimental, but I have been using it happily until 0.9.47, when the "active" mode stopped working.

I can still trigger the layout manually with a hotkey, but I had gotten used to it automatically enforcing my layout rules.

I have been using 0.9.46 and eagerly install each new release in hopes that whatever caused this experimental feature to fail would get fixed. The 0.9.49 release just landed and still no joy.

I am content to run 0.9.46, as it satisfies my current demands, but that contentment decreases with each new release.

Just thought I would let someone know in case the problem is easily fixed and has just been overlooked.

**Comment by cmsj** [comment]
@wsmith323 thanks for the report, this should be fixed by 30aecb7 :)
