### ISSUE TITLE
Key Repeat is slow since 0.9.49

### ISSUE THREAD

**Issue by lrytz** [Hammerspoon/hammerspoon#1082]
Key Repeat is much slower since 0.9.49. The rate still changes if I move the slider in System Preferences - Keyboard. But shortcuts bound to hammerspoon repeat much slower than other keys. Downgrading to 0.9.48 fixes it for me.

**Comment by asmagill** [comment]
If you're using hs.eventtap.keyStroke, check out https://github.com/Hammerspoon/hammerspoon/issues/1011#issuecomment-261114434

If you're referring to something else, then please provide more details.

**Comment by lrytz** [comment]
Thanks for the pointer! Indeed, using `myDoKeyStroke` instead of ` hs.eventtap.keyStroke` fixes it for me.

I know next to nothing about hammerspoon and its internals, but to me the new behavior is unexpected, I'd call it a regression. But feel free to close this issue if you disagree.

**Comment by cmsj** [comment]
Closed because the delay is now an optional parameter on the various relevant functions. Further potential work would be to make it a module level setting (a la window animation durations)

**Comment by RichardForrester** [comment]
@cmsj What is the current way to remove the delay? I'm looking at the documentation and I don't see anything about overriding the default delay, at least on hs.hotkey and hs.hotkey.modal.

**Comment by cmsj** [comment]
@RichardForrester the delay is on hs.eventtap.keyStroke(), the hs.hotkey repeat callbacks should match the repeat settings in System Preferences -> Keyboard

**Comment by RichardForrester** [comment]
Thank you for responding @cmsj. That was enough information for me to figure it out. Unfortunately I do not speak Hammerspoon and therefor had to cross reference several sources and spend an hour or so tinkering to get there.

If anyone else out there is in the same boat I'll try to explain the way I got what I wanted, which is to use the default keystroke delay setting from MacOS on bindings made through Hammerspoon.

As an example, the old code to rebind the 'l' key to the right arrow key (only on repeat for clarity) looks like:
```
function repeatfn()
  hs.eventtap.keyStroke({}, 'right')
end

hs.hotkey.bind({}, 'l', nil, nil, repeatfn)
```

Compare that with the new code to ensure you override the default delay set by Hammerspoon on the repeat function. First, you can make a global variable to hold number of microseconds set by MacOS for the delay. Second, you use that variable in the keyStroke function as the optional third parameter.
```
delay = hs.eventtap.keyRepeatDelay()`

function repeatfn()
  hs.eventtap.keyStroke({}, 'right', delay)
end

hs.hotkey.bind({}, 'l', nil, nil, repeatfn)
```
That's it, so easy.
