### ISSUE TITLE
Should hs.spotlight be a core module?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1086]
@cmsj (& others?  not sure who the regulars are anymore), I was finishing up the documentation for a proposed `hs.spotlight` module (which can add alternate application name mapping as requested in #1043) when I began to wonder if we really want this to be a core module... The syntax for complex queries is not exactly simple, and even simple ones require the use of less than obvious attribute names (unless we want to write a parser to go with it that is way beyond what I had in mind when I started the module).

I do not want to have to provide support for questions along the lines of "why doesn't my query work"...

The proposed module can be found at https://github.com/asmagill/hammerspoon_asm/tree/master/spotlight, and a name mapping solution can be found in its examples directory.

And it is useful and it does fill a need, so I see the following options:

* we include it, and if people do post query related questions to the Hammerspoon issues that aren't about an error in the module or an extension suggestion, we refer them back to the [query string documentation](https://github.com/asmagill/hammerspoon_asm/tree/master/spotlight#queryString) and tell them to RTFM.
* we include it, but do not document it, leaving pointers in the init.lua file that points them to documentation online if they really want to use it, but understand that it is not fully supported
* we do not include it and it remains a third part extension addition (in this case, I would go through and change the path so that `_asm` is included in, reinforcing the idea that it is a third party module, not an included one)

The first two allow us to extend `hs.application` so that the functions which currently do not handle alternate application names could do so... and I suppose we could add code to detect if the third-party version was installed and support it then, but not otherwise, but... that way lies a whole other set of issues/questions I don't want to have to handle.

I'm leaning towards option 1, but perhaps replicate the links that are provided in the queryString documentation at the top of the module header as well and make it clear that the Google group and not Hammerspoon Github issues is where query help may be requested... and to RTFM!

Thoughts?  As always, I will go with the consensus, if there is one.

**Comment by cmsj** [comment]
I vote option 1. I want to use it :)

**Comment by cmsj** [comment]
(FTR, I don't think it matters that the NSPredicate language is complex, and I definitely do not think we should try and wrap it)

**Comment by cmsj** [comment]
I'm also going to close this, because I unilaterally say we should include your module :D
