### ISSUE TITLE
flagsChanged works on the lock screen

### ISSUE THREAD

**Issue by AaronLasseigne** [Hammerspoon/hammerspoon#1088]
I'm using a combination of `hs.eventtap.event.types.flagsChanged` and `hs.eventtap.event.types.keyDown` to do some modifier remappings. I'm trying to emulate the behavior of ctrl acting as escape when tapped and ctrl when used with another key (and a similar behavior with the shift keys). So far the code seems to work fine except for when I'm on the lock/login screen. It looks like `flagsChanged` is triggered but `keyDown` is not. The result is that I get extra characters as I'm typing my password.

Is it possible to avoid this? Can `flagsChanged` be turned off for the lock screen? Is there a way to detect the lock screen in HS so I can avoid this?

I've included the code for reference.

```lua
function bindLoneModifierKey(modName, modifiers, key)
  modToCode = {
    ['left shift'] = 56,
    ['ctrl'] = 59,
    ['right shift'] = 60
  }
  codeToMod = {
    [56] = 'shift', -- left
    [59] = 'ctrl',
    [60] = 'shift' -- right
  }

  displayLoneTap = null

  hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(eventType)
    displayLoneTap = null
  end):start()

  hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function(eventType)
    keyCode = eventType:getKeyCode()

    pressedDown = eventType:getFlags()[codeToMod[keyCode]]
    if pressedDown then
      displayLoneTap = keyCode
    else
      if keyCode == modToCode[modName] and keyCode == displayLoneTap then
        hs.eventtap.keyStroke(modifiers, key)
        displayLoneTap = null
      end
    end
  end):start()
end
bindLoneModifierKey('ctrl', {}, 'escape')
bindLoneModifierKey('left shift', {'shift'}, '9')
bindLoneModifierKey('right shift', {'shift'}, '0')
```

**Comment by cmsj** [comment]
You can use http://www.hammerspoon.org/docs/hs.caffeinate.watcher.html to detect when the screen locks/unlocks, and stop/start your eventtap :)

**Comment by AaronLasseigne** [comment]
I didn't think to look there. Thanks a bunch.
