### ISSUE TITLE
Karabiner Homerow mode replication

### ISSUE THREAD

**Issue by aristidesfl** [Hammerspoon/hammerspoon#1092]
I've been using [Karabiner](https://github.com/tekezo/Karabiner) for complex key remapping configurations. Unfortunately it is not compatible with macOS Sierra.

Wondering how much effort would it be required to replicate this functionality with hammerspoon, specifically **Homerow Arrow and modifier mode**

![screen shot 2016-11-22 at 22 37 23](https://cloud.githubusercontent.com/assets/208149/20542983/5cdbfc28-b104-11e6-9727-a56b5c519be9.png)

**Comment by Fabbi** [comment]
I know this one is rather old now, but if someone stumbles upon this in the future:

This should be pretty much doable. 
I've actually implemented the Karabiner "Caps Lock to Control_L (+ When you press Caps Lock only send ESC)" feature in hammerspoon. It shouldn't be much of a trouble to add these few options, too.

**Comment by aristidesfl** [comment]
@Fabbi thanks, that is great to hear, better old than never.

Can you point me to your caps lock example? Can Hammerspoon modify the space key as well?

**Comment by Fabbi** [comment]
I will clean up my code a little and put a link here later when I get home.

You can watch for almost every keyevent with `hs.eventtap` and tell the system to drop the current keyevent (and replace it with another one). It shouldn't be a problem to catch hitting the space key, set a variable for `in home row mode` and then filter every action and translate it. 

How do you leave the homerow mode? Another `SPC` press?

**Comment by aristidesfl** [comment]
The mode is enabled while the space key is pressed, and deactivated when the space key is released. If the space key is pressed and released quickly it should emit a space character.

**Comment by Fabbi** [comment]
I see. That makes a lot more sense that way 😃

**Comment by aristidesfl** [comment]
@Fabbi any luck with the cleanup? :)

**Comment by Fabbi** [comment]
I'm sorry, I had no time yesterday 😅 

I made a repo: [Fabbi/hammerspoon](https://github.com/Fabbi/hammerspoon) 

Disclaimer: 
- I am no lua coder
- it is WIP
- space is lagging
- `h` does not work when another key is being held down
- other modifiers are being ignored atm

**Comment by aristidesfl** [comment]
Hopefully the H key might be keyboard ghosting, but is should still work with a few keys.

Thanks!

**Comment by cmsj** [comment]
I note that Karabiner Elements' beta releases now support complex keyboard modifications, and I would strongly urge people to use that instead of Hammerspoon, for this sort of thing :)
