### ISSUE TITLE
Wiki Documents and Module Coding

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1095]
I've been thinking about spending some time during December to focus on some wiki pages (I'll host them on my fork to keep it clear that I'm speaking only for me until/unless it's decided they should be moved into the main Hammerspoon site) describing module building... specifically I think I want to focus on the following areas:

* update my earlier [module writing walkthrough](https://github.com/asmagill/HS_ModuleWalkthrough/) with a heavier emphasis on the newer features of LuaSkin
* provide a complete list of the NSObject helper functions provided by each module:
  * to make sure we know what modules to pre-load when you need a particular object type handled
  * to make sure we don't accidentally replicate functionality
  * to encourage updating an existing handler if you think more functionality can/should be added... as an example, by adding images-as-patterns to `hs.drawing.color`'s NSColor handlers in #931, this was automatically added to every module that used NSColor objects through `hs.drawing.color` without having to make any changes to the other modules.
* describe some of the reasons behind why I code modules in the way I do... I don't want this to be seen as me promoting my way as "Hammerspoon Best Practices" (for the record, I'm willing to change), but because I think some of the questions faced when writing a module are common and we probably *should* create a best practices document at some time... laying out the questions I faced and how and why I answered them the way I did I think will get the ball rolling on this.

Other subjects that anyone think should be added to this list?

**Comment by asmagill** [comment]
* outline the steps to building a self-signed copy of Hammerspoon yourself
* outline how to add a completely new module to Hammerspoon

@cmsj, re adding a new module... did you ever get anywhere with trying to move some of the XCode configuration into separate files?  And would this even help with adding new modules?  One of the more annoying issues when adding new modules is that we either have to stagger the pull requests or deal with merge-conflicts in the `project.pbxproj` file.

**Comment by cmsj** [comment]
I haven't explored the Xcode separation thing for ages. I always got scared that we'd end up being stuck with some tool that isn't updated for new Xcode project formats :/

**Comment by asmagill** [comment]
* Capturing userdata in local versus global vars (see #1103), garbage collection, and callback functions

**Comment by cmsj** [comment]
@asmagill Do you still have any plans on this? I think it's fair to say that the number of people who are interested in writing modules is very close to zero, so I'm questioning whether it's worth spending a ton of time writing documentation for it.

**Comment by asmagill** [comment]
Not anything active... we probably do need to update the FAQ and add some wiki docs, but this particular plan never went anywhere, so I'm going to close it for now.  We can reopen it if there is interest, or start something a little more specifically targeted if people start asking for it.

**Comment by latenitefilms** [comment]
I'm going to slowly start consolidating all the amazing information you've both shared with me across many different issues and put it either in a blog post or in the CommandPost Developers Guide. I'm slowly starting to understand how all these Objective-C extensions work.
