### ISSUE TITLE
Change system preferences

### ISSUE THREAD

**Issue by ergl** [Hammerspoon/hammerspoon#1102]
I'm wondering if we can change certain system preferences options from hammerspoon – for example, inverting the scroll direction of the trackpad, enabling the standard function keys, or toggling display mirroring.

**Comment by cmsj** [comment]
@ergl those sorts of things are generally not exposed as API for us to consume. Having said that, it's usually possible to use AppleScript to tell the system preferences app to change them, and/or use the `defaults` terminal command to change them, but that usually also involves forcing the Dock to restart. I think I'd rather not start shipping either of those options inside Hammerspoon, but either should be fairly trivial to automate with Hammerspoon :)

**Comment by latenitefilms** [comment]
@ergl - I currently use **hs.execute** and `defaults` or `plistbuddy` to get and change system preferences, although as @cmsj  has said, in SOME cases you can also use [AppleScript](http://www.macosxautomation.com/applescript/features/system-prefs.html).

Personally, I would LOVE to see someone implement something like **hs.plist** in the future that allows you read/write plist values quicker than using **hs.execute** - especially when you need to read lots of plist values from the single plist file quickly.

**Comment by ergl** [comment]
@latenitefilms great, thanks for the tip! I'll give that a try
