### ISSUE TITLE
LuaSkin treat table with __call metamethod as function?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1105]
This has been in the back of my mind since #932... it's a relatively simple addition to LuaSkin to treat a table with a `__call` metamethod as a function in `checkArgs:`... we can even limit the check to when the spec for that argument position is LS_TFUNCTION anyways... and I've verified that `lua_pcall` can handle such a table as it's function argument with no other changes required on our part, so...

Is it a good idea to go ahead and make the change?  The only real drawback I can see is if the __metatable on the table goes away, we can't really easily detect it, so when it's finally treated like a function, it will cause a lua error to the console... but that's what you'd expect/want to happen anyways... so thoughts?

**Comment by asmagill** [comment]
Note that this would not change the actual type in the stack... if your function later checks with `lua_type` it will still see it as `LUA_TTABLE`... this would just allow `checkArgs:` to accept a table with a __call metamethod as a function like `lua_pcall` does.

(yes, I came across this exact situation while testing out possible code to implement)

**Comment by cmsj** [comment]
I think it makes sense to move towards being able to use `__call`able tables wherever functions are accepted :)

**Comment by cmsj** [comment]
@asmagill this Issue is all taken care of now, right?

**Comment by asmagill** [comment]
Yes, if `checkArgs:` is looking for a `LS_TFUNCTION` and the item at the index is a table with a `__call` metamethod, checkArgs: accepts the item as a function.

However, older modules which do not use `checkArgs` for validation (i.e. that use an explicit `lua_type()` for validation will fail unless they include their own logic to validate the table with metamethod or switch to `[skin luaTypeAtIndex:]` instead.

See https://github.com/Hammerspoon/hammerspoon/pull/1108 for details.
