### ISSUE TITLE
Offer a feedback UI when submitting a crash report

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1106]
`MJAppDelegate` already gets called when Crashlytics is detecting a crash report on startup, we should probably display some UI here for users to give us some information about what they were doing.

**Comment by latenitefilms** [comment]
Good idea - although I have to admit, I do like the fact that currently Hammerspoon just submits crash logs without any fuss. Maybe this new dialog box should be optional?

**Comment by cmsj** [comment]
Yes, I do not want to drive down our reporting rate. That's why we don't currently say anything, because experience shows that asking for reports == no reports ;(

**Comment by asmagill** [comment]
With the wrapping of exceptions so that they generate in-console errors, I think a prompt is less important... what I don't want to do is drive people away because it crashes and they feel they have no idea why or anything to post other than "it crashes"...

If you feel a prompt might discourage people, then I'm not wedded to the idea.

**Comment by latenitefilms** [comment]
Maybe a "Submit Feedback" button in the menu would be helpful? Something like this?

<img width="604" alt="screen shot 2017-02-06 at 7 27 27 pm" src="https://cloud.githubusercontent.com/assets/22286696/22639493/67bfb8d0-eca2-11e6-908d-24109e99969e.png">
<img width="604" alt="screen shot 2017-02-06 at 7 27 29 pm" src="https://cloud.githubusercontent.com/assets/22286696/22639492/67bddb96-eca2-11e6-904b-9e7ee4bb8fb2.png">
<img width="604" alt="screen shot 2017-02-06 at 7 27 31 pm" src="https://cloud.githubusercontent.com/assets/22286696/22639494/67c066ea-eca2-11e6-8da4-101f7721dff6.png">

**Comment by cmsj** [comment]
I'm going to close this out for not having any traction.
