### ISSUE TITLE
Support for other bluetooth HIDs (e.g. PS4 / Xbox One S controllers)

### ISSUE THREAD

**Issue by rayshan** [Hammerspoon/hammerspoon#1109]
Hi, I have a PlayStation DualShock 4 controller connected via Bluetooth in El Capitan. Is it possible to map the controller buttons using `hs.hotkey` or `hs.eventtap`? I don't believe `hs.keycodes.map` shows anything for the controller.

**Comment by cmsj** [comment]
I don't believe it's currently possible, but I don't really know anything about how those devices appear to the system in terms of getting their events.

It'd be a fun addition though, we'll see what we can do :)

**Comment by cmsj** [comment]
Note for future use: https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/mac/hid.c seems relevant here, and there are a variety of tools which build on that in nodejs land, for DS4 access.

**Comment by asmagill** [comment]
If it maps to keyboard or mouse events, then we should be able to use it... if it's seen as a game controller (joystick or the like), then I don't think we can, but I agree, it would be a nice addition.  I thought I remembered an extension request for such, but I'm not finding it in the issues, so this can stand in for it.

The questions I have are what does this (the DualShock controller specifically) device appear as to the system, and would it also apply to USB controllers (I have a few I wouldn't mind using on occasion), or would that be separate code?

**Comment by rayshan** [comment]
This is what System Information app shows for my controller:

```
  Devices (Paired, Configured, etc.):
  Wireless Controller:
  Address:	40-1B-5F-EC-F3-33
  Major Type:	Peripheral
  Minor Type:	Peripheral
  Services:	Wireless Controller
  Paired:	Yes
  Configured:	Yes
  Connected:	Yes
  Manufacturer:	Qualcomm Atheros (0x6, 0x01)
  Firmware Version:	0x0100
  Vendor ID:	0x054C
  Product ID:	0x09CC
  Class of Device:	0x05 0x02 0x2508
  AFH:	On
  AFH Map:	FFA7700000807F
  RSSI:	-53
  Role:	Master
  Connection Mode:	Active Mode
  Interval:	0 ms
  Host Connectable:	No
  EDR Supported:	Yes
  eSCO Supported:	Yes
  SSP Supported:	Yes
```

Apps like [OpenEmu](https://github.com/OpenEmu/OpenEmu) and [Enjoyable](https://yukkurigames.com/enjoyable/) see the controller and allow mapping. Here's another open source project that may be helpful:
https://github.com/slembcke/CCController

Is there anything else I can provide?

**Comment by runeimp** [comment]
I came across this looking for DS4 battery status help on OS X. I have used Slate in the past and I'm loving Hammerspoon even more! Lua makes me happy.  😃

Wondering what the status is of adding DS4 specifically or a general Bluetooth device status API to Hammerspoon?

**Comment by cmsj** [comment]
@runeimp I don't think anyone is currently working on it, but it would be nice if we had it.

(I think that these things tend to work best if the code is written/maintained by someone who actually wants to use it, so they have motivation to stay involved)

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
