### ISSUE TITLE
hs._asm.canvas

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1110]
Unless there are objections, I think I want to go ahead and add my canvas module, minus its support for other views (media, etc)

Pros:
* It's a lot more flexible and easy to update individual elements than `hs.drawing` is
* There is a lua wrapper for `hs.drawing`, when we're ready to truly replace it
* I have some other modules I'd like to offer that sort of require it (primarily a KODI/XBMC media server controller module that creates an on-screen remote control... the visual isn't really necessary, but makes it a whole lot easier to use and would be a real pain to do with just `hs.drawing`.)
* It allows for tracking areas, so we can track when the mouse moves into or out of a visual and not just when the mouse button is pressed
* Some examples of what it makes easier/possible can be seen at https://github.com/asmagill/hammerspoon_asm/blob/master/canvas/EXAMPLES.md

Cons:
* Eventually I want to wrap even that with `hs._asm.enclosure` (which basically mimics NSWindow), so there will eventually be potentially *another* lua wrapper for canvas (which, btw is written, but the enclosure module needs a whole lot more work before it's safe to include (if you stray too far outside of what the canvas wrapper requires, it can crash or create a visual element that is unusable), though it *will* support other view types like media and buttons and even `hs.webview` as a subview (i.e. with other subviews around/over it), when it's ready... I just don't have time to work on it right now *and* do other things I've committed to or think are more important right now (the touch bar stuff, getting axuielement in a usable format, the wiki docs, life, etc.)

**Comment by cmsj** [comment]
+1 :)

**Comment by cmsj** [comment]
Closing, since hs.canvas merged
