### ISSUE TITLE
Hammermoon

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#1111]
Repo [here](https://github.com/lowne/hammermoon). Not even remotely close to readiness status, but a look at the code that's there should be sufficient to get the general idea.
(note that the lower level guts are still very much WIP; I'm trying to hammer objc.lua to also fully manage retain/release for CF stuff)

Would love to hear any thoughts/ideas/suggestions/strongly worded opinions :)

**Comment by asmagill** [comment]
I've not kept up with luajit... how wedded is it to lua 5.2 these days?  I've come to like the bit operators, the 64 bit integers, and the distinction between integer and float at the lua code level.

On the macOS API side... how hard/easy is it to handle or add undocumented APIs, both objects and functions?

**Comment by cmsj** [comment]
LuaJIT is firmly wedded to Lua 5.1. They have partial 5.2 compatibility, but that's it.

**Comment by cmsj** [comment]
(I should note that there are some compatibility shims, but they're not 100%)

**Comment by asmagill** [comment]
Thought I had heard about a fork that was 5.2 (or almost) compatible... like I said, I haven't kept up with it :-)

**Comment by lowne** [comment]
5.2 compatibility is pretty good; see towards the end of http://luajit.org/extensions.html; off the top of my head I can't think of missing stuff other than `#table`~=`mt.__len(table)` and `_ENV` (ne' `setfenv`)

**Comment by lowne** [comment]
Also: bit operators are in `bit`, 64bit integers are boxed ffi cdata (e.g. `0LL`) and I don't know when the distinction between integer and float is useful besides type checking (which is trivial)

**Comment by lowne** [comment]
Re: undocumented stuff, you can add literal C declarations directly via `ffi` (see [here](https://github.com/lowne/hammermoon/blob/master/hm/applications.lua#L488) for a (temporary) example - all that stuff is being cleaned up and moved into `hm._os`), or indirectly via `objc.lua`'s `addfunction` (which is all over the place in the repo)

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
