### ISSUE TITLE
Use ctrl+p/ctrl+n to move up and down the chooser list

### ISSUE THREAD

**Issue by stiang** [Hammerspoon/hammerspoon#1115]
It would be great if it were possible to use ctrl+p and ctrl+n to move the selection up/down, in addition to the arrow keys. This is the standard Emacs keybinding for moving up/down, which is also supported by default in macOS, bash etc.

(Originally filed as nathancahill/anycomplete#9 - I thought the chooser was specific to anycomplete.)

**Comment by ashfinal** [comment]
Vote for this. 

I made my own plugin, and it will be more convenient if we can have this feature. https://github.com/ashfinal/awesome-hammerspoon

**Comment by aldur** [comment]
@cmsj PR https://github.com/Hammerspoon/hammerspoon/pull/1249 addressed this issue, didn't it?

**Comment by cmsj** [comment]
@aldur yes, thanks!
