### ISSUE TITLE
KVO lite for Lua?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1116]
I've started using https://github.com/asmagill/hammerspoon_asm/tree/master/watchable so I can "communicate" between files in my setup and so that I can reduce the number of watchers that are really doing exactly the same thing (e.g. using `hs.caffeinate.watcher` to detect when the system is about to go to sleep).

Would this be useful in core or just confusing to people not familiar with KVO?

**Comment by junkblocker** [comment]
This is a must! :+1:
