### ISSUE TITLE
hs.webview:url() ignores HTTPBody

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#1121]
```Lua
if web then web:delete() web=nil end
web = hs.webview.new(hs.geometry.rect(100, 100, 600, 600))
web:show()web:url({URL='http://requestb.in/r1g2dir1', HTTPBody='PostalCode=1223DB&HouseNumber=77', HTTPMethod='POST'})
```

The request arrives with Content-Length 0 and no body. Changing the code (in `http/internal.m` as used by `webview` via `LuaSkin`) in the following ways yielded no change:
1. switching the body to NSString (as that is what `hs.http.post` uses, and body content does work there!)
2. stealing all of the code that `hs.http.post` uses
3. adding a `Content-Type` (it does get passed along but body stays empty)

During all these experiments I can confirm that the length passed to the relevant constructor or property setter is correct.

I don't think this is a HS bug; it looks like a `WKWebview` limitation more likely.

**Comment by asmagill** [comment]
I can confirm that as of 10.12.2, this appears to be a limitation in WKWebView... reusing all of the code `hs.webview:url` uses to create the NSURLRequst and then feeding this directly into a modified `hs.http.doRequest` succeeds while the webview version continues to fail.

There are some known oddities with WKWebView and I will do some digging to see if we can work around this, but at present, I don't think we can.
