### ISSUE TITLE
win:screen() has wrong value?

### ISSUE THREAD

**Issue by microcosm** [Hammerspoon/hammerspoon#1126]
Hi,

I am following this simple example from the [getting started tutorial](http://www.hammerspoon.org/go/):

    hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Left", function()
      local win = hs.window.focusedWindow()
      local f = win:frame()
      local screen = win:screen()
      local max = screen:frame()
    
      f.x = max.x
      f.y = max.y
      f.w = max.w / 2
      f.h = max.h
      win:setFrame(f)
    end)

However, if the window in question is on my second screen (to the right), it is moved back to the first screen and the frame values are applied based on the first screen.

**Comment by asmagill** [comment]
Does this happen with all applications?  In my tests, it works as expected and moves the focused window on the screen it's already on (note that the focused window may not be the window the mouse pointer is over, and that threw me for a sec)

**Comment by microcosm** [comment]
Thanks @asmagill. I get this consistently with every application. Here's my [config](https://github.com/microcosm/hammerspoon-config), maybe something else I am doing is causing the problem?

**Comment by asmagill** [comment]
Hmmm... strange...

Couple of thoughts:
* do you have any kind of window watcher or window filters going on in the background?
* any other applications running which manage window positions?
* in the "Mission Control" pane of your "System Preferences", is "Displays have separate spaces" checked or unchecked?
* What's the output of this when you enter it into the Hammerspoon console?
~~~lua
for i,v in ipairs(hs.screen.allScreens()) do print(v:name(), (hs.inspect(v:frame()):gsub("%s+", " "))) end
~~~
* and:
~~~lua
hs.accessibilityState()
~~~

**Comment by microcosm** [comment]
> do you have any kind of window watcher or window filters going on in the background?

No

> any other applications running which manage window positions?

I used to use ShiftIt, but I removed that when I started using Hammerspoon

> in the "Mission Control" pane of your "System Preferences", is "Displays have separate spaces" checked or unchecked?

Checked

> What's the output of this when you enter it into the Hammerspoon console?
```
> for i,v in ipairs(hs.screen.allScreens()) do print(v:name(), (hs.inspect(v:frame()):gsub("%s+", " "))) end
-- Loading extension: screen
-- Loading extension: inspect
DELL U3415W	{ -- hs.geometry.rect(0.0,23.0,3440.0,1417.0) _h = 1417.0, _w = 3440.0, _x = 0.0, _y = 23.0 }
Color LCD	{ -- hs.geometry.rect(3440.0,23.0,1440.0,873.0) _h = 873.0, _w = 1440.0, _x = 3440.0, _y = 23.0 }
SONY TV	{ -- hs.geometry.rect(-1920.0,23.0,1920.0,1057.0) _h = 1057.0, _w = 1920.0, _x = -1920.0, _y = 23.0 }
```
> and
```
> hs.accessibilityState()
true
```

The `Color LCD` above is my laptop's internal display. The screens are physically arranged like this:
`[SONY] [DELL] [Color LCD]`

In `System Preferences > Display > Arrangement` the screens are also arranged that way, horizontally aligned along their top edges.

- The problem occurs when the window is on `[Color LCD]` and I press the key combination, in which case the window moves to `[DELL]`. 
- The problem does not occur when the window is on `[DELL]` and I press the key combination, in which case the window stays on `[DELL]` and resizes as expected.

When I have either of these configurations...

`[DELL] [Color LCD]` or `[SONY] [Color LCD]`

... the problem occurs from my laptop to whichever screen is left of it. The window will move to the `DELL` or `SONY`instead of remaining on `Color LCD`.

Oddly, when the window arrives on the left screen, it is _resized_ based on the dimensions of the `Color LCD`, however it is _positioned_ on the left screen. When I push the key combination a second time, it remains on the left screen and now resizes to match the left screen.

**Comment by lowne** [comment]
My guess is this has to do with animations and `hs.window.setFrameCorrectness`.

**Comment by microcosm** [comment]
Thanks @lowne. I tried setting `hs.window.setFrameCorrectness` to `true`.

```
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Left", function()
  hs.window.setFrameCorrectness = true;
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()

  f.x = 0
  f.y = 0
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end)
```

I reloaded the config and tried again - it made no difference to the resulting action.

**Comment by lowne** [comment]
Then I'm at a loss. To make sure the problem is `:setFrame(f)`, try with a `print(f)` or `print(hs.inspect(f))` right before it, to confirm that `f` is indeed in the `Color LCD` screen. If it is, try also `hs.window.animationDuration=0` and `win:setFrameWithWorkarounds(f)` instead of setFrame.

**Comment by microcosm** [comment]
I found the answer. I misunderstood the X and Y value of the window frame object. I thought they were relative to the screen, but they appear to be relative to a larger multi-screen coordinate system.

I [changed the](https://github.com/microcosm/hammerspoon-config/commit/b6101684f32dd3addd5136fcec7e8205938a7312) X and Y assignments to use the screen frame's X and Y instead of just 0, and that fixed it. I also [changed the](https://github.com/microcosm/hammerspoon-config/commit/396d57edcb0660c60d11728a94e622cc892b1d80) variable naming that I had gotten from the [intro doc](http://www.hammerspoon.org/go/), as I think it was less expressive and that was making it less clear what the problem was.

Thanks both of you for the help!
