### ISSUE TITLE
mailto support for hs.urlevent

### ISSUE THREAD

**Issue by wincent** [Hammerspoon/hammerspoon#1127]
I'd find this pretty useful. Before diving in and trying to code it up, I wanted to ask if there is any reason why hs.urlevent is currently limited to handling http and https schemes (and therefore, why supporting mailto might not be a good idea).

**Comment by cmsj** [comment]
I'm not opposed to supporting mailto: - I don't remember there being any particular technical issue with supporting it, I just wanted to start with http/https.

**Comment by wincent** [comment]
On further digging [I found out here](https://groups.google.com/forum/#!msg/iterm2-discuss/TFPl1D_miIU/uDVV2ZZpYWQJ) that iTerm2 already allows you to make it the URL handler for a bunch of different protocols, including `mailto`. So I've been able to hack something together using that for now (basically have iTerm2 handle the URL by running a command that I supply), so I've been able to achieve what I needed without Hammerspoon.

But it may still be useful to have this, and also consider looking at [the list of schemes](https://github.com/gnachman/iTerm2/blob/469d65f3e1521504b96d707c0f272eb285589ca2/plists/iTerm2.plist#L81-L179) that iTerm2 supports.

**Comment by cmsj** [comment]
better late than never :D

**Comment by junkblocker** [comment]
🎉

**Comment by junkblocker** [comment]
An example of how one could use it would be useful. Currently it gets the call but says it doesn't know anything about handling mailto urls. No documentation or anything seems to have been updated in this change.

```
2020-01-13 19:55:16: 19:55:16 ERROR:  urlevent: Hammerspoon has been passed a mailto URL, but does not know how to handle it
```
