### ISSUE TITLE
merging project.pbxproj

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1134]
@cmsj,  I'm, relatively speaking, new enough to Xcode and git that I wouldn't want to apply this without someone else checking it out first, but take a look at http://roadfiresoftware.com/2015/09/automatically-resolving-git-merge-conflicts-in-xcodes-project-pbxproj/ and let me know what you think

**Comment by asmagill** [comment]
https://github.com/simonwagner/mergepbx also gets a lot of mention, but it wouldn't be recognized on github.

**Comment by asmagill** [comment]
Although... check out http://stackoverflow.com/a/18275082

We may just be stuck with manual merging.

**Comment by cmsj** [comment]
I don't think I want to trust automagic XML merging tools - from what I've read, they are not a good idea for xcodeproj files.

Do you run into this particularly often?

**Comment by asmagill** [comment]
The only time this file changes is when a new module is added (or removed, but that's less often) to the Hammerspoon core application, so... not too often; it's really only an issue when two new modules are being introduced at the same time and both share the same parent... one get's merged with no problem and then the other requires a manual merge because a file it modified no longer has the same parent in master.

I kind reached the same conclusion re automated tools.  Staggering new modules or redoing a pull request against the new master works, so... yeah, leave this closed.
