### ISSUE TITLE
Rewrite API docs generator

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1143]
I don't understand Ruby enough to sanely maintain the current API doc generator, and I have been wanting to rewrite it for a while so that we can extract more structure from our (mostly) well structured docstrings.

I propose to rewrite the scripts in Python, because it's a language I'm much more familiar with (and idiomatic Python is significantly less complex than idiomatic Ruby, so others should find it easier to hack on).

Initially, I would have it spit out very similar HTML to it does now, but from there we have can have as much flexibility as we want to improve the structure, layout and features of the docs. Anyone have any particular things they are after?

**Comment by junkblocker** [comment]
One of the unreleased vim plugins I have and use when writing hs code extracts an extra file during doc build which looks like this.

```
hs
hs.accessibilityState(shouldPrompt) -> isEnabled
hs.alert
hs.alert.closeAll([seconds])
hs.alert.closeSpecific(uuid, [seconds])
hs.alert.defaultStyle[]
hs.alert.show(str, [style], [screen], [seconds]) -> uuid
...
```

It would be good if this kind of type signature can be presented when completing code in the console also and this doc build included as part of the build process also as for now I am maintaining a local patch.

And :+1: for rewriting it in python. Including my local patch for reference.

```diff
diff --git a/Makefile b/Makefile
index d45cef2..4400765 100644
--- a/Makefile
+++ b/Makefile
@@ -19,7 +19,7 @@ $(APPFILE): build $(shell find Hammerspoon -type f)
        cp -R ${PRODUCT_DIR}/Hammerspoon.app.dSYM build/
        cp -R ${PRODUCT_DIR}/LuaSkin.framework.dSYM build/
 
-docs: build/Hammerspoon.docset
+docs: build/Hammerspoon.docset $(HOME)/.vim/data/hammerspoon.dat
 
 build/Hammerspoon.docset: build/docs.sqlite build/html
        rm -rf $@
@@ -47,6 +47,10 @@ build/docs.sqlite: build/docs.json
 build/docs.json: build
        find . -type f \( -name '*.lua' -o -name '*.m' \) -not -path '*/sample-extensions/*' -not -path './build/*' -not -path './extensions/.build/*' -not -path './Pods/*' -exec cat {} + | scripts/docs/bin/gencomments | scripts/docs/bin/genjson > $@
 
+$(HOME)/.vim/data/hammerspoon.dat: build/docs.json
+       mkdir -p $(shell dirname "$@")
+       python scripts/docs/bin/genvim < $< >| $@
+
 build:
        mkdir -p build
 
@@ -55,6 +59,6 @@ clean:
        rm -rf LuaSkin.framework
 
 clean-docs:
-       rm -fr build/Hammerspoon.docset build/Hammerspoon.tgz build/html build/docs.json build/docs.sqlite
+       rm -fr build/Hammerspoon.docset build/Hammerspoon.tgz build/html build/docs.json build/docs.sqlite $(HOME)/.vim/data/hammerspoon.dat
 
 .PHONY: all release clean clean-docs
diff --git a/scripts/docs/bin/genvim b/scripts/docs/bin/genvim
new file mode 100755
index 0000000..01cbbfb
--- /dev/null
+++ b/scripts/docs/bin/genvim
@@ -0,0 +1,32 @@
+#!/usr/bin/env python
+try:
+    import simplejson as json
+except ImportError:
+    import json
+import sys
+
+DOCS = []
+
+def gen_item(item, prefix=''):
+    global DOCS
+    if not item:
+        return
+    if 'def' in item:
+        DOCS += [item['def']]
+    elif 'name' in item:
+        DOCS += ["%s%s" % (prefix, item['name'])]
+    if 'items' in item:
+        gen_itemlist(item['items'], prefix=(item['name'] + '.'))
+
+
+def gen_itemlist(lst, prefix=''):
+    if not lst:
+        return
+    for item in lst:
+        gen_item(item)
+
+
+gen_itemlist(json.load(sys.stdin))
+for item in sorted(DOCS):
+    print(item)
+sys.exit(0)
```

**Comment by asmagill** [comment]
Just a note for when we do switch:  to keep things looking the same in the builtin documentation viewer, the hs.doc.markdown submodule should be updated to use whatever github-flavored-markdown engine you change to when moving this to python.

**Comment by cmsj** [comment]
I'm not 100% why I didn't reference this bug at the time, but the new doc generator landed in master back in late December.
