### ISSUE TITLE
cant trap keys in iterm2

### ISSUE THREAD

**Issue by dannydulai** [Hammerspoon/hammerspoon#1145]
This works everywhere but if iTerm2 is focused, it doesnt print anything anymore. Changing to any other app works fine:

```
hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('tap!', hs.inspect(event))
  return false
end):start()
```

however, this works fine with iTerm2:
```
hs.eventtap.event.types.flagsChanged
```

any ideas? This is in MacOS 10.12.1 and iTerm2 3.0.12

**Comment by cmsj** [comment]
fwiw, I can't reproduce this on 10.12.2 and iTerm2 3.0.13. Are you able to re-test?

**Comment by cmsj** [comment]
I'm going to close this due to lack of response. If you can provide more information, please feel free to re-open it.

**Comment by hugo187** [comment]
I was having the same issue and found out the problem appears when "Secure Keyboard Entry" feature is enabled in iTerm.
