### ISSUE TITLE
hs.chooser dark mode looks bad with Reduce Transparency accessibility setting

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1150]
I've come across a strange `hs.chooser` issue.

On my system, the `hs.chooser` looks like this:

<img width="839" alt="good" src="https://cloud.githubusercontent.com/assets/22286696/21350138/e94bfd64-c709-11e6-80cf-473501990b81.png">

However, on another person's system it looks like this:

![bad](https://cloud.githubusercontent.com/assets/22286696/21350160/06cdf36a-c70a-11e6-990a-b1a0987b94d0.png)

Both are using exactly the same code, and same version of Hammerspoon.

The code is using the following settings:

```
:bgDark(true)
:fgColor(drawing.color.x11.snow)
:subTextColor(drawing.color.x11.snow)
```

Any ideas on why we'd be seeing different things? @asmagill ?

Thanks in advance!

**Comment by cmsj** [comment]
@latenitefilms that second screenshot looks suspiciously like an older version of Hammerspoon before we fixed up the `hs.chooser` dark mode. Might that other machine have an older version installed from Homebrew or something like that?

**Comment by latenitefilms** [comment]
No, apparently it's the latest version of Hammerspoon as downloaded from the site - but I'll triple check.

**Comment by latenitefilms** [comment]
Just checked... they're definitely running the latest version of Hammerspoon (see attached).

Any ideas?

![hammerspoon](https://cloud.githubusercontent.com/assets/22286696/21393656/85d69b82-c7e9-11e6-9ad6-56fce87caba8.jpg)

**Comment by latenitefilms** [comment]
FYI: Both my system and this other person are running macOS 10.12.1. Very odd!

**Comment by cmsj** [comment]
In the OSX Accessibility prefs, in the Display section, do they have reduce transparency on?

**Comment by latenitefilms** [comment]
Owww... interesting idea! I'll find out. Stay tuned!

**Comment by latenitefilms** [comment]
I haven't heard back from the user that reported the issue, but I can definitely reproduce on my machine. Thank you! Genius as always.

@cmsj & @asmagill - Is it worth adding some code into `hs.chooser` to detect if **Reduce transparency** is activated, and if so, offer a different Dark Mode setting?

**Comment by cmsj** [comment]
Yeah I think we should figure out how to detect that, so we can avoid looking bad.

**Comment by latenitefilms** [comment]
FYI: You can work out if it's enabled or not by looking in  `~/Library/Preferences/com.apple.universalaccess.plist` for the `reduceTransparency` boolean.

**Comment by cmsj** [comment]
http://stackoverflow.com/questions/27203272/nsvisualeffectview-behind-nsscrollview Has code to detect the setting. Just need to work out now what to do about it :)

**Comment by latenitefilms** [comment]
@cmsj - I guess if `reduceTransparency` is `true` and bgDark is `true` then `fgColor` and `subTextColor` should default to black on the selected item and white on non-selected items. If the user puts in a custom `fgColor` and `subTextColor`, then the none selected items should be the inverse of these values (i.e. if you puts in black, the non-selected items should be white).

**Comment by cmsj** [comment]
@latenitefilms so, I was just playing around with this, and it occurred to me that your example is setting custom colours. I have tested with reduced transparency with the default colours and I think it honestly looks fine, so what I would propose instead is that we expose a value somewhere that lets you check if the user has reduced transparency, so you can either set a different custom colour, or leave the defaults in place.
I think it would be a mistake for us to override custom colour choices if the user has accessibility options enabled.

**Comment by latenitefilms** [comment]
Legend, thanks @cmsj ! Will download and test it out!

**Comment by latenitefilms** [comment]
I downloaded the latest Hammerspoon Master, and the new `hs.chooser` code seems to not have a text colour regardless of whether I'm in dark mode or not?

`hs.screen.accessibilitySettings()` however works great, so I've reverted back to a previously build of `hs.chooser` and now everything is working really well - so not sure what the issue is?

<img width="827" alt="screen shot 2016-12-25 at 11 03 39 am" src="https://cloud.githubusercontent.com/assets/22286696/21469196/1def033c-ca92-11e6-9931-0574dddbbcaa.png">

**Comment by latenitefilms** [comment]
Also, interestingly, when I reverted back to the old `hs.chooser`, if I toggle **Reduce transparency** in the middle of a Hammerspoon session, it seems that any items I "moused over" in one mode, keep their "colour" in the other mode.

<img width="830" alt="screen shot 2016-12-25 at 11 52 04 am" src="https://cloud.githubusercontent.com/assets/22286696/21469315/b12da6fc-ca98-11e6-8d3a-f3f41ec1d771.png">

**Comment by asmagill** [comment]
@latenitefilms, This is with your FCPXHacks code?  I'll take a look at it sometime tomorrow or Monday because I'm not seeing this behavior with all of the latest and greatest compiled in for my usage of `hs.chooser` (which admittedly is fairly basic, but I'm starting to play with the callbacks and using the right click features and such).  Any special settings on your machines I should be aware of?  (e.g. *Reduce Transparency*, etc.)

**Comment by latenitefilms** [comment]
@asmagill With the latest Master, and **Reduce transparency** turned off in all of the below examples, if I use the following code straight into the Console...

```
function completionFn(result)
	print(result)
end
local choices = {
 {
  ["text"] = "First Choice",
  ["subText"] = "This is the subtext of the first choice",
  ["uuid"] = "0001"
 },
 { ["text"] = "Second Option",
   ["subText"] = "I wonder what I should type here?",
   ["uuid"] = "Bbbb"
 },
 { ["text"] = "Third Possibility",
   ["subText"] = "What a lot of choosing there is going on here!",
   ["uuid"] = "III3"
 },
}
local test = hs.chooser.new(completionFn):choices(choices):show()
```

...it gives me this:

<img width="801" alt="screen shot 2016-12-25 at 11 07 31 pm" src="https://cloud.githubusercontent.com/assets/22286696/21471051/fb794564-caf6-11e6-9dde-989956b030d7.png">

If I use the following code directly within the console...

```
function completionFn(result)
	print(result)
end
local choices = {
 {
  ["text"] = "First Choice",
  ["subText"] = "This is the subtext of the first choice",
  ["uuid"] = "0001"
 },
 { ["text"] = "Second Option",
   ["subText"] = "I wonder what I should type here?",
   ["uuid"] = "Bbbb"
 },
 { ["text"] = "Third Possibility",
   ["subText"] = "What a lot of choosing there is going on here!",
   ["uuid"] = "III3"
 },
}
local test = hs.chooser.new(completionFn):choices(choices):bgDark(true):show()
```

...it gives me:

<img width="793" alt="screen shot 2016-12-25 at 11 08 42 pm" src="https://cloud.githubusercontent.com/assets/22286696/21471057/2aa38b6a-caf7-11e6-9650-19d99c8feb7f.png">

If I switch back to an older version of `hs.console` (not sure of which version - but it was the one where you added the right-clicking feature) and use the following code:

```
function completionFn(result)
	print(result)
end
local choices = {
 {
  ["text"] = "First Choice",
  ["subText"] = "This is the subtext of the first choice",
  ["uuid"] = "0001"
 },
 { ["text"] = "Second Option",
   ["subText"] = "I wonder what I should type here?",
   ["uuid"] = "Bbbb"
 },
 { ["text"] = "Third Possibility",
   ["subText"] = "What a lot of choosing there is going on here!",
   ["uuid"] = "III3"
 },
}
local test = hs.chooser.new(completionFn):choices(choices):show()
```

...it gives me this:

<img width="809" alt="screen shot 2016-12-25 at 11 11 50 pm" src="https://cloud.githubusercontent.com/assets/22286696/21471068/b6ec1a6a-caf7-11e6-9992-ccdbd083a7af.png">

And if I use this code:

```
function completionFn(result)
	print(result)
end
local choices = {
 {
  ["text"] = "First Choice",
  ["subText"] = "This is the subtext of the first choice",
  ["uuid"] = "0001"
 },
 { ["text"] = "Second Option",
   ["subText"] = "I wonder what I should type here?",
   ["uuid"] = "Bbbb"
 },
 { ["text"] = "Third Possibility",
   ["subText"] = "What a lot of choosing there is going on here!",
   ["uuid"] = "III3"
 },
}
local test = hs.chooser.new(completionFn):choices(choices):bgDark(true):show()
```

...it gives this this:

<img width="805" alt="screen shot 2016-12-25 at 11 13 28 pm" src="https://cloud.githubusercontent.com/assets/22286696/21471074/d4dad87c-caf7-11e6-9019-3649685ca768.png">

I have attached both the "old" and "new" `hs.chooser` files used above in the below ZIP file for your reference:

[choosers.zip](https://github.com/Hammerspoon/hammerspoon/files/672181/choosers.zip)

Maybe something is going wrong when I'm building Hammerspoon?

Any ideas @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
Hammerspoon 0.9.51 seems to fix the issue I was having! Something must have been going funky when I built the latest Hammerspoon code using `rebuild.sh`. I'm still having an issue described above, but I'll put that in a new issue to avoid confusion.
