### ISSUE TITLE
Sierra repeat key randomly stopping

### ISSUE THREAD

**Issue by MichaelHindley** [Hammerspoon/hammerspoon#1156]
Using the below script,if holding J for Up or K for down, and navigating a text file, the cursor and event will randomly stop firing.  
Sometimes after just 3-4 lines, other times it can go over 50 lines.
Pressing the key again re-engages it.

I have tried experimenting with different `event`declarations, as well as usleep values.

I have also tried the code from here https://github.com/Hammerspoon/hammerspoon/issues/1011#issuecomment-261114434,  it results in the same issue.

This is on Sierra.

```lua
local function keyCode(key, modifiers)
    modifiers = modifiers or {}

    return function()
        local event = require("hs.eventtap").event
        event.newKeyEvent(modifiers, key, true):post()
        hs.timer.usleep(100)
        event.newKeyEvent(modifiers, string.lower(key), false):post()
    end
end


hs.hotkey.bind({''}, 'j', keyCode('up'), nil, keyCode('up'))
hs.hotkey.bind({''}, 'k', keyCode('down'), nil, keyCode('down'))
```

**Comment by asmagill** [comment]
I don't know if it's a change in macOS, but lately I've been having better luck with code like this (modify `trigger-modifiers`, `trigger-key`, `desired-modifiers`, and `desired-key` as appropriate):

~~~lua
h = hs.hotkey.bind({trigger-modifiers}, "trigger-key", function()
    hs.eventtap.event.newKeyEvent({desired-modifiers}, "desired-key", true):post()
end, function()
    hs.eventtap.event.newKeyEvent({desired-modifiers}, "desired-key", false):post()
end, function()
    hs.eventtap.event.newKeyEvent({desired-modifiers}, "desired-key", true):setProperty(hs.eventtap.event.properties.keyboardEventAutorepeat, 1):post()
end)
~~~

This approach doesn't try to force both the keyDown and keyUp into the same hotkey trigger for down and repeat, but rather spreads them across the actual trigger key being pressed, repeated, and released... each "state" of the hotkey matches exactly one created "event" rather than trying to fit two events into the same hotkey action.

**Comment by MichaelHindley** [comment]
@asmagill thanks, with your code, the issue occurs less frequently, I'd say about 30% less, but does still very much occur practically all the time, for example when holding up/down when navigating code in Intellij, Visual Studio Code or just plain text in Word.

**Comment by MichaelHindley** [comment]
After restarting hammerspoon, the issue does not occur at all for a few minutes. Going to give it a few days with a barebone up / down bound config only setup to see if anything else I might have is somehow affecting the binds.

**Comment by MichaelHindley** [comment]
So I found out that this problem only exists for Up, Down, Left and Right keycodes.

With the below code, holding "p" will randomly stop, sometimes after just 4 lines in a text editor, sometimes after 100.

Replacing "up" to a character, like "b", it will never stop, it will keep repeating without fault.
```lua
h = hs.hotkey.bind({}, "p", function()
    hs.eventtap.event.newKeyEvent({}, "up", true):post()
end, function()
    hs.eventtap.event.newKeyEvent({}, "up", false):post()
end, function()
    hs.eventtap.event.newKeyEvent({}, "up", true):setProperty(hs.eventtap.event.properties.keyboardEventAutorepeat, 1):post()
end)
```

**Comment by edanm** [comment]
@MichaelHindley 
Have you ever gotten to the bottom of this problem?

I have the same issue, and it also seems to stop for a while when restarting Hammerspoon.

**Comment by MichaelHindley** [comment]
@edanm sadly not, I have filed a issue after more investigation in regards to Up, Down, Left and Right keys, since I only get this behaviour on those, since this issue is now misleading, I suggest it is closed.

#1308 is the new issue

**Comment by edanm** [comment]
Hey,

Unfortunately, after a bit of testing, I think this bug *does* happen even with characters, not just the arrow keys. I tried to change one of my standard arrow key mappings to "r", and after a few hours, it *also* stopped repeating after ~6 repeats.

It did take far longer for the bug to start than with the arrow keys, though.

**Comment by trzeciakp** [comment]
Has it been fixed? I've upgraded hammerspoon to 0.9.54 but I still experience the issue.

**Comment by edanm** [comment]
@trzeciakp This hasn't been fixed to my knowledge, I've always experienced this issue on all Hammerspoon versions I've tried.

**Comment by MichaelHindley** [comment]
It has stopped occurring for me with the 0.9.55 update!

**Comment by cmsj** [comment]
Very odd! Anyone else have info on whether this is still happening?

**Comment by cmsj** [comment]
I'm going to close this out for now. Please feel free to re-open it if you are still getting this issue.
(Also I'm going to remind people that for keyboard remapping, Karabiner Elements is now really good, and is much better placed to remap things, than Hammerspoon is)
