### ISSUE TITLE
i18n Library for Hammerspoon?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1158]
[This](https://github.com/kikito/i18n.lua) might be a good addition to Hammerspoon?

**Comment by asmagill** [comment]
no objections from me

**Comment by cmsj** [comment]
For me this falls right on the line of whether it's appropriate for us to include, or if interested people should use luarocks. I think I'd like to figure out how it would integrate with Hammerspoon (e.g. how would we figure out where to load translations from, particularly for a third party module) and whether anyone is interested in doing translation work for our/other modules.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as you're probably right - it's not something that necessarily needs to be added to the Hammerspoon core.
