### ISSUE TITLE
Add rebuild.sh to Master

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1160]
So that I don't have to manually copy and paste it each time I download the Hammerspoon source code, any chance of adding [rebuild.sh](https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md) to the Master, so I can just run that to build a local copy? Thoughts @cmsj & @asmagill ?

**Comment by latenitefilms** [comment]
Also, [rebuild.sh](https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md) doesn't seem to work on the latest Master code. It fails to build for me, whereas all previous version have worked fine. Maybe related to those Ruby discussions you were having elsewhere?

**Comment by latenitefilms** [comment]
Ignore me... apparently `rebuild.sh` doesn't like spaces in folder names! Working fine now!

**Comment by latenitefilms** [comment]
Thanks @cmsj !

**Comment by latenitefilms** [comment]
Thanks @cmsj - although `rebuild.sh`still seems to be missing from **Master**?

**Comment by latenitefilms** [comment]
@cmsj - FYI: I don't think the paths are setup correctly when `rebuild.sh` is in the scripts subdirectory? Moving the script into the root directory however seems to work.

**Comment by cmsj** [comment]
@latenitefilms it should work fine if you're in the root directory and run `./scripts/rebuild.sh`

**Comment by latenitefilms** [comment]
Ah, right! That makes sense! Thanks @cmsj - apologies for the stupid question!
