### ISSUE TITLE
hs.chooser needs to be recreated when changing Reduce Transparency

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1162]
If you change the **Reduce transparency** option in Accessibility System Preferences whilst Hammerspoon is running with a `hs.chooser` already created, the only way to make the chooser look "right" is by creating a new one via `hs.chooser.new()`.

This is what it looks like if you change the **Reduce transparency** option "mid-session":

<img width="845" alt="screen shot 2016-12-26 at 2 16 01 pm" src="https://cloud.githubusercontent.com/assets/22286696/21474593/e4ddd5de-cb75-11e6-9781-5ea4f9a6926e.png">

This is my workaround - but would be good to solve in `hs.chooser` at some point:

```
function hacksconsole.new()

	hacksconsole.hacksChooser = chooser.new(hacksconsole.completionAction):bgDark(true)
											           				 	  :rightClickCallback(hacksconsole.rightClickAction)
											        				 	  :choices(hacksconsole.choices)

	local reduceTransparency = screen.accessibilitySettings()["ReduceTransparency"]
	hacksconsole.reduceTransparency = reduceTransparency
	if reduceTransparency then
		hacksconsole.hacksChooser:fgColor(nil)
								 :subTextColor(nil)
	else
		hacksconsole.hacksChooser:fgColor({alpha = 1, blue = 0.98, green = 0.98, red = 1.0})
								 :subTextColor({alpha = 1, blue = 0.98, green = 0.98, red = 1.0})
	end

end

function hacksconsole.show()

	local reduceTransparency = screen.accessibilitySettings()["ReduceTransparency"]
	if reduceTransparency ~= hacksconsole.reduceTransparency then
		hacksconsole.new()
	end

	hacksconsole.hacksChooser:show()

end
```

**Comment by cmsj** [comment]
I'd like to know more about why that setting would be changed while a chooser is in use - it is possible for us to subscribe to a notification that the setting has changed, but I'm not currently sure why anyone would be changing that setting often enough that this would be an issue - you either need transparency reduced for Accessibility reasons or you don't?

Or am I missing something? :)

**Comment by latenitefilms** [comment]
Good question! I'm not really sure why you would change the **Reduce transparency** setting mid-session (to be honest, I didn't even know this option existed until you told me about it!) - however, the person who originally had the issue with `hs.chooser`, did change the setting with Hammerspoon running (as they have Hammerspoon running on startup). I guess that's the only concern - that a lot of people will just always have Hammerspoon running, so if they do change this setting, chances are Hammerspoon will be already running, they might not think to restart it if the chooser goes a bit funky?

However, the above code in my previous post gets around the issue, so it's not a problem if you don't want to mess any further with `hs.chooser`. Will leave up to you - feel free to close this issue if you want. Thanks @cmsj !
