### ISSUE TITLE
Assigning Two Results to the Same Key 

### ISSUE THREAD

**Issue by akivascript** [Hammerspoon/hammerspoon#1168]
I'm trying to repurpose my CAPS LOCK key to be ESCAPE if pressed and released and CTRL when pressed and held. Is there a way to get `hs.eventtap.keyStroke()` to pass through whatever character CTRL is being chorded with? Something like...

```
if hs.eventtap.checkKeyboardModifiers().ctrl then
  hs.eventtap.keyStroke({'ctrl'}, ???)
else
  hs.eventtap.keyStroke({}, 'escape')
  hs.alert.show('escape')
end
```

**Comment by Peeja** [comment]
Are you in an event tap responding to an event at this point? You should be able to use [`event:getCharacters()`](http://www.hammerspoon.org/docs/hs.eventtap.event.html#getCharacters) to get the character you need.

**Comment by cmsj** [comment]
I'm going to close this because I feel quite strongly that Karabiner Elements is the correct tool for remapping keyboard stuff, now that it can do things like this. We operate far too high up the OS stack to be able to do a smooth job of this sort of thing. Sorry!

**Comment by Peeja** [comment]
@cmsj Ooh, that's awesome. Thanks for the heads up!
