### ISSUE TITLE
Add User Locale to hs.host?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1170]
Something as simple as this?

```
function host.userLocale()
	local a, userLocale = osascript.applescript("return user locale of (get system info)")
	return userLocale
end
```

**Comment by asmagill** [comment]
I'm going to do one better... I have some code snippits that return most of the info that an NSLocale object contains, so I'll add `hs.host.locale` as a submodule allowing you to get at this for the current or an arbitrary locale.  Should be up for testing later today.

**Comment by asmagill** [comment]
If there is interest, I'll turn it into a pull tomorrow; otherwise I *could* just reduce it down to the single query you've asked for 😜... it's at https://github.com/asmagill/hammerspoon_core/tree/master/locale if you want to take a look sooner.

**Comment by latenitefilms** [comment]
This is PERFECT! Thanks so much @asmagill for all your endless hard work and support!

Works great! This is definitely something I think should be added to the Hammerspoon core!

**Comment by cmsj** [comment]
@asmagill are we able to set the locale somehow?

**Comment by asmagill** [comment]
To my knowledge there is no programmatic interface to changes the users current locale... certainly not in the NSLocale class which is most of what the submodule is based on.  If you know of one I'm fine with adding it, but a quick google search didn't turn anything up that was immediately promising, so...

I hope to have this up as a pull request later tonight or tomorrow.

**Comment by latenitefilms** [comment]
> To my knowledge there is no programmatic interface to changes the users current locale... certainly not in the NSLocale class which is most of what the submodule is based on. If you know of one I'm fine with adding it, but a quick google search didn't turn anything up that was immediately promising, so...

@cmsj - If you really wanted this functionality, you could do it via Terminal comments (or via a [future Preferences extension](https://github.com/Hammerspoon/hammerspoon/issues/1130#issuecomment-266266474)):

https://macmule.com/2011/03/02/setting-user-os-language-post-install-from-casper/

**Comment by cmsj** [comment]
definitely don't want to have us calling out to terminal commands. If it can't be done neatly in code, so be it :)
