### ISSUE TITLE
Implement a beta release stream

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1171]
As has come up more than once previously (most recently in #1140), we have released with at least one user-facing regression.

Our progress on a comprehensive test-suite has completely stalled, and even if we did have a very large selection of unit tests, we've had the UI testing disabled for a long time because it was unreliable.

So, it seems likely to continue to be the case that our best testing apparatus is humans.

With that in mind, here are some thoughts about what would be needed to run a beta release stream that users could elect to follow

Changes to Hammerspoon:
 * [ ] GUI option in Preferences window for using Beta releases
 * [ ] Above option would change the SUUpdate URL at runtime (it's normally read from Info.plist)

Changes in release workflow:
There are two options here - one blocks master while a release is in beta, the other does not.

Master blocker:
 * [ ] when releasing a new beta, a release is built from master, uploaded and added to the beta appcast.xml. master is now closed to feature work.
 * [ ] as regressions are identified and fixed, new beta releases are built/uploaded
 * [ ] when everyone is happy, master is tagged with the final release number, and a full release is made
 * [ ] master re-opens for feature work

Master non-blocker:
 * [ ] when releasing a new beta, a branch is created with the target version number
 * [ ] a release is built, uploaded and added to the beta appcast.xml
 * [ ] as regressions are identified, they are fixed in master and cherry-picked onto the version branch
 * [ ] when everyone is happy with the state of the beta release, the release branch is tagged and a full release is made

There is also a third option where master only ever records the results of feature branches, and all feature work always happens on a `develop` branch. This feels to me like it's getting out of control for the size/scope of our project though!

I tend to think that the Master Blocker option is probably best for us - for one thing it's less complexity, and it's also going to put pressure on us to get from beta->final quickly, because we can't land anything but bugfixes in that period.

There is also one entirely different option here, which would be for there to be a Nightly channel, which gets a fresh release every day if there have been any commits. This has the advantage that it doesn't change the release workflow at all, and it can be fully automated.

What are peoples' thoughts here? Does anyone want to enthusiastically volunteer to always run the beta channel and give swift feedback if we've broken something? (That's my biggest concern here - if we can release with regressions because we're not using 100% of the API ourselves, that will still potentially be true even with beta releases).

**Comment by cmsj** [comment]
I've started investigating what would be necessary for signed nightly builds, generated automatically by Travis, with help from https://www.objc.io/issues/6-build-tools/travis-ci/

**Comment by latenitefilms** [comment]
Awesome! Thanks @cmsj - personally, I think nightly builds would be awesome.

**Comment by cmsj** [comment]
This didn't end up going anywhere, and our development velocity isn't (imho) significant enough at the moment to justify spending more time on it, so I'm closing this issue.
