### ISSUE TITLE
Dvorak Programmer keyboard layout act error

### ISSUE THREAD

**Issue by shuxiao9058** [Hammerspoon/hammerspoon#1176]
I use Dvorak Programmer keyboard layout.
Some configure of hs like this:

```
hyper = { "alt" }

-- Lock System
hs.hotkey.bind(hyper, 'Q', 'Lock system', function() hs.caffeinate.lockScreen() end)
```

But `Alt+;` do lock system action and `Alt+Q` do nothing at all(with dvorak programmer layout).

**Comment by cmsj** [comment]
The keyboard maps in macOS always go by what is printed on the key, so regardless of the layout I think you should bind to what is printed on the key.
