### ISSUE TITLE
Feature Request - Better AppleScript/Automator Integration

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1177]
It would be amazing if Hammerspoon had better integration with AppleScript & Automator.

For example, it would be amazing if Hammerspoon had it's own AppleScript Dictionary, and if you could manipulate this dictionary via LUA code.

For example, the Terminal App has it's own "Terminal Suite" of AppleScript commands, such as `do script`. What I would like to do is use Hammerspoon to define my own set of AppleScript Commands, which trigger LUA functions.

That way, I could build up my own Automator workflows in Automator, but they actually really just trigger Hammerspoon functions.

Is this remotely possible? @cmsj or @asmagill ?

**Comment by nikitavoloboev** [comment]
Yeah I wold really love to have something like [external triggers](https://www.alfredapp.com/help/workflows/triggers/external/) in hammer spoon. Right now the only way to call lua bindings from hammer spoon is using hotkeys.

**Comment by latenitefilms** [comment]
@nikitavoloboev - You can actually tell Hammerspoon what to do via [URL events](http://www.hammerspoon.org/docs/hs.urlevent.html), or [CLI](http://www.hammerspoon.org/docs/hs.ipc.html) as well, but I do think an AppleScript interface would be really handy too.

**Comment by cmsj** [comment]
I like the idea of this, although before people get too excited, I would note that the AppleScript dictionary for an app has to be defined statically as an XML file in the .app bundle, and is fairly rigid, so we'll have to do something pretty much exactly like `hs.urlevent` - we'll offer up a single AppleScript command (maybe `trigger` :) and it will have to take probably just one string argument, possibly with URL encoding so it can be split up later. I haven't looked at how return values work, but again I think the declaration is pretty static ahead of time, so we may just have to return a string and the  user can decide what they want to pack into it.

**Comment by latenitefilms** [comment]
@cmsj - Maybe this is TOO crazy, but I was thinking we could just manipulate the dictionary files that are WITHIN the Hammerspoon bundle? For example, if I wanted to add a new AppleScript Action to the Dictionary, we could just modify the `.scriptSuite` and `.scriptTerminology` XML files within the Application Bundle to add this new Action.

However, if modifying the contents of the Hammerspoon Bundle is getting too dodgy, then I'd be happy with just having some un-changable Hammerspoon AppleScript Commands.

Maybe something like like this to start...

```
Hammerspoon Suite > application > triggerFunction([globalFunction])
Hammerspoon Suite > application > getValue([globalValue])
```

...then eventually implement some of the other standard Hammerspoon functions into AppleScript functions, for example:

```
Hammerspoon Suite > application > configdir
Hammerspoon Suite > application > processInfo
Hammerspoon Suite > application > autoLaunch([true | false])
```

Thoughts?

**Comment by cmsj** [comment]
I honestly have no idea what happens if you modify the dictionary files in an already-installed app, but I think that would be fairly hacky and not the way to go.

I think a solid first step here would be a really simple "run this arbitrary snipped of Lua and return a string"

**Comment by latenitefilms** [comment]
Note to self: https://www.objc.io/issues/14-mac/scripting-data/
