### ISSUE TITLE
down/up arrow event not working for google search box

### ISSUE THREAD

**Issue by AndreGeng** [Hammerspoon/hammerspoon#1183]
I have mapped ctrl-hjkl to arrow keys. it works everywhere except for google search box. I would like to use ctrl-j & ctrl-k to navigate between search suggestions, but now when I hit ctrl-j/ctrl-k nothing happens(by the way ctrl-h/ctrl-l works normally)

below is the lua script for those mappings.

````
local fireArrowKey = function(configItem)
  return function()
    hs.eventtap.event.newKeyEvent({}, string.lower(configItem.direction), true):post()
  end
end
hs.fnutils.each({
  {key='h', mod={'ctrl'}, direction='left'},
  {key='l', mod={'ctrl'}, direction='right'},
  {key='j', mod={'ctrl'}, direction='down'},
  {key='k', mod={'ctrl'}, direction='up'}
}, function(configItem)
  local arrowRemappings = hs.hotkey.bind(configItem.mod, configItem.key, fireArrowKey(configItem), nil, fireArrowKey(configItem))
end)
````

Do you guys have any idea why this is happening?

**Comment by AndreGeng** [comment]
by the way navigation between those search suggestion using the original down/up arrow key works and I also try using ctrl-j/ctrl-k on other websites' search box, and it also works. Seems just do not work for google search box, do not know why this is happening..

**Comment by asmagill** [comment]
I'm not sure what Google is doing differently, but one thought that comes to mind is that you're not issuing a "keyUp" event for the remapped arrow key in your code...  you might try adding `hs.eventtap.event.newKeyEvent({}, string.lower(configItem.direction), false):post()` as the second line in the returned function of `fireArrowKey`.

You might also take a look at https://github.com/Hammerspoon/hammerspoon/issues/1128#issuecomment-266104051 which shows a vi-key wrapper that uses only `hs.eventtap` and ignores `hs.hotkey` entirely... I've had good luck with this code (actually, a variant of it that is linked to in a later comment of that thread).

**Comment by AndreGeng** [comment]
@asmagill Thanks very much for your reply. After adding the "keyUp" event, it works now. awesome:)  I am closing this
