### ISSUE TITLE
Issues using Hammerspoon and TextExpander

### ISSUE THREAD

**Issue by pdoak** [Hammerspoon/hammerspoon#1188]
I have just started using Hammerspoon and have noticed that when Hammerspoon is running, it disables TextExpander snippets. However, if I bring TextExpander to the front and then switch back to whatever application that I was using and invoke the snippet again, it works. 

Is anyone else experiencing this problem and if so, is there a way to get Hammerspoon and TextExpander working in harmony?

Many thanks

Paul

**Comment by latenitefilms** [comment]
@pdoak - Curious, and slightly off-topic, but does your Hammerspoon config make use of hotkeys? If so, have you noticed any performance issues (i.e. keyboard lagging) with running Hammerspoon & TextExpander on the machine?

**Comment by pdoak** [comment]
It's interesting that you say that. In one application, I have noticed some lag but thought it was due to that one application. I haven't noticed it generally, though.

**Comment by pdoak** [comment]
I have noticed that the issue arises when a snippet trigger comes directly after a return key press. In this situation, the expansion does not fire. If I press the up and down arrow key( to get the cursor in the same position) the expansion works.

**Comment by cmsj** [comment]
What are you doing in your Hammerspoon config? We shouldn't be blocking TextExpander
