### ISSUE TITLE
Validation Extension?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1191]
Another thing that could be a REALLY handy addition to Hammerspoon is a proper validation extension.

Maybe something like:

- https://github.com/bungle/lua-resty-validation
- https://github.com/sailorproject/valua

Thoughts?

**Comment by cmsj** [comment]
What sort of use case are you thinking about here? I don't immediately feel like there is any direct relevance here with automating macOS - at the moment these things would fall on the "if someone wants this, there's luarocks" spectrum for me.

**Comment by latenitefilms** [comment]
I just think it would be handy to have some built-in validation tools, in the same way that having built-in utility functions in [hs.fnutils](http://www.hammerspoon.org/docs/hs.fnutils.html) is REALLY helpful.

For example, it would be great to check if a `targetAddress` is valid when using [hs.messages](http://www.hammerspoon.org/docs/hs.messages.html) given that it doesn't return anything, so you just have to ASSUME it works. Yes, I could just find some email/phone number validation code on the Internet, but I feel like this kind of validation checking is needed in a lot of Hammerspoon scripts anyway, so it would be handy to have it built in.

**Comment by cmsj** [comment]
@asmagill any thoughts here? I'm worried that we're going to turn into a general purpose Lua distribution and be responsible for keeping a bunch of different things up to date.

**Comment by asmagill** [comment]
@cmsj, I tend to agree, especially when the additions are pure lua.

**Comment by cmsj** [comment]
@latenitefilms Sorry, I'm going to close this out for now. We can revisit this in the future if/when things change, but I think I have to come down on the side of not accreting more and more third party Lua modules just because they're useful, when there are already multiple supported ways of installing them.

**Comment by latenitefilms** [comment]
No worries at all! Thanks for considering @cmsj & @asmagill !
