### ISSUE TITLE
rebuild.sh fails if source path contains a space

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1200]
As mentioned in #1160, `./scripts/rebuild.sh` will fail if the path to the Hammerspoon source folder has any spaces in it. I don't think this is a problem with the rebuild script itself - but rather something in the Xcode project that doesn't like spaces.

Not really a show-stopper - as you can just remove spaces from any folders in the path - but thought it was worth mentioning for anyone else who runs into the same issue.

**Comment by deryni** [comment]
Without seeing the error I'm going to guess that the problem is with the `rm -fr` step that tries to delete the current `Hammerspoon.app` file since the backtick-ed command to get the path isn't quoted.

Using this might work better:

    rm -fr "`xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration DEBUG -showBuildSettings | sort | uniq | grep " BUILT_PRODUCTS_DIR =" | awk '{ print $3 }'`/Hammerspoon.app"

Or, if we are changing that line already:

    rm -fr "`xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration DEBUG -showBuildSettings | awk '/ BUILT_PRODUCTS_DIR =/ { print $3; exit }'`/Hammerspoon.app"

which drops a few unnecessary pipeline components and just lets awk do the work (assuming the sort didn't change which, of multiple, `BUILT_PRODUCTS_DIR` values was found and we want the first one found).

**Comment by cmsj** [comment]
@latenitefilms do you happen to have a rebuild log showing the failure?

**Comment by cmsj** [comment]
@latenitefilms let me know if this doesn't fix the issue. Thanks @deryni for spotting that mistake in the script :)

**Comment by latenitefilms** [comment]
FYI - finally got around to testing this. The script still fails if there's a space in the path:

```
LateNite-Chris:hammerspoon 0.9.52 latenitechris$ ./scripts/rebuild.sh 
No matching processes belonging to you were found
rm -rf build
rm -rf LuaSkin.framework
mkdir -p build
echo "Building Hammerspoon in Debug configuration"
Building Hammerspoon in Debug configuration
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration Debug clean build > build/Debug-build.log
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Copy\ extensions\ to\ bundle /Users/latenitechris/Library/Developer/Xcode/DerivedData/Hammerspoon-ciglyhmjjiamyyexkzesprzdlpwq/Build/Intermediates/Hammerspoon.build/Debug/Hammerspoon.build/Script-4FBE2D161B7268DF00407788.sh
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
rm -f build/docs.sqlite
scripts/docs/bin/gensql < build/docs.json | sqlite3 build/docs.sqlite
mkdir -p build/html
rm -rf build/html/*
cp scripts/docs/templates/docs.css build/html
scripts/docs/bin/genhtml build/html < build/docs.json
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- github/markdown (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from scripts/docs/bin/genhtml:3:in `<main>'
make: *** [build/html] Error 1
build/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A: No such file or directory
build/Hammerspoon.app: No such file or directory
The file /Users/latenitechris/Downloads/hammerspoon 0.9.52/0.9.52/scripts/build/Hammerspoon.app does not exist.
```

**Comment by cmsj** [comment]
Huh. Could you dig through the build log (should be in `build/Debug-build.log` for why that `Copy extensions to bundle` script failed? (Or just attach the log here). That script is supposed to be very careful about path quoting.

**Comment by latenitefilms** [comment]
The last lines show:

```
    /bin/sh -c /Users/latenitechris/Library/Developer/Xcode/DerivedData/Hammerspoon-ciglyhmjjiamyyexkzesprzdlpwq/Build/Intermediates/Hammerspoon.build/Debug/Hammerspoon.build/Script-4FBE2D161B7268DF00407788.sh
+ /Users/latenitechris/Downloads/hammerspoon 0.9.52/scripts/copy_extensions_to_bundle.sh
/Users/latenitechris/Library/Developer/Xcode/DerivedData/Hammerspoon-ciglyhmjjiamyyexkzesprzdlpwq/Build/Intermediates/Hammerspoon.build/Debug/Hammerspoon.build/Script-4FBE2D161B7268DF00407788.sh: line 3: /Users/latenitechris/Downloads/hammerspoon: No such file or directory
```

**Comment by cmsj** [comment]
Perfect, thanks, the problem was how the script is being called. Just pushed a revision that should fix that :)

**Comment by latenitefilms** [comment]
Perfect - fixed! Thank you!
