### ISSUE TITLE
Select Keyboard

### ISSUE THREAD

**Issue by Felipeforerome** [Hammerspoon/hammerspoon#1205]
I've been looking but I haven't found a way to tell Hammespoon to only listen to keystrokes in a specific keyboard. What I mean with this is that if I press, let's say, letter A in muy  secondary keyboard it would use a eventtap to simulate certain keypress, but if I press letter A in my main keyboard, Hammerspoon would do nothing about it and the letter A would be written

**Comment by z3t0** [comment]
I think [Karabiner](http://www.hammerspoon.org/go/#karabinerurl) is the only way achieve what you want.

**Comment by xyoun** [comment]
i'm also looking for the solution, is there any API to record the key is pressed by which keyboard? 
a very nice feature is: disable internal keyboard when external keyboard is attached. 
Karabiner is not working for 10.12.

**Comment by asmagill** [comment]
If you use `hs.eventtap` to capture key events, you can check the `hs.eventtap.event.properties.keyboardEventKeyboardType` property of the key events and it may help you determine which keyboard the event came from... if I recall correctly this value is supposed to indicate the physical keyboard image that the old KeyCaps or similar apps would display, so while it probably wouldn't distinguish between two keyboards of the exact same type, it should be sufficient when comparing say a laptop keyboard to an external USB one.

Unfortunately at this time there is no tie-in between `hs.hotkey` and `hs.eventtap`, so you'd basically have to write your own hotkey detection/execution code around `hs.eventtap`.  I'm hoping to change this in the future and merge the two somewhat, but have no eta at the moment.

**Comment by cmsj** [comment]
Yeah the API that hs.hotkey uses has no way to distinguish between which input device a hotkey came from. Maybe we can improve this with the `hs.eventtap` version that @asmagill mentioned, but until then, I'm afraid it's not possible. Sorry!

(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by latenitefilms** [comment]
This might be helpful for anyone who stumbles upon this issue:

http://www.usboverdrive.com/USBOverdrive/Information.html
