### ISSUE TITLE
hs.json.decode doesn't ignore comments?

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1206]
I'll take a look at fixing this if its an issue, just wanted to add it to the tracker.

**Comment by cmsj** [comment]
Do you have some more information on this? If there is a bug it would be good to get it fixed, but at least some test data to reproduce it, would be helpful.

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
