### ISSUE TITLE
hs.hotkey should have a delete all

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1207]
There should be a function that deletes all key bindings without needing to be given parameters? Probably would just be a wrapper around the existing function with all the possible parameters.

**Comment by cmsj** [comment]
It's not a bad idea, we can certainly look at this for a future release.

One option you might look into, is using `hs.hotkey.modal` - that lets you collect hotkeys into a group which can be activated/deactivated, thereby turning all of them on/off at once.

Is that suitable for your needs?

**Comment by z3t0** [comment]
I will certainly take a look at that. Do you know if reloading hammerspoon using the example in getting started deletes key bindings?

**Comment by cmsj** [comment]
Yes reloading should destroy all state that was created by the previous config. We literally destroy the entire Lua environment and recreate it.

**Comment by z3t0** [comment]
Ah okay, in that case my purpose is already being served 😄 

I would recommend keeping this issue open however as I will take a look at adding a deleteAll function

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
