### ISSUE TITLE
window.frame.y is reversed

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1208]
I think this might be a misunderstanding on my part, but following the code from Getting Started:
```lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "J", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()

  f.y = f.y + 10
  win:setFrame(f)
end)
```

It would seem that adding to f.y causes the window to go down, instead of up? Is there a reason for t his design choice or is it just a bug?

**Comment by aldur** [comment]
Due to historical reasons, modern computers have the origin of their screen coordinate system on the top left corner. [More info here](https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html).

**Comment by cmsj** [comment]
@z3t0 I'd love to say there was a perfectly logical reason for that choice, but the reality is that I chose to make Hammerspoon treat the top left as 0,0 because I prefer it :)
