### ISSUE TITLE
next window in expose

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1209]
I am trying to figure out how I can switch between windows in an orderly fashion and was thinking of the alt-tab functionality by expose. Is there any API for doing something like this or any suggestions? Thanks

**Comment by cmsj** [comment]
@z3t0 I'm not sure I understand what you're looking for here. Are you wanting to build your own window switcher? We do have `hs.expose` which works a little like macOS's Exposé feature, but there are certainly lots of things you can use to build your own (`hs.window` and `hs.drawing`/`hs.canvas` come to mind).
