### ISSUE TITLE
Add named pasteboards to hs.pasteboard

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#121]
see methods like: https://developer.apple.com/library/Mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSPasteboard_Class/index.html#//apple_ref/occ/clm/NSPasteboard/pasteboardWithName:

this gives people lots of flexibility to paste text into apps without disrupting the user's default pasteboard.

**Comment by sclarke** [comment]
@cmsj: is it possible to paste the contents of a named pasteboard?

**Comment by latenitefilms** [comment]
@sclarke - Yes, you can use `hs.pasteboard.getContents([name])` to get the contents of a named pasteboard. See: http://www.hammerspoon.org/docs/hs.pasteboard.html#getContents
