### ISSUE TITLE
Slow repeat rate: hs.eventtap.event.newKeyEvent

### ISSUE THREAD

**Issue by aristidesfl** [Hammerspoon/hammerspoon#1211]
I'm using Karabiner to increase the key repeat rate.

![screen shot 2017-01-24 at 14 27 01](https://cloud.githubusercontent.com/assets/208149/22247232/60b5c87e-e241-11e6-97ad-b838b3c7e0d4.png)

For some reason Hammerspoon KeyEvents are slower even without `hs.timer.usleep`.
Is it possible to increase the rate further?

### Example code

```
local function keyCode(key, modifiers)
  modifiers = modifiers or {}

  return function()
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), true):post()
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), false):post()
  end
end


hs.hotkey.bind({'ctrl'}, 'j', keyCode('left'), nil, keyCode('left'))
hs.hotkey.bind({'ctrl'}, 'k', keyCode('down'), nil, keyCode('down'))
hs.hotkey.bind({'ctrl'}, 'i', keyCode('up'), nil, keyCode('up'))
hs.hotkey.bind({'ctrl'}, 'l', keyCode('right'), nil, keyCode('right'))
```

**Comment by cmsj** [comment]
I don't think you're going to be able to get faster than that code. We use the system key repeat time for calling the `repeatfn` callback, but I don't know if Karabiner's repeat time is separate from the macOS one.
I do think you'd get better performance if you remapped the keys with Karabiner though, since that is happening inside the kernel and isn't bouncing back and forth between C and Lua.

**Comment by aristidesfl** [comment]
@cmsj I'm trying to port a few modes I using with Karabiner to HammerSpoon since Karabiner doesn't work on macOS. Should I open a new ticket to request a way to increase the repeat rate above what is available in the system?

**Comment by cmsj** [comment]
@aristidesfl fwiw, Karabiner Elements is the rewrite of Karabiner for Sierra. It's not feature complete yet, but I believe it does include keyboard repeat rate settings. You might want to take a look at that :)

**Comment by aristidesfl** [comment]
@cmsj thanks, I'm aware of Karabiner Element status otherwise wouldn't be trying to implement this with hammerspoon. Also have contributed with some code for Karabiner (Homerow and Tabmode). As far as I remember and can read from the docs, karabiner elements doesn't yet support keyboard repeat rate modification. It is overall quite limited and there is no estimate for when the features from Karabiner will be implemented. Either way the problem is the same. Hammerspoon has a limit on the key repeat rate, and it would be desirable to change it, either in its own settings, or using karabiner. Neither of those is possible at the moment.
