### ISSUE TITLE
win.setSize() produces unreliable results?

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1212]
I am trying to resize a window but for some reason calling setSize() does not set the size as expected. Instead calling it several times eventually allows it to work.

example code:
```lua
local win = hs.window.focusedWindow()
local f = win:frame()
size = {}
size.w = 1500
size.h = 1000
win:setSize(size) -- calling this makes it getting closer and closer to the set size each time ...
```

**Comment by z3t0** [comment]
Interestingly the issue is resolved when using `win:setFrame()` so perhaps my understanding of the two is incorrect?

**Comment by cmsj** [comment]
Is the window near the dock or a screen edge? They have a slightly magnetic effect on windows which can make them hard to resize by small amounts

**Comment by z3t0** [comment]
Ah yes that was the issue.
