### ISSUE TITLE
Option to customise key repeat rate.

### ISSUE THREAD

**Issue by aristidesfl** [Hammerspoon/hammerspoon#1216]
Hammerspoon KeyEvents repeat rate is bound to the key repeat rate set in the System Preferences.

![screen shot 2017-01-30 at 00 05 07](https://cloud.githubusercontent.com/assets/208149/22408807/c72a2608-e67f-11e6-8b99-a402e32f7dd7.png)

That means that if you customise the key repeat rate with Karabiner, the key repeat rate of keys mapped with Hammerspoon, is going to be different than the repeat rate set with Karabiner.

![screen shot 2017-01-24 at 14 27 01](https://cloud.githubusercontent.com/assets/208149/22408800/ac8d1300-e67f-11e6-9bfd-e4c75e6c2a22.png)

On the other hand Karabiner doesn't support macOS Sierra, so there is no way to increase the key repeat rate going forward. 

Would it be technically feasible to have a global or newKeyEvent option, that lets the key repeat rate be increased further?

---------

Example application
```lua
local function keyCode(key, modifiers)
  modifiers = modifiers or {}

  return function()
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), true):post()
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(key), false):post()
  end
end


hs.hotkey.bind({'ctrl'}, 'j', keyCode('left'), nil, keyCode('left'))
hs.hotkey.bind({'ctrl'}, 'k', keyCode('down'), nil, keyCode('down'))
hs.hotkey.bind({'ctrl'}, 'i', keyCode('up'), nil, keyCode('up'))
hs.hotkey.bind({'ctrl'}, 'l', keyCode('right'), nil, keyCode('right'))
```

**Comment by cmsj** [comment]
@aristidesfl I'm not 100% sure if it's wired up to anything, but the prefs UI in Karabiner Elements has options for setting the keyboard repeat rate, and works on macOS Sierra. We could look at adding some API for controlling Hammerspoon's repeat rate, but I'd like to know how things sit with Karabiner Elements first.

**Comment by aristidesfl** [comment]
@cmsj I can't find the options for setting the keyboard repeat rate in Karabiner Elements. Can you share a screenshot?

**Comment by cmsj** [comment]
hmm, for me it's in the preferences as another tab, but I am using an older, third party fork of Elements, so it may not be in the main repo yet.

**Comment by aristidesfl** [comment]
Don't see any pull requests with that feature

**Comment by aristidesfl** [comment]
It is no longer supported https://github.com/tekezo/Karabiner-Elements/issues/551

**Comment by cmsj** [comment]
Oh, damn :(

**Comment by aristidesfl** [comment]
This seems to work be working fine with hammerspoon 

```bash
defaults write NSGlobalDomain KeyRepeat -float 1.3
defaults write NSGlobalDomain InitialKeyRepeat -int 11
```

**Comment by megalithic** [comment]
@franciscolourenco could you confirm if this is still working for you?

**Comment by franciscolourenco** [comment]
@megalithic I've not used Hammerspoon for a while, but I still use those settings in macOS. I could test it if it is important.
