### ISSUE TITLE
token-crashlytics Format?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1219]
Sorry, I should be able to work this out myself, but I've failed so far.

I'm playing around with compiling my own version of Hammerspoon, and want to test out Crashlytics to see how it all works.

@asmagill or @cmsj - could you please give me an example of what `token-crashlytics` should look like? An example of `token-codesign` could also be really handy later down the line.

I've tried just having `CRASHLYTICS_API_KEY="insert-api-key-here"` in the `token-crashlytics` file, but no dice.

Again, sorry - I know it's something really simple!

**Comment by latenitefilms** [comment]
I've also tried... 

```
export CRASHLYTICS_API_KEY=x
export CRASHLYTICS_BUILD_SECRET=x
```

...but still not having much luck. Any suggestions?

**Comment by cmsj** [comment]
Apologies, I thought I'd already replied to this. The file has the format:

```
CRASHLYTICS_API_KEY=123456abcdef
CRASHLUTICS_BUILD_SECRET=123456abcdef
```

**Comment by cmsj** [comment]
And while we're doing tokens, token-codesign looks like:

```
CODESIGN_IDENTITY="Developer ID Application: Chris jones (1234ABCD)"
```

which is the name of the non-appstore mac app developer certificate I created with Apple.

token-github-release is just a bare token in the file, no variable name or anything.

Shout if you have any further problems :)

**Comment by latenitefilms** [comment]
Legend, thanks @cmsj !

I'm still having issues getting Crashlytics to work, but I'll keep playing.
