### ISSUE TITLE
Bind EJECT key

### ISSUE THREAD

**Issue by seguri** [Hammerspoon/hammerspoon#1220]
I'd like to bind EJECT key on macOS 10.12.2 but the key does not trigger keyDown event:

```lua
hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
    print('tap!')
    return false
end):start()
```

**Comment by asmagill** [comment]
The system keys do not generate traditional key-down events and need to be caught with the `NSSystemDefined`.  See the help for `hs.eventtap.event:systemKey` as well, since you'll need this to identify which system key is being pressed.

This works for some system keys and not so well for others... it depends (I think) on what system process normally handles the system key, but I haven't deduced the pattern.  I am in the process of rewriting the eventtap module so capturing some of these common cases is more like the `hs.hotkey` model, but for now, you'll have to do this the hard way.

**Comment by seguri** [comment]
Here is the code for those who stumble upon:

```lua
hs.eventtap.new({ hs.eventtap.event.types.NSSystemDefined }, function(event)
    -- http://www.hammerspoon.org/docs/hs.eventtap.event.html#systemKey
    event = event:systemKey()
    -- http://stackoverflow.com/a/1252776/1521064
    local next = next
    -- Check empty table
    if next(event) then
        if event.key == 'EJECT' and event.down then
            print('This is my EJECT key event')
        end
    end
end):start()
```

**Comment by kaidiren** [comment]
@seguri thanks!

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by laurensk** [comment]
> Here is the code for those who stumble upon:
> 
> ```lua
> hs.eventtap.new({ hs.eventtap.event.types.NSSystemDefined }, function(event)
>     -- http://www.hammerspoon.org/docs/hs.eventtap.event.html#systemKey
>     event = event:systemKey()
>     -- http://stackoverflow.com/a/1252776/1521064
>     local next = next
>     -- Check empty table
>     if next(event) then
>         if event.key == 'EJECT' and event.down then
>             print('This is my EJECT key event')
>         end
>     end
> end):start()
> ```

This works, thanks. But how can I check if another key is pressed at the same time?
I want to fire an action when I press the EJECT button and 'S' simultaneously.

**Comment by certainlyakey** [comment]
> > Here is the code for those who stumble upon:
> > ```lua
> > hs.eventtap.new({ hs.eventtap.event.types.NSSystemDefined }, function(event)
> >     -- http://www.hammerspoon.org/docs/hs.eventtap.event.html#systemKey
> >     event = event:systemKey()
> >     -- http://stackoverflow.com/a/1252776/1521064
> >     local next = next
> >     -- Check empty table
> >     if next(event) then
> >         if event.key == 'EJECT' and event.down then
> >             print('This is my EJECT key event')
> >         end
> >     end
> > end):start()
> > ```
> 
> This works, thanks. But how can I check if another key is pressed at the same time? I want to fire an action when I press the EJECT button and 'S' simultaneously.

To me only this has worked (note both handlers are not local to avoid garbage collection - otherwise i had the Eject key stopping working after every 10-20 times it was pressed):

```lua
toggleApp = function(evt)
  local appName = 'Toggl Track'
  local event = evt:systemKey()
  local next = next
  if next(event) then
    if event.key == 'EJECT' and event.down then
      local frontmostApp = hs.application.frontmostApplication()
      local frontmostAppName = frontmostApp:name()
      if appName == frontmostAppName then
        local mainWin = frontmostApp:mainWindow()
        if mainWin then
          mainWin:close()
        else
          -- Opening main window
          frontmostApp:selectMenuItem({ 'Window', 'Timer' })
        end
      else
        hs.application.launchOrFocus(appName)
      end
    end
  end
end

toggleAppTap = hs.eventtap.new({ hs.eventtap.event.types.systemDefined }, toggleApp)
toggleAppTap:start()
```

**Comment by andrewcrook** [comment]
Apple Silicon 
macOS 14.6.1 (23G93)
Hammerspoon Version 1.0.0 (6864)

```
hs.eventtap.event.types.NSSystemDefined 
```
didn’t work for me 

```
 hs.eventtap.event.types.systemDefined
```
does work
