### ISSUE TITLE
Feature Request - Add support for LetsMove?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1222]
I always like it when I download and run an Application, and it instantly asks me if I want to move the Application to the Applications folder. Maybe [LetsMove](https://github.com/potionfactory/LetsMove/) would be a good addition to Hammerspoon? Thoughts @asmagill & @cmsj ?

**Comment by asmagill** [comment]
check out hs.pathwatcher, i think you should be able to make it do what you want

**Comment by latenitefilms** [comment]
Thanks @asmagill - and yes, I COULD do this in a Lua script - however, I think it would be better if it was implemented into the Hammerspoon core app.

I guess it could be done in `extensions/hs/_coresetup/init.lua`, but it's probably better if it's done in Objective-C?

**Comment by cmsj** [comment]
I do like LetsMove, but I sort of feel like the level of user we're targetting, probably knows where to put applications, and has made a deliberate choice that we don't really need to care about.

**Comment by latenitefilms** [comment]
Sure - as an end-user who kinda knows what he's doing, I know that when I download Hammerspoon and unzip it, I SHOULD drag it from the Downloads folder to the Applications folder - but I still think it would be nice if Hammerspoon just did it for me auto-magically.

I also think it makes the application a bit more "sticky" - for example, there's lots of applications I'll download to test out, and initially just run them from the downloads folder to try them out - but sometimes I'll forget to move them across to applications, and I'll forget about them, as they're hidden away in my downloads in some random folder. Adding this feature could help users who download Hammerspoon just to check it out, but then forget about it because the application is hidden away in their downloads somewhere.

I assume LetsMove only asks the user once to move the application, so it shouldn't annoy advanced users?

Anyway... if you disagree, feel free to close this issue. All good, either way!

**Comment by junkblocker** [comment]
@latenitefilms , which Applications directory does it move to? For example, I use `~/Applications` exclusively for all the apps I install. If this is going to ask me to move the app to `/Applications/` I'd be annoyed. 

I have this impression that you are using hammerspoon as a framework to build apps for non-technical users and including changes like this would end up making hammerspoon enterprise-y and heavyweight reducing control for the current crop of intended users. Since these can be done in lua my vote would be to keep these out of core.

**Comment by latenitefilms** [comment]
@junkblocker - Yes, I assume it would ask to move it to the `~/Applications` folder.

You're absolutely right - I'm currently trying to use Hammerspoon as a framework to build apps for video editors, rather than hardcore coders. Our end-users are still pretty technical - and I'm HOPING that a lot of them will jump into the Lua code and improve upon the stuff we've done, but yeah, they're certainly not all programmers.

I'll close this issue for now, and have a play with trying to add LetsMove to a Hammerspoon fork myself.

Thanks everyone for your feedback!
