### ISSUE TITLE
Idiots guide to Crashlytics?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1226]
Sorry, I know this is not something that most (or any) other users will run into, but I'm currently experimenting with building my own fork of Hammerspoon, and I'm having trouble getting Crashlytics setup.

I've created a new Crashlytics account, and I've setup the token file correctly (as explained [here](https://github.com/Hammerspoon/hammerspoon/issues/1219#issuecomment-277969965), however, every time I try to build the "release" of Hammerspoon (using `release.sh`, but commenting out all the things I obviously can't do in `librelease.sh`, such as `release_tweet` and `release_add_to_github`), everything SEEMS to work fine, but when I look on the Crashlytics page it just says "We couldn't find your app".

Any ideas @cmsj ?

**Comment by cmsj** [comment]
@latenitefilms I'd suggest installing the Fabric app from Crashlytics, it helps add the app by having you build it in Xcode and monitoring the outcome.

**Comment by latenitefilms** [comment]
Thanks for the suggestion! I still seem to get stuck on this though:

<img width="432" alt="screen shot 2017-02-08 at 12 00 07 am" src="https://cloud.githubusercontent.com/assets/22286696/22692124/a0697794-ed91-11e6-97f2-f57b29575136.png">

**Comment by cmsj** [comment]
Are you building Hammerspoon with the release scheme in xcode? (selected next to the Play/Stop buttons on the toolbar)

**Comment by latenitefilms** [comment]
Yep, definitely in the release scheme.

**Comment by latenitefilms** [comment]
The Fabric guys have suggested enabling Debug Mode - but I'm not exactly sure where I should add this, as I can't see `[Fabric with:@[CrashlyticsKit]];` in the code anywhere?

https://docs.fabric.io/apple/fabric/advanced-settings/debugging.html

**Comment by cmsj** [comment]
@latenitefilms yeah we don't initialise crashlytics that way. See `applicationDidFinishLaunching` in `MJAppDelegate.m`. We already enable debug mode though :)

**Comment by latenitefilms** [comment]
Awesome, thanks!

However, I still can't get it to work. No idea why.

If I download the latest Hammerspoon develop, set up my own tokens for Crashlytics, then run `release.sh`, should it just work out-of-the-box?

**Comment by latenitefilms** [comment]
@cmsj - Should `hs.crash.crash()` cause something to be logged in Crashlytics?

**Comment by latenitefilms** [comment]
The answer is yes. Finally got this all working!
