### ISSUE TITLE
Feature Request - hs.dialog()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1227]
I currently use `hs.osascript.applescript()` to create things like dialog boxes, colour pickers, file browsers, etc, which works great - HOWEVER, because of [the weirdness](https://github.com/Hammerspoon/hammerspoon/issues/1178) that happens between Hammerspoon & AppleScript, I'd love to come up with something a bit more reliable. For example, when I create a dialog box, for some strange reason on Sierra, I need to click the dialog box button a few times before it actually gets clicked. Maybe it's also related to [this](https://github.com/Hammerspoon/hammerspoon/issues/1180)?

What are the chances of someone here making up a extension that allows you to create various dialog boxes using Objective-C?

These links might be relevant:

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Dialog/Tasks/UsingAlerts.html
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/UsingtheOpenandSavePanels/UsingtheOpenandSavePanels.html
https://developer.apple.com/reference/appkit/nscolorpanel

For anyone who's interested, you can see how we're doing it with AppleScript [here](https://github.com/CommandPost/CommandPost/blob/develop/src/cp/dialog/init.lua). It would be really awesome to do something similar, but use Objective-C instead.

Thoughts?

In terms of "controls" it would be amazing to be able to offer all the same functionality you currently get with AppleScript - for example:
<img width="525" alt="screen shot 2017-02-08 at 10 47 17 pm" src="https://cloud.githubusercontent.com/assets/22286696/22736059/a1f02e86-ee50-11e6-8e2e-4dbbc61e65d8.png">
<img width="525" alt="screen shot 2017-02-08 at 10 47 19 pm" src="https://cloud.githubusercontent.com/assets/22286696/22736060/a2495966-ee50-11e6-8e13-1834e3201d83.png">
<img width="525" alt="screen shot 2017-02-08 at 10 47 22 pm" src="https://cloud.githubusercontent.com/assets/22286696/22736061/a24da7f0-ee50-11e6-98a2-8767be88a93e.png">

**Comment by cmsj** [comment]
I think it's super unlikely that anyone has the time at the moment to work on something like those Dialog Maker examples, but I can see us slowly building up an `hs.dialog` with really simple single-purpose dialogs (so like a text entry one, a color picker one, a file requester one, etc).

I'm gonna close this issue, because this is covered by #337 :)

**Comment by latenitefilms** [comment]
@cmsj - Just to be clear, I'm definitely not saying we need to build interfaces like those screenshots - I'm more suggesting that these "simple" dialog boxes should have all the "controls" that the Dialog Maker shows. For example, in regards to a simple dialog box, I'd suggest something like:

`hs.ui.dialog(message, [title])`
**Parameters:**
`message` - What message the dialog box displays
`title` - Optional custom title for the dialog box

**Example:**
<img width="532" alt="screen shot 2017-02-11 at 2 01 28 am" src="https://cloud.githubusercontent.com/assets/22286696/22831323/0759e4e8-effe-11e6-994a-ee582574ea77.png">

`hs.ui.dialog(message, [title], [textEntry], [defaultAnswer], [icon])`
**Parameters:**
`message` - What message the dialog box displays
`title` - Optional custom title for the dialog box
`textEntry` - true, false or "secure"
`icon` - path to icon (or maybe even `hs.drawing`)

**Example:**
<img width="532" alt="screen shot 2017-02-11 at 2 06 35 am" src="https://cloud.githubusercontent.com/assets/22286696/22831548/dbb3a788-effe-11e6-9d7e-f25e26ceb967.png">

`hs.ui.dialog(message, [title], [textEntry], [defaultAnswer], [icon], [customButton1], [customButton2], [customButton3], [defaultButton], [cancelButton], [timeout])`
**Parameters:**
`message` - What message the dialog box displays
`title` - Optional custom title for the dialog box
`textEntry` - true, false or "secure"
`icon` - path to icon (or maybe even `hs.drawing`)
`customButton1` - string for custom button one
`customButton2` - string for custom button two
`customButton3` - string for custom button three
`defaultButton` - which button is highlighted by default
`cancelButton` - which button is triggered when you cancel
`timeout` - nil or a value in seconds for how long the dialog displays before timing out

**Example:**
<img width="577" alt="screen shot 2017-02-11 at 2 10 35 am" src="https://cloud.githubusercontent.com/assets/22286696/22831665/4b268fb8-efff-11e6-92b5-59a2fdce09a6.png">

`hs.ui.list(items, [title], [prompt], [defaultItems], [multipleSelection], [emptySelection])`
**Parameters:**
`items` - a table of strings
`title` - title as a string
`prompt` - message as a string
`defaultItems` - a table of default items (must be same values as `items`)
`multipleSelection` - true or false
`emptySelection` - true or false

**Example:**
<img width="452" alt="screen shot 2017-02-11 at 2 15 14 am" src="https://cloud.githubusercontent.com/assets/22286696/22831842/f3aed910-efff-11e6-9a9b-3ee733045eb5.png">

`hs.ui.file([customPath], [prompt], [restrictFileTypes], [showInvisibleFiles], [multipleSelection], [packageContents])`
**Parameters:**
`customPath` - path as string, otherwise defaults to `~/Desktop`
`prompt` - custom prompt as string
`restrictFileTypes` - table of restricted file types
`showInvisibleFiles` - true or false
`multipleSelection` - true or false
`packageContents`- true or false

Does that make sense?
