### ISSUE TITLE
hs.urlevent.openURLWithBundle in latest stable chrome on OSX doesn't work correctly

### ISSUE THREAD

**Issue by ryanseddon** [Hammerspoon/hammerspoon#1228]
OS: OSX 10.11.6
Hammerspoon: 0.9.52
Chrome: Version 56.0.2924.87 (64-bit) Stable

When trying to open a URL with `hs.urlevent.openURLWithBundle(url, bundleID)` in Chrome it opens a new chrome window and not a tab like it used to do in the current active chrome window. It also doesn't actually pass the url and just has a blank new window. Chrome canary works fine, same with Firefox and Safari.

I'm not sure what the last Chrome stable version was that worked correctly.

**Comment by junkblocker** [comment]
Works for me on latest OSX (10.12.3) and Hammerspoon (0.9.52 - or rather HEAD) with same version of Chrome.

```lua
hs.urlevent.openURLWithBundle('https://www.google.com', 'com.google.Chrome')
```

**Comment by ryanseddon** [comment]
![hammerspoon-openurl](https://cloud.githubusercontent.com/assets/143402/22761862/b733df12-eeb0-11e6-8156-0e473660191a.gif)

Here's a screencap of the behaviour I'm seeing.

**Comment by cmsj** [comment]
hmm, I also can't reproduce this with current macOS/Chrome/Hammerspoon.

@ryanseddon can you try using the `open` command in the Terminal app? Something like:

`open -b com.google.Chrome https://www.google.com`

**Comment by ryanseddon** [comment]
Yep so turns out after a reboot everything is back to normal. One day I file an issue that is actually useful, sorry.
