### ISSUE TITLE
hs.eventtap.event.newKeyEvent gets caught by hs.hotkey.bind 

### ISSUE THREAD

**Issue by aristidesfl** [Hammerspoon/hammerspoon#1230]
I'm trying to implement Karabiner's KeyOverlaidModifier.
It transforms a normal key into a custom modifier, except if the key is pressed and released under a second, it should send the normal key. (there is more to it but for now is that)

The problem is that when I send the original key, it gets captured again by the `hs.hotkey.bind` and enters an infinite loop. Is it possible to use `hs.hotkey.bind` so that it doesn't catch events sent by hammerspoon, or emit `hs.eventtap.event.newKeyEvent` in such a way that it doesn't trigger `hs.hotkey.bind`?

Example code:

```
local spaceDowntimestamp = nil
local isHomerowEnabled = false

local function spacePressed()
    spaceDownTimestamp = hs.timer.secondsSinceEpoch()
    isHomerowModeEnabled = true
end

local function spaceReleased()
    isHomerowModeEnabled = false
    if hs.timer.secondsSinceEpoch() - spaceDownTimestamp < 1 then
        hs.eventtap.event.newKeyEvent(modifiers, 'space', true):post()
        hs.timer.usleep(200)
        hs.eventtap.event.newKeyEvent(modifiers, 'space', false):post()
    end
end

hs.hotkey.bind({}, 'space', '', spacePressed, spaceReleased)
```

**Comment by aristidesfl** [comment]
One way to work around this issue is to listen for events with `hs.eventtap.new` and then use `event:getProperty(hs.eventtap.event.properties.eventSourceUnixProcessID)` to get the ID of the process which emitted the event. Key events sent by hammerspoon will have a value bigger than `0`. Events sent by the keyboard directly usually have a value of `0`

Example:
```lua
 hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
    if event:getKeyCode() == hs.keycodes.map[activator] and event:getProperty(hs.eventtap.event.properties.eventSourceUnixProcessID) == 0 then
      if event:getProperty(hs.eventtap.event.properties.keyboardEventAutorepeat) == 0 then
        onDown()
      end
      return true, {}
    end
  end):start()
```

**Comment by quickdraw6906** [comment]
I worked around this by setting user data in all events created by Hammerspoon, then the keyDown event tap I shunt all but those events that do NOT have user data:

`if e:getProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA) == 55555 then return false end`

**Comment by aristidesfl** [comment]
@quickdraw6906 also thought about doing that but thought it was not possible to tamper with the event properties. can you show how do you add user data?

**Comment by quickdraw6906** [comment]
https://github.com/quickdraw6906/hammerspoon-pc

**Comment by quickdraw6906** [comment]
functions.lua, getKeyEvent(), line 91

**Comment by aristidesfl** [comment]
For future reference: 

- https://github.com/quickdraw6906/hammerspoon-pc/blob/ea716cc872266a62b6a85e980aeda40acc7ff21b/config.lua#L3
- https://github.com/quickdraw6906/hammerspoon-pc/blob/ea716cc872266a62b6a85e980aeda40acc7ff21b/functions.lua#L94

Thanks!

**Comment by cmsj** [comment]
I believe it's now possible to do what you want with Karabiner Elements, which I suggest would be much better than trying to hack it in Hammerspoon.
