### ISSUE TITLE
timer.delayed:running() not working properly on short timers

### ISSUE THREAD

**Issue by leos** [Hammerspoon/hammerspoon#1232]
I may be missing something obvious, but this feels broken (repros in console - all pasted in as one block - and in init.lua code):
```
a = hs.timer.delayed.new(0.15, noop_func)
a:start()
print(a:running())
```
results in `false` while
```
b = hs.timer.delayed.new(4, noop_func)
b:start()
print(b:running())
```
prints out `true`. Setting the delay to `1` also results in the code printing out `false` and it's pretty clear there isn't a 1 second gap between the statements executing.

Alternatively, is there any way to expose millisecond precision times in Hammerspoon? If there was, I wouldn't need to have (potentially) messy timers for the code I'm doing.

**Comment by cmsj** [comment]
Good catch, thanks! This will be fixed in 0.9.53 :)

**Comment by leos** [comment]
Thanks for fixing! Is it worth adding a test for this? Are you able to actually get millisecond time in the timers themselves? if so, would it be possible to expose millisecond time through the hs API?

I've had to install luaposix as a workaround (including spending some time in bit32 hell as part of the hackery :-/ )

**Comment by cmsj** [comment]
@leos our hs.timer objects are very thin wrappers around NSTimer, which should be fine with millisecond intervals, although I'm curious what sort of Hammerspoon config would require that.

(and yes, I should have added a test when I fixed the bug :)

**Comment by leos** [comment]
Awesome, thank you @cmsj !

I'm using Hammerspoon to do paddle keys (because karabiner-elements doesn't support it yet :-( ). 

So, for example, a tap on a key results in one action while a hold (more than ~150ms) results in another. For example, tapping on my left and right shift keys gives me '(' and ')' while holding them down results in normal behavior as shift modifiers. Using timers is a really convenient way to encapsulate the state involved and it's also doable with some other optimizations by manually keeping track of time (but obviously with ms precision).

**Comment by quaritexa** [comment]
Does it possible in 0.9.52 to call some function after 250 ms of some key released?
