### ISSUE TITLE
Reload Hammerspoon after script error.

### ISSUE THREAD

**Issue by quaritexa** [Hammerspoon/hammerspoon#1233]
I have this shortcut in my init.lua:
```key.bind('ctrl-shift-escape', 'hs.reload()')``` it's equivalent to 
```hs.hotkey.bind({"ctrl", "shift"}, "escape", function() hs.reload() end)```
but I can't use it when hs stops on some error in my init.lua.

**Comment by latenitefilms** [comment]
Unfortunately, this is just the way it works. When there's an error, the Lua execution stops, and hence, your `init.lua` code also stops. You can press CMD+SHIFT+R when Hammerspoon has focus to Reload the configuration.

You could also potentially split up your "reload" script from your "main" script using a `hs.timer`. That way if your "main" script causes a fatal error, in THEORY the "reload" script should still work.

@asmagill or @cmsj might have better ideas though!

**Comment by cmsj** [comment]
@latenitefilms is right, this is pretty much unavoidable in Lua, but you can still use macOS' menu shortcuts system to make ctrl-shift-escape call Hammerspoon's menubar icon reload menu item. See System Preferences -> Keyboard -> Shortcuts -> App Shortcuts.

**Comment by quaritexa** [comment]
How to call Hammerspoon menubar2 item from any application via System Preferences shortcuts prefpane? I think it's impossible.

**Comment by cmsj** [comment]
@quaritexa I'm not quite sure I understand your question
