### ISSUE TITLE
Screensaver shortcut

### ISSUE THREAD

**Issue by quaritexa** [Hammerspoon/hammerspoon#1234]
I can't bind hs.caffeinate.startScreensaver() to ctrl-shift-forwarddelete. 
It flashes for a second and off. But if I bind to F12 - all is ok.

**Comment by quaritexa** [comment]
The working case (function on key release):
hs.hotkey.bind({"ctrl", "shift"}, "delete", nil, function() hs.caffeinate.startScreensaver() end)

**Comment by cmsj** [comment]
(for historical completeness, what was happening here was that the screensaver would be started when the keyDown events happened, and then cancelled by the keyUp events. @quaritexa moved the startScreensaver() call to the releasedfn hotkey parameter, so no additional keyboard events happen after triggering the hotkey)
