### ISSUE TITLE
Linking to local files using hs.webview?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1236]
I'm currently trying to generate some `hs.webview` HTML content during runtime.

I can generate the HTML fine using `hs.webview:html`, but how to do insert images or css files that are stored locally on my machine? I've tried using "file:///Users/etc" in the HTML href/src, but it doesn't work - I assume because of App sandboxing.

Any suggestions?

**Comment by rootscript** [comment]
It would be cool if there was something like `hs.webview:html(html,[baseURL])` for specifying where to load resources from (CSS, images etc).
I've been trying to figure this out too, but haven't even got as far as loading a local .html file into a hs.webview.  Would appreciate a small example.

**Comment by latenitefilms** [comment]
You can just load local HTML files by reading them in Lua then passing that data through to the hs.webview:html function. The only way I've been able to make images work is base64 encode them into the HTML.

We also use a template function which is cool - see: https://github.com/CommandPost/CommandPost/tree/develop/src/cp/welcome

**Comment by asmagill** [comment]
@rootscript, the `hs.webview:url` method does recognize the `file://` url type (e.g. `:url("file:///Users/<user>/Sites/index.html")`.
