### ISSUE TITLE
accessibilityState Watcher?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1239]
Any chance of adding a `accessibilityState` watcher to Hammerspoon? It would be great to know if a user (or the OS) has turned off the `accessibilityState` mid-session.

I guess you could just use a `hs.timer` but I assume a proper "watcher" would be less CPU intensive?

**Comment by latenitefilms** [comment]
Thoughts @asmagill & @cmsj ?

**Comment by cmsj** [comment]
I don't have a problem with doing this. We're doing it in the core of Hammerspoon anyway.

**Comment by latenitefilms** [comment]
Awesome - thanks @cmsj !

**Comment by latenitefilms** [comment]
@cmsj Sorry - I've tried to give this a bash myself, but unfortunately it's a bit out of my skill-set, so if anyone else is able to do, that would be amazing!

@asmagill or @knu ?
