### ISSUE TITLE
Hammerspoon doesn't fire activated event on focus

### ISSUE THREAD

**Issue by quickdraw6906** [Hammerspoon/hammerspoon#1240]
Either Hammerspoon (console) doesn't fire an activated type event when given focus, or the activated event it fires is of a different sort that the watcher doesn't trap (tap?).

hs.application.watcher.new(
  function(name, type, app)
    if app == 'Hammerspoon' and type == hs.application.watcher.activated then
      hs.console.clearConsole()
    end
  end
):start()

Tried unhide as well. I had console forced on top. Tried closing and reopening to.

**Comment by cmsj** [comment]
apologies for the slow response. Is this still an issue? I'd note that `activated` doesn't specifically mean that a window was focused, it means that some part of the app got focus. You'd need to switch to a completely different application and then back to Hammerspoon, to trigger an `activated` event.
