### ISSUE TITLE
First key makes it to VirtualBox, second key does not

### ISSUE THREAD

**Issue by quickdraw6906** [Hammerspoon/hammerspoon#1241]
Using a Windoz VM with VirtualBox. Got everything working (!) except one snag:
Using script that traps flags of ctrl+fn and shift+fn to simulate ctrl+insert/shift+insert on a PM. Can't use hotKeys.bind for this kind of thing to a VM (at least not with Vbox) so went direct. 

Issue is the copy works. The paste does not. Instead a single uppercase 'V' is sent. 

Now that is odd, because you can see in the log below no event with shift flag is ever sent. At the very end you see the flagsChanged eventtab fire after I release the delete key but before I release shift. 

Thanks for your consideration!

```
etFlagsTest = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function (e)
  flags = e:getFlags()
  mods = hs.eventtap.checkKeyboardModifiers()
  key = 'c'
  if next(flags) ~= nil then
    log('++++++++++++++++++++++++++++++++++++++++++++++++')
    log('flagsChanged event flags=' .. hs.inspect(flags) .. ';keycode=' .. e:getKeyCode())
  end
  if flags.fn then
    if mods.shift then key = 'v' end
    evKey = hs.eventtap.event.newKeyEvent({'ctrl'}, key, true)
     -- Shunt other eventtaps
    evKey:setProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA, 55555)
    log('================================================')
    dump(evKey:getFlags())
    evKey:post()
    hs.timer.usleep(1000)
    hs.eventtap.event.newKeyEvent({'ctrl'}, key, false):setProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA, 55556):post()
  end
end):start()
```

Setting the user data property so another eventtab (keyDown) will shunt. Here is the beginning of that eventtap:

```
etKeyDown = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function (e)
  local cancel = false
  local kc = e:getKeyCode() -- Key user pressed
  local flags = hs.eventtap.checkKeyboardModifiers() -- Modifier keys user was pressing
  local data = e:getProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA)
  log('keyDown event: keycode=' .. tostring(kc) .. '; userdata=' .. tostring(data) .. '; semaphore=' ..  tostring(semaphore) .. '; flags=' .. hs.inspect(e:getFlags()))
  -- Only do if not an event generated by another script- which sets the user data
  -- of the event to distinguish itself from user/OS key events. See getKeyEvent()
  if data == 55555 then return cancel end
...snip
```

Finally, here is the keyUp eventtap that logs out the event:

```
etKeyUp = hs.eventtap.new({hs.eventtap.event.types.keyUp}, function (e)
  log('keyUp event: keycode=' .. tostring(e:getKeyCode()) .. '; userdata=' .. tostring(e:getProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA)) .. "; semaphore=" ..  tostring(semaphore) .. '; flags=' .. hs.inspect(e:getFlags()))
  -- If a scripted action needed to block other keyboard events, then look
  -- for a key up event from the last event in the scripted chain of events
  -- and disable the event shunt eventtap and this eventtap
  if e:getProperty(EVENTPROPERTY_EVENTSOURCEUSERDATA) == 55556 then
    --log('Disabling shunt')
    ekKeyDownShuntCtrl:stop()
    --etKeyUp:stop()
  end
end):start()
```
Here is the console log from this [annotations in square brackets]:

2017-02-25 23:38:17: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:17: flagsChanged event flags={
  ctrl = true
};keycode=62
2017-02-25 23:38:17: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:17: flagsChanged event flags={
  ctrl = true,
  fn = true
};keycode=63
2017-02-25 23:38:17: ================================================
2017-02-25 23:38:17: DUMP: {
  ctrl = true
}
2017-02-25 23:38:17: keyDown event: keycode=8; userdata=55555; semaphore=0; flags={
  ctrl = true
}
2017-02-25 23:38:17: keyUp event: keycode=8; userdata=55556; semaphore=0; flags={
  ctrl = true
}
2017-02-25 23:38:17: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:17: flagsChanged event flags={
  ctrl = true
};keycode=63

[END Copy. BEGIN Paste (typed immediately after each other)]

2017-02-25 23:38:19: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:19: flagsChanged event flags={
  shift = true
};keycode=60
2017-02-25 23:38:20: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:20: flagsChanged event flags={
  fn = true,
  shift = true
};keycode=63
2017-02-25 23:38:20: ================================================
2017-02-25 23:38:20: DUMP: {
  ctrl = true
}
2017-02-25 23:38:20: keyDown event: keycode=9; userdata=55555; semaphore=0; flags={
  ctrl = true
}
2017-02-25 23:38:20: keyUp event: keycode=9; userdata=55556; semaphore=0; flags={
  ctrl = true
}
2017-02-25 23:38:20: ++++++++++++++++++++++++++++++++++++++++++++++++
2017-02-25 23:38:20: flagsChanged event flags={
  shift = true
};keycode=63

**Comment by cmsj** [comment]
I wonder if you could do this with Karabiner Elements - for keyboard remapping things, that is a much more appropriate tool where possible (because it happens in the kernel and we are a normal userspace application)
