### ISSUE TITLE
Request: consider adding a gitter chanel for this repo

### ISSUE THREAD

**Issue by emanresusername** [Hammerspoon/hammerspoon#1242]

**Comment by cmsj** [comment]
@emanresusername so, we have an IRC channel, which isn't particularly busy. we have github issues which are fairly busy. we have a mailing list which isn't very busy. I'm not sure I really want to have another conversation medium to pay attention to, sorry!

**Comment by latenitefilms** [comment]
@cmsj - While we're on it - I'd consider just dropping the Mailing List, in favour of making all the discussion happen on GitHub?

**Comment by cmsj** [comment]
@latenitefilms I think that the reality is that no one platform can serve all the needs of a community. Issues are good for having linear discussions. Mailing lists are good for having branching discussions. IRC is good for real-time discussion.

**Comment by emanresusername** [comment]
RE: don't want another channel to worry about: ![thats fair](https://cloud.githubusercontent.com/assets/860471/23972902/f0b58ce0-0990-11e7-8930-dc18d42cc036.gif)

**Comment by emanresusername** [comment]
@cmsj not sure if this is intentionally not broadcasted as sort of an easter egg for those that go to IRC or an oversight, but most of the stuff i wanted from this (or [this as well](https://github.com/Hammerspoon/hammerspoon/issues/946) i'd imagine) is handled by [the bot bot](https://botbot.me/freenode/hammerspoon/) integration (namely history and search)

**Comment by cmsj** [comment]
@emanresusername that's a very good point, thanks!
