### ISSUE TITLE
Basic question about calling hammerspoon from a shell script

### ISSUE THREAD

**Issue by aphecetche** [Hammerspoon/hammerspoon#1247]
Hi,

I'd like to use the power of Hammerspoon from within a shell script, so I guess I have to use the `hs` command line tool (right ?)

For example, create a window and make it fill the half right of my screen 

```code
#!/usr/bin/env sh

osascript <<EOF
tell application "iTerm2"
create window with profile "Notes"
tell current session of current window
write text "cd ~/Dropbox/Notes"
write text "tmux new-session"
end tell
end tell
EOF

hs -c "windowHalfRight()" 
```

(where windowHalfRight is defined in my init.lua as : 

```code
function windowHalfRight()
    local win = hs.window.focusedWindow()
    local f = win:frame()
    local screen = win:screen()
    local max = screen:frame()
    f.x = max.x + (max.w/2)
    f.y = max.y
    f.w = max.w / 2
    f.h = max.h
    win:setFrame(f)
end
```

The thing is actually working but with a big delay (1-2 seconds) between the creation of the window and the move of the window. 

So the question would be whether I am misusing something here ?
Is there maybe a clever way to achieve this ?

Thanks for your help,

**Comment by cmsj** [comment]
I'm going to close this out - 0.9.53 will be out soon, and it adds an AppleScript interface that lets you execute Lua directly from AppleScript :)
