### ISSUE TITLE
SPOTIFY Request :: hs.spotify.getTrackDuration()

### ISSUE THREAD

**Issue by jeffmikels** [Hammerspoon/hammerspoon#1253]
I'd like to request one addition to the spotify API:

hs.spotify.getTrackDuration()

Here's the lua code I'm using to make it happen now:

```lua
function get_track_duration()
	-- applescript code because hammerspoon can't return
	-- track time yet
	local script = [[
	tell application "Spotify"
		set tt to duration of current track
		set tt to tt / 1000
		return tt
	end tell
	]]
	
	local success, result, raw = hs.osascript.applescript(script)
	if success then
		return result
	end
end
```

**Comment by natemara** [comment]
This is already available, it's hs.spotify.getDuration, it's [here](https://github.com/Hammerspoon/hammerspoon/blob/3ddac80aec17e8a82760ebad8e298054ae8d796e/extensions/spotify/init.lua#L293), and the documentation is [here](http://www.hammerspoon.org/docs/hs.spotify.html#getDuration). According to the commit history, that function was added back in January 2017.

**Comment by jeffmikels** [comment]
Great! I don't think it was on the documentation site when I made the request, but it's there now. Thanks to whoever took care of this!

**Comment by cmsj** [comment]
👍
