### ISSUE TITLE
Repeating triggers while key depressed

### ISSUE THREAD

**Issue by pdoak** [Hammerspoon/hammerspoon#1254]
I have set up a hot key that moves the focused window 10 pixels to the right. If I repeatedly press the hot key the window will keep moving to the right. Is it possible to continually repeat the action if the hot key remains depressed?

**Comment by cmsj** [comment]
Yep! See the `repeatFn` argument to `hs.hotkey.bind()` :)

**Comment by pdoak** [comment]
I have amended my `hs.hotkey.bind` as follows:

```
 hs.hotkey.bind({ 'ctrl','shift'}, 'L',nil,nil, (function()
    local win = hs.window.focusedWindow()
    local f = win:frame()
    f.x = f.x + 30
    win:setFrame(f)
  end))
```
However, the function isn't repeatedly called when the keys remain depressed. Am I doing something wrong?

**Comment by quickdraw6906** [comment]
I tried looking at the event properties for the indication of repeat, but I never set keyboardEventAutorepeat ever be something other than non-zero.
