### ISSUE TITLE
Feature Request: Webcam events

### ISSUE THREAD

**Issue by Peeja** [Hammerspoon/hammerspoon#1255]
As I work from home and jump in and out of video conference meetings all day, I'd like to sense when my camera turns on and off and set Do Not Disturb and Away statuses on various services automatically while I'm in a meeting. (I don't think there's an API that makes that possible yet, although I may be missing it.)

**Comment by cmsj** [comment]
There are tools that can monitor webcam access, e.g. https://objective-see.com/products/oversight.html But I've not seen one that can emit events to Hammerspoon. They seem to involve running with root access, which is something we've been trying to avoid for Hammerspoon.
Perhaps the author of Oversight could be persuaded to send some kind of notification when it detects webcam use?

**Comment by Peeja** [comment]
Sounds good. Thanks for taking a look!

**Comment by onderweg** [comment]
Is the way it's done in https://github.com/ProZsolt/onair, possible in userspace, non-privileged code?

**Comment by cmsj** [comment]
Yeah that looks like it would do the trick. Great fine @onderweg :)

**Comment by asmagill** [comment]
For the record, I downloaded and ran the `onair` program on my machine and it detected when Skype calls started and stopped on an M1 mac for both mic and camera... There was maybe a second delay, but it definitely works without elevated privileges.

**Comment by onderweg** [comment]
Great! Thanks for reopening the issue, looking forward to using it in Hammerspoon.

**Comment by cmsj** [comment]
FWIW onair is GPL, which makes it more complicated for us to use its source as a reference, but I also found https://github.com/antonfisher/go-media-devices-state which does essentially the same thing and is MIT licensed.

**Comment by cmsj** [comment]
I also looked into the code for Oversight (which has the difference that it can tell you which process is using the camera/mic) and it seems like that is actually constantly parsing macOS logs to find specific messages from the camera/mic subsystems. A clever solution, but I don't think I want to go down that route.

**Comment by onderweg** [comment]
There is also this: https://github.com/jakobwesthoff/on-air-notifier that can be used as a reference.

It is written in Swift, but uses the same Objective-C API's as `onair`, and is MIT licensed.

**Comment by cmsj** [comment]
https://github.com/Hammerspoon/hammerspoon/pull/2998 adds `hs.audiodevice:inUse()` (which actually works for outputs as well as inputs). Not quite sure where in the API the camera one should go though, we don't really have anything camera-related at the moment.

**Comment by latenitefilms** [comment]
Maybe just make a new `hs.camera` for now? I can imagine other camera functions in the future.

**Comment by cmsj** [comment]
#2999 adds hs.camera (with support for querying in-use status and receiving notifications when it changes)

**Comment by cmsj** [comment]
If people want to start playing with hs.camera and the new "in use" stuff in hs.audiodevice, a signed dev build will be available from here in about 20 minutes: https://github.com/Hammerspoon/hammerspoon/actions/runs/1492232080

**Comment by onderweg** [comment]
Great work!

The property watcher receives `gone` events, whenever another application starts/stops the web cam. I think that's supposed to happen.
But, within the property watcher callback, `camera:isInUse()` seems to be always false.
Shouldn't that return true when camera is on?

```lua
local firstCamera = cameras[1]
firstCamera:setPropertyWatcherCallback(function(camera, property, scope, element)
    print("Camera Property Event: "..tostring(camera:name())..": "..tostring(property))
    if (camera:isInUse()) then
        -- does not happen
        print("Camera in use")
    else
        print("Camera not use")
    end
end)
firstCamera:startPropertyWatcher()
```
