### ISSUE TITLE
Can I use hs.execute to execute a node command line tool?

### ISSUE THREAD

**Issue by AndreGeng** [Hammerspoon/hammerspoon#1265]
Is it possible to execute a nodejs command line tool using hs.execute? 
Currently I have written a simple command line tool to change karabiner's profile configuration using nodejs, I want to be able to execute it when my external keyboard added/removed. But hs.execute('kess') always return ' nil exit 127'.  Below is the code snippets

```
hs.usb.watcher.new(function(dataTable)
  if dataTable['productName'] == 'Poker' then
    if dataTable['eventType'] == 'added' then
      hs.execute('kess -p 1')
    elseif dataTable['eventType'] == 'removed' then
      hs.execute('kess')
    end
  end

end):start()
```

```
#!/usr/bin/env node
var fs = require('fs');
var path = require('path');
var DEFAULT_CONFIG = {
  PROFILE_INDEX: 0,
  CONFIG_FILE: '.config/karabiner/karabiner.json'
}
var configFileLocation = path.resolve(process.env.HOME, DEFAULT_CONFIG.CONFIG_FILE);
var argv = require('yargs')
  .number('p')
  .alias('p', 'profile')
  .alias('h', 'help')
  .option('p', {
    demand: true,
    default: DEFAULT_CONFIG.PROFILE_INDEX
  })
  .help('h')
  .argv;
delete require.cache[configFileLocation]
var configFile = require(configFileLocation);
configFile.profiles.map(function(item, index) {
  if (index === argv.p) {
    item.selected = true;
  } else {
    item.selected = false;
  }
  return false;
});
fs.writeFileSync(configFileLocation, JSON.stringify(configFile, null, 2));
```
Any help is appreciated..

**Comment by latenitefilms** [comment]
If you type "kess" into Terminal, does it work for you?

I'm ASSUMING not, and you just need to get the path right.

**Comment by AndreGeng** [comment]
Actually 'kess' can works correctly within command line.  
I also tried hs.execute('node') inside 'hammerspoon console'  which output '	nil	exit	127' as well. But commands like "hs.execute('pwd')" can works correctly in 'hammerspoon console'.

**Comment by asmagill** [comment]
Try it as `hs.execute('kess', true)` and see if that makes a difference.

When a command line program is invoked via `hs.execute`, `os.execute`, or `hs.task`, it inherits a very basic environment with a minimal `PATH`.  Adding the `true` argument to `hs.execute` actually wraps the command in an invocation of `bash` (so it *is* a little slower) which means it will inherit any changes to the environment that your login shell's configuration files set (i.e. it loads `.bashrc_profile`, etc.)

Another option, if the command you're executing doesn't require the inherited path from your login files is to specify the path to `kess` explicitly (e.g. for my setup, `node` would be `/opt/node/bin/node`)

**Comment by AndreGeng** [comment]
ah, that's why... using hs.execute('kess', true) it works now. I really should read the 'API documents' twice before opening this. Thanks @asmagill for pointing this out. I am closing this.

**Comment by megalithic** [comment]
@asmagill resurrecting a closed issue.. is there such a thing with that wrapping hs.execute in your login shell but for hs.task? not finding it in the docs.

**Comment by asmagill** [comment]
Not directly, but you can replicate what `hs.execute(cmd, true)` is doing with something along the lines of the following (this is untested, but should be close): `hs.task.new(os.getenv("SHELL"), callbackFn, streamCallback or nil, { "-l", "-i", "-c", cmd})`.

Essentially we're making `bash` (or your default shell, if you've change it) the "task" and then passing the same arguments that `hs.execute` does (it's defined in `hs._coresetup`, which you can view at https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/_coresetup/init.lua#L186)
