### ISSUE TITLE
layout.lua in Resources Folder?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1267]
Curious... is there any reason why `layout.lua` exists in the `resources` folder when you build Hammerspoon? Is this just a mistake or by design? @cmsj ?

**Comment by cmsj** [comment]
Good catch, thanks. It doesn't cause any harm, it's just an annoying default when adding Lua files to the Hammerspoon project :)

**Comment by latenitefilms** [comment]
Legend, thanks mate!
