### ISSUE TITLE
Trying to codesign HS with a self-signed cert is suddenly crashing

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1269]
I have a script that builds HS and then self-signs the resulting app.  The script is a modification of one that's in the HS repo.  It has worked for a long time.

After building HS, it removes the unneeded extra copy in ~/Library/Developer/blah and then self-signs the app:
```
rm -rf $(\
  xcodebuild -workspace Hammerspoon.xcworkspace \
             -scheme Hammerspoon \
             -configuration DEBUG \
             -showBuildSettings \
 | sort \
 | uniq \
 | grep " BUILT_PRODUCTS_DIR =" \
 | awk '{ print $3 }' \
)

codesign --verbose \
         --sign "SelfSignedApplications" \
        "build/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A"
codesign --verbose \
         --sign "SelfSignedApplications" \
         "build/Hammerspoon.app"
```

Today I just tried to rebuild HS, and  the codesigning part crashes:
```
73174 Trace/BPT trap: 5       codesign --verbose --sign "SelfSignedApplications" "build/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A"
73176 Segmentation fault: 11  codesign --verbose --sign "SelfSignedApplications" "build/Hammerspoon.app"
```

As far as I know nothing has changed on my end.  It's the same self-signed cert that has worked previously.  I'm wondering if something in HS might have changed recently that's causing this.

**Comment by asmagill** [comment]
I'm assuming you've checked that the certificate is still valid (the first one I created had an expiration of 1 year... suffice to say the current one is set to 10 years)

I also ran into an issue a while back where certain file attributes were set on some of the assets (images I think) that `codesign` didn't like and added this right before the first `codesign` command:

~~~sh
xattr -cr "build/Hammerspoon.app" # codesign has become more anal in 10.12
~~~

This link also has some suggestions:

http://stackoverflow.com/questions/29687605/segmentation-fault-11-when-attempting-to-codesign-app

Hope one of these helps!

**Comment by chdiza** [comment]
None of that worked, unfortunately.  I finally just had to delete and recreate my self-signing cert.  I don't know what was wrong; it wasn't expired.
