### ISSUE TITLE
Hex color support

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1270]
It would be really convenient if we could use hex codes for color is this feasible?

**Comment by z3t0** [comment]
```lua 
function Util:hex2rgb(hex)
    hex = hex:gsub("#","")
    return tonumber("0x"..hex:sub(1,2)), tonumber("0x"..hex:sub(3,4)), tonumber("0x"..hex:sub(5,6))
end

```

this is what i am doing in my script

**Comment by asmagill** [comment]
This is actually not a bad idea.  `hs.drawing.color` which *most* modules use to inherit color support could be modified for this fairly easily...

It will have to be added as a new table type (e.g. `color = { hex = "#RRGGBB" }` to ensure that it doesn't break or change anything else... while allowing color to be specified as a simple string might seem more intuitive, there are a *crap ton* (that's the official programming term 😝) of places in the Hammerspoon code where argument checking would have to be modified in not so simple ways...

What formats should be supported?  I'm partial to the HTML style (#rgb or #RRGGBB), but traditional hex (0x######) wouldn't be hard to include as well... thoughts?

**Comment by asmagill** [comment]
Other questions if anyone wants to chime in:

* do we allow an optional additional field for alpha or keep that as a separate key? (e.g. `{ hex = "#RRGGBBAA" }` or `{ hex = "#RRGGBB", alpha = a }` where `a` is between 0 and 1

* should the preceding "#" (or "0x") be optional (i.e. should `#RRGGBB` and `0xRRGGBB` and `RRGGBB` all be allowed?

**Comment by z3t0** [comment]
i think it doesn't really matter as long as we choose a standard and stick to it

**Comment by cmsj** [comment]
I would prefer html style, I think. Seems likely to be more familiar to more people, than plain hex

**Comment by asmagill** [comment]
since merged, I am closing this.  reopen if you disagree.
