### ISSUE TITLE
hs.httpserver.hsminweb Example Fails?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1274]
In the [hs.httpserver.hsminweb](http://www.hammerspoon.org/docs/hs.httpserver.hsminweb.html) API documentation it says:

> You can start this web server by typing the following into your Hammerspoon console:
> `require("hs.httpserver.hsminweb.hsdocs").start()` and then visiting `http://localhost:12345/` with your web browser.

How that doesn't actually work.

Might need to update the documentation @cmsj ?

**Comment by asmagill** [comment]
Doh! That should read `require("hs.doc.hsdocs").start()`... I'll update it in master since its just one line in the documentation strings.

**Comment by latenitefilms** [comment]
Legend, thanks mate!
