### ISSUE TITLE
Display system UI overlay when changing sound volume?

### ISSUE THREAD

**Issue by iliyang** [Hammerspoon/hammerspoon#1275]
The touch bar on the new Macbook Pro has made changing the sound volume cubersome. Thankfully we have Hammerspoon to help us set custom shortcuts for changing the volume. And it works great for me, but unfortunately I don't get the system UI overlay pop up when I do so – I have to rely on Hammerspoon notifications which can be problematic (If necessary, I can go into details why, but I think that's a different topic).

So is there a way to show the system volume UI overlay from a Hammerspoon script?

![image](https://cloud.githubusercontent.com/assets/802594/24353121/1d01e6f2-12e4-11e7-9af1-82bce3d76bf5.png)

**Comment by cmsj** [comment]
Please do file bugs about Hammerspoon notifications if you have run into issues (also I'd maybe suggest using hs.alert for this sort of thing)

Unfortunately, I'm not aware of any way to instruct the OS to show those UI overlays - they are all hidden away in the private BezelServices framework, and I've been unable to find any code that interacts with it.

If anyone knows of any tools that are able to make this work, please re-open this and let me know :)

**Comment by treadup** [comment]
I was able to make this kind of work using a utility called [cliclick](https://www.bluem.net/en/projects/cliclick/).

What I wanted to do was assign F10 to mute, F11 to volume down and F12 to volume up.

To be able to bind the F10 and F11 keys in Hammerspoon you have to assign other shortcuts for "Show Desktop" and "Show Dashboard" for Mission Control. See [https://github.com/Hammerspoon/hammerspoon/issues/901](https://github.com/Hammerspoon/hammerspoon/issues/901) for more information.

Now all we have to do is add the following code to init.lua
```
hs.hotkey.bind({}, "f10", function()
  hs.execute("/usr/local/bin/cliclick kp:mute")
end)

hs.hotkey.bind({}, "f11", function()
  hs.execute("/usr/local/bin/cliclick kp:volume-down")
end)

hs.hotkey.bind({}, "f12", function()
  hs.execute("/usr/local/bin/cliclick kp:volume-up")
end)
```

The one remaining problem is that the keypresses do not repeat. So if you hold down f12 it will raise the volume by one step and then just sit there. To raise the volume further you have to release the key and then press it again.

The following link [https://github.com/Hammerspoon/hammerspoon/issues/1011#issuecomment-261114434](https://github.com/Hammerspoon/hammerspoon/issues/1011#issuecomment-261114434) might be relevant for the no repeat issue.

**Comment by atdt** [comment]
I got this to work with no external tools. Key repeat works too:

```lua
local function sendSystemKey(key)
    hs.eventtap.event.newSystemKeyEvent(key, true):post()
    hs.eventtap.event.newSystemKeyEvent(key, false):post()
end

local volume = {
    up   = function() sendSystemKey("SOUND_UP") end,
    down = function() sendSystemKey("SOUND_DOWN") end,
    mute = function() sendSystemKey("MUTE") end,
}
hs.hotkey.bind({}, "f10", volume.mute)
hs.hotkey.bind({}, "f11", volume.down, nil, volume.down)
hs.hotkey.bind({}, "f12", volume.up, nil, volume.up)
```

**Comment by luckman212** [comment]
@atdt That is ... awesome 👏 
Thank you

**Comment by rsurjano** [comment]
you save me my day, appreciate
