### ISSUE TITLE
hs.window.filter recognised tabbed Keynote as two separate windows in Sierra

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#1277]
![screen shot 2017-03-27 at 20 49 12](https://cloud.githubusercontent.com/assets/1040420/24372652/ecd3fcf4-132e-11e7-92ae-a407efe8c1cd.png)

```lua
hs.fnutils.each(hs.window.filter.new():setDefaultFilter():getWindows(), function(win) 
  print(win:title(), win:application():name(), win:frame()) 
end)
```

Gives me two "Keynote" windows:

```
Untitled 2      Keynote hs.geometry.rect(1285.0,10.0,1265.0,1420.0)
Untitled        Keynote hs.geometry.rect(10.0,10.0,1265.0,1420.0)
```

This is also the case with Pages, but not with Finder or Safari...

**Comment by cmsj** [comment]
I have a suspicion that this must relate to the new NSDocument tab support in Sierra. Any application which uses NSDocument to represent its document instances, now gets automatic support for tabs. Presumably they are doing this by creating a window, and just forcibly rendering it inside a tab.

Currently not sure what we can do about that.

**Comment by szymonkaliski** [comment]
Yeah, I was suspecting it's something with that tabs feature in Sierra... I think we should keep this issue open though, I'll try to come up with some hacky workaround as this thing get's in my way often.

**Comment by cmsj** [comment]
I'm going to close this out because I don't think there is anything we can do about it. Please feel free to re-open if you disagree :)
