### ISSUE TITLE
ROpt/LOpt & RCommand/LCommand Support

### ISSUE THREAD

**Issue by laktak** [Hammerspoon/hammerspoon#1278]
Would it be possible to add support for the left/right option and command keys?

For example I'd like to bind Right-Option + Cursor-Left while leaving Left-Option + Cursor-Left alone.

**Comment by asmagill** [comment]
Not directly, no.

Couple of "messy" possibilities right now...

* Set up the hotkey as you normally would then use `hs.eventtap.checkKeyboardModifiers(true)` and look at the `_raw` field and logically AND the value against one of the following:
~~~
deviceRightAlternate      64
deviceRightCommand        16
deviceRightControl        8192
deviceRightShift          4
~~~

Down side, you capture `opt-right` no matter which option key is used, but you can have it do something different for each.  Some people have had some luck with trying to pass the typed key back out of a hotkey callback, others have had nothing but problems.  See https://github.com/Hammerspoon/hammerspoon/issues/894 (and the link to the Google group thread in it) for one such discussion.  You can also find others by searching in these issues for `hotkey` and `newKeyEvent`.


* You can watch for `flagsChanged` events with `hs.eventtap` and with a similar ANDing against `event:getRawEventData().CGEventData.flags` in the event callback (after verifying it's the appropriate modifier flag(s) with `event:getFlags()` and *only* then enabling the hotkeys (and also disabling them whenever the modifier keys change again -- either a release or additional modifiers)


I am working on an update to `eventtap` (and maybe eventually `hotkey` if I can address some timing issues) that should make this kind of thing cleaner, but its a significant change in the code base to address a wide range of oddities and limitations we've discovered with `eventtap`... I have no timeframe atm.
