### ISSUE TITLE
Remove hs.redshift

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1280]
Given that macOS now has Night Shift built-in, does anyone want to stand up for hs.redshift's continued existence? :)

**Comment by asmagill** [comment]
* older machines (< 2012) don't support Night Shift
* 10.12.x isn't our minimum supported OS version yet
* no per application setting - NS is all or nothing
* also has easy interface to invert

Ok, that last one could easily be moved to `hs.screen`.

Aside from some issues when the machine goes to sleep/wakes up which can be mitigated with a caffienate watcher, redshift may be a little confusing to setup/understand at first, but its worked fine (for me at least).

I don't see a need to remove it, but maybe note that no future development is planned for it in the docs.

**Comment by cmsj** [comment]
All very reasonable points :)

**Comment by chdiza** [comment]
Apparently NightShift actually does a poor job of removing blue light, while F.lux still does well in that regard.
