### ISSUE TITLE
hsminweb stops responding after a while

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1287]
The port stays open but the server stops responding. Restarting hammerspoon doesn't do anything. Only a reboot fixes the problem. No crash report or anything seen. I am running @asmagill 's latest cheatsheet code with asset server serving the locally cached js without any change . Mac OS X - 10.12.4/XCode 8.3 .

**Comment by asmagill** [comment]
I haven't seen this... I did have a problem once when something else tried to open the same port, but changing the port that application used and restarting both Hammerspoon and the other application cleared it out...

What does `lsof -n -i -P | grep :7734` (where 7734 is the port number you care about) when entered into a terminal window report?

For me, I get
~~~
$ lsof -n -i -P | grep :8192
Hammerspo 50380 amagill   20u  IPv4 0xc3a1b3b545dff46d      0t0  TCP *:7734 (LISTEN)
Hammerspo 50380 amagill   21u  IPv6 0xc3a1b3b545f743dd      0t0  TCP *:7734 (LISTEN)
~~~

Which is what I would expect -- a listener for both IPv4 and IPv6.

**Comment by junkblocker** [comment]
Ah, duh, I only checked via `netstat`, should have used `lsof` . I have `autossh` grabbing that port. Thanks for the quick response, @asmagill !

**Comment by asmagill** [comment]
Glad to hear it!... as I notice my example above shows the command for 8192 but the results for 7734... I'll edit that so its consistent in case someone searches for this <sheepish grin>
