### ISSUE TITLE
Building a LuaSkin docset for developer documentation

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1289]
I am opening this issue to take the comments and thoughts and suggestions out #1284.

The goal is to create a LuaSkin docset containing the documentation for developers to use when building or editing modules for Hammerspoon.  It is not expected that this documentation will be of interest to the casual or general user of Hammerspoon.

What I'm putting forth here is by no means absolute -- it is just my thoughts, experiences, etc. and, as always, I will differ to consensus if anything here does make it into the common Hammerspoon source or makefile.

* This documentation will probably not be added to the Dash docsets which can be searched for and installed from within Dash.  My reasons for thinking this are:
  * at least for now, its going to be changing a lot while the process is worked out and some bugs in the current headerdoc comments are worked out
  * the target audience is probably pretty small and generally limited to people who are likely to be comfortable building their own version of Hammerspoon anyways
  * I don't want to take on the responsibility of keeping it current
* A pure HTML version should be either a step in the process to generating the docset, or a by-product.  This is so the API documentation available online can be kept on par with the docset
* The comments from which the documentation is generated must not require changes that would prevent XCode from using the same comments for inline code completion and internal documentation by those who do develop for Hammerspoon from within Xcode. *[edit - wrong app originally specified]*

Feel free to discuss/comment/suggest. I will followup with my current experiences generating documentation for LuaSkin in separate comments.

**Comment by asmagill** [comment]
First, the method I have used up to today did not generate a docset... only HTML.  It uses the `headerdoc2html` command which is included with Xcode.  The commands I used were in my build script for Hammerspoon and were as follows:

~~~sh
	classDir=build/html/LuaSkin
# hack because headerdoc2html doesn't seem to recognise @code/@endcode and @remark anymore
	sed -e 's/@code/<pre>@textblock/' \
	    -e 's/@endcode/@\/textblock<\/pre>/' \
	    -e 's/@remark/@attributeblock Notes/' LuaSkin/LuaSkin/Skin.h > Skin.h
	headerdoc2html -u -o ${classDir} Skin.h
	resolveLinks ${classDir}
	rm Skin.h
# clean up the destination folder a little bit
	mv ${classDir}/Skin_h/* ${classDir}
	rmdir ${classDir}/Skin_h

	mv build/html/LuaSkin ~/Documents/Hammerspoon/
~~~

And now I can view the LuaSkin docs in my browser with `open ~/Documents/Hammerspoon/LuaSkin/index.html`

As noted above, this requires a hack because some of the headerdoc directives no longer seem to be recognized and it generates a crap load of notices, warnings, etc.

And isn't a docset, so no Dash, no easy search.

**Comment by asmagill** [comment]
Introducing [appledoc](https://github.com/tomaz/appledoc)

This will generate both a docset and html and looks like the way I'm going to be recommending... except that Homebrew's version appears to be broken, at least under 10.12.

However, if you install it as follows:

~~~sh
$ git clone git://github.com/tomaz/appledoc.git
$ cd appledoc
$ sh install-appledoc.sh -t default
~~~
(if /usr/local/bin isn't writable -- i.e. you aren't using homebrew -- you can use `sudo` for the last command... in fact the appledoc installation guide tells you to, but its only so the command line tool can be installed)

Then the following:

~~~sh
$ /usr/local/bin/appledoc \
    --project-name "LuaSkin" \
    --project-company "Hammerspoon" \
    --company-id "org.hammerspoon" \
    --output "build/LSDocs" \
    --clean-output \
    --no-install-docset \
    --no-publish-docset \
    --logformat xcode \
    --keep-undocumented-objects \
    --keep-undocumented-members \
    --keep-intermediate-files \
    --ignore "*.m" \
    LuaSkin/LuaSkin
~~~

The docset is created in `~/Library/Developer/Shared/Documentation/DocSets/org.hammerspoon.LuaSkin.docset` (and in `build/LSDocs/docset` but without the `.docset` extension) and the HTML can be found in `build/LSDocs/html`.

I'm by no means quite ready to call this done... 
* It does still report some warnings about a few things I want to try and clean up in `Skin.h`
* `appledoc` supports including additional `html` files and incorporates them into the docset... I want to explore this and see what the best way to start documenting the `luaskin.lua` file that is part of LuaSkin might be and add this as well
* I've been working on this for only about an hour now (well, an hour since I figured out that the brew version was broken...) so the proper arguments may require some tweaking as well.

I will upload the docset and HTML pages a little later tonight (when I figure out the cleanest way to do so) for you to review without having to install appledoc yourself.  Consider it a work in progress, though.

**Comment by asmagill** [comment]
Ok, an example can be found at https://asmagill.github.io/LuaSkin.html.  There is a link to view the html and a link to download the docset for offline viewing.

**Comment by junkblocker** [comment]
Beautiful :+1:

**Comment by latenitefilms** [comment]
Looks pretty slick! Nice work!

This might be completely irrelevant, but in regards to documentation, I wonder if it would be worthwhile moving the online [API Documentation ](http://www.hammerspoon.org/docs/index.html) over to something like [GitBook](https://www.gitbook.com), so that you can make use of it's built-in search features? Admittedly, I've never used Dash, and I've never really used the built-in help tools within Hammerspoon, so I spend a lot of time on the online [API Documentation ](http://www.hammerspoon.org/docs/index.html), which is pretty annoying to navigate. I realise that all your documentation is "rendered" as HTML, not markup, so this could be a useless suggestion.

**Comment by asmagill** [comment]
Prepping the Hammerspoon API (the documentation at http://www.hammerspoon.org/docs/index.html) should be pretty easy... it starts as markdown snippits in the lua and objective-c files that make up the Hammerspoon modules.

Prepping the LuaSkin (i.e. http://www.hammerspoon.org/docs/LuaSkin/) specific documentation would be challenging.  I'm not aware of any headerdoc to markdown conversion tools out there (which is not to say they don't exist).

While an interesting idea, I think it's really a separate question/issue from what this this particular thread is focusing on.  If you want to pursue it and see what it gains us and discuss what it would entail in terms of code or process additions/changes, feel free to open up another issue!

**Comment by cmsj** [comment]
@asmagill wow, that AppleDoc output is great. Much better than the headerdoc2html output! +1 for moving to AppleDoc. It looks like we could also do with tidying up some of the tags, since I see a few bits showing incorrectly in your output, but it's still a huge improvement. Thanks for discovering this!

**Comment by asmagill** [comment]
Known issue with AppleDoc: does not document typedefs, enums, or functions and it doesn't look like this will be addressed soon unless someone wants to contribute: https://github.com/tomaz/appledoc/issues/2

Still, its the best look  so far...

**Comment by asmagill** [comment]
@latenitefilms -- see [my comment above](#issuecomment-290306392): which documentation are you wanting in markdown format?  And how/when?  At compile time when you have access to the full sources (as an addition to the Makefile, maybe)?  At runtime when executing a specific `hs.doc` function?  To a preset location (e.g. in the build/ folder, if at compile time) or to a folder specified?  As one monolithic file or separate files for each module?

**Comment by cmsj** [comment]
@asmagill any thoughts on this one? I do like the appledoc output, but since it has a few gaps in what it can document, and given that it'd be a fair bit of work to integrate this and get all the docstrings in shape, do we actually still want to do it?
