### ISSUE TITLE
Add client-side search engine to HTML API docs

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1290]
As discussed [here](https://github.com/Hammerspoon/hammerspoon/issues/1289#issuecomment-290302121), I wonder if it would be worthwhile moving the online [API Documentation](http://www.hammerspoon.org/docs/index.html) over to something like [GitBook](https://www.gitbook.com/), so that you can make use of it's built-in search features? Admittedly, I've never used Dash, and I've never really used the built-in help tools within Hammerspoon, so I spend a lot of time on the online API Documentation , which is pretty annoying to navigate. I realise that all your documentation is "rendered" as HTML, not markup, so I'm not sure how tricky this is to implement.

**Comment by cmsj** [comment]
@latenitefilms if it's something that can be automated, I'd be ok with mirroring it there, but I don't think we can make our primary source of API truth be a third party service.

If someone were so inclined, they could probably add some Javascript to our HTML docs which consumes the docs.json to add searching, without any server-side requirements.

**Comment by latenitefilms** [comment]
> if it's something that can be automated, I'd be ok with mirroring it there, but I don't think we can make our primary source of API truth be a third party service.

I was under the impression the Hammerspoon website was all hosted by GitHub anyway? GitBook can store all your content on GitHub, so I don't think that's an issue.

> If someone were so inclined, they could probably add some Javascript to our HTML docs which consumes the docs.json to add searching, without any server-side requirements.

This is a MUCH better idea! I don't think I'm smart enough to make this happen, but I do think adding a search feature to the website API documentation would be worthwhile. Or at the very least better page navigation.

**Comment by cmsj** [comment]
I've just added a very simple search engine to the HTML docs. It looks ugly as heck, but I am not capable of fixing that, so hopefully someone can do a good job of that :)

(maybe @jasonm23 is still interested in helping with our CSS shortcomes? :D )

**Comment by jasonm23** [comment]
@cmsj I can have a look at this for you
