### ISSUE TITLE
Getting window on launch?

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1291]
Is there a way to get the windows of an application on launch?
 
I am using hs.application.watcher to detect the launch event for an app, the goal being to then get its windows and push them to a specific space. I already have the space part figured out but the problem is that on launch it seems that the alWindows returns {}, which is probably because it is before the application is able to create a window. Any other ways to go about doing this?

**Comment by szymonkaliski** [comment]
Is hs.window.filter what you are looking for? http://www.hammerspoon.org/docs/hs.window.filter.html

**Comment by cmsj** [comment]
Yeah window.filter should do it, or you can use the application watcher to set up a window watcher for each application as it launches (which is effectively what window.filter is doing for you :)

**Comment by z3t0** [comment]
Thanks I'll try that!

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
