### ISSUE TITLE
More clarity in documentation the fact that `dIn ` is four letters long in the audio device watcher callback argument

### ISSUE THREAD

**Issue by srubin** [Hammerspoon/hammerspoon#1295]
The documentation notes the different possible arguments in the audio watcher callback: dIn, dOut, sOut, and dev#. I thought I was going insane because `arg == 'dIn'` was never true. The problem is that these are the enum values from CoreAudio (see CoreAudio > AudioHardware.h lines 585-586) and they're all 4 characters long. So `dIn` actually has a space at the end of it. 

Either the Hammerspoon documentation should reflect this, or the audio watcher code should trim the trailing space from the arg string.

**Comment by cmsj** [comment]
Thanks for raising this :)
