### ISSUE TITLE
hs.application.launchOrFocus not working as expected

### ISSUE THREAD

**Issue by AndreGeng** [Hammerspoon/hammerspoon#1298]
I have mapped ctrl+h/j/k/l to arrow keys. 
Say, I am using ctrl + j/k to scroll web pages opened in chrome. Then I launch 'atom' by calling hs.application.launchOrFocus("Atom"). After that if I hit ctrl + j/k again, I want to move the cursor inside 'atom'. But now ctrl + j/k still controls web pages in chrome. 
I think this is not expected,  because now 'atom' is the focus window right? or is there any way to work around this?

**Comment by aaronjensen** [comment]
Looks related to https://github.com/Hammerspoon/hammerspoon/issues/288

**Comment by aaronjensen** [comment]
I also have a problem with the Highfive client. `launchOrFocus('/path/to/HighfiveApp.app')` does not actually switch to Highfive or focus it. Using the bundle id does not help either. It seems to be a problem common to Electron apps

**Comment by cmsj** [comment]
That's kinda weird because `launchOrFocus()` is literally just calling the underling OS code for launching/focusing apps - we don't do anything clever there at all :(

**Comment by aaronjensen** [comment]
Yeah, and that doesn't work either for Highfive (spotlight->Highfive-Return)

**Comment by AndreGeng** [comment]
actually hs.application.launchOrFocus('atom') can successfully switch to atom application on my mac. what is not working is those mapped arrow keys(ctrl-j/k), I can not use them to interact with currently focused window launched by 'launchOrFocus' method. They seems always controls previous application I interacted with.  But those real arrow keys on the keyboard works as expected. If I use those real arrow keys to move the course around a little bit then those mapped arrow key can works properly after that.  I am using following code to remapping keys, Could it be key mapping's problem?
```
local fireKey = function(configItem)
  return function()
    hs.eventtap.keyStroke(configItem.mapTo.mod, string.lower(configItem.mapTo.key), 20000)
  end
end
hs.fnutils.each({
  {key='h', mod={'ctrl'}, mapTo = {mod = {}, key = 'left'}},
  {key='l', mod={'ctrl'}, mapTo = {mod = {}, key = 'right'}},
  {key='j', mod={'ctrl'}, mapTo = {mod = {}, key = 'down'}},
  {key='k', mod={'ctrl'}, mapTo = {mod = {}, key = 'up'}},
  {key='h', mod={'ctrl shift'}, mapTo = {mod = {'shift'}, key = 'left'}},
  {key='l', mod={'ctrl shift'}, mapTo = {mod = {'shift'}, key = 'right'}},
  {key='j', mod={'ctrl shift'}, mapTo = {mod = {'shift'}, key = 'down'}},
  {key='k', mod={'ctrl shift'}, mapTo = {mod = {'shift'}, key = 'up'}},
  {key='h', mod={'alt'}, mapTo = {mod = {'alt'}, key = 'left'}},
  {key='l', mod={'alt'}, mapTo = {mod = {'alt'}, key = 'right'}},

  {key=',', mod={'ctrl'}, mapTo = {mod= {}, key='delete'}},
  {key='escape', mod={'cmd'}, mapTo = {mod= {'cmd', 'shift'}, key='`'}}
}, function(configItem)
  local arrowRemappings = hs.hotkey.bind(configItem.mod, configItem.key, fireKey(configItem), nil, fireKey(configItem))
end)
```

**Comment by rootscript** [comment]
@AndreGeng 
@aaronjensen
I had a similar issue, and used this <https://github.com/Hammerspoon/hammerspoon/issues/272#issuecomment-96085256> to allow me to bind/unbind keys per application.

**Comment by cmsj** [comment]
I would strongly recommend using Karabiner Elements to remap keys if at all possible - it's gotten really good now and operates at a much more appropriate layer of the OS for this sort of thing.

I'm going to optimistically close this issue, but people can feel free to re-open it if they want :)
