### ISSUE TITLE
nstask module

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#130]
I've been mulling over writing a nstask based module so external scripts/commands/whatever can be called and have stdin pulled form a function and stdout retrieved by polling or callback (ultimately both, but I think polling will be easier at first).

Question for the group:  should I include the ability to invoke the task with Administrative privileges?  The proper way to do so requires a developer license and setting up a "helper" that is invoked by launchd... I won't be able to test it directly until it's merged, as I don't have a license.

The other options are to use the deprecated (but I think still available in 10.10) AuthorizationExecuteWithPrivileges, or to use Applescript to invoke the command, but then I think (not absolutely certain yet) we might lose the async access that was the point of this module.

Or we can forgo admin rights all together -- it is putting a lot of potential into potentially dangerous hands :-)

**Comment by cmsj** [comment]
@asmagill is this still something you care about? (I note that we have hs.http now, which covers your initial usecase). I'm not opposed to keeping this idea around, but I'm trying to tidy up the github Issues a bit :)

**Comment by asmagill** [comment]
I still think that this might be useful but so far each time I've really encountered a need, it ends up being easier to write a more focused specific module (http ended up in this category, though I didn't write it -- I didn't keep all of my tests, but the solution looks remarkably similar to one I did try -- I wish I'd kept it so I could compare and see what I missed, but oh well!) or come at the problem in another way and use a different module I'd not worked with before (*cough* 'find...' versus hs.fs)

I guess what I'm getting at is go ahead and close it... async access to the results of external processes has ended up being less of a stumbling block than I feared, and it can always be reopened.

**Comment by cmsj** [comment]
groovy, thanks :)
