### ISSUE TITLE
keyStroke during bind press doesn't work as you'd expect if the key is the same in both

### ISSUE THREAD

**Issue by aaronjensen** [Hammerspoon/hammerspoon#1304]
I believe I saw that this was a known issue in another issue, but I'm opening this anew because it is surprising and if it were fixable it'd be great. This is a contrived example to demonstrate the problem:

```
z = hs.hotkey.modal.new()
z:bind({}, '.', function()
  hs.eventtap.keyStroke({'shift'}, '.')
end, nil, function()
  hs.eventtap.keyStroke({'shift'}, '.')
end)
hs.hotkey.bind(
  {},
  'z',
  function()
    z:enter()
  end,
  function()
    z:exit()
  end
)
```

If you hold <kbd>z</kbd> and hit <kbd>.</kbd> nothing will happen. If you hold it, it will repeat `.`  (as opposed to `>`). If you change the binding to something like <kbd>F</kbd> it will emit `>` and holding it will will repeat `>`. 

I would expect <kbd>.</kbd> to work the same as the <kbd>F</kbd> binding.

By the way, thank you much for Hammerspoon. I thought I was stuck on El Capitan forever because of lack of Karabiner, but Hammerspoon has given me a way out! 😄

**Comment by cmsj** [comment]
I would note that Karabiner Elements' beta releases now support much more complex key remapping, so you might want to take a look at whether it can now support your use case.

I'm very glad you like Hammerspoon, but it's really the wrong tool for complex keyboard remappings - we run at much too high a level in the OS to be able to influence things without weird side effects.

**Comment by aaronjensen** [comment]
Thanks, I'll check it out. I abandonded Karabiner Elements because modifier keys would randomly get stuck while it was running. I had no idea why or how to debug and it doesn't with Hammerspoon.

I was able to replicate everything (custom symbol layer, hyper key, quick launch, etc) I had before (with Karabiner on El Capitan) with Hammerspoon, so don't sell it too short 😉  by using eventtaps and custom event properties.

https://github.com/aaronjensen/dotfiles/blob/master/hammerspoon/common.lua
https://github.com/aaronjensen/dotfiles/blob/master/hammerspoon/symbol_layer.lua

It took a lot of code, but it has been working quite well for me.

**Comment by cmsj** [comment]
I suspect it might be a good idea to delay the `keyStroke()` call - otherwise it's sending out an event while there are keys held down, which can cause confusion (in this case you're sending a keyDown for `.` after one has already been sent.

I'm going to optimistically close this issue because I think the above is where the issue lies, but please feel free to re-open if I'm wrong :)
