### ISSUE TITLE
Window switcher doesn't work when filtered

### ISSUE THREAD

**Issue by sarangak** [Hammerspoon/hammerspoon#1309]
I have a simple binding:
``` lua
hs.hotkey.bind('alt', 'tab', function()
    local current_app = hs.window.focusedWindow():application():name()
    hs.window.switcher.new(current_app):next()
end)
```

When I press Alt-Tab multiple times in an application with multiple (visible) windows, Hammerspoon freezes / becomes laggy and I have to Force Quit it to get it back to normal. 

This happens even if I hardcode an application, e.g., 'iTerm2' in place of `current_app`.

Expected behavior:
I should be able to select past the second window of an application.  The default window switcher works perfectly, but when filtered it does not.

**Comment by cmsj** [comment]
@sarangak I think that may be because you're creating a new window switcher object each time you press the key. Take a look at the examples at the top of and you'll see that the switcher object is created once as a global variable, and then manipulated by the hotkeys.

**Comment by cmsj** [comment]
(please feel free to re-open this issue if I'm wrong :)

**Comment by latenitefilms** [comment]
@sarangak - You could try something like this:

```
mySwitchers = {}

hs.hotkey.bind('alt', 'tab', function()
    local currentApplication = hs.window.focusedWindow():application():name()
    if mySwitchers[currentApplication] == nil then
    	mySwitchers[currentApplication] = hs.window.switcher.new(current_app)
    end
    mySwitchers[currentApplication]:next()
end)
```

**Comment by sarangak** [comment]
Perfect!  Thanks for the help!

For posterity:
```lua
mySwitchers = {}
function currentApplicationSwitcher()
  local currentApplication = hs.window.focusedWindow():application():name()
  if mySwitchers[currentApplication] == nil then
    mySwitchers[currentApplication] = hs.window.switcher.new(currentApplication)
  end
  return mySwitchers[currentApplication]
end
hs.hotkey.bind('alt', 'tab', function()
                 currentApplicationSwitcher():next()
end)
hs.hotkey.bind('alt-shift', 'tab', function()
                 currentApplicationSwitcher():previous()
end)
```
