### ISSUE TITLE
Can't bind ctrl-up/down

### ISSUE THREAD

**Issue by quaritexa** [Hammerspoon/hammerspoon#1310]
This is in modal bind:
2017-04-07 20:25:04: 20:25:04 ERROR:   LuaSkin: hs.hotkey:enable() keycode: 126, mods: 0x1000, RegisterEventHotKey failed: -9878
2017-04-07 20:25:04: 20:25:04 ERROR:   LuaSkin: hs.hotkey:enable() keycode: 125, mods: 0x1000, RegisterEventHotKey failed: -9878

Normal bind just doesn't works with no errors.
ctrl-left/right works fine.

**Comment by cmsj** [comment]
Take a look in System Preferences -> Keyboard -> Shortcuts, in the Mission Control section, I'd guess you have the Mission Control and Application Windows shortcuts enabled, which default to those two keys. If not, maybe something else in those shortcut sections. That's often what the error you're seeing, means.

Please feel free to re-open this issue if I'm wrong :)

**Comment by quaritexa** [comment]
So strange bug. 

Before creating this issue I checked out Mission Control shortcuts. But long time ago I turned off almost all Mac shortcuts in the Keyboard Prefpane. 

Now, I turned on two shortcuts (⌃↑ and ⌃↓), changed it to F15, then back turned off. The problem was solved.

What was it?

**Comment by latenitefilms** [comment]
Unfortunately, that seems to be just the way macOS works. It seems even if a Mission Control shortcut is disabled, it will still clash with Hammerspoon.

See:
https://github.com/Hammerspoon/hammerspoon/issues/1296#issuecomment-290991614
https://github.com/Hammerspoon/hammerspoon/issues/1261#issuecomment-291380344
https://github.com/Hammerspoon/hammerspoon/issues/400#issuecomment-121942157
https://github.com/Hammerspoon/hammerspoon/issues/305#issuecomment-107105195
