### ISSUE TITLE
Better Error Messages for hs.hotkey?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1311]
Issues like #1310 seem to pop up quite a bit. I wonder if it's worth rewriting the `hs.hotkey` error messages to offer a bit more advice on how to fix when you get `RegisterEventHotKey failed` problems?

I wonder if it's worth checking the  `System Preferences -> Keyboard -> Shortcuts` values, and seeing if a clash already exists before even attempting to register the hotkey? [This](http://apple.stackexchange.com/questions/201816/how-do-i-change-mission-control-shortcuts-from-the-command-line) might be relevant?

Thoughts @cmsj & @asmagill ?

**Comment by rootscript** [comment]
@latenitefilms maybe you can use `defaults read com.apple.symbolichotkeys` to see if `enabled = 1`

**Comment by rootscript** [comment]
under the 3rd parameter I think this modifiers could get us started:
```
1179648:{cmd, shift},
1572864:{cmd, alt},
1835008:{cmd, ctrl, alt},
1441792{cmd, ctrl, shift},
1703936{cmd, alt, shift},
393216{ctrl, shift},
131072:{shift},
262144:{ctrl},
524288:{alt},
1048576:{cmd}
```

**Comment by cmsj** [comment]
I'm not thrilled about calling out to `defaults` from Hammerspoon, but we can certainly look into improving the error message to give people a hint about where to look.

**Comment by latenitefilms** [comment]
@cmsj - If your worry is relying on Terminal commands, you could just use `NSUserDefaults` in Objective-C land (until someone eventually adds a preferences reading/writing extension)?

**Comment by cmsj** [comment]
@latenitefilms a fair point, but I think it's largely unnecessary here - a decent error pointing the user in the right direction, seems like the best option here, IMHO.

**Comment by latenitefilms** [comment]
Works for me! Thanks @cmsj !

**Comment by ryan-williams** [comment]
Not sure if the above describes what I just observed.

System Preferences → Keyboard Shortcuts had _inactive_ hotkeys for e.g. `⌃→`, but Hammerspoon was giving me errors:

```
LuaSkin: hs.hotkey:enable() keycode: 124, mods: 0x1000, RegisterEventHotKey failed: -9878
LuaSkin: This hotkey is already registered. It may be a duplicate in your Hammerspoon config, or it may be registered by macOS. See System Preferences->Keyboard->Shortcuts
```

The offending keycodes didn't seem present in the output of `defaults read com.apple.symbolichotkeys`.

Changing the hotkeys in System Preferences to other key combos resolved the issue.

Seems strange that inactive hotkeys in System Preferences was causing Hammerspoon to not be able to use those hotkeys.
