### ISSUE TITLE
Drag & Drop to Dock Icon

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1319]
As discussed in #1057, it would be great to add a drag & drop to dock icon callback.

I'll give this a bash sometime.

**Comment by latenitefilms** [comment]
See: #1320

**Comment by cmsj** [comment]
fwiw, it's perfectly ok to leave the Issue open, and put "Closes: #1319" in the commit message of the pull request. github will then do the magic when the PR merges :)

**Comment by latenitefilms** [comment]
Ah, right of course! Sorry, will keep that in mind next time.
