### ISSUE TITLE
The dialog "Do you want to allow this page to open 'Hammerspoon'" always showed up in Safari

### ISSUE THREAD

**Issue by Ninlives** [Hammerspoon/hammerspoon#1322]
I'm using Tampermonkey and I want to write some user script using hammerspoon functions through url event, but the dialog keeps showing up and I have to manually click the confirm button every time. Is there a way to avoid this? Or maybe another way to silently call Hammerspoon functions in Safari?Thanks!

**Comment by cmsj** [comment]
AFAIK there is no way to prevent Safari from showing that dialog. It's generally a good thing that Safari is being cautious about passing URLs from the Internet to local apps, but it can be inconvenient some times. Perhaps a future version of Safari will allow us to whitelist particular apps.
