### ISSUE TITLE
AppleScript should raise an error if Lua code has errors

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1324]
Currently the AppleScript `execute lua code` function (see: #1177) will simply return the result from `MJLuaRunString`. This works great if you feed it good code (i.e. `execute lua code "1+1"` will return `2`), but it should really generate an error if there's a Lua error (i.e. currently `execute lua code "1++1"` will return a string value of `"[string \"1++1\"]:1: unexpected symbol near '1'"`). This will require either duplicating and modifying, or just modifying `MJLuaRunString`.

FYI: `HSAppleScript.m` already has an example of how you can raise an error in AppleScript.

**Comment by cmsj** [comment]
As mentioned on IRC, I don't want to tackle this in 0.9.53 because this is the wrong time to be messing with MJLuaRunString.

**Comment by asmagill** [comment]
I haven't looked closely at the applescript integration, but it may be better to build your own runstring specifically for use by the applescript bridge. `hs.ipc` basically does this to avoid having to put a lot of conditionals into MJLuaRunString and the `runString` function returned by `hs._coresetup`.

**Comment by latenitefilms** [comment]
Fine by me - but I fear that might be outside of my skillset, so might have to leave for you guys to finish. Unless I can just duplicate `MJLuaRunString`?

**Comment by asmagill** [comment]
I should be able to take a look at this in a day or so, if no one can any sooner.

**Comment by cmsj** [comment]
I believe this is now done.
