### ISSUE TITLE
Holding down space to act as cmd

### ISSUE THREAD

**Issue by winstonjz** [Hammerspoon/hammerspoon#1325]
Hi,

I'm trying to mimic the feature from Karabiner 'Use the space key as left command key when you press keys while holding the space key.'

I was looking at #1252 to use space instead of tab as a modifier.  E.G. space + tab = cmd + tab or event space + shift + t = cmd + shift + tab

Any help would be greatly appreciated

**Comment by cmsj** [comment]
I'm always very uneasy about using Hammerspoon to replicate Karabiner's features - they are a kernel level program which can modify input events before they are processed higher up the OS. We can't do that and I think it's always unreliable.

**Comment by cmsj** [comment]
I note that Karabiner Elements' beta releases now support complex keyboard modifications, and I would strongly urge people to use that instead of Hammerspoon, for this sort of thing :)
