### ISSUE TITLE
Updating spoon that's already installed

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1326]
Currently the only way to update a spoon is to first remove the existing folder from `~/.hammerspoon/Spoons`.

Should the user be prompted to confirm an overwrite/merge?
* If so, should also remind to reload Hammerspoon in case the spoon was previously in use.
* If not, we should have a link to a page describing how to remove the spoon so the update can be installed.

**Comment by cmsj** [comment]
Yeah this is a good point. I think that the only reasonable option is to remove the existing Spoon and move the new one in place.

I'm not sure about what to do about a reload notification, but I guess that is worth doing.
