### ISSUE TITLE
hs.application.find() with multiple matches

### ISSUE THREAD

**Issue by tonycpsu** [Hammerspoon/hammerspoon#1328]
The docs for `hs.application.find` describe its return value as:

    one or more hs.application objects for running applications that match the supplied search
    criterion, or nil if none found

However, when there are multiple matches, the return value seems to just be a single application.  The docs sort of hint at this behavior:

    But be careful when using it in your init.lua: terminal=hs.application'term' will assign either
    "Terminal" or "iTerm2" arbitrarily (or even, if neither are running, any other app with a window that
    happens to have "term" in its title);

but if `hs.application.find` isn't going to let me iterate through the matching apps, what is the point of it as compared to `hs.application.get`?

My use case is where I'm running multiple instances of the same app, as is possible with some apps, e.g. mpv media player.  If I have two mpv apps open, I get this:

    > hs.application.find("mpv")
     hs.application: mpv (0x61800064fcb8)	hs.application: mpv (0x618000648cf8)

But I don't know how to iterate through these to get the one I want.  If I try:

    for app in hs.application.find('mpv') do ...
I get:

    attempt to call a hs.application value

I apologize in advance if there's an easy answer to this that I'm just not finding.

**Comment by cmsj** [comment]
I agree this is a little unclear. What's actually happening is that `hs.application.find()` is returning multiple results. You can capture these into a table with:

```lua
foo = {hs.application.find("blah")}
```

I'll add a note to the docs to make this clearer.
