### ISSUE TITLE
Typo in librelease.sh?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1329]
@cmsj - Obviously it's not causing you issues when releasing, but just FYI..

`pushd "${HAMERSPOON_HOME}" >/dev/null` should be `pushd "${HAMMERSPOON_HOME}" >/dev/null` in [librelease.sh](https://github.com/Hammerspoon/hammerspoon/blob/master/scripts/librelease.sh#L165).

**Comment by cmsj** [comment]
Good catch, thanks!
