### ISSUE TITLE
hs.ipc.cliUninstall - Force Option?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1333]
This function is currently very conservative. I wonder if it's worth adding an optional "force" option, so that you can forcefully uninstall the CLI when things go funky?

Thoughts @cmsj ?

**Comment by cmsj** [comment]
@latenitefilms I'm curious what situation you're running into, that motivated filing this issue?

@asmagill IIRC we decided to be conservative about this to not tread on the toes of multiple Hammerspoon installations, but I'm wondering how reasonable that actually is - it's the kind of thing that's mostly just going to affect people doing local builds of Hammerspoon for development, and they ought to accept some level of discomfort from doing that (e.g. file/URL associations will tend to go to the wrong instance of Hammerspoon). When I'm doing local testing I just copy a Release build into `/Applications` to make sure I'm getting the authentic experience.

**Comment by latenitefilms** [comment]
@cmsj - Basically, I've never actually been able to get the `hs.ipc.cliUninstall` function to work - probably because I have so many random builds of Hammerspoon lying around. I generally just end up manually deleting in Terminal. I just want an easy option to delete the command line tools, regardless of which version of Hammerspoon installed them. Uninstall should always be able to uninstall.

**Comment by cmsj** [comment]
This was covered by e14e3939462bad2bbffe54857bb96e8094b6f0e8
