### ISSUE TITLE
How can I modify Hammerspoon to run a script automatically?

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1342]
I am trying to bundle my lua code with hammerspoon in such a way that the user can download one single binary and use it as though it were an application. So far I have my code in ~/.hammerspoon but don't really know where to start in terms of putting this in a place within the Hammerspoon source code so that it runs that instead?

**Comment by cmsj** [comment]
@z3t0 when Hammerspoon starts, it loads `setup.lua` from its app bundle, which these days mostly just loads `hs._coresetup`.

I would suggest that you put your Lua code in a new extension, and have `hs._coresetup` load that extension. There should be sufficient docs for adding a pure-Lua extension in our CONTRIBUTING.md.

(Also if you're going to publicly distribute a fork of Hammerspoon, which you are very welcome to do of course, we would appreciate it if you could change the name to avoid confusion :)

**Comment by latenitefilms** [comment]
@cmsj - I still feel like you should add a variables to Spoons, that allow you to auto-load a Spoon, if the developer so desires. This would mean there would be far less reasons to need to fork Hammerspoon.

**Comment by cmsj** [comment]
@latenitefilms I'm still really uncomfortable with that idea. Hammerspoon is trying to be a tool for people to get really deep into desktop automation - it's not supposed to be a platform for building opinionated distributions of automation functionality. Anyone is very welcome to fork it for their own purposes (including turning it into a platform), but it's not what Hammerspoon is for IMO.

**Comment by z3t0** [comment]
> (Also if you're going to publicly distribute a fork of Hammerspoon, which you are very welcome to do of course, we would appreciate it if you could change the name to avoid confusion :)

Will do!

**Comment by cmsj** [comment]
@latenitefilms having said all that, if there are things we can do to Hammerspoon that make it easier to fork (like your patch to look up the bundle ID dynamically), I'm very happy to include those.

**Comment by latenitefilms** [comment]
@cmsj - No problemo! I think #1357 could be really helpful in terms of forking. When I get some free time I'll look back through our CommandPost fork and see what things I needed to change to make it work, and what could have be done better/easier in retrospect (now that I'm slowly starting to understand GitHub and how everything works!).
