### ISSUE TITLE
Hold Command+Option on Launch to Trash Hammerspoon Preferences

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1348]
It would be great to have a really easy way to trash the Hammerspoon Preferences.

For example, Apple's Final Cut Pro allows you to hold down Command+Option when launching the app from the Dock to trash the preferences. The user will be presented with the attached dialog box to confirm.

<img width="532" alt="screen shot 2017-04-21 at 10 03 01 pm" src="https://cloud.githubusercontent.com/assets/22286696/25276677/a1b7cc8c-26de-11e7-81ac-73d72d7c35c4.png">

**Comment by chdiza** [comment]
How about just binding a hotkey to execute the right `hs.execute("defaults delete blah blah")` command?  To the extent that there is any need for such a frequent deletion, it's even handier to do it with a hotkey than a pulldown menu.

**Comment by latenitefilms** [comment]
@chdiza - You would still need to refresh the Preferences cache (`killall –u username cfprefsd`), and restart Hammerspoon for the changes to take place. I still think [cc378d8](https://github.com/latenitefilms/hammerspoon/commit/cc378d846ea287821ed52c8532bd60f7a2ce7653) is valid, but we'll just have to wait and see what @cmsj decides. No stress either way on my end, as I've added to my Hammerspoon fork anyway. I find myself regularly trashing the preferences for debugging/testing purposes, so I'm definitely a strange use-case.

**Comment by chdiza** [comment]
> You would still need to refresh the Preferences cache

Not if you use `defaults delete`.  The cache killing is only for if one tweaks the plist via some non-`defaults` mechanism.

If I was intent on having a "clean" running instance of HS to test something on, I'd restart HS after the pref-cleanout anyway.

**Comment by latenitefilms** [comment]
Ah, yes, you're absolutely right about the `defaults`.

Using a hotkey is also a good idea. I still like the Command+Option shortcuts though, as it keeps things consistent with Apple's ProApp's, and it'll just make end-user support easier if you do need them to trash preferences. This probably isn't relevant for Hammerspoon though.
