### ISSUE TITLE
Changing Webview Size without "resizable" enabled?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1352]
Currently it's only possible to use `hs.window:setFrame` and `hs.window:setSize` on `hs.webview:hswindow` if `hs.webview.windowMasks` contains `resizable`.

However, I would like a `hs.webview` to be fixed from the users perspective, but still be able to change it's size programatically.

I tried changing `hs.webview:windowStyle` to `resizable` and back again, but that gets rid of the `hs.webview:toolbar`, which is not ideal. Adding the toolbar back in seems to crash Hammerspoon.

Any ideas?

**Comment by latenitefilms** [comment]
Any suggestions @asmagill or @cmsj ?

**Comment by asmagill** [comment]
The crash is definitely a concern... I'll look into it tonight.

As to the resizing... Since we don't have this issue with drawing/canvas, I'm going to guess that it's because `hs.window` uses accessibility methods to resize windows while canvas and drawing change the underlying NSPanel object directly... which can be added to webview... I should also be able to address this tonight.

**Comment by latenitefilms** [comment]
Amazing - thanks @asmagill !

**Comment by asmagill** [comment]
@latenitefilms, I cannot replicate the crash you mention when reassigning the toolbar after cycling through not-resizable -> resizable -> not-resizable.

Can you provide more details re the crash and/or what you did?  I know you said the additions in #1359 would obviate the workaround, but any crash that can be replicated/identified is of interest -- we want to prevent them if at all possible!

**Comment by latenitefilms** [comment]
Basically I had a function that:

* Changed the webview to resizable
* This made the existing toolbar disappear
* Resized the webview programatically
* Changed the webview to not resizable
* Added the original toolbar back in
* Hammerspoon would then freeze my whole computer doing this, and I needed to force shutdown

Once this happened twice, I basically just gave up, and just left the webview as resizable.

Hope this helps?

**Comment by asmagill** [comment]
Not really because that's exactly what I did as well...

~~~lua
resizeWebview = function(wv, tbl)
    local tb = wv:attachedToolbar()
    wv:windowStyle(wv:windowStyle() | hs.webview.windowMasks.resizable)
    wv:hswindow():setFrame(tbl)
    wv:windowStyle(wv:windowStyle() & ~hs.webview.windowMasks.resizable)
    wv:attachedToolbar(tb)
    return wv
end
~~~

Anything I missed in this sample function I used?

**Comment by latenitefilms** [comment]
I don't have the code I was using on me, but I think I was doing something like:

```
mod.webview:windowStyle({"titled", "closable", "nonactivating", "resizable"})
mod.webview:hswindow():setSize({w = mod.defaultWidth, h = v.height })
mod.webview:windowStyle({"titled", "closable", "nonactivating"})
mod.webview:toolbar(mod.toolbar)
```

**Comment by asmagill** [comment]
Nope... still works on mine... I was wondering if there was a problem with the code which parsed the table, but using the labels as you spell them out worked fine for me.  Unless you want to keep poking at it and find a way to replicate it, I'm comfortable calling this one a fluke based on unknown circumstances... with a freeze I can't even check to see if Craslytics/Fabric received anything I can identify, so...

BTW, I changed the method from `hs.webview:toolbar` to `hs.webview:attachedToolbar` (your last line above)... the original name matches the `hs.webview.toolbar` submodule in the documentation so one (usually the method) was getting left out each time the documentation file was being parsed... you'll need to change when you upgrade to 0.9.53 -- sorry for breaking backwards compatibility without warning!

**Comment by latenitefilms** [comment]
All good - I'm more than happy to just assume I was doing something really funky in my code!

Either way, it shouldn't matter now anyway, as I can just use `hs.webview:size` to resize, even if the webview's window mask doesn't include `hs.webview.windowMasks.resizable`, which is perfect!

Thanks so much for all your help and testing! I look forward to you pressing the "merge" button!
