### ISSUE TITLE
extensions with multiple files

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1354]
Hi 

I created an extension with init.lua which loads other files e.g. window.lua. This worked fine when it was under ~/.hammerspoon but now using require makes it look for the file in ~/.hammerspoon even  though the init file is an extension in hammerspoon, how do i get it to load a file in the extension.

eg..
extension/ext/init.lua
extension/ext/window.lua

in init.lua
```lua
---

require("window")
---
```

**Comment by latenitefilms** [comment]
Try: require("extension.ext.window")

**Comment by z3t0** [comment]
Tried that no luck hmm

```
	no file '/Users/z3t0/Library/Developer/Xcode/DerivedData/Hammerspoon-gwmnxzafgdaerrfpjbfyfnynzwha/Build/Products/Debug/Hammerspoon.app/Contents/Resources/extensions/zwm/utilities.lua'
```
is given in the output even though that file does exist...

**Comment by z3t0** [comment]
got it!
