### ISSUE TITLE
Localise Hammerspoon

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1357]

**Comment by latenitefilms** [comment]
FYI: I'll give this a bash sometime over the coming months.

**Comment by cmsj** [comment]
@latenitefilms is this still something that interests you? I'm very unlikely to have the time to work on it, so unless you think you're going to, I suggest we close this.

**Comment by latenitefilms** [comment]
Yeah, keep it open for now, and I'll close it if it ends up being something I definitely won't do.

**Comment by latenitefilms** [comment]
I can't see myself tackling this anytime soon, so I'm going to close this issue for now. If anyone's up for the challenge, feel free to re-open it!
