### ISSUE TITLE
hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.leftMouseDragged}, { 10, 10 })

### ISSUE THREAD

**Issue by joyspce** [Hammerspoon/hammerspoon#1358]
hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.leftMouseDragged}, { 10, 10 })
        hs.timer.usleep(1000);
        hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.rightMouseUp}, { 10, 10 })

2017-04-24 07:49:14: Error: unrecognised mouse button eventtype: table: 0x610000c6d700

hello, dear author, why do I use this code, alway get that error? please help

**Comment by asmagill** [comment]
for `newMouseEvent`, the first argument is an integer, not a table (i.e. `hs.eventtap.event.types.leftMouseDragged`, not `{hs.eventtap.event.types.leftMouseDragged}`)

**Comment by joyspce** [comment]
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, { 10, 10 })
hs.timer.usleep(1000)
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, { 10, 10 })

thanks asmagill 
When I  use this code, get that error, I did try so many times  

2017-04-24 17:28:11: ********
2017-04-24 17:28:11: 17:28:11 ERROR:   LuaSkin: hs.hotkey callback error: ...n.app/Contents/Resources/extensions/hs/eventtap/init.lua:131: bad argument #-1 to '_newMouseEvent' (number expected, got nil)
stack traceback:
	[C]: in function 'hs.eventtap.event._newMouseEvent'
	...n.app/Contents/Resources/extensions/hs/eventtap/init.lua:131: in function 'hs.eventtap.event.newMouseEvent'
	/Users/joys/.hammerspoon/init.lua:52: in function </Users/joys/.hammerspoon/init.lua:48>
2017-04-24 17:28:11: ********

**Comment by cmsj** [comment]
```hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, { 10, 10 })```

The first argument is right now, but the second isn't - try `{ x=10, y=10 }` :)

**Comment by cmsj** [comment]
Oh, also, all newMouseEvent() does is *create* an event, it doesn't actually insert it into the event stream, you should add `:post()` on the end of each call, so the complete working version would be:

```lua
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, { x=10, y=10 }):post()
hs.usleep(1000)
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, { x=10, y=10 }):post()

```

**Comment by joyspce** [comment]
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseDown, { x=10, y=10 }):post()
hs.usleep(1000)
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.leftMouseUp, { x=10, y=10 }):post()

this code worked perfect,  thanks cmsj a lot
