### ISSUE TITLE
API docs formatting

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#136]
http://www.hammerspoon.org/docs/hs.milight.html is an example of how I think we should format API docs (but with parameter names (and return values?) monospaced)

**Comment by asmagill** [comment]
Is there a specific reason (tool?) for using this expanded format?  Basically, should I take the time to update existing modules I've written, or just make sure I use it in new or updated modules?

This is not a complaint -- I like the format and think it's a good idea, just... not looking forward to updating already existing schtuff just for form's sake...

**Comment by cmsj** [comment]
It's really just part of a theme of consistency I have in my head. Right now there's no tooling reason.

You don't necessarily need to worry about the things that are already in-tree, I've already started converting them and will continue to do so - it's my mess, so I'm cleaning it up ;)

**Comment by cmsj** [comment]
Reminder to self: add mention of formatting for optional arguments, to CONTRIBUTING.md, and re-visit the already updated extensions to apply that.

(Since I forgot in one of the extensions I updated earlier :)

**Comment by asmagill** [comment]
trying to build from pull today (both from command line Makefile and from within Xcode 6.1.1:

PhaseScriptExecution Compile\ docs.json /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-cnumkdcgfqpvcechcwthlkbpsnbc/Build/Intermediates/Hammerspoon.build/Debug/Hammerspoon.build/Script-4FC09F7A19F99E48007542A6.sh
    cd /opt/amagill/src/hammerspoon/hammerspoon-local
    export ACTION=build
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=amagill
    export ALWAYS_SEARCH_USER_PATHS=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS=YES
...
    export VERSION_INFO_STRING="\"@(#)PROGRAM:Hammerspoon  PROJECT:Hammerspoon-\""
    export WRAPPER_EXTENSION=app
    export WRAPPER_NAME=Hammerspoon.app
    export WRAPPER_SUFFIX=.app
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=6A2008a
    export XCODE_VERSION_ACTUAL=0611
    export XCODE_VERSION_MAJOR=0600
    export XCODE_VERSION_MINOR=0610
    export XPCSERVICES_FOLDER_PATH=Hammerspoon.app/Contents/XPCServices
    export YACC=yacc
    export arch=x86_64
    export variant=normal
    /bin/sh -c /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-cnumkdcgfqpvcechcwthlkbpsnbc/Build/Intermediates/Hammerspoon.build/Debug/Hammerspoon.build/Script-4FC09F7A19F99E48007542A6.sh

find . -type f \( -name '*.lua' -o -name '*.m' \) -not -path '*/sample-extensions/*' -not -path './build/*' -not -path './extensions/.build/*' -exec cat {} + | scripts/docs/bin/gencomments | scripts/docs/bin/genjson > build/docs.json
error: couldn't find module for Notes:
make: *** [build/docs.json] Error 1


I'm thinking the code which tries to identify function names is choking on the the fact that new docstrings also contain : after a single word (i.e. no spaces) at the beginning of a line and is mis-identifying them as functions... probably will need to update hs.docs as well, but I'll wait to see what ends up getting changed in the core so they remain in sync.

**Comment by cmsj** [comment]
My bad, I mistyped a line of docstrings as -- instead of ---. Fixed by 60c5017

**Comment by asmagill** [comment]
oops!  Guess i didn't look closely enough!  That fixed it.  Thanks!

**Comment by cmsj** [comment]
Extensions still to reformat the docstrings for:

 * [ ] hs
 * [ ] hs.application.watcher
 * [ ] hs.battery.watcher
 * [ ] hs.eventtap.event
 * [ ] hs.fs
 * [ ] hs.geometry
 * [ ] hs.grid
 * [ ] hs.hotkey
 * [ ] hs.hotkey.modal
 * [ ] hs.inspect
 * [ ] hs.ipc
 * [ ] hs.itunes
 * [ ] hs.json
 * [ ] hs.keycodes
 * [ ] hs.layout
 * [ ] hs.location
 * [ ] hs.milight
 * [ ] hs.mjomatic
 * [ ] hs.pasteboard
 * [ ] hs.pathwatcher
 * [ ] hs.screen
 * [ ] hs.screen.watcher
 * [ ] hs.settings
 * [ ] hs.sound
 * [ ] hs.spotify
 * [ ] hs.timer
 * [ ] hs.uielement
 * [ ] hs.uielement.watcher
 * [ ] hs.utf8_53
 * [ ] hs.wifi
 * [ ] hs.wifi.watcher
