### ISSUE TITLE
hs.application:path() returns incorrect result

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1360]
As mentioned on IRC @cmsj ...

I have multiple versions of Final Cut Pro currently installed on my machine (as Apple has broken a bunch of stuff in the latest release, so I'm jumping back and forth between 10.3.3 and 10.3.2).

If I have 10.3.2 open, `hs.application.get("com.apple.FinalCut")` returns the correct `hs.application` instance, however `hs.application.get("com.apple.FinalCut"):path()` returns the incorrect path (as it just grabs the highest version number of the application with that bundle ID - so in this case it's giving me the 10.3.3 path, even though 10.3.2 is open). This is because internally `hs.application:path()` is using `absolutePathForAppBundleWithIdentifier`.

Is this fixable @asmagill ?

**Comment by latenitefilms** [comment]
Here's a temporary workaround:

```
function getPathToApplicationFromPID(pid)
	local appleScript = [[
 		tell application "System Events"
			return POSIX path of application file of every application process whose unix id is ]] .. tostring(pid) .. "\n\n" .. [[
		end tell
	]]
 	local success, result = osascript.applescript(appleScript)
	if success and result and result[1] then
		return tostring(result[1])
	else
		return nil
	end
end
```

**Comment by cmsj** [comment]
I think I have a way to fix `:path()` - will look at it this evening

**Comment by latenitefilms** [comment]
Legend, thanks mate!

The AppleScript seems to be doing the job for now - but would be good to avoid AppleScript if possible. Seriously appreciate all your help!

**Comment by latenitefilms** [comment]
Thank you!!
