### ISSUE TITLE
loadSpoon doesn't expose spoon to global namespace

### ISSUE THREAD

**Issue by kballard** [Hammerspoon/hammerspoon#1361]
The docs for [`hs.loadSpoon(NAME)`](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#loading-a-spoon) says that it makes the spoon available to the global namespace as `NAME`. But AFAICT it actually doesn't do that. If I say something like

```lua
hs.loadSpoon("Seal")
print(Seal)
```

it just prints `nil` to the console.

**Comment by cmsj** [comment]
it's loaded as `spoon.NAME`, so in this case, `spoon.Seal` :)

**Comment by kballard** [comment]
In that case the documentation is wrong. It explicitly says

> This will make the spoon available in the global Lua namespace as `NAME`.

**Comment by cmsj** [comment]
Where are you seeing that? This gets mentioned in several places and I guess I missed one :/

**Comment by kballard** [comment]
https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#loading-a-spoon

**Comment by cmsj** [comment]
Thanks :)
