### ISSUE TITLE
hs.application require question?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1365]
Is there any reason:

`local uielement = hs.uielement  -- Make sure parent module loads`

...is not:

`local uielement = require("hs.uielement")`

in `hs.application`?

I'm trying to track down a rogue `-- Loading extension: uielement` in my console.

I also have a rogue `-- Loading extension: window` which I can't track down.

Thoughts @asmagill & @cmsj ?

**Comment by cmsj** [comment]
hs.application, hs.window and hs.uielement are almost indivisible at this point. They're three of our oldest modules and are a bear trap of subtlety. I fear to change things there and suspect a full rewrite may be needed.

**Comment by cmsj** [comment]
(Also we'll probably change those module loading messages to being hidden by default)

**Comment by latenitefilms** [comment]
Haha, no worries.

Maybe it's because I've spent too much time looking at @asmagill's posts and code examples, but I also use the Console for a way of finding things that are "incomplete" and the `-- Loading extension:` messages just mean that something hasn't been "loaded" properly.

I guess it doesn't really matter, but I feel like hiding the debug message doesn't really solve the issue it just hides it away.

For development, I generally have the `hs.logger` level set to `debug` anyway, so I would still see these messages in the Console.
