### ISSUE TITLE
Assign value / specify to clipboard/pasteboard items?

### ISSUE THREAD

**Issue by emg80** [Hammerspoon/hammerspoon#1371]
Is there a way to specify a particular pasteboard/clipboard item?

Sorry if this has already been asked, been browsing around for a few hours and can't seem to put together a solution!

The plan is to create a key bind using the num keys to denote each clipboard item [(see image)](http://i.imgur.com/J9pxIQx.png)

What I have so far (not a lot, I know!:)

```lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "5", function()
hs.eventtap.keyStrokes(hs.pasteboard.getContents())
hs.alert.show("Paste test done")
end)
```

Default returns the first item on the pasteboard - Returns/pastes 'A'

Ideally "5" would return/paste 'E' ( "6"='F' , "7"='G' etc)

Any help is really appreciated!

**Comment by cmsj** [comment]
when you say pasteboard *item*, what do you mean exactly? If you mean pasteboard history, you're going to need to do a little more work I'm afraid, we don't keep track of pasteboard history.

Or do you mean the different file type representations of the current pasteboard item?

**Comment by emg80** [comment]
Thanks for your reply and sorry for not clarifying properly/clearly.

Currently my init.lua provides the pasteboard functionality to my main menu bar (see sceenshot above).
It is set to remember the past 20 copied items, and is persistent between relaunching hs/system.

#######################
local frequency = 0.8 -- Speed in seconds to check for clipboard changes.
local hist_size = 20 -- How many items to keep on history
local label_length = 40 -- How wide (in characters) the dropdown menu should be. Copies larger than this will have their label truncated and end with "…" (unicode for elipsis ...)
local honor_clearcontent = false --asmagill request. If any application clears the pasteboard, we also remove it from the history https://groups.google.com/d/msg/hammerspoon/skEeypZHOmM/Tg8QnEj_N68J
local pasteOnSelect = true -- Auto-type on click

-- Don't change anything bellow this line
local jumpcut = hs.menubar.new()
jumpcut:setTooltip("Jumpcut replacement")
local pasteboard = require("hs.pasteboard") -- http://www.hammerspoon.org/docs/hs.pasteboard.html
local settings = require("hs.settings") -- http://www.hammerspoon.org/docs/hs.settings.html
local last_change = pasteboard.changeCount() -- displays how many times the pasteboard owner has changed // Indicates a new copy has been made

--Array to store the clipboard history
local clipboard_history = settings.get("so.victor.hs.jumpcut") or {} --If no history is saved on the system, create an empty history

-- Append a history counter to the menu
function setTitle()
  if (#clipboard_history == 0) then
    jumpcut:setTitle("✂") -- Unicode magic
    else
      jumpcut:setTitle("✂ ("..#clipboard_history..")") -- updates the menu counter
  end
end

function putOnPaste(string,key)
  if (pasteOnSelect) then
    hs.eventtap.keyStrokes(string)
    pasteboard.setContents(string)
    last_change = pasteboard.changeCount()
  else
    if (key.alt == true) then -- If the option/alt key is active when clicking on the menu, perform a "direct paste", without changing the clipboard
      hs.eventtap.keyStrokes(string) -- Defeating paste blocking http://www.hammerspoon.org/go/#pasteblock
    else
      pasteboard.setContents(string)
      last_change = pasteboard.changeCount() -- Updates last_change to prevent item duplication when putting on paste
    end
  end
end

-- Clears the clipboard and history
function clearAll()
  pasteboard.clearContents()
  clipboard_history = {}
  settings.set("so.victor.hs.jumpcut",clipboard_history)
  now = pasteboard.changeCount()
  setTitle()
end

-- Clears the last added to the history
function clearLastItem()
  table.remove(clipboard_history,#clipboard_history)
  settings.set("so.victor.hs.jumpcut",clipboard_history)
  now = pasteboard.changeCount()
  setTitle()
end

function pasteboardToClipboard(item)
  -- Loop to enforce limit on qty of elements in history. Removes the oldest items
  while (#clipboard_history >= hist_size) do
    table.remove(clipboard_history,1)
  end
  table.insert(clipboard_history, item)
  settings.set("so.victor.hs.jumpcut",clipboard_history) -- updates the saved history
  setTitle() -- updates the menu counter
end

-- Dynamic menu by cmsj https://github.com/Hammerspoon/hammerspoon/issues/61#issuecomment-64826257
populateMenu = function(key)
  setTitle() -- Update the counter every time the menu is refreshed
  menuData = {}
  if (#clipboard_history == 0) then
    table.insert(menuData, {title="None", disabled = true}) -- If the history is empty, display "None"
  else
    for k,v in pairs(clipboard_history) do
      if (string.len(v) > label_length) then
        table.insert(menuData,1, {title=string.sub(v,0,label_length).."…", fn = function() putOnPaste(v,key) end }) -- Truncate long strings
      else
        table.insert(menuData,1, {title=v, fn = function() putOnPaste(v,key) end })
      end -- end if else
    end-- end for
  end-- end if else
  -- footer
  table.insert(menuData, {title="-"})
  table.insert(menuData, {title="Clear All", fn = function() clearAll() end })
  if (key.alt == true or pasteOnSelect) then
    table.insert(menuData, {title="Direct Paste Mode ✍", disabled=true})
  end
  return menuData
end

-- If the pasteboard owner has changed, we add the current item to our history and update the counter.
function storeCopy()
  now = pasteboard.changeCount()
  if (now > last_change) then
    current_clipboard = pasteboard.getContents()
    -- asmagill requested this feature. It prevents the history from keeping items removed by password managers
    if (current_clipboard == nil and honor_clearcontent) then
      clearLastItem()
    else
      pasteboardToClipboard(current_clipboard)
    end
    last_change = now
  end
end

--Checks for changes on the pasteboard. Is it possible to replace with eventtap?
timer = hs.timer.new(frequency, storeCopy)
timer:start()

setTitle() --Avoid wrong title if the user already has something on his saved history
jumpcut:setMenu(populateMenu)

#######################

In theory, if I could assign a value to each item on the board, I could then bind this to keys as outlined above?

**Comment by cmsj** [comment]
So it kinda sounds like all you'd need to do is look for a specific entry in your pasteboard history table?

If you did something like

```lua
function pasteItem(item)
  return function()
    hs.eventtap.keyStrokes(clipboard_history[item])
  end
end
hs.hotkey.bind({foo}, "5", pasteItem(5))
```

that ought to work I think?
