### ISSUE TITLE
Discussion: spoon utilities module

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#1376]
I think it would be nice to have an `hs.spoon` library as part of HS, to hold spoon-related utilities. Some such utilities could include:
- `hs.spoon.install(name-or-URL)` - install, either from the main repo or from a given URL
- `hs.spoon.uninstall(name)`
- `hs.spoon.template(name, metadata, basedir)` - generate a new spoon skeleton
- other functions to operate/search on the official `docs.json` or on others that conform to the same format.

I think having this functionality could go a long way to enabling more automated management of Spoons, and also to allow having multiple Spoon repositories so that not everything has to be merged into the main repo.

These could also be implemented a a Spoon if you don't want to have this in the HS core.

**Comment by zzamboni** [comment]
Other ideas:
- `hs.spoon.script_path()` so not everyone has to copy it off https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md :)
- Some common way of implementing keybindings so not everyone has to reimplement it. I'm still thinkin about how this could be done, but some table declaration of binding names and functions comes to mind.

**Comment by zzamboni** [comment]
I have opened https://github.com/Hammerspoon/Spoons/pull/8 to demonstrate some of these functions. In particular I think `bindHotkeysToSpec` would be very useful for Spoon developers.

**Comment by cmsj** [comment]
@zzamboni did we cover all of this in hs.spoons? If so, could you close this issue out please? :)

**Comment by zzamboni** [comment]
Yes, it's covered. Closing.
