### ISSUE TITLE
Ability to add items to main hammerspoon menubar menu

### ISSUE THREAD

**Issue by ddfisher** [Hammerspoon/hammerspoon#1377]
As far as I can tell from reading the docs, there's currently no way to add new menu items to the main hammerspoon menubar menu (i.e. the menu on the icon that appears when the "Show menu icon" preference is checked).  I'd like to add some toggleable checkmarks there that control aspects of my hammerspoon config, but would prefer not to have another menubar entry just for that.

I didn't see anything about this in the docs or the tracker.  Is this currently not possible, or am I missing something?

**Comment by cmsj** [comment]
It's somewhat intentionally not possible, to prevent config errors from breaking the menu.

There should be enough API in the main `hs` module to recreate the menu yourself though, with `hs.menubar`
