### ISSUE TITLE
Addition to hs.image?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1378]
It would be good to have some more controls in `hs.image` for manipulating sizes, etc.

https://github.com/tnodir/luafreeimage

**Comment by cmsj** [comment]
I would suspect that we could do a lot of that stuff with the native NSImage/CoreGraphics features of macOS.

I don't have much time to work on non-specific enhancements at the moment, but perhaps specific issues for features you need might get some traction from interested parties :)
