### ISSUE TITLE
Network configuration extension

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#138]
SystemConfiguration provides a useful framework for introspecting and monitoring network configuration in OSX. It would be fun to have this for multiple reasons:
- Reacting to state changes (e.g. when a particular interface is activated/deactivated, or when the default route changes)
- Introspecting current state (e.g. if an extension needs to know the broadcast IP of a subnet the machine is connected to)
- Internet Reachability testing

http://stackoverflow.com/questions/11532144/how-to-detect-ip-address-change-on-osx-programmatically-in-c-or-c has some examples (albeit not using the C API), also see the SystemConfiguration framework docs.

**Comment by junkblocker** [comment]
:+1: After having replaced the **Caffeine**, **UnPlugged** and **BetterTouchTool** apps with **Hammerspoon** within a few hours of discovering it, I now want to get rid of **ControlPlane** too and this feature is needed to be able to do that (without resorting to very inefficient and/or constant parsing of `netstat` output myself as I am not an `Obj-C/Lua` guy) :smile: .
