### ISSUE TITLE
Simulate Drag & Drop?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1383]
@asmagill or @cmsj - do you know if it's possible to simulate a drag and drop event?

For example, in Final Cut Pro, you can drag and drop a file from the Finder to an Library and/or Event in Final Cut Pro which imports this file into the Event. Is there anyway to do this programatically without having to physically drag and drop using the mouse?

Another example is that this GitHub page allows you to drag and drop items from Finder to the "attach files" drop zone. Obviously in this example there are other ways to achieve this same thing, but is there a way I could do this programatically?

I'm assuming dragging and dropping is using the Pasteboard API?

Any words of wisdom?

**Comment by cmsj** [comment]
Are you saying you want to be able to initiate a DnD from one application to another, where neither of those is Hammerspoon? I'm not sure that's going to be possible beyond simulating mouse events.

**Comment by latenitefilms** [comment]
Yeah, that basically what I want - and I know it might not be possible - however there was something @asmagill wrote a while back (about how dragging and dropping uses the Pasteboard API), made me think that MAYBE it could be done with some really clever Pasteboard/GUI Scripting manipulation?

**Comment by asmagill** [comment]
At best, *maybe* we could create an NSDraggingSession for views within Hammerspoon (webview, canvas, etc), but you'd still need to use eventtap to move it to the destination and release it... you wouldn't be able to initiate a drag for anything that Hamemrspoon didn't create.

Easier to just replicate the events and let the OS handle the behind the scenes stuff.

**Comment by latenitefilms** [comment]
No worries - given this, I'll close this issue and re-think things. Thanks anyway!
