### ISSUE TITLE
Hammerspoon Docs Search doesn't work.

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1384]
The search feature on the [Docs page](http://www.hammerspoon.org/docs/index.html) doesn't work. Error message attached.

<img width="1327" alt="screen shot 2017-05-01 at 7 35 52 pm" src="https://cloud.githubusercontent.com/assets/22286696/25576870/6e405ae4-2ea5-11e7-89d3-ee710354f87c.png">

**Comment by cmsj** [comment]
Thanks, this should be fixed on the website and in the release script.
