### ISSUE TITLE
[Question] How I could switch between Sierra's tabs

### ISSUE THREAD

**Issue by AlexVKO** [Hammerspoon/hammerspoon#1387]
Hey guys,

I'm wondering how I could operate this new tabs on sierra, I din't find any native shortcuts to operate this, so I've tried to do it with Hammerspoon. 

## This is the tabs (the above one):
![screen shot 2017-05-01 at 10 30 07 pm](https://cloud.githubusercontent.com/assets/8848152/25600943/9853a502-2ebe-11e7-9bc1-4e4a09106863.JPG)

## I tried as follows:
```lua
-- Open application
app = hs.application.find('Atom Beta')
hs.application.launchOrFocus('Atom Beta')

-- Enable tabs (not sure if it's really necessary)
hs.tabs.enableForApp(app)

-- Focus tab (it should focus the last tab)
hs.tabs.focusTab(atom, 10)
``` 

Problem:
-- The application is opened, but the tab is not changed.

## Just a screenshot of the execution:
![screen shot 2017-05-01 at 10 40 35 pm](https://cloud.githubusercontent.com/assets/8848152/25601023/3c018a8e-2ebf-11e7-93fc-03d3818cba5a.JPG)

Thanks guys!

**Comment by duskwuff** [comment]
`hs.tabs` doesn't interact with Sierra-style tabbed windows. It's a completely separate feature -- it's created the little thing in the upper right of the window's titlebar.

**Comment by cmsj** [comment]
I think the NSDocument automatic tab feature in Sierra is actually still visible to us as though the tabs were separate windows. I've not tried it, but perhaps they can be focused like regular windows?

**Comment by AlexVKO** [comment]
@duskwuff 
you're right dude, thanks for clarifying!

@cmsj 
Sorry about the delay,

I just tried, and no, it doesn't work... the returned list of windows doesn't display tabs, it displays only the active tab as a window...

Any thoughts ? maybe a feature request?

**Comment by cmsj** [comment]
We've just included hs.application:focusTab() in 0.9.56, which I think should cover this :)
