### ISSUE TITLE
Feature request - more methods for hs.eventtap.event

### ISSUE THREAD

**Issue by duskwuff** [Hammerspoon/hammerspoon#1389]
The following CGEvent methods are not available through `hs.eventtap.event`. Having them available would make it much easier to synthesize specific types of events.

- [ ] CGEventCreate
- [ ] CGEventSetType
- [ ] CGEventGetLocation and CGEventSetLocation

(I'm specifically trying to synthesize "swipe" events to remap buttons 4 and 5 on a USB mouse to back/forward actions. There's probably a lot of other things these methods would be useful for, though!)

**Comment by asmagill** [comment]
These are part of a replacement I want to write for eventtap, but getting that right is taking longer than I thought without breaking things or introducing other issues that I don't have a fix for yet.

I'll see about getting these added to the existing core module later tonight/tomorrow.
