### ISSUE TITLE
Implement Crash Reporter privacy

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#139]
The core we inherited from Mjolnir is very stable, but it's likely that we have bugs in some of the extensions. It would be good to have a crash reporter in HS, preferably one that submits to a free service!

**Comment by asmagill** [comment]
I've been away a bit, and I've not looked too closely at the crashlytics code yet, so if this is posted somewhere, please let me know so I can review it... does HS have a way to disable crash reporting?  A posted privacy policy about what is being sent when a crash occurs? As with anything that goes on behind the scenes, collecting user data should always be an opt in ( or at a minimum provide a way to opt out ) kind of thing.

Sorry if this is covered elsewhere... it just hit me that I hadn't seen anything like this addressed anywhere yet...

**Comment by cmsj** [comment]
@asmagill we are currently failing to live up to expectations on the crash reporting front. It was pushed in swiftly to handle a rising tide of awful crash bugs, but the failure to get it properly exposed to users, is entirely mine, and I apologise for that.

I would strongly prefer it to be opt-out, because I fear that opt-in will drastically reduce the quantity of crash reports we get. However, if people feel strongly in the other direction, then I will blame them for unfixable crash bugs, and make it opt-in ;)

Let's re-open this issue and figure out how we present this

**Comment by cmsj** [comment]
So, how about another entry in the prefs window, of the form:

    [✔] Send anonymous crash reports

Perhaps then a little __Privacy Policy__ link underneath it, which goes to something on www.hammerspoon.org with some painfully non-legalese that says "This is what gets collected, it's hosted by Crashlytics.com (part of Twitter), we will never sell or give the data to anyone else, here is Crashlytics' privacy policy"

Thoughts?

**Comment by asmagill** [comment]
Personally, I prefer opt-in things, but I'm fine with opt out, as long as it's in a reasonably easy place to see... the prefs dialog is perfect -- you're guaranteed to see it at least once when you first install HS.  I understand the need for good crash data, especially as a programmer, but I really don't like when things aren't transparent...

It's not that I disagree with the purpose... it just struck me that I don't know much about how it works or what it collects, and realized that this is the kind of thing that so many complain about with regards to privacy!  We definitely don't want anyone shying away from HS because of uncertainty.

**Comment by cmsj** [comment]
@Asmagil completely agreed. I should have tackled this much earlier.

FWIW I feel very conflicted about the default state of the checkbox. I would prefer it to be opt-in, but the numbers I've seen show that would have a massively negative impact on the number of people submitting crash reports. I think opt-out is ok, because as you say, it's right there in the first run prefs window.

**Comment by cmsj** [comment]
@asmagill What do you think about 47dbd78 ? It should cover our needs here, I think. Similarly, what do you think about the contents of http://www.hammerspoon.org/privacy.html ?

**Comment by asmagill** [comment]
Looks good to me!  I'm ok with closing this again unless anyone else has anything else to add.

**Comment by cmsj** [comment]
@asmagill cool, thanks. I'd like @Habbie to chime in, particularly on the Privacy Policy, before closing the issue.

**Comment by cmsj** [comment]
07:06:49 <@Habbie> Ng, the privacy policy appeared to be missing a lot of full stops at end of sentences when i read it last night
07:06:55 <@Habbie> Ng, otherwise it looks great :)

closing :)
