### ISSUE TITLE
hs.fs - Support for Reading/Writing Extended Attributes?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1394]
It would be great if we could do the same things [xattr](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/xattr.1.html) can do, directly from the `hs.fs` extension.

**Comment by asmagill** [comment]
This looks interesting... Not sure exactly when/if I'll get to it, so if someone wants to beat me to it, it looks like you should start with the functions in `/usr/include/sys/xattr.h`

(the xattr command looks to be a python wrapper to these or something similar, see https://github.com/xattr/xattr and `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/`)

**Comment by asmagill** [comment]
Should be addressed in #1515, reopen if you discover outstanding issues.
