### ISSUE TITLE
hs.speech:speakToFile() - WAV File?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1395]
Would it be possible to add an option to `hs.speech:speakToFile` to output a `WAV` file instead of an `AIFF`?

**Comment by asmagill** [comment]
`NSSpeechSynthesizer`, which this module is based on, does not support choosing the output file type.  Unless someone wants to work on a conversion module, I'd look at using `ffmpeg` which you can get from various places, including Homebrew.

**Comment by latenitefilms** [comment]
No worries - I thought that might be the case. Thanks anyway @asmagill !
