### ISSUE TITLE
hs.speech:speakToFile() Suggestion

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1397]
Currently `hs.speech:speakToFile(textToSpeak, destination)` returns the synthesizer object.

However it would be way more useful if it returned the path to the generated file if successful, otherwise `nil` if an error occurred (or better yet, and error message).

Thoughts @asmagill ?

**Comment by asmagill** [comment]
IIRC this method still has to go through the synthesizing process so it's not guaranteed that it won't error out along the way... you need to keep the object around until `hs.speech:speaking()` returns true or the callback (if set) receives "didFinish".

**Comment by latenitefilms** [comment]
Awesome, thanks! I'll experiment with the callback and see what I can come up with!
