### ISSUE TITLE
Path to Resource URL?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1401]
Is there an easy way to convert a path (i.e. `~/Desktop/Test Folder/[CrazY!]-Fi!En@ME.tmp`) to a resource URL (for use in `hs.pasteboard.writeObjects`)?

I've tried using `hs.http.encodeForQuery`, which works for simple cases, but doesn't work once you throw in crazy (but valid) symbols in the filename.

Thoughts @asmagill ?

**Comment by latenitefilms** [comment]
Here's a better example of a crazy filename (that's valid in macOS):

`[[inpt TUNE]] ~ AA {D 120; P 176.90 171.422 161.761} r {D 60; P 166.70} ~ y {D 210; P 161.00} UW {D 70; P 178.50} _ S {D 290; P 173.30 178.28 184.919 222.981} 1AX {D 280; P 234.50 246.139} r {D 170; P 264.20} ~ y {D 200; P 276.90 274.917 271.050} UW {.aif`

**Comment by asmagill** [comment]
Does `hs.pasteboard.writeObjects(hs.sharing.fileURL("funky-file-name"))` do what you need?

**Comment by latenitefilms** [comment]
Quite possibly! Will test out. Thanks!

**Comment by asmagill** [comment]
@latenitefilms did you ever try out `hs.sharing.fileURL("funky-file-name")` to see if it did what you required?

**Comment by latenitefilms** [comment]
Sorry - yes, I did have a play, but from memory `hs.sharing.fileURL` didn't translate things properly, which is why I didn't close the issue. I'll have to give it another bash soon and let you know what exactly was going wrong.

**Comment by asmagill** [comment]
To test this, I need an example of a specific file name that is causing problems and a code snippit where you are attempting to use it to test against... funky file names that I've come up with thus far work in my samples, but your code and a file name you're having problems with will give me more insight into exactly what may be failing.

**Comment by latenitefilms** [comment]
I'm just going to close this for now, as I ended up resolving it using this:

```
function tools.safeFilename(value, defaultValue)

	--------------------------------------------------------------------------------
	-- Return default value.
	--------------------------------------------------------------------------------
	if not value then
		if defaultValue then
			return defaultValue
		else
			return "filename"
		end
	end

	--------------------------------------------------------------------------------
	-- Trim whitespaces:
	--------------------------------------------------------------------------------
	result = string.gsub(value, "^%s*(.-)%s*$", "%1")

	--------------------------------------------------------------------------------
	-- Remove Unfriendly Symbols:
	--------------------------------------------------------------------------------
	--result = string.gsub(result, "[^a-zA-Z0-9 ]","") -- This is probably too overkill.
	result = string.gsub(result, ":", "")
	result = string.gsub(result, "/", "")
	result = string.gsub(result, "\"", "")

	--------------------------------------------------------------------------------
	-- Remove Line Breaks:
	--------------------------------------------------------------------------------
	result = string.gsub(result, "\n", "")

	--------------------------------------------------------------------------------
	-- Limit to 255 characters (including extension):
	--------------------------------------------------------------------------------
	result = string.sub(result, 1, 255 - 4)

	return result

end
```

**Comment by asmagill** [comment]
For anyone who may look at this later, :, /, and \ are always problematic... you *can* embed them in file names, but depending upon the filesystem the file is being written to, they often have to be escaped and its not always clear which ones.  It's easier to steer clear of them unless absolutely necessary.

And I do recall coming across some filename, path component, and complete path length limits when working on xattr, but I don't know what they are... I think it's also file system dependent.
