### ISSUE TITLE
hs.pasteboard.read* functions have unexpected behavior

### ISSUE THREAD

**Issue by Ninlives** [Hammerspoon/hammerspoon#1403]
This code will print the string in the pasteboard
```
function test1()
  type = hs.pasteboard.typesAvailable()
  str = hs.pasteboard.readString()
  print(str)
end
test1()
```

But this code will print a table
```
function test2()
  local type = hs.pasteboard.typesAvailable()
  str = hs.pasteboard.readString()
  print(str)
end
test2()
```

When use `hs.pasteboard.readImage()`, similarly the test1() works fine but test2() print a table

**Comment by knu** [comment]
This looks like a bug.  readString() tries to [read the stack top](https://github.com/Hammerspoon/hammerspoon/blob/366f058ea9f70386881e08c28208176735d68a66/extensions/pasteboard/internal.m#L307-L308) even if no parameter is given, so if the previous operation has left `true` on the stack it works in "getAll" mode.

**Comment by knu** [comment]
So, try `hs.pasteboard.readString(false)` for now, and avoid overriding the global function `type` in any case, or many stuff will be broken.  Always use `local`.
