### ISSUE TITLE
Mouse scroll events stop being processed, menu bar button disappears

### ISSUE THREAD

**Issue by iliyang** [Hammerspoon/hammerspoon#1406]
I have encountered a very weird issue that impacts both mouse scroll event handling and menu bar items. I have the following code:

```lua
-- Show alert when scrolling with mouse cursor at the top of the screen
hs.eventtap.new({hs.eventtap.event.types.scrollWheel}, function(e)
    if hs.mouse.getAbsolutePosition().y == 0 then
        hs.alert.show('mouse scroll')
    end
end):start()

-- Create a dummy menu bar item
hs.menubar.new():setTitle('my'):setMenu({ { title = "my menu item" } })
```

Try running this code in Hammerspoon and then do some mouse scrolling with the mouse cursor at the very top of the screen. After a few scrolls, the event stops being processes (until the Hammerspoon script is restarted). Also, weirdly, the menu bar item disappears.

The mouse scrolling at the top I want to use for adjusting the sound volume. When I insert the appropriate code there (in place of the `alert()` above), the event handling still breaks, though it takes a bit more effort (i.e. longer scrolling).

Any ideas?

**Comment by cmsj** [comment]
capture the return values of both of those statements, in global variables. What's almost certainly happening is that because they're not captured, Lua is garbage collecting those objects.

(Please feel free to re-open this if I'm wrong :)

**Comment by iliyang** [comment]
Wow, you were right. Rookie mistake :) Everything seems to be working now. Never would have thought of that, thanks so much!
