### ISSUE TITLE
Little Snitch Configuration is invisible to Hammerspoon

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#1408]
When I open only "Little Snitch Configuration" app, `hs.window.allWindows()` returns empty table, is there any other method I could potentially use to find it?

**Comment by latenitefilms** [comment]
You could try [hs.window.filter](http://www.hammerspoon.org/docs/hs.window.filter.html)?

What does `hs.application:allWindows()` return?

**Comment by szymonkaliski** [comment]
> What does hs.application:allWindows() return?

```
> hs.inspect(hs.window.allWindows())
{ <userdata 1> -- hs.window: Hammerspoon Console (0x610000654728) }
```

(while only "Little Snitch Configuration" and HS Console are opened)

> You could try hs.window.filter?

```
> hs.inspect(hs.window.filter.defaultCurrentSpace:getWindows())
{ <userdata 1> -- hs.window: Hammerspoon Console (0x608000051548) }
```

So, same result :(

**Comment by latenitefilms** [comment]
You could try [hs._asm.axuielement](https://github.com/asmagill/hs._asm.axuielement/blob/master/Reference.md#systemElementAtPosition)?

**Comment by szymonkaliski** [comment]
Yeah but to try it I would have to get window reference first (AFAIK)...? I really would like to get the window object to be able to set frame.

**Comment by latenitefilms** [comment]
If you use `axuielement.systemElementAtPosition(hs.mouse.getAbsolutePosition())` you might be able to get the `hs.window` from that, then go back and work out why you're not seeing it using `hs.application:allWindows()`?

Any other ideas @cmsj or @asmagill ?

**Comment by szymonkaliski** [comment]
Ok, that works, but not sure what to do with that info:

```
> hs.inspect(require('hs._asm.axuielement').systemElementAtPosition(hs.mouse.getAbsolutePosition()):title())
"Little Snitch Configuration"

> hs.inspect(require('hs._asm.axuielement').systemElementAtPosition(hs.mouse.getAbsolutePosition()):role())
"AXApplication"

```

**Comment by szymonkaliski** [comment]
One more interesting thing:

```
> hs.inspect(require('hs._asm.axuielement').systemElementAtPosition(hs.mouse.getAbsolutePosition()):asHSApplication())
<userdata 1> -- hs.application: Little Snitch Configuration (0x600000e5bef8)

> hs.inspect(require('hs._asm.axuielement').systemElementAtPosition(hs.mouse.getAbsolutePosition()):asHSWindow())
nil
```

**Comment by cmsj** [comment]
This is because Little Snitch blocks access to its GUI for security reasons. If you want to override its behaviour, open the Little Snitch preferences and look in the Security tab.
