### ISSUE TITLE
ipc should perhaps return mock table in case of failure

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#141]
Right now if `hs.ipc` fails to load (usually because another instance of Hammerspoon is already running), it returns `nil` during require (which gets turned into `true`, see #140). If a user then calls `cliInstall` presumably this will bomb out. Perhaps `ipc` should return a table containing no-up methods, just to avoid failure. Perhaps in that case we should also alert/notify.

**Comment by cmsj** [comment]
I'm going to close this because I think it's a sufficiently unusual case that it's not ever going to be addressed.
