### ISSUE TITLE
hs.pathwatcher - Only trigger when file has completed copying?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1411]
@asmagill and/or @cmsj - is there anyway to make `hs.pathwatcher` only trigger when a file has FINISHED being copied to a watch folder?

**Comment by knu** [comment]
Unfortunately no, since currently it does not pass eventFlags to a callback function.

**Comment by knu** [comment]
I guess the condition for checking if a regular file that has been opened for writing is closed would be this:
```
eventFlags[i] & (kFSEventStreamEventFlagItemIsFile | kFSEventStreamEventFlagItemCreated | kFSEventStreamEventFlagItemModified) == kFSEventStreamEventFlagItemIsFile | kFSEventStreamEventFlagItemCreated | kFSEventStreamEventFlagItemModified
```

If you also need to detect when a file is moved to the folder you are watching, you'll have to cover events with `kFSEventStreamEventFlagItemRenamed`.

**Comment by latenitefilms** [comment]
AMAZING! Thank you!!

I'll test out later tonight. Thanks again!

**Comment by latenitefilms** [comment]
Thanks so much for your help with this @knu! HUGELY appreciated!

At the moment, `eventFlags` seems to be returning a table with a single number - for example: 

`{ 67584 }`

Would it be better to return a table with strings of the various constants? For example:

`{ "itemCreated", "itemIsFile", "itemModified" }`

It would probably also be worthwhile adding some more documentation to `hs.pathwatcher` to explain what all the callback results actually mean (which I guess would just be a lot of copying and pasting between the Apple Docs?).

Thoughts @asmagill  & @cmsj ?

Either way, I'd love to see this in Hammerspoon!

**Comment by latenitefilms** [comment]
Also, if I rename a file, I get:

`{ 67584, 67584 }`

...the first value in the table which relates to the original filename, and the second value relates to the new file name.

I wonder if `hs.pathwatcher` should be smart enough to only release a single callback when something is renamed, rather than two? Or should this "logic" be done in Lua-land as opposed to in the Objective-C extension?

**Comment by latenitefilms** [comment]
FYI: [hs.speech:setCallback](http://www.hammerspoon.org/docs/hs.speech.html#setCallback) is probably a good example of how I would imagine the callback to work/be documented.

**Comment by knu** [comment]
As hs.pathwatcher has been there at least for a couple of years and it deals with filesystems, I don't think we should break compatibility and risk user's files in any way.

A higher level API could be implemented as a Spoon using hs.pathwatcher.

**Comment by latenitefilms** [comment]
Very good point @knu  - however, as `hs.pathwatcher` is pretty simple/limited in its functionality, it should be pretty easy to add additional functionality without breaking backwards compatibility.

As you say though, a higher level API via a Spoon could also be really handy.

Either way, I've been playing around with your additions, and they're really great - thank you!!

**Comment by latenitefilms** [comment]
Actually... rather than:

`eventFlags[i] = { "itemCreated", "itemIsFile", "itemModified" }`

...it would probably be better to have something like:

`eventFlags[i] = { 
	["itemCreated"] = true, 
	["itemIsFile"] = true,
	["itemModified"] = false,
	etc.
}`

Thoughts @knu, @asmagill & @cmsj ?

I would love to get this PR into the Hammerspoon core, as I'm currently using this PR in our Hammerspoon fork beta release anyway.

Thanks so much for all your help @knu !

**Comment by asmagill** [comment]
I'd leave out the false ones... a nil response to a missing key has the same effect, but otherwise, I do agree that key-value pairs are easier to test if the expectation is that you're going to check for the existence or absence of a specific flag or flags.  Arrays are better when the count of items in the table matters or if the order of the items in the table matters.

**Comment by cmsj** [comment]
So the way I look at this is that everyone who uses the eventFlags parameter, as it stands right now, will have to do a bitwise test against all of the flags they care about, to see if they are true or not. It's not a difficult test to code, but it's a little bit more work for each of them, and unlike almost all of our other APIs.

I think I would prefer it if we do the work of doing the bitwise tests in C and make the parameter be a Lua table with the flags as the key names, so people can do:

```lua
if eventFlags["itemCreated"] then
  foo
end
```
