### ISSUE TITLE
Can spoon have dependency spoon?

### ISSUE THREAD

**Issue by puttin** [Hammerspoon/hammerspoon#1413]
as title

**Comment by cmsj** [comment]
Officially, no. I want to keep things simple at the start of Spoons by not encouraging dependencies.

Technically, yes, in that a Spoon can use the global Lua namespace like any other Lua code can, so it could look for `spoon.Foo` and use it.

But for now, I wouldn't accept any inter-Spoon dependencies into the official Spoons repo.
