### ISSUE TITLE
hs.eventtap.event.newMouseEvent() throws exception (on sierra)

### ISSUE THREAD

**Issue by kaisershahid** [Hammerspoon/hammerspoon#1417]
if i try to invoke newMouseEvent (e.g. `hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], {236.0, 719.0})`) i get the following exception:

    ...n.app/Contents/Resources/extensions/hs/eventtap/init.lua:131: bad argument #-1 to 
    '_newMouseEvent' (number expected, got nil)
    stack traceback:
    	[C]: in function 'hs.eventtap.event._newMouseEvent'
    	...n.app/Contents/Resources/extensions/hs/eventtap/init.lua:131: in function 'hs.eventtap.event.newMouseEvent'
    	[string "local mouse = hs.eventtap.event.newMouseEvent..."]:1: in main chunk
    	[C]: in function 'xpcall'
    	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:401: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:381>

i'm currently using version `0.9.54`

**Comment by asmagill** [comment]
try `hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], {x = 236.0, y = 719.0})` or if you really don't like key-value pairs `hs.eventtap.event.newMouseEvent(hs.eventtap.event.types["leftMouseDown"], hs.geometry.point(236.0, 719.0))`

**Comment by cmsj** [comment]
I've closed this because I'm sure that @asmagill 's answer will resolve things, and I've just pushed d5cbd0eb to make the docs more clear about what the parameter should be. It wasn't wrong, but it was too subtle to be quickly understood :)

**Comment by kaisershahid** [comment]
@asmagill @cmsj ahhh yes that does it, thank you!
