### ISSUE TITLE
hs.midi - Add Extension for MIDI Control

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1422]
Could this be implemented into a Hammerspoon extension?

https://github.com/charlieroberts/midiStroke

**Comment by latenitefilms** [comment]
This might also be relevant? 

http://www.pjb.com.au/comp/lua/MIDI.html

**Comment by latenitefilms** [comment]
@charlieroberts - would you be remotely interested in helping port midiStroke to a Hammerspoon extension?

**Comment by charlieroberts** [comment]
@latenitefilms Although Hammerspoon looks like a great(!) project, I just don't have any bandwidth to dive into it at the moment... best of luck!

**Comment by latenitefilms** [comment]
@charlieroberts - No worries at all! Looking at your website, you certainly look incredibly flat out!

I'll attempt to try and do it myself someday, and hopefully someone smarter than me can jump in and help wrap it up.

Thank you for making it open source!!

**Comment by latenitefilms** [comment]
@knu - You seem to be a bit of a Objective-C guru? Is this something you could help with?

**Comment by latenitefilms** [comment]
This might also be helpful: https://github.com/krevis/MIDIApps

**Comment by latenitefilms** [comment]
Note to self: https://github.com/mixedinkey-opensource/MIKMIDI
