### ISSUE TITLE
undocumented.bluetooth crashes in 10.8 VM

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#143]
I know it's not in the core modules, and I know it's a VM, and I know it's 10.8... but as a general rule of thumb, for things that might not be present (or might eventually be removed because they're deprecated or private API's), what is the "correct" obj-c way to verify their existence and error gracefully instead?

**Comment by cmsj** [comment]
@asmagill is there anything left for this? If so, please feel free to re-open :)
