### ISSUE TITLE
CPU usage is very high when using timer

### ISSUE THREAD

**Issue by volzkzg** [Hammerspoon/hammerspoon#1430]
Here I want to build a lyric display in menu bar for Apple Music.

But in the first step, I encounter a weird question that when I use hs.timer's, the cpu usage can be higher than 60%, and the hammerspoon's menubar is no response. 

The following is my lua code, 

```
function updateItunesLyrics()
  currentTrack = hs.itunes.getCurrentTrack()
  currentArtist = hs.itunes.getCurrentArtist()
  itunesLyrics:setTitle(currentArtist .. ' - ' .. currentTrack)
  duration = hs.itunes.getDuration()
  position = hs.itunes.getPosition()
  timer = hs.timer.doAfter(duration - position, updateItunesLyrics())
end

hs.hotkey.bind({"cmd", "ctrl"}, "L", function()
    itunesLyrics = hs.menubar.new()
    updateItunesLyrics()
end)

hs.hotkey.bind({"cmd", "ctrl"}, "C", function()
    itunesLyrics:delete()
end)
```

My system is macOS 10.12.5

**Comment by ashfinal** [comment]
Clean your things **before** creating new objects.
```
    if timer then timer:stop() timer = nil end
    if itunesLyrics then itunesLyrics:delete() itunesLyrics = nil end
```

**Comment by jhgg** [comment]
You are calling the function instead of passing a reference to to it in doAfter, basically causing you to infinitely loop. Remove the parenthesis after updateItunesLyrics in the doAfter call.

**Comment by cmsj** [comment]
I think @jhgg has the answer here :)

Please re-open if that does't help, for some reason (but it really should)
