### ISSUE TITLE
Extension for Reading/Writing External Property List Files

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1432]
This has been discussed a few times, but I just realised there's no actual standalone issue for it.

I would absolutely LOVE the ability to be able to read and write plist (and binary plist) files using Hammerspoon. Ideally it would be great if you could read an entire plist file to a table, manipulate it, then write the table back out to a plist file. It should use the macOS API's so that cacheing doesn't become an issue. Maybe this could be included as part of `hs.settings`?

I believe @asmagill has [played around with this in the past](https://github.com/asmagill/hammerspoon_asm/tree/master/preferences), but nothing was ever developed to a point where it could be included in the Hammerspoon core.

We currently have some [Lua code](https://github.com/CommandPost/CommandPost/tree/develop/src/extensions/cp/plist) that does pretty good at reading plist files, but need to rely on `defaults` and `PlistBuddy` for writing back to plist files.

Is this something you're still interested in developing @asmagill ? Maybe this is something @knu or @cmsj could help with?

Thanks in advance!

**Related links:**
- [Lua plist parser](https://codea.io/talk/discussion/1269/code-plist-parser)
- [Persistence.lua](https://github.com/effelsberg/loveCodea/blob/master/loveCodea/Persistence.lua)

**Related Issues:**
- [Question - Reading a plist file that contains data](https://github.com/Hammerspoon/hammerspoon/issues/1012) (issue #1012)
- [Release 0.9.51](https://github.com/Hammerspoon/hammerspoon/issues/1130#issuecomment-266266474) (issue #1130)

**Comment by cmsj** [comment]
I'll take a crack at this

**Comment by knu** [comment]
Nice.  I was just about to write code invoking `defaults read ... | grep ...` around.

**Comment by latenitefilms** [comment]
Amazing. Thanks @cmsj !!

**Comment by latenitefilms** [comment]
It would also be awesome if `NSKeyedArchiver` support was built into this extension.

[This](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/plist/archiver.lua) is how we're currently handing it.

[This](https://www.mac4n6.com/blog/2016/1/1/manual-analysis-of-nskeyedarchiver-formatted-plist-files-a-review-of-the-new-os-x-1011-recent-items) might also be relevant.
