### ISSUE TITLE
hs.open doesn't support URLs?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1435]
Instead of using `os.execute('open "http://google.com/"')`, it would be great if we could use `hs.open("http://google.com/")` to open a URL in the default web browser.

**Comment by zzamboni** [comment]
Heh - I came here to open an issue about this, so I will just comment on this one. I've been playing a bit with this but I'm no Cocoa expert. @cmsj I got to this point: 
```
static int core_open(lua_State *L) {
    LuaSkin *skin = [LuaSkin shared];
    [skin checkArgs:LS_TSTRING, LS_TBREAK];

    id path = [skin toNSObjectAtIndex:1];
    BOOL result;

    result = [[NSWorkspace sharedWorkspace] openFile:path];
    if (!result) {
      NSURL *url=[NSURL URLWithString:path];
      result = [[NSWorkspace sharedWorkspace] openURL:url];
    }

    lua_pushboolean(L, result);
    return 1;
}
```
Which works for regular URLs and for regular file paths.

However, this doesn't work for all application URLs. Some of them work fine, for example `omnifocus:///add?name=Pick%20up%20milk&note=You%20gotta` for OmniFocus, but others don't, for example `onenote://https://collaboration.company.com/confidential/blahblahblah#section-id={65D9F07B-2F61-AB44-97E6-69F3F66D8A50}&end` for OneNote.

Both URLs work with the `open` command, so I guess there must be a way of correctly processing them.

Any ideas?

**Comment by cmsj** [comment]
I'd note that hs.urlevent can open URLs. We could improve its API to be able to look up the default URL handler automatically, but I don't feel a burning need for hs.open to behave exactly like /usr/bin/open (which afaict uses a very different set of APIs than hs.open).
