### ISSUE TITLE
permanent variables

### ISSUE THREAD

**Issue by matthew-groth** [Hammerspoon/hammerspoon#1436]
I am new, but according to the [getting started guide](http://www.hammerspoon.org/go/#variablelife) variables "will survive for until you reload your config, or quit Hammerspoon". Is there a way they can persist?

I am coming from Keyboard Maestro whose variables are stored permanently. I'm playing with the idea of moving some of my macros to Hammerspoon and this is the first major challenge I've come across.

**Comment by aldur** [comment]
Yes, you can use [hs.settings](http://www.hammerspoon.org/docs/hs.settings.html) to save your settings to a permanent storage. You'll need the `set` and `get` methods.

**Comment by matthew-groth** [comment]
Great, I made [a PR to add this to the getting started guide](https://github.com/matthew-groth/hammerspoon.github.io/pull/1)
