### ISSUE TITLE
hs.fs - Support for localised directory names?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1438]
It would be great to add a function to `hs.fs` that adds easy support for "translating" [localised directory names](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemAdvancedPT/LocalizingtheNameofaDirectory/LocalizingtheNameofaDirectory.html).

**Comment by latenitefilms** [comment]
Possible @cmsj or @asmagill ?

**Comment by asmagill** [comment]
I'm not entirely sure what you mean here... are you wanting the localized name for "/path/folder.localized" or are you wanting to get the real folder name for a folder in an already localized string?

Off hand, from the link you specified, I'm not seeing methods to do this... If I had to guess, it looks like Apple is assuming that you as the developer already know what folders you want (or they're specified in resource files), while the localization is strictly for how things look to the user in the Finder, but I could be missing something...

**Comment by latenitefilms** [comment]
The attached screenshot will hopefully make it more clear. Finder will automatically translate a `.localized` extension, but if you look in Terminal, you'll see what's really going on:

<img width="389" alt="screen shot 2017-08-18 at 3 30 27 pm" src="https://user-images.githubusercontent.com/22286696/29445445-3285a1c8-842a-11e7-9fe5-c0f4945a1c94.png">

Here's our current way of handling it:

https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/localized/init.lua

...which is all Lua-based, but I'm sure there's a way to do it easier using Objective-C Frameworks?

**Comment by latenitefilms** [comment]
FYI: 

<img width="674" alt="screen shot 2017-08-18 at 3 34 53 pm" src="https://user-images.githubusercontent.com/22286696/29445552-d13d20e8-842a-11e7-80ea-22cb71c5e2b2.png">

**Comment by latenitefilms** [comment]
I'd love to be able to give `hs.fs` a path, and it will return the "user friendly" file name in whatever language I want. For example:

`hs.fs.localised(path, locale)`

```
hs.fs.localised("~/Movies/Motion Templates.localized/Effects.localized/0E758582-5A62-4523-981D-96127A1E3C35.localized", "en")
-> "~/Movies/Motion Templates/Effects/", "Sheffield Softworks"
```

**Comment by latenitefilms** [comment]
We also had to solve #1452 in Lua (See: https://github.com/CommandPost/CommandPost/tree/develop/src/extensions/cp/utf16), to get this to work as different versions of macOS seem to treat localised files differently.

**Comment by asmagill** [comment]
let me know if the latest addition to the fsTweaks pull works... I couldn't find anything for when you specify the locale, but this looks like it should work for the users current locale.

**Comment by latenitefilms** [comment]
Amazing! It works as advertised. However unfortunately, for our purposes, we do need to be able to specify a locale - as we need to search all languages. Let me know if there's anything I can to do help!

```
> hs.fs.displayName("~/Movies/Motion Templates.localized/Effects.localized/0E758582-5A62-4523-981D-96127A1E3C35.localized")
Sheffield Softworks
```

**Comment by latenitefilms** [comment]
Pinging @randomeizer as well.

**Comment by asmagill** [comment]
I'm not finding any easier way to get at alternate locale directory names then what you've already done -- read and parse the files yourself.  For the purposes of getting #1515 into 0.9.56 and see if I can't knock out a few more of the low hanging fruit before @cmsj decides to build the release, I'm going to hold off on this for now, though I will try and get some UTF16 tools in place if I have time this week.  I'll leave it up to whether you want to close this issue when the merge occurs or not.

**Comment by latenitefilms** [comment]
Legend, thanks mate!
