### ISSUE TITLE
Drawing ClickCallback function not work after click finder.

### ISSUE THREAD

**Issue by mpco** [Hammerspoon/hammerspoon#1442]
OS: 10.11.6
HS version: 0.9.54

My code:
```
function ClickFunction()
    print("test")
end

imgRect = hs.geometry.rect(50, 50, 400, 400)
imagedisp = hs.drawing.image(imgRect,"/xx/xx/xx.jpg")
imagedisp:setLevel(hs.drawing.windowLevels.desktopIcon)
imagedisp:setClickCallback(ClickFunction, nil)
imagedisp:show()
```

After reload config, Clicking on the image will callback *ClickFunction*.
Then, click finder(other area of the desktop).
Then, clicking on the image will **not**  callback *ClickFunction*.

I can not find out the reason.
Thank you.

**Comment by latenitefilms** [comment]
@asmagill ?

**Comment by asmagill** [comment]
Apparently this is a limitation of the level `hs.drawing.windowLevels.desktopIcon` -- when you click on anything else at the same level (e.g. the background of the finder), it is raised above in the responder chain so your image can no longer receive mouse clicks.

Use `imagedisp:setLevel(hs.drawing.windowLevels.desktopIcon + 1)` and it works as expected.

Note that this limitation seems to affect both `hs.drawing` and `hs.canvas`; as such it's not something we can change -- it's inherent either with the level itself or with how the Finder treats items at that level.

**Comment by latenitefilms** [comment]
Maybe something to add as a note in the docs?

**Comment by mpco** [comment]
@asmagill  Thank you!
