### ISSUE TITLE
Any possible to move window that without tile bar ?

### ISSUE THREAD

**Issue by fionser** [Hammerspoon/hammerspoon#1448]
Hi guys, 
    I use Hammerspoon to mimic some features  of the awesome. 
My codes somehow works perfect for now, but not with tile-free windows.
App such as iTerm2 can hide its tile bar, but for tile hidden windows,
my codes failed to move these windows. 

So I want to know is it possible to move such kind of tile-free windows ?

**Comment by szymonkaliski** [comment]
Can you post the code you're using for moving windows? I'm `:setFrame()`-ing title-less iTerm windows without problems...

**Comment by fionser** [comment]
@szymonkaliski Thank you! I will try!.
