### ISSUE TITLE
Spoon Documentation - Lua file name conflict

### ISSUE THREAD

**Issue by RainmanNoodles** [Hammerspoon/hammerspoon#1449]
## The Error

"pp/Contents/Resources/extensions/hs/doc/spoonsupport.lua:44: attempt to concatenate a nil value (field 'path')" (note that it is cut off in the dialog)

## How to Reproduce

* There is a spoon at `.hammerspoon/Spoons/SomeName.spoon/` which of course contains `init.lua`
* There is also a file at `.hammerspoon/SomeName.lua`

## Explanation

There is a function in `spoonsupport.lua` called `findSpoons()` at [line 30](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/doc/spoonsupport.lua#L30). The error at line 44 occurs because `spoonDetails.path` is not defined. At line 43, it is supposed to be defined by the regex match `spoonDetails.path     = spoonInit:match("^(.+)/init%.lua$")`.

At first, it looks like this should work because in line 36 we just determined that the path does in fact contain an `init.lua` and we then set `name` in line 39 to be the name of the spoon. However, the `package.searchpath()` in line 40 *is not guaranteed to match this path*. In the end, `name` is set to `SomeName` but instead of finding the path `.hammerspoon/Spoons/SomeName.spoon/init.lua`, instead `package.searchpath()` finds `.hammerspoon/SomeName.lua`. Then, line 43 attempts to search for `.hammerspoon/SomeName.lua/init.lua` which of course fails miserably. In the end, the result is that there is no spoon.

**Comment by cmsj** [comment]
@asmagill any ideas how we might fix this? (which may need to be "don't do that")

**Comment by asmagill** [comment]
It's also worth noting that if you have `.hammerspoon/SomeName/init.lua` then it doesn't crash, but it does fail to find the `docs.json` file in the spoon directory.

I'm going to need to think about this a bit...

**Comment by asmagill** [comment]
Sorry didn't mean to close this...

**Comment by asmagill** [comment]
addressed by limiting search for docs file to the already discovered spoon paths
