### ISSUE TITLE
Using non-modifer key as a modifier

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1450]
Is it possible to use for example Tab key as is (when pressed single time) and as a modifier when held?

Karabiner (pre Elements) version had this option. I could switch between apps by holding `Tab` and `j/k`. Can someone tell me if something like this doable with Hammerspoon. Thanks.

**Comment by knu** [comment]
It is technically doable and there are some attempts in trying to implement such a configuration with Hammerspoon, but I recommend for the time being you use [this PR/fork](https://github.com/tekezo/Karabiner-Elements/pull/247) of Karabiner-Elements, at least until after #1396 is merged.

**Comment by cmsj** [comment]
Karabiner-Elements' beta release now support complex keyboard modifications, so I would strongly suggest that you use that instead of trying to bend Hammerspoon's high-level key events to do it :)
