### ISSUE TITLE
Binding keys in specific apps

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1453]
What's the best way to get hotkey working only in specific app(s)? 

I started naively:

using `hs.window.filter` with `subscribe`, something like:

    hs.window.filter.new{'Google Chrome'}
    :subscribe(hs.window.filter.windowFocused, function()
       doTheBindings(chromeKeys)
    end)
    :subscribe(hs.window.filter.windowUnfocused, function()
       hs.hotkey.disableAll(chromeKeys)
    end)
    
and it does work. But! If I add more than just one app it gets extremely slow. Can you guys suggest a better way? Thanks!

**Comment by agzam** [comment]
It seems one of the reasons why it turned out to be so painfully slow was this:

    :setAppFilter('Emacs', {allowRoles='*'})
     
I have managed to make it bearable by specifying exact values:

    :setAppFilter('Emacs', {allowRoles={'AXUnknown', 'AXStandardWindow'}})

I'm still curious if there's a better way

**Comment by ashfinal** [comment]
I believe using [hs.application.watcher](http://www.hammerspoon.org/docs/hs.application.watcher.html) is a better way. Thus we can hook `activated/deactivated` event for adding or removing the keybindings, or creating dynamic menuitems. I had the idea for quite a time, but I'm too lazy to move forward… 

I'll get time in recent days to see what I can do about this.

**Comment by agzam** [comment]
@ashfinal I didn't have time in the past few weeks to play with HS, indeed `hs.application.watcher` is better suited for what I'm trying to do. Thanks!

**Comment by danielo515** [comment]
Can someone explain me why application watcher is more suited for the task than window filter?

**Comment by danielo515** [comment]
@agzam I know the conversation is old, but the two APIs still exist, and I'm trying to do a similar thing. I wanted to ask about how to do it properly, and I saw this thread, where @ashfinal suggested one api over the other, because the latter is a better tool for the job. I just wanted to know why, that's all.

**Comment by ispringle** [comment]
@danielo515 it's better because the watcher method is based on events. Event A happens so Action A is done. There is no polling (subscriptions) to keep tabs on the app. It's just a one time fire and forget.
