### ISSUE TITLE
Add hints module

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#146]
Currently staged at https://github.com/Hammerspoon/hammerspoon/tree/add-hints-extension, ported from https://github.com/trishume/mjolnir.th.hints

Nits I noticed:
- [x] icons on my second monitor are all clamped to the right edge of the display
- [x] I have a few icons bunched on top of each other at the top of my primary display. At least one of those is for an off-screen window, and possibly the others are, but I can't see immediately what they are
- [x] I get an icon for some windows that aren't necessarily appropriate (e.g. my GeekTool geeklets)
- [x] If there are more windows than hintChars, the loop explodes and the hints don't work
- [x] Needs API documentation

I also wondered if it would make sense to print the window title below the icon (likely with shadowed text, for readability) for when folks have, e.g. multiple Safari windows.

**Comment by maxrothman** [comment]
Is there any interest in generalizing this extension to be a multi-purpose hint draw-er? I'd be interested in using hints do to other things (show locations a window can be moved to, dismiss specific notifications, etc.). It seems like a good general-purpose context-giving feature.

**Comment by cmsj** [comment]
@maxrothman it's an interesting idea. Perhaps some more work on hs.drawing would be a better angle to come at this from?

**Comment by maxrothman** [comment]
@cmsj That sound like a good approach. More functionality would need to get added to hs.drawing though (e.g. rounded rectangles, fill gradients, etc.) so it wasn't ugly as sin.

**Comment by cmsj** [comment]
@maxrothman certainly true :)

**Comment by cmsj** [comment]
@maxrothman well both of those options turned out to be very easy to add. Obviously the main missing thing now is support for rendering images. I'll try and get to that tomorrow.
Anything else you can think of that we might be missing here, drawing-wise?

**Comment by maxrothman** [comment]
Looking at the [Cocoa drawing docs](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CocoaDrawingGuide/DrawingEnviron/DrawingEnviron.html#//apple_ref/doc/uid/TP40003290-CH202-BBCJDGHJ), their drawing primitives include lines, rectangles, ovals/circles, arcs, bezier cubic curves, images, and text. They support RGB/CMYK/grey colors with transparencies and gradient and pattern fills, as well as shadows.

I think all of those would be good to support except for multiple color spaces. I think RGB is more than sufficient on that front.

**Comment by cmsj** [comment]
@maxrothman agreed that RGB is sufficient, I have no intention of going anywhere near supporting multiple colourspaces!
Lines, rectangles, ovals/circles and text we have already. Images is definitely needed. I think for arcs/curves I'd want to see a solid use case before I implemented them (I'd also be fine with someone sending in a solid patch to do them, then I care much less about the use case ;)
We now have linear gradients. I suspect we might want to extend that to also support angular gradients.
So that just leaves pattern fills and shadows. I haven't looked at the API for pattern fills yet, but shadows look like they should be do-able, although it does raise the interesting issue that right now we create the NSView/NSWindow at the same size as the requested drawing object, but if we're going to start rendering a shadow, we'll need to embiggen the view/window by arbitrary amounts, so that will take some thought.

Thanks!

**Comment by maxrothman** [comment]
[Pattern fills are just another type of color](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Color/Color.html#//apple_ref/doc/uid/TP40003290-CH205-SW7), so it seems like images would need to be done first. I agree that arcs/curves can wait for now, but I'd vote for [rounded rectangle](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Paths/Paths.html#//apple_ref/doc/uid/TP40003290-CH206-SW23) support (maybe as part of the rectangle abstraction?)

The other previously unmentioned feature that should receive some thought is line dashing, but that might be non-urgent enough to wait for a while.

**Comment by cmsj** [comment]
@maxrothman rounded rects are done already, see 26ab4a6 from last night :)

**Comment by maxrothman** [comment]
[Woohoo!](http://www.reactiongifs.com/r/h-d.gif)

**Comment by cmsj** [comment]
@maxrothman simple images are now implemented :)
