### ISSUE TITLE
hs.execute with subshell?

### ISSUE THREAD

**Issue by biocyberman** [Hammerspoon/hammerspoon#1461]
I would prefer to do the first command and get expected outcome like the second command? Is it possible?

```
> hs.execute("cat <(echo B)")
	nil	exit	2

> hs.execute("bash -c 'cat <(echo B)'")
B
	true	exit	0
```

**Comment by cmsj** [comment]
At the moment no, but you could create your own function that takes a string parameter and executes it with `bash -c`, and returns the results :)

**Comment by deryni** [comment]
It looks like using `hs.execute(command, true)` lets this work (by doing exactly that `bash -c` wrapping ([ref](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/_coresetup/init.lua#L186)).

**Comment by cmsj** [comment]
@deryni makes a good point, for some reason I looked at the docs of `os.execute()`. Sorry about that, looks like we can close this as already being implemented \o/
