### ISSUE TITLE
Key remapping doesn't work on lock screen

### ISSUE THREAD

**Issue by YOnoda** [Hammerspoon/hammerspoon#1464]
Hi,

I'm going to switch to Hammerspoon from Karabiner, but I found that the key remapping does not work on the lock screen. It works on the unlocked, main screen, though.

On Karabiner the remapping also worked on the lock screen. I wonder why this doesn't on Hammerspoon... Is this a bug or a limitation?

Thanks,

**Comment by cmsj** [comment]
It's a limitation - Karabiner runs as a kernel module and is hooked very deep into the OS. We are a userspace application running as your user when you are logged in. The login screen runs as a totally separate user.

I would strongly suggest you do not switch to Hammerspoon for remapping keys - Karabiner is extremely good at it, and is running at a much more appropriate level of the OS. I'd also note that Karabiner Elements' current beta releases are getting really good, and have brought back a lot of the power of Karabiner pre-Sierra :)
