### ISSUE TITLE
Hammerspoon crashes when using hs.base64.encode on an image

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#1466]
```
> img=hs.image.imageFromURL("http://www.hammerspoon.org/images/hammerspoon.png")


> img
hs.image:  (0x608000442188)

> hs.base64.encode(img)
-- Loading extension: base64
2017-06-21 09:24:30.215 hs[47154:10290197] *** CFMessagePort: dropping corrupt reply Mach message (0b000100)
error communicating with Hammerspoon: message port was invalidated
error unregistering CLI instance with Hammerspoon: message port invalid
```

**Comment by asmagill** [comment]
admittedly the crashing is an issue I'll have to look into, but `hs.base64.encode` isn't intended for converting userdata objects (which `img` is in your example).  If you're needing to convert an image into a string (for storage, transport, etc.), use `hs.image.encodeAsURLString`

**Comment by zzamboni** [comment]
@asmagill thanks! `encodeAsURLString` is exactly what I was looking for - I remembered seeing it somewhere but couldn't find it. Works perfectly, but I agree it would be nice to fix this crash.

**Comment by cmsj** [comment]
+1 for leaving hs.base64 away from trying to deal with random userdata objects
+1 for fixing the crash when someone tries it anyway :D
