### ISSUE TITLE
Locked keyboard and mouse

### ISSUE THREAD

**Issue by keirthomas** [Hammerspoon/hammerspoon#1467]
Sorry for reporting this issue a little late but I needed to check it went away once I removed Hammerspoon.

I got a lot of keyboard and mouse lockups, in that the Mac was still running fine but the mouse cursor would disappear and the only keyboard input that worked was Option+Tab to switch apps (but they wouldn't actually switch once an icon was selected). The only fix was to hard-reset the Mac using the power button because I was unable to shutdown or reboot via any menus. 

MBP mid-2015 15in. I was running a script provided by AppleHelpWriter to show the SSID in the menu bar. 

My best guess would be that this was a bug with the Accessibility feature Hammerspoon uses but I wanted to report it.

**Comment by ashfinal** [comment]
I don't think your problem has anything to do with Hammerspoon.
As for switching apps with `Opt`+`Tab` and showing SSID in the menubar, there is a configuration written by me to do all those staff. https://github.com/ashfinal/awesome-hammerspoon

I'm quite proud about this configuration, hoping you like it as well. :)

**Comment by cmsj** [comment]
@keirthomas I'd be interested to see the Hammerspoon config you were using, but really unless it was doing lots of deep event magic, there really shouldn't be a way for Hammerspoon to lock up mouse/keyboard events 😐
