### ISSUE TITLE
Determine the amount of VRAM Installed?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1471]
Is there anyway to determine the amount of VRAM installed on a machine?

If not, maybe something for `hs.host`?

Any suggestions @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
FYI: I just realised I can use this Terminal command:

`system_profiler SPDisplaysDataType`

...however a way to do this natively in Hammerspoon would be awesome.

**Comment by cmsj** [comment]
Looks like this information is available from IOKit

**Comment by latenitefilms** [comment]
This code might be of help?

https://gist.github.com/ScrimpyCat/8043890

Unfortunately, it's a little bit too advanced for me, so I'll leave this one to @cmsj and @asmagill .
