### ISSUE TITLE
Webview: intercept click on _blank links

### ISSUE THREAD

**Issue by octplane** [Hammerspoon/hammerspoon#1473]
Hi,

Is there a way to intercept click on `<a` with a `_blank` target and actually summon a system command (like `open ...`) so that the link is opened in a regular browser?

Thanks for your time!

**Comment by asmagill** [comment]
To my knowledge there is no direct way to modify the way the underlying WKWebView handles system events, but it may be possible by injecting a javascript onClick (or similar -- HTML DOM and Javascript are not my strong suits) handler with `hs.webview.usercontent` that passes the information about the URL being clicked to Hammerspoon through the user content callback.

**Comment by octplane** [comment]
Ok, will try in this direction. Thanks for your expresss reply!
