### ISSUE TITLE
hs.chooser keyboard shortcut alignment

### ISSUE THREAD

**Issue by jyc** [Hammerspoon/hammerspoon#1482]
Hi! Thanks for the great software.

This is a really tiny nit, but it would be cool if the keyboard shortcuts in the hs.chooser dialog were aligned: right now because different numbers have different widths the "command" and number symbols don't always line up column-wise. Again, a super minor nit, but it would look very clean.

**Comment by cmsj** [comment]
I agree, the problem is that I'm really really bad at doing UI stuff, so I haven't actually been able to figure out how to make them align properly :/

**Comment by latenitefilms** [comment]
@cmsj - I wonder if it's worthwhile re-writing `hs.chooser` to use a `hs.webview`? That way it could be completely customisable via HTML/CSS?

**Comment by cmsj** [comment]
it's taken a while, but they should all be perfectly aligned in the next release.
