### ISSUE TITLE
Change keyboard layout (JIS -> US)

### ISSUE THREAD

**Issue by ky0on** [Hammerspoon/hammerspoon#1485]
Is there any configuration examples to change keyboard layout from JIS to US?

**Comment by cmsj** [comment]
I'm not super familiar with alternate input methods, but I think if you run the following in the Hammerspoon Console, you should see a US option:

```lua
hs.inspect(hs.keycodes.methods())
```

then call ```hs.keycodes.setMethod("FOO")``` with the appropriate input method name.

You might need to do the same things with ```hs.keycodes.inputs()``` and ```hs.keycodes.setInpu()``` - I'm not sure if that happens automatically or not.

Hope that helps :)
