### ISSUE TITLE
hs.spoons nil

### ISSUE THREAD

**Issue by waynehoover** [Hammerspoon/hammerspoon#1487]
Spoons require hs.spoons but for some reason it's not loading for me. Any ideas?

Details here: https://github.com/Hammerspoon/Spoons/issues/42

full init.lua:
```
hs.loadSpoon('WindowHalfsAndThirds')
spoon.WindowHalfsAndThirds:bindHotkeys({max = { {"ctrl", "alt", "cmd"}, "Up" }})
```

Sorry for the dupe not sure the right repo for this.

**Comment by cmsj** [comment]
This should be fixed by 0.9.55 which was just released :)
