### ISSUE TITLE
Sparkle license and github build checks

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1492]
@cmsj, the build checks you've added to the Hammerspoon repository report that Sparkle has an unknown license... knowing nothing about VersionEye and very little about the Sparkle pod, I leave this in your hands but wanted an issue reported so it can be addressed or formally rejected.

**Comment by cmsj** [comment]
I think this is Versioneye being unable to parse the LICENSE file in Sparkle's repo (or not trying to). I've sent a suggestion through to Versioneye in their license tracker tool, to update Sparkle's entry to say that it's MIT licensed. Thanks for prodding me to take care of this :)
