### ISSUE TITLE
hs.image.imageFromPath does not work in 0.9.55

### ISSUE THREAD

**Issue by joshua7v** [Hammerspoon/hammerspoon#1493]
I'm using config files from [ashfinal/awesome-hammerspoon](https://github.com/ashfinal/awesome-hammerspoon), not very familiar with hammerspoon.

but here's what i found:
1. I upgraded hammerspoon to the latest version which is 0.9.55
2. I cloned [ashfinal/awesome-hammerspoon](https://github.com/ashfinal/awesome-hammerspoon)
3. there is an error occurred in the console : `Unable to load image: ./resources/watchbg.png`
4. I tried some ways to fix this error but failed.
5. An idea came into my mind, how about downgrading to 0.9.54, and it suddenly works.
6. I checked the release notes, the newer release comes with some new features related to hs.image
7. so i guess maybe there is a bug or something ...

**Comment by cmsj** [comment]
It's interesting that it seems to work in 0.9.54 - there's an issue on the awesome-hammerspoon repo from last week which seems very similar: https://github.com/ashfinal/awesome-hammerspoon/issues/40

**Comment by joshua7v** [comment]
@cmsj yep, I noticed that issue before my attempt. But he didn't post enough information, I don't know if he can use it correctly with 0.9.54 as well.

**Comment by ashfinal** [comment]
@joshua7v 
It works well on my machine, both in 0.9.54 and 0.9.55.
My guess is installing Hammerspoon with Homebrew may change its working directory, which results in the error. Maybe using relative image path in my configuration is not a good idea, I will do some test at tomorrow and see what I can do.

**Comment by joshua7v** [comment]
@ashfinal possibly. I've tested on my personal mac. Homebrew-installed hammerspoon did not work, and 0.9.55 from github perform perfectly.

**Comment by asmagill** [comment]
the changes i remember making should have no affect on locally loaded resources, but i'll check closer tonight. re the working directory, type 'hs.execute("pwd")' into the console... should default to '~/.hammerspoon' but there are ways to change it.

**Comment by ashfinal** [comment]
@joshua7v Good to hear my guess is right. :) I've never used Homebrew cask to install any apps. 
I'll change to absolute image path in my configuration, and push the update.

@asmagill I'll use `hs.configdir` to compose absolute path. Last time I checked it returned the right result, and I don't think there is an issue.

**Comment by ashfinal** [comment]
@joshua7v 
I will presume this issue solved. Please pull the latest commit and reload the configuration.
