### ISSUE TITLE
hs.canvas doesn't behave like hs.drawing

### ISSUE THREAD

**Issue by ashfinal** [Hammerspoon/hammerspoon#1500]
I'm rewriting my script with `hs.canvas`, then find `hs.canvas` doesn't behave exactly like `hs.drawing`.
<img width="409" alt="screen shot 2017-07-24 at 22 06 54" src="https://user-images.githubusercontent.com/6827900/28527207-70236c4e-70bc-11e7-8138-847f4c6de964.png">
Here is the code:
``` lua
tmp1 = hs.canvas.new({x=0,y=0,w=200,h=200}):show()
tmp1[1] = {type="arc",action="stroke",endAngle=270}
tmp2 = hs.drawing.arc({x=300,y=100},100,0,270)
tmp2:setFill(false)
tmp2:show()
```
I'm wondering `hs.canvas` works as intended or not. What can I do if I don't want the two lines of `tmp1`?

**Comment by asmagill** [comment]
`tmp1[1].arcRadii = false` (or include `arcRadii = false` in the line defining element 1 of the canvas)

**Comment by ashfinal** [comment]
Great! Thanks very much.
