### ISSUE TITLE
EventTap stops working in Sierra until Reboot.

### ISSUE THREAD

**Issue by jackcasey** [Hammerspoon/hammerspoon#1502]
I have a hammerspoon script with a few `hs.hotkey.bind`s and a complicated hs.eventtap that gives me a function layer by holding spacebar (just tapping spacebar will enter a space). I'm using something like this:
```
hs.eventtap.new({hs.eventtap.event.types.keyDown, hs.eventtap.event.types.keyUp}, doAllKindsOfStuff)
```

On a fresh reboot this all works fine, but after a while the eventtap just stops ever calling the function. Maybe this is after a sleep or keyboard re-plug I'm not sure, I've never caught it directly.
Reloading the HS config doesn't change anything.

The hotkeys still work. But from this point on until reboot no amount of calling hs.eventtap will make anything work. It never gets into the specified function.

Anyone have any ideas?

This is on MacOS Sierra.

**Comment by cmsj** [comment]
Out of interest, does quitting Hammerspoon and re-launching it, restore the functionality?

**Comment by jackcasey** [comment]
Not that wasn't fixing it. Only a reboot seemed to work.

I've subsequently stopped using hammerspoon for the key remapping (switched to karabiner elements) and now only use it for moving windows around (using hotkey rather than eventtap) and that is working fine for me.

**Comment by cmsj** [comment]
thanks for the reply. fwiw I do think it's generally better to do remapping in KE than Hammerspoon - we run at a *much* higher level of the OS and get way less power for subverting input events.

**Comment by viddo** [comment]
Old issue I know, but I have been having this exact problem and circumstances described in original post for a long while now. Found this entry when searching for issues.

Similar to Jack, I have not been able to pinpoint what causes it either, but from what I observed it  appears to happen more often after computer is woken up from sleep or unplugging/plugging in external monitor.

It does not help to reload config or restart application. A few times it have helped to unplug and plug in external monitor again, but not today.

Is there anything I could do to troubleshoot or additional information I could provide that would help fix this? FWIW, I'm using latest stable version 0.9.78 (5164) on latest macOs Catalina 10.15.4. Re: peripherals I only use an external monitor, if that would matter.

**Comment by asmagill** [comment]
Just to rule it out, you are capturing the eventtap in a global variable (or upvalue captured local) so it doesn't get cleared by garbage collection prematurely, correct? Granted a reload or relaunch should be sufficient to temporarily restore the behavior if you weren't, but... doesn't hurt to confirm.

**Comment by viddo** [comment]
Yes. :)

For what it's worth, I found the other thread and a comment of mine from 6 months ago that has some more info: https://github.com/Hammerspoon/hammerspoon/issues/1743#issuecomment-555131382 
So when this behavior is observed it does not appear to affect _all_ eventtaps, so maybe there is something there that could help to narrow it down? Is there something else I could try in the console or look into at lower level at that point that would be of help pinpoint the issue?
