### ISSUE TITLE
Bind Control Click to Command Click?

### ISSUE THREAD

**Issue by deybhayden** [Hammerspoon/hammerspoon#1503]
Hey there, title says it all. I tried searching the API docs and groups/issues but I'm not finding the answer to my question. Is there a way to accomplish this mapping in Hammerspoon? Thanks!

**Comment by cmsj** [comment]
You might be able to do it with `hs.eventtap`, but I tend to discourage people from using Hammerspoon for input remapping, it's usually much better to use something like Karabiner Elements or BetterTouchTool which run at more appropriate layers of the OS.
