### ISSUE TITLE
Detecting if ChromeDevTools are open

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1506]
I need to detect if Chrome DevTools panel is open or not from Hammerspoon module. Can someone suggest a way? Thanks!

**Comment by asmagill** [comment]
If you developer panel is in a separate window, then the window finder ability should be able to detect it with something like `hs.window("Developer Tools")`.  It it's a panel in the main window, I'm not aware of a way using the core modules of Hammerspoon.

It might be possible with a third party module [hs._asm.axuielement](https://github.com/asmagill/hs._asm.axuielement), but this is still very raw and you'd need to do a lot of experimentation to come up with an efficient search path, if it's even possible -- it depends upon how accessibility compliant chrome and it's developer panel are.

**Comment by cmsj** [comment]
Sadly Chrome doesn't seem to indicate the state of the DevTools panel in the menus, otherwise that would be a good way to check. I don't think there is going to be any way around this other than @asmagill 's suggestions. Sorry!
