### ISSUE TITLE
Hammerspoon frozen after sleep/hibernate

### ISSUE THREAD

**Issue by technovangelist** [Hammerspoon/hammerspoon#1507]
There are a few seemingly related issues in this repo, but not sure if they are completely the same. When my MacBookPro comes back from sleep (lid closed), hammerspoon is frozen and not reacting to any events. I have watchers for screen, application, usb, battery, path, and caffeinate, but none of them react to any changes unless I reload the config. 

This is on the newest 15" MBP with the current version of the OS.

**Comment by latenitefilms** [comment]
I've also noticed this on my MacBook Pro (15-inch, 2017) - whereas I never had this issue on my 2013 MacBook Pro. I haven't looked into it properly yet though.

**Comment by technovangelist** [comment]
Is there a way to force hammerspoon to restart when it comes back from sleep? Otherwise, its pretty much useless.

**Comment by technovangelist** [comment]
So i think i answered my own question. I tried this but it didn't help.
`
function sleepCallback( eventType )
  hs.reload()
end

hs.caffeinate.watcher.new(sleepCallback):start()
`
Then I changed it to this and it restarts correctly and everything works...so far. 

`
function sleepCallback( eventType )
  hs.timer.doAfter(1,hs.reload)
end

hs.caffeinate.watcher.new(sleepCallback):start()
`

**Comment by technovangelist** [comment]
I closed this and then thought this work around isn't really a solution.  I'll let someone else decide if it should close

**Comment by cmsj** [comment]
I think let's keep this open, that workaround is handy for now, but not ideal. Is your config available somewhere? I don't use a laptop a huge amount, but when I do mine always seems to wake up fine, so maybe there is something you're doing which is tickling a bug we can find&fix :)

**Comment by technovangelist** [comment]
here is my current config: https://gist.github.com/technovangelist/eaa55d8d86740a23d6550cb37d9219d5

**Comment by asmagill** [comment]
Most watchers are a sort of self contained userdata object or table that must be stored in a global variable to avoid the possibility of garbage collection -- if you don't explicitly save a return value Lua assumes that it's eligible for purging during a collection cycle. (there are exceptions but I'd have to do a code review to remember them)

Instead of, for example, "hs.caffeinate.watcher.new(sleepCallback):start()", try something like "sleepWatcher = hs.caffeinate.watcher.new(sleepCallback):start()" in your config file.

**Comment by technovangelist** [comment]
Interesting. I originally had it as x = watcher but then saw a bunch of examples that did it without that so changed it fairly recently. Will make the change and let you know if there is any diff

**Comment by technovangelist** [comment]
so i think we can quietly close this one and blame it on user error. Assigning the watchers to a variable that does not get GC seems to have solved it. Maybe I edited the file and got rid of those assignments when I moved to the new machine. doh!

**Comment by cmsj** [comment]
@technovangelist thanks very much for testing and getting back to us :)
