### ISSUE TITLE
Can not kill System Events

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1509]
For some reasons like lid closing etc., it seems System Events stops responding to some AppleScript commands like setting textfield values etc. I've taken to automatically killing it once I detect this issue. However seems the following

```lua
function killApp(...)
    for _, v in pairs({...}) do
        local app = hs.appfinder.appFromName(v)
        if app then
            app:kill()
        else
            print("No such app " .. v)        
        end
    end
end

killApp("System Events")
```

fails. However in a terminal

```sh
killall -9 'System Events' 
```

works. I am hacking it for now by actually launching that ``killall`` in a shell but would be great if hs ``app:kill()`` just worked.

**Comment by asmagill** [comment]
does the lua function report no such app or does it "look likes it works"?  also note that :kill  does not send the same signal that -9 represents in the killall cmd... try :kill9() indtead.

--
Aaron Magill

**Comment by junkblocker** [comment]
kill9 did the trick. Thanks!
