### ISSUE TITLE
Transcription tools in macOS from iOS?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1511]
@asmagill & @cmsj - is it possible to bring across the transcription tools in iOS across to macOS via Hammerspoon? I assume given that you can use the iOS emulator in Xcode, that all the required Frameworks are already on the Mac? Thoughts?

https://developer.apple.com/documentation/speech/sftranscriptionsegment

**Comment by cmsj** [comment]
What's the use case here? (But fwiw I think pulling frameworks out of the iOS simulator is not a good plan ;)

**Comment by latenitefilms** [comment]
I'm thinking it would be amazing to have a Hammerspoon extension that allows you to input a video or audio file, and it will return the transcribed text from that video or audio file. I know there are third party cloud solutions for this - but seems crazy to pay for a third party solution, when it's already built into iOS?

**Comment by cmsj** [comment]
@latenitefilms that seems incredibly niche for integration into Hammerspoon - I would think that would be better placed as its own app?

**Comment by latenitefilms** [comment]
Fair enough - no problemo!
