### ISSUE TITLE
hs.applescript blocks lua script's execution

### ISSUE THREAD

**Issue by ashfinal** [Hammerspoon/hammerspoon#1517]
I'm trying to access system colorpicker from the menubar. Then found `hs.applescript("choose color")` will block all lua script's execution, including running timers which should update the canvas elements otherwise. 

I'm expecting`hs.applescript` run asynchronously just like `hs.http.asyncGet`. Is that possible?

**Comment by cmsj** [comment]
It's not currently possible to do that. I'm not even sure if it's possible to execute applescript on a background thread. Sorry!

A better fix here would be for us to have a colour picker widget, as part of wider support for general UI stuff, which has issues open already.

**Comment by latenitefilms** [comment]
Yeah, I'm planning on adding a colour picker widget to: https://github.com/Hammerspoon/hammerspoon/pull/1504

**Comment by ashfinal** [comment]
@latenitefilms Cool, can't wait to see it.
