### ISSUE TITLE
Question - Detecting when Magic Mouse is connected to Mac?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1531]
Is there anyway currently to detect when a Bluetooth Device (in this case, a Magic Mouse & Magic Mouse 2) is connected/disconnected to/from a system?

**Comment by asmagill** [comment]
At present, not that I am aware of.  There does seem to be some activity which can be detected with `hs.distributednotifications` that might lead to such a detector, but to my knowledge no one has really investigated this too closely.

You can use code like the following to capture these notifications for perusal if you want to try and see if you can identify the specific messages a tailored watcher could be set up for:

~~~lua
-- appends notification info into `hs.configdir .. "/notifications_logs.txt"` for review
-- the file gets big fast, so only run as necessary and expect to prune
distributedObserver = hs.distributednotifications.new(function(n,o,i)
    local f = io.open("notification_logs.txt","a") ;
    f:write(os.date("%F %T").."\t".."name:"..hs.inspect(n).."\tobj:"..hs.inspect(o):gsub("%s+"," ").."\tinfo:"..hs.inspect(i):gsub("%s+"," ").."\n")
    f:close()
end):start()
~~~

If you identify a specific `name` that you want to limit watching to, you can then use `hs.distributednotifications.new(callbackFn, "name")` to only capture those specific notifications.

**Comment by asmagill** [comment]
Sorry, didn't mean to close!

**Comment by latenitefilms** [comment]
Perfecto! Thank you!

FYI: `com.apple.MultitouchSupport.HID.DeviceAdded` is the name I need to look out for.
