### ISSUE TITLE
Determine Mouse Scroll Direction?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1536]
I couldn't find it, so I'm assuming there's not already any API for determining or setting your mouses scroll direction (i.e. Natural vs Normal)?

Maybe a good addition to `hs.mouse`?

FYI: `defaults read ~/Library/Preferences/.GlobalPreferences com.apple.swipescrolldirection` returns 1 if "Natural" or 0 is "Normal".

**Comment by cmsj** [comment]
```
NSString *scrollDirection = [[[NSUserDefaults standardUserDefaults] objectForKey:@"com.apple.swipescrolldirection"] boolValue]? @"Natural" : @"Normal";
```

**Comment by asmagill** [comment]
`hs.settings.get("com.apple.swipescrolldirection") and "Natural" or "Normal"` also works with what Hammerspoon already has.  You can't use settings to set global settings (because it's limited to writing in the hammerspoon preferences and would thus only change it for Hammerspoon -- and not all globals allow per app customization anyways) but you can read them with the settings module.

**Comment by cmsj** [comment]
hmm, interesting, I hadn't considered using hs.settings for that.

I wonder which is better:

1) Don't add this to HS, let people get it themselves with hs.settings
2) Add it in hs.mouse's init.lua using hs.settings
3) Add it in hs.mouse's internal.m using #1541 

I think 2 or 3 seem reasonable, and 2 is less overall code.

Any thoughts?

**Comment by latenitefilms** [comment]
> `hs.settings.get("com.apple.swipescrolldirection")` and "Natural" or "Normal" also works with what Hammerspoon already has. 

Amazing - I had no idea you can do that!

> I wonder which is better:

I'm assuming option 3 is the fastest (even though it's probably of microseconds different) - so I'd probably go with that?

Although #1541 looks awesome - the only thing I'd LOVE is if you could also feed it a function so that you could create a callback for when this value changes. I'm currently using `hs.pathwatcher.new("~/Library/Preferences/")` for this which works fine - but if I can avoid yet another `hs.pathwatcher` that would be ideal (as I already have a LOT running in CommandPost).

Thoughts @cmsj & @asmagill ?

**Comment by latenitefilms** [comment]
Slightly off topic, but still interesting - List of macOS Global settings:
https://gist.github.com/smgt/3227665

**Comment by cmsj** [comment]
I think it's possible to do KVO on NSUserDefaults stuff, so maybe hs.settings could have a generic watcher?

**Comment by latenitefilms** [comment]
Sounds cool to me!
