### ISSUE TITLE
Crash Logs

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1537]
@asmagill @cmsj - Not sure if this is useful or not, but attached are a bunch of crash logs from CommandPost (which is essentially exactly the same as the latest Hammerspoon release). Any questions let me know!
[org.latenitefilms.commandpost_issue_25_crash_a748f29c28d64c109399b90cfc5f35d7_de7ac306977e11e78b2456847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299895/org.latenitefilms.commandpost_issue_25_crash_a748f29c28d64c109399b90cfc5f35d7_de7ac306977e11e78b2456847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_11_crash_480801cb5783496d97a3ce4d0f0eb03a_6b967d43988b11e7af3456847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299899/org.latenitefilms.commandpost_issue_11_crash_480801cb5783496d97a3ce4d0f0eb03a_6b967d43988b11e7af3456847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_15_crash_196ff64fe6cb47818ee320411d324cfd_5cc6bdd997b611e78b2456847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299897/org.latenitefilms.commandpost_issue_15_crash_196ff64fe6cb47818ee320411d324cfd_5cc6bdd997b611e78b2456847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_26_crash_223a2fbfb6914b0ca88217ff19f2e9cc_5a2d615e989211e79c5656847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299902/org.latenitefilms.commandpost_issue_26_crash_223a2fbfb6914b0ca88217ff19f2e9cc_5a2d615e989211e79c5656847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_27_crash_8af558e2bd4f48ac8b8c9956657f24e2_6cedf25d989211e7af3456847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299896/org.latenitefilms.commandpost_issue_27_crash_8af558e2bd4f48ac8b8c9956657f24e2_6cedf25d989211e7af3456847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_28_crash_bc109523c0af41489ad0e9631d36d504_65401688989411e781b556847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299898/org.latenitefilms.commandpost_issue_28_crash_bc109523c0af41489ad0e9631d36d504_65401688989411e781b556847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_29_crash_61ebefe429d543adb2b54b04882c9e27_723c1aff989511e7b8e356847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299900/org.latenitefilms.commandpost_issue_29_crash_61ebefe429d543adb2b54b04882c9e27_723c1aff989511e7b8e356847afe9799_0_v2.txt)
[org.latenitefilms.commandpost_issue_30_crash_d9d387ebe329404a875fe64ea8f271a8_e571830a989511e7b32456847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1299901/org.latenitefilms.commandpost_issue_30_crash_d9d387ebe329404a875fe64ea8f271a8_e571830a989511e7b32456847afe9799_0_v2.txt)

**Comment by cmsj** [comment]
The first two or three look related to menus - what menu stuff are you doing in CommandPost?

**Comment by latenitefilms** [comment]
We use `hs.menubar` a lot for both adding a CommandPost icon to the macOS menubar (see: https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/menu/manager/init.lua), and also lots of instances of `hs.menubar` in choosers (see: https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/finalcutpro/action/manager/activator.lua).

Given that CommandPost-App is essentially a clone of Hammerspoon, just with the names changed (and "spoons" renamed to "plugins"), is it worth adding @cmsj & @asmagill to the CommandPost Crashlytics account - or do you already get enough crash data in the Hammerspoon Crashlytics account?

**Comment by cmsj** [comment]
@latenitefilms mostly it seems like the crash reports we get are completely unactionable, but I don't recall them looking like yours, so there might be some value. If you want to add me, cmsj@tenshu.net I promise to only mostly ignore the crashes ;)

**Comment by latenitefilms** [comment]
@cmsj - Done! FYI: I want to avoid our CommandPost-App fork from drifting too different from Hammerspoon, to keep things completely compatible, so any crashes we discover and work out, I'll always push to correct them in Hammerspoon, then merge into CommandPost-App. Any questions let me know!

**Comment by cmsj** [comment]
thanks :)

**Comment by latenitefilms** [comment]
@asmagill - Given I'm using a lot of your undocumented extensions in CommandPost, did you want me to add you to our Fabric account as well?

**Comment by asmagill** [comment]
probably not a bad idea

**Comment by latenitefilms** [comment]
@asmagill What's your email?

**Comment by asmagill** [comment]
Same handle as here at icloud.com.

I want to get the docs for guitk finished and then redo portions of the touchbar code. I don't think it will cause any significant syntax changes, but a lot of the guitk stuff should be able to slide right in as items (though not all of them make sense), and I am a fan of using modules rather then duplicating code where possible 😊

It's also given me some ideas re the menubar rewrite, so if @cmsj doesn't already have plans, I'll probably tackle that soon too... in theory, the guitk elements should be usable anywhere the macOS accepts an NSView subclass... and that's a *lot* of places.

**Comment by latenitefilms** [comment]
@asmagill - Added!

I've only played around with `guitk` - I haven't actually put it to use yet in CommandPost, but it looks very impressive. Definitely planning to make use of it soon.

The `touchbar` extension on the other hand I'm using extensively!

Thanks again for all your amazing work!!
