### ISSUE TITLE
Third-party app (SwitchResX) renames hs.screen names

### ISSUE THREAD

**Issue by jkroes** [Hammerspoon/hammerspoon#1538]
After installing and uninstalling SwitchResX, my previous scripts have broken. The app renamed my laptop screen (hs.screen.allScreens) from 'Color LCD' to 'SwitchResX4 - Color LCD'. Is there a particular file where the screen names live that can be deleted or reset? None of the files mentioned by the app's website have worked.

Btw, I'm working on macOS Sierra.

**Comment by nonissue** [comment]
This isn't really a hammerspoon problem, but I found this: 

> My ColorSync profile shows the name "SwitchResX" after uninstallation.
> The ColorSync profiles settings are stored in the file named /Library/Preferences/.GlobalPreferences.plist
> 
> Delete this file and reboot, you'll get a the normal settings again.

http://www.madrau.com/support/support/faq.html

What I'd recommend is copying that file to your desktop and then deleting it or renaming it, so you still have it in case something goes wrong. But if you rename the original, on restart the OS should generate a new one. Proceed at your own risk. 

If you're looking to change display resolutions quickly with hotkeys with hammerspoon or from the menubar, I actually wrote something for myself that accomplishes this. Let me know and I might be able to help you out.

**Comment by nonissue** [comment]
Oh, another suggested solution I found with some googling is:

> Delete /Library/ColorSync/Profiles/Displays

https://discussions.apple.com/thread/7053660?start=0&tstart=0

Again, I'd recommend copying the contents of the folder somewhere else before you delete it.

**Comment by jkroes** [comment]
You're right, but since I have seen discussion of the app in previous Hammerspoon issues, I figured it might be worth mentioning. It turns out that there is a third component also needed to be restored from TimeMachine: /System/Library/Displays. SwitchResX modifies one of the many files in this folder, though I couldn't pinpoint exactly which one. Restoring was an easy fix. Hopefully no one else runs into this issue.

**Comment by nonissue** [comment]
Did you end up resolving this?

**Comment by nonissue** [comment]
Let me know if you want help using hammerspoon to change screen resolutions, it's not super hard.

Feel free to email me: andy [at] nonissue.org
