### ISSUE TITLE
Hammerspoon debug build enabled instruments profiling?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1555]
@cmsj, I can't tell if this is something you enabled or if it's a new default since I installed XCode 9, but I've started seeing `default.profraw` created in the working directory every time I launch Hammerspoon or use the `hs` command line tool... any thoughts?  I'm going to try and track down the specific flag that enables this in the application build scheme, but if you've enabled it on purpose, I'll make the change strictly local until I get to the point where I want to use it in my own tests.

**Comment by cmsj** [comment]
@asmagill I don't think that was me, at least not intentionally. I try to keep my instruments/malloc_guard/address_sanitiser stuff on a separate build scheme which isn't shared.

**Comment by asmagill** [comment]
I haven't tested it fully, but disabling "Gather coverage data" in the scheme editor for the Hamemrspoon scheme within XCode seems to work, at least for me.  I don't want to submit a pull until you've verified it doesn't affect something you want @cmsj, but @chdiza in the mean time, this is what I did:

1. Open  `Hammerspoon.xcworkspace` in XCode
2. Near the upper left corner of the window you will see a scheme designation of "Hammerspoon > My Mac" -- click on "Hammerspoon" and scroll al the way to the bottom and select "Edit Scheme..."
3. In the window that opens, click on the "Test" line in the column on the left
4. Uncheck "Gather coverage data"
5. Click on "Close"
6. Close XCode
7. Build as normal

You'll have to remove any currently existing `default.profraw` files, but so far I haven't seen them come back (and it used to everytime I quit and restarted Hammerspoon).

<img width="1635" alt="screen shot 2017-10-04 at 4 11 15 pm" src="https://user-images.githubusercontent.com/8139480/31200349-3ce78f6c-a920-11e7-9f8e-227d41412a6e.png">

**Comment by chdiza** [comment]
Thansk for the tip!  It seems to be working over here too.

**Comment by cmsj** [comment]
@asmagill if you want to submit a PR, go ahead - the only thing I care about here really is whether the Travis builds still collect coverage data, which I think they should, but the build results of a PR will tell us :)
