### ISSUE TITLE
Get Pixel Color

### ISSUE THREAD

**Issue by Jetjames** [Hammerspoon/hammerspoon#1559]
I need getting x and y coordinates of a color on screen. Someone can help me? Can this be done in Hammerspoon?

**Comment by latenitefilms** [comment]
Owwwww, good question! I don't believe so.

@cmsj & @asmagill - might be something cool to add to `hs.screen`?

**Comment by asmagill** [comment]
At present, no.

To implement this, you'll need to take a screen shot (or at least a small one at the coordinates you're interested in) and then check the bitmap directly... which introduces the distinction between pixels and points (screen coordinates)... on HiDPI (i.e. Retina) displays, there is no longer a 1-1 correspondence between the two, more like a 4-1 (and I don't know if the newer 4k and 5k monitors ramp it up even further), so you have to decide if you just want the 0,0 pixel in the bitmap at the coordinate you want, or if you want the average of all of the pixels that make up the point you're interested in.

And with High Sierra allowing direct overlay in Metal 2, even that might not work for all cases.

I won't have time to tackle this probably until the weekend, but the first example at https://stackoverflow.com/questions/4395420/get-the-color-a-pixel-on-the-screen-in-objective-c-cocoa-app looks like a promising place to start if someone else wants to take a crack at it. Still have to figure out how to handle the pixel/point difference...

**Comment by yingnierxiao** [comment]
now must save a picture,read picture get Pixel with 3rd lib
