### ISSUE TITLE
Executing hs from emacs-lisp code

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1560]
Since the update to  Hammerspoon 0.9.56, an emacs-lisp function that used to work for me before somehow stoped working. 
I'm not sure due to what change in Hammerspoon it broke. Here's is the function:

    (defun hs-alert (message)
      "shows Hammerspoon's hs.alert popup with a MESSAGE"
      (when (and message (eq system-type 'darwin))
        (call-process (executable-find "hs")
                      nil 0 nil
                      (concat "-c" "hs.alert.show(\"" message "\", 1)"))))
                      
I've tried debugging it by changing `call-process` arguments, like that:

    (call-process (executable-find "hs")
                  nil t nil
                  "-c " "'hs.alert.show()'")
                  
So it would append the output from executable to the buffer, and apparently `hs` complains:

    /usr/local/bin/hs: illegal option: -c

Can someone help me to get to the bottom of this?
_`hs.alert.show` is not the only thing that I execute from Emacs._

**Comment by agzam** [comment]
I think I found the issue, it was due to incorrect quoting, here's the fixed version:

    (defun hs-alert (message)
      "shows Hammerspoon's hs.alert popup with a MESSAGE"
      (when (and message (eq system-type 'darwin))
        (call-process (executable-find "hs")
                      nil 0 nil
                      "-c"
                      (concat "hs.alert.show(\"" message "\", 1)"))))

    (hs-alert "yo")

**Comment by asmagill** [comment]
Does call-process take the separate strings and treat them as arguments to something like `execv`?  If so, the extra space in "- c" in your second example would cause a problem.

**Comment by asmagill** [comment]
Ah, you fixed it.

**Comment by agzam** [comment]
Yeah, maybe this is not related to Hammerspoon's update at all, maybe it's due to 25.3.1 of Emacs, basically I need to pass `-c` and the next argument separately

**Comment by asmagill** [comment]
It may *be* the new Hammerspoon code... I don't recall what library the original `hs` used to parse arguments, but the new version takes advantage of the macOS feature of sticking them into the NSUserDefaults for the executable... I liked the syntax better :-)

In the first example, `-c "hs.alert.show(\"message\", 1)"` is treated as 1 argument, not two.  By separating `-c` and the string to execute as separate arguments to whatever low level function is doing the actual spawn of the hs process, they become 2 arguments, one `-c` which the cli tool knows means that the next argument will be lua code to execute.

Either way, this discussion is in the issue history now and should probably be added to the FAQ if we ever get around to bringing it up to date.
