### ISSUE TITLE
Move current window to next or previous desktop.

### ISSUE THREAD

**Issue by zhujinghui** [Hammerspoon/hammerspoon#1563]
Hello,

Would it be possible to move current window to next or previous desktop?
Thanks very much for answering.

**Comment by cmsj** [comment]
For "desktop" do you mean Spaces or multiple monitors?

**Comment by zhujinghui** [comment]
I mean spaces, not monitor. Thanks.

**Comment by cmsj** [comment]
Officially, no, there's no API in macOS for us to do that. @asmagill has a module available in his github repos that use private APIs, you might have a look at that :)
