### ISSUE TITLE
hs.chooser - Set Position on Screen?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1564]
As far as I can see, there's no way to set the screen position of a `hs.chooser`?

It would be great if we could set the position of a `hs.chooser`, because currently in a dual-screen environment, it's always popping up on the wrong screen for me. I would have THOUGHT it would appear on whatever screen the mouse is currently on - but that doesn't seem to be the case.

Currently I have two monitors next to one another.

Any ideas @cmsj or @asmagill ?

**Comment by cmsj** [comment]
Currently it's supposed to appear on the active display, ie whichever one has a focused window, but I think it would be reasonable to have it be user-positionable

**Comment by latenitefilms** [comment]
It could be the fact that I've set it so that Hammerspoon doesn't have a Dock Icon, so maybe it doesn't consider the Hammerspoon Console as a focussed window?

**Comment by latenitefilms** [comment]
FYI - I had a quick look at this @cmsj & @asmagill, and I have no idea how to add this, so will leave for someone else to tackle.

**Comment by cmsj** [comment]
Implemented in a719c531

**Comment by asharpe** [comment]
> Currently it's supposed to appear on the active display, ie whichever one has a focused window

This doesn't appear to be the case.  It always appears on the monitor which has the OSX Dock on it (Version 0.9.73 (0.9.73)).

Upgraded to 0.9.78 and have the same issue
