### ISSUE TITLE
hs.chooser - Doesn't wait for callbacks to finish?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1566]
We're having an issue with `hs.chooser` when feeding it incredibly complicated and time consuming functions as callbacks. It seems that the chooser will display BEFORE the callbacks have finished doing their thing, which causes the `hs.chooser` to fail. If I re-trigger the same trigger again shortly after, it works as it should.

Possibly the same issue I was having in #1393.

Any ideas @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
I'm struggling on this one - any ideas @asmagill or @cmsj ?

FYI: Here's the code that's causing us grief: https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/action/manager/activator.lua

**Comment by latenitefilms** [comment]
Looking at the code:

https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/chooser/HSChooser.m#L85

Unless I'm missing something, it doesn't look like `[self.choicesTableView reloadData]` is actually implemented?

I'll keep playing - but if you have ideas @asmagill or @cmsj let me know.

**Comment by asmagill** [comment]
The chooser table is a subvlass of NSTableView -- see https://developer.apple.com/documentation/appkit/nstableview/1528382-reloaddata?language=objc

I probably won't get a chance to look at it that closely for a couple of days, but I'll keep an eye on this thread to see if you make any progress in the mean time.

**Comment by latenitefilms** [comment]
Legend, thanks @asmagill - that makes way more sense! Further testing makes me think something is funky in OUR code, not `hs.chooser` - so will keep fault-finding.

**Comment by latenitefilms** [comment]
This code seems to work fine - so I'm just going to close this issue for now. We must be doing something funky in our own code to break things.

```
-- hs.chooser Example

local inspect = require("hs.inspect")

local logger = require("hs.logger")
logger.defaultLogLevel = 'debug'
log = logger.new("chooser")

local chooser = require("hs.chooser")
local menubar = require("hs.menubar")
local mouse = require("hs.mouse")

showAChoice = true
numberOfChoices = 100000

function choicesA()
	local result = {}

	for i=1, numberOfChoices, 1 do
		table.insert(result, {
			["text"] = "Choice " .. tostring(i),
			["subText"] = "This is the subtext of choice " .. tostring(i),
			["uuid"] = tostring(i)
		})
	end

	return result
end

function choicesB()
	local result = {}

	for i=1, numberOfChoices, 1 do
		table.insert(result, {
			["text"] = "New Choice " .. tostring(i),
			["subText"] = "This is the subtext of choice " .. tostring(i),
			["uuid"] = tostring(i)
		})
	end

	return result
end

myMenubar = menubar.new(false)
	:setMenu({
       {
       	title = "Refresh",
       	fn = function()
       		log.df("Refreshing Choices.")
       		if showAChoice then
       			choices = choicesB()
       		else
       			choices = choicesA()
       		end
       		showAChoice = not showAChoice
			myChooser:refreshChoicesCallback()
       	end
       },
   })

function completionFn(value)
	log.df("completionFn value: %s", inspect(value))
end

function choicesFn(value)
	if not choices then
		choices = choicesA()
	end
	return choices
end

function rightClickFn()
	local point = mouse.getAbsolutePosition()
	myMenubar:popupMenu(point)
end

function queryChangedFn(value)
	log.df("queryChangedFn value: %s", inspect(value))
end

function showFn()
	log.df("showFn triggered.")
end

myChooser = chooser.new(completionFn)
	:choices(choicesFn)
	--:queryChangedCallback(queryChangedFn)
	:showCallback(showFn)
	:rightClickCallback(rightClickFn)
	:show()
```
