### ISSUE TITLE
How can open a new window of chrome?

### ISSUE THREAD

**Issue by zhujinghui** [Hammerspoon/hammerspoon#1568]
c = 'Google Chrome'

for key, app in pairs(keyApp) do
    if key == string.upper(key) then
        hs.hotkey.bind(prefixShift, key, function() hs.application.launchOrFocus(app) end)
    else
        hs.hotkey.bind(prefix, key, function() hs.application.launchOrFocus(app) end)
    end
end

Dear developer,
I would like to know, how can I open a new window of chrome base on this code?

**Comment by latenitefilms** [comment]
Have a look at `hs.application:selectMenuItem(menuitem[, isRegex])`.

See: http://www.hammerspoon.org/docs/hs.application.html#selectMenuItem

**Comment by cmsj** [comment]
note that you usually have to focus an application before you can successfully interact with its menus. The other alternative would be to use AppleScript, as described in https://superuser.com/questions/104180/how-to-create-a-new-chrome-window-on-mac-os-x-using-applescript-or-a-shell-scrip

(you can execute AppleScript in Hammerspoon using `hs.osascript`)
