### ISSUE TITLE
HS is littering `default.profraw` files to disk

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1569]
For some reason starting sometime within the last two weeks, HS has been dumping files called `default.profraw` on my disk.  Running `file` on those reveals that they're some kind of debugging tool for llvm (`LLVM raw profile data, version 4`).

I'm on 10.12.6.  My `.hammerspoon` is a symlink to a folder called `hs` that lives elsewhere, and it's in this `hs` folder that the `default.profraw` files are usually getting dumped.

I can reproduce this every single time on more than one machine by doing the following:
```
$ open -a Hammerspoon
[wait for it to finish loading]
$ osascript -e "tell app \"Hammerspoon\" to quit"
$ ls ~/.hammerspoon
default.profraw
[the usual files]
```

Sometimes this file gets dumped elsewhere on the file system, but it's usually to `~/.hammerspoon`.  I've never seen this before, and it's driving me nuts.  I built HS locally from source, but I didn't turn on any kind of debugging flag.  I just run `make` in the source dir.  Maybe this is Yet Another Thing Xcode 9 Sees Fit To Screw Up?

I've ruled out that it might be something in my `init.lua` or other things it sources (like my fake geeklets), by moving the contents of `~/hammerspoon` elsewhere and following the reproduction steps.  I still get littered.

In case it might be connected: There have been some occasions within the last week where on one of my machines my system comes to a crawl, and Activity Monitor has HS running at 200% CPU.  That also has never happened before, and I have no idea why HS would be doing that.  But this phenomenon is not a necessary precursor of the `default.profraw` litter (and anyway, the litter happens on two different machines while the CPU spike is only on one).

**Comment by chdiza** [comment]
It's got to do with Xcode 9.  If I go back and rebuild HS using Xcode 8.3.3 and their associated CommandLineTools, I don't get the litter.  As soon as I point `xcode-select` at Xcode 9 and reinstall *their* CLT, I get the litter.

(If I don't match the CLT version to the Xcode.app version, then when I run `make` I see a complaint about some kind of framework mismatch.  So to rule that out from being a factor, I made the two versions match.)

So I'm hoping that either (a) there's some kind of setting that can be set in the `makefile` to get rid of the litter, or (b) there's some other way to build HS locally that doesn't cause the litter.

**Comment by cmsj** [comment]
@asmagill mentioned that he was seeing this - it's weird, the profiling (code coverage) data should only be generated when the Test configuration is built, but for some reason it seems to be doing it for the Debug configuration too. Not sure if this is a change in behaviour, or a bug in Xcode 9.

**Comment by chdiza** [comment]
Is there a tweak I can locally make to the makefile that will use a different "configuration"?  Or an envvar I can set?  I can live with the litter, but I'd rather not have to live with it until Xcode 9.x comes out :)
