### ISSUE TITLE
hs.streamdeck Questions

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1576]
@cmsj - Awesome work on `hs.streamdeck`!

A few questions:

1) Does `hs.streamdeck.init()` NEED to be called prior to using `hs.streamdeck.numDevices()` as it's not clear in the documentation?

2) When I have a Stream Deck connected prior to loading Hammerspoon, then start Hammerspoon, `hs.streamdeck.numDevices()` returns 0 (which is incorrect), and when I call `hs.streamdeck.init()`, the callback returns a `hs.streamdeck` object, but it doesn't have a serial for some reason? If I then disconnect and reconnect the Stream Deck, the callback will trigger again, but this time it will have a serial number. I assume this is a bug?

**Comment by latenitefilms** [comment]
As a feature request, it would also be awesome if you could add a text label to the buttons (similar to how the Stream Deck app works - i.e. ability to set bottom, middle or top for each title).

**Comment by latenitefilms** [comment]
I'm not sure it matters... but should there also be a way to stop the Stream Deck monitoring?

**Comment by latenitefilms** [comment]
Actually... in regards to question 2 - it seems it does return a serial IF the Stream Deck application is closed when Hammerspoon starts. There must be some kind of conflict?

**Comment by cmsj** [comment]
Yeah it's very unlikely that HS and StreamDeck.app can co-exist, each will be trying to talk to the deck and that's not going to make anyone happy :)

As for putting text on the buttons, I don't feel a burning need to add it directly to hs.streamdeck when http://www.hammerspoon.org/docs/hs.canvas.html#imageFromCanvas exists :D

As for `.init()` - yes, that does need to be called. I flip-flopped quite a lot on that one, but in the end decided not to start looking for decks when `hs.streamdeck` is loaded, since that might not be the behaviour that people want.

**Comment by cmsj** [comment]
15b458f4 should clear up the docs a little. Your second point needs some more investigation.

**Comment by latenitefilms** [comment]
> Yeah it's very unlikely that HS and StreamDeck.app can co-exist, each will be trying to talk to the deck and that's not going to make anyone happy :)

No worries - I'll make sure `StreamDeck.app` is closed prior to `hs.streamdeck.init()` being triggered.

> As for putting text on the buttons, I don't feel a burning need to add it directly to hs.streamdeck when http://www.hammerspoon.org/docs/hs.canvas.html#imageFromCanvas exists

No worries - make sense.

> As for `.init()` - yes, that does need to be called. I flip-flopped quite a lot on that one, but in the end decided not to start looking for decks when `hs.streamdeck` is loaded, since that might not be the behaviour that people want.

No worries - thanks for the documentation tweaks!

However, I wonder if this should be re-worked to be `hs.streamdeck.start()` and `hs.streamdeck.stop()`, so that you can go back to using `StreamDeck.app` (and vice-versa) without having to restart Hammerspoon?

I'm also having some issues getting the button callback to work - but I'll keep playing and see if I can work it out.

Currently I'm getting `ERROR:   LuaSkin: hs.streamdeck received a button input, but no callback has been set. See hs.streamdeck:buttonCallback()` - even though, I'd definitely setup a callback.

Thanks heaps @cmsj !

**Comment by latenitefilms** [comment]
@cmsj - Maybe I'm doing something stupid, but as far as I can tell, this doesn't work:

```
local logger = require("hs.logger")
logger.defaultLogLevel = 'debug'
local log = logger.new("streamDeck")
local streamdeck = require("hs.streamdeck")

local function discoveryCallback(connected, object)
	log.df("Stream Deck Callback. Connected: %s, Object: %s", connected, object)
end

streamdeck.init(discoveryCallback)

local numberOfDevices = streamdeck.numDevices()

log.df("numberOfDevices: %s", numberOfDevices)

if numberOfDevices == 1 then

	log.df("Found 1 device...")

	local device = streamdeck.getDevice(1)

	device:buttonCallback(function(object, buttonID, pressed)
		log.df("object: %s, buttonID: %s, pressed: %s", object, buttonID, pressed)
	end)

end
```

...but this does:

```
local logger = require("hs.logger")
logger.defaultLogLevel = 'debug'
local log = logger.new("streamDeck")
local streamdeck = require("hs.streamdeck")

local function discoveryCallback(connected, object)
	log.df("Stream Deck Callback. Connected: %s, Object: %s", connected, object)

	if connected and object then
		object:buttonCallback(function(object, buttonID, pressed)
			log.df("object: %s, buttonID: %s, pressed: %s", object, buttonID, pressed)
		end)
	end

end

streamdeck.init(discoveryCallback)
```

It seems the `hs.streamdeck` objects created by the `hs.streamdeck.init()` callback work fine, but if you get a `hs.streamdeck` object from `hs.streamdeck.getDevice()`, it doesn't work properly.

Can you reproduce?

**Comment by cmsj** [comment]
I haven't tried to reproduce, but my guess is that you're checking `numDevices()` before any have been discovered - the discovery callback is where you should a button callback.

**Comment by latenitefilms** [comment]
No worries - that all makes sense.

However, maybe the documentation should be updated to better reflect this? My original reading of the documentation didn't reveal that you really HAD to use the discovery callback - I was originally thinking I could just manually call `hs.streamdeck.numDevices()` to work out what's connected, then use `hs.streamdeck.getDevice()` (as opposed to using the discovery callback) - which obviously doesn't work.

Also, I wonder if `hs.streamdeck.numDevices()` and `hs.streamdeck.getDevice()` should return an error or `nil` if `hs.streamdeck.init()` hasn't already been called?

**Comment by latenitefilms** [comment]
@cmsj - I'm also noticing an issue with the `buttonCallback`. Even though I definitely have a `buttonCallback` set up, I occasionally get:

`ERROR:   LuaSkin: hs.streamdeck received a button input, but no callback has been set. See hs.streamdeck:buttonCallback()`

Should `hs.streamdeck:buttonCallback()` be set in the `discoveryCallback`?

**Comment by latenitefilms** [comment]
@cmsj - Here's my code:

https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/streamdeck/manager/init.lua

Any idea what I'm doing wrong?

I've tried comparing to your Hammerspoon Config, and the only thing I can think of is maybe something is screwing up because I'm saving the `hs.streamdeck` in a table?

It's odd - because the buttons work fine - it's just the callback that won't "stick".

**Comment by latenitefilms** [comment]
This crash report might also be helpful?

[org.latenitefilms.commandpost_issue_41_crash_52763cdd7c1542a0806243beb3ec4e4f_10c6ccedb21911e7a7eb56847afe9799_0_v2.txt](https://github.com/Hammerspoon/hammerspoon/files/1386107/org.latenitefilms.commandpost_issue_41_crash_52763cdd7c1542a0806243beb3ec4e4f_10c6ccedb21911e7a7eb56847afe9799_0_v2.txt)

**Comment by cmsj** [comment]
@latenitefilms fixed in 44d35ade

**Comment by latenitefilms** [comment]
@cmsj - Legend, thank you so much!

**Comment by latenitefilms** [comment]
@cmsj - Yep - that fixed my issue. Thank you!
