### ISSUE TITLE
hs.osc - Add Extension for OSC Control

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1580]
I'd imagine it interfacing with something like: 

https://hexler.net/docs/touchosc-configuration-connections-osc

Similar reasons for #1422.

Possibly Useful:

https://github.com/lubyk/osc
http://lua-users.org/lists/lua-l/2006-04/msg00408.html

**Comment by cmsj** [comment]
What sort of use-cases are you thinking of, for this?

**Comment by latenitefilms** [comment]
I basically want to add this extension so that we can use iOS interfaces like [TouchOSC](https://hexler.net/software/touchosc) for controlling Hammerspoon. In my specific case, we use Hammerspoon to control Final Cut Pro (thanks to @asmagill's amazing `hs._asm.axuielement`), so the end game is basically using TouchOSC to control Final Cut Pro - i.e. a slider on TouchOSC could control a slider within the FCPX interface. Unlike Apple's Logic application, Final Cut Pro doesn't have any API for being controlled by MIDI or OSC devices, so Hammerspoon could be an awesome "interface" to solve this.

For more general users, you could also use it in the same way as you're using Stream Deck - but as a more mobile set of buttons you can take with you everywhere on your phone. For example, you could use button on TouchOSC to do all the things we normally do `hs.hotkey`. Rather than building a standalone Hammerspoon iOS app - this could be a really good way to bringing Hammerspoon control mobile.

That's basically the reason why I also want to do #1422 (i.e. be able to use MIDI devices to trigger Hammerspoon to make it "do stuff") - but have held off on doing that for now, as Objective-C work takes me ages, because I basically just spend the whole time copying and pasting coding examples to make things work. Definitely on my to-do list though, as will no doubt hit up everyone here in the Hammerspoon community for help.

Any questions let me know!

**Comment by asmagill** [comment]
At a quick glance, it looks like OSC uses  a UDP socket to communicate and everything else is just the protocol or encoding of the data in the udp datagram... this might be doable already with `hs.socket.udp` and the decoding could be done in lua by implementing the  http://opensoundcontrol.org/spec-1_0 specification with judicious use of `string.unpack`.

**Comment by latenitefilms** [comment]
Awesome! Thanks for looking into it @asmagill - very much appreciated! I'll have a look into it sometime soon.

**Comment by latenitefilms** [comment]
Note to self: https://charlesmartin.com.au/blog/2013/3/26/finding-a-good-osc-library-for-ios

**Comment by cmsj** [comment]
Is your use case for this covered by hs.midi?

**Comment by latenitefilms** [comment]
Kinda, but I’d still like OSC support as well as MIDI (as MIDI is pretty old school, and a lot of modern hardware now supports OSC), so I’d like to keep this issue open for now. I’ll have a bash at this at some point.

**Comment by latenitefilms** [comment]
I don't see myself doing this anytime soon, so closing this issue for now.

**Comment by latenitefilms** [comment]
I'm re-interested in this, so re-opening to remind myself.

**Comment by latenitefilms** [comment]
https://github.com/Figure53/F53OSC
