### ISSUE TITLE
hs.image - Invert transparent image?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1581]
I have a transparent image (PNG) containing a white icon. Is there anyway to invert this image to be black on a transparent background using `hs.image` or otherwise?

**Comment by latenitefilms** [comment]
@asmagill - Is this something that could maybe done in `hs.canvas`?

**Comment by asmagill** [comment]
Look at the compositing options for canvas. You’ll probably need to define item 1 as a black rectangle then define item 2 as the image with ‘compositeRule’ set to something other then the default of sourceOver; check out https://github.com/asmagill/hammerspoon/wiki/hs.canvas.examples#gradients for a better example

**Comment by latenitefilms** [comment]
@asmagill - Legend, thanks! Works great!
