### ISSUE TITLE
Strange dialogs and control positioning in 0.9.57

### ISSUE THREAD

**Issue by al3xandru** [Hammerspoon/hammerspoon#1583]
Since upgrading to 0.9.57 I'm noticing some strange positioning issues:

1.  the menu bar drop down menu shows up disconnected from the icon

<img width="246" alt="screen shot 2017-10-16 at 10 46 55 pm" src="https://user-images.githubusercontent.com/290841/31648678-f0f97860-b2c3-11e7-90ed-4d15b6592f40.png">

2.  the about dialog shows off the top of the screen

<img width="351" alt="20171016-224738-screenshot_from_finder-702x578" src="https://user-images.githubusercontent.com/290841/31648703-0d3594dc-b2c4-11e7-8f77-14c7edd6cd9f.png">

3.  `hs.chooser` is also displayed off the top of the screen

<img width="136" alt="20171016-224837-screenshot_from_safari_of_github com-272x972" src="https://user-images.githubusercontent.com/290841/31648724-2e246ca4-b2c4-11e7-86aa-d2232c987fe2.png">

Environment:

1.  macOS 10.12.6 on a retina MBP 13" with no external monitors
2.  Hammerspoon 0.9.57

**Comment by al3xandru** [comment]
Just for double checking, I have reinstalled 0.9.56 and I can't reproduce any of the above.

**Comment by asmagill** [comment]
A custom build of the latest source does not have this issue — i’ll try downloading the actual release when i get a chance this weekend and see if i can reproduce it with that.

**Comment by cmsj** [comment]
@asmagill did you get a chance to try the release build? I've not seen this on either my my Macs :/

**Comment by latenitefilms** [comment]
I haven't seen this on any of our machines either. I'm assuming it's a one off High Sierra glitch.

**Comment by asmagill** [comment]
Sorry, no I'm not able to replicate this even with the 0.9.57 release.

**Comment by cmsj** [comment]
@al3xandru are you still seeing this with more recent builds and/or more recent versions of macOS?

**Comment by al3xandru** [comment]
I'm going to close this for now.  If I reproduce it with recent versions I'll re-open.  Thanks for the ping.
