### ISSUE TITLE
Text selection trigger

### ISSUE THREAD

**Issue by kingtosh** [Hammerspoon/hammerspoon#1586]
I want to make actions about text selection in some applications.
So, is it possible to use text selection as a trigger?

**Comment by cmsj** [comment]
I don't believe the underlying system APIs provide an event for text selection. My observation of tools like PopClip is that they watch for double clicks and click-drag-release, which should be possible to some extent with hs.eventtap, but might need one of @asmagill 's future extensions for better interaction with UI elements.
