### ISSUE TITLE
Pull request template?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1591]
@cmsj - Just came across [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). Might be worth investigating?

**Comment by cmsj** [comment]
fwiw I am not a fan of issue templates, but a PR template is potentially interesting. I'll give it some thought, thanks! :)
