### ISSUE TITLE
hs.expose needs to cycle through spaces

### ISSUE THREAD

**Issue by Donkeyfish87** [Hammerspoon/hammerspoon#1592]
If you reload your config and call hs.expose.new(...) it won't pick up windows on other than active space. It is required to cycle through all the spaces once for the windows to show up.

Not sure if this is intended or a bug.

**Comment by cmsj** [comment]
It's not intended, but it is unfortunately unavoidable - the window management APIs on macOS are actually accessibility APIs that are intended for use with things like Screen Readers, and as such they only deal with windows that are currently present. I'm not aware of a way we can work around this, sorry! 😕
