### ISSUE TITLE
Typo in SPOONS.md

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#1594]
```Lua
  { someFeature: {{"cmd", "alt"}, "f"},
    otherFeature: {{"shift", "ctrl"}, "b"}}
```

Should read:

```Lua
  { someFeature = {{"cmd", "alt"}, "f"},
    otherFeature = {{"shift", "ctrl"}, "b"}}
```

It's also very challenging to find out the list of features that can be bound.  I opened an issue in the Spoons repository with some discussion of that.

**Comment by cmsj** [comment]
Good catch, thanks! Little bit of Python slipped out there 😁
