### ISSUE TITLE
hs.layout.apply not accepting screen value

### ISSUE THREAD

**Issue by tizatron** [Hammerspoon/hammerspoon#1595]
This may be pilot error but I have been looking that this for a while and can't seem to sort it out.

Hammerspoon 0.9.57, Dual Displays on Mac Sierra.

I want to display all my Chrome Windows on the External Monitor or Screen.  I found some code and have been hacking it up to try and make it work.

```
function cascadeChromeWindows()
    display = hs.screen("Display")
    local windows = hs.application.get'Google Chrome':allWindows()
    local screen = windows[1]:screen():frame()

    local xMargin, yMargin = 0, 0
    local layout = {}
    for i, win in ipairs(windows) do
        local winPos = {
            win:application(),
            win:title(),
            "Display",
            nil, nil,
            hs.geometry.rect(
            (i-1), -- x
            (i-1), -- y
            1400,  -- w
            1200   -- h
            )
        }
        layout[#layout+1] = winPos
    end
    hs.layout.apply(layout)
end
```

I have this function bound to a hot key:

`hs.hotkey.bind({'cmd','alt','ctrl'}, "W", cascadeChromeWindows)`

Every time I execute the HotKey, the Chrome Window displays briefly in the Display (External) Monitor, before Moving (you can see the window move) to LCD Monitor.

From the snipet above you can see me try to hard code in the Display.   Something is still pulling the window back to the laptop screen.

Not sure if this is bug, or expected behavior.  My expectation is that once I pass Display to the layout, that's where the window will land.

**Comment by cmsj** [comment]
Some thoughts:

 * You don't need to specify `win:application()` and `win:title()` for each thing - you have the window object in `win` so you can just pass that, so that would change `winPos` to `{nil,win,"Display",etc}`
 * Are you sure "Display" is the name of your external monitor? You can get the names of your displays with: `hs.fnutils.each(hs.screen.allScreens(), function(screen) print(screen:name()) end)` in the console window

**Comment by cmsj** [comment]
Try this:

```lua
function cascadeChromeWindows()
  local display = hs.screen("Thunderbolt Display") -- Change this to the name of your monitor
  local offset = 5 -- This needs to be greater than zero, set it to however much you want the windows to be separated

  local frame = display:frame()
  local windows = hs.application.get("Google Chrome"):allWindows()
  local layout = {}
  local x = 0
  local y = 0

  for i, win in ipairs(windows) do
    -- Chrome tends to have lots of weird invisible windows, so we'll only do anything if this is a standard window
    if win:isStandard() then
        x = x + offset
        y = y + offset
        local winPos = { nil, win, display, nil, nil, hs.geometry.rect(frame.x + x, frame.y + y,1400,1200)}
        layout[#layout+1] = winPos
    end
  end
  hs.layout.apply(layout)
end
```
