### ISSUE TITLE
hs.timer runs in NSDefaultRunLoopMode not NSRunLoopCommonModes

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1598]
@cmsj, when you moved from the CFTimer to the NSTimer approach for `hs.timer`, you switched modes... any particular reason?

In working on an update to menubar which would allow, among other things, the ability to change the menu while it's open, I found that I could do so through the `hs` command, but not with a timer callback function... apparently things scheduled in the default run loop mode don't fire during activity in the other common modes (eventtap and ipc are two notable exceptions, both of which do *most* of their work in common modes).

I'll try switching modes in `hs.timer` later this weekend and see what breaks, but if you had a specific reason for the change, I can concentrate on seeing how/if we can work around that before submitting a pull.

**Comment by cmsj** [comment]
@asmagill I don't remember making a conscious choice for that, I may well have gone with whatever felt more defaulty, so feel free to do science on making it better :D

**Comment by latenitefilms** [comment]
Related: https://stackoverflow.com/questions/7222449/nsdefaultrunloopmode-vs-nsrunloopcommonmodes/7223765#7223765
