### ISSUE TITLE
How to middle mouse drag -> space+left mouse drag

### ISSUE THREAD

**Issue by krasnovpro** [Hammerspoon/hammerspoon#1601]
The hammerspoon syntax is too complicated for my understanding. Please help me with this task:
I need middle-mouse click and drag convert to left-mouse click with spacebar pressed.
In windows autohotkey.exe it is:

```
MButton::
  Send "{Space down}{LButton down}"
  KeyWait "MButton"
  Send "{Space up}{LButton up}"
  return
```

How to do it with hammerspoon?

**Comment by cmsj** [comment]
I'd recommend taking a look at BetterTouchTool - it's probably a more appropriate app for this kind of thing 🙂

**Comment by krasnovpro** [comment]
It's sad. I don't want to use other apps. I like hammerspoon.
