### ISSUE TITLE
hs.application.launchOrFocus not working for some applications

### ISSUE THREAD

**Issue by MichaelHindley** [Hammerspoon/hammerspoon#1602]
OS: 10.13.1 (High Sierra)
HS: 0.9.57

The code below has historically been working fine.
`hs.hotkey.bind({ "ctrl" }, "W", function() hs.application.launchOrFocus("Google Chrome") end)`

Since last update, HS will always just launch a new Google Chrome window instead, regardless of how many other Google Chrome windows are present.

Actual: Pressing CTRL + W 5 times results in 5 Google Chrome windows.
Expected: Pressing CTRL + W 5 times results in 1 Google Chrome window.

I have not yet been able to reproduce this behaviour with other applications.

**Comment by MichaelHindley** [comment]
Closing this, the issue was with a faulty Chrome build.

**Comment by johnste** [comment]
I've been experiencing this issue in both Chrome 63 and Chrome Canary 65 after my Mac has been in sleep mode - I can fix it temporarily by restarting Chrome.

**Comment by johnste** [comment]
As an update, I'm still having issues in Chrome Canary 66.

**Comment by cmsj** [comment]
@johnste it's possible that Canary needs to be given a different name there. Try running this in the console and see if Canary shows up under a different name:

```lua
hs.fnutils.each(hs.application.runningApplications(), function(app) print(app:name()) end)
```
