### ISSUE TITLE
how to start depend app while open specific url

### ISSUE THREAD

**Issue by yorkbai** [Hammerspoon/hammerspoon#1603]
some website include the download link point to another site .   I hope when the jump url like "https://pan.baidu.com/***/***" , first start aria2gui , then open this url .  plz !

**Comment by cmsj** [comment]
@yorkbai I'm not quite sure I understand your question, but if you want to open a URL with a specific application, you can do that with http://www.hammerspoon.org/docs/hs.urlevent.html#openURLWithBundle
