### ISSUE TITLE
Question: Right Mouse button + Dragging = Moving Left/Right a Space

### ISSUE THREAD

**Issue by nguyenhimself** [Hammerspoon/hammerspoon#1604]
I'm trying to emulate Karabiner's old setting for the Trackman Marble Trackball mouse, specificallyl

**While holding down the Right Mouse Button, one mouse drag from left to right = Move left a space, and vice versa.**

I already managed to map **RMB + Dragging Up & Down** to vertical scrolling, thanks to [this answer]. Just one more tweak and I am perfectly happy with using my trackball in Sierra. Thanks

(https://github.com/tekezo/Karabiner/issues/814#issuecomment-337643019).
![Karabiner](https://i.stack.imgur.com/fs0I3.png)

**Comment by cmsj** [comment]
We don't have very much API for interacting with Spaces because there's no public API for it. I wonder if you could make something work by emitting the system preferences keyboard shortcuts for changing Space?
