### ISSUE TITLE
Better error handling for hs.json.decode()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1612]
Currently if you feed `hs.json.decode()` something it can't handle it throws an error ("The data couldn’t be read because it isn’t in the correct format").

I reckon it would be better if it returned `nil` on error and print a warning to the console?

Thoughts @asmagill & @cmsj ?

**Comment by latenitefilms** [comment]
And yes, I realise I can just wrap it in `pcall()`, but I feel like that just adds an extra unnecessary step.

**Comment by asmagill** [comment]
a) I disagree -- pcall is in lua for that very reason -- if an error occurs and you want to capture it, use pcall, and
b) nil could be the result of a json decode as null is a valid json value:
~~~lua
> hs.json.decode("null")
nil
~~~

**Comment by latenitefilms** [comment]
Ah, cool - that makes sense! I'll continue to use `pcall()` then. Thanks @asmagill !
