### ISSUE TITLE
Why is fn key not triggered...?

### ISSUE THREAD

**Issue by YOnoda** [Hammerspoon/hammerspoon#1614]
I'm now trying to trigger `fn` + `delete` by keyboard remapping. However, the following code doesn't delete a character on the right; it deletes a character on the left.

So I feel the `fn` doesn't work in Hammerspoon, although the documentation on Dash includes `fn` as well as other keys.

Why does it not work in my case...?

		if keyCode == VK_F then
        if flagsMatches(flags, {"ctrl"}) then
            if event:getType() == 10 then
                hs.eventtap.keyStroke({"fn"}, "DELETE", 1000)
            end
        end
    end

**Comment by latenitefilms** [comment]
I can confirm that `hs.eventtap.keyStroke({"fn"}, "delete")` doesn't work for me either - it does a backspace, not a forward-delete, as it should.

Any ideas @asmagill or @cmsj ?

**Comment by rkalis** [comment]
As a fix for your problem you can write `hs.eventtap.keyStroke({}, "forwarddelete", 1000)` to achieve the results you want. That doesn't fix the underlying problem of course.

**Comment by cmsj** [comment]
I'm honestly not sure if sending fn-delete has ever worked, and I would argue that sending `forwarddelete` is a better solution anyway 🙂

**Comment by cmsj** [comment]
@YOnoda it's possible that Terminal does some unusual input processing that we can't interact with. I would honestly suggest that for keyboard remapping, look at Karabiner Elements - it works in the kernel, so it can change keypresses before the application layers ever see them.
