### ISSUE TITLE
moveOnescreenEast can't use 

### ISSUE THREAD

**Issue by Pioneer-Linzi** [Hammerspoon/hammerspoon#1615]
module.throwLeft = function ()
 local this = current:new()
 this.window:moveOneScreenWest()
 end
module.throwRight = function ()
local this = current:new()
this.window:moveOneScreenEast()
end

I use this , but not any thing happen,   I use mac os high sierra 10.13.1,

**Comment by Pioneer-Linzi** [comment]
no  log to show

**Comment by cmsj** [comment]
That looks like a snippet of a larger config - are you able to share your whole config?

**Comment by mvgrimes** [comment]
I'm seeing a similar issue on version 0.9.70. I've commented out everything in my init.lua excep:

```
hs.hotkey.bind({ "alt" }, "X", function() 
  local win = hs.window.focusedWindow()
  if win == nil then
    hs.alert.show("No win")
    return
  end

  hs.alert.show("Going West")
  win:moveOneScreenWest()
end)
```

I see the "Going west" alert, but nothing happens. I've tested with numerous application windows and ensured that there is a space to the west.

Here is the output in the console:

```
2018-09-26 16:32:46: -- Lazy extension loading enabled
2018-09-26 16:32:46: -- Loading ~/.hammerspoon/init.lua
2018-09-26 16:32:46: -- Loading extension: hotkey
2018-09-26 16:32:46: 16:32:46     hotkey: Enabled hotkey ⌥X
2018-09-26 16:32:46: -- Done.
2018-09-26 16:33:05: -- Loading extension: window
2018-09-26 16:33:05: -- Loading extension: uielement
2018-09-26 16:33:05: -- Loading extension: alert
```

**Comment by alexparker** [comment]
@mvgrimes Did you ever resolve this? i'm having the exact same issue - Looking for a solution :)

**Comment by sameer03697** [comment]
Is this issue fixed?

**Comment by sameer03697** [comment]
@mvgrimes ?

**Comment by mvgrimes** [comment]
Yes it seems to be working in version 0.9.97. Thanks!
