### ISSUE TITLE
Is it possible to distinguish between scrollevent coming from a trackpad or a mouse?

### ISSUE THREAD

**Issue by therealmarv** [Hammerspoon/hammerspoon#1618]
I want to press a key on mouse scroll event which works good.
But I also use a trackpad from time to time and on the trackpad I don't want this scrollevents to fire up. Is it possible to distinguish the two? I tried to lookup http://www.hammerspoon.org/docs/hs.eventtap.event.html#properties but so far no luck in finding any difference.

```lua
hs.eventtap.new({hs.eventtap.event.types.scrollWheel}, function(e)
  scrollWheelClick = e:getProperty(hs.eventtap.event.properties.scrollWheelEventDeltaAxis1)
  app = hs.application.frontmostApplication()
  if app:name() == "Xee³" then
    if scrollWheelClick > 0 then
      hs.eventtap.keyStrokes(",")
      return true
    elseif scrollWheelClick < 0 then
       hs.eventtap.keyStrokes(".")
      return true
    end
  end
end):start()
```

**Comment by cmsj** [comment]
At the moment, no. The level of the OS at which we run is too late in the input chain for this information to still be available, unfortunately. I'm not sure this will ever change unless we start including kernel extensions (something we are really unlikely to do!)

You might be able to make this work with Karabiner Elements to remap the mouse scroll events, but I'm not sure.

**Comment by therealmarv** [comment]
ok, thx anyway and also for explanation! :)
