### ISSUE TITLE
Add hs.styledtext support to hs.chooser

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1624]
@cmsj - I was thinking about using `hs.chooser` as a font selection tool. Is it possible to add `hs.styledtext` support to `hs.chooser`?

To clarify, it would be great if the "text" and "subText" for each individual "choice" could be a `hs.styledtext` object - so that I could use `hs.chooser` as a font selection tool (i.e. each result will be displayed as a different font).

**Comment by cmsj** [comment]
@latenitefilms do you mean to the search box, or the results?

**Comment by latenitefilms** [comment]
Results would be amazing!

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - I'm happy to give this a bash myself if one of you can point me in the right direction?

**Comment by cmsj** [comment]
So, I think the branch I just pushed should address this, but I can't get it to actually do anything. I can see from the debugger that `NSAttributedString` objects are making it into the `NSTableView` delegate methods and being set on the choice cells, but my quick experiment with it doesn't work:

```diff
diff --git a/Spoons/Seal.spoon/seal_apps.lua b/Spoons/Seal.spoon/seal_apps.lua
index 5cb3111..cda6f77 100644
--- a/Spoons/Seal.spoon/seal_apps.lua
+++ b/Spoons/Seal.spoon/seal_apps.lua
@@ -79,7 +79,10 @@ function obj.choicesApps(query)
                 instances = hs.application.applicationsForBundleID(app["bundleID"])
             end
             if #instances > 0 then
-                choice["text"] = name .. " (Running)"
+--                choice["text"] = name .. " (Running)"
+                styled = hs.styledtext.new(name .. " (Running)")
+                styled:setStyle({color=hs.drawing.color.hammerspoon.osx_red}, -9, -1)
+                choice["text"] = styled
             else
                 choice["text"] = name
             end
```

I've never used `hs.styledtext` before - am I doing something wrong with it?

**Comment by cmsj** [comment]
@latenitefilms maybe you could try my branch and let me know if you get any luck with it?

**Comment by latenitefilms** [comment]
@cmsj - Soooooooo close! The `subText` works, but the `text` doesn't.

Maybe [this line](https://github.com/cmsj/hammerspoon/blob/ec081a663643d8cbd7975eaa13d4d2222e4f957c/extensions/chooser/HSChooser.m#L388
) is the issue?

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))
end

local fancyText = styledtext.new("First Choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 20 },
    })

local fancySubText = styledtext.new("This is the subtext of the first choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 20 },
    })

console.printStyledtext(fancyText)
console.printStyledtext(fancySubText)

local choices = {
	{
		["text"] = fancyText,
		["subText"] = fancySubText,
		["uuid"] = "0001"
	},
	{ 
		["text"] = "Second Option",
		["subText"] = "I wonder what I should type here?",
		["uuid"] = "Bbbb"
	},
	{ 
		["text"] = "Third Possibility",
		["subText"] = "What a lot of choosing there is going on here!",
		["uuid"] = "III3"
	},
}

theChooser = chooser.new(completionFn)
	:choices(choices)
	:show()
```

**Comment by latenitefilms** [comment]
Ummm... I'm not sure what's going on. The code you've added definitely seems to get setting `text` to 
an `NSAttributedString`. Something must be happening to it AFTER `- (NSView *)tableView:(NSTableView *)tableView viewForTableColumn:(NSTableColumn *)tableColumn row:(NSInteger)row`?

<img width="1046" alt="screen shot 2018-04-18 at 8 36 10 am" src="https://user-images.githubusercontent.com/22286696/38902389-a9a93990-42e3-11e8-9eba-ea28a76c4e29.png">

**Comment by cmsj** [comment]
@latenitefilms try now?

**Comment by latenitefilms** [comment]
No luck I'm afraid. `subText` works fine, `text` does not, which is weird. `hs.styledtext` is being passed back in the `completionFn`.

Here's my test code:

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

console.clearConsole()

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))	
	
	print("text:")
	console.printStyledtext(result.text)
	print("subText:")
	console.printStyledtext(result.subText)

end

local text = styledtext.new("First Choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 20 },
    })

local subText = styledtext.new("This is the subtext of the first choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 20 },
    })

print("text:")
console.printStyledtext(text)
print("subText:")
console.printStyledtext(subText)

local choices = {
	{
		["text"] = text,
		["subText"] = subText,
		["uuid"] = "1"
	},
	{ 
		["text"] = text,
		["subText"] = subText,
		["uuid"] = "2"
	},
	{ 
		["text"] = text,
		["subText"] = subText,
		["uuid"] = "3"
	},
}

theChooser = chooser.new(completionFn)
	:choices(choices)
	:show()
```

This is what it looks like:

<img width="747" alt="screen shot 2018-04-18 at 9 12 11 am" src="https://user-images.githubusercontent.com/22286696/38903527-9da6234c-42e8-11e8-841d-fa75ae59adef.png">

Console looks like this:

<img width="1072" alt="screen shot 2018-04-18 at 9 12 47 am" src="https://user-images.githubusercontent.com/22286696/38903542-b221d096-42e8-11e8-8e5b-025d78ef12db.png">

I'll keep trying to work out why `subText` works fine, but `text` doesn't. Very odd.

Thanks for all your help!!

**Comment by latenitefilms** [comment]
Ok, worked it out!

No idea what this means or how it works, but if you opened up `HSChooserWindow.xib` the `Text` Chooser Cell had two "Referencing Outlets", whereas the `Sub Text` only had one, so I removed the second one to match, and problem solved:

<img width="1512" alt="screen shot 2018-04-18 at 9 19 22 am" src="https://user-images.githubusercontent.com/22286696/38903717-a23090e0-42e9-11e8-8bb1-00a22683a0ef.png">

**Comment by latenitefilms** [comment]
@cmsj - Note, you need to remove the second value from both the Text row without the subtext and the one below it without.

**Comment by latenitefilms** [comment]
This test code:

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

console.clearConsole()

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))	
	
	print("text:")
	console.printStyledtext(result.text)
	print("subText:")
	console.printStyledtext(result.subText)

end

local text = styledtext.new("Styled Text", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 18 },
    })

local subText = styledtext.new("Styled Subtext", {
        color = {hex = "#800000", alpha = 1},
        font = { name = "Futura", size = 10 },
    })

print("text:")
console.printStyledtext(text)
print("subText:")
console.printStyledtext(subText)

local choices = {
	{
		["text"] = text,
		["subText"] = subText,
		["uuid"] = "1"
	},
	{ 
		["text"] = "Plain Text",
		["subText"] = "Plain Text Subchoice",
		["uuid"] = "2"
	},
	{ 
		["text"] = text,
		["uuid"] = "3"
	},
	{ 
		["text"] = "Plain Text",
		["uuid"] = "3"
	},		
}

theChooser = chooser.new(completionFn)
	:choices(choices)
	:show()
```

...gives me:

<img width="788" alt="screen shot 2018-04-18 at 9 37 07 am" src="https://user-images.githubusercontent.com/22286696/38904156-2157df20-42ec-11e8-9770-1e565bb5e99d.png">

**Comment by cmsj** [comment]
@latenitefilms good catch! thanks :)

**Comment by cmsj** [comment]
Good point :)

**Comment by latenitefilms** [comment]
@cmsj - Not sure what's changed, but this now seems to be broken in 0.9.66?

Using the same test code above, now gives me:

<img width="697" alt="screen shot 2018-05-08 at 9 11 47 am" src="https://user-images.githubusercontent.com/22286696/39729559-e308f024-529f-11e8-9297-a3c1a94388e2.png">

I think maybe something has gone funky in LuaSkin - given we're also seeing this:

https://github.com/Hammerspoon/hammerspoon/issues/1441#issuecomment-387079056

Thoughts?

**Comment by latenitefilms** [comment]
Doh! Sorry - ignore me, I was testing in 0.9.66, rather than the latest `master` branch.

**Comment by latenitefilms** [comment]
@cmsj - Ok, I've worked out what's broken - but not sure how to fix.

This works:

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

console.clearConsole()

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))	
	
	print("text:")
	console.printStyledtext(result.text)
	print("subText:")
	console.printStyledtext(result.subText)

end

local text = styledtext.new("Styled Text", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 18 },
    })

local subText = styledtext.new("Styled Subtext", {
        color = {hex = "#800000", alpha = 1},
        font = { name = "Futura", size = 10 },
    })

print("text:")
console.printStyledtext(text)
print("subText:")
console.printStyledtext(subText)

local choices = {}

for i, v in pairs(styledtext.fontNames()) do
	local choice = {}	
	if string.sub(v, 1, 1) ~= "." then 
		local displayName = styledtext.fontInfo(v).displayName
		choice.text = styledtext.new(displayName, {
			font = { name = v, size = 18 },
		})
		choice.subText = ""
		choice.uuid = choice.text
		table.insert(choices, choice)
	end		
end

theChooser = chooser.new(completionFn)
	:choices(choices)
	:show()
```

...but if you remove `choice.subText = ""`, then it only shows plain text?

Any ideas?
