### ISSUE TITLE
hs.window.switcher shows UI only on primary display

### ISSUE THREAD

**Issue by reestr** [Hammerspoon/hammerspoon#1627]
When using hs.window.switcher on a macbook with external display, the UI only shows on the macbook internal display, even if the currently focus'd application is on the external display.  Expected behaviour, UI will show on the screen/workspace which last holds focus.

This is especially annoying if there is a maximised application on the macbook display, the hs.window.switcher UI sits behind the maximised application and cannot be seen by the user.

**Comment by cmsj** [comment]
Thanks, this should be fixed in the next release :)

**Comment by reestr** [comment]
That's great, the fact this was worked on Christmas Eve makes it even more awesome! Thanks!

**Comment by cmsj** [comment]
@reestr (you may or may not have noticed, but 'the next release' is now out, 0.9.58 :)
