### ISSUE TITLE
hs.axuielement - Accessing Accessibility Objects with Hammerspoon

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1630]
I just realised we don't actually have an issue for [`hs._asm.axuielement`](https://github.com/asmagill/hs._asm.axuielement) in the Hammerspoon repository, so I thought we should probably make one as a place to post notes until @asmagill has time to merge into Hammerspoon Core.

My Wishlist for `hs.axuielement`:

- [x] Add Notifications/Observers

@asmagill also has a to-do list [here](https://github.com/asmagill/hs._asm.axuielement/blob/master/TODO.txt).

For anyone who's interested, we've been using `hs._asm.axuielement` for over a year now in [CommandPost](http://commandpost.io), and it's truly awesome.

**Comment by latenitefilms** [comment]
@asmagill - Playing around with `0.7alpha` I've noticed:

```
2018-01-15 17:47:00: ********
2018-01-15 17:47:00: 17:47:00 ERROR:hs._asm.ax: .../CommandPost/src/extensions/hs/_asm/axuielement/init.lua:200: attempting to make a 'nil' into a constant table
2018-01-15 17:47:00: ********
```

**Comment by asmagill** [comment]
Have you done a complete restart of Hammerspoon? The `notifications` table moved, so if it's still loading the cached `internal.so` file, you would see something like this.

**Comment by latenitefilms** [comment]
@asmagill - Got it in one. I thought I did a restart, but I obviously didn't. Thanks for the fast reply!

**Comment by latenitefilms** [comment]
Apologies in advance @asmagill - I'm sure this will be the first of MANY questions.

Here's what I'm trying:

```
> ax = require("hs._asm.axuielement")
playhead = _fcp:timeline():playhead():UI()
print(playhead)
o = ax.observer.new(playhead:pid())
    :callback(function(...) print(hs.inspect(table.pack(...), { newline = " ", indent = "" })) end)
    :addWatcher(playhead, "AXValueChanged")
    :start()
2018-01-15 21:47:23: hs._asm.axuielement: AXValueIndicator (0x60c000058058)
[string "ax = require("hs._asm.axuielement")..."]:4: Notification is not supported by target.
stack traceback:
	[C]: in method 'addWatcher'
	[string "ax = require("hs._asm.axuielement")..."]:4: in main chunk
	[C]: in function 'xpcall'
	...Github/CommandPost/src/extensions/hs/_coresetup/init.lua:484: in function <...Github/CommandPost/src/extensions/hs/_coresetup/init.lua:464>

> hs.inspect(require("hs._asm.axuielement").observer._internals())
2018-01-15 21:47:26: -- Loading extension: inspect
{
  [<userdata 1> -- hs._asm.axuielement.observer: (0x60c0002566d8)] = {
    callbackRef = 1,
    isRunning = false,
    selfRefCount = 2,
    watching = {
      [<userdata 2> -- hs._asm.axuielement: AXValueIndicator (0x60c000c40d18)] = {}
    }
  }
}
```

According to UI Browser, I should be able to register to this notification:

<img width="1277" alt="screen shot 2018-01-15 at 9 48 09 pm" src="https://user-images.githubusercontent.com/22286696/34938834-ce763596-fa3d-11e7-9727-2b98045a7aec.png">

Thoughts?

**Comment by asmagill** [comment]
Hmm, not sure... but I am intrigued by UI Browser giving you a list of available notifications -- I looked for a way to look this up and couldn't find one... guess I'll look closer.

Last night I was just happy that I finally got it to work without crashing and didn't do a whole lot of testing beyond what I mentioned about Safari. Let me try some more today and see if I can come up with any suggestions.

**Comment by asmagill** [comment]
Some implementation questions, unrelated to the issue you're having right now, but I want your input:

* Should `hs.axuielement.observer.new` allow you to use an `hs.application` object instead of the `pid`? Maybe accept either? What about maybe also allowing any element object, since you can easily get the pid from that as well?
* Should the `hs._asm.axuielement` metatable have an `:observe(notification1, ...)` method added which implicitly creates the observer for you? It would have to return the observer object instead of the element object, so subsequent methods (callback, start, etc.) would be applied to the observer rather then the element itself... would it be confusing to change userdata objects mid-stream (e.g. `ax.applicationElement(hs.application("Hammerspoon")):observe("AXTitle"):callback(...):start()`)?
* regarding the tables of constants, which approach do you think makes the most sense for the predefined labels (e.g. attributes, notifications, etc.):

With attributes, they are laid out as key-value pairs in the table, but the key is just a "friendlier" version of the actual string required -- when passing it directly into the appropriate function (i.e. not using the metamethods which create "dynamic" methods on the fly), you still need to use the full string, e.g.:

~~~lua
ax = require("hs._asm.axuielement")
element = ax.applicationElement(hs.application("Hammerspoon"))

-- to get the title, the following are the "official" methods:
element: attributeValue("AXTitle")
element:attributeValue(ax.attributes.general.title)
-- using the metamethods, which do an implicit `attributeValue` for you:
element:title()
element:AXTitle()
~~~

While the notifications table (`ax.observer.notifications`) is just an array of the pre-defined search types, i.e. not key-value pairs. So if you're using a reference from the table, you have to do so by index number, e.g.:
~~~lua
observer:addWatcher(element, "AXTitleChanged")
observer:addWatcher(element, ax.observer.notifications[36])
~~~

I like the label approach in attributes better, if you're actually referencing the constants table directly, but honestly in almost all of my code, I just type in the exact string because it's shorter -- the key-value approach is a more obvious win if you're converting a label into a number (think `hs.canvas.windowBehaviors`), but it's not quite as obviously beneficial when it maps to a similarly descriptive string value.

Your thoughts?

**Comment by asmagill** [comment]
@latenitefilms when you register in UI Browser to watch the object you're trying to target, do you get notification details in the log if you change the ui element in FCP?

I'm trying to determine if the list of notifications UI Browser is offering are just the standard ones that are appropriate for the type of element or if it's actually able to query the element about what notifications it supports.  If the former, it's still up to the application (FCP) to decide if they *will* support the standard notification; if it's the latter, I'd love to know how they're doing it... an initial google search is less then hopeful.

**Comment by latenitefilms** [comment]
> Should hs.axuielement.observer.new allow you to use an hs.application object instead of the pid? Maybe accept either? What about maybe also allowing any element object, since you can easily get the pid from that as well?

I think it makes sense if it could accept any object that you can get a PID from (i.e. `hs.application`, `hs.window` or `hs._asm.axuielement`).

> Should the hs._asm.axuielement metatable have an :observe(notification1, ...) method added which implicitly creates the observer for you?

Yeah, that sounds like it could be handy.

> regarding the tables of constants, which approach do you think makes the most sense for the predefined labels (e.g. attributes, notifications, etc.):

I would normally just type: `observer:addWatcher(element, "AXTitleChanged")`.

> when you register in UI Browser to watch the object you're trying to target, do you get notification details in the log if you change the ui element in FCP?

Actually... no, I don't - so maybe it's just that Final Cut Pro doesn't support that notification.

To quote the manual:

> Open UI Browser's Notifications preferences by choosing UI Browser > Preferences or using the Command-comma keyboard shortcut, and then select the Notifications pane when the Preferences window opens.
> 
> Normally, UI Browser lets you register to observe any of the standard Accessibility notifications implemented by Apple's Accessibility technology. See Observe notifications. Developers of assistive applications may want to implement custom notifications. To test them in UI Browser, add new notification names in UI Browser's Notifications preference pane. The new notifications will appear in the Notifications drawer for every selected UI element, allowing you to register to observe them in the Notification Log window.
> 
> By default, the Notification Log window opens only when you specifically open it by choosing the Notification Log item in the View menu or clicking the View Log button in the Notifications drawer. If you prefer it to open automatically whenever you register to observe a notification, set the "Open log when registering a notification" preference.
> 
> By default, UI elements other than the root application element only issue notifications that are appropriate to the element's function. For example, a window issues a 'window miniaturized' notification, while a button does not. However, the Accessibility API does not rigorously define the notifications that should be implemented by each kind of UI element. Developers testing their implementations of the Accessibility API can set the "Register any notification for any UI element" preference to verify exactly what notifications are issued by a particular UI element. Setting this preference causes UI Brower's Notifications drawer to display every notification implemented by the Accessibility API for the selected UI element, so you can register any of them to test whether they work.
<img width="561" alt="screen shot 2018-01-16 at 7 05 19 am" src="https://user-images.githubusercontent.com/22286696/34959717-db15fd6a-fa8b-11e7-9a37-2cd4060e3e34.png">

This PDF might also be of interest?

http://pfiddlesoft.com/frameworks/downloads/Assistive_Application_Programming_Guide.pdf

**Comment by latenitefilms** [comment]
Pinging @randomeizer

**Comment by asmagill** [comment]
> > regarding the tables of constants, which approach do you think makes the most sense for the predefined labels (e.g. attributes, notifications, etc.):
>
> I would normally just type: `observer:addWatcher(element, "AXTitleChanged")`.

So you'd be ok if I moved all of the constants tables for `hs._asm.axuielement` to the list approach used for `hs._asm.axuielement.observer.notifications`? That way you could still type the table's name (off of a global variable containing the module or something like `hs.axuielement.attributes.general` once it's moved into core) into the console to view the list as a reference, but then specify the actual string value you want when writing your code.

I'll review the pdf later and see if it offers any additional thoughts or insights.

**Comment by latenitefilms** [comment]
Yes, that all sounds good to me. Thanks heaps!

**Comment by latenitefilms** [comment]
For anyone who's playing along at home, I've just thrown together a very quick and dirty way to help work out what Accessibility Notifications are available for an application:

```lua
ax = require("hs._asm.axuielement")
app = hs.application("Final Cut Pro")
ae = ax.applicationElement(app)
o = ax.observer.new(app:pid())

processChildren = function(child)
    failureCount = 0
    failures = ""
    for i, notification in pairs(ax.observer.notifications) do
        local status, err = pcall(function() o:addWatcher(child, notification) end)
        if not status then
            failureCount = failureCount + 1
            if i == #ax.observer.notifications then
                failures = failures .. notification
            else
                failures = failures .. notification .. ", "
            end
        end
    end
    if failureCount == 0 then
        print(string.format("All notifications available for: %s", child))
    else
        if failureCount == #ax.observer.notifications then
            print(string.format("ERROR: All notifications unavailable for: %s", child))
        else
            print(string.format("ERROR: Some notifications unavailable for: %s (%s)", child, failures))
        end
    end    

    children = child:attributeValue("AXChildren")
    if children and #children > 0 then
        for _, v in pairs(children) do
            processChildren(v)
        end
    end

end

rootChildren = ae:attributeValue("AXChildren")
if #rootChildren > 0 then
    print(string.format("PROCESSING: %s", app))
    print("--------------------------------------")
    for i, v in pairs(rootChildren) do
        processChildren(v)
    end
else
    print("ERROR: There are no root children in application, so aborting.")
end
```

**Comment by asmagill** [comment]
How long does this take to iterate through the entire FCP app?  Is it worth adding a variant of this to the module itself?

**Comment by latenitefilms** [comment]
@asmagill - About 4 seconds. Having something like this in the module itself would definitely be really helpful. Maybe something like `hs._asm.axuielement:supportedNotifications()`?

**Comment by latenitefilms** [comment]
Merged!
