### ISSUE TITLE
hs.socket callback error

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1634]
It doesn't cause any issues, but just FYI @asmagill & @cmsj, every now and again I get the following error in the console:

```
2017-12-29 10:31:20: ********
2017-12-29 10:31:20: 10:31:20 ERROR:   LuaSkin: hs.socket connect callback error: attempt to call a nil value
stack traceback:
2017-12-29 10:31:20: ********
```

Not sure why?

**Comment by cmsj** [comment]
All that really tells us is that a Lua error occurred somewhere in your callback.

**Comment by latenitefilms** [comment]
Thanks @cmsj - no doubt I just had a typo in the callback or something!
