### ISSUE TITLE
hs.http.asyncGet is crashing my computer

### ISSUE THREAD

**Issue by wangsongiam** [Hammerspoon/hammerspoon#1635]
I love Hammerspoon and I am using it to sync my behavior with a database, and I need to occasionally get some data from the cloud with `hs.http.asyncGet`. Yet apparently getting a longer-than-100-char-or-something-string is making my computer crash into system user login page. Not sure if that's designed by purpose, but knowing the threshold of the crashing point would be helpful.

**Comment by wangsongiam** [comment]
Also, looks like using a URL with querying params is not supported yet, is it possible to workaround that?

**Comment by cmsj** [comment]
@wangsongiam we certainly shouldn't be crashing anything at all, and it shouldn't even be possible to crash hard enough to log you out. Are you able to share some Lua code that reproduces this?

**Comment by wangsongiam** [comment]
I don't have that code anymore, I trimmed the response to a shorter one and it works 99% of the time. The left 1% crash only the Hammerspoon app but I can live with that once in a day. Btw I have 3 app watchers listening to a bunch of keystroke events. Closing it but thank you for the follow-up.

**Comment by cmsj** [comment]
If Hammerspoon is crashing, I want to know about it, so if you have a config you can share that crashes even once a day, please do :)
