### ISSUE TITLE
hs.midi - Incorrectly returning noteOn when should be noteOff

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1636]
@asmagill - I'm not sure if this is an issue in `hs.midi` or MIKMIDI 1.6.2, but when I have a MIDI keyboard connected to my computer, when I press a key I'm now seeing two `noteOn` commands, instead of a `noteOn` and `noteOff`.

When I was originally testing things, I was definitely seeing `noteOff` commands - so I'm not sure when/how it broke.

Using the following test code:

```
midiDevice = hs.midi.new(hs.midi.devices()[2]) midiDevice:callback(function(object, deviceName, commandType, description, metadata)
       print("object: " .. tostring(object))
       print("deviceName: " .. deviceName)
       print("commandType: " .. commandType)
       print("description: " .. description)
       print("metadata: " .. hs.inspect(metadata))
end)
```

...gives me:

```
2017-12-30 11:02:05: object: table: 0x60c00046f200
2017-12-30 11:02:05: deviceName: USB O2
2017-12-30 11:02:05: commandType: noteOn
2017-12-30 11:02:05: description: <MIKMIDINoteOnCommand: 0x600000a32e20> time: 11:02:05.068 command: 159 channel 0 note: 25 velocity: 42 
	data: <90192a>
2017-12-30 11:02:05: metadata: {
  channel = 0,
  note = 25,
  timestamp = "11:02:05.068",
  velocity = 42
}
2017-12-30 11:02:05: object: table: 0x60c00046f200
2017-12-30 11:02:05: deviceName: USB O2
2017-12-30 11:02:05: commandType: noteOn
2017-12-30 11:02:05: description: <MIKMIDINoteOnCommand: 0x60400063c360> time: 11:02:05.652 command: 159 channel 0 note: 25 velocity: 0 
	data: <901900>
2017-12-30 11:02:05: metadata: {
  channel = 0,
  note = 25,
  timestamp = "11:02:05.652",
  velocity = 0
}
```

Notice the `<MIKMIDINoteOnCommand: 0x600000a32e20>` and `<MIKMIDINoteOnCommand: 0x60400063c360>` - which makes me think it's maybe a bug in MIKMIDI? Any ideas @armadsen?

**Comment by latenitefilms** [comment]
Actually, maybe this is the issue: https://github.com/mixedinkey-opensource/MIKMIDI/issues/207

**Comment by latenitefilms** [comment]
Yep - that seems to be the issue, the MIDI keyboard I'm currently using must just trigger a second Note On command with 0 velocity instead of Note Off. So it's not a bug - but I will make a note of this in the documentation.

**Comment by asmagill** [comment]
I can confirm that some keyboards do exactly that -- they use a noteOn with velocity 0 instead of a noteOff... I forget where I first read about this (it was years ago), but http://www.kvraudio.com/forum/viewtopic.php?t=291892 gives a pretty good run down of why.

**Comment by latenitefilms** [comment]
Legend, thanks @asmagill!
