### ISSUE TITLE
Hammerspoon

### ISSUE THREAD

**Issue by jiexishede** [Hammerspoon/hammerspoon#1638]
https://stackoverflow.com/questions/48037404/how-to-end-the-sleepscript-when-sleep-%EF%BD%8Danual

**Comment by cmsj** [comment]
Rather than do the shutdown with a 30 minute delay, perhaps look at using hs.timer.doAfter() to call the shutdown only when you want it, then you have an hs.timer object you can interact with, make a menu icon for, or hotkeys, etc. Easy to cancel :)
