### ISSUE TITLE
get current front application without windows?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#164]
Trying to find out if an application without mac recognizable windows (specifically X11, but any app without windows but a menubar might qualify) is the frontmost active application without being able to use hs.window.focusedWindow()... any thoughts, or am I missing something obvious, or is this actually something we're missing?

**Comment by cmsj** [comment]
This should be fully addressed by the landing of #169

**Comment by cmsj** [comment]
https://github.com/fikovnik/ShiftIt/blob/develop/ShiftIt/X11WindowDriver.m Those folks abstracted things a little and added drivers for both Accessibility and X11. I'm not sure it's something I want to put any time into, but it's an interesting option for the future.
