### ISSUE TITLE
Open Config triggers a file change notification

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#1647]
Setup: Mac OS High Sierra 10.13.2 / Hammerspoon 0.9.58

I run with my ``hs.configdir`` set to ``/Users/xxxx/.config/hammerspoon`` by setting defaults

```sh
/usr/bin/defaults write org.hammerspoon.Hammerspoon MJConfigFile ~/.config/hammerspoon/init.lua```
```

All the lua files in there are symlink to original files in a directory ```/Users/xxx/work/mine/my_git_repo/_os/Darwin/.config/hammerspoon``` in my personal git repo ```/Users/xxx/work/mine/my_git_repo``` which I watch using an ``hs.pathwatcher``.

Problem:

Whenever I do an Open Config from hs global menu, a modify event gets triggered and my pathwatcher gets triggered. This didn't use to be the case until a few months ago. The modification flags according to

```
configFileWatcher = hs.pathwatcher.new(original_config.DIR,  function(paths, flagTables)
    print(hs.inspect(flagTables))
    for i = 1, #paths do
        if fs.isFile(paths[i]) then
            print(paths[i])
            -- reloadConfig(paths, true)
            return
        end
    end
...
...
```

are

```
{ {
    itemIsFile = true,
    itemXattrMod = true
} }
/Users/xxxx/work/mine/my_git_repo/_os/Darwin/.config/hammerspoon/init.lua
```

which seems to be an xattr modification. Is it only me or xattr shouldn't be getting modified and this notification shouldn't trigger on just opening config file? Checking the xattrs before or after does show changes.

```sh
% xattr -l ~/work/mine/my_git_repo/_os/Darwin/.config/hammerspoon/init.lua
com.apple.lastuseddate#PS:
00000000  85 D3 58 5A 00 00 00 00 47 E1 9D 26 00 00 00 00  |..XZ....G..&....|
00000010

% xattr -l ~/work/mine/my_git_repo/_os/Darwin/.config/hammerspoon/init.lua
com.apple.lastuseddate#PS:
00000000  F9 D3 58 5A 00 00 00 00 37 05 5B 29 00 00 00 00  |..XZ....7.[)....|
00000010
```

**Comment by latenitefilms** [comment]
I’ve also noticed that Hammerspoon reloads for me everytime I OPEN a Lua file, as opposed to edit a Lua file, which never used to be the case. Never looked into it properly though.

I have a feeling this happened around the same I updated to High Sierra and my hard drive changed formats to APFS. Probably related?

**Comment by asmagill** [comment]
If the OS has changed such that an xattr changes when a file is opened, it would trigger the path watcher -- we can't stop if from triggering as that's an OS decision. However you can check the flags table and only do your reload when `itemModified` or `itemCreated` is true.

**Comment by junkblocker** [comment]
If I just do ``vi /that/file.lua`` or even from MacVim.app directly, the xattr doesn't change. If I open it from hs, it does. So I am wondering if hs us using something special to open it that might be causing xattr change.

**Comment by junkblocker** [comment]
So I guess hammerspoon is doing equivalent of ``open -e /path/to/file.lua`` which does change xattrs. I am closing this and resorting to doing a modification flags check.

**Comment by asmagill** [comment]
I would have to look at the code later tonight, but Hammerspoon will probably be using whatever the Foundation API method (probably in NSWorkspace) is to open a file within the user's defined text editor is, so yes, it probably is the equivalent of "open -e"

**Comment by cmsj** [comment]
Yep, Hammerspoon uses the highest level API for opening files, where VIM uses almost the lowest (although given that vim usually creates a temporary .swp file, it can easily trigger pathwatcher).

I hadn’t noticed this behaviour, but it does look like the OS is performing as intended.

I would suggest that we make sure http://www.hammerspoon.org/Spoons/ReloadConfiguration.html has all the right little tweaks :)
