### ISSUE TITLE
hs.bonjour - Add Bonjour Support

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1653]
See: https://github.com/asmagill/hammerspoon_asm/tree/master/bonjour

**Comment by asmagill** [comment]
@cmsj, @latenitefilms -- I believe that the module is complete and documentation has been added.

I hope to move it to `hs.bonjour` and provide a pull to Hammerspoon in a day or so, and follow shortly with a spoon which will use it to provide a launcher for advertised services (initially ssh and http, but I have in mind a templating approach which should allow adding other services that follow well know formats easily as well).

This is the version that uses `NSNetService` and `NSNetServiceBrowser`, so its use is limited to browsing advertisements and publishing things on your own machine; the rewrite using `dns_sd.h` bas begun, but is targeted for v2.0 and currently has no ETA.

**Comment by latenitefilms** [comment]
Woohoo! Amazing work! Now I just need to find a reason/excuse to use it in CommandPost! :)
