### ISSUE TITLE
HS consuming huge amounts of RAM

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1671]
Sometime within the last few days, HS begain consuming huge amounts of RAM for no apparent reason.  Even upon first startup, it immediately is using about 128MB.  It used to only use 15-25.

When I activate my fake geektool stuff, it skyrockets to ~750MB, even though normally it should only be about 40MB.

If I have time I'll bisect.

This is 10.13.3 by the way.

**Comment by chdiza** [comment]
Forgot to mention that I'm building HS from source, not downloading a precompiled binary.

**Comment by chdiza** [comment]
The "bad" commit is b5efc2915efa72086e241

If I want to build "release" rather than "debug", then (a) what is the proper way to do this?  `make release`?  (b) Is this even going to work without an Apple developer signing cert?

**Comment by chdiza** [comment]
The answer to (b) is apparently "No".

I built by doing `make release`.  It built and I installed it.  When I tried to run it, I got a macOS dialog box saying:
```
Insecure update error!

For security reasons, you need to code sign your application or sign your updates with a DSA key. See https://sparkle-project.org/documentation/ for more information.
```

**Comment by chdiza** [comment]
I figured out how to get around that, by doing an extra `codesign` step for sparkle (which was not necessary in a debug build).

But now, every time I restart HS, I have to re-grant it accessibility in System Preferences.  This was not the case in the debug build.  It would stick.

**Comment by cmsj** [comment]
@chdiza yeah sorry about this, I've turned on the memory checking options because we're on a general hunt for some heap corruption bugs that have been eluding capture for some time. Your best option here may well be to go into the `Product->Scheme->Manage Schemes` menu, duplicate the `Hammerspoon` scheme, then edit that new scheme and in the `Run` section, under `Diagnostics`, turn off all the things. Also make sure `Shared` is unticked in the scheme list, and your change should remain completely local and not block you from clean `git pull`s. Next time we make a critical build change though, you'll need to repeat this (but those are fairly rare).

**Comment by chdiza** [comment]
@cmsj OK, I figured it was something like that.

> I've turned on the memory checking options because we're on a general hunt for some heap corruption bugs that have been eluding capture for some time.

So will these be permanently on, or just until those heap corruption bugs are found?  Knowing this might help me decide some workaround details.

**Comment by cmsj** [comment]
It's hard to say at this point. The same day I turned them on, I found two memory bugs, so part of me really wants to leave them on permanently so we're more likely to catch our subtle bugs, but I do appreciate that for people who self-build, it's a fairly painful imposition!

**Comment by asmagill** [comment]
@cmsj for those of us that actively code for HS I’m inclined to leave it on permanantly. How hard would it be to create a third build scheme for those who like to self build and be cutting edge but don’t want to actually have full debugging info tracked? It should follow the current debug options (ie no sparkle) but without your recent flags turned on.

**Comment by cmsj** [comment]
@asmagill A third build scheme is easy, what will be harder is remembering to keep it up to date when we change something critical in the Hammerspoon/Release schemes. Granted that's not very often, and if (when) we forget, hopefully some interested folk like @chdiza will let us know 😁

**Comment by chdiza** [comment]
That idea would be fine, but also, I think I finally got building under the Release scheme to work without weird side-effects.

**Comment by cmsj** [comment]
If @chdiza is happy with the current arrangement of things, I'd say let's avoid adding another build scheme.
