### ISSUE TITLE
Cleanup - Remove hs._TERMINATED?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1676]
@cmsj & @asmagill - Curious... Does `hs._TERMINATED` serve any purpose?

**Comment by cmsj** [comment]
Hmm, I'm sure this used to be used for something, but I don't see any other references to it anymore.

**Comment by latenitefilms** [comment]
Me neither - shall we remove it?

**Comment by latenitefilms** [comment]
@cmsj - Will leave you to action and/or close this issue.
