### ISSUE TITLE
Request: API to control LEDs on the keyboard

### ISSUE THREAD

**Issue by prsquee** [Hammerspoon/hammerspoon#1680]
Hello! 

I have my capslock key remapped for hyper, left the LED unused. It would be nice to have an API to control/watcher for the LEDs on the keyboard. Could be used to indicate new notifications while the screen is off. 

Reference:
http://osxbook.com/book/bonus/chapter10/kbdleds/
http://osxbook.com/book/bonus/chapter10/kbdleds/download/keyboard_leds.c

thanks!

**Comment by blahgeek** [comment]
I'd also love to see this feature implemented.

Currently `hs.hid.capslock` API can change the caps lock state (and of course the caps lock LED would change with it as well). But it would be great to have another API to control caps lock LED only without affecting caps lock state (say, `hs.hid.capslock_led`?)

The reference code can be found [here](https://developer.apple.com/library/content/samplecode/HID_LED_test_tool/Listings/main_c.html), it should be trivial to add it to hammerspoon if anyone has some time :)
