### ISSUE TITLE
Feature Request - Tabs for Chooser

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1681]
It would be amazing if you could add a customisable toolbar to `hs.chooser`. 

For example:

<img width="1387" alt="console_revamp_idea" src="https://user-images.githubusercontent.com/22286696/36083446-62fd19cc-1006-11e8-90e4-cb47a92530a6.png">

@asmagill - Maybe this is something that could be tackled with `hs.guitk` at some stage in the future?

**Comment by latenitefilms** [comment]
Also see: https://colorsnapper.com

**Comment by latenitefilms** [comment]
It would actually be really cool if we could "attach" a `hs.webview.toolbar` to a `hs.chooser`.

I've tried playing around but my Xcode skills aren't really up to it.

Any hints or tricks @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
Given you're both online at the moment @asmagill & @cmsj - any ideas on how best I can try and get this working? Basically I want to try and attach a `NSToolbar` to a `hs.chooser` window.

Related: https://dikant.de/2007/09/05/nstoolbar-basics/

**Comment by asmagill** [comment]
The challenge will probably be that @cmsj wrote the chooser using the layout tools within XCode while I wrote the toolbar module completely in Objective-C eschewing any of the helpers or placeholder values XCode offers... I've always meant to learn how to use the layout tools in XCode, but haven't had the need or job requirements to do so...

That said, assuming that the window/panel object that comprises the chooser has a place for the toolbar, unless I'm missing something, it shouldn't be much harder than adding it to the console window was (some of the window styles available don't show or have space for some of the add-on objects (toolbars, rulers, etc.) even when they're attached).

I'll take a closer look and see if I think it's something I can do relatively soon or if I need to plan it for later (or give you pointers on where to look if you want to tackle it yourself in the meantime)
