### ISSUE TITLE
Hammerspoon High Memory Usage

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1682]
I can't remember which issue we were discussing this in @cmsj - so creating a new one.

See: https://github.com/CommandPost/CommandPost/issues/1013

Are you using `hs.pathwatcher`? Maybe a good candidate for more testing?

**Comment by cmsj** [comment]
Did you maybe end up with the various memory debugging options turned on for your Release builds? (Select your release build on the Xcode toolbar, then edit the scheme, and for the Run job, in the Diagnostics tab, everything should be unticked)

**Comment by latenitefilms** [comment]
@cmsj - The last public release we did was 25 days ago, and I'm pretty sure you did the debugging changes more recently than that?

**Comment by latenitefilms** [comment]
All debugging options are turned off:

<img width="888" alt="screen shot 2018-02-13 at 8 35 18 pm" src="https://user-images.githubusercontent.com/22286696/36142869-6ed6adec-10fd-11e8-90ce-23ebe827c719.png">

**Comment by latenitefilms** [comment]
I'm going to close this for now, as I'm not sure how we move forward on it anyway.
