### ISSUE TITLE
Streamdeck Discovery Callback, no disconnection call

### ISSUE THREAD

**Issue by EspyingStar** [Hammerspoon/hammerspoon#1686]
I'm not receiving any callbacks when I disconnect the Streamdeck from my Mac.
Connection events fire fine, device connects and can call all its functions without issue, just no callbacks when disconnected.

Broke it right down to basics to test, but still no results.

```
streamdeck = nil
isConnected = nil

function buttonCallback(device, buttonId, isPressed)

end

function discoveryCallback(connected, device)
    if connected then
        isConnected = true
        streamdeck = device
        streamdeck:reset()
        streamdeck:buttonCallback(deckButton)
        hs.alert("Streamdeck connected")
    else
        isConnected = false
        streamdeck = nil
        hs.alert("Streamdeck disconnected")
    end
end

hs.streamdeck.init(discoveryCallback)
```

Thoughts?

**Comment by latenitefilms** [comment]
I've been away from the office (where my Stream Deck lives), but once I'm back I'll check this out.

In the meantime, @cmsj might have some ideas?

**Comment by cmsj** [comment]
Yes, this is my fault, we never actually call the callback on disconnect events. I'll fix that shortly :)

**Comment by cmsj** [comment]
Fixed in 7d96c3fd14e4a021b0ef87412d412d355b172ede

**Comment by Badsheep** [comment]
Hello,

Sorry I just have a question, I'm a complete beginner in Hammerspoon and I'd love to configure my Deck Mini with it.
Now I'm just trying to understand how the code works.

My question is : if I take the code wrote in the 1st message, I put it in the right ".hammerspoon" folder in a "init.lua" file...
I launch Hammerspoon, then a message "Streamdeck connected" should appear, right ?
Nothing happens...
(the official Strem Deck app is closed).
Thanks for your help ! If you know a better place where to ask help, I'm interested too.

**Comment by latenitefilms** [comment]
Working fine here:

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/22286696/217669973-6ee57ea6-2ef7-4399-86fd-e4ff3357724f.png">

I replaced the alerts with prints to make it easier to see.

**Comment by latenitefilms** [comment]
What type of device do you have?

**Comment by Badsheep** [comment]
A Stream Deck Mini.

Here's my result when typing the code in the console like you did : 
<img width="483" alt="Capture d’écran 2023-02-08 à 23 59 31" src="https://user-images.githubusercontent.com/46049911/217670973-e4dbd2de-3f67-4083-ac82-ce0a3e847939.png">

**Comment by Badsheep** [comment]
I'm using a usb-c adaptor on a MacBook Pro, could it be reason ?
The Stream Deck turns on and display the Elgato logo.

**Comment by latenitefilms** [comment]
It shouldn't make a difference.

What exact model of Stream Deck are you using? It's possible you have a newer model that's not currently supported.

**Comment by Badsheep** [comment]
Yes it's brand new...
Model is 20GAI9902

**Comment by latenitefilms** [comment]
Currently Hammerspoon only supports:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/22286696/217672759-0afd4e94-5e81-460e-b586-1b5870a56199.png">

Can you see what you get in System Information:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/22286696/217674031-13974dfa-6b08-417d-bba9-fb03fe1462bb.png">

**Comment by Badsheep** [comment]
Here it is

<img width="477" alt="Capture d’écran 2023-02-09 à 00 24 56" src="https://user-images.githubusercontent.com/46049911/217674565-e5bdcb65-bc69-4c44-b5d5-a52bcbd3249e.png">

**Comment by latenitefilms** [comment]
Hopefully it's just the case of duplicating the existing Stream Deck Mini code and changing the Product ID.

I've added a new issue here: #3377

I'll try do a pull request today and you can test it out.

**Comment by Badsheep** [comment]
Thanks !
