### ISSUE TITLE
Current crash reports

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#1688]
Here are links to the current crash reports we have open:

Crashers in Lua/LuaSkin:
 * Lua sweeplist: http://crashes.to/s/c455d9b0ac7
 * Lua poscall: http://crashes.to/s/ada5f090af8
 * Lua hook: http://crashes.to/s/e2a3309d157
 * LuaSkin toNSObject: http://crashes.to/s/3d212f28d89

Crashers that at least sound related to our modules:
 * hs.drawing delete: http://crashes.to/s/836ac602b4d
 * hs.drawing: rect: http://crashes.to/s/8245a5ea3c8
 * hs.drawing: rect: http://crashes.to/s/dfed73c043c
 * Toolbar item mouseDown: http://crashes.to/s/dd43cb0b6bc

Crashers that boggle my mind:
 * I don't even: http://crashes.to/s/02ce13f1733
 * Menu?: http://crashes.to/s/b7ffc0043a0
 * Unknown: http://crashes.to/s/c66901c7b5a

**Comment by cmsj** [comment]
@asmagill @latenitefilms I'm getting very tempted to leave the lua_check change in the next release. It will almost certainly mean more crashes in the short term, but they seem to generally be things that are quickly fixable, and may mean we clear out some of these more obscure crashes.

Any objections?

**Comment by latenitefilms** [comment]
Fine by me!

**Comment by cmsj** [comment]
I'm going to close this since it's not going anywhere and we've made some substantial Lua safety improvements in the last couple of weeks.
