### ISSUE TITLE
How to show text in the middle of screen styled nicely

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#1690]
I have this function in my[ init.lua](https://github.com/nikitavoloboev/dotfiles/blob/master/hammerspoon/init.lua#L45):

```Lua
-- Show TODO task briefly in middle of screen
function showTodoTask()
    if not todo_draw then
        local mainScreen = hs.screen.mainScreen()
        local mainRes = mainScreen:fullFrame()
        local todo_str = hs.execute("~/app/hammerspoon/todo")
        local todo = hs.styledtext.new(todo_str,{font={name="Impact",size=120},color=red, paragraphStyle={alignment="center"}})
        local timeframe = hs.geometry.rect((mainRes.w-300)/2,(mainRes.h-200)/2,300,150)
        todo_draw = hs.drawing.text(timeframe,todo)
        todo_draw:setLevel(hs.drawing.windowLevels.overlay)
        todo_draw:show()
        timer = hs.timer.doAfter(4, function() todo_draw:delete() todo_draw=nil end)
    else
        todo_draw:delete()
        todo_draw=nil
    end
end
```

What it does is read contents of file `todo` that is this simple bash script:

```Bash
#!/bin/bash

echo Write a program to find movies
```

The function then should show me `Write a program to find movies` in the middle of my screen in full text. The issue is that the function is that it does not show the text because it wraps the words due to constrained `timeframe`. So all I see when I call the function is:

![2018-02-17 at 22 12](https://user-images.githubusercontent.com/6391776/36345653-b4c97098-142f-11e8-8766-3e55b64eff9b.png)

I talked with @cmsj on IRC who helped me find what the issue is but he couldn't think of a solution to this. Is there anything I can do to make this work?

My goal is that this function will show any string (in my case the output of a shell script but can be any string), and show it fully in the middle of screen in that nicely styled largish font.

**Comment by asmagill** [comment]
You're displaying a 120 pt font in a space that is 300x150 points in size... it's going to crop to fit, and by default at word boundaries.

Consider a smaller font size, set the width to match the screen width (it will still be centered given your styled text attributes), consider setting the lineBreak mode to something else (see the `lineBreak` property of the styled text `paragraphStyle` table) and check out `hs.drawing.getTextDrawingSize` which can give you the size required to display a styled text object.

You should also note that `echo` is going to add a newline at the end of the text, so you might want to do `todo_str = hs.execute("~/app/hammerspoon/todo"):match("^(.*)[\r\n]?$")`

**Comment by nikitavoloboev** [comment]
> set the width to match the screen width

How can I specify this?

**Comment by nikitavoloboev** [comment]
I tried this:
`local timeframe = hs.geometry.rect((mainRes.w-300)/2,(mainRes.h-200)/2,mainRes.w,150)`

But the text is not cantered .

**Comment by asmagill** [comment]
Try `local timeframe = hs.geometry.rect(0, (mainRes.h-200)/2, mainRes.w, 150)`, or more "correctly" if you have multiple monitors, `local timeframe = hs.geometry.rect(mainRes.x, mainRes.y + (mainRes.h-200)/2, mainRes.w, 150)`

Since you're expanding the width to match the screen, you also need to push the left side up against that side of the screen, hence the 0 (or `mainRes.x`).

**Comment by nikitavoloboev** [comment]
Oh wow @asmagill 

This `timeframe` line fixed everything for me. I am not quite sure how the `rectangle` frame actually looks now but the text renders perfectly.

Would it be possible to make the background text of the text black? That is currently the task is shown like so:

![2018-02-17 at 22 48](https://user-images.githubusercontent.com/6391776/36345923-c1eaadb4-1434-11e8-8f55-987bb58e3966.png)

But sometimes it's still hard to decipher the text. It would be awesome if the background behind the text was black. 

I am actually thinking of publishing this function as a Spoon that other people can use.

**Comment by asmagill** [comment]
The only surefire way to do it with `hs.drawing` is to create a separate rectangle object with the same frame as the text object and then display both of them, making sure to either show the text last or use something like `textDrawing:orderAbove(rectangleDrawing)` to place the text on top of the rectangle.

Its because of things like this (requiring multiple objects for anything more complex then a basic shape) that I created the `hs.canvas` module... it's a bit harder to get started with, but once you understand it, it's a whole lot more powerful.

**Comment by cmsj** [comment]
@nikitavoloboev does the hs.canvas API look sufficient for your needs?

**Comment by nikitavoloboev** [comment]
Haven't had the chance to look at it yet but I hope it is sufficient. Will report here whether it works or not.
