### ISSUE TITLE
Javascript code does not get executed.

### ISSUE THREAD

**Issue by Phosphor303** [Hammerspoon/hammerspoon#1696]
I try to use the `hs.osascript.javascriptFromFile` method, but unfortunately the docs don't tell me how to format the file parameter (or if there are requirements on where the file has to be). I tried the following to no success:

`hs.osascript.javascriptFromFile("test.js")`
`hs.osascript.javascriptFromFile("./test.js")`
`hs.osascript.javascriptFromFile("~/.hammerspoon/test.js")`
`hs.osascript.javascriptFromFile("Users/name/.hammerspoon/test.js")`

My JavaScript code works when I call it in the terminal with `osascript -l JavaScript ~/.hammerspoon/test.js`. Here it is:

```Javascript
#!/usr/bin/env osascript -l JavaScript
/* jshint esversion: 6 */

var app = Application.currentApplication();
app.includeStandardAdditions = true;
app.displayNotification('1', { withTitle: '1', subtitle: '1' });
```

**Comment by latenitefilms** [comment]
Try: 

```lua
local path = hs.fs.pathToAbsolute("~/.hammerspoon/test.js")
hs.osascript.javascriptFromFile(path)

```

**Comment by Phosphor303** [comment]
Thank you for your suggestion, but unfortunately it didn't work either.

**Comment by latenitefilms** [comment]
It looks like @rkalis added this recently, so he might have some ideas? Or @cmsj ?

**Comment by rkalis** [comment]
After some testing I noticed that the shebang is causing it to fail, in other words, a file with just the following in it worked:
```js
var app = Application.currentApplication();
app.includeStandardAdditions = true;
app.displayNotification('1', { withTitle: '1', subtitle: '1' });
```

Currently, javascriptFromFile just reads the file contents and execute them as javascript, but javascript doesn't know how to handle this shebang. I can change the function to filter out the shebang, then execute the remaining code.
