### ISSUE TITLE
Making something B&W using hs.canvas?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1697]
@asmagill - I have the following image:

<img width="25" alt="screen shot 2018-02-27 at 7 21 24 pm" src="https://user-images.githubusercontent.com/22286696/36717768-7c4baf12-1bf3-11e8-8afa-da1faa089f38.png">

Can I somehow use `hs.canvas` to make the grey background transparent and the icon pure white?

**Comment by ashfinal** [comment]
Using an image processor for this may be a good idea.

**Comment by latenitefilms** [comment]
@ashfinal - Having a Hammerspoon extension that does image processing would be pretty cool!

I've created a new issue for this:

- [Extension Suggestion - Image Processor](https://github.com/Hammerspoon/hammerspoon/issues/1710)

**Comment by cmsj** [comment]
I'm gonna close this issue out since we have the extension suggestion one :)
