### ISSUE TITLE
If the keypad is locked, the shortcut keys will fail.

### ISSUE THREAD

**Issue by yingnierxiao** [Hammerspoon/hammerspoon#1703]
imac lock screen, the shortcut keys will fail.

**Comment by cmsj** [comment]
If the screen is locked, normal applications like Hammerspoon are not able to receive shortcuts. Sorry!

**Comment by yingnierxiao** [comment]
how can i close screen and go on use ，CTRL + SHIFT + Power power key is no map

**Comment by cmsj** [comment]
Maybe look at Karabiner Elements - it can remap keys in the kernel, which we can't.
