### ISSUE TITLE
Feature request: Open minimised

### ISSUE THREAD

**Issue by nathanhornby** [Hammerspoon/hammerspoon#1704]
**Apologies if I've missed a configuration option or overlooked something**, but is there a way to open Hammerspoon at launch _minimised_? I only see the 'Launch Hammerspoon at login' checkbox but it tends to be a standard feature of any software that allows you to open it at login to also allow you to open it minimised so that your screen doesn't fill with configuration windows.

**Comment by latenitefilms** [comment]
What windows are you referring to? By default, Hammerspoon shouldn't open any windows, assuming you have a working `~/.hammerspoon/init.lua` file and Accessibility Permissions are enabled.

These might also be helpful for you:

- Enable/disable opening of the Hammerspoon Console on Dock Icon click: [hs.openConsoleOnDockClick()](http://www.hammerspoon.org/docs/hs.html#openConsoleOnDockClick)
- Enable/disable Hammerspoon Dock Icon: [hs.dockIcon()](http://www.hammerspoon.org/docs/hs.html#dockIcon)
- Get the Console `hs.window` so you can close/manipulate it as required: [hs.console.hswindow()](http://www.hammerspoon.org/docs/hs.console.html#hswindow)

**Comment by nathanhornby** [comment]
Sorry I should have been more explicit, I'm referring to the preferences window:

<img width="518" alt="screen shot 2018-03-12 at 21 37 16" src="https://user-images.githubusercontent.com/1975168/37310996-a50177c6-263d-11e8-9c49-3cb055ec6be8.png">

However I didn't notice it today and am now wondering if it opened simply because it was open when I shut down.

**Comment by latenitefilms** [comment]
The Hammerspoon Preferences window should only really appear if Accessibility is disabled.

**Comment by nathanhornby** [comment]
Ah that might have been it, I've only recently enabled it.

**Comment by latenitefilms** [comment]
That'll be it then! Please close this issue, unless you have further questions.

Thanks mate! Happy coding!

**Comment by chdiza** [comment]
> The Hammerspoon Preferences window should only really appear if Accessibility is disabled.

It also loves to appear when Accessibility *is* enabled but one has just built a new HS from source.

**Comment by cmsj** [comment]
@chdiza that's line 253 in MJAppDelegate.m - the prefs window is popped up for the first run of a new version. As my comment there suggests, I'd be fine with that going away, and I'm going to remove it now because that annoys me too :)
