### ISSUE TITLE
HSStreamDeckDevice.m line 67 -[HSStreamDeckDevice reset]

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1705]
@cmsj See: http://crashes.to/s/70036543d51

**Comment by cmsj** [comment]
@latenitefilms was anything unusual going on at the time? HS restart? Device unplugged? USB bus reset? It rather looks like the IOHIDDeviceRef went NULL, which it shouldn't be doing!

**Comment by latenitefilms** [comment]
Unfortunately this came from an anonymous user, so I'm not sure, sorry!

I'm hoping to push out a new CommandPost beta later this week which is in-line with Hammerspoon's `master` branch, so hopefully the added debugging code will be helpful for situations like this?

**Comment by latenitefilms** [comment]
Maybe related? https://github.com/Hammerspoon/hammerspoon/issues/1686
