### ISSUE TITLE
hs.timer.doEvery silently stops working after some time

### ISSUE THREAD

**Issue by hansenchris** [Hammerspoon/hammerspoon#1713]
Hi, I'm having issues with using doEvery as it will (randomly) stop executing. 
I'm trying to find a way to debug what's going on however the console is empty (nothing related to timers).

I have a few hs.timer.doEvery for updating menubar statuses every five seconds, and another one every 10 minutes to update weather. They will work fine for some time, even between laptop suspend/resume, however randomly they will stop working (usually after a day or so since last config reload). I can see that since I keep a "last updated" menu item for weather and the other items are actually the time, and I can see that they all get stuck at the same time. 

I've tried this on two systems running 10.13.3 with the latest version (0.9.60). 

Any hints?

**Comment by latenitefilms** [comment]
Probably garbage collection? Make sure you capture the timer in a global variable.

See: [A quick aside about variable lifecycles](http://www.hammerspoon.org/go/)

**Comment by hansenchris** [comment]
That's most probably what happens, I just had ```hs.timer.doEvery(``` in my init.lua, now I'll assign them to a variable.

Thanks!!
