### ISSUE TITLE
Bindings not working

### ISSUE THREAD

**Issue by bradyt** [Hammerspoon/hammerspoon#1721]
I'm on macOS High Sierra Version 10.13.3. Previously, the following worked, making windows fullscreen. 

    fullscreen = function() hs.window.focusedWindow():toggleFullScreen() end
    hs.hotkey.bind({"cmd", "ctrl", "alt"}, 'f', fullscreen)

Now, all I see in Hammerspoon Console is

    2018-03-25 15:27:15: -- Loading extension: window
    2018-03-25 15:27:15: -- Loading extension: uielement

but windows are not fullscreening. (Though, Hammerspoon Console itself can successfully fullscreen, if it is the one in focus.)

**Comment by cmsj** [comment]
If it's working for Hammerspoon and not other apps, check that you still have accessibility permissions enabled for Hammerspoon.

**Comment by bradyt** [comment]
Oh you're totally right, that fixed it. This might be a candidate for every time someone says, "doesn't work on OS update". I had to reinstall because installation issues. Thank you!
