### ISSUE TITLE
detect hotkey's that might interfere with OS?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#173]
I have bound CMD-OPT-CTRL-T to something within Hammerspoon.  Works great.  Then I stumble across http://www.reddit.com/r/apple/comments/2jr6s2/1010_i_found_a_way_to_dynamically_switch_between/ and forget I already have a binding for this apparently hard coded key-sequence.

Usually not a problem -- one or the other wins out, either HS or the app, or in some cases, the app and then it passes through to HS anyways... weird and maybe annoying, but ok.

Not this time... hard immediate crash of HS.

So, moral of the story is, if you want this toggle, don't bind CMD-ALT-CTRL-T in Hammerspoon.

What I want to know, though, is can we detect if a key is already bound somewhere?  Someone suggested running through the menus, which most of the code already exists for I think, but this wouldn't have been caught even if it was done... is there something more fundamental we can check?

I'll dig deeper later (the individual who discovered this tweak was nice enough to describe how he did it, so I will play around myself when I get a chance), but if anyone already knows or has an idea, I thought I'd throw it out there.

**Comment by cmsj** [comment]
Did you get a trace back of the crash? We run Crashlytics on release builds, but I'm guessing you were running a local build?
(I'm running into a fair number of crashes after starting to use hs.wifi.watcher and hs.screen.watcher and I'm thinking we have some threading issues with callbacks)

**Comment by asmagill** [comment]
Yeah, it's a local build -- mainly because I remove the Updater object so I don't have to deal with Sparkle errors when I do work on core modules.  Last build time was sometime earlier today after the fix to the documentation comments.  I did get a .crash file that I can view in Console.app, if that helps... otherwise, is their an option or compile flag I can set to generate what you're looking for?

Hmm... thought I could attach a file to this, but it looks like only pictures... try this link if you want to take a look at it: https://cumulus.dysfunctionalmonkey.info:8192/public.php?service=files&t=f9d51795b7ae47c12f1a4d0774130236

**Comment by asmagill** [comment]
Since this occurred in relation to a Yosemite-only undocumented tweak for toggling the dark style (maybe we can come up with our own way within HS? Need to look into that...), I don't think it's likely to happen often, so not a high priority; but since it doesn't fail gracefully like most other interfering key bindings I've run across, it is noteworthy and if it's not too difficult to find a way to detect it, probably a good idea.

FWIW the tweak also caused DTerm and Tunnelblick to pop up their menus... not a crash, but this tweak doesn't play well with others, so I wouldn't be surprised if Apple removes it eventually.

At the very least, it's in here and if we start to get questions, can refer people to this thread so we can see just how big of a deal it really becomes.

**Comment by asmagill** [comment]
see #313 -- moving to EventTap may alleviate this crash and/or allow overriding system keys since we'll be using the recommended hotkey method rather than the older Carbon RegisterEventHotKey method.
