### ISSUE TITLE
Hammerspoon places config file directory in user home, contributing to dot file/folder clutter in home directory

### ISSUE THREAD

**Issue by malob** [Hammerspoon/hammerspoon#1734]
Hammerspoon places it's config files in `~/.hammerspoon`. This contributes to dot file/folder clutter in my home folder.

I think it would be great if Hammerspoon put files like this in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/index.html) directories. In this particular case that would likely mean `~/.config/hammerspoon`.

I'm not familiar with the codebase, but I'd assume it should be pretty easy to first check if `~/.hammerspoon` exists, then use that folder to preserve backward compatibility, otherwise use `~/.config/hammerspoon`.

**Comment by cmsj** [comment]
I'm not sure if we'll ever get around to moving it properly, but you can override the default yourself with:

```defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"```

**Comment by malob** [comment]
Thanks for the tip!

Would you accept a pull request that addressed this? If so, are there any files relevant to this besides [variables.m](hammerspoon/Hammerspoon/variables.m)?

**Comment by AlJohri** [comment]
My `~/.hammerspoon` folder has both the `init.lua` and `Spoons`. Is there a config to change the location of the entire `hamerspoon` folder including `Spoons`? It seems like the MJConfigFile is only for `init.lua`.

```
❯ ls ~/.hammerspoon
init.lua  Spoons
```

https://github.com/Hammerspoon/hammerspoon/blob/56b5835dc1bf7bb430dfea3f1662379cccec0c82/Hammerspoon/variables.m#L9

**Comment by minusfive** [comment]
> My `~/.hammerspoon` folder has both the `init.lua` and `Spoons`. Is there a config to change the location of the entire `hamerspoon` folder including `Spoons`? It seems like the MJConfigFile is only for `init.lua`.
> 
> ```
> ❯ ls ~/.hammerspoon
> init.lua  Spoons
> ```
> 
> https://github.com/Hammerspoon/hammerspoon/blob/56b5835dc1bf7bb430dfea3f1662379cccec0c82/Hammerspoon/variables.m#L9

Tracing the code it seems the spoons directory is computed relative to the config directory from the `MJConfigFile`, so no need I think.

**Comment by minusfive** [comment]
For future reference, added a snippet to https://github.com/Hammerspoon/hammerspoon/discussions/3730 with how to set this up with Nix.

**Comment by QuantumLibet** [comment]
> > My `~/.hammerspoon` folder has both the `init.lua` and `Spoons`. Is there a config to change the location of the entire `hamerspoon` folder including `Spoons`? It seems like the MJConfigFile is only for `init.lua`.
> > 
> Tracing the code it seems the spoons directory is computed relative to the config directory from the `MJConfigFile`, so no need I think.

This, as documented [here](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#loading-a-spoon) with "`Note that hs.loadSpoon() uses package.path to find Spoons.`", where it also gives a code example on how to deviate, if necessary.

**Comment by joeyagreco** [comment]
Note that **you'll need to restart hammerspoon** after running `defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"` in order for the newly-located init file to be found and reloaded
