### ISSUE TITLE
Global commandTable

### ISSUE THREAD

**Issue by casouri** [Hammerspoon/hammerspoon#1735]
Could there be a global commandTable that provides quick access to various functions?

Each key is a "command" and each value is a function that takes no argument.

This way I can pop a chooser and type commands and execute them.

**Comment by cmsj** [comment]
I'm not quite sure what you mean, but it sounds like something you could make yourself, and possibly even distribute as a Spoon for others to use :)

**Comment by casouri** [comment]
I'm thinking about something that every spoon can modify, i.e. add their public commands to. 

Say I made an Emoji chooser(which someone did), I can add a command like `startEmojiChoose` to global command table, and users can pop a command chooser and type in `startEmojiChoose`, hit enter, start to choose emojis. 

This way you don't need to bind a shortcut for every single command you want to use. It is similar to what to `M-x` in Emacs and `:` in VIm.

**Comment by latenitefilms** [comment]
I feel like this would actually be a good idea for a Spoon (i.e. a spoon that scans for all other spoons, and builds a `hs.chooser` that allows you to trigger the built-in commands of each spoon) - rather than something that should be added to the Hammerspoon core?

**Comment by casouri** [comment]
That sound doable. I'll try to do something like that.

**Comment by casouri** [comment]
I encounter some problems when trying to grab commands form spoons.

Here I have a spoon `Binder`, and looping through it gives me all the local functions

```
> for key, value in pairs(spoon.Binder) do print(key, value) end
2018-04-09 20:42:49: escapeKey	table: 0x600001060800
2018-04-09 20:42:49: helperEntryEachLine	5
2018-04-09 20:42:49: name	Binder
2018-04-09 20:42:49: recursiveBind	function: 0x600001481900
2018-04-09 20:42:49: helperEntryLengthInChar	20
2018-04-09 20:42:49: __index	table: 0x60000106e100
2018-04-09 20:42:49: version	0.7
2018-04-09 20:42:49: singleKey	function: 0x600002c56da0
2018-04-09 20:42:49: showBindHelper	true
2018-04-09 20:42:49: helperFormat	table: 0x600001a60e00
2018-04-09 20:42:49: author	Yuan Fu <casouri@gmail.com>
2018-04-09 20:42:49: homepage	https://github.com/Hammerspoon/Spoons
2018-04-09 20:42:49: license	MIT - https://opensource.org/licenses/MIT
```

Is there any way to get only the public commands?

**Comment by latenitefilms** [comment]
In your example above, if you wanted to trigger `singleKey` you could with `value. singleKey()`.

**Comment by casouri** [comment]
You know what, it is my fault, `singleKey` is a public function, I thought it's local. :P Sorry.
