### ISSUE TITLE
Crash - internal.m line 631 blockAlert

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1739]
See: http://crashes.to/s/bd5d4466518

**Comment by cmsj** [comment]
@latenitefilms I think I'd like to keep the crash reports out of github - I get the notifications for HS and CP crashes, and typically they're almost impossible to do anything with. I'd rather keep chipping away at the fundamental issues like the recent Lua stack guarding work, to remove as many whole classes of inscrutable crashes as possible, which should leave us with things we can actually hope to fix, but either way, I'm not seeing any value in having them duplicated here.

**Comment by latenitefilms** [comment]
@cmsj - Sweet - no worries!

**Comment by cmsj** [comment]
I just put 0.9.65 out which has all of the protections we've added so far. Let's give it a week or two and see if the HS crashes have disappeared or if I need to go back to the drawing board :)
