### ISSUE TITLE
Extension Suggestion - LIFX light API

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1745]
See: https://api.developer.lifx.com

**Comment by cmsj** [comment]
fwiw I don't have any LIFX bulbs, and since I already have Hue ones, I'm unlikely to get any LIFX, but it's also worth noting that it's extremely likely that LIFX support can be implemented in pure Lua, which opens it up to more possible implementors :)

**Comment by latenitefilms** [comment]
Yeah, I might try and buy a LIFX light to give it a test run. The API can just be triggered via [HTTP](https://api.developer.lifx.com) so it shouldn't be too hard to do all in Lua-land.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as I don't think I'm going to have time to tackle this anytime soon.
