### ISSUE TITLE
error log when dock icon is hidden

### ISSUE THREAD

**Issue by daviehh** [Hammerspoon/hammerspoon#1747]
When the "show dock icon" is set to off in hammerspoon preference, the start up log now outputs:

```
2018-04-12 14:44:39: ********
2018-04-12 14:44:39: 14:44:39 ERROR:   LuaSkin: hs.dockIconClickCallback: attempt to call a nil value
stack traceback:
2018-04-12 14:44:39: ********
```
If I recall correctly, this seems to happen after a recent version change? Thanks!

**Comment by latenitefilms** [comment]
@daviehh - Are you using `hs.dockIconClickCallback` at all in your code?

**Comment by cmsj** [comment]
Removed a little too much code in a recent refactoring. There was no harm here, just an unguarded function call, which is now guarded again :)
