### ISSUE TITLE
hs.hints.windowHints() slow on first few uses

### ISSUE THREAD

**Issue by jfchevrette** [Hammerspoon/hammerspoon#175]
I currently have 8 windows spanning two screens. On first use, hs.hints.windowHints() is very slow and takes a few seconds before showing hints. It's still slow after a few quick successive uses. Then after a short while it's very speedy.

I have an i7 processor, 8GB RAM, SSD. 

I ave 89 app bundles in /Applications

IRC #hammerspoon suggested running perf analysis. With proper instructions I don't mind running them myself.

Thanks!

**Comment by jfchevrette** [comment]
0.9.15 seem to have fixed this issue. displaying windowHints right after startup is now very fast.

**Comment by sprig** [comment]
Hi, 

I am experiencing this issue with 0.9.31

**Comment by dktn** [comment]
I am experiencing this issue with 0.9.38

**Comment by lowne** [comment]
("crossposting" for completeness)
After having updated to 0.9.40 or later,  as soon as you (if you still) notice sluggishness or excessive delay (upon calling `windowHints`, `layout`, etc), please open the Console and run this:
```lua
hs.window._timed_allWindows()
```
(If you get no output, try again a bunch of times (up arrow+return) until you (hopefully) do)

Then please paste the output in issue #233.

**Comment by sprig** [comment]
Though it may be too soon to say this, it seems that the this update solved
it for me! The letters appear instantly in the times I've tried this (with
hours' difference between attempts)...

**Comment by ryfow** [comment]
```
> hs.window._timed_allWindows()
took 6.00s for com.adobe.PDApp.AAMUpdatesNotifier
took 6.00s for org.pqrs.Karabiner-AXNotifier
table: 0x7ffca30b3280
```

**Comment by cmsj** [comment]
@sprig we should be getting better at this, we've started blacklisting "weird" helper processes that were slowing it down. I'm sure this job will never be finished, but hopefully we'll catch most of them eventually :)
