### ISSUE TITLE
hs.menubar:isInMenuBar() documentation/code disagreement

### ISSUE THREAD

**Issue by daviehh** [Hammerspoon/hammerspoon#1751]
After some searching, it seems the spelling is not `isInMenuBar` but `isInMenubar`, with lower case "b". So it's just a documentation disagreement with code? Since functions like `returnToMenuBar` are spelt with capital "B" maybe it's better to change the code to "isInMenuBar"? (But that may break people's existing init.lua if they used the lowercase function...maybe add a new name `isInMenuBar` that also link to `menubar_isInMenubar` so that both upper case (which agrees with documentation and other function names such as `removeFromMenuBar`) and lower case version (people's currently working init.lua) both work?)

[doc link](https://www.hammerspoon.org/docs/hs.menubar.html#isInMenuBar)

code:

https://github.com/Hammerspoon/hammerspoon/blob/fb196acb9b14f6adf5042431017a54b5c7d9994c/extensions/menubar/internal.m#L985
(comment is spelt with capital "B")

https://github.com/Hammerspoon/hammerspoon/blob/fb196acb9b14f6adf5042431017a54b5c7d9994c/extensions/menubar/internal.m#L994

https://github.com/Hammerspoon/hammerspoon/blob/fb196acb9b14f6adf5042431017a54b5c7d9994c/extensions/menubar/internal.m#L1193

(codes are spelt with lower case "b")

=========
original message:

Hi,
Thanks for the wonderful project! Here's one possible bug where `hs.menubar:isInMenuBar()` appears to be broken in the latest version of hammerspoon (0.9.66)

Example (run in hammer spoon console):

```
test_menu = hs.menubar.new()
test_menu:setTitle("testing")
```

then `hs.menubar:isInMenuBar()` fails:

```
[string "return test_menu:isInMenuBar()"]:1: attempt to call a nil value (method 'isInMenuBar')
stack traceback:
	[string "return test_menu:isInMenuBar()"]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:417: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:397>
```

if the code is in my init.lua, the error is

```
attempt to call a nil value (method 'isInMenuBar')
stack traceback:
	/path/to/.hammerspoon/init.lua:[(line number of isInMenuBar in my init.lua)]: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Thanks!

**Comment by daviehh** [comment]
After some searching, it seems the spelling is not `isInMenuBar` but `isInMenubar`, with lower case "b". So it's just a documentation disagreement with code? 

[doc link](https://www.hammerspoon.org/docs/hs.menubar.html#isInMenuBar)

**Comment by latenitefilms** [comment]
@daviehh - Good spotting! I've just pushed a quick pull request for @cmsj to review.

**Comment by cmsj** [comment]
Thanks for the very thorough bug report! I've pushed a fix (sorry @latenitefilms I decided to go the opposite route - `:IsInMenubar()` feels more consistent, since we don't capitalise with `MenuBar` anywhere else.
