### ISSUE TITLE
Docs for a Notification object?

### ISSUE THREAD

**Issue by robacarp** [Hammerspoon/hammerspoon#1772]
Hello,

I've found the docs for [hs.notify](http://www.hammerspoon.org/docs/hs.notify.html#new) to be very helpful, but they reference a `notification` object which I can't find the documentation for. Is there a place in the online docs that I'm missing?

Cheers

**Comment by latenitefilms** [comment]
@robacarp - [`hs.notify.new()`](http://www.hammerspoon.org/docs/hs.notify.html#new) creates a new `notification` object. Once a new notification object is created, then you can can use the methods on it, such as `hs.notify:autoWithdraw()`, etc.

**Comment by robacarp** [comment]
@latenitefilms thanks.

I sorted out my confusion, which may have been mostly due to my unfamiliarity with Lua naming conventions. `hs.notify.new()` has this phrase: "Returns: A notification object", but I missed the subtlety that the page called "hs.notify" also documents objects of type `notification`.
