### ISSUE TITLE
Crash - internal.m line 222 - pasteboard_changeCount

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1781]
See: http://crashes.to/s/45b1f641e4c

Problem line of code: 

[`lua_pushinteger(L, [lua_to_pasteboard(L, 1) changeCount]);`](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/pasteboard/internal.m#L222)

@cmsj - Maybe more error detection needs to be put in place to make sure that `changeCount` is valid?

**Comment by cmsj** [comment]
This isn't about whether `changeCount`'s result is valid, the crash is happening inside the call to get the value of `changeCount`, so either something is wrong with the `NSPasteboard` object or there's a bug in AppKit/CoreFoundation. I had a quick poke around in Hopper at both AppKit and CF and I can't figure out where the CFRelease is happening, so I'm not really sure what to do next here.

**Comment by latenitefilms** [comment]
Given @cmsj hasn't been able to solve, I'm going to close this issue for now. We can always re-open it if the bug re-surfaces.
