### ISSUE TITLE
Question: Is it possible to define a single grid which spans over two displays

### ISSUE THREAD

**Issue by kiryph** [Hammerspoon/hammerspoon#1783]
Consider following display setup

```
+---------------------------+ +-------+
|                           | |       |
|     Screen 1  (16:9)      | |Screen2|
|                           | |  3:4  |
+---------------------------+ |       |
                              +-------+
```
Can I define a grid as follows:
```
+---------------------------+ +-------+
|             |             | |       |
|     I       |     II      | |       |
|             |             | |  III  |
+---------------------------+ |       |
                              +-------+
```

The documentation seems to answer this with a no:
http://www.hammerspoon.org/docs/hs.grid.html#setGrid.

The macOS setting under Preferences->Mission Control: `Displays have separate Spaces` could also be relevant.

**Comment by cmsj** [comment]
At the moment, no, the grids are per-screen. I suspect it would be very challenging to have a grid system that can span monitors which are arranged arbitrarily around each other!

**Comment by kiryph** [comment]
> arranged arbitrarily around each other!

People place multiple monitors usually immediately next to each other or even in an array.
So this feature could be limited to these cases.

I did also not mean that individual cells would cross screen borders.

One approach I had in mind was:
setting up a grid for each monitor and define manually neighbouring cells.

This would allow to use:

- pushWindowDown
- pushWindowLeft
- pushWindowRight
- pushWindowUp

I agree that 

- resizeWindowThinner
- resizeWindowWider

would not be possible if cells of different screens would have different heights.
Same applies for

- resizeWindowShorter
- resizeWindowTaller

when the cells have different widths.

**I should rephrase this issue as:**

Allow to use pushWindow[Down,Left,Right,Up] to move windows across screen borders when using grids and neighbouring cells have been defined manually.

**Comment by cmsj** [comment]
I would definitely like to see hs.grid improved for multiple monitors, but even the seemingly simple "immediately next to each other" case has complications - e.g. I have two physically identical monitors, but they run in different resolutions, so even though they are next to each other, the top and bottom edges are not aligned in the window server.
There are other complications, such as a window can't span monitors if they don't have the same pixel density.

**Comment by kiryph** [comment]
> There are other complications, such as a window can't span monitors if they don't have the same pixel density.

As mentioned before this is not what I had in mind. Just a simpler movement of windows with  resizing if the neighouring cell has a different size.

Do you know any other project which has a feature which treats several monitors more like a single screen?

**Comment by kiryph** [comment]
I came across following post for Linux which describes what I have in mind:

https://sillybytes.net/2016/06/seamlessly-vim-tmux-windowmanager_24.html
