### ISSUE TITLE
Add "Dark Mode" to hs.menubar

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1786]
Like `hs.console.darkMode()` and `hs.webview:darkMode()` it would be great if `hs.menubar` also had the ability to appear in the macOS dark appearance.

**Comment by dasmurphy** [comment]
You can try to get the dark mode of the menu bar with

`local darkmode = hs.osascript.applescript('tell application "System Events"\nreturn dark mode of appearance preferences\nend tell')`

**Comment by latenitefilms** [comment]
@dasmurphy - Thanks for the suggestion, but I'm specifically wanting to make a `hs.menubar.new(false)` menu bar (i.e. a menu bar that I can display dynamically - not in the macOS tool bar) dark. I'm using it as a right-click contextual menu.

**Comment by cmsj** [comment]
@latenitefilms I'm somewhat tempted to wait on this, since 10.14 is going to change all the dark mode stuff, and we'll definitely be automatically inheriting the default OS dark mode setting (because I will be running dark mode exclusively, so I will fix anything that doesn't inherit dark mode :)

**Comment by latenitefilms** [comment]
`hs._asm.guitk.menubar` actually gives you "dark mode" popup menu's which is awesome! However, it doesn't support dark mode for a system menubar - however this might be a limitation of macOS?

There are however a few bugs that's holding me back using it:

- [`hs._asm.guitk.menubar.legacy` `nil` error](https://github.com/asmagill/hammerspoon_asm/issues/13)
- [`hs._asm.guitk.menubar.legacy` in dual screens](https://github.com/asmagill/hammerspoon_asm/issues/14)
- [Crash - `hs._asm.guitk.menubar`](https://github.com/asmagill/hammerspoon_asm/issues/15)

It would however be good to have dark mode support eventually for menubar's - just for system's still on High Sierra or older.

**Comment by latenitefilms** [comment]
@cmsj - Is it actually possible to modify the existing `hs.menubar` to display dark popup menus, or is this impossible with `NSMenu`? Seems like it's easy to do with `NSPopUpButton`, but not so much with `NSMenu`? I'm REALLY keen to try and solve this issue prior to 10.14 going public, as I'm adding some Hammerspoon popups to Final Cut Pro, which is already natively "dark".

**Comment by asmagill** [comment]
I won't have time to do this anytime soon (in the middle of a move), but the problem is that a stand-alone (popUp) menu has no appearance of its own -- it inherits that of its parent "window", and the background (screen) has no appearance, even in dark mode.

The original code to pop up a menu consisted of 1 line (see https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/menubar/internal.m#L923)

The guitk version is a little more complex, but should be simple enough to add to the existing module once you decide how to specify which mode to use (see https://github.com/asmagill/hammerspoon_asm/blob/master/guitk/menubar/menu.m#L237-L247)

**Comment by cmsj** [comment]
My very strong suspicion is that 10.14's dark mode will fix this.

**Comment by asmagill** [comment]
Presumably we're still targeting the current macOS and the last two major versions? It may be worth considering making the addition anyways to support 10.12 and 10.13 reliably.

I'm hoping in late July or early August I can start working on Hammerspoon regularly again... is Apple following the same pattern of expected release in September, public betas in the 2-3 months prior?

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - Thanks guys! HUGELY appreciated!

I'll give updating `hs.menubar` a go later today, so that macOS 10.12 and 10.13 users can still have nice dark menubar's before updating to 10.14. Stay tuned!
