### ISSUE TITLE
Move a fullscreen application to another monitor

### ISSUE THREAD

**Issue by dcrozz** [Hammerspoon/hammerspoon#1787]
I want to send one window from a monitor to the next so I use win:moveToScreen(), which works.
But it seems that the function doesn't work with a fullscreen window, so I use split the work into 3 steps
```
win:setFullScreen(false)
win:moveToScreen(screen:next())
win:setFullScreen(true)
```
the first 2 steps works but the last one failed. The window only moves to the next monitor but doesn't get fullscreened.
How this happened? Or is there any other way to send a fullscreen window to the other monitor?

**Comment by qxjit** [comment]
I discovered I was able to work around this by delaying the `win:setFullScreen(true)` using a timer:

```
hs.timer.doAfter(0.6, function()
  win:setFullScreen(true)
end)
```

This makes me suspect it has something to do with the fullscreen transition animation, perhaps.

**Comment by dcrozz** [comment]
@qxjit Solved! Thanks so much! Shameful for such a silly question.
