### ISSUE TITLE
Hammerspoon LuaSkin Test Fails

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1795]
@cmsj & @asmagill - When I click "Product > Test" in Xcode I get the following error:

<img width="1898" alt="screen shot 2018-05-18 at 6 49 35 pm" src="https://user-images.githubusercontent.com/22286696/40225404-46053618-5acc-11e8-8af4-6ce797a123e2.png">

**Comment by latenitefilms** [comment]
Also, @cmsj & @asmagill - I wonder if there's a way we could integrate Leaks testing into your existing Test Suite? Given you test each extension individually - I wonder if we could simply run the `leaks Hammerspoon` command line tool before and after each test to see if a specific extension has any memory leaks?

**Comment by latenitefilms** [comment]
Maybe relevant? https://code.facebook.com/posts/583946315094347/automatic-memory-leak-detection-on-ios/

**Comment by cmsj** [comment]
This should be fixed as-of ab17adc72e64cee4664477f1c64e9a8196b6e042
