### ISSUE TITLE
Hammerspoon stops responding when going/waking up from sleep

### ISSUE THREAD

**Issue by Facens** [Hammerspoon/hammerspoon#1798]
Since very recently, whenever I wake my Mac from sleep, I find that Hammerspoon has stopped responding.

From the logs, it seems to be executing the wakeup command, but not the sleep one.

I'm attaching the console log:
[log.txt](https://github.com/Hammerspoon/hammerspoon/files/2076357/pb-Ju9r3XO2ax.txt)

I've already tried reverting to 0.9.65, but same result.

Any ideas?

**Comment by Facens** [comment]
I've edited my initial message with more info. Any clues?

**Comment by cmsj** [comment]
@Facens has your config changed? When you say "stopped responding", do you mean that it's completely hung and its menubar item is beachballing?

**Comment by nonissue** [comment]
@Facens There aren't any obvious errors I can see in your hammerspoon log (I'm assuming it's from your hammerspoon console?) though I'm no expert. As @cmsj, it would help to know if you're experiencing an hammerspoon app crash, or something else, like watchers not firing after a wake from sleep event. 

Something you may want to do is just create a variable simple config (After backing up your existing files) and try using that for a day or two and see if that resolves the problem. If so, there must be a problem in your config somewhere.

**Comment by Facens** [comment]
@cmsj Yes precisely, beachballing. I haven't changed anything, it used to work, now it doesn't.
@nonissue It seems to hang on the sleep script, which looks like this:

cat /etc/rc.sleep                                                                                                                                                                                                                                     
#!/bin/sh
pkill -SIGINT Python &

Nothing fancy as you can see.

Let me know if there's any test I could do to collect some additional data, and thanks in advance for your help.

**Comment by Facens** [comment]
I've managed to fix it. The wakeup script used & at the end of the command to run multiple commands without waiting the previous one to finish. This caused Hammersoon to beachball. I'm closing it but up to you whether this needs further investigation. For now I've implemented a workaround.

**Comment by LuciusChen** [comment]
same situation

**Comment by mrjones2014** [comment]
Still having this issue as well.
