### ISSUE TITLE
Meta: forum

### ISSUE THREAD

**Issue by sldx** [Hammerspoon/hammerspoon#1799]
(Not sure if this is appropriate place but couldn't find other contact means)

It would really help hammerspoon if there was a forum where people could share automations, ask questions, discuss integrations, etc. (I recommend Discourse)
The google group is not enough, and nobody wants to pollute github. 

Cheers!

**Comment by latenitefilms** [comment]
GitHub is currently probably the best place to ask questions, and get help, etc. It's actively monitored, which is awesome. Personally, I don't think I could be bothered monitoring yet another platform - although a Hammerspoon Facebook group probably wouldn't be a horrible thing?

**Comment by cmsj** [comment]
whichever options we choose, they will never cover what everyone wants. We already have IRC, GitHub and the Google Group. I'm not sure that adding more things is workable!
