### ISSUE TITLE
hs.canvas not triggering mouse callback if mouse key is held down

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1808]
@asmagill - I've got a `hs.canvas` with the following settings:

```lua
mod._canvas = canvas.new(frame)
-- Other stuff goes here...
mod._canvas:appendElements({
    id = "dragCentre",
    action = "fill",
    center = { x = savedX, y = savedY },
    radius = 8,
    fillColor = fillColor,
    type = "circle",
    trackMouseDown = true,
    trackMouseUp = true,
    trackMouseMove = true,
})
mod._canvas:clickActivating(false)
mod._canvas:canvasMouseEvents(true, true, true, true)
mod._canvas:mouseCallback(function(_, event, id, x, y)
    print("EVENT HAPPENING!")
end)
mod._canvas:level("status")
mod._canvas:show()
```

The mouse callback works fine when I move the mouse around WITHOUT any mouse keys down, but as soon as I click and hold the mouse key, the callback stops until I release the mouse.

Any ideas how I can make the callback still trigger when the mouse key is down?

Thanks heaps!

**Comment by latenitefilms** [comment]
@asmagill - If you have time to look at this, that would be awesome, as I've hit a dead end. Thanks heaps!

**Comment by asmagill** [comment]
Haven't had a chance to look at your code, and probably won't for a bit, but I recalled wanting to do something like I think what you're wanting with a remote control display for a KODI server I used to have (I don't have the server running any more, so I haven't worked on it for a while).

The code can be seen at https://github.com/asmagill/hammerspoon-config/blob/master/utils/kodiRemote.lua#L315

What I basically did, IIRC, was use the mouse click callback to create an eventtap which tracked mouse drags and mouse releases -- until the release, the canvas position was adjusted relative to the mouse movements; once the release occurred, the eventtap was cleared.

**Comment by latenitefilms** [comment]
@asmagill - Legend, thanks heaps!

Is there a way to set the "topLeft" of a canvas element, as opposed to the canvas itself?

**Comment by latenitefilms** [comment]
Never mind, worked it out. Thanks heaps @asmagill !!
