### ISSUE TITLE
karabiner_cli and `hs.execute'

### ISSUE THREAD

**Issue by srustamo** [Hammerspoon/hammerspoon#1810]
I'm on OSX 13 10.13.5, and have Karabiner-elements 12.1.0

Karabiner-elements supplies cli command:
`/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --select-profile [profile_name]`

I try to use this command with Hammerspoon so:
`hs.execute("/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --select-profile a")`

which does not change the profile to 'a', from 'd' - default.
In Hammperspoon console, I tried executing the latter, but this also fails, with 'nil	exit	127'.
Also tried `os.execute` with similar output.

Profiles 'a' and 'd' exist, and running the former command in the terminal succeeds.

**Comment by latenitefilms** [comment]
Maybe try:

```lua
hs.execute("/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --select-profile a", true)
```

**Comment by srustamo** [comment]
Still get `nil	exit	127` and no switching.

**Comment by latenitefilms** [comment]
You could try [`hs.task`](http://www.hammerspoon.org/docs/hs.task.html)?

**Comment by cmsj** [comment]
```
hs.execute [["/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli" "--select-profile" "Default profile"]]
	true	exit	0
```

**Comment by srustamo** [comment]
Is there a uniform set of rules for escape symbols?
