### ISSUE TITLE
eventtap stops getting media key down events after a while

### ISSUE THREAD

**Issue by dsedivec** [Hammerspoon/hammerspoon#1859]
I have a Hammerspoon hs.eventtap that I use to do things when I hit play/pause, rewind, or fast forward media keys on my keyboard(s).  After Hammerspoon has been running for a while, the event tap handler stops receiving key *down* events for the play/pause, fast forward, and rewind media keys on my keyboards.  It keeps getting key *up* events.

This is weird enough that I don't know how much of my config is relevant, so I'm going to provide the entire relevant part of my config, my apologies for its length:

```lua
MPD_COMMANDS = {PLAY = "toggle"; FAST = "next"; REWIND = "prev"}
AIRFOIL_EVENTS = {SOUND_UP = "+", SOUND_DOWN = "-"}
DEBUG_TAP = false
tap = hs.eventtap.new({hs.eventtap.event.types.NSSystemDefined}, function(event)
	if DEBUG_TAP then
		print("event tap debug got event:")
		print(hs.inspect.inspect(event:getRawEventData()))
		print(hs.inspect.inspect(event:getFlags()))
		print(hs.inspect.inspect(event:systemKey()))
	end
	local sys_key_event = event:systemKey()
	local delete_event = false
	if not sys_key_event or not sys_key_event.down then
		return false
	elseif MPD_COMMANDS[sys_key_event.key] and not sys_key_event['repeat']
	then
		print("received media event, calling as-mpc")
		hs.execute("~/bin/as-mpc " .. MPD_COMMANDS[sys_key_event.key])
	elseif AIRFOIL_EVENTS[sys_key_event.key] and event:getFlags().ctrl then
		script = string.format([[
			if application "Airfoil" is running then
			  tell application "Airfoil"
			    set activeSpeakers to every speaker whose connected is true
			    repeat with aSpeaker in activeSpeakers
			      set aSpeaker's volume to ((aSpeaker's volume) %s 0.05)
			    end repeat
			  end tell
			end if
		]], AIRFOIL_EVENTS[sys_key_event.key])
		hs.osascript.applescript(script)
		delete_event = true
	end
	return delete_event
end)
tap:start()
```

This works fine after I first start Hammerspoon.  Inevitably, after some amount of time—I'm not sure if it's hours or days—Hammerspoon stops receiving, or at least reporting to my handler, key *down* events for PLAY/FAST/REWIND keys.  I can see this by toggling `DEBUG_TAP = true` in the console and observing what happens as I hit those keys.  For example, here's what I see in the Hammerspoon console when I hit the play/pause key when having this problem:

```
2018-06-08 15:28:11: event tap debug got event:
2018-06-08 15:28:11: {
  CGEventData = {
    flags = 8388864,
    keycode = 0,
    type = 14
  },
  NSEventData = {
    data1 = 1051392,
    data2 = -1,
    modifierFlags = 8388864,
    subtype = 8,
    type = 14,
    windowNumber = 0
  }
}
2018-06-08 15:28:11: {
  fn = true
}
2018-06-08 15:28:11: {
  down = false,
  key = "PLAY",
  keyCode = 16,
  repeat = false
}
```

That's only the `down = false` event.  I never saw the `down = true` event.

* Other "special" keys seem to still be working: EJECT, SOUND_UP, SOUND_DOWN, MUTE.  I get key down and key up events for all of those.
* I am using a Bluetooth keyboard but I get the same results in all cases with my MacBook Pro's built-in keyboard.
* If I start a new eventtap from the Hammerspoon console, listening for `NSSystemDefined` and printing the events, that new tap prints both the key down and then key up events, even while the old tap still prints only the key up event!
* If I restart my existing tap from the Hammerspoon console (`tap:stop(); tap:start()`) it starts working again.  (For a while.)

I feel bad for submitting such an awful bug because reproducing it is difficult, but I have had this happen over and over, and based on my above research I have to believe it is at least possible that it really is a Hammerspoon bug.

MacBookPro11,3 (late 2013 Retina 15"), macOS 10.13.4, Hammerspoon 0.9.66

Thank you to everyone who has contributed to Hammerspoon!  It's awesome.

**Comment by latenitefilms** [comment]
Are you putting your computer to sleep at all when the issues happen?

My first thought was garbage collection - but you seem to be capturing everything in global's, so it's not that.

@cmsj or @asmagill might have some ideas?

**Comment by dsedivec** [comment]
> Are you putting your computer to sleep at all when the issues happen?

I am putting my computer to sleep frequently.  After you asked this I tried to observe whether it happened only after sleep, but I've been unable to definitively say that it was after sleep.

Moreover, in the past week or two I haven't noticed that it's happened again.  Perhaps it is notable that about two weeks ago I installed the 10.13.5 update.

I'm going to make a more concerted effort to reproduce this over the next week or so.  I'm going to set a reminder for next Sunday, and if I can't reproduce this before then I'll close the issue.

**Comment by dsedivec** [comment]
I have tried to reproduce this every day this week variously after waking from sleep and I have been unable, so I'm closing now.  Of course, I've probably installed two macOS point releases since I filed this.  Can I blame Apple, and then thank them for fixing it?!

**Comment by cmsj** [comment]
👍

**Comment by eccentric-j** [comment]
I encountered a similar error https://github.com/agzam/spacehammer/issues/31. I think it happens to be caused by Lua's garbage collector. If tap is only a local variable it will be garbage collected after a period of time depending on app\memory usage of the host. 

The solution was to store the listener in a global var, or in my case, a global table.

Of course, it could be something else but again, very similar use case where I was creating a listener instance, and eventually, it would just stop responding. Sometimes it could be a few hours, sometimes a few days.

Anyway hope this helps.
