### ISSUE TITLE
Memory Leak - hs.canvas:imageFromCanvas()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1867]
We're noticing some weirdness with `hs.canvas:imageFromCanvas()` running the publicly downloadable version of **Hammerspoon 0.9.66**.

When Hammerspoon first starts:

```
Process:         Hammerspoon [32761]
Path:            /Applications/Hammerspoon.app/Contents/MacOS/Hammerspoon
Load Address:    0x104ab4000
Identifier:      org.hammerspoon.Hammerspoon
Version:         0.9.66 (0.9.66)
Code Type:       X86-64
Parent Process:  ??? [1]

Date/Time:       2018-06-14 19:39:21.152 +1000
Launch Time:     2018-06-14 19:39:15.209 +1000
OS Version:      Mac OS X 10.13.5 (17F77)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 9.4.1 (9F2000)

Physical footprint:         44.8M
Physical footprint (peak):  47.5M
----

leaks Report Version: 3.0
leaks[32767]: Process 32761 is not debuggable.
Due to security restrictions, leaks cannot show memory contents of restricted processes.

Process 32761: 126287 nodes malloced for 23729 KB
Process 32761: 0 leaks for 0 total leaked bytes.
```

Here's what Activity Monitor gives us:

<img width="1452" alt="screen shot 2018-06-14 at 7 41 41 pm" src="https://user-images.githubusercontent.com/22286696/41404602-fd48d9c6-700a-11e8-9faa-666c451904f4.png">

Here's the Console output of our little test:

```
2018-06-14 19:39:15: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2018-06-14 19:39:17: -- Lazy extension loading enabled
2018-06-14 19:39:17: -- Loading extension: notify
2018-06-14 19:39:17: -- Loading extension: fnutils
2018-06-14 19:39:17: -- Can't find ~/.hammerspoon/init.lua; create it and reload your config.
2018-06-14 19:42:07: ********
2018-06-14 19:42:07: 19:42:07 ERROR:   LuaSkin: hs.dockIconClickCallback: attempt to call a nil value
stack traceback:
2018-06-14 19:42:07: ********

> local startCount = collectgarbage("count")
print(string.format("Starting Memory: %s", startCount))
for count=1, 1000 do

    local image = require("hs.image")
    local window = require("hs.window")
    local canvas = require("hs.canvas")

    local w = window.frontmostWindow()

    local i = w:snapshot()

    local c = canvas.new({w=1, h=1})

    c[1] = {
        type = "image",
        image = i,
        imageScaling = "none",
        imageAlignment = "topLeft",
    }

    local o = c:imageFromCanvas()

    c:delete()
    c = nil
    i = nil
    o = nil
    
end
local endCount = collectgarbage("count")
print(string.format("Ending Memory: %s", endCount))
print(string.format("Difference: %s", endCount - startCount))
collectgarbage("collect")
print(string.format("After Garbage Collection Memory: %s", collectgarbage("count")))
2018-06-14 19:42:14: Starting Memory: 11241.734375
2018-06-14 19:42:14: -- Loading extension: uielement
2018-06-14 19:43:06: Ending Memory: 12254.32421875
2018-06-14 19:43:06: Difference: 1012.58984375
2018-06-14 19:43:06: After Garbage Collection Memory: 5837.4111328125
```

Here's what `leaks` says:

```
Process:         Hammerspoon [32761]
Path:            /Applications/Hammerspoon.app/Contents/MacOS/Hammerspoon
Load Address:    0x104ab4000
Identifier:      org.hammerspoon.Hammerspoon
Version:         0.9.66 (0.9.66)
Code Type:       X86-64
Parent Process:  ??? [1]

Date/Time:       2018-06-14 19:46:06.281 +1000
Launch Time:     2018-06-14 19:39:15.209 +1000
OS Version:      Mac OS X 10.13.5 (17F77)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 9.4.1 (9F2000)

Physical footprint:         107.6M
Physical footprint (peak):  291.1M
----

leaks Report Version: 3.0
leaks[32836]: Process 32761 is not debuggable.
Due to security restrictions, leaks cannot show memory contents of restricted processes.

Process 32761: 202677 nodes malloced for 76687 KB
Process 32761: 1 leak for 80 total leaked bytes.

Leak: 0x600000094dc0  size=80  zone: DefaultMallocZone_0x104e47000   OS_dispatch_group  ObjC  libdispatch.dylib
```

Here's the Activity Monitor again:

<img width="1452" alt="screen shot 2018-06-14 at 7 46 21 pm" src="https://user-images.githubusercontent.com/22286696/41404866-a93f2096-700b-11e8-8b0d-5e6488ef8fcd.png">

All this seems normal. However, if I run the code via `init.lua` I get:

<img width="952" alt="screen shot 2018-06-14 at 8 25 56 pm" src="https://user-images.githubusercontent.com/22286696/41406979-51dc3658-7011-11e8-9b1c-b3c1145ff434.png">

It seems running `collectgarbage()` in the Console does something different than in `init.lua`?

Interestingly, the issue I saw happening [here](https://github.com/Hammerspoon/hammerspoon/issues/1790#issuecomment-389509047) (i.e. CommandPost going red/yellow in the Memory Pressure graph in Activity Monitor) seems like it can be solved by commenting out our code that performs `hs.canvas:imageFromCanvas()`.

Thoughts @cmsj or @asmagill ?

**Comment by cmsj** [comment]
I'm not sure I'm seeing the weirdness there - other than `leaks` reporting an 80 byte leak of some kind?

**Comment by latenitefilms** [comment]
@cmsj - Sorry, I pressed "Comment" prematurely. Original post updated.

**Comment by randomeizer** [comment]
I think the core of our issue was we were creating a lot of images in a very short time. This was also keeping the thread busy and not allowing the garbage collector to keep up. I'm not sure now much can be done about it though.

The of thing is, it wasn't reclaiming the memory automatically once our image collecting code stopped. If I set a time to run about 4-5 seconds later it would actually clear. Any calls to `collectgarbage()` during or immediately after would be ignored. But I suspect that is a design choice in lua itself.

**Comment by randomeizer** [comment]
In the meantime I've improved or code so it doesn't create anywhere near so many images, which should solve our issue.
