### ISSUE TITLE
Hyper Key is stuck

### ISSUE THREAD

**Issue by wolkym** [Hammerspoon/hammerspoon#1869]
Hell all,

I have tried to find similar issue but with no success.

Using version `0.9.66`.

When some particular buttons are mapped as `hyper` (e.g. `capslock` or `f2`) it works as **no key up event happened**. Thus, it operates as if I would be holding button.

```lua
local hyper = {"capslock"}

-- Moving to another screen
local cycleScreens = hs.fnutils.cycle(hs.screen.allScreens())
hs.hotkey.bind(hyper, "o", function()
  hs.window.focusedWindow():moveToScreen(cycleScreens())
end)
```

Once I will press `capslock`, button `o` will move window from one screen to another despite I have released `capslock` button.

**Comment by cmsj** [comment]
capslock is not a modifier key, nor is f2. the first argument to hs.hotkey.bind() must be one or more modifier keys (ie some combination of shift, ctrl, cmd and option).
