### ISSUE TITLE
hs.alert formatting enhancements

### ISSUE THREAD

**Issue by af** [Hammerspoon/hammerspoon#187]
Hi,
I have no knowledge as to the feasibility of this, but it'd be nice to have some control over the formatting
of the text displayed by `hs.alert`. Off the top of my head:
- control over the font used (typeface/size)
- bold/italic/strikethrough/etc
- emoji support

**Comment by lowne** [comment]
My priority order would be:

- background colour (so any errors can be set to stand out in red)
- position/size (to have more 'transient' alerts smaller, at the bottom)

(AFAIK unicode is already natively supported everywhere - at least, I have emoji for hs.alert() and hs.menubar:setTitle() working as expected)

**Comment by cmsj** [comment]
I believe these items have all now been addressed by the new style options for `hs.alert`

**Comment by af** [comment]
Nice, thanks! Here are [the docs](http://www.hammerspoon.org/docs/hs.alert.html) for anyone curious
