### ISSUE TITLE
hs.notify with additionalActions glitches

### ISSUE THREAD

**Issue by randomeizer** [Hammerspoon/hammerspoon#1877]
I've been playing with the `additionalActions` options in `hs.notify`, which are cool. A couple of little things that would make them work a bit better, IMHO:

1. Currently, there is no visual hint that extra options exist. With Apple's notifications (for Reminder, for example), by default you just see the `action` button, like so:
<img width="363" alt="banners_and_alerts" src="https://user-images.githubusercontent.com/3589315/41775492-65bcb934-7667-11e8-9d0d-458f74e7557c.png">

But when the mouse hovers over it a 'downward chevron' appears:
<img width="364" alt="banners_and_alerts" src="https://user-images.githubusercontent.com/3589315/41775518-781d65ce-7667-11e8-9a32-f13901b285c8.png">

This would be super helpful.

2. When I do click-n-hold on the action, the drop-down box of options appears as expected. If I just release the mouse click without selecting an option, the notification stays visible as expected, but if I then just do a click on the action button without holding, it takes two clicks for it to actually activate.

Anyway, just a couple of minor things.

**Comment by latenitefilms** [comment]
Unfortunately I don't think this private API works any longer in macOS Mojave. Doh!

**Comment by latenitefilms** [comment]
Although `_alwaysShowAlternateActionMenu` still seems to be in the `Foundation/_NSConcreteUserNotification` header on macOS 10.14.6.
