### ISSUE TITLE
Question: any way to invoke hammerspoon function through CLI?

### ISSUE THREAD

**Issue by amirrajan** [Hammerspoon/hammerspoon#1883]
Is there anyway to do something like this from the CLI? `somemagiccommand 'hs.alert("hi")'`

**Comment by latenitefilms** [comment]
Yes, there’s a Command Line interface for Hammerspoon. 

See: http://www.hammerspoon.org/docs/hs.ipc.html

**Comment by antogerva** [comment]
For the record, once installed the magic command would be:
```
hs -c "hs.alert.show('Hello, world!')"
```

**Comment by MShahzaib** [comment]
Exactly what i was looking for
