### ISSUE TITLE
Add sunrise/sunset times to hs.location

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#189]
Seems like it would be useful for various reasons.

The best looking code I've found for this, is: https://github.com/alexander-yakushev/awesomerc/blob/master/lustrous.lua

I've emailed @alexander-yakushev to ask if we can include his code (since it lacks a clear license, afaict)

**Comment by alexander-yakushev** [comment]
Sure, go ahead. That repo doesn't have any license indeed, and before I put one I have to check if I don't violate anything myself.

For lustrous let's say it is CC0, and you can "use" it from here: https://gist.github.com/alexander-yakushev/88531e23a89a0f2acbf1

**Comment by cmsj** [comment]
@alexander-yakushev awesome, thanks!
