### ISSUE TITLE
Failed Hammerspoon Tests

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1893]
@cmsj - FYI: I just ran the Hammerspoon tests on my MacBook Pro and got the following failures:

- `HSapplication: testKilling`
- `HSsocket: testTcpClientServerReadWriteDelimiter`
- `HStask: testTaskWorkingDirectory`
- `HSuielement: testHammerspoonElements`

**Comment by cmsj** [comment]
try re-running them, some of the tests are a bit racy, but if they fail, the log output for the failing tests would be useful to see :)

**Comment by cmsj** [comment]
(Closing for now, feel free to re-open if they fail persistently)
