### ISSUE TITLE
Custom web searches

### ISSUE THREAD

**Issue by airblade** [Hammerspoon/hammerspoon#1895]
Hello!

I am trying to replicate Alfred's custom web searches in Hammerspoon.  I am not too familiar with Hammerspoon (or Lua) yet and would appreciate some guidance.

In this case a custom search combines a predefined URL (from your list) with user input.  The URL is then sent to Safari.

For example:

- Search Rubygems
  - Keyword: `gem`
  - URL: `https://rubygems.org/search?query={query}`
- Search HTTP status codes
  - Keyword: `http`
  - URL: `http://httpstatus.es/{query}`
- etc

I'm envisaging:

- an `hs.chooser` with the list of searches from which the user selects one by typing the keyword;
- at that point the user presses space or enter and then types their query;
- and then presses enter to submit the query.

I can do the first part, but I'm not sure how best to implement the second part.  Any pointers would be appreciated!

**Comment by cmsj** [comment]
Sounds like what you want is to write plugins for the Seal spoon - see http://www.hammerspoon.org/Spoons/Seal.html (Spoons are pure-Lua plugins for Hammerspoon, Seal uses hs.chooser to create something like Alfred.

**Comment by airblade** [comment]
Thanks, that's exactly the kind of pointer I needed.  (I would never have guessed what Seal does from its name.)

**Comment by cmsj** [comment]
(Yes, the name is pretty bad, which is my fault!)
