### ISSUE TITLE
`hs.menubar:isInMenuBar()` docs dont match function name

### ISSUE THREAD

**Issue by nonissue** [Hammerspoon/hammerspoon#1896]
So there are two issues here:

1. In the documentation, this function call has the following case: `hs.menubar:isInMenuBar()`. Calling the function with the specified case does not work. However, I discovered that the function exists, it just has an a different case: `hs.menubar:isInMenu**b**ar()`. Either the function name needs to be corrected, or the documentation should change
2. If the function name as implemented is how it is supposed to be, and the documentation needs to be updated, that creates inconsistencies with the other methods (removeFromMenuBar, returnToMenuBar, etc) I saw there was another issue related to this problem [#1751](https://github.com/Hammerspoon/hammerspoon/issues/1751), but I'm not clear what the resolution was. I'm fine with the case of all the functions changing to `Menubar` but this would break a lot of existing codebases. In reality, I think the simplest thing is to update the function implementation for `hs.menubar:isInMenubar()` to `hs.menubar:isInMenuBar()`. I see there was a pull request submitted by @latenitefilms, but it looks like it was rejected? [[#1752](https://github.com/Hammerspoon/hammerspoon/pull/1752)]

Maybe I'm missing something, I just think this could definitely cause issues for people, and it would be quite tricky to troubleshoot, especially for beginners. Feel free to close this if it is resolved in an upcoming release.

**Comment by latenitefilms** [comment]
@nonissue - @cmsj fixed this here: https://github.com/Hammerspoon/hammerspoon/commit/301f2170caeafa20cc9077f470165cefb614b180

**Comment by nonissue** [comment]
hmm.. that's weird, it doesn't appear to be a fix to me? In my opinion, the way to fix this is to make the code match the docs (which still different from how the code is implemented in that commit) ie. change the function as written to be `hs.menubar:isInMenuBar()`. That way it will both match docs, and match the other method calls for the hs.menubar object. 

Am I totally missing something?

**Comment by nonissue** [comment]
Hmm. @latenitefilms I was going to close this, but wouldn't it be better to change the method name to match the documentation (isInMenuBar()) rather than the other way around? Then you maintain consistency with the other methods in hs.menubar.

**Comment by latenitefilms** [comment]
@nonissue - @cmsj explains his reasoning here: https://github.com/Hammerspoon/hammerspoon/issues/1751#issuecomment-395410838

**Comment by nonissue** [comment]
@latenitefilms yah, I saw that (and ref'd it) in my original post. I do see that @cmsj says he thinks `isInMenubar` is a better fit because the casing: `MenuBar` isn't used elsewhere, but as I said other methods in the module use the `MenuBar` case (`removeFromMenuBar`, `returnToMenuBar`, etc) I think `isInMenuBar` would be better for the internal consistency of the module since the other functions use that case (and so do some of the other docs).

I didn't really skim the rest of the docs, are there references to `Menubar` elsewhere that I'm maybe missing?

Thanks for your reply!

Also, this isn't the biggest issue, so if you guys are happy with the solution as is please close this, I don't mean to badger either of you about it.

**Comment by cmsj** [comment]
Thanks @nonissue - I'm looking back at what I wrote on this earlier and I was wrong - in the Objective C code we use `Menubar`, but all of the relevant Lua API endpoints use `MenuBar`.

**Comment by nonissue** [comment]
No problem @cmsj. Thanks for responding and resolving it so quickly and for tolerating my nit-picking! (And more generally thank you for all your hardwork @cmsj + @latenitefilms and the other contributors, Hammerspoon is an amazing project).
