### ISSUE TITLE
ASCII icon in menu bar rendering error

### ISSUE THREAD

**Issue by dasmurphy** [Hammerspoon/hammerspoon#1897]
I created some ASCII icons and added them to the menu bar. I saw a rendering error, where the icon is displayed differently than the specification.

Example:
```lua
numberIcons = {
[[ASCII:
.......a.......
...............
...............
.......2.......
...............
...............
.....1.........
a.............a
...............
...............
...............
.......3.......
...............
...............
.......a.......
]]
}
m = hs.menubar.new():setIcon(numberIcons[1])
```

It is displayed as a filled circle, but the specification says, the circle (a's) should be empty, because of the lowercase.

See here: http://xqt2.com/asciiIcons.html

And paste to see how it should be looking. The icon should be a circle with a 1 in it.
```
.......a.......
...............
...............
.......2.......
...............
...............
.....1.........
a.............a
...............
...............
...............
.......3.......
...............
...............
.......a.......
```

Is this an error or did i do something wrong? Thanks for any help.

Hammerspoon Version 0.9.66 (0.9.66)

**Comment by dasmurphy** [comment]
Thanks for the snippet. I will take a look at the documentation. This looks very good to me.

So is this right that the default image from http://xqt2.com/asciiIcons.html cannot be drawn then in the menu bar as example?
```lua
numberIcons = {
[[ASCII:
a==========d
=..........=
=.C.D..i.j.=
=..........=
=.F.E..l.k.=
=..........=
=..B....g..=
=.B.B..g.g.=
=..B....g..=
=..........=
b==========c]]
}
m = hs.menubar.new():setIcon(hs.image.imageFromASCII(numberIcons[1], {
  { shouldClose = false },
  { fillColor = { alpha = 0 }},
}))
```
This displays only non filled circles/squares. Is this correct?

Just asking to get being sure for it, since i would like to get more symbols drawing with ASCII. Thanks.

**Comment by dasmurphy** [comment]
After reading more carefully the website. I see it was extended. Any way thanks for the help, i hope i can whip something up for my icons. We can close it now.

**Comment by asmagill** [comment]
You can get what you want, it's just a little more complicated... each entry in the table after `numberIcons[1]` specifies the "rules" for a step in the ascii art... order is capital letters followed by lower case letters, so this would work:

~~~lua
hs.image.imageFromASCII(numberIcons[1], {
  { fillColor = { alpha = 1 }},
  { fillColor = { alpha = 1 }},
  { fillColor = { alpha = 0 }},
  { fillColor = { alpha = 0 }},
  { fillColor = { alpha = 0 }},
})
~~~

(check the docs, you can also do things like set stroke (line) width, etc.)

Basically we're telling it to fill in the B circle and the C-F square, but don't fill in the a-d square (the frame) or the i-l square or the g circle (think of the alpha channel as transparency with 1 being opaque and 0 being transparent and anything in between being see-through to some degree).

@cmsj, if I recall correctly, you're the one who added asciiImage support... do you think the extensions @dasmurphy has identified are worth upgrading to? Was ascii image support added as a CocoaPod that just needs to be updated? I can try and take a look at in next week and give my opinion, but figured I'd bounce it off of you as well.
