### ISSUE TITLE
Less intrusive updates?

### ISSUE THREAD

**Issue by trodrigues** [Hammerspoon/hammerspoon#1907]
Hi there.

Is there a way that Hammerspoon's updates could possibly become a bit less intrusive? What I mean by this is that it's somewhat intrusive when an update popup comes up and takes main focus when you are in the middle of doing something else, possibly even typing.

I don't exactly remember Hammerspoon doing this in the past. Some other apps which I don't update via the App Store sometimes only ask for updates upon a system restart, not out of the blue.

If we could at least be given an option there, it would be very nice.

**Comment by trodrigues** [comment]
@latenitefilms I understand that, but I still want it to check for updates automatically. The problem here is how it presents that to the user.

The thing is, in the past there wasn't a pop up coming out of nowhere while I'm doing something else, which seems to be the case now. If you're in the middle of typing you can accidentally hit the space key and confirm it without even notice what you're doing.

As I mentioned, other apps (Docker for Mac, Karabiner, are good examples) only ask after booting the system which ensures it's not as disruptive and less likely to get confirmed by accident.

**Comment by cmsj** [comment]
@trodrigues the API @latenitefilms pointed to, combined with an `hs.timer` object calling (`hs.checkForUpdates(true)`, which checks for updates without presenting the normal Sparkle dialog) combined with `hs.updateAvailable()`, make it possible to write some config (ideally a Spoon!) that checks frequently for updates, and informs the user via `hs.notify` or `hs.menubar` or `hs.dockicon.setBadge()` or whatever, that an update is available. When the user interacts with whichever of those methods is being used, a call to `hs.checkForUpdates(false)` would trigger the normal update UI.

So, I think everything required for what you want, exists, and I think it would be awesome to have a Spoon in the official Spoons repo, to do it.

I do take your point that the focus stealing is annoying, so it might be interesting to file an issue on Sparkle, requesting that they have an option to present the dialog without stealing focus, but I'm not sure if that fits with their intended usage of the framework.
