### ISSUE TITLE
Clipboard tool with German message

### ISSUE THREAD

**Issue by tiagoboldt** [Hammerspoon/hammerspoon#1912]
The clipboardtool spoon is not fully translated. I guess it would make sense to have it in english, if only one language is supported. 

<img width="422" alt="screenshot 2018-07-24 20 32 36" src="https://user-images.githubusercontent.com/147858/43161825-1403788e-8f81-11e8-896a-b4befecc1d97.png">

**Comment by cmsj** [comment]
We don't actually have any translation support at all in Hammerspoon or Spoons - those strings are exactly as provided by the author of the `ClipboardTool` spoon. I'd suggest filing an issue on the Spoons repo so we can tag him there, or emailing him directly (his email is in the source of the spoon).
