### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by imagnma** [Hammerspoon/hammerspoon#1916]
Hello, thanks for this great application. 
can't wait to start experiment with it and contribute to it .. great job guys 

so I've tried download the application from https://github.com/Hammerspoon/hammerspoon/releases/tag/0.9.70 

and its seems to have a problem, the downloading speed is incredibly slow, 3 kb. at first I thought it might be a problem with my connection, so I left it and then tried again with a different connection and it is very slow. the source files is okay nano problem downloading them. 

Anyone can tell how to install it from the source files one Mac lol . thanks

**Comment by latenitefilms** [comment]
I think there must be a problem with your Internet connection. I just tried the exact same link and it downloaded in seconds - and I don't have a super fast Internet connection.

**Comment by imagnma** [comment]
hmmm, I've tried downloading in two different internet connections one at home and now in the coffee shop as well as currently trying to install it by cask and it stuck on 1.4%, the source files download very fast..

**Comment by imagnma** [comment]
@latenitefilms Can you tell me how can I just install the application from the source ? thanks

**Comment by latenitefilms** [comment]
Weird. Is everything from GitHub downloading slowly for you?

There's instructions on how to build Hammerspoon here:

https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md#how-is-everything-built

**Comment by imagnma** [comment]
that's what drives me crazy lol , everything download normally, but this particular link. 

thank you

**Comment by imagnma** [comment]
@latenitefilms can you do me small favor and upload on another link so I can download the app. building from the source take a lot of time for me.

**Comment by latenitefilms** [comment]
@imagnma - Here you go: https://latenitefilms.digitalpigeon.com/shr/k-IpUJpKEei4UQYtQsGbAw/0gtoUAd8sCSGcxbr5Vxbpg

**Comment by imagnma** [comment]
Thanks a lot <3
