### ISSUE TITLE
hs.keycodes and F21-F24

### ISSUE THREAD

**Issue by kour1er** [Hammerspoon/hammerspoon#1918]
Would it be possible to add F21, F22, F23 and F24 to the keycode list?

**Comment by cmsj** [comment]
I'm not sure those are valid macOS keycodes? They don't appear in `HIToolbox`'s `Events.h` which is where we get our keycodes from.

**Comment by kour1er** [comment]
Fair enough! Karabiner can work with the high F keys but I guess they're a kernel extension so can do whatever they want :)

**Comment by cmsj** [comment]
Indeed. Note that you can bind Karabiner modifications to a shell command, so you could use that to pass a message to Hammerspoon (either via hs.urlevent or hs.ipc).

**Comment by dufferzafar** [comment]
@cmsj Just wanted to check if these keycodes are still not available? USB HID list does have them.

My usecase is binding some extra keys to F18/19/20 via HIDUTIL and then use Hammerspoon to map those keys to something cool.

https://www.freebsddiary.org/APC/usb_hid_usages.php
