### ISSUE TITLE
Add $XDG_CONFIG_HOME or ~/.config as config lookup paths?

### ISSUE THREAD

**Issue by slmjkdbtl** [Hammerspoon/hammerspoon#1925]

**Comment by slmjkdbtl** [comment]
I just came across #582 and it works, but will it be any better if hammerspoon look up these directories by default?

**Comment by latenitefilms** [comment]
I wouldn't actually personally make use of this, but sounds like a good idea to me! Thoughts @cmsj & @asmagill ?

We should also probably better document the `MJConfigFile` preference, and probably replace all the `MJ`'s with `HS`'s?

**Comment by cmsj** [comment]
I'd need to look at it again - my concern has always been making the startup code even more complex.

As for replacing `MJ` with `HS` - if Apple can live with all their classes being prefixed by `NS` for 17 years, we can live with `MJ` 😉

**Comment by asmagill** [comment]
I could be remembering incorrectly or the situation may have changed with the newer macOS versions, but I seem to recall that there were difficulties getting macOS applications (as opposed to shell commands) to see environment variables set by the user during application startup that aren't managed by the OS itself... I seem to recall at least one Preference Panel tool that was written a few years back to try and work around this and it mostly worked, except when it didn't...

If I'm remembering incorrectly or this has changed, then I'd support the addition, though I'm not in a position to help with it at the moment.

As for the renaming of things, a case could be made that user facing things that start with MJ might benefit from being changed (MJConfigFile, for example. Any others?) But I agree, the internals and source file names shouldn't change for historical/git/dont-fix-it-if-it-aint-broke reasons.

That said, we'd need to support both anyways for backwards compatibility or automatically change them during an update and that way leads to breaking things that currently work, so I'm not really in favor of even that unless others care more.

**Comment by cmsj** [comment]
So, for anyone looking to do the work for this, search the code for `MJConfigFile` and think about each of the places it's used. Realistically, we'd need to have an array of possible locations and check at startup to see if any exist, load the first one that matches. We'd also need to cover the situation where one doesn't exist, we'd also then need to make sure that loading files from `~/.config/hammerspoon/` worked properly...

All in all, I don't want to do the work for this, I think it would make for a much more complicated and fragile startup process.

We should have used `~/.config/` from the start, but we didn't and I think I'm mostly against trying to change it now. Sorry!
