### ISSUE TITLE
Request: add option to hs.window:maximize() to disable animation

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#193]
I'm experimenting with porting my mjolnir stuff over to Hammerspoon.

I see that `hs.window:setFrame()` has the optional argument `duration` which can be set to `0` to disable animation.  This is awesome, and without it I would not even consider using Hammerspoon.

Unfortunately for me, `window:maximize()` doesn't have this optional argument.  Could this please be added?

If such a change would be a matter of pure lua, I could try tackling this myself if someone points me towards what to tweak.

**Comment by cmsj** [comment]
Do you want to just disable all window animations? If so, just add:

hs.window.animationDuration=0

to your init.lua. Or is there a specific case where you want it on for some things and not others?

(I think the argument to setFrame was a mistake, given the global variable)

**Comment by jfchevrette** [comment]
I feel like the global variable is not very flexible. What if you want animations only for some actions?
That would make for some very redundant code with lots of 

```lua
function moveSomewhere()
  hs.window.animationDuration=0
  win:setFrame(someframe)
end

function moveElsewhere()
  hs.window.animationDuration=0.2
  win:setFrame(elsewhere)
end
```

and such...

**Comment by chdiza** [comment]
> Do you want to just disable all window animations? If so, just add:
> hs.window.animationDuration=0

Ok, thanks, I didn't see that there.  I don't recall it being in Mjolnir; I should've looked for new functions.

I happen to despise animations so I'll use it.  But I can imagine someone wanting animations for some things but not others.

**Comment by cmsj** [comment]
@jfchevrette fair point. I've pushed an update that makes all of the hs.window methods take an optional duration argument

**Comment by zwpaper** [comment]
@cmsj Do you add the duration argument update in 0.9.34, I try to disable the animation, and I add the following in my init.lua, but  it doesn't work.

```
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "t", function()
    f = hs.window.focusedWindow()
    _animationDuration = hs.window.animationDuration
    hs.window.animationDuration = 0
    f:minimize()
    hs.window.animationDuration = _animationDuration

end)
```

after reload the config, I press the hotkey, the window minimized with animation.

also, I have try this

```
    f:minimize(0)
```

it doesn't work too.

Am I doing anything wrong?

**Comment by cmsj** [comment]
@zwpaper minimize animations are performed by the OS, not Hammerspoon, and I don't think we can disable them. hs.window.animationDuration is for controlling the animations that we perform when moving/resizing windows.

I'll update the documentation to be more clear about this.

**Comment by zwpaper** [comment]
@cmsj Got it, Thanks.
