### ISSUE TITLE
Slow when moving window to another screen

### ISSUE THREAD

**Issue by hotpxl** [Hammerspoon/hammerspoon#1931]
I'm trying to write a WM using Hammerspoon. I have actions that 1. move windows to a certain part on the same screen, 2. move windows to another screen.
Compared to 1, moving windows to another screen is significantly slower (using `window:setFrame` with frame from the other screen). If I remove a few windows at the same time, the latency is very noticeable to the eye. Is this an implementation issue, or is there another API I should be using?

**Comment by cmsj** [comment]
This is likely the default animation we use, which is blocking. Try `hs.window.animationDuration=0`
