### ISSUE TITLE
Xcode 10 & Mojave?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1940]
Curious... Now that Xcode 10 is out, and Mojave is right around the corner, what's the game plan for Hammerspoon @cmsj & @asmagill ?

**Comment by 2shortplanks** [comment]
Any update?

**Comment by asmagill** [comment]
Downloading Mojave tonight, so hopefully I can play with it this weekend and see what works/doesn't work. Am I reading #1941 & #1944 right that Hammerspoon currently doesn't build in the new environment? That will be the first thing to address, though if the releases from github at least run, I believe Travis lets us stick with XCode 9 for the moment, at least for releases.

**Comment by latenitefilms** [comment]
@asmagill - Correct, currently Hammerspoon doesn't built in Xcode 10, however Hammerspoon 0.9.70 as downloaded from GitHub seems to work fine for the most part on Mojave. 

One potential problem in Mojave is the increased security, which is probably what's broken #1946 - I believe other apps such as Keyboard Maestro are also having issues, but I haven't looked into it too much yet.

I've fixed #1941 in #1943 - it should be all good to merge. I'm not sure about #1944 though - I believe you can correct it by just adjusting the compiler warning settings, but not sure if that's the best plan of attack, so will leave with yourself or @cmsj to fix.

**Comment by latenitefilms** [comment]
I'm going to close this issue in favour of #1941 & #1944.
