### ISSUE TITLE
setFrame behavior

### ISSUE THREAD

**Issue by lx75249** [Hammerspoon/hammerspoon#1945]
I just switched to hammerspoon from mjolnir. The following function is to trully maxmize a window.
```lua
hs.hotkey.bind({"ctrl"}, "=", function()
  local win = hs.window.focusedWindow()
  win:setTopLeft(hs.geometry.point(0, 0))
  --win:maximize()
  win:setFrame(hs.geometry.rect(0, 0, win:screen():fullFrame().w, win:screen():frame().h))
end)
```

But the behavior of setFrame is buggy for MacVim. It makes MacVim's window blank. I have to resize the window manually to recover it. When I set to duration to 0, it works.

**Comment by cmsj** [comment]
Do you mean the animation duration? That would suggest to me that MacVim is getting confused by being very rapidly redrawn, and ending up blank.

**Comment by chdiza** [comment]
This is a problem with MacVim.  It's been reported to happen with basically every window manager and resizer that there is.  (Though the conditions for triggering are variable and unreliable.)  The MacVim repo's issues page should have at least a couple of longstanding threads about this.

**Comment by lx75249** [comment]
@chdiza Thanks for your explanations.
