### ISSUE TITLE
hs.notify make lose focus to the frostiest window

### ISSUE THREAD

**Issue by Voleking** [Hammerspoon/hammerspoon#1948]
Every time I call `hs.notify.show()`,  I lose focus to the frostiest window. That's disgusting when you want carry on you input or work. I wonder if there is any way to get rid of this.
```
hs.notify.show("Hammerspoon", "", "Config loaded")
```
BTW, AppleScript`display notification` does not have this problem.
`macOS 10.14`
`hammerspoon: 0.9.70`

**Comment by latenitefilms** [comment]
I'm not seeing this on HS 0.9.70. For example, if I type the following code in the Hammerspoon Console, press enter, then jump to Safari, the notification appears, and Safari still has focus.

```lua
hs.timer.doAfter(3, function() hs.notify.show("Hammerspoon", "", "Config loaded") end)
```
