### ISSUE TITLE
hs.eventtap.keystroke() does not have return key?

### ISSUE THREAD

**Issue by jenksguo** [Hammerspoon/hammerspoon#1949]
Hi I am trying to get hs to make a "return" keystroke but I could not find any means to do this. Can someone help please?

**Comment by latenitefilms** [comment]
Try:

```lua
hs.eventtap.keyStroke({}, "return")
```

**Comment by jenksguo** [comment]
That worked, thanks! I didn't know why it didn't work the few times...
