### ISSUE TITLE
hs.layout.apply and multiple monitors 

### ISSUE THREAD

**Issue by steveoh** [Hammerspoon/hammerspoon#195]
I would like to be able to arrange windows on my 3 monitor setup. Two of my monitors have the same name. 

The [getting started guide](http://www.hammerspoon.org/go/#winlayout) shows using these names as a parameter for the `hs.layout.apply` method. 

These name parameters either need to be made unique some how or another parameter needs to be able to be passed into the apply method. Possibly the screen object?

**Comment by cmsj** [comment]
This should be addressed by e73e6ef
