### ISSUE TITLE
Is there a way to se the default printer?

### ISSUE THREAD

**Issue by peterloron** [Hammerspoon/hammerspoon#1951]
I'm using Hammerspoon to adjust settings and window positions on my machine as I move between home and work. One thing I would like to do is switch the default printer. I don't see anything in the API docs that seems to handle this case. Am I missing it?

Thanks!

**Comment by latenitefilms** [comment]
You could try: 

http://mistermorris.com/blog/setting-the-default-printer-with-a-script-with-mac-os-x/

**Comment by latenitefilms** [comment]
You can also try these CUPS Terminal commands: 

- `lpstat -p` will show you the printers available 
- `lpstat -d` will show you the current default printer 
- `lpoptions -d printername` will set the default to whichever printer you specify

You can use [`hs.execute`](http://www.hammerspoon.org/docs/hs.html#execute) or [`hs.task`](http://www.hammerspoon.org/docs/hs.task.html) to execute these commands in Hammerspoon.

**Comment by peterloron** [comment]
Interesting. That looks doable. Let me see if I can hack something together. Thanks!

**Comment by cmsj** [comment]
I don't think there are any more official APIs for interacting with printers, so I'm going to close this for now. It might be fun to have a Spoon that calls out to `lpstat`/`lpoptions` to get information about printers and manipulate the defaults, if you fancy writing that :)
