### ISSUE TITLE
Can't launchOrFocus Things.app

### ISSUE THREAD

**Issue by ideologysec** [Hammerspoon/hammerspoon#1952]
Very strange - I can't use hs.application.launchOrFocus to do anything with Things.app (/Applications/Things.app). This has been the case since I switched to it roughly 6 months ago from Todoist, on both High Sierra and Mojave.

The *only* thing that works is
```
hs.application.launchOrFocusByBundleID("com.culturedcode.ThingsMac")
```
in the console - but if I add that to my init.lua and bind it to ctrl+option+command+2 or 8 or anything, it doesn't work. Specifying the full path for the app doesn't work either.

hs.inspect doesn't seem to show anything out of the ordinary. I'm tearing my hair out over here - any suggestions or instructions for further troubleshooting?

**Comment by ideologysec** [comment]
It works from the console, but not when added to init.lua.

**Comment by ideologysec** [comment]
I'm an idiot. Missed a quote around the key to use for activation. launchOrFocusByBundleID is working in my init.lua.

Not sure why launchOrFocus isn't working, but, this can probably be closed.

**Comment by cmsj** [comment]
Apps can have multiple names, it's very likely that Things.app actually refers to itself as something else. You may well see it if you iterate over `hs.applications.runningApplications()`.
