### ISSUE TITLE
Is there a way to do keywait?

### ISSUE THREAD

**Issue by Eric-on-2b2t** [Hammerspoon/hammerspoon#1954]
In autohotkey, it is possible to do keywait, which waits for a certain key to be pressed. Is there a way to do this in hammerspoon? I am trying to recreate the hotstrings function of AHK.

Thanks, Eric

**Comment by latenitefilms** [comment]
You can use [`hs.eventtap.event`](http://www.hammerspoon.org/docs/hs.eventtap.event.html) to watch for keypresses. You could use [`hs.timer.doAfter`](http://www.hammerspoon.org/docs/hs.timer.html#doAfter) to remove the observer after a certain period of time.

**Comment by Eric-on-2b2t** [comment]
@cmsj , I want hammerspoon to excecute something after I press some keys in succession, such as when I press D then A then T then E, hammerspoon will press the delete key 4 times and then fill out the current date.

**Comment by cmsj** [comment]
Aha, thanks. So, that is possible using `hs.eventtap`, but it's not going to be easy or pretty. Honestly for that specific use-case I think you'd be better off with something like TextExpander. Sorry!

**Comment by Eric-on-2b2t** [comment]
So mor specifically, how would it be done? A single hs.eventtap to watch for the D key, and then how would it detect teh A key being pressed?

**Comment by cmsj** [comment]
You’d create one event tap and listen for all key presses, and keep track of the most recent X number of presses. If the most recent presses match DATE or some other string, fire off some kind of function call to do what you want.
