### ISSUE TITLE
Add hs.tabs.disableForApp()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1957]
Currently there's no API for disabling an application using `hs.tabs`. It would be good to have the ability to easily toggle the functionality.

**Comment by cmsj** [comment]
@trishume any thoughts on this?

**Comment by trishume** [comment]
Maybe, I'll review a PR if you ping me, but I don't use hs.tabs myself anymore since they added real tabs to macOS, so I don't plan on doing any more work on it myself.

**Comment by latenitefilms** [comment]
I'm going to close this issue, given `hs.tabs` is no longer being updated.
