### ISSUE TITLE
HS on Mojave: antialiased text looks bad

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1959]
I'm trying HS on Mojave; I just copied a version I built on High Sierra, and it seems to be working.

However: because Mojave eliminates the OS's subpixel antialiasing, my fake geeklets made in HS look absolutely *awful* (on my non-Retina monitor).  They contain small-sized text, which is particularly hurt.  It becomes an unholy combination of thin, blurry, and faint.

I tried the trick `defaults write -g CGFontRenderingFontSmoothingDisabled -bool false`, documented [here](https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/), but it didn't help.  That trick apparently *does* help some apps regain their old-style smoothed fonts.  MacVim, for instance, was restored.  But it doesn't help all of them.

I know that iTerm2 has (just?) added a checkbox for turning on subpixel antialiasing.  This might only be in the most recent betas.  This actually works!  I don't know if they're rolling their own implementation or what.

I'm sure hoping there's some way to improve the look of text in HS on non-retina monitors.

**Comment by chdiza** [comment]
> This works for me

Next time I'm on Mojave I'll try setting `AppleFontSmoothing` to 2, but I'm doubtful.  It was already on 1.

**Comment by cmsj** [comment]
If anyone has a link to the specific code in iTerm for the anti-aliasing, that would be handy to have. I took a look through their recent commits on `master` and couldn't see anything relevant.

**Comment by chdiza** [comment]
> This works for me

OK, I tried it, and it did absolutely nothing to help.  (It might be better than having `AppleFontSmoothing` at zero, but I don't know, since I always have it pegged at `1`.)

@cmsj I can try asking the iTerm2 maintainer if he can point out where the antialiasing action is, and hopefully will have something to report back here.
