### ISSUE TITLE
`win:tabCount()` not working with latest Chrome

### ISSUE THREAD

**Issue by vjpr** [Hammerspoon/hammerspoon#1960]
`Version 69.0.3497.100 (Official Build) (64-bit)`

**Comment by vjpr** [comment]
I am trying to discern Bookmark App windows from regular windows.

The element class of Bookmark App windows is `NativeWidgetMacNSWindow`.
For regular windows it is `BrowserNativeWidgetWindow`.

**Comment by vjpr** [comment]
@cmsj Any chance you can take a look at `window:tabCount()` for Chrome?

**Comment by latenitefilms** [comment]
@vjpr You could try using [`hs._asm.axuielement`](https://github.com/asmagill/hs._asm.axuielement).

Using **UI Browser** I can see that Chrome only has a single `AXWindow`, with the tabs within that single window - see:

<img width="1400" alt="screen shot 2018-10-08 at 11 10 19 pm" src="https://user-images.githubusercontent.com/22286696/46608136-6dcff400-cb4f-11e8-9338-0a29d76b26cc.png">

**Comment by vjpr** [comment]
@latenitefilms Thanks! I had been playing around with `axuielement`, but until now I didn't think about counting the children to determine tab count. 

Also had been using Accessibility Inspector instead of UI Browser which looks much better.

**Comment by vjpr** [comment]
Found it!

```
local hsWindow = <an hs.window>
local axWindow = ax.windowElement(hsWindow)
local hasTabs = axWindow:elementSearch({role="AXTabGroup"}) ~= nil
```
