### ISSUE TITLE
hammerspoon cannot bind alt + e now

### ISSUE THREAD

**Issue by hitzhangjie** [Hammerspoon/hammerspoon#1961]
After I upgrade macOS to Mojave, hammerspoon cannot bind alt + e now.

![image](https://user-images.githubusercontent.com/3725760/46593990-e0ff4900-cb02-11e8-8eba-0794d2689aab.png)

When I changed from alt+e to alt+g and press alt+g, it works.

**Comment by latenitefilms** [comment]
@hitzhangjie - Try "option" instead. This works for me in Mojave:

```lua
> hs.hotkey.bind({"option"}, "e", function() print("TEST") end)
2018-10-08 17:06:40: -- Loading extension: hotkey
2018-10-08 17:06:40: 17:06:40     hotkey: Enabled hotkey ⌥E
table: 0x600002318bc0
2018-10-08 17:06:43: TEST
```

**Comment by latenitefilms** [comment]
Actually, this also works for me:

```lua
> hs.hotkey.bind({"alt"}, "e", function() print("TEST") end)
2018-10-08 17:07:58: -- Loading extension: hotkey
2018-10-08 17:07:58: 17:07:58     hotkey: Enabled hotkey ⌥E
table: 0x600002244080
2018-10-08 17:08:01: TEST
```

...as does this:

```lua
> hs.hotkey.bind({"ALT"}, "E", function() print("TEST") end)
2018-10-08 17:08:28: -- Loading extension: hotkey
2018-10-08 17:08:28: 17:08:28     hotkey: Enabled hotkey ⌥E
table: 0x6000022b25c0
2018-10-08 17:08:31: TEST
```

I wonder if you have **OPTION+E** assigned to anything else in macOS? Have a look in **System Preferences > Keyboard > Shortcuts**.

**Comment by hitzhangjie** [comment]
Thanks, I see the error log in console, I will check whether 'option + E' has been used by macOS. Now I press option +E , it will print a special character "**´**", it looks like a different keyboard layout character.

```
2018-10-08 15:05:40: ********
2018-10-08 15:05:40: 15:05:40 ERROR:   LuaSkin: hs.hotkey:enable() keycode: 14, mods: 0x0800, RegisterEventHotKey failed: -9878
2018-10-08 15:05:40: ********
2018-10-08 15:05:40: ********
2018-10-08 15:05:40: 15:05:40 ERROR:   LuaSkin: This hotkey is already registered. It may be a duplicate in your Hammerspoon config, or it may be registered by macOS. See System Preferences->Keyboard->Shortcuts
2018-10-08 15:05:40: ********
```

**Comment by latenitefilms** [comment]
You don't accidentally already have the shortcut key assigned in your `init.lua`?

**Comment by hitzhangjie** [comment]
@latenitefilms No, I use hammerspoon to bind 'alt+E' to open Finder.

**Comment by hitzhangjie** [comment]
I use `/usr/libexec/PlistBuddy -c "Print" ~/Library/Preferences/com.apple.symbolichotkeys.plist` the 'option + E' is used or not.

Here is the interest part in the output:
![image](https://user-images.githubusercontent.com/3725760/46644060-5c1f3880-cbb1-11e8-883d-8388700f7957.png)

press 'E', its keycode is 14,
press 'option', its keycode is 524288, as is said in following picture:
![image](https://user-images.githubusercontent.com/3725760/46644144-a86a7880-cbb1-11e8-868d-030bf90b03eb.png)

maybe I should modify the `com.apple.symbolichotkeys.plist` to try again.

**Comment by hitzhangjie** [comment]
Surprising！

As is mentioned in above comment, option+E is used but disabled, I checked again keyboard shortcut settings, option+E is used by `open finder search window`. I enabled it, then disabled it, then reload hammerspoon config, now option+E works!

![image](https://user-images.githubusercontent.com/3725760/46644508-1bc0ba00-cbb3-11e8-89c8-b7f44d566387.png)

I will continue to watch this issue, hope it works forever. @latenitefilms Thank you very much.

**Comment by latenitefilms** [comment]
Nice detective work!

Yeah, I've also run into weird things with Keyboards Preferences as well in the past.

I'd guess that something is going funky when you upgrade from High Sierra to Mojave.

If all is working, feel free to close this issue, and you can always re-open it later if needed.

**Comment by yuanotes** [comment]
I have found a solution for this issue if the "enable and disable"  trick doesn't work.

You can remap the "Show Finder search window" to another combination of keys like cmd+shift+option+E and **disable it**.

Now you can definitely use Option-E in your hammerspoon scripts now.

**Comment by JellyZhang** [comment]
i had same problem in a new computer, and turned out that i forget to give hammerspoon accessibility in mac's setting.
