### ISSUE TITLE
tel/facetime url protocols not reliable in hs.urlevent.openURL

### ISSUE THREAD

**Issue by rsefer** [Hammerspoon/hammerspoon#1962]
`hs.urlevent.openURL('tel://' .. number ..'?audio=yes')` doesn't seem to work reliably in macOS 10.14 (and possibly elsewhere), even when all obvious Privacy permissions are granted.

Standard macOS functionality will pass a 'tel' protocol to Facetime automatically and bring up a rich notification with an option to start a call to that number. This seems to work unreliably on a per-load basis for Hammerspoon. ie. if hammerspoon loads and it brings up Facetime properly the first time, it will work until hammerspoon is unloaded. If hammerspoon loads and it doesn't work, it will not work again.

What I'm trying to accomplish:

hs.chooser with pre-defined contacts:

![image](https://user-images.githubusercontent.com/539765/46823196-2a45d780-cd53-11e8-9dbc-f3ab2e5004dd.png)

```lua
self.chooser = hs.chooser.new(function(choice)
   callNumber(choice.number)()
end)
```
...

```lua
local function callNumber(number)
  return function()
    hs.execute('osascript ' .. script_path() .. 'phonecall.scpt ' .. number)
    -- hs.urlevent.openURL('tel://' .. number ..'?audio=yes')
  end
end
````

the `hs.urlevent.openURL` is unreliable, as mentioned. My workaround involves hs.execute to invoke an included applescript (`phonecall.scpt`) and passing the script the phone number:

```
on run {input}
	open location "tel://" & input & "?audio=yes"
	return input
end run
```

This works *nearly* every time but is inelegant. I'm curious if I am making an obvious error somewhere that is preventing the standard 'tel' from working or if this is a known bug.

As an aside, would love to be able to pass values using the hs.osascript function.

**Comment by cmsj** [comment]
There isn't a known bug here, it ought to work every time. Do you get any messages in the Hammerspoon Console when it's not working? The actual code for `openURL` is so minimal that it's really hard to imagine how this could be a Hammerspoon issue :/

**Comment by cmsj** [comment]
Seems like maybe this hasn't recurred? I'll close the issue for now, but feel free to re-open it in the future.
