### ISSUE TITLE
Global key listener doesn't work when entering a password.

### ISSUE THREAD

**Issue by zgqq** [Hammerspoon/hammerspoon#1965]
`
etKeyDown = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function (e)
    return false end)
etKeyDown:start()
`

**Comment by cmsj** [comment]
I believe that is intended behaviour from macOS - either through the use of an NSSecureTextField or by using EnableSecureEventInput, applications are allowed to prevent event taps from listening to keyboard strokes.

What is your use case for needing to intercept password key events?

**Comment by zgqq** [comment]
@cmsj I need to implement shortcuts having multiple keystores like vim mode and listen specific hotkeys of some apps to do something.

**Comment by zgqq** [comment]
@cmsj I need to implement shortcuts having multiple keystrokes like vim mode and listen specific hotkeys of some apps to do something.

**Comment by cmsj** [comment]
Unfortunately it's not possible to override the macOS secure input state. That's a good thing for security, but maybe not always what is wanted by other apps! Sorry.

**Comment by cmsj** [comment]
FWIW the next release of Hammerspoon will include `hs.eventtap.isSecureInputEnabled()` so you'll at least be able to check if your eventtaps are not receiving events because of that.
