### ISSUE TITLE
Remap key-combination to Caps Lock

### ISSUE THREAD

**Issue by ravishchawla** [Hammerspoon/hammerspoon#1968]
Is it possible to remap a key combination to Caps Lock. My caps lock key is stuck and never turns on. Something like CMD+ALT+CTRL+S . Are there any examples of scripts used to remap a key-combo to another key?

**Comment by cmsj** [comment]
For remapping keys like that, I would strongly recommend you use Karabiner Elements - it does its work inside the macOS kernel, and will be far more reliable than Hammerspoon can be.

**Comment by ravishchawla** [comment]
awesome, thanks. Ended up using this script:

It remaps R_OPT+R_CMD to caps lock, two of my least used keys on my keyboard.
`
"rules": [
                    {
                        "manipulators": [
                            {
                                "description": "Change command+control+option to caps_lock.",
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": [
                                        "right_command"
                                    ]
                                },
                                "to": [
                                    {
                                        "key_code": "caps_lock",
                                        "modifiers": {
                                            "optional": [
                                                "any"
                                            ]
                                        }
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
`
