### ISSUE TITLE
Intermittent "Funk" error sound and no input into apps on Mojave

### ISSUE THREAD

**Issue by JoeCotellese** [Hammerspoon/hammerspoon#1971]
I recently upgrade to Mojave. Since upgrading I've experienced a strange intermittent issue that prevents text input in apps.

I first noticed in in Chrome, on occasion I would try to type into a field or even the address bar and I would hear the Mac funk sound. Fixing it often involved restarting Chrome

Recently, I noticed it in other apps too, most recently VS Code.

I began to suspect that it was related to the Accessibility Privacy Setting. I have a number of apps that request permissions to control my Mac. I disabled them one by one. The last one I disabled was Hammerspoon. 

Since then I haven't experienced the issue.

**Comment by latenitefilms** [comment]
Are you able to share your config?

**Comment by JoeCotellese** [comment]
I forgot I posted this here. The problem turned out to be a different app.
