### ISSUE TITLE
hs.location sunrise/sunset can return times on different days due to UTC offset

### ISSUE THREAD

**Issue by malob** [Hammerspoon/hammerspoon#1977]
I'm in California which right now has a UTC offset of -7.

This is the current time:
```lua
> os.date("%F %X")
2018-11-02 22:08:25
```

This is the sunrise time returned by `hs.location.sunrise()`:
```lua
> os.date("%F %X", hs.location.sunrise(hs.location.get(), -7))
2018-11-02 07:35:33
```

This is the sunset time returned by `hs.location.sunset()`:
```lua
> os.date("%F %X", hs.location.sunset(hs.location.get(), -7))
2018-11-01 18:09:17
```

The issue is that the sunset time returned is on the previous day.

Running those two lines of code again with no offset returns the following:
```lua
> os.date("%F %X", hs.location.sunrise(hs.location.get(), 0))
2018-11-02 14:35:33

> os.date("%F %X", hs.location.sunset(hs.location.get(), 0))
2018-11-02 01:09:17
```

It seems like `hs.location` is defining a day as 00:00–23:59 UTC, and then finding the sunrise and sunset times at my location that are in that range. So because the sun is setting in my location after midnight UTC, that's the next day according to `hs.location`, while the sunset of the previous day in my location happens early in the morning in UTC.

I think it would make a lot more sense if `hs.location` returned the sunrise/sunset times for the same day in the location provided in the first argument of the sunrise/sunset functions.

**Comment by cmsj** [comment]
Agreed, unfortunately the code for calculating the sunrise/sunset times is pretty simplistic and indeed works on UTC. I'll see if I can find something better

**Comment by cmsj** [comment]
@malob I've just pushed up some replacement code that uses a more reasonable looking Objective C library. Are you able to build from git to test it? Also, would you be willing to work up some location co-ordinates and offsets that show some variations of correct/incorrect behaviour in the old code, so I can add some tests?
