### ISSUE TITLE
Can't use hs.timer.absolutetime()

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#1979]
I get this error: `attempt to call a nil value (field 'absolutetime')`

When trying to get a timestamp with: `hs.timer.absolutetime()`

Am I doing it wrong?

I'm on version 0.9.73

**Comment by cmsj** [comment]
Darn, that’s a mistake in the docs. It should be `absoluteTime` not `absolutetime`. Sorry about that, I’ll get it fixed up!

**Comment by Madd0g** [comment]
Thanks, `absoluteTime` works!
