### ISSUE TITLE
HammerSpoon error filling Console.app

### ISSUE THREAD

**Issue by voldemortensen** [Hammerspoon/hammerspoon#1983]
While investigating a completely unrelated issue on my Mac, I opened Console.app and noticed an error from HammerSpoon being reported roughly twice per second.

`AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.`

I have no idea how to track this down and provide more information or I would. If anyone can point me in the right direction I'm happy to help. Thanks for a great tool!

**Comment by voldemortensen** [comment]
Right after submitting this I had a thought about it for a second and started deactivating my various Spoons and scripts and I've narrowed it down to something with `hs.timer.doEvery`.

Commenting out [this line](https://github.com/voldemortensen/SpotifyMagic.spoon/blob/f5b435896e79a8024e2d409e0389548619c2f8ef/init.lua#L27) makes the error stop.

That line is:
```lua
hs.timer.doEvery(1, function() self:checkSong() end)
```

and `self:checkSong` is:
```lua
function obj:checkSong()
    self.tempArtist = hs.spotify.getCurrentArtist()
    self.tempTrack  = hs.spotify.getCurrentTrack()

    if self.tempArtist ~= self.song.artist or self.tempTrack ~= self.song.track then
        self.song.artist = self.tempArtist
        self.song.track  = self.tempTrack

    --    self.menu:setTitle(self.song.track .. ' - ' .. self.song.artist)

        local note = hs.notify.new('spotify_new_song', {title=self.song.track, informativeText=self.song.artist})
        local icon = hs.image.imageFromPath('/Applications/Spotify.app/Contents/Resources/Icon.icns')
        note:setIdImage(icon)
        note:send()
        icon = nil

        self.tempArtist = nil
        self.tempTrack  = nil
    end
end
```

**Comment by latenitefilms** [comment]
I believe it's just log spam - see:

https://stackoverflow.com/questions/48212616/appleevents-received-mach-msg-which-wasnt-complex-type-as-expected-in-getmemor

Not sure if there's anything that can be done to remove it? Thoughts @asmagill or @cmsj ?

**Comment by latenitefilms** [comment]
@voldemortensen - What version of macOS are your running? Are you running the public release of Hammerspoon, or your own custom build?

**Comment by voldemortensen** [comment]
@latenitefilms 
macOS: `10.13.6 (17G3025)`
hs: `0.9.73` (public release)

**Comment by cmsj** [comment]
Yep, it's log spam, see the bottom post from Eskimo at https://forums.developer.apple.com/thread/88126

Doesn't seem like there's anything we can do unfortunately, and it'll likely be removed in some future macOS release.
