### ISSUE TITLE
Is there any way to number the windows?

### ISSUE THREAD

**Issue by iromise** [Hammerspoon/hammerspoon#1991]
Hi, when we swipe up with three fingers, we may see many window overviews, is it possible to number these windows and choose it using number, such as 1, 2, 3, 4?

**Comment by iromise** [comment]
Thanks, i will try it. And is there any existing configuration about window numbering?

**Comment by cmsj** [comment]
I've not seen people numbering windows, but it doesn't sound super different to the `hs.hints` module. If you're building something from scratch, I would iterate over `hs.window.allWindows()` and fetch the `:id()` property of each, put them in a table, then sort it and you have a mostly-but-not-guaranteed consistent number for each window.
