### ISSUE TITLE
win:setFrame not working when window touches right screen edge

### ISSUE THREAD

**Issue by Robert-M-Muench** [Hammerspoon/hammerspoon#1992]
My screen setup:
* left: 1920x1080
* mid: 5120 x 2880
* right: 1920x1080

The following code doesn't change the width when the window on the mid-screen is touching the right edge. It stays as it is. If I narrow the window a bit, it starts to work.

````
    local win = hs.window.focusedWindow()
    local f = win:frame()

    f.w = f.w - 20
    win:setFrame(f)
````

**Comment by cmsj** [comment]
Unfortunately this is the OS - if you try to manually resize the window with your mouse/trackpad, when it's touching a screen edge (or the dock), by a very small amount, you'll see that it's ever so slightly sticky. The only workaround is to resize by more than about 50 pixels then immediately resize again to the value you originally wanted :(

**Comment by Robert-M-Muench** [comment]
Ah, ok. Maybe a good addition for the docs.
