### ISSUE TITLE
hs.avf - AVFoundation Extension

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1993]
AVFoundation is a Framework that allows you to work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.

I'd like to build an extension that utilities AVFoundation for getting the metadata of files - for example:

```objc
NSString *path = @"path/file.mp3";
NSURL *url = [[NSURL alloc] initFileURLWithPath:path];
AVAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];

NSArray *metadata = [asset commonMetadata];
for ( AVMetadataItem* item in metadata ) {
  NSString *key = [item commonKey];
  NSString *value = [item stringValue];
  NSLog(@"key = %@, value = %@", key, value);
}
```

In Lua-land, maybe this would looking something like:

```lua
local avf = require("hs.avf")
local asset = avf.new("~/Desktop/file.mp3") -- Creates a new AVAsset
local metadata = asset:metadata() -- Returns a table of metadata fields
```

**Comment by cmsj** [comment]
Sounds like a reasonable extension to have, but I don't think I'd go with `new()`, that sounds like it's creating something. Maybe `open()`?

**Comment by latenitefilms** [comment]
@cmsj - Very good point. I should probably use `getByFile` to be consistent with `hs.sound`.

**Comment by asmagill** [comment]
FWIW, `hs.sound` was one of the earliest modules that I wrote that wasn't strictly a conversion of existing code from Hydra or Mjolnir... I'm not particularly wedded to the names chosen for the functions/methods and in fact actually don't like `getByFile`... I'd probably use `open` or `fromPath` if I were to write it now...

That said, backwards compatibility/similarity with the existing/known has its place too, so...

I guess what I'm saying is don't feel obligated to follow the old pattern unless you think it either makes sense or will help people remember when using the module.

**Comment by latenitefilms** [comment]
Good to know - thanks @asmagill ! I'll have a proper think once I start working on this issue, and obviously you can offer any feedback when I eventually do a pull request.

Very glad to see you back on GitHub too! :)

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as I don't foresee having the time to tackle such a big extension any time soon. Maybe one day...
