### ISSUE TITLE
Support hs.audiodevice balance adjustments

### ISSUE THREAD

**Issue by drn** [Hammerspoon/hammerspoon#1994]
I occasionally run into [this OSX bug](https://apple.stackexchange.com/questions/280145/macbook-pro-bluetooth-audio-balance-keeps-changing-by-itself) that causes the audio balance to change when connecting bluetooth devices + when I set volume via `device:SetVolume(...)`. I'd love to have a hotkey that forces audio balance.

Reading through hs.audiodevice docs, we don't have control over it yet. Has this been explored? I wonder if there is some hook in [CoreAudio](https://developer.apple.com/documentation/coreaudio) or [AudioToolbox](https://developer.apple.com/documentation/audiotoolbox) that can be leveraged.

If anyone is familiar with these libraries and can point me in the right direction, I'm happy to take a stab at it.

**Comment by cmsj** [comment]
Good suggestion, thanks. It'll be in the next release :)

**Comment by drn** [comment]
Awesome, thanks @cmsj!
