### ISSUE TITLE
Add hs.window:lostFocus()

### ISSUE THREAD

**Issue by zgqq** [Hammerspoon/hammerspoon#1996]
Currently, there is no good way that lets a window lost focus.

**Comment by cmsj** [comment]
Are you asking for a way to remove focus from a window, or get a callback when a window loses focus?

**Comment by zgqq** [comment]
@cmsj A way to remove focus from a window.

**Comment by cmsj** [comment]
I’m not aware of a way to do that other than by giving focus to another window, unfortunately.

**Comment by zgqq** [comment]
Ok, thinks for your response.
