### ISSUE TITLE
Chooser: Add Title Label

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#2000]
It would be lovely if `hs.chooser` could have an optional `title()` method which creates a title label at the top.  This would be useful to give the user  context for _what_ they are selecting.

**Comment by jdtsmith** [comment]
Something like (with automatic truncation ellipsis): 

![chooser_withtitle](https://user-images.githubusercontent.com/93749/50048131-4edf6800-0092-11e9-948a-3cc3e8249417.png)

**Comment by cmsj** [comment]
I've just added support for setting placeholder text in the query field (ie greyed out text that is shown when there is no other text in the field). I think this is probably a sufficiently useful way of setting a title without too much intrusion into the size/shape of the window.

**Comment by jdtsmith** [comment]
I think this is still waiting official release?  Seems like quite a few updates have occurred since the last in October.

**Comment by Madd0g** [comment]
for me, as soon as I attach a `hs.webview.toolbar`, I have a title in my chooser that I don't know how to change, I have seen lots of screenshots of chooser+toolbar here in the issues, but never seen that in other screenshots

![image](https://user-images.githubusercontent.com/1171003/127285418-e4334f58-08d5-4a06-ba5b-c6a10fe70777.png)

**Comment by fyrebase** [comment]
@Madd0g I have the exact same issue with Chooser and attaching a Toolbar.

![CleanShot 2023-10-31 at 23 14 30@2x](https://github.com/Hammerspoon/hammerspoon/assets/210659/8185df1d-93e8-4ae4-9f96-ba58a3c84a62)
