### ISSUE TITLE
hs.mouse.setAbsolutePosition causes delay on El Capitan

### ISSUE THREAD

**Issue by thecodewarrior** [Hammerspoon/hammerspoon#2005]
Hi, I believe I've already worked out what the issue is, but here's some context:

Because I use a Wacom tablet I have no scroll wheel, so I have a hammerspoon script that allows me to scroll by dragging with the middle mouse button. In order to have the mouse always scroll over whatever I started in (as opposed to scrolling whatever the mouse happens to be over as I drag it up or down) I save the starting position and in my update function run `hs.mouse.setAbsolutePosition(start); event:post(); hs.mouse.setAbsolutePosition(oldPos)`. 

I've been running this script on a Mac using macOS Sierra for quite a while and I can drag the middle mouse button freely to adjust the speed just fine. However, on my El Capitan Mac the moment after I click the cursor freezes in place and I can't move it. I worked out that if I change the scroll update speed to 3.8Hz I can just barely cause the mouse to move between updates.

After a bit of research it appears `CGWarpMouseCursorPosition` (used [here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/mouse/internal.m#L47)) disassociates the mouse from the cursor for a fraction of a second. There appear to be two solutions, either the deprecated `CGEventSourceSetLocalEventsSuppressionInterval` before the warp or `CGAssociateMouseAndMouseCursorPosition` afterward to re-associate the mouse and the cursor with each other.

Here are some of the resources I found.
- [A StackOverflow question](https://stackoverflow.com/questions/8215413/why-is-cgwarpmousecursorposition-causing-a-delay-if-it-is-not-what-is)
- [A patch from Wine](https://www.winehq.org/pipermail/wine-patches/2015-October/143826.html)
- [A Rust library](https://github.com/tomaka/glutin/issues/670#issuecomment-162440037)
- [A file from libsdl](https://hg.libsdl.org/SDL/file/1982dc994254/src/video/cocoa/SDL_cocoamouse.m#l229) and [its latest version](https://hg.libsdl.org/SDL/file/8feb5da6f2fb/src/video/cocoa/SDL_cocoamouse.m#l230)

**Comment by cmsj** [comment]
Thanks very much for the excellently researched bug report! Fixed in 62bf81a1
