### ISSUE TITLE
Is there a way to donate to the Hammerspoon project?

### ISSUE THREAD

**Issue by tomrbowden** [Hammerspoon/hammerspoon#2008]
This is a great project, and I’ve been using Hammerspoon a lot lately. While I’m a bit short on time (and probably expertise as well) to properly contribute to this project, I would love to be able to donate in order to show my appreciation to those who have contributed. Is there any way I can donate?

**Comment by latenitefilms** [comment]
Currently no. I believe this has been discussed before in a GitHub issue, but I can't seem to find it - so maybe it was in IRC.

Whilst I've love to be able to throw @asmagill & @cmsj some cash, as they've both been a HUGE help to me personally over the years, I think they both just enjoy doing this as a hobby in between things, and adding cash into the mix complicates things.

**Comment by latenitefilms** [comment]
Maybe a question worth adding to the [FAQ](http://www.hammerspoon.org/faq/)?

**Comment by cmsj** [comment]
Done.
