### ISSUE TITLE
noises feature stopped working in mojave?

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#2011]
The noises feature doesn't work for me anymore in Mojave.
This is the gist of what I'm doing in my code, it used to work in 10.11 but I upgraded to 10.14 and the callbacks no longer fire.

    local noiseCallback = {
        [1] = function() hs.alert.show("start!") end,
        [2] = function() hs.alert.show("finish!") end,
        [3] = function() hs.alert.show("you did it!") end,
    }

    noisesListener = hs.noises.new(function(noiseType)
        noiseCallback[noiseType]()
    end)

    local mod = {}

    function mod.start()
        noisesListener:start()
    end

    function mod.stop()
        noisesListener:stop()
    end

    hs.hotkey.bind(cah, "y", function()
        hs.alert.show("listening")
        noisesListener:start()
    end)

Thanks

**Comment by latenitefilms** [comment]
Maybe this is something @trishume can help with?

**Comment by trishume** [comment]
Darn. I haven't upgraded to Mojave yet but I will soon and then I might be able to reproduce this and possibly fix.

**Comment by Madd0g** [comment]
When I first tried this feature, I thought it wasn't very useful, I could only produce the 'sssss' sound, so how useful could it be if I could only trigger one thing with it?

But then I realized since there's a start and end event, I could track the duration and do something useful with it. So I started building a morse code thingy where longer hissing meant a different event and you could associate a hissing pattern to an action.

So I built most of the initial logic for my idea and then sadly upgraded to mojave so I never finished the actual thing I imagined. Recently I got that itch again, so I [gave it a UI](https://gfycat.com/imaginaryvibrantamericancrow) that I'm triggering with a modifier key.

I'm patient, but I really want to try hissing at this UI. I've been dreaming about this for a year.

**Comment by asmagill** [comment]
Huh, I used to use that module some a couple of machines ago, but hadn't really used it recently... I can confirm that it no longer seems to work in Mojave.

Taking a quick look at the Security and Privacy settings panel, I'm going to guess that Hammerspoon needs to be given access to the microphone, but I don't see a way to add it manually, so we'd need to find a way to trigger the request... @cmsj or @latenitefilms, any thoughts? @trishume did you ever get a chance to try it out in Mojave?

**Comment by latenitefilms** [comment]
I've never actually tried `hs.noises`, but...

In theory, macOS should automatically prompt the user for access if Hammerspoon requires microphone access. It's possible that if you've updated your machine from High Sierra to Mojave, that something could have gone funky with permissions? You could try resetting your microphone permissions by triggering `tccutil reset Microphone` from Terminal.

If you're running Hammerspoon from Xcode, I believe you must have the `NSMicrophoneUsageDescription` key in the `Info.plist` for the notification to actually trigger. I've added a pull request here: #2172

It might also be worth adding a function for [`requestAccessForMediaType:completionHandler:`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624584-requestaccessformediatype?language=objc) to `hs.sound`?

**Comment by latenitefilms** [comment]
When executing the following code with the #2172 pull request code, I get the attached notification.

```lua
noises = hs.noises.new(function(result) 
    print(string.format("Result: %s", result))
end):start()
```
<img width="499" alt="Screen Shot 2019-09-08 at 8 32 08 pm" src="https://user-images.githubusercontent.com/22286696/64486980-d8197900-d277-11e9-9a39-6651c4f78412.png">

...which seems to fix the issue:

```lua
2019-09-08 20:30:39: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2019-09-08 20:30:42: -- Lazy extension loading enabled
2019-09-08 20:30:42: -- Loading ~/.hammerspoon/init.lua
2019-09-08 20:30:42: init.lua loaded
2019-09-08 20:30:42: -- Done.

> noises = hs.noises.new(function(result) 
    print(string.format("Result: %s", result))
end):start()
2019-09-08 20:32:03: -- Loading extension: noises

2019-09-08 20:33:04: Result: 1
2019-09-08 20:33:04: Result: 2
2019-09-08 20:33:39: Result: 1
2019-09-08 20:33:40: Result: 2
2019-09-08 20:33:40: Result: 1
2019-09-08 20:33:40: Result: 2
2019-09-08 20:33:41: Result: 1
2019-09-08 20:33:41: Result: 2
```

**Comment by trishume** [comment]
You can also check out https://talonvoice.com/ which is a scriptable input system which I worked with to integrate my noise recognizers, and then the author of Talon optimized them to use Accelerate.framework SIMD functions so it uses even less CPU.

**Comment by Madd0g** [comment]
@trishume - I am actually very interested in the idea of voice coding. I recently remembered that [2013 pycon video](https://www.youtube.com/watch?v=8SkdfdXWYaI) and I just did a couple of days research about what's available these days. I really liked the idea of connecting it to HS and doing all the automation in lua, but it seems like all these systems have their own scripting engines.

talonvoice looks cool, I love the idea of combining the hisses with regular voice commands. I'll check it out. I wonder how usable it is without dragon.

Thanks

**Comment by Madd0g** [comment]
I tried talonvoice, it's an amazing tool. 

I managed to send the hiss events back to hammerspoon from talonvoice. It's a bit awkward because it communicates via `hammerspoon://` urls which feels a bit slow, but it works.

**Comment by trishume** [comment]
I recommend trying to do everything within Talon, it's very powerful and all the hot reloading and things will work better and quicker that way. Talon can do basically everything Hammerspoon can, although it may not be documented and you have to look at examples or ask in the Talon Slack.

**Comment by Madd0g** [comment]
> Talon can do basically everything Hammerspoon can

I am too invested in HS, it's not even funny how reliant I am on it. I can't imagine going back and rewriting everything in python. 

Most of the things I need are not time sensitive, so I can accept some slowness due to talon>HS communication. I wonder if an applescript API in HS would have been better than `hammerspoon://` urls for communication.

**Comment by Madd0g** [comment]
can confirm that 0.9.76 fixes the problem, thanks!

**Comment by muescha** [comment]
@Madd0g I have seen your screencast. very interesting.
Is your hammerspoon config somewhere public available? I would like to look also into your hs.noises morse code setup

**Comment by Madd0g** [comment]
@muescha - for the only other person in the world who thinks it's cool - I took the time and [created a gist](https://gist.github.com/Madd0g/57e7f7fcbc0170b5b8392532b2db9780)

I cleaned up a little and removed dependencies on my other code, I was careful but cannot guarantee I didn't forget to remove something, I did not test it, but should work (fingers crossed).

PLEASE if you get it to work, provide some feedback!
I only showed it to like 3 people in the entire world, with not enough appreciation in my opinion 🤣 It's hard to find the right cross section of people that can appreciate something like that lol

**Comment by muescha** [comment]
@Madd0g thx a lot
