### ISSUE TITLE
How to update pods locally without modifying pod shell scripts?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2012]
@cmsj - As you'll have seen in #2009, when I execute `pod update` locally, it modifies `Pods/Target Support Files/Pods-Hammerspoon/Pods-Hammerspoon-frameworks.sh`, `Pods/Target Support Files/Pods-Hammerspoon/Pods-Hammerspoon-resources.sh`, etc. Is there a way to get around this? How do you update pods on your machine?

**Comment by latenitefilms** [comment]
I'm closing this issue for now. I'll just leave the pod-handling to @cmsj.

**Comment by cmsj** [comment]
Cocoapods “owns” those scripts, if it wants to modify them, it’s fine and I just commit the results.
