### ISSUE TITLE
hs.battery.psuSerial is always zero.

### ISSUE THREAD

**Issue by asenyshyn** [Hammerspoon/hammerspoon#2021]
Hi,

I think I found a bug in battery module. 
I saw in some blogpost idea about checking power adapter serial number and alerting if it's not yours.
So I tried to implement it in my configuration, but hs.battery.psuSerial() always returns zero.
System info on my macbook(late 2016 with usb-c power) shows power adapter serial like `C4H701102AXXXXXXX` - it just does not seem to be an integer as defined in battery module.

```
> hs.inspect(hs.battery.getAll())
{ amperage = 0,
  capacity = 3963,
  cycles = 333,
  designCapacity = 4315,
  health = "Good",
  healthCondition = "n/a",
  isCharged = true,
  isCharging = false,
  isFinishingCharge = "n/a",
  maxCapacity = 3963,
  name = "InternalBattery-0",
  otherBatteryInfo = {},
  percentage = 100.0,
  powerSource = "AC Power",
  privateBluetoothBatteryInfo = {},
  psuSerial = 0,
  timeRemaining = -2.0,
  timeToFullCharge = 0,
  voltage = 12910,
  watts = 0.0
}
```

**Comment by cmsj** [comment]
It's weird, the underlying API for getting battery/charger info has the serial typed as an Integer, but that doesn't seem like it's the case with more modern chargers. I can't find any indication that there is new API to inspect them, unfortunately.

**Comment by asenyshyn** [comment]
from what I found:
macbooks with usb-c chargers have this issue.
older - return serial just fine.

I don't know objective c, but I tried to get serial number value and I succeeded with code like:

```
static int battery_psuSerial(lua_State* L) {
    CFDictionaryRef psuInfo = IOPSCopyExternalPowerAdapterDetails();
    if (psuInfo) {
        NSString *serialNumber =(__bridge NSString *) CFDictionaryGetValue(psuInfo, CFSTR("SerialString"));
        if (serialNumber) {
            lua_pushstring(L, [serialNumber UTF8String]);
        }
        CFRelease(psuInfo);
    }
    lua_pushnil(L);
    return 1;
}
```

It does not work as it should, but it returns my serial :)

**Comment by cmsj** [comment]
@asenyshyn out of interest, what about that doesn't work as it should?

**Comment by asenyshyn** [comment]
@cmsj It did not seem to refresh data in lua table after plugging/unplugging charger.
I built hammerspoon with this function and got my serial number in application, but it did not change after unplugging power(I'd expect it to become empty string or none). 
But, frankly, I did not investigate it any deeper..

**Comment by cmsj** [comment]
Added `hs.battery.psuSerialString()`

**Comment by asenyshyn** [comment]
Thank you!
