### ISSUE TITLE
hs.alert suppressed by hs.execute

### ISSUE THREAD

**Issue by ottopic** [Hammerspoon/hammerspoon#2024]
Hello,
I'm trying to display alert befor excute command but it's seems impossibile:

```
hs.alert("Hello")
hs.execute("java .hello.jar")
```

Is it my fault?

**Comment by latenitefilms** [comment]
You could try wrapping `hs.execute` in a `hs.timer` so there's a bit of a delay after showing the alert?

**Comment by ottopic** [comment]
Trying with
```
hs.alert("Hello")
hs.timer.usleep(4000000);
hs.execute("java .hello.jar")
```
no results.

Using
```
hs.alert("Hello")
hs.timer.doAfter(4, function()
      hs.execute("java .hello.jar")
end)
```
works!

**Comment by latenitefilms** [comment]
@ottopic - Nice one! If you're happy with this solution, please close this issue. You can always reopen later if needed.
