### ISSUE TITLE
is there a way to share a file directly to a person with AirDrop?

### ISSUE THREAD

**Issue by eggcaker** [Hammerspoon/hammerspoon#2025]
I know hammerspoon can open airdrop dialog with share items , is possible to define recipients for AirDrop sharing ?

**Comment by latenitefilms** [comment]
Does [`hs.sharing:recipients([recipients])`](https://www.hammerspoon.org/docs/hs.sharing.html#recipients) do what you want?

**Comment by eggcaker** [comment]
I tried , but I don't know how to set the recipient, for email sharing, it's the email address. But not found any doc or source code to find this for AirDrop sharing, i tried the mac host(ex: Mike's MBP) in the AirDrop dialog, not working

**Comment by asmagill** [comment]
Ok, noticed some mistakes in the documentation for `hs.sharing` that I'll have to address later, but just to add, the documentation provided by Apple isn't exactly crystal clear on the subject either -- from their docs on the `NSSharingService` class and the `recipients` property:

> Each object in the array is an NSString object that contains the handle of a single recipient. The specific format of these handle varies from service to service. For example, some services use email addresses as handles.

**Comment by eggcaker** [comment]
@asmagill so you mean no way to to set the recipient correctly to send file with airdrop?

**Comment by asmagill** [comment]
Without an example, I'm not sure what to try if you've already tried email addresses and names as they appear in your Contacts application.  If you (or anyone else who cares to chime in) know of sample code, either from Apple's examples, or from other open source projects that we can examine the source for, I'm not sure what else to try.

It's definitely expecting an array of one or more strings, we just have no way to determine what strings it's trying to match against without more information.

**Comment by asmagill** [comment]
I suppose it may be that setting a recipient to the sharing object does nothing for AirDrop and is ignored... IIRC, AirDrop shows you everyone around you -- or just in your contact list that's currently around you if you toggled that in Settings (iOS) or in the Finder's AirDrop window (OSX) -- that can currently accept items (i.e. their device is on and unlocked); I don't recall off the top of my head ever *not* having to select someone from the AirDrop panel once I'd selected an item to share (which isn't to say whether or not it might be possible to predetermine them, it's just not the way I've ever used it)

Again, sample code or better documentation specifically about AirDrop would help if anyone has any suggestions.

**Comment by cmsj** [comment]
I’d be surprised if this is possible, the airdrop recipient can’t just be an iCloud username because airdrop goes to a specific device.

**Comment by vergenzt** [comment]
Based on https://github.com/seemoo-lab/opendrop/blob/ae5ac821fb3b233df3ac800e4eb47f287f4422cf/opendrop/client.py, it seems like AirDrop recipients are identified by an mDNS hostname prefix... I wonder if some simple command line tools could help to discover that 🤔

**Comment by asmagill** [comment]
You should be able to use the [hs.bonjour](https://www.hammerspoon.org/docs/hs.bonjour.html) module for discovery if you have the mDNS service identifier.

**Comment by asmagill** [comment]
Looking closer, we'd have to extract keys and do some other weird stuff to do it natively within Hammerspoon... kinda beyond our scope.

If you did install opendrop, though, you should be able to run it from within Hammerspoon via `hs.execute` or `hs.task`.
