### ISSUE TITLE
Permissions on Mojave: Not authorized to send Apple events to iTerm.

### ISSUE THREAD

**Issue by reybok** [Hammerspoon/hammerspoon#2031]
Since upgrading to Mojave, running the following commands, either via keybinding or directly in the console, doesn't work:
```
success,output,description = hs.osascript.applescript("tell application \"iTerm2\"\ncreate window with default profile\nend tell")
print('success:', success, 'output:', output); for k,v in pairs(description) do print(k,v) end
```
I get the following output:
```
2019-01-30 10:26:21: success:	false	output:	nil
2019-01-30 10:26:21: OSAScriptErrorAppNameKey	iTerm
2019-01-30 10:26:21: NSLocalizedFailureReason	Not authorized to send Apple events to iTerm.
2019-01-30 10:26:21: OSAScriptErrorRangeKey	NSRange: {24, 37}
2019-01-30 10:26:21: OSAScriptErrorAppAddressKey	<NSAppleEventDescriptor: [0x0,49049 \"iTerm2\"]>
2019-01-30 10:26:21: NSLocalizedDescription	Not authorized to send Apple events to iTerm.
2019-01-30 10:26:21: OSAScriptErrorNumberKey	-1743
2019-01-30 10:26:21: OSAScriptErrorBriefMessageKey	Not authorized to send Apple events to iTerm.
2019-01-30 10:26:21: OSAScriptErrorMessageKey	Not authorized to send Apple events to iTerm.
```

I have the current version of Hammerspoon (0.9.73).
After searching the internet for 2 days, I think adding Hammerspoon to the 'system settings' > 'security' > 'privacy' > 'automation' Panel could resolve the issue, but I don't know how - I get no dialogs from Mac asking for permission... 

All other settings should be fine (`hs.accessibilityState()` returns `true`).

Thanks in advance!

**Comment by cmsj** [comment]
@reybok that's weird, it's supposed to ask you for permission when you try to send events to an app. There was an issue that we didn't have a permissions request string in our Info.plist in an older version, so I wonder if it might work if you delete Hammerspoon and re-install it? Maybe something went wrong with the upgrade.

**Comment by cmsj** [comment]
Maybe try `tccutil reset AppleEvents` in a terminal (I'd probably reboot after that too).

**Comment by reybok** [comment]
I tried that, sadly it also didn't solve the problem. I'm sorry for all the trouble, I don't want to waste your time. If I can provide any additional info, let me know! 

I attached the screenshots from the privacy settings where I tried to enable as much as possible. Maybe that helps

![screenshot 2019-01-30 at 14 17 35](https://user-images.githubusercontent.com/32271425/51983862-16f18000-249a-11e9-8798-97ff921fe9e0.png)
![screenshot 2019-01-30 at 14 17 48](https://user-images.githubusercontent.com/32271425/51983864-16f18000-249a-11e9-9d66-e6c189d7f0b4.png)
![screenshot 2019-01-30 at 14 17 59](https://user-images.githubusercontent.com/32271425/51983865-178a1680-249a-11e9-8ddd-06aa650638bd.png)

**Comment by cmsj** [comment]
No, you're right, it should be listed there, and the tccutil reset should have made it prompt to be there :/

**Comment by ivmirx** [comment]
There seem to be a bug in macOS when permission dialogs are swallowed. Even disabling System Integrity Protection and deleting `/Library/Application Support/com.apple.TCC/TCC.db` (that keeps all the permissions) doesn't recover them for some apps.

**Comment by ivmirx** [comment]
There seem to be a bug in Mojave that prevents some apps from showing permission dialogs and appearing in the "Automation" list at all. Disabling System Integrity Protection and deleting `/Library/Application Support/com.apple.TCC/TCC.db` (that keeps all the permissions) should fix it in theory but sometimes it doesn't help.

**Comment by chdiza** [comment]
I'm having a similar problem on Mojave, except it has to do with being blocked from accessing the Calendar database.  All my HS configs are identical on my Mojave and High Sierra machines, but only Mojave has this problem.

**Comment by reybok** [comment]
I won't be able to test and verify patches in the future since I switched to a linux machine a couple of weeks ago. 

I'm sure the projects' maintainers know how to proceed (close, if no one else can experiences the same bug?) with this issue. Thanks for providing hammerspoon to people that want more control of their mac OS.

**Comment by tom-haines** [comment]
Just found this thread after a lot of hunting around.  @ivmirx huge thanks for tip about deleting TCC.db : finally that fixed my issues!
