### ISSUE TITLE
can't remap keys for OSX 10.14.3

### ISSUE THREAD

**Issue by aeftimia** [Hammerspoon/hammerspoon#2033]
I had been using the following snippet from [one of the hammerspoon examples](https://github.com/kkamdooong/hammerspoon-control-hjkl-to-arrow/blob/master/init.lua)

```
local function pressFn(mods, key)
    if key == nil then
        key = mods
        mods = {}
    end

    return function() hs.eventtap.keyStroke(mods, key, 1000) end
end

local function remap(mods, key, pressFn)
    hotkey.bind(mods, key, pressFn, nil, pressFn)
end

remap({'ctrl'}, 'h', pressFn('left'))
remap({'ctrl'}, 'j', pressFn('down'))
remap({'ctrl'}, 'k', pressFn('up'))
remap({'ctrl'}, 'l', pressFn('right'))
```

for about a year and a half now on two macbooks, but code doesn't work on my latest Macbook Pro (version 10.14.3). The console doesn't show any errors, just the above hotkeys don't have any effect any more.

Probably (but not necessarily) unrelated: my usual window manager hotkeys also no longer work, and now throw following error in the console for everything (even when there is a window is obviously in focus):
`2019-01-30 09:49:33: 09:49:33 ** Warning:      grid: Cannot get frontmost window`

**Comment by cmsj** [comment]
Check the security system prefs and make sure Hammerspoon has Accessibility access.
