### ISSUE TITLE
hs.screen.watcher fires when monitors haven't changed

### ISSUE THREAD

**Issue by evantravers** [Hammerspoon/hammerspoon#2041]
I use hs.screen.watcher to automatically reflow my screens when I plug my laptop into my dock.

https://github.com/evantravers/hammerspoon/blob/0c338b2283f67b2b7a3c02572e791379e3bc5c10/autolayout.lua#L29

However… the watcher seems to fire randomly when I'm just moving my mouse around… I haven't been able to determine what causes it to happen…

current theories:

- moving the mouse between monitors
- I hide my dock, maybe when the dock appears? I haven't been able to figure it out.

**Comment by cmsj** [comment]
It's possible it's dock related - the screen watcher fires when screen related parameters change, but since the menubar and dock regions are considered out of bounds for apps, the screen's effective frame size will be changing. Do you explicitly hide the dock, or use auto-hiding?

**Comment by evantravers** [comment]
Thanks for responding Mr. Jones. You guessed it, auto hiding.

If that’s it, maybe I can capture the event and only fire the watcher when
the number of displays changes rather than all events? I’ll look at the
docs.

**Comment by cmsj** [comment]
I'll close this issue, since I don't think there's anything we can do in Hammerspoon to help identify *why* the event fired, unfortunately.
