### ISSUE TITLE
hs.audiodevice should allow inspection of the outputs on a device

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#205]
Some devices have multiple outputs. Some (e.g. "Built-in Output" have a single output which changes name sometimes - e.g. from "Internal Speakers" to "Headphones" and vice versa)

It would be useful to be able to introspect these, and maybe even watcher them.

**Comment by cmsj** [comment]
https://github.com/celsworth/priordio/tree/master/Priordio has some related code

**Comment by cmsj** [comment]
This is also necessary to set an AirPlay device as the default output device

**Comment by lowne** [comment]
(fwiw, [this CLI tool with source](http://whoshacks.blogspot.it/2009/01/change-audio-devices-via-shell-script.html) also works with "Internal Speakers" etc)

**Comment by cmsj** [comment]
At least for AirPlay, it seems like all bets are off. 10.11's CoreAudio will no longer usefully interact with AirPlay devices. See http://openradar.appspot.com/radar?id=5039701907996672

**Comment by cmsj** [comment]
@nkg (see previous comment about AirPlay. Looks like it's not going to be possible because 10.11 ruins everything)

**Comment by nkg** [comment]
Thanks @cmsj
