### ISSUE TITLE
hs.http.post send wrongly encoded payload when certain utf-8 characters are present in the data

### ISSUE THREAD

**Issue by ecerulm** [Hammerspoon/hammerspoon#2058]
A particular example 

hs.http.post(url, '”text”')

Note the special character ” which is not a regular double quote but a [U+201D](https://www.compart.com/en/unicode/U+201D) that should be sent as `e2 80 9d`. 

For some reason, `hs.http.post` is sending it as `61 00 1d`. 

I'm pretty sure that the input string is correct as I write it to disk with
```
local file = io.open("tmp.txt", "w")
file:write(json)
file:close()
```
and I can see with `hexdump` that the correct sequence `e2 80 9d`. 

I should note that other UTF-8 characters are sent ok.

**Comment by ecerulm** [comment]
I see a suspicious conversion of the body text at
https://github.com/Hammerspoon/hammerspoon/blob/b456479c247338dca45a2614436ae67ebd921098/extensions/http/internal.m#L164-L165

**Comment by asmagill** [comment]
In situations like this, Hammerspoon should be treating the string as a block of data only and not make any assumptions/conversions... LuaSkin can convert an item on the stack as raw data (NSData).

Since thats what the ‘setHTTPBody’ method accepts, we should use that and keep the encoding type at the lua level.

I’ll try to get some time tomorrow to address this if no one else can sooner.

**Comment by asmagill** [comment]
@ecerulm are you able to build a development version of Hammerspoon to test #2059 against your specific situation? I'll be working up some tests myself later tonight/tomorrow but if you are comfortable with building your own, I figured you might want to test it yourself sooner.

**Comment by ecerulm** [comment]
I just tried against the [GitHub create gist api](https://developer.github.com/v3/gists/#create-a-gist) and it works now. Thanks for the quick fix.

**Comment by cmsj** [comment]
I'm going to close this issue since I believe this has been addressed. Please re-open if you disagree.
