### ISSUE TITLE
 Switching between textboxs (equivalent to tab key)

### ISSUE THREAD

**Issue by AviAlche** [Hammerspoon/hammerspoon#2065]
Im trying to automate logging into a site with multiple fields in different textboxs.
All I need is to input a text, then press 'tab' to jump to the next textbox and then input some more text.

Tried using ({tab}) and \t.    It works as a tab when I test it in a text editor, but in the site the 'tab' key does not change the textbox and I end up with all the input in the first textbox.

Is that feature supported?

**Comment by latenitefilms** [comment]
`hs.eventtap.keyStroke(nil, "tab")` will press the "tab" button.

**Comment by AviAlche** [comment]
great thx a lot! do you know where is the documentation for it?

**Comment by latenitefilms** [comment]
http://www.hammerspoon.org/docs/hs.eventtap.html#keyStroke

**Comment by cmsj** [comment]
(I'm closing this issue because I think it's fully answered now? Please feel free to re-open if that's not the case).
