### ISSUE TITLE
Arrow keys return fn flag when using hs.eventtap?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2074]
@asmagill & @cmsj - I've just noticed that when using `hs.eventtap` that if I press the arrow keys on my external Mac full-size keyboard or on my MacBook Pro keyboard that `: getFlags()` returns `fn = true`. Is this expected behaviour?

**Comment by Habbie** [comment]
> Is this expected behaviour?

I don't know, but I see it too.

**Comment by asmagill** [comment]
Yes, this is normal. Many (all?) of the "named" (Page Up/Down, Home, etc.) keys are considered "Function Keys" by the OS.

Actually holding down the Fn key while pressing these doesn't change anything, so the only way to detect something like "Fn+Cmd+arrow" would be to use eventtap to capture `flagsChanged` and set/unset a local flag when it detects the change to Fn and then use this to determine if it was pressed *before* however you're capturing `Cmd-arrow` (either via hotkey or another eventtap).

**Comment by cmsj** [comment]
Closing, since we have an answer.

**Comment by latenitefilms** [comment]
@cmsj - Might be worth updating the documentation in that case?
