### ISSUE TITLE
Weird launching/focusing of VSCode

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#2075]
I have some launching/focusing code and it's acting weird, different names of the app work differently in different hs.application functions.

When the app is running/not running:

```lua
hs.application.launchOrFocus('Code') -- doesn't work
hs.application.launchOrFocus('Visual Studio Code') -- works
```

When the app is running:
```lua
hs.application.get('Code') -- works
hs.application.get('Visual Studio Code') -- doesn't work
```

Thanks

**Comment by cmsj** [comment]
This is ultimately down to the app itself - if it declares different names for itself in different parts of its metadata, we get stuck in this situation. Other than adding a fragile lookup table of things like this, I'm not sure there's any way around it for us, unfortunately 😕

**Comment by DavidLGoldberg** [comment]
This hack isn't great.  It's a bit slower, but for now I think it's working well enough for me in my script:

    --hs.application.launchOrFocus("Visual Studio Code")
    hs.osascript.applescript("do shell script \"/usr/local/bin/code\"")

Gross. I know :)

I have to fix my environment and I'll revert back.
@Madd0g  were you developing extensions and running the various test configs by any chance?

**Comment by latenitefilms** [comment]
You could also just use the bundle ID?

AppleScript has the potential of memory leaks sadly.
