### ISSUE TITLE
hs.spoons.use: attempt to index a nil value (global 'spoon')

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#2077]
`hs.spoons.use`, which looks like a great way to load spoons, calls: 

```lua
      local spn=hs.loadSpoon(name)
```
 This fails to set the global variable `spoon`, which results in the error above.  This occurs because `hs.spoons.list`, which is called on use of `use` (via `isInstalled`), references this global variable.  Perhaps the global should just be included by default if the spoons module is going to use it throughout.  Or at minimum `use` should enable the global by calling `loadSpoon` with a 2nd argument of `true`.

**Comment by cmsj** [comment]
Could we see the full Lua traceback you get? I'm not sure I quite understand what's going on here, because `hs.loadSpoon()`'s second argument defaults to true, so the global `spoon` variable should be created.

**Comment by jdtsmith** [comment]
```
2019-05-03 14:04:36: -- Loading extension: spoons
2019-05-03 14:04:36: *** ERROR: ...oon.app/Contents/Resources/extensions/hs/spoons/init.lua:165: attempt to index a nil value (global 'spoon')
stack traceback:
	...oon.app/Contents/Resources/extensions/hs/spoons/init.lua:165: in function 'hs.spoons.list'
	...oon.app/Contents/Resources/extensions/hs/spoons/init.lua:188: in function 'hs.spoons.isInstalled'
	...oon.app/Contents/Resources/extensions/hs/spoons/init.lua:235: in function 'hs.spoons.use'
	/Users/jdsmith/.hammerspoon/init.lua:61: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)
```

and here's the call in my init:

```lua
hs.spoons.use("TextClipboardHistory",
	      {hotkeys={toggle_clipboard={mash,"c"}},start=true})
```

It's an easy workaround with `spoon={}` beforehand, but probably non-intuitive to new users.

**Comment by latenitefilms** [comment]
@cmsj - Did you see my suggested fix in #2082?

**Comment by asmagill** [comment]
The issue is that `_G["spoon"]` isn't created by `hs.loadSpoon` until *after* `hs.spoons.use` first checks to see if it's already loaded with `hs.spoons.list`... which assumes that the global has been created.

Is there a reason the global `spoon` isn't just created when `hs._coresetup` is first loaded? Why wait until `hs.loadSpoon` is invoked? If it's a question of keeping the global namespace "cleaner" until global spoon use is actually asked for, then #2082 looks good, though we should probably check to make sure that there aren't other places in `hs.spoons` which assume the global variable already exists.

**Comment by latenitefilms** [comment]
I personally preferred to keep the global namespace "cleaner" - as we don't use spoons in CommandPost - however, more than happy to go with whatever you prefer.

Adding `spoon={}` to `hs._coresetup` is definitely another very easy fix.

**Comment by cmsj** [comment]
@asmagill good catch. I prefer the route of just creating `_G["spoon"]` so we don't end up with checks like #2082 all over the place. I've just pushed what should be a reaonable fix - we now just create the global `spoon` variable when `hs.spoons` starts loading.
