### ISSUE TITLE
Key Sequence Bindings

### ISSUE THREAD

**Issue by smackesey** [Hammerspoon/hammerspoon#208]
Rather than just binding modifiers and a single keystroke, it would be great if you could bind key sequences a la Vim, emacs, Keymando, etc.

**Comment by smackesey** [comment]
@cmsj made the following comment on the Google Group about this:

>This is technically possible, in that you could have the first key enter a modal state which listens for subsequent ones. The vimperator variant of hs.hints does something similar to this.
There's no higher level implementation that makes this trivial to do though. I think it would be interesting to have a wrapper that provided that implementation, but I'd want it to be a separate function from hs.hotkey.bind(), to keep things clean.

**Comment by cmsj** [comment]
For the sake of clarity, are you thinking that you hit, for example "ctrl-alt-shift-t", then release all of those and then hit "f", or would you expect to keep the modifiers pressed throughout?
(I would say the former, that seems more like how I would describe sequences in VIM, but it seems worth enumerating the specifics :)

**Comment by smackesey** [comment]
I'm thinking that you should be able to do either; basically you should be able to create sequences of arbitrary chords, where a chord is defined as some set of modifiers + a main key. Vim (and other keymap utilities I've encountered) allow this.

**Comment by gwww** [comment]
Do the modal functions in https://github.com/gwww/dotfiles/blob/master/_hammerspoon/init.lua help? I have bound it to hyper-a

**Comment by cmsj** [comment]
@smackesey do either of the last two comments help with this?

**Comment by kevinastone** [comment]
thanks @gwww, that works great!

**Comment by kevinastone** [comment]
Oh, even better:
http://www.hammerspoon.org/docs/hs.hotkey.modal.html

**Comment by gwww** [comment]
Nice. Did not know about the modal api. Thx!

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Comment by dvcrn** [comment]
Old issue but wondering if anything changed in hammerspoon about this. Looking for similar functionality (do something when a certain combination of keys are pressed within $timeout). Not necessarily going into modal mode, just do something when for example certain characters have been entered into a text box
