### ISSUE TITLE
Notarization for Hammerspoon?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2084]
@cmsj - Curious... have you done any tests or experiments yet in regards to getting Hammerspoon [Notarized](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc)?

**Comment by cmsj** [comment]
Not yet, but it's quite likely that I'll be figuring that out over the summer, since it's quite likely to be a requirement in 10.15. I'll close this issue, since I'm not going to do anything until we learn what the future looks like, at WWDC in a month.
