### ISSUE TITLE
Typing in lock screen after waking from sleep?

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#2085]
Weird thing, I recently added some code that uses `eventtap` to send keystrokes. After that I had several cases where the system would wake from sleep and continuously type _something_ in the password field, it never stops and I have to force shut down the system by holding the power button.

I can't be 100% sure it's caused by HS, but it sure feels like it, because it never happened before.

This is my function, it switches themes in VSCode:

```lua
function switchVsCode(mode)
    hs.eventtap.keyStroke({ 'ctrl' }, '`')
    hs.timer.usleep(200)
    local theme = mode == 'dark' and 'one monokai' or 'quiet'
    hs.eventtap.keyStrokes(theme)
    hs.timer.usleep(200)
    hs.eventtap.keyStroke({ '' }, 'return')
end
```

Worth mentioning, this code uses `usleep` (I don't know if that's a good idea, just copied it from somewhere) and it actually doesn't do what I expect it to, instead of waiting for all characters (i.e. "one monokai") to be typed, the `return` is sent immediately after 1-2 letters ("on" and then "e monokai" is sent after the `return`).

Another thing I remembered, this function is called from a `hs.urlevent.bind` (which is called by Karabiner-Elements via a hotkey), maybe something queues them up somehow and then releases them all at once upon waking?

So do you think it could really be HS sending keystrokes to the password field on the lock screen? Do you think the bug in my script can have anything to do with the problem?

Thanks!

**Comment by latenitefilms** [comment]
To be honest, I'm not sure, but you could add a simple check in the `switchVsCode` function to only trigger if VSCode is frontmost and see if that makes a difference?

**Comment by Madd0g** [comment]
Good idea, I did that.

**Comment by latenitefilms** [comment]
Fingers crossed it fixes the issue. If it does, please close the issue. Thanks @Madd0g!

**Comment by Madd0g** [comment]
Today it happened again, today it happened _after_ I typed my password and not on the lockscreen itself, then I just saw the letter e typed over and over again. I managed to restart HS while it was doing it but it kept typing the letter, so I don't think it's HS anymore. Maybe somehow Karabiner is doing it...

**Comment by cmsj** [comment]
(I'm going to close this since it seems like we're off the hook, but please feel free to re-open if it seems like it might be an HS problem)
