### ISSUE TITLE
Variable keystrokes in bindings

### ISSUE THREAD

**Issue by smackesey** [Hammerspoon/hammerspoon#209]
This only makes sense in the context of key sequence bindings (#208). A prefix (first or first n keystrokes) is fixed, which activates a listener for one or more variable keystrokes. An action can then be taken dynamically depending on the variable keystroke. This allows the collapsing of large numbers of similar mappings into one. Here are two possible use cases:
- splitting the screen between two applications.

``` lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "VAR1", "VAR2", function(VAR)
  local apptable = { m = "macvim", t = "iterm", x = "excel", ... }
  local app1 = argtable[VAR1]
  local app2 = argtable[VAR2]
  -- move app1 to left half, app2 to right half
end)
```
- passing an argument to a script. For example, I have a script that creates a new file from a template and opens it in MacVim. I have a lot of different templates. The command line invocation looks like:

``` sh
$ new_draft.zsh ruby
$ new_draft.zsh python
$ new_draft.zsh vega
etc...
```

It would be nice if I could cover all my templates by using a single binding like:

``` lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "VAR", function(VAR)
  local argtable = { r = "ruby", p = "python", v = "vega" }
  local arg = argtable[VAR]
  -- stuff with arg ...
end)
```

**Comment by smackesey** [comment]
@cmsj made the following comment about this on the Google Group:

>This is an interesting idea. I'm moderately sure it can't easily be done using the underlying mechanics of hs.hotkey, in that we have to bind to static events, however, we have hs.eventtap, so it ought to be possible to have the first hotkey start up an eventtap that reads n subsequent strokes and then stops itself, firing off appropriate actions afterwards.

**Comment by cmsj** [comment]
I think this should already be doable with a function that takes a table of inputs and produces all of the bindings you need, so rather than implement specific extra API in Hammerspoon that caters to one specific need, this can be implemented in pure Lua by any user, to address their needs.
