### ISSUE TITLE
hs.window needs to expose isMaximizable

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#2093]
There are windows which `hs.window` reports as  "standard" windows, which are not maximizable.  A good example of this is the System Preferences window.  Notice its green button is dimmed out.  Is there perhaps another flag that could be exposed in hs.window to report on whether a window is suitable for maximizing?  While doing a split view operation, these "regular, non-maximizable" windows are smaller and grouped on the bottom outside corner of the selection half-screen.

**Comment by cmsj** [comment]
Great idea, thanks! It will be in the next release :)

**Comment by jdtsmith** [comment]
Awesome, thanks! Looking forward to trying it out.
