### ISSUE TITLE
Cannot set hotkey to type individual characters

### ISSUE THREAD

**Issue by TechnoSam** [Hammerspoon/hammerspoon#2097]
I am using release 0.9.75.

I can manipulate the clipboard to insert text, and that works for most applications, but some do not handle pasting the same as inserting individual characters, so it would be good to have a way to just send the keystrokes directly.

I have looked at [keyStrokes](http://www.hammerspoon.org/docs/hs.eventtap.html#keyStrokes), but that just doesn't work. Maybe it's a bug, but this never inserts more than one character, and it's hard for me to figure out how it chooses which character to insert.

If this isn't a bug, then I think a new feature is probably needed. If it is a bug, I can try to look into it.

**Comment by cmsj** [comment]
it's probably a good idea to pass your functions as the next argument to `hs.hotkey.bind()`, so the code is executed when you release the hotkey - otherwise you're emitting keystrokes while another key is held down, which is likely to cause some confusion.
Does that help?

**Comment by TechnoSam** [comment]
No, I don't really understand what you mean by that. What function am I passing as which argument to the `bind` function?

**Comment by cmsj** [comment]
Sorry, yeah, that wasn't very clear. Try this:

```lua
hs.hotkey.bind({}, "a", nil, nil, function()
  hs.eventtap.keyStrokes("test")
end)```

(i.e. there's a couple of extra `nil` parameters before the function. See http://www.hammerspoon.org/docs/hs.hotkey.html#bind for the full rundown of possible parameters)

**Comment by TechnoSam** [comment]
Ah, that makes a lot of sense. I will try that as soon as I can.

Thank you!
