### ISSUE TITLE
Isn't window_topleft not window_bottomleft?

### ISSUE THREAD

**Issue by bsingr** [Hammerspoon/hammerspoon#2105]
Trying to get some window positioning working correctly and stumbled across hammerspoons window topleft function.

The apple docs state `The position in points of the element's lower-left corner in screen-relative coordinates (NSValue).` (https://developer.apple.com/documentation/appkit/nsaccessibilitypositionattribute?language=objc), but in the hammerspoon code it says `topleft` (https://github.com/Hammerspoon/hammerspoon/blob/f4fe1a665deaa1208ccef710d924814d9b414958/extensions/window/internal.m#L15)

Did i miss something or is the hammerspoon name wrong?

**Comment by cmsj** [comment]
Both are right! If you’re using Apple’s API directly, the window point is bottom left. We chose to use top left basically just because I prefer it 😬
