### ISSUE TITLE
hs.keycodes.setLayout and hotkeys

### ISSUE THREAD

**Issue by tysonvinson** [Hammerspoon/hammerspoon#2107]
This is really an informational request because this is a weird edge case that you wouldn't necessarily want to handle. I'm using hs.usb.watcher to switch between keyboard layouts with an external keyboard. Like so:

```
function usbDeviceCallback(data)
    if (data["productID"] == 0x6060 and data["vendorID"] == 0xfeed ) then
        if (data["eventType"] == "added") then
            hs.keycodes.setLayout("U.S.")
        elseif (data["eventType"] == "removed") then
            hs.keycodes.setLayout("Dvorak")
        end
    end
end
usbWatcher = hs.usb.watcher.new(usbDeviceCallback):start()
```

My reason for wanting to do this is that the external keyboard is doing a remap, in hardware, to Dvorak and its layout and modifiers would be different, and worse, if I left the hardware mapping of the keyboard in US and set the layout to Dvorak in macOS. But hs.hotkey.bind creates a table with keycodes and hs.keycodes.setLayout doesn't do anything to reload hotkeys to their layout-appropriate positions.

My thought on how to work around this is to replace all the places where I'm procedurally calling hs.hotkey.bind and instead add the binding information to a table. Then I could create a function that would delete all hotkeys (maybe by walking hs.hotkey.getHotkeys()) and then bind all hotkeys in one action. This function could be called at launch and in the usb callback. Does this sound reasonable? Is there a better way to do it or something obvious that I'm missing?

**Comment by cmsj** [comment]
Your proposed solution sounds pretty reasonable, although I'm a little surprised you need to do anything - if the keyboard is remapping in hardware, shouldn't the hotkey binds work the same without any layout changing?

I'm going to close this issue, but we can keep discussing, and re-open it if some HS work is required.
