### ISSUE TITLE
Hammerspoon Deletes Spoons When Clicked in Finder

### ISSUE THREAD

**Issue by davidalim** [Hammerspoon/hammerspoon#2112]
Hi,

I ran into an issue that could have ended up much worse on my Mac.
 
I wanted to edit my custom Spoon and went to ~/.hammerspoon/Spoons and double clicked on my `MySpoon.spoon` directory, thinking it would show the contents. 
Instead, an alert popped up which said 
```
“MySpoon.spoon” couldn’t be moved to “Spoons” because either the former  
 doesn't exist, or the folder containing the latter doesn't exist.

Source: /Users/<username>/.hammerspoon/Spoons/MySpoon.spoon
Dest: /Users/<username>/.hammerspoon/Spoons
```
It then proceeded to fully ***delete*** the entire Spoon!!

Luckily, I had this Spoon symlinked to another directory which had git initialized, so I was able to recover everything. 
My guess is that this is a bug in how Hammerspoon installs spoons.

To reproduce
1. Go to ~/.hammerspoon/Spoons
1. Copy/paste an existing `.spoon` folder (as to not delete the original spoon)
1. Double-click on the copied spoon
1. See error produced and that the spoon is completed deleted (not even moved into trash)

**Comment by cmsj** [comment]
Hmm, that's a good point. The idea was that, like many plugins/extensions on macOS, double clicking on them would move them to the correct folder, but we don't actually test if they're already in the correct folder.

I'll look into this!
