### ISSUE TITLE
Creating a mini window of a section of content already on screen

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2113]
This is probably a @asmagill thought exercise I'd imagine...

Basically, imagine I have an application which has a video player in it, which takes up about half of the app's interface of the screen.

What I want to do is stream this video player as another little popup window elsewhere on the screen.

My initial experiments have been to take a screen capture with `hs.window:snapshot()` crop and scale it using `hs.canvas`, then reposition it on the screen within a `hs.timer` loop, however performance is pretty terrible as you can imagine.

Any other ways you can think of tackling this problem?

**Comment by szymonkaliski** [comment]
If the app has support for syphon you could try that, the perf is usually very good: http://syphon.v002.info/ 

Other than that I doubt it's possible to do this in a performant way.

**Comment by latenitefilms** [comment]
That looks really cool - thanks @szymonkaliski - however unfortunately the application I'm thinking is Apple's Final Cut Pro in this case.

**Comment by cmsj** [comment]
I suspect that it might be possible to do this with whatever screen recording apps use, but whatever that is, I'm not familiar with the API. It also feels a little too niche even for HS, so unless there are any wild objections, I'm going to close this issue. Sorry!
