### ISSUE TITLE
Can I call C code from hammerspoon lua code?

### ISSUE THREAD

**Issue by antifuchs** [Hammerspoon/hammerspoon#2114]
I have an ObjC framework function that I'd like to call from hammerspoon: `extern int SACLockScreenImmediate ( void );` is the C declaration. I know where on the system the library lives (it's a private framework, eep): `-F /System/Library/PrivateFrameworks -framework login` is how I'd link it to a C program.

Now, I wonder if the lua interpreter included in Hammerspoon allows users to `dlopen` that file and call functions from it... and if so, what functions to use to do so.

So, two questions that I couldn't quite find from the `hs` docs:
* What lua environment does hammerspoon use? Is it LuaJIT?
* How do the `help("lua._C")` docs relate to this problem?

**Comment by asmagill** [comment]
First, check out `hs.caffeinate.lockScreen()` and see if it's sufficient for your needs.

Lua can only access C functions that are presented to it in a specific manner... there are some good books on the subject... I think my first was the C API section of [Programming In Lua](http://www.lua.org/pil/)

We've added a LuaSkin framework that allows for easier integration with Objective-C and simplified creation of complex objects with meta-methods, but at its most basic, for your example, you'd need to do something like this:

Save the following as `test.m`:

~~~objc
@import LuaSkin ;

// not really used for this example, but if we want to add callbacks or references to other
// entities defined in the lua state, this is where we'll store the reference to them
static int refTable = LUA_NOREF;

extern int SACLockScreenImmediate();

// function to add to the Lua interpreter
static int lockscreen(lua_State* L) {
  lua_pushinteger(L, SACLockScreenImmediate()) ;
  return 1 ;
}

// dictionary linking function name in Lua interpreter to the actual C function
static luaL_Reg moduleLib[] = {
    {"lockscreen", lockscreen},
    {NULL, NULL}
};

// required function, invoked when module is "required" by Lua interpreter
int luaopen_test(lua_State* __unused L) {
    LuaSkin *skin = [LuaSkin shared] ;
    refTable = [skin registerLibrary:moduleLib metaFunctions:nil] ;

    return 1;
}
~~~

Now, in the macOS Terminal, do the following:

~~~sh
$ clang test.m -fmodules -fobjc-arc -F/Applications/Hammerspoon.app/Contents/Frameworks/ -F /System/Library/PrivateFrameworks -framework login -dynamiclib -undefined dynamic_lookup -o test.so
$ mv test.so ~/.hammerspoon
~~~

Now, in the Hammerspoon console, you can do something like this:

~~~
xtras = require("test")
xtras.lockscreen()
~~~

For more complex examples, check out the `extensions` subdirectory of this repository. The `LuaSkin` framework documentation is at http://www.hammerspoon.org/docs/LuaSkin/, most of my modules, in various states of "working", can be found at https://github.com/asmagill/hammerspoon_asm, and you can find an old attempt at a module creation walkthrough at https://github.com/asmagill/HS_ModuleWalkthrough (it's outdated and probably misses some of the more recent additions we've made to LuaSkin, but the core of it should still be mostly correct). The [Google Group](https://groups.google.com/forum/#!forum/hammerspoon) and the issues and pull requests (including closed) here are also good places to peruse for questions and examples others have created or used when adding potential modules.

Hope some of this gives you a starting point!

**Comment by asmagill** [comment]
The help documentation provided under the "lua" branch is parsed from the official Lua documentation found at http://www.lua.org/manual/5.3/manual.html, "lua._C" is specifically section 4, so while it's a useful reference for the C API functions available to module writers, it doesn't include a full example, nor does it cover any of the LuaSkin additions we've added.

And we're using the (latest? I know it gets updated every so often, so we may be a minor release or two off) version of Lua 5.3.

LuaJIT is limited to 5.1 (with some attempts at 5.2 with varying levels of completeness), and for *most* things we've found modern machines to be fast enough, even with Lua being strictly interpreted and not compiled at run time. Trying to integrate LuaJIT of any version at this point would break practically everything, though I think someone was trying out a fork at one point (search the issues for LuaJIT if you're interested) and there has been some discussion of moving some of the modules to Swift to see if that might make adding future items quicker or easier, but as far as I know, none of the regular contributors here have the experience or time to properly evaluate this.

**Comment by antifuchs** [comment]
Thank you so much for the extremely clear and comprehensive answer! I can absolutely work with that!

**Comment by cmsj** [comment]
FWIW, as of 90d6ef7a we are now calling `SACLockScreenImmediate()` to lock the screen, so in the next release you'll be able to do this without adding your own module :)

**Comment by antifuchs** [comment]
That's amazing, thank you so much - I look forward to trying the new release (:
