### ISSUE TITLE
Context of execution of io.popen

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#2116]
I was trying to run gpg2 to decrypt a file content, but somehow running it in Hammerspoon doesn't work. e.g:

    $ lua
    > io.popen("which gpg2"):read("*all")
    /usr/local/MacGPG2/bin/gpg2
    
    $ hs
    > io.popen("which gpg2"):read("*all")

First one works as expected, second one - returns an empty string. I wonder why is that?

**Comment by cmsj** [comment]
My first suspect would be `$PATH`:

```
> io.popen("bash -c 'echo $PATH'"):read("*all")
/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by asmagill** [comment]
Hammerspoon starts up with a pretty limited PATH environment variable (all Mac applications do), which doesn’t include most of the paths that usually get set with shell startup scripts. Take a look at [hs.execute](http://www.hammerspoon.org/docs/hs.html#execute) or the [hs.task](http://www.hammerspoon.org/docs/hs.task.html) module which both offer (different) work arounds for this limitation.

**Comment by agzam** [comment]
Thank you for shedding light to this. I'm closing this for now.
