### ISSUE TITLE
求助：怎么运行一个命令

### ISSUE THREAD

**Issue by jiutianhuanpei** [Hammerspoon/hammerspoon#2119]
实在是对lua了解太少，有些常用的功能仅配合终端命令行就能搞定，所以想用它来执行一个脚本就好，找到以下代码可以执行：

```
cmd = "open  aFile"
hs.osascript.applescript(string.format('do shell script "%s"', cmd))
```

但是有一些后期添加的一些脚本，比如鼠须管的 Squirrel，它的位置是在 `/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel`，路径中间有一个空格，然后我试了仅有空格、一个\、两个\  ，结果都不能正常运行这个脚本 ，而单独在终端里运行 `/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload` 是可以的。

求大佬们帮忙

**Comment by Habbie** [comment]
From Google Translate:

It is really too little to know about lua, some commonly used functions can only be done with the terminal command line, so I want to use it to execute a script, just find the following code to execute:

Cmd = "open aFile"
Hs.osascript.applescript(string.format('do shell script "%s"', cmd))

But there are some scripts added later, such as Squirrel, which is in the mouse, in /Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel, with a space in the middle of the path, then I tried only spaces. , a \, two \, the results can not run this script, and running /Library/Input\Method/Squirrel.app/Contents/MacOS/Squirrel --reload in the terminal alone is fine.

Ask the big guys to help

**Comment by cmsj** [comment]
Using AppleScript to launch a shell command seems a bit heavy, and is making the shell quoting harder here. I'd look at using `os.execute()` or `hs.task()`

**Comment by jiutianhuanpei** [comment]
> Using AppleScript to launch a shell command seems a bit heavy, and is making the shell quoting harder here. I'd look at using `os.execute()` or `hs.task()`

Thank you very much, I solved it with `os.execute()`
