### ISSUE TITLE
Unable to selectMenuItem when active window is a full screen app

### ISSUE THREAD

**Issue by eccentric-j** [Hammerspoon/hammerspoon#2122]
First I want to say I'm enjoying Hammerspoon, this is an excellent project. Combining it with fennel has been a dream!

# Reproduction
1. Create a hotkey binding to refresh Safari:
   ```lua
   hs.hotkey.bind({"cmd"}, "m", function()
     local safari = hs.appfinder.appFromName("Safari")

     safari:activate()
     safari:selectMenuItem({ "View", "Reload Page" })
   end)
   ```
2. Open Safari
3. Press `cmd-M` – This should trigger a refresh.
4. Open another app and enter full-screen mode
5. Press `cmd-M` again.

## Expected
- When you press `cmd-M` in Safari, a refresh is triggered.
- When you press `cmd-M` in a full-screen app, Safari should still refresh

## Actual
- Safari refreshes when no full-screen apps are active
- Safari does not refresh when you are in a full-screen app

## Notes
- Logging shows the hotkey is activating and the app is receiving focus, but the menu item is not activating.

## Environment

| Property            | Value                 |
| ------------------- | --------------------- |
| Operating System:   | OS X 10.14.4 (Mojave) |
| Hammerspoon Version | 0.9.75                |
| Monitors Required   | 2 or more             |

**Comment by latenitefilms** [comment]
Try using `hs.dockIcon(false)`.

Discussed in #1184

**Comment by eccentric-j** [comment]
Thanks for the suggestion. I had added hs.dockIcon(false) both before the hotkey binding and at the beginning of the callback. It does not fix the issue. Any other ideas?

**Comment by latenitefilms** [comment]
It could be a timing issue... try using `hs.dockIcon(false)` at the top of `init.lua`.

Also, try adding in some debugging code, and make sure `safari` isn't `nil` when in fullscreen mode.

```lua
hs.hotkey.bind({"cmd"}, "m", function()
  local safari = hs.appfinder.appFromName("Safari")
  print(string.format("safari: %s", safari))
  safari:activate()
  safari:selectMenuItem({ "View", "Reload Page" })
end)
```

**Comment by eccentric-j** [comment]
Tried your snippet and moved the dockIcon switch earlier in the initialization. Unfortunately, Safari is still not refreshing from a full-screen app. Is it working when you try that?

The Safari app was found and is being activated:

```
2019-06-28 21:46:53: safari: hs.application: Safari (0x600002e0ce08)
```

**Comment by cmsj** [comment]
I think actually what's going on here is that it's typically unreliable to interact with an app that isn't visible (or even focused) via menus. This is all being done via the accessibility APIs and they are intended to control what the user is seeing.

It might be worth trying to send some AppleScript from Hammerspoon to Safari to tell it to reload itself, but I very much doubt we're going to be able to make this work directly with the menus, unfortunately!
