### ISSUE TITLE
how to stop console dark mode

### ISSUE THREAD

**Issue by bosconb** [Hammerspoon/hammerspoon#2123]
After tested some lua files,the hammerspoon console suddenly turned to dark mode, i restarted it several times ,it was still the same. Any suggestion  to shut down it ? lots of thanks!!
![image](https://user-images.githubusercontent.com/47100031/60565404-0cfbe200-9d96-11e9-8ecd-154e361aaef3.png)

**Comment by latenitefilms** [comment]
Try [`hs.console.darkMode(false)`](http://www.hammerspoon.org/docs/hs.console.html#darkMode)

**Comment by bosconb** [comment]
> hs.console.darkMode(false)

coool ,it works!
