### ISSUE TITLE
Why is the launchOrFocus so slow?

### ISSUE THREAD

**Issue by zgqq** [Hammerspoon/hammerspoon#2126]
It takes 20+ milliseconds to focus some apps.

**Comment by cmsj** [comment]
Do you mean 20 seconds? 20ms is a pretty short amount of time!

Either way, I'm afraid there's probably nothing we can do about this - all `launchOrFocus()` does is tell the OS to launch the app name specified. Perhaps your Spotlight database needs rebuilding?
