### ISSUE TITLE
problem with script mapping caps to escape

### ISSUE THREAD

**Issue by gartha1** [Hammerspoon/hammerspoon#2127]
I don't know much about hammerspoon, but I am using vim a bit, and I want a setup whereby if I tap caps lock it taps escape, and if I hold caps lock, it holds the control key.  

And there is a script written(not by me), apparently for this or some such purpose here - 

 remap_capslock.lua

https://gist.github.com/zcmarine/f65182fe26b029900792fa0b59f09d7f

I have installed hammerspoon and have init.lua load the script.

The script requires that I use some external software, karabiner elements, to map caps lock to control.. (though the Mac OS has an option too, under 'system preferences'..'keyboard'..'modifier keys'). But either way, the hammerspoon script gives me the same issue..

I am on a mac laptop, a macbook. Let's say I am in Chrome, and I control-click (which does a right click), so as to access the right-click menu.  

Then as soon as I release control, the menu disappears. So if I want to click something in that menu I have to keep control held down.  I think what is happening is when I release caps lock it taps escape which makes the menu disappear.

If I close hammerspoon or comment out the loading of the script from the init.lua file, then the problem disappears. (But then I don't have caps mapped as I want it, to both escape and control)

**Comment by voldemortensen** [comment]
You need to add mouse clicks to the `non_modifier_tap` watcher so it sets `send_escape` to false when a click happens. I haven't tested this, but the general idea:

```lua
non_modifier_tap = hs.eventtap.new({hs.eventtap.event.types.keyDown, hs.eventtap.event.types.leftMouseDown}, function(evt)
  send_escape = false
  return false
end)
```

**Comment by cmsj** [comment]
I generally strongly encourage people to use Karabiner Elements for simple remappings like this - it operates in the macOS kernel, so it is able to modify/replace events *much* lower down the stack than we are, and so it typically works a lot better.
