### ISSUE TITLE
Relative mouse motion while keys are pressed 

### ISSUE THREAD

**Issue by jkrumbiegel** [Hammerspoon/hammerspoon#2128]
Is it possible to read out relative mouse motion while a certain application is open and some keys on the keyboard are pressed?

I want to connect my photo editing application in a way that when I press hyperkey+e and move up on the trackpad, exposure is increased, for example.

It would be best if I could also hide the cursor during this and not rely on absolute cursor coordinates, because changing settings in the software always works relative to the current value.

**Comment by asmagill** [comment]
Something like this? (The `Hyper-E` toggles it on and off)

~~~lua
local hotkey   = require("hs.hotkey")
local eventtap = require("hs.eventtap")

local eTypes = eventtap.event.types
local eProps = eventtap.event.properties

local mouseTap = eventtap.new({ eTypes.mouseMoved }, function(e)
    local xDelta = e:getProperty(eProps.mouseEventDeltaX)
    local yDelta = e:getProperty(eProps.mouseEventDeltaY)
    print("X: " .. tostring(xDelta) .. ", Y: " .. tostring(yDelta))
    return true
end)

myKey = hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "e", function()
    if mouseTap:isEnabled() then
        mouseTap:stop()
    else
        mouseTap:start()
    end
end)
~~~

Don't know of a way to hide the cursor anymore... there used to be a "private" API method to control the cursor, but Apple stopped supporting it many macOS versions ago and I'm not aware of any way to do that now, except when your own application (in this case Hammerspoon) is the frontmost app.

**Comment by cmsj** [comment]
I'm going to close this issue because I don't think any Hammerspoon work is required. Please re-open if you disagree.
