### ISSUE TITLE
Goals for this fork?

### ISSUE THREAD

**Issue by joelmccracken** [Hammerspoon/hammerspoon#213]
Hi,

What are the philosophical differences/goals between this project and
Mjolnir? I'm thinking about trying it, but I keep wondering what the
differences are.

**Comment by cmsj** [comment]
We wanted:
 * a more integrated release model - lots of extensions included in the .app rather than separately managed with luarocks.
 * signed releases
 * a more active core development community
 * easier discovery of extensions
