### ISSUE TITLE
touch bar f keys not recognized

### ISSUE THREAD

**Issue by madsem** [Hammerspoon/hammerspoon#2131]
Just started using Hammerspoon, it's extremely amazing! :)
Thanks a ton for creating this.

So if this is a known fact, sorry, but I couldn't find anything that was clear on if Hammerspoon recognizes touch bar keys?

I am using Karabiner-Elements to map caps-lock, and configured hammerspoon to create various layouts when pressing `hyper + fn + F<key>`.

This was also working, but now I've switched to a macbook with touch bar, and this combination doesn't do anything anymore. Console also stays empty, Karabiner event viewer does recognize the F key press though.

This is my config if it helps:
https://github.com/madsem/dotfiles/tree/master/.config/hammerspoon

**Comment by latenitefilms** [comment]
I think this is probably a Karabiner-Elements issue rather than a Hammerspoon issue.

For example, this works fine on my MacBook Pro with Touch Bar:

```lua
hs.hotkey.bind({}, "f1", function() print("test") end)
```

**Comment by cmsj** [comment]
@latenitefilms does it still work if you add a hyper? (not sure if you use KE to add a hyper key)

**Comment by madsem** [comment]
@latenitefilms don't think it's a karabiner-elements issue, as the event viewer there recognizes the f key event. Plus, it was working on an older Macbook pro without touchbar...

**Comment by latenitefilms** [comment]
No sorry, I haven’t tested with KE.

**Comment by cmsj** [comment]
Given the general disappearance of the touchbar from the macbook lineup, I think we might as well close this.
