### ISSUE TITLE
WebSocket client

### ISSUE THREAD

**Issue by jeffmikels** [Hammerspoon/hammerspoon#2132]
Perhaps I'm just missing this, but can hammerspoon act as a websocket client?

I want to connect to a websocket server, and listen and react on certain messages.

**Comment by latenitefilms** [comment]
See: http://www.hammerspoon.org/docs/hs.httpserver.html#setCallback

**Comment by cmsj** [comment]
I think this is all taken care of? Please re-open if something is missing/wrong.

**Comment by jeffmikels** [comment]
I see how that function can set a callback for the httpserver, but what I'm looking for is the ability to connect to a remote websocket server and have hammerspoon operate as a **client**.

What am I missing?

**Comment by jeffmikels** [comment]
Turns out hs.http.websocket exists, but it is undocumented. I will open an issue for that.
