### ISSUE TITLE
Karabiner-elements key mapping stop working when locking screen with hs.caffeinate.lockScreen() 

### ISSUE THREAD

**Issue by changgengli** [Hammerspoon/hammerspoon#2134]
For my laptop if I close the lid and wake it up, keymapping in Karabiner-elements is working.
But if I use hs.caffeinate.lockScreen()  to lock the screen, the keymapping is not working when typing my password.

I also noticed if I use hs.caffeinate.lockScreen(), I cannot change input method when typing password while if I close the lid(or CTRL+CMD+Q) I can do that.

Is caffeinate.lockScreen() using a different mechanism to lock the screen?

**Comment by cmsj** [comment]
All `hs.caffeinate.lockScreen()` does is:

```lua
os.execute("/System/Library/CoreServices/Menu\\ Extras/User.menu/Contents/Resources/CGSession -suspend")
```

which is the only way I know of to lock the screen from an app. If there is a better way, that doesn't break other tools, I would love to know about it!

**Comment by cmsj** [comment]
Ah, I think what you're seeing is probably because that command doesn't just lock the screen, it triggers the Fast User Switch function of macOS, so you're looking at a system-wide login screen and per-user things like Karabiner are not going to be active.

**Comment by asmagill** [comment]
It uses a private API, so I don't know if or when Apple might remove it, but has anyone checked whether the keymapping in question works when the screen is locked with `SACLockScreenImmediate`? If someone wants to give it a try, check out https://github.com/Hammerspoon/hammerspoon/issues/2114 for sample code to create the function within Hammerspoon and if it works, it might be worth adding it to the core module as an option for locking the screen (with the appropriate documentation that it might go away and the existing method, while it has some differences, is more likely to remain supported.)

**Comment by cmsj** [comment]
@asmagill Thanks for the pointer. Given that that API is what the keychain menu uses, I think we can be moderately sure that it, or something very much like it, will stick around. Worst case, we can just switch back.

I've switched the code over to using `SACLockScreenImmediate()` and kept the existing code as `hs.caffeinate.fastUserSwitch()`. Both will be available in the next release.

Thanks everyone!
