### ISSUE TITLE
Today's commits broke building on 10.14.6

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#2136]
I just tried building  9e6a0c8f7c9 after a `git pull`.  I did `make release` as usual and got:

```
/opt/bld/hammerspoon/LuaSkin/LuaSkin/Skin.m:280:32: error: unknown warning group '-Wsizeof-pointer-div', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wsizeof-pointer-div"
                               ^
/opt/bld/hammerspoon/LuaSkin/LuaSkin/Skin.m:322:32: error: unknown warning group '-Wsizeof-pointer-div', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wsizeof-pointer-div"
                               ^
2 errors generated.
```

I had to mine this out of `Release-build.log`.  What showed in the terminal was:

```
The following build commands failed:
	CompileC /Users/chdiza/Library/Developer/Xcode/DerivedData/Hammerspoon-adlzscacpnutjgcpsrpwvdewubqc/Build/Intermediates.noindex/LuaSkin.build/Release/LuaSkin.build/Objects-normal/x86_64/Skin.o /opt/bld/hammerspoon/LuaSkin/LuaSkin/Skin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
```

**Comment by latenitefilms** [comment]
You need to use Xcode 11 Beta 5, or comment out those lines.

**Comment by cmsj** [comment]
Yeah I’m getting us ready for xcode11 and Catalina.

**Comment by chdiza** [comment]
Does this mean that HS will from now on only be buildable on Xcode11 (and thus, only on Mojave or greater)?  Or is this just some initial tinkering?

**Comment by cmsj** [comment]
@chdiza This isn't tinkering, I'm getting everything in order for Catalina and Xcode 11 releasing, which typically includes going over any new build warnings and fixing them.

Are you building on something older than Mojave?

**Comment by chdiza** [comment]
> I'm getting everything in order for Catalina and Xcode 11 releasing, which typically includes going over any new build warnings and fixing them.

That's all I meant by "tinkering" :)  I was just wondering if the inability to build on a pre-Mojave or pre-Xcode11 setup is going to be permanent, or is rather just a temporary side effect of testing-and-getting-ready.

> Are you building on something older than Mojave?

On my High Sierra machines, yes.  On my Mojave machine, no.

**Comment by asmagill** [comment]
@cmsj, do you know of any way to determine at compile time if certain warnings exist for the local version of clang and branch around the two pragma's identified above? At present, these two lines are the only things preventing Hammerspoon from building under the latest non-beta of XCode... for now I'm just removing them (and then making sure to discard my changesto `Skin.m`  before pushing anything into a pull request, but it would be nice if some sort of test for warnings existed in clang like feature tests do so I didn't have to...

Not a biggie, I believe being proactive wrt to the upcoming OS update is more important than my convenience, but that doesn't mean I wouldn't prefer to eat my cake along with having it too 😝

**Comment by chdiza** [comment]
I just git-pulled today and am still getting the same build failure.  I was under the impression that some of the commits between now and when I opened this thread were supposed to fix building on Xcode10.  In particular, I thought (based on the commit message) that bc6a085b1865ef674d7c was supposed to make building on Xcode10 possible.

**Comment by asmagill** [comment]
Try pulling it now

Apparently when https://github.com/Hammerspoon/hammerspoon/commit/c8634a6ec5d8ede2fa5e297a9066ef5358570708#diff-199fdd8e796ac99961b38a8bd287d369 was applied, it removed the additional pragmas.

**Comment by chdiza** [comment]
@asmagill OK, that works now, thanks.
