### ISSUE TITLE
Confusion now that CFBundleVersion is an incrementing build number

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2152]
In the current public version of Hammerspoon `CFBundleVersion` is the same as the `CFBundleShortVersionString`, however in a [recent commit](https://github.com/Hammerspoon/hammerspoon/commit/4447448a406107e4a97f3e67aa0769ae7a45e185) this behaviour has now changed, and the `CFBundleVersion` is an automatically increasing build number.

This poses two interesting issues:

1) Using `hs.processInfo.version` returns the `CFBundleVersion`, so you get the build number rather than the expected version information. This can be easily fixed by modifying the `push_hammerAppInfo` function in `MJLua.m`. However maybe this build information should also be exposed?

2) The release scripts used to require the version as a parameter for protection, however now they require the build number, which is a bit confusing. This can again be fixed by modifying the release script.

However, when investigating this - I can across this:

https://stackoverflow.com/questions/19726988/what-values-should-i-use-for-cfbundleversion-and-cfbundleshortversionstring

...which made me wonder if rather than just having `CFBundleVersion` as a single number that increments each time, should it actually also contain the version information? For example, rather than `5011`, should it be `0.9.76.5011`? Thoughts @cmsj ?

**Comment by cmsj** [comment]
I think the proper thing to do here is just to switch `hs.processInfo` and the release script to use CFBundleShortVersionString (we can also expose the build number in `processInfo` though)
