### ISSUE TITLE
Where to download version 0.9.76

### ISSUE THREAD

**Issue by ZevveZ** [Hammerspoon/hammerspoon#2164]
![image](https://user-images.githubusercontent.com/17964973/64272555-2fff6980-cf72-11e9-9f54-08c2711809a0.png)
![image](https://user-images.githubusercontent.com/17964973/64272691-75239b80-cf72-11e9-8574-a7963fd8848f.png)

**Comment by latenitefilms** [comment]
0.9.76 hasn't been released yet.

**Comment by latenitefilms** [comment]
Actually, it looks like @cmsj updated the release notes, but never actually pushed out the update?

http://www.hammerspoon.org/releasenotes/

**Comment by ZevveZ** [comment]
> Actually, it looks like @cmsj updated the release notes, but never actually pushed out the update?
> 
> http://www.hammerspoon.org/releasenotes/

**Comment by rsefer** [comment]
> Actually, it looks like @cmsj updated the release notes, but never actually pushed out the update?
> 
> http://www.hammerspoon.org/releasenotes/

Release notes in question are here and comitted on 7/11: [https://github.com/Hammerspoon/hammerspoon.github.io/commit/736c65fd481f1829d3ab29f34f1592c11152e282](https://github.com/Hammerspoon/hammerspoon.github.io/commit/736c65fd481f1829d3ab29f34f1592c11152e282) but it doesn't seem like there is an official release/tag (or branch) in github, so the app package can't be downloaded or picked up by homebrew and the like
