### ISSUE TITLE
keyDown/keyUp stopped working after mac update to 10.14.6

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#2166]
I just updated to macOS 10.14.6, all my keyDown handlers have stopped firing, no errors in the console.

Hammerspoon 0.9.75

EDIT: other apps that hook up to key events broke as well, for example I'm using synergy to control another computer, but now it only sends the mouse events over. I can't find anyone else complaining about it, so maybe it's me? :(

Yay, I'm [not alone](https://github.com/debauchee/barrier/issues/393)

**Comment by latenitefilms** [comment]
Have you tried toggling Accessibility access off and on again?

See: http://www.hammerspoon.org/faq/

**Comment by Madd0g** [comment]
It's funny, even though at the time I restarted the OS multiple times, it just wouldn't work. Then a few days later (no restarts or shutdowns, only sleep), it sort of fixed itself and it never happened again. Weird.
