### ISSUE TITLE
hs.screen.desktopImageURL does not return image name

### ISSUE THREAD

**Issue by jchilders** [Hammerspoon/hammerspoon#2169]
When the wallpaper is set to rotate through images in a folder, `desktopImageURL()` does not return the wallpaper name, only the path to the folder containing it.

To reproduce:

1. Open System Preferences | Desktop & Screen Saver | Desktop
2. Make sure "Change picture" is checked & set
3. In Hammerspoon console:

```
> hs.screen.mainScreen():desktopImageURL()
file:///Library/Desktop%20Pictures/
```

**Comment by latenitefilms** [comment]
Ummm.. working fine here?

```lua
> hs.screen.mainScreen():desktopImageURL()
2019-09-07 10:13:09: -- Loading extension: screen
file:///Library/Desktop%20Pictures/Mojave%20Day.jpg
```

**Comment by cmsj** [comment]
@latenitefilms it only gives the bare directory when macOS is set to cycle through all of the images in a folder.

@jchilders As far as I can tell, this is a limitation of the system API we're using to get the desktop image, so unless Apple chooses to change the behaviour, I don't think there's anything we can do about this, unfortunately. I've added a note about this to our documentation (via 51e2cef0).
