### ISSUE TITLE
please consider XDG_CONFIG_HOME support

### ISSUE THREAD

**Issue by puttin** [Hammerspoon/hammerspoon#2175]
see also [XDG Base Directory Specification
](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

now the folder is in `~/.hammerspoon`

**Comment by latenitefilms** [comment]
You can change Hammerspoon's config file location by executing the following command in Terminal:

```
defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"
```
