### ISSUE TITLE
macOS Catalina 10.15 - Icon Issues

### ISSUE THREAD

**Issue by rsefer** [Hammerspoon/hammerspoon#2176]
As of the latest version of the macOS Catalina 10.15 betas (I believe it is developer Beta 8 / Public Beta 7 - build 19A558d) there is an issue with certain PDF icons. This is presented in at least 2 places.

1. The Hammerspoon Console icon for "Reload config"

![image](https://user-images.githubusercontent.com/539765/64751020-71e35f00-d4e0-11e9-8d82-eaf6168e510a.png)

2. `hs.menubar` icons when the `template` option is set to true.

When the template is set to false (or not explicitly set), all of my icons appear as one would expect

`:setIcon(icon, false)`

![image](https://user-images.githubusercontent.com/539765/64751139-e1594e80-d4e0-11e9-81f3-d9009e7be656.png)

When set to true, they do not appear at all (or are possibly transparent)

`:setIcon(icon, true)`

![image](https://user-images.githubusercontent.com/539765/64751169-fcc45980-d4e0-11e9-8a89-ed765e18909d.png)

In my specific use case:

The orange Overcast icon is orange when the podcast is playing, and black, or "templated", when it is paused or stopped. The paused/stopped is not appearing or is transparent. PDF here: [https://github.com/rsefer/dotfiles/blob/be4f9041e01edca95fabcd0e69a83f8753fe44e5/hammerspoon.symlink/Spoons/SDCOvercast.spoon/images/overcast_orange.pdf](https://github.com/rsefer/dotfiles/blob/be4f9041e01edca95fabcd0e69a83f8753fe44e5/hammerspoon.symlink/Spoons/SDCOvercast.spoon/images/overcast_orange.pdf)

In a separate and unrelated menubar + icon, the green clock icon is green when the timer is running, and black , or "templated", when it is stopped. The stopped is not appearing or is transparent.

**Comment by cmsj** [comment]
I'm seeing this too - I'd suggest we wait to see if it changes in a later beta. It's possible we're doing something wrong, but I'm not sure what that could be.

**Comment by rsefer** [comment]
The latest beta (Developer beta 9 / Public beta 8) seems to fix this

**Comment by latenitefilms** [comment]
Woohoo! Great news! Please close this issue if you’re now happy that it’s resolved.
