### ISSUE TITLE
Chooser choice images look too dark or too dark

### ISSUE THREAD

**Issue by jonathanj** [Hammerspoon/hammerspoon#2180]
With the below sample code I'm getting the darked/lightened icons in the screenshots. I'm using Hammerspoon 0.9.75 on macOS 10.14.6 (18G87). It looks like a blending mode is causing this because with multiple results moving the selection onto an item will emphasise the effect.

```lua
ch = hs.chooser.new(function(x) end)
ch:choices(function()
    local app = hs.application.find('Google Chrome')
    return {{text = 'Test', image = hs.image.imageFromAppBundle(app:bundleID())}}
end)
--ch:bgDark(true)
ch:show()
```

![image](https://user-images.githubusercontent.com/112166/64923449-44492f00-d7da-11e9-8394-5a798b6f37e4.png)

![image](https://user-images.githubusercontent.com/112166/64923456-4d3a0080-d7da-11e9-85ef-a7ab0c240dbc.png)

I also tried saving the resulting image out to a file, in case the image from the app bundle was behaving strangely but that looks fine.

```lua
local app = hs.application.find('Google Chrome')
hs.image.imageFromAppBundle(app:bundleID()):saveToFile('test.png')
```

![image](https://user-images.githubusercontent.com/112166/64923622-bd955180-d7db-11e9-887b-ab1a64241208.png)

**Comment by latenitefilms** [comment]
I've also just noticed this. Any ideas @cmsj or @asmagill ?

<img width="867" alt="Screen Shot 2019-10-20 at 1 09 53 am" src="https://user-images.githubusercontent.com/22286696/67146378-59801480-f2d6-11e9-9fba-953871ba313c.png">

**Comment by latenitefilms** [comment]
Setting all the `allowsVibrancy` values to `NO` seems to fix this.

**Before:**

<img width="802" alt="Screen Shot 2019-10-20 at 1 11 23 pm" src="https://user-images.githubusercontent.com/22286696/67153785-608d3e00-f33b-11e9-8f29-edf59cc20ab8.png">

<img width="802" alt="Screen Shot 2019-10-20 at 1 14 40 pm" src="https://user-images.githubusercontent.com/22286696/67153797-9af6db00-f33b-11e9-8d71-7b777f2052b7.png">

**After:**

<img width="802" alt="Screen Shot 2019-10-20 at 1 13 25 pm" src="https://user-images.githubusercontent.com/22286696/67153788-6daa2d00-f33b-11e9-9b9e-6025f6d4fd8d.png">

<img width="802" alt="Screen Shot 2019-10-20 at 1 14 29 pm" src="https://user-images.githubusercontent.com/22286696/67153801-a4804300-f33b-11e9-9862-edab44b18332.png">

I've added a pull request. Thoughts @asmagill & @cmsj ?
