### ISSUE TITLE
Update Sparkle Scripts to use new Build Numbers

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2187]
I'm not sure if you've already done this or not @cmsj but to quote the Sparkle site...

> If you use internal build numbers for your `CFBundleVersion` key (like an SVN revision number) and a human-readable `CFBundleShortVersionString`, you can make Sparkle hide the internal version from your users.
> 
> Set the `sparkle:version` attribute on your enclosure to the internal, machine-readable version (ie: “1248”). Then set a `sparkle:shortVersionString` attribute on the enclosure to the human-readable version (ie: “12.X Sea Lion”).
> 
> Remember that the internal version number (`CFBundleVersion` and `sparkle:version`) is intended to be machine-readable and is not generally suitable for formatted text.

**Comment by cmsj** [comment]
Interesting, I hadn't come across that, we set `sparkle:version` to the human-readable release number. Probably should change that!

**Comment by latenitefilms** [comment]
As discussed on another issue, the latest Xcode keeps on automatically using `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION` to populate `CFBundleVersion` and `CFBundleShortVersionString`. Rather than fight Xcode each time, should we just embrace this new way as well while we're at it.

Something like this might be helpful for getting `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION`:

http://bdunagan.com/2010/04/13/xcode-tip-update-version-numbers-with-agvtool/
