### ISSUE TITLE
Is it possible to copy on mouse select?

### ISSUE THREAD

**Issue by airblade** [Hammerspoon/hammerspoon#2196]
iTerm2 has a great feature where selecting text with the mouse automatically copies it.  It can then be pasted anywhere, not just into iTerm2.

Is it possible to implement the same copy-on-select behaviour with Hammerspoon?

**Comment by nonissue** [comment]
You may want to look at:

https://www.hammerspoon.org/docs/hs.uielement.html#selectedText

Though there is the caveat:

`Many applications (e.g. Safari, Mail, Firefox) do not implement the necessary accessibility features for this to work in their web views`

Do you want this to be available system-wide in all applications? That might be tricky, and I can imagine there are probably quite a few pitfalls even if you could get this working. It might be easier/possible in a specific application.

**Comment by nonissue** [comment]
Ah, on further examination, I don't think hs.uielement is the right tool. 

You might be able to implement something with hs.eventtap, but I imagine it would be enormously complicated.

Someone wrote a custom utility to do this (found via [stackoverflow](https://apple.stackexchange.com/a/241753)) but I'm not sure if it still works. Other answers in that thread suggest bettertouchtool.

**Comment by asmagill** [comment]
This idea intrigued me, so I threw together something you can try at https://github.com/asmagill/hammerspoon-config-take2/blob/master/_scratch/x11CopyPaste.lua

It's basically a Hammerspoon implementation of the code @nonissue found at stackoverflow.

Save it in your hammerspoon config directory and then add the following to your `init.lua` file:

~~~
x11Paster = require("x11CopyPaste")
x11Paster:start() -- use x11Paster:stop() to disable
~~~

It needs more testing, but I may try and recode it as a spoon later on -- I don't use a three button mouse very often, usually just my trackpad, so I want to think about other ways the paste could be quickly triggered, like maybe a hotkey (though why not just use Cmd-C/V then?) or when certain modifiers are being held down during a left/right click, etc.

**Comment by airblade** [comment]
@asmagill That works pretty well.  Thank you!

**Comment by airblade** [comment]
The only caveat is that every time I click anywhere, the system beeps at me because it's trying to copy but nothing is selected.

I suppose there's no way to detect whether any text is highlighted/selected?

**Comment by CKolkey** [comment]
For anyone coming here in the pursuit of a solution (like me), I adapted Asmagill's code with some improved heuristics to avoid attempting to copy when not desired, which seems to be pretty successful in my usage. 

```lua
local eventtap = require("hs.eventtap")
local eventTypes = eventtap.event.types
local timer = require("hs.timer")

local M = {}

local dragCount = 0
local clickStack = {}

local function trackClick()
	clickStack[2] = clickStack[1]
	clickStack[1] = timer.secondsSinceEpoch()

	return false
end

local function incrementDragCount()
	dragCount = dragCount + 1

	return false
end

local function wasDoubleClick()
	if not clickStack[2] then
		return false
	end

	return clickStack[1] - clickStack[2] <= eventtap.doubleClickInterval()
end

local function wasDragging()
	return dragCount > 10
end

local function handleMouseUp()
	local additionalEvents = {}

	if wasDragging() or wasDoubleClick() then
		additionalEvents = {
			eventtap.event.newKeyEvent({ "cmd" }, "c", true),
			eventtap.event.newKeyEvent({ "cmd" }, "c", false),
		}
	end
	dragCount = 0

	return false, additionalEvents
end

M._mouseDownEvent = eventtap.new({ eventTypes.leftMouseDown }, trackClick)
M._mouseDragEvent = eventtap.new({ eventTypes.leftMouseDragged }, incrementDragCount)
M._mouseUpEvent = eventtap.new({ eventTypes.leftMouseUp }, handleMouseUp)

M.load = function()
  M._mouseDownEvent:start()
  M._mouseDragEvent:start()
  M._mouseUpEvent:start()
end

return M
```
