### ISSUE TITLE
macOS Catalina 10.15 - hs.menubar ordering out of whack

### ISSUE THREAD

**Issue by rsefer** [Hammerspoon/hammerspoon#2197]
The order in which hs.menubars are displayed seems to be out of whack in the latest build of macOS 10.15 Catalina (Developer beta 9 / Public beta 8 - 19A573a). I imagine this is related to the fact the ordering functions don't seem to be supported any longer. `newWithPriority()` triggers the following:

https://github.com/Hammerspoon/hammerspoon/blob/aef049b9a560af045d5ace2deeabfc8690aa783f/extensions/menubar/internal.m#L99

Up to now, I've always used the standard `new()` and manually ordered things in my code. Strangely, there doesn't seem to be a rhyme or reason as to how they are being ordered. Consider the following example:

**Hammerspoon is not running. The following are displayed right to left in the menubar:**

[System Icon 4] [SI 3 - One Password] [SI 2 - Clock] [SI 1 - Search Icon]

**When launching Hammerspoon, I would expect the following, as was the case until recently:**

[Hammerspoon Icon 4] [H 3] [H2] [H1] [System Icon 4] [SI 3] [SI 2] [SI 1]

**Now (sometimes), the Hammerspoon ordering is messed up:**

[Hammerspoon Icon 2] [H 3] [H1] [H4] [System Icon 4] [SI 3] [SI 2] [SI 1]

**and other times, Hammerspoon becomes mixed in with existing system icons with what seems to be random ordering:**

[Hammerspoon Icon 2] [System Icon 4] [SI 3] [H1] [SI 3] [SI 2] [H4] [SI 1]

**Comment by rsefer** [comment]
Hoping this is a temporary beta bug, of course, but wanted to mention it anyway!

**Comment by cmsj** [comment]
Looking at class dumps of AppKit from 10.15, I don't think this is a temporary bug, I think they've just straight up removed the private API we were relying on.

I'll push a commit shortly to document that the `hs.menubar:priority()` method won't work from 10.15 onwards, and unfortunately we'll just have to live with what we've got.

FWIW I use Bartender to manage my menubar icons and the positions seem to be pretty stable in 10.15, but I don't have a lot of dynamic Hammerspoon icons, just a couple that stay visible all the time.

**Comment by rsefer** [comment]
@cmsj Dang! I should have been a bit more clear: ordering isn't working at all, both with priority and without. I also use Bartender and things are wonky. Oh well!

**Comment by asmagill** [comment]
Actually the priority methods have been almost useless for longer than 10.15, I just haven't gotten around to removing them.  2.0 probably should't even provide them at all.

There is a property which has been around since 10.12 that we're not using (autosaveName) that sounds like it persists some information about the `NSStatusItem` at the bottom of our menu items:

> A unique name for saving and restoring information about a status item.

I'm hoping this might include some sort of position info when the user manually positions the status item by command clicking and dragging it; I'll see about adding a method in the next couple days to set this property so we can see if it gives us at least an indirect way to adjust positioning.

**Comment by rsefer** [comment]
I've done a poor job explaining my issue and I think I threw things off by mentioning Priority. My apologies. Maybe I’m being redundant but I figure it may help if I try again, so here goes.

The issue I am having is related to the ordering of menu bar items _with regard to the order in which they are initiated via Hammerspoon_. Let’s say I had a completely blank menu bar but wanted to add my first:

```lua
FirstMenubar = hs.menubar.new():setTitle(“First”)
```

My menubar would look like this:

[First]

If I added another one: (`SecondMenubar = hs.menubar.new():setTitle(“Second”)`) it would look like this, as macOS stacks right-to-left:

[Second] [First]

And a third (`ThirdMenubar = hs.menubar.new(“Third”)`):

[Third] [Second] [First]

...and so on. For some reason, greater than 50% of the time recently the ordering seems to be random, where the third item will be inserted between the second and the first, so it will look like this:

[Second] [Third] [First]

Or

[First] [Third] [Second]

Or any other combination imaginable. This is the case for when I load spoons that have single menubars AND for when I call multiple menubars within a single spoon.

I had (maybe incorrectly?) assumed this was a bug or change in macOS 10.15, as I had never seen the issue before the past couple of betas. I will experiment with a blank config and see if I can reproduce or possibly fix it, in which case it was user error (likely!)

Does the above make sense?

**Comment by rsefer** [comment]
Here is a strange real world example of the ordering issue interspersed with System Icons:

Hammerspoon is not running:

![image](https://user-images.githubusercontent.com/539765/66157857-4a1c7e00-e5ea-11e9-9ae0-a2e05870c4ef.png)

with the following config, Hammerspoon loads:

```lua
hs.menubar.new():setTitle('First')
hs.menubar.new():setTitle('Second')
hs.menubar.new():setTitle('Third')
```

![image](https://user-images.githubusercontent.com/539765/66157907-5f91a800-e5ea-11e9-8134-9f46c1234ac6.png)

**Comment by rsefer** [comment]
And another with a spoon loading. I would expect the following:

[Left] [Center] [Right] [Third] [Second] [First] [...all of the system icons...]. With this config:

init.lua:
```lua
hs.menubar.new():setTitle('First')
hs.menubar.new():setTitle('Second')
hs.menubar.new():setTitle('Third')
hs.loadSpoon('Sample')
```
Sample spoon:
```lua
--- === Sample ===
local obj = {}
obj.__index = obj
obj.name = "Sample"

hs.menubar.new():setTitle('Right')
hs.menubar.new():setTitle('Center')
hs.menubar.new():setTitle('Left')

return obj

```

but instead I'm getting results like these:

![image](https://user-images.githubusercontent.com/539765/66158218-0f671580-e5eb-11e9-92dc-25d696318995.png)

and doing hacky things like delaying doesn't seem to make a difference:
```lua
--- === Sample ===
local obj = {}
obj.__index = obj
obj.name = "Sample"

hs.menubar.new():setTitle('Right')
hs.timer.doAfter(2, function()
	hs.menubar.new():setTitle('Center')
	hs.timer.doAfter(2, function()
		hs.menubar.new():setTitle('Left')
	end)
end)

return obj
```

![image](https://user-images.githubusercontent.com/539765/66158483-97e5b600-e5eb-11e9-81e3-c1c626ee41a7.png)

**Comment by asmagill** [comment]
Ok, well that blew the idea I was just about to post out of the water... I'm not running Catalina yet, but I'll install it on my desktop this weekend and see what, if anything, I can uncover... I do have another module for creating menu items that does things in an entirely different manner, but it breaks backwards compatibility (even with a legacy wrapper, it's only about 90% backwards compatible), so I've been saving it for version 2 of Hammerspoon (which, last I heard, was on the table for next year) If there is a difference between the two, maybe my new approach gets moved up.

**Comment by rsefer** [comment]
@asmagill thanks for the info! Strange issue indeed. If I come up with a hacky workaround, I'll leave that here

**Comment by rsefer** [comment]
![image](https://user-images.githubusercontent.com/539765/66159070-da5bc280-e5ec-11e9-9e95-e4619ea52b85.png)

¯\_(ツ)_/¯
