### ISSUE TITLE
Autoclicker stops clicking after a while

### ISSUE THREAD

**Issue by ideaman924** [Hammerspoon/hammerspoon#2198]
Hi all! I have an autoclicker script that will enable when I press a hotkey, and continue right-clicking until I disable it with a different hotkey. The script is:

```
enableAutoClick = false
-- Seconds to delay before next click. 0.001 works OK.
speedDelay = 0.005

function mouseRightClick()
    -- Run right mouseclick
    hs.eventtap.rightClick(hs.mouse.getAbsolutePosition())
end

function isAutoClickerEnabled()
    return enableAutoClick
end

function setupClicker()
    -- Set continuous run to true
    enableAutoClick = true
    print("Enabled autoclicker")

    hs.timer.doWhile(isAutoClickerEnabled, mouseRightClick, speedDelay)
    
end

function stopClicker()
    -- Stop autoclicker
    enableAutoClick = false
end

function sleep(n)
    local t = os.clock()
    while os.clock() - t <= n do
      -- nothing
    end
end

hs.hotkey.bind({"cmd","alt","shift"}, "A", setupClicker)
hs.hotkey.bind({"cmd","alt","shift"}, "D", stopClicker)
```

The problem is after running for about a minute or so the script suddenly stops working. No right-clicks. I can try and revive the script by pressing on the Command key, which makes it start up again sometimes. When that doesn't work, I have to halt the script by pressing ⌘⌥⇧D, and then resume by pressing ⌘⌥⇧A.

Am I running into some internal limitation?

**Comment by latenitefilms** [comment]
Try capturing the timer in a global variable:

```lua
myTimer = hs.timer.doWhile(isAutoClickerEnabled, mouseRightClick, speedDelay)
```

See: http://www.hammerspoon.org/go/#variablelife

**Comment by cmsj** [comment]
I'm going to close this, because I believe @latenitefilms 's answer will solve your problem. Please feel free to re-open if that isn't the case :)
