### ISSUE TITLE
match native screenshot functionality?

### ISSUE THREAD

**Issue by psifertex** [Hammerspoon/hammerspoon#2199]
I'm trying to automate a bunch of screenshots unfortunately I'm trying to match the native drop-shadow the built in MacOS screenshot does. It looks like the hammerspoon screenshot APIs do their own image grab of the screen which doesn't produce the same effect if I use `hs.window.focusedWindow():snapshot():saveToFile(fileName)`.

Is there a way to automate getting a screenshot as if I'd done CMD-SHIFT-4, SPACE, then clicked the foreground window?

**Comment by MooseV2** [comment]
Use the [builtin](https://ss64.com/osx/screencapture.html) `screencapture` command; specifically with the `-l<windowid>` flag.

You can get the window id with `hs.window():id()`

**Comment by psifertex** [comment]
Excellent, thanks! If anyone else stumbles across this, here's what I'm currently doing:

```
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "4", function()
    local timeStamp = string.gsub(os.date("%Y-%m-%d_%T"), ":", ".")
    local fileName = os.getenv("HOME") .. "/Desktop/ss-" .. timeStamp .. ".png"
    local windowId = hs.window.frontmostWindow():id()
    hs.task.new("/usr/sbin/screencapture", nil, {"-l" .. windowId, fileName }):start()
end)
```

**Comment by Write** [comment]
I wanted to select a region manually and the capture to go to the clipboard.

```
function printScreenRegion()
    hs.task.new("/usr/sbin/screencapture", nil, {"-ic"}):start()
end
```

**Comment by muescha** [comment]
For your reference, there is also an available Seal Plugin with comparable functionality:

https://github.com/Hammerspoon/Spoons/blob/master/Source/Seal.spoon/seal_screencapture.lua#L8
