### ISSUE TITLE
API deprecation

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#22]
Allow modules to notify Hammerspoon if a user is using a call that will go away in a future version. Then we can show all of these warnings in a single place in the prefs.

**Comment by JosephFerano** [comment]
Maybe we should consider putting a disclaimer in the README saying that this is alpha software? We could potentially skip that step if we do so, considering how there's a lot of API calls that I want to change, mainly in grid and mjomatic.

**Comment by cmsj** [comment]
fwiw, we're trying to use Semantic Versioning, which means that since we're <1.0, we can do whatever we like ;)

**Comment by cmsj** [comment]
I'm wondering what we can actually usefully do with the knowledge that a particular extension is using deprecated APIs. It's not like the user can do anything about it other than avoid using those APIs.

That would suggest that we should just not ship any deprecated APIs at all, but I'm not sure we actually want to do that.

So... I propose we skip this until we actually face the issue of a new OSX release removing an API that was previously deprecated. At that point we'd either have to drop old release support entirely, or start introducing multiple code paths in affected modules, and weakly linking with various new/old frameworks.

Re-open if you disagree :D
