### ISSUE TITLE
Can't fill screen completely.

### ISSUE THREAD

**Issue by robinhoodexe** [Hammerspoon/hammerspoon#220]
I'm having a small problem about the way Hammerspoon moves windows. I use this function in my ``init.lua``:

```lua
local cmdshift = {"cmd", "shift"}

hs.hotkey.bind(cmdshift, "M", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()

  f.x = max.x
  f.y = max.y
  f.w = max.w 
  f.h = max.h
  win:setFrame(f)
end)
```

Plus a function that resizes the window to half of the screen width and moves it to left or right. When used, it looks like this:

![screen shot 2015-02-17 at 17 59 28](https://cloud.githubusercontent.com/assets/6505938/6232795/c35df47e-b6ce-11e4-8be2-3762b6d3838d.png)
Now, why is there a small space at the bottom? I assume it's related to the dock (which I have on autohide), but why can't hammerspoon fill that, since it's possible to manually move a window past the "invisible line" although one cannot manually resize it beyond the limit.

Related issue I had with Mjolnir: https://github.com/BrianGilbert/mjolnir.bg.grid/issues/4

**Comment by cmsj** [comment]
It's because hs.screen:frame() returns a frame that excludes the menubar and dock :)

If you grab both hs.screen:frame() and hs.screen:fullFrame() you should be able to figure avoid the menubar at the top of the screen, and ignore the dock space at the bottom.

**Comment by 0942v8653** [comment]
@cmsj: that doesn't actually work. It's not Hammerspoon's fault, though; the Accessibility API actually prevents you from resizing a window into those 4 pixels.

**Comment by cmsj** [comment]
Well that's disappointing, but thanks for the detail!

**Comment by Willamin** [comment]
The 4px margin is on whichever side of the screen the dock is. For me, it's on the left.
```
r = mywindow:size()
r.w = r.w+4
mywindow:setSize(r)
mywindow:move(hs.geometry.point(-4,0))
```
That will stretch `mywindow` into the special dock margin. A similar trick can be done for other dock positions.

**Comment by andrewwillette** [comment]
I solved this issue by setting the margins to 0.

```lua
grid.setMargins({ x = 0, y = 0 })
```
