### ISSUE TITLE
Repo detritus after build

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#2200]
Sometime recently, I noticed that after I build HS from source there is now a modified file that git complains about: `Hammerspoon/Hammerspoon-Info.plist`.

This detritus also fails to be deleted by `make clean`.

Can that file be made to be cleaned up by `make clean`, or at the very least be made untracked and added to the .gitignore?

**Comment by chdiza** [comment]
I noticed this just now, after doing my first `git pull` in a few days but *prior* to building.   The `pull` failed because it said I had modified files laying around.  I had to do a `reset --hard HEAD` before I could re-pull.

Then the file reappeared after I built.

**Comment by latenitefilms** [comment]
I think this is because of:

https://github.com/Hammerspoon/hammerspoon/commit/5b3303ed1c43b2ae5203ed9f4374c29c052ef78e

The build number is now synced to the number of commits in the GitHub branch.

**Comment by cmsj** [comment]
As of 3b26711b03a3f060268625d11347f332545509c5 this should be fixed. I'm now only auto-incrementing the build number if a signing token is present.

**Comment by chdiza** [comment]
Thanks!
