### ISSUE TITLE
hs.timer only executes a few times, if any

### ISSUE THREAD

**Issue by voldemortensen** [Hammerspoon/hammerspoon#2202]
I just updated to 0.9.76 (5104) and one of my spoons has stopped working properly. Relevant code is here: https://github.com/voldemortensen/SpotifyMagic.spoon/blob/master/init.lua#L27

The hs.timer won't fire until I call `:fire()` manually. At that point it may or may not execute a few times before stopping. I've tried logging everything I can and don't see any errors anywhere. The alt+cmd+C hotkey still works, which is basically the same code, just triggered with a hotkey.

Not sure where to look to provide more helpful info.

**Comment by Habbie** [comment]
You're not saving the timer object, so eventually it will get garbage collected, possibly even 'very soon'. Store the return value in a variable to keep it alive. The same goes for `hs.hotkey.bind` right after it, etc.

**Comment by voldemortensen** [comment]
Ah, that did it. I'm guessing this will also solve the issue I've had with notifications not showing after the machine wakes from sleep.

Thanks!
