### ISSUE TITLE
Request: Trigger for notifications

### ISSUE THREAD

**Issue by emale999** [Hammerspoon/hammerspoon#2203]
Would it be possible to get a trigger/watcher for all notifications (that were not sent by hammerspoon itself)?

Problem: There are some annoying notifications like "battery of mouse low", "your time machine backup is 7 days old" popping up several times a day and that you can't turn off.

Would be a great thing to catch these notifications and auto-close them with the help of hammerspoon.
Couldn't find something like this in the docs. Only to submit own notifications via hammerspoon.

**Comment by latenitefilms** [comment]
Maybe have a play around with:

http://www.hammerspoon.org/docs/hs.distributednotifications.html

**Comment by cmsj** [comment]
@emale999 unfortunately there's no macOS API that lets us detect or interact with notifications that we didn't generate.
