### ISSUE TITLE
StreamDeck button numbers changed?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2204]
@latenitefilms I think you use a StreamDeck - have the button numbers changed for you either in 0.9.76 and/or Catalina? Mine used to go 1-15 and now they seem to go 29-43?!

**Comment by latenitefilms** [comment]
I'm still on Mojave, so will check.

**Comment by latenitefilms** [comment]
@cmsj - Sorry for the delayed reply. Everything seems to be the same on Mojave 10.14.6 - Stream Deck extension is working as expected.

**Comment by latenitefilms** [comment]
Have you tried #2102 on Catalina?

**Comment by latenitefilms** [comment]
@cmsj - I haven't updated to Catalina yet personally, however, we just had a CommandPost user contact us saying that whilst their Stream Deck worked great on Mojave, after they updated to Catalina 10.15.1 it stopped working. Are you still having issues with your Stream Deck in Hammerspoon?

**Comment by mvandermeulen** [comment]
I am having issues with Stream Deck in Cataline - I use it with Keyboard Maestro(well I used to).

**Comment by latenitefilms** [comment]
@cmsj - I think this can be closed.
