### ISSUE TITLE
Console Steals Focus Momentarily with hs.chooser

### ISSUE THREAD

**Issue by roeybiran** [Hammerspoon/hammerspoon#2218]
Hello,
I have noticed that whenever the HS console is open in the background (I have it hidden in the menu bar and in the dock), and I choose a given row in a hs.chooser panel, the console window pops up and gains focus for a brief moment. Then it relinquishes focus back to the previously active app. I find this behavior undesired.

This issue does not occur if the chooser was dismissed without a choice.

Steps to reproduce:
1. Set the console to hidden in the menu bar and in the dock
2. Open the console, switch to a different app
3. Run a script that calls the chooser, and choose something

Thanks to anyone involved in this amazing project!

![gif](https://user-images.githubusercontent.com/37002381/67573995-450ea280-f742-11e9-852d-4583c267b016.gif)

**Comment by latenitefilms** [comment]
This will hopefully eventually be solved in #2078.

**Comment by roeybiran** [comment]
I see. Hoping for that as well. Thanks!
