### ISSUE TITLE
Hammerspoon “Freezes” After a While

### ISSUE THREAD

**Issue by roeybiran** [Hammerspoon/hammerspoon#2219]
Hello,
I’ve noticed that after a certain period of time (the duration of which fluctuates greatly) of using Hammerspoon it, in a sense, “freezes”. The extent of this problem also varies from time to time:

1. There are times when it seems like HS is completely stuck. And all of my registered hotkeys become unresponsive. I can open the console, but it prints nothing (normally it prints quite a lot of info). Hotkeys registered for the HS window itself do not respond as well, and the only way to mitigate this is to restart HS.

2. Other times, the problem manifests itself a bit differently:
My setup relies heavily on application-specific modals, which are loaded on init. A given modal becomes the active one (`enter()` is called) when its respective app also become active. Accordingly, `exit()` is called on a modal when its app deactivates.
When this issue happens, some hotkeys that belong to a specific modal are not disabled even when that modal has, supposedly, exited. Here's an example that involves Script Debugger and the ⌘+D keys, but unfortunately this happens with many other apps and different kinds of hotkeys and scripts:
I have a modal for Script Debugger that binds ⌘D to escape if a certain UI element has a certain attribute. After switching to different app like Finder and pressing ⌘D to duplicate a file, (a native shortcut) nothing happens. I open the console and I see that ⌘D is still active as a hotkey that triggers a Script Debugger script, and it produces an error since obviously the Script Debugger UI element it relies on isn’t available anymore. This of course renders ⌘D useless for both its “original” app and the current one. This happens even if Script Debugger was terminated a long time ago and many apps gained and lost focus since.

What’s interesting about this is that Hammerspoon continues to work in other ways — the application watcher still operates and enters/exits modals as it should, and the console continues to print messages.

Sadly, I have no idea how to reproduce this issue. It always catches me by surprise, without me doing anything special and again, after an unspecified amount of time.
P. S. - if there’s a way to debug this and check what’s happening under the hood, I would love to know how to do it (I have zero knowledge in debugging Hammerspoon, and/or Lua in general).

Thanks in advance!

**Comment by jokajak** [comment]
I have no idea how to debug this or fix but a quality of life improvement might be to add a cleanup timer that ensures all of the modals are in the correct state based on the currently running application/system state. That way you could trigger the cleanup for each of the modals. If things are still wonky you could destroy/create them as necessary.

**Comment by latenitefilms** [comment]
Could you share your config?

My guess is something is blocking something somewhere along the lines.

**Comment by roeybiran** [comment]
Thanks for the replies.

@jokajak, how do I do that? (the cleanup function, specifically)

@latenitefilms, sure thing. My config is [here](https://github.com/roeybiran/.hammerspoon), but to keep this simple, here’s an excerpt from the config that might be related to the issue:
1. Each application has its own .lua file. They all reside in a folder and each file contains a table with keys that contain the app’s bundle identifier, its modal, associated scripts etc. On HS’ launch, I iterate over the folder and `require()` the .lua files, with each app’s object inserted into a table.
Here’s an example for this structure, used throughout my config:
```
local hotkey = require('hs.hotkey')
local ax = require("hs._asm.axuielement")
local ui = require("util.ui")

local m = {}

m.id = 'com.apple.ActivityMonitor'
m.thisApp = nil
m.modal = hotkey.modal.new()
m.modal:bind({'cmd'}, 'delete', function() m.thisApp:selectMenuItem({'View', 'Quit Process'}) end)
return m
```
2. I have a `hs.application.watcher` that monitors apps as they activate and deactivate. On each run of the watcher’s callback, I iterate over the previously mentioned table (that contains the application-specific tables). If there’s a match between the bundle id of the app that triggered the app watcher callback and the bundle id stored in the app-specific table, the app’s modal object is entered or exited, depending on the type of the app event.
Here’ the app watcher callback:
```
local function handleGlobalAppEvent(appName, event, appObj)
    if (event == application.watcher.activated) then
        toggleApplicationEnvironment("on", appObj)
    elseif (event == application.watcher.deactivated) then
        toggleApplicationEnvironment("off", appObj)
    end
end
```
And here’s the ` toggleApplicationEnvironment` function:
```
local function toggleApplicationEnvironment(argForModalSwitch, hsAppObj)
    local id
    if not hsAppObj then
        -- if called on init, hsAppObj is nil
        -- if called from appWatcher, hsAppObj is a sent argument
        hsAppObj = application.frontmostApplication()
    end
    id = hsAppObj:bundleID()
    for _, appEnv in ipairs(appEnvs) do
        if appEnv.id == id then
            if argForModalSwitch == "on" then
                appEnv.thisApp = hsAppObj
                if appEnv.modal then
                    appEnv.modal:enter()
                    print("active modal is now: "..appEnv.id)
                end
                if appEnv.listeners then
                    for _ ,v in ipairs(appEnv.listeners) do
                        v:start()
                    end
                end
            elseif argForModalSwitch == "off" then
                if appEnv.modal then
                    appEnv.modal:exit()
                end
                if appEnv.listeners then
                    for _ ,v in ipairs(appEnv.listeners) do
                        v:stop()
                    end
                end
            end
        end
    end
end
```
Again, `appEnvs` is table containing lots of sub-tables similar to the one described above for Activity Monitor. As you can see, I make sure to call `exit()` on the modals, and it works — only partially!

Moreover, `thisApp` is a key that should contain the `hs.application` object, without it no script would work. When an application gains focus, its `hs.application` instance is “injected” to its respective table. I did this with the notion that this may reduce overhead by avoiding calls to `hs.application()` in every function that requires it (and there are many).

If I manage to solve this, I hope it will somehow solve the other, total-freeze problem.

**Comment by jokajak** [comment]
I'm not sure what's causing it but you could modify toggleApplicationEnvironment to turn off all the other appEnvs. This way you have a double disable of the hotkey in case the exit event doesn't fire.
If you want to get more information on what order of events is happening you could add a log message for the enter/exit events.

Just spitballing more, you could define a appEnv.modal.entered and appEnv.modal.exited that disabled the other modals and logged the event.

**Comment by roeybiran** [comment]
Thanks for the replies everyone —  I believe I was able to solve this issue, which was probably all due to a wrong implementation of the application watcher callback — many app terminations were not fully  ‘catched’ by the HS, omitting the exiting app’s bundle id, data which is critical to this setup. This is what caused the mess.

Now the code is modified to handle solely the activation event (event #5). The code loops over the table that contains the app modals, and calls `exit()` (even if it isn’t currently active) and every modal whose associated bundle id doesn’t match that of the app that has just activated.

Here’s the revised code:
```
-- app watcher callBack
local function appWatcherCallbackFn(_, event, appObj)
  if (event == application.watcher.activated) then
    -- BEGIN HEBREW-RELATED
    forceABC.keepState(appObj)
    -- END HEBREW-RELATED
    local id = appObj:bundleID()
    -- print("Active app is now "..id)
    for _, appEnv in ipairs(appEnvs) do
      local modal = appEnv.modal
      local listeners = appEnv.listeners
      if appEnv.id == id then
        appEnv.thisApp = appObj
        if modal then
          modal:enter()
        end
        if listeners then
          for _, listener in ipairs(listeners) do
            listener:start()
          end
        end
      else
        if modal then
          modal:exit()
        end
        if listeners then
          for _, listener in ipairs(listeners) do
            listener:stop()
          end
        end
      end
    end
  end
end
```
