### ISSUE TITLE
Feature request: Change resolution from Hammerspoon

### ISSUE THREAD

**Issue by kbadk** [Hammerspoon/hammerspoon#222]
I'd be neat if you programatically could change screen resolution using Hammerspoon. I imagine some could be reused from http://github.com/jhford/screenresolution/, even though `screenresolution` doesn't support scaled/Retina resolutions.

**Comment by cmsj** [comment]
fwiw, https://github.com/robbertkl/ResolutionMenu/blob/master/Resolution%20Menu/DisplayModeMenuItem.m was also very helpful here. The jhford link uses the public CoreGraphics APIs for changing modes, but unfortunately they do not support HiDPI (e.g. Retina) modes, so we are having to use a private CoreGraphics API, which may need further work in future OS X releases.
