### ISSUE TITLE
hs.application("app") randomly kills my hs.menubar

### ISSUE THREAD

**Issue by sisoe24** [Hammerspoon/hammerspoon#2221]
**OS**: macOS Mojave 10.14.6 18G103 x86_64
**Hammerspoon**: 0.9.76 

I have a script that periodically launches and/or kills an application and checks if is hidden. But every now and then all of my Hammerspoons menubar scripts disappear.   
I found out that calling `hs.application("someapp")` was the culprit and also that stops the `hs.pathwatcher()`. there is no error message/notification on the console.

I am able to recreate the problem every time, even on an empty `init` file and empty menus:
```lua
-- empty init.lua
local menu1 = hs.menubar.new()
menu1:setTitle("menu1")

local menu1_opt = {
  {title = "menu1"}
}

if menu1 then
  menu1:setMenu(menu1_opt)
end
```
then calling `hs.application("someapp") ` there is a random chance that it kills the menubar objects. I could do it from the console, with a shortcut or with a `hs.timer` event.

Sometimes it happens at the first try and sometimes after a while but it always does (when is just the empty `init` file it does take longer). 

![menubar](https://user-images.githubusercontent.com/28490646/67610920-feca3b00-f763-11e9-873a-3db7aebc38d7.gif)

Excluding the QuickTime stop button, the first 3 icons are my Hammerspoon scripts. It kills the first 2 but not the third one (the Spotify icon) because, as a noob, I am creating the menu twice (since I don't know how get the checked toggle value if the menu is pressed). So the button is calling a function that rewrites the menu and for some reason it doesn't get deleted (supposedly because the scope of the menu is inside the function).

```lua
local menu1 = hs.menubar.new()
menu1:setTitle("menu1")

local function enableCheck(keyMod, caller)
  local menu_state = caller.state

  if menu_state == "off" then
    menu_state = "on"
  elseif menu_state == "on" then
    menu_state = "off"
  end

  local menu1_opt = {
    {title = "menu1", fn = enableCheck, state = menu_state}
  }

  -- if I comment out this section then this menu also disappears
  if menu1 then
    menu1:setMenu(menu1_opt)
  end

end

local menu1_opt = {
  {title = "menu1", fn = enableCheck, state = "off"}
}

if menu1 then
  menu1:setMenu(menu1_opt)
end
```

**Comment by latenitefilms** [comment]
Try capturing the `hs.menubar` in a global (`menu = hs.menubar.new()`) and see if that makes any difference.

Sound like a garbage collection issue:

http://www.hammerspoon.org/go/#variablelife

**Comment by sisoe24** [comment]
> Try capturing the `hs.menubar` in a global (`menu = hs.menubar.new()`) and see if that makes any difference.
> 
> Sound like a garbage collection issue:
> 
> http://www.hammerspoon.org/go/#variablelife

yes making it global works

**Comment by latenitefilms** [comment]
Great news! Please close this issue unless you have any further questions. Thanks!
