### ISSUE TITLE
Add a non-blocking variant of hs.image.imageFromURL

### ISSUE THREAD

**Issue by andweeb** [Hammerspoon/hammerspoon#2224]
My use case in particular falls within the context of `hs.chooser` choices, each choice item needing an icon image from an external URL as shown in the gif below.

![test](https://user-images.githubusercontent.com/10726590/67921737-f314b500-fb65-11e9-8471-d7129fc17886.gif)

Due to the blocking nature of `hs.image.imageFromURL`, using it blocks not only the chooser modal itself but the entire application in general, which isn't a great experience. For example attempting to load http://deelay.me/20000/https://i.imgur.com/2lrs7zF.jpg (simulated delay of 20s) blocks the whole app for the full 20 seconds.

It'd be awesome if there were a way to fetch images from URLs without blocking the main application thread.

**Comment by latenitefilms** [comment]
@andweeb - I've added an optional callback in #2227. Let me know if that works as you intended.

**Comment by andweeb** [comment]
Wow thanks so much for the help! I'll try that as soon as I have time today and report back. :)

**Comment by idr4n** [comment]
> Wow thanks so much for the help! I'll try that as soon as I have time today and report back. :)
> 
> Edit: Works perfectly, thank you!

Do you guys mind to tell me how to use the callback in this case so I can get the icons of the URL asynchronously?

Basically, I'm pulling the tabs from Safari and their URL's into a chooser, pretty much looks like the gif above. As mentioned by @andweeb, user experience is not great if using `hs.image.imageFromURL` without a callback. However, as mentioned in the docs, when using the callback, the function returns `nil` right away, and so the images don't show when I trigger the chooser.

This is a sample code of the chooser:

```lua
tabs_chooser:choices(function()
	local _, result = hs.osascript.applescript(tabsScript)
	local lines = {}
	for line in string.gmatch(result, "(.-)\n") do
		table.insert(lines, line)
	end
	local tabs = {}
	for _, tab in pairs(lines) do
		local winID, tabNumber, tabTitle, url = string.match(tab, "(.*);(.*);(.*);(.*)")
		-- local img = hs.image.imageFromURL("https://www.google.com/s2/favicons?sz=64&domain=" .. url)
		local img = hs.image.imageFromURL("https://www.google.com/s2/favicons?sz=64&domain=" .. url, function() end)
		table.insert(tabs, {
			["text"] = tabTitle,
			["subText"] = url,
			["win"] = winID,
			["tab"] = tabNumber,
			["image"] = img,
		})
	end
	return tabs
end)

hs.hotkey.bind("alt", "'", function()
	tabs_chooser:refreshChoicesCallback(true)
	tabs_chooser:show()
end)
```

Thanks in advance!

**Comment by latenitefilms** [comment]
Here's an example:

```lua
print("before")
hs.image.imageFromURL("https://latenitefilms.com/media/2013/09/latenitefilms_text.png", function(img)
    print(string.format("Here's your image: %s", img))
end)
print("after")
```

This will output:

```lua
2022-08-05 11:50:09: before
2022-08-05 11:50:09: after
2022-08-05 11:50:09: Here's your image: hs.image:  (0x600000b9ddb8)
```

Callback's obviously happen asynchronously, so you'd need to update your chooser results AFTER the image callback is triggered.

**Comment by idr4n** [comment]
Thanks for your reply @latenitefilms. OK, so I can use the fetched image in the callback as a parameter. Great! However, how can I update the chooser results while the chooser is visible (i.e, after being triggered with `chooser:show()`)?
