### ISSUE TITLE
Add Spotlight-like Information Panel to hs.chooser

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2231]
I'm thinking something along the lines of:

![Chooser Example](https://user-images.githubusercontent.com/22286696/68290485-22826f00-00dc-11ea-8bd6-af747a95d288.jpg)

**Comment by cmsj** [comment]
Yes, I want to be able to do this very much, but I first need to figure out how to have parts of the UI hide, without it breaking the layout.

**Comment by latenitefilms** [comment]
Can you not just dynamically adjust the Table Column?

**Comment by latenitefilms** [comment]
Xcode actually has a really nice design too:

<img width="727" alt="Screen Shot 2019-11-06 at 9 45 45 pm" src="https://user-images.githubusercontent.com/22286696/68291852-d4bb3600-00de-11ea-8638-a0f2513f5f18.png">

**Comment by latenitefilms** [comment]
One option for ultimate customisability would be to just have the "panel" as a webview, then you could put whatever you wanted in there?

**Comment by latenitefilms** [comment]
Whilst I'd love to tackle this one day, I don't have the time/skill currently, so I'm going to close this issue for now. Feel free to re-open.
