### ISSUE TITLE
Hammerspoon no more able to send keystroke to applications with Catalina upgrade

### ISSUE THREAD

**Issue by jthebert** [Hammerspoon/hammerspoon#2236]
MacOS Catalina 10.15.1
Hammerspoon: Version 0.9.76 (5104)
hammerspoon has been added to the "Security and confidentiality" settings. 

The following function used to work before the upgrade to catalina (was using mojave): 
```lua
hs.hotkey.bind(hyper, '$', function()
	hs.eventtap.keyStrokes(os.date("%Y-%m-%d", os.time()) .. " JTH: " )
end)
```
I tried as well keystroke() on top of keystrokes(), but still no characters added in the window (and I'm sure the function is called as the print() are visible in the console)
```lua
hs.hotkey.bind(hyper, '$', function()
    print("Sending keystrokes")
	hs.eventtap.keyStrokes(os.date("%Y-%m-%d", os.time()) .. " JTH: ")
	print("Sending keystroke")
	hs.eventtap.keyStroke({}, "a")
	print("Leaving keystroke")
end)
```
It seems hammerspoon does not have the right to send keystroke anymore (but no errors are reported)

**Comment by cmsj** [comment]
Apologies for the slow reply...

I can't reproduce this, it does work for me on Catalina. Which sections of the Security & Privacy preferences is Hammerspoon listed in?

**Comment by latenitefilms** [comment]
Try closing Hammerspoon, then execute this in Terminal:

```
tccutil reset All org.hammerspoon.Hammerspoon
```

This will reset all the Hammerspoon Security & Privacy preferences (it only works on Catalina - `tccutil` is broken on Mojave). Then restart Hammerspoon, enable all the permissions and fingers crossed everything works again.

**Comment by jthebert** [comment]
Thanks for your feedback. 

I made 2 things:
* tcutil command as requested above and enabled all the permissions
* updated to latest version 

And it works now. 

So I don't if the problem was with the permissions or the version. 
I close this issue. 

Anyway thanks for your great work

Jérôme.
