### ISSUE TITLE
Calling hs.application.open after hs.application.get returns nil even if the application is launched

### ISSUE THREAD

**Issue by bchris86** [Hammerspoon/hammerspoon#2240]
While I know I need a check to see if app is nil or not, the following code is a barebones example of what I was trying to do
```
hs.hotkey.bind(hotkeyCombination, 'i', function()
	local app
	-- Terminal must not be open for this code to error out
	app = hs.application.get('Terminal')
	app = hs.application.open('Terminal', 15, true)
	-- app = nil at this point, after Hammerspoon hangs for 15 seconds due to the wait value, even if the application launches
	-- The :maximize() line below will throw an error in the console for attempting to index a nil value.
	app:focusedWindow():maximize()
end)
```

What I'd like to do is create a hotkey to switch to an application if it's open, and if it's not open, open it and then maximize it. Obviously the above code would have several if-then statements, but this is just an example to highlight the issue.

Any suggestions on how I can get this to work?

**Comment by andweeb** [comment]
I feel like the `hs.application` API would really benefit from a treatment similar to the solution that resolved #2224.

An optional callback argument could similarly be added to the `hs.application:open` method (or in an entirely new method) to invoke a callback after the application is launched or activated.

My current workaround is to simply not use the `wait` parameter and trigger my hotkey twice (once to launch, second to apply an action). Not really ideal. :(

**Comment by latenitefilms** [comment]
@bchris86 - Maybe something like this will give you some ideas?

```lua
local application = require("hs.application")
local timer = require ("hs.timer")

local checkTimerTimeoutCounter = 0
checkTimer = timer.new(0.1, function()
    if checkTimerTimeoutCounter == 10 then
        checkTimer:stop()
        checkTimerTimeoutCounter = 0
        return
    end
    local apps = application.applicationsForBundleID("com.apple.Terminal")
    local terminal = apps and apps[1]
    if terminal then        
        if terminal:activate() then 
            local focusedWindow = terminal:focusedWindow()
            if focusedWindow then
                focusedWindow:maximize()
                checkTimer:stop()
                checkTimerTimeoutCounter = 0
                return
            else            
                -- Terminal is activated, but there's no windows:
                terminal:selectMenuItem({"Shell", "New Window", "Basic"})
            end
        end
    end
    checkTimerTimeoutCounter = checkTimerTimeoutCounter + 1
end)

hs.hotkey.bind({"control", "option", "command"}, "q", function()
    local apps = application.applicationsForBundleID("com.apple.Terminal")
    local terminal = apps and apps[1]
    if terminal then
        checkTimer:start()
        return
    else
        if application.launchOrFocusByBundleID("com.apple.Terminal") then
            checkTimer:start()
            return
        end
    end
end)
```

**Comment by cmsj** [comment]
I think for right now the best option here would be to use hs.application.watcher to react to when the application is launched.

**Comment by kassi** [comment]
@cmsj unfortunately, hs.application.watcher event "launched" (1), which is the last event occuring (sequence, 0, 5, 1), delivers an app object without any windows.
app:focusedWindow() == nil
app:allWindows() == {}
And there's no window watcher I could start right after.
Seems to be an issue still to do it properly.
