### ISSUE TITLE
Register callback functions for arbitrary schemes in urlevent

### ISSUE THREAD

**Issue by dresken** [Hammerspoon/hammerspoon#2245]
I was trying to get Hammerspoon to handle a particular scheme - but doesn't look to be supported

I believe it really only needs something similar to the current "bind" set up for the hammerspoon in /extensions/urlevent/init.lua - but I am only really guessing:

ie 
function urlevent.bindScheme(scheme, callback)
    urlevent.setDefaultHandler(scheme)
    schemeCallbacks[scheme] = callback
end

local function urlEventCallback(scheme, event, params, fullURL)
....
elseif (schemeCallbacks[scheme]) then
            local ok, err = xpcall(function() return schemeCallbacks[scheme](event, params) end, debug.traceback)
            if not ok then
                hs.showError(err)
            end
else
        log.ef("Hammerspoon has been passed a %s URL, but does not know how to handle it", scheme)
....

**Comment by cmsj** [comment]
Unfortunately we can't bind to URL schemes purely at runtime - we have to specify all of the ones we might bind to, in the app's Info.plist at build time. I'm happy to add any reasonable schemes that people want to use, but I don't believe there is any way to open it up to any possible URL scheme. Sorry!

**Comment by dresken** [comment]
Well I've added arbitrary ones and I just get the message: "Hammerspoon has been passed a scheme URL, but does not know how to handle it" - so it is simply a self impose limit in that case
