### ISSUE TITLE
Disabling “hotkey: Enabled/Re-enabled/Disabled hotkey…” console messages 

### ISSUE THREAD

**Issue by roeybiran** [Hammerspoon/hammerspoon#2246]
Hello,
The HS console constantly prints messages related to `hs.hotkey`. Some are shown upon launch, some when I switch apps.
 
Here is a screenshot:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/37002381/69815421-f2bc1800-11fe-11ea-8967-690c32206785.png">
Is there any way to disable those? I’ve looked through the docs but couldn’t find anything.

Basically, I would like the console to print nothing but **errors, warnings, lazily-loaded modules**, and stuff I’ve **explicitly** chosen to print out.

Thanks!

**Comment by latenitefilms** [comment]
Try: `hs.hotkey.setLogLevel("error")`. 

See: http://www.hammerspoon.org/docs/hs.logger.html#setLogLevel

**Comment by latenitefilms** [comment]
You can also globally define the logger level using:

`[hs.logger.defaultLogLevel](http://www.hammerspoon.org/docs/hs.logger.html#defaultLogLevel)`

**Comment by roeybiran** [comment]
Brilliant! That did the trick. Thanks!

Since the `setLogLevel` method doesn’t appear in the `hs.hotkey` docs, I can assume every module has its own `hs.logger` instance?

Thanks again.

**Comment by cmsj** [comment]
@roeybiran it's not a completely valid assumption, I think we have some things that still don't use `hs.logger`, but it's a fairly safe assumption (and bugs would be welcome for things that aren't using it!)

**Comment by roeybiran** [comment]
Will do. Thanks a lot!
