### ISSUE TITLE
hs.layout apply crash

### ISSUE THREAD

**Issue by deepumukundan** [Hammerspoon/hammerspoon#225]
I get this wierd error when the layout tries to switch between single and multi monitors. I have the init.lua tweaked from @cmsj 's sample
-------------------------------------------------------------------------------------------------------------------------------------------
...oon.app/Contents/Resources/extensions/hs/layout/init.lua:147: bad argument #1 to 'setTopLeft' (table expected, got nil)
stack traceback:
	[C]: in function 'setTopLeft'
	...oon.app/Contents/Resources/extensions/hs/layout/init.lua:147: in function 'apply'
-------------------------------------------------------------------------------------------------------------------------------------------
Here is the part of my init.lua which specified layouts.

local display_laptop = hs.screen.allScreens()[1]
local display_middle = hs.screen.allScreens()[2]
local display_left = hs.screen.allScreens()[3]

local internal_display = {
    {"iTerm",             nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Mail", 			  nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Microsoft Outlook", nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Google Chrome",     nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"TextWrangler",      nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Atom",              nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"HipChat",           nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"SourceTree",        nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Calendar",          nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Evernote",          nil,          display_laptop, hs.layout.maximized, nil, nil},
    {"Spotify",           nil,          display_laptop, hs.layout.maximized, nil, nil},    
    {"iTunes",            "iTunes",     display_laptop, hs.layout.maximized, nil, nil},
    {"iTunes",            "MiniPlayer", display_laptop, nil,                 nil, hs.geometry.rect(575, -45, 215, 45)},
    {"Finder",            nil,          display_laptop, hs.layout.maximized, nil, nil},
}

local triple_display = {
    {"iTerm",             nil,          display_left,    hs.layout.left50,    nil, nil},
    {"Mail", 			  nil,          display_left,    hs.layout.right50,   nil, nil},
    {"Microsoft Outlook", nil,          display_left,    hs.layout.right50,   nil, nil},
    {"Google Chrome",     nil,          display_middle,  hs.layout.maximized, nil, nil},
    {"TextWrangler",      nil,          display_middle,  hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_middle,  hs.layout.maximized, nil, nil},
    {"Atom",              nil,          display_laptop,  hs.layout.maximized, nil, nil},
    {"HipChat",           nil,          display_laptop,  hs.layout.maximized, nil, nil},
    {"SourceTree",        nil,          display_laptop,  hs.layout.maximized, nil, nil},
    {"Calendar",          nil,          display_laptop,  hs.layout.maximized, nil, nil},
    {"Evernote",          nil,          display_laptop,  hs.layout.maximized, nil, nil},
    {"Spotify",           nil,          display_laptop,  hs.layout.maximized, nil, nil},    
    {"iTunes",            "iTunes",     display_laptop,  hs.layout.maximized, nil, nil},
    {"iTunes",            "MiniPlayer", display_laptop,  nil,                 nil, hs.geometry.rect(575, -45, 215, 45)},
    {"Finder",            nil,          display_laptop,  hs.layout.left50,    nil, nil},
}

And the function for screen change call back
function screensChangedCallback()
    newNumberOfScreens = #hs.screen.allScreens()

    if lastNumberOfScreens ~= newNumberOfScreens then
        if newNumberOfScreens == 1 then
            hs.layout.apply(internal_display)
        elseif newNumberOfScreens == 3 then
            hs.layout.apply(triple_display)
        end
    end

    lastNumberOfScreens = newNumberOfScreens
end

screenWatcher = hs.screen.watcher.new(screensChangedCallback)
screenWatcher:start()

**Comment by cmsj** [comment]
I'm looking into this.

Something that does jump out at me, which I hadn't really considered when we discussed adding support for hs.screen objects in hs.layout, when you filed the issue about that, is that they will change when they are disconnected/reconnected.

It's more overhead on the Lua side, but I suspect it would be worth converting display_{laptop,left,middle} from static variables, to functions, so something like:

function display_left() {
  return hs.screen.allScreens()[3]
}

and then doing this in your layout tables:

{"iTunes", "iTunes", display_left(), foo, bar, baz},

It's possible that is what is causing this issue - when your init.lua is loaded, your display_{laptop, left, middle} variables are being set, and then never changing when you plug/unplug the monitors.

**Comment by cmsj** [comment]
I've made the code a little more careful, so it at least won't spew that traceback if things are in a confused state, but I'd like to know if making the change I suggested, fixes things, to know if I need to dig further :)

**Comment by deepumukundan** [comment]
Thanks a lot for the pointers Chris. I will try this out and reply to this issue soon!

**Comment by deepumukundan** [comment]
Spot on Chris! That did indeed fix the issue. Thanks much!
Closing the issue.

**Comment by deepumukundan** [comment]
Hi Chris, this reoccured after a restart. Yesterday I had only tried plugging out the monitors and adding them back. I found out that if I restart HS after a display switching, this is resolved, but it won't be an ideal solution. 

Not that switching the display names to functions has solved it. I believe it fixed part of the issue because I know before that change the layout switching was not working for me.

**Comment by cmsj** [comment]
Can you post your init.lua please?

**Comment by deepumukundan** [comment]
Sure! Here you go. It is actually 95% same as yours. Thanks for that!

-------------------------------------------------------------------------------------------------
local windowConfigs = require "windowConfigs"

---------------------------------- Core Config -----------------------------------
-- Ensure the IPC command line client is available
hs.ipc.cliInstall()

-- Set the style of hints
-- hs.hints.fontName = "SanFranciscoDisplay-Medium"
-- hs.hints.style = "vimperator"
-- hs.fnutil.map(hs.window.visibleWindows(), ensureIsInScreenBounds) end) -- TODO - Fix this so that after arrangement windows are not extending
-- hs.hotkey.bind(hyper, ';', function() hs.fnutil.map(hs.window.visibleWindows(), hs.grid.snap) end) --TODO - Verify

----------------------------------- Variables ------------------------------------
-- Things we need to clean up at reload
local configFileWatcher = nil
local appWatcher = nil
local wifiWatcher = nil
local screenWatcher = nil

-- Define some keyboard modifier variables
-- (Node: Capslock disabled normal function and bound to cmd+alt+ctrl+shift via Seil and Karabiner)
local alt = {"⌥"}
local cmd = {"⌘"}
local hyper = {"⌘", "⌥", "⌃", "⇧"}

-- Define monitor names for layout purposes
function display_laptop() 
	return hs.screen.allScreens()[1]
end

function display_middle()
	return hs.screen.allScreens()[2]
end

function display_left()
	return hs.screen.allScreens()[3]
end

-- Defines for screen watcher
local lastNumberOfScreens = #hs.screen.allScreens()

-- Define window layouts
--   Format reminder:
--     {"App name", "Window name", "Display Name", "unitrect", "framerect", "fullframerect"},

local internal_display = {
    {"iTerm",             nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Mail", 			  nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Microsoft Outlook", nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Google Chrome",     nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"TextWrangler",      nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Atom",              nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"HipChat",           nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"SourceTree",        nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Calendar",          nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Evernote",          nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Spotify",           nil,          display_laptop(), hs.layout.maximized, nil, nil},    
    {"iTunes",            "iTunes",     display_laptop(), hs.layout.maximized, nil, nil},
    {"iTunes",            "MiniPlayer", display_laptop(), nil,                 nil, hs.geometry.rect(575, -45, 215, 45)},
    {"Finder",            nil,          display_laptop(), hs.layout.maximized, nil, nil},
}

local triple_display = {
    {"iTerm",             nil,          display_left(),    hs.layout.left50,    nil, nil},
    {"Mail", 			  nil,          display_left(),    hs.layout.right50,   nil, nil},
    {"Microsoft Outlook", nil,          display_left(),    hs.layout.right50,   nil, nil},
    {"Google Chrome",     nil,          display_middle(),  hs.layout.maximized, nil, nil},
    {"TextWrangler",      nil,          display_middle(),  hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_middle(),  hs.layout.maximized, nil, nil},
    {"Atom",              nil,          display_laptop(),  hs.layout.maximized, nil, nil},
    {"HipChat",           nil,          display_laptop(),  hs.layout.maximized, nil, nil},
    {"SourceTree",        nil,          display_laptop(),  hs.layout.maximized, nil, nil},
    {"Calendar",          nil,          display_laptop(),  hs.layout.maximized, nil, nil},
    {"Evernote",          nil,          display_laptop(),  hs.layout.maximized, nil, nil},
    {"Spotify",           nil,          display_laptop(),  hs.layout.maximized, nil, nil},    
    {"iTunes",            "iTunes",     display_laptop(),  hs.layout.maximized, nil, nil},
    {"iTunes",            "MiniPlayer", display_laptop(),  nil,                 nil, hs.geometry.rect(575, -45, 215, 45)},
    {"Finder",            nil,          display_laptop(),  hs.layout.left50,    nil, nil},
}

-------------------------------- Utility Methods ---------------------------------
-- Function to toggle an application between being the frontmost app, and being hidden
function toggle_application(_appName)
    local app = hs.appfinder.appFromName(_appName)
    if not app then
        hs.application.launchOrFocus(_appName)
        return
    end
    local mainwin = app:mainWindow()
    if mainwin == hs.window.focusedWindow() then
        mainwin:application():hide()
    else
        mainwin:application():activate(true)
        mainwin:application():unhide()
        mainwin:focus()
    end
end

-- Callback function for application events
function applicationWatcher(appName, eventType, appObject)
    if (eventType == hs.application.watcher.activated) then
        if (appName == "Finder") then
            -- Bring all Finder windows forward when one gets activated
            appObject:selectMenuItem({"Window", "Bring All to Front"})
        end
    end
end

-- Callback function for changes in screen layout
function screensChangedCallback()
    newNumberOfScreens = #hs.screen.allScreens()

    if lastNumberOfScreens ~= newNumberOfScreens then
        if newNumberOfScreens == 1 then
            hs.layout.apply(internal_display)
        elseif newNumberOfScreens == 3 then
            hs.layout.apply(triple_display)
        end
    end

    lastNumberOfScreens = newNumberOfScreens
end

-- Reload config automatically
function reloadConfig()
    configFileWatcher:stop()
    configFileWatcher = nil

    appWatcher:stop()
    appWatcher = nil

    screenWatcher:stop()
    screenWatcher = nil

    hs.reload()
end

-- Move the cursor to middle of focused application
function cursorToMiddle()
  	local win = hs.window.focusedWindow()
  	local focusedFrame = win:frame()
  	local screen = win:screen()
  	local screenFrame = screen:frame()
	
  	local c = hs.mouse.getAbsolutePosition()
	c.x = focusedFrame.w/2 + (focusedFrame.x - screenFrame.x)
	c.y = focusedFrame.h/2 + (focusedFrame.y - screenFrame.y)
		
	hs.mouse.setRelativePosition(c, screen)
end

function fullScreenWindows()
	for win in hs.window.visibleWindows() do
		hs.alert(win)
	end 
	--hs.window:ensureIsInScreenBounds())
end

----------------------------- Actual Config Methods ------------------------------
-- Hotkeys to resize windows absolutely
hs.hotkey.bind(hyper, '[', function() hs.window.focusedWindow():moveToUnit(hs.layout.left50) end)
hs.hotkey.bind(hyper, ']', function() hs.window.focusedWindow():moveToUnit(hs.layout.right50) end)
hs.hotkey.bind(hyper, 'f', function() hs.window.focusedWindow():maximize() end)

hs.hotkey.bind(hyper, 'h', function() hs.window.focusedWindow():focusWindowWest() end)
hs.hotkey.bind(hyper, 'l', function() hs.window.focusedWindow():focusWindowEast() end)
hs.hotkey.bind(hyper, 'k', function() hs.window.focusedWindow():focusWindowNorth() end)
hs.hotkey.bind(hyper, 'j', function() hs.window.focusedWindow():focusWindowSouth() end)
hs.hotkey.bind(hyper, '0', function() windowConfigs.moveWindow() end)

-- Hotkeys to trigger defined layouts
hs.hotkey.bind(hyper, '1', function() hs.layout.apply(internal_display) end)
hs.hotkey.bind(hyper, '2', function() hs.layout.apply(triple_display) end)

-- Application hotkeys
hs.hotkey.bind(hyper, 't', function() toggle_application("iTerm") end)
hs.hotkey.bind(hyper, 'g', function() toggle_application("Google Chrome") end)
hs.hotkey.bind(hyper, 'x', function() toggle_application("Xcode") end)
hs.hotkey.bind(hyper, 'e', function() toggle_application("Evernote") end)

-- Misc hotkeys
hs.hotkey.bind(hyper, 'r', hs.reload)
hs.hotkey.bind(hyper, 'y', hs.toggleConsole)
hs.hotkey.bind(hyper, 'n', function() os.execute("open ~") end)
hs.hotkey.bind(hyper, 'm', cursorToMiddle)
hs.hotkey.bind(cmd,   'e', hs.hints.windowHints)

-- Create and start our callbacks
configFileWatcher = hs.pathwatcher.new(os.getenv("HOME") .. "/.wsup/dotfiles/.wsup/Darwin/.hammerspoon/", reloadConfig)
configFileWatcher:start()

appWatcher = hs.application.watcher.new(applicationWatcher)
appWatcher:start()

screenWatcher = hs.screen.watcher.new(screensChangedCallback)
screenWatcher:start()

-- Finally, show a notification that we finished loading the config successfully
hs.notify.show("Hammerspoon", "", "Locked and loaded!", "")

**Comment by cmsj** [comment]
Argh, I'm so dumb. We didn't change a thing by switching those entries to be functions, they still get called at the time the table is being assembled.
I'm about to push a fix that allows the screen entry to be a function, which will get called when the layout is being applied, so then you'd do:
   ` {"iTerm", nil, display_laptop, hs.layout.maximized, nil, nil},`
and it will call your display_laptop() function when it is applying the layout. This will be in the next release. Sorry!

**Comment by deepumukundan** [comment]
Not a problem. Good that you found a fix. Sorry I couldn't help much more; I am new to Lua
