### ISSUE TITLE
How to disable the build-in keyboard 

### ISSUE THREAD

**Issue by how25** [Hammerspoon/hammerspoon#2250]
Does any api can do this
disable the build-in keyboard 
for my control + F1 doesn't work

**Comment by dasmurphy** [comment]
I don't know if this helps, but you can use a System Keyboard Handler to disable Keyboard Input.

I think in the Keyboard Events is an information if an USB Keyboard is used.

Here is the listening snippet i use. And keyboardHandler is the function that handles the events.
```
keyboardEventListener = hs.eventtap.new({
		hs.eventtap.event.types.flagsChanged,
		hs.eventtap.event.types.keyDown,
		hs.eventtap.event.types.keyUp -- ,
		-- hs.eventtap.event.types.NSSystemDefined
	}, keyboardHandler)
keyboardEventListener:start()
```

**Comment by cmsj** [comment]
@how25 we don't have a way to disable a keyboard. As dasmurphy suggests you could just capture all of its input, but I'd also suggest you take a look at Karabiner Elements - it may well be able to disable a keyboard.
