### ISSUE TITLE
snapshot() returns nil

### ISSUE THREAD

**Issue by Clark248** [Hammerspoon/hammerspoon#2253]
I have been using hammerspoon to automate some subtitling in Premiere Pro. My script worked for some time, but after coming back to it after a month the snapshot() function is returning nil.

I tried looking for a list of possible reasons that this would happen but all the documentation says is that snapshpt() will return nil if it is unable to get a snapshot, but doesn't give any common reasons why this might happen.

Various google searches have turned up nothing as it seems that the hammerspoon community is not as big as some others (nature of the niche, I suppose).

Anyway, I was hoping to get some insight into what could possibly be causing this.

I am using a Mac Pro running Catalina Version 10.15.1 (I had updated from Mojave since the last time the script worked so this may be the culprit)

Hammerspoon says it's up-to-date with version 0.9.76

Premiere Pro is up-to-date with version 13.1.5 (Build 47)

Any help you can give will be greatly appreciated, and if I have left out some important information, then I apologize, and please let me know what you need.

Thanks!

Here is the hotkey function up to and including the line that throws the exception.

`hs.hotkey.bind({"cmd", "alt", "ctrl"}, "T", function()
    local script_loc = ""
    hs.fs.chdir(hs.fs.currentDir() .. "/../Hammerspoon Projects/")
    --hs.alert.show(hs.fs.currentDir())
    function getScript(file)
        local file_lines = io.lines(file)
        local line_table = {}
        for line in file_lines do 
            table.insert(line_table,line)
        end
        print(hs.inspect.inspect(line_table))
        return line_table  
    end
    function PixleFinder(sshot, rshot)
        local photoRecog = hs.task.new('/usr/local/bin/python3', photoMatchCallback,photoMatchStream,{"PixleFinder.py",sshot,rshot}):start()
        while (photoRecog:isRunning()) do
        end
        local json_file = io.open("RelayFile.json", "r")
        local json_string = json_file:read("a")
        local response_table = hs.json.decode(json_string)
        return response_table.finds
    end
    function photoMatchCallback(exitCode, stdOut, stdErr)
        return stdOut
    end
    function photoMatchStream(task, stdOut, stdErr)
        return true
    end
    -- Get text from "script" file
        -- Get user to pick file
    hs.appfinder.appFromName("Hammerspoon"):activate()
    if (script_loc == "") then
        local fileTable = hs.dialog.chooseFileOrFolder("Please specify the script file.",os.getenv("HOME") .. "/Documents/")
        print(fileTable["1"])
        script_loc = fileTable["1"]
    end
    --Pull lines from script file
    
    --local lines = getScript("/Users/Tyler/Desktop/In Progress/GIVE_A_GUN/script.txt")
    --local lines = getScript(fileTable["1"])
    local lines = getScript(script_loc)
    --bring up PP Program window
    --TODO if PP is not open load it and wait for the load to finish
    local app = hs.application.find("Premiere Pro")
    app:activate()
    
    local wins = app:allWindows()
    local win
    local win2
    for i,curWin in ipairs(wins) do
        if curWin:title() ~= "" then
            win = curWin
            break
        end
    end
    local screen = win:screen()
    win:focus()
    win:maximize()
    --TODO only select "Titling" if it is not already selected
    app:selectMenuItem({"Window", "Workspaces", "Titling"})
    --make sure text tool is selected
    --TODO get screen shot of app window. send ss and sample of text tool to pixle finder
    local snapshot = win.snapshotForID(win:id())
    snapshot:saveToFile("search_photo.png",false,"png")`

Here is the error

2019-12-04 10:41:01: 10:41:01 ERROR:   LuaSkin: hs.hotkey callback: /Users/Tyler/.hammerspoon/init.lua:168: attempt to index a nil value (local 'snapshot')
stack traceback:
	/Users/Tyler/.hammerspoon/init.lua:168: in function </Users/Tyler/.hammerspoon/init.lua:105>
2019-12-04 10:41:01: ********

**Comment by latenitefilms** [comment]
In Catalina, Hammerspoon requires Screen Recording permissions.

**Comment by Clark248** [comment]
Thank you so much! That worked!
