### ISSUE TITLE
Toggle Airpods Pro's Modes - Noise Control

### ISSUE THREAD

**Issue by Pczek** [Hammerspoon/hammerspoon#2255]
With the recent release of the Airpods pro I've encountered the usecase to toggle between the transparency and noise canceling mode. It's quite a hassle to stop the music and then reach for my ear to disable the noise canceling when I just quickly want to listen to someone speaking to me. 
It would be cool to integrate such a workflow somehow with hammerspoon into a keyboard shortcut, for example `fn + play/pause key`.

I think this feature might fit quite well in to the `hs.audiodevice` module.

Modes to toggle `Transparency / Off / Noise Canceling`

<img width="190" alt="Screenshot 2019-12-12 at 09 38 13" src="https://user-images.githubusercontent.com/839848/70696041-2b5df600-1cc3-11ea-9957-f127f611414d.png">

**Comment by latenitefilms** [comment]
Related: https://github.com/insidegui/NoiseBuddy

**Comment by cmsj** [comment]
Looking through the code of NoiseBuddy, I'm not sure this is something we should integrate - it's pretty complex and I think it would probably make more sense to leave that to Rambo, who knows what he is doing with it. Perhaps he'd be willing to add AppleScript support so Hammerspoon could interact with it?
