### ISSUE TITLE
hs.application.open opens Firefox in Safe Mode

### ISSUE THREAD

**Issue by andreas-schlicker** [Hammerspoon/hammerspoon#2256]
I'm trying to create a keyboard shortcut to open Firefox. In principle this works, however, Firefox is always opened in Safe Mode. When I start it any other way (Spotlight Search, Terminal, Dock) it works fine. Here's the code from my init.lua:

mashOpen = {'alt', "ctrl"}
hs.hotkey.bind(mashOpen, 'f', function() hs.application.open("firefox.app") end)

I also tried it with other functions in hs.application with the same result. There's no output on the Hammerspoon console. 

I'm using Hammerspoon Version 0.9.76 (5104) and Firefox 71.0 on Catalina (10.15.2). But I had the same problem on macOS 10.14. Can anyone help?

Thanks,
andi

**Comment by Donkeyfish87** [comment]
+1.
I have identical behavior on Firefox 71 and Catalina too

**Comment by cmsj** [comment]
Is it starting in safe mode because you're holding keyboard modifiers? Does it still happen if you just run `hs.application.open('firefox.app')` in the Hammerspoon console? (fwiw I can't reproduce this, so it may also be something about your Firefox config/profile).

**Comment by andreas-schlicker** [comment]
Thanks for the tip. The keyboard modifiers is actually the solution. I was always using a modifier combination that included the option ("alt") key. Pressing "option" when opening Firefox opens Safe Mode. So the solution is to choose a modifier combination without "option".

**Comment by steady137** [comment]
This also happens to Zotero (bibiography tool based on Mozilla stuff) so I'm mentioning that here in case others could find this fix; presumably also Thunderbird (and Seamonkey).

http://kb.mozillazine.org/Safe_mode
https://forums.zotero.org/discussion/31507/all-add-ons-have-been-disabled-by-safe-mode
