### ISSUE TITLE
hs.http.doAsyncRequest Caching Problem

### ISSUE THREAD

**Issue by mgreenw** [Hammerspoon/hammerspoon#2259]
It seems that the `hs.http` method `doAsyncRequest` seems to automatically cache responses to requests. I believe the problem may be due to the use of the deprecated `NSURLConnection` and the problems described by this blog post:

https://blackpixel.com/writing/2012/05/caching-and-nsurlconnection.html

**Comment by mgreenw** [comment]
I think it would be possible to set a "No cache" policy by constructing the `NSMutableURLRequest` with a `cachePolicy`:

https://stackoverflow.com/questions/405151/is-it-possible-to-prevent-an-nsurlrequest-from-caching-data-or-remove-cached-dat

Here:
https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/http/internal.m#L189

**Comment by latenitefilms** [comment]
@mgreenw - I've just attempted to implement this in #2263. Let me know if it solves your issue.

**Comment by mgreenw** [comment]
Woah @latenitefilms thanks so much! This is awesome. I believe this will solve my issue.
