### ISSUE TITLE
Feature request: Enable and disable monitors from Hammerspoon

### ISSUE THREAD

**Issue by kbadk** [Hammerspoon/hammerspoon#227]
Many people have TV screens or other monitors connected to their computer that they only use occasionally. It'd be practical if Hammerspoon allowed you to enable and disable these monitors, so you won't accidentally "lose" a window on a monitor that's currently turned off.

During my research, I found only very few apps with this feature, most prominently the commercial and closed source app [SwitchResX](http://www.madrau.com/), but luckily also an open source ObjC implementation, [Eun's DisableMonitor](https://github.com/Eun/DisableMonitor).

**Comment by cmsj** [comment]
I had a look at the source of DisableMonitor and I'm a little worried - it seems like it's futzing around quite heavily in CoreGraphics and IOKit to do its work.
I also note that it does things like move windows off a monitor before disabling it, which suggests to me that the OS normally wouldn't do that (unlike if you unplug a monitor, when it would relocate all the windows). That sort of thing worries me, because it suggests that the OS is going to be in a slightly inconsistent state (which I think is also born out by what you said on IRC about not always being able to bring the monitor back?)

**Comment by kbadk** [comment]
SwitchResX is doing the job very well from what I hear. Maybe DisableMonitor just isn't doing everthing as it should be—the project is less than a year old and maintained by just one guy.

I only tested DisableMonitor briefly and it did seem to behave oddly. The layout in System Preferences -> Displays -> Arrangement didn't seem to correspond to the real layout and making changes in there would cause the System Preferences window to freeze for a few seconds. I haven't heard of any similar issues with SwitchResX. If I recall correctly, the disabled monitors don't even show up in Arrangement with SwitchResX, but they do with DisableMonitor.

**Comment by cmsj** [comment]
@kbadk fair point. I'll dig around and see what I can find out :)

**Comment by cmsj** [comment]
So, I think a sensible first step at this point would be to file a bug against DisableMonitor - Eun looks to be fairly active on the project, and clearly knows a lot more about the display subsystems than I do. It may well be that he can fix the odd behaviour you see.
(Something that might help, would be killing the Dock after DisableMonitor has reconfigured things. It will respawn and lots of desktop stuff will get refreshed. That might mean the layout prefsPane knows more about what is going on)

**Comment by kbadk** [comment]
I filed [two](https://github.com/Eun/DisableMonitor/issues/19) [issues](https://github.com/Eun/DisableMonitor/issues/20) at [Eun's DisableMonitor](https://github.com/Eun/DisableMonitor/issues) now. :)

**Comment by cmsj** [comment]
Thanks :)

I did also notice that DisableMonitor is GPL. That shouldn't prevent us from being inspired by its code, since our license (MIT) is more liberal, but we should also take care how we integrate the feature, if the kinks can be worked out.

**Comment by cmsj** [comment]
Having checked back in on this every so often, I think the reality is that disabling monitors is outside the scope of the system APIs. I note that the current-newest issue on DisableMonitor is that it doesn't work in 10.11. I don't think we should be using such fragile API hacks in Hammerspoon. Sorry!

**Comment by lowne** [comment]
fwiw and future reference: DisableMonitor never worked very well for me (even in Yosemite), whereas SwitchResX (invoked via `hs.applescript`) + manually toggling the backlight (via `hs.brightness`) does, also in El Cap.
