### ISSUE TITLE
How can I detect if the macOS toolbar is visible?

### ISSUE THREAD

**Issue by cweagans** [Hammerspoon/hammerspoon#2270]
I'm working on some window management stuff in my configuration. If I set the Y coordinate for a window to 0, it actually ends up at Y = 23 because the toolbar pushes the window down (as expected). I'm trying to figure out how I can take this into account when building out window layouts.

I figured this would be a property on hs.screen, but I wasn't able to find anything. Am I just looking in the wrong place?

**Comment by szymonkaliski** [comment]
Here's what I do:

```lua
local isMenubarVisible = hs.screen.primaryScreen():frame().y > 0
```

**Comment by cweagans** [comment]
Works for me! Thanks!
