### ISSUE TITLE
The Best Way of Passing Path Arguments to HS?

### ISSUE THREAD

**Issue by roeybiran** [Hammerspoon/hammerspoon#2271]
Hello everyone,
I’m interested in finding out if there’s an ideal way of passing paths to HS functions from other programs — LaunchBar, for example. Paths selected in LB can be passed on to LaunchBar “Actions”, which are basically scripts that accept any argument.

From thereon, I can do pretty much whatever I want, and in context of passing input to HS:

1. One option is AppleScript, with something like ``tell app "Hammerspoon" to execute lua code "spoon.mySpoon.myFunc(" & thePaths & …")``, but I feel it's shaky and prone to AS’ idiosyncracies and escaping issues.

2. Another options is to use ``hs.urlevent.bind``, and then run a shell script in LB, something along the lines of ``open -g hammerspoon://myFunc?path1=foo``. However, I would like the extra work required in preparing each argument and formatting the URL, and then again it feels like a lot more can go wrong with this approach compared to simply calling an executable with space-delimited paths as arguments.

Thanks in advance!

**Comment by latenitefilms** [comment]
There's also: [`hs.ipc`](http://www.hammerspoon.org/docs/hs.ipc.html)

**Comment by roeybiran** [comment]
Hi @latenitefilms,
I’ve read through the module’s docs, but still couldn’t figure out a way to pass arguments to HS from another app. Specifically, how will I be able to receive those arguments within the Lua code?

Thanks.

**Comment by latenitefilms** [comment]
You can use the `hs` command line tool to control Hammerspoon.

For example, if you have this function in `init.lua`:

```lua
function myTest()
    print("test")
end
```

...then trigger `hs -c "myTest()"` from Terminal, it will write "Test" in the Console.

**Comment by roeybiran** [comment]
Thanks for the reply — it’s a shame I haven’t even considered checking if there’s a `man` for the `hs` tool. I had no idea it has such depth.

Anyway, how do I pass parameters to the function I specify after `-c`? I did the following:
1. Listed some quoted, space-separated paths after the function, with or without a preceding `--`.
2. To access `_cli.args` within the Lua code, the most reasonable thing to me was to treat `args` as a property of a the parameter passed to the function, i.e.  `myTest(_cli)`, but that didn’t work.

**Comment by latenitefilms** [comment]
You can use [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html) to pass along the output of other commands as arguments.

For example, if you have this function in `init.lua`:

```lua
function alert(message)
    hs.alert(message)
end
```

You can use this Terminal command to display the date as an alert:

`hs -c "alert(\"$(date)\")"`

To clarify, by passing the `-c` argument to `hs` it:

> Specifies a Hammerspoon command to execute. May be specified more than once and commands will be executed in the order they appear. Disables colorized output unless -N is present. Disables interactive mode unless -i is present. If -i is present or if stdin is a pipe, these commands will be executed first.

So you can essentially pass along ANY Lua code, in the similar way to how `tell app "Hammerspoon" to execute lua code` in AppleScript-land works.

**Comment by roeybiran** [comment]
Thanks! I think I’ll stick with `urlevent`. Seems safer when working with paths.

**Comment by ipatch** [comment]
> You can use the `hs` command line tool to control Hammerspoon.
> 
> For example, if you have this function in `init.lua`:
> 
> ```lua
> function myTest()
>     print("test")
> end
> ```
> 
> ...then trigger `hs -c "myTest()"` from Terminal, it will write "Test" in the Console.

i definitely missing something here, but where do i find the `hs` command line tool.

I installed Hammerspoon using **brew**

```shell
brew cask install hammerspoon
```

and searching through my `$PATH` env var I do not see any CLI cmd called `hs`

**Comment by latenitefilms** [comment]
You can install the Command Line tool via:

[hs.ipc.cliInstall()](http://www.hammerspoon.org/docs/hs.ipc.html#cliInstall)

For documentation on the tool see [here](http://www.hammerspoon.org/docs/hs.ipc.html).
