### ISSUE TITLE
Hammerspoon Home Environment Variable

### ISSUE THREAD

**Issue by digitrance** [Hammerspoon/hammerspoon#2275]
Is there an environment variable that can be set to point Hammerspoon to someplace other than the ~/.hammerspoon directory?

For example, it could look something like this:
launchctl setenv HS_HOME $HOME/.config/hammerspoon

See: [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by latenitefilms** [comment]
See: https://github.com/Hammerspoon/hammerspoon/pull/582
