### ISSUE TITLE
Can I detect MacBook lid close/open as a separate event?

### ISSUE THREAD

**Issue by raarts** [Hammerspoon/hammerspoon#2277]
Hi,

I have seen several solutions that detect this based on the sleep function. But sleep can be initiated through other means and I need to specifically know if the lid is closed/opened. Is it possible?

Thanks.

**Comment by latenitefilms** [comment]
Try:

```lua
isLidOpen = hs.execute("ioreg -r -k AppleClamshellState -d 4 | grep AppleClamshellState | head -1 | grep Yes") == ""
```

**Comment by raarts** [comment]
Thanks, this works. But I guess there's no way to trigger on this event right? So I'm dependent on the sleep event, and need to check the lid there?

**Comment by latenitefilms** [comment]
After a quick Google, I can't see any way to get a notification when the lid is open or closed, sorry.

**Comment by raarts** [comment]
Ok, in any case, I'm using your solution, thanks for that.
