### ISSUE TITLE
Add function to relaunch Hammerspoon - hs.relaunch()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2278]
I propose that `hs.restart()` should restart the Hammerspoon app.

I tried doing this with `hs.task()`, based on what I read [here](https://vgable.com/blog/2008/10/05/restarting-your-cocoa-application/), but couldn't get it to work, so I believe to achieve this, we'll need a little helper app as discussed [here](https://stackoverflow.com/a/27497031/6925202).

**Comment by asmagill** [comment]
This what I use that has worked reliably for me for as long as I can remember:

~~~lua
relaunch = function()
    os.execute([[ (while ps -p ]]..hs.processInfo.processID..[[ > /dev/null ; do sleep 1 ; done ; open -a "]]..hs.processInfo.bundlePath..[[" ) & ]])
    hs._exit(true, true)
end
~~~

**Comment by latenitefilms** [comment]
Legend - thanks heaps @asmagill ! Genius as always.
