### ISSUE TITLE
hs.application:findMenuItem() doesn't seem to allow escaping parenthesis with "%"

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2280]
Hammerspoon Version 0.9.77 (5129)

I use Hammerspoon to select different persona in Chrome under the "People" menu. Recently Chrome started displaying a persona as either "Dev" or "Von (Dev)" I think depending on whether or not I'm logged into Google. I user a number of Google accounts, so the "Von" part may vary and I'm trying to use a regex with findMenuItem() (as added in #1041) to match either form using a regex of "^.* %(Dev%)" [where "%" is apparently what lua uses to escape special regex characters](https://www.lua.org/pil/20.2.html).

The problem is that I don't seem to be able to escape parenthesis in findMenuItem(). In the following case, I have a menu item labeled "Von (Dev)" and I would expect both of the following to work, but only the second one does:
```
> hs.inspect(chrome:findMenuItem(".*%(Dev%)", true))
nil

> hs.inspect(chrome:findMenuItem(".*Dev.", true))
{
  enabled = true,
  ticked = true
}

```

Using the first form above that fails in findMenuItem(), seems to work outside of that method:
```
> s="Von (Dev)"


> s:match(".*%(Dev%)")
Von (Dev)

```

Escaping characters other than the parenthesis seems to work as expected, e.g. escaping the "." here causes it to fail to match the paren:
```
> hs.inspect(chrome:findMenuItem(".*Dev%.", true))
nil
```

Using parenthesis without escaping them works as I would expect if lua were treating them as special characters for grouping with the the following both failing to match the parens literally:
```
> hs.inspect(chrome:findMenuItem("^.*(Dev)$", true))
nil
> hs.inspect(chrome:findMenuItem("^.*(Dev).$", true))
{
  enabled = true,
  ticked = true
}
```

**Comment by latenitefilms** [comment]
AFAIK [`hs.application:findMenuItem()`](http://www.hammerspoon.org/docs/hs.application.html#findMenuItem) uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression), not [Lua Patterns](https://www.lua.org/pil/20.2.html).

**Comment by von** [comment]
@latenitefilms You are correct. Thanks.

In case someone else ends up here for the same reason, here is the regex that works for me:

> chrome:findMenuItem("Dev|Von \\\\(Dev\\\\)", true)

The trick being there should be [two backslashes in a lua string to end up with one in the regex](https://stackoverflow.com/a/53738023/197789).
