### ISSUE TITLE
Add a function to hs.wifi to get WIFI power state

### ISSUE THREAD

**Issue by yuhan0** [Hammerspoon/hammerspoon#2284]
There is currently a `setPower(...)` function in `hs.wifi` but no `getPower()`, making it difficult to write a helper function to toggle the WIFI on/off.

**Comment by latenitefilms** [comment]
You can use [`hs.wifi.interfaceDetails(interface).power`](http://www.hammerspoon.org/docs/hs.wifi.html#interfaceDetails).

**Comment by yuhan0** [comment]
That works perfectly, thanks!
