### ISSUE TITLE
Calling Applescript from Hammerspoon error

### ISSUE THREAD

**Issue by sisoe24** [Hammerspoon/hammerspoon#2290]
I am trying to assign a shortcut to focus one of my menu done in Hammerspoon. The only way I found on how to do that is with Applescript

`tell application "System Events" to tell process "Hammerspoon" to tell menu bar item 1 of menu bar 2 to click`

this works, but when calling this from Hammerspoon

`hs.osascript.applescript("tell application \"System Events\" to tell process \"Hammerspoon\" to tell menu bar item 1 of menu bar 2 to click")`  

I get an index error:  

`{
  NSLocalizedDescription = 'System Events got an error: Can\\U2019t get menu bar 2 of process \\"Hammerspoon\\". Invalid index.',
  NSLocalizedFailureReason = 'Can\\U2019t get menu bar 2 of process \\"Hammerspoon\\". Invalid index.',
  OSAScriptErrorAppAddressKey = '<NSAppleEventDescriptor: [0x0,93093 \\"System Events\\"]>',
  OSAScriptErrorAppNameKey = "System Events",
  OSAScriptErrorBriefMessageKey = 'Can\\U2019t get menu bar 2 of process \\"Hammerspoon\\". Invalid index.',
  OSAScriptErrorMessageKey = 'System Events got an error: Can\\U2019t get menu bar 2 of process \\"Hammerspoon\\". Invalid index.',
  OSAScriptErrorNumberKey = -1719,
  OSAScriptErrorOffendingObjectKey = "<NSAppleEventDescriptor: 'obj '{ 'form':'indx', 'want':'mbar', 'seld':2, 'from':'obj '{ 'form':'name', 'want':'prcs', 'seld':'utxt'(\\\"Hammerspoon\\\"), 'from':null() } }>",
  OSAScriptErrorRangeKey = "NSRange: {142, 5}"
}`

I also tried call from file `hs.osascript.applescriptFromFile`but I got the same error.

btw I am an absolute newb in applescript so maybe I am missing something

**Comment by cmsj** [comment]
Separate from the AppleScript question, I think this ought to make the menu appear:

```lua
foo = SOME_MENUBAR_PREVIOUSLY_CREATED

menuFrame = foo:frame()
foo:popupMenu(hs.geometry.point(foo.x, foo.y + foo.h))
```

**Comment by sisoe24** [comment]
yes, it can do thanks! it works better if I give it the mouse position as the menus are not the same and doesn't look too nice next to each other.
I dont think I need applescript anymore at least right now.. so should I close the issue?

**Comment by cmsj** [comment]
Yep, I think we can close it. Thanks for letting us know it works 🙂
