### ISSUE TITLE
hs.window.filter as an alternative to hs.application.watcher?

### ISSUE THREAD

**Issue by roeybiran** [Hammerspoon/hammerspoon#2291]
Hello everyone,

Ever since I first started using HS, I’ve been using `hs.application.watcher` to respond to app events and specifically to enter an app’s associated `hs.hotkey.modal` object when it gains focus, and exit that modal when it loses focus.

Naturally, I want an app’s modal to be active only when that app is truly the focused object.  Many times however, the focus is taken by windows belonging to other apps. Those are mainly “helper” windows, input bars or other components (usually accompanying the main app)  — think 1Password 7 mini, the Emoji & Symbols window, Spotlight’s search bar.

Those windows are never detected by `hs.application.watcher`, and this conflicts with the keybindings I set for the previously active app. Instead of sending the keypresses to the app that's truly focused (or simply exiting the modal), HS still sends those to the keybinding’s target app, as in the configuration. And this usually does nothing since the target app doesn’t have the focus.

This leads me to having to check if the active app (as `hs.application.watcher` sees it) is indeed the active up — I do that by calling what I regard as the source of truth in this case —  `hs.window.focusedWindow:application()`, and comparing the results. I have to do that for almost every `hs.hotkey` I bind so the code can become extremely verbose.

`hs.window` is insanely powerful — it detects even negligible windows (like the aforementioned Emoji & Symbols one) and never fails me when detecting the truly focused app.

So, I was wondering are there any downsides to using `hs.window.filter` to responds to app events instead of `hs.application.watcher`? (performance and/or stability wise).

Thanks!

**Comment by megalithic** [comment]
I heard from Chris on IRC that the hs.application module is essentially outdated and should be replaced by the hs.window and associated hs.wind.filter submodule. 

I’ve made the switch to it also, from an automation that used hs.application. So far so good with the exception of figuring how to setup exclusions to ignore certain window titles or window roles/subroles for an app. 

Good luck to you!

**Comment by cmsj** [comment]
I think hs.application.watcher still has its place, but yes, hs.window.filter is much more capable and is perfectly reasonable for this kind of task :)

**Comment by roeybiran** [comment]
> I heard from Chris on IRC that the hs.application module is essentially outdated and should be replaced by the hs.window and associated hs.wind.filter submodule.
> 
> I’ve made the switch to it also, from an automation that used hs.application. So far so good with the exception of figuring how to setup exclusions to ignore certain window titles or window roles/subroles for an app.
> 
> Good luck to you!

That is exactly what I’ve been doing since I first opened this issue. I’m using a combination of `hs.application` and `hs.window` where the latter is used to detect activation of “transient" apps (1Password 7, LaunchBar, Spotlight). I want to make the full switch, but similarly I’ve yet to find a way to define rules that would make the `windowfilter` behave more like the `appwatcher`.

**Comment by muescha** [comment]
what are the window.filter events replacements for `hs.application.watcher.launched` and `hs.application.watcher.terminated` ?
