### ISSUE TITLE
Add support for the Loupedeck CT

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2292]
Similar to `hs.streamdeck`, I'd like to add native support for the [Loupedeck CT](https://loupedeck.com/en/products/loupedeck-ct) in Hammerspoon.

It seems this team has already done some awesome reverse engineering work here:

https://github.com/bitfocus/loupedeck-ct

It uses websockets, so I'm hoping to make use of the currently undocumented `hs.http.websocket`.

There's quite a few issues open regarding websockets, so I'm hoping I can close up a few of them at the same time.

**Comment by latenitefilms** [comment]
@cmsj or @asmagill - Have either of you played much with `hs.http.websocket`?

I keep on getting this error:

```lua
2020-01-17 02:00:48: 02:00:48    LuaSkin: (secondary thread): hs.http.webSocket: didFail: Error Domain=PSWebSocketErrorDomain Code=3 "Output stream end encountered" UserInfo={NSLocalizedDescription=Output stream end encountered}
```

...which seems to be the same issue reported [[here].](https://github.com/zwopple/PocketSocket/issues/57)

Related: #2056

**Comment by cmsj** [comment]
Sorry, I’ve never used websocket.

**Comment by latenitefilms** [comment]
For anyone who's interested, you can find our current implementation here:

https://github.com/CommandPost/CommandPost/blob/issue/2292-loupedeck-ct/src/extensions/hs/loupedeckct/init.lua

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as this extension is probably a bit too niche for Hammerspoon anyway.

**Comment by glaforge** [comment]
@latenitefilms where can I find your implementation? The link provided isn't working.
