### ISSUE TITLE
missing application event from event_t?

### ISSUE THREAD

**Issue by philbert** [Hammerspoon/hammerspoon#2298]
I'm running Version 0.9.78 of hammerspoon on macOS 10.15.2 with a simple application watcher that merges Finder windows when the application is activated:

```
function applicationWatcher(appName, eventType, appObject)
    if (appName == "Finder") then
        if (eventType == hs.application.watcher.activated) then
            appObject:selectMenuItem({"Window", "Merge All Windows"})
        end
    end
end
appWatcher = hs.application.watcher.new(applicationWatcher)
appWatcher:start()
```

However, if I already have Finder running and it currently has focus, and I launch a new Finder window, there is no event triggered at all. Finder is not special in this regard, as I have tested the behavior is the same for other applications.

Looking at this code, 
https://github.com/Hammerspoon/hammerspoon/blob/37491202e31712147ca5d3708dbd21ab1596ffe2/extensions/application/watcher.m#L54-L62

I wonder if this is a limitation of hammerspoon or a limitation of macOS?

Can you suggest a workaround for this issue?

**Comment by latenitefilms** [comment]
You can add an additional [`hs.window.filter`](http://www.hammerspoon.org/docs/hs.window.filter.html#new) watcher to trigger code when a new window is created?

**Comment by philbert** [comment]
The problem is that there is no event triggered with a new window.

**Comment by cmsj** [comment]
The underlying macOS api is for application-level events, which window creation is not considered to be, so for now the best we can offer is either hs.uielement or hs.window.filter.

**Comment by philbert** [comment]
Thanks for the explanation @cmsj. If I come up with some smart way to solve the problem I'll post it here.

**Comment by philbert** [comment]
Now I understood your answer @latenitefilms :)

This code seems to fix my problem:
```
finderWindowCreateFilter = hs.window.filter.new():setAppFilter("Finder")
finderWindowCreateFilter:subscribe(
    hs.window.filter.windowCreated,
    function (win, appName, event)
        win:application():selectMenuItem({"Window", "Merge All Windows"})
    end
)
```

However now I get a bunch of warning like this now, that seem to be related to #1551 and #1964?

```
2020-01-27 22:57:11: 22:57:11 ** Warning:   wfilter: No accessibility access to app Skype Helper (Renderer) (no watcher pid)
2020-01-27 22:57:11: 22:57:11 ** Warning:   wfilter: No accessibility access to app Firefox Developer EditionCP Web Content (no watcher pid)
2020-01-27 22:57:11: 22:57:11 ** Warning:   wfilter: No accessibility access to app Firefox Developer EditionCP WebExtensions (no watcher pid)
2020-01-27 22:57:11: 22:57:11 ** Warning:   wfilter: No accessibility access to app Firefox Developer EditionCP RDD Process (no watcher pid)
2020-01-27 22:57:36: 22:57:36 ** Warning:   wfilter: Spotlight (20773) is not registered yet
2020-01-27 22:57:51: 22:57:51 ** Warning:   wfilter: Finder (23683) is not registered yet
2020-01-27 22:57:57: 22:57:57 ** Warning:   wfilter: Google Chrome (23684) is not registered yet
```

It appears like that the 'No accessibilitiy' warnings only happen once when I reload my config, but the 'not registered yet' warning appear for every window creation which spams my console log. 

Am I missing something from ```:setAppFilter("Finder")``` to limit this filter to only look at events from Finder?
