### ISSUE TITLE
[Question]: disable chrome prompt for `hammerspoon://`

### ISSUE THREAD

**Issue by 404pilot** [Hammerspoon/hammerspoon#2300]
Hi, 

I am using [urlevent](https://www.hammerspoon.org/docs/hs.urlevent.html) module to register an action with `hammerspoon://update_file`. When I type it in chrome, chrome will give me a prompt every time:
 
<img width="443" alt="Screen Shot 2020-02-04 at 2 10 50 PM" src="https://user-images.githubusercontent.com/2459544/73782724-3039a600-4758-11ea-98e9-c615bd5c4db6.png">

I am wondering if there is a way to automatically select `Open Hammerspoon` or just disable the prompt.

**Comment by cmsj** [comment]
It seems like Chrome 77 removed the ability to tell Chrome to always allow it, but I think this might help? 
https://www.jroeder.net/2020/02/04/bring-back-always-open-these-types-of-links-in-the-associated-app-to-google-chrome/

**Comment by 404pilot** [comment]
@cmsj it works! Magic! Thank you!
