### ISSUE TITLE
Add Physical Drive information to hs.fs.volume.allVolumes()

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2305]
For example, I'd love to specifically get the "Media Name" as found in System Information:

<img width="1596" alt="Screen Shot 2020-02-18 at 1 08 03 am" src="https://user-images.githubusercontent.com/22286696/74660940-2b123780-51eb-11ea-8f5b-4626abfdf915.png">

Possible @asmagill  or @cmsj ?

In the meantime, you can use this Terminal command:

`system_profiler SPStorageDataType`

**Comment by cmsj** [comment]
Looks like that information is provided by the SPSupport private framework, so you're probably best off fetching the info from system_profiler (which I believe can output XML, for easier parsing). Sorry!

**Comment by latenitefilms** [comment]
No problemo - thanks @cmsj !
