### ISSUE TITLE
Tunnelblick spoon

### ISSUE THREAD

**Issue by rzuritamilla** [Hammerspoon/hammerspoon#2318]
Hi,
I am trying to use the Tunnelblick spoon but I cannot get it to work.... 

```
hs.loadSpoon("Tunnelblick") 
spoon.Tunnelblick.connection_name = "vpn_bla"
spoon.Tunnelblick.username = "bla@bla.com"
spoon.Tunnelblick.password_fn = ???? 
spoon.Tunnelblick:connect()
```

I am not sure of what to pass to the password_fn variable.  Any suggestions?

**Comment by cmsj** [comment]
It should be a function that returns the password as a string, so you can fetch the password from the keychain, or a file, or prompt the user, instead of hard coding it in your config. See http://www.hammerspoon.org/Spoons/Tunnelblick.html#password_fn

**Comment by rzuritamilla** [comment]
@cmsj Thanks!
I am pretty new to Hammerspoon and even to MacOS. could you please verify the below solution?
```
hs.loadSpoon("Tunnelblick")
hs.loadSpoon("Keychain")
spoon.Tunnelblick.connection_name = "vpn_bla"
spoon.Tunnelblick.username = "bla@bla.com"
spoon.Tunnelblick.password_fn = function()
  local item = spoon.Keychain:getItem{
                  account = spoon.Tunnelblick.username}
  return item.password
  end
spoon.Tunnelblick:bindHotkeys({login = {hyper, "v"}})
spoon.Tunnelblick:connect()
```
I have two additional questions, if I may.
1/ How to get more info about the parameters of the getItem method?
I do not know what type, kind and service mean.... In keychain, I see kind, account and where
 
2/ How can I disconnect the session? I see no disconnect method in this spoon... 

And a possible typo in the documentation:
in the usage section of https://www.hammerspoon.org/Spoons/Keychain.html 
it says: spoon.Keychain.addItem{... and  item = spoon.Keychain.getItem{...
but addItem and getItem are method so, shouldn't it read "spoon.Keychain**:**addItem or getItem{..." ?

Thanks!
