### ISSUE TITLE
Process Priority Helper Tool

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2328]
I just noticed the optional "Process Priority Helper Tool" in BetterTouchTool. I wonder if something similar could be added to Hammerspoon? Thoughts @asmagill ?

<img width="1056" alt="Screen Shot 2020-03-23 at 10 06 49 am" src="https://user-images.githubusercontent.com/22286696/77264311-324aca80-6cee-11ea-9514-dfd4d41ac914.png">

**Comment by latenitefilms** [comment]
This got no traction, so closing.

**Comment by asmagill** [comment]
Must have missed this before... I can think of two possibilities for what they are doing with their priority helper, both of which would require us to write a support application to handle the tasks requiring elevated privileges.

This is something we've been avoiding (it has come up before)... I can't speak for everyone involved in the previous conversations, but from my perspective, it introduces a whole new set of security questions that need to be asked and considered. Right now if Hammerspoon does something dangerous, the worst outcomes are scrambled data or a locked up machine... with elevated privileges, it becomes *theoretically* possible that the OS itself gets scrambled and requires reinstallation if we're not careful about how the helper app is written. And once that solution has been deployed to fix one problem, it will be an easy slide into seeing it as the answer for *other* issues that might be solvable (at least to an acceptable degree, if not completely) another way.

I'm not against it in principle, but thus far the benefits (in my mind at least) haven't outweighed the risks and effort required to be careful that should be applied in such a situation.

And I think with proper use of coroutines, and possibly the yield function I keep going back and forth on, we can mitigate *most* of the cases where Hammerspoon slows things down... we're still at the mercy of other apps slowing things down, though.
