### ISSUE TITLE
hs.screen not returning name for macOS Catalina Sidecar display

### ISSUE THREAD

**Issue by 23maverick23** [Hammerspoon/hammerspoon#2329]
Wondering if anyone else is seeing this issue. I'm using the macOS Catalina to get my iPad Pro 10.5 as a secondary display. In most cases, the name of the display profile works as the name of the screen in `hs.screen()` for calling other methods (like `hs.layout`). However, with Sidecar enabled, the name of my display is returned as `(un-named screen)`. Any workarounds for this?

Ex//
```
> hs.screen('0,0')
hs.screen: Color LCD

> hs.screen('0,0'):next()
hs.screen: LG UltraFine

> hs.screen('0,0'):previous()
hs.screen: (un-named screen)
```

macOS 10.15.3
iPad Pro 13.3.1

**Comment by cmsj** [comment]
I'll check into this, but it's entirely possible that for some reason Apple didn't name the Sidecar fake-monitor.

**Comment by cmsj** [comment]
Yeah this looks like it's a bug on Apple's side, the Sidecar display has no matching values for `kDisplayProductName`. I've filed a bug report with Apple, but I'll close this issue since there's nothing we can do in Hammerspoon.

**Comment by 23maverick23** [comment]
Thanks for looking into this Chris (and apologies for the delay on the reply). I appreciate it.
