### ISSUE TITLE
WindowHints Performance

### ISSUE THREAD

**Issue by rphillips** [Hammerspoon/hammerspoon#233]
I'm running Yosemite 10.10.2 and hammerspoon's windowHints take about 5-6 seconds to display. Seems to be a bit slow.

``` lua
hs.hotkey.bind(hyper, "i", function()
    hs.hints.windowHints()
end)
```

**Comment by cmsj** [comment]
Yeah, I've noticed this too. It seems to not happen immediately, but some time afterwards. If you move the mouse over the Hammerspoon menubar icon, you'll probably see a beachball.
I need to do some investigation, but my suspicion is that this means that the performance issue is coming from something in the OS X Accessibility API :(

**Comment by atsepkov** [comment]
I'm seeing similar issue, occasionally. Sometimes hints open immediately (even with 20+ apps/windows), other times there is a lag of several seconds.

**Comment by echiu64** [comment]
Same, i notice it's not just hammerspoon, but overall GUI responsiveness goes downhill. I've been rebooting Yosemite about 10X more often than my windoze machine. Disappointing...

**Comment by rcoedo** [comment]
The same thing happens to me, `hs.hints.windowHints()` is completely unusable at the moment.

I also noticed that `hs.hints.windowHints()` somehow messes with the `hs.hotkey.modal` module. It's like the modal state is stuck after calling windowHints():

1. Make the hs.hints.windowHints() call
2. Switch to a window
3. Now if you use your modal key mappings without the prefix the functions are executed.

**Comment by cmsj** [comment]
This should be addressed when #511 lands

**Comment by lowne** [comment]
After having updated to 0.9.40 or later,  as soon as you (if you still) notice sluggishness or excessive delay (upon calling `windowHints`, `layout`, etc), please open the Console and run this:
```lua
hs.window._timed_allWindows()
```
(If you get no output, try again a bunch of times (up arrow+return) until you (hopefully) do)

Then please paste the output here.

**Comment by ryfow** [comment]
```> hs.window._timed_allWindows()
took 6.00s for com.adobe.PDApp.AAMUpdatesNotifier
took 6.00s for org.pqrs.Karabiner-AXNotifier
table: 0x7ffca30b3280
```

**Comment by lowne** [comment]
@ryfow thanks, added in #594

**Comment by cmsj** [comment]
(fwiw, #594 is merged and will be in the next release)

**Comment by asethwright** [comment]
Not sure if this is helpful but an old adobe verison appears to cause slowness. Once I kill the process the window hints work fine.

```
> hs.window._timed_allWindows()
took 6.00s for com.adobe.csi.CS5.5ServiceManager
took 0.35s for N/A
table: 0x7f966e57ace0
```

**Comment by cmsj** [comment]
@asethwright thanks for that, we can add that to the filtering

**Comment by sapjax** [comment]
@lowne 
```
> hs.window._timed_allWindows()
took 6.00s for com.apple.mrt.uiagent
table: 0x7fcb1b5c4ee0
```

**Comment by swummoq** [comment]
took 5.84s for org.pqrs.Karabiner-AXNotifier
took 6.00s for de.appsolute.MAMP
took 0.17s for com.apple.FolderActionsDispatcher
took 6.00s for com.hp.devicemonitor
table: 0x7fdecfdb23c0

**Comment by mgee** [comment]
> hs.window._timed_allWindows()
took 6.00s for com.apple.WebKit.WebContent
table: 0x7fd3059691e0

**Comment by mrohr** [comment]
It seems like more hotkeys are being unbound/rebound each successive time you use the hints keybinding.  Here is my console as I use and reuse hints right after relaunching Hammerspoon, I have 4 window open.



First use:
>    hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey H

Selected a window:
>   hotkey: Re-enabled previous hotkey G
>             hotkey: Re-enabled previous hotkey H
>             hotkey: Re-enabled previous hotkey V
>             hotkey: Re-enabled previous hotkey Y

Second use:
> hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey H
>             hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey H
>             hotkey: Disabled previous hotkey H

Selected a window:
> hotkey: Re-enabled previous hotkey G
>             hotkey: Re-enabled previous hotkey H
>             hotkey: Re-enabled previous hotkey V
>             hotkey: Re-enabled previous hotkey Y
>            hotkey: Re-enabled previous hotkey G
>             hotkey: Re-enabled previous hotkey Y
>             hotkey: Re-enabled previous hotkey V
>             hotkey: Re-enabled previous hotkey H

Third use:
> hotkey: Disabled previous hotkey G
>            hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey H
>             hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey H
>             hotkey: Disabled previous hotkey H
 >            hotkey: Disabled previous hotkey G
 >            hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey G
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey Y
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey V
>             hotkey: Disabled previous hotkey V
 >            hotkey: Disabled previous hotkey H
 >            hotkey: Disabled previous hotkey H
>             hotkey: Disabled previous hotkey H

Selected a window:
> hotkey: Re-enabled previous hotkey G
>             hotkey: Re-enabled previous hotkey H
>             hotkey: Re-enabled previous hotkey V
>             hotkey: Re-enabled previous hotkey Y
>             hotkey: Re-enabled previous hotkey G
>             hotkey: Re-enabled previous hotkey Y
 >            hotkey: Re-enabled previous hotkey V
 >            hotkey: Re-enabled previous hotkey H
>             hotkey: Re-enabled previous hotkey G
 >            hotkey: Re-enabled previous hotkey Y
 >            hotkey: Re-enabled previous hotkey V
  >           hotkey: Re-enabled previous hotkey H

**Comment by bkentropy** [comment]
@lowne
> hs.window._timed_allWindows()
took 6.00s for com.skype.skype
table: 0x7fae2e4e0450

**Comment by von** [comment]
> hs.window._timed_allWindows()
2017-02-22 06:58:39: took 0.18s for com.apple.PressAndHold
2017-02-22 06:58:39: took 0.06s for com.microsoft.outlook.databasedaemon
2017-02-22 06:58:39: took 0.12s for com.apple.appkit.xpc.documentPopoverViewService
2017-02-22 06:58:39: took 0.09s for com.google.Chrome
2017-02-22 06:58:39: took 0.37s for com.apple.WebKit.WebContent
2017-02-22 06:58:39: took 6.00s for com.microsoft.autoupdate.fba

**Comment by yqrashawn** [comment]
When I relaunch Default folder X, it works fine.
```
2017-02-22 23:03:02: took 5.97s for com.stclairsoft.DefaultFolderX5
```

**Comment by cmsj** [comment]
I think we can close this - there isn't an actual performance issue in `hs.windowhints`, we just have people running into other apps/processes that are failing to respond to Accessibility events in a timely fashion. If people are hitting that and restarting those apps doesn't help, please file new issues so we can blacklist those apps.
