### ISSUE TITLE
hs.task:new() does not validate all task arguments are strings

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2337]
If one passes a value in the arguments array for hs.task.new() that is not a string, one gets a highly unclear error when invoking start():

> 2017-05-10 13:27:10: 13:27:10 ** Warning: LuaSkin: hs.task:launch() Unable to launch hs.task process: -[__NSCFNumber fileSystemRepresentation]: unrecognized selector sent to instance 0x337

Referencing #1418 as that is where one ends up if one searches for the above error.

**Comment by cmsj** [comment]
Thanks @von this is a good bug discovery!
