### ISSUE TITLE
Allow capturing of key events in secure input mode

### ISSUE THREAD

**Issue by caillou** [Hammerspoon/hammerspoon#2341]
I have heavily modified my keyboard using Hammerspoon. Now I run into the problem, that I can hardly use my keyboard when the OS decides, that I am in secure input mode.

Unfortunately the system tends to stay in secure input mode, even if the application with the password field loses focus.

I have noticed, that the keybindings defined through [Karabiner Elements](https://github.com/pqrs-org/Karabiner-Elements) continue to work in secure input mode. This leads me to believe, that it should be possible to circumvent secure input.

**Comment by latenitefilms** [comment]
Karabiner Elements is working at a much deeper system level of macOS than Hammerspoon - using a `kext` to control things, rather than "user level" APIs. Could you just use Karabiner Elements to "talk" to Hammerspoon to achieve all the things you want to do?

**Comment by cmsj** [comment]
Yeah Karabiner Elements is a kernel extension, we're a userspace program. I think it's essentially impossible for us to defeat secure input mode (otherwise it wouldn't be a very secure input mode!). Sorry.
