### ISSUE TITLE
docs » hs.eventtap, small typo: 'mouse' → 'key'

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2351]
In the docs at https://www.hammerspoon.org/docs/hs.eventtap.html#keyStroke

> delay - An optional delay (in microseconds) between **mouse** down and up event

"mouse" should be "key" 🙂

**Comment by luckman212** [comment]
Just realized the docs were public, so I made a PR

**Comment by cmsj** [comment]
Nice spot, thanks! While the docs are public, they're also auto-generated from docstrings in the code, so I'll push a fix momentarily.

**Comment by cmsj** [comment]
(although fwiw, the docs site won't update just yet, I only generate new versions when we have a release)
