### ISSUE TITLE
Feature Request: Run terminal commands

### ISSUE THREAD

**Issue by specter78** [Hammerspoon/hammerspoon#2356]
Run pre-defined terminal commands (like git commit and push) with a shortcut.

**Comment by cmsj** [comment]
We can already launch external commands with hs.task 👍

**Comment by latenitefilms** [comment]
Have a look at [`hs.execute()`](http://www.hammerspoon.org/docs/hs.html#execute) and [`hs.task`](http://www.hammerspoon.org/docs/hs.task.html).

**Comment by specter78** [comment]
> Have a look at [`hs.execute()`](http://www.hammerspoon.org/docs/hs.html#execute) and [`hs.task()`](http://www.hammerspoon.org/docs/hs.task.html).

Thank you. `hs.execute` works perfectly, though I think it could be given more visibility.
