### ISSUE TITLE
Possible to remove "Hammerspoon error" notification?

### ISSUE THREAD

**Issue by rsefer** [Hammerspoon/hammerspoon#2363]
With my "run it and see what happens" approach to editing my Hammerspoon config, I frequently add config-crashing errors, which result in error notifications like this one:

![image](https://user-images.githubusercontent.com/539765/81831664-40a1af80-9503-11ea-9740-8dfaf8d3400f.png)

Is there any way to access that notification and withdraw/remove it upon reload (assuming the error has been fixed and doesn't cause a new notification, of course)? As far as I can tell, there isn't a way to access notifications from *other* applications, but maybe it's possible for Hammerspoon itself...

I looked in some obvious places like `hs.crash`, `hs.logger`, etc with no luck.

**Comment by rsefer** [comment]
Inelegant solution: find and click the notification in applescript

```applescript
hs.osascript.applescript([[
	tell application "System Events"
		tell process "NotificationCenter"
			set windowCount to count windows
			repeat with i from windowCount to 1 by -1
				if value of static text 1 of window i is "Hammerspoon error" then
					click button "Close" of window i
				end if
			end repeat
		end tell
	end tell
]])
```

**Comment by asmagill** [comment]
`hs.notify.withdrawAll()`

It was written to remove lingering notifications generated by the `hs.notify` module, but I'm pretty sure it will catch the ones generated by the macOS portion of Hammerspoon as well.

**Comment by rsefer** [comment]
@asmagill thank you! I breezed right past that in the documentation...

**Comment by latenitefilms** [comment]
@rsefer - You can replace the [`hs.showError()`](http://www.hammerspoon.org/docs/hs.html#showError) function with your own code to override this.
