### ISSUE TITLE
PSA: Spotify's AppleScript support is broke

### ISSUE THREAD

**Issue by megalithic** [Hammerspoon/hammerspoon#2365]
Just adding this here for posterity and cross-reference. 

I noticed my notifications for track changes/info stopped working. Seeing HS uses AppleScript to talk to Spotify, I went digging on their forums and came across this:

https://community.spotify.com/t5/Desktop-Mac/You-broke-AppleScript-Again/td-p/4937134

Wanted to document that here, in case others come searching for logged issues in HS first.

**Comment by rsefer** [comment]
FWIW, one of the Spotify app updates over the past couple of weeks seems to have fixed this issue (on Catalina). I currently run app version 1.1.34.694.gac68a2b3 and apple scripting works consistently, as it used to.

**Comment by cmsj** [comment]
Thanks. I’ll close this issue now.
