### ISSUE TITLE
Canvas Window Level

### ISSUE THREAD

**Issue by lahomagit** [Hammerspoon/hammerspoon#2366]
I'm trying to use hs.canvas to "recolor" my menu bar. I've been nearly able to get it working, except that the rectangle I draw covers up my "menu" items on the left side of the menu bar (which I don't want), while leaving the system tray icons and clock on the right end uncovered (which is my desired behavior). I have the window level set to 24, which is apparently equivalent to "mainMenu". If I lower it the rectangle either disappears or is drawn below the menu bar like a normal window. If I raise the window level it covers both the menu items on the left and the icons/clock on the right.

Can anyone help me figure out how to put the rectangle under BOTH the tray/clock and the menu items (I'm actually unsure of the technical term for these two areas of the menu bar, as is likely apparent by now)? I'd also accept figuring out how to draw the rectangle behind the menu bar such it can be seen through the menu bar's partial transparency, but no window level I've tried seems to do that yet...

`a = c.new{x=0,y=0,h=menuBarHeight,w=screenFrame.w}:appendElements( {
    action = "build", padding = 0, type = "rectangle"
  }, {
    action = "fill",
    fillColor = { alpha = 1, red = 1.0  },
    frame = { x = "0", y = "0", h = "1", w = "1", },
    type = "rectangle",
    withShadow = false,
 } ):level(24)`

Menu bar without rectangle drawn:
![menubar_norect](https://user-images.githubusercontent.com/63752567/81991615-8be8ba80-95f6-11ea-80c5-59df8854f4bb.png)

Menu bar with rectangle:
![menubar_rect](https://user-images.githubusercontent.com/63752567/81991610-89866080-95f6-11ea-84f8-92452d152173.png)

**Comment by cmsj** [comment]
I would honestly be surprised if there is a level difference between the menubar itself and the text on the left. The only reason the "tray" icons on the right are a different level is that they are each independent little views.

What about instead drawing the colour as a thin strip at the very top of the screen, that doesn't obscure the menu text?

**Comment by asmagill** [comment]
Tried with `:orderBelow()` which places the element behind *other* elements at the *same* level, but that doesn't work -- the menubar isn't see-through, at least not to non-system items.

However, setting the canvas alpha (not the fill color, but the entire canvas) may give you something you can live with: try appending `:alpha(.5)` to your canvas to see what I mean.
