### ISSUE TITLE
Fix up hs.application:newWatcher()

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2374]
This method was previously inherited from hs.uielement and is not currently being so, in master. This breaks (amongst other things) hs.windowfilter subscriptions.

I need to go and look at this method specifically, but also any remaining hs.uielement methods in both hs.application and hs.window contexts.

**Comment by latenitefilms** [comment]
Does this mean that `hs.window.filter` is currently broken in the master branch?

**Comment by cmsj** [comment]
Yes, it does

**Comment by cmsj** [comment]
This should now be fixed and has a test, along with `hs.window:newWatcher()` and `hs.uielement:newWatcher()` (although the test for the latter is disabled due to it not being obviously possible to test just now.
