### ISSUE TITLE
Can't fill half of screen with iTerm2

### ISSUE THREAD

**Issue by gloryVine** [Hammerspoon/hammerspoon#2379]
I am currently doing the tutorial and am using the following code to move a window to the lower half of the screen:

```
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Down", function()
local win = hs.window.focusedWindow()
local f = win:frame()
local screen = win:screen()
local max = screen:fullFrame()

f.x = max.x
f.y = max.y + (max.h / 2)
f.w = max.w
f.h = max.h / 2
win:setFrame(f)
end)
```

This works fine for all applications I've tried, except for iTerm2 (which is one of the main applications I intend to use hammerspoon for).
Specifically, the iTerm2 window doesn't touch the lower part of the screen after resizing. There are a few pixels left in between.

I used `local max = screen:frame()` first, then I tried `local max = screen:fullFrame()`. Neither is working. I printed max, and saw that the hs.geometry.rect object contains the same values for both frame() and fullFrame().

I have deleted all iTerm2 application data and reinstalled it, but I still get the same result.

Has anyone an idea what could be causing this, or maybe encountered it before?

**Comment by cmsj** [comment]
I suspect than iterm allows its window to size only in steps that match its font size, which is why you end up a few pixels off. I’m wondering if it has a setting to allow arbitrary sizes that just have slightly larger internal margins?

**Comment by gloryVine** [comment]
> I suspect than iterm allows its window to size only in steps that match its font size, which is why you end up a few pixels off. I’m wondering if it has a setting to allow arbitrary sizes that just have slightly larger internal margins?

That was indeed it, thank you very much.
Can I ask you how you knew this was the problem?

**Comment by cmsj** [comment]
@gloryVine it's something I've been running into for years, since my days on Linux :)
