### ISSUE TITLE
Is Hammerspoon subject to AppNap?

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#238]
I'm wondering if Hammerspoon is subject to AppNap, and if so, whether you guys can make that not be the case.

I ask, because despite having done `defaults write -g NSAppSleepDisabled -bool true`, Hammerspoon is often not properly responsive.

I use HS almost entirely for moving windows around.  If it's been a while since I've done so, and then I press the hotkey to move my window to the northeast corner, HS will wait 1-1.5 seconds before moving the window.  Subsequent moves are instantaneous, until I again go some time without using my hotkeys to move windows, at which point there is a delay.

The following apps do not have this problem: Slate, Hydra, Mjolnir.  For the last two I use init files that are virtually identical to that for Hammerspoon, so I don't think something's wrong with my init.

**Comment by cmsj** [comment]
Hmm, it's an interesting question. I suppose it's possible that we're being hit by App Nap for some reason, where the others aren't.

I'm going to leave Activity Monitor running for a while, and see if I notice Hammerspoon showing up in App Nap - can I ask that you do the same? My config is quite complex and is often doing things with timers, or otherwise monitoring events, so it's possible I'm not hitting whatever idle pause it is that triggers App Nap.

**Comment by chdiza** [comment]
Good idea, I'll keep an eye on it.

**Comment by cmsj** [comment]
@chdiza I haven't seen Hammerspoon go into AppNap in my Activity Monitor. Have you seen it happen in yours?

**Comment by chdiza** [comment]
No, I haven't either.  Either something else is responsible for the AppNappish delays, or ActivityMonitor is not accurate.

**Comment by cmsj** [comment]
@chdiza are you still seeing this? I'm almost certain that we're not subject to AppNap

**Comment by tmandry** [comment]
The only times when I see HS go unresponsive are when it is querying a large number of (potentially unresponsive) apps, as it does in calls to `hs.window.allWindows()`. Is it possible that's what's going on?

**Comment by cmsj** [comment]
@tmandry that is my guess, it's a fairly common slowdown that we really can't avoid, sadly.

**Comment by chdiza** [comment]
@cmsj I haven't seen it, but then, I haven't used Hammerspoon in months.

FWIW, I have never done what @tmandry mentioned as a possible cause.

**Comment by chdiza** [comment]
I retried using HS for about twelve hours.  I still see the problem.  If HS is open but sits unused for a while, there is an annoying lag the first time one calls a hotkey.
