### ISSUE TITLE
Is there a way to get a list of the active applications, ordered by the last time they were opened?

### ISSUE THREAD

**Issue by avshyz** [Hammerspoon/hammerspoon#2381]
When you hit `CMD + Tab` on your, you'd see a list the running applications, ordered by the last time they were open.
The order of the applications in that list is determined by the last time they were activated or opened.

Is there a way to have something equivalent (like `hs.application.runningApplications()`, but ordered)?

Much obliged

**Comment by latenitefilms** [comment]
You could probably use [hs.window.orderedWindows()](http://www.hammerspoon.org/docs/hs.window.html#orderedWindows) to sort the list of applications?

**Comment by avshyz** [comment]
Ohh, that's just what I've needed! thanks for the help!
