### ISSUE TITLE
Darkmode Watcher - The Night Watch 

### ISSUE THREAD

**Issue by khoi** [Hammerspoon/hammerspoon#2386]
I'm having a setup where I need to run a couple of scripts when dark mode is activated. Should we add another `watcher` for this event?

**Comment by latenitefilms** [comment]
Related: https://medium.com/@ruiaureliano/check-light-dark-appearance-for-macos-mojave-catalina-fb2343af875f

**Comment by rsefer** [comment]
In the meantime, the following rough script might work:

```lua
function appearanceIsDark()
	asSuccess, asObj, asDesc = hs.osascript.applescript("tell application \"System Events\" to tell appearance preferences to return dark mode")
	return asObj
end

lastUIAppearance = appearanceIsDark()

hs.timer.doEvery(1, function()
	currentUIAppearance = appearanceIsDark()
	if currentUIAppearance ~= lastUIAppearance then
		if currentUIAppearance then
			-- dark scripts
		else
			-- light scripts
		end
	end
	lastUIAppearance = currentUIAppearance
end)
```

**Comment by rsefer** [comment]
P.S. This can also be done via `hs.distributednotifictions` using 'AppleInterfaceThemeChangedNotification'. Not sure if this is more efficient than my previous suggestion with `hs.timer` or not, but this *seems* like it would be:

```lua
function appearanceIsDark()
	asSuccess, asObj, asDesc = hs.osascript.applescript("tell application \"System Events\" to tell appearance preferences to return dark mode")
	return asObj
end

lastUIAppearance = appearanceIsDark()

hs.distributednotifications.new(function(name, object, userInfo)
	currentUIAppearance = appearanceIsDark()
	if currentUIAppearance ~= lastUIAppearance then
		if currentUIAppearance then
			-- dark scripts
		else
			-- light scripts
		end
	end
	lastUIAppearance = currentUIAppearance
end, 'AppleInterfaceThemeChangedNotification'):start()
```

**Comment by dasmurphy** [comment]
> P.S. This can also be done via `hs.distributednotifications` using 'AppleInterfaceThemeChangedNotification'. Not sure if this is more efficient than my previous suggestion with `hs.timer` or not, but it _seems_ like it would be:

Yes it should be more efficient, since it does not get fired every second. Thanks for the nice solution. This could be implemented as an official module so this should be only fired once from the system and lua manages all callbacks.

**Comment by dsedivec** [comment]
A note for anyone following rsefer's example in https://github.com/Hammerspoon/hammerspoon/issues/2386#issuecomment-643715994: I believe that you need to store the result of `hs.distributednotifications.new` in a variable, or else it will be garbage collected and you will stop getting notifications.  Signed, someone who *keeps forgetting* about this in Lua/Hammerspoon.

**Comment by rsefer** [comment]
@dsedivec Good catch! Thanks for finding that
