### ISSUE TITLE
hs.window.watcher for all window events

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#239]
Rather than have to set up a watcher on every application, it would be good to be able to have a global watcher for window events. Perhaps the OSX SDK allows for this, or perhaps it means we'd just be automating the process of adding watchers to each application.

**Comment by jwkvam** [comment]
This would be great, I'm currently drawing borders around applications to highlight focus but it's not perfect with the application events.

https://github.com/jwkvam/hammerspoon-config/blob/master/init.lua#L134

**Comment by cmsj** [comment]
Apparently I opened two issues for this. I'll close this and we'll track progress on #254
