### ISSUE TITLE
Hotkey callbacks execute synchronously, causing potential keyboard lockups

### ISSUE THREAD

**Issue by saagarjha** [Hammerspoon/hammerspoon#2395]
Hammerspoon's hotkey callbacks execute synchronously, which means that if code execution blocks in them for any reason they lock up keyboard input for the entire machine. On my computer `__getattrlist` has decided that it would like to be very, very slow (taking 10s of seconds to complete) which means that my hotkey to launch an app gets all hung up in that and messes with the rest of the system. Would it be possible to run the callback in some asynchronous capacity so the runloop doesn't hang and prevent other applications from receiving events?

**Comment by asmagill** [comment]
No, Hammerspoon executes *all* Lua and callbacks (though where thread safe, many of the Objective-C portions of some of the callback infrastructure is on another thread, but hotkeys isn't one of them that's thread safe) on the main application loop. Changing this would break... well, practically everything at this point... attempts have been started and abandoned in the past.

If `__getattrlist` is a lua function of your own devising (I didn't see it in the extensions anywhere when I checked with grep), then it may be possible in the next Hammerspoon release to leverage coroutines to alleviate some of this. See https://github.com/Hammerspoon/hammerspoon/wiki/Coroutines for more information, especially the document about leveraging coroutines in your own code.

**Comment by cmsj** [comment]
I suspect that's the internal implementation of the `getattrlist()` syscall, so that's part of the BSD area of macOS.

It's possible to defer callback execution to a later point in the runloop, using `hs.timer.doAfter()` to do the actual work you want to do, but overall I would suggest that if a relatively simple filesystem syscall is taking 10s of seconds, you're probably better off focusing on solving that problem (fsck would be my first port of call, ultimately leading to a re-install if necessary).

**Comment by saagarjha** [comment]
Right, it's the internal alias for `getattrlist(2)` in libsytem_kernel.dylib. I'm pretty sure my disk is fine and that this is just a Catalina thing, but I'll double check to make sure it's doing OK. But back to the point, I appreciate the insight into the design. If I call `hs.timer.doAfter` with a delay of 0 seconds, will that put the code on the next runloop iteration? If so, I'll try that out and see I can keep the hang confined to just Hammerspoon rather than the entire system–perhaps if that works making the callback work that way directly might be less invasive?

**Comment by asmagill** [comment]
`hs.timer` doesn't like 0 as an interval or delay time... I can't recall if `hs.math.minFloat` is defined in the current release of if that was added to the one in progress, but if it doesn't exist on your system, the value is `4.9406564584125e-324` and represents the smallest time interval `hs.timer` doesn't consider 0.

So I'm assuming you're using `hs.fs` then? That's based on `lfs`... which we're pretty much just dropping in "as is"... if it becomes an ongoing issue that some of the function calls are becoming slower with Apple's changes to APFS, it may be possible and/or desirable to create versions of some of these functions which *do* run the C stuff in a different thread and can then callback to Hammerspoon when they're done, but that's a larger undertaking... we'd need more confirmation that its a widespread/common issue before thinking about something like that.

**Comment by saagarjha** [comment]
No, just calling `hs.application.launchOrFocus`, which is calling that through LaunchServices; the slowness is almost certainly not Hammerspoon's fault :) I was just suggesting adding a `dispatch_async(dispatch_get_main_queue(), …)` around the call into Lua in `trigger_hotkey_callback` so the system presumably wouldn't be borked regardless of what the user might be doing in that callback.

**Comment by asmagill** [comment]
And for the record, in case this becomes a list of slow file system issues that may lead to future changes, I just want to add that APFS *does* have issues with folders that have a lot of little files in them or their direct subfolders -- I have a clone of https://github.com/WebKit/webkit downloaded and every time I enter that directory in the Terminal to look at any of the files or grep for something, even just run `ls`, there is a noticeable pause of at least 2 seconds before any activity begins. I can't recall for certain, but I don't remember this delay when the drive was formatted as HFS+.

**Comment by asmagill** [comment]
@cmsj, `launchApplication:` in NSWorkspace is deprecated in 10.15. They recommend `openApplicationAtURL:configuration:completionHandler:` which does call the completion handler asynchronously, but this was *introduced* in 10.15 as well...

Not sure, but it sounds like this *might* be more responsive, but because it was introduced with Catalina, we'd need to check and fallback to `launchApplication`, at least for the next couple of updates to the macOS to maintain our compatibility range.
