### ISSUE TITLE
Resizing/Moving windows fails

### ISSUE THREAD

**Issue by oschrenk** [Hammerspoon/hammerspoon#240]
I have some troubles moving windows around, specifically with my [configuration](https://github.com/oschrenk/dotfiles/blob/master/.hammerspoon/init.lua). I've tried other people configurations with the same error

```
-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Loading extension: window
-- Loading extension: uielement
-- Loading extension: hints
-- Loading extension: hotkey
-- Loading extension: pathwatcher
-- Loading extension: alert
-- Done.
/Users/oliver/.hammerspoon/init.lua:38: attempt to index local 'window' (a nil value)
stack traceback:
	/Users/oliver/.hammerspoon/init.lua:38: in function </Users/oliver/.hammerspoon/init.lua:36>
	[C]: in function 'xpcall'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:29: in function <...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:27>
```

The configuration fails on all application but funny enough works on the hammerspoon console log window once it pops up.

Do I have to restart (the applications)?

**Comment by cmsj** [comment]
Could you paste in your init.lua please?

(You shouldn't need to restart any applications after Hammerspoon, it doesn't cache lists of windows or anything like that)

**Comment by cmsj** [comment]
So, I would add a check before line 38 to ensure that `window` isn't nil - there are various situations where there is no focused window (e.g. if there just legitimately is no window with focus, or if you're using an X11 app). What sort of window has focus when you're getting the error?

Also, FWIW, personally speaking, I'm not a huge fan of the style of config that has lots of functions being passed around - I think it makes it much harder to reason about exactly when the various levels of function are going to be evaluated.

To pick one of your window management lines:

`hs.hotkey.bind(mash, "h", updateWindow(currentWindow, windowLeft))`

(which I interpret as moving/resizing the focused window to fill the left half of the screen), I would tend to write this as:

```lua 
    hs.hotkey.bind(mash, "h", function()
        hs.window.focusedWindow():moveToUnit(hs.geometry.rect(0, 0, 0.5, 1.0)
    end)
```

(note that this also skips checking the result of hs.window.focusedWindow(), so would also produce an error if there is no focused window)

Now all of the functionality is encapsulated with the hotkey. Certainly, it's not as abstract and may be more repetitive, but it's also possible to genericise it somewhat, without returning functions:

```lua
    local function moveCurrentWindowToUnit(unitrect)
        hs.window.focusedWindow():moveToUnit(unitrect)
    end
    local function moveCurrentWindowLeftHalf()
        moveCurrentWindowToUnit(hs.geometry.rect(0, 0, 0.5, 1.0)
    end
    local function moveCurrentWindowRightHalf()
        moveCurrentWindowToUnit(hs.geometry.rect(0, 0.5, 0.5, 1.0)
    end

    hs.hotkey.bind(mash, "h", moveCurrentWindowLeftHalf)
    hs.hotkey.bind(mash, "l", moveCurrentWindowRightHalf)
```

If it helps, my config is at: https://github.com/cmsj/hammerspoon-config/blob/master/init.lua

(Note, I'm not saying that what you have can't work, it absolutely can, I'm just stating a personal opinion that I think it's harder to understand and debug configs like yours :)

**Comment by cmsj** [comment]
Oh, one other thing to check is that Hammerspoon shows a green dot in its Preferences window next to Accessibility - if something is wrong there, you certainly won't be able to interact with any windows :)

**Comment by oschrenk** [comment]
Ugh. It was the Accessibility thing. It threw me off that the controls worked for the console window of Hammerspoon. Which, if you think about it makes sense, because the app is allowed to control itself but no windows of other applications. Maybe it would help to have that checked every time the configuration is reloaded and throw a warning. Also it would have been great to have some timestamps in the console logs to differentiate when the various errors occurred.

So sorry for the noise and hank you for the advice on the coding style!
