### ISSUE TITLE
Switch to Lua 5.4?

### ISSUE THREAD

**Issue by dasmurphy** [Hammerspoon/hammerspoon#2407]
I just saw that Lua 5.4 was released. How much work is it to implement?

https://www.lua.org/versions.html#5.4

I think it would be awesome if this is implemented before the next release. I don't think it will be breaking much code in lua.

Any comments?

**Comment by cmsj** [comment]
We usually track upstream Lua pretty closely:

- 14d230d3f66726ce6682dd83e171fdf4c6368725 adds Lua-5.4.0
- fec701b25b729cf77e2ae7ffdfe0768ed1d667c2 switches us to using 5.4.0

:)

**Comment by dasmurphy** [comment]
Thanks for the nice information. Did not know that.
