### ISSUE TITLE
 abc9124 produces unusable HS on 10.14.6

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#2408]
I just tried to build HS as usual (i.e., `make release`) and it succeeded; but when I tried to start HS I got this stranged dialog box:
<img width="488" alt="Screen Shot 2020-06-30 at 9 44 00 a" src="https://user-images.githubusercontent.com/3311113/86140425-77815400-bab6-11ea-82d8-6c722072efe1.png">

Upon reattempting to start HS, I got nothing but an HS console saying "Welcome to the Hammerspoon Console!
You can run any Lua code in here."  Apparently it refused to read my config.

**Comment by latenitefilms** [comment]
I assume this has something to do with @cmsj recently updating to Lua 5.4.

As a workaround, try commenting out this line:

https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/_coresetup/init.lua#L14

**Comment by cmsj** [comment]
Looks like there's a new implementation of `math.random()` so probably `math.randomseed()` too, and it's more strict about receiving an Integer, where we previously sent a float.

**Comment by chdiza** [comment]
Thanks for the fix!
