### ISSUE TITLE
uielement globalAppWatcher doesn't like nil as application passed to callback.

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#241]
Just saw this pop up in my hammerspoon console:

    ....app/Contents/Resources/extensions/hs/uielement/init.lua:72: attempt to index local 'app' (a nil value)
    stack traceback:
    	....app/Contents/Resources/extensions/hs/uielement/init.lua:72: in function <....app/Contents/Resources/extensions/hs/uielement/init.lua:71>

I am not using hs.uielement for anything of my own yet, so I was intrigued... looking closer, it looks like the callback to act for globalAppWatcher is receiving nil for the app parameter.

This occurred within seconds of when I received a notification from Messages while Messages was not actually running -- it was caused by my phone receiving a text.  Note that Facetime (call handoff) didn't trigger this -- it didn't occur until the text message came in.

In case it matters -- I just updated my local git clone of Hammerspoon and recompiled it around noon on 3/9/2015, so I'm pretty sure I'm running the latest code.

It would be simple to stick a check for nil into the lua callback, but someone familiar with uielement should probably check to make sure the obj-c code isn't missing something.  I'll try and force the same conditions some more this evening and see if I can narrow it to something more specific than my guesses about it being from Messages and involved in a notification from handoff.

**Comment by cmsj** [comment]
damn, looks like I caused that with commit 2aee23fc257890d7e0d0b0eeb8562219a9465581 earlier today. I was hoping to avoid a crash when creating hs.application objects for objects with no PID, but apparently I made things worse!

**Comment by cmsj** [comment]
@asmagill this should be fixed, apologies!
