### ISSUE TITLE
Privacy Policy clarification re console log

### ISSUE THREAD

**Issue by b-** [Hammerspoon/hammerspoon#2418]
Is the Hammerspoon console log ever transmitted via Crashlytics? Whether it is or not, could I please request that you add some specific clarification on this to the Privacy Policy?

**Comment by cmsj** [comment]
Console logs are never transmitted, but I agree we can make that explicit in the PP. Thanks for pointing it out!

**Comment by cmsj** [comment]
Fixed, thanks!
