### ISSUE TITLE
Add animated GIF support to hs.streamdeck

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2429]
Would this be possible @cmsj ?

**Comment by cmsj** [comment]
I suspect it probably is possible, although it might not be easy. The way it would need to work is a background thread writing the images every 1/x seconds, since the deck itself doesn't support animation.

**Comment by latenitefilms** [comment]
Ah right, so in terms of the official Stream Deck app, the Mac app is actually doing all the work (as opposed to the hardware), and just sending new images on a regular interval?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as I doubt @cmsj has the time to tackle, and I lack the skills. Anyone who stumbles across this in the future, feel free to re-open if you think it'd be helpful.
