### ISSUE TITLE
fullscreen (not lion-style) iterm doesn't get hints

### ISSUE THREAD

**Issue by jwkvam** [Hammerspoon/hammerspoon#243]
When I have iTerm fullscreen on one of my monitors, it doesn't get a window hint. iTerm shows up in `allWindows()`, but has the following attributes when full screened.

```
isFullScreen() is false
isVisible() is true
isStandard() is false
```

I'm not sure what the effect of filtering on `isVisible()` would be but I'm sure it was for good reason, it seems like finder is always visible along with windows on other workspaces. Anyway I don't have a solution in mind, I only spent a few minutes trying to figure out why it wasn't working.

**Comment by cmsj** [comment]
I can reproduce this. I think it means you have iTerm set to not use the "Lion" style fullscreen - i.e. it's doing something nonstandard with the window to make it fullscreen.

I'm not quite sure how to proceed with this - coming up with a reliable way to match windows suitable for getting a hint, seems to be a bottomless pit of apps that do things slightly strangely :(

**Comment by jwkvam** [comment]
Thanks, you're right, I had it deselected. I didn't realize that was an option! I think I'll just switch to using lion style fullscreen. Feel free to close this if you want, thanks!

**Comment by cmsj** [comment]
Thanks!

**Comment by srustamo** [comment]
Is 'lion-style' full-screen a `hammerspoon` option or iTerm? I don't see window hint for any of my full-screen windows, Emacs, iTerm2. 

OS X 10.9.5

**Comment by srustamo** [comment]
I must add, that I do see a hint for the full-screen window, but I don't see hints for other apps in the same space (this is true for iTerm2 and Chrome).

Also, for Emacs in full-screen, I do see other window hints, but once switched to another app choosing the hint, I no longer see Emacs's hint.

**Comment by cmsj** [comment]
@srustamo in the latest versions of iTerm, the option is called "Native full screen windows"

**Comment by srustamo** [comment]
@cmsj Thanks. How about other issues listed (Chrome full-screen etc)?
