### ISSUE TITLE
How can I auto change network location while changing wifi connection or how can I set up network DNS setting?

### ISSUE THREAD

**Issue by einverne** [Hammerspoon/hammerspoon#2434]
I use different DNS settings in different Wifi networks, so I create a Network Location called Home which holds the DNS setting of my Home. And there is a default automatic network which uses the default DNS setting.

So I was wondering can hammerspoon change the DNS setting? I scan all the [documents](https://www.hammerspoon.org/docs/index.html) and only find [hs.bonjour](https://www.hammerspoon.org/docs/hs.bonjour.html) related to DNS, but hs.bonjour is not for this purpose.

And I tried to add two key binds to change the network location.

```
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "H", function()
	hs.execute('/usr/sbin/networksetup -switchtolocation Home')
end)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "W", function()
	hs.execute('/usr/sbin/networksetup -switchtolocation Automatic')
end)
```

But when I add the `hs.execute` or `hs.network.confugration:setLocation` it doesn't work.

```
wifiWatcher = nil
homeSSID = "HomeWifi"
lastSSID = hs.wifi.currentNetwork()

function ssidChangedCallback()
    newSSID = hs.wifi.currentNetwork()

    if newSSID == homeSSID and lastSSID ~= homeSSID then
        -- We just joined our home WiFi network
        hs.audiodevice.defaultOutputDevice():setVolume(25)
		hs.alert.show("Welcome home!")
		-- result = hs.network.configuration:setLocation("Home")
		-- hs.alert.show(result)
    elseif newSSID ~= homeSSID and lastSSID == homeSSID then
        -- We just departed our home WiFi network
        hs.audiodevice.defaultOutputDevice():setVolume(0)
		hs.alert.show("left home!")
		-- result = hs.network.configuration:setLocation("Automatic")
		-- hs.alert.show(result)
    end

    lastSSID = newSSID
end

wifiWatcher = hs.wifi.watcher.new(ssidChangedCallback)
wifiWatcher:start()
```

**Comment by pboschmann** [comment]
Hi @einverne 
I had a similar issue and careful reading of the documentation (multiple times with a big cup of tea I must admit) helped me.

`hs.execute` passes four returns back: `output`, `status`, `type`, `rc`

> status -- true if the command terminated successfully or nil otherwise.
> rc -- if the command exited of its own accord, then this number will represent the exit code (usually 0 for success, not 0 for an error
> 

So I think if you write something like this:

```
output, status, cmd_type, return_code = hs.execute('/usr/sbin/networksetup -switchtolocation Automatic')
hs.alert(return_code)
```

there is a high possibility that you will receive `64` as error code which stands for `command line usage error`.
If it is so, check the last sentence of the `hs.execute` documentation:

> If you need to execute commands that have spaces in their paths, use a form like: hs.execute [["/Some/Path To/An/Executable" "--first-arg" "second-arg"]]

Bear in mind: I don't want to mess up my network settings and have therefore not tested this snippet. It should be something like this:
```
command = [["/usr/sbin/networksetup" "-switchtolocation" "Automatic"]]
output, status, cmd_type, return_code = hs.execute(command)
hs.alert(return_code)
```

Hope it helps.

**Comment by einverne** [comment]
@pboschmann Thank you for your response, I found Hammerspoon provider `hs.network.configuration:setLocation(location)`  method to set the network location, which works great. So the problem solved.

And thank you again for providing the right way to use the `hs.execute`.

**Comment by r00zza** [comment]
> @pboschmann Thank you for your response, I found Hammerspoon provider `hs.network.configuration:setLocation(location)` method to set the network location, which works great. So the problem solved.
> 
> And thank you again for providing the right way to use the `hs.execute`.


I'm trying to do the same automation as your post but for sure I've not well understood how to use the hs.execute.
I would like to load DNS of "Office Milan" location when I connect to my work network and use the "Automatic" on all other networks.

Here is my code that is doing nothing when I connect to my work network:

wifiWatcher = nil
workSSID = "FS"
lastSSID = hs.wifi.currentNetwork()

function ssidChangedCallback()
    newSSID = hs.wifi.currentNetwork()

    if newSSID == workSSID and lastSSID ~= workSSID then
		-- command = [["/usr/sbin/networksetup" "-switchtolocation" "Office Milan"]]
output, status, cmd_type, return_code = hs.execute(command)
		-- hs.alert(return_code)
    elseif newSSID ~= workSSID and lastSSID == workSSID then
		-- command = [["/usr/sbin/networksetup" "-switchtolocation" "Automatic"]]
output, status, cmd_type, return_code = hs.execute(command)
		-- hs.alert(return_code)

    end

    lastSSID = newSSID
end

wifiWatcher = hs.wifi.watcher.new(ssidChangedCallback)
wifiWatcher:start()


Can you please help me?
