### ISSUE TITLE
hs.screen brightness calls broken by recent macOS?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2437]
Has anyone else noticed that hs.screen's getBrightness and setBrightness have stopped working in one of the 10.15 minor updates? I'm using them on two external displays that should work, and were working previously.

If this is not just me, then presumably the private API that Apple uses, has changed somehow.

**Comment by latenitefilms** [comment]
Related:

- #2312 - Bug in hs.brightness.set()
- #1970 - `hs.brightness.ambient()` is returning "-1" (an error) 
- #2436 - Some actions not updated in System Preferences 
- #1641 - Document shortcomings of hs.brightness

**Comment by cmsj** [comment]
Maybe something about my Mac, or the Mac Pro, but I got someone to test this on an iMac and it was working fine for them.
