### ISSUE TITLE
hs.loadSpoon() does not call :start()

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2440]
It appears that `hs.loadSpoon()` doesn't call the Spoon's `start()` method when it loads it. `init()` and `start()` modified in the following to log a warning when they are called:

```
> s = hs.loadSpoon("Contexts")
2020-08-30 13:40:11: -- Loading Spoon: Contexts
2020-08-30 13:40:11: 13:40:11 ** Warning:  Contexts: Init()
> s:start()
2020-08-30 13:40:15: 13:40:15 ** Warning:  Contexts: Start()
```

I think this is a bug. If this is the intended behavior, it seems counterintuitive and I suggest the the [documentation for hs.loadSpoon()](https://www.hammerspoon.org/docs/hs.html#loadSpoon) and [the Spoons documentation](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#loading-a-spoonl) be updated to warn users of this.

**Comment by cmsj** [comment]
This is intended behaviour, so we should indeed clarify this in the docs, thanks.

The reasoning for this behaviour is that the user may not want to start all Spoons the moment they are loaded - having the :start() method means they can bind it to a hotkey, or trigger it in some other way. Spoons have :init() for things they need to do at load time.

**Comment by von** [comment]
OK, I'll submit a PR for `SPOONS.md`. My understanding is that the user is responsible for calling `start()`, if such a function exists, after loading a Spoon and before they attempt to do anything else with it.

And a detailed point: I assume the user should endeavor to only call `start()` once, but the Spoon developer should be prepared to handle it being called multiple times gracefully (e.g. check if it's been called before and just return)? Or would a user calling `start()` multiple times have some other expected behavior?
