### ISSUE TITLE
hs.window:setFrame() cannot resize window of apps like Emacs/iTerm linearly?

### ISSUE THREAD

**Issue by whitemuu** [Hammerspoon/hammerspoon#2444]
linearly here I mean you can set size 1,2,3.., but for Emacs/iTerm you can only set 1,5,9..(pseudo), with gaps between.

It seems to use the same API as mouse dragging does?
It cannot achieve fullscreen, like I cannot do with my mouse.
![image](https://user-images.githubusercontent.com/24451861/91866271-e80a4400-eca4-11ea-95d0-e00a5ae7a9f7.png)

applescript works totally fine.

    local function resizeFrame1(x, width, y, heigth, win)
       local screen = win:screen()
       local screenSize = screen:frame()
       local x1 = screenSize.w * x
       local x2 = x1 + screenSize.w * width
       local y1 = screenSize.y + screenSize.h * y
       local y2 = y1 + screenSize.h * heigth
       local script = string.format('tell application "%s" to set bounds of front window to {%d, %d, %d, %d}',
                                    win:application():name(), math.floor(x1), math.floor(y1), math.floor(x2), math.floor(y2))
       hs.osascript.applescript(script)
    end

**Comment by cmsj** [comment]
I’m not sure what, if anything, AppleScript is doing differently, but this is ultimately down to the apps requesting that they only be resized in even steps that match their font size. I don’t believe there is a way for us to override that, unfortunately.

I’m not sure about Emacs, but I know iTerm had a setting to resize smoothly.

**Comment by whitemuu** [comment]
Thanks, you can resize Emacs smoothly via (setq frame-resize-pixelwise t) as per https://stackoverflow.com/questions/27758800/why-does-emacs-leave-a-gap-when-trying-to-maximize-the-frame
