### ISSUE TITLE
Extension for IOKit HID devices?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2447]
@asmagill - I realise you already have `hs._asm.iokit`, but I was wondering how practical/possible it would be to create a Hammerspoon extension that can handle IOKit HID devices (i.e. so that we could, in theory, recreate something like `hs.streamdeck` using this new extension and Lua code)?

The purpose of this extension would be for allowing adding support for generic HID devices easier - i.e. I could build the `hs.gamepad` extension in Lua, rather than Objective-C.

Another example is that Razer recently dropped macOS support (from Catalina onwards) for their range of gaming mice and keyboards (for example, the [Razer Tartarus V2](https://www.razer.com/gaming-keypads/Razer-Tartarus-V2/RZ07-02270100-R3U1)) - so I was thinking I could possibly add native support for these devices directly within Hammerspoon. It would be much quicker/easier if I could do this in Lua-land, rather than writing a new extension in Objective-C.

I'm thinking you could create a new HID device using the vendor ID and product ID, then you can use `IOHIDDeviceRegisterInputReportCallback` as a callback for new messages from the HID.

Thoughts? Is this a crazy idea @cmsj ?

Maybe related?
https://github.com/Arti3DPlayer/USBDeviceSwift

**Comment by latenitefilms** [comment]
Whilst you're around @asmagill - if you have any thoughts, comments, suggestions on this, let me know.

**Comment by asmagill** [comment]
I have never been wedded to `hs._asm.iokit`... I've never really expanded upon it or created the kind of filters it would require to be truly useful.

It's something I may revisit someday, but if you have ideas on an implementation you want to try out, then by all means, give it a go!

What I found that dampened my initial enthusiasm after looking at all of our existing modules that use IOKit in some fashion or another (battery, usb, and fs immediately come to mind, but IIRC there are others) is that there seem to be more than one approach used, and depending upon what specifically you want to do, some approaches work better than others for certain types of queries or actions... it will probably end up that we'll need one iokit submodule for type X queries/actions, and another iokit submodule for type Y queries/actions, and so on. I never really got around to figuring out a way to group or classify them before getting distracted by other things, though.

**Comment by latenitefilms** [comment]
Legend, thanks! I'll have a play at some point.

**Comment by latenitefilms** [comment]
> I'm really not sure at all that writing device drivers in Lua is a good idea :)

Yeah, fair enough. It is probably much better to handle device code in Objective-C land. Thanks @cmsj !

**Comment by gingerbeardman** [comment]
Another case for #3392
