### ISSUE TITLE
Resize events?

### ISSUE THREAD

**Issue by JaredSartin** [Hammerspoon/hammerspoon#245]
Should changing a window's size trigger any events to the window? I notice when I resize my terminal (iTerm) with Vim open, it doesn't register the resize. If I were to use BetterSnapTool (a resize app) and do the same thing, the Vim session in iTerm gets notified and acts accordingly (status bars go to bottom and buffer splits resize).

No rush on fixing this - it is just a minor annoyance that I can deal with for now. One less app running because of hammerspoon - huzzah!

**Comment by cmsj** [comment]
Can you paste in the relevant section of your init.lua that does the resize?

**Comment by JaredSartin** [comment]
```
require "extensions.key-combos"

local frame_cache = {}

function set_frame(w, f)
  if frame_cache[w:id()] == nil then
    frame_cache[w:id()] = w:frame()
  end
  w:setFrame(f, 0)
end

function unset_frame()
   local w = hs.window.focusedWindow()
   local f = frame_cache[w:id()]
   if f then
      set_frame(w, f)
   end
   frame_cache[w:id()] = nil
end

function maximize()
   local win = hs.window.focusedWindow()
   local max = screen_frame(win)
   set_frame(win, max)
end

function screen_frame(win)
   local screen = win:screen()
   local max = screen:frame()
   local dx = max.x
   if dx > 0 and dx < 10 then
      max.x = 0
      max.w = max.w + dx
   end
   return max
end

function fraction_frame(pframe, orient, frac, offs)
   local f = {x = 0, y = 0, w = 0, h = 0}
   if 'vertical' == orient then
      f.w = math.ceil(pframe.w * frac)
      f.h = pframe.h
      f.x = pframe.x + (offs * f.w)
      f.y = pframe.y
   elseif 'horizontal' == orient then
      f.w = pframe.w
      f.h = math.ceil(pframe.h * frac)
      f.x = pframe.x
      f.y = pframe.y + (offs * f.h)
   end
   return f
end

function left_half()
   local win = hs.window.focusedWindow()
   local max = screen_frame(win)
   local half = fraction_frame(max, 'vertical', 0.5, 0)
   set_frame(win, half)
end

function right_half()
   local win = hs.window.focusedWindow()
   local max = screen_frame(win)
   local half = fraction_frame(max, 'vertical', 0.5, 1)
   set_frame(win, half)
end

-- Keybinds
hs.hotkey.bind(mash, "m", maximize)
hs.hotkey.bind(mash, "delete", unset_frame)
hs.hotkey.bind(mash, "left", left_half)
hs.hotkey.bind(mash, "right", right_half)
```

**Comment by JaredSartin** [comment]
@cmsj Is this enough to diagnose? Am I using the improper setters?

**Comment by cmsj** [comment]
@JaredSartin that ought to be enough, yeah. It's interesting, ultimately you're just using `hs.window:setFrame()`, which is exactly the right thing, and it should indeed cause windows to update properly. I'm using the latest iTerm2 build (2.0.0.20141103) and my various resizing hotkeys cause it to send the SIGWNCH signal to things running inside it, so they update correctly.

**Comment by JaredSartin** [comment]
Odd. I will make sure iTerm is updated. I do notice going from small to
large that my buffer splits are real odd looking until I do anything that
would cause vim to reevaluate the window sizes, then they snap into place.
My right-side terminal status text does shift properly, however. Could be a
vim problem.

Thanks for investigating. Feel free to close this and I will open it again
if there is a definite problem with Hammerspoon and not term configure.

On Saturday, March 28, 2015, Chris Jones <notifications@github.com> wrote:

> @JaredSartin <https://github.com/JaredSartin> that ought to be enough,
> yeah. It's interesting, ultimately you're just using hs.window:setFrame(),
> which is exactly the right thing, and it should indeed cause windows to
> update properly. I'm using the latest iTerm2 build (2.0.0.20141103) and my
> various resizing hotkeys cause it to send the SIGWNCH signal to things
> running inside it, so they update correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hammerspoon/hammerspoon/issues/245#issuecomment-87362744>
> .
>


-- 
*Jared Sartin*
269.364.1735 | jared.sart.in | @JaredSartin <http://twitter.com/JaredSartin>
