### ISSUE TITLE
Using spacebar for mashing

### ISSUE THREAD

**Issue by ianks** [Hammerspoon/hammerspoon#246]
I know as of now Hammerspoon only supports using modifier keys for trigger hammerspoon. There is probably an underlying reason for this which I am overlooking, but would it be possible to use Spacebar as a trigger for a mash? Ideally, my workflow would be `mash = { 'ctrl', 'space' }`. What are the chances of implementing this? Impossible? Possible?

**Comment by cmsj** [comment]
So, hs.hotkey uses OS X's Carbon Events to register hotkeys, and they are very traditional, very limited modifers+key type things.

However, you may well be able to make this work with hs.hotkey.modal - you'd map ctrl-space to enter a modal state, which activates a series of other hotkeys, which can then handle your next key-press (and likely then exit the modal state).

**Comment by ianks** [comment]
Worked like a charm. Thanks! Now, the only issue is hints does not work correctly. I am guessing it also enables modal mode which will conflict. Any ideas on how to resolve nested modals?

**Comment by cmsj** [comment]
Ooh, yeah, I think nested modals are not going to work with the current code. If you have ctrl-space enter the modal state, and in your callback for the next character (which I guess is triggering hs.hints.windowHints()?) disable the initial modal state before calling windowHints(). I haven't tested it, but I'd expect that would work.

**Comment by ianks** [comment]
Excellent. I actually prefer this modal pattern than thr "hyper/mash" pattern. It gives the user more options, and allows the user to have a delay after pressing their modal "mash" sequence. 

What are the the theoretical downsides to this pattern?

**Comment by cmsj** [comment]
I'm not sure there really are any downsides at the moment. I suppose that if the complexity of a configuration increased, you might find yourself wanting to trigger a new modal state while already in another, which is pretty much what has happened here, but (unless it didn't work?) it seems like we have a reasonable option for that.

Assuming that disabling the state before calling windowHints(), works, I think we're good to close this issue out?

**Comment by ianks** [comment]
Yes! I am out of town but I will report back here if it doesn't work. Cheers!
