### ISSUE TITLE
Suggestion/Request: Blog post showing feature use on release

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#2475]
Every time a new release comes out, it looks full of cool features. But with a long list it takes a lot of digging to find relevant use possibility especially for complex features.  I'd personally find it very useful if a blog post showing new features was done at release time for discoverability/usability.

**Comment by junkblocker** [comment]
Just discovered this for coroutines - https://github.com/asmagill/hammerspoon/wiki/CoroutinesLeveraging

**Comment by asmagill** [comment]
FWIW, that document is also available through the primary site Wiki (https://github.com/Hammerspoon/hammerspoon/wiki) as well. I try to keep mine and the Hammerspoon one in sync, though occasionally mine will have a few updates or in-progress documents that I haven't merged in yet. However, the coroutine stuff should be current.

**Comment by junkblocker** [comment]
@asmagill  - Thank you for creating these awesome modules and for updating the wiki! I see `hs.canvas` tutorial is on there too now and that's another example of one of the features I've not used yet since it looked like a big feature from the outside I never found a tutorial for that. Until this mention of the wiki, the way to find examples for me has been to look at your old personal config, which at some point changed to new config and which last I saw was not updating much ... and the tracking gap between your work being done and that getting into a release also grew.

This helps immensly. It would help even more if the practice of adding at least small snippets and such for all newly added features were added to the wiki became standardized for hs.

**Comment by latenitefilms** [comment]
Agreed - when I get a chance I'll try write up a new Wiki explaining what's new in the latest release.

**Comment by asmagill** [comment]
Ditto, and I've been trying to move in that direction lately... it may be a while to catch up with some of the earlier changes that I think still deserve some of their own example pages, but having them in a consistent location will go a long way to spreading their use!

Many of the modules I end up adding have their own Example directories which don't always get reflected in my personal config, but once they're moved into core, we don't really have a place for example files and the module docs aren't a great place for more than a few lines of code for demonstrations, so they get lost sometimes... another reason I would like to expand the under-utilized wiki more.

**Comment by asmagill** [comment]
@cmsj we should probably come up with a set of regular headings for the sidebar, use the footer, and maybe some "best practices" for creating new pages... I've been writing them like I do other markdown pages, but because the wiki throws a common header and does some other non-obvious stuff (especially in the sidebar with links) I'm sure we could make things look better. 

Of course, these are low priority items, but figured I'd mention them so maybe we don't forget... 🤪 I make myself laugh sometimes...

**Comment by latenitefilms** [comment]
@junkblocker - I've added some release notes to the Wiki [here](https://github.com/Hammerspoon/hammerspoon/wiki/0.9.79).

Any questions, comments, or suggestions let me know! If you're happy with this, you can close this issue, and I'll try do this for each new feature release.

**Comment by junkblocker** [comment]
Thanks, @latenitefilms , @asmagill . This is looking useful!

**Comment by latenitefilms** [comment]
Note to self - here's a great example of a good GitHub Wiki: https://github.com/Netflix/Hystrix/wiki

**Comment by asmagill** [comment]
@latenitefilms nice cleanup job on the wiki... want to tackle the coroutine ones as well? Just kidding -- I need to update and reorganize them anyways -- some of it no longer applies and some of the rest was written in a hurry to get info available and really should be reorganized. Thankfully the most useful file to most is in pretty good shape.
