### ISSUE TITLE
build_docs.py doesn't work with Python3

### ISSUE THREAD

**Issue by von-forks** [Hammerspoon/hammerspoon#2477]
`build_docs.py`, whose use is described in [SPOONS.md](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#generating), doesn't seem to work with Python3 and only with Python2, which is now [depreciated](https://www.python.org/doc/sunset-python-2/).

```
% ~/develop/hammerspoon/scripts/docs/bin/build_docs.py --templates ~/develop/hammerspoon/scripts/docs/templates/ --output_dir . --json --html --markdown --standalone .
Traceback (most recent call last):
  File "/Users/von/develop/hammerspoon/scripts/docs/bin/build_docs.py", line 620, in <module>
    main()
  File "/Users/von/develop/hammerspoon/scripts/docs/bin/build_docs.py", line 599, in main
    results = do_processing(arguments.DIRS)
  File "/Users/von/develop/hammerspoon/scripts/docs/bin/build_docs.py", line 359, in do_processing
    raw_docstrings += extract_docstrings(filename)
  File "/Users/von/develop/hammerspoon/scripts/docs/bin/build_docs.py", line 93, in extract_docstrings
    line = raw_line.decode('utf-8').strip('\n')
AttributeError: 'str' object has no attribute 'decode'
% python --version
Python 3.8.5
```

**Comment by cmsj** [comment]
This is true, but for now macOS still ships with Python 2.x. It will certainly become an issue in the future because Apple will likely stop shipping Python entirely and we'll have to use a Python 3.x from Homebrew or similar.

I'll certainly update it when it becomes an issue for releasing Hammerspoon :)

**Comment by von** [comment]
Since this script is effectively bound to `/usr/bin/python` it may be worth changing the `#!` line to such? Any other python that is picked up seems certain to be python3.

**Comment by cmsj** [comment]
@von yeah that's a good point, thanks.
