### ISSUE TITLE
itunes.getCurrentTrack() returns a table if iTunes isn't playing any tracks

### ISSUE THREAD

**Issue by peterhajas** [Hammerspoon/hammerspoon#249]
I found this while working on my iTunes current track display.

If I call `hs.itunes.getCurrentTrack()` after freshly launching iTunes, it will return a value of type `table` instead of an empty string (or `nil`).

See this change I made to my `init.lua` for my current workaround:

https://github.com/peterhajas/dotfiles/commit/2fd7b35d0ff039a53f1b0c36aa62c5ff8ff4a9df

**Comment by cmsj** [comment]
Good catch, thanks. I went with nil rather than an empty string. Slightly more work for users to check the response, but it feels a little more correct. I'm still slightly on the fence though, given the intended cheapness of using hs.itunes/hs.spotify.
