### ISSUE TITLE
Link to examples from module doc

### ISSUE THREAD

**Issue by sheijk** [Hammerspoon/hammerspoon#251]
It would be very helpful to have examples for each module. A first step would be to add links to the examples in the getting started guide for those modules that are covered.

**Comment by cmsj** [comment]
I think this is a good idea, it also provides a nice way to discover the Getting Started Guide from the API docs. I suspect we should also do the reverse, and link to the API docs for each covered module, from the GSG.

Thanks!

**Comment by cmsj** [comment]
I think I've changed my mind on this, we removed the example extensions some time ago, and we have so many extensions that work in sufficiently different ways, that I don't think there is any real value anymore in having the idea of separate, non-functional examples.
