### ISSUE TITLE
hs.moveOneScreen* removed?

### ISSUE THREAD

**Issue by swummoq** [Hammerspoon/hammerspoon#2513]
I was getting errors calling the hs.moveOneScreenEast/West etc methods. Looking at the HS source I see they are commented out. Is this accidental or are these depreciated?

**Comment by latenitefilms** [comment]
I believe this has been fixed in #2488 - so should be fixed in the next release, or you could build Hammerspoon yourself using the latest code in the `master` branch.

**Comment by dooreelko** [comment]
i fixed mine with 

`
hs.hotkey.bind(mash2, hs.keycodes.map["left"], function() 
  win = hs.window.focusedWindow()
  win:moveToScreen(win:screen():toWest())
end)

hs.hotkey.bind(mash2, hs.keycodes.map["right"], function() 
  win = hs.window.focusedWindow()
  win:moveToScreen(win:screen():toEast())
end)

**Comment by asmagill** [comment]
The `hs.window:moveOneScreenXXX` commands are methods and should be applied to `hs.window` objects directly, not invoked as a function taking the object as its first argument. During a clean up of `hs.windows` to ensure a proper separation of functions and methods, the commands referring to cardinal directions were overlooked, but this has been corrected in the master branch of the repository and will be reflected in the next release of Hammerspoon, expected soon.

**Comment by asmagill** [comment]
If you wish to manually apply the necessary fixes for this issue before the next release is built, you can apply the changes outline in https://github.com/Hammerspoon/hammerspoon/pull/2488/files and https://github.com/Hammerspoon/hammerspoon/commit/7a689568e94bb65fa9727822b5758069603683af directly by editing `/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/window/init.lua` with any text editor of your choice.

I'm going to close this, but feel free to reopen if you think we've missed anything.
