### ISSUE TITLE
Update 0.9.80 broke hs.window:focusWindowWest(South,North,East)

### ISSUE THREAD

**Issue by helmling** [Hammerspoon/hammerspoon#2515]
Doing: hs.window.focusedWindow():focusWindowEast(nil,true,true)
gives me a: attempt to call a nil value (method 'focusWindowEast')

Console:

>  hs.window.focusedWindow():focusWindowEast(nil,true,true)
[string "return  hs.window.focusedWindow():focusWindow..."]:1: attempt to call a nil value (method 'focusWindowEast')
stack traceback:
	[string "return  hs.window.focusedWindow():focusWindow..."]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:514: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:494>

**Comment by latenitefilms** [comment]
I believe this has been fixed in #2488 - so should be fixed in the next release, or you could build Hammerspoon yourself using the latest code in the `master` branch.

**Comment by helmling** [comment]
Just tested - almost fixed: line 576 also needs to get changed (window -> objectMT), than it works.

Thanks

**Comment by latenitefilms** [comment]
Pinging @asmagill - as he's been doing the `hs.window` fixes.

**Comment by asmagill** [comment]
Fixed in master
