### ISSUE TITLE
Add ability to delete stale drawing objects

### ISSUE THREAD

**Issue by sheijk** [Hammerspoon/hammerspoon#252]
Currently objects created by hs.drawing will stay around forever even when reloading the config. So when they are never hidden or deleted they will stay on the screen forever. This requires the user to restart Hammerspoon when it happens. It would be nice to have an API to either enumerate over all existing/visible drawing objects or at least to be able to delete all of them so a config reload could clean up.

**Comment by cmsj** [comment]
Good catch, not sure why I didn't spot this, but it'll be fixed in the next release!

**Comment by cmsj** [comment]
(and by fixed I mean that all drawing objects will be removed when the config is reloaded)
