### ISSUE TITLE
hs.application.open() does not open app, only switches to it

### ISSUE THREAD

**Issue by 12-Seconds** [Hammerspoon/hammerspoon#2531]
In my init.lua, I have the following:

```
hs.hotkey.bind({"alt"}, "space", function()
  local alacritty = hs.application.find('alacritty')
  if alacritty:isFrontmost() then
    alacritty:hide()
  else
    hs.application.open("/Applications/Alacritty.app")
  end
end)
```

However, this only switches to the specified app, and does not open it when it is closed.

**Comment by latenitefilms** [comment]
That's strange. What version of Hammerspoon are you running?

If I use TextEdit as an example, this launches TextEdit for me:

```lua
hs.application.open("/Applications/TextEdit.app")
```

You could also try [`hs.application.launchOrFocus()`](http://www.hammerspoon.org/docs/hs.application.html#launchOrFocus)?

**Comment by 12-Seconds** [comment]
I'm using the most recent version of Hammerspoon, 0.9.80, and `hs.application.launchOrFocus()` does not work either

**Comment by latenitefilms** [comment]
Ah, I think I see the problem - try this:

```lua
hs.hotkey.bind({"alt"}, "space", function()
    local alacritty = hs.application.find('alacritty')
    if alacritty and alacritty:isFrontmost() then
        alacritty:hide()
    else
        hs.application.open("/Applications/Alacritty.app")
    end
end)
```

If Alacritty is not running then `alacritty` will be `nil`.

**Comment by 12-Seconds** [comment]
Yes, this works now. Thank you!
