### ISSUE TITLE
Help with hs.geometry

### ISSUE THREAD

**Issue by lanox** [Hammerspoon/hammerspoon#2534]
Hi
I am stuck and I am not sure how to fix this problem, I have the following code, 

```
local function tileWindows()
	local wins = hs.window.filter.new():setCurrentSpace(true):getWindows()
  for k,v in pairs(wins) do print("Windows",k,v) end
	local screen = hs.screen.mainScreen():frame()
	local rect = hs.geometry.rect(screen['x'], screen['y'], screen['w'], screen['h'])
	hs.window.tiling.tileWindows(wins, rect)
end

hs.hotkey.bind(cap_lock_hyper, 't', tileWindows)
```

That almost works where I arranges my windows on the screen, however, I can't seem to work out how I can tell the last window to use all the space that is free.
Eg:
Below is the image you can see where the console window is the same size as all others.

<img width="2880" alt="Screen Shot 2020-09-29 at 2 55 34 pm" src="https://user-images.githubusercontent.com/7599183/94514161-dc8a4880-0263-11eb-962d-4219227e25c6.png">

However, I would like it to be something like this if there are no more active windows.

<img width="2879" alt="Screen Shot 2020-09-29 at 1 30 05 pm" src="https://user-images.githubusercontent.com/7599183/94509829-98de1180-0258-11eb-8d4e-6ee788b28244.png">

any suggestions would be appreciated.
Thanks

**Comment by latenitefilms** [comment]
I'm not sure how to solve your specific problem, however, I do note that [`hs.screen.mainScreen():frame()`](http://www.hammerspoon.org/docs/hs.screen.html#frame) actually returns a `hs.geometry rect` object, so you can feed that directly into [`hs.window.tiling.tileWindows`](http://www.hammerspoon.org/docs/hs.window.tiling.html#tileWindows).

I'm not sure this is relevant in this particular case, but there are known issues in Hammerspoon v0.9.79 and v0.9.80 to do with `hs.window`, so it may be worth trying your code with v0.9.78 to see if you get different results.

One thought is that maybe `wins` actually has more window objects in it than you actually want (i.e. I count 5 windows on your screenshots, but the Console looks like it's detecting a lot more than 5?).

**Comment by lanox** [comment]
Hrm, you are right, it seems that Microsoft Teams notification was getting somehow picked up even tho the windows was minimised, and that is why it had that blank space there. 

When I killed Microsoft Teams and all windows tiled although it changed arrangement of windows to different positioning.
 I am not sure how it determines positioning. 

<img width="2880" alt="Screen Shot 2020-09-29 at 3 00 51 pm" src="https://user-images.githubusercontent.com/7599183/94514461-997ca500-0264-11eb-893f-1d260e5359bd.png">

**Comment by lanox** [comment]
Does anyone have any suggestions, I can't seem to work out the order that windows are been arranged.

**Comment by latenitefilms** [comment]
I've never used `hs.window.tiling`, but have you tried experimenting with the `desiredAspect`, `processInOrder`, and `preserveRelativeArea` options?

**Comment by lanox** [comment]
I have but I can't seem to get it to work with my code, or I am not doing something right, this is what I am doing.
```hs.window.tiling.tileWindows(wins, rect):processInOrder(true) ```

**Comment by latenitefilms** [comment]
Reading the documentation, I think you'd need to do something like:

```lua
local desiredAspect = true
local processInOrder = true
local preserveRelativeArea = true
local animationDuration = 1

hs.window.tiling.tileWindows(wins,rect,desiredAspect,processInOrder,preserveRelativeArea,animationDuration)
```

**Comment by lanox** [comment]
thank @latenitefilms I tried that as well and I was getting following error.

```
2020-09-30 11:42:36: 11:42:36 ERROR:   LuaSkin: hs.hotkey callback: ...n.app/Contents/Resources/extensions/hs/window/tiling.lua:95: Cannot create geometry object, wrong arguments
stack traceback:
	[C]: in function 'error'
	...n.app/Contents/Resources/extensions/hs/geometry/init.lua:138: in function 'hs.geometry.new'
	...n.app/Contents/Resources/extensions/hs/window/tiling.lua:95: in function 'hs.window.tiling.tileWindows'
	/Users/lpuljic/.hammerspoon/tile-windows/tile-windows.lua:14: in function </Users/lpuljic/.hammerspoon/tile-windows/tile-windows.lua:5>
```

**Comment by asmagill** [comment]
Looking at the docs for [hs.window.tiling.tileWindows](https://www.hammerspoon.org/docs/hs.window.tiling.html#tileWindows), `desiredAspect` isn't supposed to be a boolean, but rather "an `hs.geometry` size (or constructor argument) or a number, indicating the desired optimal aspect ratio (width/height) of the tiled". The "constructor argument" must be one of the types listed at the top of [hs.geometry](https://www.hammerspoon.org/docs/hs.geometry.html). If you want the default aspect used by the module, specify it as `nil`.

**Comment by lanox** [comment]
Thank you to both, I got this working not exactly how I want it but it works, I am just not 2 sure how it actually figures out arrangement but it will do.
