### ISSUE TITLE
Add a global window event watcher

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#254]
We have hs.application.watcher for global application events, but no equivalent for window events (creation, destruction, moving, resizing, etc)

AFAICS there's no global window event mechanism in the OS X SDK, so instead this would have to operate at the application level, creating hs.uielement.watchers for each app, to monitor its windows, and then dispatch those events to subscribers.

(While this could be implemented in objc, it would just be repeating what's already in hs.application.watcher and hs.uielement.watcher, so this would probably make the most sense to be done in pure Lua, building on those extensions)

**Comment by cmsj** [comment]
Something like https://gist.github.com/cmsj/591624ef07124ad80a1c might well do here (that gist is forked from @tmandry 's gist repo)

**Comment by cmsj** [comment]
Anyone fancy getting that in shape to be hs.window.watcher? :D

**Comment by tmandry** [comment]
@cmsj I have updated the code since that gist, here's the version I have now: https://gist.github.com/tmandry/43ca021fbd3fb8b42a20

Can you tell if anything further needs to be done on it? Or is it pretty much in good shape to be incorporated into HS?

**Comment by cmsj** [comment]
This is covered by #374
