### ISSUE TITLE
Question about hs.socket garbage collection?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2547]
@asmagill - I'm not sure if this is an issue or not, but just having a look at the `hs.socket` [code](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/socket/internal.m#L688), I noticed that the userdata is being cleared before the socket is disconnected. Is this an issue at all?

```objc
static int userdata_gc(lua_State *L) {
    asyncSocketUserData *userData = lua_touserdata(L, 1);
    HSAsyncTcpSocket* asyncSocket = (__bridge_transfer HSAsyncTcpSocket *)userData->asyncSocket;
    userData->asyncSocket = nil;

    LuaSkin *skin = [LuaSkin sharedWithState:L];
    [asyncSocket disconnect];
    [asyncSocket setDelegate:nil delegateQueue:NULL];
    asyncSocket.readCallback = [skin luaUnref:refTable ref:asyncSocket.readCallback];
    asyncSocket.writeCallback = [skin luaUnref:refTable ref:asyncSocket.writeCallback];
    asyncSocket.connectCallback = [skin luaUnref:refTable ref:asyncSocket.connectCallback];
    asyncSocket = nil;

    return 0;
}
```

**Comment by asmagill** [comment]
From what I can determine, I don't *think* this is an issue. It appears that the specific `asyncSocketUserData` structure isn't really used anywhere except in `new` and `gc` and could theoretically be removed entirely... (well, every other method technically uses it in the `getUserData` macro which just returns the `asyncSocket` member of the structure, but unnecessarily... from what I can determine the rest of the structure is ignored everywhere.)

And in terms of system callbacks, it's the `HSAsyncTcpSocket : GCDAsyncSocket` object (i.e. the `asyncSocket` member of the structure) that is actually sent to the delegate, so even if through some hiccup of timing on differing threads a callback was already in the application queue, the callbacks are all set to LUA_NOREF by the time that `asyncSocket` in the scope of `userdata_gc` reaches a retain count of 0 (i.e. the last line before the return).

I'm guessing that during development of this module the exact understanding of what was needed in the userdata structure changed or evolved... while the code could be cleaned up and simplified a bit, I don't see an obvious error or gotcha... that said, if you have evidence to the contrary, let me know... this is just my assessment after reviewing the code for all of 15 minutes or so -- nothing crash inducing is obvious, at least not yet... Should I keep looking?

**Comment by latenitefilms** [comment]
Awesome, thanks! Nope - no crashes, so all good there. I'm just looking for potential memory leaks, as I'm still trying to hunt down why sometimes Hammerspoon's memory usage keeps dramatically growing over time. Thanks @asmagill!
