### ISSUE TITLE
Add proxy table support for NSDictionary to LuaSkin

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2549]
As @cmsj experimented with here:

https://github.com/Hammerspoon/hammerspoon/commit/5d7721de1d0e782ed985948786ae1820ecd16a69

Something like this might be useful if/when @asmagill looks into `hs.plist/hs.preferences`?

**Comment by asmagill** [comment]
It's already in there for `hs.doc`. Get why I was so annoyed at myself in https://github.com/Hammerspoon/hammerspoon/issues/2544#issuecomment-702546832 for not documenting LuaSkin better now?

**Comment by latenitefilms** [comment]
Ahhhhh, sweet. I'll have a look at the LuaSkin code at some point then!
