### ISSUE TITLE
Question: how to keep reading from hs.socket.server

### ISSUE THREAD

**Issue by CantGetRight82** [Hammerspoon/hammerspoon#2550]
I'm trying to facilitate some communication between Hammerspoon and NodeJS and decided to use a unix socket.

I am able to create a server with ```hs.socket.server``` and connect to it from NodeJS.
However, it seems like I have to call ```hs.socket:read()``` repeatedly to see if there is any data available.

Is there a way to have Hammerspoon just call the callback function whenever there is data available? Or do I really need to employ some sort of polling mechanism myself?

**Comment by latenitefilms** [comment]
The TCP protocol is modelled on the concept of a single continuous stream of unlimited length. Have a read of [this](https://github.com/robbiehanson/CocoaAsyncSocket/wiki/CommonPitfalls) for further explanation.

Have a look at `hs.tangent`'s [code](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/tangent/init.lua#L1701) to see how you can use `hs.socket` in Hammerspoon.

Hope this helps!

**Comment by CantGetRight82** [comment]
Ah this really helps!
I
n NodeJS it looks like some of these internals are abstracted away from the user (perhaps by assuming a newline delimiter).

Thank you very much!
