### ISSUE TITLE
XQuartz does not respond to hammerspoon-defined shortcuts

### ISSUE THREAD

**Issue by gbelanger** [Hammerspoon/hammerspoon#2563]
I googled and looked through the issues, but can't find anything about the fact that XQuartz windows are the only ones that don't respond to the keyboard hammerspoon window-resizing shortcuts defined in init.lua. Did I miss something somewhere? Can you tell if there's something I need to do to make this work?

I'm running 
- macOS 10.15.7 on a new MacBook pro
- XQuartz 2.7.11 (xorg-server 1.18.4)

**Comment by asmagill** [comment]
X11 (i.e. XQuartz) windows are not macOS windows in the traditional sense and do not implement the accessibility API requirements that Hammerspoon uses to manipulate the windows of other applications. At present there is no workaround.  #164 and #2315 mention some external command line tools, `xdotool` and `wmctrl` that might be used to mimic the behaviors of `hs.window`, but to my knowledge no one has actually explored this or written any sort of wrapper to take advantage of them.

**Comment by gbelanger** [comment]
Once again, thank you very much for the lightning speed response! I'll close the issue. It might be good to put this somewhere visible, like in the readme. Most of us who like to manipulate stuff quickly with keyboard shortcuts usually also use X11, I thought. But maybe not. Anyway, thanks again.
