### ISSUE TITLE
how to stop multiple hs.timer.doUntil loop simultaneously

### ISSUE THREAD

**Issue by akahanaton** [Hammerspoon/hammerspoon#2577]
Hi guys: 
I have multiple doUntil loops with different time intervals, something like:
```
timer1 = hs.timer.doUntil(stopBuffs,  startBuffs1, 2)
timer2 = hs.timer.doUntil(stopBuffs,  startBuffs2, 3)
timer3 = hs.timer.doUntil(stopBuffs,  startBuffs3, 5)
timer4 = hs.timer.doUntil(stopBuffs,  startBuffsLeftMouse, 5)
timer5 = hs.timer.doUntil(stopBuffs,  startBuffsRightMouse, 5)
```
currently, I use one single function, the _sotpBuffs_ ,  as the predicateFn to control all those actionFn. the _sotpBuffs_ detect some hotkey binding to stop the doUntil loop.
However, those actionFn cannot be stopped simultaneously, I need press the hotkey for five times to stop all the loops, cause there five loops. Any suggestions to optimize those code? thank you very much.

Best regards,

**Comment by latenitefilms** [comment]
Untested, but is something like this what you're thinking?

```lua
local timers = {}
local doUntil = require("hs.timer").doUntil
timers[1] = doUntil(stopBuffs,  startBuffs1, 2)
timers[2] = doUntil(stopBuffs,  startBuffs2, 3)
timers[3] = doUntil(stopBuffs,  startBuffs3, 5)
timers[4] = doUntil(stopBuffs,  startBuffsLeftMouse, 5)
timers[5] = doUntil(stopBuffs,  startBuffsRightMouse, 5)
for _, t in pairs(timers) do
t:stop()
end
```

**Comment by akahanaton** [comment]
Hi Chris, thanks for your help. Sorry,  this is not I want. The t:stop() stopped the doUntil immediately, what I want is, the five doUntill loops continue  until I press a hotkey to invoke the _stopBuffs_ function, then the five loops stop. 
Best regards,

**Comment by akahanaton** [comment]
Ok, I find a solution for this, use doEvery and then terminate all the loops by t:stop(), thank you so much
