### ISSUE TITLE
Lua 5.4.2 heads up

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#2587]
@cmsj, Just a heads up (it's not ready quite yet):

The lua team is apparently testing 5.4.2 out at the moment... no official statement that I've found about release candidates or dates yet, but I think this is one we'll probably want to update to once it is available.

From a comment by Roberto re recursion in C functions invoked within coroutines (I've been trying to move away from recursion where the alternative isn't too annoying to implement, but I think there are a few places where we still rely on it):

> Re: Lua 5.4 bug with coroutines
>
> .. stuff cut for brevity ...
>
> See the function debug.setcstacklimit. You probably has to set a
> larger C stack. (Or wait for 5.4.2; we are reversing back to a
> stackless implementation, which uses less C-stack space.)
>
> -- Roberto

When 5.4.2 does finally drop, it might also be a good time to try and see how hard implementing #2479 might be.

**Comment by llity** [comment]
I used lua5.3, and found moonscripts do not work for hs.

**Comment by asmagill** [comment]
@llity see https://github.com/Hammerspoon/hammerspoon/issues/2591#issuecomment-725807785

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - Looks like Lua 5.4.2 is [out now](https://www.lua.org/news.html)!

**Comment by cmsj** [comment]
5.4.2 merged in #2717
