### ISSUE TITLE
version 0.9.79 - 0.9.81 not found moonscript but 0.9.78 support

### ISSUE THREAD

**Issue by LuciusChen** [Hammerspoon/hammerspoon#2591]
2020-11-12 08:40:29: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-11-12 08:40:29: -- Lazy extension loading enabled
2020-11-12 08:40:29: -- Loading ~/.hammerspoon/init.lua
2020-11-12 08:40:29: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: module 'moonscript' not found:
	no field package.preload['moonscript']
	no file '/Users/luciuschen/.hammerspoon/moonscript.lua'
	no file '/Users/luciuschen/.hammerspoon/moonscript/init.lua'
	no file '/Users/luciuschen/.hammerspoon/Spoons/moonscript.spoon/init.lua'
	no file '/usr/local/share/lua/5.4/moonscript.lua'
	no file '/usr/local/share/lua/5.4/moonscript/init.lua'
	no file '/usr/local/lib/lua/5.4/moonscript.lua'
	no file '/usr/local/lib/lua/5.4/moonscript/init.lua'
	no file './moonscript.lua'
	no file './moonscript/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/moonscript.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/moonscript/init.lua'
	no file '/Users/luciuschen/.hammerspoon/moonscript.so'
	no file '/usr/local/lib/lua/5.4/moonscript.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './moonscript.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/moonscript.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
	/Users/luciuschen/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by llity** [comment]
I have the same issue. Please fix it.

**Comment by asmagill** [comment]
Follow the instructions at https://github.com/Hammerspoon/hammerspoon/wiki/Luarocks-and-Hammerspoon#version and then reinstall the moonscript luarocks.
