### ISSUE TITLE
Is putting an hs.image as icon on hs.menubar supposed to work?

### ISSUE THREAD

**Issue by Madd0g** [Hammerspoon/hammerspoon#2611]
I tried putting a jpeg image as an icon in a menubar but it's just showing up as a white square.

(I tried with my avatar here from github for example, results in this behavior:

![image](https://user-images.githubusercontent.com/1171003/100965019-a1fc9080-34de-11eb-9de0-243b8dee8dbe.png)

```lua
menu = hs.menubar.new()
local img = hs.image.imageFromURL(url):setSize({h=16, w=16})
menu:setIcon(img)
menu:setTitle('hello world')
```

i tried dumping the image to a string and it looks ok as a string. but is showing up as a white square in the menu.

**Comment by luckman212** [comment]
I don't think JPG works - try PNG or PDF

**Comment by Madd0g** [comment]
Ah that's unfortunate, I'm getting it from a url, so I have no control over it.
I wish I could easily convert it on the fly, but I don't think I want to get into saving it to disk, converting and then loading from disk again.

**Comment by dasmurphy** [comment]
This works for me...
```lua
menu = hs.menubar.new()
url = 'https://avatars1.githubusercontent.com/u/1171003?s=88&v=4'
local img = hs.image.imageFromURL(url):setSize({h=16, w=16})
menu:setIcon(img,false)
```
I used your avatar url for tests...

![ychlm5gz4wzrk67kv08fipianmi1qlnv](https://user-images.githubusercontent.com/941826/101292929-ccb65400-3812-11eb-8f1e-b0e3993a44c3.png)

You need to use `setIcon` with `false`, otherwise it would be used as a template, which converts it to b/w for displaying with normal- and darkmode.

**Comment by Madd0g** [comment]
@dasmurphy - wow it works, thank you very much!

I think during my tests I tried passing `true` there but that's what I get for not reading the docs carefully enough, I totally missed that true is the default
