### ISSUE TITLE
make docs fails

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#2615]
@cmsj, with your latest additions (and yes, I ran the commands in `scripts/github-ci-pre.sh` to make sure python3 had what was required), I get the following:

~~~sh
% make docs
scripts/docs/bin/build_docs.py -o build/ --json Hammerspoon/ extensions/
scripts/docs/bin/build_docs.py -o build/ --sql Hammerspoon/ extensions/
Traceback (most recent call last):
  File "scripts/docs/bin/build_docs.py", line 617, in <module>
    main()
  File "scripts/docs/bin/build_docs.py", line 605, in main
    write_sql(arguments.output_dir + "/docs.sqlite", results)
  File "scripts/docs/bin/build_docs.py", line 462, in write_sql
    cur.execute("VACUUM;")
sqlite3.OperationalError: cannot VACUUM from within a transaction
make: *** [build/docs.sqlite] Error 1
~~~

**Comment by cmsj** [comment]
Darn. I'll look into it, thanks!

**Comment by asmagill** [comment]
Wondered if the fix would be that simple, but wasn't sure if you had them in that order for a specific reason or not.

I'd like to try and land a few of the outstanding pulls over the next few days... what automated testing errors should I be worried about and which can I ignore? Or would you rather I hold off until you're done with your current tests/changes?

**Comment by cmsj** [comment]
Go for it, we ought to be in a place where the CI runs are as reliable as they ever are (ie there are a few individual tests that fail sometimes for reasons I can't explain), and if the Actions stuff needs some fixes because it fails for infrastructure reasons, it'll be helpful to uncover them :)
