### ISSUE TITLE
NSInternalInconsistencyException: createLuaState was unable to find luaskin.lua

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2632]
@asmagill - I just spotted this crash in Sentry for CommandPost. Any ideas what's going on?

https://sentry.io/share/issue/8e6e2eeac58040daac5e6ace4f07abeb/

**Comment by asmagill** [comment]
There is a lua file that has been included within the LuaSkin framework for some time now... in the source it should be at `../LuaSkin/LuaSkin/luaskin.lua` and in the built application at `../Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A/Resources/luaskin.lua`.

I think one of the interim stages of one of my recent pull requests had a broken version of the file, but I'm 99% certain I immediately pushed the fix... if you've merged in any of my recent pull requests, make sure it's in the latest state. If you find that I've missed something, let me know!

**Comment by latenitefilms** [comment]
Yeah, that's the weird part - the `luaskin.lua` file is definitely there, and the same build is working fine on my Intel machines on both Mojave & Big Sur. The Sentry crash is from some random user - I'm just not sure how they would have gotten to this state. I wonder if there's some kind of bug in there somewhere where `luaskin.lua` can fail to load under certain circumstances?

**Comment by latenitefilms** [comment]
I haven't seen this pop up again, so I'm just going to close this issue for now.
