### ISSUE TITLE
hs.chooser not using full width

### ISSUE THREAD

**Issue by meain** [Hammerspoon/hammerspoon#2633]
![Screenshot 2020-12-27 at 8 25 05 PM](https://user-images.githubusercontent.com/14259816/103173557-d49d6d00-4881-11eb-9b09-6b7ce9ee8682.png)

`hs.chooser` not taking up the full width assigned to it. This happens with/without setting custom width. There is always some space to the right of the chooser as long as the width is not a really small amount(like ~30%).

**Comment by latenitefilms** [comment]
I just noticed this as well. As far as I can tell, nothing has changed recently in `hs.chooser` so may be related to the fact Hammerspoon has been compiled in Big Sur? @cmsj ?

**Comment by latenitefilms** [comment]
Are you able to replicate @asmagill ?

**Comment by latenitefilms** [comment]
To clarify, I'm seeing this on Hammerspoon 0.9.82 (5614) using this simple example code:

```lua
local eventtap = require("hs.eventtap")
local chooser = require("hs.chooser")

local completionFn = function(result)
    if result and result.code then
        hs.eventtap.keyStrokes(result.code)
    end
end

local exampleCode = [[| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |]]

local function getChoices()
	return {
		{ 
		    ["text"] = "Example 1",
		    ["subText"] = "This is a markdown table example.",		        
		    ["code"] = exampleCode,
		},
		{ 
		    ["text"] = "Example 2",
		    ["subText"] = "This is a markdown table example.",		        
		    ["code"] = exampleCode,
		},		
	}
end

codeChooser = chooser.new(completionFn):choices(getChoices):show()
```

**Comment by latenitefilms** [comment]
FYI: I tried opening the chooser XIB in Xcode running on Big Sur, and it automatically made some changes, and whilst it looked correct in Big Sur, when I went back to Mojave it was still broken. However, I just tried doing the same thing on Xcode running on Mojave, and it seemed to fix things for Mojave. I'll try using this modified XIB in Xcode on Big Sur and see what happens.

**Comment by latenitefilms** [comment]
I tried updating the XIB in Mojave, then opening it again in Big Sur, then compiling in Big Sur, and whilst it still works great in Big Sur, in Mojave, you still have the same problem - doh!

**Big Sur:**

<img width="784" alt="Big Sur" src="https://user-images.githubusercontent.com/22286696/104092284-1513d680-52d7-11eb-99fe-6cb7e6b1e65b.png">

**Mojave:**

<img width="869" alt="Mojave" src="https://user-images.githubusercontent.com/22286696/104092289-1cd37b00-52d7-11eb-984c-327016192deb.png">

**Comment by meain** [comment]
I just upgraded from Cataline to Big Sur and the issue does not seem to be happening anymore.

**Comment by latenitefilms** [comment]
Do you still have Mojave or Catalina lying around @asmagill ? I've tried a few things to try and fix this, but no luck thus far.

**Comment by latenitefilms** [comment]
FYI: I just tried updating to the latest Xcode update on Big Sur, but that made no impact sadly.

**Comment by cmsj** [comment]
I have my hs.chooser set to be very wide and I've never been able to get the shortcuts to move to the very right side of the window, and I have no idea why. I've tried adding autolayout constraints to force them to be there, and they still don't move.

Honestly, hs.chooser's UI is such a mess, I'm kind of resigned to waiting another 2 years until our minimum supported release is 10.15 so I can rewrite it with SwiftUI.

**Comment by latenitefilms** [comment]
Huh, I've never noticed `hs.chooser:width()` before.

I can confirm that using a wider width such as `80` also reproduced a similar issue on Mojave.

```lua
local eventtap = require("hs.eventtap")
local chooser = require("hs.chooser")

local completionFn = function(result)
    if result and result.code then
        hs.eventtap.keyStrokes(result.code)
    end
end

local exampleCode = [[| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |]]

local function getChoices()
	return {
		{ 
		    ["text"] = "Example 1",
		    ["subText"] = "This is a markdown table example.",		        
		    ["code"] = exampleCode,
		},
		{ 
		    ["text"] = "Example 2",
		    ["subText"] = "This is a markdown table example.",		        
		    ["code"] = exampleCode,
		},		
	}
end

codeChooser = chooser.new(completionFn):choices(getChoices):width(80):show()
```

<img width="2071" alt="Screen Shot 2021-02-15 at 11 51 23 am" src="https://user-images.githubusercontent.com/22286696/107894583-2e6a0b80-6f84-11eb-8028-9ad8ff6115ac.png">

However, I did noticed that in Interface Builder if I make the window much bigger, the rows didn't go the full width of the table, so I changed the maximum table column constraint, which seemed to fix things:

<img width="1310" alt="Screen Shot 2021-02-15 at 11 59 34 am" src="https://user-images.githubusercontent.com/22286696/107894904-5efe7500-6f85-11eb-85ec-11eec9b6dcef.png">

<img width="2070" alt="Screen Shot 2021-02-15 at 12 05 33 pm" src="https://user-images.githubusercontent.com/22286696/107895083-27dc9380-6f86-11eb-9352-3e3dac13524a.png">

I think the only change needed is changing:

```
<tableColumn editable="NO" width="496" minWidth="40" maxWidth="1000" id="U09-Ar-y6G">
```

to:

```
<tableColumn editable="NO" width="496" minWidth="40" maxWidth="90000" id="U09-Ar-y6G">
```

Will have a go at compiling on Big Sur and testing on Mojave later today to see if it actually fixes things.

**Comment by cmsj** [comment]
@latenitefilms oh wow, incredibly good find there. I don't think I had any idea that a max width property even existed, let alone would be respected while AutoLayout is being used. Thanks very much for that!

**Comment by latenitefilms** [comment]
FYI: @cmsj - I can't solve this (I assume it's an Xcode bug?), so I've submitted an Apple Developer Technical Support request. We'll see what they come back with.

**Comment by Rhys-T** [comment]
For what it's worth, this seems (at least on my Catalina system) to be the result of the table column's `width`, _not_ its `minWidth`/`maxWidth`. I'm actually not sure why it's working right on the newer systems. I'm currently working around it with a custom extension module that wraps `hs.chooser.new` and sets the `width` equal to the `maxWidth` on each new chooser's table column (so that I don't have to modify the XIB every time).
