### ISSUE TITLE
Garbage Collection not running correctly?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2635]
After leaving my computer running for a while, on return I saw that CommandPost was taking up a LOT of application memory:

<img width="539" alt="Screen Shot 2020-12-28 at 2 09 47 pm" src="https://user-images.githubusercontent.com/22286696/103187033-f0068780-4916-11eb-9306-2e857899baef.png">

So I ran this:

```lua
> hs.crash.attemptMemoryRelease()
2020-12-28 14:11:16: Process resident size: 325603328
2020-12-28 14:11:16: Lua state size: 33938878
2020-12-28 14:11:16: Process resident size: 325611520
2020-12-28 14:11:16: Lua state size: 28161794
```

...which fixed the issue:

<img width="539" alt="fixed" src="https://user-images.githubusercontent.com/22286696/103187149-6a370c00-4917-11eb-99b3-9ebcc5225cfb.png">

It just so happened that I also ran @asmagill's `drEval()` function before and after - incase this is helpful:

https://gist.github.com/latenitefilms/d8cbe5339288358a4771c139c2ff035f

At some point in CommandPost's history I actually had `collectgarbage()` running on a `hs.timer` every 15mins, but removed that code at some point, as I figured it wasn't a great idea. However, I'm now wondering if I should add it back in?

@asmagill - Is it possible that something in Hammerspoon or CommandPost's code is preventing the Lua garbage collection from happening? Any thoughts or ideas?

**Comment by latenitefilms** [comment]
It is possible that Garbage Collection only runs when Hammerspoon is the frontmost/active application? I just noticed that CommandPost was increasing in memory usage, and then a few seconds after making the Error Console active, the memory usage dramatically dropped?

**Comment by asmagill** [comment]
Frontmost shouldn't matter, but processing some sort of lua code would (the lua code could be in a callback or timer, it doesn't have to be something you typed into the console).

I know that Lua 5.4.2 is supposed to revert a change that was made in C-stack management, but I don't know the details... as I recall, the discussion on the list centered around recursion being less efficient with 5.4 than in 5.3, but it may impact memory as well, so I'd be interested in knowing if that makes a difference, once we upgrade lua (@cmsj, is that something you think you'll be able to do in say the next week, or do you want me to give it a shot? I know you make some modifications for capturing exceptions, but I'm pretty sure I can figure that our by comparing against the stock releases... are there other mods I should be aware of?)

**Comment by latenitefilms** [comment]
> but processing some sort of lua code would (the lua code could be in a callback or timer, it doesn't have to be something you typed into the console)

Sorry, could you explain a bit more what you mean by this? A lot of our code is wrapped in `hs.timer`'s.

**Comment by asmagill** [comment]
Lua garabage collection is interleaved with the execution of lua code (and in fact can occur in between any two distinct lua commands, as I discovered when working on hs.window.filter a short while back), so whenever Hammerspoon is executing Lua code, garbage collection can occur. 

If you have a Hammerspoon instance with no timers, no callbacks, no watchers registered, etc. and it has only run code that you manually type into the console, then, and only then, would Hammerspoon being frontmost impact whether or not garbage collection could occur.

If any type of mac activity (timer, delegate callback, etc.) triggers a lua callback, then even if Hammerspoon isn't in the foreground, it's running Lua code, so lua garbage collection can occur.

However, now that I think about it, it is just *Lua* garbage collection that I'm talking about... I can't say if Big Sur has changed anything about the way Arc handles Objective-C garbage collection, though that should affect *all* macOS apps, not just us, if that was the case...

**Comment by latenitefilms** [comment]
Legend, thanks @asmagill ! Well, I definitely have lots of timers and callbacks running, so I'm just going to close this issue for now then.
