### ISSUE TITLE
hs.window:focusedWindow() issue after upgrade

### ISSUE THREAD

**Issue by fmaiabatista** [Hammerspoon/hammerspoon#2636]
Hi all,

I've got a very simple config that used to work but is not working anymore when I updated HS to version 0.9.82.

<pre><code>
2020-12-28 11:57:37: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-12-28 11:57:38: -- Lazy extension loading enabled
2020-12-28 11:57:39: -- Loading ~/.hammerspoon/init.lua
2020-12-28 11:57:39: -- Loading Spoon: ReloadConfiguration
2020-12-28 11:57:39: -- Loading extension: pathwatcher
2020-12-28 11:57:39: -- Loading extension: notify
2020-12-28 11:57:39: -- Loading extension: grid
2020-12-28 11:57:39: -- Loading extension: hotkey
2020-12-28 11:57:39: 11:57:39     hotkey: Enabled hotkey ⌥G
2020-12-28 11:57:39:              hotkey: Enabled hotkey ⌥1
2020-12-28 11:57:39:              hotkey: Enabled hotkey ⌥2
2020-12-28 11:57:39:              hotkey: Enabled hotkey ⌥3
2020-12-28 11:57:39:              hotkey: Enabled hotkey ⌥4
2020-12-28 11:57:39:              hotkey: Enabled hotkey ⌥5
2020-12-28 11:57:39: -- Done.
2020-12-28 11:58:17: -- Loading extension: window
<strong>2020-12-28 11:58:17: 11:58:17
ERROR: LuaSkin: hs.hotkey callback: /Users/fmaiabatista/.hammerspoon/init.lua:18
ERROR: incorrect number of arguments. Expected 0, got 1
stack traceback:
	[C]: in function 'hs.window.focusedWindow'
	/Users/fmaiabatista/.hammerspoon/init.lua:18:
        in function &lt;/Users/fmaiabatista/.hammerspoon/init.lua:17&gt</strong>
</pre></code>

My script is

<pre><code>
-- Automatically watch for changes and reload config

hs.loadSpoon("ReloadConfiguration")
spoon.ReloadConfiguration:start()
hs.notify.new({title="Configuration loaded"}):send()

-- Window Management Utilities
-- Defines the Grid

hs.grid.ui.textSize = 50
hs.grid.setGrid("16x12")

hs.hotkey.bind({"alt"}, "G", function()
    hs.grid.toggleShow()
end)

hs.hotkey.bind({"alt"}, "1", function()
    local win = hs.window:focusedWindow() <strong><em>-- <<< line 18 </em></strong>
    hs.grid.set(win, {1, 1, 14, 10})
end)

hs.hotkey.bind({"alt"}, "2", function()
    local win = hs.window:focusedWindow()
    hs.grid.set(win, {0, 0, 8, 12})
end)

hs.hotkey.bind({"alt"}, "3", function()
    local win = hs.window:focusedWindow()
    hs.grid.set(win, {8, 0, 8, 12})
end)

hs.hotkey.bind({"alt"}, "4", function()
    local win = hs.window:focusedWindow()
    hs.grid.set(win, {3, 2, 10, 8})
end)

hs.hotkey.bind({"alt"}, "5", function()
    local win = hs.window:focusedWindow()
    hs.grid.set(win, {5, 2, 6, 8})
end)
</pre></code>

I looked for issues that addressed this specific method on the window object but couldn't find anything related but other hs.window regression issues.

Also, the API at https://www.hammerspoon.org/docs/hs.window.html#focusedWindow seems to be the same.

**Comment by latenitefilms** [comment]
It's a function, not a method.

Try:

`hs.window.focusedWindow()`

...instead of:

```
hs.window:focusedWindow()
```

**Comment by fmaiabatista** [comment]
It worked, thanks a lot!

Just to confirm that this has changed, right? Now I see the API has a `.` instead of the `:`. That code used to work in a previous version.

**Comment by benhsmith** [comment]
@fmaiabatista I was just setting up a new laptop and run into the same thing. Seems to have been quietly changed.

**Comment by cmsj** [comment]
We rewrote hs.application, hs.window and hs.uielement about a year ago, so it was probably 0.9.79 in September where the change became visible to users.
It worked before because those modules were among the oldest in Hammerspoon and didn't do a good job of differentiating between module-level functions and object-level methods.
