### ISSUE TITLE
Unix domain sockets support

### ISSUE THREAD

**Issue by bviefhues** [Hammerspoon/hammerspoon#2637]
Would be great if Hammerspoon supported Unix domain sockets.

That wouuld allow implementing a Lua library/spoon for interacting with [yabai](https://github.com/koekeishiya/yabai), for example.

**Comment by MuhammedZakir** [comment]
Have you tried `hs.socket` [1]?

[1] http://www.hammerspoon.org/docs/hs.socket

**Comment by bviefhues** [comment]
@MuhammedZakir thanks for pointing out. Did not ralize hs.socket does support this already.

**Comment by asmagill** [comment]
`hs.socket` supports TCP and UDP style sockets, not unix file type sockets. This comes up every so often and its probably time to add it to the wish list.

**Comment by bviefhues** [comment]
@asmagill Haven't tried yet, but the `hs.socket` documentation says it supports UNIX domain sockets.

**Comment by asmagill** [comment]
Hmm... The header portion of the docs doesn’t mention it, and thats as far as I read before posting... I seem to recall that they weren’t properly supported when the module was first added, but it has been a while or maybe an update I forgot about was made. You are correct that they are explicitly mentioned in some of the function/method documentation.

I’ll give it a shot later tonight and assuming it works, change the feature request I posted to a  request to clarify in the docs.
