### ISSUE TITLE
Unable to use the letter 's' as a trigger in hotkey modal

### ISSUE THREAD

**Issue by iamdana** [Hammerspoon/hammerspoon#264]
I'm using hotkey modal for text expansion. 

For example, I have the following code (096 is the backtick):

```lua
k = hs.hotkey.modal.new({}, '\096')

myname = 'Jane Doe'
email = 'jane@example.com'
phone = '987.654.3210'
sig = 'Hello world'

k:bind({}, 'n', function() hs.eventtap.keyStrokes(myname) k:exit() end)
k:bind({}, 'e', function() hs.eventtap.keyStrokes(email) k:exit() end)
k:bind({}, 'p', function() hs.eventtap.keyStrokes(phone) k:exit() end)
k:bind({}, 's', function() hs.eventtap.keyStrokes(sig) k:exit() end)
```

Every one of my 'shortcuts' work, except for the 's'. It either outputs nothing or it outputs the second and third character of the variable (el is the output from the above example). Furthermore, it breaks the other bindings. I have to comment out the s-hotkey to keep the others working.

I am not using the 's' key anywhere else. I've tried using different mod keys, same result. I thought it could be another program causing the problem - I'm also running Quicksilver - but shutting it down didn't help. Can anyone confirm this?

Thanks

**Comment by cmsj** [comment]
Yep, I can reproduce this. actually, using your sample, none of those 4 works reliably for me, which is super weird because I use keyStrokes() a lot to type out the contents of my clipboard, and that is generally very reliable!

I'll dig into this and see what I can figure out. Thanks!

**Comment by cmsj** [comment]
I think I have this fixed - certainly in my local testing this is now super reliable with your Lua example. It'd be interesting to get you to test it - would you be up for trying a test build?

**Comment by iamdana** [comment]
Sure. Just tell me what I need to do. Thanks.

**Comment by cmsj** [comment]
@iamdana https://dl.dropboxusercontent.com/u/20103940/Hammerspoon.app.zip is a test build. I'd recommend not installing it on top of your current Hammerspoon.app, it's not a release build and has some debugging/testing code in it, but hopefully it should be sufficient to test your config :)
