### ISSUE TITLE
Can you use hammerspoon to control display mirroring?

### ISSUE THREAD

**Issue by AdamBD** [Hammerspoon/hammerspoon#2649]
Hi,

I am looking to programmatically toggle display mirroring on / off. I dont see any reference to mirroring in the documentation.

Is this within the scope of this tool?

**Comment by nonissue** [comment]
@AdamBD Have a look [here](https://github.com/Hammerspoon/hammerspoon/issues/1462#issuecomment-568489119)

**Comment by cmsj** [comment]
Thanks for the suggestion, the next release will offer `hs.screen:mirrorOf()` and `hs.screen:mirrorStop()`.
