### ISSUE TITLE
Missing documentation for hs.spaces

### ISSUE THREAD

**Issue by iliyang** [Hammerspoon/hammerspoon#2652]
The [main docs page](https://www.hammerspoon.org/docs/hs.html) contains a link to the [hs.spaces](https://www.hammerspoon.org/docs/hs.spaces.html) which is broken. Where can these docs be found?

**Comment by latenitefilms** [comment]
That's odd. Any ideas @cmsj or @asmagill ?

**Comment by latenitefilms** [comment]
Oh, right, there is no `hs.spaces`, there's only [`hs.spaces.watcher`](https://www.hammerspoon.org/docs/hs.spaces.watcher.html).

**Comment by iliyang** [comment]
Oh, I see, thanks! Maybe the broken link can be removed then.

**Comment by latenitefilms** [comment]
Yeah, I think the correct solution should be to add a new `hs.spaces` page, even though it will only contain a link to `hs.spaces.watcher`. I'll submit a pull request shortly.

**Comment by iliyang** [comment]
Thanks a lot for the lightning-fast response!
