### ISSUE TITLE
LuaSkin: hs.canvas:imageAnimates must be a boolean

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2654]
@asmagill - Hope all is well in your world!

I'm seeing a lot of these errors in user bug reports, but no idea what it means. Any ideas?

**Comment by latenitefilms** [comment]
FYI - I'm not using `imageAnimates` anywhere in our code, so must be something within Hammerspoon's core code.

**Comment by asmagill** [comment]
Betting its only on M1 macs and #2614 should fix it.

Been super busy here lately, but hoping to get back to working on Hammerspoon this weekend or early next week and see about merging some of these outstanding pulls.

**Comment by latenitefilms** [comment]
Legend, thanks! I'll merge #2614 into CommandPost and see if anything explodes.
