### ISSUE TITLE
hs.screen.watcher not firing reliably

### ISSUE THREAD

**Issue by thowi** [Hammerspoon/hammerspoon#2660]
Hey,

I'm using hs.screen.watcher to automatically update my screen layout when the monitor configuration changes:
```
-- Update layout when number of screens chamged.
num_of_screens = 0
hs.screen.watcher.new(function()
  logger.d("Screen watch", #hs.screen.allScreens())
  if num_of_screens ~= #hs.screen.allScreens() then
    logger.d("Update layout")
    applyLayout(layoutConfig)
    num_of_screens = #hs.screen.allScreens()
  end
end):start()
```

Unfortuantely, this doesn't trigger reliably.
It sometimes does, but often doesn't.
I tried turning the external screen on/off as well as plugging the cable out/in.

It does trigger reliably when I reload the config first, and then change the screen setup.
It seems to only trigger once after config reload and then stop.

Is there something wrong with my config or is this a legitimate bug?
I'm running on a 2020 MacBook Pro 13" with an external monitor connected via USB-C.

**Comment by latenitefilms** [comment]
I think this is a [garbage collection issue](http://www.hammerspoon.org/go/). Try capturing the watcher in a global variable.

```lua
-- Update layout when number of screens chamged.
num_of_screens = 0
screenWatcher = hs.screen.watcher.new(function()
  logger.d("Screen watch", #hs.screen.allScreens())
  if num_of_screens ~= #hs.screen.allScreens() then
    logger.d("Update layout")
    applyLayout(layoutConfig)
    num_of_screens = #hs.screen.allScreens()
  end
end):start()
```

**Comment by thowi** [comment]
Hm, the example on https://www.hammerspoon.org/go/#variablelife looks very similar.
The watcher is assigned to `screenWatcher` in my config.
I'm not a Lua expert, but global seems to be the default: https://www.lua.org/pil/1.2.html

**Comment by latenitefilms** [comment]
In the code in your original post, you're not assigning the watcher to any variable?

**Comment by thowi** [comment]
Oh, that's right! It works perfectly now.
Sorry for the noise and thanks for your help! :)
