### ISSUE TITLE
Theme Appearance Change

### ISSUE THREAD

**Issue by DreamSaddle** [Hammerspoon/hammerspoon#2664]
Can I dynamically switch the MacOS theme look and feel with this application.
I didn't find the relevant API.

**Comment by dasmurphy** [comment]
If you want to get the Darkmode or change from Normal to Dark and back, i created a small library for it.

You can get it here: https://github.com/Hammerspoon/hammerspoon/issues/2386#issuecomment-648421532

**Comment by DreamSaddle** [comment]
> If you want to get the Darkmode or change from Normal to Dark and back, i created a small library for it.
> 
> You can get it here: [#2386 (comment)](https://github.com/Hammerspoon/hammerspoon/issues/2386#issuecomment-648421532)

Oh, Thanks.
