### ISSUE TITLE
hs.speededitor - Add support for DaVinci Resolve Speed Editor keyboard

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2667]
Like Tangent panel support, this is pretty niche, and probably not of interest to the wider Hammerspoon community, but I'm interested in adding support for the DaVinci Resolve Speed Editor keyboard for CommandPost, so adding a Hammerspoon issue anyway, as I'll try get it working in Hammerspoon first.

This is the product:

https://www.blackmagicdesign.com/media/release/20201109-02

**Comment by cmsj** [comment]
I don't object to carrying it, but I agree it is pretty niche :)

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - It's also proving to be VERY tricky, as it seems Blackmagic really don't want people to use this hardware outside of their DaVinci Resolve software. Would either of you be up for helping me understand some Hopper results?

**Comment by asmagill** [comment]
No promises, I only half understand Hopper's output sometimes myself, but I could take a look.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as I think it falls into the too hard basket sadly.

**Comment by latenitefilms** [comment]
A very kind genius has "cracked" the authentication code here:

https://github.com/smunaut/blackmagic-misc/tree/c0e71caa1b544026ef7f422b48a1b66b0288d91f

I now just need to "port" this Python code into Objective-C land - woohoo!

HID Reports still confuse me a lot, so I'll probably need your genius at some point @asmagill and/or @cmsj.

**Comment by burningmonkapp** [comment]
> A very kind genius has "cracked" the authentication code here:
> 
> https://github.com/smunaut/blackmagic-misc/tree/c0e71caa1b544026ef7f422b48a1b66b0288d91f
> 
> I now just need to "port" this Python code into Objective-C land - woohoo!
> 
> HID Reports still confuse me a lot, so I'll probably need your genius at some point @asmagill and/or @cmsj.

Amazing!! Do you know if this could be a route to open the Speed Editor up to other pages in Davinci?

**Comment by latenitefilms** [comment]
Only one application can control the Speed Editor at a time, so if Hammerspoon has control before you launch DaVinci Resolve, then Hammerspoon has control and you can make it do whatever you want. If you want the buttons and jog wheel to match their existing functions, you need to trigger the equivalent using menu bar items, virtual keypresses or using the Accessibility API.

**Comment by burningmonkapp** [comment]
Thanks! 
So Hammerspoon can take control of the Speed Editor, and then I can reprogram it within Davinci myself?

**Comment by latenitefilms** [comment]
@burningmonkapp - Unfortunately DaVinci Resolve is the one app you won't be able to re-program it for - DaVinci Resolve will always "take control" of the hardware. You can however use this extension to make the Speed Editor work in other apps. I've added this to CommandPost. This is probably too niche for Hammerspoon, so I'm going to close this issue for now.
