### ISSUE TITLE
Cancel focus event

### ISSUE THREAD

**Issue by czabaj** [Hammerspoon/hammerspoon#2670]
Is it possible to cancel a focus event with hammerspoon?

I have a problem with Chrome (and also Brave Browser... seems to be related to Chromium), which constantly steals focus.

It is very annoying, it bumps me over several screens just to prank me. I use Chrome for development only, its DevTools are a must-have, switching to some other browser for development purposes is a no-go.

I searched Google extensively for "Chrome steals focus" and it bugs a lot of people for a long time, but is unresolved and seems to never be resolved.

If it is possible to revert/cancel the focus event with Hammerspoon, I can create logic, which will prevent Chrome to gain focus when the mouse is not hovering over its window. But I'm not very experienced with HS and I did not find any clue in the docs.

**Comment by bviefhues** [comment]
You can subscribe to all focus events with `hs.window.filter` and remember the currently focused window. Whenever a window you don't like gets focus, you can change focus to the remembered window.

**Comment by czabaj** [comment]
Well, so far the best I can come up with is this code, which aims to restore focus after "Brave Browser" steals it

```lua
local lastActiveWindow = hs.window.focusedWindow()
-- listen for all app focus excluding "Brave Browser" window
-- and store the focused window as "lastActiveWindow"
hs.window.filter.default:rejectApp('Brave Browser'):subscribe(
   hs.window.filter.windowFocused,
   function(window, appName)
      print('Storing window - ' .. appName)
      lastActiveWindow = window
end)
-- listen for focus of "Brave Browser" when it is not in current
-- mission control space
hs.window.filter.new{['Brave Browser']={currentSpace=false}}:subscribe(
   hs.window.filter.windowFocused,
   function(window, appName)
      print('Reverting Brave browser focus NOW')
      lastActiveWindow:focus()
end)
```

but the Brave Browser (or Chrome) seems to trigger the focus several times, my screen stars to move towards the Mission Control space with the browser, the above code then reverts the focus, so the screens moves few pixels back, but, before it stops, it runs once again towards Brawe Browser. The moving screen is also not pleasant, I'm not convinced this approach will yield any fruits.

So I test other chromium browsers, hopefully, some of them will not suffer from this issue. For example, I use Vivaldi browser as my main browser and it never did such rudeness to me, but I like to separate dev browser and main browser, for I sometimes crash the dev browser with infinite loop and I do not want to crash my main browser with potentially big unsaved context and also my main browser extension needs are clearly different from extensions I need in dev browser.

**Comment by czabaj** [comment]
For future reference, I read the docs through and through and cancelling the focus event, as e.g. `event.stopImmediatePropagation()` in the JavaScript, is not possible.

Also, I did not find any way how to prevent
