### ISSUE TITLE
hs.window:frame() returning stale / incorrect values?

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2671]
- hs 0.9.82
- macOS 11.2
- [`hs.window:frame()`](https://www.hammerspoon.org/docs/hs.window.html#frame)

Running into a gotcha and wondering if I'm doing something wrong, hit a bug, or just a limitation. **TL;DR–** is there some reason that `hs.window:frame()`  returns incorrect info when called multiple times within the same function block?

I have a window resizing function that shrinks the focused window in increments. I found that Google Chrome (and other apps) don't allow their windows to be shrunk below a certain size (in Chrome's case, it's 500 x 375)

Below is some test code that triggers on <kbd>⌘cmd</kbd><kbd>⇧shift</kbd><kbd>←leftarrow</kbd>. It will try to shrink the active window's width by 100px. Try it on Chrome. When you hit _"current width: 500, want: 400 actual: 400"_, you've hit the bug. 

`win:frame()` is reporting the rect width as `400` after the call to `setFrame()`— but you can see that **the window hasn't shrunk**, and if you measure it with e.g. Accessibility Inspector.app you'll see the width is still 500. Upon firing the function again, it confirms this by again printing "current width: 500"...

To repro, put this in your `init.lua` or in an include file:

```lua
function resize()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local w = math.floor(f.w)
  hs.alert.show('current width: '..w)
  w = w - 100
  f.w = w
  win:setFrame(f)
  return w
end

function checksize(width)
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local w = math.floor(f.w)
  hs.alert.show('want: '..width..' actual: '..w)
end

hs.hotkey.bind({"cmd", "shift"}, "Left", function()
  w = resize()
  checksize(w)
end)
```

screenshots:

![image](https://user-images.githubusercontent.com/1992842/106815772-541d1980-6642-11eb-8280-b97267314e0b.png)

![image](https://user-images.githubusercontent.com/1992842/106815637-259f3e80-6642-11eb-86ef-1d8941ccfd8b.png)

**Comment by cmsj** [comment]
This isn't a bug per-se, but it is a "surprising" feature. We animate the resizing of windows, over a period of 0.2 seconds (per `hs.window.animationDuration`). Your hotkey calls `resize()` immediately followed by `checksize()` so you're reading the value back out before anything has really happened, and things are not fully consistent yet.

What's actually happening is that we know that an animation is in progress, so `:frame()` is returning the expected end-state of the animation, but we have no way of knowing that Chrome is going to refuse to be resized any smaller, so for that 0.2 seconds, nothing is actually happening and the data returned by `:frame()` is wrong.

If you want to retain the animation, I would suggest wrapping the `checksize(w)` call in `hs.timer.doAfter()` with a time of maybe 0.3 seconds. If you don't mind losing the animation, set `hs.window.animationDuration = 0` in your HS config somewhere.

**Comment by cmsj** [comment]
(Alternatively, `:setFrame()` takes a `duration` argument which you can use to just specifically set that call to have an animation duration of zero)

**Comment by luckman212** [comment]
Brilliant @cmsj !
That was indeed the problem.

I used the **doAfter** as you suggested, working great.

```lua
function checkWidth(win,want)
  local got = win:frame().w
  if got ~= want then
    hs.alert.show('wanted: '..want..' got: '..got)
  end
end

[...snip...]
win:setFrame(frame)
if check_t then check_t:stop() end
check_t = hs.timer.doAfter(0.3, function() checkWidth(win,frame.w) end)
[...snip...]
```
