### ISSUE TITLE
hs.canvas crash: LuaState initialised on a background thread

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2684]
I just noticed that https://sentry.io/organizations/hammerspoon/issues/2061856609/?project=5220516&query=is%3Aunresolved&sort=freq&statsPeriod=90d is one of our most common crashes at the moment (although to be fair, that's on the order of 31 crashes in the last 90 days) and it looks like a pretty simple fix.

@asmagill looks to me like `HSCanvasWindow`'s `- (void)fadeOut:(NSTimeInterval)fadeTime andDelete:(BOOL)deleteCanvas withState:(lua_State *)L` just needs to have the entire block wrapped in a libdispatch call to execute it on the main thread. Any objections if I go ahead and do that?

**Comment by asmagill** [comment]
Go ahead -- now that we've landed the @encode pull, I don't have anything outstanding at the moment re canvas.
