### ISSUE TITLE
Onclick handlers for hs.drawing shapes

### ISSUE THREAD

**Issue by JosephFerano** [Hammerspoon/hammerspoon#269]
I've been creating a tabbing system for the window management and it currently generates a set of tabs using hs.drawing. It would be great if I could also attach an onclick handler to these shapes in order to shift the focus of the window in the region.

**Comment by cmsj** [comment]
So, I originally had it in my head that hs.drawing wouldn't support any kind of mouse event, but perhaps a simple click event is ok. I suspect that it will lead to more though, and before long we'll have implemented a whole UI toolkit ;)
