### ISSUE TITLE
Hook up hs.canvas to NSDockTile?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2701]
I saw something yesterday that, while superficially useless, made me think that some interesting possibilities might exist for HS users: https://twitter.com/neilsardesai/status/1362537709840048128?s=20

The API at work here is [NSDockTile](https://developer.apple.com/documentation/appkit/nsdocktile) and the way it seems to work is that you set up some kind of view that's the right size, tell NSDockTile about it, then call an update function every time you want it to re-render the dock image. Could be an interesting way for users to display a small amount of status.

**Comment by latenitefilms** [comment]
Haha, I saw that on Twitter too, and was thinking it would be fun to add to Hammerspoon!

**Comment by latenitefilms** [comment]
Could be a good thing to pair with:

- Add Ability to add Custom Items to Dock Icon Contextual Menu #1350

**Comment by latenitefilms** [comment]
This looks fun:

https://twitter.com/neilsardesai/status/1362890469970214917?s=21

**Comment by asmagill** [comment]
Beyond verifying that it basically works, the following will work (warning, it's minimally tested, so caveat emptor and all that crap)

I added the following to `hs.dockicon`:

~~~objc
@interface NSView (HSCanvasView)
-(NSWindow *)wrapperWindow ;
@end

static int icon_docktileCanvas(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L] ;
    [skin checkArgs:LS_TANY | LS_TOPTIONAL, LS_TBREAK] ;
    NSDockTile *tile = [[NSApplication sharedApplication] dockTile];

    if (lua_gettop(L) != 0) {
        NSView *oldView = tile.contentView ;
        if (lua_type(L, 1) == LUA_TNIL) {
            tile.contentView = nil ;
        } else {
            [skin checkArgs:LS_TUSERDATA, "hs.canvas", LS_TBREAK] ;
            tile.contentView = [skin toNSObjectAtIndex:1] ;
        }
        [tile display] ;
        // if canvas removed from tile, reattach it so it can be displayed as a canvas again
        if (![oldView isEqualTo:tile.contentView] && [oldView isKindOfClass:NSClassFromString(@"HSCanvasView")]) {
            [oldView.wrapperWindow setContentView:oldView] ;
        }
    }
    [skin pushNSObject:tile.contentView] ;
    return 1 ;
}

static int icon_docktileSize(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L] ;
    [skin checkArgs:LS_TBREAK] ;
    NSDockTile *tile = [[NSApplication sharedApplication] dockTile];

    [skin pushNSSize:tile.size] ;
    return 1 ;
}

static int icon_docktileUpdate(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L] ;
    [skin checkArgs:LS_TBREAK] ;
    NSDockTile *tile = [[NSApplication sharedApplication] dockTile];

    [tile display] ;
    return 0 ;
}

// also add these to the function list for the module:

    {"tileCanvas", icon_docktileCanvas},
    {"tileSize", icon_docktileSize},
    {"tileUpdate", icon_docktileUpdate},
~~~

Once this is in place, the following code should show it off:

~~~lua
a = hs.canvas.new{ x = 100, y = 100, h = 128, w = 128 } 
a[#a + 1] = { type = "text", text = "placeholder" } 
hs.dockicon.tileCanvas(a)
t = hs.timer.doEvery(1, function() a[1].text = os.date() ; hs.dockicon.tileUpdate() end)
~~~

At present, any updates to the canvas have to be followed with `hs.dockicon.tileUpdate()` to actually update the displayed tile.

If this does make it into a formal update, I'd probably also modify `hs.canvas` by adding something like the following at the end of canvas's `drawRect:` and remove the need for the `hs.dockicon.tileUpdate` function completely:

~~~objc
// note this is untested at present
    // are we in a docktile?
    NSDockTile *tile = [[NSApplication sharedApplication] dockTile];
    NSView *dockTileView = tile.view ;
    if (dockTileView and [self isEqualTo:dockTileView]) [tile display] ;
~~~

I leave things like making the dock icon into a gaming console to you 😜

**Comment by asmagill** [comment]
Oh, and I suppose `require("hs.canvas")` should be added to dockicon's `init.lua`... on my machine canvas is used by so many other things its safe to assume it's already loaded, but in a more minimal setup, it might not be.

**Comment by asmagill** [comment]
Actually reading the API docs closer for NSDockTile's `display` method suggests that adding the recommended code to canvas's `drawRect:` might cause a crash/infinite loop... can't test at the moment, but if I'm reading this correctly, we might be stuck with having to manually trigger updates with `hs.dockicon.tileUpdate()`.

**Comment by cmsj** [comment]
#2703 is merged.
