### ISSUE TITLE
test if window referenced by hs.window object exists?

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2714]
I read https://www.hammerspoon.org/docs/hs.window.html but don't see a canonical way to check if the window linked to an `hs.window` object still exists or was destroyed. I created this function:

```lua
function winExists(w)
  if (w and w:role() ~= '') then return true else return false end
end
```

from HS console:
```
w = hs.window.focusedWindow()
winExists(w)
==> true
```
(now close the window)
```
winExists(w)
==> false
```
It seems to work, but not sure if this is the most efficient way to do this...? **_N.B._** `w:id()` will return the original win ID even after the window is gone or the app has been quit, so that doesn't work.

**Comment by cmsj** [comment]
I expect that is fine for the vast majority of windows, but I would bet that there are more than zero apps out there who set their AXWindowRole to an empty string, or something that will end up being invalid, for which we will return an empty string.

A better option would be:

```lua
w = hs.window.focusedWindow()
hs.axuielement.windowElement(w):isValid()
==> true
```

`:isValid()` attempts to copy an attribute from the underlying `AXUIElementRef` of the `hs.window` object, which is something the window has to actively reply to, so it ought to be completely reliable (with the one exception of apps which have gotten into a weird state and don't reply to Accessibility events, but that's generally quite rare).
