### ISSUE TITLE
isFrontmost() broken 0.9.83 ?

### ISSUE THREAD

**Issue by SomeoneCalledRob** [Hammerspoon/hammerspoon#2724]
Since updating to Hamerspoon 0.9.83, I've found that hs.application:isFrontmost() always returns false, which is breaking some stuff in my init.lua.

Running on Catalina 10.15.7/Intel.

**Comment by stephen-bunn** [comment]
Encountering the same issue.
Mojave 10.14.6/Intel

**Comment by cmsj** [comment]
See #2721 - a fixed version will be released in the next few hours. Apologies!
