### ISSUE TITLE
Auto collect hs.canvas objects?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#2730]
Reading #2729 and remembering a discussion I had on here a couple of weeks ago about hs.canvas and collection specifically, I wonder if it's worth biting the bullet and changing canvas to auto-collect now rather than in some nebulous  2.0 (I hope more in the sense of *when* than in the sense of actuality)?

We may have to field some issues in cases where people have created drawings that they leave up all/most of the time because they may see some of them suddenly disappear... but I'm not sure how many cases that will be -- how many use cases can you think of where an image is created and *never* removed? Maybe the rounded-corners spoon... but any others I can think of also involve hiding them based on some logic which means that they have to be capturing the drawing in a variable already thus preventing collection.

It's not a completely simple fix (more tedious than hard) so I don't want to give an eta quite yet, but are there any objections if I proceed sooner rather than later?

**Comment by latenitefilms** [comment]
No objections here! We use `hs.canvas` a lot, so I'm sure we'll have to do some code changes, but all good.

**Comment by cmsj** [comment]
I have a few things rendered on top of my desktop background (sort of a lite version of GeekTools) that are expected to remain visible forever, but they are captured in global variables.

I think we should make the switch - I think it's more consistent with the model we try to drum into everyone's head everywhere else, that you have to retain a reference to things you don't want GC'd.
