### ISSUE TITLE
Multimedia keys appear to be broken

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#2731]
It looks like the Multimedia keys broke in `0.9.84 (5829)`.

`hs.eventtap.event.newSystemKeyEvent("NEXT", true):post()` doesn't work, neither is `PLAY`, `PREVIOUS`, etc.

Can someone please check

**Comment by agzam** [comment]
Hmm. I tried reverting to  `0.9.82 (5614)`. The keys still don't work. This must be something to do with the Big Sur update.

**Comment by cmsj** [comment]
Interesting. I'm on macOS 11.2.1 and your code works for me in 0.9.84.

**Comment by agzam** [comment]
What about NEXT/PREVIOUS. I rebooted the machine SOUND_UP/SOUND_DOWN/MUTE are working, but not NEXT/PREVIOUS/PLAY

**Comment by agzam** [comment]
Alright. Sorry for the false alarm. It seems this has nothing to do with Hammerspoon. This is something to do either with one the Big Sur's Security & Privacy settings or GPMDP. Closing this.

**Comment by agzam** [comment]
Linking the issue (in case someone else stumbles on it) https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3920
