### ISSUE TITLE
hs.canvas build warnings

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2736]
@asmagill we have some deprecation warnings on hs.canvas about the use of `NSDisableScreenUpdates` which suggest that it's typically not needed anymore. Do you happen to know if that's true for hs.canvas?

If we do need them, then I'll wrap them with clang diagnostics pragmas to silence the warnings.

**Comment by asmagill** [comment]
Go ahead and remove them entirely. They don't really do anything anymore (I think they've been basically no-ops for quite a while now).

**Comment by cmsj** [comment]
Closed by #2737
