### ISSUE TITLE
hs.websocket stops calling callback function

### ISSUE THREAD

**Issue by jeffmikels** [Hammerspoon/hammerspoon#2738]
hs version 0.9.84

code

```lua
ws = hs.websocket.new('ws://endpoint', print)
```

`print` is called when the socket is opened, but it is never called again.

Can anyone reproduce?

**Comment by luckman212** [comment]
What does `ws:status()` say?

**Comment by jeffmikels** [comment]
`open`

**Comment by jeffmikels** [comment]
I just tested and it works fine with the websocket echo server at `wss://echo.websocket.org`.

It also works fine with a node.js websocket server. I'm opening a new issue with a different name.
