### ISSUE TITLE
[help] How to bind bluetooth headset control clicks with hammerspoon?

### ISSUE THREAD

**Issue by sbakiu** [Hammerspoon/hammerspoon#2739]
I am trying to detect `eventtaps` on my bluetooth headset and write some custom logic `hs.eventtap` module. Following is a minimal code snippet in `init.lua`:
```
function mediaKeyCallback(event)
    print(event:getType())
end
eventtap = hs.eventtap.new({
    hs.eventtap.event.types.gesture,
  }, mediaKeyCallback)
eventtap:start()
```
If I change the volume from the touch bar, there are events logged. However, when doing the same from the headset, the volume indeed changes, but the event is not caught by Hammerspoon. I tried to use `hs.eventtap.event.types.systemDefined` and `hs.eventtap.event.types.NSSystemDefined` without any success. Should I be using some other module or am I missing something fundamental?

**Comment by cmsj** [comment]
I don't think those events are exposed anywhere - I've looked before, but I'm pretty sure the OS just consumes them itself and doesn't send them to the HID event system, unfortunately.
