### ISSUE TITLE
Hotkey groupings discussion item

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#274]
More and more we're seeing cases where using modal key groupings that are toggled by program logic rather than a key press is useful... when an application activates or deactivates, etc.

It's got me thinking about how we're defining modal key sets... currently we have to give it some combination of key modifiers and a key which is unlikely to be used, when in actuality we don't even want the key to be the modal trigger at all.

For discussion, I think we should consider allowing the first parameter (or 2?) to hotkey.modal.new be a string label... more for program documentation than as an index for lookup (though that is a possibility too)... this has the simplicity of simply checking the first parameter type -- if it's a table, go through the regular binding process of making the key modifiers and key toggle the modal state; if it's not a table, skip this part and assume the caller is going to capture the returned userdata so the enter and exit methods can be called programmatically without using a key that we *think* we won't ever use but will then pull our hair out debugging if we ever do.

By allowing labels for groupings, module writers could also include a preset "default" group of key bindings defined, which can easily be added to your active set by creating one global key binding which invokes the modal set defined by the module author... you can still create your own bindings invoking specific methods in the ways you as the end user want, but I'll admit I've spent time before digging through docs and code and testing this and that trying to figure out the best way to utilize a module when a few predefined defaults would have gone a long way to getting me using it quickly without the digging and testing... and occasional cursing :-)  I know we don't want module authors to assume they know what the end user wants or potentially overwrite active hotkeys the user already has, so these predefined groups should not be active by default or assigned to the global (non modal) key space, but the end user can define one key to test out the authors example cases and then create their own bindings once they've experimented and decided how they want to add it to their personal workflow.

I'm also wondering if maybe it would make sense to really consider internally *ALL* key bindings as part of a modal group... just that the non-modal versions of the hotkey methods actually utilize an implicit global modal grouping.  This would make it easy to turn them all on or off programmatically without requiring explicit use of modal or some other recording mechanism and keep the internals consistent.  Other than possibly simplifying the code base, though, I'm less sure of how much benefit this might be... hence the discussion.

**Comment by cmsj** [comment]
Some interesting ideas here.

 * I think having hs.hotkey silently wrap hs.hotkey.modal is a bad idea - it would prevent you from having truly global hotkeys that work in all your modal states.
 * I like the idea of naming modal States, and I think I would want the module to keep track of them, so users can get a reference to them at will
 * I like the idea of opinionated modules shipping a modal state (likely named "hs.foo" to match their namespace)

**Comment by asmagill** [comment]
See #313 -- I'm considering adding a method to both hotkey and hotkey modal for storing a description and as for "opinionated modules", now that I've thought about it some more, this can already be done by adding an unbound (no key definition) modal hotkey as either a member of the module or as the result of a function in the module.
