### ISSUE TITLE
[Bug] hsWindow:snapshot(true) gives error

### ISSUE THREAD

**Issue by dasmurphy** [Hammerspoon/hammerspoon#2742]
I made some tests with the webview and tried to save a screenshot to a file.

### The Bug

When i try this it works.
```lua
webview:hswindow():snapshot():saveToFile('~/test.png',false,'png')
```

When i try this to save the transparency in the file, it gives an error.
```lua
webview:hswindow():snapshot(true):saveToFile('~/test.png',false,'png')
```

The error is:
```text
[string "return webview:hswindow():snapshot(true):save..."]:1: ERROR: incorrect number of arguments. Expected 1, got 2
stack traceback:
	[C]: in method 'snapshot'
	[string "return webview:hswindow():snapshot(true):save..."]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:514: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:494>
```

The [documentation](https://www.hammerspoon.org/docs/hs.window.html#snapshot) states:
```text
hs.window:snapshot([keepTransparency]) -> hs.image-object
```
`keepTransparency` is optional. In the current state it give an error.

---

### Code internals

I think this line is not correct
https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/window/internal.m#L621

```c
[skin checkArgs:LS_TUSERDATA, USERDATA_TAG, LS_TBREAK];
```

I think it must be something like
```c
[skin checkArgs:LS_TUSERDATA, USERDATA_TAG, LS_TBOOLEAN|LS_TOPTIONAL, LS_TBREAK];
```

The second parameter check seemed to be wrong, but my Macos development skills are a little bit limited currently and i did not test it out.

---

### Workaround for others

After looking around i found a workaround, which works fine.
```lua
hs.window.snapshotForID(webview:hswindow():id(),true):saveToFile('~/test.png',false,'png')
```

---

### Question

Would it be possible to fix this? In theory you can't save any transparency currently. Look fairly easy to fix and release it.

**Comment by cmsj** [comment]
Thanks for the great bug report - you nailed it with where the mistake is. I'll fix it momentarily.

**Comment by luckman212** [comment]
@dasmurphy nice, I ran into this too and was going to report it- you nailed it 👍

**Comment by dasmurphy** [comment]
@cmsj Thanks for the fix!

@luckman212 Hope my workaround helped you a little bit.
