### ISSUE TITLE
Sentry API URL (SENTRY_API_URL) unavailable - HSLogger.h

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2750]
When building from source, I get this warning in Xcode:

![image](https://user-images.githubusercontent.com/1992842/110519249-1563fe80-80db-11eb-827b-01f58da47134.png)

I assume this is normal, but does this mean that crash logs from these builds don't get sent to Sentry?

Anything to do here?

**Comment by cmsj** [comment]
This is indeed normal and expected. The URL isn't really secret, it's just that I didn't want to get crash reports from third party builds.
