### ISSUE TITLE
hs.application.watcher start() function fails for certain processes due to missing pid() function

### ISSUE THREAD

**Issue by simichaels** [Hammerspoon/hammerspoon#276]
I have the following piece of code in my hammerspoon init.lua (taken from https://gist.github.com/tmandry/a5b1ab6d6ea012c1e8c5):

    function watchApp(app, initializing)
        if watchers[app:pid()] then return end

        local watcher = app:newWatcher(handleAppEvent)
        watchers[app:pid()] = {watcher = watcher, windows = {}}

        watcher:start({events.windowCreated, events.AXFocusedWindowChanged})

        -- Watch any windows that already exist
        for i, window in pairs(app:allWindows()) do
            watchWindow(window, initializing)
        end
    end

For certain applications, e.g. universalaccessd, Hammerspoon will throw this error:

    ....app/Contents/Resources/extensions/hs/uielement/init.lua:135: attempt to call method 'pid' (a nil value)
    stack traceback:
        ....app/Contents/Resources/extensions/hs/uielement/init.lua:135: in function 'start'
        /Users/simichaels/.hammerspoon/init.lua:72: in function 'watchApp'
        /Users/simichaels/.hammerspoon/init.lua:44: in function 'init'
        /Users/simichaels/.hammerspoon/init.lua:115: in main chunk
        [C]: in function 'xpcall'
        /Applications/Hammerspoon.app/Contents/Resources/setup.lua:201: in main chunk

The source is line 135 in hs/uielement/init.lua,

    local pid = self._element:pid()

So it appears that application watchers for universalaccessd do not have a pid() function assigned. This may be the case for other applications as well.

**Comment by lowne** [comment]
This happens for me for `node-webkit Helper`, `Little Snitch Agent` and `Little Snitch Network Monitor`.
My workaround for now (for, apparently, the exact same use case) is this:
```
      local watcher = app:newWatcher(windowCreated,force)
      if watcher._element.pid then
        appWatchers[appname] = watcher
        watcher:start({uiwatcher.windowCreated})
      else
        log.w('No PID for app '..appname)
      end
```

**Comment by cmsj** [comment]
@lowne oddly, I'm not able to reproduce this, even with Little Snitch Agent (which is configured to not allow scripting additions or GUI scripting, so it should be rejecting this!).

Could you check if watcher._element is nil please? and maybe hs.inspect() it?

**Comment by lowne** [comment]
@cmsj `watcher._element` is userdata (and definitely not nil) so can't quite inspect it.
Among whatever I have running right now, these are the problematic apps: `Little Snitch Network Monitor, Google Chrome Helper, universalaccessd, Little Snitch Agent, Safari Networking, iTunes Helper, QTKitServer-(644) Safari Web Content, Spotify Helper, sharingd`.

Possibly related: sometimes even 'regular' apps don't have a `.pid` (thus requiring the workaround) right after a `hs.application.watcher.launched` event; if I simply retry a half second later, all is fine again.

**Comment by cmsj** [comment]
Per IRC discussion, we should be checking for :pid() in hs.application.watcher.new() and returning nil.

**Comment by lowne** [comment]
Bug still present when stopping a watcher; PR above fixes that too.

**Comment by cmsj** [comment]
(PR #366 is now landed)
