### ISSUE TITLE
Crash in hs.serial

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2763]
This might be a bug in the underlying [ORSSerialPort](https://github.com/armadsen/ORSSerialPort) pod?

CC @armadsen in case he's interested.

Crash log: https://sentry.io/share/issue/57c1cd8f2df7404bb31ff5141a5b902a/

**Comment by cmsj** [comment]
It's our bug - see the breadcrumbs section on the Sentry report: "Destroying Lua instance" and look in the full traceback, the app is in the process of terminating, and it's cleaning up resources, so the serial port is destroyed and hs.serial tries to call a callback after Lua has been destroyed.

Two things come to mind from looking at this:

1. hs.serial should be using the `_lua_stackguard_entry(skin.L);` and `_lua_stackguard_exit();` macros in these C callbacks
2. Lua garbage collection should have caused this object to be destroyed

While we should look at number 2, adding the macros and `checkLuaSkinInstance` to the callbacks would avoid the crash. Take a look at how the callback in hs.timer works now, and shout if you have any questions.
