### ISSUE TITLE
hs.drawing.disableScreenUpdates() replacement in 0.9.85?

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2766]
Seems like the latest version (0.9.85) removed the deprecated `hs.drawing.disableScreenUpdates()` function. The `hs.drawing` docs point me at `hs.canvas` for replacement functionality, but looking `hs.canvas` over, I don't see a replacement for `disableScreenUpdates()`.

**Comment by asmagill** [comment]
It has been a NOP for a long time now and wasn't really doing anything. It's not necessary and can just be removed.
