### ISSUE TITLE
Disabling window animations doesn't actually work (most of the time)

### ISSUE THREAD

**Issue by andweeb** [Hammerspoon/hammerspoon#2770]
I always disable window animations by statically setting `hs.window.animationDuration` to `0` in my config, and constantly make use of various [`hs.window`](http://www.hammerspoon.org/docs/hs.window.html) functions in my day-to-day to resize my windows without animations.

Lately though I've been running into inconsistent behaviors with windows animating when I've explicitly set the animation duration to `0`. For some reason, it seems that windows for _specific_ applications seem to incorrectly animate, or correctly _do not_ animate until I open specific applications that _do_ animate, for example:
<video src="https://user-images.githubusercontent.com/10726590/111018542-3f811f00-836e-11eb-8ff9-181d49e4f133.mp4" />

* ✅ I open Alacritty and can resize the window without animating (and close Alacritty)
* ✅ I open TablePlus and can resize the window without animating
* ✅ I focus Alacritty (with TablePlus still open) and can resize the window without animating
* ❌ I focus TablePlus (with Alacritty still open) and now the window animates when resizing
* ❌ I focus Alacritty (with TablePlus still open) and now the window animates when resizing (not shown in video)

Safari/Finder/most other applications simply just do not animate when resizing. I've ensured that `hs.window.animationDuration == 0` in the console at runtime, and I've even tried using [`hs.window.setFrame`](http://www.hammerspoon.org/docs/hs.window.html#setFrame) with an explicit `0` value. And what confuses me _even more_ is that my work laptop doesn't seem to have this issue, with the same config!

I'd really love to not have my windows animate while resizing, especially since (when animating) `setFrame` only partially sets it to the target frame dimensions. I'd really appreciate if I could get some help with this!

**Comment by cmsj** [comment]
Could it be that some other file in your hammerspoon config, or maybe a Spoon, is setting `animationDuration` back to some non-zero value?

**Comment by andweeb** [comment]
Hmm.. it seems to have been working okay since yesterday when I turned my computer back on.

I did try out using a new spoon so that might've been it, but it is strange that windows were still animating despite removing the spoon and resetting my config to have animations disabled. Even restarting didn't fix it, so maybe changes to that `animationDuration` value always requires a system off/on cycle?

In any case, since it's working I'll close this issue and report back if the weird behavior returns. Thanks!

**Comment by edyrhaug** [comment]
I am able to replicate this now by enabling the accessibility on screen keyboard. All applications that have windows open while the onscreen keyboard is enabled becomes animated like this. The effect persists after closing the onscreen keyboard, for both existing and new windows of any of these affected applications. Quitting the application and restarting it makes its windows behave normally again.
