### ISSUE TITLE
GitHub Action for validating in-line documentation changes?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2774]
@cmsj - I wonder if it's possible/worthwhile to add some kind of GitHub action for validating in-line documentation. For example, with the header:

```lua
/// hs.websocket:send(message[, isData]) -> object
```

...it could check for the amount of commas in between the round brackets (i.e 1), and compare to the number of parameters listed below (i.e. 2).

```lua
/// Parameters:
///  * message - A string containing the message to send.
///  * isData - An optional boolean that sends the message as binary data (defaults to true).
```

I'm basically thinking @sticker-ci for in-line docs.

You might even just be able to do this by triggering your existing Python scripts for generating docs?

**Comment by cmsj** [comment]
Our CI does do a `make docs` before even building Hammerspoon, so in theory we're already validating for actual errors.

As for matching up the signature to the Parameters section, that ought to be possible too.

**Comment by cmsj** [comment]
In theory the CI for #2774 should now explode with a huge number of docstring parameter lint warnings 😬

**Comment by cmsj** [comment]
Wheee, that's a lot of errors 🤣

I've fixed some locally already before pushing the script changes, but I still have 68 to work through.

**Comment by cmsj** [comment]
And now the PR contains fixes for all of the parameter lint errors it found. I did have to make some arguably bad changes to docstrings, to keep the linter from becoming unreasonably complex. Happy to discuss this compromise if people want to.

**Comment by latenitefilms** [comment]
Amazing work! All looks good to me!

That will be a massive help in future ensuring all pull requests have good and valid documentation! Nice one!

**Comment by cmsj** [comment]
Hopefully, yeah, and we can slowly extend the linting over time to force the docstrings to become more and more correctly formatted :)
