### ISSUE TITLE
hs.eventtap printing some extra debug info (keyDelay, targetApp) to console

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#2777]
I noticed these repeated messages filling my console in the last few weeks.

![image](https://user-images.githubusercontent.com/1992842/111168626-9fe3ac80-8578-11eb-9e29-e3a9d8f80932.png)

Looks like that was added ~a month ago in this commit:
https://github.com/Hammerspoon/hammerspoon/blob/8c6d548393608128383c152201f7fa5c3c769c6d/extensions/eventtap/init.lua#L274-L275

Should that be removed, or at least use a `log.df(...)` method instead @cmsj ?

**Comment by cmsj** [comment]
Thanks!
