### ISSUE TITLE
hs CLI can't load dynamic library.

### ISSUE THREAD

**Issue by myelsukov** [Hammerspoon/hammerspoon#2784]
After upgrading to 0.9.86 `hs` CLI fails:

```
> hs
dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /usr/local/bin/hs
  Reason: image not found
Abort trap: 6
```

**Comment by latenitefilms** [comment]
This will be fixed in the next release.

https://github.com/Hammerspoon/hammerspoon/issues/2775

@cmsj turned on some debugging to try and resolve some weird crashes which inadvertently broke the CLI.

In the meantime you can roll back to the previous version.
