### ISSUE TITLE
hs.screen.find() no longer works

### ISSUE THREAD

**Issue by rectalogic** [Hammerspoon/hammerspoon#2793]
As of 0.9.86 on macOS 10.15.7, `hs.screen.find()` no longer works.
```
> hs.screen.allScreens()[2]:name()
Built-in Retina Display
> hs.inspect(hs.screen.find("Built-in Retina Display"))
nil
```

**Comment by asmagill** [comment]
Screen Find uses string.match for comparison. Try “Built%-in Retina Display”. If that doesn’t work, try seeing what the following reports (making this work on the M1 Macs under Big Sur required a change in the way the name is captured):

~~~lua
for i, v in ipairs(hs.screen.allScreens()) do
    print(v:name())
end
~~~

**Comment by rectalogic** [comment]
Yes that works, thanks
```
> hs.screen("Built%-in Retina Display")
hs.screen: Built-in Retina Display (0x60600047d5f8)
```
