### ISSUE TITLE
[Bug] Hammerspoon IPC command line program is broken

### ISSUE THREAD

**Issue by raguay** [Hammerspoon/hammerspoon#2795]
The last update has messed up the IPC program for the command line: hs. It only gives this error now:

dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /usr/local/bin/hs
  Reason: image not found

It would be best to make this a static linked program. Where would the dylib be?

**Comment by latenitefilms** [comment]
See pinned issue: #2784
