### ISSUE TITLE
Is there a keybinding to toggle the console?

### ISSUE THREAD

**Issue by talwrii** [Hammerspoon/hammerspoon#2801]
When debugging I often find that I want to frequently pop and hide the console? But there doesn't seem to be a way of setting a keybinding for this. 

I can *hide* the consoel with `hs.console.hswindow():close()` but there seems to be no way of undoing that through the api. I tried looking at `hs.menubar` to simulate some clicks in the dock to do it. 

Am I missing something obvious?

**Comment by cmsj** [comment]
see [`hs.toggleConsole()`](http://www.hammerspoon.org/docs/hs.html#toggleConsole) 🙂
