### ISSUE TITLE
hs.hotkey.modal:bind documentation conflicts with actual behavior

### ISSUE THREAD

**Issue by mikaraunio** [Hammerspoon/hammerspoon#2802]
Documentation for `hs.hotkey.modal:bind` says message should be nil for no alert:

> message - A string containing a message to be displayed via hs.alert() when the hotkey has been triggered, or nil for no alert

However, `modal:bind` actually behaves like `hs.hotkey.bind`, where message must be omitted, not nil, if not used - indeed all it does is basically call `hotkey.new(...)`.

Is there a rationale why the two should in fact behave differently, or is this just a documentation error? If the latter, can file a doc PR if needed.

**Comment by latenitefilms** [comment]
I believe this was corrected in #2762

**Comment by mikaraunio** [comment]
Quite. Did not check the closed PRs.
