### ISSUE TITLE
hs.pathwatcher does not respond to file changes

### ISSUE THREAD

**Issue by naefl** [Hammerspoon/hammerspoon#2803]
OS: MacOS Big Sur
Sys: M1 MacBook Air
Download: brew

I would expect the following to alert me when i create new files (in my `init.lua`):

```lua
local function alert_downloads_changes()
    hs.pathwatcher.new(os.getenv('HOME') .. '/Downloads/', function(a) hs.alert(hs.inspect.inspect(a)) end):start()
end

alert_downloads_changes()
```

However, trying

```bash
cd $HOME/Downloads/ && echo 'test' > test.txt
```

Nothing happens.

Sorry if this is a coding mistake and thanks 3*10**18 for the awesome library!

**Comment by asmagill** [comment]
Your pathwatcher isn't stored in a global or upvalue-captured local so it's being cleared when lua garbage collection kicks in.

The simplest fix is to do something like:

~~~lua
local function alert_downloads_changes()
    myPathWatcher = hs.pathwatcher.new(os.getenv('HOME') .. '/Downloads/', function(a) hs.alert(hs.inspect.inspect(a)) end):start()
end

alert_downloads_changes()
~~~

This makes `myPathWatcher` a global variable so the pathwatcher isn't collected and terminated during garbage collection.

If you wanted to do this without creating a global variable, something like this would work:

~~~lua
local function alert_downloads_changes()
    local mPW -- has to be predeclared so it can be referenced within the assignment
    mPW = hs.pathwatcher.new(os.getenv('HOME') .. '/Downloads/', function(a)
        if mPW then -- this makes it an upvalue, and since it has a value, it's considered *true*
            hs.alert(hs.inspect.inspect(a))
        end
    end):start()
end

alert_downloads_changes()

~~~
This is discussed in more detail at https://groups.google.com/g/hammerspoon/c/WJPc1FdjR6I/m/7Hd0AIKfBwAJ and I hope to add a wiki article here in the not-to-distant future that we can refer people to as well.

**Comment by naefl** [comment]
That worked perfectly. Closing!
