### ISSUE TITLE
Add ability to get a list of system emoji names?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2804]
I was just having a look at the [Emojis Spoon](https://github.com/Hammerspoon/Spoons/tree/master/Source/Emojis.spoon), and it seems to just have a JSON list of all the system emoji's. Surely there's some kind of Apple API for a getting a list of all the available system emoji's by name?

Closest I've found so far is something like this:

https://github.com/onmyway133/Smile

...but it also just uses hardcoded values.

Have you ever looked into this @asmagill ?

I had a quick look into the "Emoji & Symbols" app (`/System/Library/Input Methods/CharacterPalette.app`), but at first glance I couldn't see anything obvious. However, then I had a look at open files in Activity Monitor which lead me to:

```
/System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/Resources/en_AU.lproj/AppleName.strings
```

I'm on Mojave... I wonder if this file still exists on Catalina and Big Sur?

**Comment by asmagill** [comment]
Affirmative on my Catalina iMac, and affirmative on my Big Sur laptop.

I'm not aware of any objective-c class or corefoundation method to get the list, but honestly I haven't really looked all that hard.

You'd need to verify that the list is complete, but the benefit of checking those files is that you could easily use localized names -- take a look at my in progress spaces module to see how it checks the preferred languages and locale to attempt to find the plist file (it's near the top of `init.lua`)... it's not that hard if someone wants to give it a shot.

**Comment by luckman212** [comment]
Neat! @asmagill just making sure, you're referring to your `getDockExitTemplates()` from [here](https://github.com/asmagill/hammerspoon_asm/blob/b04eb5188addc6ac4d910e607d465f48e0a861e9/spaces/init.lua#L59-L81) right?

I made a quick adaptation @latenitefilms, you can paste this blob into your HS console and then fire `getEmojis()` - it works!

Looks like the list is "Emoji 2020 compliant" according to [emojipedia](https://blog.emojipedia.org/117-new-emojis-in-final-list-for-2020/). It contains the "ninja🥷 ", "pinched fingers🤌 ", and "disguised face🥸 "—but not the "headstone". Guess Apple censored that as too provacative. 😉 

```lua
getEmojis = function()
    local localesToSearch = hs.host.locale.preferredLanguages() or {}
    localesToSearch = table.move(localesToSearch, 1, #localesToSearch, 1, {})
    table.insert(localesToSearch, hs.host.locale.current())
    local path   = hs.application("Dock"):path() .. "/Contents/Resources"
    local locale = ""
    while #localesToSearch > 0 do
        locale = table.remove(localesToSearch, 1):gsub("%-", "_")
        while #locale > 0 do
            if hs.fs.attributes(path .. "/" .. locale .. ".lproj/Accessibility.strings") then break end
            locale = locale:match("^(.-)_?[^_]+$")
        end
        if #locale > 0 then break end
    end
    if #locale == 0 then locale = "en" end -- fallback to english
    local emojiPath = '/System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/Resources'
    local contents = hs.plist.read(emojiPath .. "/" .. locale .. ".lproj/AppleName.strings")
    print(hs.inspect(contents))
end
```

**Comment by asmagill** [comment]
Yup, that's the section!

**Comment by latenitefilms** [comment]
Closing this issue, as I think @luckman212's solution does the job. Thanks heaps!
