### ISSUE TITLE
Add scale option to hs.canvas:imageFromCanvas()?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2807]
@asmagill - Thoughts on adding a `scale` option to `hs.canvas:imageFromCanvas()`, similar to what you find in `hs.image:encodeAsURLString()`?

> `scale` - an optional boolean, default false, which indicates that the image size (which macOS represents as points) should be scaled to pixels. For images that have Retina scale representations, this may result in an encoded image which is scaled down from the original source.

**Comment by asmagill** [comment]
The source material for the image is entirely different, so not exactly sure where to start... what are you trying to accomplish with this? Might help to have a better idea of the actual problem first.

**Comment by latenitefilms** [comment]
I'm sending `hs.image` icons to a control surface. They need to be 60x90 pixels, however for legacy reasons, some of our icons are stored as 90x90 pixels, so we're using `hs.canvas` to resize those using the below code:

```
local decodedImage = imageFromURL(encodedIcon)
local size = decodedImage and decodedImage:size()
if size and size.w ~= 60 or size.h ~= 90 then
    --------------------------------------------------------------------------------
    -- The Knob Icon isn't 60x90 pixels, so it must be a legacy icon that needs
    -- to be scaled:
    --------------------------------------------------------------------------------
    local v = canvas.new{x = 0, y = 0, w = 60, h = 90 }

    v[1] = {
        frame = { h = "100%", w = "100%", x = 0, y = 0 },
        fillColor = { alpha = 1, hex = "#000000" },
        type = "rectangle",
    }

    v[1] = {
      type = "image",
      image = decodedImage:croppedCopy({ x = 15, y = 0, h = 90, w = 60 }),
      frame = { x = 0, y = 0, h = 90, w = 60 },
    }

    local fixedImage = v:imageFromCanvas()

    local encoded = fixedImage:encodeAsURLString(true)
    decodedImage = imageFromURL(encoded)

    v:delete()
    v = nil -- luacheck: ignore
end
```

Currently I'm using `encodeAsURLString(true)` to get around a scaling issue.

**Comment by dasmurphy** [comment]
I know this is a long shot and a not really good workaround, but how about making the image in accordance to the `scale`.

```lua
local scale = hs.screen.mainScreen():currentMode().scale

local v = canvas.new{x = 0, y = 0, w = 60/scale, h = 90/scale }
-- ... mode code...
-- also do this in the croppedCopy command
```

I don't know if this works fine then, but it should be producing the right size of the image in the canvas.
I also support the pixel parameter for `imageFromCanvas`.

**Comment by latenitefilms** [comment]
Owwww, that's an interesting idea. I'm not sure it'll work for my particular use case though, as the images might come from a different machine.

**Comment by asmagill** [comment]
And the problem is that pulling an image from the canvas renders an image that is in points, not pixels, correct (I'm trying to understand exactly what you're trying to end up with)?

Looking at the code for canvas and image, I *think* it would be easier to add a method to `hs.image` that converts to a bitmap (more accurately, a bitmap image representation) and returns that as a new `hs.image` object. Would that work for your case?

**Comment by asmagill** [comment]
And just to be clear before I look into this, you've tried changing the size with `hs.image:size` after cropping it, correct?

**Comment by latenitefilms** [comment]
To be honest, I'm a little bit confused as to what's breaking exactly, but I think it has something to do with DPI/resolution, rather than actual frame size.

For example, if I check the `:size()` before and after, they're the same:

```lua
2021-04-09 10:41:39: 10:41:39       ldCT:     fixedImage size: {
  __luaSkinType = "NSSize",
  h = 90.0,
  w = 60.0
}
2021-04-09 10:41:39:                          decodedImage size: {
  __luaSkinType = "NSSize",
  h = 90.0,
  w = 60.0
}
```

I've added some debugging code to the below code I'm using, and will attached the PNGs, so you can see what's happening:

```lua
--------------------------------------------------------------------------------
-- The Knob Icon isn't 60x90 pixels, so it must be a legacy icon that needs
-- to be scaled:
--------------------------------------------------------------------------------
local v = canvas.new{x = 0, y = 0, w = 60, h = 90 }

v[1] = {
    frame = { h = "100%", w = "100%", x = 0, y = 0 },
    fillColor = { alpha = 1, hex = "#000000" },
    type = "rectangle",
}

v[1] = {
  type = "image",
  image = decodedImage:croppedCopy({ x = 15, y = 0, h = 90, w = 60 }),
  frame = { x = 0, y = 0, h = 90, w = 60 },
}

local fixedImage = v:imageFromCanvas()

log.df("fixedImage size: %s", hs.inspect(fixedImage:size()))

fixedImage:saveToFile("/Users/chrishocking/Desktop/fixedImage-scale-false.png", false)
fixedImage:saveToFile("/Users/chrishocking/Desktop/fixedImage-scale-true.png", true)

--------------------------------------------------------------------------------
-- NOTE: We do this encode/decode dance because otherwise something
--       screws up with the scale. Hopefully this will eventually be
--       addressed with Hammerspoon Issue #2807.
--------------------------------------------------------------------------------
local encoded = fixedImage:encodeAsURLString(true)
decodedImage = imageFromURL(encoded)

log.df("decodedImage size: %s", hs.inspect(decodedImage:size()))

decodedImage:saveToFile("/Users/chrishocking/Desktop/decodedImage-scale-false.png", false)
decodedImage:saveToFile("/Users/chrishocking/Desktop/decodedImage-scale-true.png", true)

v:delete()
v = nil -- luacheck: ignore
```

Download the PNG's here: https://latenitefilms.digitalpigeon.com/msg/uZaIYJjNEeuCpAbIWq2rQQ/3m4Fxs7xEUjcwEaO8RtZ5w

Hope this helps!

**Comment by latenitefilms** [comment]
FYI - eventually this `hs.image` is getting fed into [`hs.image:getLoupedeckArray()`](https://github.com/CommandPost/CommandPost-App/blob/master/extensions/image/internal.m#L1501), so this issue may be specifically related to that?

**Comment by latenitefilms** [comment]
...but yes, adding a "bitmap" and then a "scale" option to `imageFromCanvas()` would probably be the right fix?

**Comment by asmagill** [comment]
@latenitefilms if I'm understanding your code correctly, I think you can bypass the whole canvas render and do something along the lines of `decodedImage:croppedCopy{ x = 15, y = 0, h = 90, w = 60 }:bitmapRepresentation{ h = 90, w = 60 }`

Let me know if this works for you.

**Comment by asmagill** [comment]
(with the recently added pull #2814, that is)

**Comment by latenitefilms** [comment]
Thanks! I think I'll have to keep using `hs.canvas` because if there's any transparent pixels, it blows up - which is why I force the black background.

Once #2814 is merged in, I'll bring it across to CommandPost and take it for a spin. Thanks heaps!!
