### ISSUE TITLE
Triggering hs.eventtap.keyStroke() quickly?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2808]
I want to trigger `hs.eventtap.keyStroke({"command"}, "=", 0)` each time I turn the knob on a control surface quickly, however, for some reason, the faster I turn, the more likely it is that the COMMAND key is "lost", and the "=" key is only triggered. I've tried using AppleScript instead, but it adds a bit too much lag. Any tips or trick @asmagill or @cmsj, or is this just a limitation of eventtaps on macOS?

**Comment by dasmurphy** [comment]
Just an idea: When turning the knob fill an array which holds all the keystrokes and start a repeating timer when it is not running. Which each timer event check if anything is remaining in the array, when yes remove one item from the array and use keyStroke, when not stop the timer. This may cause some small lag, but i think it will be working fine.

If you have questions about this idea, please ask. But it may work as a work around if no other solution is there currently.

**Comment by latenitefilms** [comment]
I've had a look at another app, which uses [`robotjs`](https://github.com/octalmage/robotjs) to trigger virtual keyboard presses in macOS, and it works perfectly. I wonder if this node module is using different macOS API's than we're using in `hs.eventtap`?

Note to self - have a proper look at: https://github.com/octalmage/robotjs/blob/master/src/keypress.c

**Comment by cmsj** [comment]
I wonder if you'd be better off making your own hs.eventtap events - you could start by emitting a `cmd` key_down event, then emit `=` down/up events and have a timer that emits the `cmd` key_up event if nothing has happened for half a second. That's how a human would repeatedly press a shortcut, I think?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now and do some testing/experimenting. Thanks team!
