### ISSUE TITLE
ability to change screen focus (not app focus)

### ISSUE THREAD

**Issue by atsepkov** [Hammerspoon/hammerspoon#281]
I've mapped a shortcut for spawning a new window for a given app (typically use this for terminals) using bindNewWin() function I got from one of the available configs. The problem I'm having now is OSX prefers to spawn the new window in the same screen/monitor as the window it happened to bring to front. Basically OSX (Yosemite) seems to refocus screen to the window that activated with launchOrFocus().

So for example, if I have a full-screen version of the terminal running on 1 monitor (with a tmux session or vimdiff) and then want to spawn another shell on my second monitor via the shortcut, OSX spawns the new window on the same monitor and auto-fullscreens it, which is somewhat annoying.

I've looked at `hs.screen` module to see if I can refocus back to original screen. It looks like I can detect the originally-focused screen via mainScreen() function, but telling Hammerspoon to refocus to a given screen is not there. I can get other screens as "objects" for scripting purposes via next(), previous(), toEast(), etc. methods, but I still can't focus to them (while keeping the app the same).

**Comment by cmsj** [comment]
I don't think it's possible to indicate that a given screen should have focus - apps get focus, so I'm not sure I see a way around this at the moment :(

**Comment by knownasilya** [comment]
Slightly related. Is there a way to open a screen if it's hidden? OR to find windows within that screen?
