### ISSUE TITLE
Crash in hs.screenRecordingState()?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2812]
`Exception 1, Code 0, Subcode 8 > Attempted to dereference null pointer.`

https://sentry.io/share/issue/ca15be252b634d88813903b0495e8411/

I can't see anything obvious in [`isScreenRecordingEnabled()`](https://github.com/Hammerspoon/hammerspoon/blob/master/Hammerspoon/MJLua.m#L273)?

Thoughts @cmsj and/or @asmagill ?

**Comment by cmsj** [comment]
Perhaps `CGWindowListCopyWindowInfo()` can return NULL?

**Comment by latenitefilms** [comment]
Bingo!

> An array of CFDictionary types, each of which contains information about one of the windows in the current user session. If there are no windows matching the desired criteria, the function returns an empty array. If you call this function from outside of a GUI security session or when no window server is running, this function returns NULL.
