### ISSUE TITLE
Feature request: package manager

### ISSUE THREAD

**Issue by wkoszek** [Hammerspoon/hammerspoon#2813]
Hammerspoon is awesome, and I'd love to have our employees use it inside of the company. It would be awesome if I could distribute the extension/plugin to people, and they could easily install / update it.

It could be something easy where if you pull up a GUI, and the Hammerspoon lists all the extensions out there, or I could maybe tell people to do:

install github.com/company/company_snippets

and it'd get all the files to disk in the right place, and maybe it could allow them to do:

update github.com/company/company_snippets

Of course former is better, but latter is something we could start from.

**Comment by latenitefilms** [comment]
Maybe relevant?

https://www.hammerspoon.org/Spoons/SpoonInstall.html

**Comment by wkoszek** [comment]
@latenitefilms I saw that, and it definitely looks like at least the backend for this is done. But from what I understand we still have a chicken and egg problem: you must install HammerSpoon, then you install this plugin, and then it almost seems like I'd need to provide folks with `init.lua` so that the SpoonInstaller can initialize all the spoons.

**Comment by cmsj** [comment]
In theory you could make a Spoon for your organisation that installs/updates all the stuff you want for your team, then they just have to install Hammerspoon and double click your Spoon file.

In general though, I'm mostly against the idea of making it too easy to make distributions on Hammerspoon. I know that's an unusual thing to say, but the reasoning is that we are a very small team with limited time and if we make this too easy to use, we'll be overwhelmed with people needing help (frankly, we already have more incoming requests for help across GitHub Issues, mailing list, IRC and subreddit, than we can handle).

Hammerspoon was always intended to be a very advanced automation platform for programmers, but we do have the example of @latenitefilms 's CommandPost fork, which is an Out-Of-The-Box distribution with some amazing features for a specific audience, but  they are doing a ton of work to make it that way.

**Comment by cmsj** [comment]
I'm going to close this on the grounds that we won't be adding a fully fledged package manager, but we can keep the discussion going if you want to talk over ideas for different ways to handle your organisation's config.
