### ISSUE TITLE
Recent changes to Xcode project prevents backwards compatibility?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2818]
@cmsj - After recent changes to the Hammerspoon project, I can no longer open it on Xcode 11.3.1 on Mojave.

<img width="532" alt="Screen Shot 2021-04-11 at 1 32 46 pm" src="https://user-images.githubusercontent.com/22286696/114291410-7ca21380-9aca-11eb-8c1a-2cf67c9a01e0.png">

Changing the project back to `objectVersion = 46;` seems to fix.

**Comment by cmsj** [comment]
huh, in Xcode itself the Project Format is set to the (hilarious) value of "Xcode 3.2 compatible"

**Comment by cmsj** [comment]
If someone knows where/how I can change this in Xcode so it stays at a slightly older version, I'm happy to do so.

**Comment by latenitefilms** [comment]
If you change the `objectVersion` back to `46`, that seems to fix.

**Comment by cmsj** [comment]
That's not a viable fix though, because as soon as I change anything else in Xcode, it will rewrite it back to the later version.

**Comment by latenitefilms** [comment]
Ummm, maybe try change the Project Format to one of the newer values? In theory, AFAIK, changing the `Project Format` should change both the `compatibilityVersion` and `objectVersion` - so in theory, it shouldn't change each time you do a change on your machine.

**Comment by latenitefilms** [comment]
The CocoaPods Xcode project now requires the latest Xcode version, and Sentry no longer builds on Mojave (you need to comment out a line of code), so I'm just going to give up compiling in Mojave for now.

**Comment by cmsj** [comment]
That's rather unfortunate :(

**Comment by latenitefilms** [comment]
For releases I need Big Sur anyway for a Universal build, so it’s not a major issue. I just dual boot between Mojave and Big Sur.
