### ISSUE TITLE
how to find the screen size of a monitor

### ISSUE THREAD

**Issue by akahanaton** [Hammerspoon/hammerspoon#2823]
Hi
Sorry, this is no a issues. I just need help on how to find the screen size or resolution of a monitor, cause I have two monitors and I want to adjust the window size according to screen size. Could some give me a hint which function can do that. Thank you very much

**Comment by dasmurphy** [comment]
Please take a look at [hs.screen](https://www.hammerspoon.org/docs/hs.screen.html).

You can test this with the mainscreen function in the console like this.
```lua
hs.inspect(hs.screen.mainScreen():currentMode())
```

**Comment by akahanaton** [comment]
> Please take a look at [hs.screen](https://www.hammerspoon.org/docs/hs.screen.html).
> 
> You can test this with the mainscreen function in the console like this.
> 
> ```lua
> hs.inspect(hs.screen.mainScreen():currentMode())
> ```
> 
> On my screen this is the result
> 
> ```
> > hs.inspect(hs.screen.mainScreen():currentMode())
> {
>   depth = 4.0,
>   desc = "1680x1050@2x 0Hz 4bpp",
>   freq = 0.0,
>   h = 1050,
>   scale = 2.0,
>   w = 1680
> }
> ```
> 
> It has the screen resolution and more informations.

It works perfectly, thank you heaps, Best regards
