### ISSUE TITLE
How to set a short delay between two eventtap

### ISSUE THREAD

**Issue by akahanaton** [Hammerspoon/hammerspoon#2828]
Hi,
For example, I have two eventtap like:
```
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.rightMouseDown, mousepoint):post()
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.rightMouseUp, mousepoint):post()
hs.eventtap.event.newKeyEvent("4", true):post()
hs.eventtap.event.newKeyEvent("4", false):post()
```
I want the key event excute 1 second later after the mouse event. But it seems in my code these two event excute simultaniously. How to setup a short delay for the later ones? I have tried 

`hs.timer.usleep(1000)`

but with no luck.

Thank you so much

**Comment by cmsj** [comment]
`hs.timer.usleep()` is measured in microseconds, so try with a value of `200000` (ie 0.2 seconds).

**Comment by cmsj** [comment]
Sorry, my comment wasn't very clear. Typically you want a short sleep between the down and up events, separate from your desire to have a 1 second delay between the mouse/keyboard events. I would do it like this:

```lua
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.rightMouseDown, mousepoint):post()
hs.timer.usleep(200000)
hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.rightMouseUp, mousepoint):post()

hs.timer.doAfter(1, function()
    hs.eventtap.event.newKeyEvent("4", true):post()
    hs.timer.usleep(200000)
    hs.eventtap.event.newKeyEvent("4", false):post()
end)
```

**Comment by akahanaton** [comment]
hi cmsj

thank you very much for your code and detailed explanation, it works now. Best regards.
