### ISSUE TITLE
URLEvent handler: supply sender pid along with URL to callback

### ISSUE THREAD

**Issue by slippycheeze** [Hammerspoon/hammerspoon#2831]
The `URLEvent` extension passes a URL open request to lua code, used to do dynamic routing in `URLDispatcher.spoon`.  I was hoping to replace Finicky, which does the same routing thing but in JavaScript, with this in hammerspoon.

Finicky has one feature that HS misses: it captures the sender PID from the AppleEvent and exposes data from it to the router, allowing me to write rules that understand the relationships between certain application/browser pairs.  I make reasonably extensive use of this in my current ruleset: just over 70 percent of the rules are sender-based.

The information is available from the `NSAppleEventDescriptor` with the key `keySenderPIDAttr`, an int32 value.  Passing only that to the URL handler callback should be sufficient to give the same level of functionality.

I did try adding this myself, but when I hit that it touches `HSOpenFileDelegate` protocol to pass the information I realised I was beyond the scope of a quick change to make this work.

**Comment by cmsj** [comment]
Thanks for this, it's a great idea and will be available in the next release.

If you're up for some testing, in about 15 minutes there will be a signed development build downloadable from https://github.com/Hammerspoon/hammerspoon/actions/runs/768434530 (be aware though that it won't auto-update to 0.9.88 when we release that, you'll have to do it manually)

**Comment by slippycheeze** [comment]
I'll see about testing that out in the next day or two—thank you so much for the quick response!

**Comment by slippycheeze** [comment]
I got to testing this: it does supply a PID for application URL lanuches.  Sends `-1` from `open` and similar, which is presumably a placeholder for "not from a specific application."   you may want to map that into lua `nil` for the sake of clarity.
