### ISSUE TITLE
LuaSkin conversion functions in modules should be static

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#2836]
This is more of a reminder list for myself (unless someone wants to get to it first).

Low priority, since we're loading the libraries via lua which doesn't "share" library bindings with other libraries it's not really a problem, but it is a bad idea.

The following NSObject conversion functions should be made static in their respective files:

~~~
% ack '^\s*id\s+to' --objc
wifi/watcher.m:406:id toHSWifiWatcherFromLua(lua_State *L, int idx) {
notify/internal.m:1366:id toNSUserNotificationFromLua(lua_State *L, int idx) {
sharing/internal.m:545:id toHSSharingServiceFromLua(lua_State *L, int idx) {
midi/internal.m:1581:id toHSMIDIDeviceManagerFromLua(lua_State *L, int idx) {
location/internal.m:740:id toCLGeocoderFromLua(lua_State *L, int idx) {
network/ping/internal.m:645:id toPingableObjectFromLua(lua_State *L, int idx) {
webview/datastore.m:431:id toWKWebsiteDataStoreFromLua(lua_State *L, int idx) {
ipc/internal.m:287:id toHSIPCMessagePortFromLua(lua_State *L, int idx) {
bonjour/internal.m:332:id toHSNetServiceBrowserFromLua(lua_State *L, int idx) {
bonjour/service.m:656:id toHSNetServiceWrapperFromLua(lua_State *L, int idx) {
serial/internal.m:1049:id toHSSerialPortFromLua(lua_State *L, int idx) {

% ack '^\s*int\s+push' --objc
axuielement/common.m:361:int pushCFTypeToLua(lua_State *L, CFTypeRef theItem, LSRefTable refTable) {
axuielement/observer.m:21:int pushAXObserver(lua_State *L, AXObserverRef observer) {
axuielement/internal.m:7:int pushAXUIElement(lua_State *L, AXUIElementRef theElement) {
axuielement/axtextmarker.m:25:int pushAXTextMarker(lua_State *L, AXTextMarkerRef theElement) {
axuielement/axtextmarker.m:33:int pushAXTextMarkerRange(lua_State *L, AXTextMarkerRangeRef theElement) {
~~~

**Comment by cmsj** [comment]
@asmagill I'm pretty sure the axuielement ones can't be static, because those are called from various places in that module (they're all declared as `extern` in the `common.h`) but otherwise #2838 should take care of the rest.

**Comment by asmagill** [comment]
You may be correct -- if a module compiles multiple obj-c files into one library, then anything which any file accesses via extern *can't* be static.

Thankfully it would trigger a compile time error, so it wouldn't last long :-)

Like I said above, this is *not* a problem but more of a stylistic issue or good programming practice... which is why I labeled it a `nit`.
