### ISSUE TITLE
Layout switching is broken after version 0.9.82 (5864)

### ISSUE THREAD

**Issue by jahson** [Hammerspoon/hammerspoon#2842]
After update to 0.9.82 I've encountered a problem — my configuration for layout switching is working very bad.

The layout switching code is here.
```
local module = {}
module.showPopUp = false
module.leftCmdLayout = "ABC"
module.rightCmdLayout = "Russian - PC"


module.eventwatcher1 = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function(e)
  local flags = e:getFlags()

  if flags.cmd
    and not (flags.alt or flags.shift or flags.ctrl or flags.fn)
    then
    module.cmdWasPressed = true
    module.cmdShouldBeIgnored = false
    return false;
  end

  if flags.cmd
    and (flags.alt or flags.shift or flags.ctrl or flags.fn)
    and module.cmdWasPressed
    then
    module.cmdShouldBeIgnored = true
    return false;
  end

  if not flags.cmd
    then
    if module.cmdWasPressed
      and not module.cmdShouldBeIgnored
      then
      local keyCode = e:getKeyCode()

      if keyCode == 0x37 then
        hs.keycodes.setLayout(module.leftCmdLayout)

        if module.showPopUp then
          hs.alert.show("English", 0.2)
        end

      elseif keyCode == 0x36 then
        hs.keycodes.setLayout(module.rightCmdLayout)

        if module.showPopUp then
          hs.alert.show("Russian", 0.2)
        end
      end
    end

    module.cmdWasPressed = false
    module.cmdShouldBeIgnored = false
  end

  return false;
end):start()


module.eventwatcher2 = hs.eventtap.new({"all", hs.eventtap.event.types.flagsChanged, hs.eventtap.event.types.NSEventTypeGesture}, function(e)
  local flags = e:getFlags()

  if flags.cmd and module.cmdWasPressed then
    module.cmdShouldBeIgnored = true
  end

  return false;
end):start()
```
I will try to add more details a little bit later.

**Comment by cmsj** [comment]
That first line with `local module = {}` -  is the `module` variable ever stored somewhere that isn't `local`? If not, it's being garbage collected by Lua.

**Comment by asmagill** [comment]
Traditionally when you start a file with `load module = {}` or similar, the file ends with `return module` -- this allows the `module` table to be captured by the lua command `require` and stored in `package.loaded`. If you're not returning `module` then @cmsj's point stands -- without you storing it somewhere, it's likely it is being garbage collected.

**Comment by jahson** [comment]
Thanks, guys, I'll try to return the module.

**Comment by jahson** [comment]
I tried to return the module, but it does not help. I'm suspecting some clash with Karabiner-Elements at the moment, because with latest version of Hammerspoon the module works almost all of the time when the Karabiner-Elements is disabled.

**Comment by jahson** [comment]
I'll probably close the issue, because I think that issue is within the code, not Hammerspoon and not Karabiner-Elements.
I think the main problem is `hs.eventtap.event.types.NSEventTypeGesture` in my code.
