### ISSUE TITLE
Crash in table_toNSFont?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2849]
`Attempted to dereference garbage pointer 0x1058bd000.`

See: https://sentry.io/share/issue/71c961a19b8d429f87aed29952af014a/

**Comment by cmsj** [comment]
I think this is not a crash in `table_toNSFont` - take a look at the bottom of the call stack, this is code triggered by an `hs.timer` callback. It looks a lot like the "weird" crashes that have been plaguing us for a long time, that I've been trying to address with the new `checkLuaSkinInstance` API on LuaSkin. I'm still not 100% that I have identified the right symptoms, and I'm a long way from 100% understanding of how it is that we're receiving events (in some cases several seconds) after we've recreated our Lua instance.

**Comment by cmsj** [comment]
If I am right about what's going on, 0.9.88 should now be explicitly logging the events to Sentry, but not crashing. We should find out in a few days as people upgrade, but even then, it doesn't get us to a point where the problem is fixed, because we still don't understand how it is that system callbacks are arriving for objects that should have been garbage collected when a Lua instance was destroyed.

**Comment by latenitefilms** [comment]
Ah, ok... I just assumed that the `table_toNSFont` was where it crashed - even though it was triggered from deep inside a `hs.timer`.

CommandPost has a billion timers running - for better or for worse, generally speaking, if I find any delays (i.e. if a `hs.chooser` takes a while to load when loaded from a HTML button), wrapping in a `hs.timer` fixes in a lot of cases.

Is it a matter of adding a check to `table_toNSFont` to make sure it's been triggered on the right Lua stack, or am I completely misunderstanding?

Dumb question... when you reload Hammerspoon, is garbage collection forcefully run (i.e. are all the current `hs.timer` objects stopped straight away and destroyed)?

When Googling "Attempted to dereference garbage pointer", I came across this which is interesting:

> Based on the App Specific info `Attempted to dereference garbage pointer`, and the fact that you're a few frames into an allocator, I believe that you are experiencing heap corruption. These kinds of crashes can be really hard to debug.
> 
> Heap corruption, which is a specific case of a memory corruption, can be hard to track down. The main reason is the source of the corruption is usually not captured at all by the stack trace. Typically, the crashes are just symptoms.
> 
> You cannot even be confident that the TwilioChatClient library is even responsible. It's totally possible, and common, for an unrelated system to just overwrite a bit of memory Twilio uses. What's worse, this could have happened much earlier in time before the now-invalid memory gets used.
> 
> What I generally recommend in these situations:
> 
> Look for other crashes that look memory-corruption-related
> Try out `Zombies` in Instruments
> Try malloc scribble, or guardmalloc, two other good memory debugging tools
> It's hard, and often even impossible, to reason about heap corruption. Replicating the bug can also be impossible, as memory corruption crashes are typically not deterministic.
> 
> So, just try to find and fix as many issues as you can. It's totally possible that one of them is responsible for a variety of crashes, one of which could be this one.

I'll close this issue for now, but feel free to re-open it if useful.
