### ISSUE TITLE
`bind` for new `hotkeys` seems to be broken since Big Sur update to 11.3.1

### ISSUE THREAD

**Issue by DanEEStar** [Hammerspoon/hammerspoon#2864]
I recently updated to Mac Big Sur 11.3.1 from something 11.2.x

Since then it seems some things in hammerspoon seem not to work anymore.
It comes down to this simple script I carved out from my config.

```
hyper = hs.hotkey.modal.new({}, 'f17')

pressedF17 = function()
    hyper:enter()
end

releasedF17 = function()
    hyper:exit()
end

hs.hotkey.bind({}, 'f10', pressedF17, releasedF17)


-- bind with "more complex" keys still works
hyper:bind({}, 'space', function() hs.alert('hello, space pressed') end)

-- bind with single keys does not work anymore...
hyper:bind({}, 'e', function() hs.alert('hello, e pressed') end)
```

The `hyper:bind({}, 'e', ...)` to a single key does not work anymore. The `hyper:bind({}, 'space', ...)` to other keys still work fine.

I tested this with the newest hammerspoon version 0.9.89. I also downgraded to 0.9.84 and there is the same behavior.

It was definitely working before, I used a more sophisticated config of that for years.

The only thing on my machine that seems to have change is the upgrade of Mac OS itself to 11.3.1. I was already on Big Sur 11.2 before and there it still worked.

Thanks a lot for the great work with Hammerspoon by the way.
Only when it does not work I remember how dependent on it I already am :)

**Comment by DanEEStar** [comment]
a reboot fixed the problem...

**Comment by svenax** [comment]
I also have this problem. More specifically, `modal:bind()` for single keys does not work in password fields. Named keys, e.g. `space` do still work, and single key binds do work outside password fields.
