### ISSUE TITLE
hs.serial broken - LuaSkin has caught an attempt to operate on an object that has been garbage collected

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2873]
@cmsj - I just tried the latest code in the `master` branch, and it seems to have broken `hs.serial`.

I'm seeing the following error when I attempt to connect to a serial device:

```lua
2021-05-12 09:21:26: 09:21:26 ** Warning:   LuaSkin: LuaSkin has caught an attempt to operate on an object that has been garbage collected.
```

Sentry Issue: https://sentry.io/share/issue/f2a529e679a24b4aa822da9779c4d474/

Any ideas?

**Comment by cmsj** [comment]
Looks like I missed a canary creation. Line 1017  (the serial port alloc/inky) needs this after it:

watcherDeviceManager.lsCanary = [skin createGCCanary];
