### ISSUE TITLE
New keybindings

### ISSUE THREAD

**Issue by jasonfurry** [Hammerspoon/hammerspoon#2876]
Hello,

I'm a mac user, who uses external mouse (razer deathadder v2) for every day use. I'm aware that it's not possible to use any type of razer synapse on big sur MacOS 11.3, but I would really love to be able to use my additional mouse buttons, which at the moment are not particularly useful. I do know, that there are external programs that can help me modify the usage of those buttons, but most of them are pay to use (steermouse) or unusable, because of errors it causes (Karabiner). I would like to ask to help me learn to write the code (or maybe redirect to same similar disccusions), which would enable my 4th and 5th mouse buttons (1st, 2nd and 3rd being left, right and middle buttons) to work as shift and control keys respectively. Thank you for your time inadvance.

**Comment by latenitefilms** [comment]
Somewhat related, I'm really interested in adding support for the Razer Tartarus V2 to Hammerspoon/CommandPost.

It's been on my to-do list for a while. Maybe a more general `hs.razer` extension could be built?

**Hardware:**
https://www.razer.com/gaming-keypads/Razer-Tartarus-V2/RZ07-02270100-R3U1

**Related:**
https://github.com/openrazer/openrazer (Linux Only)
https://github.com/z3ntu/razer_test (Works on macOS)
https://github.com/CalcProgrammer1/openrazer-win32 (Windows Only)

**Comment by jasonfurry** [comment]
> Somewhat related, I'm really interested in adding support for the Razer Tartarus V2 to Hammerspoon/CommandPost.
> 
> It's been on my to-do list for a while. Maybe a more general `hs.razer` extension could be built?
> 
> **Hardware:**
> https://www.razer.com/gaming-keypads/Razer-Tartarus-V2/RZ07-02270100-R3U1
> 
> **Related:**
> https://github.com/openrazer/openrazer (Linux Only)
> https://github.com/z3ntu/razer_test (Works on macOS)
> https://github.com/CalcProgrammer1/openrazer-win32 (Windows Only)

I'm sorry, I'm no good when it comes to coding, but could you explain what are those and what could I do with these?

**Comment by latenitefilms** [comment]
Apologies, my previous post probably isn't that helpful - it was more a reminder to myself incase I refer back to this issue in the future. Ideally I'd like to build a new Hammerspoon extension that talks directly to the Razer hardware via IOKit. I'm hoping to use openrazer as a reference.

Also, I just came across:

https://github.com/1kc/razer-macos
https://github.com/FruityRazer/FruityKit

**Comment by jasonfurry** [comment]
> Apologies, my previous post probably isn't that helpful - it was more a reminder to myself incase I refer back to this issue in the future. Ideally I'd like to build a new Hammerspoon extension that talks directly to the Razer hardware via IOKit. I'm hoping to use openrazer as a reference.
> 
> Also, I just came across:
> 
> https://github.com/1kc/razer-macos
> https://github.com/FruityRazer/FruityKit

Gotcha. I did test the following links you included and they do work, unfortunately not entirely what I was expecting. Let me know if you stumble upon something like this in the future :)
