### ISSUE TITLE
hs.window:screen documentation is inaccurate/inconsistent

### ISSUE THREAD

**Issue by wearley** [Hammerspoon/hammerspoon#2884]
The documentation says both that hs.window:screen gets 'the screen which the window is on' and that it returns 'the screen which most contains the window by area', but these are not necessarily the same thing. You can reproduce this by dragging a window between two screens, and the window it will end up on is that which your cursor mouse-upped from. You should be able to arrange a window so that only a small section of it is visible, and so the screen of the window will be the screen which least contains the window by area.

https://github.com/Hammerspoon/hammerspoon/blob/4ef364a535d3ebda26380c0ad000c15d3ad100e5/extensions/window/init.lua#L618-L626

So the simple fix is just to make the documentation say that this method returns 'the screen which most contains the window by area'. The more difficult fix is to make the method actually return the screen on which the window is displayed. Unfortunately my limited investigations with Accessibility Inspector and the Applescript Library suggests that maybe this information is not available? Does anyone know if it is technically possible to determine this information?

**Comment by cmsj** [comment]
Thanks for reporting this. I've updated the docstrings to describe the actual behaviour.
