### ISSUE TITLE
Documentation for allVolumes inaccurate for SD cards

### ISSUE THREAD

**Issue by pR0Ps** [Hammerspoon/hammerspoon#2885]
https://www.hammerspoon.org/docs/hs.fs.volume.html#allVolumes says:
> The meanings of NSURLVolumeIsEjectableKey and NSURLVolumeIsRemovableKey are not generally what they sound like. If you want a simple test as to whether or not a volume is a removable drive (e.g. a USB hard disk), check for NSURLVolumeIsInternalKey being false (this is what Finder does)

Some tests (2015 MBP running 10.14.6, irrelevant keys omitted)

Plugging a microSD card into the SD card slot using an SD card adapter:
```
{
  NSURLVolumeIsAutomountedKey = false,
  NSURLVolumeIsBrowsableKey = true,
  NSURLVolumeIsEjectableKey = true,
  NSURLVolumeIsInternalKey = true,
  NSURLVolumeIsLocalKey = true,
  NSURLVolumeIsRemovableKey = true
}
```

Plugging in the same microSD card, but using a USB-based adapter:
```
{
  NSURLVolumeIsAutomountedKey = false,
  NSURLVolumeIsBrowsableKey = true,
  NSURLVolumeIsEjectableKey = true,
  NSURLVolumeIsInternalKey = false,
  NSURLVolumeIsLocalKey = true,
  NSURLVolumeIsRemovableKey = true,
}
```

Plugging in a normal SD card (no adapter) into the SD card slot:
```
{
  NSURLVolumeIsAutomountedKey = false,
  NSURLVolumeIsBrowsableKey = true,
  NSURLVolumeIsEjectableKey = true,
  NSURLVolumeIsInternalKey = true,
  NSURLVolumeIsLocalKey = true,
  NSURLVolumeIsRemovableKey = true,
}
```

In all cases Finder shows an eject icon meaning that at the very least "this is what Finder does" isn't correct. Is there a more up-to-date source on what checks Finder uses now?

See also:
 - #1740
 - https://github.com/boyvanamstel/VolumeEjectableBug
 - https://developer.apple.com/documentation/foundation/nsurlvolumeisinternalkey

**Comment by cmsj** [comment]
Hmm, looking at the output you provided, comparing it with mine, and what Apple Engineering said 5 years ago in that VolumeEjectableBug repo..... I think the answer is that we now have no reliable way of knowing whether or not a drive is removable, and indeed our docs are no longer accurate wrt what Finder is doing.

I have an internal drive on a PCIe card and it shows `IsInternal` as `false`, I also have a SATA drive inside my Mac and it shows `IsInternal` as `true`. Neither are really "removable" in the sense we now think about drives, but I guess with this stuff all hailing from before USB was a thing, it's gotten complicated.

I'm going to update that doc text to indicate that we basically have no idea how to determine the truth of a drive, sadly. Thanks for letting me know!
