### ISSUE TITLE
drawing off for hs.chooser

### ISSUE THREAD

**Issue by whiterock** [Hammerspoon/hammerspoon#2888]
A picture tells more than my words could:
<img width="864" alt="Screenshot 2021-06-03 at 11 04 21" src="https://user-images.githubusercontent.com/6281495/120623077-abe85780-c45f-11eb-854d-1409ba5213d9.png">
I would like the cmd+1, cmd+2, etc. text to be right-justified, as I think it is supposed to be (at least all the screenshots I have found on the web pertaining to hs.chooser show it this way)

I am on Catalina OS X 10.15.7

cheers, whiterock

**Comment by latenitefilms** [comment]
This has been discussed in:

- `hs.chooser` not using full width #2633

Unfortunately I haven't been able to find a fix. When compiled in Big Sur, it works fine in Big Sur, but is broken in Catalina & Mojave. When compiled in Mojave it works fine in Mojave, but Hammerspoon now requires Big Sur to build.

**Comment by whiterock** [comment]
Ah that seems a strange bug yeah. Well I was at least able to make it aesthetically pleasing locally by fiddling around with the width parameter. It now looks like this:
<img width="476" alt="Screenshot 2021-06-04 at 11 19 09" src="https://user-images.githubusercontent.com/6281495/120779435-5b3c3180-c527-11eb-9725-287c1ee862c7.png">
However another problem I am facing now is, that if the subText is too long the keyboard shortcut text gets out of the frame like this:
<img width="476" alt="Screenshot 2021-06-04 at 11 22 24" src="https://user-images.githubusercontent.com/6281495/120779593-7eff7780-c527-11eb-975c-f583d22a76a9.png">
which does NOT seem to happen in https://github.com/Hammerspoon/hammerspoon/issues/2633. So is this a bug or am I supposed to calculate the length in pixels of the subText and adjust accordingly?

cheers, whiterock

**Comment by cmsj** [comment]
That's a bug in `hs.chooser` for sure, it should be truncating the text.

**Comment by latenitefilms** [comment]
@cmsj - Do you still have a Catalina or Mojave machine? I wonder if we can just hardcode some width values for the different macOS releases to fix the issues described in #2633 ?

**Comment by cmsj** [comment]
@latenitefilms nope, I'm Big Sur only (and from tomorrow I'll be 50% Big Sur, 50% New California Place :)

**Comment by latenitefilms** [comment]
Haha, hopefully New California Place doesn’t break too many things.

**Comment by latenitefilms** [comment]
FYI - the latest Hammerspoon build still looks funky on Mojave:

<img width="1054" alt="Screen Shot 2021-06-08 at 10 17 36 pm" src="https://user-images.githubusercontent.com/22286696/121183431-684e7d00-c8a7-11eb-823d-de6ce956e389.png">
