### ISSUE TITLE
hints module skips windows that have never had focus yet

### ISSUE THREAD

**Issue by atsepkov** [Hammerspoon/hammerspoon#289]
Hints module doesn't seem to be aware of windows that have yet to receive focus. The best example of this is if I'm using an app that takes up full screen and someone IMs me to start a new conversation. To avoid distraction, I have my messenger set up to open windows in the background. I have no way to get to that new IM now without minimizing the full-screen app because hints module will only cycle through windows that already received focus before. Once I find that IM among the stack of background windows, I can then access it through hints just fine.

**Comment by cmsj** [comment]
I'm going to guess that this is something to do with the Accessibility API, but I haven't tested it yet. I'll mark this as a bug for now, but if the OS X Accessibility APIs don't tell us about the window, there's going to be no way to solve this :(

**Comment by cmsj** [comment]
I'm closing this out because we haven't gotten to it in the last 2 years, which means it's unlikely to get worked on. If someone wants to investigate further, please feel free to re-open.
