### ISSUE TITLE
New features for macOS Monterey

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#2895]
- [x] Expose a Shortcuts intent for running Lua
- [x] Add hs.shortcuts to enumerate and run Shortcuts

**Comment by latenitefilms** [comment]
If these get added, will Hammerspoon still be able to run on Mojave?

**Comment by asmagill** [comment]
I've noted in the past that I'm willing to do some work to try and maintain compatibility with Catalina for a while yet (my iMac can't run anything newer, and I don't use it often enough to justify replacing it any time soon -- it's mostly used as a file and print server).

I suspect that any wrappers or run-time checks I'll need to add would also work for Mojave, though I may need you to test that for me as and when it occurs.

**Comment by latenitefilms** [comment]
Can do! I'm hoping to jump across to Big Sur or Monterey at some point, but I kinda just want to wait until new MacBook Pro's arrive first.

**Comment by cmsj** [comment]
The second one - enumerating and running Shortcuts from Hammerspoon, will definitely be fine with older OSes - it needs to happen by communicating with the Shortcuts Events process over Apple Events, so there's really no SDK dependency there at all.

The former one..... I have no idea yet, it'll need a static Intents definition file in the app bundle which I guess the older OSes will just ignore, and a couple of classes to handle the incoming Intents. I would guess that the SDK will let those exist in the code on older releases and we'll just have to use some `@available` macros to avoid instantiating them.

I've requested a WWDC Lab appointment for this Friday to talk to the Shortcuts team, to ask this kind of thing, so if people have any other questions about Shortcuts and Hammerspoon, now is definitely the time to ask them :)
