### ISSUE TITLE
Expose NSWindowToolbarStyle controls in hs.webview.toolbar

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2898]
Currently using `hs.webview.toolbar` doesn't look very Big Sur-y on Big Sur.

Is there a way to make it look more like this (taken on Mojave, but you get the point):

<img width="947" alt="Screen Shot 2021-06-10 at 7 27 45 pm" src="https://user-images.githubusercontent.com/22286696/121500787-f6e70980-ca21-11eb-8b73-28352773d9a5.png">

Thoughts @asmagill ?

**Comment by asmagill** [comment]
Not entirely sure what you mean by "Big Sur friendly"...

You might check out `hs.webview.toolbar:inTitleBar()` but beyond that, I'm not sure what specifically you're looking for -- can you send a picture from an app that shows what you're looking for?

**Comment by latenitefilms** [comment]
This is what `hs.webview.toolbar` currently looks like on Big Sur:

![Screen Shot 2021-06-10 at 19 38 19](https://user-images.githubusercontent.com/22286696/121513226-f5234300-ca2d-11eb-8b70-bc16f75842c9.png)

This is what it looks like on Mojave:

<img width="1478" alt="Screen Shot 2021-06-10 at 8 54 44 pm" src="https://user-images.githubusercontent.com/22286696/121513354-1ab04c80-ca2e-11eb-9346-c0ea695ca52f.png">

This is what I think of as "Big Sur-y" (i.e. centre aligned):

<img width="947" alt="Screen Shot 2021-06-10 at 7 27 45 pm" src="https://user-images.githubusercontent.com/22286696/121513606-5ea35180-ca2e-11eb-9ece-08aec1bb67d4.png">

...but thinking about it, to centre the icons, I just need to a "flexible space" on each side. And then maybe I just need to remove the window title on Big Sur to get rid of the label (I'm currently on Mojave so haven't tested myself yet).

**Comment by latenitefilms** [comment]
**Related:** Feature Request: SF Symbols access #2409

It would be nice to be able to more easily access SF Symbols using a Hammerspoon API, for this kind of use-case.

**Comment by asmagill** [comment]
Big Sur does shove the icons to the right by default, and even using flexible space in the toolbar only adjusts it a little... blame Apple's UI people.

I think the best way to get something that centers is to use flexible space on both sides, then use `toolbar:inTitleBar(true)`. Unfortunately you loose the text label underneath the icons doing this and as far as I've been able to determine thus far, there is no work around.

**Comment by latenitefilms** [comment]
Ummm, unfortunately for some reason (at least on Mojave) adding a `NSToolbarFlexibleSpaceItem` at the start and end, doesn't seem to actually work - it makes all the icons align from the right. If you manually drag in a flexible space via the "Customise Toolbar" contextual menu, it works though. Not sure if this is a bug in Hammerspoon or macOS? Will see if I can reproduce on Big Sur.

Unfortunately `toolbar:inTitleBar(true)` doesn't really work in our use-case as you loose the text labels.

I wonder how [Remote Buddy](https://www.iospirit.com/products/remotebuddy/) is doing their toolbar?

**Comment by asmagill** [comment]
Now that you mention it, I vaguely recall stumbling across a bug a while back in our implementation wrt to inserting multiple system defined tags programatically... then of course forgot to fix it. I'll add it to my list.

**Comment by latenitefilms** [comment]
Forgot to post this yesterday... this is what I was seeing in Big Sur:

<img width="1044" alt="Screen Shot 2021-06-11 at 10 37 15 pm" src="https://user-images.githubusercontent.com/22286696/121803563-a07a0500-cc85-11eb-8563-38a080f103a2.png">

**Comment by latenitefilms** [comment]
Maybe related:

- https://www.reddit.com/r/OSXTweaks/comments/k7e19l/can_we_talk_about_the_chunky_tool_bars_in_big_sur/
- https://developer.apple.com/forums/thread/667007

**Comment by latenitefilms** [comment]
Maybe we need to add the option to `hs.webview` to "Hide Title Text", and an option in `hs.webview.toolbar` to set the "Toolbar Style" (screenshot below taken from [here](https://www.reddit.com/r/OSXTweaks/comments/k7e19l/can_we_talk_about_the_chunky_tool_bars_in_big_sur/))?

![up6kzm609f361](https://user-images.githubusercontent.com/22286696/121803954-36faf600-cc87-11eb-90e0-5e396034d14a.png)

**Comment by latenitefilms** [comment]
I just came across this post:

https://cdfinder.de/blog/files/apple_window_stew.html

Specifically:

> Also, you can use a new AppKit method to bring back separate NSWindow titles and NSToolbars for your own applications in macOS 11:
> 
> ```objc
> if (@available(macOS 11.0, *))
> {
> myWindow.toolbarStyle = NSWindowToolbarStyleExpanded;
> } 
> ```
