### ISSUE TITLE
hs.usb.watcher - not loading from `require' but loads from Console

### ISSUE THREAD

**Issue by srustamo** [Hammerspoon/hammerspoon#2899]
macOS 10.14.6 (18G9216)

I have `atreus.lua` file in the`.hammerspoon` dir with this content:
```
local usbWatcher = nil

function usbDeviceCallback(data)
    if (data["productName"] == "Atreus") then
        if (data["eventType"] == "added") then
		hs.execute [["/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli" "--select-profile" "a"]]
		hs.alert("Atreus profile")
        elseif (data["eventType"] == "removed") then
			 hs.execute [["/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli" "--select-profile" "m"]]
			 hs.alert("Mac profile")
        end
    end
end

usbWatcher = hs.usb.watcher.new(usbDeviceCallback)
usbWatcher:start()
```
I use `require "atreus"` in `init.lua`

Connecting and disconnecting USB device `Atreus` does not trigger `usbDeviceCallback` function.

However, if I paste the code from `atreus.lua` directly into the hammerspoon's Console the function works. 

What is going on?

**Comment by latenitefilms** [comment]
I’m assuming it’s a garbage collection issue. Try making `usbWatcher` a global by removing `local usbWatcher = nil`.

**Comment by srustamo** [comment]
Thanks, this fixed the problem.
