### ISSUE TITLE
modules that require 10.10

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#29]
Some modules (by _asm) require 10.10. Right now, if we simply import those, Xcode forces us to build the whole app with a 10.10 requirement.

Request: figure out how to have 10.10-only modules without forcing the whole app to 10.10. I'm okay with this meaning *building* requires 10.10, especially after we cover #6 for working on specific modules 'out of band'.

**Comment by cmsj** [comment]
So, we've been going at this for a while and we haven't really run into this issue in practice, afaics. I'm going to close this issue out because I don't think we actually need to do anything at the moment. If that changes, or if anyone disagrees, please re-open :)
