### ISSUE TITLE
`hs.window.focusedWindow()` returns `nil` with Safari Technology Preview 126

### ISSUE THREAD

**Issue by ravasthi** [Hammerspoon/hammerspoon#2909]
I just installed Safari Technology Preview 126 today, and trying to run my normal window-sizing methods is failing. I think this is because `hs.window.focusedWindow()` is returning `nil`, and subsequent calls to `win:moveToUnit()` are failing with the following error: `attempt to index a nil value (local 'win')`

The method definition is quite simple:

```lua
local position = require "rpa.utils.position"
local window   = require "hs.window"

function rpa.utils.move.halfLeft()
  local win = window.focusedWindow()
  win:moveToUnit(position.halfLeft())
end

-- For reference
function rpa.utils.position.halfLeft()
  return {
    x = 0,
    y = 0,
    w = 0.5,
    h = 1
  }
end
```

I worry that this will be a problem for all native applications in Monterey. Maybe someone with a developer preview of the OS can try this out?

**Comment by norio-nomura** [comment]
It seems that `hs.window.focusedWindow()` returns `nil` because Safari Technology Preview does not have focus in its initial state. When the tab of the current page is clicked and the address is in the edit state, `hs.window.focusedWindow()` will correctly return a window.
I got around this issue by using `hs.window.frontmostWindow()` instead.

**Comment by ravasthi** [comment]
Thanks for that tip @norio-nomura! Unfortunately, though, this can fail if you have your status bar visible, as I do.

Specifically, I use `ctrl` as a modifier key in the shortcut I use to trigger my window resizing method. When I press `ctrl`to do so with Safari active, the status bar appears with a hint reading "Display a menu," and `hs.window.frontmostWindow()` (rightly) returns the status bar as the frontmost window rather than the main browser window, causing the status bar to be the target of the resize. 😞

I'll read through the documentation to see if there's another workaround.

**Comment by ravasthi** [comment]
Closing as this was fixed in a subsequent release of Safari Technology Preview.

**Comment by duhd1993** [comment]
I'm having this bug on Monterey 12.1. As you said, this seems to be a bug for all Monterey native windows, which Hammerspoon is not? Strangely, this bug is only found on my new MacBook Pro 14' with Apple Silicon
