### ISSUE TITLE
hs.mouse.scrollDirection() only ever returns "normal"

### ISSUE THREAD

**Issue by Alazoral** [Hammerspoon/hammerspoon#2910]
### Versions tested
- Hammerspoon 0.9.90 (6030)
- macOS 11.4

### Steps to reproduce
1. In the Hammerspoon Console, execute `hs.mouse.scrollDirection()`
2. Open the Mouse System Preferences panel (with attached mouse)
3. Toggle the "Scroll direction: Natural" checkbox
4. Do step 1 again

### Expected behaviour
When "Scroll direction: Natural" is checked, `hs.mouse.scrollDirection()` should return "natural", and "normal" when it is unchecked.

### Notes
I believe this is a regression as this used to work for me fantastically well, but I'm not certain whether its due to a change in Hammerspoon, macOS or both. 

As an aside, I'd like to take the opportunity to express my deep gratitude and admiration for the Hammerspoon developers and community. I believe my script that this issue affected is one of the finest pieces of software I've ever written, which consistently made me smile every time it ran, and that is down to you fine developers.

**Comment by Alazoral** [comment]
After my initial report I have done some digging. It seems like hs.mouse.scrollDirection tries to read from the user defaults domain `com.apple.swipescrolldirection` from [this line](https://github.com/Hammerspoon/hammerspoon/blob/3713f7044b860ccff6042172ebd2dd2ff2ee421a/extensions/mouse/internal.m#L109). Trying to read that in Terminal gets me:

```
❯ defaults read com.apple.swipescrolldirection
2021-06-24 11:30:14.851 defaults[93891:31826277]
Domain com.apple.swipescrolldirection does not exist
```

I only have a fairly limited experience with defaults, but if I'm accessing that correctly, it seems like it's been changed out from under us.

**Comment by latenitefilms** [comment]
Try doing this in Terminal:

`defaults read NSGlobalDomain com.apple.swipescrolldirection`

**Comment by Alazoral** [comment]
> Try doing this in Terminal:
> 
> `defaults read NSGlobalDomain com.apple.swipescrolldirection`

Interesting, that works for me, with 1 being natural and 0 being normal.

**Comment by Alazoral** [comment]
It's also working correctly in the Swift REPL:
```
❯ swift
Welcome to Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57).
Type :help for assistance.
  1> import Foundation
  3> UserDefaults.standard.bool(forKey: "com.apple.swipescrolldirection")
$R1: Bool = false
  4> UserDefaults.standard.bool(forKey: "com.apple.swipescrolldirection")
$R2: Bool = true
```

**Comment by latenitefilms** [comment]
Very strange. I'm still on Mojave, and can't boot into Big Sur currently to test.

Any ideas @cmsj or @asmagill ?

**Comment by latenitefilms** [comment]
Actually, I can reproduce on Mojave, `hs.mouse.scrollDirection()` always returns "normal".

Maybe a bug in [this line](https://github.com/Hammerspoon/hammerspoon/blob/3713f7044b860ccff6042172ebd2dd2ff2ee421a/extensions/mouse/internal.m#L265)?

**Comment by latenitefilms** [comment]
This seems to work fine:

```lua
static int mouse_scrollDirection(lua_State *L) {
    LuaSkin *skin = LS_API(LS_TBREAK);
    NSString *scrollDirection = [[[NSUserDefaults standardUserDefaults] objectForKey:@"com.apple.swipescrolldirection"] boolValue]? @"natural" : @"normal";
    [skin pushNSObject:scrollDirection];
    return 1;
}
```

...so I'm assuming it's some kind of typo when @cmsj modernised things.

**Comment by asmagill** [comment]
Change this line: https://github.com/Hammerspoon/hammerspoon/blob/3713f7044b860ccff6042172ebd2dd2ff2ee421a/extensions/mouse/internal.m#L108

Method name should match getter function, not property name, so change to “getScrollDirectionNatural”.

In transit at the moment so can’t push fix till tomorrow.
