### ISSUE TITLE
After triggering 24 times, the Keydown event failed inexplicably

### ISSUE THREAD

**Issue by Drincann** [Hammerspoon/hammerspoon#2913]
A very simple counting program, record the number of times we press any key and display.

On my machine, the counting program stops after 24 times.

OS: Mac OS Big Sur 11.4.

```lua
local counter = 0
hs.eventtap.new({hs.eventtap.event.types.keyDown}, function()
    counter = counter + 1
    hs.alert.closeAll()
    hs.alert(counter)
end):start()
```

**Comment by Drincann** [comment]
It seems that the problem lies in this function call `hs.alert(counter)`. If it is not called, the above situation will not occur.
why?

**Comment by cmsj** [comment]
`counter` should not be `local`, and you need to capture the result of `hs.eventtap.new()` into a variable as well - the problem you are seeing is almost certainly that the eventtap is being garbage collected.

**Comment by Drincann** [comment]
> `counter` should not be `local`, and you need to capture the result of `hs.eventtap.new()` into a variable as well - the problem you are seeing is almost certainly that the eventtap is being garbage collected.

Thank you. It's working.
