### ISSUE TITLE
allWindows() doesn't grab full screen windows

### ISSUE THREAD

**Issue by electrovir** [Hammerspoon/hammerspoon#292]
on OS X 10.8.5 at least.

**Comment by cmsj** [comment]
My current understanding is that this is a limitation of the OS X Accessibility API we use to get information about windows. If that is true, then I don't think there's anything we can do about this, sadly.

If anyone knows of an OSX window management tool which does see full screen windows, I would love to know about it, so we can figure out what we're missing!

**Comment by cmsj** [comment]
While there may be nothing we can do with code to resolve this, I suspect we should document that some windows aren't included.
