### ISSUE TITLE
Error in Timer stops timer

### ISSUE THREAD

**Issue by maxsnts** [Hammerspoon/hammerspoon#2920]
Hello.

Is it normal for an error in a Timer completely disabling the timer?
Is there a way around this?

Code for testing
```
function CheckTimer()
    print(" *** Check if WorkTimer running: "  )
    print(tmWork:running())
end

function WorkTimer()
    print(" *** WorkTimer run ... *** ")
    error("Error Message")
end

tmCheck = hs.timer.doEvery(2, CheckTimer)
tmWork = hs.timer.doEvery(10, WorkTimer)
```

The output is: 
```
2021-07-19 10:21:50:  *** Check if WorkTimer running: 
2021-07-19 10:21:50: true
2021-07-19 10:21:50:  *** WorkTimer run ... *** 
2021-07-19 10:21:50: 10:21:50 ERROR:   LuaSkin: hs.timer callback error: /Users/max/.hammerspoon/init.lua:592: Error Message
stack traceback:
	[C]: in function 'error'
	/Users/max/.hammerspoon/init.lua:592: in function 'WorkTimer'
2021-07-19 10:21:52:  *** Check if WorkTimer running: 
2021-07-19 10:21:52: false
```

Thank you

**Comment by gera2ld** [comment]
The document says `hs.timer.doEvery` is a shorthand for `hs.timer.new(...):start()` and `hs.timer.new` has a third parameter `continueOnError` which might be what you are looking for.

**Comment by asmagill** [comment]
Yes, by design timers do stop on errors by default -- this prevents run-away spamming to the console and other potential problems when trying to regain control of something that is designed to repeat quickly. As already noted, by using `hs.timer.new` directly, you can override this behavior on an as needed basis.

**Comment by maxsnts** [comment]
OK, Thank you
