### ISSUE TITLE
hs.razer - Add support for Razer devices

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2921]
I've discussed this before in other issues (#2447, #2876), but something I'd love to tackle sooner rather than later is add support for the Razer Tartarus V2 to Hammerspoon, offering a similar extension to `hs.streamdeck`.

**Hardware:**
- https://www.razer.com/gaming-keypads/Razer-Tartarus-V2/RZ07-02270100-R3U1

**Useful Code:**
- https://github.com/1kc/librazermacos

**Related:**
- https://github.com/1kc/razer-macos
- https://github.com/FruityRazer/FruityKit
- https://github.com/kprinssu/osx-razer-blade
- https://github.com/openrazer/openrazer (Linux Only)
- https://github.com/z3ntu/razer_test (Works on macOS)
- https://github.com/CalcProgrammer1/openrazer-win32 (Windows Only)

**Comment by latenitefilms** [comment]
Actually, after playing around with https://github.com/1kc/librazermacos it seems this really only takes care of changing the LED colours - not actually handling the button presses. By default the Razer Tartarus V2 just seems to trigger regular key presses.

@asmagill & @cmsj - I'm sure this has been discussed before, but is there anyway to modify `hs.eventtap` to target specific devices?

**Comment by latenitefilms** [comment]
It seems that most people using the Razer Tartarus V2 on macOS without the official Synapse software are basically using Karabiner-Elements to remap the default Razer Tartarus V2 keyboard layout to whatever they want.

Ideally, I don't want to rely on Karabiner-Elements, so I had a play with using `hidutil` instead, and it worked great:

```
hidutil property --matching '{"ProductID":0x022b}' --set '{"UserKeyMapping": 
 [{"HIDKeyboardModifierMappingSrc":0x70000002C,
   "HIDKeyboardModifierMappingDst":0x700000004
 }]
}'
```

In the above case I'm remapping the "20" button, which defaults to "spacebar", to the "a" key.

This `hidutil` generator is pretty handy: 

https://hidutil-generator.netlify.app

It also looks like you can do this via code as well: 

https://developer.apple.com/library/archive/technotes/tn2450/_index.html

This actual explains how `IOHIDKeyboardFilter` and `hidutil` works:

https://www.nanoant.com/mac/macos-function-key-remapping-with-hidutil

...and links to this source code:

https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-1090.260.23/IOHIDEventSystemPlugIns/IOHIDKeyboardFilter.mm

Here's the source for `hidutil`:

https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-1090.220.12/tools/hidutil/

However, whilst remapping the keys to different keys is cool - it still doesn't really solve my actual problem - in that I actually want to trigger individual Hammerspoon code for each button.

So now I'm wondering, @asmagill - does the above `IOHIDKeyboardFilter.mm` or `hidutil` code give you any ideas how we could add "device filtering" to `hs.eventtap`?

**Comment by asmagill** [comment]
As long as it doesn’t require sudo to work or other privilege escalation, I would think so. I can try and take a closer look this weekend.

**Comment by latenitefilms** [comment]
Doesn't seem to... I can just type this in Terminal:

```
hidutil property --matching '{"ProductID":0x022b}' --set '{"UserKeyMapping": 
 [{"HIDKeyboardModifierMappingSrc":0x70000002C,
   "HIDKeyboardModifierMappingDst":0x700000004
 }]
}'
```

...and it just works.

Note to self:

- https://stackoverflow.com/questions/8676135/osx-hid-filter-for-secondary-keyboard
- https://gist.github.com/GaretJax/3783042

**Comment by latenitefilms** [comment]
https://stackoverflow.com/questions/30380400/how-to-tap-hook-keyboard-events-in-osx-and-record-which-keyboard-fires-each-even

**Comment by latenitefilms** [comment]
Note to self - this code looks like it should be able to remap keys using code, taking into account the `ProductID`:

https://gist.github.com/heiner/ca5b66b673d5514e520ad8099a9c905e#file-remapping-cc

**Comment by nonissue** [comment]
Are you suggesting that support for the Tartarus will be a core part of the hammerspoon API? If so, I'm not really sure how I feel about that. Having packages in the core API to target super niche hardware products doesn't seem to fit in to my mental model of hammerspoon, but maybe I'm alone in that — ¯\\_(ツ)_\\/¯.

Side note: If you're trying to figure out what hardware key events are fired by the Tartarus, Karabiner-Elements comes with an app called 'EventViewer' which is very useful.

**Comment by latenitefilms** [comment]
I’m actually hoping to support all the Razer devices that OpenRazer already supports - at least in terms of controlling their LEDs. At this stage in terms of having a callback for button presses, I’m only working on the Razer Tartarus V2, but that could be extended fairly easily by others if they have the hardware.

In terms of niche devices, we already support Tangent panels, Stream Deck’s, etc.

Ultimately it’s up to @cmsj and @asmagil as to whether or not they merge, but if not - I can just merge directly into CommandPost. It can’t be done as a Spoon, because spoons must be Lua only.

**Comment by dasmurphy** [comment]
@latenitefilms Just a curious question from me: Would it be possible to add something to a keyboard hook in Hammerspoon to identify the keyboard where the key is pressed? Or is it already possible? I have a Delux Designer T11 keyboard where i would like to remap the keys and don't want to use the original driver.

**Comment by latenitefilms** [comment]
Unfortunately that's above my skillset - but I'm hoping @asmagill might be able to investigate this at some point. I'm HOPING it's possible, based on some of the digging above, but I'm not really sure.

In the meantime, you can use the `hidutil` Terminal command to remap keyboard keys per device. For example, I'm currently remapping all the Razer Tartarus V2 key to "dummy keys" - which mean they do nothing, then I'm using IOKit to detect the key presses, and then trigger a Lua callback. It's a bit of a hack job, but it works, and doesn't require any privilege escalation or drivers (i.e. Karabiner-Elements).

**Comment by dasmurphy** [comment]
@latenitefilms Thanks for the good answer. I may try to get some stuff working. That also is above my pay grade ;) And my spare time is currently very limited... :)

**Comment by cmsj** [comment]
So there are several things we should figure out here, which at least include:

1) Should we get into the business of RGB?
2) Are we ok with hs.razer including some GPL third party code

I've not thought for super long on this, but I think for 1) I'm ok with controlling RGB of a device that is supported in Hammerspoon for some larger reason, but I don't think we should just do RGB alone for lots of devices - OpenRGB is probably much better placed to tackle that.

For 2) I'm very torn and currently leaning towards no, but I'd really like to hear what other people think?

**Comment by latenitefilms** [comment]
I've replied to some of these questions in the pull request [here](https://github.com/Hammerspoon/hammerspoon/pull/2922#issuecomment-898968308).

> Should we get into the business of RGB?

I'm less interested in the LEDs, I was more interested in button callbacks, but figured if I was going to support the device at all, you'd want to control the LEDs too. Then I found Open Razer, and figured if I'm going to support one Razer device, why not support them all!

> I've not thought for super long on this, but I think for 1) I'm ok with controlling RGB of a device that is supported in Hammerspoon for some larger reason, but I don't think we should just do RGB alone for lots of devices - OpenRGB is probably much better placed to tackle that.

I didn't even come across OpenRGB in any of my earlier searches! Looks like it uses Open Razer too, for Razer devices.

> For 2) I'm very torn and currently leaning towards no, but I'd really like to hear what other people think?

I don't really know much about the pro's and con's of mixing and matching open source licenses, are you able to provide some more information on this? Even if this doesn't make it to Hammerspoon, I'd love your advice on this, as I do want to ideally merge it into CommandPost.

**Comment by latenitefilms** [comment]
Ahhh, I see the issue:

> **Can I use GPL-licensed code in my MIT-licensed project?**
> No. The project as a whole must conform to the terms of the GPL license and must be distributed under the terms of that license. Therefore such a project as a whole must be distributed as GPL, but can still contain MIT-licensed software.

Ummm, in that case, I wonder if `hs.razer` could just be a completely seperate extension, outside of both Hammerspoon and CommandPost?

**Comment by latenitefilms** [comment]
After looking into the whole GPL thing more deeply, I think the only option really is to drop all the Open Razer code, and go back to the drawing board in terms of controlling the LEDs for the Razer Tartarus V2.

**Comment by cmsj** [comment]
hs.razer could indeed be distributed on its own and not "infect" Hammerspoon with the GPL, but yeah if we include it then while each other file in Hammerspoon individually is still MIT licensed, the project as a whole takes on the properties of GPL.

**Comment by latenitefilms** [comment]
No worries - I'm going back to the drawing board. I'll close this issue, and start afresh.

**Comment by gingerbeardman** [comment]
Perhaps another case for #3392

**Comment by latenitefilms** [comment]
Yes, it could definitely be. Currently `hs.razer` is basically built upon `hs.streamdeck`.

The latest `hs.razer` code is currently only in CommandPost though - I haven't brought back into Hammerspoon as there wasn't really enough interest/demand.
