### ISSUE TITLE
"Fancier Hello World" example does not work

### ISSUE THREAD

**Issue by sterlinm** [Hammerspoon/hammerspoon#2925]
I've no idea if this is machine specific, but the "Fancier Hello World" example from the getting started docs does not seem to work (the first example does).

I'm on Version 0.9.90 (6030).

``` lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "W", function()
  hs.notify.new({title="Hammerspoon", informativeText="Hello World"}):send()
end)
```

Nothing happens when I plus the hotkey combination.

Thanks!

**Comment by walkersutton** [comment]
@sterlinm Do you allow notifications under `System Preferences / Notifications / Hammerspoon` ?
