### ISSUE TITLE
hs.eventtap.event.types.systemDefined does not capture brightness

### ISSUE THREAD

**Issue by AvivWn** [Hammerspoon/hammerspoon#2926]
Hi

It is seems that systemDefined event does not longer triggered for brightness change.
I am using an official apple keyboard, with macOS Big Sur.

https://github.com/Hammerspoon/hammerspoon/blob/55b8d46d5767e39b20ac6482f5b1c34c28d10e4c/extensions/eventtap/event.m#L1333

The issue can be reproduced using the AllBrightness official Spoon.
I uncommented the prints there and encountered that nothing is printed to screen when brightness is being set.

**Comment by AvivWn** [comment]
This is still an issue...
Anyone?

**Comment by toy** [comment]
This works: https://github.com/Hammerspoon/hammerspoon/issues/706#issuecomment-881958949
For example:

```lua
hs.hotkey.bind({}, 145, function() hs.eventtap.keyStroke({}, 'F1') end)
hs.hotkey.bind({}, 144, function() hs.eventtap.keyStroke({}, 'F2') end)
```

**Comment by AvivWn** [comment]
Works like a charm, thanks :)

**Comment by cmsj** [comment]
In general, for keyboards where the brightness keys aren't behaving as expected, use Karabiner Elements to set the relevant keys on the specific keyboard that isn't working, to `display_brightness_decrement` and `display_brightness_increment`
