### ISSUE TITLE
Unable to regenerate documentation for Spoon

### ISSUE THREAD

**Issue by sprak3000** [Hammerspoon/hammerspoon#2928]
I overhauled my Spoon and wanted to regenerate the documentation (`docs.json`) that goes along with it. Tried following the instructions on the [Spoon repo](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#generating) but receive this error:

```
ArrangeDesktop.spoon % pwd
/Users/luiscruz/github.com/sprak3000/Spoons/Source/ArrangeDesktop.spoon
ArrangeDesktop.spoon % hs -c "hs.doc.builder.genJSON(\"$(pwd)\")" | grep -v "^--" > docs.json
...oon.app/Contents/Resources/extensions/hs/doc/builder.lua:146: attempt to concatenate a nil value (field 'type')
```

Thought it might be something in how my Spoon is documented, but comparing Hammerspoon source file patterns doesn't have anything jumping out at me as wrong. You can see [the file on my branch](https://github.com/sprak3000/Spoons/blob/arrange-desktop-2.0/Source/AppLauncher.spoon/init.lua).

Hammerspoon is listed as latest with version 0.9.90 (6030) on macOS Big Sur 11.5.1.

Thanks in advance for any help sorting this out.

**Comment by cmsj** [comment]
hmm, I can't reproduce that error here, I'm able to generate docs for that init.lua. @asmagill is there some kind of external dependency that maybe @sprak3000 is missing?

**Comment by sprak3000** [comment]
@cmsj & @asmagill 

Any ideas on what might be happening here? The error in question seems to happen in this block of the code:

```
         if not mod then
             error("couldn't find module for "..i.def.." ("..i["type"]..") ("..i.doc..")")
         end
```

Some module, maybe mine, is not found, and the state of things at that point has the `i` variable with no `type` key.

**Comment by sprak3000** [comment]
@cmsj & @asmagill 

I decided to locally modify the source of the line throwing the error. If I do that, I can get this error message to appear when trying to generate the docs:

```
bash-3.2$ hs -c "hs.doc.builder.genJSON(\"$(pwd)\")"
-- Loading extension: doc
...oon.app/Contents/Resources/extensions/hs/doc/builder.lua:146: couldn't find module for Metadata () ()
```

Hope that might shed a bit more light on what my issue might be.

**Comment by sprak3000** [comment]
@cmsj & @asmagill 

That error helped sort me out. My code had this block in it:

```
--- Metadata
obj.name = "ArrangeDesktop"
obj.version = "2.0.0"
obj.author = "Luis Cruz <sprak3000+github@gmail.com>"
obj.homepage = "https://github.com/Hammerspoon/Spoons"
obj.license = "MIT - https://opensource.org/licenses/MIT"
```

Removing the `---Metadata` clears up the issue. Going to close this out.

Cheers.
