### ISSUE TITLE
Convert a table of hs.drawing.color objects into an NSArray of NSColor objects?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2929]
@cmsj or @asmagill - what's the best way to convert a table of `hs.drawing.color` objects into an `NSArray` of `NSColor` objects in Objective-C land?

**Comment by asmagill** [comment]
Couple of ways to do it...

If you don't mind making sure that every color sub-table has the key-value pair `__luaSkinType = "NSColor"`, then a regular `[skin toNSObjectAtIndex:idx]` will work.

A more generic and lenient method is to iterate over the table while building the array...

~~~objc
NSMutableArray *colorArray = [NSMutableArray array] ;

while (lua_next(L, idx) != 0) {
    [colorArray addObject:[skin luaObjectAtIndex:-1 toClass:"NSColor"]] ;
    lua_pop(L, 1) ; // pop value but leave key on stack for `lua_next`
}
~~~

(I should note that `lua_next` may not return the elements in order... though in my experience, as long as the table being iterated over has always been an array (i.e. has never had a non-sequential-or-non-integer key added to the table) it will be. You will probably want to use `lua_rawgeti` if you need to guarantee order.)

**Comment by latenitefilms** [comment]
Legend, thanks @asmagill !

I still don't quite have my head around it - I think because I don't quick understand how Lua stacks works.

As an example:

```lua
static int razer_keyboardBacklightsCustom(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L];
    [skin checkArgs:LS_TUSERDATA, USERDATA_TAG, LS_TTABLE, LS_TBREAK];
    
    HSRazer *razer = [skin toNSObjectAtIndex:1];
    NSArray *colors = [skin toNSObjectAtIndex:2];
    
    NSLog(@"colors: %@", colors);
    
    BOOL result = [razer setKeyboardBacklights:@"custom" speed:nil direction:nil color:nil secondaryColor:nil customColors:colors];
    lua_pushboolean(L, result);
    return 1;
}
```

As far as I can tell, `NSArray *colors = [skin toNSObjectAtIndex:2];` just returns an array of `NSDictionary` objects containing text, as opposed to actual `NSColor` objects (either that or I'm misunderstanding `NSLog` outputs).

Does that make sense?

**Comment by latenitefilms** [comment]
This is what I ended up with:

```lua
static int razer_keyboardBacklightsCustom(lua_State *L) {
    LuaSkin *skin = [LuaSkin sharedWithState:L];
    [skin checkArgs:LS_TUSERDATA, USERDATA_TAG, LS_TTABLE, LS_TBREAK];
    
    HSRazer *razer = [skin toNSObjectAtIndex:1];

    NSMutableArray *colorArray = [NSMutableArray array];
    lua_Integer i = 1;
    while (lua_rawgeti(L, 2, i) != LUA_TNIL) {
        [colorArray addObject:[skin luaObjectAtIndex:-1 toClass:"NSColor"]];        
        lua_pop(L, 1);
        i++;
    }
    lua_pop(L, 1); // the terminating nil

    BOOL result = [razer setKeyboardBacklights:@"custom" speed:nil direction:nil color:nil secondaryColor:nil customColors:colorArray];
    lua_pushboolean(L, result);
    return 1;
}
```

Thanks heaps @asmagill !

**Comment by asmagill** [comment]
Looks good! I had forgotten about `lua_rawgeti` until I was about to press "comment" on my original example, which is why I added it as a last minute note... I didn't have an example of its use in front of me at the time.

I still have hopes of doing a series of documents about writing modules with LuaSkin and I think including things like this will be useful, as it's a little non-intuitive -- while LuaSkin has helpers for grabbing singular NSObject's, it's a little less clear when grabbing an array or table of them (but still easier than with stock lua); and making the distinction between `lua_next` and `lua_rawgeti` is an important one as well.

**Comment by latenitefilms** [comment]
@asmagill - Actually, thinking about it, what if I want to allow a `nil` value in the table (i.e. `{1, 2, nil, 3, 4}`)? Is there another way I can do the `while` without having it stop on a `nil`?

**Comment by latenitefilms** [comment]
Ummm, I'm getting a `invalid key to 'next'` error when using this code.

**Comment by asmagill** [comment]
Ack, forgot to push the initial `nil` to start things off...

~~~objc
     lua_pushnil(L);  /* first key */
     while (lua_next(L, idx) != 0) {
        ... the rest of the code ...
~~~
