### ISSUE TITLE
Add ambient light sensor support

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#294]
From [this cli tool](https://stackoverflow.com/questions/17625495/how-do-you-programmatically-access-the-ambient-light-sensor-on-mac-os-x-10-5/18614019#18614019), simplified here:
```objc
// ambientlight.mm
//
// clang -o ambientlight ambientlight.mm -framework IOKit -framework CoreFoundation

#include <mach/mach.h>
#import <IOKit/IOKitLib.h>
#import <CoreFoundation/CoreFoundation.h>

static io_connect_t dataPort = 0;

int main(void) {
  kern_return_t kr;
  io_service_t serviceObject;
  CFRunLoopTimerRef updateTimer;
  uint32_t outputs = 2;
  uint64_t values[outputs];

  serviceObject = IOServiceGetMatchingService(kIOMasterPortDefault, IOServiceMatching("AppleLMUController"));
  if (!serviceObject) {
    fprintf(stderr, "failed to find ambient light sensors\n");
    exit(1);
  }

  kr = IOServiceOpen(serviceObject, mach_task_self(), 0, &dataPort);
  IOObjectRelease(serviceObject);
  if (kr != KERN_SUCCESS) {
    mach_error("IOServiceOpen:", kr);
    exit(kr);
  }

  setbuf(stdout, NULL);
  kr = IOConnectCallMethod(dataPort, 0, nil, 0, nil, 0, values, &outputs, nil, 0);
  if (kr == KERN_SUCCESS) {
    // printf("%8lld %8lld", values[0], values[1]);
    printf("%lld", values[0]);
  }
  exit(kr);
}
```
Not sure what the second value was for, it was always identical to the first one on my rMBP2012. Perhaps some models have more than one sensor?

It should be straightforward to integrate this into `hs.brightness` (says the one who doesn't get along with Xcode at all...)

**Comment by lowne** [comment]
...speaking of `hs.brightness`, for super bonus points: https://github.com/kfix/ddcctl (not sure I should open a new issue for that, so I'm just throwing it out there)

**Comment by cmsj** [comment]
@lowne ddcctl seems terrifying! I'd at least want to know if that can damage hardware if used incorrectly :)
