### ISSUE TITLE
Question: How do I move application window between virtual desktop?

### ISSUE THREAD

**Issue by phuna** [Hammerspoon/hammerspoon#295]
Hi,
Question as subject. I've checked the document and see there're API to move between screen but no API for moving between virtual desktop. Anyone help?

Thank,

**Comment by oskarols** [comment]
Hey,

I'm assuming with "Virtual desktop" you're referring to "Spaces". That functionality isn't currently in Hammerspoon. There's basically two ways of approaching this as I know it.

Either you can use https://github.com/asmagill/hammerspoon_asm.undocumented/tree/master/spaces which requires installing and using undocumented APIs.

Or you could use Mission Control either directly or via Hammerspoon to configure hotkeys that switch spaces. 
System Preferences -> Keyboard -> Shortcuts (tab) -> Mission Control

**Comment by phuna** [comment]
@oskarols Thank you for your answer. I'll check that API
