### ISSUE TITLE
hs.inspect does nothing

### ISSUE THREAD

**Issue by jasonvarga** [Hammerspoon/hammerspoon#2954]
Hi! 👋 

I feel like I must be doing something silly.

When I try to use `hs.inspect`, it just doesn't seem to do anything.

In my `init.lua`, `print('hello')` shows up in the hammerspoon console.
`hs.inspect('hello')` doesn't. It just says `Loading extension: inspect`

If I type `hs.inspect('hello')` into the console directly, it works.

Here's my `init.lua`

```lua
print('hello')
hs.inspect('inspected')
print('world')
```

```
2021-09-30 23:09:00: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2021-09-30 23:09:00: -- Lazy extension loading enabled
2021-09-30 23:09:00: -- Loading ~/.hammerspoon/init.lua
2021-09-30 23:09:00: hello
2021-09-30 23:09:00: -- Loading extension: inspect
2021-09-30 23:09:00: world
2021-09-30 23:09:00: -- Done.
```

I'm running Hammerspoon 0.9.90

**Comment by jparoz** [comment]
The return type of [hs.inspect](http://www.hammerspoon.org/docs/hs.inspect.html#inspect) is `string`. So to print something in the console, you need to print the return value of `hs.inspect`, e.g. `print(hs.inspect('inspected'))`. I do this all the time when making configuration changes, and I'm too lazy to type too much, so I define a helper function:

```lua
function printi(...)
    return print(hs.inspect(...))
end
```

Hope this helps!

**Comment by cmsj** [comment]
Thanks @jparoz - that's exactly the right answer. It's not very clear though, so I've added a note mentioning using `print()` to the `hs.inspect` docs, via 36c6495c.

**Comment by jasonvarga** [comment]
D'oh. So obvious now. Thanks!
