### ISSUE TITLE
`hs.hotkey.bind'  how to call a function twice

### ISSUE THREAD

**Issue by srustamo** [Hammerspoon/hammerspoon#2956]
I need to call a terminal command twice from a single `hs.hotkey.bind'. Is it possible?

I have this function, which calls terminal command:
```
function yabai(args)

  hs.task.new("/usr/local/bin/yabai",nil, function(ud, ...)
    print("stream", hs.inspect(table.pack(...)))
    return true
  end, args):start()

end
```

I try to bind it twice to a single hot key:
```
hs.hotkey.bind(mash,  "1", function()  yabai({ "-m", "window", "--space",  "1"}) end, function() yabai({ "-m", "space", "--focus", "1"}) end)
```
Only the first function gets exectud.

**Comment by MuhammedZakir** [comment]
Do what you want in a single function:
```lua
hs.hotkey.bind(mash,  "1", function()
  yabai({ "-m", "window", "--space",  "1"})
  yabai({ "-m", "space", "--focus", "1"})
end)
```

**Comment by srustamo** [comment]
The second call still doesn't execute.

**Comment by srustamo** [comment]
Looks like a local issue, tried a different kind of a second function and it worked  well. Thanks.

**Comment by cmsj** [comment]
My guess would be that the two calls are happening so close to each other that one of them fails (I'm assuming that yabai can only have one instance of its command line tool running at a time). Try embedding the second call in an `hs.timer.doAfter()` maybe?
