### ISSUE TITLE
hs.httpserver:websocket() closes connection after receiving one message

### ISSUE THREAD

**Issue by jparoz** [Hammerspoon/hammerspoon#2960]
I'm trying to make a basic web server to display information about some peripherals connected to a computer. I've used `hs.httpserver` before with basic GET requests returning JSON content, but this is the first time I've needed 2-way communication. WebSockets seem like the right tool to use for this, given that I want to be able to both update the webpage asynchronously from Hammerspoon, and also press an HTML button to trigger actions in Hammerspoon.

When I tried to use `hs.httpserver:websocket()`, I was successful in setting up a basic connection, and I can send messages from Hammerspoon to my web server and use the messages to update my page, etc. However, when I try to send messages from my page back to Hammerspoon, the first message is sent as expected, I can see evidence that my callback is called in Hammerspoon console, and my webpage receives the returned response. Straight after that, I see a message saying `LuaSkin: (secondary thread): Closed websocket connection`. Any messages sent from the webpage after that are not received. I've included some test code to reproduce the issue, by running the code in Hammerspoon, then connecting to `http://localhost:80` in a web browser.

I don't know why the websocket is closing after receiving a message. For the record, I am generally unfamiliar with WebSockets, and so I may be misunderstanding something more fundamental about this situation.

Thanks in advance for any help.

```lua
webserver = hs.httpserver.new()
webserver:setPort(80)
webserver:setCallback(function(type, path, headers, body)
    local html =
[[
<script>

let sock = new WebSocket("ws://localhost:80/");
sock.onmessage = function(event) {
    console.log(event);
    if (event.data) {
        document.getElementById("greeting").innerHTML = event.data;
    }
};
function SendHello() {
    console.log("Sending hello");
    sock.send("hello");
}

</script>
Greeting: <span id="greeting">Hello</span>
<button onclick="SendHello()">Test sending hello</button>
]]

    return html, 200, {["Content-Type"] = "text/html"}
end)

webserver:websocket("/", function(msg)
    print("received websocket msg: " .. msg)
    return "Received"
end)

webserver:start()
```

**Comment by jparoz** [comment]
I did actually try `hs.websocket`, but I found that when I tried to create a WebSocket using `hs.websocket.new`, I could get one of two results:
1. Calling `hs.websocket.new("ws://localhost:80/", print)` results in `fail    nil` being printed;
2. Calling `hs.websocket.new("/", print)` results in Hammerspoon crashing.
It also seemed like `hs.websocket` was designed to make a WebSocket client, whereas I'm trying to make a WebSocket server. I could very well be wrong in this conclusion as well, but I couldn't figure out from the documentation in Hammerspoon how to move forward, and my best attempts to figure it out from the various web-tech documentation sites failed as well. The most likely scenario still seems to me like I'm missing something basic, and if so I would love to know what it is!

It's possible that this crash should be a separate issue.

Thanks for the help.

**Comment by cmsj** [comment]
I have to say, I don't really know anything about WebSockets, but I think this might be a bug in CocoaHTTPServer.

I pushed up https://github.com/Hammerspoon/hammerspoon/pull/2992 as a discussion point for this. We can't merge that PR as it's editing a CocoaPod - we'd have to merge it into @latenitefilms 's CocoaHTTPServer fork, but I would really appreciate someone who knows more about this than I do, confirming that my fix makes sense.

**Comment by cmsj** [comment]
@latenitefilms it looks like you added that extra check for WS_OP_BINARY_FRAME - are you able to check and test my change with something websockety?

**Comment by cmsj** [comment]
Moved my PR to https://github.com/Hammerspoon/hammerspoon/pull/2995 to point at a new fork of CocoaHTTPServer into the Hammerspoon org, with my proposed fix.

**Comment by cmsj** [comment]
Looks like it fixes the persistent websocket test errors. I should have spotted this a long time ago :/
https://github.com/Hammerspoon/hammerspoon/pull/2995/checks?check_run_id=4263543220

**Comment by cmsj** [comment]
@latenitefilms I've merged the PR for this, because I'm pretty sure my fix is correct, but that means we now have two forks of CocoaHTTPServer on the go. Do you want to switch over to  using the one in the Hammerspoon org?

**Comment by latenitefilms** [comment]
Sorry for the lack of a response on this thread - I haven't had a chance to properly think about it yet.

Yes, I'm totally fine with the `CocoaHTTPServer` fork to be on the Hammerspoon repo - I just added it to the CommandPost one as a quick fix at the time. I'd much rather have you idiot checking any changes than me!

...and yes, that looks like it's totally my mistake with the `if` instead of the `else if` - apologies! It seems I'm only working with binary websocket data, which is why I never noticed. Thanks for fixing!
