### ISSUE TITLE
Monterey: hs.audiodevice.defaultInputDevice():setMuted(true) mutes output as well

### ISSUE THREAD

**Issue by JakeStevenson** [Hammerspoon/hammerspoon#2965]
I've got hammerspoon set up as a PTT system.  With Big Sur and headphones, this code would mute the microphone but still allow me to hear output:

`		device = hs.audiodevice.defaultInputDevice()
		device:setMuted(true)
`

In Monterey, it appears to also mute the output so I cannot hear any audio at all.

**Comment by jtgrenz** [comment]
I'd also like to +1 this or at least track the status with Apple.  I just muted myself and had a full conversation off camera totally unaware I was unmuted  and I couldn't hear anyone tell me I was unmuted because it muted my output 🤦‍♂️
