### ISSUE TITLE
hs.shortcuts Suggestions

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2984]
@cmsj - I think you're still missing in-line documentation for `hs.shortcuts.run()`?

Also, I wonder if you should also be able to run by ID, just incase there's shortcuts with the same name?

**Comment by cmsj** [comment]
Unfortunately the underlying API can only accept names. I get the sense it was a minimum-effort addition by Apple 😕

I'll check the docs, thanks!
