### ISSUE TITLE
I swap command and option key in an app(iTerm2), then hammerspoon's global key bindings don't work when the app(iTerm2) is active.

### ISSUE THREAD

**Issue by netjune** [Hammerspoon/hammerspoon#2985]
The app(iTerm2) has the function to swap the two key in its app. I enable it.

It seems that hammerspoon received the swapped key events by the app(iTerm2), so keybindings don't work.  Can hammerspoon receive the original key events before an the app(iTerm2) swaps them?

**Comment by cmsj** [comment]
It's very unlikely we'll be able to get access to the events earlier than we currently do - we use Event Taps, which is the lowest level you can do without going into the kernel. You might be able to make some of this work (including the key swap) with Karabiner Elements, which does run in the kernel and thus gets to do things before any app has seen them.
