### ISSUE TITLE
Api documention some source link page not found

### ISSUE THREAD

**Issue by KURANADO2** [Hammerspoon/hammerspoon#2993]
When I read hs.canvas API Documention，some link cannot access，show GitHub page not found
Example:
docs -> hs.canvas -> attributes -> Source -> [extensions/canvas/init.lua](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/canvas/init.lua#L15)

**Comment by cmsj** [comment]
Yeah this is an unfortunate timing thing - I'm trying to get us to a new release ASAP and that release has renamed most of the Lua files, so the links are broken for now. They'll be back once 0.9.92 is out, or if you change the start of the URL to http://www.hammerspoon.org/docs/0.9.91/ the existing links will work.
