### ISSUE TITLE
AppleScript with doEvery only execute once

### ISSUE THREAD

**Issue by lecoan** [Hammerspoon/hammerspoon#3001]
- OS: Big Sur 11.6
- Arch: x86-64

I am new to both Hammerspoon and AppleScript, so I am not sure is it a bug or just I used it in wrong manner. I want to execute some bash script (e.g., pushing to GitHub) with a timer, but I found the shell script only executed once.

```lua
cmdArr = {"cd /Users/<username> && echo test >> test.log"}

function runAutoScripts()
    for key, cmd in ipairs(cmdArr) do
        hs.osascript.applescript(string.format('do shell script "%s"', cmd))
        print('Done')
    end
end

hs.timer.doEvery(4, runAutoScripts)
```

The logs are as follow:

```
2021-11-23 12:11:15: -- Lazy extension loading enabled
2021-11-23 12:11:15: -- Loading ~/.hammerspoon/init.lua
2021-11-23 12:11:15: -- Loading extension: timer
2021-11-23 12:11:15: -- Done.
2021-11-23 12:11:19: -- Loading extension: osascript
2021-11-23 12:11:19: Done
```

 `Done` is only printed once. But if I only use `doEvery`,  everything is fine.

```lua
cmdArr = {"cd /Users/<username> && echo test >> test.log"}

function runAutoScripts()
    for key, cmd in ipairs(cmdArr) do
        -- hs.osascript.applescript(string.format('do shell script "%s"', cmd))
        print('Done')
    end
end

hs.timer.doEvery(4, runAutoScripts)
```

`Done` is printed every 4 sec.

```
2021-11-23 12:11:31: -- Lazy extension loading enabled
2021-11-23 12:11:31: -- Loading ~/.hammerspoon/init.lua
2021-11-23 12:11:31: -- Loading extension: timer
2021-11-23 12:11:31: -- Done.
2021-11-23 12:11:35: Done
2021-11-23 12:11:39: Done
2021-11-23 12:11:43: Done
2021-11-23 12:11:47: Done
2021-11-23 12:11:51: Done
```

**Comment by cmsj** [comment]
This is probably Lua Garbage Collection - try capturing the return value of `hs.timer.doEvery()` in a global variable like so:

```lua
autoTimer = hs.timer.doEvery(4, runAutoScripts)
```

**Comment by lecoan** [comment]
> This is probably Lua Garbage Collection - try capturing the return value of `hs.timer.doEvery()` in a global variable like so:
> 
> ```lua
> autoTimer = hs.timer.doEvery(4, runAutoScripts)
> ```

Thanks for your reply. Now it works properly! But I still can't understand why the second way (only print `Done`) is not affected by Lua Garbage Collection.

**Comment by latenitefilms** [comment]
Printing "done" won't take up much memory, so it could take a while before garbage collection kicks in, however when you trigger the AppleScript Objective-C code, that probably triggers garbage collection quicker. It's worth adding a `collectgarbage(); collectgarbage()` at the end of your `init.lua` to help find these kinds of garbage collection issues early on.

**Comment by cmsj** [comment]
yup, exactly what @latenitefilms. Lua triggers Garbage Collection every time its memory allocation roughly doubles. The AppleScript stuff does a lot of internal jiggery-pokery to make things work, so a lot of Lua objects get created/destroyed, dramatically increasing the chances of triggering GC.
