### ISSUE TITLE
hs.audiodevice method "setBalance(0.5)" is not working in macOS 12

### ISSUE THREAD

**Issue by legendaryaman** [Hammerspoon/hammerspoon#3005]
The **speaker balance method** is not working in macOS Monterey.

`hs.audiodevice.defaultOutputDevice():setBalance(0.5)`

<img width="427" alt="Screenshot 2021-11-26 at 9 59 12 AM" src="https://user-images.githubusercontent.com/3285444/143526894-9228b2cf-bd55-4d0d-a2f4-26e7627cba8d.png">

**Comment by cmsj** [comment]
Thanks for reporting this, it turns out it's not an issue with Monterey, I broke `:setBalance()` when updating some API calls for changes in Monterey. It will be fixed in 0.9.94, thanks very much for reporting this!
