### ISSUE TITLE
Updating Hammerspoon on MacOS 10.14

### ISSUE THREAD

**Issue by dasmurphy** [Hammerspoon/hammerspoon#3020]
The update is presented, but the updated binary does not run.... I think this should not happen, or?

Thanks for any hints... May be providing a 10.14 binary would be better... ;)

**Comment by cmsj** [comment]
Apologies, I hadn't bumped the minimum version in the updater's metadata (`appcast.xml`). As of 0.9.92, the minimum supported macOS is 10.15 (we typically only support the current release and two previous versions). I've updated the metadata now, so it should stop offering you the update.
I'm sorry this isn't better news though 😕

**Comment by dasmurphy** [comment]
No problem. I will be updating from 10.14 to Maverick in the near future. This OS feels something dated since homebrew is also not support any more and the newest Apps somehow want Big Sur as a Minimum...

**Comment by dasmurphy** [comment]
Thanks for the update also :)
