### ISSUE TITLE
You have macOS 10.14.6. The application requires macOS 10.15 or later.

### ISSUE THREAD

**Issue by nalzok** [Hammerspoon/hammerspoon#3023]
I'm getting the following error when trying to run the latest release. The last release which works for Mojave is [v0.9.91](https://github.com/Hammerspoon/hammerspoon/tree/0.9.91) released on Oct 27, 2021.

<img width="420" alt="Screen Shot 2021-12-13 at 16 04 54" src="https://user-images.githubusercontent.com/13443062/145896306-7435f77c-ad2b-4b22-84d1-24489241d14a.png">

I understand that macOS Mojave has reached its end of life on Nov 30, 2021. However, I am reluctant to upgrade because I really like some good old 32-bit applications unsupported by macOS since 10.15. Is there any chance you could release a backward-compatible build?

**Comment by cmsj** [comment]
Here is a signed and notarized build with the minimum macOS version set back to 10.14. Please note though that if this works at all, it will certainly be the last version that works on 10.14. I have some changes queued up which will make it impossible to build for an SDK that old.

[Hammerspoon-0.9.93-for-10.14.zip](https://github.com/Hammerspoon/hammerspoon/files/7707382/Hammerspoon-0.9.93-for-10.14.zip)

**Comment by MichaelMerchant** [comment]
For anyone getting this error on OSX 10.13, the latest release signed to work with 10.13 is [release 0.9.91](https://github.com/Hammerspoon/hammerspoon/releases/tag/0.9.91)
