### ISSUE TITLE
Documentation Source Field Shows Local File Path

### ISSUE THREAD

**Issue by cmpadden** [Hammerspoon/hammerspoon#3028]
The source field in the documentation is linking to a local file path.

```
https://github.com/Hammerspoon/hammerspoon/blob/master//Users/cmsj/hacking/hammerspoon/hammerspoon/extensions/layout/layout.lua#L14
```

Rendered as:

[/Users/cmsj/hacking/hammerspoon/hammerspoon/extensions/layout/layout.lua](https://github.com/Hammerspoon/hammerspoon/blob/master//Users/cmsj/hacking/hammerspoon/hammerspoon/extensions/layout/layout.lua#L14)

See screenshow below:

![image](https://user-images.githubusercontent.com/5807118/146082644-c5e9eba1-8c80-427e-aba4-faa8dbfdf4c4.png)

**Comment by cmsj** [comment]
Thanks, I completely missed that when making some build system changes. Should be fixed now.
