### ISSUE TITLE
Handle crashes coming from old Mjolnir modules

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#303]
At least one user of Hammerspoon is using an old Mjolnir installation and init.lua and is getting crashes from some module or other (I can't tell which because we don't have symbolification for Mjolnir modules).

I propose that we extend our require() wrapper to detect the loading of Mjolnir modules that we provide replacements for.
If it finds someone loading such a thing, it should set a flag in Crashlytics.
If we find ourselves starting up after a crash, and that flag was set on the preceding crash, we should display a message to the user (ideally a persistent NSUserNotification) that can take them to a FAQ entry detailing which Mjolnir modules we are able to directly replace, and how they can go about doing that.

**Comment by cmsj** [comment]
(note: this is not meant as a denigration of Mjolnir in any way, but we have fixed many crashes in the modules we brought over from Mjolnir, so it is likely that the affected user(s) would not see the same crashes from Hammerspoon, but we are unable to deliver fixes to them without rudely replacing the modules they are using, or rudely having require() silently load our modules instead)

**Comment by asmagill** [comment]
More generically, if 'require' noted the path for each module loaded, be it mjolnir or other, and flagged it (in the report) if it is external to the HS core...

Mjolnir (and HS, but for Mjolnir this was one of it's selling points) modules can come from and be stored practically anywhere and named practically anything... for Hammerspoon, almost everything is from a known specific path unless it is being developed, specifically overridden (testing updates), or is from an outside source (like Mjolnir).

Just my 2 cents on the issue.

**Comment by cmsj** [comment]
@asmagil we currently log the name of modules being require()'d and, if they are Hammerspoon ones, their location on disk. It was adding the former, which exposed the cause of some of the mystery crashes.

I'd prefer not to add any more logging, and may well want to take some out after we have this Issue closed - I feel uncomfortable every time I see a path in a crash log which starts with /Users/ :(

**Comment by asmagill** [comment]
Point taken about the user directory... could do some obfuscation by substring replacement, but that's really not addressing the underlying problem, is it?

And I do recofnize that with Mjolnir specifically, most modules do have a one-to-one replacement...

Maybe outside of the Mjolnir specific issue, just a flag that indicates if it's internal or external (i.e. doesn't begin with the BundlePath for the app)... we don't really need to know more specifically than that, do we?

--
A-Ron

**Comment by cmsj** [comment]
@asmagill Yeah I think we could look at more logging of the extensions being loaded, but for now I want to keep it very specific and as minimal as possible.

**Comment by cmsj** [comment]
Derp, this isn't finished, we need a startup check for the previous crash, and to display the notification.

**Comment by cmsj** [comment]
Closed properly by fd5f9c4
