### ISSUE TITLE
Auto Hotkey on Mac using Hammerspoon

### ISSUE THREAD

**Issue by maisumh** [Hammerspoon/hammerspoon#3031]
### Discussed in https://github.com/Hammerspoon/hammerspoon/discussions/3030

<div type='discussions-op-text'>

<sup>Originally posted by **maisumh** December 15, 2021</sup>
Hello,

I was hoping to use Hammerspoon to gain Auto Hotkey functionality that is familiar in Windows. Auto Hotkey is a script that as soon as you run it, it will save the contents of your clipboard directly to a specific key combination (ex. CMD+Shift+P). We have admin passwords that rotate daily and we would like to copy the password and run the hammerspoon script that saves the content of the current clipboard into a specific set of keys that will paste that specific password. That way if we were to override the current clipboard, that password would remain in the specific set of keys unless overridden. Additionally - if there is already content in the saved password variable, it would be overwritten with the new clipboard contents.

I'm sorry if this has been brought up before, I did research and have not been able to find something for this. I was able to find the API's that can help but am unable to fully put it together so any help or guidance would be greatly appreciated.</div>

**Comment by cmsj** [comment]
So I would do something like this:

```lua
savedPassword = nil

storePWHotkey = hs.hotkey.bind({"ctrl", "cmd"}, "s", function() 
  savedPassword = hs.pasteboard.getContents()
end)
typePW = hs.hotkey.bind({"ctrl", "cmd"}, "t", function()
  if savedPassword ~= nil then
    hs.eventtap.keyStrokes(savedPassword)
  end
end)
```

i.e. one hotkey to store the current clipboard contents into a variable (`savedPassword`) and another hotkey to type the contents of that variable.
