### ISSUE TITLE
Where's hs executable now?

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#3034]
I just updated to version 0.9.93 (6148) and `hs` (cmd line utility) appears to be gone. Is that right?

**Comment by agzam** [comment]
Messed up linking step or something like that maybe?
Found it all the way in:
`/usr/local/Caskroom/hammerspoon/0.9.93/Hammerspoon.app/Contents/Frameworks/hs/hs`

**Comment by cmsj** [comment]
We rearranged the app bundle to have all the executable code in a more appropriate place. It does unfortunately mean that symlinks and some third party paths need to change, but it now shouldn't need to move again.

**Comment by agzam** [comment]
> It does unfortunately mean that symlinks and some third party paths need to change

I don't get it, are you saying the homebrew formula/installer needs to/will be updated to symlink `hs`, so it's in the PATH, or now the end-users have to do the linking manually?
