### ISSUE TITLE
Camera never reports in use

### ISSUE THREAD

**Issue by onderweg** [Hammerspoon/hammerspoon#3046]
The property watcher receives gone events, whenever another application starts/stops the web cam. I think that's supposed to happen.
But, within the property watcher callback, camera:isInUse() seems to be always false.
Shouldn't that return true when camera is on?

(see also https://github.com/Hammerspoon/hammerspoon/issues/1255).

```lua
cameras = hs.camera.allCameras()
local firstCamera = cameras[1] -- Build in MacBook FaceTime HD Camera
firstCamera:setPropertyWatcherCallback(function(camera, property, scope, element)
    print("Camera Property Event: "..tostring(camera:name())..": "..tostring(property))
    if (camera:isInUse()) then
        -- does never happen
        print("Camera in use")
    else
        print("Camera not in use")
    end
end)
firstCamera:startPropertyWatcher()
```

**Comment by von** [comment]
I'm seeing camera:isInUse() always returning false in general.

**Comment by cmsj** [comment]
Thanks for reporting, looks like I made a mistake when refactoring the code and `:isInUse()` wasn't actually being called properly.

**Comment by cmsj** [comment]
If you'd like to try a signed/notarized development build which has the fix included, see the artefacts on https://github.com/Hammerspoon/hammerspoon/actions/runs/1729296305

**Comment by onderweg** [comment]
Thanks! 
Seems to work as expected now with the development build.

**Comment by von** [comment]
+1 - dev build works for me as well
