### ISSUE TITLE
Add drawing method to adjust window level to NSScreenSaverWindowLevel

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#306]
Per google message at https://groups.google.com/forum/#!topic/hammerspoon/5gURJT03fdI, we should allow the replacement of 'Shady' by adding a way to place a semi-transparent rectangle over the entire screen at the NSScreenSaverWindowLevel.

Would other levels not currently supported be of interest as well? (I think it currently supports only NSFloatingWindowLevel and kCGDesktopIconWindowLevelKey)

If no one can get to this sooner, I'll take a crack at it next week.

**Comment by cmsj** [comment]
Does anyone have a reason to not just replace NSFloatingWindowLevel with NSScreenSaverWindowLevel? It doesn't interfere with actual screensavers, and it makes the behaviour less confusing wrt dock/menubar IMO.

**Comment by asmagill** [comment]
I'd need to experiment with it, but I think when I mucked around with window levels (this was way back in the Hydra days, so 10.8 I think? maybe 10.9...) NSScreenSaverWindowLevel would also put it above full screen displays... can't remember if I needed to set another flag so it appeared on all screens as well or not, but... depending upon exact behavior, though, this could be a reason to allow both.

Like I said, I can play with it next week, if you like.

**Comment by cmsj** [comment]
@asmagill I'm happy to add it, it's something I'd like to have too. I'm stuck on the API though - if we don't replace Floating with ScreenSaver then I have no idea how to differentiate bringToFront(), which is Floating, and the ScreenSaver level. bringToEvenFronter() ? ;)

Actually, maybe the thing to do is add an optional boolean parameter to bringToFront(), such that it defaults to Floating, but can be twiddled to be ScreenSaver. I'll work that up and land it
