### ISSUE TITLE
Mojave support dropped unexpectedly

### ISSUE THREAD

**Issue by mikaraunio** [Hammerspoon/hammerspoon#3060]
HS running on Mojave offered to auto-update and I accepted, but it didn't restart after the update. Indeed, it seems that versions since 0.9.92 are no longer compatible with Mojave:

```
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_class
  Referenced from: /Users/mika/Downloads/Hammerspoon.app/Contents/MacOS/./Hammerspoon (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_class
  Referenced from: /Users/mika/Downloads/Hammerspoon.app/Contents/MacOS/./Hammerspoon (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6
```

I unfortunately can't say for sure whether I was running 0.9.91 or an earlier release before updating, and whether it updated to 0.9.92 or .93. I reinstalled .91 manually, and it now no longer offers updates when I choose "Check for updates..."

Is dropping Mojave support intentional? If so, do feel that should at least be clearly mentioned in the release notes.

**Comment by dasmurphy** [comment]
This should help with a new version: https://github.com/Hammerspoon/hammerspoon/issues/3023

And this clarifies the support for operating systems: https://github.com/Hammerspoon/hammerspoon/issues/3020#issuecomment-992526342

Cheers :)

**Comment by mikaraunio** [comment]
Thanks. Was sure I searched existing issues mentioning this, yet somehow missed #3020.

Guess it's time to install OpenCore on the classic Mac Pro to upgrade it beyond 10.14.
