### ISSUE TITLE
hs.window.focusedWindow() not working on Apple Silicon

### ISSUE THREAD

**Issue by duhd1993** [Hammerspoon/hammerspoon#3065]
I have a MacBook Pro 13.3 2015, and recently purchased a MacBook Pro 14'.
I find that window resizing plugin not working on the new machine.

1. hs.window.focusedWindow()  returns nil on the new machine
2. In very few cases, it works on the new machine. For example, the console window of Hammerspoon itself.
3. Both have Monterey 12.1 and Hammerspoon Version 0.9.93 (6148)

This does seem like a software issue. But both Mac's have the same version of software. I can only guess it's the architecture specific code that caused this issue.

**Comment by luckman212** [comment]
"working for me" - M1 Mac Mini on Monterey 12.1

try from your console:
```lua
hs.timer.doAfter(3, function() print(hs.window.focusedWindow():application()) end)
```
quickly flip to another window and see if the app's name is printed...

if not, check your Accessibility permissions

**Comment by latenitefilms** [comment]
If you used the Migration Assistant, try removing Hammerspoon's accessibility permission and adding it again.

**Comment by duhd1993** [comment]
> If you used the Migration Assistant, try removing Hammerspoon's accessibility permission and adding it again.

That works. Thank you!

**Comment by jacks808** [comment]
When you update Mac OS to Monterey(12.0.1), you should regrant accessibility to hammerspoon. after this operation, `hs.window.focusedWindow()` won't return nil anymore.
