### ISSUE TITLE
Build Script Errors on New Machine

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3067]
@cmsj - FYI - I'm attempting to use your fancy new build screen on a new 16-inch Apple Silicon. I've just installed Xcode, and Homebrew, but when I tried to use your `installdeps` script I got:

<img width="1298" alt="Screen Shot 2022-01-06 at 9 15 14 pm" src="https://user-images.githubusercontent.com/22286696/148367492-99b1acbd-7798-4c4d-ab03-d3445ef5b677.png">

I then tried compiling in Xcode and got this:

<img width="545" alt="Screen Shot 2022-01-06 at 9 18 13 pm" src="https://user-images.githubusercontent.com/22286696/148368123-e858e1f8-fc4d-4cbf-87ba-8d920670ccf1.png">

...so I ran:

```
python3 -m pip install -r requirements.txt
```

...which then allowed me to compile in Xcode.

**Comment by cmsj** [comment]
Well that's embarrassing, the error output telling the user to run `brew install coreutils` was mistakenly actually running the command. Should work now :)

**Comment by latenitefilms** [comment]
@cmsj - I just realised that `cocoapods` is not part of `installdeps`. I wonder if this should be added?

**Comment by cmsj** [comment]
@latenitefilms it's not required to build though, and there's more than one way to install cocoapods, so I think I'd rather leave that as an exercise for those who are motivated enough to actually be wanting to change/update/install pods.
