### ISSUE TITLE
hs.streamdeck does not support StreamDeck MK.2

### ISSUE THREAD

**Issue by jcutler** [Hammerspoon/hammerspoon#3076]
The StreamDeck extension doesn't appear to recognize the [Stream Deck MK.2](https://www.elgato.com/en/stream-deck-mk2) which has a Product ID of `0x0080`.

**Comment by jcutler** [comment]
[](url)

**Comment by cmsj** [comment]
I would definitely like to get it supported. It is a little bit tricky without having a Mk2 on hand, but if you'd be willing to try out some test builds, I can try and add the support.

**Comment by latenitefilms** [comment]
I'll try get my hands on a MkII.

**Comment by cmsj** [comment]
> I'll try get my hands on a MkII.

I would, but I already have an Original, Mini and XL on my desk 🤣

**Comment by jcutler** [comment]
> I would definitely like to get it supported. It is a little bit tricky without having a Mk2 on hand, but if you'd be willing to try out some test builds, I can try and add the support.

I would definitely try out some test builds if it would help.

**Comment by gineer01** [comment]
@cmsj : I'm curious how a new device like Mk2 can be added. Looking at the source code for hs.streamdeck, it seems to reverse-engineer the protocol to talk to the Stream Deck device. What tool do you use to view what Stream Deck device send and receive? Thanks!

**Comment by latenitefilms** [comment]
It looks like most of the hard work has been done here:

https://github.com/OpenMacroBoard/StreamDeckSharp/pull/36/commits/1ba07177dfe57913a28d1dc2031e638dc39d34ee

**Comment by jcutler** [comment]
@latenitefilms @cmsj: I put together a PR (seems identical to other gen2 StreamDecks) with a couple of functionality caveats I'm not sure are expected or not: #3089
