### ISSUE TITLE
tidal support?

### ISSUE THREAD

**Issue by slinchan1337** [Hammerspoon/hammerspoon#3077]
hi all,

is there any chance to get a tidal implementation to control the app? Or any other workaround to achiev this?
Like the one for spofity (https://www.hammerspoon.org/docs/hs.spotify.html) or deezer (https://www.hammerspoon.org/docs/hs.deezer.html).

Thanks !

**Comment by cmsj** [comment]
Does the Tidal app have an AppleScript interface? (If you open Script Editor.app and choose File->Open Dictionary, you'll see a list of all installed apps that support AppleScript)

**Comment by slinchan1337** [comment]
I cannot see it.

![image](https://user-images.githubusercontent.com/97840564/150295091-5e43dcf3-c428-4338-a0a5-c32d4b709de2.png)

**Comment by cmsj** [comment]
Unfortunately that's going to make it almost impossible for us to support in the same way as the other media players 😕

**Comment by slinchan1337** [comment]
ok thank your sir! keep up the good work! I need to check for a different solution then.

**Comment by latenitefilms** [comment]
FYI: You can still control it via menubar items and virtual shortcut keys. I'm assuming most of the playback controls will be in the app's menubar anyway?

**Comment by slinchan1337** [comment]
Can you please explain a little more in detail or just a link :) Do you have any link how to make the Tidal app shortcuts globally available that the app itself dont need to be in foreground?

Thanks!
