### ISSUE TITLE
Hammerspoon's Lua's package.cpath points to x64 path

### ISSUE THREAD

**Issue by Grazfather** [Hammerspoon/hammerspoon#3081]
I run hammerspoon on an M1 mac and I noticed that I get errors when I trying to import _.so_ files.

Turns out `package.cpath` starts with "/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so". The `.so` files in there are compiled for x86_64.

If I run `lua` (from brew) the `cpath` is set correctly to "/opt/homebrew/lib/lua/5.4/?.so;/opt/homebrew/lib/lua/5.4/loadall.so;./?.so", where ARM64 binaries live.

If I start hammerspoon with `LUA_CPATH="/opt/homebrew/lib/lua/5.4/?.so;/opt/homebrew/lib/lua/5.4/loadall.so;./?.so" /path/to/Hammerspoon` it also works.

Looks like you are hardcoding the path [here](https://github.com/Hammerspoon/hammerspoon/blob/master/LuaSkin/lua-5.4.3/src/luaconf.h#L221) which might not be appropriate for ARM, especially since `brew` keeps only x64 packages in there, and uses `/opt/homebrew/` for ARM stuff.

I can live with setting `LUA_CPATH` but I wonder whether there should be some logic in Hammerspoon itself to set the env appropriately.

Original error below

```
 *** ERROR: error loading module 'socket.core' from file '/usr/local/lib/lua/5.4/socket/core.so':
	dlopen(/usr/local/lib/lua/5.4/socket/core.so, 0x0006): tried: '/usr/local/lib/lua/5.4/socket/core.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/core.so' (no such file)
```

**Comment by latenitefilms** [comment]
It's probably easiest to just add the paths to:

https://github.com/Hammerspoon/hammerspoon/blob/master/Hammerspoon/setup.lua

Thoughts @cmsj ?

**Comment by Grazfather** [comment]
Yes but note that in my case since I DO have a _socket.so_ in my x64 directory I would never get to the 'proper' `socket` because the require crashes when it calls `dlopen` on the library with the wrong arch.

The reverse could happen for people on M1s who are running Hammerspoon on x64 (for some reason) if the order were reversed.

**Comment by latenitefilms** [comment]
Ah, I see what you mean. It could be a feature request for Lua, as I'm pretty sure Hammerspoon just imports the Lua library without any changes.

**Comment by Grazfather** [comment]
It does, but I'm saying that your suggested change to `setup.lua` maybe should check the arch it's running in (`uname -m`?) and if it's `arm64` set one path and if it's `x86_64` set another one.

**Comment by Grazfather** [comment]
Yes I did, and that's certainly how I ended up with the polluted `/usr/local/bin/lib/lua` dir. I have since cleared it out, but at the very least the problem would remain that Hammerspoon wouldn't be able to find the`socket` in /opt

**Comment by Grazfather** [comment]
I don't suggest using the migration tool for others... create a `Brewfile` and then reinstall from there.

**Comment by cmsj** [comment]
Ok, I think I have a way for us to resolve this that ought to work for most people.

At startup we detect if we're running on ARM and if so, we put `/opt/homebrew/` ahead of `/usr/local` in `package.cpath`. It's not a magic bullet solution because there are still cases where it can fail, but in the general case of either no homebrew installed, or ARM-only homebrew installed, or ARM+x64 homebrew installed, it should do the right thing.

**Comment by cmsj** [comment]
If you'd like to test the change out with a signed/notarized build, see the artefacts attached to https://github.com/Hammerspoon/hammerspoon/actions/runs/1726174041

**Comment by Grazfather** [comment]
I will test this out tonight.

**Comment by Grazfather** [comment]
Works for me on M1:

```
> package.cpath
/Users/g/.hammerspoon/?.so;/opt/homebrew/lib/lua/5.4/?.so;/opt/homebrew/lib/lua/5.4/loadall.so;/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so;./?.so;/private/var/folders/wp/n7lqy3px1zj4frbssdpqwdp40000gp/T/AppTranslocation/2DF47ED2-B36B-4ECC-91A7-2E77977D3284/d/Hammerspoon.app/Contents/Frameworks/?.dylib;/Users/g/.luarocks/lib/lua/5.4/?.so;/Users/g/.luarocks/lib/lua/5.3/?.so      
> package.path
/Users/g/.hammerspoon/?.lua;/Users/g/.hammerspoon/?/init.lua;/Users/g/.hammerspoon/Spoons/?.spoon/init.lua;/opt/homebrew/share/lua/5.4/?.lua;/opt/homebrew/share/lua/5.4/?/init.lua;/opt/homebrew/lib/lua/5.4/?.lua;/opt/homebrew/lib/lua/5.4/?/init.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/private/var/folders/wp/n7lqy3px1zj4frbssdpqwdp40000gp/T/AppTranslocation/2DF47ED2-B36B-4ECC-91A7-2E77977D3284/d/Hammerspoon.app/Contents/Resources/extensions/?.lua;/private/var/folders/wp/n7lqy3px1zj4frbssdpqwdp40000gp/T/AppTranslocation/2DF47ED2-B36B-4ECC-91A7-2E77977D3284/d/Hammerspoon.app/Contents/Resources/extensions/?/init.lua;/Users/g/.luarocks/share/lua/5.4/?.lua;/Users/g/.luarocks/share/lua/5.4/?/init.lua;/Users/g/.luarocks/share/lua/5.3/?.lua;/Users/g/.luarocks/share/lua/5.3/?/init.lua                                                                                               ~
```
