### ISSUE TITLE
hs.doc overhaul

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#309]
Is anyone using the hs.doc.fromArray or hs.doc.fromPackageLoaded methods of hs.doc?  I want to overhaul this module and allow it to concatenate multiple json files as I think I've worked out a way to allow third-party module providers to provide their own json files which can be "appended" to the built in docs ...

These 2 functions are really just hacks I threw on top of the core code (hs.doc.fromJSONFile) in a poor attempt at what I think will now easily work with the more robust core and I'd like to junk them if possible.

I will post this in the google group as well, just to make sure no one is using them...

--
A-Ron

**Comment by cmsj** [comment]
+1 junking

**Comment by asmagill** [comment]
FYI https://github.com/asmagill/hammerspoon_doc is what I will be proposing hs.doc is replaced by... it needs to be more fully tested, and I'd like to be able to give module developers a zip file that they can simply expand into their development directory, execute a couple of commands, and start including their own documentation, but this should give you an idea of what I envision.

Thoughts or comments welcome.

**Comment by cmsj** [comment]
looks good. Would you envision us recommending that authors explicitly push their docs into HS as part of their init.lua?

**Comment by asmagill** [comment]
That's certainly a possibility, especially if I can get the build process better at giving constructive errors.

**Comment by asmagill** [comment]
Ok, some thought on this...

Yes, I would like to see a mechanism where developers who provide modules which for whatever reason are not included in core can have their documentation added, at least via the console, automatically on module load.  Not saying we should require it, but we should provide for it.  So... task list (mostly so I can keep it straight... let me know if you think there are steps I'm missing or forgot...)

- [ ] need a simple bundle for developers which includes gencomments, genjson, and supporting ruby/github library/definition files that are not OS X standard (I forget what they are, so substep - [ ] figure that out) so that they can easily add these to their development process.  This can be included in the HS resources dir, or as a separate download.
- [ ] genjson needs to issue errors with line numbers/filenames so it's obvious what needs to be fixed when it chokes
- [ ] gencomments needs to insert blank line before/after each file included to keep doc comments from running together because of missing breaks due to comments at very top or bottom of file
- [ ] hs.doc needs to issue clear errors when it can't parse something... passing genjson and hs.json.decode is a start, but not enough.
- [ ] need a way to validate docs from makefile/developer directory without fully loading into HS.
- [ ] hs.doc needs to warn/error when overwriting an existing definition
- [ ] hs.doc needs to intelligently merge paths so that adding hs.a after hs.a.x... doesn't obliterate hs.a.x -- currently we get around this by sorting, but since we're going to allow an arbitrary load order, this isn't enough anymore 

Have I missed anything?

**Comment by asmagill** [comment]
As a side item, I've added makeLuaDocs.lua and lua.json to  https://github.com/asmagill/hammerspoon_doc... the makeLuaDocs.lua file is more for example purposes (though it needs to be cleaned up some), but what it does is go to Lua's web site and grab the contents and manual html and parse them into lua.json... This can be loaded with the in progress hs.doc (maybe with the original as well... I should check that out) and, if you're using the __tostring method documented  at the site, you can type in things like `doc.lua.string.gsub` or `doc.lua._man._6_4_1` to pull directly from the lua documentation.

If we decide to include the lua docs, I would recommend using the json file only, though keep the lua file around as an example of doc building and in case the web site updates or version changes again.

**Comment by asmagill** [comment]
I'm going to be uploading this as a pull soon along with the lua 5.3 manual documentation added to the help command.  I've been going back in forth in my mind, however, about whether or not the __tostring method of accessing the help should be added to setup.lua as well... basically, it's the difference between typing `help("hs.application")` and `doc.hs.application` (or, taking inspiration from inspect, `help.hs.application`).

The lua additions will allow you to do things like:

`help("lua.string.gsub")` or `help.lua._man._6_4_1` to get the docs from section 6.4.1 of the lua manual, etc.

I'll also include the lua file to generate the lua.json file, in case we need to invoke it in the future, but it will normally sit dormant in the apps resources.

Thoughts?  Preferences?  I'm leaning to enhancing `help` itself so it's both the function and the table necessary for both methods if no one else has objections or preferences.

**Comment by cmsj** [comment]
@asmagill does __tostring get us the long-sought ability to do help(hs.application)?

**Comment by cmsj** [comment]
(and no, I have no objections)

**Comment by asmagill** [comment]
The problem with help(hs.whatever.function) is that the lua parser tries to convert hs.whatever.function into a lua data type before the help function is ever called.  The doc.X tostring method I've described actually creates each of these pieces as tables, so when I type `doc.hs.application.runningApplications`, lua is looking at a data structure that exists and looks something like:

doc = { hs = { application = { runningApplications = {...}, ...}, ...}, ...}

And it is the innermost table for runningApplications which has the tostring output corresponding to the help info for hs.application.runningApplications.

It is probable that I could merge help and auto-load such that the auto-load hidden table maps to locations in (for the above example) doc, but this would only allow us to get help up to the module name, not it's children (i.e. functions) until the module is actually loaded (then we might be able to use the same trick to map function addresses).  This wouldn't work for userdata methods that don't also exist in the __index of the parent module and it wouldn't allow for "fake" entries that are just informational (e.g. if a module wanted to have a section in it's help that gave examples, etc. but didn't correspond to an actual real function or piece of data -- I don't think any currently do this except for the lua documentation I'll be introducing with the update, but it's been possible)

I'll plan on adding the update so that `help("whatever")` and `help.whatever` work, and then look into what would be involved with integrating this with the autoload pseudo-tables.

Just had a thought... another approach might be to allow the insertion of a "pre-parser" (I think hs.ipc provides for this already, so we'd just have to add it to the console) that is invoked after something is submitted via the console, but before it is actually parsed by the lua interpreter... basically, the user input is sent as a string to a function which does whatever it wants to the string then returns it, and it's this returned string that is considered the users input... quote levels could become an issue (e.g. if I type `print("help(hs.application)")`, it shouldn't change anything, but if I type `print(help(hs.application))` it should) but that's tractable... or maybe we just limit it to "If the first 4 chars are 'h' 'e' 'l' and 'p'..."

I need to work on hs.ipc soon anyway to make it safer with bad utf8 data, so I'll play with pre-parsing then and see how well it works... I'm thinking that's the better way to go for the help update after this.

**Comment by cmsj** [comment]
The pre-parser is a great idea!

**Comment by asmagill** [comment]
Addressed by #414 for now.  Open a separate issue for the pre-parser, if you think it should be given a higher priority.
