### ISSUE TITLE
CommandPost & New Build Script

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3094]
Ok @cmsj, the time has come for me to finally work out how I can build CommandPost again!

I'm currently getting stuck on:

```
Signing CommandPost.app (in target 'Hammerspoon' from project 'Hammerspoon')
[Hammerspoon] Touching CommandPost.app
Archive Succeeded
+ '[' archive == archive ']'
+ xcodebuild -exportArchive -archivePath /Users/chrishocking/Documents/GitHub/CommandPost-App/build/Hammerspoon.app.xcarchive -exportOptionsPlist 'Hammerspoon/Build Configs/Archive-Export-Options.plist' -exportPath /Users/chrishocking/Documents/GitHub/CommandPost-App/build
objc[59784]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1eceb2b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104bb02c8). One of the two will be used. Which one is undefined.
objc[59784]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1eceb2be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104bb0318). One of the two will be used. Which one is undefined.
2022-01-26 17:20:52.855 xcodebuild[59784:6663006] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/fw/nrl3xr1d2j93lrbqwkpwthb80000gn/T/Hammerspoon_2022-01-26_17-20-52.855.xcdistributionlogs".
2022-01-26 17:20:52.864 xcodebuild[59784:6663006] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key "method": expected one of {}, but found developer-id

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "method": expected one of {}, but found developer-id" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "method": expected one of {}, but found developer-id}

** EXPORT FAILED **
```

...when running:

```
./scripts/build.sh build -d -y CommandPost
```

Any ideas?

**Comment by latenitefilms** [comment]
Looks like I've run into the same issue as #3043 - although I do have a Developer account.

**Comment by cmsj** [comment]
if you take a look at the `Hammerspoon-Debug.xcconfig` and `Hammerspoon-Release.xcconfig` files in `Hammerspoon/Build Configs/` they should both end with an optional include:

```#include? "../../../Hammerspoon-Downstream.xcconfig"```

If that file exists (so it would be one directory level above the repo checkout) any values in it will override things already set in the existing `.xcconfig` files, so you can set the signing things to whatever you need:

```
CODE_SIGN_IDENTITY = Developer ID Application
DEVELOPMENT_TEAM = VQCYSNZB89
```

On thinking about it since you filed this issue, I wonder if that `-Downstream.xcconfig` file should actually be in the repo, since a fork is maintaining a repo of some kind.

Just getting the `DEVELOPMENT_TEAM` right *ought* to make it build & export properly, but if it doesn't, we'll keep digging and refactoring these build configs until it does work, because half of the point of doing it was to make forks easier to manage :)

**Comment by latenitefilms** [comment]
Legend, thanks! I'll test adding a `Hammerspoon-Downstream.xcconfig` file now.

**Comment by latenitefilms** [comment]
That definitely did something - as I was prompted for my password for `codesign`, and it seemed to sign everything successfully, but it still failed on:

```
Signing CommandPost.app (in target 'Hammerspoon' from project 'Hammerspoon')
[Hammerspoon] Touching CommandPost.app
Archive Succeeded
+ '[' archive == archive ']'
+ xcodebuild -exportArchive -archivePath /Users/chrishocking/Documents/GitHub/CommandPost-App/build/Hammerspoon.app.xcarchive -exportOptionsPlist 'Hammerspoon/Build Configs/Archive-Export-Options.plist' -exportPath /Users/chrishocking/Documents/GitHub/CommandPost-App/build
objc[87366]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1eceb2b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080bc2c8). One of the two will be used. Which one is undefined.
objc[87366]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1eceb2be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080bc318). One of the two will be used. Which one is undefined.
2022-01-26 21:09:14.346 xcodebuild[87366:6758862] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/fw/nrl3xr1d2j93lrbqwkpwthb80000gn/T/Hammerspoon_2022-01-26_21-09-14.345.xcdistributionlogs".
2022-01-26 21:09:14.353 xcodebuild[87366:6758862] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key "method": expected one of {}, but found developer-id

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "method": expected one of {}, but found developer-id" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "method": expected one of {}, but found developer-id}

** EXPORT FAILED **
```

It seems to be failing on:

```
xcodebuild -exportArchive -archivePath /Users/chrishocking/Documents/GitHub/CommandPost-App/build/Hammerspoon.app.xcarchive -exportOptionsPlist 'Hammerspoon/Build Configs/Archive-Export-Options.plist' -exportPath /Users/chrishocking/Documents/GitHub/CommandPost-App/build
```

`Archive-Export-Options.plist` is just the same as in Hammerspoon:

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>destination</key>
    <string>export</string>
    <key>method</key>
    <string>developer-id</string>
</dict>
</plist>
```

`Hammerspoon.app.xcarchive` also exists.

Any ideas?

**Comment by latenitefilms** [comment]
Ok, I think it has something to do with `hs.razer` and/or `hs.speededitor`, as I just tried doing `./scripts/build.sh build -d` on the main Hammerspoon repo, and it worked as expected.

Is there something special I need to do with new extensions that I didn't have to do previously?

**Comment by latenitefilms** [comment]
Here's what the Archive generated from the main Hammerspoon repo looks like:

<img width="1136" alt="Screen Shot 2022-01-26 at 9 38 39 pm" src="https://user-images.githubusercontent.com/22286696/151148596-5b3887d5-5904-40b1-83c4-93a6604cafaa.png">

Here's what it looks like when generated from the CommandPost-App repo:

<img width="1136" alt="Screen Shot 2022-01-26 at 9 39 02 pm" src="https://user-images.githubusercontent.com/22286696/151148714-75625a58-cb7a-4157-b317-62962759556d.png">

Comparing the bundles, it looks like this is the culprit:

<img width="1118" alt="Screen Shot 2022-01-26 at 9 42 27 pm" src="https://user-images.githubusercontent.com/22286696/151149084-96c1e2e5-0be9-4d3f-88e5-177d3d2ccfde.png">

**Comment by cmsj** [comment]
huh, what the heck is `alert.dylib`? Our `hs.alert` is pure Lua

**Comment by cmsj** [comment]
but I will say that when you see stuff in those bundles that's going into `usr/local` it likely means something isn't being handled in the `Copy Extensions Dylibs` build phase. I hit that early on when figuring out the Archive & Export commands

**Comment by cmsj** [comment]
It might be librazer.dylib - looking at that PR, the xcodeproj changes have `productName = alert` - maybe its target needs to be renamed and it needs to be added to that build phase?

**Comment by latenitefilms** [comment]
Bingo! It seems there's a few demons in my Xcode project, haha.

Whilst I've got you, it seems I can no longer do `require("hs.eventtap.event")` - is this an expected side-effect of the changes you've made?

**Comment by cmsj** [comment]
hmm, no that doesn't sound right. I'll dig into it

**Comment by latenitefilms** [comment]
There's still some funkiness in my Xcode project, but I can't remove any of these weird duplicates without Xcode crashing, haha:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/22286696/151244944-48d01902-bce0-494e-9984-9e9ac5bf1f37.png">

@cmsj - I can't see any specific options in the build settings - what's required to make Sparkle work again?

`LuaSkin: Sparkle Update framework not available for the running instance of CommandPost.`

**Comment by cmsj** [comment]
hmm, Sparkle ought to be linked in automatically in a Release build

**Comment by latenitefilms** [comment]
I've tried using:

```
./scripts/build.sh build -s Release -d
```

...but it still says:

```
2022-01-27 20:25:47: 20:25:47 ** Warning:   LuaSkin: Sparkle Update framework not available for the running instance of CommandPost.
```

Potentially another merge issue/conflict?

**Comment by latenitefilms** [comment]
Ummm, nope, `MJAppDelegate.m` and `MJLua.m` seem basically the same - just with a lot of CommandPost's instead of Hammerspoon's.

**Comment by latenitefilms** [comment]
There's also no Sparkle in the Frameworks folder after building, so something is preventing it from copying over.

**Comment by latenitefilms** [comment]
I just had a look at `Pods-Hammerspoon-frameworks.sh` which has:

```python
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_framework "${PODS_ROOT}/Sparkle/Sparkle.framework"
fi
```

...so I think the problem is that I need the build scheme and build configuration to be "Release".

However, when I try this:

```
./scripts/build.sh build -s Release -c Release -d
```

I now just get a lot of errors like:

```
❌ error: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "VQCYSNZB89" with a private key was found. (in target 'pasteboardwatcher' from project 'Hammerspoon')
```

Any ideas what I'm misunderstanding @cmsj ?

**Comment by cmsj** [comment]
Hmm, it could be LuaSkin at fault here - its `.xcconfig` doesn't have a downstream override include. Did you end up using an override `.xcconfig` file? If so, that will need to have an optional include in `LuaSkin/LuaSkin-Release.xcconfig`. Sorry for missing that one!

**Comment by latenitefilms** [comment]
Also, whilst I've got you... where's the right place to set `SENTRY_ORG` and `SENTRY_PROJECT`?

**Comment by cmsj** [comment]
At the moment, they're environment variables that `build.sh` will inherit if they exist, but if it would be more useful for you to have them as arguments to `build.sh` we can absolutely change that.

**Comment by latenitefilms** [comment]
@cmsj - Even if you don't want to add DMG support to the Hammerspoon build script, one thing that would be handy would be to add an argument to allow you to notarise the DMG file as opposed to the `.app` bundle, so that I could still use your build script to notarise the DMG. Thoughts?

**Comment by cmsj** [comment]
I am completely happy for our build system to support DMG. I don't plan on using it, but it'll be less work for CP if you're nit carrying that stuff as a patch 🙂

**Comment by latenitefilms** [comment]
@cmsj - I finally got around to tweaking our CommandPost build script so that it actually works:

https://github.com/CommandPost/CommandPost/blob/develop/scripts/build_commandpost_release.sh

Currently I'm doing all the notarisation stuff in the above script (as opposed to using your awesome Hammerspoon build script) - because it's looking for the `.app` file, whereas I want to notarise the entire `.dmg`. It's essentially all the same code as your previous build script.

Any suggestions on the best way to use your existing notarisation functions to notarise my `.dmg`? Could you just update your build script to have a variable for the notarisation file extension, so all I need to do is change one variable? Thoughts?

**Comment by cmsj** [comment]
@latenitefilms check out #3142 - it adds a new argument for the `notarize` command, specifically `-z` so you can build your dmg and then use `-z` to pass the path of the DMG. I've not tested it super well, but I think it should work.
You'll also need to pay attention to the Note in the `NOTARIZATION OPTIONS` section of `build.sh --help`.

I think the DMG/Uninstall stuff should probably stay in your script, particularly since the DMG stuff uses a third party tool, and the appcast generation is different because you use DSA keys and we don't. I wouldn't necessarily be opposed to adding that to our appcast though, so we're even closer.

**Comment by latenitefilms** [comment]
Thanks so much! Will test it out later today.

Are you able to merge into "master"?

Totally agree with DMG/Uninstall stuff. Currently I'm still just using the commercial tool [DMG Canvas](https://www.araelium.com/dmgcanvas) for the DMG creation, however it should be easy enough to swap out with [create-dmg](https://github.com/create-dmg/create-dmg) at some point - and then it's possible we could add to the Hammerspoon build script.

I haven't yet played with GitHub Actions, and I currently just update the AppCast manually - but eventually I'd like to basically duplicate everything you've automated in Hammerpoon.

Regarding DSA keys:

> Sparkle before version 1.21 used to use only older DSA signatures, which are now deprecated. They are however still supported for migration purposes. We strongly recommend migrating over to EdDSA (ed25519) and planning to drop DSA signatures in new updates of your applications.

**Comment by asmagill** [comment]
Trying out the new build process so I can *finally* start contributing again (I think I need to rewrite my proposed changes to axuielement and spaces from scratch as an attempt to merge them caused a bunch of conflicts... figured it was best to start from a known good build)...

Looking at `LuaSkin/LuaSkin-Release.xcconfig` I see that it still lists VQCYSNZB89 (yours @cmsj?) as the development team and doesn't check for the upstream file like the` Hammerspoon-Debug.xcconfig` does... is this an issue for development builds or just release ones?

Also, do I need to worry about notarization with Development builds? And if so, what's the process -- never done that before.  Oh and do I need to do anything special regarding entitlements?

**Comment by latenitefilms** [comment]
I'll leave @cmsj to answer the specifics incase I say anything wrong, but in the meantime, AFAIK, you should be able to compile Hammerspoon in Xcode now without any special tricks or requirements.

**Comment by latenitefilms** [comment]
@cmsj - Any chance you could put the below into its own function, so that I can easily call it from my release script using an optional variable?

```bash
    # Upload dSYMs to Sentry if so desired
    if [ "${UPLOAD_DSYM}" == "1" ]; then
        export SENTRY_ORG="${SENTRY_ORG:-hammerspoon}"
        export SENTRY_PROJECT="${SENTRY_PROJECT:-hammerspoon}"
        export SENTRY_LOG_LEVEL=error
        if [ "${DEBUG}" == "1" ]; then
            SENTRY_LOG_LEVEL=debug
        fi
        export SENTRY_AUTH_TOKEN
        "${HAMMERSPOON_HOME}/scripts/sentry-cli" upload-dif "${HAMMERSPOON_XCARCHIVE_PATH}/dSYMs/" 2>&1 | tee "${BUILD_HOME}/sentry-upload.log"
    fi
```

**Comment by cmsj** [comment]
> Are you able to merge into "master"?

Merged as of last night :)
 
> swap out with [create-dmg](https://github.com/create-dmg/create-dmg) at some point - and then it's possible we could add to the Hammerspoon build script.

huh, is there not a built-in tool for doing it on macOS? (I've never actually built a DMG)

> Regarding DSA keys:
> 
> > Sparkle before version 1.21 used to use only older DSA signatures, which are now deprecated. They are however still supported for migration purposes. We strongly recommend migrating over to EdDSA (ed25519) and planning to drop DSA signatures in new updates of your applications.

I also noticed, in the Xcode console after merging the newer Sparkly:

```
Hammerspoon[46364:3661086] [Sparkle] Error: Serving updates without an EdDSA key and only using Apple Code Signing is deprecated and may be unsupported in a future release. Visit Sparkle's documentation for more information: https://sparkle-project.org/documentation/#3-segue-for-security-concerns
```

which suggests that Hammerspoon is going to need to adopt the additional signing keys at some point too.

**Comment by cmsj** [comment]
> Looking at `LuaSkin/LuaSkin-Release.xcconfig` I see that it still lists VQCYSNZB89 (yours @cmsj?) as the development team and doesn't check for the upstream file like the` Hammerspoon-Debug.xcconfig` does... is this an issue for development builds or just release ones?

Shouldn't affect dev builds, but yeah that will break release builds for anyone who doesn't have my signing keys/certs. Thanks, I should have added an override include for that as well. Fixed in f41952d0

> Also, do I need to worry about notarization with Development builds? And if so, what's the process -- never done that before. Oh and do I need to do anything special regarding entitlements?

No need to notarize for dev builds, that's just a release thing.

**Comment by latenitefilms** [comment]
> huh, is there not a built-in tool for doing it on macOS? (I've never actually built a DMG)

Yes, you can build DMGs from Terminal, but it's the "formatting" that's the pain (i.e. adding a nice background, spacing out the icons nicely, adding a EULA popup if you want, etc.) - which is why I use DMG Canvas currently.

**Comment by latenitefilms** [comment]
> @cmsj - Any chance you could put the below into its own function, so that I can easily call it from my release script using an optional variable?
> 
> ```shell
>     # Upload dSYMs to Sentry if so desired
>     if [ "${UPLOAD_DSYM}" == "1" ]; then
>         export SENTRY_ORG="${SENTRY_ORG:-hammerspoon}"
>         export SENTRY_PROJECT="${SENTRY_PROJECT:-hammerspoon}"
>         export SENTRY_LOG_LEVEL=error
>         if [ "${DEBUG}" == "1" ]; then
>             SENTRY_LOG_LEVEL=debug
>         fi
>         export SENTRY_AUTH_TOKEN
>         "${HAMMERSPOON_HOME}/scripts/sentry-cli" upload-dif "${HAMMERSPOON_XCARCHIVE_PATH}/dSYMs/" 2>&1 | tee "${BUILD_HOME}/sentry-upload.log"
>     fi
> ```

Opps, sorry, I pasted the wrong thing... I actually want this function:

```bash
    echo " Updating Sentry release..."
    export SENTRY_ORG="${SENTRY_ORG:-hammerspoon}"
    export SENTRY_PROJECT="${SENTRY_PROJECT:-hammerspoon}"
    export SENTRY_LOG_LEVEL=error
    if [ "${DEBUG}" == "1" ]; then
        SENTRY_LOG_LEVEL=debug
    fi
    export SENTRY_AUTH_TOKEN
    "${HAMMERSPOON_HOME}/scripts/sentry-cli" releases set-commits --auto "${VERSION}" 2>&1 | tee "${BUILD_HOME}/sentry-release.log"
    "${HAMMERSPOON_HOME}/scripts/sentry-cli" releases finalize "${VERSION}" 2>&1 | tee -a "${BUILD_HOME}/sentry-release.log"
```

**Comment by latenitefilms** [comment]
For reference, this is what I'm currently doing:

https://github.com/CommandPost/CommandPost/blob/develop/scripts/build_commandpost_release.sh#L90

**Comment by cmsj** [comment]
I wonder if `op_release()` should generally be broken down a bit more, since it's just a grab-bag of "the things Chris needs to do when there is a new release" at the moment.

**Comment by latenitefilms** [comment]
Up to you, but given you'll be the only one ever doing a Hammerspoon release, I think it's fine. It's really only that sentry stuff I'd like to trigger from your main build script, so that if sentry changes anything, I can keep Hammerspoon and CommandPost easily in-sync.

**Comment by latenitefilms** [comment]
@cmsj - FYI - I'm now seeing:

```
❌ error: LuaSkin has conflicting provisioning settings. LuaSkin is automatically signed for development, but a conflicting code signing identity Developer ID Application has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'LuaSkin' from project 'LuaSkin')
```

**Comment by cmsj** [comment]
(LuaSkin build error fixed after a quick chat on IRC)

**Comment by latenitefilms** [comment]
@cmsj - As mentioned on IRC before I had to jump offline...

> This would be really CommandPost specific, but any chance you could add an argument to the build script to uploading any `dSYM` files stored within the application bundle? The reason being, I currently copy across pre-compiled extensions like `hs._asm.cfpreferences` and `hs._asm.undocumented.touchbar` into the extensions folder during the build process, so these aren't being picked up by Sentry's upload process. Thoughts?

**Comment by cmsj** [comment]
@latenitefilms I think probably the best option here would be if I refactor the dSYM upload into its own command, with a default path so you can call it twice, once with the default (xccarchive) path and then a second time with wherever your dSYMs are.

**Comment by latenitefilms** [comment]
Thinking about it further, I wonder if I should remove all the Obj-C extensions from our CommandPost repo and actually import them into Xcode in our CommandPost-App repo? That might make it easier to track down bugs/issues? The only reason I avoided doing this is the potential for complicated Xcode project merge conflicts, but as there's already some extensions in CommandPost but not Hammerspoon (ie OSC) that's probably a redundant argument now anyway. Will have a play today.

**Comment by latenitefilms** [comment]
Whilst you're online @asmagill - do you have any thoughts/opinions on me bringing across your extensions (i.e. touchbar, touchdevice, cfpreferences, text) directly into our CommandPost-App repo? I started doing it today just to see if it'll work - but it requires a LOT of tweaks/changes/renaming because of the new way Hammerspoon extensions are structured. Thoughts?

**Comment by latenitefilms** [comment]
Currently I'm using:

- `hs._asm.cfpreferences`
- `hs._asm.undocumented.touchbar`
- `hs._asm.undocumented.touchdevice`
- `hs._asm.xml`
- `hs.text`

What are you thoughts on merging `hs._asm.xml` and `hs.text` in the Hammerspoon master? These both seem like they'd be pretty helpful for the masses. I can help with adding the missing documentation, etc?

`hs._asm.cfpreferences` would also be handy to have in Hammerspoon, but we still need to work out how all that preferences stuff is organised between all the different modules.

`hs._asm.undocumented.touchbar` and `hs._asm.undocumented.touchdevice` I'm assuming will never make it to Hammerspoon, so I'm wondering if you'd be up for renaming them to `hs.touchbar` and `hs.touchdevice`? We could then re-organise things and rename things to match the new Hammerspoon structure, and I can help fix up all the documentation so that it builds without error?

I started doing this in this branch:

https://github.com/CommandPost/CommandPost-App/commit/53757b7f8a3b3be174d01a9f25d6e254eb6e552d

...but run into some issues getting everything to build, then the Xcode project got corrupt somehow, so I need to re-add all these extension to our CommandPost-App Xcode project to see if I can actually get it to build.

**Comment by asmagill** [comment]
@cmsj so if I'm understanding the new organization correctly, for a given module:

1. all compiled code for the module and it's submodules are compiled into a single dynamic library named `lib<MODULENAME>.dylib`
2. all non-compiled files are either combined into a single `lua` file named `<MODULENAME>.lua`, or a subdirectory like before if there are multiple file types (e.g. `hsdocs`).
3. the `dylib` files end up in `Hammerspoon.app/Contents/Frameworks/hs`
4. all other files end up in `Hammerspoon.app/Contents/Resources/extensions/hs`.

We should probably add `hs.configdir .. "/?.dylib"` to `package.cpath` to allow third party external modules to more closely match this pattern to simplify eventual inclusion.

**Comment by latenitefilms** [comment]
That sounds right to me.

Also note: https://github.com/Hammerspoon/hammerspoon/blob/master/Hammerspoon/setup.lua#L9

**Comment by asmagill** [comment]
Ok, so submodules aren't compiled into the same file as the module itself but as `lib<MODULENAME-SUBMODULE>.dylib` which may be a combination of the two (e.g. `libapplicationwatcher.dylib` for `hs.application.watcher`) or something simpler like just the submodule name (e.g. `libmarkdown.dylib` for `hs.doc.markdown`)

**Comment by latenitefilms** [comment]
Correct, although I'm ASSUMING that the inconsistency in the naming isn't deliberate, and just a side-effect of trying to update all the legacy extensions. Personally, I prefer the ones that are named `lib<MODULENAME>_<SUBMODULE>` in Xcode, as it seems cleaner. I had issues getting `hs.text` to work with this new format though last night.

**Comment by asmagill** [comment]
K well I want to take a crack at my axuielement updates (which IIRC was mostly to the lua, so should be easy) and spaces additions so I can formally retire `hs._asm.undocumented.spaces` first, then I'll take a closer look at `hs.text` as I want to see what it is I still need to add before adding it to core as well -- that was the original plan for it anyways.

**Comment by latenitefilms** [comment]
Amazing - thanks so much @asmagill ! Great to see you back on GitHub! Hope all is well on the other side of the world!

**Comment by cmsj** [comment]
@asmagill yeah I didn't do a great job with the consistency of sub modules. The good news is that we can fix them without anyone noticing, because they're all hidden behind package.preload in setup.lua

**Comment by latenitefilms** [comment]
> @latenitefilms I think probably the best option here would be if I refactor the dSYM upload into its own command, with a default path so you can call it twice, once with the default (xccarchive) path and then a second time with wherever your dSYMs are.

Now that I've had a proper play, I think that whilst long term, it would be great to move all the Objective-C stuff from our CommandPost repo into our CommandPost-App (Hammerspoon Fork) repo - it's probably best/safest to wait until @asmagill brings stuff into the Hammerspoon master, rather than try hack it together myself - or at least, I might try bring across some extensions that'll never make it into Hammerspoon (i.e. `hs._asm.undocumented.touchbar` and `hs._asm.undocumented.touchdevice`), but it would probably just cause merge headaches later down the line if I attempt `hs._asm.cfpreferences`, `hs._asm.xml` and `hs.text`.

Given this, it would be really handy to have the dSYM upload in its own command if that's ok?

**Comment by asmagill** [comment]
It's probably because I generally don't use Xcode directly and am mostly self taught, but I'm not sure I understand what you mean by "have the dSYM upload in its own command"... can you clarify?

**Comment by latenitefilms** [comment]
Oh, sorry, that was specifically for @cmsj - basically I need a new way to upload the dSYM from your extensions to Sentry as part of CommandPost-App’s build process.

**Comment by asmagill** [comment]
Ok, I wondered (hoped, actually) if you were talking about a way to have the dSYM data embedded in the libraries themselves instead of as separate directories... I'd prefer that if I knew how to do it because (1) I think the extra directories are ugly, and (2) making a universal one is a really ugly hack.

**Comment by asmagill** [comment]
@cmsj, is there a reason why none of the dylib's in `Hammerspoon.app/Contents/Frameworks/hs` have underscores in their names, but at least some of the source files for them do? A recommendation by Apple/clang or limitation of same?

I ask because it's making it hard for me to update my generic Makefile so that I can easily create modules which can then be slotted into Hammerspoon itself once they're ready for inclusion with minimal changes when adding them to the Xcode workspace.  It would be easier on my end if source file names and the dylib file names matched (with the exception of the file extension, of course).

Objections if I go ahead and do this (not necessarily all at once, but at this time specifically for `libspaces_watcher` since I'm trying to get my proposed changes to the `hs.spaces` module into a pull request for review)?

**Comment by asmagill** [comment]
Ok, this is a new one:

~~~
Checking Cocoapods state...
ERROR: cocoapods installation does not seem sane
~~~

I haven't touched the pods in any way shape or form... suggestions?

**Comment by latenitefilms** [comment]
Do you have `cocoapods` installed?

Maybe try `./build.sh installdeps -r`?

Here's where it's tripping up for reference:

```python
function assert_cocoapods_state() {
  echo "Checking Cocoapods state..."
  pushd "${HAMMERSPOON_HOME}" >/dev/null || fail "Unable to enter ${HAMMERSPOON_HOME}"
  if ! pod outdated >/dev/null 2>&1 ; then
    fail "cocoapods installation does not seem sane"
  fi
  popd >/dev/null || fail "Unknown"
}
```

**Comment by asmagill** [comment]
It had worked before and is working now... I'm guessing some sort of transient network error since `pod outdated` actually checks with github. I just freaked a little since I *have* been working in Xcode to prepare for a new pull and was *mostly* certain I hadn't done anything wrong...

**Comment by asmagill** [comment]
@latenitefilms I'm hoping to work on xml and text this weekend. Re the xml module, I've not tested it much myself -- the few xml files I've needed to work with were actually more easily handled with a simplified parser I was able to write in pure lua. Are the files you're working with somewhere that I can use them in my tests? It would be nice to have something more challenging than a Roku's web interface to parse and see where the benefits of using the macOS XML classes can pay off.

**Comment by latenitefilms** [comment]
Here's a bunch of random FCPXML's you can play with:

https://latenitefilms.digitalpigeon.com/msg/yK3CQKaDEeyh9QZr2s64yQ/8ZQu8wkG-H3x_lMnr3T7LQ

If you want to see how we're currently using the XML module if you download this repo and search for `hs._asm.xml` you should find a bunch of use-cases:

https://github.com/CommandPost/CommandPost

**Comment by latenitefilms** [comment]
@cmsj - Any ideas why I'm now seeing these errors?

AFAIK nothing has changed recently in `luaskin.m` so either Xcode 13.3 has gotten more strict, or something has changed in the warning flags somehow?

<img width="2191" alt="image" src="https://user-images.githubusercontent.com/22286696/158961086-f0b8cbbc-9531-4bb2-8c29-fa18db08e7e4.png">

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/22286696/158961150-52b5908f-8a45-4b50-ab18-f786fef3d7d6.png">

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/22286696/158961185-6e63f80d-7df6-4754-9279-15b015e8786c.png">

**Comment by latenitefilms** [comment]
Ok, I tried to just ignore those two lines using:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/22286696/158964810-c770a560-7c3c-440a-a560-3f43d6558bc8.png">

...but now I'm getting:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/22286696/158964871-41a60268-e6b7-471a-b811-1a5700df62b1.png">

...if I ignore that too it builds:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/22286696/158965135-dc8cad1c-2f8b-4d37-9304-e7307e9b3b9a.png">

**Comment by latenitefilms** [comment]
Also, whilst I've got you @cmsj - this is my current (temporary) workaround for the other files for Sentry:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/22286696/158974584-e32cef20-9d11-4615-8d01-ed7d5e180e5d.png">

There could probably just be an extra variable to load one more extra path for files for Sentry to upload, which enables this line - keep things simple?

**Comment by cmsj** [comment]
new build errors are handled by #3159

**Comment by latenitefilms** [comment]
I'm going to close this issue for now. My Sentry workaround above is good enough for now.

Thanks team!!
