### ISSUE TITLE
New to Hammerspoon, need help in some simple Hotkey remapping

### ISSUE THREAD

**Issue by Sam-dev93** [Hammerspoon/hammerspoon#3097]
I am new to Mac, been using AHK on Windows for simple tasks

My task requires me to copy and paste continuously, which makes it tiring keeping fingers on 2 keys, then switching
Therefore, using AHK I found a simple code the remaps Control+C to F1 and Control+V to F2 (Windows)

I was wondering if there is a similar way using Hammerspoon on Mac
Command+C to F1        [Copy]
Command+V to F2        [Paste]

Hope that made sense, I'm guessing is simple, but I have been searching for hours online for an answer

Thanks for your time!

**Comment by Sam-dev93** [comment]
I have found a similar code online and adjusted it to F1 and F2

hs.hotkey.bind({}, "f1", function()
    hs.eventtap.keyStroke({"cmd"}, "c")
end)
hs.hotkey.bind({}, "f2", function()
    hs.eventtap.keyStroke({"cmd"}, "v")
end)

<img width="481" alt="image" src="https://user-images.githubusercontent.com/90390752/151456569-cbb6b852-04d2-4cf5-bfd8-6dbb52e566e8.png">


Doesn't seem to work
If anyone has a solution please help me

Thanks

**Comment by latenitefilms** [comment]
Unfortunately `hs.hotkey.bind` requires a modifier key to work. One way to do it would be to use an `hs.eventtap`. I'm away from a computer but I can try post an example later if needed.

**Comment by Sam-dev93** [comment]
Thanks please do

**Comment by Sam-dev93** [comment]
No has any solutions to this? 😔

**Comment by toy** [comment]
@Sam-dev93 Just tried and your example works for me, may it be that you have os setting for F1-F12 to work as media keys by default and you forgot to hold `fn` modifier? You can easily see when hotkey is triggered by using additional argument of `bind`, it will show a hammerspoon alert when F1 or F2 is pressed:
```lua
hs.hotkey.bind({}, "f1", "f1 hotkey", function() hs.eventtap.keyStroke({"cmd"}, "c") end)
hs.hotkey.bind({}, "f2", "f2 hotkey", function() hs.eventtap.keyStroke({"cmd"}, "v") end)
```

Not sure about answer from @latenitefilms, as I can bind both function keys and normal keys without modifiers (following will prevent you from typing a, remove it and reload hammerspoon config after testing):
```lua
hs.hotkey.bind({}, "a", "caught a", function() end)
```

**Comment by Sam-dev93** [comment]
Thank you @toy you're a life saver

**Comment by Sam-dev93** [comment]
Issue solved! Thanks
