### ISSUE TITLE
possible crash in pathwatcher...

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#310]
I'm seeing an occasional crash during the callback for hs.pathwatcher... I have confirmed that it is running in the main thread, and I *think* it may be because I'm calling the lua garbage collector from within the callback and something, perhaps weakly bound, is disappearing... at least all of the crash logs indicate that the crash occurs with luaB_collectgarbage a step or so back in the trace. 

At any rate, I've removed the garbage collection and it seems more stable, but I also think I recall some emails a while back about making some changes to one or another of the watchers to make them more resilient... was pathwatcher included in that?  Or is my memory playing tricks?  If such a change in code was done, which watcher(s) was it done to?  I'd like to see what changes were made and see if pathwatcher could benefit from the same.

**Comment by cmsj** [comment]
AFAIR the main thing was that I went through and every time we luaL_unref() something, I'd set the variable to LUA_NOREF, so we could detect if a C callback was happening after Lua had GC'd the user's function.

**Comment by cmsj** [comment]
If you can reproduce the crash with the release binary, we'll get a nice crash dump in Crashlytics :)

If not, could you post a trace back from Xcode?

**Comment by asmagill** [comment]
Ok, running a stock version of HS now, and I've re-added the collectgarbage() lines I removed from filelistmenu, so you should get data when/if it happens again.  I'll try and post here when it happens so you have an approximate time to look for.

**Comment by asmagill** [comment]
Hmm... I was thinking it also involved the lazy extension loading, but formally requiring everything (which I should be doing anyways...) didn't change things.  At any rate, you should have some examples in Crashlytics now... there are probably a couple of other entries regarding a menu walker I am revisiting... since it's an completely external module, I suspect it should be obvious in your data which were created by such, but if not, let me know and I'll redo this again... I'm just tired of crashes I don't expect and switched back to the more stable version of the filelistmenu for now :-)

**Comment by cmsj** [comment]
@asmagill yeah there was a little flurry of crash reports just now. They all look pretty weird - would you like an invite to Fabric/Crashlytics to inspect them? If not I think I can paste public URLs for them, so we can figure out what's going on :)

**Comment by asmagill** [comment]
Whichever is easiest... I'm not familiar with Crashlytics, so... is their a reference or is it pretty straightforward?

**Comment by cmsj** [comment]
@asmagill their help is generally poor IME, but I can walk you through it. Generally you go to the site and it shows you a list of crashes, which you can filter by app version, then for each one you get to see the symbolicated traceback. There's then also a More Details link which shows the contents of the Crashlytics logs, but that's unlikely to be tremendously useful here, I suspect.

**Comment by asmagill** [comment]
Interestingly, I have about 8 crashes recorded for the time period, but Fabric only records 4 that I can definitely identify as mine.  2 are in #122 and are within the callback... I can't tell if it's before or after the garbage collection occurs, but it is within memory reallocation routines that the crash is occurring... this is  consistent with what I was seeing earlier.

#121 and #123 appear to be occurring when I clicked on the drop-down menu item and if I'm reading the log right, the crash is occurring within hs.menubar.internal in parse_table after it's decided it needs to rebuild the menu... this would be consistent with expected behavior after the callback determined an update was required and cleared out the old menu definition data, though I'm not sure what a lua garbage collection run would affect that would lie dormant until reaching parse_table.

My whole reason for including manual garbage collection was because I know the lua structures can be large when rendering a menu that is based upon a list of files in development and application directories... figure an ounce of prevention and all that and that I'd give lua a hand rather than wait for the internal trigger for garbage collection to occur.  But apparently something else is being affected by the forced gc... I've since removed the forced collection from the published module, but it makes me wonder if we'll get spurious crashes when lua decides it needs to do collection on it's own.

**Comment by asmagill** [comment]
guess it's time to see about attaching Xcode to hammerspoon while it's running and see what that tells me when it crashes... haven't done that before, but it's as good a time as any to learn how!

**Comment by cmsj** [comment]
@asmagill what's curious to me is that the parse_table crashes both happen quite deep inside the OS frameworks that parse_table is calling out to. It might be interesting to throw some temporary NSLog()s in parse_table to see what is actually getting put into the menu items. Perhaps it's some unusual characters in filenames, which are causing weird errors inside the OS?

**Comment by asmagill** [comment]
Here's the really odd thing... having put some NSLog's into parse_table like you suggest... I no longer get crashes in parse_table... however I have noticed that the crashes seem to happen a lot more often when I'm pushing physical memory to the limit (upgrading to my latest machine was a blessing and a curse... faster, multi-core, ssd, battery that works... and half the ram.)  Oddly enough, it doesn't matter if I'm pushing memory when I don't do manual garbage collection... only when I do.  And it doesn't matter if I call collectgarbage() once or twice as some sources suggest, since lua uses a two pass system on finalizers... if I call it at all, it crashes. Sometimes.

I'm going to dig deeper into lua's gc code and run with Xcode attached (I hate to do so because of the memory footprint but I'm running out of options)... maybe I'm throwing off some mechanism that determines when to swap or compress memory or a malloc somewhere is returning 0 but not being caught or something...  All I know for certain right now is that calling collectgarbage throws something off.

**Comment by asmagill** [comment]
Simple answer -- don't force a garbage collection cycle within any function which *might* be invoked while already in a garbage collection cycle.  Will see if there is some way to detect this or prevent it from crashing, but this particular issue will be considered closed until someone sees a need/reason to reopen it.
