### ISSUE TITLE
Key events for arrow keys have `fn` modifier detected while it is not pressed

### ISSUE THREAD

**Issue by toy** [Hammerspoon/hammerspoon#3101]
Using following code:

```lua
spy = hs.eventtap.new({
  hs.eventtap.event.types.keyDown,
}, function(event)
  print(string.gsub(hs.inspect(event:getFlags()), "\n *", "") .. ' ' .. hs.keycodes.map[event:getKeyCode()])
end):start()
```

Gives following output when typing first `a` then `left` without modifiers and with every one separately:
```
{} a
{cmd = true} a
{alt = true} a
{ctrl = true} a
{fn = true} a
{shift = true} a
{fn = true} left
{cmd = true,fn = true} left
{alt = true,fn = true} left
{ctrl = true,fn = true} left
{fn = true,shift = true} left
```

**Comment by asmagill** [comment]
This has always been true... Apple has always considered "special" keys as "function" keys... this includes arrows, PageUp, PageDown, etc.

I used to have a list somewhere, I'll see if I can find it and post it up here, but seeing the `fn` flag is expected for most non-character keys.

**Comment by dasmurphy** [comment]
Awesome. Thanks for the perfect answer.

**Comment by toy** [comment]
Behaviour feels a bit weird, but if it is intended I just need to handle it properly 🤷 
Thank you for detailed answer!
