### ISSUE TITLE
a second hs.timer.doAfter doesn't fire

### ISSUE THREAD

**Issue by jrwren** [Hammerspoon/hammerspoon#3102]
I had code like this:

```lua
hs.timer.doAfter(5, function()
  print("done")
end
hs.timer.doAfter(90, function()
  print("second done")
end
```

 The second timer never fired, but if I did this instead:

```lua
hs.timer.doAfter(5, function()
  print("done")
hs.timer.doAfter(85, function()
  print("second done")
end
end

```

The second timer would fire and I'd see the `second done` message in the log.

Is there something which only allows one doAfter timer handle at a time?

**Comment by luckman212** [comment]
Probably garbage collection..... try assigning variables to the timers, eg:

```lua
one = hs.timer.doAfter(5, function()
  print("done")
end
two = hs.timer.doAfter(90, function()
  print("second done")
end
```
