### ISSUE TITLE
Enhancement: hs.http.put and hs.http.asyncPut

### ISSUE THREAD

**Issue by peterhajas** [Hammerspoon/hammerspoon#3107]
`hs.http` is a great module for dealing with web services, but it's missing a `PUT` variant. This is possible by ducking down to run `curl` using `hs.execute`, but it'd be nice to have proper Hammerspoon support for `PUT`.

**Comment by peterhajas** [comment]
This is possible with `hs.http.doRequest` - I wonder if this is just a wrapper around that?

**Comment by cmsj** [comment]
They are indeed just wrappers: https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/http/http.lua

so it should be pretty easy to construct equivalents for PUT.

**Comment by cmsj** [comment]
@peterhajas Do you have an easy way to test a `PUT` request? If so, if:

```lua
http.doRequest(url, "PUT", data, headers)
```

and:

```lua
http.doAsyncRequest(url, "PUT", data, headers, callbackFn)
```

work, which I imagine they would, I can add the wrappers to `hs.http` prety quickly.

**Comment by peterhajas** [comment]
Yep - `http.doRequest` works for the `PUT` endpoints I'm talking to. I haven't tried with data or headers, but I can talk to the OwnTone API this way with Hammerspoon.
