### ISSUE TITLE
anonymous object is killed after a while

### ISSUE THREAD

**Issue by FischLu** [Hammerspoon/hammerspoon#3117]
I am a noob of lua, but I observed a strange behavior of anonymous object, I have the following code in my `init.lua` file
```lua
hs.application.watcher.new(function(name, eventType)
    if eventType == hs.application.watcher.activated and name = 'Messages' then
        print('test')
    end
end):start()
``` 
every time I switch to `Messages`, the script prints `test` to the console. Then I kept trying to switch between `Messages` and other applications, after about 10 times I cannot see any new outputs in the console. I suppose the anonymous object created by the above code is killed?? If i create a named object of the above code, say
```lua
mywatcher = hs.application.watcher.new(function(name, eventType)
    if eventType == hs.application.watcher.activated and name = 'Messages' then
        print('test')
    end
end)
mywatcher:start()
``` 
The outputs never stop. For `hs.caffeinate.watcher` class I have the same experience.

So is this a bug or is it an intentional behavior? Thank you.

**Comment by MuhammedZakir** [comment]
> So is this a bug or is it an intentional behavior? Thank you.

This is not a bug. If you don't save the object in a global variable, or in a local variable that is directly or indirectly referenced by a global variable, it will be garbage collected after some time. That's why, you don't get any output after some time.

**Comment by FischLu** [comment]
> > So is this a bug or is it an intentional behavior? Thank you.
> 
> This is not a bug. If you don't save the object in a global variable, or in a local variable that is directly or indirectly referenced by a global variable, it will be garbage collected after some time. That's why, you don't get any output after some time.

OK, that makes sense, thank you!
