### ISSUE TITLE
Remove udhandler code from many/most extensions?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#312]
This issue mainly exists so I can ask @asmagill a question - specifically that a lot of our extensions are using the store_udhandler() / remove_udhandler() pattern, but I believe it may be cargo culting, as the values stored in the IndexSet are almost never actually used. Is there some deeper magic going on here?

**Comment by asmagill** [comment]
I'll take a close look tomorrow, but if I recall correctly, this is mostly a holdover from the programming style employed as far back as Hydra.  The primary concern with removing/changing it would be to make sure that all of the appropriate handlers get garbage collected correctly so finalizers can be called.

I think at one point there was a central store of all userdata types being collected in a single array in Hydra... as I recall it was to ensure everything had a unique reference in the lua stack, but LUA_NOREF probably addresses this sufficiently.

**Comment by cmsj** [comment]
@asmagil thanks. The reason I ask is two-fold. Firstly, maybe we can reduce code in the extensions, but more importantly, I'm experimenting with writing an objc wrapper around Lua. Not to abstract away the Lua API, that is still fully exposed, but to 1) make the Lua state available via a singleton (no more passing lua_State through objc callbacks), 2) abstract common, complex tasks that extensions do with Lua (checking function argument types, converting Lua<->ObjC types, registering extension libraries.

I'd be interested in your thoughts on what I have so far ( https://gitHub.com/cmsj/LuaSkin ), and any suggestions you have for other things it could do.

What it has so far is lua_State lifecycle management and library registration, and it has both docs and tests :)

**Comment by cmsj** [comment]
Closing this out for now, I don't have any intention of working on this. The code that's there may be redundant most of the time, but it's not doing any harm.

**Comment by asmagill** [comment]
FWIW, I just had a thought about where/how this might be useful...

If we wanted to ensure that the userdata registry entry returned for the "same" object was identical, this array could be used to look up existing defined registry entries for a given objc data object...

e.g. type `hs.window.focusedWindow()` into the console and then type it in again... two different registry entries are returned, even though they refer to the same object (try saving them into variables and doing something to one or the other)

I'm not aware of any module that currently does this, though.  Our current approach is maybe a little wasteful, but in most cases, only a few bytes are at play per object...

**Comment by cmsj** [comment]
So, I'm re-opening this and intend to repurpose it a little.

We're seeing reports of people getting worthless tracebacks in their console, that look to be errors where some system event is trying to call a Lua callback, but when it does its lua_rawgeti(), it's actually getting back a userdata value.

This tells me that we are doing some luaL_unref() improperly somewhere, but it also occurs to me that reducing the weird random things in LUA_REGISTRYINDEX is probably a good idea.

**Comment by cmsj** [comment]
This was closed by 38b02b4710972e0e85bdff4febcf6e7791795e44
