### ISSUE TITLE
Found two issues with the Getting Started Guide, how to create a PR?

### ISSUE THREAD

**Issue by qubist** [Hammerspoon/hammerspoon#3124]
Where is the source for the Getting Started guide at hammerspoon.org/go? I'd like to submit a PR to fix two issues I found with that site:

- Typo: `modifier` -> `modifies` in Fancy configuration reloading
- Broken link at bottom of page

**Comment by MuhammedZakir** [comment]
https://github.com/Hammerspoon/hammerspoon.github.io/blob/master/getting-started.md

**Comment by qubist** [comment]
Thanks!
