### ISSUE TITLE
mailto: links not working in hammerspoon setDefaultHandler\bind combo

### ISSUE THREAD

**Issue by eccentric-j** [Hammerspoon/hammerspoon#3126]
Working in fennel with the following:

Attempting the same thing with hs but running into the same issue:

```fennel

(tset hs.urlevent :httpCallback url-handler)
(hs.urlevent.bind "mailto" url-handler)
(hs.urlevent.setDefaultHandler "mailto")

```

## Reproduction

```lua
hs.urlevent.httpCallback = urlHandlerCb
hs.urlevent.bind("mailto", urlHandlerCb)
hs.urlevent.setDefaultHandler("mailto")
hs.urlevent.setDefaultHandler("https")
```

Attempt to open a mailto URL:

```shell
open "mailto:somebody@example.com"
```

## Expected

When visiting a mailto:someone@example.com I expect hammerspoon to let me process it and dispatch my urlHandler.

## Actual

When visiting mailto:someone@example.com I get the following error in hammerspoon:

```
2022-02-22 18:24:09: 18:24:09 ERROR:  urlevent: Hammerspoon has been passed a mailto URL, but does not know how to handle it
```

It seems tied to #1127

**Comment by eccentric-j** [comment]
Figured it may help to dig around a bit and found the following:

https://github.com/Hammerspoon/hammerspoon/blob/0a5dfb6c191c2c8f1216a64079b53eb24afe7572/extensions/urlevent/urlevent.lua#L47-L62

Looks like it handle http, https, and file URLs a bit differently then checks to see if it at least starts with hammerspoon. If it does not start with hammerspoon it throws that error message I'm getting.

Happy to make a PR but should probably discuss what the desired behavior is first.

Might try to rig up a proxy script to prepend it to mailto and set that as the default handler. Not ideal, but does unblock me.

**Comment by cmsj** [comment]
Huh, I have no idea how we missed that, but you're right. Looks like we need an `hs.urlevent.mailtoHandler` variable for users to register a callback for `mailto:` URLs if they set Hammerspoon as the default.

If you're willing to work up a PR for that, that would be awesome.

**Comment by eccentric-j** [comment]
Looked a little more closely and noticed:

```lua
urlevent.setCallback(urlEventCallback)
```

Tried calling setCallback myself, and sure enough it works so I can get myself unstuck like that.

I'll push up a PR for what you suggested though. Seems straight forward enough.
