### ISSUE TITLE
Hammerspoon not working on all apps (except Hammerspoon console)

### ISSUE THREAD

**Issue by SiddharthShyniben** [Hammerspoon/hammerspoon#3128]
Was playing with the hammerspoon getting started guide and the first few hotkeys for moving windows dont seem to work. a peek into the console shows that `hs.window.focusedWindow()` is `nil`.

Currently on macOS 10.15.7 if that helps

**Comment by cmsj** [comment]
I suspect this means you need to enable Accessibility permissions for Hammerspoon in System Preferences, in Security & Privacy.
