### ISSUE TITLE
hs.hotkey upgrade to eventtap?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#313]
There are some limitations in hs.hotkey that I've come across... maybe mentioned in here before, but for reference, the ones that specifically bug me:

* certain key combinations (Ctrl-#, Cmd-Tab, etc.) are not usable, even in limited modal usage, because the system catches them before we can act on them.
* nested modals which define the same hotkey sequence -- in my experience, the first registered is fired and the second disappears completely

In looking into this, most of the recommendations I've found online say that this is because the system is using EventTap to detect hotkeys and we're using the older RegisterEventHotKey.

For discussion, would it be worth redoing hs.hotkey to use the EventTap model?  I have no idea yet how difficult this might be or what other issues it might introduce or help with.  I think our eventtap code may already contain most of what we need... is there interest in looking into this beyond my own?

**Comment by cmsj** [comment]
I'm entirely agnostic to the idea, if it works better to use even trap and isn't tons more overhead, it would be less C code and that is good :)

**Comment by asmagill** [comment]
Ok, working on a prototype for this...  trying to mimic hs.hotkey as closely as possible to avoid complications with replacing it, but also address some of the limitations and problems within hs.hotkey at the same time...

What should happen in the following cases:

* a global hotkey is duplicated?  Currently my testing indicates that the second is ignored completely unless the initial one is first disabled, but even then -- unless the disabling occurs before the creation of the second definition, the second has to be re-enabled before it will work.  Mimic this, including the requirement to re-enable?  Or do something different, e.g. issue error or warning?
* a modal hotkey is the same as a global hotkey?  Currently my testing shows that this behaves as above -- the first defined, whichever it is, if it is enabled, prevents the second (in this example the modal) from working at all unless you do the disable/re-enable dance. Should modal override globals or issue error/warning?

Or more simply, should it be first defined takes precedence? or most recently defined?

**Comment by cmsj** [comment]
I think the first defined should win and a second define should fail with an error :)

**Comment by asmagill** [comment]
The current code I'm testing simply issues a warning if a key definition matches an *enabled* key definition, and then executes the first enabled one found in the list (list is in the order defined)... still not entirely happy with it because it means a modal can't override a previous global or previous modal (if nested) without knowing about the other to disable it first, but... I can live with it... nesting *should* be done with some trepidation and care.

I'm a little less certain about failing with an error, though, as that would break out of a script, potentially in an odd state (I'm thinking modals that draw big info displays covering things here... and yes, speaking from frustrated experience).  Are your thoughts on it strong enough that you want to convince me?

**Comment by asmagill** [comment]
Got a request... it seems that some keys automatically have the *fn* modifier pressed (Function keys, Home, arrows, etc), and since eventtap detects this modifier, I figured I'd add support for it... now I have to track a list of exceptions to automatically add this modifier... no prob, except I don't have all of the keys on my keyboard, so I'm asking if anyone does to run a test for me:

These I flat out don't have, so I can't test them... other F# keys do, so I'm assuming they do as well, but confirmation would be appreciated:

    [10]   = "§",
    [106]  = "f16",
    [64]   = "f17",
    [79]   = "f18",
    [80]   = "f19",
    [90]   = "f20",

This keycode is returned when I press NumLock on my keypad, and it does have *fn* set, so if someone who has an actual padclear key can confirm, I'd appreciate it:

    [71]   = "padclear",

The other pad keys (numbers) don't have *fn* true unless you press it yourself, but I don't have pad= on my keypad, so if someone with it could confirm that it *doesn't* have *fn* set, I'd appreciate it as well:

    [81]   = "pad=",

A simple test is to paste following in the console and try the keys out:

    a = hs.eventtap.new({hs.eventtap.event.types.keyup, hs.eventtap.event.types.keydown}, function(o) print(o:getKeyCode(), o:getType(), hs.inspect(o:getFlags())) ; return false end):start()

You can stop it by reloading or typing `a:stop()`


Thanks!

**Comment by cmsj** [comment]
I have § on my keyboard. The down/up events are:

10	10	{}
10	11	{}

**Comment by asmagill** [comment]
Thanks for the info on the separation(?) key.

Just an FYI -- I've completely replaced hs.hotkey with this new one on my installation and so far everything is working fine... it's actually entirely in lua now (well, it relies on eventtap, but hotkey itself is all lua)!  I need to compare the two versions a little closer and make sure I'm not missing any behaviors that I don't normally use, and perhaps clean up or protect some of the state-data that was in userdata blobs and the registry before, but is now in lua tables, but it's looking promising.

I'll post the code and some nested modal examples that kind of started me thinking along these lines for review and further testing in a day or so when I've had a chance to test it further.

**Comment by asmagill** [comment]
If you're adventurous, check out https://github.com/asmagill/hammerspoon_hotkey.

I still consider it very experimental and am not ready to even consider proposing it as a replacement, but it seems to work for me, does allow overriding system keys (the previous issue regarding ctrl-1, for example), uses less c-code that hs.hotkey, and more gracefully handles multiply defined hotkeys (more graceful in that the first active one is acted on, and disabling one doesn't inadvertently disable all of the duplicated keys until one is reactivated explicitly... I still go back and forth as to whether it should be first activated or most recently activated, or if a method should be added to reorder them programmatically, or if they should be rejected completely... the latter being impractical unless modal hotkeys are handled in a completely new way)

But, it is ready for others interested to take a look and/or comment on.

**Comment by asmagill** [comment]
Eventtaps which receive keyUp and keyDown events require accessibility... Not sure which other types do... mouse events and flag changes don't seem to... But even after accessibility is enabled, eventtaps of the key sort can't be created until Hammerspoon is exited and restarted... in looking around for a clean way to do this (I have a hacky way using os.execute and knowing the bundle path and using sleep), I came across a mention that if we're using the Sparkle framework, relaunch support is already provided by Sparkle... is their a document I can look at so I can take a gander at it's API, or should I just start poking around at it within Xcode?

**Comment by cmsj** [comment]
I don't think Sparkle exposes relaunching as API, but their implementation looks to be pretty trivial:

https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/Autoupdate/Autoupdate.m#L122

**Comment by asmagill** [comment]
I'm going to close this, as it's kind of at a standstill until I learn some more.

I like the idea of using eventtap, and it does give us some additional options -- use of the fn key as a modifier, the ability to override some more of the system-defined hotkeys, and access to right versus left modifiers (though at present hs.eventtap.event doesn't express this, it's available if you look at the raw data, so I may eventually add wrappers to make it easier to access).

BUT -- and it's a big but, if Hammerspoon is slowed down for any reason (slow lua code from something else, slow response due to needing to page something in/out , etc.) the eventtap gets disabled and regular keystrokes in every app get dropped for a second or two until HS can respond to the eventtapDisabledByTimeout event.  It's annoying :-)

I do think this is memory pressure related -- I'm on a 4GB laptop most of the time, and it seems to happen less often when I have access to a desktop with 16GB -- but until I can figure out why the existing RegisterEventHotKey doesn't suffer from this same fate and implement something closer to it, this is not a viable replacement.
