### ISSUE TITLE
hs.camera:isInUse() crashes Hammerspoon 0.9.94

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#3132]
With the latest Hammerspoon (0.9.94), the following code causes Hammerspoon to reliably crash for me. This is on an Intel Mac running 12.2.1 with both an internal laptop camera and a USB camera.

```
c = hs.camera.allCameras()
c[1]:isInUse()
```

Ref #3046

**Comment by cmsj** [comment]
Huh, wow. So it crashes if Hammerspoon is built in Release mode, but not in Debug mode, so I didn't see this while working on the feature in Xcode.

Thanks very much for reporting this - I'll see if I can figure out why it's only crashing in Release mode.

**Comment by von** [comment]
@cmsj  Just confirming the build works as I expect, both in terms of not crashing Hammerspoon and that isInUse() returns values that are correct. Thank you.
