### ISSUE TITLE
Problem building docs

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#3145]
When running `scripts/build.sh docs` I get the following error:

~~~
Building docs HTML...
Traceback (most recent call last):
  File "/opt/amagill/src/hammerspoon/hammerspoon/scripts/docs/bin/build_docs.py", line 791, in <module>
    main()
  File "/opt/amagill/src/hammerspoon/hammerspoon/scripts/docs/bin/build_docs.py", line 781, in main
    write_html(arguments.output_dir + "/html/",
  File "/opt/amagill/src/hammerspoon/hammerspoon/scripts/docs/bin/build_docs.py", line 686, in write_html
    write_templated_output(output_dir, template_dir, title, source_url_base, data, "html")
  File "/opt/amagill/src/hammerspoon/hammerspoon/scripts/docs/bin/build_docs.py", line 651, in write_templated_output
    data = process_markdown(data)
  File "/opt/amagill/src/hammerspoon/hammerspoon/scripts/docs/bin/build_docs.py", line 444, in process_markdown
    class HighlightRenderer(mistune.HTMLRenderer):
AttributeError: module 'mistune' has no attribute 'HTMLRenderer'
~~~

Is there a module missing from `requirements.txt` or a specific version of mistune I should be using?

**Comment by latenitefilms** [comment]
Maybe try `./scripts/builds.sh installdeps`?

**Comment by asmagill** [comment]
Already did that...

**Comment by latenitefilms** [comment]
I'm using:

```
> python3 -m pip show mistune
Name: mistune
Version: 2.0.1
Summary: A sane Markdown parser with useful plugins and renderers
Home-page: https://github.com/lepture/mistune
Author: Hsiaoming Yang
Author-email: me@lepture.com
License: BSD 3-Clause License
Location: /Users/chrishocking/Library/Python/3.8/lib/python/site-packages
Requires: 
Required-by: 
```

**Comment by cmsj** [comment]
I ran into this a few months ago - I believe this is a side-effect of us not specifying version numbers in `requirements.txt` - you have mistune installed, but probably an old enough version that its API has changed. It took me a very long time to track that one down.

FWIW, here are the versions I have installed:

```
❯ /usr/bin/pip3 list
Package    Version
---------- -------
Jinja2     3.0.3
MarkupSafe 2.0.1
mistune    2.0.0
pip        20.2.3
Pygments   2.11.2
setuptools 49.2.1
six        1.15.0
ttp        0.6.0
wheel      0.33.1
```

**Comment by asmagill** [comment]
Yeah, that was it... I would recommend adding version numbers to the requirements file.

**Comment by cmsj** [comment]
Already done 😁
Thanks for reminding me of this, I should have added them when I ran into this.

btw I hope you don't hate the new build system, xcconfig use, etc. - the idea was to allow CommandPost to be closer to our repo, and to get all our build config stuff unified across the extensions in xcconfigs (which isn't complete yet, there are still a few snowflakes that still have their config in the xcodeproj)

**Comment by asmagill** [comment]
I get it, no problem... it was just different and broke my build script... however, once I understood what was going on, it actually simplified my build script!

IMHO, the section at https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md#how-is-everything-built on building is a little vague on specifics in a couple of places, but honestly I think a Wiki article would be a better place to go into detail, and I have a few of those to polish up and publish as well, so I hope to address that soon... may wait a bit on the build one to see what other tweaks you and @latenitefilms need to work out, but I'm good for now -- got the newest development build on my M1 and Intel 12.x machines, and on my Catalina 10.15.7 machine (though I haven't tried building it there yet) today, so I can start working on Hammerspoon again!

**Comment by asmagill** [comment]
Sorry to necropost, but don't think this necessarily requires a new issue, unless we want to open one regarding doc building nits...

At any rate, @cmsj, my current nit is about blank lines within the Notes section -- I've noticed that an error is now thrown during documentation generation if their is a blank line in the `Parameters:` or `Returns:` section (i.e. a line that is just `///` or `---`), but for `Notes:`, the parser just stops collecting note data so that anything after the blank line is simply ignored.

Personally I liked the blank lines because it allowed a type of grouping within descriptions, but if the consensus is to do away with them, then the behavior should be consistent -- it should also throw an error in the `Notes:` section rather than silently ignore the data that follows.

**Comment by cmsj** [comment]
@asmagill hmm, I don't think errors are actually thrown for blank lines in Parameters/Returns sections. They should be, but right now the parser is not aware enough of what it's doing, to detect that, it just discards anything after a blank line in any section.

**Comment by cmsj** [comment]
https://github.com/Hammerspoon/hammerspoon/pull/3157 adds linting for blank lines within Parameters/Returns/Notes/Examples sections. It seems to find 146 of them

**Comment by asmagill** [comment]
Hmm, maybe there was another error in the docs strings as well and I corrected them both at the same time... in any case, yeah, we should either allow these blank lines, or error on them, but *not* silently stop accepting input without any kind of warning... you'd never know unless you reviewed the resulting documentation line by line and lets be honest, I at least usually only give it a cursory once over to make sure that it's at least generated -- I seldom look at it closely unless I'm looking for something specific to see how it rendered.

I'll take a look at your pull later tonight.  Thanks!

**Comment by cmsj** [comment]
Agreed that we should definitely not just silently drop the docstrings.

I'm in two minds about whether it should be a lint error or not - I would ideally like to say that each section could be freeform Markdown and we can have whatever we want in them, but I'm also trying to slowly move the entire set of docstrings into a more uniform format so we can do nicer things with the HTML docs.

I'm pretty certain that the blank line lint errors make no sense in `Examples` sections, and I'm willing to be persuaded that they also don't make sense in `Notes`, but I do think they should be errors in the stringtly list oriented `Parameters` and `Returns`. How does that sound to you?

**Comment by asmagill** [comment]
I have used blank lines in the Notes section in the past, and I think it *can* help group related things together, so if you're asking, my vote would be to allow blank lines in the `Notes` and `Examples` sections. I'm fine with preventing them in other sections.

**Comment by asmagill** [comment]
Oh and it goes without saying that in the areas where blank lines *aren't* allowed, they should throw an error if they're not signifying a new section.

**Comment by cmsj** [comment]
PR updated to ignore `Notes`/`Examples`. Looks like there are 15 instances of Parameters/Returns having blank lines in them. I'll get those squared away and then merge the PR.
