### ISSUE TITLE
0.9.95 (6211) Breaks Character Input Atomicity

### ISSUE THREAD

**Issue by mechaHarry** [Hammerspoon/hammerspoon#3146]
I have a config to type out a specific sequence of characters on hotkey.
Before the update, I can get a proper typeout of example "abcd1234".
After the update, I get improper typeouts of examples "acbd1432" or "ad134".

**Comment by mechaHarry** [comment]
Isolated it to a specific application after further testing.
Will reopen if I can find a more consistent behavior/pattern for this issue.

**Comment by MuhammedZakir** [comment]
Possibly related (behavior): https://github.com/Hammerspoon/hammerspoon/issues/2708
