### ISSUE TITLE
Unable to update to v0.9.95 from v0.9.91

### ISSUE THREAD

**Issue by alvarnell** [Hammerspoon/hammerspoon#3147]
When I select "Check for updates..." from the menu icon I'm told: 
<img width="532" alt="Screen Shot 2022-03-09 at 9 44 22 PM" src="https://user-images.githubusercontent.com/4943704/157597369-d069da64-e21b-407a-8b73-b63e35348010.png">

macOS 10.14.6 Mojave

**Comment by latenitefilms** [comment]
Unfortunately Mojave support has been dropped.

See: https://github.com/Hammerspoon/hammerspoon/issues/3060

**Comment by dasmurphy** [comment]
Here is a compiled version for Mojave which is newer than the 0.9.91 and older than the current.

[#3023](https://github.com/Hammerspoon/hammerspoon/issues/3023#issuecomment-992980087) - v0.9.93

Use at your own risk 😁 Me too.

**Comment by cmsj** [comment]
Thanks for replying @latenitefilms and @dasmurphy
