### ISSUE TITLE
internal modules should not assume auto-load is enabled

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#315]
Going to be testing a hs.hotkey replacement soon so I want to make absolutely sure that my module is the one loaded... so, I disabled the auto-load of extensions...

This breaks at least internal module hs.application which references hs.uielement.

Since we allow the disabling of the autoloader, no internal module should assume its state... things should be explicitly required for core so that no assumptions are made.

**Comment by cmsj** [comment]
A good point, I've definitely made this mistake.

@Habbie I wonder if we can integrate this into the tests somehow?

**Comment by cmsj** [comment]
(the reason I ask about testing is that this could be quite tricky to completely track down all the instances of - both in the existing code we have, and in new code we add later)

**Comment by cmsj** [comment]
I went through all of extensions/*/init.lua and fixed the autoloader abuses I found, except for uielement/application/window, which need some more careful thought as to how to fix properly

**Comment by asmagill** [comment]
It may be the order in which I'm using them, and I haven't really stress tested it yet, but...

I just added require to the `local uielement =` lines in the window and application init.lua files and it seems to be working for me... what specific issues did you encounter?

**Comment by asmagill** [comment]
If you're concerned that hs.uielement is available specifically at that path when looked for within the C code, and not just loaded, you can do what I've done in eventtap before requiring the C module which needs it :

     if not hs.keycodes then hs.keycodes = require("hs.keycodes") end

The mere testing of this will cause an auto-load of hs.keycodes, if autoloading is enabled, but if it's not enabled, we set the module explicitly where we need it.  Another option would be to load it locally within the init.lua file and then reference it from package.path... I think the following should work, but I haven't tested it yet...

     lua_getglobal(L, "package");
     lua_getfield(L, -1, "path");
     lua_getfield(L, -1, "hs.uielement");
     ...whatever else you're doing...

If one of these doesn't help, I'll need more specifics on what problem you're encountering, because as my last comment indicates... it is working for me.

**Comment by asmagill** [comment]
(corrected package.loaded instead of package.path.)

**Comment by asmagill** [comment]
@cmsj - do you still see an issue with uielement, window, etc.?  What do I need to do to recreate your problem so a specific fix can be added, and this issue can be closed?

**Comment by cmsj** [comment]
@asmagill AFAIR I wasn't hitting any specific issues, I was just concerned about their interdependencies, so I skipped them.

**Comment by cmsj** [comment]
I'm not actually aware of anyone who isn't using the autoloader, but whatever, it's a fairly self contained feature.

I've just pushed a patch to .travis.yml to disable the autoloader, which will probably explode gloriously, but once I've settled down all the loading of modules in the test scripts, this might be a nice way to get some idea of problems relating to this issue, and we can finally close it :)

**Comment by cmsj** [comment]
I'm going to close this out now, we know the problematic modules which will need to be rewritten at some point, and we've not ever run into an issue with autoloading being disabled (because nobody does it ;)
