### ISSUE TITLE
How to get the MacOS version?

### ISSUE THREAD

**Issue by dasmurphy** [Hammerspoon/hammerspoon#3161]
Is there any internal function or variable to get the MacOS version?

I myself use currently `sw_vers` with `hs.execute`. I want to check for Monterey or any other version (10.x, 11.x, 12.x) for changing to the correct UI.
Any other solutions?

Thanks for a small answer.

**Comment by asmagill** [comment]
See http://www.hammerspoon.org/docs/hs.host.html#operatingSystemVersion and http://www.hammerspoon.org/docs/hs.host.html#operatingSystemVersionString

**Comment by dasmurphy** [comment]
@asmagill perfect. Thanks for the quick answer. That helps much. I did not looked under `hs.host`. i tried to finde something like `hs.os` or other name that sounds like that.
