### ISSUE TITLE
0.9.96 breaks hs.menubar icon alignment

### ISSUE THREAD

**Issue by luckman212** [Hammerspoon/hammerspoon#3171]
### repro:

```lua
foo = hs.menubar.new()
foo:setIcon(hs.image.imageFromName('NSTouchBarCommunicationAudioTemplate'))
foo:setTitle('fooBar')
```

### result

note the overlap, icon should be positioned to the left of the title

![image](https://user-images.githubusercontent.com/1992842/160682027-9d9aa017-aa7a-4e12-b371-c6a9e24be4f2.png)

**Comment by cmsj** [comment]
Thanks @luckman212. I've prepared a PR which I will merge shortly, that fixes this, and as a bonus, also exposes a new `hs.menubar:imagePosition()` which can be used to show the image before/after the text (or overlap for some reason)

**Comment by cmsj** [comment]
A signed dev build with the fix, will appear here soon: https://github.com/Hammerspoon/hammerspoon/actions/runs/2061369499

**Comment by luckman212** [comment]
I grabbed the test build - works great! thanks @cmsj
