### ISSUE TITLE
Watch login/wake to trigger scripts

### ISSUE THREAD

**Issue by hjklapp** [Hammerspoon/hammerspoon#3182]
Feature request:
I would like to trigger a script every time I login/wake my computer.

As far as I could tell, this is currently not possible. (Or is there a way?)

**Comment by latenitefilms** [comment]
See:

http://www.hammerspoon.org/docs/hs.caffeinate.watcher.html

**Comment by hjklapp** [comment]
Ah, thank you! And sorry for not finding it myself.
