### ISSUE TITLE
hs.application.defaultAppForUTI() uses deprecated method

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3197]
Xcode reports:

> 'LSCopyDefaultHandlerForURLScheme' is deprecated: first deprecated in macOS 10.15 - Use -[NSWorkspace URLForApplicationToOpenURL:] instead.

https://github.com/Hammerspoon/hammerspoon/blob/0399ebcadd30bc7ede4089e227be33ecaadce9c7/extensions/application/libapplication.m#L233

**Comment by cmsj** [comment]
Yeah, this is really bad, their suggested replacement method doesn't seem to do what we want, so I think we need to stick with the deprecated call for now and hope they don't remove it!
