### ISSUE TITLE
camelStyle for event types in hs.eventtap?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#320]
It's driving me nuts.  And it's primarily my fault since I'm the one that ported this module from Hydra into Mjolnir (and then into Hammerspoon?)...

If I were to change the list of event types and properties in hs.eventtap to match the camelStyle of our functions/methods and of the internal constants they refer to, how much would break?  Should both be accepted?  Should  I see if I can find a way that both can be accepted for a time, but the old style will trigger a deprecation warning to the console?

Outside of core, do we have any feel for how much these are used?

At any rate I feel better now... let me know if this is worth doing or if I just need to get over it!

**Comment by asmagill** [comment]
See pull-request #318, unless anyone objects.

**Comment by cmsj** [comment]
Sorry, meant to reply to this earlier. Strong +2 for camelCase!

**Comment by cmsj** [comment]
#318 merged, closing.
