### ISSUE TITLE
hs.socket has lots of weird formatting issues

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3201]
For example:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/22286696/166091704-56090f30-9d2f-4f50-992e-f3f29fcb3c18.png">

**Comment by latenitefilms** [comment]
Also this is really confusing:

```
hs.socket:connect({host, port}|path[, fn]) -> self or nil
```

...because it looks like a table.

**Comment by latenitefilms** [comment]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/22286696/166092728-5cbfd9be-1629-429d-bdc6-573f44c5e3e8.png">

**Comment by jparoz** [comment]
For what it's worth, it seems like [the Hammerspoon docgen script](https://github.com/Hammerspoon/hammerspoon/blob/master/scripts/docs/bin/build_docs.py) doesn't process the Description field as Markdown. This seems like a bug to me, especially as it contains [specific logic](https://github.com/Hammerspoon/hammerspoon/blob/master/scripts/docs/bin/build_docs.py#L343) to detect Markdown syntax in the Description field. Should we create another issue for this?
