### ISSUE TITLE
View `hs.execute` output in real time

### ISSUE THREAD

**Issue by andmis** [Hammerspoon/hammerspoon#3203]
It would be great if the output of `hs.execute` when run interactively from the HS console were visible in real time, instead of just all at once at the end.

**Comment by cmsj** [comment]
`hs.execute()` is really just a thin wrapper around Lua's `io.popen()` - if you want to have more control over the execution of a subtask, we have the `hs.task` API which can have a callback that gets called when output is generated, rather than collecting it all at the end.
