### ISSUE TITLE
<Home> and <End> keys don't work in console input field

### ISSUE THREAD

**Issue by andmis** [Hammerspoon/hammerspoon#3205]
In the text input field here:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/5308024/166161018-4cd8ca50-0bd7-4102-9f09-c2fda7517c15.png">

The `<Home>` and `<End>` keys don't work to go to the beginning/end of the command line.

**Comment by cmsj** [comment]
I'm pretty sure Home and End aren't supposed to control the cursor in a standard macOS text box - at least they don't in the few random things I've just tested that I have open right now - Safari URL bar, Messages text box, Spotlight search and Finder search bar.

The good news is that macOS has a very flexible input remapping system built into it, which lets you customise things like this system-wide: http://www.hcs.harvard.edu/~jrus/site/cocoa-text.html
