### ISSUE TITLE
hs.application.open appears to fail on repeated calls?

### ISSUE THREAD

**Issue by turing** [Hammerspoon/hammerspoon#3209]
```
hs.eventtap.new({hs.eventtap.event.types.rightMouseDown}, function(event)
	if hs.eventtap.checkKeyboardModifiers().cmd then
		if hs.application.frontmostApplication().title ~= "Mission Control" then
			hs.application.open("Mission Control")
		end
	end
end):start()
```

Any reason why this would work perfectly exactly 7 times (total of 14 right mouse + cmd presses) then abruptly stop working? When the config is reloaded, it instantly begins working again.

Goal is to reliably trigger Mission Control on <cmd><rightMouseDown>

**Comment by turing** [comment]
I'm leaving the above in case anyone else makes the same mistake, but upon further inspection, 

`hs.application.frontmostApplication()` will *never* return Mission Control. I'm so close to solving this it's tantalizing, but I can't get it to work. :)

**Comment by latenitefilms** [comment]
It could just be garbage collection? Try capturing your eventtap in a global variable - i.e.

```lua
myEventtap = hs.eventtap.new({hs.eventtap.event.types.rightMouseDown}, function(event)
	if hs.eventtap.checkKeyboardModifiers().cmd then
		if hs.application.frontmostApplication().title ~= "Mission Control" then
			hs.application.open("Mission Control")
		end
	end
end):start()
```

**Comment by turing** [comment]
@latenitefilms Ah! That was it, thank you sir!
