### ISSUE TITLE
utility functions and methods

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#321]
(Moved from below, and existing stuff that's addressed moved down to keep progress meter happy.)

Some additional functions/methods

- [x] htmlEntities - a map of common HTML entities to their UTF8 counterpart (see http://www.freeformatter.com/html-entities.html) as well as a metamethod which converts numeric entities directly (e.g. &#number;)
- [x] convertHtmlEntities - a related function which uses the above table to convert all entities in a string to their UTF8 counterparts... useful as a post-filter for data from hs.http.get and getAsync
- [x] asciiOnly -- not UTF8 aware, but insures that the string passed into it is all printable (i.e. 7-bit) ascii -- all other bytes are converted to \\### (by default excludes tab, cr, and lf, but this can be toggled)
- [x] hexDump -- shows lines of 16 (by default) hex bytes, followed by the ascii equivalent (non-printable converted to .) of the input string of bytes

The last two may not be as interesting to include in the core, but I include them here to get the thoughts of others.

The HTML entity ones, though... I'm not sure if they should go into utf8, http, or maybe into a new hs.textconv module, and maybe pull the utf8 additions from above into it as well.

Thoughts?  Interest?

Going through some of my code and trying to see what might be a useful support type function or something that I use regularly and figured i'd get some input on where to put some of these, as some might nicely augment an existing module, while others might be better placed in a general catch all...

The following come to mind right now, and I'll submit additional questions as I come across others...

- [x] a function which returns the immediate (i.e. right now) state of the keyboard modifier keys, including the fn key... I use it in menubar items so that the target function of a menu item can act differently when different keys are clicked
- [x] a function which returns the immediate (i.e. right now) state of the mouse buttons... to my knowledge it should support however many buttons the os does, but I only have a three button mouse, so that's how far I've tested it.  I use it in the menubar callback function to allow a right click to pull up a different menu (like the mods table passed in, but based on mouse button instead)
- [x] a shell execute function which returns the output of the command sent, as well as the other parameters that os.execute returns, so similar tests as to exit status, etc. can be done with minimal change (the first return value is the output, so the others are offset by 1).  It also takes an optional boolean to indicate that the shell should be considered a login shell and load the users .profile and other shell startup scripts.  Works with bash and tcsh, so I would assume sh and csh as well... I've not tested ksh.
- [x] an iterator function which returns elements in a table with hashed keys sorted by the key name instead of the undefined order of pairs()
- [x] a function which takes a unicode codepoint and returns the proper UTF-8 byte sequence for output with print() or hs.drawing.text()
- [x] a function which returns the name of all available fonts... the font names can then be used with hs.drawing.text.
- [x] a special-keys table which contains the common utf-8 versions of special keys (cmd, ctrl, apple, etc.)  A little more user-friendly than the codepoint-utf8 function mentioned above, but really a duplicate of results... perhaps a way to register/use names for codepoints would be better?
- [x] a function which returns the same data as vm_stats in a table (except for memory compression statistics... still looking for those).  I also plan on adding a function to get cpu usage information and use these and hs.drawing to replace what I use geektool for, so maybe this should wait until I add the cpu and compression stuff and call it something like hs.systemstats?

At any rate, if there are any suggestions on existing modules any of these should be added to, I'm open to ideas... I kind of think the codepoint to utf8 one belongs in utf8_53, but that is currently the lua 5.3 utf8 library only and this would be departing from that specificity...

**Comment by cmsj** [comment]
> a function which returns the immediate (i.e. right now) state of the keyboard modifier keys

+1 - I think this should probably live in hs.eventtap

> a function which returns the immediate (i.e. right now) state of the mouse buttons

+1 - ditto

> a shell execute function which returns the output of the command sent, as well as the other parameters that os.execute returns

+1 - probably this belongs in the root hs object? Either that or we retool hs.applescript to be hs.script?

> an iterator function which returns elements in a table with hashed keys sorted by the key name instead of the undefined order of pairs()

+1 - hs.fnutils I think

> a function which takes a unicode codepoint and returns the proper UTF-8 byte sequence for output with print() or hs.drawing.text()

+1 - agree that hs.utf8_53 seems right for this, but I wonder if starting hs.utf8 would make more sense, since utf8_53 should go away at some point (testing a Lua 5.3 upgrade is on my hilarious todo list)

> a function which returns the name of all available fonts... the font names can then be used with hs.drawing.text.

+1 - for now I'd suggest this belongs in hs.drawing since that's the only place we care about fonts

> a special-keys table which contains the common utf-8 versions of special keys (cmd, ctrl, apple, etc.) A little more user-friendly than the codepoint-utf8 function mentioned above, but really a duplicate of results... perhaps a way to register/use names for codepoints would be better?

+1 - I think this would also fit nicely in an hs.utf8, especially if it has a way to register friendly names for things (and comes pre-populated with the keyboard ones)

> a function which returns the same data as vm_stats in a table (except for memory compression statistics... still looking for those). I also plan on adding a function to get cpu usage information and use these and hs.drawing to replace what I use geektool for, so maybe this should wait until I add the cpu and compression stuff and call it something like hs.systemstats?

+1 - I kinda feel like hs.host would be appropriate for these things. Right now it's for networking things, but there's very few of those, and growing into a "information about the host I'm running on" seems reasonable to me.

**Comment by asmagill** [comment]
Some additional functions/methods

- [ ] htmlEntities - a map of common HTML entities to their UTF8 counterpart (see http://www.freeformatter.com/html-entities.html) as well as a metamethod which converts numeric entities directly (e.g. &#number;)
- [ ] convertHtmlEntities - a related function which uses the above table to convert all entities in a string to their UTF8 counterparts... useful as a post-filter for data from hs.http.get and getAsync
- [ ] asciiOnly -- not UTF8 aware, but insures that the string passed into it is all printable (i.e. 7-bit) ascii -- all other bytes are converted to \### (by default excludes tab, cr, and lf, but this can be toggled)
- [ ] hexDump -- shows lines of 16 (by default) hex bytes, followed by the ascii equivalent (non-printable converted to .) of the input string of bytes

The last two may not be as interesting to include in the core, but I include them here to get the thoughts of others.

The HTML entity ones, though... I'm not sure if they should go into utf8, http, or maybe into a new hs.textconv module, and maybe pull the utf8 additions from above into it as well.

Thoughts?  Interest?

**Comment by cmsj** [comment]
+1 to those 4. I think I'd go with the html entity ones in hs.http and the other two in hs.utf8

**Comment by asmagill** [comment]
closing... will reopen or add new issue if I come up with more "helpers" that I need help in deciding where they belong.
