### ISSUE TITLE
Dash Docset for Hammerspoon is still at 0.9.95

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#3212]
@cmsj, are we no longer updating the docset with Kapeli? Or is this an oversight because you're still tweaking the new build process?

**Comment by cmsj** [comment]
We're supposed to be, but the GitHub command line client is weird and I messed up the last couple of PRs

**Comment by cmsj** [comment]
It asks questions about base repos for the PR and I keep answering it incorrectly and haven't figured out how to automate that part fully yet 🤔

**Comment by cmsj** [comment]
Closing since we've been better about this lately, and the PR for 1.0.0 is awaiting Dash review: https://github.com/Kapeli/Dash-User-Contributions/pull/5085
