### ISSUE TITLE
Is there support for gestures?

### ISSUE THREAD

**Issue by mzbik** [Hammerspoon/hammerspoon#322]
I'd like to do things like trap various swipes when the cursor is over windows and controls.

**Comment by cmsj** [comment]
At the moment, unfortunately not. It ought to be possible to use BetterTouchTool to recognise the gestures and then dispatch actions to Hammerspoon (either by using a script that calls the `hs` command line (see the docs for `hs.cli`) or by having it open URLs that map to events bound with `hs.url`).

While we could, in theory, have a gesture recogniser, I rather suspect that it would be quite a complex piece of code, and we'd end up re-implementing much of BTT.

**Comment by cmsj** [comment]
sorry, I meant `hs.urlevent` there. I had a quick peek at BTT's website and it doesn't seem immediately obvious that they support opening URLs in the background (which is fairly important for neat integration), so I've asked the developer on Twitter and we'll see what he says :)

**Comment by mzbik** [comment]
Cool… I’ve asked the BTT people if they can detect gestures in certain UI parts of windows (namely scroll bars, title bars, and menus)… Let’s share notes when we get data.

**Comment by cmsj** [comment]
I'm re-opening this because it seems like there is interest in working on the feature, so we'll keep this around as a tracking bug.

**Comment by latenitefilms** [comment]
This might be relevant?

https://github.com/calftrail/Touch

Thoughts @asmagill & @cmsj ?

**Comment by latenitefilms** [comment]
Also see: https://github.com/calftrail/Sesamouse

**Comment by cmsj** [comment]
@asmagill has done some investigations into gesture recognition recently, and has a third party Hammerspoon module that can do some of it, but it seems like this uses a lot of private, undocumented APIs, so I don't think we'll be able to bring the feature into the mainline Hammerspoon release. Sorry!

**Comment by chavlji** [comment]
@cmsj could you please provide a simple example on how to call some method defined in some lua file from the terminal?

I guess I have to do something similar to this in lua script:
```
hs.cli.registerHandlerForMessage('print-test', function(payload)
	print('testing')
end)
```
And then I should call it from the terminal with something similar to:
```
hs -c "sendMessage('payload', 'print-test')"
```
Could you please provide an example please?

**Comment by mogenson** [comment]
I ran into some limitations working with hs.eventtap to recognize swipe gestures on MacOS 14.4.1 and HammerSpoon 0.9.100:
- hs.eventtap.events.type.swipe is never issued by Quartz
- touch event phase "began", "ended", and "cancelled" is never issued, only "moved" and "stationary"
- touch events with "moved" phase contain previousNormalizedPosition values of 0

I was still able to create a Spoon that recognizes multi finger swipe gestures and calls a registered callback with the swipe direction and cumulative distance from the beginning of the swipe:

https://github.com/mogenson/Swipe.spoon
