### ISSUE TITLE
UTF8 in document generation code

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#323]
I have the following in the comments of some additions to utf8_53 that I plan to issue a pull request for soon, but ran into an oddity that will affect documentation in Dash...

In the hammerspoon console I get:

     Predefined keys include:

         (U+2325) alt            ⌥
         (U+F8FF) apple          
         (U+21E4) backtab        ⇤
         (U+21EA) capslock       ⇪
         (U+2318) cmd            ⌘
     ... cut short for brevity ...

In Dash:

     Predefined keys include:

     (U+2325) alt            âŒ¥
     (U+F8FF) apple          ï£¿
     (U+21E4) backtab        â‡¤
     (U+21EA) capslock       â‡ª
     (U+2318) cmd            âŒ˜
     ... cut short for brevity ...

I'm guessing that at least one of the conversion steps that makes the documentation doesn't know about UTF-8 encoding... any thoughts on which piece we need to fix?  I'll look into this over the weekend, but Ruby is not something I'm that familiar with, so I thought I'd throw it out and see if anyone else is already familiar with UTF-8 in Ruby.

**Comment by cmsj** [comment]
So, take a look at the docs target in the toplevel makefile, it's a chain of commands that finds the code, extracts the docstrings, processes them into json and converts them to html. presumably at some point in that chain, one of the tools is mangling the output.
