### ISSUE TITLE
After updating to Mac OS 12.5 kept getting space characters

### ISSUE THREAD

**Issue by seonghuhn** [Hammerspoon/hammerspoon#3262]
Yesterday I updated to Mac OS 12.5. Later I noticed that it appeared as though my space bar key was stuck because space characters kept being outputted. I tried cleaning it with compressed air but that didn't help. Then I rebooted and it appeared to solve the problem but after about 15 minutes it came back. I tried again and the same thing happened.

I then booted into Safe Mode and noticed the problem was no longer happening. I don't have much third party software so I was wondering if the update was affecting Hammerspoon. I rebooted and quit Hammerspoon and I no longer have the repeating space character issue.

Has anyone else experienced this? Is there maybe something wrong with my config? Is this a known issue?

I hope if this is an issue it can be fixed soon because I very much enjoy Hammerspoon. 🤓

**Comment by latenitefilms** [comment]
Are you able to post your Hammerspoon configuration? It must be something in your Lua scripts that's causing it.

**Comment by seonghuhn** [comment]
Thanks for asking. For some reason this is no longer an issue. I unfairly blamed Hammerspoon. 🤓
