### ISSUE TITLE
Create a Hammerspoon Widget Extension

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3275]
See: https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension

**Comment by cmsj** [comment]
What sort of thing would you want to put in the widget?

**Comment by latenitefilms** [comment]
I haven’t looked into it too deeply yet, but I’m hoping the widget contents could be programatically generated from Lua, so that users could add their own text data, buttons, etc. Simple solution could just be to make it a webview, another option could be to make it a canvas?

**Comment by latenitefilms** [comment]
I'm not sure when I'll have time to look into this, so closing for now.
