### ISSUE TITLE
How to construct a Smart magnify `eventtap.event`

### ISSUE THREAD

**Issue by jannis-baum** [Hammerspoon/hammerspoon#3282]
I can't seem to figure out how to construct a [Smart magnify event](http://www.hammerspoon.org/docs/hs.eventtap.event.html#types) any way other than capturing a "real" one, using [hs.eventtap.event:asData()](http://www.hammerspoon.org/docs/hs.eventtap.event.html#asData) to get its data and constructing a new one from the data with [hs.eventtap.event.newEventFromData](http://www.hammerspoon.org/docs/hs.eventtap.event.html#newEventFromData).

I've tried

- creating a [newEvent](http://www.hammerspoon.org/docs/hs.eventtap.event.html#newEvent), setting its type, location (& timestamp) and [post](http://www.hammerspoon.org/docs/hs.eventtap.event.html#post)ing it, which does nothing
- creating a [newMouseEvent](http://www.hammerspoon.org/docs/hs.eventtap.event.html#newMouseEvent), which throws an error since it doesn't recognize the Smart magnify type
- creating a [newGesture](http://www.hammerspoon.org/docs/hs.eventtap.event.html#newGesture), which also doesn't recognize it

The way I have it now is keeping the base64 encoded data from a captured event hardcoded in my config, using [hs.eventtap.event.newEventFromData](http://www.hammerspoon.org/docs/hs.eventtap.event.html#newEventFromData) to construct a working event, modifying its location and then posting it. This does work but of course is far from optimal.

Is there anything I am missing or is it not supported to construct Smart magnify events?

**Comment by latenitefilms** [comment]
Ummm... I think "smart magnify" would probably need to be added to `hs.eventtap.event.newGesture`, as it currently only supports magnify.

@asmagill might have a better explanation?

For future reference, this is how I trigger new gestures:

https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/gestures/init.lua
