### ISSUE TITLE
Allow newlines in docstrings

### ISSUE THREAD

**Issue by bviefhues** [Hammerspoon/hammerspoon#3284]
Seems that various docstring elements do not support newlines, i.e. paragraphs composed of several comment lines. My OCD would be much more happy if I could do this:
```
--- <spoon variable>
--- Variable
--- Very very long text which wraps around depending on editor 
--- configuration and obviously is much longer that 80 characters, 
--- which some people prefer as their editor configuration.
```

instead of this:
```
--- <spoon variable>
--- Variable
--- Very very long text which wraps around depending on editor configuration and obviously is much longer that 80 characters, which some people prefer as their editor configuration.
```
Would be great if `build_docs.py` could accomodate that.

**Comment by cmsj** [comment]
While it would be nice, I don't think this is very likely to happen - newlines are part of the "format" of our docstrings, and the parser is complicated enough already! Sorry.
