### ISSUE TITLE
Add an optional readOnly parameter to hs.dialog.textPrompt

### ISSUE THREAD

**Issue by TheQuinbox** [Hammerspoon/hammerspoon#3289]
It would be great if we could pass an (optional) readOnly parameter to hs.dialog.textPrompt, making the text field uneditable/read only.

**Comment by latenitefilms** [comment]
Curious... what would be the point of a read only text box?

**Comment by TheQuinbox** [comment]
If you need to display a long string, especially for screen reader users, like myself. My personal use case was because I'm making a spoon that displays all the properties of an AXUIElement, and showing that in an alert box isn't good because I can't read by line/character/whatever else.

**Comment by latenitefilms** [comment]
Unfortunately it doesn't look like `NSAlert` has a read-only property. You could use a `hs.webview` instead and build your own UI?

**Comment by TheQuinbox** [comment]
Ah, yeah, looks like hs.webview will do what I want. Thanks!
