### ISSUE TITLE
os.execute command not returning expected result

### ISSUE THREAD

**Issue by olivertaylor** [Hammerspoon/hammerspoon#3291]
When I do this in the command line: ``{cal & meet} | open -tf``

I get a TextEdit window like this:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1388093/191580800-29022ac3-37b5-4fb7-b689-d28e1ffa7e48.png">

But when I try to wrap that in a Hammerspoon function, Hammerspoon does not seem to do anything.

Making the paths to the scripts absolute results in an empty TextEdit window:

```lua
function displayCalMeet()
  os.execute( "{/usr/bin/cal & /Users/oht/home/dot/bin/meet} | open -tf" )
end
```

What's going on here?

**Comment by cmsj** [comment]
I'm not sure I want to really dig in and break down the underlying unixy reasons why it's happening, but fwiw this will work:

```lua
hs.execute("echo \"$(cal;meet)\" | open -tf")
```

**Comment by olivertaylor** [comment]
I tried the following, which did not work:

```lua
function meetingTimes2()
   hs.execute("echo \"$(cal;meet)\" | open -tf")
end
```

But I take your point. I worked around it by tweaking my script and doing this:

``` lua
function meetingTimes()
   os.execute("osascript -e 'tell app \"Terminal\" to do script \"meet\"'")
   hs.application.launchOrFocus("Terminal")
end

```
