### ISSUE TITLE
hs.fs.rmdir cannot delete a directory that not empty

### ISSUE THREAD

**Issue by KURANADO2** [Hammerspoon/hammerspoon#3299]
I have a directory: 	/Users/jing/.hammerspoon/.wallpaper/2022-10-12, and there are a.jpg file in this directory.
I want to use `hs.fs.rmdir('/Users/jing/.hammerspoon/.wallpaper/2022-10-12')` to delete the directory, but return `nil Directory not empty`
I'm not sure this is a problem or not.
Is there any way to delete a non-empty directory?

**Comment by asmagill** [comment]
This result is expected -- `rmdir` will only remove empty directories (this includes the pesky dot files that are hidden (by default) in the Finder, but will show up if you look at it from the Terminal with `ls -la`.

If you want to remove the directory, even if it contains files, use `rm -r <dir>` or `rm -fr <dir>`

`-r` to `rm` tells it to recurse through the directory and delete everything it finds at that directory or deeper.

`-f` to `rm` tells it to ignore permissions or other situations that would normally prompt for a confirmation. Note that if you do not have sufficient permissions to delete a sub file or sub directory at all (e.g. owned by root and parent directory doesn't have the set-uid or set-gid (I forget which) bit set, this will still fail -- it only avoids prompts where the permissions of the file won't let you, but the directory permissions allow you to override it's files.

**Comment by KURANADO2** [comment]
Thank you for your reply, I'll try to do as you say.
