### ISSUE TITLE
Project health

### ISSUE THREAD

**Issue by zdcthomas** [Hammerspoon/hammerspoon#3307]
Hey y'all, I just started using hammerspoon and it's absolutely amazing! I wanted to ask though, it seems like it hasn't had any activity on the repo since July. Is there a call for maintainers/is there anything I could help with to get started? 

I'd really love to help this project stay alive!

**Comment by latenitefilms** [comment]
It's still very much alive!

Hammerspoon is also the "engine" for [CommandPost](https://commandpost.io) so we do a lot of stuff in there before doing a pull request in Hammerspoon.

Pull request are always welcome though!

**Comment by cmsj** [comment]
The lack of activity is mostly my fault, I've been too busy for the last 6 months to spend much time on Hammerspoon, unfortunately!

**Comment by asmagill** [comment]
I used to contribute fairly regularly while @cmsj managed the actual releases. My time has become more constrained over the last year and I don't have nearly as much free time to contribute or troubleshoot on a regular basis, though I don't intend to completely disappear!

If you or others would like to contribute, please feel free to submit pull requests or share your experiences and work-arounds when people post questions or problems that come up. There are some basic patterns and conventions we use in our code and integration with the LuaSkin framework, but as always, documenting this and providing tutorials is always easy to put off or push back. I'll see what I can maybe do over the holidays coming up to provide more documentation and suggestions with regards to the "style" of coding and programming we've adopted that has evolved over the last few years (wow, has it really been that long?).

**Comment by cmsj** [comment]
@zdcthomas if it's any reassurance, I rely on Hammerspoon dozens of times every day. I don't use every feature of it, but a substantial amount of my workflow is built around it, so at the very least I will be forced to keep the bits I care about working on as many future macOS releases as I can ;)

To answer your specific question about what help is needed - I agree with @asmagill, helping out on Issues would be really awesome, we have almost 500 open at the moment.

I'm going to close this, but feel free to ask any more questions, if you have them.

**Comment by zdcthomas** [comment]
Hey that's awesome to hear that the community around it is still alive and well!! I've really grown to like hammer spoon so I'll definitely take a crack at contributing! 

Thanks for all the answers!
