### ISSUE TITLE
CommandPost commit tagged in main Hammerspoon repo?

### ISSUE THREAD

**Issue by Rhys-T** [Hammerspoon/hammerspoon#3308]
I was looking through the history of some of Hammerspoon's code, and noticed on one commit's page that the newest tag containing the commit was supposedly [1.2.17](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.2.17). This seemed odd, given that last time I looked, Hammerspoon was still using 0.x version numbers. Looking closer, I noticed:

1. The tag was created by @latenitefilms.
2. "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
3. The XCode project file (the last thing modified in that tag) mentions a number of [CommandPost](https://github.com/CommandPost/CommandPost)-specific files (including `CommandPost.sdef` and `cp*.icns`).
4. CommandPost does have a series of 1.2.x versions, which goes up to 1.2._16_ before jumping to 1.3.0.

At first I thought a version of CommandPost had somehow gotten tagged in the wrong repository. However, the source tree for that tag mostly looks like a Hammerspoon one (e.g. it still has Hammerspoon's README.md, not the CommandPost one). Also, if it was just a misplaced tag for a real CommandPost version, I'd expect the corresponding _release_ to still exist in the CommandPost repo, but I don't see one. So now I'm not sure what's going on.

Is this tag supposed to be here? Is there any way to convince GitHub that it's not actually the newest version of Hammerspoon, despite the number?

**Comment by latenitefilms** [comment]
It looks like maybe a tag has incorrectly come across when getting hs.razer code from CommandPost-App to Hammerspoon? This is most likely totally my fault. @cmsj might know how to fix?

**Comment by cmsj** [comment]
Thanks @Rhys-T, I've removed the offending tag. I'm not really sure how it managed to migrate from CommandPost to Hammerspoon!

**Comment by Rhys-T** [comment]
@latenitefilms @cmsj I hate to bother you, but it looks like whatever caused this is still happening. Not only is 1.2.17 back in Hammerspoon's tag list, but a bunch of newer CommandPost versions seem to be over here too. As before, some of these tags are _only_ in the HS repo, and not the CP one - if these correspond to legitimate CommandPost versions and need to be kept around, make sure they get copied back before they get deleted here. (I don't know whether they're real versions or not, because as I mentioned before, '1.2.17' seems to be a weird mix of the two apps.)

Using the GitHub REST API and [`jq`][jq], I've attempted to build a list of the misplaced tags. I basically took every tag with a '1.x' name. Tags in _**bold italics**_ are currently only in the Hammerspoon repo as far as I can tell. I've come up with 63 misplaced tags, 29 of which are only in HS.

<details>
<summary>Misplaced tags</summary>

- _**[1.4.16-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.16-beta.1)**_
- [1.4.15](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.15)
- [1.4.15-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.15-beta.2)
- [1.4.15-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.15-beta.1)
- [1.4.14](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.14)
- [1.4.13](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.13)
- _**[1.4.13-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.13-beta.2)**_
- _**[1.4.13-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.13-beta.1)**_
- [1.4.12](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.12)
- [1.4.11](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.11)
- _**[1.4.11-beta.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.11-beta.3)**_
- _**[1.4.11-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.11-beta.2)**_
- _**[1.4.11-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.11-beta.1)**_
- [1.4.10](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10)
- _**[1.4.10-beta.7](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.7)**_
- _**[1.4.10-beta.6](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.6)**_
- _**[1.4.10-beta.5](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.5)**_
- _**[1.4.10-beta.4](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.4)**_
- _**[1.4.10-beta.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.3)**_
- _**[1.4.10-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.2)**_
- _**[1.4.10-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.10-beta.1)**_
- [1.4.9](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.9)
- [1.4.8](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.8)
- [1.4.7](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.7)
- [1.4.6](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.6)
- [1.4.5](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.5)
- [1.4.4](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.4)
- _**[1.4.4-beta.4](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.4-beta.4)**_
- _**[1.4.4-beta.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.4-beta.3)**_
- _**[1.4.4-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.4-beta.2)**_
- _**[1.4.4-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.4-beta.1)**_
- [1.4.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.3)
- [1.4.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.2)
- [1.4.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.1)
- [1.4.0](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.4.0)
- [1.3.14](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14)
- _**[1.3.14-beta.12](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.12)**_
- _**[1.3.14-beta.11](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.11)**_
- _**[1.3.14-beta.10](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.10)**_
- _**[1.3.14-beta.9](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.9)**_
- _**[1.3.14-beta.8](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.8)**_
- _**[1.3.14-beta.7](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.7)**_
- _**[1.3.14-beta.6](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.6)**_
- _**[1.3.14-beta.5](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.5)**_
- _**[1.3.14-beta.4](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.4)**_
- _**[1.3.14-beta.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.3)**_
- _**[1.3.14-beta.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.2)**_
- [1.3.14-beta.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.14-beta.1)
- [1.3.13](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.13)
- [1.3.12](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.12)
- [1.3.11](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.11)
- [1.3.10](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.10)
- [1.3.9](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.9)
- [1.3.8](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.8)
- [1.3.7](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.7)
- [1.3.6](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.6)
- [1.3.5](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.5)
- [1.3.4](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.4)
- [1.3.3](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.3)
- [1.3.2](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.2)
- [1.3.1](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.1)
- [1.3.0](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.3.0)
- _**[1.2.17](https://github.com/Hammerspoon/hammerspoon/releases/tag/1.2.17)**_

</details>

[jq]: https://stedolan.github.io/jq/

**Comment by latenitefilms** [comment]
Huh, that's interesting. It must be that whenever I do a pull request from CommandPost-App to Hammerspoon, it somehow brings across all of CommandPost's tags?

I wonder if @cmsj can manually remove tags when merging a pull request that originates from CommandPost-App?
