### ISSUE TITLE
Migration to Lua 5.3

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#332]
For local module building (i.e. outside of a full Hammerspoon build), I had to install lua5.3 via homebrew and modify my makefiles by changing -I/usr/local/include/lua5.2 to -I/usr/local/include/lua53...

I've seen some applications that allow building support modules that include the necessary library and include files within the application resources so that you didn't have to have them installed elsewhere as well.  Is this a possibility for Hammerspoon?  Sample build instructions would include referencing this as something like '-I/Applications/Hammerspoon.app/...../lua5.3' and since I build it elsewhere, I'd have to change this, but I think we can assume people doing interim builds know enough to check for this...

Thoughts?  What other then include files would actually be necessary?

**Comment by cmsj** [comment]
We should just need the include files. This is something I've already addressed in LuaSkin, which ships all of the Lua header files in its .framework. We probably should do the same in Hammerspoon, at least until I get LuaSkin more ready, and integrated.
