### ISSUE TITLE
Ultra-wide 4K display slowdowns

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#3320]
Does anyone experience strange issues with large screens?

Sometimes, for reasons I don't yet understand, things get slow. I thought it might be a bug in my config. It uses a kind of elaborate system of modals built on top of a finite-state-machine, but that's irrelevant.

Also, I have been dealing with weird issues when `hs.grid` won't resize windows properly. For a very long time I thought it was a difficult-to-debug bug in Hammerspoon, see related [issues](https://github.com/Hammerspoon/hammerspoon/issues?q=is%3Aissue+is%3Aopen+hs.grid) and I was hoping someone gets to fix it. Imagine my surprise that after reinstalling system anew, `hs.grid` started working properly.

And with this newly installed OS, everything at first was smooth, but then for some reason, things again have gotten slow. I couldn't figure out what the heck is causing that. I was thinking it might be due to some apps I installed. And then it hit me -  what if that has something to do with the screen resolution? I have a 5120x1440 4K monitor. I lowered the res. After restarting Hammerspoon, I was no longer experiencing slow-downs. Then I changed it back to 4K resolution again - no issues.

But I'm pretty sure, at some point, they will start haunting me again. I wonder if I can use `hs.screen` and write some kind of "reset" function to help me mitigate these issues?

Any suggestions are appreciated. Hammerspoon is one of the most important tools I use, and all these hiccups are hugely annoying.

**Comment by cmsj** [comment]
Is it that every part of Hammerspoon gets slow? hs.grid is certainly inefficient and could probably be made a lot faster.
