### ISSUE TITLE
hs.audiodevice:watcherIsRunning() returns false on a fresh userdata object even if a watcher exists on a previous userdata object

### ISSUE THREAD

**Issue by jlaffaye** [Hammerspoon/hammerspoon#3330]
```lua

local defaultInputDevice = hs.audiodevice.defaultInputDevice()
defaultInputDevice:watcherCallback(function(device_uuid, event, channel)
    log.d("got event "..event.." on device "..device_uuid)
end)
defaultInputDevice:watcherStart()

defaultInputDevice:watcherIsRunning() -- returns true

hs.audiodevice.defaultInputDevice():watcherIsRunning() -- returns false
```

This is because the "getters" like `hs.audiodevice.defaultInputDevice()` create new lua objects every time and the state `watcherIsRunning` is stored in the lua object.

**Comment by cmsj** [comment]
You're right, that is why this is happening. This is one of our oldest extensions and its design is... lacking... compared to what we might do today.

I wonder if we could hack in a cache of the userdata objects so we can return an existing one rather than creating new ones.

**Comment by cmsj** [comment]
I'm going to close this out because I think over the coming year or two we'll be trying to rework the watcher system across all extensions, at least partly to eliminate this exact design failure.
