### ISSUE TITLE
hs.hid.led.set only works once after startup

### ISSUE THREAD

**Issue by fishstik** [Hammerspoon/hammerspoon#3331]
`print(hs.hid.led.set("caps", true))`

Upon system startup, this prints `true` in the console. Subsequent calls as well as config reloads prints `false`. Upon rebooting or logging out and back in, it prints `true` once and `false` thereafter.

Related to #1802

**Comment by fishstik** [comment]
Karabiner-Elements is the culprit. `hs.hid.led.set` works after quitting Karabiner or turning off `Modify events` for the Apple Internal Keyboard in Devices tab. Does not work after turning off `Manipulate caps lock LED` in Karabiner.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/4278123/206645646-8def5755-fa75-4412-8113-7656cb1aa082.png">

**Comment by eleksir** [comment]
Caps Lock handler in MacOS kinda shitty. It delivers something strange to Hammerspoon if you push CapsLock button. Some weird pack of events and the amount of pack differs on each push of button.

And if you want to mess with Caps Lock it looks like you have to consume whole Cap Lock stuff including led, on low level. Karabiner does exactly _that_ and handles Caps Lock things _entirely by itself_.

Maybe.. maybe Karabiner _can_ expose **led** by some mean that can be interact with by Hammerspoon. But this topic is a subject of discussion between authors of both projects. And after implementing result of successfull discussion, both projects should put in their documentation a description of how to work with _hid.led_.

Do not mess with MacOS _native_ Caps Lock stuff - its weird and totally sic for years and Apple don't want to fix it.
