### ISSUE TITLE
proposal: expand hotkey prefix list to include alpha characters

### ISSUE THREAD

**Issue by jakeschurch** [Hammerspoon/hammerspoon#3333]
I started using hammerspoon due to hearing that it would be a good alternative to i3 WM on linux. 

The experience is quite compatible, but was surprised to find that the following is not allowed(!)

```lua
hs.hotkey.bind({ "cmd", "o" }, "c", function()
	return hs.application.open("Google Chrome")
end)
```

The hotkey seems to instead bind to `cmd+c`(!)

I did some quick repo-digging and seems like only a small patch is required in [getMods in ./extensions/hotkey/hotkey.lua](https://github.com/Hammerspoon/hammerspoon/blob/b03d628f792eb88188962643c32a490f1174c10d/extensions/hotkey/hotkey.lua#L127-L142).

Was wondering if you also thought this would be a nice feature to add. If so, I wouldn't mind volunteering myself :) - if not, no worries

**Comment by jakeschurch** [comment]
If getMods is fn that needs to be updated, it might also make sense to refactor `getMods.find` to allow for more expansive sequences

**Comment by Rhys-T** [comment]
Unfortunately, it looks like the underlying Carbon Events API that `hs.hotkey` is based on can only handle true modifier keys. The results of that `getMods` function end up getting converted into the appropriate bitmask here, in the native-code part of `hs.hotkey`: https://github.com/Hammerspoon/hammerspoon/blob/b03d628f792eb88188962643c32a490f1174c10d/extensions/hotkey/libhotkey.m#L176-L185

You should be able to do something similar with `hs.hotkey.modal`s, however:
```lua
cmdOModal = hs.hotkey.modal({"cmd"}, "o")
cmdOModal:bind({}, "c", function()
	cmdOModal:exit()
	return hs.application.open("Google Chrome")
end)
-- bind any other ⌘O-prefixed keys using `cmdOModal:bind(...)` here
-- make sure they start with `cmdOModal:exit()` so you don't get stuck in the modal
```

[The RecursiveBinder spoon](https://www.hammerspoon.org/Spoons/RecursiveBinder.html) also provides a fancier version of this type of setup. Simple example config: https://github.com/cpriyank/dotfiles/blob/c06ea9a3b58da71e27994bde588203e21139663c/hammerspoon/.config/hammerspoon/init.lua

**Comment by jakeschurch** [comment]
easy enough! thanks so much for your help
