### ISSUE TITLE
Control Keyboard Backlight

### ISSUE THREAD

**Issue by specter78** [Hammerspoon/hammerspoon#3334]
How to control keyboard backlight brightness using HS?

**Comment by rsefer** [comment]
```lua
-- Illumination Down
hs.eventtap.event.newSystemKeyEvent('ILLUMINATION_DOWN', true):post()
hs.eventtap.event.newSystemKeyEvent('ILLUMINATION_DOWN', false):post()

-- Illumination Up
hs.eventtap.event.newSystemKeyEvent('ILLUMINATION_UP', true):post()
hs.eventtap.event.newSystemKeyEvent('ILLUMINATION_UP', false):post()
```

Note: the toggling of the System Key Event to true and then false is necessary. Personally, I bind these to [keyboard shortcuts](https://github.com/rsefer/hammerspoon-config/blob/101b58bc22f7b24debb723f020e076261184abbb/lib/shortcuts.lua#L30-L40).

**Comment by specter78** [comment]
@rsefer Thank you. It works.
