### ISSUE TITLE
Add support for Elgato Stream Deck +

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3342]
Note to self:

https://github.com/julusian/node-elgato-stream-deck/commit/37479d8a14bffe6eb421164bbaad1161dc302502

https://github.com/bitfocus/companion/commit/b1183862855336992630bbeb5c35f3e34f2b5173

https://github.com/OpenMacroBoard/StreamDeckSharp/issues/50

https://github.com/cgiesche/streamdeck-homeassistant/issues/117

**Comment by cmsj** [comment]
@latenitefilms are you likely to work on this? I don't think I'm going to buy a Deck+

**Comment by latenitefilms** [comment]
Yep! Hoping for new toy to arrive next week.

**Comment by yakobie** [comment]
Just got my new stream deck, very excited to see this is being developed. Thank you for the hard work

**Comment by latenitefilms** [comment]
I now have the hardware - I'm hoping to have time to try make it work over the next couple of weeks. Stay tuned!

**Comment by spenceratwatson** [comment]
@latenitefilms how is it going getting the dials to work with HASS?
