### ISSUE TITLE
Please make an example script to replicate functions of "catchmouse" app

### ISSUE THREAD

**Issue by Paw2Pom** [Hammerspoon/hammerspoon#3343]
The catchmouse app is very popular and super useful for multi-monitors users, where it can quickly move the mouse cursor to the center of desired monitor with simple self-set shortcuts.

<img width="800" alt="Screenshot 2022-12-08 at 9 55 13 AM" src="https://user-images.githubusercontent.com/21134942/206337154-626cf047-89ec-48c6-bdef-244119b49a89.png">

The catchmouse project itself is closed-source, and the original owner doesn't seem to willing to update the app design alot of requests on the project page:

https://github.com/round/CatchMouse/issues/7

So is there any chance we can use HammerSpoon to achieve the same with catchmouse? If so, any chance can provide a sample script that we can just paste into HS and run it directly?

Thank you so much!

**Comment by fishstik** [comment]
```lua
function moveMouse(screenNum)
    local screens = hs.screen.allScreens()
    local rect = screens[screenNum]:fullFrame()
    local center = hs.geometry.rectMidPoint(rect)
    hs.mouse.setAbsolutePosition(center)
end
hs.hotkey.bind({'shift'}, '4', function() moveMouse(1) end)
hs.hotkey.bind({'cmd'}, '2', function() moveMouse(2) end)
```

**Comment by Paw2Pom** [comment]
Thank you so much @fishstik!

If I want to make:
Display 1 Shortcut = SHIFT + CMD + Arrow Key Down
Display 2 Shortcut = SHIFT + CMD + Arrow Key Left
Display 3 Shortcut = SHIFT + CMD + Arrow Key Right

How can I adjust the code?

**Comment by Paw2Pom** [comment]
Am I on the right track here?

`
function moveMouseScreen(screenNum)
    local screens = hs.screen.allScreens()
    local rect = screens[screenNum]:fullFrame()
    local center = hs.geometry.rectMidPoint(rect)
    hs.mouse.setAbsolutePosition(center)
end
hs.hotkey.bind({'cmd'}, {'shift'}, 'down', function() moveMouseScreen(1) end)
hs.hotkey.bind({'cmd'}, {'shift'}, 'left', function() moveMouseScreen(2) end)
hs.hotkey.bind({'cmd'}, {'shift'}, 'right', function() moveMouseScreen(3) end)
`

**Comment by dasmurphy** [comment]
try this one:
```lua
function moveMouseScreen(screenNum)
    local screens = hs.screen.allScreens()
    local rect = screens[screenNum]:fullFrame()
    local center = hs.geometry.rectMidPoint(rect)
    hs.mouse.setAbsolutePosition(center)
end
hs.hotkey.bind({'cmd', 'shift'}, 'down', function() moveMouseScreen(1) end)
hs.hotkey.bind({'cmd', 'shift'}, 'left', function() moveMouseScreen(2) end)
hs.hotkey.bind({'cmd', 'shift'}, 'right', function() moveMouseScreen(3) end)
```
