### ISSUE TITLE
I want to make a small dot next to the mouse cursor... Is it possible?

### ISSUE THREAD

**Issue by pppaapp** [Hammerspoon/hammerspoon#3345]
![CleanShot 2022-12-20 at 19 53 21](https://user-images.githubusercontent.com/31263588/208650472-1dbeea55-986c-4bce-9e5a-87988e78f98a.gif)

I want to make a small dot that follows the mouse cursor in real time...

**Comment by dasmurphy** [comment]
I created for that an example that you may use and change for your liking. It works really fine for me.

Take a look at this ticket: https://github.com/Hammerspoon/hammerspoon/issues/2425

**Comment by pppaapp** [comment]
> I created for that an example that you may use and change for your liking. It works really fine for me.
> 
> Take a look at this ticket: [#2425 (comment)](https://github.com/Hammerspoon/hammerspoon/issues/2425#issuecomment-745306044)
> 
> Here is a video of how it works: [#2425 (comment)](https://github.com/Hammerspoon/hammerspoon/issues/2425#issuecomment-708398553)

Thank you.

but the code is too long for me

I don't know because I don't have knowledge...
