### ISSUE TITLE
How to read from hs.socket.server without polling

### ISSUE THREAD

**Issue by alexanderflink** [Hammerspoon/hammerspoon#3348]
Hello!
I know there has been a previous issue about this #2550, however I don't think it came to a conclusion.
I have some code to set up a unix socket, but it seems I need to continuously poll the server with `:read("\n")` in order to have the callback fire.

Is this how you are supposed to work with unix sockets in Hammerspoon or is there a better way which does not require polling?

Thanks!

Using this code, I can send data to the socket like: `echo "message" | nc -U /tmp/mysocket`. It works, but i'd like to avoid polling like this.

```lua
local server = hs.socket.server("/tmp/mysocket", function(data)
	print(data)
end)

hs.timer.doEvery(0.1, function()
	server:read("\n")
end)
```

**Comment by cmsj** [comment]
Is the callback to `.server()` not called when new data is available? Perhaps that is a difference with UNIX sockets?

**Comment by Rhys-T** [comment]
Possibly related to #3456? That one is about TCP sockets, not Unix domain sockets, but it's still trying to run a stream (as opposed to datagram) server, and having trouble reading from the connection…

**Comment by cmsj** [comment]
From poking around a bit, I don't think the underlying library we use (CocoaAsyncSocket) can automatically poll a UNIX socket for you, so polling is indeed the way to go here.
