### ISSUE TITLE
It does not launch at login.

### ISSUE THREAD

**Issue by qlife1146** [Hammerspoon/hammerspoon#3352]
I tried check the 'launch hammerspoon at login'. but, The check mark will continue to be turned off.

https://user-images.githubusercontent.com/32091837/209766725-b1600d69-debb-4e5f-93d9-4b794d157611.mov

Please tell me the solution.

**Comment by ottopic** [comment]
Hello I have the same problem with new fresh installation.

**Comment by ottopic** [comment]
@qlife1146 rollback to previous version, add to login then run hammerspoon autoupdate.

**Comment by juanyunis** [comment]
Real solution is:
1. Go to System Settings > General > Login Items > Select Hammerspoon.app from Open at login list > Click minus button (-)
2. Inside Hammerspoon.app click Launch at login again and it should persist.
