### ISSUE TITLE
window.orderedWindows() broken again

### ISSUE THREAD

**Issue by chavlji** [Hammerspoon/hammerspoon#3357]
The following `init.lua` doesn't work as expected: 

```lua
hs.eventtap.new({hs.eventtap.event.types.leftMouseDown}, function ()
  print('button down')
  local _ = hs.application
  print(hs.window.orderedWindows())
end):start()

hs.console.clearConsole()
```

### To reproduce
Run the above script in Happerspoon, open the console and start pressing the left mouse button. It works fine some 20-30 times and then all of a sudden there are no more new entries in the console (no errors though).

If I comment out line `print(hs.window.orderedWindows())` it works flawlessly all the time.

It really drives me nuts! What could be the case here?

### My Specs:
Hammerspoon 0.9.97 (6267)
Ventura 13.0
MB Pro 16" 2021 M1 Max

**Comment by latenitefilms** [comment]
It's probably a garbage collection issue. Try saving your `hs.eventtap` in a global variable.

`et = hs.eventtap.new(...)`
