### ISSUE TITLE
Extend package.path so require can import any file in a Spoon's root directory

### ISSUE THREAD

**Issue by alexwforsythe** [Hammerspoon/hammerspoon#3362]
## Problem

I want to split up my spoon's `init.lua` file into several smaller files so it's easier to maintain. My issue is I can't use `require` to import other files from `init.lua` because statements like this:
```lua
require('MySpoon.spoon.myfile')
```

Produce the following error:
```
2023-01-22 12:42:19: *** ERROR: ...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: module 'MySpoon.spoon.myfile' not found:
	no field package.preload['MySpoon.spoon.myfile']
	no file '/Users/alex/.hammerspoon/MySpoon/spoon/myfile.lua'
	no file '/Users/alex/.hammerspoon/MySpoon/spoon/myfile/init.lua'
	no file '/Users/alexforsythe/.hammerspoon/Spoons/MySpoon/spoon/myfile.spoon/init.lua'
	...
```

Lua can't find `myfile.lua` in `package.path`. This happens because:
 - `require` substitutes `.` with `/` (the directory separator on MacOS)
 - Spoon directories must contain a `.spoon` suffix

So Lua interprets `MySpoon.spoon.myfile` as `MySpoon/spoon/myfile`. `package.path` doesn't contain `~/.hammerspoon/MySpoon.spoon/?.lua`, so I can't simply use `require('myfile')` either.

## Proposal

I'd like to propose we append `~/.hammerspoon/Spoons/?.spoon/?.lua` to `package.path` so we can require files like `myfile.lua` via statements like:
```lua
require('MySpoon;myfile')
```

I assume this could be done easily from somewhere in the Hammerspoon initialization code with something like:
```lua
package.path = package.path .. ';' ..
  '~/.hammerspoon/Spoons/?.spoon/?.lua'
```

According to the Lua docs, `package.path` can contain templates with multiple substitution points (`?`), and their names can be provided to `require` as strings delimited by `;` (the default separator).

This would make it easier for developers to manage multi-file Spoons by allowing us to use the recommended import method provided by Lua (`require`). It would also allow Spoons to share modules with user files and other Spoons, but whether that's a benefit seems arguable because it subverts the abstraction layer originally introduced by the Spoon pattern.

**Comment by cmsj** [comment]
I'm not ruling the idea out, but we do already do this slightly differently in a few Spoons. Check out how Seal loads its plugins with loadfile() for example.

**Comment by Rhys-T** [comment]
If you do want to use `require`, note that this seems to take more than just modifying `package.path`. As far as I can tell, every `?` in a `package.path` entry gets replaced with the entirety of the `require`d module name (with `.`s changed to `/`s), with no way to put part of it before the `.spoon/` and part of it after.

Testing using `package.searchpath(...)`, and using the error message to see what it's looking for:
```lua
package.searchpath('MySpoon.myfile', hs.configdir..'/Spoons/?.spoon/?.lua')
--[[
returns:
	nil	no file '/Users/username/.hammerspoon/Spoons/MySpoon/myfile.spoon/MySpoon/myfile.lua'
when what we want is:
	nil	no file '/Users/username/.hammerspoon/Spoons/MySpoon.spoon/myfile.lua'
]]
```

I can't find any reference to putting semicolons in `require`'s argument, only in the `package.path` string. If I try passing in a module name containing `;`, it does something _very_ weird: it seems to first replace all the `?`s in `package.path` with the module name, _then_ split on `;`s, _including_ ones that came from the module name.

```lua
package.searchpath('MySpoon;myfile', hs.configdir..'/Spoons/?.spoon/?.lua')
--[[
returns:
	nil	no file '/Users/username/.hammerspoon/Spoons/MySpoon'
		no file 'myfile.spoon/MySpoon'
		no file 'myfile.lua'
]]
```

`require` _can_ be made to look for modules within spoons, but it will probably need a custom function added to the [`package.searchers`](https://www.lua.org/manual/5.4/manual.html#pdf-package.searchers) table.

<details>
<summary>Example searcher to make this work for any spoon</summary>

```lua
local match = string.match
local searchpath = package.searchpath
local function spoonModuleSearcher(moduleName)
	local spoonName, moduleSubName = match(moduleName, '^([^.]+)%.(.+)$') -- split at first dot
	if not moduleSubName then
		return
	end
	-- The following line will need to be changed if Spoons are being stored anywhere other than
	-- the main Spoons directory - see also #2441, #2887
	local pathPatterns = hs.configdir .. '/Spoons/' .. spoonName .. '.spoon/?.lua'
	local filePath, err = searchpath(moduleSubName, pathPatterns)
	if err then
		return err
	else
		local fn, err = loadfile(filePath)
		if err then
			error(err)
		else
			return fn, filePath
		end
	end
end
package.searchers[#package.searchers+1] = spoonModuleSearcher

require('MySpoon.mymodule')
```

</details>

<details>
<summary>Example to embed in a Spoon's `init.lua` to make it work for that Spoon (simple version)</summary>

```lua
-- in MySpoon.spoon/init.lua, at top level:
local match = string.match
local searchpath = package.searchpath
local function thisSpoonModuleSearcher(moduleName)
	local moduleSubName = match(moduleName, '^MySpoon%.(.+)$') -- split at first dot
	if not moduleSubName then
		return
	end
	local pathPatterns = hs.spoons.resourcePath('?.lua')
	local filePath, err = searchpath(moduleSubName, pathPatterns)
	if err then
		return err
	else
		local fn, err = loadfile(filePath)
		if err then
			error(err)
		else
			return fn, filePath
		end
	end
end
package.searchers[#package.searchers+1] = thisSpoonModuleSearcher

require('MySpoon.mymodule')
```

</details>

<details>
<summary>Example to embed in a Spoon's `init.lua` to make it work for that Spoon (fancy version)</summary>

This one is somewhat overengineered. It avoids making any assumptions about the Spoon's name, or what folder it's in. It gives the Spoon and all its sub-modules access to a `requireMy` function, which is just a shortcut for `require('MySpoon.<whatever>')`, but without having to know the name `MySpoon`.

```lua
-- in MySpoon.spoon/init.lua, at top level:
local spoonName, spoonInitPath = ... -- arguments passed by the `require` that loaded this Spoon
local spoonNameEscaped = spoonName:gsub('(%W)', '%%%1')
local spoonModulePattern = '^' .. spoonNameEscaped .. '%.(.+)$'
local spoonPath = spoonInitPath:match('^(.*)/[^/]*$')
local match = string.match
local searchpath = package.searchpath
local yield = coroutine.yield
local function requireMy(moduleSubName)
	return require(spoonName .. '.' .. moduleSubName)
end
local function spoonModuleWrappedLines(filePath)
	return coroutine.wrap(function()
		yield("local _ENV, requireMy = realEnv, requireMy; ")
		for line in io.lines(filePath, 'L') do
			yield(line)
		end
	end)
end
local function thisSpoonModuleSearcher(moduleName)
	local moduleSubName = match(moduleName, spoonModulePattern)
	if not moduleSubName then
		return
	end
	local pathPatterns = spoonPath .. '/?.lua'
	local filePath, err = searchpath(moduleSubName, pathPatterns)
	if err then
		return err
	else
		local fn, err = load(spoonModuleWrappedLines(filePath), '@' .. filePath, 't', {realEnv = _G, requireMy = requireMy})
		if err then
			error(err)
		else
			return fn, filePath
		end
	end
end
package.searchers[#package.searchers+1] = thisSpoonModuleSearcher

requireMy('mymodule')
```

</details>

(Warning: none of those have been tested very extensively.)
