### ISSUE TITLE
What should the permissions be on the init.lua file?

### ISSUE THREAD

**Issue by vesper8** [Hammerspoon/hammerspoon#3367]
I just rebooted my Mac and suddenly Hammerspoon wouldn't start and it was complaining that it could not open the `~/.hammerspoon/init.lua` file

The permissions on that file at this time were `-rw-------@`

I just `chmod 775` on `init.lua` and that solved the problem. But I'm unsure if this is safe.

Also have no idea why this happened in the first place.. a reboot seems to have messed with the permissions somehow.

But in any case, I was wondering if anyone could confirm what should be the permission level on `init.lua` to make things work but also safe?

Thanks!

**Comment by EdgardoArriagada** [comment]
Hey there!

Another hammerspoon user here

my current `~/.hammerspoon/init.lua` file permissions are `.rw-r--r--`

When I do create a new file using the `touch` command, the new file permissions are `.rw-r--r--`.

So I guess didn't have to change the `init.lua` file permissions before.

**Comment by Rhys-T** [comment]
Hmm - I don't know of any reason it would need to be more than `0600`/`rw-------`. Hammerspoon is running under your user ID, after all, and `init.lua` isn't being directly 'executed' in the Unix sense.

That `@` isn't part of the permissions - it indicates that the file has extended attributes. I suppose it's possible that one of those could be causing macOS's sandbox/TCC/etc. stuff to block Hammerspoon's access to the file. (Not sure why any xattrs would have gotten added, though… my `init.lua` doesn't have any…)

If you run `ls -l@ ~/.hammerspoon/init.lua`, does it list any extended attributes below the file?
