### ISSUE TITLE
feature request, general: user interface input elements

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#337]
maybe as several separate modules, maybe as combination of existing modules or extensions of such...

initial suggestions, add more here:
- basic text input, one line and multi line
- chooser from among a list
  - https://github.com/sdegutis/choose has been suggested
  - pop-up menu
  - multiple selection support from a selection box?
- dialog box with N buttons
  - defaults OK, Cancel, etc.
  - other arbitrary labels?
- checkboxes/radio buttons?
- combine multiple types into a more generic form object?
- will adding support for WebView instead of just NSView and NSTextView to hs.drawing help here?  Or should it be a separate module?

Some thoughts:
- Should be as generic as possible, not targeted to just a handful of specific uses, for easy re-use.
- Should support multiple layers/hierarchy (e.g. a button in a dialog causes another dialog to pop up for more specific input, rather than just closing out the initial one)
- Should hs.drawing allow full screen rectangle that captures, rather than passes through, input, so we can create modal views similar to those in some web sites where the background greys out and the input area is focused "on top"?
- Use callbacks attached to dialogs/input displays rather than stop lua/Hammerspoon processing until user responds?

**Comment by cmsj** [comment]
Definitely should all be callback driven, blocking is awful.

I think basic system UI is actually not being asked for very much - what I'm seeing more and more, is people wanting choosers (be they in list form, or in graphical tab form like alt-tab system thing)

**Comment by szymonkaliski** [comment]
> I think basic system UI is actually not being asked for very much

Yeah, and you can always do it with AppleScript pretty easily ;)

> what I'm seeing more and more, is people wanting choosers (be they in list form, or in graphical tab form like alt-tab system thing)

+1 on the list thing though!

**Comment by cmsj** [comment]
FYI, I'm working on a port of choose at the moment.

**Comment by asmagill** [comment]
I'd forgotten about this one...

`choose` would be a great addition.  I'd like to request more display options than the original code offered (background color, font, size, etc.) but even a basic drop in of the current version would be good.

As for text input, as mentioned, applescript is always an option, and I've successfully used `hs.webview` with a web form in https://github.com/asmagill/hammerspoon-config/blob/master/dterm.lua and a javascript `window.prompt` in https://github.com/asmagill/hammerspoon-config/blob/master/utils/prompter.lua, so I think we're probably good and can close this and maybe #675 as well once the chooser is in place.

**Comment by cmsj** [comment]
@asmagill I'm still in the aggressively-bootstrapping phase, so I'm not sure what I'll be able to do with it yet, but I'm fine with attempting to make it as customisable as possible. I'm trying to get it to operate in two modes, one where you give it a fixed list of items and it helps you fuzzily search them, and a second one where you type something and it calls a Lua callback to get a list of results, maybe you select one, maybe you type some more and the callback gets called again. This second mode would make it possible to start thinking about implementing something like Alfred, which is a long term goal of mine.

**Comment by cmsj** [comment]
(hs.chooser is landed now)

**Comment by latenitefilms** [comment]
For future reference, I've posted some examples of what I would like to see in terms of dialog boxes here: https://github.com/Hammerspoon/hammerspoon/issues/1227#issuecomment-278972348

**Comment by latenitefilms** [comment]
FYI - I'm still noticing lots of weirdness when using AppleScript within Hammerspoon - especially for UI things like dialog boxes, and file browsers in Sierra. For example, the AppleScript dialog boxes will appear, and they LOOK like they're working, but the dialog boxes are non-responsive and it takes multiple goes at clicking the "OK" button before it actually registered - it's almost as if Hammerspoon (or the AppleScript "engine") has stalled. When the computer finally recognises you've clicked the dialog box, it's almost as if it's forgotten you've released the mouse, because if I have a text editor in the background, suddenly I'm dragging text selections (as if the mouse button is being held down). Very weird behaviour - but it definitely seems to be something Apple's done in Sierra that's causing it.

Replacing AppleScript dialog boxes with `hs.webview`'s is maybe an option (@asmagill has a great example [here](https://github.com/asmagill/hammerspoon-config/blob/master/utils/prompter.lua)), but I still think a proper Objective-C powered extension would be best (as discussed in more detail [here](https://github.com/Hammerspoon/hammerspoon/issues/1227#issuecomment-278972348)).

Maybe something for `0.9.53`?

**Comment by latenitefilms** [comment]
@asmagill, @cmsj and/or other Objective-C gurus...

I've finally had a chance to start messing around with Objective-C and I'm SLOWLY trying to create what I suggested in #1227 (i.e. a `hs.dialog` extension so that we can avoid using unreliable AppleScript).

I've got the basic's working, but I'd love your advice on how I can make the dialog box "non-blocking" and trigger a callback when a button is pressed (as opposed to locking up Hammerspoon, until the user presses something). Is this possible?

Below is what I've got so far. Any ideas, comments or suggestions would be HUGELY appreciated!

```
@import Cocoa ;
@import LuaSkin ;

#define USERDATA_TAG "hs.dialog"
static int refTable = LUA_NOREF ;

/// hs.dialog.show(messageText, informativeText, [callbackFn], [buttonOne], [buttonTwo], [style]) -> nil
/// Function
/// Displays a dialog box.
///
/// Parameters:
///  * messageText - The message text to display
///  * informativeText - The informative text to display
///  * [callbackFn] - Callback function
///  * [buttonOne] - An optional value for the first button as a string (defaults to 'OK')
///  * [buttonTwo] - An optional value for the second button as a string
///  * [style] - Style of the dialog box as a string (defaults to 'NSWarningAlertStyle')
///
/// Returns:
///  * `true` if all the arguments are valid, otherwise `false`
///
/// Notes:
///  * If `callbackFn` is not provided this is a blocking function, and will return the text of which ever button is pressed.
///  * Otherwise, if `callbackFn` is provided then this becomes a non-blocking function, and will trigger the callback function when a button is pressed.
static int showDialog(lua_State *L) {	
	
 	LuaSkin *skin = [LuaSkin shared];
    [skin checkArgs:LS_TSTRING, LS_TSTRING, LS_TFUNCTION | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TBREAK];

    NSString* messageText = [skin toNSObjectAtIndex:1];
    NSString* informativeText = [skin toNSObjectAtIndex:2];
    
    NSString* buttonOne = [skin toNSObjectAtIndex:4];
    NSString* buttonTwo = [skin toNSObjectAtIndex:5];
    NSString* style = [skin toNSObjectAtIndex:6];
	
	if( buttonOne == nil ){
		buttonOne = @"OK";
	} 
	
	NSAlert *alert = [[NSAlert alloc] init];
	[alert addButtonWithTitle:buttonOne];
	[alert addButtonWithTitle:buttonTwo];
	[alert setMessageText:messageText];
	[alert setInformativeText:informativeText];
	[alert setAlertStyle:NSWarningAlertStyle];

	NSInteger result = [alert runModal];

	if (result == NSAlertFirstButtonReturn) {
		[LuaSkin logInfo:@"First button was pressed."];
		if ([skin toNSObjectAtIndex:4] == nil) {
			lua_pushstring(L,"OK");
		}
		else
		{
			lua_pushvalue(L, 4);
		}
	}
	else if (result == NSAlertSecondButtonReturn) {
		[LuaSkin logInfo:@"Second button was pressed."];
		lua_pushvalue(L, 5);
	}
	else
	{
		// THIS SHOULD NEVER HAPPEN:
		[LuaSkin logInfo:@"Neither the first nor second button was pressed."];	
		lua_pushstring(L, "Neither the first nor second button was pressed.");	
	}
	
	return 1 ;
}

// Functions for returned object when module loads
static luaL_Reg moduleLib[] = {
    {"show", showDialog},
    {NULL,  NULL}
};

int luaopen_hs_dialog_internal(lua_State* __unused L) {
    LuaSkin *skin = [LuaSkin shared];
	refTable = [skin registerLibrary:moduleLib metaFunctions:nil] ;
	
    return 1;
}
```

**Comment by cmsj** [comment]
I believe NSAlert can only run in a blocking form, because it's intended for alerts. For non-alerts you'd likely want a simple NSWindow with a textfield for the message, and various buttons.

**Comment by latenitefilms** [comment]
@cmsj - Ah, right - thanks! Makes sense.

I've started throwing together something I'm calling `hs.dialog` in #1504.

My plan is to try and implement everything I suggested in #1227.

I'm just making it up as I go along, so would definitely love and welcome any comments, suggestions, ideas or improvements.

I have some more specific questions - but I'll ask them in the #1504 comments.

**Comment by cmsj** [comment]
Given that hs.dialog is coming and has its own Feature Request issue, I suggest we close this issue out and if there are things that would still be useful later, handle them in individual issues.
