### ISSUE TITLE
hs.drawing image elements do not respond properly to :setSize()

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#338]
Noticed this while I was working on hs.drawing.appImage() this morning. Resizing an image element does resize the HSDrawingWindow, but the image inside it stays the same size, or disappears. Presumably we have some missing propagation of frame sizing, or NSImage sizing.

**Comment by asmagill** [comment]
I did have to make special allowances for hs.drawing.text objects (which was my primary objective at the time)... but I didn't test image; just text, rect, circle, and line... and line doesn't resize the line, but the viewable area -- you can clip the line by changing its size, but the line itself stays the same.  Moving it works, though.
