### ISSUE TITLE
Method for creating an hs.sound from an array of samples?

### ISSUE THREAD

**Issue by TheQuinbox** [Hammerspoon/hammerspoon#3384]
For my spoon, I need to be able to feed hs.sound a table of samples, and have it able to play them. With a quick glance through the docs, this is not possible. Am I missing something? If not, is it possible for this to be added?

**Comment by latenitefilms** [comment]
You could code this yourself. Create your own table of `hs.sound` objects, then use the `callback` to determine when a sound has finished playing so that you can start playing the next sound in the table?

**Comment by TheQuinbox** [comment]
No, that's not what I mean. I meant raw samples.
Take this function:
local function generateSineWave(frequency, duration, sampleRate)
	local sampleRate = sampleRate or 44100
	local numSamples = math.floor(duration * sampleRate)
	local samples = {}
	for i = 1, numSamples do
		local t = i * sampleRate
		samples[i] = math.sin(2 * math.pi * frequency * t)
	end
	return samples
end

This generates raw samples, and I want to be able to feed those to the audio engine directly, and have them played. I could write them to a file, play it, and then delete it, but that seems very inefficient

**Comment by latenitefilms** [comment]
Ah, I see. Internally `hs.sound` uses `NSSound`, and `NSSound` doesn't give you access to raw sample data. You'd need to use the [Audio Toolbox framework](https://developer.apple.com/documentation/audiotoolbox) instead.

Maybe helpful:

https://medium.com/programming-for-music/generating-raw-audio-samples-f08f3adf73af

**Comment by TheQuinbox** [comment]
Ah, okay. I see. Thanks!
