### ISSUE TITLE
lua 5.3 number audit in modules

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#339]
For lua 5.3 -- an audit should be done to identify things which should be integers versus numbers; for example:

hs.application.applicationsForBundleID(hs.settings.bundleID)[1]:pid()
returns (for example): 65555.0

A process ID is never a float -- it is always an integer, and it should be returned as such.

A simple lua fix is to wrap these with math.floor(...), but existing code will fail until this is added because of 5.3's distinction between integer and number (lua_tonumber vs lua_tointeger).

(posted this to #328 and only realized it was closed after posting)

**Comment by cmsj** [comment]
Good point! I've started work on this, and I'll push the results up to a separate branch for review, since there are quite a few points where we probably should switch to lua_Integer.

**Comment by cmsj** [comment]
Said branch for review is #344

**Comment by cmsj** [comment]
And that is now landed :)
