### ISSUE TITLE
Feature request: call command by name with completion

### ISSUE THREAD

**Issue by dmgerman** [Hammerspoon/hammerspoon#3390]
I love hammerspoon 

But there is one thing that makes it hard to use: I have to assign a key to any command I want to use (or use the console and trying to identify, of all the functions which are are "interactive").

Would it be possible to create some mechanism that:

1. Tags some functions to be available to be executed manually
2. A command to bring a chooser window that asks for a command to be executed
4. In this window completion is available so as one types, the list of potential candidates is narrowed
5. Type return and execute the currently displayed command
6. Keeps track of any keybinding that calls this command

When a user selects a command, it is executed and the keybinding displayed (e.g. similar to M-x in emacs).

The console provides a bit of completion, but it is not very usable in its current state for this purpose, since any symbol is available for completion.

I have sketched a partial solution to this, but I think #1 above would make things easier.

My solution has been:

1. Create a table of commands: <name, function ... end, reminder of keybinding>
2. Show a chooser window
3. Execute selected command
4. Show the reminder if defined

The problem with this approach is that it has to be managed manually.

**Comment by cmsj** [comment]
We would have to modify Lua itself to be able to tag functions in some way, and we've tried very hard to not modify Lua, so we can keep it updated easily.

I think the lowest-effort way to achieve what you're looking for would be to have a global table which you add functions to, in your Hammerspoon config. It is manual management, but it should be pretty easy to just do something like `table.insert(fnCompletions, someNewFunction)` each time you declare a function.
