### ISSUE TITLE
"Development Builds" fails miserably on forks

### ISSUE THREAD

**Issue by jsoref** [Hammerspoon/hammerspoon#3395]
In order to usefully contribute to a project, one needs to be able to update branches corresponding to an upstream's default branch.

In the case of hammerspoon, that's the `master` branch

When one performs a sync with the github ui or the github cli or just performs a fetch from the upstream and then a push to the fork, github treats that new commit for `master` as a `push` and will perform all workflows that have an `on: push` for which `master` is applicable.

One such workflow is:
https://github.com/Hammerspoon/hammerspoon/blob/e1bd3ef46d7b4619ccd918a13c845eed3b511724/.github/workflows/ci_nightly.yml#L3-L6

That workflow relies on repository secrets which will _generally_ not be present in forks:

https://github.com/Hammerspoon/hammerspoon/blob/e1bd3ef46d7b4619ccd918a13c845eed3b511724/.github/workflows/ci_nightly.yml#L29-L35

The end result is a workflow that fails like this:
https://github.com/jsoref/hammerspoon/actions/runs/4284616541/jobs/7461819087#step:5:1
```
Decrypt Secrets
Run ./ci-secrets/crypto.sh decrypt
ERROR: REPO_GPG_PASSPHRASE is unset
Error: Process completed with exit code
```
...
https://github.com/jsoref/hammerspoon/actions/runs/4284616541/jobs/7461819087#step:13:11
```
Delete notarization/signing credentials
Run ./scripts/build.sh keychain-post
Gathering info...
2023-02-2[7](https://github.com/jsoref/hammerspoon/actions/runs/4284616541/jobs/7461819087#step:13:8) 16:55:42.569 xcodebuild[4595:1293[8](https://github.com/jsoref/hammerspoon/actions/runs/4284616541/jobs/7461819087#step:13:9)] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
 Removing keychain...
security: SecKeychainDelete: The specified keychain could not be found.
Error: Process completed with exit code 50.
```

---

The way to handle this properly is to have a job that checks for all necessary secrets and then have a job conditional on the first job's output confirming it has all the secrets it needs.

**Comment by cmsj** [comment]
I think it's fair to note that the Development Builds action doesn't work on forked repos, I don't think the answer is to consume GitHub resources on every commit to every fork, testing if secrets are set.

I would think a more reasonable option would be to disable that workflow, which can be done with the little `...` button on the right side of https://github.com/jsoref/hammerspoon/actions/workflows/ci_nightly.yml

It would be nice if I could say the workflow is disabled by default in the yaml, but I don't believe that is possible.

**Comment by jsoref** [comment]
The alternative is to add an `if:` that checks if the repository explicitly matches `Hammerspoon/hammerspoon` which would result in it not running (from memory, there's at least one check somewhere for a webhook that does this).

**Comment by jsoref** [comment]
And, indeed, it's absolutely not possible to make workflows disabled by default. And worse, in general if you touch/push a workflow, it tends to reenable itself, so it's basically a fool's errand (I trip on this stuff a *lot* as I maintain lots of forks of lots of repositories).

**Comment by cmsj** [comment]
Ugh, if the workflows are going to re-enable themselves in forks when they resync with origin then the choice is really "waste some Linux runner time" vs "waste some macOS runner time" and the former is then definitely preferable.

**Comment by obecker** [comment]
Hi, may I ask why this issue is still open? There is a PR, there is this discussion, but there is no resolution. I wonder if Hammerspoon is actually still maintained.

**Comment by obecker** [comment]
Alright, just found https://github.com/Hammerspoon/hammerspoon/discussions/3506 - which answers my second question.
