### ISSUE TITLE
Implement alternative to stickler-ci

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3403]
Sadly, old mate @stickler-ci is shutting down.

https://stickler-ci.com/shutting-down

Maybe something like this for Lua?

https://github.com/marketplace/actions/luacheck

**Comment by cmsj** [comment]
Have you found the Stickler comments useful? I added it in a fit of optimism, but I'm not convinced the output is actually useful. Quickly running `luacheck` and `serene` over our `extensions/` folder produces *thousands* of warnings 😫

**Comment by latenitefilms** [comment]
I always found it useful, but mainly because I primarily use BBEdit, which doesn't have built-in lint warnings, so sticker-ci made me aware of silly Lua mistakes.
