### ISSUE TITLE
Sponsorship?

### ISSUE THREAD

**Issue by eccentric-j** [Hammerspoon/hammerspoon#3406]
I'd like to show my appreciation for this project and the people who maintain it by sponsoring with a donation. It does not seem like there are any sponsorship options on the gh org page or project. Could you please consider setting one up?

**Comment by eccentric-j** [comment]
Thanks! I had searched previous issues but looked for "Sponsor" and missed those.

**Comment by cmsj** [comment]
Thanks @eccentric-j :)

**Comment by eccentric-j** [comment]
You're welcome. Thanks for everyone involved in making Hammerspoon so great. Hacking on spacehammer has been one of the most fun projects I've ever worked on :grin:
