### ISSUE TITLE
It takes about 3 seconds before the function(window:focus()) returns.

### ISSUE THREAD

**Issue by netjune** [Hammerspoon/hammerspoon#3421]
OS: macOS 10.15.7
hammerspoon: 0.9.97 

I have some code like this:
```
   local win = hs.appfinder.windowFromWindowTitlePattern(title)
   if win == nil then
	  return false
   end

   win:focus()
```

It first finds a window with the title and then make it focused. Sometimes it finishes quickly. But most of the time, it takes about 3 seconds or more to finish.

I tried  `hs.appfinder.windowFromWindowTitlePattern(title)` in console. It always finished quickly.
Then I tried `hs.appfinder.windowFromWindowTitlePattern(title):focus()` in console. Most of the time, It took too long to finish.

**Comment by cmsj** [comment]
If you open Hammerspoon's Console window and run `hs.window._timed_allWindows()` does it identify something as taking most of that time? This often happens when an application has become somehow stuck and isn't replying to macOS' accessibility messages.

**Comment by netjune** [comment]
It seems yes.

```
> hs.window._timed_allWindows()
2023-03-16 11:13:52: took 2.04s for com.apple.ActivityMonitor
table: 0x6000015e4f00

> hs.window._timed_allWindows()
table: 0x6000015e7280

> hs.window._timed_allWindows()
table: 0x600001a7a740

> hs.window._timed_allWindows()
table: 0x600001a70040

> hs.window._timed_allWindows()
2023-03-16 11:14:00: took 2.07s for com.apple.ActivityMonitor
table: 0x600001a74b80

```

Then what should I do for this?

**Comment by cmsj** [comment]
is it faster if Activity Monitor is not running

**Comment by netjune** [comment]
Yes. I killed Activity Monitor. It is fast enouth now. 
Thanks.
