### ISSUE TITLE
Unexpected change in behaviour: hs.application.find

### ISSUE THREAD

**Issue by gingerbeardman** [Hammerspoon/hammerspoon#3427]
This just broke in 0.9.99

It was fine in yesterday's update.

**code**
```
local appMenuBar = hs.application.find("Tiles")
if(appMenuBar ~= nil) then
	appMenuBar:kill()
end
```

**description**
Depending on wether I am plugged in (Desktop) or not (Mobile) I look for certain apps and kill/quit them to make sure what I need is running.

**error**
```
2023-03-13 21:34:56: *** ERROR: /Users/matt/.hammerspoon/init.lua:59: attempt to call a nil value (method 'kill')
stack traceback:
	/Users/matt/.hammerspoon/init.lua:59: in function 'toggleDesktopOrMobile'
	/Users/matt/.hammerspoon/init.lua:92: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**workaround**
```
local appMenuBar = hs.application.find("Tiles", true, false)
```

**what happen**
- So the default behaviour has changed?
- Release notes explain the new parameters, but not that new defaults are a code breaking change

**Comment by cmsj** [comment]
Yeah I'm not thrilled that we're breaking peoples' code, but [hs.application.find()](http://www.hammerspoon.org/docs/hs.application.html#find) has always been allowed to return multiple results and I suspect that's what you're seeing here?

I think the way things are now is likely more correct overall, and if you want to find a single application I would lean more towards using `hs.application.get()`.

I've updated the release notes for 0.9.99 to make it clear that this may produce different results now.

Thanks!

**Comment by gingerbeardman** [comment]
Happy to use what its better for my purpose, will try `hs.application.get()`

Thanks Chris
