### ISSUE TITLE
Extend window layout to take application/title patterns or accept function or window object

### ISSUE THREAD

**Issue by peterloron** [Hammerspoon/hammerspoon#345]
Currently the window layout system only supports defining the application and/or window using a simple string. This makes it hard to capture windows that may have a varying title. E.g. a web page that always starts with the site name, but may change the rest of the title depending on which page you are on.

A solution would be for the layout to accept a regex pattern. This may break existing scripts that have reserved characters in them.

Another option would be to allow passing in a function or an object in addition to a string. As part of this, a method to use patterns to get windows would be needed, possibly something like "windowFromTitlePattern".

**Comment by cmsj** [comment]
I think this can be closed, we've been able to accept Lua Patterns (which are not regexes, unfortunately) for window titles for a while now, by passing `string.match` as the optional string comparison function.
