### ISSUE TITLE
hs.setting.set does not allow values starting with uppercase

### ISSUE THREAD

**Issue by danielo515** [Hammerspoon/hammerspoon#3473]
Thank you for creating Hammerspoon!

I've noticed that `hs.setting.set` does not allow to set a value that starts with uppercase, no error is thrown but the value is always returned as nil. However, the same operation with camelCase works fine. Is this an intended limitation? I couldn't find any mention of this in the documentation.

Thank you for your help!

**Comment by danielo515** [comment]
Ok, maybe an edge case where I accidentally set it first using camel case and then I was not able to use it again with PascalCase?

```
>  hs.settings.set("brainFart", "abc")

> hs.settings.get("brainFart")
abc

> hs.settings.set("BrainFart", "Abc")

> hs.settings.get("BrainFart")
Abc

> hs.settings.get("brainFart")
abc
```

Ok, nope. Does it matter that I'm doing this from within a spoon and I'm using the SpoonName as key?

**Comment by danielo515** [comment]
Ok, something is now wrong with my spoon setting settings, now they are not stored at all. Do you mind having a look at it? https://github.com/danielo515/StreamDeckButton.spoon/blob/main/init.lua

**Comment by latenitefilms** [comment]
This line looks wrong:

https://github.com/danielo515/StreamDeckButton.spoon/blob/7127c8916f4272c678e6882696c6c401869b180d/init.lua#L54

You should be providing the key and value?

**Comment by danielo515** [comment]
Oh, dam it, how can I be so dumb?

**Comment by danielo515** [comment]
That was indeed the problem. That is one of the things I hate about Lua, and why I try to not code anything complex in it. Probably will have to write some Haxe bindings for some type safety here 😂 
Thanks for your help
