### ISSUE TITLE
Build Issue - pygments~=2.11.2 distribution was not found

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#3498]
I've just tried building CommandPost, but I now get this error which I haven't seen before:

```
Checking Python requirements.txt is satisfied...
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygments~=2.11.2' distribution was not found and is required by the application
```

AFAIK `pygments` is installed though?

```
pip install 'pygments~=2.11.2'        
Requirement already satisfied: pygments~=2.11.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.11.2)
```

Any ideas @cmsj? Has something changed recently in the build scripts that I've missed?

**Comment by latenitefilms** [comment]
Oh, and I'm still on Monterey v12.6.3 - could that be related? Did you update code to only work with Xcode on Ventura?

**Comment by cmsj** [comment]
Where is the pip executable that you're calling? (`which pip`)

This could be one of the tedious things that happens when you have multiple Python installs and paths get messy.

**Comment by latenitefilms** [comment]
`/Library/Frameworks/Python.framework/Versions/3.11/bin/pip`

That weird part is that I've build fine previously, and as far as I can see, nothing has changed in the build scripts since I last built, and I haven't updated Xcode, because I'm still on Monterey.

**Comment by asmagill** [comment]
In my Catalina build attempts, I've run into an issue with the Sparkle Pod not honoring the limitation to build for 10.15, so I haven't tested the doc building yet. Checking the docs for Sparkle I found one line in the release notes that talks about bumping the required Xcode version to something after the one I can run on Catalina, but no details. Still trying to learn how the pods work, maybe I could tell it to use an earlier version?

I'm thinking about stripping out Sparkle completely since we won't be using it anyways, but I was trying to keep the core files as close to the original as possible to simplify future merges. I'll poke at it some more next week.

**Comment by cmsj** [comment]
Yep, your pip is from a different Python than the one being used during the build (3.11 vs 3.9).

Have you run the build.sh installdeps?

**Comment by latenitefilms** [comment]
Will try again now.

**Comment by latenitefilms** [comment]
Ok, so I ran `build.sh installdeps` but now I get..

```
Building docs Markdown...
Traceback (most recent call last):
  File "/Users/chrishocking/Documents/GitHub/CommandPost-App/scripts/docs/bin/build_docs.py", line 835, in <module>
    main()
  File "/Users/chrishocking/Documents/GitHub/CommandPost-App/scripts/docs/bin/build_docs.py", line 829, in main
    write_markdown(arguments.output_dir + "/markdown/",
  File "/Users/chrishocking/Documents/GitHub/CommandPost-App/scripts/docs/bin/build_docs.py", line 735, in write_markdown
    write_templated_output(output_dir, template_dir, title, source_url_base, data, "md")
  File "/Users/chrishocking/Documents/GitHub/CommandPost-App/scripts/docs/bin/build_docs.py", line 662, in write_templated_output
    import markdown
ModuleNotFoundError: No module named 'markdown'
```

**Comment by latenitefilms** [comment]
Ah, actually, maybe this is my fault:

```
	########################################################
	## ADDED BY CHRIS FOR COMMANDPOST:
	########################################################
    import jinja2
    import markdown

    md = markdown.Markdown(extensions=['meta'])

    jinja = jinja2.Environment()
    jinja.filters['markdown'] = lambda text: jinja2.Markup(md.convert(text))
    jinja.trim_blocks = True
    jinja.lstrip_blocks = True
	########################################################
```

**Comment by latenitefilms** [comment]
Adding `markdown` to `requirements.txt` solved for me!

Thanks team! Apologies for the noise.
