### ISSUE TITLE
How do you simulate pressing the close button of a window?

### ISSUE THREAD

**Issue by epheien** [Hammerspoon/hammerspoon#3517]
One of my needs is to switch to the previous window when I close the current window.

For example, I open iTerm in Finder, and then closing iTrem causes other iTerm windows to pop up, and then I figure out how to switch to Finder.

So I need the requirements mentioned above.

I use hammerspoon to implement a switching logic, as follows:
```lua
hs.hotkey.bind({"cmd"}, "w", function()
  local win = hs.window.focusedWindow()
  local prevWin = hs.window.orderedWindows()[2]

  win:close() -- NOTE: another window of this app will popup

  if prevWin ~= nil then
    prevWin:focus()
  end
end)
```

But `win:close()` causes other windows of iTerm to pop up automatically.

However, in practice, there is a scenario that can avoid popping out of other windows of iTerm, that is, first switch to finder, and then click the close button of the iTerm window.

So how do I simulate this with Hammerspoon?

**Comment by Rhys-T** [comment]
That's the standard behavior on macOS, not something Hammerspoon is doing. Closing the front window in the current app always switches focus to another window from that same app, if there is one.

Have you tried moving the `prevWin:focus()` part above `win:close()`? That should do the equivalent of the 'first switch to Finder' part.

Note, however, that if attempting to close a window triggers a dialog (e.g. "Do you want to save your changes?" - or in iTerm's case, depending on how it's configured, "There's still stuff running in this terminal. Are you sure you want to terminate it?"), then the app may bring itself right back to the foreground to show that dialog - and in any case, interacting with the dialog will also do that - which means that when the window _actually_ closes, it'll probably still end up bringing another window from that app to the front.

**Comment by epheien** [comment]
As you said, macOS defaults to window behavior like that, and the exported API doesn't work for my needs
