### ISSUE TITLE
Tilde in `userruntime` variable used in `package.path` not expanded

### ISSUE THREAD

**Issue by habibalamin** [Hammerspoon/hammerspoon#3518]
Looks like a bunch of paths under `~/.local/share/hammerspoon/site` are added to `package.{c,}path` in `setup.lua`. See the current tree:

https://github.com/Hammerspoon/hammerspoon/blob/0ccc9d07641a660140d1d2f05b76f682b501a0e8/Hammerspoon/setup.lua#L3-L24

Unfortunately, using a directory in the path doesn't work, unless you add the same path with `/Users/$USER` instead of `~`. I think that first line which sets `userruntime` should be set to `os.getenv("HOME") .. "/.local/share/hammerspoon/site"` instead of `~/.local/share/hammerspoon/site`.

**Comment by cmsj** [comment]
Good catch, thank you!
