### ISSUE TITLE
allWindows() skips Finder windows

### ISSUE THREAD

**Issue by chavlji** [Hammerspoon/hammerspoon#3533]
MacBook Pro M1 16", 64 GB
Ventura 13.0

**Bug**
`hs.window.allWindows()` used to include `Finder` windows.
Some months ago it stopped including them.
I did no major system updates or other major changes during that time.

Here's an example (app.name + app.id). No Finder app is printed, but I do have two Finder windows opened:
```
Google Chrome 74789
Google Chrome 67212
Google Chrome 67213
Google Chrome 67214
Google Chrome 67215
Google Chrome 67216
Google Chrome 67217
Google Chrome 67218
Google Chrome 67219
Google Chrome 67222
Google Chrome 67223
iTerm2 69070
Hammerspoon 83282
Hammerspoon 83281
Hammerspoon 82963
Fork 78864
Code 82927
Code 79325
Code 83204
Notion 79784
MonitorControl 82849
GitHub Desktop 83194
```

Please fix it or advise if there's anything else I could try! 🙏
I've created some win management tool and this bug drives me nuts!

---
I've also tried this and I get empty table:
```
> hs.inspect.inspect(hs.application.find("Finder"):allWindows())
{}
```

**Comment by luckman212** [comment]
I was curious so I tested this on my system, which is an M1 Mini now running 14.0 Sonoma. It seems to be working. Check your Accessibility permissions would be my guess.

```lua
for _,n in pairs(hs.application.find("Finder"):allWindows()) do print(n:title()) end
```

![image](https://github.com/Hammerspoon/hammerspoon/assets/1992842/39eacc47-f875-419f-bfcf-1d454b9b2b2f)

**Comment by chavlji** [comment]
Ahhh... Just disabled and reenabled Accessibility permissions and now it works again like charm. No idea what happened.
Thank you @luckman212 !
