### ISSUE TITLE
Keyboard Shortcuts on Sonoma?

### ISSUE THREAD

**Issue by jaidetree** [Hammerspoon/hammerspoon#3540]
Hey there! Just upgraded to Mac OS Sonoma but noticed my hotkey modals are not working. 

## Reproduction
1. Setup a global hs.hotkey.bind 
2. When the global hotkey is pressed, activate a hotkey modal
3. Try to press a key to activate an action from the hotkey modal

### Expected
The listener for the hotkey modal fires

### Actual
- The hotkey modal action never fires
- No errors in the console

Open to suggestions on solutions to try.

**Comment by danillos** [comment]
I'm having a similar issue. But at some point it worked but now, it is not working anymore.

**Comment by Rhys-T** [comment]
- Does it fail every time, regardless of what app you're in? Or just sometimes?
- Can you tell whether the global hotkey itself is failing, or just the ones inside the modal?
- When a hotkey fails to trigger a Hammerspoon action, does it look like the key sequence is just being passed through to whatever app you're in?
- Are the hotkeys inside the modal just letters without modifier keys?

I'm trying to figure out whether this could be the same issue as (or at least related to) #3555.

**Comment by rf-** [comment]
I'm having the same issue.

> * Does it fail every time, regardless of what app you're in? Or just sometimes?

It fails every time for me.

> * Can you tell whether the global hotkey itself is failing, or just the ones inside the modal?
> * Are the hotkeys inside the modal just letters without modifier keys?

The hotkey to activate the modal is definitely working, because modified hotkeys inside the modal are working, but simple letter-only hotkeys aren't.

> * When a hotkey fails to trigger a Hammerspoon action, does it look like the key sequence is just being passed through to whatever app you're in?

Yeah, the letters just get passed through to the current app like normal.

**Comment by rf-** [comment]
Now it's working again 🤷‍♂️
