### ISSUE TITLE
hs.alert.show: how to place this alert on different place on screen (center?)

### ISSUE THREAD

**Issue by muescha** [Hammerspoon/hammerspoon#3541]
How can I position the 'hs.alert.show' alert at a different location on the screen?

I'd prefer to have it centered within a child window of an app that's not in full-screen mode.

**Comment by latenitefilms** [comment]
There's no way to change position (aside from choosing a screen) currently in the extension, but the extension is all Lua, so you could copy and modify as needed:

https://github.com/Hammerspoon/hammerspoon/blob/0ccc9d07641a660140d1d2f05b76f682b501a0e8/extensions/alert/alert.lua#L78

**Comment by muescha** [comment]
thanks for the hint. i tried to fake an screen object from a window object to get it to the alert as "Screenobject" - the only thing missing was the `:fullFrame()` 

https://github.com/Hammerspoon/hammerspoon/blob/0ccc9d07641a660140d1d2f05b76f682b501a0e8/extensions/alert/alert.lua#L103

but this patch from chat gpt not working :(

```lua
	local win = hs.window.focusedWindow()
	local extendedWindowMetatable = {
        __index = {
            fullFrame = function(self)
                return self:frame()
            end
        }
    }

    setmetatable(win, extendedWindowMetatable)

	hs.alert.show("Hello World!", win)
```

i have done it with this patch in `alert.lua`:

```diff
-   local screenFrame = screenObj:fullFrame()
+   local screenFrame = screenObj.frame and screenObj:frame() or screenObj:fullFrame()
```
https://github.com/muescha/dot_hammerspoon/commit/7a95c28a1fbea0ad6c130e0e1171151632bf75cd

now i can call it with

```lua
	hs.alert.show("Hello World!", win)
```

**Comment by muescha** [comment]
one idea was to allow a `hs.geomety` object as parameter, but this was not possible to test with `getmetatable(frame) == hs.getObjectMetatable('hs.geometry')`

**Comment by muescha** [comment]
a little bug: `:frame()` exists also on the screen so I have to test for `.allFrame`:

```diff
-   local screenFrame = screenObj.frame and screenObj:frame() or screenObj:fullFrame()
+   local screenFrame = screenObj.fullFrame and screenObj:fullFrame() or screenObj:frame()
```

**Comment by muescha** [comment]
opened:
- Update alert.lua: allow window object as parameter #3542

**Comment by Rhys-T** [comment]
> one idea was to allow a `hs.geomety` object as parameter, but this was not possible to test with `getmetatable(frame) == hs.getObjectMetatable('hs.geometry')`

For what it's worth: `hs.getObjectMetatable` seems to only work for modules that put their metatables into the [registry][], which currently means just the ones that are implemented in native code/Objective-C. `hs.geometry` is written in pure Lua and doesn't register itself, so `hs.getObjectMetatable('hs.geometry')` just returns `nil`. However, `hs.geometry` actually [uses the module itself][] as the metatable, so you can instead do `getmetatable(frame) == hs.geometry`. I don't know if that fact is considered 'public API' though, so if you'd prefer, you can do:
```lua
local geometryMT = getmetatable(hs.geometry '0x0')
if getmetatable(frame) == geometryMT then
	-- …
end
```

[registry]: https://www.lua.org/manual/5.4/manual.html#4.3
[uses the module itself]: https://github.com/Hammerspoon/hammerspoon/blob/3512c308ad6ed905daeda2bd2fe2a21abf944a5e/extensions/geometry/geometry.lua#L139

**Comment by asmagill** [comment]
FWIW, lua only code can add its metatable to the registry so `hs.getObjectMetatable` works with the following code:

~~~lua
debug.getregistry()[userdata_tag] = metatable
~~~

Then, `hs.getObjectMetatable(userdata_tag)` will work; it also means that we can assign the metatable from C/Swift side code, even though the metatable is pure lua code.
