### ISSUE TITLE
Modifiers not working on Remote desktop

### ISSUE THREAD

**Issue by maxsnts** [Hammerspoon/hammerspoon#3547]
Hi, sorry to reopen this topic, but there is something particular about hammerspoon + Remote desktop

Simple example

hs.hotkey.new("", "\\",
      function() hs.eventtap.keyStroke("", "x", 0) end,
nil, function() hs.eventtap.keyStroke("", "x", 0) end)

hs.hotkey.new("shift", "\\",
      function() hs.eventtap.keyStroke("shift", "x", 0) end,
nil, function() hs.eventtap.keyStroke("shift", "x", 0) end)

If i set these to hotkeys (as an example)

If accessing windows in a Parallels Virtual Machine
- Without modifier does work, pressing "\" i get a "x" (lowercase)
- With modifier does work, pressing "shift+\" i still get a "X" (uppercase)

If accessing windows using Remote Desktop
- Without modifier does work, pressing "\" i get a "x" (lowercase)
- The modifier does not work, pressing "shift+\" i still get a "x" (lowercase)

Thank you

**Comment by latenitefilms** [comment]
Ummm... with `hs.eventtap.keyStroke(modifiers, character[, delay, application])`, the `modifiers` should be a table of modifiers.

See: http://www.hammerspoon.org/docs/hs.eventtap.html#keyStroke

For example, to press SHIFT+X, you would do:

```lua
hs.eventtap.keyStroke({"shift"}, "x", 0)
```

I know we had to do some tricks to make keyboard shortcuts work with some non-native macOS UI's, such as Blender:

https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/shortcuts/actions.lua

**Comment by maxsnts** [comment]
Hi. Thank you for your reply.

I have chosen string because i read in the docs somewhere that it could be a table or a string.
I now changed to table, unfortunately using table has the same result.

Thank you anyway.

**Comment by latenitefilms** [comment]
Maybe try using this instead:

https://github.com/CommandPost/CommandPost/blob/c423ec8856beea468e276a15ed4d6739314c9da8/src/extensions/cp/tools/init.lua#L280

**Comment by maxsnts** [comment]
I have found no solution. I give up.
I will just use RDP using a VM.
