### ISSUE TITLE
Any way to swap caps to ctrl?

### ISSUE THREAD

**Issue by PeterChen1997** [Hammerspoon/hammerspoon#3549]
Hello, I want to swap caps to ctrl and add shortcut: ctrl+hjkl to arrows

If there is a way to config it? Many thx !!

**Comment by muescha** [comment]
1) CAPS -> [Karabiner Elements](https://karabiner-elements.pqrs.org/) best and easy solution
2) VIM Arrows:
- Full VimMode -> https://github.com/dbalatero/VimMode.spoon
- or just the hjkl: https://gist.github.com/mykolaharmash/51846c538c5703de67ad15e6e3109ba0#file-init-lua-L27-L30

**Comment by muescha** [comment]
event listener solution from @asmagill:
- cmd as modifier: https://github.com/S1ngS1ng/HammerSpoon/blob/master/vim-binding.lua#L19
- fn as modifier: https://github.com/asmagill/hammerspoon-config-take2/blob/master/utils/_keys/vikeys.lua#L19

**Comment by muescha** [comment]
FnMate:
- https://github.com/ashfinal/awesome-hammerspoon/blob/master/Spoons/FnMate.spoon/init.lua
init with `hs.loadSpoon("FnMate")`

**Comment by PeterChen1997** [comment]
Thx very much! Karabiner Elements doesn't work any more in newest MacOS. That's why I am finding something nice instead!

**Comment by muescha** [comment]
Hammerspoon also not solve this by itself (see #510)

The problem of Karabiner Elements with Somona is filed here https://github.com/pqrs-org/Karabiner-Elements/issues/3620 - maybe a solution is provided there.

**Comment by muescha** [comment]
in this thread someone mentioned hdutil for mapping: https://www.reddit.com/r/hammerspoon/comments/wcz9jb/hyper_key_without_karabiner/

**Comment by PeterChen1997** [comment]
> in this thread someone mentioned hdutil for mapping: https://www.reddit.com/r/hammerspoon/comments/wcz9jb/hyper_key_without_karabiner/
> 
> also someone described there this way:
> 
> > This works by remapping caps lock to control in system preferences->keyboard->modifier keys first.

yeps, I did the same thing! That works perfect, thx for reply!
