### ISSUE TITLE
suspected memory leak

### ISSUE THREAD

**Issue by WDayu** [Hammerspoon/hammerspoon#3552]
## Bug

I'm not sophisticated enough in the field of program development so I can't assert it's a bug, but what happened in my Mac was so bad that I had to define this issue as a bug

## description

Once Hammerspoon is launched, the amount of computer memory it occupies rises dramatically over the next day, from a dozen megabytes at the beginning to even 1GB. 

The following is some picture of the description.

<img width="422" alt="iShot_2023-10-20_14 17 27" src="https://github.com/Hammerspoon/hammerspoon/assets/142883298/19ec3d24-e400-4280-9481-74cd817519d8">
<img width="420" alt="iShot_2023-10-22_14 06 04" src="https://github.com/Hammerspoon/hammerspoon/assets/142883298/9e748c17-0ed1-411d-9971-823ea472511c">

## reproducing
Without any extra operation, a large number of memory will be occupied.

## solution

Actually I don't know how to fix this issue, my own solution is set up a shell script to restart hammerspoon every morning.

**Comment by latenitefilms** [comment]
Can you share your Lua Script, or a list of what extensions you're using? It's hard to tell if it's a memory leak, or something in your Lua code that's actually using up memory. Does "reloading" in Hammerspoon release the memory? If so, it's most likely in your Lua code.

**Comment by WDayu** [comment]
> Can you share your Lua Script, or a list of what extensions you're using? It's hard to tell if it's a memory leak, or something in your Lua code that's actually using up memory. Does "reloading" in Hammerspoon release the memory? If so, it's most likely in your Lua code.

Thanks for your attention, I should have attached my Lua Script in the description of this Issue, but due to some problems I have not. My Lua Script is completely a copy of [this open source code](https://github.com/KURANADO2/hammerspoon-kuranado).

**Comment by latenitefilms** [comment]
That GitHub repo uses a lot of different Hammerspoon Extensions.

What modules are you using from that GitHub Repo? 

Are there any clues in the Error Log?

**Comment by WDayu** [comment]
> That GitHub repo uses a lot of different Hammerspoon Extensions.
> 
> What modules are you using from that GitHub Repo?
> 
> Are there any clues in the Error Log?

When I was a newbie in hammerspoon, I didn't pay that much attention to what are extensions the configuration used, I just simply cloned his entire repository and used it according to the readme.

From the hammerspoon console, I can find the following  loaded extensions: menubar, window, hotkey, fnutils, canvas, chooser, eventtap, network, styledtext, image, pathwatcher, timer, mouse, application, geometry, screen.

I didn't find any errors in the console logs, and theoretically, once an error appears, the program should crash, right? However, the program runs very smoothly on my computer, the only downside being that it consumes an incredible amount of memory.

**Comment by latenitefilms** [comment]
Does reloading Hammerspoon (as opposed to quitting and reopening) release the memory?

**Comment by WDayu** [comment]
> Does reloading Hammerspoon (as opposed to quitting and reopening) release the memory?

According to my experiment, the occupied memory will not be released when reload Hammerspoon config, but quitting and reopening will be ok.

**Comment by muescha** [comment]
In my case there was a 4GB memory usage. Closing Hammerspoon and restart set the memory back to normal. But it is increasing ... it was 100MB, now 169MB

**Comment by WG-sss** [comment]
Fine, eventually I settled this problem.

I just deleted some of the useless Lua script modules, then the usage memory kept in about 50MB during the past two days.

I don't know why, and I am not so familiar with the Hammerspoon project that I can't locate the reason why it happens.

**Comment by WDayu** [comment]
Well, eventually I settled this problem.

I just removed some of the useless Lua scripting modules and then the memory usage was kept in about 50MB during the past two days.

I don't know why, and I'm not so familiar with the Hammerspoon project that I can't find out why it happened.
