### ISSUE TITLE
New revision of Stream Deck XL with a new PID not supported

### ISSUE THREAD

**Issue by priitohlo** [Hammerspoon/hammerspoon#3553]
It seems that my new Stream Deck XL has a new PID, which as per streamdeck.h is currently not supported by Hammerspoon.
Output from hidapitester:
`0FD9/008F: Elgato - Stream Deck XL`

Please add support for the new revision. I am happy to test it out if needed.

**Comment by latenitefilms** [comment]
@priitohlo - Apologies for the very delayed reply! Untested, but this should fix hopefully your issue.
