### ISSUE TITLE
Various small questions about the hs.wifi module

### ISSUE THREAD

**Issue by 0x0-00** [Hammerspoon/hammerspoon#3554]
1、hs.wifi.watcher.new will repeat the callback function 2-3 times after listening to a wifi switch, after specifying the event message as SSIDChange, it will still repeat.
2、hs.wifi.availableNetworks() repeatedly obtains the available networks. Only one of these duplicate networks is available and can be used in conjunction with hs.chooser to replace the wifi network.
3、Listeners such as hs.wifi.watcher will fail when the system is unsleeping, reloading the configuration or restarting hammerspoon can fix this, but this is too much of a hassle to do, does the software itself support the system waking up the listener to re-run it, and hs.pathwatcher fails even if the system isn't hibernating.

besides the subject matter ——>

With macOS tightening system permissions, today's Mac apps come with a list of system-authorized features with text descriptions for easy troubleshooting. For example, with the new "Security" option in "Settings", could hs add this option as well, now to get the SSID of the wifi you have to add print(hs.location.get()) at the top of the config file in order to check the hs in the system's location services, if the hs itself supports checking of these permissions I'd be able to delete this line of code, that's great!

**Comment by 0x0-00** [comment]
hs.wifi.watcher often fails, the wifi toggle callback function does not execute correctly, and the only way to make it work is to repeatedly reload the configuration file, which executes correctly.

**Comment by latenitefilms** [comment]
Are you capturing your watcher is a global variable? I haven't dug too deep into this, but could it be a garbage collection issue?

**Comment by 0x0-00** [comment]
<img width="494" alt="截屏2023-11-02 12 11 18" src="https://github.com/Hammerspoon/hammerspoon/assets/49114841/48fa10b9-0145-4eb7-bd49-e6accce66121">
I started it directly.
This is also the case with hs.pathwatcher, when I change the config file and save it, it doesn't execute the code in the callback function correctly, manually reloading the config file gets it working for a while, but eventually it fails.

**Comment by latenitefilms** [comment]
Try capturing it in a global:

```lua
watcher = hs.wifi.watcher.new(...)
```

**Comment by 0x0-00** [comment]
Thank you very much for solving this problem. Maybe I should re-read the documentation, it was a really low-level mistake.
 I have two more questions for ----> 
1. hs.wifi.watcher.new() only monitors "SSIDChange" by default, but when I change wifi, it executes the callback function 3 times, what usually causes this? 
2. <img width="637" alt="截屏2023-11-03 13 15 20" src="https://github.com/Hammerspoon/hammerspoon/assets/49114841/cdb8418c-0a66-4df1-b882-4dff1498073e">
There are many duplicate networks in the list of available WiFi networks obtained by hs.wifi.availableNetworks(). Only one of them can be used with hs.chooser and hs.wifi.associate to change the network, how to solve this problem?

**Comment by cmsj** [comment]
When the SSID changes you get a callback for every state change: oldSSID->disconnected, disconnected->newSSID. I'm not sure what the third one you're seeing is, but the callback's parameters should help you narrow it down.

Multiple SSIDs in `availableNetworks()`likely relates to multiple access points.
