### ISSUE TITLE
Tucking Apps

### ISSUE THREAD

**Issue by AjayShanker-geek** [Hammerspoon/hammerspoon#3571]
I am pretty new to hammerspoon and would like to create method to tuck my apps like:

- Telegram
- Slack
- WhatsApp

My plan is ensure that all three apps follow to all my spaces and pop out on keybinding for productivity. Would like to ask if it is possible with hammerspoon. My current setup uses yabai + shkd.

**Comment by cmsj** [comment]
I'm not sure what tucking is, but I'm guessing it would be hiding the windows somehow?

You can [hide](http://www.hammerspoon.org/docs/hs.application.html#hidehttp://www.hammerspoon.org/docs/hs.application.html#hide)/[unhide](http://www.hammerspoon.org/docs/hs.application.html#unhide) apps, or you could [move](http://www.hammerspoon.org/docs/hs.window.html#move) them to the very edge of the screen so they're not visible.
