### ISSUE TITLE
switcher.ui.highlight rounded corners?

### ISSUE THREAD

**Issue by R-7200** [Hammerspoon/hammerspoon#3572]
Good evening!

Is it possible to include rounded corners for switcher.ui.highlight? Right now I'm stuck with the following appearance:

![Bildschirmfoto 2023-12-16 um 17 51 07](https://github.com/Hammerspoon/hammerspoon/assets/138106707/8a62a0a7-0d83-4db4-9048-ec1f49174399)

I'd be glad about mentioned improvement - have a nice weekend, all of you :-)

Best regards.

**Comment by Rhys-T** [comment]
It doesn't look like there's currently any official way to make those corners rounded, but it could probably be added.

As a workaround for now, if you're okay poking around inside `hs.window.switcher`'s implementation details, you can get the [`hs.drawing`][] object being used to draw the highlight rectangle and set its corner radius manually using the [`setRoundedRectRadii`][] method:

```lua
ws = hs.window.switcher.new( --[[ whatever arguments ]] )
-- any ws.ui configuration goes here
local highlightRadius = 10 -- or whatever
ws.drawings.highlightRect:setRoundedRectRadii(highlightRadius, highlightRadius)
```

Make sure you finish modifying that switcher's `ui` object before you set the radius. Any changes to `ws.ui` will cause the highlight drawing to be recreated and lose that change. (Changes to the global `hs.window.switcher.ui` object won't do that, but they also won't properly update switchers you've already created.)

<details><summary>If you want to avoid losing the radius whenever you change `ws.ui`…</summary>

It's possible, but requires messing with `hs.window.switcher`'s internals even more using Lua's [`debug`][] functions:

```lua
local function findUpvalue(f, name)
	local i = 0
	local n, v
	repeat
		i = i + 1
		n, v = debug.getupvalue(f, i)
	until not n or n == name
	if not n then return nil end
	return i, v
end

local setUiPrefsUpvalueIndex, oldSetUiPrefs = findUpvalue(hs.window.switcher.new, 'setUiPrefs')
if not setUiPrefsUpvalueIndex then
	error "Couldn't find hs.window.switcher's setUiPrefs function"
end
debug.setupvalue(hs.window.switcher.new, setUiPrefsUpvalueIndex, function(self)
	oldSetUiPrefs(self)
	local highlightRadius = self.ui.highlightRadius or 0
	self.drawings.highlightRect:setRoundedRectRadii(highlightRadius, highlightRadius)
end)

-- Now you can do:
hs.window.switcher.ui.highlightRadius = 10 -- or whatever
ws = hs.window.switcher.new( --[[ whatever arguments ]] )

-- or for a specific switcher:
ws.ui.highlightRadius = 15 -- or whatever
```

</details>

<details><summary>If you want to make it match the size of the existing rounded corners…</summary>

There are three radii that are computed and used by `hs.window.switcher`, so it depends which one you're trying to match:

- `ui.titleRectRadius`: Used for the window titles in the main switcher area. [Defined](https://github.com/Hammerspoon/hammerspoon/blob/0.9.100/extensions/window/window_switcher.lua#L357) as 1/4 of `ui.textSize` (which defaults to 16, making this radius 4).
- `selectedRectRadius`: Used for the large preview box for the selected window, as well as the title box at the top of that preview. [Defined](https://github.com/Hammerspoon/hammerspoon/blob/0.9.100/extensions/window/window_switcher.lua#L360-L365) as 1/4 of the height of an uppercase `O` in the selected-window title font (with the odd effect of not rounding those corners if you turn that title off). With default settings, that seems to work out to 8.
- `padding`: Used for the corners of the switcher itself. Also has some non-corner-radius uses: It's the amount of space between two thumbnails, or between the first/last thumbnail and the corresponding edge of the switcher. [Defined](https://github.com/Hammerspoon/hammerspoon/blob/0.9.100/extensions/window/window_switcher.lua#L117-L119) in a complicated way based on `ui.thumbnailSize`, the number of windows, and the available screen width. If you're trying to match the switcher's corners, it will probably take a more involved patch to actually find that value.

</details>

[`hs.drawing`]: https://www.hammerspoon.org/docs/hs.drawing.html
[`setRoundedRectRadii`]: https://www.hammerspoon.org/docs/hs.drawing.html#setRoundedRectRadii
[`debug`]: https://www.lua.org/manual/5.4/manual.html#6.10

**Comment by R-7200** [comment]
Hi!

Works as described :-) I mistook

`switcher = hs.window.switcher.new()`

for switcher.ui.highlight.

Thank you for clarifying; marked as solved!

Have a nice day!
