### ISSUE TITLE
obscure hs.hotkey.modal error with first bound key's repeat function

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#358]
Switching back temporarily from my WIP eventap based hotkey to determine if random temporary key lockup is due to my code or something else, and I discovered something else very odd with hs,hotkey (the one currently in core)...

If you have a modal key setup, something like:

~~~
test = hs.hotkey.modal.new({"cmd","alt","ctrl"},"f")
function test:entered() hs.alert.show("entered modal mode") end
test:bind({"cmd"},"c", function() print("cmd-c down") end, nil, function() print("cmd-c repeat") end)
test:bind({},"escape", function() test:exit() end)
function test:exited() hs.alert.show("exiting modal mode") end
~~~

Now, using the core hs.hotkey, if you enter the modal mode by hitting the `cmd-alt-ctrl f`, the repeat function for the first bound key gets repeatedly triggered after test:entered() is executed.  Without pressing any key at all.  Press any key, and this repeating stops, but...

Exit and re-enter the modal -- it starts up again.

I doubt the specific modifiers matter -- the specific keys don't -- but this is pretty close to the code I'm using that brought this to my attention.  And if the repeat function for the first binding is nil, then this doesn't happen (or maybe it does, but being nil, has no visible effect.)

I don't know the hs.hotkey repeat code at all, so I throw this out in case someone has an "A-Ha!" thought... otherwise, I'll look into it tomorrow.

**Comment by asmagill** [comment]
Best guess is that it's occurring because the hotkey repeat timer is started for *EVERY* keypressed event, even if no repeat function is provided (well, technically it is, because the hs.hotkey.new wraps the functions so that even nil ends up being an empty function (i.e. essentially `function() end`) -- not a good design in my opinion because it means that Lua will be invoked at least twice and usually more often for every single hotkey pressed, even if it's only actually doing something for a single keydown or keyup .)

Now, throw in modal, and the keypressed event calls self:enter() which disables the hotkey *before the keyreleased event can ever be processed*, so there is never a corresponding stop of the repeat timer.

I'm still not sure why it seems to pick the first bound key's repeat function, other than this is the very first new one enabled during self:enter()... unless I'm missing something, the eventUID being passed around by the timer should still be pointing to the object with the function references from the now-disabled modal key...

**Comment by asmagill** [comment]
Further musing, we kind of need to fire the timer in any case, just to make sure to eat future keyPressed events for the same key, or at least record it somehow... but it's still wasteful to bother invoking lua_pcall for an empty function.  And that gets me no closer to knowing why it picks what it does to repeat...

**Comment by cmsj** [comment]
@asmagill yes, I hate the way the callback wrappers work in hs.hotkey.

**Comment by cmsj** [comment]
@asmagill so, I'm also puzzled why that particular repeat function is getting called, but if we invalidate the repeat timer in :disable() then it ought to stop being an issue

**Comment by cmsj** [comment]
oh, derp, we already do that

**Comment by cmsj** [comment]
@asmagill not directly relevant here, but I just pushed abe54ba (with minimal testing only, I should note) which switches the callbacks to be non-wrapped.

I doubt this will help with this bug, but what I would suggest trying, is uncommenting all the CLS_NSLOG calls in extensions/hotkey/internal.m. They give a fairly good overview of what is happening under the hood, wrt repeats.

**Comment by asmagill** [comment]
I'll look at it... wrt to the eventtap model I've been working on, while I think it's a stronger model in the long run, it currently suffers from invoking lua too often (for every single keypress everywhere, actually, though I return as soon as I confirm we don't care about it) -- the overhead is causing an inordinate number of disabled due to timeout events... Ultimately I think I'm going to end up merging the two, but still using the official event tap calls, rather than the not-quite-but-almost-deprecated-and-definately-recommended-against RegisterEventHotKey, so ultimately fixes in this one will likely help in mine.

**Comment by asmagill** [comment]
Ok, I don't have a clean fix yet, but I think I know what is happening...

As stated above, the timer is started for the modal hotkey... during the callback of the modal hotkey, the modal key itself is disabled, removing it from the registry, immediately followed by enabling all of the other keys -- putting them into the registry that just had a slot freed up -- it gets reused, thus having the same identifier as the modals hotkey.

Ticks pass, the timer gets sprung, looks for the registry entry it was started with -- finds it, and this one has a registered repeatFn.

It would be ideal to forgo the timer completely if the key doesn't have a repeatFn defined... The only thing I can think of that this would lose is allowing a key's pressed function add a repeat function based upon its own internal logic after the fact.  But in my mind, that logic belongs in the repeat function which can simply return rather than do something based upon its internal logic anyways, so I'm not sure it's really a loss.

I'll see how hard that would be to implement.

**Comment by asmagill** [comment]
think I have it fixed... I'll issue a pull request shortly

**Comment by cmsj** [comment]
Awesome work! Good catch with the lua refs!
