### ISSUE TITLE
`app:hide()` not work for some specific apps and always returns `false`

### ISSUE THREAD

**Issue by keidarcy** [Hammerspoon/hammerspoon#3580]
Chrome works fine with `app:hide()` but [ARC](https://arc.net/) not and `app.hide()` always returns `false` even `hide()` worked.

```
local log = hs.logger.new("toggle-me", "debug")
bundleId = "com.google.Chrome"
// bundleId = "company.thebrowser.Browser"
local app = hs.application.find("com.google.Chrome")
if app:isFrontmost() then
  local h = app:hide()
  log.i(h) // alway false
end
```

I'm binding `cmd+h` for `arc` as a workaround.

I have [accessibility](https://support.apple.com/guide/mac-help/allow-accessibility-apps-to-access-your-mac-mh43185/mac#:~:text=To%20review%20app%20permissions%E2%80%94for,any%20app%20in%20the%20list.) enabled.

More details in my runnning script: [hide](https://github.com/keidarcy/dotfiles/blob/master/hammerspoon/.hammerspoon/toggle-me.lua#L21-L22),[bind cmd + h](https://github.com/keidarcy/dotfiles/blob/master/hammerspoon/.hammerspoon/app-keybinding.lua#L39-L41)

**Comment by theutz** [comment]
I found a quick-and-dirty workaround:

```lua
local name
if app and app.name then
  name = app.name
elseif type(app) == "string" then
  name = app
end
if name then curr:selectMenuItem("Hide " .. name) end
```

**Comment by gandhiShepard** [comment]
I have the same problem. This works for all apps except ARC

```lua
hs.hotkey.bind({"cmd", "alt"}, "a", function()
  local arc = hs.application.find("arc")
  if arc:isFrontmost() then
    arc:hide()
  else
    hs.application.launchOrFocus("/Applications/Arc.app")
  end
end)
```

**Comment by eddyg** [comment]
Came here to report the same problem and found this issue.

For now, I'm special-casing **Arc** in my `openOrHideOrShowApp` key-handler function and calling `selectMenuItem` instead of `hide` when `isFrontmost` is Arc (just like @theutz suggested above).

Any idea what's "special" about **Arc**?

**Comment by cmsj** [comment]
ARC likely isn't properly implementing Accessibility, which is the interface by which we're able to hide/unhide apps. That being the case, there isn't much we can do about it other than add workarounds in configs like those shown here.
