### ISSUE TITLE
[FR] Add the ability to customize the repeat rate for `repeatfn` per hotkey

### ISSUE THREAD

**Issue by NightMachinery** [Hammerspoon/hammerspoon#3587]
I like some of my hotkeys to repeat fast, and some slow. I believe there needs to be two settings exposed: the initial delay to start the repeat timer, and the delay between each repeat.

Related:
- https://github.com/Hammerspoon/hammerspoon/issues/1216
- https://github.com/Hammerspoon/hammerspoon/issues/1211

**Comment by cmsj** [comment]
I don't think we can really address this unfortunately - the repeat information comes from the default macOS setting for key repeats. We'd have to completely change to using EventTap for all hotkeys, which is not something I think we want to do.
