### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by pkieltyka** [Hammerspoon/hammerspoon#3588]
hi all, seems there are many nice commits in master, and the last release was in March 2023 -- I was wondering if there is a plan to make another release in Q1/2024 ...?

**Comment by latenitefilms** [comment]
Yes, I’d say there’ll definitely be an update at some point early this year! @cmsj ?

**Comment by proofer** [comment]
Perhaps not in the first 1/3 of the year...

**Comment by cmsj** [comment]
Slightly later than hoped, but we released 1.0.0 yesterday :)
