### ISSUE TITLE
Repeatable hotkey keeps repeating when the callback function lasts too long

### ISSUE THREAD

**Issue by avegetablechicken** [Hammerspoon/hammerspoon#3589]
```lua
local callback = function()
  hs.application.get("com.apple.finder"):selectMenuItem({ 'Window', 'Show Next Tab' })
end
hs.hotkey.bind("⇧⌘", "]", callback, nil, callback)
```
It is quite naive a keybinding configuration and it works well. That is, when I release the key ']' after continuously pressing it for a long time, the hotkey stops immediately as expected.
But when I call `hs.timer.usleep` in the `callback` function to simulate a callback lasting long and keep pressing the hotkey, it will never stop after I release the key.
```lua
local callback = function()
  hs.timer.usleep(500000)
  hs.application.get("com.apple.finder"):selectMenuItem({ 'Window', 'Show Next Tab' })
end
hs.hotkey.bind("⇧⌘", "]", callback, nil, callback)
```
Worse still, if the callback really costs a long time, just pressing the hotkey once will be enough to bring about annoying results as described above. Here is one example:
```lua
local function VSCodeToggleSideBarSection(sidebar, section)
  local focusedWindow = hs.application.frontmostApplication():focusedWindow()
  if focusedWindow == nil then return end
  local commonPath = [[group 2 of group 1 of group 2 of group 2 of ¬
    group 1 of group 1 of group 1 of group 1 of UI element 1 of ¬
    group 1 of group 1 of group 1 of UI element 1]]
  local commonPathOld = [[group 2 of group 1 of group 2 of group 2 of ¬
    group 1 of group 1 of group 1 of group 1 of UI element 1]]
  local sidebarAction = [[
    set tabs to radio buttons of tab group 1 of group 1 of group 1 of ¬
        %s
    repeat with tab in tabs
      if title of tab starts with "]] .. sidebar .. [["  ¬
          or value of attribute "AXDescription" of tab starts with "]] .. sidebar .. [[" then
        perform action 1 of tab
        exit repeat
      end if
    end repeat
    delay 0.1
  ]]
  local sectionExpand = [[
    set sections to every group of group 2 of group 1 of group 2 of group 2 of ¬
          %s
      repeat with sec in sections
        if title of UI element 2 of button 1 of group 1 of sec is "]] .. section .. [[" then
          if (count value of attribute "AXChildren" of group 1 of sec) is 1 then
            perform action 1 of button 1 of group 1 of sec
          end if
          exit repeat
        end if
      end repeat
  ]]
  local sectionFold = [[
    set sections to every group of group 2 of group 1 of group 2 of group 2 of ¬
          %s
      repeat with sec in sections
        if title of UI element 2 of button 1 of group 1 of sec is "]] .. section .. [[" then
          perform action 1 of button 1 of group 1 of sec
          exit repeat
        end if
      end repeat
  ]]
  hs.osascript.applescript([[
    tell application "System Events"
      tell window 1 of (first application process whose bundle identifier is "com.microsoft.VSCode")
        if (exists UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPath .. [[) ¬
            and (title of UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPath .. [[ ¬
              starts with "]] .. sidebar .. [[") then
          ]] .. string.format(sectionFold, commonPath) .. [[
        else if (exists UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPathOld .. [[) ¬
            and (title of UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPathOld .. [[ ¬
              starts with "]] .. sidebar .. [[") then
          ]] .. string.format(sectionFold, commonPathOld) .. [[
        else if (not exists ]] .. commonPath .. [[) ¬
            or (title of UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPath .. [[ ¬
              does not start with "]] .. sidebar .. [[") then
          ]] .. string.format(sidebarAction, commonPath) .. [[
          ]] .. string.format(sectionExpand, commonPath) .. [[
        else if (not exists ]] .. commonPathOld .. [[) ¬
            or (title of UI element 1 of group 1 of group 1 of group 2 of ¬
              ]] .. commonPathOld .. [[ ¬
              does not start with "]] .. sidebar .. [[") then
          ]] .. string.format(sidebarAction, commonPathOld) .. [[
          ]] .. string.format(sectionExpand, commonPathOld) .. [[
        end if
      end tell
    end tell
  ]])
end
local callback = hs.fnutils.partial(VSCodeToggleSideBarSection, "EXPLORER", "OUTLINE")
hs.hotkey.bind('⌘', '7', callback, nil, callback)
```
Any way to fix it?

**Comment by avegetablechicken** [comment]
Adding a wrapper as below may work as a workaround:
```lua
local callback = function()
  hs.timer.doAfter(0, actualCallBack)
end
```
It works for the 'pressing the hotkey once' situation, preventing the hotkey from being triggered again and again. Instead, the hotkey may be triggered once or twice on my mac.
But it does not work for the`keeping pressing the hotkey` situation.

**Comment by Rhys-T** [comment]
This sounds like it might be the same issue as #1178. I've done some research into what's causing it in <https://github.com/Hammerspoon/hammerspoon/issues/3584#issuecomment-1890769365>. The short version is that Hammerspoon is faking key repeat for hotkeys internally using NSTimers, and if the 'pressed' callback calls something like `hs.osascript` that runs the event loop, the 'released' event can be received in the middle of handling the 'pressed' one and ends up confusing those timers.[^ax]

Assuming that's actually what you're running into, that workaround you posted _should_ be working, although you might want to modify it a bit to make sure there's no chance of [the timer returned by `doAfter` getting garbage-collected](https://github.com/Hammerspoon/hammerspoon/discussions/3441):
```lua
local callback = function()
  local timer
  timer = hs.timer.doAfter(0, function()
    timer = nil
    actualCallBack()
  end)
end
```
I'm not quite sure why it's not working for long 'repeat' callbacks for you, though. I can't seem to replicate it with a basic example like:
```lua
local function f()
	print 'repeat function begin'
	hs.osascript.applescript 'delay 1'
	print 'repeat function end'
end
hs.hotkey.bind('ctrl', 't', function()
	print 'pressed function'
end, nil, function()
	local timer
	timer = hs.timer.doAfter(0, function()
		timer = nil
		f()
	end)
end)
```
I just see all the 'end' messages being delayed until the final AppleScript has finished.

---

As a side note, if you're just trying to change the keyboard shortcuts for things like 'Show Next Tab', you can actually configure them in System Settings/System Preferences, under the 'Keyboard' section. [Here's Apple's documentation on that feature.](https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/14.0/mac/14.0)

[^ax]: I'm not sure about `selectMenuItem`, though. That uses the Accessibility API rather than AppleScript, and while I wouldn't be too surprised to see it running the event loop and triggering the same issue, I can't seem to replicate it here. But I'm currently stuck on older versions of both macOS and Hammerspoon, and it's possible that something has changed since then.

**Comment by avegetablechicken** [comment]
> This sounds like it might be the same issue as #1178. I've done some research into what's causing it in [#3584 (comment)](https://github.com/Hammerspoon/hammerspoon/issues/3584#issuecomment-1890769365). The short version is that Hammerspoon is faking key repeat for hotkeys internally using NSTimers, and if the 'pressed' callback calls something like `hs.osascript` that runs the event loop, the 'released' event can be received in the middle of handling the 'pressed' one and ends up confusing those timers.[1](#user-content-fn-ax-5347ab28d3256a3b90bf90f15ae298fb)
> 
> Assuming that's actually what you're running into, that workaround you posted _should_ be working, although you might want to modify it a bit to make sure there's no chance of [the timer returned by `doAfter` getting garbage-collected](https://github.com/Hammerspoon/hammerspoon/discussions/3441):
> 
> ```lua
> local callback = function()
>   local timer
>   timer = hs.timer.doAfter(0, function()
>     timer = nil
>     actualCallBack()
>   end)
> end
> ```
> 
> I'm not quite sure why it's not working for long 'repeat' callbacks for you, though. I can't seem to replicate it with a basic example like:
> 
> ```lua
> local function f()
> 	print 'repeat function begin'
> 	hs.osascript.applescript 'delay 1'
> 	print 'repeat function end'
> end
> hs.hotkey.bind('ctrl', 't', function()
> 	print 'pressed function'
> end, nil, function()
> 	local timer
> 	timer = hs.timer.doAfter(0, function()
> 		timer = nil
> 		f()
> 	end)
> end)
> ```
> 
> I just see all the 'end' messages being delayed until the final AppleScript has finished.
> 
> As a side note, if you're just trying to change the keyboard shortcuts for things like 'Show Next Tab', you can actually configure them in System Settings/System Preferences, under the 'Keyboard' section. [Here's Apple's documentation on that feature.](https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/14.0/mac/14.0)
> 
> ## Footnotes
> 1. I'm not sure about `selectMenuItem`, though. That uses the Accessibility API rather than AppleScript, and while I wouldn't be too surprised to see it running the event loop and triggering the same issue, I can't seem to replicate it here. But I'm currently stuck on older versions of both macOS and Hammerspoon, and it's possible that something has changed since then. [↩](#user-content-fnref-ax-5347ab28d3256a3b90bf90f15ae298fb)

Thanks a lot!
