### ISSUE TITLE
Shift agruments in `hotkey.new`

### ISSUE THREAD

**Issue by minhtung0404** [Hammerspoon/hammerspoon#3604]
If I understand correctly, if I put explicitly `message = nil` in the function call then it still shift the arguments, which might lead to unexpected behavior. For example if I call `hotkey:bind(mods, key, nil, f1, f2, f3)`, it shift `pressedfn` to nil, `releasedfn` to f1 and `repeatfn` to f2.

```lua
  if message==nil or getFunc(message) then
    repeatfn=releasedfn releasedfn=pressedfn pressedfn=message message=nil -- shift down arguments
  end
```
[link to code](https://github.com/Hammerspoon/hammerspoon/blame/56b5835dc1bf7bb430dfea3f1662379cccec0c82/extensions/hotkey/hotkey.lua#L218)

**Comment by cmsj** [comment]
Unfortunately this is probably not fixable at this point - it's a limitation of the way we chose to do optional arguments, and limitations in Lua for not supporting named arguments.

When the docs say "omitted", they mean literally not passing anything as the message, so by that reasoning, there shouldn't ever be a need to pass `nil`.

I agree it's ugly, but I think we're stuck with it after so many years :(
