### ISSUE TITLE
Delete Preferences modal is confusing

### ISSUE THREAD

**Issue by hofstee** [Hammerspoon/hammerspoon#3612]
I unknowingly opened Hammerspoon while trying to open Force Quit Applications, which led to the "Do you want to delete the preferences?" window popping up. The options presented are `Continue` and `Delete Preferences`, which both feel like they will delete the preferences. 

How about renaming `Continue` to `Cancel` instead (which should also allow pressing `Esc` to get out of this unwanted situation)? Maybe also potentially marking the `Delete Preferences` button with `hasDestructiveAction` since I notice the minimum macOS version is 11.0 now.

https://github.com/Hammerspoon/hammerspoon/blob/56b5835dc1bf7bb430dfea3f1662379cccec0c82/Hammerspoon/MJAppDelegate.m#L139-L144

![modal dialog](https://github.com/Hammerspoon/hammerspoon/assets/5227572/4dbbb070-7daa-4f01-b687-b7d27bf2eb4b)

**Comment by cmsj** [comment]
Thanks, this was really good feedback and will be addressed in the next release!
<img width="281" alt="Screenshot 2024-08-05 at 16 51 58" src="https://github.com/user-attachments/assets/4cc289e9-7b6a-47b8-9e9a-b58a2ca5c196">
