### ISSUE TITLE
eventtap question

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#362]
Making some changes to eventtap that I *think* will allow us to capture system events (special function keys, basic trackpad gestures -- nothing too complex, but some, etc.) and have a question regarding event types kCGEventTapDisabledByTimeout and kCGEventTapDisabledByUserInput.

The Timeout one is basically the OS's way of notifying the event tap that it thinks it is too slow... and the only way I've ever triggered the UserInput one was due to buggy Obj-C code which turned off the event tap without invalidating it's port and removing it from the runloop... not sure what else might trigger it, but I haven't been able to find out about it online and I definitely haven't been able to trigger it from Lua or within the console.

I'm leaning towards just capturing them in the Obj-C part of the callback and re-enabling the eventtap silently without bothering Lua with the callback -- it couldn't do anything other than re-enable the eventtap anyways -- the event carries no other information.  I'd also remove them from the types list in event.m, but how many people use/know about them anyways?

Obviously log this via CLS_NSLOG, but should it also print this to the Hammerspoon console?  Since a slow callback function will definitely trigger kCGEventTapDisabledByTimeout, it could be useful for debugging... on the other hand, low memory pressures or other, non-Hammerspoon-related slowness of your machine can also trigger it and seeing the warning at random intervals might be disconcerting...

Thoughts?

**Comment by cmsj** [comment]
(I'm sure I already replied to this, but github shows no replies. weird)

I agree that silent re-enabling seems sane. Let's start with just a CLS_NSLOG() and see how it goes.

**Comment by cmsj** [comment]
Closing, since the code for this has landed.
