### ISSUE TITLE
A way to prevent hs.alert.show() from stealing focus?

### ISSUE THREAD

**Issue by tino** [Hammerspoon/hammerspoon#3623]
I have an alert that shows me whether my tests that are running in the background are passing or not. However, every time the alert is show, the window I was working in (eg. code editor, or terminal) loses focus, and I have to cmd+tab twice to get it back.

Is there any way from preventing this?

**Comment by dmgerman** [comment]
Save the current window, show the alert and return. Or use hs.alert.show which is non intrusive.

**Comment by cmsj** [comment]
Agreed, hs.alert doesn't steal focus, are you perhaps using something like Stage Manager?
