### ISSUE TITLE
Add functions to hs.mouse to get more information about cursor type

### ISSUE THREAD

**Issue by germanartalejo** [Hammerspoon/hammerspoon#3628]
Hi, I was wondering if it could be possible to get the current cursor’s hotspot, image and image frame. If there’s already a way to get them I couldn’t find it.

Thanks in advance.

**Comment by dmgerman** [comment]
Look at extensions/mouse/libmouse.m

That is the low level mouse code. It looks like it might be easy to add new functionality.  You could add the functions and test them.

See https://developer.apple.com/documentation/appkit/nscursor/1529096-hotspot?language=objc

**Comment by cmsj** [comment]
I think, unfortunately, this isn't going to be possible safely - the required Apple API has been marked as Deprecated in the upcoming macOS 15: https://developer.apple.com/documentation/appkit/nscursor/1533611-currentsystemcursor?language=objc

**Comment by asmagill** [comment]
FWIW, when I experimented with this in the past, it seemed to be limited to getting information and affecting the cursor only when Hammerspoon was active; when it wasn't, most of the information was nil or wrong (didn't change when the cursor did in other applications) so I never really dug into it further. IIRC there were some undocumented functions that gave some cursor info, but they stopped working ages ago.
