### ISSUE TITLE
hs.drawing objects obscure hs.alert

### ISSUE THREAD

**Issue by jasonm23** [Hammerspoon/hammerspoon#364]
alerts now show up behind hs.drawing objects (with their default arrangement.) 

`hs.drawing:sendToBack` will allow the alert to be seen, but the drawing is then behind all the screen objects/windows etc.

I guess alerts should always be on top.

**Comment by cmsj** [comment]
I tend to agree that alerts should always be on top, I tend to think they should always be on top of everything - hs.drawing objects, normal, windows, fullscreen windows, etc. so I'm going to force them to draw at the highest possible level that an NSWindow object can be drawn. They will then only have to fight with other things that are claiming that height.

**Comment by jasonm23** [comment]
Thanks @cmsj
