### ISSUE TITLE
cannot remap SHIFT + §

### ISSUE THREAD

**Issue by mmt1821** [Hammerspoon/hammerspoon#3641]
On a Mac silicon (M3) (Sonoma 14.5) 
Hammerspoon used to allow me to map SHIFT + § to tilde (~) -- yes I have an EU keyboard.

The following code does not seem to do anything anymore:

hs.hotkey.bind({ "shift" }, "§", function() print("TILDE") end)

Any clues?

**Comment by cmsj** [comment]
In general I tend to recommend people use Karabiner to do key remappings, because it's able to operate at a much lower level than Hammerspoon is. Having said that, this seems to be working ok for me:

```
> foo = hs.hotkey.bind({"shift"}, '§', function() print("yo") end)
2024-08-05 16:08:49: 16:08:49     hotkey: Enabled hotkey ⇧§

2024-08-05 16:08:51: yo

> hs.keycodes.currentLayout()
British
```

Do you see the `Enabled hotkey ⇧§` message in your Hammerspoon console?
