### ISSUE TITLE
Wrong screen frame after toggling menubar auto-hide off and on

### ISSUE THREAD

**Issue by sergei-dyshel** [Hammerspoon/hammerspoon#3643]
When moving from setup with external displays (lid closed) to builtin display I'm disabling menubar auto-hide, since the notch doesn't allow maximizing window size anyway. After going back to external displays I'm enabling auto-hide back, but `screen:frame()` still excludes menubar (hence functions like`window:maximize()`  don't work as expected). After some time working ( 10-30 min) I notice that screen frame restores to proper size. 

Hammerspoon 0.9.100, MBP 16' M2 Pro, Sonoma 14.4.1.

**Comment by cmsj** [comment]
I'm tempted to suggest this may be some kind of OS limitation - from consulting our code for `screen:frame()` it doesn't look like we're doing any kind of caching, we just look up the values from the OS every time.
