### ISSUE TITLE
hs.drawing moveBack, moveForward

### ISSUE THREAD

**Issue by jasonm23** [Hammerspoon/hammerspoon#365]
sendToBack and bringToFront should be paired with moveBack, moveForward so that drawings can be z-arranged.

**Comment by cmsj** [comment]
At the moment, we just have three levels that drawings can appear on - "Back" (meaning between the desktop background image, and the desktop icons) and "Front" (meaning either on top of all normal windows, or on top of all windows including menubar/dock).

Do you mean you want to be able to z-order the drawing objects themselves?

**Comment by jasonm23** [comment]
> Do you mean you want to be able to z-order the drawing objects themselves?

Yes.

**Comment by cmsj** [comment]
Ok. So, I'm not sure that we're going to be able to do granular z-ordering, but we could do something that sends an object to front/back within its current level.

**Comment by asmagill** [comment]
In NSWindow, check out level:, setlevel:, orderBack:, and orderFront:... it wouldn't give absolute control over z-levels, but by allowing *any* of the window levels to be chosen (not just normal, float, etc.; to be honest, I've almost added this myself a time or two, but found a way around it for what I needed) and then allowing the orderBack/orderFront to move things within the level it would give some control, esp with regards to layering drawing objects.

It'd be nice if we could get a list of the windows within a level, at least within Hammerspoon... may look into that.

**Comment by cmsj** [comment]
I would accept arbitrary level setting, but I would discourage it's use for granular z-ordering. That's not what it's for, it's a hint to the window server for which groups windows are able to draw on top of which other groups. If people start changing the level to move things forwards/backwards in small increments, they will find themselves suddenly moving a window to a different level and having it behave differently (e.g. Mixed in with ordinary application windows and quickly getting lost as they are focused/raised)

**Comment by jasonm23** [comment]
@cmsj sounds like more trouble than it's worth.  I initially raised the issue due to the changes to  alert ordering.

**Comment by asmagill** [comment]
Remember, we can only affect the level of windows  owned by Hammerspoon so really only affects Hammerspoon's console and hs.drawing objects... 

I'd still add orderBack and orderFront... even if I only have a few preset-levels to use (like I said, I've found ways around it), being able to bring-to-front and shove-to-back things within a level would be nice -- render all hs.drawing objects I may want to use for a visual-display and then bring the ones I want, based upon user action, to the front without having to draw them from scratch would speed up the "apparent" speed to the user quite a bit.

**Comment by cmsj** [comment]
@asmagil I was thinking setLevel() with a table of presets, then bringToFrontWithinLevel() and a sendToBack() equivalent. Let's us keep the existing methods as a wrapper around setLevel()

**Comment by asmagill** [comment]
sounds good.

**Comment by cmsj** [comment]
I believe that this can be closed, @asmagill addressed it with 90e8acfda148ebf64795df4c96b33592b92e2e90

**Comment by jasonm23** [comment]
Thank you @asmagill
