### ISSUE TITLE
Sonoma: Beachball of Death and growing Memory about 1GB every 20seconds

### ISSUE THREAD

**Issue by muescha** [Hammerspoon/hammerspoon#3652]
Since upgrading macOS to Sonoma, I've frequently encountered the "beach ball of death" when using the Hammerspoon app. Additionally, its memory usage increases by around 1GB every 20 seconds, often leading to the app hanging and eventually triggering the "out of memory" message from macOS.

Is there a way to use code to detect when and what code snipped the app is crashing or hanging?

**Comment by cmsj** [comment]
I've noticed this a few times too on an Intel mac, but usually at times when I don't feel like Hammerspoon should have been doing very much, so I'm really not sure yet what's going on.

Sampling the Hammerspoon process from Activity Monitor might shed some light.

**Comment by cmsj** [comment]
I'm hoping that this will prove to have been largely resolved by the same change that mitigates #3565

**Comment by randy** [comment]
I think I may be having this same issue. I haven't checked memory usage when it happens, but I can almost always "sense" that Hammerspoon has crashed or hung on something. A quick mouse-over of the toolbar icon and I get the beach ball. Only solution is to reboot; a force quite and restart results in the same behavior. 

For what it's worth, I ran into this this morning when I brought my M3 (14.4.1) out of sleep, somewhere between 6:30am and 7:00am MST. I read on another issue that you've got Sentry, so maybe there's an event that might help. Let me know if you need additional info to hunt down that record; we use Sentry where I work and it can be a needle-in-a-haystack situation at times.

Also, I don't thinking I have HS doing anything crazy. It's mostly hot keys or modified keyboard behaviors that are app-based. I use several `hs.application.watcher` instances to turn those on and off based for the "in focus" app. I also have a thing that checks the window/frame under the mouse (using `hs.mouse.absolutePosition()`) for a specific use-case with IntelliJ...

**Comment by cmsj** [comment]
@randy is that running Hammerspoon 1.0.0?

**Comment by randy** [comment]
@cmsj , yes, 1.0.0 (6864).
