### ISSUE TITLE
Custom HotKey Creation for Java-based app in MacOS

### ISSUE THREAD

**Issue by AustinCDavis** [Hammerspoon/hammerspoon#3653]
Hi, I am attempting to create custom hotkeys for an app that offers very limited default shortcuts. I have used a combination of hammerspoon/karabiner elements and even keyboard maestro, but have not had much luck. I am attempting to directly control the UI components (checkboxes, menus, etc) in a java-based application based on a keyboard shortcut, but even with using AppleScript in conjunction with hammerspoon/karabiner elements and keyboard maestro I am not having much luck. Part of my problem I believe is the app (ThinkorSwim) I want to utilize this feature in functions out of a java-arm on my Mac and the hierarchy of the UI elements isn't readily accessible via accessibility inspector or UI browser. Some of the hierarchy is available, but every script ive tried doesn't seem to work. Only thing I've had luck with so far is keyboard maestro using its image based function, but I would much prefer it to be scripted as it won't move my mouse and will be much more dependable.

**Comment by cmsj** [comment]
If their UI isn't exposing accessibility information to macOS, then there is really nothing we can do to interact with it directly.

You could use `hs.mouse` and `hs.eventtap` to move the mouse to specific coordinates and emit mouse clicks, but that seems kinda fragile and terrible.

Sorry!

**Comment by AustinCDavis** [comment]
No worries! I figured I may be out of luck on it since they have not updated the interface in quite some time. It has some accessibility information but quite inconsistent. I’m going to cut my losses with it for the time being and maybe revisit later if they ever make modifications. I appreciate your time and comment!
