### ISSUE TITLE
hs.application.get() taking over 1s when it doesn't find matches

### ISSUE THREAD

**Issue by joshkaplan** [Hammerspoon/hammerspoon#3654]
I'm running into a very strange issue, where `hs.application.get()` is taking around ~1.5 seconds to run when it does _not_ find a match. When it _does_ find a match, it appears to take ~15ms.

i can reproduce by running the following:
```lua
logger = hs.logger.new('timer', 'debug')
t = hs.timer.absoluteTime()
hs.application.get('foobar')
logger.i((hs.timer.absoluteTime()-t)/1000000)
```

here is the output:
```
> local t = hs.timer.absoluteTime(); hs.application.get('foobar'); logger.i((hs.timer.absoluteTime()-t)/1000000)
2024-08-01 15:01:27: 15:01:27      timer: 1559.189458


> local t = hs.timer.absoluteTime(); hs.application.get('foobar'); logger.i((hs.timer.absoluteTime()-t)/1000000)
2024-08-01 15:03:41: 15:03:41      timer: 1577.769958
```

Additional info:
* This just started happening.
* I haven't made any recent changes to my config
* I'm on the latest hammerspoon (0.9.100), and have been since it came out
* I'm on macOS 14.5
* It still happens even if i comment out my entire config

Any help is appreciated!

**Comment by latenitefilms** [comment]
My guess is it's another application blocking the Accessibility API. Can you try force quitting everything else?

**Comment by joshkaplan** [comment]
turned out to be "Logi Options+" (logitech mouse software, runs in the background), which does indeed require accessibility access

killed it, and `application.get()`misses now are in the ~50-70ms range

thanks!
