### ISSUE TITLE
application.watcher stops working if window.filter is accessed even once

### ISSUE THREAD

**Issue by taylankasap** [Hammerspoon/hammerspoon#3681]
Minimal init.lua to reproduce:

```
hs.application.watcher.new(function(appName, eventType, appObject)
    hs.alert.show('Event from/to ' .. appName)
end):start()

local wf = hs.window.filter
```

This script is supposed to alert the app names every time you switch apps. But adding window.filter line breaks the application.watcher and it just alerts once for the app that got activated and not even alert the app that got deactivated. If you remove the window.filter line everything works fine.

Hammerspoon version: 1.0.0 (6864)
macOS version: 14.6.1 (23G93)

**Comment by taylankasap** [comment]
Also noticed something that might be hint is if you add
```
hs.loadSpoon("ReloadConfiguration")
spoon.ReloadConfiguration:start()
```
to the beginning, it works fine. What's going on?

**Comment by avi-cenna** [comment]
You might want to try assigning the application watcher to a global variable. Per the Hammerspoon [docs](https://www.hammerspoon.org/go/),

> Lua uses Garbage Collection to clean up its memory usage - any object it believes is no longer in use, will be destroyed at some point in the future (exactly when, can be very unpredictable, but it’s based around how active your Lua code is).
> 
> This means that a variable which only exists inside a function/loop/etc will be available for garbage collection as soon as the function/loop has finished executing. This includes your init.lua, which is considered to be a single scope that finishes when the final line of code has run.
> 
> If you create any objects in your init.lua, you must capture them in a variable, or they will be silently destroyed at some point in the future. For example:
>
> `hs.pathwatcher.new(.....):start()`
> 
> The object returned here, an hs.pathwatcher object, is not being captured, so it is available for Garbage Collection as soon as your init.lua is finished. It will likely not be destroyed for some minutes/hours after, but you will then be confused why your pathwatcher is not running. Instead, this version will survive for until you reload your config, or quit Hammerspoon:

> `myWatcher = hs.pathwatcher.new(.....):start()`
> 
> The myWatcher variable is a global variable, so will never go out of scope.

**Comment by taylankasap** [comment]
That's it, sorry about that :(

**Comment by avi-cenna** [comment]
No problem, I did the same thing a while back :)
