### ISSUE TITLE
hs.urlevent incorrectly treats scheme in case sensitive manner

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#3686]
With Hammerspoon configured to be the default URL handler via [URLDispatcher](https://www.hammerspoon.org/Spoons/URLDispatcher.html) and trying to open a URL starting with "HTTPS://" I get the following error:

`2024-09-10 13:14:11: 13:14:11 ERROR:  urlevent: Hammerspoon has been passed a HTTPS URL, but does not know how to handle it`

I.e. it looks like URLDispatcher treats "HTTPS" and "https" differently.

I believe, according to [6.2.2.1 of RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.1), schemes should be treated in a case-insensitive manner.

**Comment by von** [comment]
Looks like this is due to `hs.urlevent.urlOpen()` - simple demonstration:

```
> hs.urlevent.openURL("HTTPS://somehost.com/foo/bar")
true
2024-09-10 17:50:18: 17:50:18 ERROR:  urlevent: Hammerspoon has been passed a HTTPS URL, but does not know how to handle it
```

**Comment by cmsj** [comment]
(although note to anyone who might beat me to fixing this, actually the best place to do it would be in the Objective C side, by converting the scheme and host (but not the other fields) to lowercase: https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/urlevent/liburlevent.m#L150 )
