### ISSUE TITLE
chained window transformations cancel previous ones

### ISSUE THREAD

**Issue by mgee** [Hammerspoon/hammerspoon#369]
With the recent changes to asynchronous window transformation animations a transformation cancels a previous one if it is not finished. This breaks transformations which depend on the fact that the previous one is finished.

Here is an example:
```lua
hs.window.focusedWindow():moveToUnit({x = 0.5, y = 0.5, w = 0.5, h = 0.5}):ensureIsInScreenBounds()
```

The `moveToUnit` is cancelled in favor of `ensureIsInScreenBounds`. However, I think chaining these two transformations is a valid usecase which should be supported.

**Comment by lowne** [comment]
Never one to pass on an opportunity to toot my own horn, I have to point out that #354 fixes this :wink: - however IIRC `hs.window.animationDuration=0` should fix the problem for the time being

**Comment by cmsj** [comment]
Now that #354 has landed, this should be fixed in the next release. Thanks!

**Comment by zwpaper** [comment]
I meet another chained problem, as the animation of setFullScreen() and minimize() are performed by the OS, What can I do to chain like this
```
setFullScreen(false) 
minimize()
```
the `minimize()` will be cancel because of the animation of `setFullScreen(false) `

For now I have to use a `timer.doAfter` to wait for 2 seconds.
Is there a more effective way to do this?

**Comment by lowne** [comment]
@zwpaper not that I'm aware of :-/
You can always tinker with the OS level animations via `defaults write` (e.g. see [here](https://www.google.com/url?q=http://apple.stackexchange.com/questions/14001/how-to-turn-off-all-animations-on-os-x))
