### ISSUE TITLE
keyboard focus not switching properly to hammerspoon from Kitty.app specifically

### ISSUE THREAD

**Issue by focusaurus** [Hammerspoon/hammerspoon#3694]
## Issue Summary

It seems keyboard focus and hotkey routing is not working specifically when my foreground application is Kitty. Things work correctly for every other application I've tried so far. The issue seems to be only happening with Kitty as the foreground focused app.

Expected behavior: my hammerspoon & Menuhammer hotkeys take precedence and are processed by Hammerspoon. Kitty does not see them.

Actual behavior: keystrokes are not handled by hammerspoon and are sent to kitty instead.

Specifics: This seems to affect all of my hammerspoon bindings including one of my launchers which I bind to F11 as well as my MenuHammer.spoon which I bind to F10. Once MenuHammer has popped up the onscreen menu, letter keys are not bound and they show up as typing in kitty instead of being handled by the MenuHammer spoon.

**Workaround** If I mouse click in the MenuHammer menu or another pop-up chooser from hammerspoon, keyboard focus seems to switch to hammerspoon correctly and my keystrokes are handled properly.

## Version Details

Recently upgraded to Hammerspoon Version 1.0.0 (6864) 

(This issue was not happening on the prior release I was running)

MacOS 14.6.1 (23G93)

Kitty 14.6.1 (23G93) (Installed via homebrew)

## Screenshot

1. "s" is seen by kitty even though...
2. Menuhammer is active and "s" is supposed to be bound to launching Slack
![screen-2024-09-24-100235-uuuu](https://github.com/user-attachments/assets/9a5fa811-d6c9-421e-b2a7-78b4cd949b6d)

**Comment by focusaurus** [comment]
I think this may be specific to the MenuHammer spoon, not Hammerspoon in general. I found an open issue there: https://github.com/FryJay/MenuHammer/issues/13

I will close this one but if anyone encounters this and can help debug deep in the guts of macos key event routing, that would be amazing. MenuHammer is like THE way I use my computer so I'd love to get it working again and not have to find some workaround or alternative.

**Comment by yelog** [comment]
@focusaurus I have the same issue. May I ask if your issue has been resolved, and if so, how did you resolve it?

**Comment by yelog** [comment]
@focusaurus 我解决了这个问题, 是因为 Kitty 开启了 Security Keyboard Entry 造成的,  可以在左上角菜单中将其关闭
<img width="426" alt="image" src="https://github.com/user-attachments/assets/147e3f3a-3c18-451b-b035-962283f105e7" />
