### ISSUE TITLE
hs.http.asyncPost (or hs.http.post) crashes on Ventura

### ISSUE THREAD

**Issue by rjp** [Hammerspoon/hammerspoon#3711]
This is a weird one.  I've got a timer which calls a Home Assistant webhook via `hs.http.asyncPost` (was originally `hs.http.post` but that also crashed) which crashes hammerspoon a short time (~30s) after the HTTP call completes and the callback has been called.

But! Only on my Ventura machine.  My Sequoia machine doesn't crash when calling the same webhook with `hs.http.asyncPost`.  Both are running 1.0.0 (6864).

Have checked that it's not anything else - commenting out the `hs.http.asyncPost` fixes the crashing.  Enabling that brings the crashes straight back.

Attached is the last IPS from `Library/Logs/DiagnosticReports` (renamed to `.json` because Github is weird)

If there's anything more I can do, twiddle, enable, turn on to provide more information about what's going on, happy to help!

[Hammerspoon-2024-11-06-105932.json](https://github.com/user-attachments/files/17645946/Hammerspoon-2024-11-06-105932.json)

**Comment by cmsj** [comment]
That's interesting, it seems to be crashing while trying to log something.

**Comment by rjp** [comment]
@cmsj Oh bloody hell, I'm an idiot.  Yes, I was using `hs` as a variable somewhere else and didn't clock that it would blat the main Hammerspoon table.  Apologies!  Closing this in shame :)
