### ISSUE TITLE
Error moving windows

### ISSUE THREAD

**Issue by mattharrison** [Hammerspoon/hammerspoon#373]
Hi all, 

Trying to get hammerspoon working. I was working through the getting started guide and the command to move the window left or right works on the hammerspoon console window, but fails on others (emacs, firefox, etc...)

    /Users/matt/.hammerspoon/init.lua:25: attempt to index a nil value (local 'win')
    stack traceback:
	/Users/matt/.hammerspoon/init.lua:25: in function </Users/matt/.hammerspoon/init.lua:23>
	[C]: in function 'xpcall'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:30: in function <...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:28>

A quick search didn't seem to find any solutions.

Am on Mac 10.10.3

**Comment by tmandry** [comment]
This error message means that `win` is nil, so your problem is likely in actually finding the window. Can you paste a code snippet of what you're doing?

**Comment by mattharrison** [comment]
Below is my init.lua. When I run the "Left" or "Right" command it works with the hammerspoon console window, appears to fail on all others. What am I missing?

```
-- hs.hotkey.bind({"cmd", "alt", "ctrl"}, "W", function()
--   hs.alert.show("Hello World!")
-- end)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "W", function()
  hs.notify.new({title="Hammerspoon", informativeText="Hello World"}):send():release()
end)
-- reload in console hs.reload()

hs.hotkey.bind({"cmd", "alt"}, "Right", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()

  f.x = max.x + (max.w / 2)
  f.y = max.y
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end)


hs.hotkey.bind({"cmd", "alt"}, "Left", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()

  f.x = max.x
  f.y = max.y
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end)
```

**Comment by cmsj** [comment]
@mattharrison that sounds like you don't have Hammerspoon allowed to use Accessibility features. Check in System Preferences -> Security & Privacy -> Privacy and see if Hammerspoon.app has a tick next to it.

**Comment by mattharrison** [comment]
Thanks, that's it. Don't recall seeing any prompts when I started hammerspoon.
