### ISSUE TITLE
Add an hs.hash module?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#375]
I've already used an md5 library once. How about we add hs.hash that can do md5 and sha hashing? They seem like fundamental things people will want to do, even though it's relatively trivial to download an existing library to ~/.hammerspoon/

What do people think?

**Comment by asmagill** [comment]
+1

**Comment by cmsj** [comment]
As one might expect, there are lots of MIT licensed implementations of hashing algorithms for Lua:

SHA1: http://help.interfaceware.com/code/details/sha1-lua
SHA256: http://lua-users.org/wiki/SecureHashAlgorithmBw
MD5: https://raw.githubusercontent.com/kikito/md5.lua/master/md5.lua

Unifying them into a single style of API won't be too hard, especially for dumb "just hash this string and return a string" use cases. I'm not super familiar with HMAC stuff, so I think I'd skip those bits unless/until someone asks for them.

We could also include LuaMHash, but the mhash library is LGPL, which isn't directly an issue, but potentially makes things more complex.

**Comment by jhgg** [comment]
Wrap Apple's common crypto library c library. Expose interface to this in lua. Faster than doing the hashing in lua. 

https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/Common%20Crypto.3cc.html#//apple_ref/doc/man/3cc/CommonCrypto

**Comment by cmsj** [comment]
@jhgg good point, I'll check into that.

**Comment by cmsj** [comment]
@jhgg thanks for pointing that out. Same result, way way way less code :D

**Comment by cmsj** [comment]
(Also, this module has the honour of being the first one to use LuaSkin's registerLibrary method :)

**Comment by jhgg** [comment]
See my comments on 9038d16,

**Comment by jhgg** [comment]
It would be really nice to have hmac sha256 in this. If I have some free time I'll implement (it's also available via CommonCrypto) 

```
unsigned char digest[CC_SHA256_DIGEST_LENGTH];
CCHmac(kCCHmacAlgSHA256, key, keyLength, data, dataLength, digest);
```

Perhaps via `hash.hmacsha256(key, data) -> digest`?

**Comment by cmsj** [comment]
@jhgg Added HMAC variants :)

For future reference, I've verified all of the hs.hash functions with this code:

    assert(hs.hash.SHA1("lol") == "403926033d001b5279df37cbbe5287b7c7c267fa")
    assert(hs.hash.SHA512("lol") == "3dd28c5a23f780659d83dd99981e2dcb82bd4c4bdc8d97a7da50ae84c7a7229a6dc0ae8ae4748640a4cc07ccc2d55dbdc023a99b3ef72bc6ce49e30b84253dae")
    assert(hs.hash.SHA256("lol") == "07123e1f482356c415f684407a3b8723e10b2cbbc0b8fcd6282c49d37c9c1abc")
    assert(hs.hash.MD5("lol") == "9cdfb439c7876e703e307864c9167a15")

    assert(hs.hash.hmacSHA1("lolkey", "lol") == "2cb3d65f0cf92b733b5aa770210159e5634db459")
    assert(hs.hash.hmacSHA256("lolkey", "lol") == "01ec251a14db459d818f9e42c6edd36fa5fe293964e5e53d3155fb8357b80ea4")
    assert(hs.hash.hmacSHA512("lolkey", "lol") == "6b650ff1a2cea96e8e6a8035c68cea4d1f8b0d334768b26fdfc7dfc38b634e6af431c095616c5c336c33a591a506ad6cdcaf6acd4237b78ba7ee38cfaf058ed9")
    assert(hs.hash.hmacMD5("lolkey", "lol") == "4af8dd5b3f65c84edac76700111f22d1")

(The values there were calculated with either md5(1)/shasum(1) or `openssl dgst -{sha{1,256,512}, md5} -hmac)
