### ISSUE TITLE
moses

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#378]
The more I look at the moses module mentioned in #229 the other day, the more I think it is what fnutils wants to be when it grows up...

We'd need a few wrappers to make sure existing code using fnutils doesn't break, and there are a handful of functions we have that moses doesn't, but...

I'm almost ready to recommend it for inclusion in core, like we do inspect and lfs.

Anyone else have any thoughts on this?

**Comment by cmsj** [comment]
Looks like a good library. I think we'd want to bring it in as hs.fnutils, and put a note in the top docstring that it's actually a superset of Moses.

**Comment by jasonm23** [comment]
Moses is an excellent library :+1:

**Comment by asmagill** [comment]
There are enough subtle differences that it might be better to add this as hs.moses and leave fnutils as is until we can perhaps adjust the core modules which use fnutils...  We can certainly encourage movement to moses, and ultimately reduce fnutils to just the ones we've added that don't quite belong elsewhere (sortByKeys, etc.)

For example, fnutils.map and fnutils.each pass the value at each table key to their function, while the moses versions, even moses.eachi, pass in 2 arguments -- the position/key, and the value.

Adjusting the core to this change wouldn't be too hard, but what else out there that people are using might break?  Thoughts?

**Comment by cmsj** [comment]
ok, if the APIs aren't going to map (ha ha) tremendously cleanly, then I guess we would have to pull in moses as its own module. The question then, is do we actually want to do that, vs people installing it themselves with Luarocks.

I'm ambivalent on the subject, so I'd like to hear from people whether they think they want moses included :)

**Comment by cmsj** [comment]
Ok, let's add moses. The question now becomes how we integrate it. It doesn't seem like the upstream version is changing particularly frequently, so we ought to be ok to splice the docs into the code. Alternatively, we could place all the docs in init.lua and have that return the results of requiring moses.lua.

Any volunteers to add the docstrings in our format? :D

**Comment by jasonm23** [comment]
You know how much I enjoy docs ;) 

I can help out there

**Comment by cmsj** [comment]
After extensive investigation by @lowne, I think we're going to not add moses, because it doesn't really fit our internal needs. Users can, of course, still use luarocks to install it, or drop it in ~/.hammerspoon/
