### ISSUE TITLE
Feature request - Add "Always on top" feature to hs.window

### ISSUE THREAD

**Issue by chaucerbao** [Hammerspoon/hammerspoon#379]
Sometimes I'd like to have my editor always visible and on top of other windows, even if not focused.  Well, it could be an editor, or maybe a Youtube video... I wanted to see if it's worthwhile to consider adding functionality to toggle a window's ability to remain on top of other windows.

**Comment by jhgg** [comment]
+1 on this.

**Comment by asmagill** [comment]
IIRC we looked into this with Hydra and found that without adding a runtime module that inserts itself into all applications (for some reason I'm thinking I saw this referred to as a SMBL or something similar), we could only do this on modern systems when we could get direct access to the NSWindow objects, which translates into "we can do it to our own windows, but not other application windows".  The undocumented CoreGraphics functions only work in 32bit environments, I think.

Of course, I'd love to be shown that I'm wrong and that someone has found a way around this or that my memory is faulty.

**Comment by cmsj** [comment]
Yeah there's a SIMBL app/plugin floating around, called Afloat. I don't believe this is possible to do without using something like SIMBL. FWIW, I don't think that runtime patching other processes is something that Hammerspoon should be in the business of doing. Sorry!

**Comment by asmagill** [comment]
Runtime patching and code injection are something we should stay out of... 

Perusing the EasySIMBL issues pages (this one stands out: https://github.com/norio-nomura/EasySIMBL/issues/25, though you can find others), every update, sometimes even interim security updates, has required new fixes, and there is suspicion that with 10.11 it may be broken beyond any fix.  According to the 10.11 notes at https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html#//apple_ref/doc/uid/TP40016227-SW1 :

>System Integrity Protection
>
>A new security policy that applies to every running process, including privileged code and code that runs out of the sandbox. The policy extends additional protections to components on disk and at run-time, only allowing system binaries to be modified by the system installer and software updates. Code injection and runtime attachments to system binaries are no longer permitted.

We have enough trouble with our own bugs and tweaks -- we don't want to add ones Apple is (understandably from security perspective) working against!

**Comment by raveren** [comment]
@asmagill the solution you suggested might not be the only viable one, why not leave this feature request open? I'd love to have this functionality, perhaps one day :)

**Comment by iowahansen** [comment]
@asmagill @cmsj 
I'm still looking for a solution to keep an arbitrary window on top and I'm wondering if it is possible to configure Hammerspoon to periodically check if a specific window is in the foreground and if not, move it to the top without switching the focus from another application as a sort of hacky solution to the problem?

**Comment by asmagill** [comment]
I suppose it might be possible with an `hs.timer` set to run the `hs.window:raise` method on your chosen window, but I would expect it would be a noticeable (i.e. not like the window had never moved back) shift at times.

And thinking about it a little more, I don't think you can bring a window more forward than just behind the currently focused application's windows... so you could keep something *close* to the top, but never completely *on* top until that app had focus again.

**Comment by chrisgrieser** [comment]
I was also looking for this and found that BetterTouchTool have such a feature: 
<img width="993" alt="Pasted image 2022-06-26 22 35 06" src="https://user-images.githubusercontent.com/73286100/175832863-6c08f84d-0b7c-42ba-9f9b-b3348b41f4cc.png">

this allows to to toggle "always on top" on a window via this:
```lua
function pin ()
  hs.applescript('tell application "BetterTouchTool" to trigger_named "always-on-top"')
end
```
---

at least from using the feature, it seems like BetterTouchTool uses some wonky workaround where it displays an image of the respective app on top instead of the actual app.

**Comment by Danc2050** [comment]
HammerSpoon has a feature that puts their Console Always on top. 

[Source 1](https://github.com/Hammerspoon/hammerspoon/blob/8ea7d105ab27c917703a6c30e5980b82a23c6a0c/Hammerspoon/MJConsoleWindowController.h#L18)
[Source 2](https://github.com/Hammerspoon/hammerspoon/blob/master/Hammerspoon/MJConsoleWindowController.m)

**Comment by elzii** [comment]
Bump.
