### ISSUE TITLE
OS X 10.11 Wrong window positioning with menubar set to autohide

### ISSUE THREAD

**Issue by oschrenk** [Hammerspoon/hammerspoon#382]
I tried several different ways of sizing windows and none of the do what I expect

```
hs.hotkey.bind(hyper, 'a', function() hs.window.focusedWindow():moveToUnit(hs.layout.left50) end)
hs.hotkey.bind(hyper, "d", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()

  f.x = max.w / 2
  f.y = 0
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end
-- Toggle a window between its normal size, and being maximized
function toggle_window_maximized()
    local win = hs.window.focusedWindow()
    if frameCache[win:id()] then
        win:setFrame(frameCache[win:id()])
        frameCache[win:id()] = nil
    else
        frameCache[win:id()] = win:frame()
        win:maximize()
    end
end
-- Maximize
hs.hotkey.bind(hyper, 's', toggle_window_maximized)
```

1. The one sizing to the left half of the screen (hyper + a), leaves space at the top (the size of the menubar) and more then the usual space at the bottom
2. The one sizing to the right half of the screen (hyper + d), positions correctly at the top but leaves a lot of space at the bottom
3. Maximising window (hyper + s) leaves space for the menubar at the top
4. There is some spacing between left and right windows.

In the attached screenshot I use two iTerm2 terminals (left and right) and have Chrome running in the background.

![window-positioning](https://cloud.githubusercontent.com/assets/52898/8614948/d7702686-26ee-11e5-924b-5fafa81371c6.png)

**Comment by cmsj** [comment]
I've observed this too on my 10.11 machine, but haven't dived into it very much yet.

I think some useful data to capture, would be the contents of hs.screen.allScreens()[1]:frame() with the menubar autohide on/off. My guess is that the one with autohide on, won't be what we expect.

**Comment by oschrenk** [comment]
Reports the same to me in both cases

```
{
  h = 896.0,
  w = 1440.0,
  x = 0.0,
  y = 0.0
}
```

**Comment by cmsj** [comment]
@oschrenk thanks for checking. Very weird. I'll have a look into it further when I get a chance. Definitely before 10.11 is released ;)

**Comment by oschrenk** [comment]
I retested, since there was an update to the beta since my initial bug report and low and behold it is better. Now only iTerm2 (which has a windowbar less mode and might break some window behaviour for that matter I guess) is not working correctly. Chrome is now maximising just fine.

**Comment by cmsj** [comment]
@oschrenk I just updated to 10.11b6 and I'm playing around with hiding the menubar - I don't seem to be able to reproduce this anymore in iTerm, although I have to say that I can't find its option to run without a windowbar!

Is this still showing up as an issue for you?
