### ISSUE TITLE
Add an hs.objc?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#383]
Not sure about this one yet, but I just came across https://github.com/fjolnir/TLC (awesome work @fjolnir) and it looks interesting. It currently has only been tested with LuaJIT, but we could give it a test drive.

If nothing else, it may be an interesting source of code for converting Lua/ObjC objects, for Hammerspoon.framework.

**Comment by lowne** [comment]
:+1: :exclamation:

**Comment by cmsj** [comment]
@lowne fancy trying it out? :D

**Comment by lowne** [comment]
I will soon enough, but I'm way out of my depth with this stuff :)

**Comment by fjolnir** [comment]
LuaJIT should be drop-in compatible with Lua 5.2.

There is a FFI library for Vanilla Lua(modelled on LuaJIT's FFI) with which TLC could possibly work, but just using LuaJIT is a much better idea.

As for TLC, it's been used in production and I did my best to make it easy to work with.

**Comment by jhgg** [comment]
Having luajit in HS would be very nice. True coroutine support in luajit will be super nice. That way you can write async code in a sync style, like being able to move a window, sleep, and then move another window, without having to callback chain w/ hs.timer.

**Comment by cmsj** [comment]
@jhgg I've heard it said that LuaJIT is a drop-in replacement. Fancy giving it a go? :D
(Might be tricky, at least because we're further ahead on Lua releases than LuaJIT is, afaics)

**Comment by asmagill** [comment]
From what I've read online, LuaJIT (at least the main branch) is only a drop in for Lua 5.1... while patches exist that make it more or less drop in for 5.2, I'm not aware of any for 5.3.  Love to be proven wrong, though.

**Comment by cmsj** [comment]
It seems like the folk behind LuaJIT do not like the number/bitwise changes in 5.3 and are claiming they have no plans to support all of that stuff, so we may have a bad time if we try to switch :(

**Comment by asmagill** [comment]
I had forgotten about this thread and link, but for the truly adventurous, I finally have something along the lines of a bridge or objective-c class examination tool I've been playing with... finally got it to the point where it doesn't crash when dealing with object instances.

It's poorly documented (I hope to start on that sometime this weekend) but there are a couple of basic examples in the Readme file

https://github.com/asmagill/hammerspoon_asm/tree/master/objc

I'm using NSInvocation... an earlier version (look in its history, if you care) used just the objc_* functions directly (I still do for a lot of the "informational" stuff), then I tried libFFI for a bit, but it's with NSInvocation that I finally found some lasting success... though I think the fix I finally found for the issue with crashing object instances would probably work for the libFFI version as well... from my reading (very cursory), I think the main difference between NSInvocation and libFFI is speed... neither can handle union data types or vararg methods... Not sure what other differences they may have, though.

At any rate, while it's nowhere near (and may never be) ready for prime-time, I figure it's ready for others to play with, if interested.

**Comment by cmsj** [comment]
I've just thrown up https://github.com/cmsj/hammerspoon/tree/add-ffi which adds hs.ffi and hs.ffi.objc. The former may be working, the latter definitely isn't. 

Also to circle back to something mentioned earlier, LuaJIT is *not* a drop-in replacement for Lua, at least not for us. I burned many hours trying to get LuaSkin to host LuaJIT and achieved nothing but failure. Brave and knowledgeable adventurers are welcome to do better :D

**Comment by cmsj** [comment]
(ftr, hs.ffi is Facebook's fork of luaffi, and hs.ffi.objc is the luapower objc.lua, which was written for LuaJIT)

**Comment by cmsj** [comment]
Some progress here, I think I have managed to port LuaCocoa to use 5.3. My branch is https://bitbucket.org/cmsj/luacocoa if anyone fancies a play. Right now it's just the upstream branch with the lua-5.3.3 source and a patch to make LuaCocoa work with 5.3.

To integrate it with Hammerspoon, based on some experimentation, I think what I'd do is just link LuaCocoa directly into LuaSkin, rather than have it as an hs.objc, and also not have it as a separate framework. This would move LuaCocoa into the top-level Lua namespace, but since it's not really something you can install separately, I don't think that's a problem.

**Comment by cmsj** [comment]
(waiting for some feedback on lua-list from LuaCocoa's author, @ewmailing to see how far off the mark my port is)

**Comment by asmagill** [comment]
What type of repository does the site use?  My git client doesn't like it...

**Comment by asmagill** [comment]
nvm... mercurial... have to install hg

**Comment by cmsj** [comment]
`brew install git-remote-hg` and your git client may like it, if you're using the One True Git ;)

**Comment by cmsj** [comment]
Realistically, I don't think we're ever going to have the time/energy/expertise to get this sorted. I was flying by the seat of my pants when I was playing around with LuaCocoa and I would not be able to deal with issues found with it.
