### ISSUE TITLE
Traceback when Hints is invoked while TF2 is visible on screen

### ISSUE THREAD

**Issue by redwallhp** [Hammerspoon/hammerspoon#385]
If I call the hs.hints.windowHints method while Team Fortress 2 is visible on-screen, console pops open and displays the following traceback:

    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:120: bad argument #4 to 'new' (string expected, got nil)
    stack traceback:
        [C]: in function 'hs.hints.new'
        ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:120: in function 'hs.hints.displayHintsForDict'
        ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:215: in function 'hs.hints.windowHints'
        /Users/me/.hammerspoon/init.lua:154: in function </Users/me/.hammerspoon/init.lua:154>
        [C]: in function 'xpcall'
        ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:30: in function <...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:28>

This happens if TF2 is running, and the game window (which runs as a fullscreen app in its own Space) is visible on a monitor. Invoking the shortcut, even if another window is in focus, causes the traceback to be displayed. However, if I ensure that another Space is visible on each monitor, with TF2 not being visible at all, the Hints module will work just fine, displaying a Hint over each visible window.

This may be, at least in part, related to TF2 not having a proper app bundle, and hence no bundle identifier. (In `SteamApps/common/Team Fortress 2`, there's a regular binary and a shell script that Steam uses to launch the game.) *However*, Counter-Strike: Global Offensive (being another Source engine game) also has no app bundle...but it doesn't make Hammerspoon puke. I can use Hints to switch to other windows, but can't switch back, since Hints doesn't generate a window hint for the game. (So CS:GO half works, while TF2 is seriously broken.)

Games that have an app bundle (e.g. "Papers, Please") seem to work fine, causing no unusual behavior and even having a window hint.

I haven't been able to nail down exactly what's so special about TF2 that it breaks this badly, but it's possible that's at least partially related.

**Comment by lowne** [comment]
As far as HS is concerned, the problem is that `application_bundleID` [here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/application/internal.m#L270) can return nil, which in turn makes hints crash.
