### ISSUE TITLE
Feature request: capture window contents

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#387]
Add a way to:
[ ] capture window contents (a-la the undocumented `screencapture -l windowid`) onto some in-memory object; somewhat like #302; see [here](https://developer.apple.com/library/prerelease/mac/samplecode/SonOfGrab/Introduction/Intro.html)
[ ] feed said object to `hs.drawing.image` - @asmagill ;)

I don't know whether what the image object would actually be has an obvious solution from the OS X apis or not...

I'd use these capabilities in my expose replacement, which currently relies on calling `screencapture` onto a ramdrive :/

**Comment by asmagill** [comment]
see #388

**Comment by cmsj** [comment]
This actually ended up landing with #392 as hs.window:snapshot()

**Comment by cmsj** [comment]
(and hs.drawing now accepts hs.image objects)
