### ISSUE TITLE
Give @asmagil commit access

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#398]
Hey @asmagill - I'd like to give you direct commit access. You've been doing really excellent work and I'm almost always landing your PRs as soon as I see them, without modification.

Since we're pre-1.0, we can be a bit relaxed about peer reviews on code, and even post-1.0, we can always edit master after the fact, before a release, if we disagree about something.

Interested? :)

**Comment by Habbie** [comment]
:+1:

**Comment by asmagill** [comment]
I'm honored!

I won't abuse the trust, and I'm fine with whatever peer-review we do/don't do... I've noticed that most branches are still pulled from personal forks, unless special testing with a wider audience is required, so I'll continue submitting things the same way I have been.

Are their any guidelines I should be aware of?  I assume anything that's not a simple bug fix should be left as a pull for at least awhile (day?) for comments, and of course wait for Travis to check on compile issues, but anything more specific or detailed?

I've been meaning to get on the IRC channel as well, so I can participate more informally than Google/Github in questions and discussions... this will give me another reason to finally get around to it!

**Comment by cmsj** [comment]
The motion is carried, @asmagill has commit powers :dancer: 

@asmagill sorry, I sent two invites. One was wrong, please disregard the first one (it likely won't work anyway)

**Comment by cmsj** [comment]
@asmagill As for guidelines, we're sort of making them up as we go. I tend to push as fast as I feel confident about the code. If it's an obvious fix, or something completely new, I tend to push it up early/often - I only hold things around in a PR when they are likely to be contentious, or are a very deep change (like LuaSkin), so I can invite commentary from you and @Habbie.

Would be great to see you on the IRC channel, if you can :)

**Comment by lowne** [comment]
Yay!
Half OT, how about a dev/experimental branch for those non-trivial, should-be-tested-by-many-if-possible PRs? That would simplify the remotes dance as testers could just use upstream/dev as their "daily driver"; after sufficient time and scrutiny (starting from when the PR branch is finally stabilised), the branch can be merged into master.

(Also half OT, I reiterate my proposal for using gitter.im - I'm currently on vacation and the IRC situation is even worse than with my super-fragile home connection; unfortunately the [IRC bridge for gitter](https://github.com/finnp/gitter-irc-bot) needs a stable server which, as per what I just said, I cannot provide :disappointed:)

**Comment by asmagill** [comment]
@cmsj -- Regarding pull requests... how do I go about applying them?  Looking at the github docs, it looks like I should see a "Merge" option in the pull request comment section, unless I'm reading the wrong docs...  Should I instead create a local (on my mac) folder for the master repository and commit and push from there instead?  I hesitate to do so until you confirm (or reject, if I'm wrong!) this approach...

At any rate, on vacation myself this week, so I may not get a chance to follow up until later, but since I did add a couple today, I thought I'd ask.  Thanks!

**Comment by cmsj** [comment]
@asmagill ah, I think I didn't set up the permissions properly for the Committers team. I've attempted to fix it, so let me know if you can now merge stuff :)
