### ISSUE TITLE
Window being moved to next screen unexpectedly.

### ISSUE THREAD

**Issue by TheBaronHimself** [Hammerspoon/hammerspoon#403]
**Hello Folks,**

I have a problem with my window arrangement hotkeys. 
I configured Hammerspoon to move the currently focussed window to the left half, bottom half, top half and right half of the screen it's on at the time, using Hyper + h/j/k/l.

**My screen setup looks as follows:**

![screen shot 2015-07-17 at 15 44 48](https://cloud.githubusercontent.com/assets/11179011/8749891/2be27090-2c9c-11e5-84da-f0b7c080dd80.png)

When I want to move a window to the top half while it's on screen 1 (Hyper + k), it will move to screen 2. I don't have any issues on the other screens, with any other positions. 

**Here is the code I'm using:**

```
hs.hotkey.bind(hyper, 'k', function()
	if hs.window.focusedWindow() then
		local win = hs.window.focusedWindow()
		local f = win:frame()
		local screen = win:screen()
		local max = screen:frame()

		f.x = max.x 
		f.y = max.y - (max.h / 2)
		f.w = max.w 
		f.h = max.h / 2
		win:setFrame(f)
	else
		hs.alert.show("No active window.")
	end
end)
```

Does anyone have an idea what the problem could be?

Take care, 
Simon-Claudius

**Comment by cmsj** [comment]
@TheBaronHimself I haven't tested it, but eyeballing your code, the line:
    ```f.y = max.y - (max.h / 2)```
looks wrong. max.y is the top row of pixels of the screen's frame, and you're subtracting half of the screen's height from that (i.e. moving the window up by half of screen 1's height), therefore pushing it onto screen 2.

I think, to move something to the top half, you'd want `f.y` to be set to `max.y`. Please re-open this issue if I have misunderstood something here :)

**Comment by TheBaronHimself** [comment]
@cmsj | You were absolutely right *facepalm*. 

Thanks :).
