### ISSUE TITLE
hs.pasteboard.setContents("abc") raise error

### ISSUE THREAD

**Issue by ruoshan** [Hammerspoon/hammerspoon#405]
HS version 0.9.33

I can not set the contents to system pasteboard with `hs.pasteboard.setContents("abc")`

**Comment by cmsj** [comment]
@ruoshan this has been fixed in the development branch and will be included in 0.9.34, which I'm expecting to release tomorrow :)

**Comment by cmsj** [comment]
(for the sake of historians, the fixing commit was e44fe5413bedb54e46c80d5e7e37c0a6e2e4966c )
