### ISSUE TITLE
ASCII images no longer working

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#407]
```
chevron = [[ASCII:
.............
.AB...LM.....
.J##..U##....
..###..###...
...###..###..
....I#C..T#N.
....H#D..S#O.
...###..###..
..###..###...
.G##..R##....
.FE...QP.....
.............
]]

image = hs.image.imageFromASCII(chevron)

s = hs.drawing.image(hs.geometry.rect(mousepoint.x-40, mousepoint.y-40, 80, 80), image)

s:show()
```

ASCII Images no longer working with hs.drawing.image or the new hs.image module, with or without the `ASCII:` prefix in the latest release in OSX 10.10.4.

**Comment by cmsj** [comment]
Thanks for filing the bug. I missed a step in moving the code into hs.image.

I'll push out 0.9.34 shortly, but for now, if you drop the newlines after "ASCII:" and at the end of the final line of the image, it will render.

**Comment by cmsj** [comment]
(derp, I meant 0.9.35)
