### ISSUE TITLE
hs.screen.findById would be useful

### ISSUE THREAD

**Issue by adamgibbins** [Hammerspoon/hammerspoon#415]
hs.screen has a findByName function, this seems useful, saves people implementing custom logic to loop through allScreens to find what they want.  However, I've two screens of the same make/model - so the name is exactly the same.

It seems that findById should be a thing so I don't have to implement by own lookup logic.

**Comment by asmagill** [comment]
IIRC correctly, the ID isn't consistent across physical adding/removal of a monitor... I remember trying to store some info about a monitor based upon its ID and ended up not using it for some reason... I *think* this was why, but I don't recall for certain.

I won't have access to my external monitor for a few days, but if you could try the following code before removing a monitor, after removing one, and then again after adding it back again (all without restarting or reloading Hammerspoon) and post the results, it will tell us for certain if I'm remembering correctly, or if I'm just channeling the crazies:

`for i,v in pairs(hs.screen.allScreens()) do print(v:name(),v:id()) end`

If I'm wrong in my memory, then by all means, I support adding this function.

**Comment by asmagill** [comment]
Now that I think about it, maybe it was the hs.screen userdata object that changed values between connections... at any rate, if you run the above code in the various combinations of monitor attach/detach states, it will show for certain if ID is consistent enough for use as a unique identifier.

**Comment by adamgibbins** [comment]
@asmagill Can confirm my screen ID's appear to be staying consistent despite me having unplugged/replugged many days since things this issue.

**Comment by asmagill** [comment]
Thanks!
