### ISSUE TITLE
utf8 compatibility library

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#419]
Since lua5.3 is now the officially included lua, the need for including extensions/utf8/internal.m goes away... I know it's not huge, but it's less code to carry around that isn't actually being used anymore -- hs.utf8 checks to see if utf8 exists, and if it does, skips loading hs.utf8.internal and references the lua urf8 library directly.

Removing this file won't affect anything because it's functionally equivalent to lua 5.3's utf8 library, and the additions we've added are all in init.lua (I'm pretty sure this is true, but will verify before actually removing internal.m)  I'd leave in the mirroring of lua's utf8 library, which should minimize any necessary code adjustments.

However, we camelCase the utf8 functions and lua 5.3 doesn't... there is a __index metamethod on the hs.utf8 table which hides this fact from end users -- actually looking closer, this really should only affect hs.utf8.charPattern since codepoint is now considered one word and not camelCased (this is consistent with the words usage in most online documentation).

So, to the point -- should I remove the __index which makes the hs.utf8 library case insensitive?  I can think of a couple of places I reference hs.utf8.charPattern that would have to change, but I think most of them are actually in hs.utf8 itself, so this should be fairly easy to do.

@lowne -- I know you've used utf8 in some of your work -- your thoughts?

**Comment by cmsj** [comment]
+1 for moving with the times and not carrying lots of complex backwards compatibility code :)
