### ISSUE TITLE
hs.grid and hs.window.animationDuration

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#428]
I don't know if this is a bug in hs.grid, per se, or maybe something more inherent in hs.window...

but hs.grid.show() doesn't like it if hs.window.animationDuration is set to nil.

The ultimate cause is a problem in my code which is supposed to be saving the value, setting it to 0 for a time, then resetting it back to the old value... but the error message hs.grid.show() gives:

~~~
stack traceback:
	...local/build/Hammerspoon.app/Contents/Resources/setup.lua:47: in function <...local/build/Hammerspoon.app/Contents/Resources/setup.lua:45>
...oon.app/Contents/Resources/extensions/hs/window/init.lua:155: attempt to compare nil with number
stack traceback:
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:155: in function 'hs.window.setFrame'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:798: in upvalue 'hintPressed'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:805: in function <...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:805>
~~~

was less than helpful in figuring out what was causing the choking.

Since we list hs.window.animationDuration as a variable that the user can set, we need some way to ensure that a bad value doesn't cause errors with unclear meanings...

Thoughts?  giving hs.windows an __index metamethod that returns 0 (or 0.2, if you prefer, since that's the programmed default) for the label animationDuration would catch when it gets set to nil, but that doesn't prevent a user from accidentally setting it to a table or a string...

I suppose we could move it's value into the metatable itself, then use __index and __newindex to get and set it... that way __newindex could verify that it's being set to a number... does that seem like overkill?  The other option I can see is to verify it's a number everywhere it is used... am I missing another option?

Thoughts?  I'll see if I can whip up some templates for doing this and see how much work it would be to "catch" all user set-able variables in modules this way... it'd be nice not to have to check in each function that uses a variable that doesn't have explicit getter/setter methods, but I'm not sure how much extra work it would be to set this up "globally".

**Comment by cmsj** [comment]
We only consume animationDuration in one place (extensions/window/init.lua:setFrame()) so I suggest we just check the type there and if it's not a number, go with zero.

**Comment by lowne** [comment]
@asmagill this is a super-barebones "type checker" for modules (naturally the checking logic would be in its own module - this is a self-contained example for plain lua or HS's `init.lua`)
```lua

-- mymod.lua
local mod={} -- the module

local vartypes={ -- types for variables
  anumber='number',
  astring='string',
  afunctionvalue='function',
}
local argtypes={ -- types for function/method arguments
  afunction={'number','string'}
}
for fn,args in pairs(argtypes) do
  args.wrapper=function(...)
    for i=1,math.max(select('#',...),#args) do -- check arg types
      local tp = type(select(i,...) or nil)
      if tp~=args[i] then error(string.format('%s: wrong type for argument #%d: %s expected, got %s',fn,i,args[i],tp),2) end
    end
    return mod[fn](...) -- call the function
  end
end

mod.astring='this is a string'
mod.afunctionvalue=function()print('callback')end

function mod.afunction(num,str)
  print(string.rep(str,num))
end

local function get(_,k)
  local fn=argtypes[k]
  if fn then return fn.wrapper --it's a function, return a wrapper
  else return mod[k] end -- it's a value
end
local function set(_,k,v)
  if argtypes[k] then error('cannot override function '..k,2) end -- don't allow overriding functions/methods
  if type(v)~=vartypes[k] then error(string.format('wrong type for variable %s: %s expected, got %s',k,vartypes[k],type(v)),2) end -- can't set wrong type
  mod[k]=v
end

local wrap=setmetatable({},{__index=get,__newindex=set}) -- this is the table that gets exported

-- init.lua
mymod = wrap -- it'd be require'mymod'

local function test(code)
  local fn=load(code)
  local ok,error=pcall(fn)
  if ok then print(code..' -- pass')
  else print(code..' -- '..error) end
end

test'print(mymod.astring)'
test'mymod.astring=42'
test'mymod.astring="hello"'
test'mymod.anumber="hi"'
test'mymod.afunction(1,2)'
test'mymod.afunction("a")'
test'mymod.afunction(42)'
test'mymod.afunction(3,"repeat")'
```
However beyond straightforward additions such as allowing optionals (via `'number?'`), `'any'`s, and varargs (`'*'`), things start to get complicated for actual object types. 
Unless I'm overlooking something obvious, our options would be: 
- use heuristics to take a 'best guess' within the limits, and just give up otherwise - instances' metatables can't be compared against anything, unless we...
- keep around 'prototypical' instances for every kind of hs object (meh)
- "annotate" somehow, either in the object declaration (meh) or the checking function (something like `somefunction={{'hs.screen.watcher?',mt={'start','stop'}} -- takes 1 optional arg of type hs.screen.watcher`
- go nuclear and use a robust solution like Typed Lua (I haven't used it myself - yet)

Now I'm all for an optional (strong) type system when things start getting big enough, but I'm not sure we're at the point where it'll be worth it. Thoughts?

**Comment by asmagill** [comment]
I'm not too worried about complex data types b/c those should probably (and at least in my cursory walk through memory lane, do) have getters/setters...

It's probably simpler, if the number of cases is small, as @cmsj suggests for hs.window, for the user (i.e. function) of the variable to vet it.

But, I'll keep this around... I can see a use for it or a variant in some cases.
