### ISSUE TITLE
switch out hs.notify for asmagill's notification

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#44]
I would recommend using mjolnir._asm.ui.notification (https://github.com/asmagill/mjolnir_asm.ui) over mjolnir._asm.notify -- it's backwards compatible and offers more features (and it's primed to add scheduled (dated) notifications to it at some-point as well)... I can do this come the weekend if you'd like.

**Comment by cmsj** [comment]
@asmagil how close to landable would you say this module is? We've got at least one crashed bug in hs.notify, and looking at the code I'm not at all happy with the module, so I'm wondering if we can replace it with less effort than fixing it!

**Comment by asmagill** [comment]
I'll take a look at it this weekend and let you know... iirc the problem was with inconsistent garbage collection, which I understand better now, so hopefully it won't be too difficult to finish.

**Comment by asmagill** [comment]
Ok, I almost have a version of it ready for deploying for testing -- hope to have it ready tonight.  I haven't looked at the github site yet, but is there a specific issue entered which details the hs.notify crash you speak of below? I'd like to see if this suffers from a similar issue before putting it out there.

Also not that this does not yet support scheduled notifications (i.e. those that you want sent at a specific time) or allow you to override the banner/alert style set in the Notification System Preferences panel; I plan to add those as a separate and probably third-party module or 2, as they are either 10.10 specific or use undocumented API's or both.

**Comment by asmagill** [comment]
Ok, I think it's ready for public testing/perusal/nit-picking... still need to convert to the more expansive doc style, but that can wait for now...

It's at https://github.com/asmagill/hammerspoon_asm/tree/experiemental <https://github.com/asmagill/hammerspoon_asm/tree/experiemental>, if you want to take a look at it.

I'm more than happy to merge a hammerspoon only version into the core and issue a pull request, but what name should I give it?  I'm leaning towards installing it as hs.notification, leaving hs.notify alone for now... after it's been reviewed and tested a bit by others, we can either drop hs.notify, or replace hs.notify with the portions of hs.notification that apply and have hs.notify require hs.notification.  But I'll take your lead and issue the pull then.

**Comment by cmsj** [comment]
Given that the extension provides backwards compatibility, I think we should kick the tyres a bit and then land it as a replacement for hs.notify. If we land it as hs.notification and then migrate it to hs.notify later, we'll confuse people and probably end up carrying a compatibility shim, which will be confusing for new users.

**Comment by cmsj** [comment]
This is now merged into 0.9.17.
