### ISSUE TITLE
HS Console should have menus

### ISSUE THREAD

**Issue by adamgibbins** [Hammerspoon/hammerspoon#440]
I turn the HS menu icon off, and bring the HS console up by calling it with Alfred.  However, there's no menus within the console - so I cannot do things like trigger an update. To trigger an update I have to bring the console up, hit Cmd+, to get the preferences, turn the menu icon back on, click the icon, click update, open the console, open preferences, turn menu icon off again - meh.

**Comment by cmsj** [comment]
I'm not sure I want to add menus to the console, I'm not even sure if that's possible with the dock icon hidden, but we do now have hs.checkForUpdates() :)
