### ISSUE TITLE
HS Console should have timestamps

### ISSUE THREAD

**Issue by adamgibbins** [Hammerspoon/hammerspoon#441]
I want to know when events occurred, I currently have no idea as the HS Console is just a continuous stream of stuff - if I had timestamps I could correlate with things e.g. the OSX logs.

**Comment by lowne** [comment]
@adamgibbins if you're talking about your own console output, have you tried `hs.logger`?

At any rate, if this is implemented per-line in ObjC, then timestamps should be removed from hs.logger to avoid redundancy.

**Comment by adamgibbins** [comment]
@lowne Thanks for the heads up re hs.logger - but I'm mostly talking about Hammerspoon events.  When HS throws an error to the console, I want to try correlate when that error occurred with an event, maybe in the system log, or when I completed an action.

**Comment by asmagill** [comment]
The simplest idea I can think of is, if you truly want this for *every* line "printed" to the console, adding the following to your init.lua should (I haven't tested it) work for most cases:

~~~lua
local oldPrint = print
print = function(...)
    oldPrint(os.date("%Y-%m-%d %H:%M:%S: "), ...)
end
~~~

**Comment by cmsj** [comment]
I was thinking I'd just add this into the underlying objc stuff that inserts things into the console log as a simple [%H:%M]
