### ISSUE TITLE
Network Settings Window causing crash.

### ISSUE THREAD

**Issue by ConnerStephens** [Hammerspoon/hammerspoon#448]
When I tried to move the "Network Settings" window, my config crashed.  So far, this appears to only happen with this window for all other windows are moving as usual. The window can be centered with no issue, as well. I assume it has to do with the window not having the option to be expanded, but I thought I would note the observation.

The error is:
"~/.hammerspoon/init.lua:40: attempt to index a nil value (local 'win')" 

My config can be found: 
https://github.com/ConnerStephens/OSX-Dotfiles/blob/master/hammerspoon/init.lua

**Comment by cmsj** [comment]
Huh, I'd never noticed that before, but you're right, the system preferences window doesn't seem to work with our window management stuff. Thanks, I'll take a look at what's going on.

**Comment by lowne** [comment]
I think it's a privacy/security measure, no accessibility for 'sensitive' .prefPanes (similarly, :snapshot will "censor" the content of said panes, while the window chrome is still there)

**Comment by asmagill** [comment]
Oddly, if you minimize the System preferences panel and *then* take the window snapshot, it's not censored.  Someone in Apple's QA department was asleep one day...  :-)

**Comment by cmsj** [comment]
Oh, good point, this is going to be a security thing.

@ConnerStephens unfortunately that means there's not really anything we can do to make the Prefs window controllable. One thing you could do would be to add checks in your init.lua functions to see if the return value of hs.window.focusedWindow() is nil, and then either show a little "You can't do that" alert, or just silently do nothing.
