### ISSUE TITLE
hs.drawing and mouse clicks

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#450]
@cmsj: I've just started looking at this, so I apologize in advance if any of these will become obvious as I dig into it, but a couple of questions about the hs.drawing.setClickCallback...

* any particular reason it acts on mouseUp and not mouseDown or both?
* off the top of your head, can it made so that Hammerspoon doesn't become the active application (or at least so that it doesn't bring the console forward, if it's open) when accepting a click?
* what about right clicks?

Like I said, just beginning my looking into it, but I thought I'd see if there were specific reasons or roadblocks you encountered that led to the current implementation.

**Comment by asmagill** [comment]
Ok, as to my first question, it's easy enough to support mouse down, but I'm guessing you chose mouseUp because most items will be thought of us "button like" in which the action doesn't occur until the mouse is released, and not "menu-like"

I'd like to add support for both, but because of the nature of hs.drawing's objects, our standard approach of list functions in "down, up, repeat" order doesn't make as much sense -- the current behavior *is* the most likely expected behavior and I only noticed it because I'm working on providing popup menus...

So as a point of syntax, my first two thoughts are
* modify setClickCallback to take up to two (three?  will have to see if we get repeated downs) functions, but keep mouseUp as the first function and make the second mouseDown.  Either could be nil of course.
* add a boolean to setClickCallback which switches from the mouseUp behavior to the mouseDown behavior... loses repeat functionality, if its even possible.

Right clicks should also be doable, but because of the default behavior of providing a contextual menu in NSView for right menus, it will require a few extra steps, but I think I know what to do.

Still not sure about the issue with bringing the console forward, though.

**Comment by cmsj** [comment]
I'm also not sure about the bringing of the console forward. I don't see an NSWindow thing that lets it avoid getting focus, or an NSApplication thing. I landed your PR, it looks like a useful addition - I also like that the mouse button detection is bounced up for Lua to care about. Repeating seems unnecessary to me, so let's see if anyone ever asks for that :)

**Comment by asmagill** [comment]
FWIW, I've added an application watcher to close the HS console window when I leave for another application... it mitigates the issue for now, but I'll keep my eyes open.

If anyone is interested, a variant of this is what I'm using: https://gist.github.com/asmagill/251f8ea70b61a177a205
