### ISSUE TITLE
Make luaL_unref() less dangerous

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#454]
I think it's fairly clear that we are playing with fire when it comes to luaL_unref(). I want to look at replacing it somehow in LuaSkin.

My thoughts so far are:

 * Instead of using LUA_REGISTRYINDEX for everything, we could have a ref table for each module, so they are unable to contaminate each other's references
 * We could replace luaL_unref() with a custom implementation that never removes objects, but simply replaces them with a sentinel object that has appropriate metamethods to trigger a log and a crash when a reference is used after being freed
 * We could replace luaL_ref()/luaL_unref() to use a single custom table, and only allocate monotonically increasing references, so we'd never re-use one

We could actually do all of the above, for maximum safety. Anyone have any thoughts on this?

**Comment by asmagill** [comment]
I'm leery of making *any* change to LuaSkin which might make lua behave differently (even at a low level) or be unable to link with something that was compiled against stock Lua 5.3... I don't think we want to give up the ability for third party modules to be dropped in as is (assuming they're built against lua 5.3).  

I'd be much more comfortable if we offered these "sandboxed" references through a Hammerspoon specific API and allowed module developers to choose which implementation to code for -- standard lua or the protected approach (ideally they should be as close to syntactically identical as possible)... I *might* even be willing to go so far as to agree that anything adopted into core has to (once the framework is well tested and debugged, of course) use this protected implementation.

**Comment by cmsj** [comment]
To be clear, I am talking about adding API to LuaSkin for ref counting, not modifying luaL_{,un}ref.

As a policy, I want us to ship an unmodified Lua unless absolutely unavoidable. I might be tempted to add logging/debugging things, but modifying Lua API behaviours should be a drastic last resort.

So, for third party module authors, using our ref system, or Lua's, would be a personal choice. I would want to move the core modules towards using ours though.

**Comment by asmagill** [comment]
Ok... I may have read it wrong then, since that wasn't the initial impression I got.

I'm all for something safer being offered and even moving/requiring core to use it as long as it doesn't get in the way of including externally developed modules.

**Comment by cmsj** [comment]
my fault for not explaining it properly :)
