### ISSUE TITLE
Having issues building Hammerspoon from the workspace with Xcode 6.4

### ISSUE THREAD

**Issue by peterhajas** [Hammerspoon/hammerspoon#467]
Here's the last part of the build update. It's having trouble running a shell script associated with building:

    + '[' Debug '!=' Debug ']'
    + '[' -e utf8_53/build_vars.sh ']'
    + pushd utf8_53
    ~/src/hammerspoon/extensions/utf8_53 ~/src/hammerspoon/extensions
    + '[' 1 == 1 ']'
    + make install-lua
    make: *** No rule to make target `init.lua', needed by `install-lua'.  Stop.
    + cleanup
    + '[' utf8_53/Makefile '!=' '' ']'
    + rm /Users/phajas/src/hammerspoon/extensions/utf8_53/Makefile
    Showing first 200 notices only
    Command /bin/sh failed with exit code 2

This is using the Hammerspoon Xcode workspace from Xcode 6.4. Is there another step I'm missing for getting things building?

**Comment by cmsj** [comment]
@peterhajas I think this is a git/build side effect. we renamed utf8_53 to utf8, but the old directory is probably still there with a .dSYM in it (we're not good at cleaning those up atm). If I'm right, just remove the utf8_53 directory and HS should build properly.

**Comment by peterhajas** [comment]
Yep! This fixed it - thanks @cmsj!
