### ISSUE TITLE
window:setFrame() changes screen to primary

### ISSUE THREAD

**Issue by wsmith323** [Hammerspoon/hammerspoon#470]
Whenever I run window:setFrame(rect), the window gets moved to the primary screen.  In order to work around this, I have to do:

```lua
local screen = window:screen()
window:setFrame(someRect)
window:moveToScreen(screen)
```

Any ideas on what is going on here?

**Comment by lowne** [comment]
`setFrame` takes *absolute* coordinates, where 0,0 is the top left of the primary screen. If you want to move the window relative to its screen, you can use `moveToUnit`, or calculate the absolute rect (screen :frame()'s topleft+relative rect=absolute rect)

**Comment by cmsj** [comment]
@wsmith323 I think @lowne's answer should cover this, so I'm going to close this issue. Please re-open it if you have further questions about this, or think we've missed something :)

**Comment by wsmith323** [comment]
It did. I went back and re-read the docs more carefully, with an adjusted mental model of what _absolute_ meant, and things made much more sense. Thank you.
