### ISSUE TITLE
adding a function to check for updates

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#474]
I have a possible addition to the core functions in `hs` which triggers the check/perform update process... can easily add functions to show last checked time and whether or not automatic update checks are enabled/disabled.

My problem is that for development/local builds, the mere checking to see if [SUUpdater shared] is valid  triggers the "Insecure Update Error!" dialog... Granted, my current method of preventing this message on my local builds is to detatch the SUUpdater object from the MainMenu.xib and PreferencesWindow.xib, so in reality, my builds still contain Sparkle, just dormant... until the check.

So...

1. anyone know of a better way for me to do local builds so that Sparkle is completely removed from my local builds (I do perform a check to see if the SUUpdater class exists, so this would make graceful failure of the function automatic)
2. or, is anyone familiar enough with SUUpdater to know if there is a way to see if it has been initiated *without* triggering it if it hasn't been?
3. or should I, as a local builder, suck it up on the dialog because presumably I know when/if I want to go the automatic update route anyways?
4. or, is interest in this function low enough that I should just forget about it completely?

I know there has been at least one issue regarding this ability, but beyond that, what's the interest level?

**Comment by cmsj** [comment]
huh, Sparkle is supposed to already be omitted from local, non-release builds

**Comment by cmsj** [comment]
(the Podfile is configured to only include Sparkle in Release builds - is this not working? When I do local builds, I always get a message saying that the menu XIB couldn't be connected with SUUpdater because the class doesn't exist)

**Comment by asmagill** [comment]
How do I select that?  I usually build from the command line, so if there are additional flags I need to set, I can do that...

**Comment by cmsj** [comment]
@asmagill ah right, "make" invokes a release build. See the Makefile, it invokes xcodebuild with -scheme Release.

Maybe we should add a target that uses -scheme Hammerspoon, or make that the default and have a separate one for Release builds (I can easily switch scripts/librelease.sh to call a different make command)

**Comment by asmagill** [comment]
will try that... sounds easier than what I usually do.  And since I'm building "wrong", this should basically become a question of if this should be added, and when... let me know when you're ready for c code again

 (btw, haven't had any problems since building todays pull from your xcode extension changes, and I've had no issues with my in progress external stuff either.  My last check is to override a built in module with a development one, but I'm not expecting problems.)

**Comment by cmsj** [comment]
Yeah it seems to be going pretty well - I suspect mostly because I've had to make almost no C changes, so things either build or they don't, and they either load or they don't, both of which are tested in this process (building, by me as I go, loading, by Travis).

I've finished 36 objects and have 22 left to go, so I expect I'll be done tomorrow, then unless you've found anything (which I also don't expect), I say we land it and move on, and give ourselves a nice long dev period before 0.9.39.

What do you normally do to build? I propose that we have "make" do a -scheme Hammerspoon build, and I can just have a "make release" for release builds.

**Comment by asmagill** [comment]
That change makes sense... presumably anyone other than you who is doing `make` at the command line isn't making a release version.

It'll also be nice not to have to worry about the changes I make to the two xib files to prevent the insecure warning... They don't change often (twice that I can think of off the top of my head), but they have gotten reset on my end more than a few times if I'm not careful re-applying a stash after splitting out changes into multiple branches for testing...

Usually during a build, I use a script which checks a few things, then basically does make, pops up the security settings in Sys Prefs so I can check and uncheck HS, and then moves the docs where I keep my Dash stuff... occasionally I might try something more inventive, and I will use Xcode if I need to watch things as they happen, but... on the machine I normally use, I don't have as much memory as I'd like, so I avoid it when I can.

**Comment by lowne** [comment]
Whatever you guys are talking about, +1 for any way to `make` without the insecure update error after every build.
(I'll show myself out now, sorry for the interruption)

**Comment by asmagill** [comment]
I can confirm that changing the scheme from Release to Hammerspoon in the 2 places it's specified in the Makefile keeps the "Insecure update" message from appearing at the start of Hammerspoon, but invoking my test functions to check for updates triggers it when called, so some portion of the SUUpdater class is still included, just not initially active.

I can live with that since I won't be using the functions very often myself... it's more for those who stick to releases, but like to run without the menu icon or dock icon showing.

I'd say +1 to the proposed changes to the Makefile, and I'll add the functions at some point, and if I find a way to make them innocuous for those of us running mainly locally builds, so much the better, but we're not really the target audience for these functions.

**Comment by asmagill** [comment]
I take back that simply changing `-scheme Release` to `-scheme Hammerspoon` in the Makefile is sufficient... I hadn't purged my Xcode DerivedData folder and it was still pulling from a build which was in the Release/ subdir, not the Debug one...  I can always add `sed` to the PRODUCT_DIR line and fix it that way, but I'd like to see if I can get xcode to cough up the correct path itself... will let you know what I find.

**Comment by asmagill** [comment]
Ok, making progress... change line 4 of Makefile to:
~~~make
PRODUCT_DIR = $(shell xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -showBuildSettings | sort | uniq | grep " BUILT_PRODUCTS_DIR =" | awk '{ print $$3 }' | sed -e 's/\/Release/\/Debug/')
~~~
... and line 7 to:
~~~make
        xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon clean build > build/release-build.log
~~~

Now 'make clean && make' gives me:

~~~bash
rm -rf build
rm -rf extensions/.build
rm -rf extensions/*/*.dSYM
mkdir -p build
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon clean build > build/release-build.log
cp -R /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-hgvghytozltqbfaalzsrhqdwqvpd/Build/Products/Debug/Hammerspoon.app build/Hammerspoon.app
cp -R /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-hgvghytozltqbfaalzsrhqdwqvpd/Build/Products/Debug/Hammerspoon.app.dSYM build/
cp -R /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-hgvghytozltqbfaalzsrhqdwqvpd/Build/Products/Debug/LuaSkin.framework.dSYM build/
cp: /Users/amagill/Library/Developer/Xcode/DerivedData/Hammerspoon-hgvghytozltqbfaalzsrhqdwqvpd/Build/Products/Debug/LuaSkin.framework.dSYM: No such file or directory
~~~

The resulting app in build/ does run, and doesn't include Sparkle at all, so I'm assuming these missing debug symbols are mainly for use within Xcode itself and/or Crashlytics.

However, opening the Preferences window crashes Hammerspoon, and my previous external module which could trigger an update won't load at all because of "Symbol not found: _OBJC_CLASS_$_SUUpdater"

Sigh... apparently I wasn't as careful as I thought about checking for its existence... back to the grindstone :-)

**Comment by cmsj** [comment]
So we should be in good shape for this now, we have the Makefile sorted, and the preferences window code has an example of how to bind to Sparkle at runtime without any header/linking dependencies :)

**Comment by asmagill** [comment]
Ok... finally got one that works with dev builds and release builds and doesn't crash... NSInvocation is your friend when performSelector:withObject: fails... (gotta repeat that or I'm gonna strangle someone!)

The only two functions I can add without creating a SharedUpdaterDelegate -- and I see no reason to since (a) we don't in the gui-fied version and (b) in reality, these functions will only be attractive to a subset of our users, are the following:

1) `hs.automaticallyChecksForUpdates()` - get/set if update checks are performed automatically (this matches the checkbox in the Preferences window)
2) `hs.checkForUpdates()` - perform the check right now, and if available, start the process (this matches the menu item "Check For Updates...")

I'm not sure I like the names, but that matches the SUUpdater selector names, and I can't think of anything better.

Thoughts?  I'll add the pull tonight if there are no objections.

**Comment by cmsj** [comment]
@asmagill works for me, although I might change "Checks" to "Check", but I don't really mind either way. Thanks for doing this!

**Comment by cmsj** [comment]
I think this was covered by #476

**Comment by asmagill** [comment]
I tried to follow the actual underlying selector names... I don't really care one way or the other, so if you think it reads better in the singular, go ahead.

**Comment by cmsj** [comment]
Not gonna change it :)
