### ISSUE TITLE
Sluggishness on Version 0.9.38 (0.9.38)

### ISSUE THREAD

**Issue by larryhynes** [Hammerspoon/hammerspoon#475]
Howdy. The recent update to Version 0.9.38 (0.9.38), running on Yosemite with a pretty vanilla config has slowed window switching speed *way* down. Is it me? It's probably me. :(

**Comment by cmsj** [comment]
@larryhynes it may be worth checking in Activity Monitor to see if any of your apps are not responding. The nature of the Accessibility APIs we use, mean that many operations actually end up pinging all running apps for some data. If one is hanging, it causes us to block for a short period.

It may not be that, there may be a legitimate bug here somewhere.

If your apps all seem fine, could you post your init.lua and let us know which bits are running slowly?

**Comment by larryhynes** [comment]
A restart seems to have fixed it, so I'm inclined to think it wasn't (directly, at least) a Hammerspoon issue. If it resurfaces, I'll gather console output and my config and post them here. I'll leave this open in the meantime, but will close it if nothing further develops. Thanks.

**Comment by cmsj** [comment]
@larryhynes thanks for getting back so quickly :)

**Comment by larryhynes** [comment]
No further developments on this, so we'll leave it alone! :-)
