### ISSUE TITLE
frame of fixed-size windows may be incorrect during animation

### ISSUE THREAD

**Issue by mgee** [Hammerspoon/hammerspoon#478]
Since the asynchronous animation changes the window frame may be incorrect for fixed-size windows during an animation. This is due to changes to the way how `win:frame()` determines the frame of a window.

1. For example take a fixed-size window like the main window of Terminal.app.
2. Call `win:moveToUnit({x = 0.5, y = 0.5, w = 0.5, h = 0.5}):ensureIsInScreenBounds()` on the main window.
3. Depending on the font the Terminal window can only resize in rows and columns. Because of this the window frame after `moveToUnit` may be too large or too small and exceed the screen bounds.
4. The `ensureIsInScreenBounds` function does not work because it operates [on the frame from the `moveToUnit` animation because this animation is not finished](https://github.com/Hammerspoon/hammerspoon/blob/71e847ec217669105d16f64e49cd1139fe3fe1b0/extensions/window/init.lua#L110). The returned frame is not the actual frame of the window.

Workaround:
Let the `moveToUnit` animation finish before `ensureIsInScreenBounds`:
`win:moveToUnit({x = 0.5, y = 0.5, w = 0.5, h = 0.5}, 0):ensureIsInScreenBounds()`

**Comment by cmsj** [comment]
Hmm, I'm not sure what could be done to prevent this from happening. The animations are very nice, but they happen asynchronously and changing them to be synchronous would cause all of Hammerspoon to be blocked while the animations happen.

I'll leave the issue open for now, incase anyone has any bright ideas, but I rather suspect that you're going to be stuck with a workaround (either the one you have, which disable the animation, or use of an hs.timer.doAfter() to perform the ensureIsInScreenBounds() after the animation has finished)

**Comment by lowne** [comment]
The only solutions I can think of:
- check if a window's *actual* frame is what :setFrame thinks it should be - way too much overhead just for this issue imo
- somehow (won't be particularly pretty) jury-rig `ensureIsInScreenBounds` (and similarly affected functions, if any) to only make the check there; if it fails, fast-forward the animation and act on the resulting actual frame; the animation *still* won't run (as @cmsj said there's no way around that), but at least there won't be incorrect behaviour

**Comment by mgee** [comment]
I am fine with closing this issue since it only affects a rare corner case and the workarounds proposed are sufficient.

**Comment by cmsj** [comment]
@mgee thanks, and sorry we couldn't deliver glorious victory on this. The animation stuff has proven to be a double edged sword, sadly.

**Comment by lowne** [comment]
@cmsj on second thought, wouldn't it make sense for `ensureIsInScreenBounds` to always short-circuit the animation anyway, given its nature?
