### ISSUE TITLE
hs.menubar allowing empty menu items

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#482]
internal.m line 145
parse_table

Somehow this is allowing nil for nsmenuitem names, which raises an exception and kills Hammerspoon.

**Comment by asmagill** [comment]
My first thought, from the docs on initWithTitle:

>  Parameters
>  * itemName -  The title of the menu item. This value must not be nil (if there is no title, specify an empty NSString).
>  * anAction -  The action selector to be associated with the menu item. This value must be a valid selector or NULL.
>  * charCode -  A string representing a keyboard key to be used as the key equivalent. This value must not be nil (if there is no key equivalent, specify an empty NSString).

Check for title being nil and set it to @"" instead. (setTitle: suggests this)

If you can confirm that's being done with the lua_checkstring() then I dunno... catch the exception and see if it gives more detail in the NSException object fields.

**Comment by cmsj** [comment]
@asmagill http://crashes.to/s/1c72b64a80d is the crash in question, fwiw

**Comment by cmsj** [comment]
48408e7 intends to fix this, so I'll close this issue until we see the crash again.
