### ISSUE TITLE
hs.timer question

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#484]
Should hs.timer objects automatically stop if the callback ends in an error?

My initial thought is yes since it can cause a lot of spamming in terms of console messages and notifications if the repeat interval is short.

But... I can conceive of some important timer that due to some obscure bug only errors out once in a great while... and usually works great.  Yeah, the bug still needs to be tracked down or caught and handled within the callback function, but in the meantime it can perform most of what its supposed to do.

I'm still leaning towards having it stop automatically on error, but I could add a flag to hs.timer.new so that, by default, the timer stops on error, but can be overridden... worth it?  And if I do add the flag, should all constructors which repeat their callback (doUntil, doWhile, etc.) support the flag, or leave it to new, so that it's only set when you really know what you're doing?

Thoughts?

**Comment by cmsj** [comment]
I think the flag is fine, and I'd probably just put it on new() for now. We should explicitly document on all of the functions, what their behaviour is wrt error from callbacks.

**Comment by cmsj** [comment]
@asmagill if you're happy with this, can we close out the issue?

**Comment by asmagill** [comment]
Let me pull master and apply the changes to it so I know that the push uses the new luaskin style.  I'll submit a push and close this when I do.
