### ISSUE TITLE
code suggestion -- protect tables of constants in modules

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#486]
I've put up a gist at https://gist.github.com/asmagill/4340576881a774cac721 with a suggestion for putting metamethods in place to protect tables of constants that we provide in some of our modules.

And yes, this suggestion comes because I spent over an hour trying to debug something only to find out I had accidentally used "=" instead of "==" and changed a supposed "constant" and couldn't figure out why my code no longer worked... well, it was a little more complex than that, but... in essence, yeah, I changed a constant and then couldn't figure out why it no longer referred to what I wanted it to.

The suggestion includes metamethods that prevent setting, unsetting, and changing values in the table once it the hs._makeConstantsTable (a suggestion only, as this would make it available to every module automatically) function is called.  You can also query by key or value (the reverse look found in some of the tables -- e.g. if t = { a = 1, b = 2}, then t.b would return 2 and t[2] would return "b")

It also provides __pairs, so using pairs() on it works, and __tostring, so you can get a quick reference to its keys in the console. In lua 5.3, ipairs now respects metamethods, so that works like you'd expect -- if the values or keys are numeric, it will start at 1 and progress to the first missing index.

It's also protected from changing the metatable later, so it in effect is about close to truly constant as I think I can make it. (Rawset and rawget could still change/bypass things, but that's pretty explicit and not done by accident.  I'm ok with that.)

Thoughts?  I'll certainly be adding such to things I do in the future, but it would require less repetition of code if we made it available to everything that wants to use it.

**Comment by cmsj** [comment]
@asmagill I very much like the sound of what this is doing.

I was somewhat expecting to see this be a chunk of C, so I was a bit surprised that it was Lua - I think we push quite a few of the constants from the C parts of modules. I don't at all mind moving those into Lua, and I'd very much like the consistency that this would bring, I'm just wondering if it might cause issues with some of them.

I also have a slight hesitation about putting it in setup.lua - that file is getting pretty unwieldy already. I don't have a better suggestion, because there isn't really another place to put it, but that makes me wonder if we should be splitting it out a little more into a proper `hs` library?

**Comment by asmagill** [comment]
I do most of my constants array generation in C to make sure that any internal (i.e. hidden by the OS) changes (unlikely, but not impossible) are "corrected" with the next compile.  But their source as being compiled in shouldn't pose a problem... I can think of a couple of ways to make what the internal.so file returns the source for the _mk_constant function and also remove or replace the initial version in what the module "publishes"... I'll test them tonight, but I don't think it will require any real challenges.


I have also been working on a better treatment for lua_toNSObject and NSObject_tolua type tools (these are objective-c, however :-) ) that are getting pretty robust and modular with the ability to stick in your own overrides or additional class converters for one off use with specific modules...  and I'd like to see some of our functions like NSColorFromStack and geom_topoint, etc. also made more generally available...

I guess what I'm saying is that I think we have the makings for a start with a hs.api module (or some other name, i don't really care)... the lua portions would be in the module's init.lua, the C header with function prototypes could go into hammerspoon.h or even LuaSkin, and the first line of the init file would be something like `package.loadlib(package.searchpath("hs.api.internal", package.cpath),"*")` to ensure the library functions are available at runtime to other modules.

At any rate, food for thought.

**Comment by cmsj** [comment]
I would say that anything which is generic objc-meets-Lua stuff, and not Hammerspoon specific, belongs in LuaSkin. That would definitely cover the lua<->NSObject bridges, and probably module constants too.

**Comment by asmagill** [comment]
Do you mean the function to make the tables act like constants or the constants themselves? If the latter, not sure I agree... That takes them out of their domain.  As to other support functions, that's fine... luaSkin is becoming the proposed Hammerspoon.framework, then?

**Comment by cmsj** [comment]
Sorry, I just mean the function to make it happen. The constants themselves are definitely not the realm of LuaSkin.

**Comment by cmsj** [comment]
(Not that we currently ship any Lua in LuaSkin, so it may not be a reasonable thing to be asking for at this point :)

**Comment by asmagill** [comment]
I do believe it may be time to start thinking about a lua portion to LuaSkin.framework (or the Hammerspoon.framework idea from before, but since you've been adding to the LuaSkin framework, I've assumed you've moved away from them being separate... I guess I should ask, have you?)

I agree that hs is getting a little full and not all of them are related, and this one in particular would be of interest only to/when writing a module, so... we should have a module/namespace for functions like these... I've no problem with them being included in the LuaSkin umbrella, but that would require another path to package.path and package.cpath... maybe better a hs.luaskin module?  Which could then either be its own folder under extensions or a symbolic link into the framework, which ever makes the most sense.

**Comment by cmsj** [comment]
@asmagill I still think a Hammerspoon.framework makes sense, if only to replace hammerspoon.h

I've not had any time to work on it yet though, too busy with LuaSkin refactoring

**Comment by cmsj** [comment]
@asmagill let's go with a new hs.luaskin for now, should be easy enough to move later if desired.

**Comment by cmsj** [comment]
@asmagill 308988b adds a luaskin.lua that gets executed before any part of Hammerspoon's Lua does - at the moment it's just setup to hack itself directly into `_G` in a top-level `ls` namespace. I think that should be sufficient, and I think may be preferable to having LuaSkin features weirdly located in a `hs.luaskin`.

I wondered if you might want to have a go at getting your constants table stuff in here, as the first useful feature for `ls`?

**Comment by cmsj** [comment]
(also acceptable is a "no that's terrible and not going to work" response, or having things into _G outside of `ls` if that is more appropriate, etc)

**Comment by asmagill** [comment]
To make sure I understand correctly, you're wanting to create a `ls` table in `_G` and then put things like the constants table protection function into it so they could be referenced like `module.listOfConstants = ls.makeContantsTable(module.listOfConstants)`?

And since we're putting this into LuaSkin's source rather than in an extension in the `hs` namespace, I'm guessing you also want the functions to stick to core lua and not use hammerspoon modules if at all possible (including `hs.fnutils`)?

If you're still thinking in terms of LuaSkin potentially being a useful framework independent of Hammerspoon, both of these make sense.

 I think I'm only using `hs.fnutils.sortByKeys` which can easily be included as a local function.

While I generally don't like adding to `_G`, the only other possibility I see is to make modules load a specific file via require (e.g. `local ls = require("ls")` which means adding yet another path to `package.path` or moving `luaskin.lua` to the `.../Resources/extensions/` path.

And it does make a kind of sense that since LuaSkin is an integral part of Hammerspoon that it's functions are "just there" like all of the other core lua libraries.

**Comment by cmsj** [comment]
@Asmagill correct on all counts. I've spent enough time fighting with Travis and xcodebuild this week that I slightly wish I didn't try to keep LuaSkin independent, but I still think it's a worthwhile goal :)

**Comment by asmagill** [comment]
@cmsj, is this still something you want to add (308988b I mean)?

The makeConstantsTable function is in 11 modules, I think, so yeah... it probably would be a good idea to centralize it and reduce redundant code!

**Comment by cmsj** [comment]
@asmagill yeah I think it's a good idea :)

**Comment by cmsj** [comment]
I believe this was already handled.
