### ISSUE TITLE
Modes that share keybindings must be entered/exited in specific order

### ISSUE THREAD

**Issue by gibiansky** [Hammerspoon/hammerspoon#489]
I think I've come across a tricky bit of Hammerspoon, probably a bug. 

This happens when you have two modes that share a keybinding:

```lua
local mode1 = hs.hotkey.modal.new(nil, nil)
local mode2 = hs.hotkey.modal.new(nil, nil)
mode1:bind({}, key, function() print("Hello 1") end)
mode2:bind({}, key, function() print("Hello 2") end)
```
If you then start in `mode1`, then *enter* `mode2`, and then *leave* `mode1`, the result is that `key` is not bound to *anything*:
```lua
mode1:enter()
mode2:enter()
mode1:exit()
-- `key` is not bound to anything as a result
```

You *must* do it in this order:
```lua
mode1:enter()
mode1:exit()
mode2:enter()
-- `key` is bound to mode2 as expected
```

I ran across this in a real-world scenario and it took a long time to debug.

(The real-world scenario involved layering modes. There is a global command mode; from there you can enter more specific command modes (e.g. tmux control mode, view control mode, etc) with specific commands. However the the *exit* from all of these modes is shared. So that's why I had a bunch of modes sharing keybindings and entering and exiting simultaneously -- the entering and exiting was switching modes programmatically.)

**Comment by lowne** [comment]
#409 fixes this ;)

**Comment by cmsj** [comment]
#409 has now landed and will be in the next release :)
