### ISSUE TITLE
extensions rebuild on every build or run

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#49]
which makes cmd-r in xcode take a long time for no reason. Should figure out how to make this better - have the Makefiles actually know about all the invidual targets?

**Comment by cmsj** [comment]
Managed to figure out a way to get debug symbols into Crashlytics without having to change how extensions are built, significantly. As such, I'm not going to continue trying to get the extensions built as dylib bundles.
I wouldn't object to it if someone else wants to do it, but I no longer have a compelling reason to :)

**Comment by mgee** [comment]
Just for reference: I did a prototype transition to gyp as build system here:
https://github.com/mgee/hammerspoon/tree/gyp
In this branch gyp is used to generate Xcode projects for Hammerspoon and all extensions.
Note that this branch is not up-to-date with Hammerspoon/master.

**Comment by cmsj** [comment]
This was closed by #468
