### ISSUE TITLE
hs.timer api to get remaining time

### ISSUE THREAD

**Issue by erikcw** [Hammerspoon/hammerspoon#491]
It would be convenient to have a public method on hs.timer that returns the amount of time remaining.

**Comment by asmagill** [comment]
FWIW, if a timer has stopped, it will also return -# where # is the number of seconds since it was stopped.

Don't know if this is a problem, but should probably be documented.

**Comment by cmsj** [comment]
@asmagill hmm, I did think about non-running timers, and have them return 0, but I'm wondering if nil would be better. I don't immediately imagine that anyone would care about the amount of time since a timer was stopped, but maybe someone has a good reason to just return whatever the raw value is?

**Comment by jhgg** [comment]
I like the negative values. Let's me know how long ago a timer fired with out having to do additional book keeping.

**Comment by asmagill** [comment]
we do have the :running() method so you can determine if the negative number is because of a backlog or because the timer no longer runs... I'm fine with leaving it as-is as long as it's documented properly.
