### ISSUE TITLE
getColorFromStack - what it does and what it should do

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#494]
Partially to disentangle differing ideas in thread #477, partially because I am uncertain what is "best" myself, and partially so we can decide on common practices to provide a consistent experience for the users of Hammerspoon, I bring up this helper function which I added to the hammerspoon.h file a while back for discussion...

This function is used in a few different places (mostly in hs.drawing but a couple other places as well, I think and at least one I will probably push soon) and it does one thing:  Takes a table on the lua_stack and checks for keys which define a color and returns an NSColor object which can be used elsewhere in the C code.

There are actually two versions of this function: One which takes a fallback NSColor to use if the lua parameter is nil or not present, and one which uses [NSColor blackColor] in this case (see step 2 below).  Currently I don't believe anything actually uses the version of this function which allows for a different fallback color.

The expected table will look like this, where each # is a number between 0.0 and 1.0 inclusive:

``` lua
color = { red = #, blue = #, green = #, alpha = # }
```

What the function currently does and why:
1. if the item at the stack location which is supposed to contain this table is not a table and is also not nil or none (i.e. the absence of a passed parameter) then it generates an error via luaL_error and returns up the function call chain (i.e. execution of this function ends, but the lua function which called the function which uses this helper can either handle the error or pass it back up the chain as well).   _-- This differs from before my changes in that before it would return nil but not an error._
2. If the item at the stack location is nil or none (a non-existant parameter -- the difference between `function()` and `function(nil)`) -- then the fallback color is returned.
3. Since we have a table, a "place holder" NSColor is created with red, blue, and green = 0, and alpha = 1.  _-- this differs from before where the initial place holder had alpha = 0 as well._
4. if red, blue, green, and/or alpha are found in the table and its value is a number, then the placeholder's key of the same name is changed to match the number assigned to the tables key.
5. if a key name other than those in 4 is found or if the value found for one of the above keys is not a number, it is silently ignored.
6. the resulting placeholder NSColor is returned and used by the functions caller in whatever way it wanted the NSColor for.

Now, where this differs from before:
1. I return an error rather than silently return nil so that the developer has the opportunity to catch this rather than have it silently cause the parent function to return nil.  While it is true that the outer lua function which calls the method which eventually calls this function could be written to detect if the return value is nil, to do so is not consistent with the "lua model", which provides an error mechanism much like exceptions in other languages.  Nil is a value, which depending upon context, may be a correct value.  But in this specific context, we were using nil as an error indicator when lua _already has an error indicator built in to the language_.
2. I changed the placeholder default color to have an alpha value of 1 because previously passing in `{red = 1}` was valid, but invisible.  At a minimum, you had to include the alpha channel to see ANY color.  I chose to invert this so that specifying a color requires the minimum number of keys necessary to accurately describe that color -- and to specify a visible red, the minimum (in my opinion) is one key, not two.

The downside to 2 is that now {} represents black rather than clear... the one case in which my "minimalist" idea fails, but it does have a simple, though admittedly not _as_ simple, representation: {alpha=0}

So, now you know _why_ I made the changes I did.  My discussion points follow:
1. should an actual nil or none as a parameter be an error like a string or number (rather than a table) would be?
2. am I wrong in making alpha=1 the default placeholder?  And if not, should an exception be made when the other three are not present (i.e. should {} be clear)?
3. should unrecognized keys, or values to recognized keys which are not numbers, cause an error or be silently ignored?
4. should any these (or others to be added, if I've missed anything anyone can see) errors cause visual feedback via hs.showError()?
5. Have I missed any relevant points or thoughts?

If you've read #477 at all, you already know my thoughts on 4 are no, but I include it for completeness sake since I think the decisions we make here should act as a template for other modules... as I say above "_blah blah_ strive to be consistent _blah blah_"

At this stage this is not about easier in C or lua or whatever -- this is about what the experience should be.  The "how" we can discuss, if necessary, later.

**Comment by asmagill** [comment]
I also meant to add that returning nil but not an error means that its possible the error might not cause problems until somewhere else far away in the code: e.g. `a = hs.drawing.text(...):setTextFont(...):setTextColor("badparameter")` would set `a` to nil, but not cause an error until somewhere later in the code when you try `a:setText(...)`.  Better to have the error *where it occurs*.

**Comment by cmsj** [comment]
+1 for rolling the error up the stack, and +1 for defaulting to alpha=1. I think that's much less surprising in the general case. +1 for ignoring irrelevant table entries.

**Comment by lowne** [comment]
imo:
1. nil and none should be an error; only `{}` should be the 'full default'
2. ok to default alpha to 1 in all cases
3. irrelevant keys (`{brown='sweet'}`) should be ignored; `{red='a bit'}` should error
4. will reply to #477 
5. I'd like to also pass {0,0,1} for blue, or {1,0,0,0.5} for semi opaque red - i.e. plain list of numbers; t[5+] would be ignored; named keys, if also present, override integer keys - then I can fully get rid of the mini wrapper for grid.ui and expose.ui

**Comment by lowne** [comment]
For clarity, this is what I mean with point 5:
```lua
function parseColor(t)
  local c={0,0,0,1}
  for i=1,4 do c[i]=t[i] and (type(t[i])=='number' and t[i] or error'...') or c[i] end
  for i,k in ipairs{'red','green','blue','alpha'} do c[i]=t[k] and (type(t[k])=='number' and t[k] or error'...') or c[i] end
  return {red=c[1],green=c[2],blue=c[3],alpha=c[4]}
end```

**Comment by cmsj** [comment]
@asmagill do we still have anything to do on this issue?

**Comment by asmagill** [comment]
We never did reach a consensus on allowing color to be specified as just an array of numbers... I personally don't like it because its ambiguous... I like obvious in my data structures.  If the general will is for it, I can add it, but otherwise, this can be closed.

**Comment by cmsj** [comment]
I suppose it has the advantage of being more like hs.geometry.rect(), but I'm not super bothered.

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)
