### ISSUE TITLE
Calling bind() twice

### ISSUE THREAD

**Issue by gibiansky** [Hammerspoon/hammerspoon#495]
This applies to `hs.hotkey` and `hs.hotkey.modal` – what happens if you call `bind` on the same key with the same modifiers? 

I would have assumed that the second call overrides the first one, but I observe the opposite behaviour: the first call wins. 

1. Both of these are reasonable, but the behaviour (whatever it is) should be part of the contract of `bind` and should thus be documented.
2. If the behaviour stays as it is, there's no way to change a binding dynamically. I think this may be a useful tool, so perhaps there should be some way to inspect the current bindings and remove them or change them...

**Comment by lowne** [comment]
Same problem as #489, same pending solution (and fwiw I agree on all counts)

**Comment by cmsj** [comment]
This should be fixed in the next release, now that #409 has landed. Right @lowne ? :)

**Comment by lowne** [comment]
Yes indeed! 😜
