### ISSUE TITLE
LuaSkin and [skin pushLuaRef:refTable ref:myHandle];

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#504]
[skin pushLuaRef:refTable ref:myHandle] assumes that the reference handle passed in actually exists in the table. If it doesn't, the standard practice is to check the return type of lua_rawgeti, but this is wrapped and hidden inside the method.  Looking at the lua source, it appears that lua_rawgeti will push nil, if no entry is found, but it would be more useful if this returned the type instead of void for parity with what it is replacing.

**Comment by cmsj** [comment]
I'm confused about the standard practice of checking lua_rawgeti's return - it is also void I think.

As for pushing a nil on error, we don't know if a pushed nil was an error or the correctly fetched value.

I agree this is annoying, but the docs for rawgeti explicitly say that the reference must be valid :/

**Comment by asmagill** [comment]
Maybe it's a change in 5.3, but from the docs:

> int lua_rawgeti (lua_State *L, int index, lua_Integer n);
> Pushes onto the stack the value t[n], where t is the table at the given index. The access is raw; that is, it does not invoke metamethods.
>
> Returns the type of the pushed value.

And I traced the source -- it does push a nil if nothing is found, just like accessing a table with no key or index with that name would.  I'm not complaining about the nil (in fact I'm glad its there)... I'm asking that we return the type to save a line of code (petty of me, I know  😝)  Seriously, though, its just a suggestion and the work around is an extra line of code, so its no biggie.  I was hoping actually it would return LUA_TNONE to distinguish it from nil, but no such luck...

**Comment by asmagill** [comment]
BTW -- after I finish modernizing notify, I want to put my lua_pushNSObject code out to a wider audience for review and testing... should I add it to LuaSkin or as part of the hs.luaskin module we talked about in another thread?

**Comment by cmsj** [comment]
Oh cool, that is new. Agreed we should return that :)

As for lua to nsobject conversion, that's going to be C, right? I definitely definitely definitely want something like that in LuaSkin :D

**Comment by cmsj** [comment]
(FWIW though, I would expect us to typically not check the return of pushLuaRef because we usually do protectedCallWithTraceback right after, which will error nicely if there is no valid function. Nonetheless, I agree with changing the signature for places where we do want to check)
