### ISSUE TITLE
hs.notify question

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#506]
In cleaning up hs.notify and adding some features that were previously missing (including an image, scheduled notifications, maybe a few others) its becoming increasingly obvious to me that if you modify the properties of a notification *after it has been delivered*, bad juju can occur... at its most basic, you can't withdraw the notification on an individual basis (this assumes you have set autoWithdraw to false) -- you have to remove them all or leave it for the user to remove.  At the other extreme end is if you have a repeating notification... the repeat might continue even through a reboot and require... interesting steps to clear it.

So two questions... the first, should I just make it an error to modify an already delivered notification?  The down side is that if you want to repeat (programmatically) a notification or a slightly tweaked version of a notification, you have to create a whole brand new one.

And the second, is about repeating notifications.  Even with moving to a tagged based callback system so callbacks can be re-enabled after a reload of Hammerspoon, the way to stop a run-away repeater isn't obvious.  I've put some things in to minimize the likelihood of creating one except on purpose, but... would it just be safer to disallow repeating notifications all-together?  The down side would be the loss of repeating notifications when Hammerspoon isn't running -- while it's running, you can mimic the behavior with hs.timer, but the benefit of scheduled and repeating notifications is that Hammerspoon doesn't need to be running.  (Note that I would still leave in scheduled notifications -- they would just be one-shots.)

Thoughts?  Preferences?  I'm leaning towards disallowing repeaters, or maybe making it part of a third-party module (there are some private API things for user notifications that are kind of interesting as well, but they definitely won't be in core) that you could download separately if you really wanted to, but wasn't included with the core.

**Comment by asmagill** [comment]
I'm going with the following unless anyone objects:

* repeating notifications must autoWithdraw (this is built into the delegate) that way clicking on a runaway will clear it even if Hammerspoon isn't running.
* once a notification is queued with either :send or :schedule, it is locked from editing unless you withdraw it first.

**Comment by asmagill** [comment]
Crap.  No.  the delegate doesn't exist until hs.notify is loaded... it would fall through to the default which doesn't have that logic.  Hmm... ok back to leaning towards leaving it out.

**Comment by cmsj** [comment]
I'm find with all notifications being one-shot only. I also can't help but wonder if we are opening ourselves up to a world of pain by implementing so much of the notification API. It seems to lead to a big confusing mess when the general use case is "I just want to tell myself something in a pretty, system-like way"

**Comment by asmagill** [comment]
I tend to favor the "if-it-ain't-hard, throw-it-in-there" camp because you never know what someone else might think of doing that you didn't... and 90% of the notification stuff is just that --- not hard.

It's those pesky edge cases and a very poorly handled function callback system (given the nature of user notifications, I never should have originally moved away from the tagged based system from Hydra -- I should have expanded it) -- I've completely gutted and replaced that (and LuaSkin helped quite a bit with that, btw).

Repeaters are out, as are a few others involving replies, additional actions, and push notifications.

However, I do want function callbacks to survive a reload (and they do now, if you register the same tag as an action in your init files before the notification is clicked on) and (eventually, but not with this round) allow notifications to start Hammerspoon if it's not running (it does) *and* still act on their callback (not yet, at least not for the notification that starts Hammerspoon).

**Comment by asmagill** [comment]
followup in #509 if there are more thoughts/comments
