### ISSUE TITLE
dealing with unfocusable windows

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#507]
As I expand and refine my "annoyances that require mouse interactions" windowfilter, I've run into this peculiar beast:
![screen shot 2015-08-19 at 13 00 27](https://cloud.githubusercontent.com/assets/6718755/9354654/9fd039e8-4672-11e5-8115-e7c5ee5905d4.png)
owned by `Image Capture Extensions` and with a subrole of `AXFloatingWindow`; afaict it doesn't respond to :focus() nor :close(), nor I'm aware of a way to direct a keystroke to it, or enumerate the buttons to send a mouse click . 
If there _is_ a way, I'd be grateful to be told; if there isn't, could it be implemented (@asmagill ;) ) easily and painlessly? If the solution is too complicated then nevermind, I guess picking up the mouse a couple extra times a day won't kill me.

**Comment by cmsj** [comment]
hs.eventtap.event events can be directed at a particular application. Perhaps sending an Enter to Image Capture Extensions would do the trick?

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)
