### ISSUE TITLE
Clarification on window/application/uielement metatables

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#508]
I'm a bit confused, as window's metatable seems to be the same as for application; there's an `application_gc` in application/internal.m and a `window_gc` in window, but 
```
> getmetatable(hs.window).__gc==getmetatable(hs.application).__gc
true
```
so, unless they're hiding their metatables via __metatable (and if so, why?), what am I missing?

**Comment by asmagill** [comment]
That's the metatable for the tables hs.window and hs.application, and they probably do match if you have module autoloading enabled.

If you want to see the metatable of an hs.window or hs.application object, use hs.getObjectMetatable("hs.window") or hs.getObjectMetatable("hs.application"), or use getmetatable on an object from each.

**Comment by lowne** [comment]
No, I'm interested in the module metatable; not sure what it's got to do with autoloading, but if you say it's normal then ok, I worked around it; I just wanted to set `__call` for the modules, but the function is the same (since the metatable is the same), so I'll dispatch from inside there. Weird, though.

**Comment by asmagill** [comment]
My bad... it's the hs metatable that handles autoloading... I think window and application use uielement's metatable because the watchers are related... Its been a while since I've looked too closely at them, but remember there were some pretty close ties between the three.

**Comment by lowne** [comment]
Yes, that's why I mentioned uielement, at the very least `getmetatable(hs.application).__index==hs.uielement`; I still don't understand where this shared metatable is coming from, by looking at the luaopen_ code, but that's hardly surprising (I mean my lack of understanding); at any rate if it's intentional and if there's no chicanery with hidden metatables I can be sure that my workaround won't break things.
