### ISSUE TITLE
Firefox issue with `hs.application.launchOrFocus`

### ISSUE THREAD

**Issue by danielcorin** [Hammerspoon/hammerspoon#514]
I'm running OS X 10.10.4

When using `hs.application.launchOrFocus` with Firefox, Hammerspoon seems to try and launch the app in Safe Mode. This does not occur when launching FF normally.

**Comment by cmsj** [comment]
How are you triggering that launchOrFocus() call? Is it perhaps with a keyboard shortcut that involves modifier keys? I think that if one starts Firefox with the option key held down, it goes into Safe Mode.

**Comment by asmagill** [comment]
If this is indeed the case, I was able to get around a similar problem with something (I forget what application it was now) by moving the function to the releasedFn position (i.e. second function) instead of the pressedFn position.

**Comment by danielcorin** [comment]
I was using the modifiers ctrl-option-command. Changing to something like

    hs.hotkey.bind({'ctrl'}, 'f', function() hs.application.launchOrFocus("Firefox") end)

fixes things nicely. Thanks!

**Comment by dineshba** [comment]
If someone still wants to open firefox with `option` modifier:

Disable the safe mode for firefox explicitly 
```lua
local hyperKey = {'ctrl', 'alt', 'cmd', 'shift'}
hs.hotkey.bind(hyperKey, "b", function()
  hs.execute [["export" "MOZ_DISABLE_SAFE_MODE_KEY" "1"]]
  hs.application.launchOrFocus("Firefox")
end)
```

**Comment by dahmc** [comment]
@dineshba unfortunately that doesn't seem to work. Is this a Windows only thing that doesn't work on macOS?
