### ISSUE TITLE
Extension request: Add lsqlite3 to the default lua packages installed

### ISSUE THREAD

**Issue by ketralnis** [Hammerspoon/hammerspoon#515]
This makes a lot of settings and tasks easier. An official-ish lua module to do this [already exists](http://lua.sqlite.org/index.cgi/index), and OS X ships with sqlite3 already

**Comment by cmsj** [comment]
I think this is an interesting idea - the question is whether Hammerspoon should be shipping sqlite bindings, or if folk should use luarocks to install it.

We recently had the same question in regards to the Moses lua library, but I think there are two differences here:

 1. lsqlite3 is a C library, so users would need to have Xcode installed to be able to luarocks install it
 2. being able to access system databases is more of a Hammerspoon related feature than doing arbitrary functional programming is

So, I'm leaning towards saying yes, but I'd like some more opinions (@asmagill ?)

**Comment by asmagill** [comment]
Originally I didn't have a strong opinion one way or the other on this... however, I think I'm going to need to delve into sqlite for webview if we want to give it complete access to it's cookie cache... the stuff I'm reading is confusing at times and very IOS-centric with OS X tacked on at the end (except when it's just plain outdated), but I believe the recommended current implementation with sandboxing under WKWebView is heavy on the JS injection and sqlite, so... I say go ahead.

**Comment by asmagill** [comment]
We're going to either require a different module or include our own sqlite3 library -- trying to use the module with the stock libsqlite3.dylib gives the following error:

~~~lua
> l = require("lsqlite3")
error loading module 'lsqlite3' from file '/usr/local/lib/lua/5.3/lsqlite3.so':
	dlopen(/usr/local/lib/lua/5.3/lsqlite3.so, 6): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /usr/local/lib/lua/5.3/lsqlite3.so
  Expected in: flat namespace
 in /usr/local/lib/lua/5.3/lsqlite3.so
~~~

Forcing the use of the brew version with this:
~~~lua
> package.loadlib("/usr/local/opt/sqlite/lib/libsqlite3.dylib","*")
true

> l = require("lsqlite3")
~~~

works, however.

Trying the loadlib with the path to the system library in /usr/lib gives the same error as the first attempt, so it's definitely something that's not included in the stock version (Note, this is under 10.11 GM... I'm going to assume that the 10.11 release will be the same, and I never tried this with earlier versions, so I can't say if this is new or not.

**Comment by bradparks** [comment]
for what it's worth, i'd love to see sqlite support as well!

**Comment by ketralnis** [comment]
It may be possible to patch lsqlite3 to not require loadable extension support (and whatever other optional sqlite3 stuff it may require) but I don't see the harm in just including a version of sqlite3 in Hammerspoon. It's a pretty easy library to embed.

**Comment by asmagill** [comment]
iirc, there is a flag to include or not extension support in the lua module when it's compiled... but i don't know sqlite well enough to know what that means we lose... are extensions useful enough that we care?  i definately see a need for the module, though, so +1 if i haven't already

**Comment by ketralnis** [comment]
Loadable extension support can be nice but it's unlikely to be useful for the kinds of things that Hammerspoon wants https://www.sqlite.org/loadext.html

**Comment by wincent** [comment]
In the absence of bundled sqlite support, what's the current recommendation for doing persistent storage (beyond lightweight use of `hs.settings`)? Forking out to `hs.task` to call `sqlite3`, for example, would be pretty heavyweight.

**Comment by latenitefilms** [comment]
@asmagill - I tried installing [LuaSQLite3](http://lua.sqlite.org/index.cgi/index) via Luarocks, but I'm not having much luck getting it to work in Hammerspoon. Any suggestions?

**Comment by cmsj** [comment]
There is an experimental `hs.sqlite3` in master. Anyone who would like to build Hammerspoon and test it, would be very welcome to do so :)

**Comment by latenitefilms** [comment]
This is AWESOME! Thanks so much @cmsj ! I'm still working out how exactly to use it, but so far so good opening up databases and reading data! This is going to be VERY helpful! Thanks again!

**Comment by cmsj** [comment]
Closing this out now, hs.sqlite3 has been in for 6 months with no reported issues :)
