### ISSUE TITLE
hs.screen.watcher not triggered after hibernate

### ISSUE THREAD

**Issue by patrickli** [Hammerspoon/hammerspoon#520]
### Software

OSX Yosemite 10.10.5
- Require password after sleep
- FileVault on

Hammerspoon 0.9.38
### Hardware

MacBook Pro (Retina, 15-inch, Mid 2014)
1x External Monitor (set as primary)
## Steps to reproduce
1. Implement a `hs.screen.watcher` with a callback to `print` a debug message whenever it triggers.
2. With external monitor connected, put computer to sleep.
3. Disconnect power and monitor.
4. Leave the computer long enough so it enters hibernate.
5. Wake the computer up but don't enter the password yet.
6. Connect the external monitor.
7. Enter the password to unlock the computer.
## Expected outcome

There should be console output at steps `5` and `6`.
## Actual outcome

No debug message was triggered at all.
## Thoughts

If I skip `4`, screen watchers are triggered properly. So I wonder if that's because of the FileVault and hibernate. Since I am using FileVault, harddrive is locked when waking up from hibernate and the page file is not loaded into memory. So hammerspoon is not actually running. When unlocked, the monitors are already connected so there is no change to monitor layout as hammerspoon's concern. However the windows are rearranged by OSX because of steps `5` and `6`. That puzzles me.

**Comment by patrickli** [comment]
I did more testing. It seems the screen watcher is completely stopped from step `5`. Can only be brought back though reload config.

I will try to put a caffeinate watcher on wake to force start the screen watcher and see how it goes.

**Comment by cmsj** [comment]
I suspect you're probably right that this is a side effect of FileVault being enabled, in which case I'm not sure what we will be able to do, other than a workaround with a caffeinate watcher. Let us know how your test goes :)

**Comment by patrickli** [comment]
Using a caffeinate watcher to start the screen watcher on `systemDidWake` does solve the issue. Maybe this should be done automatically for all screen watchers? Or at least something in the manual to mention this for other people who might be in the same situation as I am.

**Comment by asmagill** [comment]
I have seen a few cases where some callbacks for various watchers get turned off at random times -- when the system is under load or tight memory, after a wakeup, etc.

Most of the time, I've been able to get around it by having the callback function include a <whateverobject>:start() command right before exiting the callback... I'll dig through my files and make a list -- we probably want to include whatever solution, check, or documentation is decided upon to cover those cases as well (off the top of my head, I remember hs.application.watcher being one I had to restart like this, but I forget right now what other times I've run into this.)

**Comment by cmsj** [comment]
@asmagill I think in this specific case, the callbacks not being triggered is expected behaviour, given that the OS isn't really running very much code until you unlock the disk. I'll add a note in the docs.

**Comment by patrickli** [comment]
It doesn't seem to be very reliable. In some occasions the caffeinate watcher is not starting the screen watcher. This can only be tested once a day so I'll have to experiment a bit more.

**Comment by lowne** [comment]
@patrickli According to `man pmset`, it seems (haven't tried it myself yet) that you can change the hibernation timer via `pmset autopoweroffdelay` to facilitate testing.

**Comment by patrickli** [comment]
@lowne Yes I am aware of that. But the Mac I use is at work so I don't have too much time testing this.
@cmsj I think when the Mac wakes up and at the unlock screen, the disk is actually unlocked because you can see the notifications for Mail, etc popping up. So applications are actually running. The caffeinate watcher doesn't always work in this case so there might be some other factors turning them off. I'll do more testing on this.

**Comment by patrickli** [comment]
OK I've tried this for a few more days and it seems sometimes the caffeinate watcher is not started when woke up. So use a caffeinate watcher to restart the screen watcher is not the solution.

The funny part is that sometimes the watchers are resumed when woke up. It can be tricky to figure out exactly how it behaves.

On another note, I converted from [slate](https://github.com/mattr-/slate) and it works every time after woke up. It might be worthwhile to see how they are monitoring system changes?

I am sorry that I can't help more despite being a software engineer myself. I have absolutely no idea on OSX development.

**Comment by cmsj** [comment]
So this is perhaps a little embarrassing, because I added the screen watcher to Slate in https://github.com/jigish/slate/pull/166 ;)

It's using a much lower level API than Hammerspoon uses, so perhaps we need to experiment with switching.

**Comment by cmsj** [comment]
(The tl;dr of that patch being that Slate uses CGDisplayRegisterReconfigurationCallback where we use NSNotificationCenter)

**Comment by patrickli** [comment]
Another day and none of the watchers has resumed. I wonder if this is something related to `NSNotificationCenter`.

Let me know if I can help debug something.

**Comment by patrickli** [comment]
Tried some more and none of the watchers are able to resume after hibernate.

**Comment by cmsj** [comment]
@patrickli when you say none of the watchers, do you mean the screen watcher and the caffeinate watcher?

**Comment by patrickli** [comment]
@cmsj Yes I mean the screen watcher and the caffeinate watcher.
