### ISSUE TITLE
LuaSkin registerLibraryWithObject: crash

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#525]
LuaSkin registerLibraryWithObject:... will crash if  objectFunctions: is nil.

Should probably ignore the Userdata tag and just fall back to registerWithLibrary instead, but at least raise a specific exception rather than crash with:

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by cmsj** [comment]
hmm. I think I'm ok with it crashing, this ought to be a bug that gets caught pretty early in development of an extension, but I agree that we could crash in a way that's more verbose about what the mistake was.

**Comment by cmsj** [comment]
(As in, I think this should probably be an assertion)

**Comment by asmagill** [comment]
I'm fine with that... the fall through would just be a convenience measure for us lazy ones :-P but an assertion that at least explains what was wrong is fine.

It took me a couple of tries to figure out which field was the problem... I wanted to check on some tables being generated in a module I expect to have more stuff in later (so I used the constructor it will *eventually* need)... Suppose I could have looked in LuaSkin.m again, but I'm kind of tired of it right now :-)

**Comment by cmsj** [comment]
I've added some asserts, with descriptive messages.
