### ISSUE TITLE
Bring back hs.notify:release() ?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#526]
@asmagill I wonder if we should have a no-op, deprecated :release() on hs.notify objects? It's going to be in lots and lots of user configs, and the cost of doing it seems low. Thoughts?

**Comment by asmagill** [comment]
We could recreate the main effect that release had by clearing the tag (or setting it to the empty function tag) in the userInfo dictionary.  I can add that tomorrow if you like.

**Comment by cmsj** [comment]
@asmagill I'm happy with that, or it being a no-op. Your call. Thanks! :)

**Comment by asmagill** [comment]
See #527.  Modifying the existing tag in the user dictionary would cause the notification to change, and thus not match the notification in the notification center... this is the next best compromise since if you don't specify a tag at creation time, a unique one is created.

**Comment by asmagill** [comment]
Should be fixed with #527
