### ISSUE TITLE
Check if application is running and perform action when it closes

### ISSUE THREAD

**Issue by kdheepak89** [Hammerspoon/hammerspoon#529]
Hi, I'm not sure if this is the best place to post this. But I'm curious to know if this is possible with hammerspoon. I would basically like to run a script when an application exits.

**Comment by cmsj** [comment]
You can discover if an application is running using `hs.appfinder.appFromName()` and use `hs.application.watcher` to register a callback function for application events, which include a `terminated` event. Note that the information available for termination events is very limited, so you may need to record the PID of the application while it's running, to compare against later in the callback.

Let us know if you have any problems getting it running :)

**Comment by kdheepak89** [comment]
That's almost exactly what I wanted to do! Thanks. Quick question - Is there a way in Hammerspoon to distinguish between an App that's been 'Quit' and an App that's just been closed. The distinguishing feature here being, an App that's just been closed is still available in the Dock with a indicator light on it. I hope my question makes sense?

**Comment by cmsj** [comment]
@kdheepak89 I think what you're talking about is an app which is still running, but has no windows open? You wouldn't get a signal from `hs.application.watcher` when it goes into that state.
We have `hs.windowfilter`, which is currently considered experimental, and will be renamed `hs.window.filter` in the next release, which lets you subscribe to window events. You should be able to use that to get notified of windows going away, and check to see if there are zero remaining windows for an app.

**Comment by lowne** [comment]
Yes, that must be either an app with no visible windows, or a hidden app (cmd-h).
The snippet below will let you know (by calling `callbackNoWindows`) when `AppName` has no more visible windows for whatever reason (app hidden, all windows closed, all windows minimised, app closed):

```lua
function callbackWindows(windows) end
function callbackNoWindows() 
  if hs.application.find('AppName') then print('AppName is still running')
  else print('AppName has been closed') end
end
hs.window.filter.new('AppName'):notify(callbackWindows,callbackNoWindows)
```

**Comment by kdheepak89** [comment]
Thanks @cmsj  and @lowne, that was very useful and I'll check it out. Just one last question, is there a way to execute a hammerspoon function from a bash/zsh shell command line?

**Comment by cmsj** [comment]
@kdheepak89 see `hs.ipc` :)

**Comment by kdheepak89** [comment]
That is awesome! Thank you!
