### ISSUE TITLE
[request] add hs.timer:setNextTrigger(sec)

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#530]
From `CFRunLoopTimerSetNextFireDate`:

> For example, if you have an action that will be performed multiple times in the future, but at irregular time intervals, it would be very expensive to create, add to run loop modes, and then destroy a timer for each firing event. Instead, you can create a repeating timer with an initial firing time in the distant future (or the initial firing time) and a very large repeat interval—on the order of decades or more—and add it to all the necessary run loop modes. Then, when you know when the timer should fire next, you reset the firing time with CFRunLoopTimerSetNextFireDate, perhaps from the timer’s own callback function. This technique effectively produces a reusable, asynchronous timer.

Therefore this seems to be more efficient than calling `:stop()` and creating a new timer in those use cases that were covered in my `hs.delayed` proposal (and I have several of these already, with another coming up for window.layout).

For clarity, this is the use case:
```lua
local myTimer=hs.timer.doAfter(A_VERY_LARGE_NUMBER,doSomething)
function doSomething() 
  ... 
  myTimer:setNextTrigger(A_VERY_LARGE_NUMBER)
end

function consolidateIncomingEvents(event)
  manipulateEvent(event)
  myTimer:setNextTrigger(0.5) -- finally act when we're done with all incoming events
end

for_example_a_windowfilter:subscribe(events,consolidateIncomingEvents)
```

*Maybe* for added convenience we could save the original `.doAfter` delay/`.new` interval, and also add `:pause()` and `:resume()`:
```lua
function hs.timer:pause() self:setNextTrigger(A_VERY_LARGE_NUMBER) end
function hs.timer:resume() self:setNextTrigger(self.original_interval) end
```
but this requires a bit of a rethinking of the API - e.g. my previous example would become a bit strange:

```lua
local myTimer=hs.timer.doAfter(0.5,doSomething):pause() -- hmm
function doSomething() 
  ... 
  myTimer:pause() -- yay!
end

function consolidateIncomingEvents(event)
  manipulateEvent(event)
  myTimer:resume() -- hmm
end

for_example_a_windowfilter:subscribe(events,consolidateIncomingEvents)
```

so perhaps a more semantically meaningful approach is preferable:
```lua
function hs.timer.delayed(sec,fn)
  local wrapper=function()
    self:setNextTrigger(A_VERY_LARGE_NUMBER)
    fn()
  end
  self=hs.timer.new(A_VERY_LARGE_NUMBER,wrapper):start()
  self.original_interval=sec
  return self
end
function hs.timer:trigger()
  return self:setNextTrigger(self.original_interval)
end
```

and

```lua
local myTimer=hs.timer.delayed(0.5,doSomething) -- yay
function doSomething() 
  ... 
  -- no need for anything here, yay
end

function consolidateIncomingEvents(event)
  manipulateEvent(event)
  myTimer:trigger() -- yay
end

for_example_a_windowfilter:subscribe(events,consolidateIncomingEvents)
```

**Comment by cmsj** [comment]
Let's start off with adding setNextTrigger() and see where that takes us with the API.
