### ISSUE TITLE
`setGamma` and `getGamma` broken since upgrading to 0.9.93

### ISSUE THREAD

**Issue by calvinwyoung** [Hammerspoon/hammerspoon#533]
Since upgrading to v0.9.39, I get this error whenever I call `screen:setGamma()` or `screen:getGamma()`:

    attempt to call a nil value (method 'setGamma')

Downgrading back to v0.9.38 fixes things. Are the `__Gamma` methods working for anyone else in v0.9.93?

**Comment by cmsj** [comment]
@calvinwyoung good catch, thanks. Sorry about that, it'll be fixed in 0.9.40

**Comment by calvinwyoung** [comment]
Wow that was fast — thanks @cmsj!!
