### ISSUE TITLE
windowhints fails with "cannot find intersection for non-rects"

### ISSUE THREAD

**Issue by ketralnis** [Hammerspoon/hammerspoon#534]
After the 0.9.39 update, windowhints no longer functions for me. It fails like this:

```
stack traceback:
...oon.app/Contents/Resources/extensions/hs/window/init.lua:337: cannot find intersection for non-rects
stack traceback:
    [C]: in function 'error'
    ...n.app/Contents/Resources/extensions/hs/geometry/init.lua:492: in function 'hs.geometry.intersect'
    ...oon.app/Contents/Resources/extensions/hs/window/init.lua:337: in function 'hs.window.screen'
    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:83: in function 'hs.hints.internal._dictSize'
    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:87: in function 'hs.hints.internal._dictSize'
    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:87: in function 'hs.hints.internal._dictSize'
    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:95: in function 'hs.hints.internal.displayHintsForDict'
    ...poon.app/Contents/Resources/extensions/hs/hints/init.lua:215: in function 'hs.hints.internal.windowHints'
stack traceback:
```

**Comment by lowne** [comment]
Could you try this in the HS console and paste the result?
```lua
for i,s in ipairs(hs.screen.allScreens()) do f=s:fullFrame() print('screen '..i,f.x,f.y,f.w,f.h) end
```
and
```lua
for i,w in ipairs(hs.window.allWindows()) do f=w:frame() print('win '..i,f.x,f.y,f.w,f.h) end
```

(the only thing I can think of that makes it fail like this is a strange window frame like {0,0,1,1})

**Comment by ketralnis** [comment]
Sadly I'm no longer able to reproduce it :( It happens maybe 1/3 of the time but I'm not sure what those times have in common

**Comment by lowne** [comment]
Well, the moment it happens again (if it does), try pasting those commands in the console and gather the output - do NOT close any windows.

**Comment by ketralnis** [comment]
Here's a related one. I'm trying to do a `window:moveToScreen` and I get

    ...oon.app/Contents/Resources/extensions/hs/window/init.lua:248: invalid rect: 2560,1439/0x0
    stack traceback:
        [C]: in function 'error'
        ...oon.app/Contents/Resources/extensions/hs/window/init.lua:248: in function 'hs.window.internal.setFrame'
        (...tail calls...)
        /Users/dking/.hammerspoon/ayla.lua:56: in function </Users/dking/.hammerspoon/ayla.lua:32>
    stack traceback:

And the outputs of those lines:

    > for i,s in ipairs(hs.screen.allScreens()) do f=s:fullFrame() print('screen '..i,f.x,f.y,f.w,f.h) end

    screen 1    0.0 0.0 2560.0  1440.0
    screen 2    2560.0  540.0   1440.0  900.0
    screen 3    -1920.0 360.0   1920.0  1080.0

    > for i,w in ipairs(hs.window.allWindows()) do f=w:frame() print('win '..i,f.x,f.y,f.w,f.h) end

    win 1   -768.0  360.0   762.0   1074.0
    win 2   2938.0  669.0   743.0   705.0
    win 3   -0.0    22.0    2560.0  1364.0
    win 4   2759.0  574.0   989.0   830.0
    win 5   -1920.0 1439.0  1.0 1.0
    win 6   -1920.0 360.0   1714.0  1080.0
    win 7   -1920.0 0.0 5920.0  1440.0
    win 8   818.0   197.0   924.0   665.0
    win 9   2594.0  563.0   740.0   458.0
    win 10  175.0   146.0   1029.0  819.0
    win 11  927.0   257.0   935.0   610.0
    win 12  3273.0  775.0   661.0   581.0
    win 13  3813.0  540.0   186.0   900.0
    win 14  348.0   22.0    952.0   824.0

    > sf=hs.screen.allScreens()[1]:frame() for i,w in ipairs(hs.window.allWindows()) do print(i,hs.geometry.intersect(sf,w:frame())) end

    -- Loading extension: geometry
    1   hs.geometry.rect(0.0,360.0,0.0,1026.0)
    2   hs.geometry.rect(2560.0,669.0,0.0,705.0)
    3   hs.geometry.rect(0.0,22.0,2560.0,1364.0)
    4   hs.geometry.rect(2560.0,574.0,0.0,812.0)
    5   hs.geometry.rect(0.0,1386.0,0.0,0.0)
    6   hs.geometry.rect(0.0,360.0,0.0,1026.0)
    7   hs.geometry.rect(0.0,22.0,2560.0,1364.0)
    8   hs.geometry.rect(1920.0,22.0,640.0,341.0)
    9   hs.geometry.rect(1920.0,22.0,640.0,341.0)
    10  hs.geometry.rect(818.0,197.0,924.0,665.0)
    11  hs.geometry.rect(2560.0,563.0,0.0,458.0)
    12  hs.geometry.rect(175.0,146.0,1029.0,819.0)
    13  hs.geometry.rect(927.0,257.0,935.0,610.0)
    14  hs.geometry.rect(2560.0,775.0,0.0,581.0)
    15  hs.geometry.rect(2560.0,540.0,0.0,846.0)
    16  hs.geometry.rect(348.0,22.0,952.0,824.0)

(if it's not the same issue I'm happy to move it to a different ticket)

**Comment by cmsj** [comment]
is this still happening?

**Comment by ketralnis** [comment]
Not to me, will reopen if it does
