### ISSUE TITLE
Simple crash with defining debug

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#535]
As soon as I add a function named debug, Hammerspoon crashes. I assume it is conflicting with a global debug function someplace.

```
local DEBUG = false

function debug(msg)
  if DEBUG then
    print(os.date() .. ': ' .. msg)
  end
end
```
And so

`local function debug...`

seems to stop the crash.

**Comment by lowne** [comment]
There's a global `debug` module in Lua - overriding any of the Lua builtins is guaranteed to result in crashes or at least weirdness.

**Comment by junkblocker** [comment]
Thanks, @lowne . I am fine with this getting closed.
