### ISSUE TITLE
Support absolute timers in hs.timer

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#543]
I'd like to be able to say something like:

```
foo = hs.timer.doAt("22:00:00", 86400, function() blah end)
foo:start()
```

the second parameter being a repeat interval (with 0 meaning no repeat). The first parameter should probably accept a full date, but I would expect to typically just be used for a time.

**Comment by cmsj** [comment]
Or maybe roll the repeatEvery into doAt as the second parameter, to avoid the method being useless on other timers.

**Comment by asmagill** [comment]
Should a scheduled event survive Hammerspoon reloading/restarting?  hs.notify does something like this, which does survive a restart, but while it shows the notification at the scheduled time, the function isn't called until the user actually clicks on the notification... I can take a closer look and see if we can use a similar mechanism

**Comment by cmsj** [comment]
I think they should be GC'd - I'm generally extremely nervous about anything persisting in the runtime across reloads/restarts, and if people want to use Hammerspoon as some kind of reminder/calendar app, they should stop wanting that ;D

**Comment by lowne** [comment]
I've just made it, on the exact prototype in OP (but no date, as I agree that HS~=calendar - if that's desired, then we should ship a proper parsing [library](https://github.com/LuaDist/luadate)); but then I realised the following:
- at 21:00, I do `timer.doAt("20:00:00",timer.days(1),fn)`: the timer will be set 23 hours from now as expected
- at 21:00, I do `timer.doAt("20:00:00",timer.hours(6),fn)`: in this case I probably expect the first trigger to occur at 02:00 (and another one at 14:00), not at 20:00 tomorrow 

or in other words, if I want to run a job every 6 hours, I think it should work irrespective of when I last reloaded HS.

So I'm going to implement it this way, but let me know if there's something I'm missing here - or if there are other scenarios to take into consideration as well.

**Comment by lowne** [comment]
To be clear: `timer.doAt("20:00:00",1,fn)` then wouldn't work, because it'd trigger the next second no matter what time it is, but I think that's a degenerate case; if you need something like that, the reasonable way would be to set a one-off at 20:00, and from *that* callback start a 1s-interval timer. Objections?

**Comment by lowne** [comment]
This has now landed; if there are no objections (as per comments above on recurring jobs) this issue can be closed.
