### ISSUE TITLE
LuaSkin protectedCallAndTraceback

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#548]
I've noticed that whenever I use this, the stack pointer increases by the number of returned objects expected + 1... looking at the docs suggests that lua_pcall pops the function and the arguments, but does not pop the message handler -- I've not confirmed this in the lua source yet, but that's the way it reads to me.

Using lua_pcall in the same place with a msgh of 0 doesn't have this problem, supporting the theory.

We should either document this or remove it before returning... I'm leaning towards the removal myself.

**Comment by cmsj** [comment]
+1 removal, I think it's super important that wherever possible, the LuaSkin functions don't leave unexpected things on the Lua stack - we can't necessarily predict what they will end up being used for, so they should do their utmost to be tidy!

Thanks for spotting this, I hadn't realised that the message handler doesn't get popped.

**Comment by asmagill** [comment]
Agreed.  In looking at the examples of using lua_pcall in my books and other references, i notice that they always push it once but reference it's specific positive index number multiple times, so I suppose in retrospect, it should have been obvious to me that it wasn't getting popped, but I do wish the documentation were more clear on it.  At any rate, it's addressed now.
