### ISSUE TITLE
hs.host.address() info is static

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#552]
It seems the the `hs.host.address()` provided information is determined at config load time and after that it never changes as I VPN (SSL) in and out to someplace. I was hoping to replace ControlPlane's functionality by checking the addresses in a timer loop.

**Comment by cmsj** [comment]
Good catch, thanks. I would note, however, that the fix for this means that these calls are now much slower than before, so I would suggest not having your timer loop fire super often, as Hammerspoon may be blocked for a couple of seconds each time, doing DNS resolution.

**Comment by asmagill** [comment]
Maybe a flag which defaults to using the cached data would be a better approach?  For his specific situation, the note would still apply, but when cached data is sufficient, it wouldn't cause the slow down each time.

**Comment by cmsj** [comment]
@asmagill maybe. I'm not sure why you'd want to call those things and be ok with getting stale data. I think this was genuinely a bug. The new behaviour is unfortunate, but if people want to cache the values, they're welcome to (I do it, because some of my config is hostname dependent).

**Comment by junkblocker** [comment]
Thanks for the super quick fix! Can't wait for the release!

**Comment by cmsj** [comment]
@asmagill sorry, that sounded rude and I didn't mean it to. I'd be interested to learn about situations where a "use-cache" flag was helpful :)

**Comment by asmagill** [comment]
Point... but a lot of things are designed around returning cached data except when explicitly asked.  It was just a thought.  I wonder if there is a notification we could be watching for... I may take a look at that later and see.

**Comment by cmsj** [comment]
:)
