### ISSUE TITLE
Hammerspoon does not recognize Google Chrome Canary

### ISSUE THREAD

**Issue by zxcvbn97** [Hammerspoon/hammerspoon#553]
Hi there,

I've tried various window and application title for google chrome canary, but hammerspoon couldn't find it. Please help

hs.hotkey.bind({"cmd", "shift", "ctrl"}, "H", function()
      local thunderboltDisplay = "Thunderbolt Display"
      local windowLayout = {
         {"Google Chrome Canary",  "Chrome",          thunderboltDisplay, hs.layout.left50,    nil, nil},
      }
      hs.layout.apply(windowLayout)
      hs.alert.show("Layout home loaded")
end)

**Comment by lowne** [comment]
the app name is "Google Chrome", which means that if you also have non-canary Chrome running, you need to use
```lua
local chrome1,chrome2=hs.application.find'Google Chrome'
```
and then disambiguate via `:bundleID()` (which differs).
At any rate `hs.layout` doesn't support this: if you're running both canary and non-canary, it'll choose one "randomly".

**Comment by cmsj** [comment]
@zxcvbn97 in the next release (0.9.41) you'll be able to pass an `hs.application` object into the layout :)
