### ISSUE TITLE
LuaSkin checkArgs fails for optional userdata type

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#554]
Am I missing something in it's use?  I'm trying:

~~~obj-c
    [[LuaSkin shared] checkArgs:LS_TTABLE,
                                LS_TTABLE    | LS_TOPTIONAL,
                                LS_TUSERDATA | LS_TOPTIONAL, USERDATA_UCC_TAG,
                                LS_TBREAK] ;
~~~

The intent is to require 1 table, and optionally require a table and/or a userdata object.  Calling the function with two tables (no third argument at all) gives me:

`bad argument #3 to 'new' (hs.webview.usercontent expected, got userdata)`

which is not one of the error messages the checkArgs method prints, so it must be from the luaL_checkudata which shouldn't be getting invoked since this argument is optional and in this case not present at all...

Looking at the code for LuaSkin doesn't suggest anything immediate, but I haven't spent too much time with it yet -- tracking down other bugs that are mine first 😝

**Comment by cmsj** [comment]
@asmagill ooh nice. This would be at the more complex end of the arguments we've checked so far!

Each argument to checkArgs represents a Lua argument, so you need to | the table and userdata together. The only exception is the userdata tags, but they are immediately consumed when LS_TUSERDATA is seen. 

I'm not 100% sure it's going to work, but I think it will. 

Separately, this made me realise that we couldn't checkArgs a function that accepted multiple userdata types for a single argument. We may end up needing a slower variant that takes a dictionary describing the arguments.

**Comment by cmsj** [comment]
So I think you want LS_TTABLE, LS_TTABLE|LS_TUSERDATA, someTag, LS_TUSERDATA|LS_TOPTIONAL, someTag

That should mean "table followed by either a table or userdata maybe followed by userdata", but this would be more complex than anything I tested. There's also no way to say that if the second argument was userdata, the third should not exist.

I'm getting less confident about whether this works or makes sense, so you may be checking types manually for now!

**Comment by asmagill** [comment]
Actually, both the second table and the userdata are optional, so I tried this:
~~~obj-c
    [[LuaSkin shared] checkArgs:LS_TTABLE,
                                LS_TTABLE | LS_TUSERDATA | LS_TOPTIONAL, USERDATA_UCC_TAG,
                                LS_TBREAK] ;
~~~

Didn't work either... I think because the userdata string is only consumed IF the lua_type (not the position type) is LUA_TUSERDATA... Also, luaL_checkudata doesn't return boolean -- it errors immediately if the userdata type is a mismatch:

~~~c
void *luaL_checkudata (lua_State *L, int arg, const char *tname);
~~~

Yeah, I think the idea is nice, but needs to be rethought a little... and there will always be some combinations that it probably can't handle, especially if the first arguments determine what the later ones should be...

At its most basic, does the checker even need to bother with userdata types?  We have to convert/check them ourselves before we can use them anyways, so I think a checker could get away with just checking if it IS userdata and not worry about WHICH userdata it is...

**Comment by asmagill** [comment]
And thinking about it, my second test isn't what I want either because the function can take 1, 2, or 3 arguments (but if 3, they have to be table, table, userdata)... should/can the parser handle multiple optional arguments?  Or just one?

**Comment by asmagill** [comment]
Hmmm... looking closer, this might not be LuaSkins fault after all... I mean, I do think it still needs to be looked at closer when handling optional userdata, but...

In this case, I was creating a userdata object very early in the function before actually knowing how many arguments were passed in... and sometimes it ended up at position 3... My bad.  I'll close this and think about some specific tests for the checkArgs method tomorrow and maybe open a specific issue for that.

Sorry!

**Comment by cmsj** [comment]
oh, good point about luaL_checkudata. I'll switch that out for luaL_testudata
