### ISSUE TITLE
LuaSkin push and table functions

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#557]
A bit long - I apologize, but if you do regular Objective-C coding for/about Hammerspoon regularly, please find some time if you can and weigh in...

The new LuaSkin additions I pushed this week allow us to create functions which can allow for the easy conversion of more complex objects in Objective-C to usable tables or userdata objects in Lua.  The updated hs.application adds a function that the pushNSObject: method can use so that any other module which wants to push an NSRunningApplication object to Lua as an hs.application object can do so without having to write any additional code themselves.

An example I'm toying with at https://github.com/asmagill/hammerspoon_text has bidirectional support for NSColor, NSParagraphStyle, NSFont, and (limited) NSAttributedString for more examples...

And the hs.webview I'm proposing uses these features a lot so that most of the functions which return something just have to make one call rather than replicate complex code for each variable type that might be passed back.

The first benefit mentioned above is that a new module doesn't have to know anything about hs.application, but if it has an application object to return, it automatically becomes a useful object to other modules which can work with hs.application.

Another benefit... our NSColor conversion code is currently limited to RGB+Alpha, but if they all used this method for transferring colors back and forth, updates to 2 functions means that *EVERY* module which uses NSColor as an argument or return value automatically gets the update.  An update such as allowing labels from the system color list or CMYK color definitions for example.

I admit this is my creation, so I'm definitely biased, but I like the idea behind these methods because it allows us to present a consistent way for the users when defining something (NSColor again is a great example) which is used by multiple modules without requiring a lot of replicated code and providing a single point for updates which are automatically gained by all modules.

However, there are some issues I see with this model going forward...

1) a conversion function only exists if a module has submitted one when it was loaded... this means that if you want to return an hs.application object, then hs.application must have been loaded at some point before or the conversion function doesn't yet exist (it won't cause an error, but instead return a string containing the [NSRunningApplication description] for that instance, just like NSLog would).  I currently get around this by having the init.lua file require a module even if it's just to get it's conversion functions loaded (see hs.webview and hs.http -- I put a couple in there because it made logical sense and I hope to work on http at some point since it's using things that are deprecated in 10.11 and because it may be where I ultimately put some things that might address some of hs.webview's limitations.)

2) currently, submitting a conversion function for a class that already has one will overwrite the entry for the previous one... so if I write one because I need something new or because I don't realize someone else already has, module load order will determine which is in effect at any given time (you could, I suppose register yours before every use, just to be safe, but that adds overhead and other issues if one module does it, but another does not)

3) LuaSkin isn't well documented outside of its source, and support functions like this aren't documented at all at present...

4) the tableAtIndex:ToClass: method is badly named... it doesn't actually check that the argument is a table unless the conversion function itself does... I take advantage of this in hs.webview by allowing NSURLRequest to accept a string (a hard coded URL) or a table (fields which make up things like the request body, HTTP headers, the URL, etc.).  I stuck with the tableAtIndex:ToClass: method name any way because it most likely will most often be a table... but if we want to change it, now is probably the time...

There are probably others, but I wanted to put this out there so some thought could be given to how best to address/manage these going forward...  If this is better addressed in the Google group, let me know and I'll move it there, but since it concerns primarily coders and developers at present, I figured I'd start it here.

If you actually read all the way through, thanks!  I think these method can make coding modules a lot easier and make the end-user experience more consistent, but only if we use it in a consistent and productive way.

**Comment by cmsj** [comment]
1) This seems like a tricky one, but I suspect the only way to solve it is documentation. It at least has the advantage of being in C, so it's not going to be something that shows up in user configs

2) I think I slightly disagree with the behaviour of replacing a pre-existing converter, given the context of this issue. What's the use case for where that might actually be desirable?

3) Agreed, we should have an issue for figuring that out. I guess we need to generate separate documentation for module authors that includes internal API stuff like LuaSkin.

4) I don't particularly have an opinion about this, probably because I've not yet really used your additions. Agreed that now is the time to change it if you feel it needs to :)

**Comment by asmagill** [comment]
1) As long as there is some communication/documentation that developers can rely on, even a wiki page listing what converters already exist and in which module, this shouldn't be too big of a problem... documentation is the key and making sure that you "require" modules which contain the support you need is expected... this is just an area where you can't get lazy and rely on the autoload feature.

2) This arose out of a few different ideas that was turning into a combinatorial explosion of the methods... at one point I wanted to include versions of the push methods which allowed you to include a crafted array (kind of like the ones used for lua functions and methods in our modules) of locally defined conversion functions that were to be checked before anything registered or the defaults... that way if you needed a specific version of a conversion function for whatever reason, then you just made sure to include it in your local list and source.  I backed away from this idea because it could encourage always defining all of your own converters rather than using ones already in place... the main thrust of these additions is to provide the end-user with consistent results across as many modules as possible and encourage updating existing converters so all modules (that use them) benefit rather than just a select few.  Since you can always code your module in a way to bypass the LuaSkin converters completely, developers can still "roll their own" if they must, and I guess I just left the code to delete/replace intact... Given that we want to discourage this, what should happen?  Ignore/throw an error/log when attempting to replace an existing converter?

4) I'm not overly concerned about the name... in general, an NSObject that isn't simple probably will require a table to contain enough info to properly build it (and if it's simple, does it need a converter function at all?)... but allowing the converter itself to accept any type (like the cited NSURLRequest) can allow for items which have a simple fallback.  I guess I just wanted it on record, that the converter function should check type, if it matters, and see if anyone can come up with a better name suggestion.

**Comment by cmsj** [comment]
2) I think throwing an error, and a fairly serious one. This is something we would want developers to notice and catch before they unleash their module on the world.

I'll file an issue for getting LuaSkin documentation out into the world, which I think could include the converters that we supply. Then I don't think there's anything else actionable in here?

**Comment by asmagill** [comment]
It would be nice if I can record which module installs the converters so the error can mention where to look if you really feel the need to update or modify the existing converter... I think I should be able to pull this from the stack trace. Yeah, this can be closed and I'll open up a pull when this is added.
