### ISSUE TITLE
Discussion: LuaSkin checkArgs and Boolean

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#558]
Lua mostly (but not always) treats boolean as "If it's not false or nil, then it's true.  Otherwise it's false."  There are a few cases where you might want to be more explicit and force an actual boolean true or false... checkArgs currently can't help with this... should it?  I naively expected it to, but can work around it, so either way is fine, but we should be explicit about it since LS_TBOOLEAN is defined, but never actually used in the code...

**Comment by asmagill** [comment]
My recommendation is to make LS_TBOOLEAN work (it currently doesn't match anything) as expected (i.e. match an actual boolean parameter) and add LS_TANY or LS_TNOTNONE (or whatever label you like) that indicates that a parameter is expected, but we don't care what at this stage

**Comment by cmsj** [comment]
Well that's embarrassing! I've added LUA_TBOOLEAN to the switch statement. I like the idea of LS_TANY, I'll take a look at that.
