### ISSUE TITLE
hs.uielement does not check its method arguments

### ISSUE THREAD

**Issue by AdamCanady** [Hammerspoon/hammerspoon#559]
Here's the code:
```lua
local function google()
  local text = hs.uielement:selectedText()
  hs.alert.show("Googling: " + text, 1.00)

  os.execute('open -a Google Chrome.app "http://google.com/?q="' + text) -- for testing only, this is incredibly bad security.
end
hs.hotkey.bind(mash, 'G', google)
```

Even just dropping `hs.uielement:selectedText()` in the console crashes the console and Hammerspoon.app.

Can anyone recreate this?

**Comment by cmsj** [comment]
`:selectedText()` is a method, so you'll need to be calling it on an object, such as:

```
local foo = hs.uielement.focusedElement()
local text = foo:selectedText()
```

I'd also suggest checking that its return isn't nil. This method depends on the object in question supporting accessibility features around text selection, which many apps, sadly, do not.

Nonetheless, we shouldn't be crashing in this scenario, I'll make sure that we at least avoid doing that :)
