### ISSUE TITLE
hs.drawing and not activating (bringing forward) Hammerspoon's console

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#565]
If we change the base class from NSWindow to NSPanel, we can set the windowStyleMask to NSNonactivatingPanelMask and hidesOnDeactivate to NO... I think that covers the only differences between NSWindow and NSPanel that apply to hs.drawing, but check me to make sure: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingPanels.html#//apple_ref/doc/uid/20000224

It's working for me well so far, but I've only really tested it for about 20 minutes now :-)

I'm trying something similar with hs.webview to allow dark titlebars (HUD) and this nonactivating behavior, but I can't seem to get around Esc closing the window whenever the window/panel is closable... I want that settable...

At any rate, should I submit a pull for the hs.drawing changes?  Should non-activating be a setting or the behavior for hs.drawing?

**Comment by cmsj** [comment]
Does clicking on drawing objects raise the console? (Sorry, away from my Mac atm)

**Comment by asmagill** [comment]
If they have a callbackOnClick set, yes.  I mitigated my earlier pain with this by having the console auto-close (appwatcher), but I stumbled across NSPanel recently (ok, I knew about it, but I finally read the docs for it 😝)... it's not as different from NSWindow as I first assumed.

**Comment by asmagill** [comment]
closed with #567
