### ISSUE TITLE
Totally minor typo

### ISSUE THREAD

**Issue by marcosscriven** [Hammerspoon/hammerspoon#568]
Title on this page is ```Relase``` notes (in the ```<head>``` tag):
http://www.hammerspoon.org/releasenotes/

Doesn't appear to be hosted in ```gh_pages```, otherwise I'd PR it.

**Comment by cmsj** [comment]
Good catch, thanks! Should be fixed momentarily when GH refreshes the site.
(also fwiw, we keep the website in a separate repo under the Hammerspoon org)
