### ISSUE TITLE
Window name character length affecting hinting performance?

### ISSUE THREAD

**Issue by joehanchoi** [Hammerspoon/hammerspoon#572]
I'm pretty sure the number of characters in the window name can considerably slow down the startup time of running the hinting module.

Regardless if I end up incorrect, can there be any way to limit the number of characters visible (or stored)? Can anyone point to some variables within the hinting extension? It's a little bit unwieldy to see window names stretching across the screen. Thanks!

**Comment by cmsj** [comment]
I think we did do something to limit the lengths here, but we shouldn't have ignored this Issue for over 18 months :/ Sorry!

Please feel free to re-open if this is still affecting you.
