### ISSUE TITLE
infinite loop in lua

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#573]
If I'm missing something obvious, feel free to mock me at will :-) but... is there a way, other than force quit or kill from the terminal, in Hammerspoon to break out of an infinite loop in the lua code?

I didn't do something this blatant, it was more subtle, but essentially reduced down to:

~~~lua
while(true) do end
~~~

**Comment by cmsj** [comment]
Short of refactoring everything so Lua runs on its own thread, I don't believe we can interrupt it if it's working :/

**Comment by cmsj** [comment]
(fwiw, having Lua on its own thread would be pretty excellent, but at this point it'd be an insane amount of work, and very hard to verify the correctness of the work)

**Comment by asmagill** [comment]
Actually, it looks like I can do something with debug.sethook, but the trick will be separating which lua_call ultimately originates from the console versus which ones originate from callbacks/timers/etc. so only the correct one gets stopped.

I've been experimenting with threading in my serial port module... the Lua stuff is still on the main thread - don't want to mess with that can of worms!  but the actual port listener runs on a separate thread and just updates an internal buffer which the main thread can siphon from either via callback or a specific read method. It's led me to think some about what could be safely put on a separate thread, but I agree the logistics and testing would be painful.

**Comment by asmagill** [comment]
FWIW, using debug.sethook mitigates this for loops in the lua code... bad C code can still crap things out.

See https://gist.github.com/asmagill/cf1d6398aecc2cee37af if interested.
