### ISSUE TITLE
hs.logger suggestion

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#580]
I admit I was skeptical about how useful hs.logger really would be at first (it seemed a lot of code for a relatively small gain) but I'm quickly warming to it...

A request -- I can't always recall what level I set certain debugging output to, so it would be nice to be able to adjust the current level up/down a level, or at least get the current level so I can add or subtract to/from it myself and set a new level from the console.

**Comment by lowne** [comment]
Good point, will do.

**Comment by lowne** [comment]
in #583

**Comment by lowne** [comment]
You can use `my_logger.level=my_logger.level+1` instead of get/setLogLevel
