### ISSUE TITLE
Airplay and hs.audiodevice

### ISSUE THREAD

**Issue by nkg** [Hammerspoon/hammerspoon#584]
If you have multiple airplay devices, only the first is returned via `hs.audiodevice.allOutputDevices()`

The reason for this; all AirPlay systems are listed under one AudioDevice (in the AudioSource list property).

It look trivial to return them.
http://joris.kluivers.nl/blog/2012/07/25/per-application-airplay-in-mountain-lion/

**Comment by cmsj** [comment]
Agreed, we should fix this. I'll close this particular issue, because this is really the same as #205. Thanks!
