### ISSUE TITLE
Do not use Java's jar command line tool to unzip the Hammerspoon-0.9.41.zip file

### ISSUE THREAD

**Issue by andrewgilmartin** [Hammerspoon/hammerspoon#586]
Not an issue, just a warning. Do not use Java's jar command line tool to unzip the Hammerspoon-0.9.41.zip file. Doing so results in an application that issues the following error

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Hammerspoon.app

Use unzip. I am running OS X 10.9.5 on a 2013 MacBook Pro.

**Comment by cmsj** [comment]
@andrewgilmartin I'm curious why you were using jar in the first place to do the unzip? Is that a common thing? If so maybe there are some zip settings we could change to make it work.

**Comment by andrewgilmartin** [comment]
I am primarily a Java developer and so jar is a very common tool for me to use.

**Comment by cmsj** [comment]
Ok thanks. Unless someone has some suggestions of ways we could make it work with jar, I think there's no action to be taken here, so I'm closing the issue.
