### ISSUE TITLE
Hints won't hint IntelliJ window

### ISSUE THREAD

**Issue by emosesSfdc** [Hammerspoon/hammerspoon#587]
IntelliJ Idea's main window has isStandard == false, so hints ignores it.  Apparently that window's role is AXWindow and it's subrole is AXDialog.  

Even if I explicitly pass that window in to hs.hints.windowHints(), it gets ignored, as all non-standard windows are ignored.  

Possible solutions that I see are a flag on windowHints to include non-standard windows, or if you explicitly pass in a list of windows, it should skip the isStandard check.

**Comment by cmsj** [comment]
#588 merged, so this should be closeable :)
