### ISSUE TITLE
The icon has jagged edges on non-Retina screens.

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#599]
I'm on a MacBookPro.  This wasn't always the case with the app icon for HS.  I first noticed this because the jagged edges are super glaring in Cmd-Tab.  I can't screenshot while Cmd-Tab is held (or rather, I don't know how), so I'm including a screenshot of the GetInfo window, which shows nearly-as-glaring jaggedness.

![jagged1](https://cloud.githubusercontent.com/assets/3311113/10402467/9675e390-6e93-11e5-81bb-0fb44b03267a.png)

**Comment by cmsj** [comment]
Thanks for pointing that out. This should be fixed by f09a693
