### ISSUE TITLE
0.9.42 -> hs.drawing.text(rect, msg) used to work with a "number" as the message

### ISSUE THREAD

**Issue by bradparks** [Hammerspoon/hammerspoon#601]
Hey! This is kind of minor, but just in case you weren't aware, the method

`hs.drawing.text(rect, msg)`

changed in 0.9.42 to accept only strings. In 0.9.41, it would accept a number as well, and I assume, converted it to a string automatically. 

I only noticed when I upgraded, and one of my scripts started failing that I was passing in a number and not converting it to a string first.

Version 0.9.42 (0.9.42)

**Comment by cmsj** [comment]
Thanks for letting us know about the regression :)
