### ISSUE TITLE
feature request: brightness control for external displays

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#603]
see https://github.com/kfix/ddcctl

- could live in `hs.brigthness` I suppose
- probably better to have some warnings in the docs and sanitise the input

**Comment by asmagill** [comment]
Since this seems to be narrowly targeted and potentially crash inducing, both to the system and the monitor, my initial thought is that it would be better as a third-party addition and pointed to in the Wiki, rather than something included in core... I don't know that we want to be fielding support questions/requests/bug reports for something that for at least some users could come down to "well, for your hardware, yeah... it crashes."

**Comment by lowne** [comment]
@asmagill all true, but I'd eventually use this in `hs.flux`; do you think that strongly worded warnings and disclaimers in the docs wouldn't be enough? (and ofc `hs.flux` itself would NOT set brightness to external displays by default; the user would have to explicitly request it after going through similar warnings)

**Comment by cmsj** [comment]
The commit I just pushed, adds `:setBrightness()` and `:getBrightness()` to `hs.screen`, using the same method that `hs.brightness` uses (i.e. IOKit). I expect this will only work on Apple's external displays, but it would be interesting to hear from folk with other external displays :)

(I tend to agree that things fiddling around with DDC directly, probably don't belong in-tree. We could design hs.flux to take this into account)

**Comment by lowne** [comment]
Neither method works on non-Apple external displays (tried with Dell and Philips) :/

**Comment by cmsj** [comment]
@lowne so how about we build a third party ddc_brightness module that hooks itself into hs.screen, then hs.flux (btw we cannot use that name, the f.lux people are too awesome to do that to) can have variables for brightness getter/setter methods :)

**Comment by lowne** [comment]
@cmsj if my understanding of "third party module" is correct, the problem with it is that it requires Xcode, manual build etc.; at that point the only difference would be "git clone [ddcctl vs hammerspoon-brightness-external], make, and `hs.flux.useDangerousBrightnessControl=true`" (ok, not the *only* difference, but a user wouldn't care if flux internally calls hs.brightness or hs.execute('ddcctl ...'). 
How about integrating non-kosher stuff like ddcctl, modules using undocumented APIs (asmagill's spaces module comes to mind), and (temporarily) other possibly-dangerous-or-not-ready-for-primetime modules (like `hs.task` mentioned in #629) into one or more segregated top level namespaces (`unsupported`, `dangerous`, `experimental`...), as opposed to the canonical, approved and sort-of-supported modules inside `hs`?

Also: I agree with the sentiment about the `hs.flux` name, but I can't come up with decent alternatives; suggestions welcome.

**Comment by cmsj** [comment]
@lowne I take your point about the difficulty of building third party modules. My concern with including them under a "dangerous" namespace, is that they'll get parcelled up into some useful script, which others will just grab and use, without noticing that it might set their GPU on fire or something :/

**Comment by lowne** [comment]
Fair point; but we can perhaps devise ways to avoid that scenario ("blind" copy/paste without full knowledge) by having the extra namespaces disabled (or dummy tables whose __index returns a no-op function), and making it quite hard (like explicitly having to run `make`) to enable them. Off the top of my head, something like `hs.enableDangerousStuff(MACaddress,'I fully understand the dangers, and word 5 of paragraph 2 on page 21 of the manual is "explode"')` (checking of course that the MAC address is indeed correct). (This example could even be a bit overkill :) )

**Comment by asmagill** [comment]
I have started (well, ok, only serial and console so far) providing compiled versions of my third party stuff... the end user still has to download them and in their hammerspoon directory (usually ~/.hammerspoon) type `unzip file`, but it doesn't require Xcode.

**Comment by cmsj** [comment]
@lowne I think the only "safe" way to enable dangerous stuff would be to have a core setting in the app - anything that can be done from Lua will just be set in the script that gets passed around.

Someone could definitely make a third party hs.ddc module and distribute it as a binary, but I think I would very much prefer not to be the person who does that - I don't want to fry my beautiful monitors as I dumbly try to port over code for sending DDC commands I don't understand!

**Comment by lowne** [comment]
@cmsj that's true of course, but I don't think we should be worrying about a malignant actor scenario... and even then, if someone wanted to cause indiscriminate damage by spreading rogue Hammerspoon scripts on the interwebs, I think they'd sooner use `hs.execute` directly (or even `io.open`) :)
Point being, a warning-like clearly named Lua flag to enable this is by itself sufficient (but further reinforced by the docs, which are pretty much required reading to get anything done with HS) to let well-intentioned people know that something is potentially dangerous, and apply the relevant common sense when publishing scripts using it.
As for the risk of physical damage, I'm willing to bet it's non-existent because 1. ddc has been around for 20 years and 2. we *only* need (and would implement/expose) brightness control, which exists in every monitor ever made; tbh I would have some trepidation with trying random flags or vendor-specific commands or whatnot with the raw `ddcctl`, (explicitly trying to *break things*) but even then, given the 20 layers of control logic between a kernel and a modern monitor's hardware (at least half of these within the monitor itself) I would still expect the worst possible breakage to be fixed after power cycling the monitor itself.

At any rate, this is certainly not a tentpole feature; if it can't be done for whatever reason, and if I do end up with an `hs.redshift` PR, I can certainly direct users to make a `ddcctl` executable, pass its path to the module, and YMMV.

**Comment by cmsj** [comment]
@lowne I'm not worried about malicious actors, it just takes one person to put together a script that sets the dangerous-is-ok flag in Lua and publish it, then other folk are at risk if they're not very carefully vetting every line of Lua scripts they find and use.

Even if we assume that physical damage is impossible, the ddcctl README makes it fairly clear that there is a good chance that either the OS X kernel, or the monitor, will crash.

As much as I dislike shelling out to external binaries, I think that is the way to go here. It forces users to go and look at ddcctl and think about whether it's a good idea at all, then it also forces them to understand that they need to experiment to find a non-crashy setup that works on their system.
