### ISSUE TITLE
How to handle API changes

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#608]
(EDIT: quote from @cmsj from #602 for context; I thought this deserved its own thread)

> I hate backwards compatibility stuff littered all over the place, but I also hate breaking working configs. I'm also increasingly conscious of the crash/download data suggesting to me that many users are going a long time between upgrades, so they won't see release note warnings about deprecations.
> I wonder if we could have a generic mechanism that presents a nice error about the use of deprecated stuff, and then assign any old variable/function/etc to that mechanism, so referencing the deprecated thing, will halt the app and let the user know what they used, and what they should be using?
> Bit complex, but every other option involves either endless complexity increases for us (which will cause regressions when we change something and forgot about its deprecated alias in another module), or confusing "why did my config start complaining about things being nil?" pain for users. Unless anyone else has bright ideas?

I agree that some sort of deprecation system is necessary; I've been thinking about it for a while, trying to figure out the easiest solution that's still general enough and not totally disrupting to users.

I think that _ideally_ there should be 4 "layers" of deprecation; over-simplifying:
1. at first, when a breaking api change is implemented, simply add a backward compatibility wrapper
2. later (say on the next release), print an error to console directing towards the new syntax for the deprecated functionality, but still have the user script work
3. later, print the error and stop - compatibility wrapper is removed
4. finally, remove all traces of the deprecation - the user script, if still not fixed, will error out normally - or, worst case, appear to still work but cause horrible problems downstream :)

Some notes:
- step 1 (the "timid" breaking change) is meant for cases where we're not totally sure a given change is a good idea and we can foresee a chance of reverting; included just for completeness, as common sense would probably dictate it already, and it wouldn't make use of a specialised deprecation infrastructure
- step 2 is meant to avoid the user scenario "HS autoupdated at night, next day the whole system is down, fixing it would take a long time for whatever reason, productivity severely hampered, urgent deadline under threat, <discourteous expletives>"
- ideally (still), the timings wouldn't be totally arbitrary; e.g. we could tag each deprecation with its creation date (otherwise we'd surely forget, and git bisect is no fun), and escalate to the next layer after an appropriate amount of time (to clarify, this would still involve manually editing the source and committing; automating it would be a bad idea imo, for a number of reasons)
- obviously everything is optional: step 1 is used rarely (if ever); steps 2 and 3 (or just 2) could be skipped if the API was very recent to begin with (so adoption can be assumed to be close to non existent), or if the module is explicitly marked as under development (which is what I do with hs.window.filter & friends)

Characteristics of the common infrastructure:
- allow flexible error messages, for helpful instructions in cases beyond "method A was renamed to B"
- simple to setup:
  - have a dedicated namespace (`deprecated`) and infer all sorts of things from its table structure; I have a feeling that all sorts of complications would arise
  - have "global" functions (say, `hs.deprecated...()`); seems probably a better choice, at least Lua side; not so simple to use from C, but LuaSkin could take care of that; I'll use this solution below
- able to handle
  - functions/methods: easy one, `hs.deprecatedFunction()` would just be a wrapper factory
  - fields (variables/constants/"fields"): more involved, as `hs.deprecatedField()` would need to use the `__index` and `__newindex` metamethods, and therefore take into account the existing metatable, if any, and insert itself in the chain; doable
  - function arguments: purity would require a full type checking system, and then it'd be a factory building all cases of "overloaded" methods; no. The pragmatic solution is to leave the type checking in the function itself and have `hs.deprecatedArgument()` be a simple convenience for printing the error

Thoughts? Did I leave something out? (I probably did)

**Comment by cmsj** [comment]
hs.webview handles this quite nicely, so if we want to expand it out from there we can do so. I'm going to close this issue.
