### ISSUE TITLE
Add hs.menubar:frame()

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#609]
It would be useful to know where on the screen the menubar items are. http://stackoverflow.com/questions/5413784/how-to-get-frame-for-nsstatusitem/10375784#10375784 may help, but we'll need to check that the proposed solutions work on 10.8.

**Comment by asmagill** [comment]
As long as it fails gracefully (i.e. in Lua and not with a crash), I think 10.8 support could be optional for a new feature... I'm more concerned about what the move in 10.11 to deprecating image and title (amongst others) in favor of using NSButton (which was only introduced in 10.10, I think) means for the future of this module...  We may end up needing 2 separate versions at some point.

**Comment by cmsj** [comment]
@asmagill if it wasn't evil to collect the data, I would love to know how many of our users are actually using 10.8, but given that we now technically support 4 major releases of OS X (even though we only test on 1 release), I think that whenever those functions are removed, we should really have dropped some of the older releases!

**Comment by asmagill** [comment]
At some point, we should... I do know that at least one user is/was using 10.8, and it would be nice if we could ensure that new things and changes don't crash on older OS versions but rather just don't work (maybe with an error, if possible), but... I don't know how much effort that will ultimately entail.

For now, they're just deprecated, not removed, so it's not a short term problem.
