### ISSUE TITLE
Input source change watcher sometimes does not fire

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#615]
Sometimes, the watcher configured through `hs.keycodes.inputSourceChanged()` does not fire. I have not been able to reliably reproduce the problem, sometimes it happens right after Hammerspoon restarts or reloads config, sometimes after my machine comes back from sleep, but other times it happens during regular operation. This code shows the problem:

```
function plainInputSourceChange()
   hs.alert.show("Input source change detected!")
end
hs.keycodes.inputSourceChanged(plainInputSourceChange)
```

Sometimes, pressing the source-input-change key (Alt-Cmd-space in my case) will not result in an alert being displayed.

**Comment by zzamboni** [comment]
I've noticed some indications that my use of Bartender may have something to do with this problem:

- If Bartender is not running, I can't seem to trigger it
- Every time I open the Bartender bar, the next keyboard-layout-change event consistently gets eaten
- After one such event gets eaten, I get the notification the next time I open the Bartender bar

**Comment by zzamboni** [comment]
It seems removing Hammerspoon from the Bartender menubar fixes the problem - thanks @lowne for the pointer!

**Comment by zzamboni** [comment]
@lowne: as per your suggestion on IRC, I just tested with a plain Hammerspoon config file, containing only the code snippet shown above, and without Bartender running. The problem still persists, but I did some additional testing, which reveals the following behavior:

- Immediately after Hammerspoon reloads its configuration (manually, through the "Reload config" menu item) **and after opening the Hammerspoon menu** (every time), the first keyboard-layout-change event (whether through the keyboard shortcut or the flag menu) is dropped. Further events fire correctly.
- The missing event fires **the next time the Hammerspoon menu is opened**. But as per the previous item, this causes the next event to be held.

I made a short screen recording that shows this behavior. Github doesn't let me attach it so you can find it here: https://www.evernote.com/l/AALhWdBz8Q1DmqLIEUur16ieWbbJq1Uu8co

**Comment by cmsj** [comment]
There are two things we should compare against ShowyEdge, one is that it uses the CF equivalent of the NS input changed notification, the other is that it specifies options when doing addObserver on the notification centre object

**Comment by cmsj** [comment]
(Note to self, see https://github.com/tekezo/ShowyEdge/blob/3976ab1182f703bda602c9c846bf668326d53237/AppDelegate.m#L272 for the notifications ShowyEdge uses)

**Comment by zzamboni** [comment]
Something weird I just noticed: if I run Hammerspoon from Xcode, this bug does not happen - the callback is fired every time the layout changes, even right after opening the Hammerspoon menubar menu. If I run **the same build** standalone, the bug occurs.

**Comment by cmsj** [comment]
Looks like that commit may well have fixed this :)

**Comment by zzamboni** [comment]
It does fix it, but unfortunately after a configuration reload, the next layout change event crashes Hammerspoon with this backtrace:

```
(lldb) bt
* thread #1: tid = 0xcdd4, 0x00007fff87d08bdb libobjc.A.dylib`realizeClass(objc_class*) + 41, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x40226)
    frame #0: 0x00007fff87d08bdb libobjc.A.dylib`realizeClass(objc_class*) + 41
    frame #1: 0x00007fff87d08cba libobjc.A.dylib`realizeClass(objc_class*) + 264
    frame #2: 0x00007fff87d0bbff libobjc.A.dylib`lookUpImpOrForward + 104
    frame #3: 0x00007fff87d0ae11 libobjc.A.dylib`objc_msgSend + 209
    frame #4: 0x00007fff8f342c9c CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    frame #5: 0x00007fff8f342c2f CoreFoundation`___CFXRegistrationPost_block_invoke + 63
    frame #6: 0x00007fff8f34c4dc CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    frame #7: 0x00007fff8f32bdf5 CoreFoundation`__CFRunLoopDoBlocks + 341
    frame #8: 0x00007fff8f32bb5b CoreFoundation`__CFRunLoopRun + 2347
    frame #9: 0x00007fff8f32afc8 CoreFoundation`CFRunLoopRunSpecific + 296
    frame #10: 0x00007fff8b881d55 HIToolbox`RunCurrentEventLoopInMode + 235
    frame #11: 0x00007fff8b881b8f HIToolbox`ReceiveNextEventCommon + 432
    frame #12: 0x00007fff8b8819cf HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 71
    frame #13: 0x00007fff8d973d96 AppKit`_DPSNextEvent + 1067
    frame #14: 0x00007fff8d9731c5 AppKit`-[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    frame #15: 0x00007fff8d967d28 AppKit`-[NSApplication run] + 682
    frame #16: 0x00007fff8d930fbe AppKit`NSApplicationMain + 1176
  * frame #17: 0x0000000100002f32 Hammerspoon`main(argc=3, argv=0x00007fff5fbff420) + 34 at MJAppDelegate.m:162
    frame #18: 0x00007fff87c7c5ad libdyld.dylib`start + 1
```
