### ISSUE TITLE
hs.screen:setMode() reduces frame rate

### ISSUE THREAD

**Issue by kbadk** [Hammerspoon/hammerspoon#617]
When running any resolution at 60 Hz on my 4K display, changing the resolution reduces the frame rate to 30 Hz.

For instance, if I'm running HiDPI 2560x1440 @ 60 Hz and calling 

```
hs.screen.mainScreen():setMode(1920, 1080, 2)
```

the resolution correctly changes to HiDPI 1920x1080, but the screen is now running at 30 Hz.

Maybe the desired frame rate could be added as an optional fourth parameter: 

```
setMode(width, height, scale, [framerate])
```

and/or the highest possible frame rate for the desired resolution could be automatically selected.

**Comment by cmsj** [comment]
I've poked around at the (unfortunately private) API we're using to query/set display modes and it seems like the frequency information is always 0. Have you used any other tools which support 60Hz correctly? (e.g. SwitchResX)

**Comment by kbadk** [comment]
I believe https://github.com/jhford/screenresolution does it correctly.

**Comment by cmsj** [comment]
@kbadk hmm, the machine I'm testing on (2015 12" MacBook) doesn't seem to show up correctly with that tool:

2015-10-28 23:17:49.119 screenresolution[3879:523459] Display 0: 1680x1050x32@0

(i.e. it thinks the refresh rate is 0, which matches up with I was seeing earlier, unfortunately)

**Comment by cmsj** [comment]
Actually, I think I have found a way to get the refresh rate using CoreVideo.framework :)

**Comment by kbadk** [comment]
For me, `screenresolution` correctly returns the hertz for all my displays, like:

    2015-10-28 18:26:03.373 screenresolution[41743:30580924] Display 0: 2560x1440x32@60

I have no knowledge of the Apple CG APIs, but when briefly skimming the source code of `screnresolution` and `/extensions/screen/internal.m`, it does seem like [`screenresolution` explictly interacts with CGDisplayModeGetRefreshRate](https://github.com/jhford/screenresolution/blob/master/cg_utils.c#L67) while Hammerspoon's Screen extension does not. Maybe that's an indication. :)

**Comment by cmsj** [comment]
GetRefreshRate() is what was returning zeros on my MacBook.

One question I do have, is whether screenresolution can set modes properly for you - like if you use Hammerspoon to change mode and get a 30Hz, can screenresolution get you back to 60Hz?

**Comment by cmsj** [comment]
ok, so it looks like the APIs used by screenresolution are not going to work out at all, they may be public APIs, but they are completely broken, at least on this hardware - screenresolution doesn't list the mode I'm using, and the APIs aren't finding any HiDPI (retina) modes at all.

This is intensely frustrating, but it seems like we are just stuck for now, whichever API we use is going to be broken for someone :(

**Comment by cmsj** [comment]
I'm going to close this because these APIs aren't changing, so clearly this is not something Apple wants us to be messing with. If someone knows of a way to make this work properly, I would love to know - please re-open the issue :)
