### ISSUE TITLE
Invalid application name for a URL Handler

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#618]
I use the urlredirector code from #257, and the name for TorBrowser is, IMO, incorrectly detected as Firefox. I know it is a modification of Firefox but for comparison [MultiBrowser.app](https://sites.google.com/site/tesseractsoftware/multibrowser) correctly lists it as TorBrowser. 

With TorBrowser and Firefox installed on OS X 10.11.1

```
local handlers = hs.urlevent.getAllHandlersForScheme('http')
for i = 1, #handlers do
    print(hs.application.nameForBundleID(handlers[i]))
end
```

Or just
```
print(hs.application.nameForBundleID('org.mozilla.tor browser'))
```

Is this an issue or should I be using a different API to get the correct name?

**Comment by cmsj** [comment]
This should be fixed in the next release, unless anyone has issues with the change I made ( @asmagill ?)

**Comment by junkblocker** [comment]
Thanks, @cmsj !

**Comment by asmagill** [comment]
go for it
