### ISSUE TITLE
fsevents

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#62]
This is a pretty huge and unfocussed area of work, but if we have deep support for FSEvents we can have Hammerspoon react to all sorts of file related events and trigger powerful automation events.

To pick some random examples that people might want to configure:

Move files in Desktop/ 30 minutes after they were last touched, to another folder (perfect for OCD Neat Freaks ;)
Move PDF files from Downloads/ into the user's document archive folder
Display a notification to the user when a new launchagent/launchdaemon plist is added to any of the folders that contain them
Trigger an import into iPhoto/Aperture/etc when a new file lands on the desktop with a name suggesting it's a screenshot, and an appropriate MIME type
(and for full bonus points...... \* Search a new PDF in a particular folder for keywords and move it to a different folder depending on what is found)

**Comment by junkblocker** [comment]
Not sure if it is possible via FSEvents but I've had to do resolve symlinks for pathwatcher myself if the `.hammerspoon` directory and/or the lua files are symlinks.

**Comment by cmsj** [comment]
Closing, pretty sure `hs.pathwatcher` covers these needs.
