### ISSUE TITLE
Can't specify right command or option keys as modifier

### ISSUE THREAD

**Issue by mattharrison** [Hammerspoon/hammerspoon#621]
Hi I'm trying to dedicate a key to Hammerspoon, rather than some 3 character chord. I would like to use right command or option (still want to preserve default functionality of left control and command). When I try to use the keycode number for those keys, they are just ignored.

Is this a feature? :)

**Comment by cmsj** [comment]
@mattharrison you can't use a keycode for a modifier, and you can't bind hs.hotkey events to just one of the option keys - the level that we collect keyboard events doesn't distinguish between the left/right variants.

My suggestion would be to use Karabiner to remap right command/option to cmd+option+shift+ctrl. It's such a silly modifier set that you end up clashing with almost no applications, and you can map almost the whole keyboard to Hammerspoon shortcuts (I do exactly that, but using CapsLock as my Hammerspoon modifier)

**Comment by mattharrison** [comment]
Thanks for the suggestion. For future reference of others here's my karabiner xml:

    <?xml version="1.0"?>
    <root>
    <item>
        <name>Right Command to alt, command, control</name>
        <identifier>private.Swap_fn_right_Command</identifier>
        <autogen>__KeyToKey__ KeyCode::COMMAND_R, KeyCode::COMMAND_R | ModifierFlag::COMMAND_R | ModifierFlag::OPTION_R | ModifierFlag::CONTROL_R</autogen>
    </item>
    </root>

Then in my hammerspoon config (``init.lua``) I put something like this:

    local hyper = {"cmd", "alt", "ctrl"}
    hs.hotkey.bind(hyper, "1", sizeup.send_resolution1)
