### ISSUE TITLE
feature request: support images in hs.pasteboard

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#626]
I don't know about other people, but I use ⌘⌃⇧4 all the time to take partial screenshots to the clipboard, frequently to upload to imgur.

In Chrome on https://imgur.com, you can then ⌘V with image data in your pasteboard and hit go. Very easy. Unfortunately it doesn't work in Safari, which I prefer these days for general browsing. Why not just set up a hotkey to upload it to imgur and return the url to the pasteboard? Seems relatively easy and something I definitely want. 

Right now hs.pasteboard is hardcoded to use `NSPasteboardTypeString`. I think we should also support `NSPasteboardTypePNG` since I can think of a number of useful utilities to make with it as an 'image-heavy' user. There are a bunch of [`NSPasteboardTypes`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSPasteboard_Class/#//apple_ref/doc/constant_group/Types_for_Standard_Data_OS_X_v10.6_and_later_) but I imagine text/images cover >99% of use cases. I am willing to implement this myself but I would like some advice on the preferred way to get the data to Lua land. Probably best just to have something explicit like `hs.pasteboard:getImageContents` and leave `getContents` alone for now.

I had started to ask the best way to get an `NSImage` to Lua space, but found an example in `hs.image.imageFromPath` using `[[LuaSkin shared] pushNSObject:]`. I was then going to ask how to 'cast' the Lua-loaded `NSObject` to `hs.image` (I'm new at all this low level language interfacing business), but decided to just build and try it and it automagically worked and returned a valid `hs.image`, I suppose because of `[[LuaSkin shared] registerPushNSHelper:NSImage_tolua forClass:"NSImage"]` in `hs.image`. Great!  It looks like `userdata_gc` in `hs.image` properly releases the NSImage.

It seems I finished it and will create a pull request if there are no objections.

```objc
static int pasteboard_getImageContents(lua_State* L) {
    NSImage *image = [[NSImage alloc] initWithData:[lua_to_pasteboard(L, 1) dataForType:NSPasteboardTypePNG]];
    
    if (image && image.valid) {
        [[LuaSkin shared] pushNSObject:image];
    } else {
        return luaL_error(L, "No valid image data in pasteboard");
    }
    
    return 1;
}

//...

static const luaL_Reg pasteboardLib[] = {
//...
    {"getImageContents", pasteboard_getImageContents},
//...
};
```

**Comment by asmagill** [comment]
+1

This is exactly the kind of thing I hoped the pushNSObject suite of methods would make easier!

You probably want to add the line `require("hs.image")` to the pasteboard's `init.lua` file (you don't have to save it's result anywhere, though)... that will make sure that no matter what order the user loads modules, the NSHelper function for hs.image is installed.
