### ISSUE TITLE
hs.application.kill and hs.application.kill9 documentation error?

### ISSUE THREAD

**Issue by jelen-dev** [Hammerspoon/hammerspoon#628]
Hi, so awesome API! As someone described already, I am like kid in candy shop. My MAC can now do magic! 

I was using kill and kill9 methods lately like this:

local appHyperSwitch = hs.application.find("hyperswitch")
if(appHyperSwitch ~= nil) then
    appHyperSwitch.kill9(appHyperSwitch)
end

In documentation kill and kill9 should have no parameters but the .lua console gave me error if I didnt use it like this.

**Comment by lowne** [comment]
See http://lua-users.org/wiki/ColonForMethodCall - these methods have no parameter because you're expected to use the colon syntactic sugar on an application object: `appHyperSwitch:kill9()`

**Comment by jelen-dev** [comment]
Oh, my bad then - I am new to lua and I tryed ":" once when playing with the tool and it produced error (most likely for some other reason) so I thought ":" is not lua syntax.
