### ISSUE TITLE
Unable to find userdata object for NSTask object

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#632]
Sometimes, for no apparent reason, the HS console appears and tells me this:
```
Unable to find userdata object for NSTask object. Please file a bug
stack traceback:
```

Nothing is listed below "traceback".  But it says to file a bug, so here I am :)

**Comment by cmsj** [comment]
Thanks. This seems fairly harmless, it's a task that's reporting in after the Lua state has been destroyed (i.e. on a config reload). I've made the handler safe and turned off the error.
