### ISSUE TITLE
More mysterious hs.task error messages

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#633]
When HS has been up and running for a while, but only after a longish while, I begin to see the following in my console:
```
ERROR: Unable to launch hs.task process:
Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9
```
It repeats a zillion times, I presume every time one of my timers that set up an `hs.task` fires.  Unfortunately I have no idea what that error means or what I might be doing wrong.

Then I see the following, which makes no sense to me.  Clearly HS thinks it's supposed to be loading `appfinder`, but nothing in my init.lua uses `appfinder`.  I only use hotkey, geometry, alert, drawing, timer, task, and ipc.  Does one of these implicitly or "undocumentedly" use appfinder?

```
-- Loading extension: appfinder
...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:238: module 'hs.appfinder' not found:
	no field package.preload['hs.appfinder']
	no file '/Users/chdiza/.hammerspoon/hs/appfinder.lua'
	no file '/Users/chdiza/.hammerspoon/hs/appfinder/init.lua'
	no file '/usr/local/share/lua/5.3/hs/appfinder.lua'
	no file '/usr/local/share/lua/5.3/hs/appfinder/init.lua'
	no file '/usr/local/lib/lua/5.3/hs/appfinder.lua'
	no file '/usr/local/lib/lua/5.3/hs/appfinder/init.lua'
	no file './hs/appfinder.lua'
	no file './hs/appfinder/init.lua'
	no file '/Applications/.storage/Hammerspoon.app/Contents/Resources/extensions/hs/appfinder.lua'
	no file '/Applications/.storage/Hammerspoon.app/Contents/Resources/extensions/hs/appfinder/init.lua'
	no file '/Users/chdiza/.hammerspoon/hs/appfinder.so'
	no file '/usr/local/lib/lua/5.3/hs/appfinder.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './hs/appfinder.so'
	no file '/Applications/.storage/Hammerspoon.app/Contents/Resources/extensions/hs/appfinder.so'
	no file '/Users/chdiza/.hammerspoon/hs.so'
	no file '/usr/local/lib/lua/5.3/hs.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './hs.so'
	no file '/Applications/.storage/Hammerspoon.app/Contents/Resources/extensions/hs.so'
stack traceback:
	[C]: in function 'rawrequire'
	...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:238: in function 'require'
	...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:173: in metamethod '__index'
	...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:74: in field 'toggleConsole'
	/Users/chdiza/.hammerspoon/init.lua:339: in function </Users/chdiza/.hammerspoon/init.lua:339>
stack traceback:
```

**Comment by cmsj** [comment]
Good catch, thanks. This should be fixed now, please pull/rebuild and let me know!

(also, what sort of timeframe are we talking for "longish while"?)

**Comment by chdiza** [comment]
> This should be fixed now, please pull/rebuild and let me know!

Will test later today.

(also, what sort of timeframe are we talking for "longish while"?)

Sorry :)  90-120 minutes or so.  Enough time for all geeklets to refresh once.  (Some of them are on timers that only fire every hour, others every five seconds).

**Comment by cmsj** [comment]
@chdiza ok thanks, I suspect it was the five seconds ones that were causing it.

As for the hs.appfinder thing - hs.toggleConsole() uses it, and it should be part of the Hammerspoon.app bundle. Not quite sure why you're seeing that error. Might be worth doing Product->Clean in Xcode.

**Comment by chdiza** [comment]
> Might be worth doing Product->Clean in Xcode.

I've been building it without opening Xcode, by doing "make" at the cmdline.  I'll test your Xcode method later today.
