### ISSUE TITLE
Map support?

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#635]
It would be pretty easy to have hs.drawing support maps (via https://developer.apple.com/library/mac/documentation/MapKit/Reference/MKMapView_Class/index.html#//apple_ref/occ/cl/MKMapView ) and possibly also hs.image. I don't immediately have a use for this, but maybe others do?

**Comment by heptal** [comment]
Possible caveat: it seems MapKit along with a few other frameworks [won't work](http://apple.stackexchange.com/questions/174230/mac-app-enterprise-distribution-outside-appstore-with-mapkit) without being a fully App-Storified app. From Apple:
>[To use the features of the Map Kit framework, turn on the Maps capability in your Xcode project (doing so also adds the appropriate entitlement to your App ID). Note that the only way to distribute a maps-based app is through the iOS App Store or Mac App Store.](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/MapKit/MapKit.html)

**Comment by cmsj** [comment]
hmm, bah, good point. If it had to be a web view then people can already do that with `hs.webview`, so I guess this issue is now unnecessary. Thanks for pointing it out :)

**Comment by asmagill** [comment]
I know its not what the request intended, but we can do address lookups and long/lat lookups and manipulate the Maps application itself...  https://github.com/asmagill/hammerspoon_asm/tree/master/geocoder.  It needs to be documented, but there are a couple of examples at the top of the internal.m file.

Should I add this to hs.location, or another module, or keep it as third-party?

**Comment by cmsj** [comment]
@asmagill I think it comes down to how stable it is to be opening the MapKit dylib directly (e.g. it only appeared in 10.9 AFAIR, and may move location in the future). I'm not opposed to adding it, but I don't see myself using it at all, so I likely wouldn't notice if it broke (although I suppose Travis might)

**Comment by asmagill** [comment]
If it were included in core, the library would be included at compile time... I only use the loadlib function because its *not* in any of the other modules and therefor not included normally.  You are right about the OS version though... however, I suspect that the module wouldn't load (missing symbols) on 10.8 anyways.

**Comment by cmsj** [comment]
This doesn't seem to have gone anywhere, so I'm going to close it out for now.
