### ISSUE TITLE
hs.image:setImageFromPath() doesn't work

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#636]
Put this in your init, where string1 and string2 are paths to two different jpegs on your machine.
```lua
foo = hs.drawing.image(hs.geometry.rect(1000,200,100,100),  string1 )
foo:show()
foo:setImageFromPath(string2)
```
Expected behavior: HS changes the image displayed by the drawing object foo into the image living at string2.  I expect this because of [the docs](http://www.hammerspoon.org/docs/hs.drawing.html#setImageFromPath).

Actual behavior: The console appears and says `attempt to call a nil value (method 'setImageFromPath')`.

Unless I'm confused here, either the docs are wrong or there is a bug in hs.drawing.

**Comment by cmsj** [comment]
Good catch, thanks!

**Comment by chdiza** [comment]
The sample code above now works, but :setImageFromPath() is still buggy in at least the following respect.  Where path1 and path2 are paths to two different jpegs on your machine, put the following in your init:
```lua
bar = "path2"
foo = hs.drawing.image(hs.geometry.rect(1000,200,100,100),  "path1" )
foo:show()
foo:setImageFromPath(bar)
```
Expected behavior: HS changes the image displayed by the drawing object foo into the image living at path2.

Actual behavior: The console appears and tells me: 
```
Unable to load image: path2
stack traceback:
	[C]: in function 'hs.image.imageFromPath'
	...on.app/Contents/Resources/extensions/hs/drawing/init.lua:77: in method 'setImageFromPath'
	/Users/chdiza/.hammerspoon/init.lua:207: in main chunk
	[C]: in function 'xpcall'
	...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:270: in main chunk
stack traceback:
	...ns/.storage/Hammerspoon.app/Contents/Resources/setup.lua:271: in main chunk
```

**Comment by cmsj** [comment]
@chdiza is there anything in the system log? (i.e. in Console.app)

I tested locally with the two image files that happen to live in my .hammerspoon/ folder (albeit they're PDFs, but they load as images) and it worked fine

**Comment by chdiza** [comment]
There's nothing in the Console.app that isn't "usually" there.  E.g., I see these things:
```
Unknown class 'SUUpdater', using 'NSObject' instead. Encountered in Interface Builder file at path /Applications/.storage/Hammerspoon.app/Contents/Resources/MainMenu.nib.

Could not connect action, target class NSObject does not respond to -checkForUpdates:

SecTaskLoadEntitlements failed error=22

disable_update_timeout: UI updates were forcibly disabled by application "Hammerspoon" for over 1.00 seconds. Server has re-enabled them.

common_reenable_update: UI updates were finally reenabled by application "Hammerspoon" after 1.11 seconds [0.90fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
```

But those seem to appear at regular intervals ever since I started playing around with HS again.

**Comment by chdiza** [comment]
OK, the last bit was because of a stupid typo by me.

But there's yet a third case that's giving me fits.  I have as the callback fn for an hs.task a fn called `show_results(exitCode, stdOut, stdErr)`.  In the relevant context, this fn is supposed to display an hs.drawing.image via :setImageFromPath, where the path *is* the `stdOut` that's passed to `show_results()`.  (The hs.task calls an image-fetching script, which after fetching the image, prints the path of that image to stdout.)

No matter what I do, HS will not display that image.  I know it's there, I know I didn't typo the path, etc.  Interestingly, it doesn't cause the HS Console to appear, either.  Would there perhaps be some manipulation of `stdOut`, as it is given to `show_results()` to prepare it for serving as a path?  Is it not a string object, e.g.?

**Comment by asmagill** [comment]
make sure it doesn't have a trailing newline... that's bitten me more than once with output from shell commands.  What I usually do is something like this: `(myString:gsub("[\r\n]", ""))`  (the extra parens are because gsub returns 2 values -- the modified string and the number of changes made.  By adding the parens around it, only the first value is kept, even in cases where multiple values are valid like `print`)

**Comment by chdiza** [comment]
@asmagill Thank you, thank you!  Your solution works.  An even easier one is for my image-fetching scripts to use `echo -n the_path` rather than `echo the_path`.

**Comment by cmsj** [comment]
We might want to filter out \r and \n in methods like this
