### ISSUE TITLE
Trouble with hs.window:setSize()

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#637]
The following window-resizing function used to work for me way back when.  It's not working now, and I don't know why.  To reproduce: make your init file just the following:
```lua
require "hs.window"

function testing_fn(xinc, yinc)
  local win = hs.window.focusedWindow()
  local cursize = win:size()
  cursize.w = cursize.w + xinc
  cursize.h = cursize.h + yinc
  win:setSize(cursize)
end
```

The Console appears with chokeage wrt hs.window.setSize():
```
...oon.app/Contents/Resources/extensions/hs/window/init.lua:405: Cannot create geometry object, wrong arguments
```

I can't see what I'm doing wrong.  I tried most of the other ways to make a size-object (including just making one from scratch like `{w=600, h=500}`), and none of those work either.

It is of course possible to work around this by using `hs.window.setFrame()` instead, but that's more steps, and anyway, the above used to work beautifully when I was last using HS as a window manager.

**Comment by nonissue** [comment]
If you change `win:setSize(cursize)` to `win:setSize(cursize.w, cursize.h)` it resizes the window as expected as far as I can tell. I don't have much time, but I'm guessing it's because it's using the hs.geometry object constructor now. Might be worth reading over the API for hs.geometry. If you can't figure it out, I'll have a closer look tomorrow.

**Comment by chdiza** [comment]
If you're right, then the source of my problem is that docs for `window:setSize()` are wrong, because they say that the one argument that should be passed to it is "A size-table containing the width and height the window should be resized to".  I tried all manner of doing that, and it never worked.  If I put a table between those parenths, I get the error message.  Your suggestion, which I haven't yet had a chance to test, is to not put a table in the parenths, but rather two numbers.

> it's using the hs.geometry object constructor now

Does this mean that any args passed to `window:setSize` are silently run through the `hs.geometry.size()` constructor first?  If so, then the same is apparently not done for related geometry methods like `setFrame()` and `setTopLeft()`, because I pass them tables and they work.

**Comment by nonissue** [comment]
That was a super quick fix, thanks @lowne

**Comment by cmsj** [comment]
Thanks everyone :)
