### ISSUE TITLE
Add a .clang-format

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#641]
I think it might be appropriate for us to have an official `.clang-format` in the repo, since we have a number of different styles of ObjC going on in the repo atm.

This sort of thing always makes for a very painful commit, because we'd suddenly be changing lots of non-code stuff in every file, but I think it's worth the pain in the long run.

My suggestion for the contents of the file (which works with the current version of clang-format in homebrew, 2015-07-31 at the time of writing) is:

```

---
BasedOnStyle: LLVM
AlignAfterOpenBracket: 'true'
AlignConsecutiveAssignments: 'true'
AlignOperands: 'true'
AlignTrailingComments: 'true'
AllowAllParametersOfDeclarationOnNextLine: 'false'
AllowShortBlocksOnASingleLine: 'false'
AllowShortCaseLabelsOnASingleLine: 'false'
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: 'false'
AllowShortLoopsOnASingleLine: 'false'
AlwaysBreakAfterDefinitionReturnType: 'false'
AlwaysBreakBeforeMultilineStrings: 'true'
BinPackArguments: 'false'
BinPackParameters: 'false'
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach
BreakBeforeTernaryOperators: 'false'
ColumnLimit: '0'
DisableFormat: 'false'
IndentCaseLabels: 'true'
IndentWidth: '4'
IndentWrappedFunctionNames: 'false'
Language: Cpp
ObjCBlockIndentWidth: '4'
ObjCSpaceAfterProperty: 'true'
ObjCSpaceBeforeProtocolList: 'true'
PointerAlignment: Right
SpaceAfterCStyleCast: 'false'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: 'false'
SpacesInCStyleCastParentheses: 'false'
SpacesInContainerLiterals: 'false'
SpacesInParentheses: 'false'
SpacesInSquareBrackets: 'false'
TabWidth: '4'
UseTab: Never

...
```

Is anyone strongly for-or-against doing this? (Also, if anyone knows of a similar thing for Lua, that might be worth looking into too)

**Comment by cmsj** [comment]
@asmagill as you're mainly the other ObjC contributor, I'd like your thoughts on this, if you have any - particularly also because our styles of formatting code are slightly different :)

(said thoughts may cover subject such as whether we should do this at all, or specific formatting choices)

**Comment by asmagill** [comment]
Other than habit and what I'm used to seeing, I don't really have strong thoughts one way or the other... if nothing else, the differing styles tend to make me more aware of what's my code versus someone else's, though at times I do try to match the surroundings if my additions are pretty minor.

I've never used a .clang-format file before, and most of my coding is done in BBEdit, not Xcode... don't know if it has a parser built in or if I'd have to add a filter to my Makefiles.

**Comment by cmsj** [comment]
I'm going to close this. We have enough work without throwing in painful formatting transitions into the mix.
