### ISSUE TITLE
0.9.43 crash upon configuration reload

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#642]
Hammerspoon 0.9.43 crashed when I triggered a configuration reload. Attached crash report. I have not been able to trigger it again.

[Hammerspoon_2015-11-18-130935_UM00104.crash.txt](https://github.com/Hammerspoon/hammerspoon/files/37803/Hammerspoon_2015-11-18-130935_UM00104.crash.txt)

**Comment by cmsj** [comment]
@zzamboni I'm going to close this because it's super old. I still want to fix crashes though :)
