### ISSUE TITLE
0.9.43 sporadic hangs

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#643]
A few times Hammerspoon 0.9.43 has "beachballed". The first sample happened after unplugging headphones (which triggers an audio device watcher in https://github.com/zzamboni/oh-my-hammerspoon/blob/master/plugins/audio/headphones_watcher.lua) and the second on triggering a configuration reload.
[Sample of Hammerspoon.txt](https://github.com/Hammerspoon/hammerspoon/files/37830/Sample.of.Hammerspoon.txt)
[Sample of Hammerspoon2.txt](https://github.com/Hammerspoon/hammerspoon/files/37831/Sample.of.Hammerspoon2.txt)

**Comment by junkblocker** [comment]
Me too to both the issues. I was running fine at around https://github.com/Hammerspoon/hammerspoon/commit/855268dada28a3adb8295402d73c411667443ce3

**Comment by cmsj** [comment]
@junkblocker interesting. Not very much changed between that commit and release. The big thing was Crashlytics. Out of curiosity, try disabling crash uploading in our Preferences and quit/restart Hammerspoon, to completely disable Crashlytics. I doubt that's the cause, but it would be good to eliminate it.

**Comment by junkblocker** [comment]
I always have Crashlytics disabled. I noticed and issue where I swap between git and release builds and that had left a stale app launching from someplace. I've fixed that and will need to see if that makes things go good again.

**Comment by junkblocker** [comment]
Ok, probably self caused issues here. I closed the lid at work, got home, did a system restart and got the 'Update error' dialog mentioning DSA keys again. Noticed two Hammerspoon instances had launched. Then remembered having seen and cleared multiple Hammerspoon instances in Login items recently. Went to check again and of course there are 3 instances sitting there again. Two of these are from my `~/Applications` folder and one is from `~/Library/Developer/Xcode/DerivedData/Hammerspoon-<gobbldygook>/Build/Products/Release` . I am not familiar with Xcode's workings at all. I was assuming build output only appeared in `<Hammerspoon_workspace>/builds/` or something only which I've been moving to `~/Applications/` WHEN I do source builds. I also doing a make clean after.

No crashes seen otherwise all day.

**Comment by heptal** [comment]
It's often necessary to `rm -rf ~/Library/Developer/Xcode/DerivedData/MyProject-hghjhjhkjh`. 

I have an alias to simply delete all the contents of DerivedData: 
`alias nuke-derived-data='rm -rf ~/Library/Developer/Xcode/DerivedData/*'`

**Comment by asmagill** [comment]
FWIW, I use the following script for rebuilds... haven't had an incorrect copy of Hammerspoon start up in a while...

~~~sh
#! /bin/bash

cd /opt/amagill/src/hammerspoon/hammerspoon
osascript -e 'tell Application "Hammerspoon" to quit'
#killall Hammerspoon
make clean
make #&& open /System/Library/PreferencePanes/Security.prefpane || exit 1
make docs
#rm -fr ~/Library/Developer/Xcode/DerivedData/Hammerspoon*
rm -fr `xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration DEBUG -showBuildSettings | sort | uniq | grep " BUILT_PRODUCTS_DIR =" | awk '{ print $3 }'`/Hammerspoon.app

# signing with self-signed cert so I no longer have to reset accessibility all the time
codesign --verbose --sign "Internal Code Signing" "build/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A"
codesign --verbose --sign "Internal Code Signing" "build/Hammerspoon.app"
open -a /opt/amagill/src/hammerspoon/hammerspoon/build/Hammerspoon.app
~~~

**Comment by junkblocker** [comment]
Thanks, @heptal  and @asmagil ! Great to know that self signing is possibly! It's all going into my script :)

**Comment by junkblocker** [comment]
I am still ending up with an extra instance of Hammerspoon in Login items on every build though now they both point to the correct and only app `~/Applications`. Here's my script `get_hammerspoon` for reference:

```sh
#!/usr/bin/env bash
set -e
me="${0##*/get_}"
if [ "$(uname -s)" != "Darwin" ]; then
  echo "$me is only available for Darwin" >&2
  exit 1
fi
running=0
ps auxwww | grep -q '/[A]pplications/Hammerspoon.app/Contents/MacOS/Hammerspoon' && running=1
close_hammerspoon() {
  echo -n "Ensuring Hammerspoon is not running ... "
  osascript -e 'tell Application "Hammerspoon" to quit'
  echo done.
}
if [ -z "$1" ]; then
  download_url="$(curl -s 'https://api.github.com/repos/Hammerspoon/hammerspoon/releases/latest'|grep -Eo '"browser_download_url":"[^"]+'|grep -Eo 'http.*')"
  echo "Installing to ${HOME}/Applications"
  cd "$HOME/Applications"
  rm -f Hammerspoon.zip
  curl -s -L -o Hammerspoon.zip "$download_url"
  close_hammerspoon
  rm -rf Hammerspoon.app
  unzip -o Hammerspoon.zip && rm Hammerspoon.zip
  [ $running -ne 0 ] && open ~/Applications/Hammerspoon.app
  exit 0
elif [ "x$1" = "xgit" ]; then
  [ ! -d ~/work/exp/Hammerspoon ] && mkdir -p ~/work/exp
  cd ~/work/exp
  if [ ! -d hammerspoon ]; then
    git clone --recursive --depth 1 'https://github.com/Hammerspoon/hammerspoon.git'
    cd hammerspoon
  else
    cd hammerspoon
    echo "Updating sources"
    git pull --recurse-submodules=yes --stat --ff-only --no-log --all --depth 1
  fi
  echo "Installing to ${HOME}/Applications"
  mkdir -p "${HOME}/Applications"
  close_hammerspoon
  rm -rf ~/Applications/Hammerspoon.app
  make clean
  make
  rm -rf "$(xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration DEBUG -showBuildSettings |grep -E '\bBUILT_PRODUCTS_DIR ='|awk '{print $3}')"
  # codesign with a self signed certificate we created to avoid fixing Accessibility every time
  codesign --verbose --sign "Internal Code Signing" "build/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A"
  codesign --verbose --sign "Internal Code Signing" "build/Hammerspoon.app"

  mv build/Hammerspoon.app "${HOME}/Applications/"
  set +e
  make clean
  [ $running -ne 0 ] && open ~/Applications/Hammerspoon.app
else
  echo "Usage: $me [git]"
  exit 1
fi
echo "Done."
exit 0
```

I do
```
get_hammerspoon git
```
.

**Comment by cmsj** [comment]
@junkblocker I'm not super familiar with how the login item stuff works, but it might be easiest to disable our setting for launching automatically at login, and just drag Hammerspoon.app into the Login Items section of the Users & Groups system prefs

**Comment by junkblocker** [comment]
@cmsj, that does seem to work. Should I create a bug out of this?

**Comment by junkblocker** [comment]
Issue #648 created for login items.

**Comment by chdiza** [comment]
FWIW, `codesign --verbose --sign "Internal Code Signing" "build/Hammerspoon.app"` results in an error about "No identity found" or something like that.

**Comment by junkblocker** [comment]
@chdiza : You have to create a (self) signing cert called 'Internal Code Signing' and save it in the default keychain etc. before it will work. See [here](http://bd808.com/blog/2013/10/21/creating-a-self-signed-code-certificate-for-xcode/) for example instructions.

**Comment by chdiza** [comment]
@junkblocker Thanks!

**Comment by zzamboni** [comment]
I haven't seen the hang in a while, so I'll close this for now. This thread was worth its weight in gold just because of @asmagill's script, which I'm now using and where I learned how to avoid having to reset accessibility options for every new build. Thanks!
