### ISSUE TITLE
One of the Nov20th commits caused huge RAM usage spike

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#650]
Without changing my init file in any way, I pulled and built the Nov 20th commits.  Prior to this, HS used about 24MB of RAM on first launch.  After the pull and build, it uses 144MB of RAM on first launch.

I can duplicate this on multiple machines.

Obviously I'm no programmer, but I don't use an audiodevice stuff and I do disable the HS menubar, so my money's on the menubar detachment commit.

I'll bisect now.

**Comment by chdiza** [comment]
Correction: One of the November 18th commits caused it, namely 83f0702ab9e2.

Let me see if I can successfully make a non-debug build.

**Comment by chdiza** [comment]
The problem with making a non-debug build is that I run into code-signing problems.  @cmsj  I followed your instructions [here](https://github.com/Hammerspoon/hammerspoon/issues/597#issuecomment-154112870), but whenever the resulting HS is fired up I get an "Insecure Update Error!" Dialog box.

**Comment by cmsj** [comment]
@chdiza wow, I hadn't noticed how insane the RAM usage was there, but my normal local config was up to 700MB. Real shame, this should have been a great way to catch bugs, but there we go. It's off now. Thanks!

**Comment by chdiza** [comment]
I might be willing to leave it on if I knew what to be looking for, just for future reference.

**Comment by asmagill** [comment]
better would be some way to build with it and without it (ideally from the command line)... as I indicated in #645, having "Address Sanitization and NSZombie detection" enabled made identifying my random seeming crashes immediately obvious.

**Comment by chdiza** [comment]
I'd also be willing to just build a non-debug build if I could get past the code signing.

Agreed on the "from the command line" part.

**Comment by lowne** [comment]
can't it be left active for regular debug builds?

**Comment by heptal** [comment]
It's easy to enable if you're investigating memory issues in Edit Scheme... > Run -> Diagnostics.

**Comment by cmsj** [comment]
@lowne I do want to bring it back at some point. If Release builds work for folk who don't have the official signing key, then yes I think we should have these options on the debug build

**Comment by cmsj** [comment]
Or maybe we add a new Full Debug scheme
