### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#658]
I get the following intermittently:
```
...app/Contents/Resources/extensions/hs/styledtext/init.lua:453: bad argument #2 to 'setStyle' (starts index must be < ends index)
stack traceback:
	[C]: in method 'setStyle'
	...app/Contents/Resources/extensions/hs/styledtext/init.lua:453: in function 'hs.styledtext.ansi'
```

One of my "geeklets" occasionally spawns this, but usually does not.  (I don't know which geeklet it is.)  That makes me think that hs.styledtext is choking on some of my ansi-colored things, when certain kinds of stdout is generated by the script that the geeklet runs.

**Comment by chdiza** [comment]
Forgot to add that further down on the console is a line reference to the geeklet's callback fn.  All my shell-geeklets have the same callback fn.

**Comment by chdiza** [comment]
Now that I pulled the latest commit, I get the error almost constantly.  I know which geeklet it is.  All it does is call a shell script that calls `netstat` and trims it down a put and colorizes certain lines.  I've had my eye on this one for a while, since it occasionally just "freezes".  Via the console I know that it's timer is running, creating hs.tasks, and the callbacks for those hs.tasks are being called; but they fail to `:setStyledText()` on the geeklet's hs.drawing object.

By some chance is there a limit on how long the lines of `stdOut` can be in an hs.task?  Or a limit on how long a line fed to hs.styledtext.ansi can be?

**Comment by asmagill** [comment]
The limits should be the limits of lua itself, so I really doubt that's the issue.  I suspect that the starts and ends index are ending up identical (i.e. an empty range)... going to have to think about the best way to handle that, as the same indexing conversion code is used in a number of places and any changes should apply to all.

To confirm, try the following styled-text version -- it gives a more verbose error for styledText:

https://github.com/asmagill/hammerspoon-config/blob/master/__debugging/styledtext-test.tgz?raw=true

Download the file, and do the following:

~~~sh
cd ~/.hammerspoon # or whatever config directory you're using
tar -xzf ~/Downloads/styledtext-test.tgz # or whatever your downloads directory is
~~~

Now restart Hammerspoon and let me know the error -- it should show 4 index values, before and after conversion to character positions.

**Comment by chdiza** [comment]
OK, here is what it says now:
```
/Users/chdiza/.hammerspoon/hs/styledtext/init.lua:453: bad argument #2 to 'setStyle' (starts index must be < ends index: starts == 4748 (i == 4748), ends == 4747 (j == 4747))
```

**Comment by asmagill** [comment]
Odd... whats being passed into setStyle is already wrong... its not in the calculations to convert it into Objective-C character spaces instead of lua bytes... this suggests something wrong with the Ansi convertor itself (certainly possible, but not what I expected)...

If its not prying, can you supply me with the script that is generating the output?  I want to take a closer look at exactly what is being fed into the ansi function.

**Comment by chdiza** [comment]
@asmagill https://gist.github.com/chdiza/afe643735a3bc19ada1a

**Comment by chdiza** [comment]
FWIW the error seems to happen typically when the number of entries returned by my shell script is relatively large (like, fill a 13" MacBookPro screen at 10 point font size).  That's why I asked about limits.

**Comment by asmagill** [comment]
@chdzia, try the latest pull and let me know... The problem was when your script applied two nested color changes to the same text (a connection was in the FIN_WAIT status, iirc), and the ANSI converter tried to apply a style to a zero-length string.  I've changed the setStyle and removeStyle methods so that they now just return the unchanged string if asked to apply a change to a zero or negative length range; it's more in line with the Lua `string.sub` style they inherit for index calculations.

**Comment by asmagill** [comment]
(@chdiza... I think I've screwed up your name more than once! sorry!)

**Comment by chdiza** [comment]
Thanks!  I'll test this right away.  I've been meaning to refactor the colorization lines in that script to use fewer wildcards; looks like I should've done that earlier.

Actually, I'll test two things: (1) the latest pull; (2) I'll remove the nested colorization attempts.

**Comment by chdiza** [comment]
I'm not seeing what you call "the latest pull".  The most recent one is from two days ago.

**Comment by asmagill** [comment]
whoops... hadn't applied it yet.  Will re-open until you confirm.

**Comment by chdiza** [comment]
Still the same error.  Ending index is one less than starting index.

A FIN_WAIT_2 line is triggering the problem.

**Comment by chdiza** [comment]
Whoops, didn't mean to close.

**Comment by chdiza** [comment]
I wonder if it wasn't that a zero-length string was asking to be colored, but that an already-colored string was asking to be colored.

**Comment by asmagill** [comment]
Did you remove the module I sent a link to yesterday?  The error message shouldn't be in the code anymore...

**Comment by chdiza** [comment]
Aiyeee, I did not.  Removing it seems to make the messages go away, but so did NOT moving it and tweaking the script to ensure nothing already colored is colored again (e.g., `$red$yel/somestuff/$nun$nun`).

**Comment by chdiza** [comment]
The error messages have vanished.  I guess my script had a weird edge case in it that triggered an oddity in the ansi converter.  Now both the script and the ansi converter are fixed.

I'm not sure this is the same issue that was causing the freeze-ups, but that will be a separate thread when I can pin them down.
