### ISSUE TITLE
hs.urlevent can not handle local file events

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#659]
When `hs.urlevent` is registered to listen to http event, file events also get registered. However when one attempts to open a local html file from Finder, Hammerspoon craps out with the message

```
The document “tiddlywiki.html” could not be opened. Hammerspoon cannot open files in the “HTML text” format.
```

`hs.urlevent` should be made able to pass local HTML file URLs too just like http/https URLs. It certainly is allowed by the various browsers.

```lua
> hs.inspect(hs.urlevent.getAllHandlersForScheme('file'))
-- Loading extension: inspect
{ "org.mozilla.firefox", "org.mozilla.tor browser", "com.vivaldi.Vivaldi", "com.apple.Safari", "com.google.Chrome", "com.apple.finder" }
```

**Comment by cmsj** [comment]
Thanks :)

**Comment by junkblocker** [comment]
Woo, two urlevent bugs fixed in one shot. Good day today! Thanks, @cmsj !
