### ISSUE TITLE
hs.mouse.watcher?

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#661]
Just an idea, but would allow us to create things like focus-follows-mouse :)

**Comment by cmsj** [comment]
I think this should be covered already by hs.eventtap. Is there anything you can't do with that, that you'd need?

**Comment by asmagill** [comment]
I've given thought to seeing if we could define regions that would trigger MouseEntered and MouseExited events, but haven't really looked into what it would take yet.  That's about the only thing I can think of that might be missing...  And @szymonkaliski, are you thinking of true focus-follows-mouse or auto-raise?  Without auto-raise, about the only thing you can guarantee is that keypresses are sent and maybe mouse clicks... menu shortcuts, etc. aren't guaranteed for anything but the active application.

http://osxdaily.com/2011/04/18/terminal-focus-follow-mouse-mac/ has a method which enables it for Terminal, and I have to say its taken some getting used to for what works and what doesn't.

http://steve-yegge.blogspot.com/2008/04/settling-osx-focus-follows-mouse-debate.html has a pretty good discussion about why its so hard to do well in OS X.

**Comment by szymonkaliski** [comment]
Oh crap, my bad, I didn't see there's `mouseMoved` insited `hs.eventtap.event.types`... I'm going to try to implement it and will bother you if I have any problems :) Thanks for the links @asmagill!
