### ISSUE TITLE
NSEnableScreenUpdates and NSDisableScreenUpdates

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#662]
Would there be any objection to adding these to `hs.drawing`?

I've been playing with them in `hs._asm.undocumented.spaces` and the only negative side effect I've seen is extra log messages if you get them unbalanced or call them out of order.

The specific use case right now is that I'm working on a set of functions for manipulating a table of images as if they were a single entity, and while these additions are not strictly necessary (and in fact can't be enforced if its over 1sec between calling NSDisableScreenUpdates and NSEnableScreenUpdates), it does make things look a little smoother when the duration can be kept short enough.

**Comment by asmagill** [comment]
I should clarify that the log messages are in the Console application (i.e. system logs) and not the Hammerspoon console.

**Comment by cmsj** [comment]
I'm fine with exposing it - as you say, SystemUIServer will forcibly reenable updates.

**Comment by lowne** [comment]
+2!
