### ISSUE TITLE
Grid hints in hs.grid don't handle keynames properly

### ISSUE THREAD

**Issue by mattdw** [Hammerspoon/hammerspoon#663]
This value for `hs.grid.HINTS`…

```lua
hs.grid.HINTS = {
  {"padclear", "pad=", "pad/", "pad*"},
  {"pad7", "pad8", "pad9", "pad-"},
  {"pad4", "pad5", "pad6", "pad+"},
  {"pad1", "pad2", "pad3", "padenter"}
}
```

…gives the following error:

```
...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:392: Invalid key: *
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:176: in function 'hs.hotkey.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:392: in method 'bind'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:801: in upvalue '_start'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:812: in function 'hs.grid.show'
```

Changing the `"pad*"` entry in `hs.grid.HINTS` changes the error to the same thing but for `Invalid key: +`. And so on. [These lines in `grid/init.lua`](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/grid/init.lua#L799-L801) appear to be doing string slicing on the keynames (to special-case the function keys I think; other keys require `shift` and the f-keys don't) which is presumably causing problems when keynames aren't the assumed 1 or 2 chars long.

Kinda seems to me that the hints function shouldn't be making assumptions about modifiers in the first place, or should expose that as another setting in `hs.grid.ui`.

**Comment by mattdw** [comment]
Not that this is any kind of fix, but I've marginally (and only mostly) hacked out the existing misbehaviour by applying the following patch. However this does also expose a problem where the rows of `hs.grid.HINTS` are reordered before use.

```diff
diff --git a/extensions/grid/init.lua b/extensions/grid/init.lua
index 5f755ee..9bca330 100644
--- a/extensions/grid/init.lua
+++ b/extensions/grid/init.lua
@@ -594,7 +594,7 @@ local function makeHints() -- quick hack to double up rows (for portrait screens
   for i,v in ipairs(grid.HINTS) do _HINTS[i]=v _HINTS[i+rows]={} end -- double up the hints
   for y=1,rows do
     for x,h in ipairs(_HINTS[y]) do
-      _HINTS[y+rows][x] = '⇧'.._HINTS[y][x] -- add shift
+      _HINTS[y+rows][x] = ''.._HINTS[y][x] -- add shift
     end
   end
 end
@@ -796,9 +796,8 @@ local function _start()
   makeHints()
   for _,row in ipairs(_HINTS) do
     for _,c in ipairs(row) do
-      local l=ssub(c,-3,-3)=='f' and -3 or (ssub(c,-2,-2)=='f' and -2 or -1)
-      local mod,key=ssub(c,-20,l-1),ssub(c,l)
-      resizing:bind({mod},key,function()hintPressed(c) end)
+      local key = string.sub(c, 1)
+      resizing:bind({},key,function()hintPressed(key) end)
     end
   end
   --TODO perhaps disable all other keyboard input?
```

**Comment by lowne** [comment]
The `shift` thingie [here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/grid/init.lua#L590) was meant to address a request for more than 5 rows of hints with the least amount of disruption to the existing code, the disruption being that horrible single line of string.sub hacky dance, which unfortunately, as you point out, doesn't take into account the possibility of hints longer than 2 chars.
A new quick hack applied on top of the old quick hack should result in a more proper way of handling the shift-hint doubling up :)

**Comment by lowne** [comment]
Never mind, by touching that data structure I broke something (obviously in hindsight, as that was the reason for not doing it "properly" to begin with) and decided to backtrack immediately; so the fix in #666 is just as ad-hoc as the previous code.

**Comment by lowne** [comment]
@mattdw slightly OT, you need to provide 5 valid rows of `hs.grid.HINTS` even if you just use 4x4 grids; `hs.grid` will pick rows 2,3,4 and 5.

**Comment by mattdw** [comment]
Awesome, thanks!
