### ISSUE TITLE
Speech synthesizer and recognizer module?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#665]
I'm playing with NSSpeechSynthesizer and NSSpeechRecognizer and, after a little more testing and documentation, plan to upload it to my work-in-progress repo...

Is there interest in adding it to core instead?

**Comment by cmsj** [comment]
I'd like to have a play with it, but definitely. The recognizer could be extremely useful for Siri-like command and control :)

**Comment by asmagill** [comment]
The main thing NSSpeechSynthesizer gives us over using hs.execute/hs.task with `say` is the ability to pause on word/sentence boundaries, output to an AIFF file, and callbacks for each word being spoken.  NSSpeechRecognizer allows us to register "phrases" which can trigger a callback for whatever function we want.  Since it uses all stock OS X stuff, I would assume it works as well as OS X dictation does with other languages, but the docs are pretty sparse on this point, and I've only got English installed.

**Comment by asmagill** [comment]
For those interested, take a gander at https://github.com/asmagill/hammerspoon_asm/tree/master/speech.  I'm still playing with a couple of methods in NSSpeechSynthesizer (hs.speech) because I want to provide as complete an interface as possible, but it should be fine for 90%+ of the uses a user will likely have for it.

By comparison, NSSpeechRecognizer (hs.speech.listener) was a breeze to implement fully, though it should be tested more before inclusion.

Some of my notes and tests are included as well for perusal if interested.

I do plan to include them in core ultimately, but not quite yet.

**Comment by cmsj** [comment]
I had a quick play with hs.speech.listen and it seems really good :)
