### ISSUE TITLE
Write an IPC/homebridge plugin

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#672]
re https://github.com/nfarina/homebridge - this is a working software implementation of HomeKit. If we expose some kind of IPC mechanism to it, people can control Hammerspoon with Siri.

**Comment by cmsj** [comment]
Closing - clearly going nowhere.

**Comment by Jayphen** [comment]
This is rather old now, but I would love this feature!

Is there some other way to trigger Hammerspoon actions from another device? Either via an HTTP request, MQTT, or something else?

**Comment by latenitefilms** [comment]
@Jayphen - it should be fairly easy to integrate Hammerspoon with Homebridge via their plugins infrastructure?
