### ISSUE TITLE
hs.wifi

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#676]
Is there interest in being able to turn the wifi power on or off (still no bluetooth without using private API's, however, so its not a true "Airplane Mode" by itself) or doing a background (i.e. non-blocking) scan with full details?

**Comment by junkblocker** [comment]
Yes, +1

**Comment by oschrenk** [comment]
Would be nice. Then I can replace, this

```
  os.execute("/usr/sbin/networksetup -setairportpower " .. wifiInterface .. " off")
```

**Comment by cmsj** [comment]
This should be closable now :)
