### ISSUE TITLE
Allow communicating with hs.task via stdin

### ISSUE THREAD

**Issue by yoavg** [Hammerspoon/hammerspoon#682]
I'd like to be able to construct a string which I could then send to an external process via stdin.

Currently, hs.task allows to define commandline arguments to be sent, but not stdin value (or is there a way to do it which I missed?)

**Comment by asmagill** [comment]
At present, I don't believe its possible.  What kind of interface are you thinking of?  Something where you can provide a string with the input when creating the task, or would there be an additional method which could be called to "feed" the stdin of a running task?

I've not actually tried a task yet that wanted input yet... what does it do?  Does it stall? or continue as if the input was empty?

**Comment by yoavg** [comment]
I was thinking of providing the input when creating the task, or perhaps changing the start() method to take the string as a parameter.

My current use-case for this is a dynamic menu with fuzzy-find functionality, i.e. feeding text into a selector such as https://github.com/sdegutis/choose and acting on the result.

**Comment by cmsj** [comment]
@asmagill I've just pushed up some code for doing stdin with both streaming and non-streaming tasks, based on what you had in #686. I don't seem to have as much Exception protection as you, and I'm not sure if that's necessary. Do you have some gnarly tests you could hurl at my code?

**Comment by asmagill** [comment]
At least one of the exception tests was around code which was failing to exit gracefully before I put it on the main thread.  I have never been able to actually trigger an exception using the writeData: message, even though its documentation reads "This method raises an exception if the file descriptor is closed or is not valid".  Even when it was failing before, it wasn't with an exception -- it was with a crash.  Using `dispatch_sync(dispatch_get_main_queue(), ^{` took away the crashes, but I still never saw an exception.

So, at a guess, I don't think it will matter. I'll try some tests tonight or tomorrow, though, and let you know.

**Comment by cmsj** [comment]
Ok thanks :)

**Comment by asmagill** [comment]
Ok, against what's currently merged, for the following script `t.sh`:

~~~bash
#! /bin/bash
sleep 15
echo "begin"
a=$(cat -)
echo $a
echo "end"
~~~

(the sleep is in there so I can do things like restart Hammerspoon, test resetting the input while it's already running, etc.)

Here are some of the things I've tested:

~~~lua
> n = hs.task.new("./t.sh", function(...) print(inspect(table.pack(...))) end)
> n:setInput("test1")
hs.task: ./t.sh  (0x60800014dd48)
> n:start()
hs.task: ./t.sh  (0x60800014dd48)
{ 0, "begin\ntest1\nend\n", "",
  n = 3
}

-- no input, even though the script expects/can accept it
> n = hs.task.new("./t.sh", function(...) print(inspect(table.pack(...))) end)
> n:start()
hs.task: ./t.sh  (0x608000264648)
{ 0, "begin\n\nend\n", "",
  n = 3
}

-- changing input before script is started
> n = hs.task.new("./t.sh", function(...) print(inspect(table.pack(...))) end)
> n:setInput("I am a test")
hs.task: ./t.sh  (0x6080002f76c8)
> n:setInput("I am not a test")
hs.task: ./t.sh  (0x6080002f76c8)
> n:start()
hs.task: ./t.sh  (0x6080002f76c8)
{ 0, "begin\nI am a test\nend\n", "",
  n = 3
}

-- changing input after script is started
> n = hs.task.new("./t.sh", function(...) print(inspect(table.pack(...))) end)
> n:setInput("I am a test")
hs.task: ./t.sh  (0x60800005d2c8)
> n:start()
hs.task: ./t.sh  (0x60800005d2c8)
> n:setInput("I am not a test")
hs.task: ./t.sh  (0x60800005d2c8)
{ 0, "begin\nI am a test\nend\n", "",
  n = 3
}
~~~

I'm ok with the input not being changeable after the task starts, though I'm not sure how that fits in with the streaming support model... I haven't looked that closely at the code.  However, the input before a task start should be replaceable (and/or append-able?)

Interestingly, I did get a couple of crashes when setting the input a second time before starting the task, but not always... The log shows

~~~
Application Specific Information:
Crashing on exception: *** -[NSConcreteFileHandle writeData:]: Bad file descriptor

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8d0dfae2 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff96577f7e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff8d0df98d +[NSException raise:format:] + 205
3   Foundation                          0x00007fff90b31c17 -[NSConcreteFileHandle writeData:] + 74
4   internal.so                         0x000000010df7e6a1 writerBlock_block_invoke_2 + 1185
5   libdispatch.dylib                   0x00007fff9ebbc33f _dispatch_client_callout + 8
6   libdispatch.dylib                   0x00007fff9ebceebf _dispatch_barrier_sync_f_slow_invoke + 523
7   libdispatch.dylib                   0x00007fff9ebbc33f _dispatch_client_callout + 8
8   libdispatch.dylib                   0x00007fff9ebcfc1d _dispatch_main_queue_callback_4CF + 1685
9   CoreFoundation                      0x00007fff8d025cd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
10  CoreFoundation                      0x00007fff8cfe0d3d __CFRunLoopRun + 1949
11  CoreFoundation                      0x00007fff8cfe0338 CFRunLoopRunSpecific + 296
12  HIToolbox                           0x00007fff95857935 RunCurrentEventLoopInMode + 235
13  HIToolbox                           0x00007fff9585776f ReceiveNextEventCommon + 432
14  HIToolbox                           0x00007fff958575af _BlockUntilNextEventMatchingListInModeWithFilter + 71
15  AppKit                              0x00007fff980490ee _DPSNextEvent + 1067
16  AppKit                              0x00007fff98415943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
17  AppKit                              0x00007fff9803efc8 -[NSApplication run] + 682
18  AppKit                              0x00007fff97fc1520 NSApplicationMain + 1176
19  Hammerspoon                         0x00000001032971b2 main + 34
20  libdyld.dylib                       0x00007fff97f475ad start + 1
~~~

but like I said (and you can see above), it was only a couple of times, so I'm not sure exactly what was different.  I'll try and dig later and see if I can find a reliable combination that crashes, or figure out if something else in my setup might have caused the problem (I do have some other hs.task's running on timers, but none that use `setInput` yet.)
