### ISSUE TITLE
style point: module getters and setters

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#683]
Ok, this may be a semi-painful transition, but I think we need to make some decisions regarding module style for consistency in the Hammerspoon "language".  I admit I'm guilty of being inconsistent in this myself, and perhaps a larger "Style Guide" is merited (@cmsj touched somewhat on the coding side of this with #641) but for this specific issue, I want to focus on "getters" and "setters"... in some cases there is some consistency within a module (though not always) but there is no consistency across modules.

For example, in hs.drawing:

`hs.drawing:setFrame({...})` will set the frame of a drawing object while `hs.drawing:frame()` returns the frame.

*but*

`hs.drawing:wantsLayer(...)` will set this property, while `hs.drawing:wantsLayer()` gets it.

I admit, my preference is the latter -- I think it makes for tighter lua code, and a shorter list of method names to remember.  I am not opposed to an explicit separation, though as some seem to prefer it.  I just think we should be as consistent as possible across all modules.

So, consensus?

And if there is a decision on a specific style, how should we go about implementing it?  A period where both work?  A period of breakage?  Just enforce it going forward?

**Comment by cmsj** [comment]
I agree that our inconsistency here is a shame, and that the transition will be semi-painful, but it seems like something we should be fixing. I vote for the latter, for the reasons you mentioned.

**Comment by lowne** [comment]
+1 for the latter, if only because it means writing (and reading) less docstrings; as for implementation, we could surely enforce it from now on, but I don't think we should break all the existing configs, and doing a deprecation transition period on such scale without proper infrastructure as per #608 would imho inevitably result in more inconsistencies at best, and subtle bugs at worst.
