### ISSUE TITLE
window hiding

### ISSUE THREAD

**Issue by yoavg** [Hammerspoon/hammerspoon#684]
I'd really like the ability to quickly hide/unhide a window or a bunch of windows.

One use-case for this is creating "scratch" windows, that I can bring up / make go away with a hotkey.
I am currently using minimize/unmiminize, but the animation makes it unbearable to use :(
Another use-case is emulating multiple desktops. 

Is it technically possible (i.e. by setting its position to outside of the screen, or some other trick) or is OSX preventing it?

**Comment by szymonkaliski** [comment]
Do you mean something else than `cmd+h`?

**Comment by yoavg** [comment]
`cmd-h` works at the application level and hides all the application's windows. I want to hide only specific windows.

**Comment by lowne** [comment]
IIRC it used to be possible; in El Cap a corner always stays in bounds. If you don't mind that, you can use `window:_setTopLeft{x=20000,y=20000}`.

**Comment by asmagill** [comment]
If you're willing to use code that uses undocumented, private functions (i.e. not Apple approved for general consumption) and that I cannot promise won't break in a future OS update, you can take a look at my undocumented spaces module... this would allow you to move the windows to another space... still reachable, but effectively hidden from what you're presumably working on in your other spaces.  Check out https://github.com/asmagill/hs._asm.undocumented.spaces if interested.

**Comment by yoavg** [comment]
Thanks @asmagill , the spaces module works well for this! I managed to whip up an implementation of the behaviour I needed. Too bad there isn't a well-documented solution to this, but an un-documented one is way better than nothing :)

[also, this surfaced two small issues which I'll mention in separate threads]
