### ISSUE TITLE
Strange behavoir

### ISSUE THREAD

**Issue by TPMi** [Hammerspoon/hammerspoon#693]
Here's my config:
http://pastebin.com/6EWiB9MF
When I run HS everything is OK:
http://pastebin.com/fjcUGJDU
But after some time (a couple hours) or after I put my macbook to sleep it stops working normally.
Application hotkeys should send cmd+` if corresponding application is already active, but they send cmd+a, and everything selects.
When I do "Reload Config" I see this:
http://pastebin.com/Gbv4U3xk
But I did not make any changes to my config.

Quit and restart fix the problem. But this is very annoying.

**Comment by cmsj** [comment]
Out of interest, which keyboards do you have enabled in System Preferences -> Keyboard -> Input Sources?

**Comment by TPMi** [comment]
U.S. and Russian

**Comment by cmsj** [comment]
@TPMi does this issue line up with when the layout is changed?

**Comment by TPMi** [comment]
@cmsj no, layout switching has no effect but layout switching :-) some of my combinations do not work in Russian, but application switching combinations work in both layouts and stop working in both simultaneously.
I can see correlation between this behaviour and additional display connection/disconnection, and also putting notebook to sleep. But nothing is stable, sometimes it works like charm for days, sometimes it's broken in a couple of hours without any hardware changes.

**Comment by cmsj** [comment]
Are you still seeing this? Sorry we've not touched it for over a year. Please re-open if this is still an issue.
