### ISSUE TITLE
LuaSkin conversion utilities and debug builds

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#697]
@cmsj, is there a defined macro or variable I can check either at compile time or run time that indicates a user is building/running a debug build?  

Among the things discussed in @lowne's and my dialog was whether or not things like toNSObjectAtIndex could reliably determine if the index specified was acceptable or not and I made the observation that checking lua_absindex(L, lua_gettop(L)) >= lua_absindex(L, idx) and assuming nil (NSNull), like the lua interpreter does for the builtin functions, when it's false *might* work.

I... feel... uncertain that this is a sufficient or reliable test, and that the only safe place for bounds checking is before you call anything in LuaSkin because LuaSkin is used both when you're in a "protected, predictable lua built environment" and when you're dealing with unpredictable environments like when responding in delegates and blocks set by timers or inserted directly into the runloop. But the more I think about it logically, I can't figure out why I feel that way and I want to collect some data and create some contrived examples, both with my setup and those that choose to help (I'm assuming you'd be game, @lowne?), but I don't want to change anything in the formally released core until I'm sure one way or the other.

Thoughts or suggestions?

**Comment by cmsj** [comment]
@asmagill im on a plane right now, but I'm pretty sure we define DEBUG correctly

**Comment by lowne** [comment]
@asmagill I'm game; fwiw (re: argument- vs stack-checking), I kept the "basic" `lua_gettop(L) < idx` check for 24 hours or so (including attaching/detaching monitors, which triggers a billion callbacks in my config) and it all worked.
I'm amply unsure about this, but just as a wild guess, maybe a possible alternative could be to play tricks with the stack (along the line of pushing the needed nils) in `checkArgs` (as opposed to `checkStack` as mentioned in #698).

**Comment by cmsj** [comment]
@asmagill OOI, what did you want to know about Debug builds for? I'm guessing prominent error messages in debug builds and not in release builds? I'm fine with that, but I think we should avoid changing actual behaviour between the two, since most of us are probably never running release builds :)

**Comment by asmagill** [comment]
That's kind of moved to the back burner for the moment... primarily I was going to throw in a lot of NSLog's so I could track exactly how the stack and index numbers change, both in-context and in terms of their absolute values, depending upon when/how LuaSkin methods are invoked.  Assuming these look ok, I was probably going to add a check at the beginning of the conversion methods so that if the indexes looked odd, it automatically returned nil... this is primarily what I was most concerned about being active in the release version before being vetted... I don't want to change behavior of something so integral until I'm sure that the edge cases it's supposed to catch really need it.

However, the error thing seems more important in the short term; long term, we'll see... if using checkArgs in the function is done properly, these edge cases really shouldn't happen; its only when trying to replicate or expect the lua behavior of "if it ain't there, it's nil, so don't bother bounds checking" that this question should even arise.  It came to the forefront because something that didn't use to use LuaSkin at all (hs.settings.set) was modified to use it, but not with checkArgs, so an unplanned behavior that allowed using set in ways it wasn't originally expected to be used in broke with the incomplete conversion to LuaSkin.

**Comment by cmsj** [comment]
Is there anything actionable here? (sorry, I'm trying to do some Issues gardening and we seem to have a few issues that are asking a question and then tailing off)

**Comment by lowne** [comment]
Speaking of checkArgs, why can I pass a function (or anything else) to drawing:setFrame() without errors?

**Comment by asmagill** [comment]
because `hs.drawing` is only *partially* LuaSkin converted/compliant/whatever...

`setFrame` calls `setSize` and `setTopLeft` directly (no `lua_pushcfunction`) and neither `setSize` or `setTopLeft` use `checkArgs` to validate their parameters.  Both are bad practice, imo.

Its this kind of thing I hope to uncover/fix in a later phase of the current LuaSkin corrections/updates.
