### ISSUE TITLE
hs.logger question about history

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#699]
How hard would it be to add a history to hs.logger so that, even if my current level is suppressing some of the messages, I can go to the console and review the last 50 (or whatever number)?

**Comment by lowne** [comment]
@asmagill not very, and something that I have wanted to do for a while, but it needs appropriate hooks to the console texture (plus a "filter" text input, I suppose) (plus #536 to begin with).

**Comment by lowne** [comment]
To be precise: it doesn't "need" the hooks, but I guess that'd be the logical next step (for ease of use) after implementing something like `hs.logger.getHistory(filter,entries)`.
Should I start with the internal implementation?

**Comment by cmsj** [comment]
@lowne I'm not sure I understand what you need here from the Console? Wouldn't this just be returning a table of the last N strings that were sent to hs.logger? (implying that hs.logger would be keeping a fixed-length buffer)

**Comment by lowne** [comment]
Yes; let's do things the other way around. I'll get to it as soon as I'm done with the current PRs.

**Comment by lowne** [comment]
To clarify: I initially thought of allowing manipulation of the console (changing log level on the fly (and retroactively), filtering by id,..) from `hs.logger`'s Lua code; but I'll just implement `hs.logger.getHistory()` which will return a list of `{timestamp,id,level,message}` entries.

**Comment by asmagill** [comment]
Not to get all kefedokhles and side-tracked again, but take your pick:

1. a format, as defined for use in `string.format` can reference 0 parameters, and ..., as defined in the lua manual refers to 0 or more arguments

2. It's one less thing on the traceback stack.

3. It doesn't matter, it works.

4. If you don't like it, write/modify it yourself... the delegate code will be very simple and found in MJLua.m... I'll let you know when the main code is ready and it should be only about 3 lines of code that will need to be modified to set the callback function

My main reason was 2, not for performance reasons, but because it seems more elegant to avoid increasing it solely for a functional syntax (why do you even have a version that takes no parameters when nothing about string.format or ...  has an issue with 0?) that I don't believe is really needed anyways.

**Comment by asmagill** [comment]
I should also probably add

5. when I first started attempting the integration, I hadn't decided for certain if I would be passing multiple args or not... I'm still not 100% that it would never be useful, but that's probably a case-by-case thing... 90% of the time, and probably 100% of the time coming from the LuaSkin log methods, I probably won't pass additional args.

**Comment by lowne** [comment]
@asmagill I guess you're replying here to #704?
> why do you even have a version that takes no parameters

I'm not entirely sure I follow your reasoning, but unless I'm missing something, any literal `%` in your (non-formatted) log message will make logger crap out (which also answers your question above)
```lua
> log=logger.new('percents')


> log.w('100% gonna work')
17:11:32 ** Warning:  percents: 100% gonna work


> log.wf('100% not gonna work')
/Users/lowne/.hammerspoon/hs/logger/init.lua:155: bad argument #2 to 'sformat' (no value)
stack traceback:
	[C]: in function 'string.format'
	/Users/lowne/.hammerspoon/hs/logger/init.lua:155: in function </Users/lowne/.hammerspoon/hs/logger/init.lua:152>
	(...tail calls...)
	[C]: in function 'xpcall'
	/Users/lowne/.hammerspoon/hs/_coresetup/init.lua:225: in function </Users/lowne/.hammerspoon/hs/_coresetup/init.lua:219>
```

**Comment by lowne** [comment]
You *can* pass multiple arguments to the non-f functions:
```lua
> log.w('omg','bbq')
17:14:44 ** Warning:  percents: omg bbq
```

**Comment by asmagill** [comment]
that may be the first good argument in favor of changing it... I'll give it some thought.

**Comment by asmagill** [comment]
(not sure how I got the issue numbers out of sync, but you're right about #704)

**Comment by lowne** [comment]
Just to clarify: when I said
>  I don't understand why you're using the 'f' method variants 

I meant it literally, as a mere request for clarification; I apologise if it came across as "I don't like it" and/or "you should change it" - as a general rule, I might have strong opinions on the general architecture, but I'm not going to criticise any *actual* ObjC code, since I can't/don't want to write any myself :)
