### ISSUE TITLE
NSSystemDefined eventtap for brightness keys not working on bluetooth keyboard

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#706]
Hi!

I'm playing with simple code like this:

``` lua
hs.eventtap.new({ hs.eventtap.event.types.NSSystemDefined }, function(event)
  local systemKey = event:systemKey()

  -- exit as soon as possible if we don't care about the event
  if not next(systemKey) then return false end

  local shouldProcessEvent = hs.fnutils.some({ 'BRIGHTNESS_UP', 'BRIGHTNESS_DOWN' }, function(key)
    return key == systemKey.key
  end)

  -- propagate event if it's not brightness related
  if not shouldProcessEvent then return false end

  if systemKey.key == 'BRIGHTNESS_UP' then
    hs.brightness.set(math.min(100, hs.brightness.get() + brightnessMod))
  end

  if systemKey.key == 'BRIGHTNESS_DOWN' then
    hs.brightness.set(math.max(0, hs.brightness.get() - brightnessMod))
  end

  -- stop propagation
  return true
end):start()
```

It's working fine on my macbook keyboard, but doesn't fire (I'm not getting any events at all) when I'm hitting brightness keys on official apple wireless keyboard.

What is event stranger, I'm getting events fine for play/rewind/fast on both macbook and wireless keyboards. It seems to not work only for brightness keys...

**Comment by asmagill** [comment]
I'd like to see specifically what is output when you tap the brightness keys on the wireless keyboard... add `print(hs.inspect(systemKey), hs.inspect(event:getRawEventData()))` before the `if not next(systemKey)...` line and let me know what is displayed for both the brightness up and down key on the wireless keyboard.

If nothing at all appears then the brightness keys on the wireless keyboard are not considered a system defined event and I'm going to have to figure out what it does differently on that keyboard... I'm hoping that it will be as simple as a different set of labels which need to be added to the `systemKey` method, though.

**Comment by szymonkaliski** [comment]
I'm away from my computer, but I remember trying this and nothing happening at all (callback to eventtap wasn't firing).

**Comment by asmagill** [comment]
Do you recall if you tried the `hs.inspect(event:getRawEventData())` part as well?  If not, do so when you get a chance (no rush).  If this at least prints something, then at least brightness is still a system event and we just need to tweak the module to identify the changed key events.  If this also doesn't print anything, then we need to figure out *what* event the brightness keys trigger...

Is this the newer thin keyboard (I think called the Apple Magic Keyboard), or the older one with the rounded end where batteries are inserted (sometimes referred to the Apple Wireless Bluetooth Keyboard)?  If the latter, I may have access to one this weekend or next week and will try to take a look at it myself as well.

**Comment by szymonkaliski** [comment]
I just tried `getRawData` but I'm not getting anything at all, even if I add `print('test')` just below the eventtap line, the callback is just not firing at all.

It's the older one with rounded end :)

**Comment by asmagill** [comment]
well poop, that means it isn't a system event and a different eventtap will probably be required... but that is the keyboard I will have access to, so I'll let you know what I figure out when I get a chance to play with it.

**Comment by cmsj** [comment]
FWIW, I have the newer Magic Keyboard and I can reproduce this, there's no callback activity for the brightness keys

**Comment by waydabber** [comment]
Amazingly this is still an issue on the latest M1 macs and the latest apple magic keyboards. :(

Working fine with the built-in keyboard but these two keys are simply not registered as an event on a wireless apple keyboard.

**Comment by waydabber** [comment]
BUT: you can still catch chis event via hs.eventtap.event.types.keyDown.

Brightness Down has a keycode of 145, Brightness Up has 144.

**Comment by cmsj** [comment]
I think trying to add in workarounds for every type of keyboard is probably not a realistic solution for us, but there is a workaround - use Karabiner Elements to set the relevant keys on the specific keyboard that isn't working, to `display_brightness_decrement` and `display_brightness_increment`
