### ISSUE TITLE
Add ability to start minimized

### ISSUE THREAD

**Issue by kpashka** [Hammerspoon/hammerspoon#708]
Would be great addition to "Launch at login" feature which always opens configuration window at launch (which is pointless because you usually configure the options once and forget about them).

**Comment by cmsj** [comment]
Have you granted Hammerspoon permission to use Accessibility features? We should only display the prefs window at startup if:

1. The first time you run a new version of Hammerspoon
1. If the OS tells us we don't have accessibility permissions (which shows in the prefs window with an orange status dot and a warning message at the bottom)

**Comment by kpashka** [comment]
@cmsj It was the accessibility issue, thanks, now it's resolved!
