### ISSUE TITLE
Spaces/desktops management

### ISSUE THREAD

**Issue by trzeciakp** [Hammerspoon/hammerspoon#711]
Hi guys,

it's not really an issue within hammerspoon, but I couldn't find better place to ask for help. Do you know 
any place to ask questions like this?

There are number of things which makes me crazy in OSX. Hopefully I fixed most of them by hammerspoon and other apps. But there are still some issues which I would like to change. 

I like the idea App per desktop. You assign each app to separate desktop and then you easily navigate to your apps by shortcuts (^ + 0-9 and ^ + alt + 1-6, up to 16 desktops). Unfortunately there are some problems:

##### 1. First desktop of each external monitor is merged to desktop#1 when unplugged 
E. g. On first screen I have desktops 1-6 and on second screen there are desktops 7-10. When I unplug second screen then I on firs screen I have desktops 1-9. There is no 7th desktop. Everything from it was moved to destkop 1. Do you know how to fix it?
##### 2. There is no good way to assign app to desktop
Currently I have to go to the proper desktop -> right click on app icon in dock -> options -> assign to -> this desktop. And do it for every app. And something is messed up and you have to do it again and again. I would love to edit it in a text file. I know where it is stored. You can read it by `defaults read com.apple.spaces` but it's not user friendly format to make any changes. Do you know any better way to edit this? Maybe it's possible via hammerspoon?
##### 3. How to show desktop number in menu bar
I come up with hammerspoon script: 
```
function showDesktopNumberInMenuBar()
  local menubar = hs.menubar.new()
  local spaceWatcher = hs.spaces.watcher.new(function(spaceNumber)
    menubar:setTitle(spaceNumber .. '')
  end)
  spaceWatcher:start()
end
```
But unfortunately it does not work. It always shows '-1'. Probably because space API have been depracated. Do you know any other way to obtain number of current desktop?

**Comment by cmsj** [comment]
@trzeciakp I don't think there's another way, sadly. I wish there was proper API for all this stuff :(
