### ISSUE TITLE
We to report bugs found on http://www.hammerspoon.org/

### ISSUE THREAD

**Issue by clemens-tolboom** [Hammerspoon/hammerspoon#712]
Reading on http://www.hammerspoon.org/ is see no link to the sites git repo so cannot create PRs for that. What did I missed?

**Comment by cmsj** [comment]
@clemens-tolboom it's https://github.com/Hammerspoon/hammerspoon.github.io (happy to take suggestions for how to advertise that :)

**Comment by clemens-tolboom** [comment]
Thanks and done :)
