### ISSUE TITLE
hs.layout.apply: frame rect cannot shrink window?

### ISSUE THREAD

**Issue by jdpopkin** [Hammerspoon/hammerspoon#715]
If I have Slack open on the larger of my two monitors, then I call `hs.layout.apply(window_layout)` with a `window_layout` like

```
{
   {"Google Chrome", nil, bigScreen, nil, hs.screen.find(bigScreen):frame(), nil},
   {"Slack", nil, smallScreen, nil, hs.screen.find(smallScreen):frame(), nil}
}
```

Slack doesn't get resized to fit `smallScreen`'s dimensions. It stays at its previous size (which is wider than `smallScreen`). I can work around this by resizing the window before applying the layout:

```
hs.application.find("Slack"):allWindows()[1]:setFrame(hs.geometry.rect(100, 100, 1, 1))
hs.layout.apply(window_layout)
```

But it seems like that shouldn't be necessary.

Awesome project, by the way :smile:

**Comment by cmsj** [comment]
I think this may be an OS limitation, it seems to get very unhappy about windows that are at/beyond the edges of screens

**Comment by cmsj** [comment]
(see also #724 )

**Comment by zzamboni** [comment]
I was having a similar issue (which resulted in my opening of #724), which seems to have been solved by setting `hs.window.setFrameCorrectness = true`. @jdpopkin maybe this helps in your case as well?
