### ISSUE TITLE
hs.grid.show for movement only?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#716]
Is there a key or flag I'm missing to the hs.grid.show interface which allows just moving a window (without resize) so it's upper left corner matches the letter space typed?

If not, can this be considered a feature request?  It would actually probably be best if there were a key (maybe return?) as the second keypress which indicates that this should be considered a move rather than a move-and-resize... this way I can choose which I want on a case-by-case basis rather than have to map the function to multiple keys, depending upon which I want to accomplish for a given invocation.

**Comment by cmsj** [comment]
I like the latter option of hitting Return to just move a window after the first keypress

**Comment by wvierber** [comment]
I'm trying/willing to close this one.
I also prefer the return key as second keypress to move the upper left of the window to the selected cell. But a few remarks:
* Should the window resize to match grid size, or just ignore the grid and only move the window to the selected grid cell?
* Should the window stay 100% inside the screen, or just move and ignore that?

So actually, should selecting a cell and hitting return really *just move* the window, or *move and resize* it to match grid/screen?

**Comment by cmsj** [comment]
@lowne any thoughts on this?

**Comment by asmagill** [comment]
I think move only (no snap to grid/check screen bounds) makes the most sense to me, but ultimately it's not a big deal either way.

**Comment by lowne** [comment]
Agree with @asmagill

**Comment by lowne** [comment]
I should point out that `window:setTopLeft()`, which would be used to achieve a "pure move", ignores `window.setFrameCorrectness`, so the usual oddities (namely window refuses to move) might apply; I guess most users keep it `false` anyway, but it could be a "surprising" behaviour for the others. The alternative is to use `w:setFrame({newx,newy},w:size())`

**Comment by wvierber** [comment]
OK, I also prefer the 'just move'. Just wanted to make sure.

@Lowne, thanks for mentioning that!
