### ISSUE TITLE
Add a callback for light/dark UI setting changes

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#719]
hs.host can interrogate the current UI setting, but we should have a callback for when it changes, see https://github.com/weAreYeah/WAYTheDarkSide/blob/master/WAYTheDarkSide/WAYTheDarkSide.m

**Comment by sebastianmarkow** [comment]
Is there a way to set the style? I like to replicate flux's switch to dark style on sunset.

**Comment by cmsj** [comment]
I'm going to close this issue because even though we haven't implemented it, it's possible to get notifications about the UI setting changing from hs.distributednotifications.

@sebastianmarkow Not currently, but if someone can find some code to show how to do it reliably, we could look at adding it :)

**Comment by latenitefilms** [comment]
You could probably just use hs.execute to change the plist values then force Finder to reload?
