### ISSUE TITLE
win is nil in: local win = hs.window.focusedWindow() 

### ISSUE THREAD

**Issue by mertnuhoglu** [Hammerspoon/hammerspoon#723]
When I use the following code, win is nil:

	> local win = hs.window.focusedWindow()
	> win
	nil

But actually the function returns some value:

	> hs.window.focusedWindow()
	hs.window: Hammerspoon Console (0x60000025f798)

This strange behavior breaks all window moving/sizing functions such as:

	hs.hotkey.bind({"cmd", "alt", "ctrl"}, "H", function()
		local win = hs.window.focusedWindow()
		local f = win:frame()

		f.x = f.x - 10
		win:setFrame(f)
	end)

Hammerspoon gives this error:

	/Users/mertnuhoglu/.hammerspoon/init.lua:6: attempt to index a nil value (local 'win')
	stack traceback:
		/Users/mertnuhoglu/.hammerspoon/init.lua:6: in function </Users/mertnuhoglu/.hammerspoon/init.lua:4>
	stack traceback:

**Comment by cmsj** [comment]
The first example is normal for the console, each command you type is its own local scope, so the "local" means the `win` variable is immediately lost. If you do `win = hs.window.focusedWindow()` it will work.

If you're getting the errors from your hotkey function, it may mean that you don't have Accessibility permissions for Hammerspoon. Check System Preferences in the Security & Privacy section.
