### ISSUE TITLE
hs.window.setFrameInScreenBounds() doesn't (always) work

### ISSUE THREAD

**Issue by zzamboni** [Hammerspoon/hammerspoon#724]
If the window is larger than the current screen, `setFrameInBounds()` doesn't seem to work. Using it through `move()` doesn't do anything, and calling `setFrameInScreenBounds()` directly makes the window shorter every time, but not narrower (maybe an inverted width/height somewhere?). For example:

```
> win
hs.window: Hammerspoon Console (0x7fa11a38cf68)

> win:frame()
hs.geometry.rect(-1200.0,-1020.0,1416.0,1916.0)   <<<--- Window is wider than the screen

> win:screen():frame()
hs.geometry.rect(-1200.0,-1020.0,1200.0,1920.0)

> win:move(win:screen():frame(), win:screen(), true)
hs.window: Hammerspoon Console (0x7fa11a38cf68)

> win:frame()
hs.geometry.rect(-1200.0,-1020.0,1416.0,1916.0)   <<<--- Window didn't move

> win:setFrameInScreenBounds()
hs.window: Hammerspoon Console (0x7fa11a38cf68)

> win:frame()
hs.geometry.rect(-1200.0,-874.0,1416.0,1623.0)  <<<--- Window became shorter

> win:setFrameInScreenBounds()
hs.window: Hammerspoon Console (0x7fa11a38cf68)

> win:frame()
hs.geometry.rect(-1200.0,-751.0,1416.0,1375.0)   <<<--- Again shorter but same width
```

**Comment by cmsj** [comment]
Paging Dr @lowne - this sounds to me like one of the weird things where OSX refuses to resize a window

**Comment by zzamboni** [comment]
For reference, I solved my immediate problem (using hs.window.moveOneScreenWest/East resulted sometimes in the window being left larger than the destination screen, and unable to resize it down) seems to have been solved simply by setting `hs.window.setFrameCorrectness = true`.

**Comment by lowne** [comment]
Yep; it's not specifically mentioned in the docstring for `setFrameCorrectness`, but this is another one of those cases (along with windows straddling screens in the "wrong" way).

The meta-rule for this situation is something like this: given 4 window corners A1, B1, C1, D1 and their destination corners A2, B2, C2, D2, if *any* point on the lines A1..A2, B1..B2 etc isn't a valid point on (one of the) screen(s), then OSX will refuse the resize.

**Comment by zzamboni** [comment]
Interesting - thanks for the clarification!

**Comment by cmsj** [comment]
If I'm reading this correctly, I don't think there's any action to be taken here, so I'm closing. Please re-open if you disagree :)

**Comment by zzamboni** [comment]
Well, it'd be nice if `setFrameCorrectness` wasn't needed because it makes the movement and resizing quite jerky, but not sure how easy/feasible this would be, and it's not a super high priority, so I'll leave it closed :)
