### ISSUE TITLE
SCNetworkReachability

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#726]
been playing with SCNetworkReachability to have a callback when a vpn network or even the internet itself becomes available/unavailable regardless of the interface it is on... should this go into `hs.host`, or are we approaching the point where we might have enough network related tidbits floating around to justify a separate module as `hs.network` or `hs.networking`?

**Comment by szymonkaliski** [comment]
:+1: on `hs.network(ing)`! I've been using `hs.task` and `curl` tandem for that :)

**Comment by cmsj** [comment]
+1 a reachability callback

I'm slightly ambivalent about an hs.network, but it's probably going to end up being a module sooner or later, and I have no objections to it being sooner :)

**Comment by asmagill** [comment]
Ok, I need to add ipv6 support and I want to test with a few more network configurations, so I'm planning on this for next release.  I'll probably go with `hs.networks` unless there are any objections as I have some other ideas that might come to fruition and fit there as well... `hs.wifi` is pretty targeted to an interface type, and `hs.host.names`, while network related and interface agnostic, also fits in nicely under the `hs.host` umbrella, so I see no reason to move or change anything existent; but I do think it better to get it in now before we have too many more networking related things scattered around.

**Comment by asmagill** [comment]
(by next, I mean not the one we're due for, but the one after it)

**Comment by madeddie** [comment]
so, should this be re-opened? (git doesn't actively reopen on ticket subject change)

**Comment by cmsj** [comment]
thanks, I thought I'd avoided github closing it. apparently not!

**Comment by asmagill** [comment]
`hs.network.configuration`, `hs.network.host`, and `hs.network.reachability` are already in Hammerspoon, so technically the original purpose of this issue has been met and the thread can be closed;  however, I'm going to leave it open for a bit because `hs.network` itself is currently an empty shell except for "requiring" the submodules, not even formally showing up in the documentation (which required a work-around to get `hs.doc.hsdocs` to properly search)...

So, tasks I am assigning to myself to get done in the next couple of days and hopefully make the next release:
* add documentation for `hs.network` as the wrapper containing configuration, host, and reachability submodules
* review host, wifi, etc. and see about putting in convenience wrappers (i.e. syntactic-sugar) for the network related functions found in other modules

**Comment by cmsj** [comment]
@Asmagill you definitely have a few days before the release. I just realised that the code signing setup on my travel laptop is completely broken. Also I need to run through Fabric for potential fixes.
