### ISSUE TITLE
0.9.44 tracking bug

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#727]
We're overdue a release!

@asmagill and @lowne  - anything you consider to be important for 0.9.44 that hasn't already landed? or any bugs that you want to fix before we release?

**Comment by asmagill** [comment]
I'm fine... I have a couple of things in the works, but nothing that's ready enough to hold up a release for.

**Comment by cmsj** [comment]
Groovy, then I shall get on with releasing :)
