### ISSUE TITLE
0.9.44 hs.application():name() depends on unloaded requirements

### ISSUE THREAD

**Issue by wvierber** [Hammerspoon/hammerspoon#731]
When I try to call ```hs.window.focusedWindow():application():name()``` HS will give me following error:
```
string "return hs.window.focusedWindow():application(..."]:1: attempt to call a nil value (method 'name')
stack traceback:
	[string "return hs.window.focusedWindow():application(..."]:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:250: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:244>
```

Loading ```hs.layout``` before executing above command will suppress that error. I just don't see the need for ```hs.layout ``` in this case.

Running the alias ```application():title()``` gives no surprises. 
I got this error since I updated to 0.9.44 yesterday.

**Comment by wvierber** [comment]
Odd, now it seems to work without errors or requiring ```hs.layout```.

**Comment by wvierber** [comment]
Sorry, this really is an issue.

```hs.window.focusedWindow():application():name()``` will **not** work with a empty ```init.lua``` . It will give the error I posted earlier.
While playing around with my config, I discovered that ```hs.window.focusedWindow():application():name()``` works when or ```hs.layout``` or ```hs.redshift``` (the new thing here) are loaded earlier. (there will probably be more)
What am I missing? Should I just use its alias ```:title()```?

**Comment by cmsj** [comment]
Thanks very much for filing this with reproduction info :)

**Comment by wvierber** [comment]
No problem, I'm glad I could help! :-)
Thanks for fixing!
