### ISSUE TITLE
Proposal: standardise on a module init function

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#734]
I think we have a glaring hole in our C modules - they do setup work in their luaopen function that doesn't get reset all the time by __gc.

I propose that luaopen should never do more than register the module/objects with Lua. Everything else should be in an __init, which is explicitly called by init.lua.

I'm prepared to do the work to convert things, if @asmagill agrees :)

**Comment by asmagill** [comment]
While I don't have a problem with the separation in principle if you like the separation better, it doesn't change the fact that the modules you site are not properly using their module level __gc (not their user-data __gc functions)... whether the initialization is automatic or invoked by calling an init function, if it isn't being cleaned up, it isn't being cleaned up.

So, no, no objections, and it may even make it more obvious where the module __gc is lacking, but I don't know that it really gains us much beyond that.  Unless I'm missing something?

**Comment by asmagill** [comment]
I would also argue for leaving the registration of helper functions in the luaopen functions, since sometimes they're the only reason a module is required -- to ensure that the convertors for NSAttributedString (or whatever) exist, whether or not anything else in the module is actually used/needed.

**Comment by cmsj** [comment]
I'm not sure why, but when I wrote this I was thinking that luaopen only gets executed when the .so is loaded, but that's clearly nonsense, so this can be disregarded. Sorry!
