### ISSUE TITLE
hs.geometry details question

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#738]
This can be considered part of #729, but I don't want to distract that issue from being more or less a roadmap or list of things we want to consider for 1.0.

I need clarification on how `hs.geometry` works, so @lowne, this is primarily directed at you...

From the outside (i.e. I don't really care about the internals), how does `hs.geometry` work?  Specifically:
1.  if I have a table which is an `hs.geometry` object, can I reliably use "standard" methods to _always_ retrieve a valid number for keys `x`, `y`, `h`, and `w`?  By standard methods, I mean `table.key` or `table["key"]` in lua, or `lua_getfield(L, idx, key)` in objective-c.
2.  If I have a table with keys `x`, `y`, `h`, and `w` (or the appropriate subset for point and size), is there a simple function which can be called to return the table converted to an `hs.geometry` object?

If the above are true, then integrating this might be pretty easy for things which use the LuaSkin's `pushNSRect`, `pushNSPoint`, and `pushNSSize` and no changes should be required for `tableToNSRect`, `tableToNSPoint`, and `tableToNSSize`.  Of course nothing forces a module to use these methods, and at least some of the older core modules don't, but updating them is a separate milestone from this specific question.

I'll need to give some thought to how to best implement this support through the delegate, since we're trying to keep LuaSkin "pure", but first I need to know if this is a simple thing to add or more complex then I hope :-)

**Comment by asmagill** [comment]
Actually, I might want to tweak the `tableTo*` methods as well... if there is a function for point 2 above, can it be safely called if a table is *already* an hs.geometry object?  Basically, I don't want the LuaSkin methods to have to know before hand if it's a geometry object or not -- they can run it through the function initially to get the keys, whether the table started as a proper `hs.geometry` object or not, and the `pushNS*` methods can run through the function *after* creating the table so what returns is a proper `hs.geometry` object.

**Comment by lowne** [comment]
1. yes, unless lua_getfield skips the metatable (but I don't see why it would)
2. yes: `geoObj=hs.geometry(theTable)` (or `hs.geometry.new(theTable)` to skip the metatable)
2b. yes: `hs.geometry(geoObj)==geoObj` - as required by making `geometry` fully "transparent" (which was the whole point)

**Comment by lowne** [comment]
To be clear re:q1, if you want/need to skip a couple hops along the metatable, you can access `_x`, `_y` etc; but a point object obviously doesn't have `w` and `h` (nor `_w`, `_h`):
```
> p=geometry'0,0'

> p:type()
point

> p.w
nil
```

**Comment by asmagill** [comment]
Thanks...  I'll give this some thought and see about putting together a pull for testing, but I think it should be doable without too much trouble.

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)
