### ISSUE TITLE
HS is crashing whenever an external monitor is attached

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#739]
This is new in the last few days or so.  I haven't changed my `~/.hammerspoon`.  But HS now crashes whenever an external monitor is plugged in.

Console.app shows
```
01/20/16 1:25:24.759 a Hammerspoon[455]: GRAVE BUG: LUA EXECUTION ON NON-MAIN THREAD
01/20/16 1:25:24.814 a Hammerspoon[455]: An uncaught exception was raised
01/20/16 1:25:24.815 a Hammerspoon[455]: Lua execution is happening on a non-main thread
```

Full crash report provided upon request.

**Comment by cmsj** [comment]
Thanks for reporting this, I'll get it fixed later today and cut a new release

**Comment by cmsj** [comment]
Hmm. The relevant code should be protected against this. I'll test locally and if I can't reproduce it, are you ok to run from Xcode or try a test build from me?

**Comment by chdiza** [comment]
If you can provide me instructions, sure.

**Comment by cmsj** [comment]
@chdiza please try: [Hammerspoon.app.zip](https://github.com/Hammerspoon/hammerspoon/files/97429/Hammerspoon.app.zip)

I'm pretty sure this is fixed now, but it would be good to double check :)

**Comment by chdiza** [comment]
Thanks!  I'll check it later today when I'm in the same room with an external monitor.

**Comment by chdiza** [comment]
FYI I also realized that the crashing also occurred whenever the external monitor was UNplugged as well.

**Comment by cmsj** [comment]
@chdiza out of interest, were you running the build of 0.9.44 from us when the crashes happened? or had you built it yourself?

(if ours, do you have crash reporting disabled? I would have expected to get a crash report about this the next time you launched Hammerspoon, but I don't see one)

**Comment by chdiza** [comment]
I tested it, and it seems fixed.  Thanks!

> out of interest, were you running the build of 0.9.44 from us when the crashes happened? or had you built it yourself?

I built it myself.
