### ISSUE TITLE
hs.urlevent logs an error when becoming the default handler for html

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#746]
I've been seeing this in the console on startup recently.

```
Wed Jan 20 17:23:39 2016: "Jan 20 17:21:38 excession Hammerspoon[92041]: (missing delegate):log level 2: Unable to set role handler for public.html: The operation couldn’t be completed. (OSStatus error -54.)"
```

**Comment by cmsj** [comment]
yeah this is a weird one. It ties in to #674 - we need to claim some file types to be able to properly support http:// events in `hs.urlevent` and for some reason the OS gives us an error when we claim the HTML one, but it still sends us HTML, so for now I'm leaving it alone until I can figure out what's going on

**Comment by cmsj** [comment]
(-54 is permErr)

**Comment by cmsj** [comment]
Still have no idea what's going on here, but I'm going to leave it as-is, since there's no actual user-facing breakage.
