### ISSUE TITLE
hide part of hs.chooser UI when there are 0 rows visible

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#748]
I want to use hs.chooser as user input only (without any selection), doing something like this:

``` lua
hs.chooser.new(function(input) print(input) end)
  :rows(0)
  :show()
```

![screen shot 2016-01-21 at 13 14 57](https://cloud.githubusercontent.com/assets/1040420/12480223/fefa7986-c040-11e5-8180-0236c1e19310.png)

It would be nice if only the user input was visible, without the line on the bottom, and extra space.

**Comment by cmsj** [comment]
I do think this is a use-case worth having, but it's also going to need some additional work - the completion callback won't be called if there are no rows to select, and the UI is made of AutoLayout constraint stuff, which I currently don't know how to dynamically remove elements from :)

**Comment by szymonkaliski** [comment]
Maybe then we should distinguish those two options and have `hs.input` as well? I'm currently using  `display dialog` in applescript but it looks ugly compared to this :)

**Comment by cmsj** [comment]
that is an option, yeah. It would also prevent overloading hs,chooser with too many different use cases

**Comment by bradparks** [comment]
wow.... this chooser idea is awesome - i'm actually working on a similar idea myself using the webview and React/MaterialUI, and will post mine somewhere for people to look at sometime soon... but having something like this in the std repo is a big win.... Can this be used from the command line, like the original Choose idea from Steven?

**Comment by cmsj** [comment]
@bradparks there's no multiselect at the moment. I haven't tried, but I imagine one could probably whip up a command line tool using a script that calls `hs` (see `hs.ipc`)

**Comment by deryni** [comment]
The ability to have chooser respond to arbitrary selections is something that I found myself missing just last night (when working on [this](https://github.com/deryni/sshchooser)).

Is that something that wants a feature request filed?

**Comment by cmsj** [comment]
I'm going to close this issue because it doesn't seem to be going anywhere. If someone wants to jump in and help fix the UI, please feel free to do so :)
