### ISSUE TITLE
FOSDEM talk

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#749]
@Habbie is giving a talk about Hammerspoon at FOSDEM in just over a week. This bug is to track ideas/snippets for him to consume.

https://fosdem.org/2016/schedule/event/hammerspoon_os_x_automation_with_lua/

**Comment by jfchevrette** [comment]
Hammerspoon t-shirt. This needs to happen. I'd buy one :)

**Comment by cmsj** [comment]
First off, I promised to give some information about LuaSkin, since that will also be mentioned in the talk:

 * LuaSkin is an Objective C framework that reduces the complexity of integrating a Lua runtime into your app. Its specific focus is providing high level API to replace most of the common, repetitive Lua C API tasks that you're likely to be performing.
 * It doesn't guarantee to make the Lua stack completely safe. You still need to think about what you're doing wrt the stack, but by wrapping up the common operations, we at least reduce the risk of subtle bugs, and ensure that the stack is left as clean as expected after each operation.
 * Its most basic function is to manage the lifecycle of a Lua environment and make it easy to access
```Objective-C
LuaSkin *skin = [LuaSkin shared];
[skin createLuaState];
// App does all its normal stuff until it wants to exit
[skin destroyLuaState];
```
 * The `lua_State` object is exposed as a property, so all of the normal Lua C API can be used (e.g. `lua_pushboolean(skin.L, true);`
 * There are helpers for creating libraries and class objects (where a library is a table of functions and a class object is a table of functions that implicitly pass `self`, i.e. methods that use colon syntax). The class objects carry a metatable entry with the name of their type to make them easier to identify later
 * For each library, a separate table is also created for storing Lua references, keeping all your libraries isolated from a) polluting each other, b) polluting `LUA_REGISTRYINDEX`
```Objective-C
static const luaL_Reg libraryFuncs[] = {
    {"someFunc", some_func},
    {NULL, NULL}
};
static const luaL_Reg libraryMetaFuncs[] = {
    {"__gc", gc_func},
    {NULL, NULL}
};
static const luaL_Reg classMethods[] = {
    {"someMethod", some_class_method},
    {"__gc", object_gc_method},
    {NULL, NULL}
};
int refTable = [skin registerLibrary:libraryFuncs metaFunctions:libraryMetaFuncs];
[skin registerObject:"objectName" objectFunctions:classMethods];
```
 * The C implementation of functions/methods can use LuaSkin to enforce the types of their Lua arguments
```Objective-C
static int some_func(lua_State *L) {
  LuaSkin *skin = [LuaSkin shared];
  // Check that we have been passed only a string and an integer/number
  [skin checkArgs:LS_TSTRING, LS_TNUMBER, LS_TBREAK];
  // Do useful stuff
  return 0;
}
static int some_object_method(lua_State *L) {
  LuaSkin *skin = [LuaSkin shared];
  // Check that we have a valid (implicit) self, and an optional string argument
  [skin checkArgs:LS_TUSERDATA, "objectName", LS_TSTRING | LS_TOPTIONAL, LS_TBREAK];
  // Do useful stuff
  return 0;
}
```
 * Offers conversion between Lua types and equivalent NSObject subclasses (you can also register functions to perform conversions between your Lua class objects and NSObject subclasses, e.g. mapping an `image` class to `NSImage`). Lua tables are bidirectionally convertible to either NSArray or NSDictionary.
```Objective-C
static int some_text_manipulation_func(lua_State *L) {
  LuaSkin *skin = [LuaSkin shared];
  [skin checkArgs:LS_TSTRING, LS_TBREAK];
  NSString *stringArgument = [skin toNSObjectAtIndex:1];
  [skin pushNSObject:stringArgument.capitalizedString];
  return 1;
}
```
 * Makes it easy to store/push/delete Lua references to values, in a table (typically the per-library tables)
```Objective-C
static int some_callback_registration_func(lua_State *L) {
  LuaSkin *skin = [LuaSkin shared];
  [skin checkArgs:LS_TFUNCTION, LS_TBREAK];
  someFunctionRef = [skin luaRef:refTable atIndex:1];
  return 0;
}
```
 * It has a convenience wrapper for `lua_pcall()` that connects `debug.traceback()` as the message handler
```Objective-C
[skin pushLuaRef:refTable ref:someFunctionRef];
[skin pushNSObject:someNSString];
BOOL success = [skin protectedCallAndTraceback:1 nresults:1];
if (success) {
  NSString *resultString = [skin toNSObjectAtIndex:-1];
}
```

**Comment by Habbie** [comment]
In no particular order, a bunch of things that make sense to present

* [ ] the milight stuff (if I can get @cmsj to shoot some video or a few photos)
* [ ] mjomatic
* [ ] hs.tabs
* [ ] hs.expose (with filters)
* [ ] one or two examples around hs.chooser (like app switching)
* [ ] bus times example (via @madeddie)
* [ ] something with a watcher, unsure what for a live demo - pathwatcher? usb?
* [ ] hs.mouse (although this may involve zooming)
* [ ] hs.speech!
* [ ] urlevent (browser picker?)

**Comment by Habbie** [comment]
@mactijn did you ever get your browser picking the way you wanted it?

**Comment by cmsj** [comment]
@Habbie fwiw, I have pretty complete code for a browser picker at: https://github.com/Hammerspoon/hammerspoon/issues/257#issuecomment-137556042

**Comment by Habbie** [comment]
@cmsj shiny

**Comment by mactijn** [comment]
@Habbie unfortunately, no. I ran into some inconsistencies when trying to interact with hs.webview (which I wanted to use for UI -- this was before hs.chooser) and then I . Also, to clarify here, the idea was to choose different profiles within a browser.

@cmsj's code looks fairly usable, I could rebase off of that in my next try :)

**Comment by asmagill** [comment]
@mactijn, I would be interested in getting more details about the inconsistencies you experienced with webview... I'm planning at some point to revisit webview, since 10.11 has added a number of new methods to WKWebView (custom user agent, creating specific cookie stores, etc.), so if there are some other things that need fixing or tweaking, I'd be interested in hearing about them.

**Comment by mactijn** [comment]
@asmagill I can't seem to reproduce it right now (2 minor versions later). I'll create an issue when I run into it again, and tag you. I think Habbie said he saw something similar.

**Comment by Habbie** [comment]
![screenshot 2016-01-28 15 47 23](https://cloud.githubusercontent.com/assets/525838/12647663/84e93d26-c5d6-11e5-846f-d7a1b7bcdba9.png)
