### ISSUE TITLE
Window with nil id as of 0.9.45

### ISSUE THREAD

**Issue by wincent** [Hammerspoon/hammerspoon#750]
I'm seeing a window with a `nil` id starting with 0.9.45. This wasn't happening in 0.9.44. This is causing [my config](https://github.com/wincent/wincent/blob/5dbee52ae32b6b7/roles/dotfiles/files/.hammerspoon/init.lua) to blow up on [this line](https://github.com/wincent/wincent/blob/5dbee52ae32b6b7/roles/dotfiles/files/.hammerspoon/init.lua#L264) with:

```
*** ERROR: /Users/glh/.hammerspoon/init.lua:264: table index is nil
```

I've worked around this by [adding a guard clause](https://github.com/wincent/wincent/commit/907a63aebab77cd0c38528753f363c83b2d1b093) to avoid the use of `nil` as a table index when dealing with the window that has the `nil` id.

Looking at [the changes](https://github.com/Hammerspoon/hammerspoon/compare/0.9.44...0.9.45) from 0.9.44 to 0.9.45 I am not sure what might have occurred to introduce this issue.

(Aside: a lot of that code in my config could be replaced with `hs.window.filter`, but I wanted to report this issue anyway as it seems like it is a lower-level thing, and might be a bug.)

**Comment by cmsj** [comment]
There was a change with the metatable for hs.application objects, and hs.application/hs.window have a...complex...relationship.

I think a good first step would be to add a little bit of code to try and get some information out of the window, like its title and the application it belongs to, so we can rule out it being some odd child window of a running app. If that doesn't turn anything up, I can quickly make you a build that logs the error returned by the C function that gets the window ID (`CGWindowID` internally, see [the source](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/window/window.h) if you're curious)

FWIW, and this is a great sadness, the API for getting the `CGWindowID` from an `AXUIElementRef` (i.e. turning the Accessibility handle for a window into an identifying ID) is private, so we have zero visibility into the rules/usage of it :/

**Comment by wincent** [comment]
Alas, after a reboot, I can't repro this. So, while I know that something changed between 0.9.44 and 0.9.45, I've lost the means to further establish what it is.

Feel free to close if you feel like this isn't actionable.

**Comment by cmsj** [comment]
Let's hold it open for a while and see if it happens again.
