### ISSUE TITLE
hs.grid.show() error

### ISSUE THREAD

**Issue by wvierber** [Hammerspoon/hammerspoon#754]
I noticed this ```hs.grid.show()``` error:
```

...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:392: Invalid key: 1
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:176: in function 'hs.hotkey.internal.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:392: in method 'bind'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:800: in upvalue '_start'
	...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:810: in function 'hs.grid.show'
	(...tail calls...)
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:251: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:245>
```

I tracked back a few HS versions and it looks like there is something wrong with ```hs.grid.show()``` since 0.9.41. In 0.9.41 it returns following:
```
...n 7.app/Contents/Resources/extensions/hs/hotkey/init.lua:391: Invalid key: 1
```

I think it's easy to reproduce via the console. Haven't had time to test other ```hs.grid``` features (or find and fix the gap).

**Comment by wvierber** [comment]
Never mind. (stupid Belgian AZERTY...)
Is there a way to mention incorrect ```hs.grid.HINTS``` settings in the given error to prevent this kind of issues in the future?
But yeah, I should just have read until the very last line of the doc...

**Comment by kbecker87** [comment]
I get the same error message – using a german QWERTZ layout… What exactly did you do to fix it?

**Comment by wvierber** [comment]
You can easily fix it by adjusting `hs.grid.HINTS` in your config.
In my case (see image):
```lua
hs.grid.HINTS = {
		{ "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10" },
		{ "&", "é", '"', "'", "(", "§", "è", "!", "ç", "à" },
		{ "A", "Z", "E", "R", "T", "Y", "U", "I", "O", "P" },
		{ "Q", "S", "D", "F", "G", "H", "J", "K", "L", "M" },
		{ "W", "X", "C", "V", "B", "N", ",", ";", ":", "=" }
	}
```
![screen shot 2016-02-15 at 21 45 26](https://cloud.githubusercontent.com/assets/12418372/13059935/0f12c0a2-d42e-11e5-830a-900259945695.png)

You can also check the [docs](http://www.hammerspoon.org/docs/hs.grid#HINTS).

**Comment by kbecker87** [comment]
Thanks! Works fine now.

**Comment by asmagill** [comment]
I wonder... since the hints are used to generate a hotkey binding, they should all map back to a number in `hs.keycodes.map`, shouldn't they?  This would create the keys in lower case, but since `hs.hotkey` internally does that anyways, it shouldn't matter if my supposition is correct.

Can someone who has a non-US keyboard (or uses one with a non-QWERTY layout) test this function as the generator of the hints table?

~~~lua
function generateCurrentHintsTable()
    local keycodes = require("hs.keycodes")
    local keymap = { 
        { 122, 120, 99, 118, 96, 97, 98, 100, 101, 109 },
        { 18, 19, 20, 21, 23, 22, 26, 28, 25, 29 },
        { 12, 13, 14, 15, 17, 16, 32, 34, 31, 35 },
        { 0, 1, 2, 3, 5, 4, 38, 40, 37, 41 },
        { 6, 7, 8, 9, 11, 45, 46, 43, 47, 44 }
    }

    local results = {}
    for i, v in ipairs(keymap) do
        results[i] = {}
        for i2, v2 in ipairs(v) do
            results[i][i2] = keycodes.map[v2]
        end
    end

    return results
end
~~~

If it works correctly, we could maybe add it with an optional watcher to `hs.grid` so that when the keyboard layout changes, so does the hints table.

**Comment by wvierber** [comment]
I tried your function in ``hs.grid`` and it seems to work for me! Here is my exact test in ``hs.grid``:
```lua
...
-- modal grid stuff below

-- grid.HINTS={{'f1','f2','f3','f4','f5','f6','f7','f8','f9','f10'},
--   {'1','2','3','4','5','6','7','8','9','0'},
--   {'Q','W','E','R','T','Y','U','I','O','P'},
--   {'A','S','D','F','G','H','J','K','L',';'},
--   {'Z','X','C','V','B','N','M',',','.','/'}
-- }

function generateCurrentHintsTable()
    -- @asmagill's function
end

grid.HINTS = generateCurrentHintsTable()

local _HINTROWS,_HINTS = ...
```
I deleted the ``hs.grid.HINTS``table in my ``init.lua``.
Here is a screenshot from the result. My layout can be found in an earlier comment up here.

![screen shot 2016-08-30 at 00 20 59](https://cloud.githubusercontent.com/assets/12418372/18069531/16ca1fb6-6e48-11e6-934f-86f36e74c32b.png)

This should be a great enhancement to ``hs.grid``!
