### ISSUE TITLE
NSWorkspaceActiveDisplayDidChangeNotification

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#755]
This is an undocumented (as far as I can tell) message which can be monitored for with an NSWorkspace observer to detect when the active screen (monitor) changes...

I'd like to add this to hs.screen.watcher (or somewhere in hs.screen), but since it's not documented anywhere that I can find, I want to solicit opinions before doing so.

**Comment by cmsj** [comment]
So, the events are just strings, and this one isn't defined anywhere public, so we'd be passing it as an NSString object. AIUI you can register for any string name event you like - ie if/when Apple deprecates this, we'd just never receive those events, we wouldn't break/error/crash.

Assuming the above is true, +1 for adding it, providing its documented as private and therefore potentially....exciting :)

**Comment by asmagill** [comment]
Yes, the messages themselves are just strings, and your assumption is correct -- if Apple does take the message away, all our watcher would do is never fire, so...

The question where to put it/how to integrate it... As I see it, the possibilities are:

 1. add it to the hs.screen.watcher code, but add an argument to the new function indicating whether the watcher callback should be triggered for a change in the screen layouts (like now) or for the active screen changing -- probably the least work.
 2. add a second type of watcher to hs.screen.watcher -- basically the same as 1, but with a new function name instead of an argument.
 3. a more generic module that is effectively "watch for this message string" or all messages (if you don't pass in a string)... I actually have one more or less already written that I use for testing when trying to figure out the order of message firings (https://github.com/asmagill/hammerspoon_asm/tree/master/_moved_to_core/notificationcenter... ignore the "moved_to_core" folder part... until recently I figured most/all of the useful messages already had watchers, so never proposed the module in this form)... it would need some cleanup and documentation, but would effectively allow adding any watcher for intra-application or workspace messages without requiring an additional module as soon as someone recognizes a message worth watching for

Item 3 is perhaps the most interesting, but would require clear documentation and may lead to "why isn't this working" kind of questions that are primarily caused by typos/misspellings, etc. in the message string.

**Comment by asmagill** [comment]
(FWIW, the module I mention in 3 is how I came across the message, then when googling to confirm what I suspected it was for, found a few references in things like Tunnelblick and Iterm to it, but nothing from Apple)

**Comment by cmsj** [comment]
Maybe hs.spaces.watcher might be a better place? Also I wonder what's the difference between the undocumented notification, and the one we have in hs.spaces.watcher

**Comment by asmagill** [comment]
`NSWorkspaceActiveDisplayDidChangeNotification` is sent when the visible space changes, on any screen.

`NSWorkspaceActiveDisplayDidChangeNotification` is sent only when (a) Displays have separate spaces is checked, and (b) the active screen (i.e. the screen with the window which has focus) changes (i.e. when `hs.screen.mainScreen()` changes its value.

I suppose it could go in spaces as well... it's kind of blend of both, but seems more related to `hs.screen.mainScreen` in my mind... just let me know what the consensus is.

**Comment by asmagill** [comment]
oops... typo corrected above...

**Comment by cmsj** [comment]
ok, then let's throw it in `hs.screen.watcher`
