### ISSUE TITLE
hs.urlevent problem with special characters

### ISSUE THREAD

**Issue by junkblocker** [Hammerspoon/hammerspoon#756]
When trying to open a local file

```
Sun Jan 24 00:35:00 2016: "Jan 24 00:33:01 HOSTNAME Hammerspoon[82365]: ERROR: Unable to parse 'file:///Users/USER/Documents/foo/bar/Dog's Tail/Dog's Tail.HTML' as a URL"
```

**Comment by cmsj** [comment]
Could you post some code that reproduces this? I am guessing that we need to add some kind of URL encoding somewhere.

**Comment by junkblocker** [comment]
I am just using the url redirector example from #257 that you had posted. When clicking on an HTML file in finder that has a space in the name this happens.

**Comment by junkblocker** [comment]
@cmsj , the following patch works.

```diff
diff --git a/extensions/urlevent/internal.m b/extensions/urlevent/internal.m
index f30cb74..140ac99 100644
--- a/extensions/urlevent/internal.m
+++ b/extensions/urlevent/internal.m
@@ -97,6 +97,8 @@ static HSURLEventHandler *eventHandler;
         return;
     }
 
+    openUrl = [openUrl stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
+
     if ([openUrl hasPrefix:@"/"]) {
         openUrl = [NSString stringWithFormat:@"file://%@", openUrl];
     }
```

Usual disclaimers of me knowing nothing about Objective-C/Lua/macOS SDK apply :)

**Comment by junkblocker** [comment]
That patch needs to be made conditional as it doesn't care if content is already properly escape, breaking proper URLs...maybe just for file URLs for now would be good or maybe one attempt before where we are throwing the error currently.

**Comment by cmsj** [comment]
As @junkblocker noted in #1060, this should be closed :)
