### ISSUE TITLE
Character encoding display issue in console

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#759]
```lua
*** ERROR: hs.http callback error: The data couldn‚Äôt be read because it isn‚Äôt in the correct format.
stack traceback:
	[C]: in function 'hs.json.internal.decode'
```
Could be caused by improper NSLog formatting?
http://stackoverflow.com/questions/10940423/my-apostrophe-turns-into-Äô

Root cause from another SO answer:
>You have declared your file to be encoded with UTF-8, so your byte-string literal is in UTF-8. The curly apostrophe is U+2019. In UTF-8, this is encoded as three bytes, \xE2\x80\x99. Those three bytes are written to your output file. Then, when you examine the output file, it is interpreted as something other than UTF-8, and you see the three incorrect characters instead.

>In Mac OS Roman, those three bytes display as ‚Äô.

>Your file is a correct UTF-8 file, but you are viewing it incorrectly.

**Comment by asmagill** [comment]
I'd need to see what the actual text is that the json decoder is choking on.  The issue with the ‚Äô characters is unrelated -- that's because the error message is being generated as UTF8 by `[NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:&error];` in the `hs.json` module, but the code which `hs.http` uses to display it:


~~~lua
    if (![skin protectedCallAndTraceback:3 nresults:0]) {
        const char *errorMsg = lua_tostring(L, -1);
        [skin logError:[NSString stringWithFormat:@"hs.http callback error: %s", errorMsg]];
    }
~~~

treats the error message as a C-string (not inherently Unicode aware) rather then as an NSString (where encoding is assumed UTF8 unless otherwise specified).

**Comment by heptal** [comment]
Here is the code that generated the error. The error occurred on the `local response = hs.json.decode(body)` line.
```lua
hs.hotkey.bind(hyper, "u", function() 
    local image = hs.pasteboard.readImage()

    if image then 
        image:saveToFile("/tmp/tmp.png")
        local base64 = hs.execute("base64 -i /tmp/tmp.png")
        local b64 = string.gsub(base64, "\n", "")
        b64 = hs.http.encodeForQuery(b64)

        local headers = {["Authorization"] = "Client-ID abc123"}

        local url = "https://api.imgur.com/3/upload.json"

        local payload = "type='base64'&image="..b64

        hs.http.asyncPost(url, payload, headers, function(status, body, returnedheaders)
            print(status)
            print(body)
            if status == 200 then
                local response = hs.json.decode(body)
                local imageURL = response.data.link
                hs.pasteboard.setContents(imageURL)
                hs.urlevent.openURLWithBundle(imageURL, "com.apple.Safari")
            end
        end)
    end
end)
```
Luckily I had it printing mostly everything relevant. 
```lua
-- Loading extension: pasteboard
-- Loading extension: http
200
HTTP/1.1 1203
Server: nginx
Date: Mon, 25 Jan 2016 20:32:52 GMT
Content-Type: application/json
Connection: close
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, SESSIONCOUNT
Access-Control-Expose-Headers: X-RateLimit-ClientLimit, X-RateLimit-ClientRemaining, X-RateLimit-UserLimit, X-RateLimit-UserRemaining, X-RateLimit-UserReset
ETag: "a6c52169944def26ad4d7db9a05eddc9f3829a0c"
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: UPSERVERID=i-8d094c3e; path=/

{"data":{"error":"Imgur is over capacity. Please try again.","request":"\/3\/upload.json","method":"POST"},"success":false,"status":1203}
-- Loading extension: json
*** ERROR: hs.http callback error: The data couldn‚Äôt be read because it isn‚Äôt in the correct format.
stack traceback:
	[C]: in function 'hs.json.internal.decode'
	/Users/michael/.hammerspoon/imgur.lua:20: in function </Users/michael/.hammerspoon/imgur.lua:16>
```
I don't think I've ever seen that particular imgur server error before while using Hammerspoon. For comparison here are 2 normal responses printed using the same code:
```lua
400
{"data":{"error":"Image is larger than 10MB. Make the image smaller and then try uploading again.","request":"\/3\/upload.json","method":"POST"},"success":false,"status":400}
```
```lua
200
{"data":{"id":"A5sW3m7","title":null,"description":null,"datetime":1453754635,"type":"image\/png","animated":false,"width":668,"height":500,"size":208634,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":0,"comment_preview":null,"deletehash":"bDVHfcCAEG35LlU","name":"","link":"http:\/\/i.imgur.com\/A5sW3m7.png"},"success":true,"status":200} 
```
As you can see in the response that generated the error, the headers were printed even though I only asked it to print HTTP status and body. It could be a malformed response from imgur's server but I can't reliably reproduce it. In any case, it seems that `hs.http.asyncPost` mushed the body+headers together in what was sent to its callback (in `connectionDidFinishLoading`?), so that could be a new and separate issue. That method seems pretty straightforward; I can't see where it could have happened unless `NSURLConnection`'s `receivedData` had the wrong contents.

**Comment by asmagill** [comment]
Ok, according to the docs:

> Discussion
> In rare cases, for example in the case of an HTTP load where the content type of the load data is multipart/x-mixed-replace, the delegate will receive more than one connection:didReceiveResponse: message. When this happens, discard (or process) all data previously delivered by connection:didReceiveData:, and prepare to handle the next part (which could potentially have a different MIME type).

I'm going to guess that for whatever reason, the `didReceiveResponse` delegate method was called twice and I can verify that the code currently doesn't clear the received data buffer as indicated above... Not sure how easy it would be to setup a server that causes this situation predictably, but in any case, if someone doesn't get a chance to do so before I can, I'll put together a pull which addresses this later tonight.  I don't know how often you have this problem, so we may have to wait a while to verify it fixes this, but it sounds likely.

**Comment by heptal** [comment]
I think I understand the issue/fix (found similar code addressing this as well) and made the pull request. I suppose these string encoding quirks can be useful for identifying more subtle bugs :)
