### ISSUE TITLE
Slow response when Emacs is busy - singe thread problem?

### ISSUE THREAD

**Issue by srustamo** [Hammerspoon/hammerspoon#760]
Running, say, `package-list-packages` in Emacs takes a bit of time, and calling, say, `hs.hotkey.bind(mash, '.', hs.hints.windowHints)` will not show the hints until Emacs is finished.

**Comment by cmsj** [comment]
this is because we use the Accessibility framework for talking to windows, and the way that works is that OS X sends a message to the application you're inspecting/controlling, and the application has to respond.

There isn't really an easy way around this, unfortunately :(
