### ISSUE TITLE
hs.grid.toggleShow(nil, true) no longer works in 0.9.45

### ISSUE THREAD

**Issue by jesselang** [Hammerspoon/hammerspoon#761]
Worked with a previous version, broke after the version was updated.

```
local mash = {"ctrl", "alt", "cmd"}

local log = hs.logger.new('config','debug')

hs.hotkey.bind(mash, "Space", function()
    hs.grid.toggleShow(nil, true)
end)
```

**\* ERROR: hs.hotkey callback error: ...oon.app/Contents/Resources/extensions/hs/window/init.lua:125: attempt to call a nil value (method 'visibleWindows')
stack traceback:
    ...oon.app/Contents/Resources/extensions/hs/window/init.lua:125: in function 'hs.window.visibleWindows'
    ...oon.app/Contents/Resources/extensions/hs/window/init.lua:141: in function 'hs.window.orderedWindows'
    ...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:676: in upvalue 'startCycling'
    ...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:814: in function 'hs.grid.show'
    ...spoon.app/Contents/Resources/extensions/hs/grid/init.lua:824: in function 'hs.grid.toggleShow'
    /Users/jesse/.hammerspoon/init.lua:6: in function </Users/jesse/.hammerspoon/init.lua:5>

**Comment by jesselang** [comment]
I was able to get the grid working by removing the arguments. I would like to use the multipleWindows option. How should I be doing that?

**Comment by cmsj** [comment]
Are you still able to reproduce this? It worked for me on 0.9.54. Please re-open if it's still an issue :)
