### ISSUE TITLE
hs.window.filter doesn't "see" Chrome windows

### ISSUE THREAD

**Issue by wincent** [Hammerspoon/hammerspoon#764]
Just started playing with `hs.window.filter` and have noticed that it doesn't "see" Chrome windows:

```
local log = hs.logger.new('debug', 'debug')

local filter = hs.window.filter.new(true)
filter:subscribe(
  hs.window.filter.windowCreated,
  (function(window, applicationName)
    log.wf('got a callback from %s', applicationName)
  end),
  true
)
```

The above will log something when I create windows in other apps, but not in Chrome, despite the `true` passed into the constructor (which should allow all windows through).

This on 0.9.45.

**Comment by cmsj** [comment]
I'm unable to reproduce this with 0.9.54 and current Chrome. My guess would be that Chrome improved their weird window handling in the last ~year.
