### ISSUE TITLE
Enable Binding of Command+Tab

### ISSUE THREAD

**Issue by tscheffe** [Hammerspoon/hammerspoon#766]
Right now this isn't working out of the box:

``` lua
hs.hotkey.bind({"cmd"}, "Tab", function ()
  hs.hints.windowHints(nil)
end)
```

I was able to get it working by using Karabiner to change `cmd+tab` to emit `F19` and binding to that. It would be awesome if I didn't have to use an external dependency. The issue is that the normal cmd+tab, Application Switcher, functionality is embedded really deeply into the OS and you can't bind it via normal means.

I asked about it on the IRC chat and mentioned that Slate let you bind window hints to cmd+tab. `Ng` did some investigating and said they're using event taps and that Hammerspoon could do something similar.

Hopefully it's a feature we can get included!

Thanks again `Ng` for all of your help on the forums.

**Comment by cmsj** [comment]
@tscheffe I'm sorry we've not replied to this sooner. We do have eventtap support (see http://www.hammerspoon.org/docs/hs.eventtap.html) - I think that should cover what you need? If not, please feel free to re-open this.

**Comment by marekzidek** [comment]
It seems like it covers it, but are there any examples? Even though hammerspoon docs are really great, I find it hard to dig this particular usecase from eventtap. Also, I cannot find any examples on the internet without Karabiner.

**Comment by kjslag** [comment]
This seems to work for me.
```
switcher = hs.window.switcher.new(hs.window.filter.new():setCurrentSpace(true))
function mapCmdTab(event)
    flags = event:getFlags()
    chars = event:getCharacters()
    if chars == "\t" and flags:containExactly{'cmd'} then
        switcher:next()
        return true
    elseif chars == string.char(25) and flags:containExactly{'cmd','shift'} then
        switcher:previous()
        return true
    end
end
tapCmdTab = hs.eventtap.new({hs.eventtap.event.types.keyDown}, mapCmdTab)
tapCmdTab:start()
```
