### ISSUE TITLE
Hammerspoon Console input textblock

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#77]
I should probably look into this myself, so I can learn, but maybe it's easy and can be done by one of you with a few lines...

I just recently found that I can insert a return while typing in text by using opt-Return... useful for testing out AppleScript... how hard would it be to make this input field tall enough for a few lines?  Or auto grow and shrink as needed?  Or put a handle on it for dragging?

I'll probably look into it myself eventually, but if it's simple and useful to others, maybe it can be done faster by someone else.

**Comment by cmsj** [comment]
(for the record, I'm basically just handwaving over things like the arrow keys, because I don't want to dive into a rabbit hole of changing UI behaviours, and anyone who even knows they can hit opt-Enter, can probably figure out opt-arrows :)
