### ISSUE TITLE
feature request: OSX Keychain access

### ISSUE THREAD

**Issue by teunvink** [Hammerspoon/hammerspoon#770]
Access to OSX Keychain could be useful. It can be achieved by executing the `security` binary and parsing the resutls (as done for example in [this script](https://github.com/teunvink/hammerspoon/blob/master/token.lua)), but some native bindings would be nice.

**Comment by asmagill** [comment]
I have played with the OS X Keychain Services API somewhat before (see https://github.com/asmagill/hammerspoon_asm/tree/master/keychain, if curious, though it's pretty limited at present) but decided doing a full treatment of all of the possible options wasn't going to be worth the effort at the time... If the main need is to simply query for generic or internet passwords, it should be pretty simple to do... are there other keychain activites that should be considered as well (perhaps adding passwords to the keychain?)

**Comment by teunvink** [comment]
Thanks for sharing that. I can only speak for myself, but for me retrieving passwords and perhaps storing them would be enough for the cases I can think of at this moment.

**Comment by cmsj** [comment]
There are quite a few Cocoapods that wrap the Keychain API in something higher level. It might be worth investigating one of those

**Comment by redmice** [comment]
An interesting use case could be to access the WiFi passwords. That way, a call to `hs.wifi.associate` would not have to include a passphrase in cleartext in your .lua files.

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
