### ISSUE TITLE
hs.location.sunrise throwing field min not an integer

### ISSUE THREAD

**Issue by adamgibbins** [Hammerspoon/hammerspoon#771]
```
> hs.location.sunrise(1, 1, 0)
...n.app/Contents/Resources/extensions/hs/location/init.lua:161: field 'min' not an integer
```

Per IRC:
\<heptal\> it's a bug, the geometrical calcs used for sunrise call os.date, which only accepts int arguments, and a fractional argument generated by those calcs is being passed into the minute field

**Comment by cmsj** [comment]
I think this should be a relatively easy fix to `extensions/location/init.lua` line 162 (and we might want to capture the fractional remainder of minutes and convert it to seconds and throw that into the date constructor too)

**Comment by heptal** [comment]
Also, what do you think about a flag for if location services are currently active?
Say a user wants to set `hs.redshift.start`'s `nightStart/End` using their current location's sunrise/sunset times. They could do something like
```lua
if not hs.location.isActive() then
   hs.location.start()
   loc = hs.location.get()
   hs.location.stop()
else 
  loc = hs.location.get()
end

lat, long = loc.latitude, loc.longitude
...
...
```
without either leaving location updates running unnecessarily or ending updates in case another bit of code is currently using them. Something like
```diff
diff --git a/extensions/location/internal.m b/extensions/location/internal.m
index 81d6f0b..a94f87d 100644
--- a/extensions/location/internal.m
+++ b/extensions/location/internal.m
@@ -5,6 +5,7 @@

 @interface HSLocation : NSObject<CLLocationManagerDelegate>
 @property (strong, atomic) CLLocationManager* manager;
+@property (nonatomic, assign, getter=isActive) BOOL active;
 @end

 static HSLocation *location;
@@ -106,6 +107,7 @@ static int location_start_watching(lua_State* L) {
         return 1;
     }
     [location.manager startUpdatingLocation];
+    location.active = true;
     lua_pushboolean(L, 1);
     return 1;
 }
@@ -224,6 +226,20 @@ static int location_is_enabled(lua_State *L) {
     return 1;
 }

+/// hs.location.isActive() -> bool
+static int location_is_active(lua_State *L) {
+    BOOL active = (location && location.active) ? true : false;
+    lua_pushboolean(L, active);
+    return 1;
+}
 // ----------------------- Lua/hs glue GAR ---------------------

 static int location_gc(lua_State *L __unused) {
@@ -237,6 +253,7 @@ static const luaL_Reg locationlib[] = {
     {"stop", location_stop_watching},
     {"get", location_get_location},
     {"services_enabled", location_is_enabled},
+    {"isActive", location_is_active},
     {"distance", location_distance},
     {NULL, NULL}
 };
```

**Comment by cmsj** [comment]
I don't hate the idea, but I want to note that calling location.get right after location.start is not reliable, it can take a little time to get a reliable location. What I'd really like is a location API that enables location finding, calls a callback when it's stabilised, then disables location finding.

It's a simple idea, but it would need to be implemented carefully to avoid interfering with other Lua code doing location things.
