### ISSUE TITLE
hs.pathwatcher stops watching after some time

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#774]
It seems that after some (variable) amount of time, `hs.pathwatcher` objects will spontaneously stop. This is obvious with the standard config reload: 
```lua
hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", hs.reload):start()
hs.alert.show("Config loaded")
```
because it will stop responding to saved changes. Upon manual reload it will work fine (until it doesn't).

**Comment by cmsj** [comment]
@heptal you need to capture the result of `hs.pathwatcher.new()` into a variable. This catches a lot of people out, all of our constructors return a Lua userdata object, which, if not captured, will eventually be garbage collected.

**Comment by heptal** [comment]
\*facepalm\* duh. In my actual config I had it referenced as a local variable, since I had other things like menubars captured as locals (but they are referenced in other places preventing collection) and wasn't thinking. Can confirm that `collectgarbage()` removes it.
