### ISSUE TITLE
Philips Hue extension

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#779]
Philips provide some kind of .framework, or there's some simple open source stuff we could clone (see https://github.com/benknight/hue-alfred-workflow/ )

(if the latter, don't forget to use the https://www.meethue.com/api/nupnp trick)

**Comment by cmsj** [comment]
This doesn't need to be here anymore, it could be implemented as a pure Spoon.

**Comment by asmagill** [comment]
FWIW, I have started working on this at https://github.com/asmagill/hammerspoon_asm/tree/master/hue though it's still in its infancy and should be converted to a spoon.

It does use UPNP to discover your device, but should probably allow for a hard coded IP address as well to shortcut the query (quicker failure detection when on a different network for example) and needs better examples and maybe some specificly targeted functions as well -- currently you have to know the Hue API, the module just gives you wrappers for the get, post, and put methods and stores your user id, etc. so you don't have to remember them or include them in your example code.

The code is up for grabs if anyone wants to take it further; I may at some point, but then again may not... I can do what I need ATM, and have other more interesting and immediate items I'm currently working on.

**Comment by cmsj** [comment]
@asmagill note that the nupnp URL I linked to has nothing to do with UPnP - it's a clever thing Philips have done where you just fetch that URL and the JSON response tells you the LAN IPs of Hue bridges behind your current public IP.

**Comment by asmagill** [comment]
Yeah, I have that disabled on mine.  But I suppose if this is moved to a spoon, all three methods should be supported.

**Comment by asmagill** [comment]
(FWIW the UPNP is totally lua based -- it uses hs.socket)

**Comment by cmsj** [comment]
yeah your upnp code is cool, just wanted to note the nupnp trickery :)
