### ISSUE TITLE
Migrate to using .xcconfig files

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#786]
It turns out that there is a solution to the crazy proliferation of Xcode settings, and merging and other related horrors - we could just put all of our build settings in .xcconfig files and configure our .xcodeproj files to pull in their settings from there. This would also potentially allow us to have a single `extensions-Shared.xcconfig` file for all of the extensions.

Some relevant links:

http://www.jontolof.com/cocoa/using-xcconfig-files-for-you-xcode-project/

and when you've read that and jaw-dropped at how much work it would be to pull out all the current settings, read:

http://jamesdempsey.net/2015/01/31/generating-xcode-build-configuration-files-with-buildsettingextractor-xcodeproj-to-xcconfig/ (which leads to https://github.com/dempseyatgithub/BuildSettingExtractor )

**Comment by mgee** [comment]
I once extracted the Hammerspoon and extensions Xcode settings into gyp files.
Perhaps this reduces some work:
https://github.com/mgee/hammerspoon/blob/gyp/Hammerspoon.gyp
https://github.com/mgee/hammerspoon/blob/gyp/extensions/lua_extension.gypi

**Comment by cmsj** [comment]
@mgee I do like the GYP option, but I'm not sure about whether it's a good idea or not, mainly because I haven't used it. I already suspect that moving to .xcconfig would require us to ditch Cocoapods for Carthage (because pods like to write out lots of .xcodeproj/.xcworkspace data).

I'm not intending on making any changes here in the immediate future, I mostly created this issue so I wouldn't lose the links :)

**Comment by mgee** [comment]
@cmsj What I meant to say was that the `xcode_settings` blocks in the gyp files already contain many extracted Xcode settings which can possibly be reused for `.xcconfig` files. The syntax is only slightly different.

**Comment by cmsj** [comment]
I'm going to close this out because the idea never really got any traction, and I don't have time to do the migration.
