### ISSUE TITLE
systemWillSleep systemWillPowerOff are incorrect in documentation

### ISSUE THREAD

**Issue by sfcgeorge** [Hammerspoon/hammerspoon#788]
In [the documentation](http://www.hammerspoon.org/docs/hs.caffeinate.watcher.html#systemDidWake) these methods are listed as 

`hs.caffeinate.watcher.systemWillPowerOff` and `hs.caffeinate.watcher.systemWillSleep`

but they should be  `hs.caffeinate.watcher.willPowerOff` and `hs.caffeinate.watcher.willSleep`

as can be seen from the [code here](https://github.com/Hammerspoon/hammerspoon/blob/80038f62060409ff75d05a13a961924a8cfad75a/extensions/caffeinate/watcher.m#L77)

**Comment by cmsj** [comment]
Are you seeing a problem with using them in Lua? The enum you linked to isn't the canonical storage of the names of the events, it's just a numerical list that we use to pass around the event types as numbers (which is what is actually sent to the Lua callback, for it to compare against the values stored in hs.caffeinate.watcher.systemWillPowerOff and friends)

**Comment by sfcgeorge** [comment]
Ah I see. Well the names given in the documentation weren't working for me, but after changing to `willSleep` that event works but power never seems to work for me either way. Maybe because I'm trying to listen to the power off event in hs then make a http request to another process—could that be getting killed before the event fires?

**Comment by cmsj** [comment]
that is possible, yeah

**Comment by cmsj** [comment]
I'm not sure there's anything actually wrong here so I'm going to close the issue. Please re-open it if you disagree :)
