### ISSUE TITLE
feature request: awesome-wm-like window dragging/resizing

### ISSUE THREAD

**Issue by atsepkov** [Hammerspoon/hammerspoon#790]
I'm not sure if it's already scriptable and I just suck at wrapping my head around it or if something is missing (seems like ability to stack mouse events with keyboard events is missing), but after a few attempts at trying to get window-dragging/resizing similar to `awesome wm`, I am now stuck.

For those unfamiliar with awesome wm, here is what I'm trying to accomplish:
- holding Windows/Command key + clicking and dragging a window allows the user to drag the window by any portion of the window (effectively turning entire surface area of the window into a titlebar)
- holding Windows/Command key + right-clicking a window allows the user to resize it by any portion of the window (effectively turning entire surface area of the window into a window border, such that the corner that gets resized by is the one closest to the mouse pointer at the time of the click)

This may not seem like much but it's very convenient and makes titlebars unnecessary (which in turn would allow me to use borderless compilation of iTerm).

My main issue seems to be that I can't figure out how to stack keyboard "pressed key" state with "mouse click" or "mouse move" events. I tried modal events (which didn't seem like the right way to go since releasing the key should reset the state) as well as a few other alternatives but couldn't get this to work.

**Comment by deryni** [comment]
I would like this too. I went looking for how to find the window under the mouse and came across https://gist.github.com/kizzx2/e542fa74b80b7563045a which looks, at a glance or two, like it does this.

I don't have time to try it right now though and I think I'd make some changes to it before using it myself but it is probably worth a try.

**Comment by cmsj** [comment]
@atsepkov it's quite a large hammer to use, but have you looked at using hs.eventtap for this?

**Comment by cmsj** [comment]
Closing due to lack of response.
