### ISSUE TITLE
Feature Request: Add an hs.bluetooth module

### ISSUE THREAD

**Issue by EranAvidor** [Hammerspoon/hammerspoon#793]

**Comment by Habbie** [comment]
Hello, what features are you thinking of in this module?

**Comment by EranAvidor** [comment]
Hi, it should behave something like the wifi module
basic functionality should support toggling ON/OFF, get list of devices..
how does it sound?

**Comment by reestr** [comment]
Perhaps the ability to enumerate the connected devices.  Also a watcher to trigger events as bluetooth devices are connected/disconnected.

**Comment by chdiza** [comment]
At the very least the ON/OFF mechanism would be nice.  Even people like me who don't use Bluetooth can benefit from an easy way to ensure that it's turned off and not draining the battery.  I've been using [this](https://github.com/toy/blueutil), but it seems like it's dead or near-dead.

**Comment by cmsj** [comment]
The issue here is that there is no public API for interacting with Bluetooth hardware in OSX. You might like to look at https://github.com/asmagill/hammerspoon_asm.undocumented/tree/master/bluetooth

**Comment by EranAvidor** [comment]
@cmsj thanks

**Comment by cmsj** [comment]
I'm going to close this out for now, since there's not much we can safely/reasonably do in the main tree. If that changes, we'll jump on it :)

**Comment by retrography** [comment]
I realize this thread is old, but it finishes with an upbeat promise from @cmsj! So, here you are:

I have just found out there is [this command line tool](https://github.com/toy/blueutil) for working with Bluetooth devices using macOS's private APIs. The program is not new, but the new version is pretty powerful and its methods may be worth considering. [Here](https://gist.github.com/ysimonson/fea48ee8a68ed2cbac12473e87134f58) you can find a test config. I use it to connect/disconnect the bluetooth devices on my work desk (e.g. mouse and keyboard) each time I plug/unplug my external monitor. Very useful.

I have noticed that now `hs.battery` relies on private bluetooth API. Then why not a full extension for BT?

**Comment by drn** [comment]
Thanks for pointing out [toy/blueutil](https://github.com/toy/blueutil)!

In case it's helpful for anyone else, you can easily hook into existing CLIs from HS bindings via `hs.execute`. You'll need to supply full paths to the CLIs, but it allows replication of the same functionality as you'd get with a native bluetooth hammerspoon module.

Something like:
```
function bluetooth.toggle()
  local output = hs.execute("/usr/local/bin/blueutil --connect 00-00-00-00-00-00")
  alert.showOnly(output:gsub('%s*$', ''), 1, 20)
end
```

Here's how I hooked it into my HS setup:
* https://github.com/drn/dots/blob/master/bin/hd1 (handled toggle logic within bash script, rather than lua so i could have a CLI alias as well)
* https://github.com/drn/dots/blob/master/hammerspoon/bluetooth.lua

**Comment by kartikeytewari** [comment]
@drn Thanks! That works flawless.

**Comment by mwagstaff** [comment]
Also worth noting that if you use blueutil, you'll need to grant Hammerspoon permissions via Settings -> Privacy & Security -> Bluetooth -> Add (+).
