### ISSUE TITLE
focusWindowEast / focusWindowWest crash

### ISSUE THREAD

**Issue by sodiumjoe** [Hammerspoon/hammerspoon#799]
To reproduce in the hammerspoon console:

`> hs.window.focusedWindow().focusWindowWest()`

resulting error:

```
...oon.app/Contents/Resources/extensions/hs/window/init.lua:125: attempt to call a nil value (method 'visibleWindows')
stack traceback:
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:125: in function 'hs.window.visibleWindows'
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:141: in function 'hs.window.orderedWindows'
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:602: in upvalue 'windowsInDirection'
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:704: in function 'hs.window.windowsToWest'
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:712: in function 'hs.window.focusWindowWest'
	(...tail calls...)
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:251: in function <...app/Contents/Resources/extensions/hs/_coresetup/init.lua:245>
```

**Comment by jessevogt** [comment]
I was running into a similar issue (same `nil` value in `visibleWindows`) and came across this https://github.com/Hammerspoon/hammerspoon/issues/736. One of the comments mentioned the problem going away by calling `hs.application`. I put `hs.application.runningApplications()` at the top of my init file and it seems to be working again.

**Comment by sodiumjoe** [comment]
@jessevogt thanks for the suggestion! I fixed it by following the suggestion to filter the window list here: https://github.com/Hammerspoon/hammerspoon/issues/595
