### ISSUE TITLE
Issues with audio device that is both an input and an output

### ISSUE THREAD

**Issue by conkiztador** [Hammerspoon/hammerspoon#801]
There's an assumption in hs.audiodevice that a device is either an output or an input device, but I have a USB headset that shows up as both. Because of this only the output volume can ever be queried or manipulated.

**Comment by cmsj** [comment]
Very good point, thanks! I'll have a think about how we can deal with this without breaking the current API too much :)

**Comment by cmsj** [comment]
@conkiztador are you able/interested in testing from git? If so, I would welcome feedback on whether this is resolved for you now. I've added specific methods for input/output volume:

 * hs.audiodevice:inputVolume()
 * hs.audiodevice:outputVolume()
 * hs.audiodevice:setInputVolume()
 * hs.audiodevice:setOutputVolume()

**Comment by conkiztador** [comment]
@cmsj Awesome! Thanks a lot for the quick fix. I tested this and it's working well for me in a script using `inputVolume` and `setInputVolume`.   :+1:
