### ISSUE TITLE
proposed additions to LuaSkin

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#809]
I may have mentioned some of these in the past, but I want to put these forth and see if/how they may fit or affect plans others may have for LuaSkin/Hammerspoon...

* `checkArgs:`
  * add `LS_TINTEGER`.  This would remove a followup check that often occurs after verifying something is a number and make the error message more consistent since they would be coming from the same code source.  Should this be separate from `LS_TNUMBER` or something bitwise-or'ed like `LS_TOPTIONAL`?
  * there needs to be a way to specify `LS_TUSERDATA` without requiring the followup of the userdata type... this is required both so that `LS_TUSERDATA` can be paired with `LS_TOPTIONAL` and so you can specify that you want a userdata, but don't care the type (or will check the type later, because it could be more than one type in that argument position).
  * remove `LS_TNONE`. It serves no purpose as there is no way to specify a place holder that can't have something in it's place... It makes sense in `LUA_Txxx` type equivalents, since `nil` and `none` are identical to some of the `lua_toXXX` functions, and the don't require a terminating `LS_TBREAK`, but we do in `checkArgs:`
  * which leads to `LS_TBREAK`... should it be required?  Currently (or at least I haven't figured it out) there is no way to say "... and whatever else follows, as much as you want, following the initial requirements specified".  Or should we add something like `LS_TVARIABLE` as an alternative/or'ed  to/with `LS_TBREAK`?

* `pushNSObject:`
  * I finally have a reasonable prototype for an `NSValue` converter (well, I will later today/tomorrow) that can handle the known types it can hold, as well as provide the contents and some information about size and obCType when it doesn't hold something well known like NSRect, NSSize, etc.  I plan to put this in so rects, etc. stored in an NSValue because they are in an NSArray or NSDictionary can be properly pushed into Lua as their Hammerspoon equivalent table formats.
  * which poses the question... do we mirror this in the `toNSObjectAtIndex:` method by allowing it to check tables for a `__type` field which can be set to known types (primarily `color`, `rect`, `point`, and `size`, but there may be others that could benefit from this, like `styledtext`, etc.)

I'll probably think of more later (I always seem to!), but that will do for what is on my mind at the moment...

Agreements?  Disagreements?  Is something pending and I should wait?

**Comment by asmagill** [comment]
... so I don't forget it:

* allow helper functions for `pushNSObject:` to return -1, indicating that it did not handle the conversion and another convertor or the default set should do so.  This came up during testing of the `NSValue` addition I want to add because I initially added it as a helper function in a test module (quicker to re-compile) and found out that NSNumber is a sub-class of NSValue... suppose if I'd read closer...

**Comment by cmsj** [comment]
re checkArgs, I have been wondering if it would be smarter to switch to objc array literals. The current scheme is C varargs, which works, but as you have identified with your  list, is fragile and inflexible.

re LS_TINTEGER, there isn't a separate Lua type for integers, they're still LUA_TNUMBER, and any LUA_TNUMBER can be cast to an integer, so I'm not entirely sure what we'd be able to check here?

re LS_TUSERDATA, I think it ought to be possible to make it LS_TOPTIONAL-able, we'd just need to silently consume the next argument. It's still a little inflexible in that we can't allow multiple valid userdata types.

re LS_TNONE, I think that should be safe to remove

re LS_TBREAK, it absolutely is required because there is no way to automatically detect the end of a C va_args list. We could add an LS_TVARIABLE before the LS_TBREAK to indicate that checkArgs should not complain about extra arguments.

I like the sound of NSValue support for the push stuff, and I think it could be useful to have it mirrored in toNSObjectAtIndex.

**Comment by asmagill** [comment]
Re LS_TINTEGER, we can follow the number check with lua_isinteger or luaL_checkinteger in checkArgs:. Currently I have to add it as a separate check after the checkArgs: line.

**Comment by asmagill** [comment]
The LS_TINTEGER option has been added in the WIP #812.  lua_tointeger(L, idx) converts 9.0 into 9, but 9.1 into 0, so unless you're prefixing it with lua_isinteger (which doesn't recognize 9.0) or luaL_checkinteger (which does, but still doesn't like 9.1), it's inconsistent and better to specify in the arguments, IMO.

See the WIP for other additions.

Need to give thought to how to handle userdata stuff, hence the WIP tag, though honestly I'm happy with what's there, it's just not everything in this list.

As for switching over to objc array literals... I like being able to check the arguments and not having to worry about it in my code, but I don't really have strong opinions as to how it's done.

**Comment by asmagill** [comment]
Oh, and expanding the lua->NSObject stuff so it can convert table representations (e.g. a color table) and not just userdata objects into NSObjects...

Should it look for the __type field? or should we use a different key name?  It needs to be something that we can safely tell Hammerspoon users/coders that they can't use for anything else without the possibility of confusing things in complex data structures being converted into NSObjects...

**Comment by cmsj** [comment]
I think I was looking at 5.1/5.2 docs when I made my comments about Integer/Number handling :/

**Comment by asmagill** [comment]
Pull #812 address most of the issues here except for:

* `LS_TUSERDATA` and being optional (or without a specified type or with multiple types, things not mentioned here, but discussed as limitations before)... should I look into this (I haven't done much beyond tweaking already in place `varargs` code, but I'm a quick study) or are you serious about planning to replace `varargs` with something perhaps a little more flexible?

* adding support in `toNSObjectAtIndex:` so that tables with a special key-value pair can be matched to a conversion function to allow more seamless conversion into NSObjects.  Do we want this, and if so, what should the key name be to minimize the likelihood of the key being used by something else?  `__type` seems too generic...  `__luaSkinType`?

At any rate, I feel #812 should probably be landed as is, since these require discussion and thought and perhaps belong in there own pull so we don't put off another release just for them.

**Comment by heptal** [comment]
```lua
choices={
  {
    text = "asdf",
    subText = "laksjdlkd adsfldk ",
    image = hs.image.imageFromPath("~/Desktop/file.png"),
  },
  {
    text = "asdf",
    subText = "laksjdlkd adsfldk ",
    image = hs.image.imageFromPath("~/Desktop/file.png"),
  }
}

c = hs.chooser.new(print):choices(choices)
********
00:33:00 ERROR:   LuaSkin: [string "choices={{..."]:11: :dictionary key (image) cannot be converted into a proper NSObject
********
********
00:33:00 ERROR:   LuaSkin: [string "choices={{..."]:11: :array element (table: 0x7fdec5ea2d10) cannot be converted into a proper NSObject
********
********
00:33:00 ERROR:   LuaSkin: hs.chooser:choices() table could not be parsed correctly.
********
```
Something in the recent changes to LuaSkin broke something related to pushing compound objects like what `hs.chooser` consumes (tables with `hs.image`).

**Comment by asmagill** [comment]
In working on pull #812, I noticed a similar issue with some userdata objects not being identified properly, depending upon how the module's code expected to retrieve them... assuming the error was in my manual handling of the conflict merge fixes, I neglected to verify the master branch.

I've updated master with the fix.

**Comment by cmsj** [comment]
Sorry :/

**Comment by asmagill** [comment]
np, it was a big -- and having reviewed it closely when dealing with the merge-conflict, positive -- change for the better, IMO.  I should have checked both when I discovered it though... I just assumed I had screwed up the manual merge!

**Comment by asmagill** [comment]
Will open a separate issue for remaining concerns.  Closing since #812 address most of this issue.
