### ISSUE TITLE
Clean up XCode Project

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#810]
It seems the time to streamline the xcodeproj is well-overdue. It turns out a few simple tasks can clean it up tremendously, removing many thousands of lines from the .pbxproj, which should make just about everything easier and more robust going forward. Creating this issue to track general progress and for further suggestions
### Clean up frameworks

Every target has a random selection of frameworks linked against in build settings. They can have some or all or none of Cocoa, Foundation, LuaSkin, etc. It is no longer [necessary](http://clang.llvm.org/docs/Modules.html#semantic-import) as long as they are modules (as frameworks are) and in the right place. System frameworks load automatically, Podfile-managed frameworks load automatically, and the LuaSkin framework does as well with correct build settings.
- [x] **Move Fabric/Sparkle to Podfile and update others** Just a few minor version updates. Nothing breaks here
- [x] **Trash Pods project, `pod install`, use generated .xcconfig** Regenerates everything freshly
- [x] **Change Crashlytics/Fabric `#include`s to `@import`s**
- [x] **Entirely remove Frameworks group** This automatically removes all references from the project, including all the `Link Binary With Libraries` build phases throughout the project. The `Embed Pods Frameworks` and `Copy LuaSkin.framework` build phases on the Hammerspoon target take care of everything. _ALL_ contents of PBXFrameworksBuildPhase and their corresponding references in PBXNativeTarget can be removed. Very satisfying!
- [ ] **Remove instructions in contributing docs for linking frameworks**  

In my local repo all tests pass with the above. Can PR
### Migrate to using .xcconfig files #786

I have played with [BuildSettingExtractor](https://github.com/dempseyatgithub/BuildSettingExtractor) and explored the output a bit. These files can `#include` one another. When I checked for dupes, it turned out there are just a few unique variants of build settings for all the targets. We can have a just a few .xcconfig files that cover just about everything: a `regular` module build file, a `strict` one (`regular` with -Weverything & -Werror added for modules have have undergone refactoring/testing). Each target's .xcconfig would then just have single line importing one of the common ones, and possibly a line or 2 for module-specific build settings (like OS version requirements). Exploring some scripts to do this reliably.

**Comment by heptal** [comment]
The way `.xcconfig` files work is by cascading from right to left, from OSX defaults, to project build settings, to `.xcconfig` files, and finally in-XCode build settings.
![](http://i.imgur.com/Un7RQi0.png)

 `.xcconfig` files can include one another to create a dependency graph. Instead of huge verbose build settings for debug and release of every target, I have created the following set of `.xcconfig`s, which, combined with the OSX and project defaults and custom flag in a few places, gives us the previous build setting configuration (which passes all tests):

**module-Debug.xcconfig**:
```c
// General module Debug build settings

DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
ENABLE_TESTABILITY = YES
MTL_ENABLE_DEBUG_INFO = YES
```
**module-Release.xcconfig**:
```c
// General module Release build settings

MTL_ENABLE_DEBUG_INFO = NO
```
**module-Shared.xcconfig**:
```c
// General module Shared build settings

CLANG_ANALYZER_DEADCODE_DEADSTORES = NO
CLANG_WARN_UNREACHABLE_CODE = YES_AGGRESSIVE
COMBINE_HIDPI_IMAGES = YES
DYLIB_COMPATIBILITY_VERSION = 1
DYLIB_CURRENT_VERSION = 1
EXECUTABLE_PREFIX = lib
MACOSX_DEPLOYMENT_TARGET = 10.8
PRODUCT_NAME = $(TARGET_NAME)
STRIP_INSTALLED_PRODUCT = NO
```
**strict.xcconfig**:
```c
// Strict build settings. Eventually every module should use this

GCC_TREAT_WARNINGS_AS_ERRORS = YES
WARNING_CFLAGS = -Weverything $(inherited)
```
**yosemite.xcconfig**:
```c
// Import this for modules which use 10.10 or later APIs

MACOSX_DEPLOYMENT_TARGET = 10.10
```

With a few exceptions, nearly all modules have identical build settings. Most of the differences that did exist had no effect and appeared to be the result of accidental propagation. A small script to generate the actual target `.xcconfigs`:
```lua
modules = {"alert","applescript","application","applicationwatcher","audiodevice",
"audiodevicewatcher","base64","battery","batterywatcher","brightness","caffeinate",
"caffeinatewatcher","chooser","console","crash","dockicon","drawing","drawing_color",
"eventtap","eventtapevent","fs","fsvolume","hash","hints","host","hotkey","http",
"httpserver","image","ipc","javascript","json","keycodes","location","menubar","milight",
"mouse","networkconfiguration","networkhost","networkreachability","notify",
"pasteboard","pathwatcher","screen","screenwatcher","settings","sound",
"spaceswatcher","speech","speechlistener","styledtext","task","timer","uielement",
"urlevent","usb","usbwatcher","webview","webviewusercontent","wifi","wifiwatcher","window"}

hs.fnutils.each(modules, function(module)
    hs.fnutils.each({"Debug", "Release", "Shared"}, function(kind)

        contents = "// Build settings specific to "..module.." / "..kind.." go here\n\n"..'#include "module-'..kind..'.xcconfig"\n\n'
        nonshared = '#include "'..module..'-Shared.xcconfig"\n\n'

        local message = contents
        message = (kind ~= "Shared") and message..nonshared or message

        local f=io.open("/Users/michael/hsconf/"..module.."-"..kind..".xcconfig","w"):write(message):close()
      end)
  end)
```
Which generates `xcconfigs` like so:
**mouse-Shared.xcconfig**:
```c
// Build settings specific to mouse / Shared go here

#include "module-Shared.xcconfig"
```
**mouse-Debug.xcconfig**:
```c
// Build settings specific to mouse / Debug go here

#include "module-Debug.xcconfig"

#include "mouse-Shared.xcconfig"
```
**mouse-Release.xcconfig**:
```c
// Build settings specific to mouse / Release go here

#include "module-Release.xcconfig"

#include "mouse-Shared.xcconfig"
```
Special cases are very simple. `hs.chooser`, which requires OSX >=10.10 is exactly the same, except `yosemite.xcconfig` has been included in its shared `.xcconfig`. You can see the hs.chooser's build settings in the image at the top and how 10.10 is chosen as the deployment target:
**chooser-Shared.xcconfig**:
```c
// Build settings specific to chooser / Shared go here

#include "module-Shared.xcconfig"

#include "yosemite.xcconfig"
```
With this, the project file was able to shed over 8000 lines! It should certainly make merging easier and is much clearer.

**Comment by heptal** [comment]
My notes and findings on the build settings since the xcconfigs will need to be regenerated (putting this here to keep track).

* Pretty much all modules use exactly the same build settings with the template `.xcconfig`s defined above with a few exceptions
* The following use 'yosemite' (`MACOSX_DEPLOYMENT_TARGET = 10.10`):
 * chooser
 * javascript/osascript
* The following, plus any additional tested modules, use 'strict' (`GCC_TREAT_WARNINGS_AS_ERRORS = YES`, `WARNING_CFLAGS = -Weverything $(inherited)`)
* javascript
 * screen
 * timer
 * audiodevice
 * base64
 * socket
* The following need user header includes (define an `podheaders.xcconfig` probably as `USER_HEADER_SEARCH_PATHS = $(SRCROOT)/Pods/Headers/Public/**`)
 * image
 * httpserver
 * socket

This covers all targets except `hs`, `Hammerspoon`, `Hammerspoon Tests`, and `Hammerspoon UI Tests`, which should just use the generated `.xcconfig`s.

Helpful tools to strip the excessively verbose generated `.xcconfig`s:
`find . -name '*xcconfig' -print0|xargs -0 -I f sed -i.backup '/\/\//d;/^$/d;/#include/d' f`

To generate default `.xcconfig`s
```lua
hs.fnutils.each(modules, function(module)
    hs.fnutils.each({"Debug", "Release", "Shared"}, function(kind)

        contents = "// Build settings specific to "..module.." / "..kind.." go here\n\n"..'#include "module-'..kind..'.xcconfig"\n\n'
        nonshared = '#include "'..module..'-Shared.xcconfig"\n\n'

        local message = contents
        message = (kind ~= "Shared") and message..nonshared or message

        local f=io.open("/path/to/xcconfig/dir/"..module.."-"..kind..".xcconfig","w"):write(message):close()
      end)
  end)
```

Removing superfluous Framework link phases (can just re-add LuaSkin if necessary):
`perl -i.backup -00ne 'print unless /Begin PBXFrameworksBuildPhase section/' Hammerspoon.xcodeproj/project.pbxproj` (-00 is 'paragraph mode' which matches subsequent indented text until unindent)

**Comment by cmsj** [comment]
@heptal do you still have interest in working on the xcconfig stuff? We're just past a fairly big release, so now would be a potentially good time for us to work on hairy changes :)

**Comment by cmsj** [comment]
I'm going to close this out because it doesn't seem to have any traction - please feel free to re-open if you want to work on it :)
