### ISSUE TITLE
Support .icns files in hs.menubar:setIcon

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#815]
There are a bunch of useful icons in [.icns format](https://en.wikipedia.org/wiki/Apple_Icon_Image_format) in  `/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/`and they respect dark mode:
![](http://i.imgur.com/edaUk7T.png)

Unfortunately they look very strange (too large) when used at menubar icons:
![](http://i.imgur.com/XRH5j8R.png)
They look nice when scaled with `hs.drawing`: ![](http://i.imgur.com/QPvMK87.png)

They should probably be supported out of the box like
`myMenubar:setIcon("/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarRemovableDisk.icns")`

**Comment by asmagill** [comment]
There is a `hs.image:size()` and `hs.image:setSize({h=...,w=...})` that might not be in the release yet (I can't recall if they were added right before or right after the last release), but they are in the github repository and should be in the next release...

I suspect that `myMenubar:setIcon(hs.image.imageFromPath(...):setSize({h=...,w=...}))` would work just as well as the scaling in hs.drawing does.

IIRC, the NSMenu object classes don't make assumptions about the menubar size... in OS X, this might not seem to make sense, but remember a lot of the underpinnings were inherited from the NeXT OS.

**Comment by heptal** [comment]
I knew I had seen a `hs.image:setSize({h=...,w=...})` somewhere... then went to the official docs page to look and didn't see it (haven't run release version in months...was just too tired at the time to realize I was looking in the wrong place, heh). `hs.menubar:setIcon()` does indeed work fine with `hs.image:setSize()`.

https://gist.github.com/heptal/5c84f96d1913faf3b8aa

From `hs.menubar` docs:
>Icons should be small, transparent images that roughly match the size of normal menubar icons, otherwise they will look very strange

Perhaps we can add the `hs.image:setSize()` suggestion here, and possibly call `hs.image:setSize()` for menubar icons with a [default 22px height](http://iconhandbook.co.uk/reference/chart/osx/).

**Comment by asmagill** [comment]
I'm leery of forcing a size in the method, as we can't account for all situations or image bounds.  Plus, I have code which "detaches" a menubar so it can be used as a pop-up menu and that code uses the image when drawing an icon where I place it in a separate "Tools bar" of my own at a slightly different size than the menubar uses.

Perhaps an optional second argument to `hs.menubar:setIcon`?  If `true` (and this can be the default when not present), it will internally resize, but if `false`, it accepts the image as is?

If this meets with approval, I can add this later this week.

**Comment by cmsj** [comment]
I think I prefer adding a `:setSize()` suggestion to the hs.menubar docs :)
