### ISSUE TITLE
Further additions to LuaSkin

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#818]
Additional requests/proposals for LuaSkin:
- In `checkArgs:`, allow `LS_TUSERDATA` (or a new tag) to be optional, without a specified type, or with multiple types... should I look into this or are we planning to replace `varargs` with something perhaps a little more flexible?
- adding support in `toNSObjectAtIndex:` so that tables with a special key-value pair can be matched to a conversion function to allow more seamless conversion into NSObjects.  What should the key name be to minimize the likelihood of the key being used by something else?  `__type` seems too generic...  `__luaSkinType`?

**Comment by cmsj** [comment]
I don't have any immediate plans to replace the varargs. It was not a good choice overall, but I don't believe it's hurting us significantly at the moment, other than in fleshing out `checkArgs`.

Agreed `__type` is too generic. I'm happy with `__luaSkinType` :)

**Comment by cmsj** [comment]
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)
