### ISSUE TITLE
hs.menubar question

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#821]
Since this involves using unpublished selectors in NSStatusBar and NSStatusItem, I figured it more appropriate to ask here rather than the Google group...

Is there interest in being able to insert `hs.menubar` items with different priorities to give some control over positioning?

I'm using a modified version of code found at https://github.com/shergin/NSStatusBar-MISSINGOrder, and it seems to work well under 10.11 -- I've been able to place and move menubar items before and after the Notification Center icon, the Spotlight Icon, the set of System icons and the set of "other" (i.e. application) icons in the system status bar... but it does make use of NSInvocation to invoke unpublished selectors in the classes.

**Comment by cmsj** [comment]
from looking at the repo you linked to, this seems reasonably safe to do. Perhaps we could play doubly safe by only invoking their codepaths at all, if the user specifies order arguments?

**Comment by asmagill** [comment]
I'll take a look at my modified module... I think I set it up as a separate method... certainly none of the existing methods/constructors need to be touched.

I'm also going to address #831 when I get to this sometime in the next few days. (hence the note to myself here :-P )

**Comment by asmagill** [comment]
addressed with #838
