### ISSUE TITLE
Add hs.wifi.associate()

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#829]
@asmagill I'm curious if there was a specific reason for not adding an `associate()` to `hs.wifi`. It seems like it ought to be reasonably simple to add.

**Comment by asmagill** [comment]
No specific reason... covering all possibilities (IBSS, enterprise and personal WPA) seemed a big enough addition I figured on waiting until there was interest since making it non-blocking was all I really cared about at the time of the last updates to the module.

**Comment by cmsj** [comment]
cool thanks. There seems to be some interest in having it now, so I'll start simple and we can think about more complex options later :)
