### ISSUE TITLE
MenuIcon:setColor?

### ISSUE THREAD

**Issue by kevinastone** [Hammerspoon/hammerspoon#831]
Could we set the color of the menubar icon?  Is that feasible?

(as a bonus ask, can we set/manipulate the hammerspoon menubar icon?)

Seems like a great way to flag or notify the user.

**Comment by asmagill** [comment]
It actually should be pretty easy to modify the title method to support hs.styledtext like the menu items do now... not really certain why I missed it when last updating the module.  It may take a few days, but I'll add it to my list.

As for the Hammerspoon menubar icon, currently no, it can't be modified.  What I've done is hide the menu icon from the application preferences panel and created my own "Hammerspoon" menu using the same icon... if you did something similar, you could easily change the icon based upon timers, etc.

**Comment by asmagill** [comment]
addressed with #838
