### ISSUE TITLE
addition to hs.application:getMenuItems

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#832]
Any objections to adding the key kAXMenuItemCmdGlyphAttribute to the attributes returned when getting an applications menus?  I need to find a more formal source to add a proper lookup for the numeric result it returns then http://superuser.com/questions/415213/mac-app-to-compile-and-reference-keyboard-shortcuts, but it would allow programs like @dharmapoudel's at https://github.com/dharmapoudel/hammerspoon-config to include menu items that have a visible glyph rather than a command character (think arrow keys, delete, etc.)?

The update would be to the _getMenuStructure function in hs.application's internal.m file at around line 802... I don't believe it should affect anything else since it's just an addition to the query dictionary.

**Comment by dharmapoudel** [comment]
That would be an awesome addition. The cheatsheet copycat is pretty limited to AXMenuItemCmdChar . Also is there any way (or workarounds) to detect long press of any keys?

**Comment by asmagill** [comment]
closed with #838

**Comment by asmagill** [comment]
@dharmapoudel, to detect long keypresses, you need to delve into `hs.eventtap` and `hs.timer`.  I recently updated a modified version of your cheatsheet code at https://github.com/asmagill/hammerspoon-config/blob/master/utils/_keys/cheatsheet.lua which watches for a 3 second press of just the command key that seems to work well... I just added the command key detection, so consider it still in "beta testing", but you're welcome to take a look at and use any portion of it that appeals to you.

(My version does require the glyphs which were recently added to the development version of Hammerspoon, but the eventtap stuff should work right now with a stock Hammerspoon release if that's what you're running.)

**Comment by dharmapoudel** [comment]
Awesome. Thanks!
