### ISSUE TITLE
Is there a way with hammerspoon to split two apps in a new desktop with a hotkey?

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#833]
For example I press a hotkey, and Sublime Text and Chrome gets maximised and split on a new desktop. 

Something like this would really be incredible and I am wondering if it can be achieved with hammer spoon.

Thank you for any help.

**Comment by javjar** [comment]
Yes you can!
You can use [AppleScript](http://www.hammerspoon.org/go/#applescript) to launch the application and [some window management/layout](http://www.hammerspoon.org/go/#winlayout) to split the windows :)

**Comment by cmsj** [comment]
The tricky part is "on a new desktop" - we don't have any way to properly interact with OS X's "Spaces" - there is no system API for that :(
