### ISSUE TITLE
Confirmation dialog with restart hotkey question.

### ISSUE THREAD

**Issue by petobens** [Hammerspoon/hammerspoon#834]
I want to create a key bind to restart my Mac. I know I can use

```
hs.hotkey.bind({"ctrl", "cmd"}, "r", function()
                hs.caffeinate.restartSystem() end)
```

However once I press the key combination I would a like a message/dialog box to open asking "Do you really want to restart you Mac?" and only if I select "Yes" then proceed to reboot; otherwise exit.  Is this currently possible? (I might be able to use hs.chooser?) Thanks in advance!

**Comment by szymonkaliski** [comment]
You could do that with hs.applescript: https://developer.apple.com/library/mac/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW12

I don't have anything exactly like that, but you could look at this as an example: https://github.com/szymonkaliski/Dotfiles/blob/9618f719c2d5662333e4e002a988462e03711462/Dotfiles/hammerspoon/ext/application.lua#L124-L158 this one displays dialog with question to close the app if it has more than one window (I use so I won't close some Safari window I have on other space that I forgot about).

**Comment by petobens** [comment]
@szymonkaliski  thank you! However I'm having a hard time trying to adapt it to my needs. Can you please help me a bit more? Thanks once again.

**Comment by szymonkaliski** [comment]
Sorry I don't have time right now to write it for you, but what part do you struggle with in specific?

**Comment by cmsj** [comment]
@petobens you could definitely use `hs.chooser` for this :)

**Comment by petobens** [comment]
@cmsj  thanks. However since `hs.chooser` is (as I understand) a relatively new feature I don't follow how to apply it to my use case. Any pointers to get me started?  (besides [hs.chooser docs](http://www.hammerspoon.org/docs/hs.chooser.html))

**Comment by petobens** [comment]
@szymonkaliski I rather use `hs.chooser` if possible (I don't know applescript at all).

**Comment by dharmapoudel** [comment]
@petobens You can go through my hammerspoon config file (battigayo.lua) to get idea of how you can use choosers  in your case.

**Comment by petobens** [comment]
@dharmapoudel  @cmsj  thanks. I have the following code:

```lua
function AskforReboot()
	test = hs.chooser.new(RebootIfChoice)
    test:rows(2)
    test:choices({{["text"] = "Restart computer", ["subText"] = ""},
                {["text"] = "Abort restart", ["subText"] = ""}})
    test:show()
end
function RebootIfChoice()
	-- local  = input.uuid
    hs.alert("Reboot if choice is Restart computer otherwise exit")
end
hs.hotkey.bind({"shift", "cmd"}, "r", function() AskforReboot() end)
```

How do I display the `hs.alert` only when choice nr 1 is chosen? i.e is it possible to write a conditional similar to:

```
if choice_nr == 1 then 
    foo
else 
   bar
end
```
Thanks in advance for any further help.

**Comment by dharmapoudel** [comment]
You are very close @petobens 

```
function AskforReboot()
    test = hs.chooser.new(RebootIfChoice)
    	:rows(2)
    	:choices({{["text"] = "Restart computer", ["subText"] = "", ["id"] = "1"},
                {["text"] = "Abort restart", ["subText"] = "", ["id"] = "2"}})
    	:show()
end

function RebootIfChoice(input)
	if(input.id == "1") then
		hs.alert("Your computer will be rebooted in "..input.id.." seconds!", 2)
	else
		-- let this else not confuse you, my friend
	end
end

hs.hotkey.bind({"shift", "cmd"}, "r", AskforReboot )
```

**Comment by petobens** [comment]
@dharmapoudel  thank you! Is it possible to add a title to the chooser object? Basically I would like to show a question stating: `Do you wish to restart your computer?` and then use something similar to the next code:

```lua
function YesNoDialogBox(ActionFunc)
	test = hs.chooser.new(ActionFunc)
    test:rows(2)
    test:choices({{["text"] = "Yes", ["subText"] = "", ["id"] = "yes"},
                {["text"] = "No", ["subText"] = "", ["id"] = "no"}})
    test:show()
end
function RebootIfChoice(input)
    if input.id == "yes" then
        hs.alert("Your choice was: yes")
    else
        hs.alert("Your choice was: no")
    end
end
hs.hotkey.bind({"shift", "cmd"}, "r", function() YesNoDialogBox(RebootIfChoice) end)
```

Again thanks in advance.

**Comment by dharmapoudel** [comment]
@petobens Currently, I don't think so. But that's upto the developer to add the title. I would even want an option to hide arrows(on the left) and shortcuts (on the right). @cmsj  @asmagill

**Comment by cmsj** [comment]
It's tough, I don't want to explode the hs.chooser API with tons of options, and thus make the code behind it super complex, but we clearly do need more UI options for people.

**Comment by asmagill** [comment]
While discussing possible additions/changes, I'd like it if a missing subText didn't show up as "UNKNOWN SUBTEXT"... if it isn't provided, it should be blank.  Ideally the text space should expand to fill the whole area, rather than the blank line when I get around this by setting subText="", but even the blank line is better than UNKNOWN SUBTEXT

I think most of the options suggested so far could be included in the choices method (kind of like the setMenu method of hs.menubar)... the only one that must be "global" to the whole box is a title, and even that could go into the choices as {title = "blah"} as the first item, if we only want to have to change one method.

I get wanting to avoid method explosion, but I personally favor giving people options -- you never know what they might think of that you didn't.  Coming up with the right interface to it, though, is tough.

**Comment by cmsj** [comment]
@asmagill the `UNKNOWN` stuff is now removed in master, in case you hadn't spotted that :)

**Comment by asmagill** [comment]
I was a few iterations back when I wrote that, and I haven't checked since returning to the current master, so I'll take your word for it :-)  That said, the options suggested here and in other issues ( #748, #782, others? ) are worth considering...

**Comment by cmsj** [comment]
I'm going to close this out - hs.dialog is coming soon and should cover this.
