### ISSUE TITLE
hs.window.focusedWindow() returns nil

### ISSUE THREAD

**Issue by TornikeNatsvlishvili** [Hammerspoon/hammerspoon#837]
I am using Hammerspoon as a window manager. I have shortcuts that put the window in each corner.

Initially everything works. However, sometimes after sleep/waking the computer .focusedWindow() starts returning nil for specific applications.

Finding the window with hs.window.allWindows() and doing .focus() on it works. However, focusedWindow() still returns nil.

I am having this issue for PyCharm.

note: I have seen comments that Hammerspoon doesn't work on X11 apps but I don't think PyCharm is X11.

**Comment by heptal** [comment]
Jetbrains apps seem to do weird things with windows - see here: https://github.com/Hammerspoon/hammerspoon/issues/736#issuecomment-184962738

Someone will need to breakpoint/debug the focusedWindow method when using IntelliJ/PyCharm.

**Comment by cmsj** [comment]
it's not just X11 apps - anything that entirely avoids the OSX accessibility stuff is very hard to interact with. What does `hs.window.frontmostWindow()` do?

**Comment by TornikeNatsvlishvili** [comment]
If you manualy get the window with pid (getApplication) then you can set the frame without issue.

**Comment by woodpeckeroloco** [comment]
I have the same problem. Window's moving hotkeys work with hammerspoon's console only.
And I also can't enable accessibility for hammerspoon app. Dot becomes yellow every time I quit hs.
But green one doesn't make window's functions work. 
sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db 'select * from access where client like "%hammerspoon%"'
gives me " kTCCServiceAccessibility|org.hammerspoon.Hammerspoon|0|0|1|| "
I have 0.9.45  hs version and os 10.11.4

**Comment by lowne** [comment]
Can anyone try if using a "focused" windowfilter works around the problem?
```lua
focusedwf=hs.window.filter.new{default={focused=true}}:keepActive()
[...]
function f(...)
  --local w=hs.window.focusedWindow() --instead:
  local w=focusedwf:getWindows()[1]
  [...]
end

**Comment by woodpeckeroloco** [comment]
It doesn't work for me
`focusedwf=hs.window.filter.new{default={focused=true}}:
function nudgeRight()
 --local win = hs.window.focusedWindow()
 local win = focusedwf:getWindows()[1]
 local f = win:frame()
   saved.win = win
   saved.winframe = saved.win:frame()
   f.x = f.x + 10
   win:setFrame(f)
end
`
now "attempt to index a nil value (local 'win')" is in "local f = win:frame()"

**Comment by kevinastone** [comment]
I see this every time I first launch hammerspoon.  If I don't focus a window after launching, `hs.window.focusedWindow()` returns nil.

**Comment by woodpeckeroloco** [comment]
I reinstalled OS. No problems with accessibility now and windows movement work fine.

**Comment by chdiza** [comment]
> I see this every time I first launch hammerspoon. If I don't focus a window after launching, hs.window.focusedWindow() returns nil.

I wonder if that's related to #651?

**Comment by cmsj** [comment]
@chdiza That was my thought too

**Comment by cmsj** [comment]
I'm trying to clean up our list of issues. This one hasn't had any activity for a year, so I'm going to close it. Please re-open, or file a new issue if you are experiencing this specific issue.

**Comment by amolkhatri** [comment]
@glendvai  Thank you!!! worked for me.

**Comment by KKimj** [comment]
Thanks. It works! 👍
