### ISSUE TITLE
Two questions regarding hs.execute

### ISSUE THREAD

**Issue by petobens** [Hammerspoon/hammerspoon#841]
When I run `mvim -u /Users/Pedro/OneDrive/vimfiles/vimrc_min` from my Terminal it correctly opens MacVim and sources the minimal vimrc file `vimrc_min`. Now when I try it from the Hammerspoon console with:

```lua
hs.execute("mvim -u /Users/Pedro/OneDrive/vimfiles/vimrc_min", true)
```
it does open MacVim and sources the minimal vimrc file but then Hammerspoon gets blocked until I exit MacVim. So my question is: how can I run the above command without blocking Hammerspoon?

Bonus: I would like to toggle hidden files with a hotkey bind. As far as I understand I can use the following shell script:
```sh
STATUS=`defaults read com.apple.finder AppleShowAllFiles`
if [ $STATUS == YES ]; 
then
    defaults write com.apple.finder AppleShowAllFiles NO
else
    defaults write com.apple.finder AppleShowAllFiles YES
fi
killall Finder
```
Is it possible to assign it to a hotkey? Are there better ways to toggle hidden files using Hammerspoon? Thanks!! (awesome project btw :) )

**Comment by cmsj** [comment]
I don't have a helpful suggestion for the hidden files stuff, but see hs.task for executing things async

**Comment by asmagill** [comment]
If you just want to open up MacVim, `hs.task` is probably overkill for this... I think you can get away with appending & to the end of the statement like this:

~~~lua
hs.execute("mvim -u /Users/Pedro/OneDrive/vimfiles/vimrc_min &", true)
~~~

However, if you want to actually know when MacVim quits, through a callback function, then `hs.task` is definitely the way to go.

Regarding the hidden files, I also think you need to restart the Finder for the setting to take effect, so I'd use something like this:

~~~lua
hs.execute("defaults write com.apple.finder AppleShowAllFiles YES ;  killall Finder")
~~~

**Comment by petobens** [comment]
@asmagill  thanks for the pointers. Mmmm your first suggestion doesn't seem to work (Hammerspoon is blocked until I quit the MacVim app). 
Regarding your second suggestion, how can I toggle (with a single keybind), hidden files on and off?
Thanks for your kind help!

**Comment by petobens** [comment]
@asmagill  what I mean regarding the toggling of the hidden files is that I tried doing:

```lua
hs.hotkey.bind(cmd_ctrl, "h", function()
    hidden_status = hs.execute("defaults read com.apple.finder AppleShowAllFiles")
    if hidden_status == "YES"  then
        hs.execute("defaults write com.apple.finder AppleShowAllFiles NO; killall Finder")
    else
        hs.execute("defaults write com.apple.finder AppleShowAllFiles YES; killall Finder")
    end
end)
```

However the `hidden_status` variable doesn't get updated (I know very little lua). How can I fix it? Thanks for the patience.

**Comment by asmagill** [comment]
Ah yes, I forgot that when I've used & before, it was always with `os.execute` rather than `hs.execute`... the builtin lua `os.execute` doesn't allow us to capture the output of the executable, hence `hs.execute` was written, but since it uses `io.popen` to capture the output, backgrounding the tasks doesn't change the fact that it's waiting for the output and will continue until the pipe is closed when the application terminates.

Try `os.execute("mvim -u /Users/Pedro/OneDrive/vimfiles/vimrc_min &")`

As to the other, your code *looks* like it should work... unfortunately I am not at my computer right now, so I can't test it at the moment... I'll take a closer look and actually try it out this afternoon when I get a chance.

**Comment by petobens** [comment]
@asmagill  thank you! Using `os.execute` works :+1:

**Comment by petobens** [comment]
@asmagill  found the problem with the conditional. I had to use `if hidden_status == "YES\n"  then`. Thank you!!
