### ISSUE TITLE
Add hs.screen:localToAbsolute() for translating co-ordinates

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#849]
Humans like to look at a screen, know its resolution, and reason about where things are relative to its resolution.

OS X likes to think of everything as being in an absolute co-ordinate space where 0,0 is the top left of the primary screen.

I think we should add hs.screen:localToAbsolute() that will take a rect or a point that describes something on that screen, in terms of its resolution, and converts it to the system's absolute co-ordinate space.

Lots of people end up having to do this for themselves, so we should give them a helper.

**Comment by lowne** [comment]
in #850

**Comment by cmsj** [comment]
Closed by #850
