### ISSUE TITLE
hs.httpserver request

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#851]
How hard would it be to pass the html request headers to the callback function in addition to the method and path? Specifically, I'm thinking of the requesters IP address, so it can be checked against an access list, but the other headers could be useful as well.  I'm thinking maybe a table of key-value pairs as the third argument so existing callback functions still work as expected, they just ignore the third argument.

I don't know anything about CocoaHTTPServer, but can find some time to dig later this week; I just figured it might be a simple addition to someone already familiar with the Pod.

**Comment by cmsj** [comment]
I think this can close, the related PR was merged alread.
