### ISSUE TITLE
extra functions

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#86]
not an issue per-se, but some minor functions I've used in debugging or that might be useful... some might be more at home in the hs core, others maybe another module or whatever.  Posting here for primarily for your review and thoughts, especially with the the functions having to do with accessibility, autolaunch, etc.  Could possibly be included in a larger module also allowing control of dockicon?

At any rate, definitely not pull ready in their current state.
https://github.com/asmagill/hammerspoon/tree/extras/extensions/extras

**Comment by cmsj** [comment]
Doing a bit of Issue gardening - that current URL is also 404 now ;)

I'm generally in favour of adding helpful utility functions, so please feel free to submit PRs with them :)
