### ISSUE TITLE
Feature request: transparency in hs.webview

### ISSUE THREAD

**Issue by heptal** [Hammerspoon/hammerspoon#873]
Really this is a question/request for @asmagill: why won't setting `opaque` to false work?
```objc
@implementation HSWebViewWindow
...
        // Configure the window
        self.releasedWhenClosed = NO;
        self.backgroundColor    = [NSColor clearColor]; //no effect
        self.opaque             = NO; //no effect
        self.hasShadow          = NO;
...
```
or similarly
```objc
static int webview_opaque(lua_State *L) {
    HSWebViewWindow *theWindow = get_objectFromUserdata(__bridge HSWebViewWindow, L, 1) ;
    if (lua_type(L, 2) == LUA_TNONE) {
        lua_pushboolean(L, theWindow.opaque) ;
    } else {
        theWindow.opaque = (BOOL) lua_toboolean(L, 2) ;
        lua_settop(L, 1) ;
    }
    return 1 ;
}
```
Would be helpful for making widgets, imo.

**Comment by cmsj** [comment]
You can already do this, `someWebView:asHSDrawing():setAlpha(0.5)`

**Comment by heptal** [comment]
That sets the alpha of the whole window rather than the background, though. I'd like the contents to remain unaffected.

**Comment by cmsj** [comment]
Oh, I see what you mean :)

**Comment by heptal** [comment]
In addition to setting the containing window's `opaque` property to `false`, the webview must have this key set: `[wkWebView setValue:YES forKey:@"drawsTransparentBackground"]` (per http://stackoverflow.com/a/30280927).
