### ISSUE TITLE
Potential (small) leak in hs.image

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#879]
In imageFromMediaFile, we have:

```
    CFStringRef UTI = UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, extension, movieUTI);
```

which, following the rules of CoreFoundation, returns an object that needs to be released, but I don't see a CFRelease anywhere (admittedly I only skimmed the function).

**Comment by heptal** [comment]
Thanks, missed that.
