### ISSUE TITLE
hs.eventtap for keyDown not working

### ISSUE THREAD

**Issue by szymonkaliski** [Hammerspoon/hammerspoon#882]
Hi! Has something changed to how we handle keyDown eventtap? It was warking with 0.9.45, and now even simple:

```lua
hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('tap!', hs.inspect(event))
  return false
end)
```

isn't printing anything. Can someone confirm if this is global, or something with my machine? I tried running init.lua with _only_ this code above, and I'm not getting any taps at all.

**Comment by cmsj** [comment]
Two things occur to me when looking at that snippet:

1) you should capture the result of `.new()` in a global variable, so it doesn't get garbage collected
2) eventtaps don't do anything until you call `:start()` on them

**Comment by szymonkaliski** [comment]
Yes, I know, I was copy and pasting quickly that's why there are simple mistakes; the point is I have eventtap-based things in my config which used to work before the recent upgrade.

Running init.lua which looks like below isn't working either: :)

```lua
local eventtap = hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('tap!', hs.inspect(event))
  return false
end)
eventtap:start()
```

**Comment by cmsj** [comment]
Has Hammerspoon lost its Accessibility permissions? That has been known to happen in upgrades. Even if it is listed in the system prefs, try removing it and re-adding it. 

Your snippet (minus the `local`) works for me in the Console:

```
> eventtap = hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('tap!', hs.inspect(event))
  return false
end)
eventtap:start()

tap!	<userdata 1> -- hs.eventtap.event: Event type: 10 (0x618000249e38)
```

(Also, going back to my point 1, capturing into a `local` is not a good idea, they go out of scope when init.lua has been executed, so are marked for garbage collection. Switch it to a global :) )

**Comment by szymonkaliski** [comment]
Ok, even with global - nothing, not working in the Console as well, and I removed and re-added to Accessibility permissions. Strange :) Any ideas for where to start debugging?

**Comment by asmagill** [comment]
I can also confirm that it works from the console... the only thing I can think of off the top of my head would be if you have other eventtaps in effect that capture keyDown?  If they return "true", the event is considered "dealt with" and not passed on to subsequent taps.

**Comment by szymonkaliski** [comment]
No, I'm running only these 5 lines of code in my init.lua, nothing else. So strange...

**Comment by szymonkaliski** [comment]
Hm, rebooting OSX fixed it.

**Comment by cmsj** [comment]
How annoying. I hate problems that go away when you reboot! :(

**Comment by szymonkaliski** [comment]
Yeah, me too, it's really bad way of fixing things :/ Anyways, thanks for help! I'll be back if it happens again!

**Comment by dannydulai** [comment]
i had this problem for ages too.. this was the code i was using:

```
control_tap = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, control_handler)
control_tap:start()
other_tap = hs.eventtap.new({hs.eventtap.event.types.keyDown}, other_handler)
other_tap:start()
```

i fixed it by changing the order of the 2:

```
other_tap = hs.eventtap.new({hs.eventtap.event.types.keyDown}, other_handler)
other_tap:start()
control_tap = hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, control_handler)
control_tap:start()
```

now, the keyDown tap works fine.
