### ISSUE TITLE
Using setFlags() with newSystemKeyEvent

### ISSUE THREAD

**Issue by petobens** [Hammerspoon/hammerspoon#885]
One quick question regarding this recent [commit](https://github.com/Hammerspoon/hammerspoon/commit/a8ad4974777edc5b5db19176faf9dd2fe7b65c6f).
How can I bind `shift+cmd` to `ctrl+EJECT`? I'm doing something definitely wrong with `:setFlags()` but I don't quite get how do it properly after reading the [docs](http://www.hammerspoon.org/docs/hs.eventtap.event.html#setFlags):

``` lua
hs.hotkey.bind({"shift", "cmd"}, "s", function()
                hs.eventtap.event.newSystemKeyEvent('EJECT', true):setFlags({"ctrl", true}):post()
                end)
```

Thanks!!!

**Comment by petobens** [comment]
One extra question, if I repeat (from the console) the following command:

```lua
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', true):post()
```
it seems that only the first time the volume is increased.  Is this a feature? Again thanks!

**Comment by cmsj** [comment]
@petobens it's worth remembering that for a event to be valid, you need to send a key-up as well as the key-down, so what I would recommend is you do osmething like:

```lua
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', true):post()
hs.timer.usleep(200000)
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', false):post()
```

if you run that over and over, you should find that it keeps working :)

**Comment by petobens** [comment]
@cmsj Great tip! Thanks!
Any ideas regarding my original question about `Ctrl-EJECT`?

**Comment by cmsj** [comment]
@petobens do you just want shift+cmd, or shift+cmd+s? The former would need an `hs.eventtap` because two modifiers on their own aren't going to trigger a hotkey.

As for the general principle - I would strongly recommend that when you want to emit a keyboard/mouse event from a hotkey, you use the `releasedfn` callback, not the `pressedfn` callback. That plus the down/usleep/up recommendation a couple of comments ago, and you should be sorted :)

**Comment by petobens** [comment]
@cmsj, unfortunately I cannot get this to work :(. I want to be able to press `shift+cmd+s` and have that converted into system keys `Ctrl+EJECT` (basically I want to be able to open the dialog that asks if I want to shutdown the computer (which, at least on my Mac, is triggered by pressing `Ctrl-EJECT`).  I believe my problem is with the `setFlags()` but have no idea how to fix it. Again thanks for the help and patience. :)

**Comment by Recognition101** [comment]
I also have this issue. If I do this:

```
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', true):setFlags({"alt", "shift"}):post()
hs.timer.usleep(200000)
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', false):setFlags({"alt", "shift"}):post()
```

I expect the volume to go up by a third of a notch (as if you pressed alt+shift+volume up, try it). Instead, the volume goes up by a full notch.

**Comment by asmagill** [comment]
I don't know about the eject key yet, but I just ran some tests with the sound keys and I think that there are some additional flags being set that the current module can't set.  I am working on some additions to hs.eventtap.event that may allow getting around this and will post more in a day or so.

**Comment by cmsj** [comment]
I think Eject is likely to be impossible to solve well - it's a weird/special key.
I'm going to close this, but please anyone re-open it if you disagree.

**Comment by waynehoover** [comment]
> I don't know about the eject key yet, but I just ran some tests with the sound keys and I think that there are some additional flags being set that the current module can't set. I am working on some additions to hs.eventtap.event that may allow getting around this and will post more in a day or so.

Has there been any updates on the sound issue? I to am trying to do

`hs.eventtap.event.newSystemKeyEvent('SOUND_UP', true):setFlags({"alt", "shift"}):post()`
But it doesn't work to increment in small steps.

**Comment by jcs** [comment]
@waynehoover The table has to have each key set to `true`:

```
hs.eventtap.event.newSystemKeyEvent('SOUND_UP', true):setFlags({["alt"]=true, ["shift"]=true}):post()
```
