### ISSUE TITLE
setIdImage method in hs.notify does not properly overwrite the default hammerspoon image

### ISSUE THREAD

**Issue by rcoedo** [Hammerspoon/hammerspoon#886]
I'm trying to create a new notification with the current artist/track from spotify, and with the spotify icon. This is my code:
```
notify.new("")
    :subTitle(spotify.getCurrentArtist())
    :title(spotify.getCurrentTrack())
    :setIdImage("resources/spotify.png")
    :send()
``` 

This is the result:
![notification](http://i.imgur.com/SpUkjYg.png)

Is this intended or a known limitation?

Thanks and keep rocking 😄

**Comment by heptal** [comment]
This is intended in that there is no known way to remove or change the miniaturized icon in the Notifications API. You'll see that other apps which use dynamically set icons such as iTunes also have the miniaturized app icon.

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
