### ISSUE TITLE
Question about hs.task

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#891]
@cmsj, in looking at `hs.task`, I noticed that the `selfRef` is assigned when a task is created (`new`), but never unreferenced *except* in the `__gc` function... this means that an `hs.task` object will *never* get collected, since it's entry in the registry prevents it being collected (except during a reload, of course).

Looking at the registry with `debug.getregistry()` confirms this... If you have `hs.tasks` which are repeated (like the "geeklets" that spawned `hs.styledtext`, etc.), you can find it's luaRef table with something like:

~~~lua
f = debug.getregistry()
a = {} ; for i,v in pairs(f) do if type(v) == "table" and #v > 0 then print(i, #v) ; table.insert(a, i) end end
~~~

then look for one with a semi large number (in my case, this time it was 1061), so...

~~~lua
> #f[1061]
182

-- the time it's taken me to write this passes --

> #f[1061]
350
~~~

Is there a reason you're keeping the selfRef?  If so, can we make sure it gets removed as soon as the task terminates (cleanly or otherwise)?  Or will this cause other problems?

**Comment by cmsj** [comment]
I'm out on my phone, so I can't be sure, but that sounds like a bug on my part

**Comment by chdiza** [comment]
I hope that the cause of the "fake GeekTool" memory leak has been found :)

A couple of weeks ago I left my office Mac running and awake all weekend, with HS running and my "geeklets" all running, but otherwise I didn't touch the machine at all (e.g., no ssh-ing in from afar, etc.).  When first fired up on Friday afternoon, HS consumed about 24MB of RAM.  On the ensuing Monday, HS was consuming 2.4 Gigabytes of RAM.

**Comment by asmagill** [comment]
Inserting the following at line 158 of hs.task's internal.m file seems to be working for me:

~~~
userData->selfRef = [skin luaUnref:refTable ref:userData->selfRef];
~~~

I haven't made a pull or edited master yet because I don't use the features which use `streamCallback` or `inputCallback` myself so I don't know how to test whether or not they are affected... I don't think they should be, since this line is in the `terminationHandler`, but I leave the final determination of whether this is sufficient/correct to Chris.

**Comment by chdiza** [comment]
@asmagill I inserted that line, and it also *seems* to have made a big difference.

I repeated my "leave HS running on the office mac on all weekend" test, and it was only using around 56MB of RAM.  I then did hs.reload(), and the RAM usage went down to 51MB.  I *think* that means that there were only about 5MB worth of lua objects, and the rest of that RAM is eaten by the HS app itself.

**Comment by chdiza** [comment]
Another thing that seems to have disappeared since I built with @asmagill's modification is this:  Previously, if HS (and my fake GeekTool) was running long enough to consume more than maybe 100MB or so of RAM, executing `hs.reload()` would take a really long time (sometimes like three minutes).  After calling the reload, Activity Monitor would show HS as "Not Responding" in red, until eventually the reload finished.

**Comment by chdiza** [comment]
Still working great over here.  The suspected leak in `hs.task` was the last barrier to keeping the real GeekTool around just in case.  Now I have thrown away GeekTool.app

I note that even with @asmagill's tweak, HS still gradually winds up with about 4 or 5 times more RAM than it starts with.  The difference is that none of that growth seems to be attributable to user-created lua objects.  (An `hs.reload()` only shaves a few MB).

**Comment by asmagill** [comment]
I've included the cleanup of tasks in a pull I hope to land later today/tomorrow, so it's good to hear it's made such a positive impact for you.

Re other memory usage, If you're using a lot of images, I have read some things that mention NSImage as a class that makes regular use of the application cache, especially when dealing with named images, and thus far, my understanding is that this is never cleared until the application is under memory pressure and forced by the OS or the application is terminated... I've only recently started looking into that aspect of OS X programming, so this is probably a superficial understanding...  And unless we're doing something wrong (entirely possible), caching the images is probably even a good thing if it means growth only once, rather than slowly increasing... depends upon usage case.

At any rate, I do hope to be able to start looking at memory usage by Hammerspoon in other ways and see what we may be able to reduce without significant re-write.  I can only hope that they turn out to be as simple to work with/around as this one was!

**Comment by chdiza** [comment]
I can do some checking to see if it really is the images that are contributing, but the images I use are pretty small (less than 70KB each) and there are only five of them.

By the way, my second paragraph wasn't a complaint.  The non-userland-lua portion of RAM usage does grow, but it doesn't seem to be out of control, and doesn't seem to get past 55-ish MB over here.  While it would be icing on the cake to hold that down lower (it starts out between 5 and 10), I am satisfied as is.

**Comment by asmagill** [comment]
No worries, I didn't take it as a complaint... but I do also observe some growth myself.

The Mjolnir fork started in part because some of the developers wanted to see just how minimal they could make the memory foot print; Hammerspoon instead focused on the ease of extending things and providing more than a minimalistic set of tools.  I personally fall somewhere in between seeing value in both.  If we can identify some places where we could be more aggressive in controlling memory usage, I'd like to, but not at the expense of ease of use.

I was pleasantly surprised at how much of a difference the tweak to `hs.task` made... while I doubt we'll find anything else that makes quite as big of a difference, who knows?  Can't hurt to look, and given that I come from a more command-line/Makefile background, it gives me a reason to become more familiar with Xcode specifically and it's associated tools.

**Comment by cmsj** [comment]
@asmagill can we close this out?

**Comment by asmagill** [comment]
Yes.  I do still believe that we should at some point take on a more aggressive search for possible memory leaks, but proper 10.12 support takes precedence and the primary purpose of this issue has been addressed, so I'm closing it.
