### ISSUE TITLE
hs.distributednotifications constructor error

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#893]
Been seeing this every time I create a new watcher at reload:

~~~
5/4/16 12:11:44.554 PM Hammerspoon[51943]: (missing delegate):log level 6: unrecognized userdata type hs.distributednotifications
~~~

@cmsj, I think it's because you check for the existence of the `name` and `object` fields *after* creating the new userdata object, so position 3, in my case, is no longer `none`, it's the new userdata object.

**Comment by cmsj** [comment]
oh, good point, thanks!

**Comment by cmsj** [comment]
I think this can be closed.
