### ISSUE TITLE
hs.hotkey.modal feeding the keys on the focused window

### ISSUE THREAD

**Issue by dsdeiz** [Hammerspoon/hammerspoon#894]
Anyone happen to know what I am missing? 

```lua
k = hs.hotkey.modal.new('ctrl', 'd')
k:bind('', 'i', function() hs.application.launchOrFocus('iTerm') end)
```

Hammerspoon is listening to it but at the same time <kbd>ctrl</kbd> + <kbd>d</kbd> is ran on the focused application e.g. if it's iTerm, it executes `^D`. It would be nice if it was the same as how [Slate](https://github.com/jigish/slate) does it.

**Comment by asmagill** [comment]
See https://groups.google.com/forum/#!topic/hammerspoon/HgDHNAWupFU

Can this be closed, or is there still an issue outstanding?

**Comment by dsdeiz** [comment]
My bad. I forgot to close.
