### ISSUE TITLE
hs.alert doesn't appear?

### ISSUE THREAD

**Issue by KyleKing** [Hammerspoon/hammerspoon#903]
Sometimes the hs.alert isn't visible, but I'm having trouble replicating this issue.

I use the hs.alert to send notifications from my battery watcher. However, sometimes the hs.alerts just stop/are somewhere off screen. The only way to see the alerts again it is to quit and restart Hammerspoon. I've just started testing where I fire both a native Mac notification and the hs.alert to see when the alert doesn't show.

```lua
function BattAlert(message)
  hs.notify.new({title="Battery Watcher", informativeText=message}):send()
  hs.alert.show(message)
end
```

I thought the issue might be related to switching between desktops or when using a full-screen application and switching, but the source, [internal.m](https://github.com/Hammerspoon/hammerspoon/blob/617b5a7e3489de5e6df2d359ee3972249b904d11/extensions/alert/internal.m), looks like it should recover on the next notification.

Has anyone else seen this issue?

**Comment by junkblocker** [comment]
On config reload or startup, the alerts are consistently all white, I suspect due to HS being busy. At that time they look invisible if  there's a white window under them. Other than that, no.

**Comment by KyleKing** [comment]
@junkblocker I see the same UI glitch, but that's doesn't seem to be related to what I'm seeing with this issue

**Comment by KyleKing** [comment]
Closing because can't be replicated at this time
