### ISSUE TITLE
hs.grid.set - weird behaviour with apps such as Chrome, Safari, Slack after the latest OSX update

### ISSUE THREAD

**Issue by jfchevrette** [Hammerspoon/hammerspoon#904]
This issue began occurring this week, seemingly after an update of OSX. Apps such as Safari, Chrome and Slack behave in a very weird way when being moved using hs.grid.set

No better way to describe it than a video I guess :)

https://youtu.be/0DkT5XoF4Ak

My config is here but it has not changed for a while... https://github.com/jfchevrette/dotfiles/blob/master/hammerspoon/.hammerspoon/init.lua

**Comment by jfchevrette** [comment]
I changed hs.window.animationDuration to 0 and now I get the following behaviour when executing the same commands as in my video:

Starting with the window in the bottom right corner (x=1,y=1,w=1,h=1), setting it to position {x=0,y=0,w=1,h=2}
First run: Window is resized (not moved at all) a little bit but still in the bottom right corner
Second run: Window is moved (but not resized at all) to the top left corner
Third run: Window is resized to fill the desired grid cells (w=1,h=2)

It is as if Hammerspoon would effectively run this operation in 3 steps (reposition the window, move it, then resize it) when animationDuration is 0. However for some reason, the hs.grid.set process is stopping between each step on my machine.

I am not sure what I can do to debug this further...

**Comment by jfchevrette** [comment]
Found the culprit.

A few days ago I installed this app https://qotoqot.com/qbserve/

The app requires Accessibility privileges. It's probably interfering with Hammerspoon for some reason.

Now sure who's fault it is or if it's even possible for two apps to be able to have control over a window as the same time.

Thoughts?

**Comment by sdrygalski** [comment]
I got this behaviour (wicked and random resizing and jumping) while using other apps too (like SizeUp, HyperDock, Cinch, Spectacle, Slate etc).

I too installed qbserve and installed el cap 10.11.5. Quitting from qbserve does not fix anything.

**Comment by sdrygalski** [comment]
Chrome, Opera (in my case), Safari and even Slack has some web components (Slack desktop client is just a packaged web browser). It's just like osx 10.11.5 changed something how webkit and chrome engine (Blink) process resizing of their windows.

**Comment by sdrygalski** [comment]
When I use moving and resizing with e.g. Slate or HyperDock (e.g. 1/2 of the screen to left or right) those apps (chrome, safari, opera, slack) seems to SLIDE (like with animation) from left to right edge if their size is not changing. Other apps JUMP to new position.

**Comment by ivmirx** [comment]
Hi, developer of Qbserve here.

I've never used Hammerspoon but some users reported issues with Moom window controlling app, so I installed it and all the windows in the system moved with a noticeable lag until the system restart.

There are dozens of errors in the Console:

	05/27/2016 21:20:31.197 WindowServer[172]: Surface testing disallowed updates for 10 sequential attempts...
	05/27/2016 21:20:31.207 WindowServer[172]: Surface test allowed updates after 11 attempts (44 ms)
	05/27/2016 21:20:34.833 WindowServer[172]: Surface testing disallowed updates for 10 sequential attempts...
	05/27/2016 21:20:34.870 WindowServer[172]: Surface test allowed updates after 17 attempts (68 ms)
	05/27/2016 21:20:34.949 WindowServer[172]: Surface testing disallowed updates for 10 sequential attempts...

Qbserve uses AX API by getting `AXUIElementRef appRef = AXUIElementCreateApplication(pid);` and then finding nodes that are required for time tracking (once in 3 seconds).

It seems that OS X is not happy with two apps using AX windows at the same time. But probably this is a mistake on my side.

**Comment by sdrygalski** [comment]
I still have it after restarts. @ivmirx are you planing on fixing it?

**Comment by ivmirx** [comment]
@sdrygalski I'd like to but I'm a bit afraid this could end as a bug report to Apple and waiting for uncertain amount of time.

Can you please try to use Hammerspoon with VoiceOver enabled? It uses the same screen reading features, so if there's the same issue – it could be a problem inside AX code itself.

**Comment by ivmirx** [comment]
Here's what I have found for the same issue with Spectacle:
https://github.com/eczarny/spectacle/issues/607#issuecomment-222386287

**Comment by ivmirx** [comment]
@sdrygalski @jfchevrette We released an update today, the issue with window managers should be fixed (Spectacle, Moom, SizeUp, Optimal Layout, BetterTouchTool, Hammerspoon).

Qbserve now detects if any of these apps are present in the workspace and doesn't touch `AXEnhancedUserInterface` (or turns it off in case it was turned on before).

Also Chrome was just updated and there's improved accessibility for full screen videos, so I plan to stop using this attribute completely in the future.

**Comment by jfchevrette** [comment]
@ivmirx this is really good news! Thanks!

**Comment by Alok** [comment]
I'm getting the same resizing issue with [this](https://gist.github.com/12cd04586b735c5ee89a484ad89eaa2c) `init.lua`.
