### ISSUE TITLE
window tagging API

### ISSUE THREAD

**Issue by yoavg** [Hammerspoon/hammerspoon#906]
Hi,
First, thanks for hammerspoon! it is really nice, and makes working with the OSX wm relatively sane again.

This is not so much an "existing issue" but rather a feature request -- let me know if this is not the correct place for these.

I would like to see an API that allows for adding "tags" to windows. Tags are just strings, and the API will allow to add a tag to a window, remove a tag from a window, retrieve the list of currently available tags, and display (graphically) the tags of the currently visible windows.
It will also allow to filter windows based on tags.

Together with the new chooser, this will allow to have a "virtual desktops" like system, where each tag functions as a desktop, each window can be assigned to several desktops, and window switching can then either look at "current" tag or not.

I think such an API will be relatively easy to add, and provide very nice flexibility in terms of windows management.

I already implemented a similar system for my own use, but because I don't really know lua, the code is (a) ugly, (b) buggy and (c) probably inefficient. I will nevertheless be happy to share if there is interest..

(One annoying behavior that I came across in my implementation is that sometimes window switch ID numbers (for example when moving to full-screen and back) -- I do not know how to track these, and it causes errors in my config when it happens. Tips on this front will be appreciated as well.)

**Comment by cmsj** [comment]
@yoavg windows changing ID is tough to deal with. I'm not aware of any way to cope with that, but maybe @lowne has some ideas since he wrote `hs.windowfilter`.

My suggestion would be to publish what you have and see if you can find some people interested in the idea to work on it with you :)

**Comment by cmsj** [comment]
I'm going to close this out, because I think it could probably be implemented as a Spoon. If someone wants to work on it, please either open an issue on the Spoons repo suggesting it, or better yet, submit a PR :)
