### ISSUE TITLE
hs.drawing doesn't unRef function references on gc

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#912]
Minor impact, since they're integer references to byte-code, and most drawings that have click callbacks are probably usually persistent throughout a Hammerspoon run, but `hs.drawing` doesn't unRef function references from registry on garbage collection/delete.

**Comment by cmsj** [comment]
@asmagill I'm away from my main machine with its more complex drawing setup, but based on my testing, I think my change here works. Happy to hear any other results :)
