### ISSUE TITLE
Is it possible to get uielement position?

### ISSUE THREAD

**Issue by puttin** [Hammerspoon/hammerspoon#913]
Is it something like `AXPosition`?

Or a methods which we can get any possible attribute?

**Comment by puttin** [comment]
I noticed there are some attributes from [here](https://discussions.apple.com/thread/5234871?tstart=0)

**Comment by puttin** [comment]
and there is a method called [`get_prop`](https://github.com/Hammerspoon/hammerspoon/blob/eda9f9e1d76a90913e3ca88c6ee19e005c1bc6cd/extensions/uielement/internal.m#L33) which guide me to [NSAccessibility_Protocol](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Protocols/NSAccessibility_Protocol/index.html#//apple_ref/doc/constant_group/Standard_Attributes)

**Comment by asmagill** [comment]
You can check out https://github.com/asmagill/hammerspoon_asm/tree/master/axuielement... it's still very much a work in progress, but I'll try and get some documentation and a precompiled module up for it later this weekend or early next week.

There are some examples of its use in the folder's readme, in issue #887, and in https://github.com/asmagill/hammerspoon-config/blob/master/utils/speech.lua#L161.

**Comment by puttin** [comment]
Nice one!

**Comment by asmagill** [comment]
FYI, I've finally provided some documentation and a precompiled binary for the axuielement module.  If you're interested, check out the Reference.md file in the repository folder.

**Comment by puttin** [comment]
Awesome!

[Reference.md](https://github.com/asmagill/hammerspoon_asm/blob/749594fc24b855b3ddb257537fec07682253ee9e/axuielement/Reference.md)
