### ISSUE TITLE
hs.menubar icons/titles are sometimes trunctated

### ISSUE THREAD

**Issue by ventolin** [Hammerspoon/hammerspoon#914]
There seems to be an issue with setting both the title and icon for a menubar, where the title gets cut off -- the width is too small. Interestingly, if you reverse the order (set the icon before the title, or the other way around), in both cases the title is cut off, but the amount that's cut off is different.

I'm on a retina display, El Capitan (10.11.5), Hammerspoon 0.9.46.

Here's a simple init.lua to demonstrate:

``` lua
local iconPath = '/Applications/Hammerspoon.app/Contents/Resources/statusicon.pdf'
local menu = hs.menubar.new()
local title = 'title'

menu:setIcon(iconPath)
menu:setTitle(title)

-- try this, too... different result
-- menu:setTitle(title)
-- menu:setIcon(iconPath)

```

Icon first:
<img width="92" alt="icon_first" src="https://cloud.githubusercontent.com/assets/33061/15833408/8fba1bb0-2bdb-11e6-8441-2abb5c8e24f7.png">

Title first:
<img width="93" alt="title_first" src="https://cloud.githubusercontent.com/assets/33061/15833407/8fb6dd7e-2bdb-11e6-92c5-659768a236c1.png">

**Comment by cmsj** [comment]
Thanks, this has been a known issue for a while, but I don't think we had a GitHub issue, so thanks for filing that!

Fixing this is going to be.... interesting. The API that we currently use for those menubar items was deprecated in 10.10 and a new API was introduced, but we currently support older releases of OS X, so I can't rewrite `hs.menubar` to use the newer APIs (which, if anyone cares, is basically moving everything to being subviews of the `NSStatusBarButton` property of `NSStatusItem`).

**Comment by cmsj** [comment]
I'm going to close this out - it could only be resolved by rewriting hs.menubar to use the newer macOS NSStatusItem APIs, and if/when we do that, this issue would automatically be resolved.

**Comment by latenitefilms** [comment]
FYI: For some reason setting the title to " " before changing the icon and title fixes things in El Capitan. This bug also seems to be fixed in Sierra.

**Comment by latenitefilms** [comment]
Discussed here: https://github.com/CommandPost/CommandPost/issues/406

**Comment by asmagill** [comment]
The upcoming rewrite also allows specifying an explicit width and adjusting position of image in relation to text when both are set
