### ISSUE TITLE
Disable Smart Quotes in Console input field

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#915]
NSTextView has a property to disable smart quote substitutions, but I don't currently see one on NSTextField. If there is such a thing, we should do it, to prevent code from being broken by the OS.

**Comment by heptal** [comment]
I'll take a look as I've been working on an NSTextView/NSTextField app recently and dealt with the [data detector stuff](https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSTextCheckingResult_Class/index.html#//apple_ref/c/tdef/NSTextCheckingType).

**Comment by cmsj** [comment]
Hmm, is this actually an issue? I can't get the console input field to do smart quotes when they are enabled in the OS. I'm going to close this for now because I think I may have been premature in filing it.
