### ISSUE TITLE
I want to pass text to display in the menu bar, can I do that?

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#925]
I want to transfer a task from [2Do](http://www.2doapp.com/) application and have the task show up in the menu bar with the text that I copied. I was thinking of either trying to do it with [Bitbar](https://github.com/matryer/bitbar) or Hammerspoon as both allow to display information in the menu bar I believe.

What I want to do is essentially have the text I copied from the app, for example this 'reply to all emails'. I want it to be displayed in my menu bar where I can easily see it. I've read through the 'getting started' guide but couldn't really figure out how can I really do it and if I can do it at all.

Can I somehow pass this text into a certain file that Hammerspoon 'watches' and have the content of the file be displayed in the menu bar? Or perhaps there is some other efficient way of doing it.

Thank you a lot for any help and I really hope such a thing would be possible to do.

**Comment by asmagill** [comment]
`hs.pathwatcher` can be used to watch a file or folder for changes, and you can use `hs.menubar` to create a menu.

The tile of the menu only really works for a couple of short words... if you want more text, it works better to put it into the menu itself and then just add some sort of indicator to the title so you know that it's changed recently.

I have some examples of using menus for various things (unfortunately not well commented) which you can examine at https://github.com/asmagill/hammerspoon-config/tree/master/utils/_menus, and you can find others by checking other user's configurations through the Wiki (https://github.com/Hammerspoon/hammerspoon/wiki/Sample-Configurations) or searching for Hammerspoon in the github gists (https://gist.github.com/search?utf8=✓&q=hammerspoon)

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
