### ISSUE TITLE
Fast User Switching and Hammerspoon lockups

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#927]
This is a continuation of the Google-group message at https://groups.google.com/forum/#!topic/hammerspoon/CQFSRkUei4E

> Yes. Two logged in accounts with fast-user-switching between them both and both accounts with the same hammerspoon setup.
> 
> I don't have any tasks but I do react to system events like power state and network changes. I'm comfortable with building from source but I don't think that these fixes help in my case. Do you have any pointers of what I can use to look at the state of the app when it is stuck and not reacting to my input. 
> 
> On Jun 29, 2016, at 7:38 AM, asmagill asmagill@icloud.com wrote:
> 
> When you say two user accounts, what do you mean?  Two logged in accounts with fast-user-switching?  If so, to be honest, I'm not sure what, if any, effect that might have... you might try posting to https://github.com/Hammerspoon/hammerspoon/issues if this is the case and see if anyone else has experience running in that type of a setup.
> 
> The other thing that jumps to mind... are you using a lot of external processes with `hs.task` in your configuration? There was a known memory leak which has been patched since the latest formal release.  If you're comfortable building from source, checkout the current master at the github site and see if that makes a difference.
> ## 
> 
> A-Ron
> 
> On Tuesday, June 28, 2016 at 1:02:14 PM UTC-5, Oliver Schrenk wrote:
> Hi,
> 
> in the last few weeks I noticed that Hammerspoon freezes up a lot and is not responding to my keyboard short cuts anymore. I have to kill it and restart the application.
> 
> Of course this is very little to go on, but I'm willing to spend time investigating the issue. Is there some way to see what state the application is in, like dumping a stacktrace in Java? Some background: I'm using two user accounts, both running  Hammerspoon, is this known to cause issues?
> 
> Regards,
> Oliver
> ## 
> 
> You received this message because you are subscribed to the Google Groups "Hammerspoon" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to hammerspoon+unsubscribe@googlegroups.com.
> To post to this group, send email to hammerspoon@googlegroups.com.
> To view this discussion on the web, visit https://groups.google.com/d/msgid/hammerspoon/7e5a48c7-8782-44d5-bfc3-020f0ea6792b%40googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by asmagill** [comment]
First thing I would do is add `hs.crash.crashLogToNSLog(true)` to the top of your init.lua file, if it isn't there already... this will ensure that anything which is captured for Crashlytics submission is also logged via NSLog to the system console.  You can then use the Console application (I usually add "Hammerspoon" in the search field to limit the output -- there is a lot going on all the time and it scrolls by quickly!) to see if anything shows up in there.

I'm not sure if we're logging anything specific that might help here, but it can't hurt to look.

Off the top of my head, one module that I'm pretty sure won't play nice with fast-user-switching is `hs.ipc`, which is necessary for the command line tool `hs` to work.  It's not loaded by default, so if you are using `hs.ipc`, try commenting that out and see if that helps.  I have some ideas on how to fix it, if it does have an issue, but won't be able to test my theory and add a fix until the weekend.

You could setup a watcher with `hs.caffeinate.watcher` to detect when user-switching occurs to enable/disable specific watchers or callbacks you're using to see if you can narrow down the specific activities which are causing the lockups... it's not ideal as a long term solution, but it would help us in determining which modules need a closer look to make them handle user switching properly.

Something along the lines of:

~~~lua
local caffeinate = require("hs.caffeinate")
switchWatcher = caffeinate.watcher.new(function(event)
    if event == caffeinate.watcher.sessionDidResignActive then
    
    -- disable watcher/timer/whatever
    
    elseif event == caffeinate.watcher.sessionDidBecomeActive then
    
    -- enable watcher/timer/whatever
    
    end
end):start()
~~~

I'll also enable fast user switching myself and run some tests (limited memory, so I usually have it disabled since it makes Xcode and Safari or Chrome unbearable to use at the same time).  It is something I think we should be able to support or at least notify users about for items that don't work with it properly.

**Comment by asmagill** [comment]
Hmm... initial testing with `hs.ipc` indicates that it does work correctly in a Fast-User-Switched environment. I'll continue testing various things and see what comes up with other functionality... have you been able to narrow down the likely culprits?

**Comment by cmsj** [comment]
I'm going to close this out due to lack of response. Please feel free to re-open it if you can give us more information to reproduce/fix the issue.

**Comment by ccjensen** [comment]
Looks like `hs.crash.crashLogToNSLog(true)` is no longer available. Is there a replacement?
