### ISSUE TITLE
Functions call 'debug' cause Hammerspoon to crash

### ISSUE THREAD

**Issue by jonathanjsimon** [Hammerspoon/hammerspoon#929]
I have a function called `debug` that prints the arg `str` prepended with a timestamp. When the function is called, Hammerspoon crashes. If I change the name of the function to something else (`debugHandler`), Hammerspoon does not crash.

```
function debug(str)
    print(os.date("%Y-%m-%d %H:%M:%S") .. ": " .. str)
end
```

**Comment by cmsj** [comment]
By making a global called `debug`, you're overwriting the Lua debug library (https://www.lua.org/manual/5.3/manual.html#6.10), which Hammerspoon is using internally. The only way around this would be to choose a different name, or mark the function as local (although even then, you're going to have weird namespace issues if you ever try to use the debug library).

I would suggest renaming your function :)

**Comment by jonathanjsimon** [comment]
Aha....good point. No problem renaming the function.

**Comment by deryni** [comment]
It might make sense to protect the `debug` (and other standard global) tables in the hammerspoon lua environment to prevent issues like this from coming up (at least for tables that hammerspoon uses internally).

That said an alternative to this would be to have hammerspoon save copies of the tables/functions it needs at startup and use those internally to avoid this sort of problem.

I don't know how often this sort of thing comes up so it may not be worth it but I just wanted to throw those ideas out there.
