### ISSUE TITLE
HS can't detect multiple iTerm windows across spaces

### ISSUE THREAD

**Issue by muppetjones** [Hammerspoon/hammerspoon#933]
`hs.window.filter.new{'iTerm2'}:getWindows()` will only return the main iTerm window and any iTerm windows in the current space, even if the focused window is iTerm. It also _must_ be `iTerm2`, or no windows will be returned. There's also an issue with calling `hs.window.launchOrFocus('iTerm2')`--only `iTerm` (no `2`) works.

**Comment by heptal** [comment]
It seems a lot of people have problems with iTerm not being accessible correctly or consistently because they probably don't implement the AX APIs correctly. Perhaps one of us should raise an issue on that project.

**Comment by chdiza** [comment]
As for the `iTerm` vs. `iTerm2` differences, it's also the case in their own Applescript dictionary.  I raised an issue about that a while back, thinking it was an oversight in the iTerm2v3 beta, but IIRC the devs said something about it being needed "for backward compatibility".

**Comment by cmsj** [comment]
@muppetjones fwiw, our interaction with Spaces is generally near-zero - the underlying OSX APIs dont give us visibility into windows on other Spaces

**Comment by cmsj** [comment]
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)
