### ISSUE TITLE
hs.osascript.javascript ram issue

### ISSUE THREAD

**Issue by miwagner1** [Hammerspoon/hammerspoon#934]
simply calling this function to do a basic script causes a small jump in ram usage. HammerSpoon does not release any ram. Its also simply creating more threads every time it is invoked

simply spam the key bind in the code below to reproduce.

`function togglemenubarscript()
	hs.osascript.javascript([[
	appPrefs = Application('System Preferences');
	appPrefs.activate();
	appPrefs.panes.byId('com.apple.preference.general').reveal();
	Application("System Events").applicationProcesses.byName("System Preferences").windows.byName("General").checkboxes.byName("Automatically hide and show the menu bar").click()
	appPrefs.preferencesWindow.close();
]])
end
hs.hotkey.bind({"cmd", "alt"}, 'm', togglemenubarscript)`

**Comment by cmsj** [comment]
@miwagner1 I'm sad to say that this does not appear to be a bug in Hammerspoon - we've come across this before and I'm very sure that we're not leaking anything. I think it is the underlying Apple framework, unfortunately.

**Comment by quaritexa** [comment]
Where I can find reference for operate UI via JavaScript?
