### ISSUE TITLE
mouse battery watcher

### ISSUE THREAD

**Issue by ghost** [Hammerspoon/hammerspoon#939]
hi, thanks for the nice work. Is it possible to add an API to watch the battery of connected devices such as magic mouse? Thanks!

**Comment by cmsj** [comment]
This ought to be possible, but it will take some investigation to figure out how other apps do it. Thanks for the suggestion!

**Comment by cmsj** [comment]
http://stackoverflow.com/questions/3548283/access-mouse-keyboard-battery-status-via-api may be helpful here

**Comment by cmsj** [comment]
This will be available via hs.battery.otherBatteryInfo() in the next release :)
