### ISSUE TITLE
Add support to hs.keycodes for enumerating/selecting Input Methods

### ISSUE THREAD

**Issue by mludv** [Hammerspoon/hammerspoon#945]
Chinese keyboard layouts as for example "Pinyin (Simplified)" don't show up in the list of enabled keyboard layouts when running:

    hs.keycodes.layouts()

Instead the table only contains the other layout which are enabled. I don't know if this is a bug or because Chinese input systems are more complicated than only a change of key layout (because the need of choosing characters etc.)

**Comment by cmsj** [comment]
Yeah, the more complex languages are separate Input Methods in their own right, rather than keyboard layouts. We should probably also have a way to enumerate the available input methods, and select them, so we'll use this Issue to track that :)
