### ISSUE TITLE
Create a chat room on Gitter

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#946]
Would it be possible to create a chatroom on Gitter where people can ask questions and have discussions about Hammerspoon. I've tried #hammerspoon IRC channel many times, not once my questions were addressed. It seems Gitter becoming de-facto a place to discuss a project hosted on Github.

**Comment by cmsj** [comment]
IRC is tough, there aren't enough people around to answer, and I'm on vacation at the moment :)

Given that we have IRC and a mailing list, I'm not thrilled by the idea of splitting discussions across yet another medium.

My suggestion would be, if you're not getting an answer on IRC, post to our mailing list. If that isn't working, file an issue on GitHub :)

**Comment by agzam** [comment]
That's exactly what I'm saying - IRC channel doesn't seem to be functional - there's never anyone around to discuss anything. Maybe something that works for other projects (there are many great open-source projects on Gitter) would also work better? If Hammerspoon was hosted somewhere else, wouldn't it make sense if someone suggested to move it to Github?

**Comment by cmsj** [comment]
So I think there are several separate parts of this. Firstly, how can a user get an answer to a question. We currently have three options for them, and I think we manage to service most requests pretty well. I'm not convinced that adding a fourth method really helps here.

Secondly, there's the larger question of whether we can grow a larger community of folk prepared to help out with doing user support. I've not yet seen much evidence that there's much energy available for this. It would be nice if we could change that, but my experience of small open source projects is that it rarely happens.
