### ISSUE TITLE
can I make hotkey bind working when holding a key

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#949]
For example this code snippet from getting started moves window to the left : 

``` Lua
hs.hotkey.bind({"cmd"}, "F4", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()

  f.x = f.x - 10
  win:setFrame(f)
end)
```

However you have to press the key repeatedly. Can I make it so that when I hold the key, it will be moving?

Thank you for any help.

**Comment by asmagill** [comment]
`hs.hotkey.bind` can take up to three functions as arguments  (see `help.hs.hotkey.bind` in the Hammerspoon console): the first being the function to run when the key is pressed down, the second a function to run when it is released, and the third a function to run when the key-combo is held down and autorepeats...  so, something like:

~~~lua
myFn = function()
  local win = hs.window.focusedWindow()
  local f = win:frame()

  f.x = f.x - 10
  win:setFrame(f)
end)
hs.hotkey.bind({"cmd"}, "F4", myFn, nil, myFn)
~~~

should do what you want.

**Comment by nikitavoloboev** [comment]
Thank you this works. Although I quite dislike that the whole window moves. I would like to move it left or right where the window will readjust itself. 

So for example I have this window : 
![2016-08-05 at 17 29](https://cloud.githubusercontent.com/assets/6391776/17441616/361b4116-5b32-11e6-9de3-b3b7e02a224c.png)

I press my 'move screen left hotkey' and I get this : 


![2016-08-05 at 17 30](https://cloud.githubusercontent.com/assets/6391776/17441642/4dd09c52-5b32-11e6-8825-93a0d3902ce7.png)

Right now the above function moves the entire window outside the current desktop space if I was to use it.

Can I do something like that? Thank you for any help.

**Comment by asmagill** [comment]
When you say "readjust itself", are you talking about snapping to a grid or about expanding, rather than moving the window?  If snapping to a grid, take a look at `hs.grid` -- it may have something like what you're looking for.  If you're talking about expanding the window, you'll need to adjust the width (`f.w`) as well as the x (`f.x`) position.  As to keeping it fully on screen, you'll want to compare the new x,y position to `hs.screen.mainScreen():fullFrame()` and make sure it's within the screen bounds.

**Comment by dunkarooftop** [comment]
https://github.com/dbmrq/dotfiles/tree/master/home/.hammerspoon

You might find this useful

**Comment by cmsj** [comment]
I'm going to close this issue due to lack of response. Please feel free to re-open it if you have more to add :)
