### ISSUE TITLE
Crash using hs.network.configuration with callback

### ISSUE THREAD

**Issue by tanelikaivola** [Hammerspoon/hammerspoon#950]
# Example 
```lua
function cb(store, keys)end
n=hs.network.configuration.open()
n:monitorKeys()
n:setCallback(cb)
n:start()
```

After that, disable wifi (or do any network change) -> Crash.

(Currently I'm don't have access to the machine I used to test this so all of this is from my memory, I'll try to test everything I stated here asap. Or maybe someone reports that this successfully crashes on their machine also..)

# Root cause

The problem seems to be in hammerspoon/extensions/network/configurationinternal.m [doDynamicStoreCallback](https://github.com/Hammerspoon/hammerspoon/blob/39c2d51dc0200e0e8141192f16d0f0f444656a7b/extensions/network/configurationinternal.m#L21).

What seems to happen is:

- CFArrayRef changedKeys is valid when entering the function
- [dispatch_async](https://github.com/Hammerspoon/hammerspoon/blob/39c2d51dc0200e0e8141192f16d0f0f444656a7b/extensions/network/configurationinternal.m#L24) is called and before we get to execute the block, we fall out of doDynamicStoreCallback
- changedKeys gets released
- dispatch_async block gets executed and [(__bridge NSArray *)changedKeys](https://github.com/Hammerspoon/hammerspoon/blob/39c2d51dc0200e0e8141192f16d0f0f444656a7b/extensions/network/configurationinternal.m#L30) is now very much invalid

# Potential fix

Just before dispatch_async add: ```NSArray *nsChangedKeys = [(__bridge NSArray *)changedKeys copy];```

and then just use ```nsChangedKeys``` where ```(__bridge NSArray *)changedKeys``` when inside dispatch_async.

There very well could be a smarter fix, I haven't been doing anything for OS X for quite a while. (If this seems to be a sensible fix, I can do the ~two line pull request, just ask =)

**Comment by asmagill** [comment]
As the author of that module, I am chagrined... I can't believe I didn't catch that bug during testing.

Your fix works perfectly and I don't see any reason why it can't be applied as you suggest. If you have, or can have, a pull request submitted, I'll get it into the next release; otherwise I can make the additions later tonight or tomorrow.

**Comment by cmsj** [comment]
Seems like this can be closed. Thanks @tanelikaivola for an excellent writeup!
