### ISSUE TITLE
spotify.isRunning returns nil when player is playing music

### ISSUE THREAD

**Issue by walkr** [Hammerspoon/hammerspoon#951]
`hs.spotify.isRunning()` returns `nil` while the Spotify player is actively playing music.

**OS X**: El Capitan
**Hammerspoon**: 0.9.46

**Comment by cmsj** [comment]
While you have Spotify running, could you run this in the Hammerspoon Console and paste the results here?:

```hs.fnutils.each(hs.application.runningApplications(), function(app) print(app:name()) end)```

**Comment by walkr** [comment]
Here it is:

```shell
Activity Monitor
AirPlayUIAgent
Alfred 3
Android File Transfer Agent
com.apple.dock.extra
CoreServicesUIAgent
Dock
EscrowSecurityAlert
Finder
FolderActionsDispatcher
Hammerspoon
icdd
Image Capture Extension
iTunes Helper
Karabiner
Karabiner_AXNotifier
Keychain Circle Notification
LaterAgent
loginwindow
Logitech Control Center Daemon
Mail
Mail Web Content
nbagent
Notification Center
Photos Agent
Sketch
SketchMirrorHelper
Spotify
Spotify Helper
Spotlight
Sublime Text
System Events
SystemUIServer
TISwitcher
universalAccessAuthWarn
ViewBridgeAuxiliary
VOX Agent
Wi-Fi
```

**Comment by magnus-staberg** [comment]
I ran into this as well. There is some kind of string equality bug. Printing `hs.spotify.state_playing`
gives `'kPSP'`and printing `hs.spotify.state_playing`gives `kPSP`.

The following is actually true
```
  state = hs.spotify.getPlaybackState()
  stateFixed = "'" .. state .. "'"
  playingState = hs.spotify.state_playing
  return stateFixed == playingState 
```

**Comment by cmsj** [comment]
@zzamboni - I think you wrote the relevant kPSP section of hs.spotify - does the proposed fix here seem reasonable?

**Comment by zzamboni** [comment]
Hi @cmsj yes, the fix is correct. The values were [originally correct](https://github.com/Hammerspoon/hammerspoon/commit/f291e402205b48f72f06fc96f2a151de84ad334b#diff-8a3c2daf08afb6027b1769e09a046782R10) (including the single quotes around the strings) but seem to have been broken by [this commit](https://github.com/Hammerspoon/hammerspoon/commit/dce6444ca2aed13126c128e772bde02c574213a3#diff-8a3c2daf08afb6027b1769e09a046782).

**Comment by zzamboni** [comment]
I hadn't tested this, but I cannot reproduce the problem with Hammerspoon 0.9.54 (OP was using 0.9.46). I think there may have been a change in between, but at the moment both `hs.itunes.getPlaybackState()` and `hs.spotify.getPlaybackState()` are working fine, with HS 0.9.54 and macOS 10.12.3. I'm afraid db0165e will break things.

**Comment by cmsj** [comment]
@zzamboni interesting, well then if it's working as-is, I'll revert db0165e. Thanks!

**Comment by zzamboni** [comment]
```
> hs -c 'hs.spotify.isPlaying()'
false
> hs -c 'hs.spotify.isPlaying()'
true
> hs -c 'hs.spotify.getPlaybackState()'
kPSP    ### Note no quotes
```
