### ISSUE TITLE
Control applications in dock

### ISSUE THREAD

**Issue by 404pilot** [Hammerspoon/hammerspoon#953]
Not sure if this is a right place to ask questions.

Basically, what I am trying to do is to bind a shortcut to open 1st, 2nd, 3rd ... application in dock.

I have already checked the documentation here: [http://www.hammerspoon.org/docs/hs.dockicon.html](http://www.hammerspoon.org/docs/hs.dockicon.html)

But that is not what I want.

Thanks.

**Comment by nikitavoloboev** [comment]
Why not just bind hotkeys to applications themselves?

**Comment by asmagill** [comment]
Currently choosing an application icon which is in the Dock is not directly possible... you have to know the application's name or bundle-id to specify which application to activate/open with `hs.application`, and there is no easy way to get the list of what applications are in (or not in) the Dock.  If you know the exact location of the Dock, you could simulate mouse button presses with `hs.eventtap`, but this would be extremely fragile depending upon dock size, magnification settings, number of icons, etc.  And `hs.application("Dock"):allWindows()` returns an empty table, so I'm not even sure at present how to get the dock's current location with the core modules included with Hammerspoon.

That said, if you're willing to use an experimental, still in progress, external module, I have been working on one at https://github.com/asmagill/hammerspoon_asm/tree/master/axuielement which should be able to do what you want... it's not currently (and may or may not ever be) part of the Hammerspoon core, so you'll need to manually add it, and it is still a work in progress, so syntax, etc. may change in the future, but I think something like this might do what you want:

~~~lua
ax = require("hs._asm.axuielement")
d = hs.application("Dock")
iconNumber = 1 -- position in the dock, starting with 1 being the furthest left item
icon = ax.applicationElement(d)[1][iconNumber]
if icon:roleDescription() == "application dock item" then
    icon:doPress()
else
    print ("not an application")
end
~~~

The exact mechanisms behind `hs._asm.axuielement` is discussed somewhat at the site listed above, but at its most basic, `ax.applicationElement(d)` is the root accessibility object for the Dock application, and it's first (and only) child object is the list of dock items (thus the `[1]`).  The list's children are the Dock items in order (thus the `[iconNumber]`), and each dock item has some actions defined, the one we care about being `doPress()`.

**Comment by 404pilot** [comment]
@nikitavoloboev  @asmagill  thanks!

**Comment by dgghita** [comment]
Hi and sorry to revive this thread. What was the outcome of the axuielement module? I see it's no longer available in the hammerspoon_asm repo. Thanks in advance!

**Comment by latenitefilms** [comment]
@dgghita - You can find it here: https://github.com/asmagill/hs._asm.axuielement

**Comment by dgghita** [comment]
@latenitefilms - Thanks so much!

(Off-topic: this looks like so much fun, can't wait to try it.)

**Comment by marcelgerber** [comment]
For anyone coming here in the year 2023, this is what I used for this feature and it works beautifully in macOS Ventura:

```lua
d = hs.application("Dock")
for i=1,9 do
    hs.hotkey.bind({"alt"}, tostring(i), function()
        iconNumber = i
        icon = hs.axuielement.applicationElement(d)[1][iconNumber]
        if icon:attributeValue("AXRoleDescription") == "application dock item" then
            icon:performAction("AXPress")
        else
            print ("not an application")
        end
    end)
end
```

**Comment by Write** [comment]
> For anyone coming here in the year 2023, this is what I used for this feature and it works beautifully in macOS Ventura:
> 
> ```lua
> d = hs.application("Dock")
> for i=1,9 do
>     hs.hotkey.bind({"alt"}, tostring(i), function()
>         iconNumber = i
>         icon = hs.axuielement.applicationElement(d)[1][iconNumber]
>         if icon:attributeValue("AXRoleDescription") == "application dock item" then
>             icon:performAction("AXPress")
>         else
>             print ("not an application")
>         end
>     end)
> end
> ```
Hello,
Is there an update for this on Sonoma ? Everything returns 'not an application for me'
Thanks
