### ISSUE TITLE
hs.layout.apply doesn't work with screens with negative absolute coordinates

### ISSUE THREAD

**Issue by ciamac** [Hammerspoon/hammerspoon#955]
I'm trying to use hs.layout.apply to move a window to a screen which has negative absolute coordinates using a frame rect, e.g.,

``` lua
> hs.screen.find("Thunderbolt Display"):frame()
hs.geometry.rect(-2560.0,0.0,2560.0,1440.0)

> hs.layout.apply({{ "Foo", nil, "Thunderbolt Display", nil,
                                  hs.geometry.rect(-2560.0,0.0,100.0,100.0), nil }})
```

This code should move the "Foo" app to a 100x100 window on the upper left of the "Thunderbolt Display" screen. Indeed, if I simply use hs.window.setFrame(), with this rect, it works fine. 

However, hs.layout.apply interprets negative coordinates differently, as offsets from the other side of the frame, before they are passed to setFrame(). Hence, the above code actually ends up moving the window to a different screen.

This effectively makes it impossible to us hs.layout.apply to place windows on screens with negative absolute coordinates with frame or full-frame rects.

**Comment by heptal** [comment]
There are a number of window coordinate systems in macOS: global coordinate space (in which your screen is placed), screen coordinate space, view coordinate space. In addition, display scaling means there can be discrepancies between 'real' and 'effective' pixels. This basically makes developing multi screen apps a huge pain, not just Hammerspoon.

Will it work if you try, say, using screen-local positive coordinate as if the global coords are not negative? Since you're already specifying the screen in `hs.layout.apply` it could already be operating in that screen's context.

**Comment by ciamac** [comment]
No, it does not work with screen-local positive coordinates. This is expected, the documentation of hs.apply.layout (consistent with hs.window.setFrame) states that it expects absolute coordinates for frame or full-frame rects.

The problem is that hs.apply.layout doesn't seem to anticipate the possibility that absolute coordinates will be negative, and overloads the meaning of negative coordinates to something else. Hence, it cannot be used on screens with negative absolute coordinates.

**Comment by cmsj** [comment]
@ciamac you're right, this is a terrible oversight on my part. As it stands, the only one of the three frames that will work is the unitrect one, which is not tremendously fine-grained.

I think the only viable solution here would be that if a monitor is specified, we treat the frame/fullframe rects as relative to that screen. This would break existing configs though, which is a shame, and it doesn't help in situations where no monitor is specified, and negative absolute co-ordinates are supplied.

Anyone got any better ideas?

**Comment by ciamac** [comment]
Perhaps a different solution could be to add an optional argument "preserveNegativeCoordinates" to hs.layout.apply(). If this is true, then hs.layout.apply() should not try to transform negative coordinates, but rather preserve them as is. If it is false or not present, then the present behavior of converting negative coordinates would apply, so as to maintain backward compatibility.

**Comment by warsaw** [comment]
I just hit this problem myself.  I had to switch out my previous docking station for a thunderbolt one (thanks to Apple's [breaking of DisplayLink](https://plugable.com/2018/03/30/macos-10-13-4-disables-displaylink-duet-display-devices/) in 10.13.4) and I haven't been able to coerce the new thunderbolt dock to layout the screens with only positive coordinates.  This means that the windows that get placed on my left display have negative absolute coordinates, and they simply cannot be placed correctly.

Having an optional argument to `hg.layout.apply()` honor negative coordinates seems fine.

**Comment by warsaw** [comment]
I'm wondering if there's been any more thought about this issue.  After upgrading to Mojave, my dock (Elgato) insists on putting the left screen in the wrong place, requiring me to use Displays arrangement to stack them correctly.  But then my left screen is negative absolute coordinates, so I can't actually set up its location in hammerspoon.

**Comment by cmsj** [comment]
@warsaw apologies for the long delay in getting back to this issue. I have a cunning plan! Are you still using `hs.layout` and would be willing to test a fix?

**Comment by cmsj** [comment]
I think this will do the trick. If you quit Hammerspoon and patch this into `/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/layout/init.lua` then you should be able to add a dictionary to each entry in the layout table with either `absolute_x` or `absolute_y` or both, set to `true` to retain the absolute co-ordinates you've set.

```lua
diff --git a/extensions/layout/init.lua b/extensions/layout/init.lua
index 4356c89f..fce59f3b 100644
--- a/extensions/layout/init.lua
+++ b/extensions/layout/init.lua
@@ -134,6 +134,10 @@ function layout.apply(theLayout, windowTitleComparator)
         local unit = _row[4]
         local frame = _row[5]
         local fullframe = _row[6]
+        local options = _row["options"]
+        if not options then
+            options = {}
+        end

         -- Find the application's object, if wanted
         if _row[1] then
@@ -233,10 +237,10 @@ function layout.apply(theLayout, windowTitleComparator)

                 if winframe then
                     if winframe.x < 0 or winframe.y < 0 then
-                        if winframe.x < 0 then
+                        if winframe.x < 0 and not options["absolute_x"] then
                             winframe.x = screenrect.w + winframe.x
                         end
-                        if winframe.y < 0 then
+                        if winframe.y < 0 and not options["absolute_y"] then
                             winframe.y = screenrect.h + winframe.y
                         end
                     end
```

Example with these set would be:

```lua
my_layout = {
  {"Mail",              nil,          display_imac,    hs.geometry.unitrect(0, 0.5, 0.5, 0.5),   nil, nil, options={absolute_x=true,absolute_y=true}},↲

}
```
