### ISSUE TITLE
Release 0.9.47

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#957]
@cmsj, I think we should probably add pull requests #936, #942, and #952 (pending your approval of them or any of the others still in PR stage) and generate release 0.9.47... it's been some time, and there have been some bug fixes added to the master branch since 0.9.46 that we should probably make sure people are using.

The canvas module I've been working on is undergoing some changes in organization and should not be a factor for this release... I'm trying to make something more flexible that can allow merging different types of views (media, textual input, buttons, webviews, etc) into a combined whole... while it *can* replace `hs.drawing` as it stands, there will be some changes along the way before I have it where I want it... i'd rather not introduce something to core that's going to be a work in progress for a while yet.

Your thoughts?

**Comment by cmsj** [comment]
@asmagill sounds like a good idea. I apologise again for having been almost entirely absent recently, and thanks for doing stuff. I'm going to be travelling for the next couple of weeks, which usually means I have some more time. I'll try and get up to speed on the PRs and get a release out :)

**Comment by cmsj** [comment]
@lowne anything you'd like to chip in for an impending release?

**Comment by lowne** [comment]
Nothing from me

**Comment by cmsj** [comment]
I've just bumped Lua from 5.3.2 to 5.3.3 - seems fine to me, but I'd appreciate feedback from others :)

**Comment by asmagill** [comment]
Ok, I'd like to get a response to #888 and #958 if possible (though how long do we wait?), and I'll be reviewing your NSTimer change tonight, but pending a review of my two pulls added this afternoon, I think I'm good to go for 0.9.47 when you are.

**Comment by cmsj** [comment]
So one thing I want to bring up (again again again again :) is our support of old releases. We're weeks away from 10.12 and unless we do something, that will mean we're up to supporting 5 major releases of OS X. As you know, I've always disagreed with supporting older releases, but I think 5 is absolutely untenable.

So, I want to drop, at the very least, 10.8 as an officially supported platform in either 0.9.47 or 48. I would also like to drop 10.9 too. Thoughts? :D

**Comment by asmagill** [comment]
I have no problem with officially dropping 10.8 and 10.9 -- I'm not sure how much testing actually gets done for these versions anyways.  There have been some pretty significant deprecations/additions starting with 10.10, so it makes a good clean cut-off point.

I would suggest that where it's obvious we're using code that doesn't support earlier versions, we include code to verify the version and print an error to the console rather than let the application crash... there is a lot of stuff that *should* continue to work fine in earlier versions if the end user is willing to compile it themselves...

Something like what I did for `hs.webview` at the top of its `init.lua`:

~~~lua
local USERDATA_TAG = "hs.webview"

local osVersion = require"hs.host".operatingSystemVersion()
if (osVersion["major"] == 10 and osVersion["minor"] < 10) then
    hs.luaSkinLog.wf("%s is only available on OS X 10.10 or later", USERDATA_TAG)
    -- nil gets interpreted as "nothing" and thus "true" by require...
    return false
end

local module       = require(USERDATA_TAG .. ".internal")
~~~

I'm not suggesting we go back and add this to all of the existing code, but as we add new modules, if you happen to notice when the class/feature was added, this will go a long way to simplifying things for anyone who wants to tackle compiling a version for earlier OS's and knowing, without crashing, what will and won't work for them.

**Comment by asmagill** [comment]
I've got a wrapper to Apple's SimplePing sample code at https://github.com/asmagill/hammerspoon_asm/tree/master/ping

I plan to add it to `hs.network` at some point, but I don't know when I'll get a chance to write the documentation for it (hopefully early next week, but I'm going to be in-between machines starting tomorrow as I move to 10.12), so I don't want this to hold up 0.9.47 unless you think it's an important addition.

I'm pretty happy with it now, but it needs documentation and I do still want to add an additional wrapper with callback that will happily send/receive ICMP(v6) ECHO packets in the background and only trigger the callback when some threshold is met (e.g. a certain number of lost packets, response time grows by a certain percentage, etc.)

**Comment by cmsj** [comment]
I think let's hold off on the ping for next time

**Comment by cmsj** [comment]
ok, we're looking to be pretty close at this point. I've updated the deployment target from 10.8 to 10.10 and updated some of the non-extension cocoapods, and travis is passing :)
A bit of banging tomorrow and two more things milestoned for 0.9.47, neither of which seems particularly critical (and one is just a docs thing anyway)

:)

**Comment by cmsj** [comment]
Done! Thanks very much everyone :)
