### ISSUE TITLE
hs.logger request

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#960]
@lowne, since hs.logger was yours, got a question/request...

To keep labels consistent in the variety of things I work on, I often set a variable at the beginning of code I think I'm likely to reuse in other modules with the module's name and then use the variable instead of a hard coded name... In doing this with hs.logger, it's less obvious then I'd like because the label has its end truncated at 10 characters... I find myself doing this:

``` lua
local logLabel = (#USERDATA_TAG <= 10) and USERDATA_TAG
                                       or hs.utf8.codepointToUTF8(0x2026) .. USERDATA_TAG:sub(-7)
local log      = hs.logger.new(logLabel, "warning")
```

This pre-truncates the label from the beginning because most of my labels start with "hs._asm.", which is 8 characters right there, leaving me with only 2 to distinguish modules... my approach keeps the most likely different portion (the end) and truncates the most likely repetitive part... and because I like the ellipsis 1 character width, the Unicode character ends up taking up 3 spaces, rather than the 1 it visually does, so I have to use -7 rather than -9, though that's more of a nit.

So, I guess two requests/questions... would making hs.logger UTF8 aware (at least for strings that it truncates internally) break anything, and would changing the truncation to the beginning break anything (or would adding a flag indicating which truncation to do be better)?

I can take a look at this next week, if you're busy, but since it was your module to begin with, I figured you might have a better idea about making sure the requested changes don't break your intentions/expectations of the module.

**Comment by lowne** [comment]
After quickly looking at the source (been a long time...):

- there's an undocumented `logger.idLength(nchars)` function ([here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/logger/init.lua#L170)), which might be the easiest solution to your problem
- truncation currently is done via `string.format` [here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/logger/init.lua#L158), so yea, it's raw bytes
- making it UTF-8 aware + fancy (and flaggable?) truncations doesn't seem trivial; if you have the time and inclination, maybe you could just redo whole thing in ObjC (IIRC that's been the repeatedly agreed-to conclusion wrt `logger` in various threads; moreover it seems likely that NSString/... could already have fancy truncation methods)

**Comment by cmsj** [comment]
@asmagill looks like this was taken care of by #968?

**Comment by asmagill** [comment]
yup
