### ISSUE TITLE
hs.http and hs.httpserver problem...

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#961]
Ok, I'm probably missing something obvious, because I know I did something very similar when testing out my changes to httpserver a while back, but this is driving me nuts...

Set up the web server like this:
~~~lua
w = hs.httpserver.new():setPort(50103):setCallback(function(...)
    print("yup")
    return hs.inspect(table.pack(...)), 200, { ["Content-Type"] = "text/plain" }
end):start()
~~~

Now, I go to my web browser and type in `http://localhost:50103/` and I get what you'd expect:

~~~
{ "GET", "/", {
    Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    ["Accept-Encoding"] = "gzip, deflate",
    ["Accept-Language"] = "en-us",
    Connection = "keep-alive",
    DNT = "1",
    Host = "localhost:50103",
    ["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7",
    ["X-Remote-Addr"] = "::1",
    ["X-Remote-Port"] = "50206",
    ["X-Server-Addr"] = "::1",
    ["X-Server-Port"] = "50103"
  }, "",
  n = 4
}
~~~

and "yup" in the console.

Now I do the following in the console:

~~~lua
hs.inspect(table.pack(hs.http.get("http://localhost:50103/")))
~~~

And after about 60 seconds (the normal timeout for no connection), I get this:
~~~
{ 0, "", {},
  n = 3
}
yup
~~~

The "yup" tells me that it actually is running the callback for the httpserver, but some how its still failing to return anything.

I've tried `hs.http.get("http://www.yahoo.com")` and it returns with the expected data almost immediately.

However, using asyncGet works for localhost, and quicker then the 60 seconds a synchronous get takes for localhost:

~~~lua
> hs.http.asyncGet("http://localhost:50103", {}, function(...) print(hs.inspect(table.pack(...))) end)

yup
{ 200, '{ "GET", "/", {\n    Accept = "*/*",\n    ["Accept-Encoding"] = "gzip, deflate",\n    ["Accept-Language"] = "en-us",\n    Connection = "keep-alive",\n    Host = "localhost:50103",\n    ["User-Agent"] = "Hammerspoon/0.9.46 CFNetwork/760.6.3 Darwin/15.6.0 (x86_64)",\n    ["X-Remote-Addr"] = "::1",\n    ["X-Remote-Port"] = "50229",\n    ["X-Server-Addr"] = "::1",\n    ["X-Server-Port"] = "50103"\n  }, "",\n  n = 4\n}', {
    ["Accept-Ranges"] = "bytes",
    ["Content-Length"] = "404",
    ["Content-Type"] = "text/plain",
    Date = "Wed, 24 Aug 2016 22:31:34 GMT"
  },
  n = 3
}
~~~

Any thoughts, or am I crazy?  I'll look at the http and httpserver code later, if no one has any thoughts, but have we made any changes to either recently?  Would the websocket changes to http or httpserver affect regular, not asynchronous "GET"?

**Comment by asmagill** [comment]
Oh, and just for completeness, it doesn't matter if I specify `localhost`, `127.0.0.1`, or `[0000:0000:0000:0000:0000:0000:0000:0001]` (still necessary in Safari for some reason) or `[::1]`... it still hangs until it returns nothing, but prints "yup" for a synchronous call, and works perfectly for an asynchronous one.

**Comment by cmsj** [comment]
I'm not sure that this could ever have worked - you're trying to do  all of this on one thread. The runloop is blocked on `[NSURLConnection sendSynchronousRequest]` from `hs.http` so has no way to get to the `hs.httpserver` listener.

**Comment by asmagill** [comment]
...what you say makes complete sense... but I really thought I remembered it working before... as you say, though, that should be impossible.  Ok... moving on.
