### ISSUE TITLE
hs.timer, __gc, and strong references to up-values

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#963]
@cmsj, your commit 500217cf6ec74a0b089a353ea94672fddba50364 reminded me of something that I think I may be getting closer to understanding wrt to `hs.timer` and its oddities... I'm putting this in here as a reminder to dig into it further next week and to see if it suggests anything to you or someone else before I get a chance to look into it...

The situation: (this is a simplification of the code I was working on, and I include it here to explain what I was doing, but I haven't tested this *exact* code, so it may require tweaking if you want to test it yourself...)

~~~lua
local module = {}
local states = setmetatable({}, { __mode = "k" }) -- weak keys

local doSomethingFunction = function(self)
    ... do something ...
end

module.new = function()
  local self = {}
  states[self] = {
    myTimer = hs.timer.doEvery(60, function() doSomethingFunction(self) end)
    myID = hs.host.uuid()
  }
  return setmetatable(self, { __index = function(_, key)
    if key == "id" then
      return function(self) return states[self].myID end
    else
      return nil
    end
  })
end

return module
~~~

The basic idea is that we have a table acting as an object that you can run methods on, e.g.
~~~lua
a = module.new()
a:id() -- will return a uuid for this object
~~~

Now, since the states table has a weak reference to `a`, entering `a = nil` *should* release the table containing the timer, causing the timer to be released and stopped.  And it does.  Sometimes.

Other times, if the `doSomethingFunction` has a strong reference to an upvalue that isn't also being collected at that time, what would happen is that the timer's __gc *was* invoked (I verified this by putting in logging output in the timer's __gc function in internal.m), but that the timer was *not* stopped, and the value in the `states` table did *not* get collected, even though there was no longer a strong reference to it's key in lua (that I could identify). The timer reference also became a generic userdata (further proof that __gc was called on it, since that removes the objects metatable).

I ended up changing my approach slightly and worked around it, but it's definitely something to add to the timer weirdness tally... To me it suggests that something is holding on to a reference to the timer's function reference (remember that timer's __gc clears it from the timer structure), and as long as it does, the timer's context isn't released, so it remains in the runloop even though __gc invalidates it.

At any rate, I don't have time to look into this before next week, but maybe in conjunction with what you've seen and are trying to work around... well, I hope it adds a piece to one of our puzzles that leads to an ultimate fix because timer has had oddities for a long time now 
😜

**Comment by cmsj** [comment]
One option that springs to mind, is rewriting `hs.timer` to use `NSTimer`. I don;t think there's a particularly good reason it's using `CFTimer`. It's not a satisfying solution to the problem, but it would probably make the module a lot easier to maintain ;)

**Comment by cmsj** [comment]
@asmagill I went ahead and committed an NSTimer rewrite. It's more in line with our other modules, almost all of the functionality is now encapsulated in an ObjC class, and we had a pretty comprehensive test suite to make it easier to trust.
I'm happy to pull this out again if we find issues - one noticeable difference is that we now don't track Running/Stopped state in a separate BOOL, which means that the __tostring doesn't return quite the same values, but I would seriously hope that nobody was parsing the string output of that, instead of using `:running()` :)

**Comment by asmagill** [comment]
I'd looked at NSTimer and was thinking about seeing how hard it would be to switch, but figured I'd wait until the next release...

I don't recall why, but I remember thinking that there was one specific use case wouldn't be simple to convert, but I forget what it was that made me think so... I'll run this against my configuration and look over it later today and see if it sparks my memory or if I'm remembering wrong.

**Comment by cmsj** [comment]
Thanks. What convinced me to do it is that CFTimer and NSTimer are toll-free bridged, so I was able to keep a few bits of the old API usage, which aren't so easy to do with NSTimer :)

**Comment by asmagill** [comment]
LGTM and I've been running with it since yesterday, with pretty heavy timer usage, and have seen no issues.

Having reviewed the code side by side with its predecessor, I can't recall what I thought might be a challenge... if I had to guess, I probably glossed over the line about them being toll-free bridged or it didn't sink in properly because I don't see anything now that raises any concerns... plus this should be easier to attach code to or inspect while its running and (hopefully) aid in future troubleshooting.

**Comment by cmsj** [comment]
cool, thanks. I'll close this out then :)
