### ISSUE TITLE
hs.window.filter allowTitles filter case-sensitive

### ISSUE THREAD

**Issue by albinekb** [Hammerspoon/hammerspoon#969]
Hello! I'm trying to integrate hammerspoon with alfred, but came across a problem.

When doing `:setAppFilters('app name', {allowTitles='title'})`, it doesn't match if the window title has capital letters, code for this is here:

https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/window/filter.lua#L199-L203

Am I missing something? Or should i make a PR to add `allowAnyCaseTitles` or something?

Thanks!

**Comment by cmsj** [comment]
I think it would make sense for the match to be case insensitive - although I worry slightly about cases where the only way to distinguish two windows is their case.

To be clear, it's working for you if you specify the exact same case in `allowTitles`, right?

**Comment by albinekb** [comment]
Yes, it works if i specify the exact same case, but in the way I'm using it i would like to have it caseinsensitive

**Comment by lowne** [comment]
You can use something like `{allowTitles='[Tt]itle'}` - see the documentation for (Lua's) `string.match`

**Comment by cmsj** [comment]
@albinekb was @lowne 's suggestion sufficient for your needs? If not, please re-open :)
