### ISSUE TITLE
10.12 -- hs.hotkey and fn modifier

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#975]
Confirmed #922 - in 10.12, holding down the `fn` key modifier in addition to whatever other modifiers are part of a hotkey binding causes the hotkey binding to be ignored, but it is still not possible to set the fn modifier as part of the binding definition.

This breaks the trick of checking the fn modifier state during the callback with hs.eventtap.checkKeyboardModifiers and doing something different if it is/is-not also being pressed, and may also break using Karabiner (when/if it is 10.12 capable) to remap fn to something else since the fn modifier state will presumably still be "down".

Will examine more closely and re-examine possible eventtap based hotkey replacement.   Should also track Karabiner and see how they eventually address this if it's not too low level.

**Comment by openroc** [comment]
@quantonganh seems it use 'ctrl' key, not 'fn' key, so the bug DOES NOT been resolved actually.

**Comment by cmsj** [comment]
@asmagill did this go anywhere?

**Comment by viogus** [comment]
any chance could we make fn key as a modifier?

**Comment by cmsj** [comment]
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)
