### ISSUE TITLE
how can i bind shift_r just by hammerspoon

### ISSUE THREAD

**Issue by Lluvio** [Hammerspoon/hammerspoon#985]
Previously i use karabiner, but now karabiner is not working on serria :(

**Comment by cmsj** [comment]
Sorry, you can't do that with Hammerspoon. The events no longer contain that kind of information when they reach us. Karabiner worked via a kernel extension to be able to see the events at a much lower level.

I'm not aware of any options beyond waiting to upgrade until Karabiner is updated (actually rewritten in this case). Sorry!

**Comment by Lluvio** [comment]
@cmsj 
it is no problem, thank you very much!
