### ISSUE TITLE
Using complex bindings possible like `hyper+k, hyper+j` and 'hyper+k, hyper+l' for left and right

### ISSUE THREAD

**Issue by excetara2** [Hammerspoon/hammerspoon#987]
Is it possible to have complex bindings where you can have `hyper+k` as your main window management button and then hitting `hyper+j,k,l,i` will send left, middle, right, and top. I hope this makes sense but essentially bindings like `ctrl+x` in emacs that can be used to do many things. I couldn't find documentation on if or how this was possible.

**Comment by deftsp** [comment]
Yes.  Try http://www.hammerspoon.org/docs/hs.hotkey.modal.html.

**Comment by excetara2** [comment]
Okay yeah thanks that looks like it will do the trick! Do you know of any good reference for this that uses similar to my use case of having a hyper binding that controls sending the windows to different areas of the screen? Or any example as I don't know Lua or have a hammerspoon file yet but planning to switch so this may ease the process.

**Comment by cmsj** [comment]
@excetara2 not explicitly using modal hotkeys, but my config (github.com/cmsj/Hammerspoon-Config) uses regular hotkeys for various window management tasks, and the modal ones work almost the same way.
