### ISSUE TITLE
How to debug Hammerspoon scripts?

### ISSUE THREAD

**Issue by quaritexa** [Hammerspoon/hammerspoon#989]
Will be nice to have debugger like this: https://youtu.be/52SVAMM3V78

**Comment by cmsj** [comment]
Honestly I think a debugger like that is way beyond our development resources at the moment.

I tend to do my debugging with print statements :)

**Comment by quaritexa** [comment]
Add at least a variable watcher.

**Comment by aristidesfl** [comment]
+1 for variable watcher. print debugging is painful

**Comment by cmsj** [comment]
What sort of functionality would you want from a variable watcher?

**Comment by aristidesfl** [comment]
The simplest implementation I can think of right now would be a debugger statement which, when executed, would pause execution, and make a window open. This window would show a list of variables available in the current scope and their values.

**Comment by cmsj** [comment]
Maybe take a look at https://github.com/pkulchenko/MobDebug

**Comment by aristidesfl** [comment]
Can it be used with Hammerspoon?

**Comment by cmsj** [comment]
@aristidesfl I would expect so, but I've never tried it. Any Lua modules *should* work.

**Comment by aristidesfl** [comment]
```lua
$ cat ~/.hammerspoon/init.lua
require("mobdebug").start()
```
```sh
$ tree ~/.hammerspoon/
/Users/user/.hammerspoon/
├── init.lua
└── mobdebug.lua
```
```
2017-02-20 16:12:48: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: module 'socket' not found:
	no field package.preload['socket']
	no file '/Users/user/.hammerspoon/socket.lua'
	no file '/Users/user/.hammerspoon/socket/init.lua'
	no file '/usr/local/share/lua/5.3/socket.lua'
	no file '/usr/local/share/lua/5.3/socket/init.lua'
	no file '/usr/local/lib/lua/5.3/socket.lua'
	no file '/usr/local/lib/lua/5.3/socket/init.lua'
	no file './socket.lua'
	no file './socket/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/socket.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/socket/init.lua'
	no file '/Users/user/.hammerspoon/socket.so'
	no file '/usr/local/lib/lua/5.3/socket.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './socket.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/socket.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
	/Users/user/.hammerspoon/mobdebug.lua:102: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
	/Users/user/.hammerspoon/init.lua:177: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by aristidesfl** [comment]
Btw, any thought on #1235 ? Can't move forward on that one.

**Comment by asmagill** [comment]
Can this be closed since #1268 is now showing signs of working?

**Comment by cmsj** [comment]
This one is closed ;)

**Comment by nimatrueway** [comment]
I managed to debug my hammerspoon script using [EmmyLua](https://marketplace.visualstudio.com/items?itemName=tangzx.emmylua).

1. Open your `~/.hammerspoon/init.lua` script, paste EmmyLua debugger server listener to your code using vscode action `EmmyLua: Insert Emmy Debugger Code`.
2. Reload your script in Hammerspoon.
3. Now you can connect to it anytime in vscode using `EmmyLua New Debug` debug configuration.
4. If your entire script becomes ugly with red squiggly lines complaining that `hs` global variable is never defined just add this to the top of your script file.
```
-- stupid workaround to undefined global hs
_hs = hs
hs = _hs
```
