### ISSUE TITLE
Question - Clear the console?

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#991]
Is there a way or command to clear the Hammerspoon Console?

I'd love to be able to 'reset' the console each time I reload the Config.

Thoughts?

**Comment by junkblocker** [comment]
@latenitefilms, [hs.console.clearConsole()](http://www.hammerspoon.org/docs/hs.console.html#clearConsole) ?

**Comment by latenitefilms** [comment]
Perfect, thanks @junkblocker !

Sorry... I missed the **hs.console** section in the API documentation. My bad!

**Comment by luckman212** [comment]
Still, a little toolbar button would be super nice to have...

**Comment by latenitefilms** [comment]
You can easily add a "clear" button yourself.

See: https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/init.lua#L107

**Comment by luckman212** [comment]
Thanks @latenitefilms 

It was a bit of a head scratcher for me, but I eventually figured out what I was doing wrong. For anyone else who might benefit, here's the code I inserted into my init.lua to get a Clear button on the Console:

```
-- custom Console toolbar (adds Clear button)
local toolbar = require("hs.webview.toolbar")
local console = require("hs.console")
local image = require("hs.image")
console.defaultToolbar = toolbar.new("CustomToolbar", {
    { id="prefs", label="Preferences", image=image.imageFromName("NSPreferencesGeneral"), tooltip="Open Preferences", fn=function() hs.openPreferences() end },
    { id="reload", label="Reload config", image=image.imageFromName("NSSynchronize"), tooltip="Reload configuration", fn=function() hs.reload() end },
    { id="openCfg", label="Open config", image=image.imageFromName("NSActionTemplate"), tooltip="Edit configuration", fn=function() openConfig() end },
    { id="clearLog", label="Clear", image = hs.image.imageFromName("NSTrashEmpty"), tooltip="Clear Console", fn=function() console.clearConsole() end },
    { id="help", label="Help", image=image.imageFromName("NSInfo"), tooltip="Open API docs browser", fn=function() hs.doc.hsdocs.help() end }
  }):canCustomize(true):autosaves(true)
console.toolbar(console.defaultToolbar)

function openConfig()
  hs.open(hs.configdir .. "/init.lua")
end
```

**Comment by latenitefilms** [comment]
@cmsj - I wonder if we should add a clear button to the default toolbar?

**Comment by chigkim** [comment]
Clear button on the console toolbar That would be awesome!

**Comment by asmagill** [comment]
I do something like this in my `init.lua` which puts it at the end of the default items:

~~~lua
hs.console.toolbar():addItems(
    {
        id = "clearConsole",
        image   = hs.image.imageFromName("NSTrashFull"),
        fn      = function(...) hs.console.clearConsole() end,
        label   = "Clear",
        tooltip = "Clear Console",
    }
):insertItem("clearConsole", #hs.console.toolbar():visibleItems() + 1)

~~~

Change the image and position as you see fit.
