### ISSUE TITLE
Console glitch on Sierra

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#996]
On Sierra, if I type a command in the HS console and hit return, I see some output.  When I hit the up arrow to put the previous command back into the prompt, the little box holding the prompt shrinks to just a few pixels high.

I *think* the previous command is "there" waiting, but I just can't see anything, which pretty much destroys the usefulness of a command history in the HS console.

I don't see this on El Cap, as far as I can tell.

**Comment by asmagill** [comment]
Repeat of #976, addressed in pull #982.  Awaiting confirmation that it doesn't break behavior in 10.11 before merging to core.

**Comment by chdiza** [comment]
Sorry for the noise, didn't see that one.
