### ISSUE TITLE
Can't execute a file correct path given

### ISSUE THREAD

**Issue by nikitavoloboev** [Hammerspoon/hammerspoon#997]
I have a file located at this path : 

![2016-09-23 at 18 37](https://cloud.githubusercontent.com/assets/6391776/18793806/c58f10e2-81bc-11e6-8dd2-9438af234591.png)

I try and run this hammer spoon script to call it : 

```LUA
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "I", function()
hs.alert.show( ( hs.execute("~/Documents/d. app/bitbar/todo") ) )
end)
```

This too doesn't work : 

```LUA
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "I", function()
hs.alert.show( ( hs.execute("~/Documents/d.\ app/bitbar/todo") ) )
end)
```

Gives an error : 

![2016-09-23 at 18 48](https://cloud.githubusercontent.com/assets/6391776/18794117/540b9fd8-81be-11e6-9571-5ff64c235039.png)

What did I do wrong? It worked before. Maybe something wrong with the fact that I have folder named 'd.  app' in there but it should work though I believe.

Thank you for any help.

**Comment by latenitefilms** [comment]
I ran into this issue recently too, and wasn't able to work out how to fix it. Obviously Lua doesn't like the spaces in the file path, but I'm not sure of the correct syntax to fix.

Hopefully someone smarter than me will tell you how to fix, but in the meantime, here's a workaround using AppleScript:

```
ok,isFinalCutProInstalled = hs.osascript.applescript([[
	set isFinalCutProInstalled to "No"
	tell application "Finder" to if exists "/Applications/Final Cut Pro.app" as POSIX file then set isFinalCutProInstalled to "Yes"
	return isFinalCutProInstalled
]])     
print ("isFinalCutProInstalled: " .. tostring(isFinalCutProInstalled))
```

Hope this helps!

**Comment by junkblocker** [comment]
@nikitavoloboev , you need just one more ``\`` to escape the backslash. e.g.

```lua
hs.execute(os.getenv("HOME") .. '/Documents/d.\\ app/bitbar/todo')
```

**Comment by latenitefilms** [comment]
@junkblocker That's what I tried, but it didn't work - here's what the HS console says:

```
> print(hs.fs.touch('/Applications/Final\\ Cut\\ Pro.app'))
nil	No such file or directory
```

However '/Applications/Final Cut Pro.app' definitely DOES exist.

**Comment by nikitavoloboev** [comment]
@junkblocker thank you, this works

**Comment by junkblocker** [comment]
@latenitefilms , @nikitavoloboev is trying to pass things to shell in ``execute``. You are not. You are executing a Lua command directly (``hs.fs.touch``). So no ``\``s must be used.

```
hs.fs.touch('/Applications/Final Cut Pro.app')
```

should work.

**Comment by latenitefilms** [comment]
Thanks @junkblocker. I tried that, but I couldn't get it to work. I ASSUMED it was because of the spaces, but I just tried doing that code in the Console, and it ACTUALLY says:

```
> hs.fs.touch('/Applications/Final Cut Pro.app')
nil	Permission denied
```

So I've solve it with:

```
function doesDirectoryExist(path)
	local answer = false
	local result, resultb = hs.fs.touch(path)
	if resultb ~= "No such file or directory" then answer = true end
	return answer
end
```

Thanks so much for your help!!

**Comment by junkblocker** [comment]
You are welcome. There's a better way to check for directory:

```lua
function doesDirectoryExist(path)
    local attr = hs.fs.attributes(path)
    return attr and attr.mode == 'directory'
end
```

**Comment by latenitefilms** [comment]
Awesome! Thank you @junkblocker - that works great!
